apache/iotdb

- confignode/src/main/java/org/apache/iotdb/confignode/manager/pipe/runtime/PipeRuntimeCoordinator.java
- confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/pipe/task/CreatePipeProcedureV2.java
- reject metric db when creating pipe and leader change
> [IOTDB-5978] Pipe: ignore data in region "root.__system"

- integration-test/src/main/java/org/apache/iotdb/it/env/cluster/MppCommonConfig.java
- integration-test/src/test/java/org/apache/iotdb/util/AbstractSchemaIT.java
- server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
- server/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java
same as https://github.com/apache/iotdb/pull/10078
> Fix schema memory config initialization

- iotdb-client/client-py/iotdb/Session.py
- iotdb-client/client-py/iotdb/sqlalchemy/IoTDBSQLCompiler.py
> [To rel/1.2] Fix reconnect logic of python client

- confignode/src/main/java/org/apache/iotdb/confignode/manager/pipe/runtime/PipeRuntimeCoordinator.java
- confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/pipe/task/CreatePipeProcedureV2.java
- reject metric db when creating pipe and leader change
cherry pick from #10093
> [To rel/1.2][IOTDB-5978] Pipe: ignore data in region "root.__system"

- antlr/src/main/antlr4/org/apache/iotdb/db/qp/sql/IoTDBSqlParser.g4
- integration-test/src/test/java/org/apache/iotdb/db/it/schema/view/IoTDBCreateAndShowViewIT.java
- server/src/main/java/org/apache/iotdb/db/metadata/mnode/mem/info/LogicalViewInfo.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/executor/RegionWriteExecutor.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/parser/ASTVisitor.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/LogicalPlanVisitor.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/metedata/write/AlterTimeSeriesNode.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/statement/metadata/AlterTimeSeriesStatement.java
same as https://github.com/apache/iotdb/pull/10080
> Support tag/attribute on view

- server/src/main/java/org/apache/iotdb/db/exception/metadata/DuplicateInsertException.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/statement/crud/InsertBaseStatement.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/statement/crud/InsertMultiTabletsStatement.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/statement/crud/InsertRowsOfOneDeviceStatement.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/statement/crud/InsertRowsStatement.java
same as https://github.com/apache/iotdb/pull/10101
> [To rel/1.2] Fix duplicate insertion bug caused by view

- server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/AnalyzeVisitor.java
- site/src/main/.vuepress/sidebar/V1.0.x/en.ts
- site/src/main/.vuepress/sidebar/V1.0.x/zh.ts
- site/src/main/.vuepress/sidebar/V1.1.x/en.ts
- site/src/main/.vuepress/sidebar/V1.1.x/zh.ts
- site/src/main/.vuepress/sidebar/en.ts
- site/src/main/.vuepress/sidebar/zh.ts
(cherry picked from commit de700e5eaabbc452757f0d4d5912be330fcb2319)
> [To rel/1.2][IOTDB-5970] Fix the info of order by when sortkey doesn't exist

- confignode/src/main/java/org/apache/iotdb/confignode/consensus/response/pipe/task/PipeTableResp.java
(cherry picked from commit c51443748320d52aa3d8bbffabae503c36f615cb)
> [To rel/1.2][IOTDB-5986] Pipe: fix "show pipe p1" shows multiple pipes (#10111)

- confignode/src/main/java/org/apache/iotdb/confignode/manager/pipe/runtime/PipeRuntimeCoordinator.java
- confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/pipe/task/CreatePipeProcedureV2.java
- server/src/main/java/org/apache/iotdb/db/pipe/collector/historical/PipeHistoricalDataRegionTsFileCollector.java
(cherry picked from commit cdcd4c3be42135f507b7a8ef435fb03ec6c2a521)
> [To rel/1.2][IOTDB-5984] Pipe: remove unnecessary pipe task creation logic on schema region (#10108)

- server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/AnalyzeVisitor.java
```
IoTDB> create database root.db;
IoTDB> create database root.view;
IoTDB> create aligned timeseries root.db.d1(s01 INT32,s02 INT64);
IoTDB> create timeseries root.db.d2.s01 with datatype=INT32;
IoTDB> create timeseries root.db.d2.s02 with datatype=TEXT;
IoTDB> create view root.view.v1(col1,col2) as root.db.d1.s01,root.db.d2.s01 ;
IoTDB>
IoTDB> insert into root.db.d1(time,s01,s02)aligned values(100,200,300);
IoTDB> insert into root.db.d1(time,s01,s02)aligned …
```
> [To rel/1.2] Fix delete data from alias series

- node-commons/src/main/java/org/apache/iotdb/commons/auth/entity/PrivilegeType.java
- server/src/main/java/org/apache/iotdb/db/audit/AuditLogger.java
- server/src/main/java/org/apache/iotdb/db/auth/AuthorityChecker.java
same as https://github.com/apache/iotdb/pull/10119
> [To rel/1.2] Fix admin and audit log management on view

- node-commons/src/main/java/org/apache/iotdb/commons/auth/entity/PrivilegeType.java
- server/src/main/java/org/apache/iotdb/db/audit/AuditLogger.java
- server/src/main/java/org/apache/iotdb/db/auth/AuthorityChecker.java
Add statement types of view operation to AuthorizeChecker and AuditLogger to support administration and audit log management on view.
> Fix admin and audit log management on view

- server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/AnalyzeVisitor.java
same as https://github.com/apache/iotdb/pull/10117
> Fix delete data from alias series

- confignode/src/main/java/org/apache/iotdb/confignode/manager/pipe/task/PipeTaskCoordinator.java
- server/src/main/java/org/apache/iotdb/db/pipe/collector/IoTDBDataRegionCollector.java
- server/src/main/java/org/apache/iotdb/db/pipe/task/stage/PipeTaskCollectorStage.java
> [HOTFIX] Pipe: PipeTaskRuntimeConfiguration cannot be cast to PipeTaskCollectorRuntimeEnvironment && unreal message when dropping pipe 

- confignode/src/main/java/org/apache/iotdb/confignode/manager/pipe/task/PipeTaskCoordinator.java
- server/src/main/java/org/apache/iotdb/db/pipe/collector/IoTDBDataRegionCollector.java
- server/src/main/java/org/apache/iotdb/db/pipe/task/stage/PipeTaskCollectorStage.java
> [To rel/1.2][HOTFIX] Pipe: PipeTaskRuntimeConfiguration cannot be cast to PipeTaskCollectorRuntimeEnvironment && unreal message when dropping pipe 

- integration-test/src/test/java/org/apache/iotdb/db/it/schema/view/IoTDBAliasSeriesIT.java
- integration-test/src/test/java/org/apache/iotdb/db/it/schema/view/IoTDBCreateAndShowViewIT.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/AnalyzeVisitor.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/SelectIntoUtils.java
There's no source series fetch and check when selecting into alias series. 
Add related schema refetch and data type check.
> [To rel/1.2][IOTDB-5938] Fix select into alias series

- integration-test/src/test/java/org/apache/iotdb/db/it/schema/view/IoTDBAliasSeriesIT.java
- integration-test/src/test/java/org/apache/iotdb/db/it/schema/view/IoTDBCreateAndShowViewIT.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/AnalyzeVisitor.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/SelectIntoUtils.java
same as https://github.com/apache/iotdb/pull/10123
> [IOTDB-5938] Fix select into alias series

- confignode/src/main/java/org/apache/iotdb/confignode/persistence/executor/ConfigPlanExecutor.java
- integration-test/src/test/java/org/apache/iotdb/confignode/it/partition/IoTDBPartitionGetterIT.java
- node-commons/src/main/java/org/apache/iotdb/commons/path/PartialPath.java
- node-commons/src/main/java/org/apache/iotdb/commons/path/PathPatternUtil.java
same as https://github.com/apache/iotdb/pull/10139
> Avoid useless query in SchemaRegion when executing show child nodes

- integration-test/src/test/java/org/apache/iotdb/db/it/aligned/IoTDBInsertAlignedValuesIT.java
- server/src/main/java/org/apache/iotdb/db/metadata/cache/TimeSeriesSchemaCache.java
- server/src/main/java/org/apache/iotdb/db/metadata/mtree/MTreeBelowSGCachedImpl.java
- server/src/main/java/org/apache/iotdb/db/metadata/mtree/MTreeBelowSGMemoryImpl.java
- server/src/main/java/org/apache/iotdb/db/mpp/common/schematree/ClusterSchemaTree.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/schema/ISchemaValidation.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/schema/NormalSchemaFetcher.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/statement/crud/InsertRowStatement.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/statement/crud/InsertTabletStatement.java
same with https://github.com/apache/iotdb/pull/10141
> [To rel/1.2] Support not checking `isAligned` in insertion

- server/src/main/java/org/apache/iotdb/db/service/metrics/WritingMetrics.java
Fix the display issue of writing metrics that some items do not have data in some cases.
> Fix the display issue of writing metrics

- confignode/src/main/java/org/apache/iotdb/confignode/persistence/executor/ConfigPlanExecutor.java
- integration-test/src/test/java/org/apache/iotdb/confignode/it/partition/IoTDBPartitionGetterIT.java
- node-commons/src/main/java/org/apache/iotdb/commons/path/PartialPath.java
same as https://github.com/apache/iotdb/pull/10139
> [To rel/1.1] Avoid useless query in SchemaRegion when executing show child nodes

- server/src/main/java/org/apache/iotdb/db/engine/compaction/cross/rewrite/selector/AbstractCompactionEstimator.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/cross/rewrite/selector/RewriteCrossCompactionEstimator.java
Optimize the estimation method of cross compaction task. See the PR towards master https://github.com/apache/iotdb/pull/9795
> [To rel/0.13] Optimize the estimation method of cross compaction task

- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/distribution/SourceRewriter.java
same as https://github.com/apache/iotdb/pull/10157
> [To rel/1.1] Support show timeseries of system db in tail

- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/distribution/SourceRewriter.java
The timeseries of  ```root.__sytem``` is not users' primary concern, thus there's no need to be shown in the first place of show timeseries result set.
Improve the source rewriter process during distribution planning by planning to read the schema regions of ```root.__system``` at last.
> [To rel/1.2] Support show timeseries of system db in tail

- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/distribution/SourceRewriter.java
same as https://github.com/apache/iotdb/pull/10157
> Support show timeseries of system db in tail

- server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/AnalyzeVisitor.java
The schemaTree provided for show latest timeseries is not updated with view info. 
Add update operation.
> [To rel/1.2] Fix show latest alias series

- server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/AnalyzeVisitor.java
same as https://github.com/apache/iotdb/pull/10167
> Fix show latest alias series

- server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/source/ShowQueriesOperator.java
- server/src/main/java/org/apache/iotdb/db/utils/TimestampPrecisionUtils.java
cp https://github.com/apache/iotdb/pull/10145
> [To rel/1.1][IOTDB-5996] Fix time display of show queries

- server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/source/ShowQueriesOperator.java
- server/src/main/java/org/apache/iotdb/db/utils/TimestampPrecisionUtils.java
cp https://github.com/apache/iotdb/pull/10145
> [To rel/1.2][IOTDB-5996] Fix time display of show queries

- server/src/main/java/org/apache/iotdb/db/rescon/TsFileResourceManager.java
Change log level from info to debug when degrading time index of TsFile in memroy
> change log level from info to debug when degrading time index of TsFile in memroy

- server/src/main/java/org/apache/iotdb/db/rescon/TsFileResourceManager.java
change log level from info to debug when degrade tsfile resource (#10184)
> [To rel/1.2] change log level from info to debug when degrade tsfile resource (#10184)

- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/DataRegion.java
Fix concurrent modification exception when getting latest time partition
> [IOTDB-6002] Fix concurrent modification exception when getting latest time partition

- site/iotdb-doap.rdf
fix iotdb-doap.rdf issue.
<hr>
This PR has:
<hr>
> fix iotdb-doap.rdf

- integration-test/src/test/java/org/apache/iotdb/db/it/schema/IoTDBExtendTemplateIT.java
- integration-test/src/test/java/org/apache/iotdb/db/it/schema/IoTDBMetadataFetchIT.java
- integration-test/src/test/java/org/apache/iotdb/db/it/schema/view/IoTDBCreateAndShowViewIT.java
- integration-test/src/test/java/org/apache/iotdb/zeppelin/it/IoTDBInterpreterIT.java
- iotdb-client/client-py/tests/test_dataframe.py
- node-commons/src/main/java/org/apache/iotdb/commons/schema/filter/SchemaFilter.java
- node-commons/src/main/java/org/apache/iotdb/commons/schema/filter/SchemaFilterFactory.java
- node-commons/src/main/java/org/apache/iotdb/commons/schema/filter/SchemaFilterType.java
- node-commons/src/main/java/org/apache/iotdb/commons/schema/filter/SchemaFilterVisitor.java
- node-commons/src/main/java/org/apache/iotdb/commons/schema/filter/impl/AndFilter.java
- node-commons/src/main/java/org/apache/iotdb/commons/schema/filter/impl/DataTypeFilter.java
- node-commons/src/main/java/org/apache/iotdb/commons/schema/filter/impl/PathContainsFilter.java
- node-commons/src/main/java/org/apache/iotdb/commons/schema/filter/impl/ViewTypeFilter.java
- node-commons/src/main/java/org/apache/iotdb/commons/schema/view/ViewType.java
- server/src/main/java/org/apache/iotdb/db/metadata/plan/schemaregion/impl/read/SchemaRegionReadPlanFactory.java
- server/src/main/java/org/apache/iotdb/db/metadata/visitor/DeviceFilterVisitor.java
- server/src/main/java/org/apache/iotdb/db/metadata/visitor/TimeseriesFilterVisitor.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/schema/source/LogicalViewSchemaSource.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/schema/source/TimeSeriesSchemaSource.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/parser/ASTVisitor.java
- server/src/test/java/org/apache/iotdb/db/metadata/schemaRegion/SchemaRegionBasicTest.java
1. Rename ViewType values to VIEW/BASE
2. Eliminate LogicalViewSchemaReader, replace by ViewTypeSchemaFilter
> [To rel/1.2] Rename ViewType values to VIEW/BASE

- consensus/src/main/java/org/apache/iotdb/consensus/iot/logdispatcher/LogDispatcherThreadMetrics.java
cherry-pick [pr](https://github.com/apache/iotdb/pull/10194)
> [To rel/1.2][Metric] Fix missing IoTConsensus metric items

- server/src/main/java/org/apache/iotdb/db/pipe/connector/legacy/IoTDBSyncConnector.java
- server/src/main/java/org/apache/iotdb/db/pipe/connector/v1/IoTDBThriftConnectorV1.java
- server/src/main/java/org/apache/iotdb/db/pipe/connector/v1/request/PipeTransferTabletReq.java
- server/src/main/java/org/apache/iotdb/db/pipe/connector/v2/IoTDBThriftConnectorV2.java
- server/src/main/java/org/apache/iotdb/db/pipe/event/common/row/PipeRow.java
- server/src/main/java/org/apache/iotdb/db/pipe/event/common/row/PipeRowCollector.java
- server/src/main/java/org/apache/iotdb/db/pipe/event/common/tablet/PipeInsertNodeTabletInsertionEvent.java
- server/src/main/java/org/apache/iotdb/db/pipe/event/common/tablet/PipeRawTabletInsertionEvent.java
- server/src/main/java/org/apache/iotdb/db/pipe/event/common/tablet/TabletInsertionDataContainer.java
- server/src/main/java/org/apache/iotdb/db/pipe/event/common/tsfile/TsFileInsertionDataContainer.java
- server/src/main/java/org/apache/iotdb/db/pipe/event/realtime/PipeRealtimeCollectEventFactory.java
- server/src/test/java/org/apache/iotdb/db/pipe/event/PipeTabletInsertionEventTest.java
- server/src/test/java/org/apache/iotdb/db/pipe/event/TsFileInsertionDataContainerTest.java
(cherry picked from commit 25b70f8b884294ccccdd7710d5e39f382102ab4f)
> [To rel/1.2][IOTDB-5990][IOTDB-5991] Pipe: support transferring aligned tablets (#10137)

- integration-test/src/test/java/org/apache/iotdb/db/it/schema/view/IoTDBShowDevicesContainedViewIT.java
- node-commons/src/main/java/org/apache/iotdb/commons/path/MeasurementPath.java
- node-commons/src/main/java/org/apache/iotdb/commons/schema/node/common/AbstractDatabaseDeviceMNode.java
- node-commons/src/main/java/org/apache/iotdb/commons/schema/node/common/AbstractDeviceMNode.java
- node-commons/src/main/java/org/apache/iotdb/commons/schema/node/common/AbstractMeasurementMNode.java
- node-commons/src/main/java/org/apache/iotdb/commons/schema/node/info/IDeviceInfo.java
- node-commons/src/main/java/org/apache/iotdb/commons/schema/node/role/IDeviceMNode.java
- server/src/main/java/org/apache/iotdb/db/metadata/mnode/mem/info/DeviceInfo.java
- server/src/main/java/org/apache/iotdb/db/metadata/mtree/MTreeBelowSGCachedImpl.java
- server/src/main/java/org/apache/iotdb/db/metadata/mtree/MTreeBelowSGMemoryImpl.java
- server/src/main/java/org/apache/iotdb/db/metadata/mtree/snapshot/MemMTreeSnapshotUtil.java
- server/src/main/java/org/apache/iotdb/db/metadata/mtree/store/disk/schemafile/MockSchemaFile.java
- server/src/main/java/org/apache/iotdb/db/metadata/mtree/traverser/collector/MeasurementCollector.java
- server/src/main/java/org/apache/iotdb/db/metadata/plan/schemaregion/result/ShowDevicesResult.java
- server/src/main/java/org/apache/iotdb/db/metadata/query/info/IDeviceSchemaInfo.java
- tsfile/src/main/java/org/apache/iotdb/tsfile/utils/ReadWriteIOUtils.java
same as https://github.com/apache/iotdb/pull/10197
> [To rel/1.2] use Boolean for isAligned

- confignode/src/main/java/org/apache/iotdb/confignode/manager/partition/PartitionManager.java
- confignode/src/main/java/org/apache/iotdb/confignode/manager/schema/ClusterSchemaManager.java
- confignode/src/main/java/org/apache/iotdb/confignode/persistence/partition/PartitionInfo.java
The show slot APIs with parameter Device=devicePath should filter Database firstly.
> [IOTDB-5998] Fix device query bugs in show slot APIs

- metrics/interface/src/main/java/org/apache/iotdb/metrics/utils/IoTDBMetricsUtils.java
Fix potential QUOTE problem in IoTDB reporter
> [IOTDB-5971] Fix potential QUOTE problem in iotdb reporter

- confignode/src/main/java/org/apache/iotdb/confignode/manager/ProcedureManager.java
- confignode/src/main/java/org/apache/iotdb/confignode/manager/pipe/runtime/PipeHeartbeatParser.java
- confignode/src/main/java/org/apache/iotdb/confignode/manager/pipe/runtime/PipeLeaderChangeHandler.java
- confignode/src/main/java/org/apache/iotdb/confignode/manager/pipe/runtime/PipeMetaSyncer.java
- confignode/src/main/java/org/apache/iotdb/confignode/manager/pipe/runtime/PipeRuntimeCoordinator.java
- confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/pipe/AbstractOperatePipeProcedureV2.java
- confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/pipe/runtime/PipeHandleMetaChangeProcedure.java
- confignode/src/test/java/org/apache/iotdb/confignode/procedure/impl/pipe/runtime/PipeHandleMetaChangeProcedureTest.java
- node-commons/src/main/java/org/apache/iotdb/commons/concurrent/ThreadName.java
- server/src/main/java/org/apache/iotdb/db/pipe/resource/wal/PipeWALResourceManager.java
For more details, see:
[IOTDB-5931] The "show cluster" command displays nodes with "Unknown" status, but these nodes can still perform read and write operations normally (https://issues.apache.org/jira/browse/IOTDB-5931)
> [IOTDB-5931] Pipe: async execute pipeHandleLeaderChange and pipeHandleMetaChange to avoid causing heartbeats to timeout

- metrics/interface/src/main/java/org/apache/iotdb/metrics/utils/IoTDBMetricsUtils.java
cherry-pick [pull](https://github.com/apache/iotdb/pull/10125)
> [To rel/1.2][IOTDB-5971] Fix potential QUOTE problem in iotdb reporter

- integration-test/src/test/java/org/apache/iotdb/db/it/groupby/IoTDBGroupByConditionIT.java
- integration-test/src/test/java/org/apache/iotdb/db/it/groupby/IoTDBGroupByCountIT.java
- integration-test/src/test/java/org/apache/iotdb/db/it/groupby/IoTDBGroupByVariationIT.java
- integration-test/src/test/java/org/apache/iotdb/db/it/orderBy/IoTDBOrderByIT.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/AnalyzeVisitor.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/statement/crud/QueryStatement.java
(cherry picked from commit d33ca34985b386b0d6e69f9dc8f4de73793353a7)
> [To rel/1.2][IOTDB-5983] Refactor error info in GROUP BY/ORDER BY in align by device

- integration-test/src/test/java/org/apache/iotdb/db/it/schema/IoTDBExtendTemplateIT.java
- integration-test/src/test/java/org/apache/iotdb/db/it/schema/IoTDBMetadataFetchIT.java
- integration-test/src/test/java/org/apache/iotdb/db/it/schema/view/IoTDBCreateAndShowViewIT.java
- integration-test/src/test/java/org/apache/iotdb/zeppelin/it/IoTDBInterpreterIT.java
- iotdb-client/client-py/tests/test_dataframe.py
- node-commons/src/main/java/org/apache/iotdb/commons/schema/filter/SchemaFilter.java
- node-commons/src/main/java/org/apache/iotdb/commons/schema/filter/SchemaFilterFactory.java
- node-commons/src/main/java/org/apache/iotdb/commons/schema/filter/SchemaFilterType.java
- node-commons/src/main/java/org/apache/iotdb/commons/schema/filter/SchemaFilterVisitor.java
- node-commons/src/main/java/org/apache/iotdb/commons/schema/filter/impl/AndFilter.java
- node-commons/src/main/java/org/apache/iotdb/commons/schema/filter/impl/DataTypeFilter.java
- node-commons/src/main/java/org/apache/iotdb/commons/schema/filter/impl/PathContainsFilter.java
- node-commons/src/main/java/org/apache/iotdb/commons/schema/filter/impl/ViewTypeFilter.java
- node-commons/src/main/java/org/apache/iotdb/commons/schema/view/ViewType.java
- server/src/main/java/org/apache/iotdb/db/metadata/plan/schemaregion/impl/read/SchemaRegionReadPlanFactory.java
- server/src/main/java/org/apache/iotdb/db/metadata/visitor/DeviceFilterVisitor.java
- server/src/main/java/org/apache/iotdb/db/metadata/visitor/TimeseriesFilterVisitor.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/schema/source/LogicalViewSchemaSource.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/schema/source/TimeSeriesSchemaSource.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/parser/ASTVisitor.java
- server/src/test/java/org/apache/iotdb/db/metadata/schemaRegion/SchemaRegionBasicTest.java
1. Rename ViewType values to VIEW/BASE
2. Eliminate LogicalViewSchemaReader, replace by ViewTypeSchemaFilter
> Rename ViewType values to VIEW/BASE 

- integration-test/src/test/java/org/apache/iotdb/db/it/groupby/IoTDBGroupByConditionIT.java
- integration-test/src/test/java/org/apache/iotdb/db/it/groupby/IoTDBGroupByCountIT.java
- integration-test/src/test/java/org/apache/iotdb/db/it/groupby/IoTDBGroupByVariationIT.java
- integration-test/src/test/java/org/apache/iotdb/db/it/orderBy/IoTDBOrderByIT.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/AnalyzeVisitor.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/statement/crud/QueryStatement.java
> Revert "[To rel/1.2][IOTDB-5983] Refactor error info in GROUP BY/ORDER BY in align by device"

- confignode/src/main/java/org/apache/iotdb/confignode/manager/load/service/StatisticsService.java
**New format:**
`RegionGroupId: oldLeader -> newLeader`
> Add leader change log

- confignode/src/main/java/org/apache/iotdb/confignode/manager/load/service/StatisticsService.java
**New format:**
`RegionGroupId: oldLeader -> newLeader`
> [To rel/1.2] Add leader change log

- confignode/src/main/java/org/apache/iotdb/confignode/manager/pipe/runtime/PipeHeartbeatParser.java
- confignode/src/main/java/org/apache/iotdb/confignode/manager/pipe/runtime/PipeLeaderChangeHandler.java
- confignode/src/main/java/org/apache/iotdb/confignode/manager/pipe/runtime/PipeRuntimeCoordinator.java
- server/src/main/java/org/apache/iotdb/db/pipe/connector/v2/IoTDBThriftConnectorV2.java
See IOTDB-6013 for more detail.
> [To rel/1.2][IOTDB-6013] Pipe: pipe-related threads (pools) should not be initialized unless necessary

- server/src/main/java/org/apache/iotdb/db/exception/metadata/SeriesOverflowException.java
- server/src/main/java/org/apache/iotdb/db/metadata/rescon/ISchemaRegionStatistics.java
- server/src/main/java/org/apache/iotdb/db/metadata/rescon/MemSchemaRegionStatistics.java
- server/src/main/java/org/apache/iotdb/db/metadata/schemaregion/SchemaRegionMemoryImpl.java
- server/src/main/java/org/apache/iotdb/db/metadata/schemaregion/SchemaRegionPBTreeImpl.java
It is necessary to add memory usage and series num to log when series overflow for better maintenance.
> [To rel/1.2] Add memory usage and series num to log when series overflow

- server/src/main/java/org/apache/iotdb/db/exception/metadata/SeriesOverflowException.java
- server/src/main/java/org/apache/iotdb/db/metadata/rescon/ISchemaRegionStatistics.java
- server/src/main/java/org/apache/iotdb/db/metadata/rescon/MemSchemaRegionStatistics.java
- server/src/main/java/org/apache/iotdb/db/metadata/schemaregion/SchemaRegionMemoryImpl.java
- server/src/main/java/org/apache/iotdb/db/metadata/schemaregion/SchemaRegionPBTreeImpl.java
same as https://github.com/apache/iotdb/pull/10226
> Add memory usage and series num to log when series overflow

- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/load/LoadSingleTsFileNode.java
- When determining whether a tsfile should be loaded locally without splitting, you should also check that all the data in this tsfile is in the same dataregion and the same time division, without previously checking the latter
这个 PR 包含：
- 在确定 tsfile 是否应该不经过拆分直接加载到本地时，应该同时检查这个 tsfile 中的所有数据是否都在同一个 dataregion 和同一个时间分区内，而之前没有检查后者
如果未检查后者将导致如下错误
> [IOTDB-6015] Pipe: Not checking whether the tsfile data loaded locally is in the same time partition during the loading process

- server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/window/ConditionWindowManager.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/window/CountWindow.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/window/CountWindowManager.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/window/CountWindowParameter.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/window/IWindow.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/window/IWindowManager.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/window/SessionWindowManager.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/window/TimeWindowManager.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/window/WindowManagerFactory.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/window/WindowParameter.java
- server/src/main/java/org/apache/iotdb/db/tools/DiskSpiller.java
- server/src/main/java/org/apache/iotdb/db/tools/FileSpillerReader.java
- server/src/main/java/org/apache/iotdb/db/tools/SortBufferManager.java
- server/src/main/java/org/apache/iotdb/db/tools/SortReader.java
- server/src/main/java/org/apache/iotdb/db/utils/windowing/handler/SlidingTimeWindowEvaluationHandler.java
- server/src/main/java/org/apache/iotdb/db/utils/windowing/runtime/WindowEvaluationTaskPoolManager.java
- server/src/main/java/org/apache/iotdb/db/utils/windowing/window/EvictableBatchList.java
> Fix code smell in server

- consensus/src/main/java/org/apache/iotdb/consensus/config/IoTConsensusConfig.java
- consensus/src/main/java/org/apache/iotdb/consensus/iot/logdispatcher/LogDispatcher.java
- node-commons/src/assembly/resources/conf/iotdb-common.properties
- node-commons/src/main/java/org/apache/iotdb/commons/concurrent/ThreadName.java
see [issue](https://issues.apache.org/jira/browse/IOTDB-6022)
> [To rel/1.2][IOTDB-6022] Modify the default parameters of iotconsensus

- confignode/src/main/java/org/apache/iotdb/confignode/conf/SystemPropertiesUtils.java
- node-commons/src/main/java/org/apache/iotdb/commons/conf/CommonDescriptor.java
Forget to read parameter `time_partition_interval`
> [To rel/1.2] [IOTDB-5999] System properties patch

- docs/UserGuide/Operate-Metadata/Database.md
- docs/zh/UserGuide/Operate-Metadata/Database.md
Add document for heterogeneous Database function based on our former design.
> [To rel/1.2][IOTDB-6018] Heterogeneous Database document

- server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/AnalyzeVisitor.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/metedata/write/view/CreateLogicalViewNode.java
same as https://github.com/apache/iotdb/pull/10277
> Fix slow creation of view when using batch creation sql

- server/src/main/java/org/apache/iotdb/db/metadata/metric/ISchemaEngineMetric.java
- server/src/main/java/org/apache/iotdb/db/metadata/metric/ISchemaRegionMetric.java
- server/src/main/java/org/apache/iotdb/db/metadata/metric/SchemaEngineCachedMetric.java
- server/src/main/java/org/apache/iotdb/db/metadata/metric/SchemaEngineMemMetric.java
- server/src/main/java/org/apache/iotdb/db/metadata/metric/SchemaMetricManager.java
- server/src/main/java/org/apache/iotdb/db/metadata/metric/SchemaRegionCachedMetric.java
- server/src/main/java/org/apache/iotdb/db/metadata/metric/SchemaRegionMemMetric.java
- server/src/main/java/org/apache/iotdb/db/metadata/schemaregion/SchemaEngine.java
Fix sonar bugs and code smells in iotdb/db/metadata/metric
Before: 12 code smells
After: 1 code smell (TODO comment)
> Fix sonar bugs and code smells in iotdb/db/metadata/metric

- node-commons/src/main/java/org/apache/iotdb/commons/exception/runtime/SchemaExecutionException.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/schema/CountGroupByLevelMergeOperator.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/schema/CountGroupByLevelScanOperator.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/schema/CountMergeOperator.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/schema/NodeManageMemoryMergeOperator.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/schema/SchemaCountOperator.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/schema/SchemaFetchScanOperator.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/schema/SchemaQueryMergeOperator.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/schema/SchemaQueryScanOperator.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/schema/SchemaTsBlockUtil.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/schema/source/DeviceSchemaSource.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/schema/source/ISchemaSource.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/schema/source/LogicalViewSchemaSource.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/schema/source/NodeSchemaSource.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/schema/source/PathsUsingTemplateSource.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/schema/source/SchemaSourceFactory.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/schema/source/TimeSeriesSchemaSource.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/OperatorTreeGenerator.java
- server/src/test/java/org/apache/iotdb/db/mpp/execution/operator/OperatorMemoryTest.java
- server/src/test/java/org/apache/iotdb/db/mpp/execution/operator/schema/CountGroupByLevelMergeOperatorTest.java
Fix sonar bugs and code smells in mpp/execution/operator/schema
> Fix sonar bugs and code smells in mpp/execution/operator/schema

- server/src/main/java/org/apache/iotdb/db/engine/settle/SettleLog.java
- server/src/main/java/org/apache/iotdb/db/engine/settle/SettleRequestHandler.java
- server/src/main/java/org/apache/iotdb/db/engine/settle/SettleTask.java
Fix bugs and code smells in settle.
> Fix bugs and code smells in settle

- server/src/main/java/org/apache/iotdb/db/engine/memtable/AbstractMemTable.java
- server/src/main/java/org/apache/iotdb/db/engine/memtable/AlignedWritableMemChunk.java
- server/src/main/java/org/apache/iotdb/db/engine/memtable/AlignedWritableMemChunkGroup.java
- server/src/main/java/org/apache/iotdb/db/engine/memtable/WritableMemChunk.java
- server/src/main/java/org/apache/iotdb/db/engine/memtable/WritableMemChunkGroup.java
fix bugs and code smells of dir:engine/memtable
> fix bugs and code smells of dir:engine/memtable

- consensus/src/main/java/org/apache/iotdb/consensus/ratis/RatisConsensus.java
- consensus/src/main/java/org/apache/iotdb/consensus/ratis/RequestMessage.java
- consensus/src/main/java/org/apache/iotdb/consensus/ratis/ResponseMessage.java
- consensus/src/main/java/org/apache/iotdb/consensus/ratis/utils/Utils.java
cherry-pick of https://github.com/apache/iotdb/pull/10314
> [To rel/1.2][IOTDB-5995] Fix SonarLint bugs in consensus module

- iotdb-api/external-api/src/main/java/org/apache/iotdb/external/api/IPropertiesLoader.java
- iotdb-api/external-api/src/main/java/org/apache/iotdb/external/api/thrift/JudgableServerContext.java
- iotdb-api/external-api/src/main/java/org/apache/iotdb/external/api/thrift/ServerContextFactory.java
- iotdb-api/pipe-api/src/main/java/org/apache/iotdb/pipe/api/access/Row.java
- iotdb-api/pipe-api/src/main/java/org/apache/iotdb/pipe/api/event/dml/insertion/TabletInsertionEvent.java
- iotdb-api/pipe-api/src/main/java/org/apache/iotdb/pipe/api/event/dml/insertion/TsFileInsertionEvent.java
- iotdb-api/pipe-api/src/main/java/org/apache/iotdb/pipe/api/type/Binary.java
- iotdb-api/pipe-api/src/main/java/org/apache/iotdb/pipe/api/type/Type.java
- iotdb-api/subscription-api/src/main/java/org/apache/iotdb/subscription/api/SubscriptionConfiguration.java
- iotdb-api/subscription-api/src/main/java/org/apache/iotdb/subscription/api/consumer/Consumer.java
- iotdb-api/subscription-api/src/main/java/org/apache/iotdb/subscription/api/strategy/SubscriptionStrategy.java
- iotdb-api/subscription-api/src/main/java/org/apache/iotdb/subscription/api/strategy/disorder/IntolerableStrategy.java
- iotdb-api/trigger-api/src/main/java/org/apache/iotdb/trigger/api/Trigger.java
- iotdb-api/trigger-api/src/main/java/org/apache/iotdb/trigger/api/enums/FailureStrategy.java
- iotdb-api/udf-api/src/main/java/org/apache/iotdb/udf/api/UDF.java
- iotdb-api/udf-api/src/main/java/org/apache/iotdb/udf/api/UDTF.java
- iotdb-api/udf-api/src/main/java/org/apache/iotdb/udf/api/access/Row.java
- iotdb-api/udf-api/src/main/java/org/apache/iotdb/udf/api/customizer/config/UDTFConfigurations.java
- iotdb-api/udf-api/src/main/java/org/apache/iotdb/udf/api/customizer/parameter/UDFParameterValidator.java
- iotdb-api/udf-api/src/main/java/org/apache/iotdb/udf/api/customizer/strategy/AccessStrategy.java
- iotdb-api/udf-api/src/main/java/org/apache/iotdb/udf/api/customizer/strategy/MappableRowByRowAccessStrategy.java
- iotdb-api/udf-api/src/main/java/org/apache/iotdb/udf/api/customizer/strategy/RowByRowAccessStrategy.java
- iotdb-api/udf-api/src/main/java/org/apache/iotdb/udf/api/customizer/strategy/SessionTimeWindowAccessStrategy.java
- iotdb-api/udf-api/src/main/java/org/apache/iotdb/udf/api/customizer/strategy/SlidingSizeWindowAccessStrategy.java
- iotdb-api/udf-api/src/main/java/org/apache/iotdb/udf/api/customizer/strategy/SlidingTimeWindowAccessStrategy.java
- iotdb-api/udf-api/src/main/java/org/apache/iotdb/udf/api/customizer/strategy/StateWindowAccessStrategy.java
- iotdb-api/udf-api/src/main/java/org/apache/iotdb/udf/api/type/Binary.java
- iotdb-api/udf-api/src/main/java/org/apache/iotdb/udf/api/type/Type.java
> [IOTDB-6025] iotdb-api: fix bugs & smells reported by SonarCloud

- confignode/src/main/java/org/apache/iotdb/confignode/persistence/partition/PartitionInfo.java
> Revert "[IOTDB-6030] Improve efficiency of ConfigNode PartitionInfo takeSnapshot"

- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/consensus/request/read/function/GetFunctionTablePlan.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/consensus/request/read/trigger/GetTransferringTriggersPlan.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/consensus/request/read/trigger/GetTriggerJarPlan.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/consensus/request/read/trigger/GetTriggerLocationPlan.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/consensus/request/read/trigger/GetTriggerTablePlan.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/consensus/request/read/udf/GetUDFJarPlan.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/consensus/request/write/function/CreateFunctionPlan.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/consensus/request/write/function/DropFunctionPlan.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/consensus/request/write/trigger/AddTriggerInTablePlan.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/consensus/request/write/trigger/DeleteTriggerInTablePlan.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/consensus/request/write/trigger/UpdateTriggerLocationPlan.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/consensus/request/write/trigger/UpdateTriggerStateInTablePlan.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/consensus/request/write/trigger/UpdateTriggersOnTransferNodesPlan.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/consensus/response/function/FunctionTableResp.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/consensus/response/udf/JarResp.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/TriggerManager.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/UDFManager.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/pipe/plugin/PipePluginCoordinator.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/persistence/TriggerInfo.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/persistence/UDFInfo.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/trigger/CreateTriggerProcedure.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/trigger/DropTriggerProcedure.java
more fix info: https://timechor.feishu.cn/base/GGTHbJDf3aHgIus9smfcxVzcnvh?table=tblst8FFRi3b0jKC&view=vewxGjnobx
> Fix code smells of UDF and Trigger in ConfigNode

- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/iot/IoTConsensus.java
- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/simple/SimpleConsensus.java
In this pr , change the promt messages back to non-query
> Change back to non-query

- iotdb-core/tsfile/src/main/java/org/apache/iotdb/tsfile/encoding/encoder/BitmapEncoder.java
- iotdb-core/tsfile/src/main/java/org/apache/iotdb/tsfile/encoding/encoder/DeltaBinaryEncoder.java
- iotdb-core/tsfile/src/main/java/org/apache/iotdb/tsfile/encoding/encoder/DictionaryEncoder.java
- iotdb-core/tsfile/src/main/java/org/apache/iotdb/tsfile/encoding/encoder/DoubleRLBE.java
- iotdb-core/tsfile/src/main/java/org/apache/iotdb/tsfile/encoding/encoder/DoubleSprintzEncoder.java
- iotdb-core/tsfile/src/main/java/org/apache/iotdb/tsfile/encoding/encoder/FloatSprintzEncoder.java
- iotdb-core/tsfile/src/main/java/org/apache/iotdb/tsfile/encoding/encoder/GorillaEncoderV1.java
- iotdb-core/tsfile/src/main/java/org/apache/iotdb/tsfile/encoding/encoder/GorillaEncoderV2.java
- iotdb-core/tsfile/src/main/java/org/apache/iotdb/tsfile/encoding/encoder/IntChimpEncoder.java
- iotdb-core/tsfile/src/main/java/org/apache/iotdb/tsfile/encoding/encoder/IntGorillaEncoder.java
- iotdb-core/tsfile/src/main/java/org/apache/iotdb/tsfile/encoding/encoder/IntRLBE.java
- iotdb-core/tsfile/src/main/java/org/apache/iotdb/tsfile/encoding/encoder/IntRleEncoder.java
- iotdb-core/tsfile/src/main/java/org/apache/iotdb/tsfile/encoding/encoder/IntSprintzEncoder.java
- iotdb-core/tsfile/src/main/java/org/apache/iotdb/tsfile/encoding/encoder/IntZigzagEncoder.java
- iotdb-core/tsfile/src/main/java/org/apache/iotdb/tsfile/encoding/encoder/LongChimpEncoder.java
- iotdb-core/tsfile/src/main/java/org/apache/iotdb/tsfile/encoding/encoder/LongGorillaEncoder.java
- iotdb-core/tsfile/src/main/java/org/apache/iotdb/tsfile/encoding/encoder/LongRLBE.java
- iotdb-core/tsfile/src/main/java/org/apache/iotdb/tsfile/encoding/encoder/LongRleEncoder.java
- iotdb-core/tsfile/src/main/java/org/apache/iotdb/tsfile/encoding/encoder/LongSprintzEncoder.java
- iotdb-core/tsfile/src/main/java/org/apache/iotdb/tsfile/encoding/encoder/LongZigzagEncoder.java
- iotdb-core/tsfile/src/main/java/org/apache/iotdb/tsfile/encoding/encoder/PlainEncoder.java
- iotdb-core/tsfile/src/main/java/org/apache/iotdb/tsfile/encoding/encoder/RLBE.java
- iotdb-core/tsfile/src/main/java/org/apache/iotdb/tsfile/encoding/encoder/RegularDataEncoder.java
- iotdb-core/tsfile/src/main/java/org/apache/iotdb/tsfile/encoding/encoder/RleEncoder.java
- iotdb-core/tsfile/src/main/java/org/apache/iotdb/tsfile/encoding/encoder/SDTEncoder.java
- iotdb-core/tsfile/src/main/java/org/apache/iotdb/tsfile/encoding/encoder/SprintzEncoder.java
- iotdb-core/tsfile/src/main/java/org/apache/iotdb/tsfile/encoding/encoder/TSEncodingBuilder.java
Fix bugs and code smells detected by SonarLint in TsFile encoder
> Fix bugs and code smells detected by SonarLint in TsFile encoder

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/client/ConfigNodeClient.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/client/ConfigNodeClientManager.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/client/DataNodeInternalClient.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/mqtt/JSONPayloadFormatter.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/mqtt/MPPPublishHandler.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/mqtt/PayloadFormatManager.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/rest/filter/ApiOriginFilter.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/rest/filter/AuthorizationFilter.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/rest/v1/handler/QueryDataSetHandler.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/rest/v1/impl/GrafanaApiServiceImpl.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/rest/v1/impl/RestApiServiceImpl.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/rest/v2/handler/QueryDataSetHandler.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/rest/v2/impl/GrafanaApiServiceImpl.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/rest/v2/impl/RestApiServiceImpl.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/thrift/handler/InternalServiceThriftHandler.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/thrift/handler/MLNodeRPCServiceThriftHandler.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/thrift/impl/ClientRPCServiceImpl.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/thrift/impl/DataNodeInternalRPCServiceImpl.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/thrift/impl/DataNodeRegionManager.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/thrift/impl/MLNodeRPCServiceImpl.java
This pr aims to fix sonar bugs and code smells in protocol, including the following packages:
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/client/ConfigNodeClient.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/client/ConfigNodeClientManager.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/client/DataNodeInternalClient.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/mqtt/JSONPayloadFormatter.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/mqtt/MPPPublishHandler.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/mqtt/PayloadFormatManager.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/rest/filter/ApiOriginFilter.java …
> Fix sonar bugs and code smells in protocol 

- integration-test/src/test/java/org/apache/iotdb/db/it/schema/view/IoTDBAlterViewIT.java
- node-commons/src/main/java/org/apache/iotdb/commons/schema/filter/SchemaFilter.java
- node-commons/src/main/java/org/apache/iotdb/commons/schema/tree/AbstractTreeVisitor.java
- node-commons/src/main/java/org/apache/iotdb/commons/schema/tree/SchemaIterator.java
- server/src/main/java/org/apache/iotdb/db/metadata/query/reader/TimeseriesReaderWithViewFetch.java
- server/src/main/java/org/apache/iotdb/db/metadata/schemaregion/SchemaRegionMemoryImpl.java
- server/src/main/java/org/apache/iotdb/db/metadata/schemaregion/SchemaRegionPBTreeImpl.java
- server/src/main/java/org/apache/iotdb/db/metadata/tag/TagManager.java
- server/src/main/java/org/apache/iotdb/db/metadata/visitor/FilterContainsVisitor.java
- server/src/main/java/org/apache/iotdb/db/metadata/visitor/TimeseriesFilterVisitor.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/LogicalPlanVisitor.java
Support tag filter in view query. Example:
> [To rel/1.2] Support tag filter in view query

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/mtree/impl/mem/snapshot/MemMTreeSnapshotUtil.java
- iotdb-core/tsfile/src/main/java/org/apache/iotdb/tsfile/utils/ReadWriteIOUtils.java
same as https://github.com/apache/iotdb/pull/10322
> Fix view snapshot recover

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/statement/crud/QueryStatement.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/plan/statement/QueryStatementTest.java
**1）Fix the error result in raw query with having clause.**
Before:
After:
**2）Fix the error in align by device query with having clause**
Before:
After:
> Fix error sql when using `raw query` and `align by device` with having clause

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/wal/WALManager.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/wal/allocation/FirstCreateStrategy.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/wal/recover/WALNodeRecoverTask.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/wal/recover/WALRecoverManager.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/wal/utils/WALEntryHandler.java
> Fix sonar bugs in wal module

- iotdb-client/jdbc/src/main/java/org/apache/iotdb/jdbc/IoTDBDatabaseMetadata.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/thrift/impl/DataNodeInternalRPCServiceImpl.java
This pr aims to fix sonar bugs and code smells including the following packages:
jdbc:
org/apache/iotdb/jdbc/IoTDBDatabaseMetadata.java
datanode:
org/apache/iotdb/db/protocol/thrift/impl/DataNodeInternalRPCServiceImpl.java
> Fix sonar bugs in jdbc and datanode

- iotdb-client/jdbc/src/main/java/org/apache/iotdb/jdbc/IoTDBDatabaseMetadata.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/thrift/impl/DataNodeInternalRPCServiceImpl.java
This pr aims to fix sonar bugs and code smells in iotdb-client, including the following packages:
jdbc:
org/apache/iotdb/jdbc/IoTDBDatabaseMetadata.java
> Fix sonar bugs in iotdb-client module

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/SchemaEngine.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/SchemaRegionUtils.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/mtree/impl/mem/MTreeBelowSGMemoryImpl.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/mtree/impl/mem/mnode/container/MemMNodeContainer.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/mtree/impl/mem/snapshot/MemMTreeSnapshotUtil.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/mtree/impl/pbtree/CachedMTreeStore.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/mtree/impl/pbtree/MTreeBelowSGCachedImpl.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/mtree/impl/pbtree/cache/LRUCacheManager.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/mtree/impl/pbtree/cache/PlainCacheManager.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/mtree/impl/pbtree/mnode/container/CachedMNodeContainer.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/read/resp/reader/impl/SchemaReaderLimitOffsetWrapper.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/read/resp/reader/impl/TimeseriesReaderWithViewFetch.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/write/req/impl/view/CreateLogicalViewPlanImpl.java
Fix sonar bugs in SchemaEngine module.
> Fix sonar bugs in SchemaEngine module

- server/src/main/java/org/apache/iotdb/db/mpp/plan/statement/crud/QueryStatement.java
- server/src/test/java/org/apache/iotdb/db/mpp/plan/statement/QueryStatementTest.java
**1）Fix the error result in raw query with having clause.**
Before:
After:
**2）Fix the error in align by device query with having clause**
Before:
After:
> [To rel/1.1] Fix error sql when using raw query and align by device with having clause

- server/src/main/java/org/apache/iotdb/db/mpp/plan/statement/crud/QueryStatement.java
- server/src/test/java/org/apache/iotdb/db/mpp/plan/statement/QueryStatementTest.java
**1）Fix the error result in raw query with having clause.**
Before:
After:
**2）Fix the error in align by device query with having clause**
Before:
After:
> [To rel/1.2] Fix error sql when using raw query and align by device with having clause

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/statement/internal/InternalBatchActivateTemplateStatement.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/statement/internal/InternalCreateMultiTimeSeriesStatement.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/statement/internal/InternalCreateTimeSeriesStatement.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/tools/schema/PBTreeFileSketchTool.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/utils/SchemaUtils.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/tools/MLogParserTest.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/tools/PBTreeFileSketchTest.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/utils/SchemaUtilsTest.java
> Add UT and fix code smell for tools/schema and utils/schema

- iotdb-client/cli/src/main/java/org/apache/iotdb/tool/ExportCsv.java
- iotdb-client/cli/src/main/java/org/apache/iotdb/tool/ExportTsFile.java
- iotdb-client/cli/src/main/java/org/apache/iotdb/tool/ImportCsv.java
This pr aims to fix sonar bugs and code smells in iotdb-client, including the following packages:
cli:
org/apache/iotdb/tool/ExportCsv.java
org/apache/iotdb/tool/ExportTsFile.java
org/apache/iotdb/tool/ImportCsv.java
and remove try-with-resource with session instance(finally contains session.close())
> Fix sonar bugs and code smells in iotdb-cli(tool)

- server/src/main/java/org/apache/iotdb/db/mpp/plan/parser/ASTVisitor.java
Rename view is not going to be supported in v1.2.0
> [To rel/1.2] Forbid rename view

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/tools/settle/TsFileAndModSettleTool.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/tools/settle/TsFileSettleByCompactionTool.java
Fix some code smells and bugs in tools.settle module
> Fix some code smells and bugs in tools.settle module

- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/config/IoTConsensusConfig.java
- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/iot/logdispatcher/LogDispatcher.java
- iotdb-core/node-commons/src/assembly/resources/conf/iotdb-common.properties
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/concurrent/ThreadName.java
cherry-pick [pr](https://github.com/apache/iotdb/pull/10267)
> [IOTDB-6022] Modify the default parameters of iotconsensus

- node-commons/src/main/java/org/apache/iotdb/commons/concurrent/WrappedRunnable.java
- server/src/main/java/org/apache/iotdb/db/engine/load/LoadTsFileManager.java
- server/src/main/java/org/apache/iotdb/db/pipe/extractor/realtime/PipeRealtimeDataRegionHybridExtractor.java
- server/src/main/java/org/apache/iotdb/db/pipe/extractor/realtime/PipeRealtimeDataRegionLogExtractor.java
- server/src/main/java/org/apache/iotdb/db/pipe/extractor/realtime/PipeRealtimeDataRegionTsFileExtractor.java
- server/src/main/java/org/apache/iotdb/db/pipe/task/connection/BlockingPendingQueue.java
- server/src/main/java/org/apache/iotdb/db/pipe/task/stage/PipeTaskConnectorStage.java
- server/src/main/java/org/apache/iotdb/db/pipe/task/stage/PipeTaskProcessorStage.java
- server/src/main/java/org/apache/iotdb/db/pipe/task/subtask/PipeSubtask.java
- server/src/main/java/org/apache/iotdb/db/pipe/task/subtask/connector/PipeConnectorSubtask.java
- server/src/main/java/org/apache/iotdb/db/pipe/task/subtask/connector/PipeConnectorSubtaskLifeCycle.java
- server/src/main/java/org/apache/iotdb/db/pipe/task/subtask/connector/PipeConnectorSubtaskManager.java
- server/src/main/java/org/apache/iotdb/db/pipe/task/subtask/processor/PipeProcessorSubtask.java
- server/src/main/java/org/apache/iotdb/db/pipe/task/subtask/processor/PipeProcessorSubtaskWorker.java
- server/src/main/java/org/apache/iotdb/db/pipe/task/subtask/processor/PipeProcessorSubtaskWorkerManager.java
- server/src/test/java/org/apache/iotdb/db/pipe/execution/PipeConnectorSubtaskExecutorTest.java
- server/src/test/java/org/apache/iotdb/db/pipe/execution/PipeProcessorSubtaskExecutorTest.java
- server/src/test/java/org/apache/iotdb/db/pipe/execution/PipeSubtaskExecutorTest.java
This is a cherry-pick PR from #10368.
See #10368 for more details.
> [To rel/1.2][IOTDB-6039] Pipe: schedular for massive processor subtasks (#10368)

- iotdb-client/cli/src/main/java/org/apache/iotdb/tool/ExportCsv.java
Avoiding increased time consumption caused by duplicate creation
> fix(iotdb-client): ExportCsv StringBuilder -> String

- integration-test/src/test/java/org/apache/iotdb/db/it/schema/view/IoTDBAlterViewIT.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/LogicalPlanVisitor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/impl/SchemaRegionMemoryImpl.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/impl/SchemaRegionPBTreeImpl.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/read/resp/reader/impl/TimeseriesReaderWithViewFetch.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/tag/TagManager.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/utils/filter/FilterContainsVisitor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/utils/filter/TimeseriesFilterVisitor.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/schema/filter/SchemaFilter.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/schema/tree/AbstractTreeVisitor.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/schema/tree/SchemaIterator.java
cp #10357 
Support tag filter in view query. Example:
> Support tag filter in view query

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/fragment/QueryContext.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/DataRegion.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/recover/CompactionRecoverManager.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/modification/ModificationFile.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/modification/ModificationFileTest.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/conf/IoTDBConstant.java
refer doc https://apache-iotdb.feishu.cn/docx/BoGVdroUAozB0Cxkdh8chnKcneM
> [IoTDB-6036] add the mods file sorting function to solve the problem that the query of large mods files is slow or even OOM

- iotdb-api/pipe-api/src/main/java/org/apache/iotdb/pipe/api/exception/PipeAttributeNotProvidedException.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/pipe/runtime/PipeHeartbeatParser.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/pipe/runtime/PipeMetaSyncer.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/persistence/pipe/PipeTaskInfo.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/pipe/task/CreatePipeProcedureV2.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/agent/task/PipeTaskAgent.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/v1/IoTDBThriftConnectorV1.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/extractor/IoTDBDataRegionExtractor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/extractor/historical/PipeHistoricalDataRegionTsFileExtractor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/extractor/realtime/PipeRealtimeDataRegionExtractor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/task/PipeTaskBuilder.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/task/stage/PipeTaskConnectorStage.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/task/stage/PipeTaskExtractorStage.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/task/stage/PipeTaskStage.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/task/subtask/PipeSubtask.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/task/subtask/connector/PipeConnectorSubtask.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/task/subtask/connector/PipeConnectorSubtaskManager.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/thrift/impl/DataNodeInternalRPCServiceImpl.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/exception/pipe/PipeRuntimeException.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/plugin/builtin/connector/IoTDBThriftConnectorV1.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/plugin/builtin/connector/IoTDBThriftConnectorV2.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/task/meta/PipeStaticMeta.java
> Style fix: fix warnings, sonar bugs, smells, lower cases of first letter in pipe/rpcimpl module

- confignode/src/main/java/org/apache/iotdb/confignode/manager/cq/CQScheduleTask.java
- integration-test/src/main/java/org/apache/iotdb/it/env/cluster/MppCommonConfig.java
- integration-test/src/main/java/org/apache/iotdb/it/env/cluster/MppSharedCommonConfig.java
- integration-test/src/main/java/org/apache/iotdb/it/env/remote/RemoteCommonConfig.java
- integration-test/src/main/java/org/apache/iotdb/itbase/env/CommonConfig.java
- integration-test/src/test/java/org/apache/iotdb/db/it/cq/IoTDBCQExecInNsIT.java
- integration-test/src/test/java/org/apache/iotdb/db/it/cq/IoTDBCQExecInUsIT.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/statement/component/GroupByTimeComponent.java
- server/src/main/java/org/apache/iotdb/db/utils/DateTimeUtils.java
cherry picked from https://github.com/apache/iotdb/pull/10420
> [To rel/1.2] Fix CQ does not take effect in ns time_precision

- confignode/src/main/java/org/apache/iotdb/confignode/manager/cq/CQScheduleTask.java
- integration-test/src/main/java/org/apache/iotdb/it/env/cluster/MppCommonConfig.java
- integration-test/src/main/java/org/apache/iotdb/it/env/cluster/MppSharedCommonConfig.java
- integration-test/src/main/java/org/apache/iotdb/it/env/remote/RemoteCommonConfig.java
- integration-test/src/main/java/org/apache/iotdb/itbase/env/CommonConfig.java
- integration-test/src/test/java/org/apache/iotdb/db/it/cq/IoTDBCQExecInNsIT.java
- integration-test/src/test/java/org/apache/iotdb/db/it/cq/IoTDBCQExecInUsIT.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/statement/component/GroupByTimeComponent.java
- server/src/main/java/org/apache/iotdb/db/utils/DateTimeUtils.java
cherry picked from https://github.com/apache/iotdb/pull/10420
> [To rel/1.1] Fix CQ does not take effect in ns time_precision

- iotdb-core/metrics/interface/src/main/java/org/apache/iotdb/metrics/AbstractMetricManager.java
Fix npe exception when invalid in metric module
> Fix npe exception when invalid in metric module

- metrics/interface/src/main/java/org/apache/iotdb/metrics/AbstractMetricManager.java
Fix npe exception when invalid in metric module
> [To rel/1.2] Fix npe exception when invalid in metric module

- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/consensus/ConsensusManager.java
- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/config/ConsensusConfig.java
- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/ratis/RatisConsensus.java
- iotdb-core/consensus/src/test/java/org/apache/iotdb/consensus/iot/ReplicateTest.java
- iotdb-core/consensus/src/test/java/org/apache/iotdb/consensus/iot/StabilityTest.java
- iotdb-core/consensus/src/test/java/org/apache/iotdb/consensus/ratis/TestUtils.java
- iotdb-core/consensus/src/test/java/org/apache/iotdb/consensus/simple/RecoveryTest.java
- iotdb-core/consensus/src/test/java/org/apache/iotdb/consensus/simple/SimpleConsensusTest.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/consensus/DataRegionConsensusImpl.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/consensus/SchemaRegionConsensusImpl.java
Add ConsensusGroupType to ConsensusConfig ( for the sake of metrics )
> [IOTDB-6045] Add consensus type to consensus config

- integration-test/src/test/java/org/apache/iotdb/db/it/schema/IoTDBSchemaTemplateIT.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/schema/DeactivateTemplateProcedure.java
reproduce SQL
```sql
insert into root.db.d1.t1(timestamp,s1) values(now(),false);
create schema template t1;
set schema template t1 to root.db.d1.t2;
create timeseries using schema template on root.db.d1.t2;
deactivate schema template from root.db.d1.t2;
```
> Fix error when deactivating empty template

- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/DataRegion.java
See this PR for details https://github.com/apache/iotdb/pull/10432
> [IOTDB-5910][To rel/1.2] Fix compaction scheduler thread pool is not shutdown when aborting compaction

- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/ratis/RatisClient.java
- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/ratis/RatisConsensus.java
Use AutoClosable to refactor RatisClient related usages.
> [IOTDB-6048] Refactor RatisClient related code

- example/hadoop/src/main/java/org/apache/iotdb/hadoop/tsfile/TsFileHelper.java
- example/jdbc/src/main/java/org/apache/iotdb/JDBCExample.java
- example/rest-java-example/src/main/java/org/apache/iotdb/HttpExample.java
- example/rest-java-example/src/main/java/org/apache/iotdb/HttpsExample.java
- example/rest-java-example/src/main/java/org/apache/iotdb/SSLClient.java
- example/session/src/main/java/org/apache/iotdb/SessionConcurrentExample.java
- example/session/src/main/java/org/apache/iotdb/SessionPoolExample.java
- example/tsfile/src/main/java/org/apache/iotdb/tsfile/TsFileForceAppendWrite.java
- example/tsfile/src/main/java/org/apache/iotdb/tsfile/TsFileWriteWithTSRecord.java
- integration-test/src/main/java/org/apache/iotdb/it/env/EnvFactory.java
- iotdb-connector/spark-tsfile/src/main/java/org/apache/iotdb/spark/tsfile/io/TsFileRecordWriter.java
- iotdb-connector/spark-tsfile/src/main/java/org/apache/iotdb/spark/tsfile/qp/Executor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/SchemaEngine.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/service/SettleService.java
- iotdb-core/tsfile/src/test/java/org/apache/iotdb/tsfile/utils/FileGenerator.java
Our company code check tool find some code bad smells: printStackTrace, so I repair them want to contribute them.
https://issues.apache.org/jira/browse/IOTDB-6047
> [IOTDB-6047] replace printStackTrace with logger

- confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/schema/DeactivateTemplateProcedure.java
- integration-test/src/test/java/org/apache/iotdb/db/it/schema/IoTDBSchemaTemplateIT.java
> [To rel/1.2] Fix error when deactivating empty template

- integration-test/src/test/java/org/apache/iotdb/db/it/schema/view/IoTDBAlterViewIT.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/parser/ASTVisitor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/plan/node/metedata/write/AlterTimeSeriesNode.java
> Fix duplicate tag/attribute check and alias check when altering view

- integration-test/src/test/java/org/apache/iotdb/db/it/schema/view/IoTDBAliasSeriesIT.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/exception/metadata/PathNotExistException.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/common/schematree/ClusterSchemaTree.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/AnalyzeVisitor.java
> Make error message more accurate when failed to inserting alias timeseries

- integration-test/src/test/java/org/apache/iotdb/db/it/schema/view/IoTDBAliasSeriesIT.java
- server/src/main/java/org/apache/iotdb/db/exception/metadata/PathNotExistException.java
- server/src/main/java/org/apache/iotdb/db/mpp/common/schematree/ClusterSchemaTree.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/AnalyzeVisitor.java
> [To rel/1.2] Make error message more accurate when failed to inserting alias timeseries

- integration-test/src/test/java/org/apache/iotdb/db/it/udf/IoTDBUDTFHybridQueryIT.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/expression/multi/FunctionExpression.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/transformation/dag/udf/UDTFInformationInferrer.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/plan/plan/ExpressionTest.java
see: https://issues.apache.org/jira/browse/IOTDB-6049
> [IOTDB-6049] Fix the issue that nested UDF functions will throw memory not enough exception

- server/src/main/java/org/apache/iotdb/db/protocol/rest/v1/handler/QueryDataSetHandler.java
- server/src/main/java/org/apache/iotdb/db/protocol/rest/v2/handler/QueryDataSetHandler.java
[ISSUE-10109] Fixed data column and data correspondence mismatch returned by the rest API interface
https://github.com/apache/iotdb/issues/10109
> [To rel/1.2][ISSUE-10109] Fixed data column and data correspondence mismatch returned by the rest API interface

- server/src/main/java/org/apache/iotdb/db/protocol/rest/v1/handler/QueryDataSetHandler.java
- server/src/main/java/org/apache/iotdb/db/protocol/rest/v2/handler/QueryDataSetHandler.java
[ISSUE-10109] Fixed data column and data correspondence mismatch returned by the rest API interface
https://github.com/apache/iotdb/issues/10109
> [To rel/1.1][ISSUE-10109] Fixed data column and data correspondence mismatch returned by the rest API interface

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/parser/ASTVisitor.java
> Forbid rename view

- integration-test/src/test/java/org/apache/iotdb/db/it/udf/IoTDBUDTFHybridQueryIT.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/expression/multi/FunctionExpression.java
- server/src/main/java/org/apache/iotdb/db/mpp/transformation/dag/udf/UDTFInformationInferrer.java
- server/src/test/java/org/apache/iotdb/db/mpp/plan/plan/ExpressionTest.java
> [To rel/1.1][IOTDB-6049] Fix the issue that nested UDF functions will throw memory not enough exception

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/parser/ASTVisitor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/statement/metadata/AlterTimeSeriesStatement.java
> Fix authority check of altering view

- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/pipe/AbstractOperatePipeProcedureV2.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/pipe/plugin/CreatePipePluginProcedure.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/service/ConfigNode.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/parser/ASTVisitor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/service/DataNode.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/plugin/service/PipePluginExecutableManager.java
Now the pipe names and pipe plugin names with "`" will not be altered by "parseIdentifier" function.
Now the exception messages are directly linked with ".".
Fix sonar bugs and lower cases of the first letter.
Pipe plugin name without '`'
Pipe name with '`':
Pipe plugin name with '`':
Procedure exception message:
<hr>
This PR has:
<hr>
> [IOTDB-6054] Allow back quote to be recorded in pipe and pipe plugin name

- .github/workflows/client-python.yml
- iotdb-client/client-py/requirements.txt
- iotdb-client/client-py/requirements_dev.txt
This PR is making Python IT more stable by upgrading the testcontainer version.
> Make Python CI more stable

- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/iot/IoTConsensus.java
- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/iot/IoTConsensusServerImpl.java
- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/iot/logdispatcher/LogDispatcher.java
see [jira](https://issues.apache.org/jira/browse/IOTDB-6051)
> [IOTDB-6051] Fixed concurrency error in IoTConsensus UT when stopping cluster

- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/persistence/schema/mnode/container/ConfigMNodeContainer.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/StoppableThread.java
> [IOTDB-6031] Fix SonarCloud bugs in confignode module

- server/src/main/java/org/apache/iotdb/db/engine/load/TsFileSplitter.java
cherry-pick [pr](https://github.com/apache/iotdb/pull/10487)
> [To rel/1.1][IOTDB-6056] Pipe: Failed to load tsfile with empty pages (NPE occurs when loading)

- docs/UserGuide/QuickStart/Files.md
- docs/UserGuide/QuickStart/ServerFileList.md
- docs/zh/UserGuide/QuickStart/Files.md
- docs/zh/UserGuide/QuickStart/ServerFileList.md
fix user guide,update *.tsfile.mod to *.tsfile.mods
> fix user guide md of mods

- server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
- server/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java
cp from https://github.com/apache/iotdb/pull/10078
> [To rel/1.1] Fix schema memory config initialization

- consensus/src/main/java/org/apache/iotdb/consensus/iot/IoTConsensus.java
- consensus/src/main/java/org/apache/iotdb/consensus/iot/IoTConsensusServerImpl.java
- consensus/src/main/java/org/apache/iotdb/consensus/iot/logdispatcher/LogDispatcher.java
cherry-pick [pr](https://github.com/apache/iotdb/pull/10457)
> [To rel/1.1][IOTDB-6051] Fixed concurrency error in IoTConsensus UT when stopping cluster

- confignode/src/main/java/org/apache/iotdb/confignode/persistence/partition/PartitionInfo.java
cherry-pick [pr](https://github.com/apache/iotdb/pull/10336/files)
> [To rel/1.1][IOTDB-6030] Improve efficiency of ConfigNode PartitionInfo takeSnapshot

- metrics/interface/src/main/java/org/apache/iotdb/metrics/AbstractMetricManager.java
cherry pick [pr](https://github.com/apache/iotdb/pull/10444)
> [To rel/1.1] Fix npe exception when invalid in metric module

- server/src/main/java/org/apache/iotdb/db/engine/load/TsFileSplitter.java
cherry-pick [pr](https://github.com/apache/iotdb/pull/10487)
> [To rel/1.2][IOTDB-6056] Pipe: Failed to load tsfile with empty pages (NPE occurs when loading)

- confignode/src/main/java/org/apache/iotdb/confignode/persistence/executor/ConfigPlanExecutor.java
- confignode/src/main/java/org/apache/iotdb/confignode/persistence/partition/PartitionInfo.java
cherry-pick [pr](https://github.com/apache/iotdb/pull/10163)
> [To rel/1.1][IOTDB-5997] Improve efficiency of ConfigNode PartitionInfo loadSnapshot

- server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
- server/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java
> [To rel/1.1] Fix storage engine memory config initialization

- integration-test/src/test/java/org/apache/iotdb/db/it/schema/IoTDBMetadataFetchIT.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/schema/CountGroupByLevelScanOperator.java
Fix count timeseries group by level return NPE
> [IOTDB-5617] Fix count timeseries group by level return NPE

- integration-test/src/test/java/org/apache/iotdb/db/it/schema/IoTDBSchemaTemplateIT.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/schema/CountGroupByLevelMergeOperator.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/AnalyzeVisitor.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/LogicalPlanBuilder.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/LogicalPlanVisitor.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/OperatorTreeGenerator.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/metedata/read/LevelTimeSeriesCountNode.java
- server/src/test/java/org/apache/iotdb/db/mpp/plan/plan/node/metadata/read/SchemaCountNodeSerdeTest.java
> [To rel/1.1] Fix template related schema query

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/rest/v1/impl/GrafanaApiServiceImpl.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/rest/v1/impl/RestApiServiceImpl.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/rest/v2/impl/GrafanaApiServiceImpl.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/rest/v2/impl/RestApiServiceImpl.java
Fixed rest api query isn't closed
https://github.com/apache/iotdb/issues/10465
> [ISSUE-10465] Fixed rest api query isn't closed

- server/src/main/java/org/apache/iotdb/db/protocol/rest/v1/impl/GrafanaApiServiceImpl.java
- server/src/main/java/org/apache/iotdb/db/protocol/rest/v1/impl/RestApiServiceImpl.java
- server/src/main/java/org/apache/iotdb/db/protocol/rest/v2/impl/GrafanaApiServiceImpl.java
- server/src/main/java/org/apache/iotdb/db/protocol/rest/v2/impl/RestApiServiceImpl.java
[To rel/1.2][ISSUE-10465] Fixed rest api query isn't closed
https://github.com/apache/iotdb/issues/10465
> [To rel/1.2][ISSUE-10465] Fixed rest api query isn't closed

- server/src/main/java/org/apache/iotdb/db/protocol/rest/v1/impl/GrafanaApiServiceImpl.java
- server/src/main/java/org/apache/iotdb/db/protocol/rest/v1/impl/RestApiServiceImpl.java
- server/src/main/java/org/apache/iotdb/db/protocol/rest/v2/impl/GrafanaApiServiceImpl.java
- server/src/main/java/org/apache/iotdb/db/protocol/rest/v2/impl/RestApiServiceImpl.java
[To rel/1.1] Fixed rest api query isn't closed
https://github.com/apache/iotdb/issues/10465
> [To rel/1.1][ISSUE-10465] Fixed rest api query isn't closed

- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/DataRegion.java
cp https://github.com/apache/iotdb/pull/10434
> [IOTDB-5910][To rel/1.1] Fix compaction scheduler thread pool is not shutdown when aborting compaction

- integration-test/src/test/java/org/apache/iotdb/confignode/it/IoTDBClusterAuthorityIT.java
- integration-test/src/test/java/org/apache/iotdb/db/it/IoTDBAuthIT.java
- integration-test/src/test/java/org/apache/iotdb/db/it/cq/IoTDBCQIT.java
- integration-test/src/test/java/org/apache/iotdb/db/it/selectinto/IoTDBSelectIntoIT.java
- integration-test/src/test/java/org/apache/iotdb/db/it/trigger/IoTDBTriggerManagementIT.java
- iotdb-core/antlr/src/main/antlr4/org/apache/iotdb/db/qp/sql/IoTDBSqlParser.g4
- iotdb-core/antlr/src/main/antlr4/org/apache/iotdb/db/qp/sql/SqlLexer.g4
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/persistence/AuthorInfo.java
- iotdb-core/confignode/src/test/java/org/apache/iotdb/confignode/persistence/AuthorInfoTest.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/auth/AuthorityChecker.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/auth/ClusterAuthorityFetcher.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/auth/AuthorizerManagerTest.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/auth/authorizer/LocalFileAuthorizerTest.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/auth/entity/PrivilegeType.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/auth/role/BasicRoleManager.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/auth/user/BasicUserManager.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/utils/AuthUtils.java
1. Add READ and WRITE privilege
2. Add aggregate privilege: ALL = all privileges, READ = READ_DATA + READ_SCHEMA, WRITE = READ + WRITE_SCHEMA + WRITE_DATA, WRITE_SCHEMA contains READ_SCHEMA, WRITE_DATA contains READ_DATA
> [IOTDB-5134] Add READ and WRITE with aggregate privilege

- docs/UserGuide/Administration-Management/Administration.md
- docs/zh/UserGuide/Administration-Management/Administration.md
- docs/zh/UserGuide/Deployment-and-Maintenance/Security-Management.md
- docs/zh/UserGuide/SQL-Manual/SQL-Manual.md
- docs/zh/UserGuide/User-Manuel/Authority-Management.md
- integration-test/src/test/java/org/apache/iotdb/db/it/IoTDBAuthIT.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/auth/AuthorityChecker.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/auth/authorizer/LocalFileAuthorizerTest.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/auth/entity/PrivilegeType.java
fix READ_DATA, READ_SCHEMA, WRITE_DATA, WRITE_SCHEMA
> [IOTDB-5134] Fix Auth Module Contain

- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/partition/PartitionManager.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/partition/PartitionMetrics.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/persistence/partition/DatabasePartitionTable.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/persistence/partition/PartitionInfo.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/partition/DataPartitionTable.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/partition/SeriesPartitionTable.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/service/metric/enums/Metric.java
see [jira](https://issues.apache.org/jira/browse/IOTDB-6066)
> [IOTDB-6066] Add ConfigNode timeslot metric

- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/partition/PartitionManager.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/partition/PartitionMetrics.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/persistence/partition/DatabasePartitionTable.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/persistence/partition/PartitionInfo.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/partition/DataPartitionTable.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/service/metric/enums/Metric.java
cherry-pick [pr](https://github.com/apache/iotdb/pull/10546)
> [To rel/1.2][IOTDB-6066] Add ConfigNode timeslot metric

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/fragment/DataNodeQueryContext.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/fragment/FragmentInstanceContext.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/fragment/FragmentInstanceManager.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/process/last/AbstractUpdateLastCacheOperator.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/process/last/AlignedUpdateLastCacheOperator.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/process/last/AlignedUpdateViewPathLastCacheOperator.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/process/last/LastQueryUtil.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/process/last/UpdateLastCacheOperator.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/process/last/UpdateViewPathLastCacheOperator.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/cache/schema/lastcache/LastCacheContainer.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/LocalExecutionPlanContext.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/LocalExecutionPlanner.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/OperatorTreeGenerator.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/distribution/SimpleFragmentParallelPlanner.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/plan/FragmentInstance.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/plan/node/source/AlignedLastQueryScanNode.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/plan/node/source/LastQueryScanNode.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/plan/node/source/LastSeriesSourceNode.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/execution/operator/LastQueryOperatorTest.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/execution/operator/LastQuerySortOperatorTest.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/execution/operator/OperatorMemoryTest.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/execution/operator/UpdateLastCacheOperatorTest.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/plan/plan/PipelineBuilderTest.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/plan/plan/distribution/Util.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/transformation/builder/EvaluationDAGBuilderTest.java
doc: https://apache-iotdb.feishu.cn/docx/KZgmdKOWRozz7JxDtSGcEkT6nWg
before fix: 
after fix:
restart DataNodes and repeat two times
> [IOTDB-6019] Fix concurrent update of last query

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/load/AlignedChunkData.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/load/TsFileSplitter.java
- iotdb-core/tsfile/src/main/java/org/apache/iotdb/tsfile/file/header/PageHeader.java
- iotdb-core/tsfile/src/main/java/org/apache/iotdb/tsfile/write/chunk/ValueChunkWriter.java
cherry-pick https://github.com/apache/iotdb/pull/10556
> [To rel/1.2][IOTDB-6068] Pipe: Failed to load tsfile when the first page is empty in a chunk (#10556)

- server/src/main/java/org/apache/iotdb/db/engine/load/AlignedChunkData.java
- server/src/main/java/org/apache/iotdb/db/engine/load/TsFileSplitter.java
- tsfile/src/main/java/org/apache/iotdb/tsfile/file/header/PageHeader.java
- tsfile/src/main/java/org/apache/iotdb/tsfile/write/chunk/ValueChunkWriter.java
cherry-pick https://github.com/apache/iotdb/pull/10556
> [To rel/1.1][IOTDB-6068] Pipe: Failed to load tsfile with first page is empty in a chunk

- .github/workflows/sonar-coveralls.yml
Update the sonar project key. See https://issues.apache.org/jira/browse/INFRA-24794.
> Update sonar key in sonar-coveralls.yml

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/AnalyzeVisitor.java
> Fix the bug when delete view meets statement error

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/AnalyzeVisitor.java
> [To rel/1.2] Fix the bug when delete view meets statement error

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/AnalyzeVisitor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/schema/AutoCreateSchemaExecutor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/schema/ClusterSchemaFetchExecutor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/schema/ClusterSchemaFetcher.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/schema/ISchemaFetcher.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/schema/NormalSchemaFetcher.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/schema/SchemaValidator.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/schema/TemplateSchemaFetcher.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/execution/QueryExecution.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/plan/analyze/FakeSchemaFetcherImpl.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/plan/plan/distribution/Util.java
> [To rel/1.2] Use customer timeout in schema fetcher

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/fragment/DataNodeQueryContext.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/fragment/FragmentInstanceContext.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/fragment/FragmentInstanceManager.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/process/last/AbstractUpdateLastCacheOperator.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/process/last/AlignedUpdateLastCacheOperator.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/process/last/AlignedUpdateViewPathLastCacheOperator.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/process/last/LastQueryUtil.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/process/last/UpdateLastCacheOperator.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/process/last/UpdateViewPathLastCacheOperator.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/cache/schema/lastcache/LastCacheContainer.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/LocalExecutionPlanContext.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/LocalExecutionPlanner.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/OperatorTreeGenerator.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/distribution/SimpleFragmentParallelPlanner.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/plan/FragmentInstance.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/plan/node/source/AlignedLastQueryScanNode.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/plan/node/source/LastQueryScanNode.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/plan/node/source/LastSeriesSourceNode.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/execution/operator/LastQueryOperatorTest.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/execution/operator/LastQuerySortOperatorTest.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/execution/operator/OperatorMemoryTest.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/execution/operator/UpdateLastCacheOperatorTest.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/plan/plan/PipelineBuilderTest.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/plan/plan/distribution/Util.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/transformation/builder/EvaluationDAGBuilderTest.java
(cherry picked from commit 5a50f0df22ff8649a23a5139474cdede1736d95e)
> [To rel/1.2] [IOTDB-6019] Fix concurrent update of last query

- iotdb-core/datanode/src/assembly/resources/tools/tsfile/validate-overlap.bat
- iotdb-core/datanode/src/assembly/resources/tools/tsfile/validate-overlap.sh
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/tools/validate/TsFileOverlapValidationTool.java
> [To gps51_rel12] add temp tool TsFileOverlapValidationTool

- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/service/ConfigNodeCommandLine.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/DataRegion.java
add version and build info in starting configNode
> add version and build info in starting configNode

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/event/common/row/PipeRowCollector.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/event/common/tsfile/TsFileInsertionDataTabletIterator.java
- iotdb-core/node-commons/src/assembly/resources/conf/iotdb-common.properties
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/conf/CommonConfig.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/conf/CommonDescriptor.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/config/PipeConfig.java
same as https://github.com/apache/iotdb/pull/10554
> [To rel/1.2] Pipe: Add a configuration parameter to control the number of rows of the tablet used within the pipe module

- client-py/iotdb/SessionPool.py
- client-py/tests/test_session.py
- client-py/tests/test_session_pool.py
(cherry picked from commit 1ff823428714df32480aff79ff4d4eb1b8cdf410)
> [To rel/1.1][IOTDB-6069] Support SessionPool in client-py

- iotdb-client/client-py/iotdb/Session.py
- iotdb-client/client-py/iotdb/SessionPool.py
- iotdb-client/client-py/tests/test_session.py
- iotdb-client/client-py/tests/test_session_pool.py
(cherry picked from commit 1ff823428714df32480aff79ff4d4eb1b8cdf410)
> [To rel/1.2][IOTDB-6069] Support SessionPool in client-py

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/cache/schema/SchemaCacheEntry.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/cache/schema/dualkeycache/impl/DualKeyCacheImpl.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/cache/schema/lastcache/DataNodeLastCacheManager.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/cache/schema/lastcache/ILastCacheContainer.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/cache/schema/lastcache/LastCacheContainer.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/cache/schema/lastcache/value/ILastCacheValue.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/cache/schema/lastcache/value/LastCacheValue.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/metadata/cache/dualkeycache/DualKeyCacheTest.java
> [To rel/1.2][IOTDB-6065] Considering LastCacheContainer in the memory estimation of SchemaCacheEntry

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/thrift/impl/ClientRPCServiceImpl.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/fragment/FragmentInstanceContext.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/fragment/FragmentInstanceManager.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/utils/QueryDataSetUtils.java
- iotdb-core/tsfile/src/main/java/org/apache/iotdb/tsfile/read/filter/TimeFilter.java
- iotdb-core/tsfile/src/main/java/org/apache/iotdb/tsfile/read/filter/factory/FilterFactory.java
- iotdb-core/tsfile/src/main/java/org/apache/iotdb/tsfile/read/filter/factory/FilterSerializeId.java
- iotdb-protocol/thrift/src/main/thrift/client.thrift
Add a new rpc interface `executeGroupByQueryIntervalQuery `, this api is only used for benchants query.
> Add executeGroupByQueryIntervalQuery rpc interface

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/thrift/impl/ClientRPCServiceImpl.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/fragment/FragmentInstanceContext.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/fragment/FragmentInstanceManager.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/utils/QueryDataSetUtils.java
- iotdb-core/tsfile/src/main/java/org/apache/iotdb/tsfile/read/filter/TimeFilter.java
- iotdb-core/tsfile/src/main/java/org/apache/iotdb/tsfile/read/filter/factory/FilterFactory.java
- iotdb-core/tsfile/src/main/java/org/apache/iotdb/tsfile/read/filter/factory/FilterSerializeId.java
- iotdb-protocol/thrift/src/main/thrift/client.thrift
Add a new rpc interface `executeGroupByQueryIntervalQuery `, this api is only used for benchants query.
> [To rel/1.2] Add executeGroupByQueryIntervalQuery rpc interface

- confignode/src/main/java/org/apache/iotdb/confignode/manager/ConfigManager.java
- confignode/src/main/java/org/apache/iotdb/confignode/manager/schema/ClusterSchemaManager.java
- confignode/src/main/java/org/apache/iotdb/confignode/persistence/schema/ClusterSchemaInfo.java
- docs/UserGuide/Reference/Common-Config-Manual.md
- docs/zh/UserGuide/Reference/Common-Config-Manual.md
- integration-test/src/main/java/org/apache/iotdb/it/env/cluster/MppCommonConfig.java
- integration-test/src/main/java/org/apache/iotdb/it/env/cluster/MppSharedCommonConfig.java
- integration-test/src/main/java/org/apache/iotdb/it/env/remote/RemoteCommonConfig.java
- integration-test/src/main/java/org/apache/iotdb/itbase/env/CommonConfig.java
- integration-test/src/test/java/org/apache/iotdb/confignode/it/utils/ConfigNodeTestUtils.java
- integration-test/src/test/java/org/apache/iotdb/db/it/schema/IoTDBDatabaseQuotaIT.java
- node-commons/src/assembly/resources/conf/iotdb-common.properties
- node-commons/src/main/java/org/apache/iotdb/commons/conf/CommonConfig.java
- node-commons/src/main/java/org/apache/iotdb/commons/conf/CommonDescriptor.java
- server/src/main/java/org/apache/iotdb/db/exception/metadata/SchemaQuotaExceededException.java
- server/src/main/java/org/apache/iotdb/db/metadata/MetadataConstant.java
- thrift-confignode/src/main/thrift/confignode.thrift
> [To rel/1.1] Add database limit threshold configuration and check when creating new database

- docs/UserGuide/Reference/Common-Config-Manual.md
- docs/zh/UserGuide/Reference/Common-Config-Manual.md
- integration-test/src/main/java/org/apache/iotdb/it/env/cluster/MppCommonConfig.java
- integration-test/src/main/java/org/apache/iotdb/it/env/cluster/MppSharedCommonConfig.java
- integration-test/src/main/java/org/apache/iotdb/it/env/remote/RemoteCommonConfig.java
- integration-test/src/main/java/org/apache/iotdb/itbase/env/CommonConfig.java
- integration-test/src/test/java/org/apache/iotdb/confignode/it/utils/ConfigNodeTestUtils.java
- integration-test/src/test/java/org/apache/iotdb/db/it/schema/IoTDBDatabaseQuotaIT.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/ConfigManager.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/schema/ClusterSchemaManager.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/persistence/schema/ClusterSchemaInfo.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/exception/metadata/SchemaQuotaExceededException.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/SchemaConstant.java
- iotdb-core/node-commons/src/assembly/resources/conf/iotdb-common.properties
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/conf/CommonConfig.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/conf/CommonDescriptor.java
- iotdb-protocol/thrift-confignode/src/main/thrift/confignode.thrift
> [To rel/1.2] Add database limit threshold configuration and check when creating new database

- example/session/src/main/java/org/apache/iotdb/SessionExample.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/cache/schema/TimeSeriesSchemaCache.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/cache/schema/dualkeycache/IDualKeyCache.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/cache/schema/dualkeycache/IDualKeyCacheComputation.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/cache/schema/dualkeycache/IDualKeyCacheUpdating.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/cache/schema/dualkeycache/impl/DualKeyCacheImpl.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/cache/schema/lastcache/DataNodeLastCacheManager.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/cache/schema/lastcache/ILastCacheContainer.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/cache/schema/lastcache/LastCacheContainer.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/metadata/cache/dualkeycache/DualKeyCacheTest.java
Fix write performance degradation caused by the extra overhead of last cache
> Fix write performance degradation caused by the extra overhead of last cache

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/cache/schema/TimeSeriesSchemaCache.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/cache/schema/dualkeycache/IDualKeyCache.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/cache/schema/dualkeycache/IDualKeyCacheUpdating.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/cache/schema/dualkeycache/impl/DualKeyCacheImpl.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/cache/schema/lastcache/DataNodeLastCacheManager.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/cache/schema/lastcache/ILastCacheContainer.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/cache/schema/lastcache/LastCacheContainer.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/metadata/cache/dualkeycache/DualKeyCacheTest.java
> [To rel/1.2] Fix write performance degradation caused by the extra overhead of last cache

- integration-test/src/test/java/org/apache/iotdb/db/it/aligned/IoTDBAlignedLastQueryIT.java
- integration-test/src/test/java/org/apache/iotdb/db/it/last/IoTDBLastQueryLastCacheIT.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/OperatorTreeGenerator.java
cp https://github.com/apache/iotdb/pull/10612
> [To rel/1.2] Fix aligned last query

- iotdb-core/metrics/interface/src/main/java/org/apache/iotdb/metrics/reporter/prometheus/PrometheusTextWriter.java
(cherry picked from commit adea4bb3c3d15c5338e094ff64c639a378aa3698)
> [To rel/1.2] Fix default label when no tag

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/DataRegion.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/tsfile/TsFileResource.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/tsfile/timeindex/DeviceTimeIndex.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/tsfile/timeindex/FileTimeIndex.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/tsfile/timeindex/ITimeIndex.java
> [To rel/1.2] Optimize the speed of delete by pattern

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/task/subtask/PipeSubtask.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/task/subtask/connector/PipeConnectorSubtask.java
same as https://github.com/apache/iotdb/pull/10577
> [To rel/1.2] Pipe: record root cause when exception is reported

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/distribution/SimpleFragmentParallelPlanner.java
same as https://github.com/apache/iotdb/pull/10579
> [To rel/1.2][IOTDB-6071] Fix internal server error when execute "show query processlist" statement

- iotdb-client/session/src/main/java/org/apache/iotdb/session/Session.java
- iotdb-client/session/src/main/java/org/apache/iotdb/session/pool/SessionPool.java
cp https://github.com/apache/iotdb/pull/10634
> [To rel/1.2] Keep special case consistent between LastDataQueryForOneDevice and others

- integration-test/src/test/java/org/apache/iotdb/db/it/schema/IoTDBTagAlterIT.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/impl/SchemaRegionMemoryImpl.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/impl/SchemaRegionPBTreeImpl.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/mtree/impl/mem/MTreeBelowSGMemoryImpl.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/mtree/impl/pbtree/MTreeBelowSGCachedImpl.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/metadata/schemaRegion/SchemaRegionAliasAndTagTest.java
> [IOTDB-6076] Add duplicate checking when upsert alias

- iotdb-core/antlr/src/main/antlr4/org/apache/iotdb/db/qp/sql/IdentifierParser.g4
Add READ and WRITE into keyword
> Add READ and WRITE into keyword

- server/src/main/java/org/apache/iotdb/db/mpp/exception/exchange/GetTsBlockFromClosedOrAbortedChannelException.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/exchange/MPPDataExchangeManager.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/exchange/sink/SinkChannel.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/exchange/source/SourceHandle.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/scheduler/FixedRateFragInsStateTracker.java
> [To rel/1.1] Fix the issue that Drivers of query with limit clause can not be finished timely

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/exception/exchange/GetTsBlockFromClosedOrAbortedChannelException.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/exchange/MPPDataExchangeManager.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/exchange/sink/SinkChannel.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/exchange/source/SourceHandle.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/scheduler/FixedRateFragInsStateTracker.java
> [To rel/1.2] Fix the issue that Drivers of query with limit clause can not be finished timely

- iotdb-client/client-py/SessionPoolExample.py
- iotdb-client/client-py/iotdb/SessionPool.py
- iotdb-client/client-py/tests/test_session_pool.py
add test for init_from_node_urls()
> [IOTDB-6069] Add more checks for session pool in client-py

- docs/UserGuide/Monitor-Alert/Metric-Tool.md
- docs/zh/UserGuide/Monitor-Alert/Metric-Tool.md
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/service/ConfigNode.java
- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/iot/client/IoTConsensusClientPool.java
- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/ratis/RatisConsensus.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/client/DataNodeClientPoolFactory.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/service/metrics/DataNodeMetricsHelper.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/client/ClientManagerMetrics.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/client/ClientPoolFactory.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/service/metric/enums/Metric.java
cherry-pick [pr](https://github.com/apache/iotdb/pull/10617)
> [To rel/1.2][IOTDB-6073] Add ClientManager metrics

- iotdb-core/confignode/src/assembly/resources/sbin/stop-confignode.sh
- iotdb-core/datanode/src/assembly/resources/sbin/stop-datanode.sh
- iotdb-core/node-commons/src/assembly/resources/sbin/stop-standalone.sh
support ./sbin/stop-confignode.sh -f
support ./sbin/stop-datanode.sh -f
support ./sbin/stop-standalone.sh -f
> [To rel/1.2][IOTDB-6077]: Stop script addition -f

- iotdb-client/client-py/SessionPoolExample.py
- iotdb-client/client-py/iotdb/SessionPool.py
- iotdb-client/client-py/tests/test_session_pool.py
(cherry picked from commit a268bcfd9bb2df69dac0043f42b3e2bd1abe5b65)
> [To rel/1.2][IOTDB-6069] Add more checks for session pool in client-py

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/mtree/impl/pbtree/schemafile/WrappedSegment.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/metadata/mtree/schemafile/WrappedSegmentTest.java
> [To rel/1.2]Fix error update alias in PB_Tree WrappedSegment 

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/mtree/impl/mem/snapshot/MemMTreeSnapshotUtil.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/tag/TagManager.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/utils/FileUtils.java
> [To rel/1.2][IOTDB-6074] Ignore error message when TagManager createSnapshot

- node-commons/src/main/java/org/apache/iotdb/commons/utils/FileUtils.java
- server/src/main/java/org/apache/iotdb/db/metadata/mtree/snapshot/MemMTreeSnapshotUtil.java
- server/src/main/java/org/apache/iotdb/db/metadata/tag/TagManager.java
> [To rel/1.1][IOTDB-6074] Ignore error message when TagManager createSnapshot

- integration-test/src/test/java/org/apache/iotdb/db/it/schema/IoTDBTagAlterIT.java
- server/src/main/java/org/apache/iotdb/db/metadata/mtree/MTreeBelowSGCachedImpl.java
- server/src/main/java/org/apache/iotdb/db/metadata/mtree/MTreeBelowSGMemoryImpl.java
- server/src/main/java/org/apache/iotdb/db/metadata/schemaregion/SchemaRegionMemoryImpl.java
- server/src/main/java/org/apache/iotdb/db/metadata/schemaregion/SchemaRegionSchemaFileImpl.java
- server/src/test/java/org/apache/iotdb/db/metadata/schemaRegion/SchemaRegionAliasAndTagTest.java
> [To rel/1.1][IOTDB-6076] Add duplicate checking when upsert alias 

- server/src/main/java/org/apache/iotdb/db/metadata/mtree/store/disk/schemafile/WrappedSegment.java
- server/src/test/java/org/apache/iotdb/db/metadata/mtree/schemafile/WrappedSegmentTest.java
> [To rel/1.1]Fix error update alias in SchemaFile WrappedSegment 

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/client/ConfigNodeClient.java
resolve this issue: https://github.com/apache/iotdb/issues/10676
doc: https://apache-iotdb.feishu.cn/docx/Gd1SdLZaIoYBsSxJ1MTc6AN5niZ
> Fixes #10676: Refactoring and warning messages improvement for ConfigNodeClient

- iotdb-core/consensus/src/test/java/org/apache/iotdb/consensus/ratis/RecoverReadTest.java
- iotdb-core/consensus/src/test/java/org/apache/iotdb/consensus/ratis/TestUtils.java
cherry-pick of https://github.com/apache/iotdb/pull/10674
> [To rel/1.2] Fix flaky test in RatisConsensus RecoverTest 

- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/service/ConfigNode.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/thrift/impl/DataNodeInternalRPCServiceImpl.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/service/metrics/DataNodeMetricsHelper.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/service/metrics/ProcessMetrics.java
- iotdb-core/metrics/interface/src/main/java/org/apache/iotdb/metrics/metricsets/UpTimeMetrics.java
- iotdb-core/metrics/interface/src/main/java/org/apache/iotdb/metrics/metricsets/cpu/CpuUsageMetrics.java
- iotdb-core/metrics/interface/src/main/java/org/apache/iotdb/metrics/metricsets/disk/DiskMetrics.java
- iotdb-core/metrics/interface/src/main/java/org/apache/iotdb/metrics/metricsets/jvm/JvmClassLoaderMetrics.java
- iotdb-core/metrics/interface/src/main/java/org/apache/iotdb/metrics/metricsets/jvm/JvmCompileMetrics.java
- iotdb-core/metrics/interface/src/main/java/org/apache/iotdb/metrics/metricsets/jvm/JvmGcMetrics.java
- iotdb-core/metrics/interface/src/main/java/org/apache/iotdb/metrics/metricsets/jvm/JvmMemoryMetrics.java
- iotdb-core/metrics/interface/src/main/java/org/apache/iotdb/metrics/metricsets/jvm/JvmThreadMetrics.java
- iotdb-core/metrics/interface/src/main/java/org/apache/iotdb/metrics/metricsets/logback/LogbackMetrics.java
- iotdb-core/metrics/interface/src/main/java/org/apache/iotdb/metrics/metricsets/net/NetMetrics.java
- iotdb-core/metrics/interface/src/main/java/org/apache/iotdb/metrics/metricsets/system/SystemMetrics.java
- iotdb-core/metrics/interface/src/main/java/org/apache/iotdb/metrics/utils/SystemMetric.java
- iotdb-core/metrics/interface/src/main/java/org/apache/iotdb/metrics/utils/SystemTag.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/concurrent/ThreadPoolMetrics.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/service/metric/enums/Metric.java
cherry-pick [pr](https://github.com/apache/iotdb/pull/10667)
> [To rel/1.2][IOTDB-6082] Improve disk space metrics

- server/src/main/java/org/apache/iotdb/db/mpp/execution/exchange/sink/SinkChannel.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/memory/MemoryPool.java
Similar to https://github.com/apache/iotdb/pull/10687
> [To rel/1.1] Fix potential memory leak in MemoryPool

- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/service/ConfigNodeCommandLine.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/DataRegion.java
cherry-pick of https://github.com/apache/iotdb/pull/10569
> [To rel/1.2] add version and build info in start confignode (#10569)

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/exchange/MPPDataExchangeManager.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/exchange/sink/SinkChannel.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/memory/MemoryPool.java
> [To rel/1.2] Fix potential memory leak in MemoryPool

- .github/workflows/client-cpp.yml
- .github/workflows/client-python.yml
- docker/src/main/Dockerfile-1c1d
- iotdb-client/client-py/iotdb/IoTDBContainer.py
Fix python IT by adding the check of cluster status.
Add a `show cluster` logic before start the docker.
> Fix python IT by adding the check of cluster status

- .github/workflows/client-cpp.yml
Fix the issue caused by #10698.
> fix windows cpp IT

- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/consensus/request/ConfigPhysicalPlan.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/consensus/request/ConfigPhysicalPlanType.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/consensus/request/write/confignode/UpdateBuildInfoPlan.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/ConfigManager.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/ProcedureManager.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/node/NodeManager.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/persistence/executor/ConfigPlanExecutor.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/persistence/node/NodeInfo.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/env/ConfigNodeProcedureEnv.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/node/AddConfigNodeProcedure.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/service/ConfigNode.java
- iotdb-core/confignode/src/test/java/org/apache/iotdb/confignode/procedure/impl/node/AddConfigNodeProcedureTest.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/common/header/ColumnHeaderConstant.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/execution/config/metadata/ShowClusterTask.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/service/DataNode.java
- iotdb-protocol/thrift-confignode/src/main/thrift/confignode.thrift
cp from https://github.com/apache/iotdb/pull/10595
> [To rel/1.2] add build info in show cluster (#10595)

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/utils/executor/fast/SeriesCompactionExecutor.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/compaction/FastCompactionPerformerWithInconsistentCompressionTypeAndEncodingTest.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/compaction/utils/CompactionTestFileWriter.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/compaction/utils/CompactionTestFileWriterTest.java
1. fix fake overlap case
2. add tests
> Fast performer force decoding

- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/ratis/ApplicationStateMachineProxy.java
- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/ratis/RatisConsensus.java
> [To rel/1.2][RatisConsensus] Support linearizable read when leader switches

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/buffer/TimeSeriesMetadataCache.java
- iotdb-core/tsfile/src/main/java/org/apache/iotdb/tsfile/read/TsFileSequenceReader.java
- iotdb-core/tsfile/src/test/java/org/apache/iotdb/tsfile/read/TimeSeriesMetadataReadTest.java
(cherry picked from commit f38f3f6a0eb1f3d5e0ffe6d82823d3da73e7629a)
> [To rel/1.2] Remove redundant new Path in query process

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/rest/utils/InsertTabletSortDataUtils.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/rest/v1/impl/RestApiServiceImpl.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/rest/v2/impl/RestApiServiceImpl.java
Add sorting based on timestamps to the insertTable method in the rest API v1/v2
> Add sorting based on timestamps to the insertTable method in the rest API v1/v2

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/rest/utils/InsertTabletSortDataUtils.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/rest/v1/impl/RestApiServiceImpl.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/rest/v2/impl/RestApiServiceImpl.java
[To rel/1.2]Add sorting based on timestamps to the insertTable method in the rest API v1/v2
> [To rel/1.2] Add sorting based on timestamps to the insertTable method in the rest API v1/v2

- server/src/main/java/org/apache/iotdb/db/protocol/rest/utils/InsertTabletSortDataUtils.java
- server/src/main/java/org/apache/iotdb/db/protocol/rest/v1/impl/RestApiServiceImpl.java
- server/src/main/java/org/apache/iotdb/db/protocol/rest/v2/impl/RestApiServiceImpl.java
[To rel/1.1]Add sorting based on timestamps to the insertTable method in the rest API v1/v2
> [To rel/1.1]Add sorting based on timestamps to the insertTable method in the rest API v1/v2

- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/service/ConfigNode.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/service/metrics/DataNodeMetricsHelper.java
- iotdb-core/metrics/interface/src/main/java/org/apache/iotdb/metrics/metricsets/jvm/JvmGcMetrics.java
- iotdb-core/metrics/interface/src/main/java/org/apache/iotdb/metrics/utils/SystemMetric.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/concurrent/ThreadName.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/service/metric/GcTimeAlerter.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/service/metric/JvmGcMonitorMetrics.java
> [To rel/1.2] Fixing partially concurrent GC's duration statistics and adding a new GC monitor

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/client/ConfigNodeClient.java
cherry-pick https://github.com/apache/iotdb/pull/10721
> [To rel/1.2] Enhance warning messages for ConfigNodeClient 

- iotdb-client/session/pom.xml
- iotdb-client/session/src/test/java/org/apache/iotdb/session/pool/SessionPoolTest.java
> add session UT

- server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/task/InnerSpaceCompactionTask.java
Skip compaction resources overlap validation if a task is UnSequenceSpaceTask
> [To rel/1.1] Skip compaction resources overlap validation if a task is UnSequenceSpaceTask

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
- iotdb-core/datanode/src/test/resources/datanode1conf/iotdb-datanode.properties
- iotdb-core/datanode/src/test/resources/datanode2conf/iotdb-datanode.properties
- iotdb-core/datanode/src/test/resources/datanode3conf/iotdb-datanode.properties
- iotdb-core/metrics/interface/src/main/java/org/apache/iotdb/metrics/metricsets/system/SystemMetrics.java
1. add sort_tmp_dir in `formulateFolders()`
2. add sort_tmp_dir in `iotdb-datanode.properties`
> Formulate folders for sort_tmp_dir

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
- iotdb-core/datanode/src/test/resources/datanode1conf/iotdb-datanode.properties
- iotdb-core/datanode/src/test/resources/datanode2conf/iotdb-datanode.properties
- iotdb-core/datanode/src/test/resources/datanode3conf/iotdb-datanode.properties
- iotdb-core/metrics/interface/src/main/java/org/apache/iotdb/metrics/metricsets/system/SystemMetrics.java
cherry-pick [pr](https://github.com/apache/iotdb/pull/10725)
> [To rel/1.2] Formulate folders for sort_tmp_dir

- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/consensus/request/ConfigPhysicalPlan.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/consensus/request/ConfigPhysicalPlanType.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/consensus/request/write/confignode/UpdateVersionInfoPlan.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/ConfigManager.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/ProcedureManager.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/node/NodeManager.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/persistence/executor/ConfigPlanExecutor.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/persistence/node/NodeInfo.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/env/ConfigNodeProcedureEnv.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/node/AddConfigNodeProcedure.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/service/ConfigNode.java
- iotdb-core/confignode/src/test/java/org/apache/iotdb/confignode/procedure/impl/node/AddConfigNodeProcedureTest.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/common/header/ColumnHeaderConstant.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/execution/config/metadata/ShowClusterDetailsTask.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/execution/config/metadata/ShowClusterTask.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/service/DataNode.java
- iotdb-protocol/thrift-confignode/src/main/thrift/confignode.thrift
> Enhance versionInfo in show cluster and show cluster detail

- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/consensus/request/ConfigPhysicalPlan.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/consensus/request/ConfigPhysicalPlanType.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/consensus/request/write/confignode/UpdateVersionInfoPlan.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/ConfigManager.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/ProcedureManager.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/node/NodeManager.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/persistence/executor/ConfigPlanExecutor.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/persistence/node/NodeInfo.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/env/ConfigNodeProcedureEnv.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/node/AddConfigNodeProcedure.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/service/ConfigNode.java
- iotdb-core/confignode/src/test/java/org/apache/iotdb/confignode/procedure/impl/node/AddConfigNodeProcedureTest.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/common/header/ColumnHeaderConstant.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/execution/config/metadata/ShowClusterDetailsTask.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/execution/config/metadata/ShowClusterTask.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/service/DataNode.java
- iotdb-protocol/thrift-confignode/src/main/thrift/confignode.thrift
cherry-pick [pull](https://github.com/apache/iotdb/pull/10743)
> [To rel/1.2]Enhance versionInfo in show cluster and show cluster detail

- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/load/LoadManager.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/load/balancer/partition/DataPartitionPolicyTable.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/node/NodeManager.java
> Fix confignode restart Error

- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/load/balancer/partition/DataPartitionPolicyTable.java
> Fix confignode restart Error 

- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/compaction/FastCompactionPerformerWithInconsistentCompressionTypeAndEncodingTest.java
add pages of aligned chunk validation in test
> [To rel/1.2]Add compression and encoding type check for FastCompactionPerformer

- server/src/test/java/org/apache/iotdb/db/engine/compaction/FastCompactionPerformerWithInconsistentCompressionTypeAndEncodingTest.java
add pages of aligned chunk validation in test
> [To rel/1.1]Add compression and encoding type check for FastCompactionPerformer

- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/compaction/FastCompactionPerformerWithInconsistentCompressionTypeAndEncodingTest.java
add pages of aligned chunk validation in test
> Add compression and encoding type check for FastCompactionPerformer

- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/load/LoadManager.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/load/balancer/partition/DataPartitionPolicyTable.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/node/NodeManager.java
cherry-pick [pull](https://github.com/apache/iotdb/pulls)
> [To rel/1.2] Fix confignode restart Error

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/base/IoTDBThriftConnector.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/v1/IoTDBThriftConnectorV1.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/v2/IoTDBThriftConnectorV2.java
- iotdb-core/node-commons/src/test/java/org/apache/iotdb/commons/pipe/PipeMetaDeSerTest.java
(cherry picked from commit 51cdd6a37101329845704676962d0c542d3b37a5)
> [To rel/1.2][IOTDB-6084] Pipe: Support node-urls (client HA) in iotdb-thrift-connector-v1(v2) (#10749)

- integration-test/src/test/java/org/apache/iotdb/db/it/aligned/IoTDBInsertAlignedValues2IT.java
- tsfile/src/main/java/org/apache/iotdb/tsfile/write/page/TimePageWriter.java
- tsfile/src/test/java/org/apache/iotdb/tsfile/write/writer/TimeChunkWriterTest.java
> [To rel/1.1][IOTDB-6098] Fix a possible flush error when using aligned timeseries

- integration-test/src/test/java/org/apache/iotdb/db/it/aligned/IoTDBInsertAlignedValues2IT.java
- iotdb-core/tsfile/src/main/java/org/apache/iotdb/tsfile/write/page/TimePageWriter.java
- iotdb-core/tsfile/src/test/java/org/apache/iotdb/tsfile/write/writer/TimeChunkWriterTest.java
> [To rel/1.2][IOTDB-6098] Fix a possible flush error when using aligned timeseries

- .github/workflows/sonar-coveralls.yml
This PR is fixing this warning.
> Use JDK 17 for sonar check

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/task/InnerSpaceCompactionTask.java
> [To rel/1.2] Close compaction memory estimator after calculate memory cost

- server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/utils/executor/fast/AlignedSeriesCompactionExecutor.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/utils/executor/fast/NonAlignedSeriesCompactionExecutor.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/utils/executor/fast/SeriesCompactionExecutor.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/utils/executor/fast/element/ChunkMetadataElement.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/utils/executor/fast/element/PageElement.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/FastCompactionPerformerWithInconsistentCompressionTypeAndEncodingTest.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/utils/CompactionTestFileWriter.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/utils/CompactionTestFileWriterTest.java
Same as PR https://github.com/apache/iotdb/pull/10712
> [To rel/1.1] Add compression and encoding type check for FastCompactionPerformer #10712

- integration-test/src/test/java/org/apache/iotdb/db/it/udf/IoTDBUDTFBuiltinFunctionIT.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/transformation/dag/adapter/ElasticSerializableTVListBackedSingleColumnRow.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/transformation/dag/adapter/LayerPointReaderBackedSingleColumnRow.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/udf/builtin/UDTFM4.java
(cherry picked from commit 9fb01f5674edc3bb1a73460c281b802670627dca)
> [To rel/1.2] [IOTDB-6096] Make M4 Function do the nullable judgement

- integration-test/src/test/java/org/apache/iotdb/db/it/udf/IoTDBUDFM4IT.java
- integration-test/src/test/java/org/apache/iotdb/db/it/udf/IoTDBUDTFBuiltinFunctionIT.java
- node-commons/src/main/java/org/apache/iotdb/commons/udf/builtin/UDTFM4.java
- server/src/main/java/org/apache/iotdb/db/mpp/transformation/dag/adapter/ElasticSerializableTVListBackedSingleColumnRow.java
- server/src/main/java/org/apache/iotdb/db/mpp/transformation/dag/adapter/LayerPointReaderBackedSingleColumnRow.java
(cherry picked from commit 9fb01f5674edc3bb1a73460c281b802670627dca)
> [To rel/1.1] [IOTDB-6096] Make M4 Function do the nullable judgement

- server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/performer/impl/FastCompactionPerformer.java
- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/DataRegion.java
- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/HashLastFlushTimeMap.java
- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/IDTableLastFlushTimeMap.java
- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/TsFileResource.java
- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/timeindex/DeviceTimeIndex.java
- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/timeindex/FileTimeIndex.java
- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/timeindex/ITimeIndex.java
- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/timeindex/V012FileTimeIndex.java
- server/src/test/java/org/apache/iotdb/db/engine/storagegroup/LastFlushTimeMapTest.java
> [To rel/1.1] Fix recover last flush time map bug

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/DataRegion.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/HashLastFlushTimeMap.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/performer/impl/FastCompactionPerformer.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/tsfile/TsFileResource.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/tsfile/timeindex/DeviceTimeIndex.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/tsfile/timeindex/FileTimeIndex.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/tsfile/timeindex/ITimeIndex.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/LastFlushTimeMapTest.java
> [To rel/1.2] Fix recover last flush time map bug

- server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/task/CrossSpaceCompactionTask.java
Simple change: Change log from error to info when memory lack for cross compaction.
> [To rel/1.1] Change log from error to info when memory lack for cross compaction

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/AnalyzeVisitor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/execution/config/executor/ClusterConfigTaskExecutor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/statement/metadata/DatabaseSchemaStatement.java
(cherry picked from commit ebc95a772b6f3ac1de05718240ce63a76381e7b1)
> [To rel/1.2][IOTDB-6094] Load: Fix error in if/else judgment of tsfileResource exists or not & Reduce warn log when timeseries exist (#10762)

- README.md
- iotdb-client/client-cpp/pom.xml
- pom.xml
- tools/thrift/pom.xml
(Also fixed the problem also enabling uinx profiles on Macs)
> build: Changed the build to build a statically linked thrift executable for Linux

- iotdb-connector/grafana-plugin/pkg/plugin/plugin.go
Removed front-end request parameters output in Grafana backend logs
> Removed front-end request parameters output in Grafana backend logs

- iotdb-core/node-commons/src/assembly/resources/sbin/iotdb-common.sh
Fixed issue where iotdb common.sh was null when obtaining iotdb port
> Fixed issue where iotdb common.sh was null when obtaining iotdb port

- node-commons/src/assembly/resources/sbin/iotdb-common.sh
[To rel/1.1] Fixed issue where iotdb common.sh was null when obtaining iotdb port
> [To rel/1.1] Fixed issue where iotdb common.sh was null when obtaining iotdb port

- Jenkinsfile
> fix: Fixed the name of the profile used to activate the integration-tests on jenkins.

- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/load/service/StatisticsService.java
cherry-pick [pull](https://github.com/apache/iotdb/pull/10797)
> [To rel/1.2] Optimize leader change event 

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/tool/Interval.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/tool/ListTimeRangeImpl.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/tool/OverlapStatisticTool.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/tool/UnseqSpaceStatistics.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/compaction/tools/ListTimeRangeImplTest.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/compaction/tools/UnseqSpaceStatisticsTest.java
add a time range tool for compaction
> Time range tool

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/utils/executor/fast/AlignedSeriesCompactionExecutor.java
Fix compaction force decoding check. https://github.com/apache/iotdb/pull/10801
Before:
After:
> [To rel/1.2] Fix compaction force decoding check

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/memory/MemoryPool.java
This pr make the error message more specific to make it easier to debug.
> Perfect some error messages of Memorypool

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/memory/MemoryPool.java
This pr make the error message more specific to make it easier to debug.
> [To rel/1.2] Perfect some error messages of Memorypool

- server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/utils/executor/fast/AlignedSeriesCompactionExecutor.java
Fix compaction force decoding check. https://github.com/apache/iotdb/pull/10801
Before:
After:
> [To rel/1.1] Fix compaction force decoding check

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/utils/executor/fast/AlignedSeriesCompactionExecutor.java
Fix compaction force decoding check
Before:
After:
> Fix compaction force decoding check

- iotdb-core/confignode/src/assembly/resources/conf/iotdb-confignode.properties
cherry-pick [pull](https://github.com/apache/iotdb/pull/10812)
> [To rel/1.2] Enhance cn_confignode_target_list comments

- iotdb-client/service-rpc/pom.xml
- iotdb-client/service-rpc/src/main/java/org/apache/iotdb/rpc/RpcUtils.java
- iotdb-client/service-rpc/src/main/java/org/apache/iotdb/rpc/StatementExecutionException.java
https://github.com/apache/iotdb/pull/10329 left some files, this PR is for removing them.
> Totally remove influxdb-protocol related files

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/service/TemporaryQueryDataFileService.java
cp from https://github.com/apache/iotdb/pull/10817
> [To rel/1.2] [IOTDB-6104] Remove tmp directory for udf query completely while query end

- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/service/ConfigNode.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/service/thrift/ConfigNodeRPCService.java
- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/iot/service/IoTConsensusRPCService.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/session/SessionManager.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/service/DataNode.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/concurrent/threadpool/WrappedScheduledExecutorService.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/concurrent/threadpool/WrappedSingleThreadExecutorService.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/concurrent/threadpool/WrappedSingleThreadScheduledExecutor.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/concurrent/threadpool/WrappedThreadPoolExecutor.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/conf/IoTDBConstant.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/service/ServiceType.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/service/ThriftService.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/service/metric/MetricService.java
- iotdb-core/node-commons/src/test/java/org/apache/iotdb/commons/client/mock/MockInternalRPCService.java
This PR is fixing this issue by unifying the package name in mbeam to org.apache.iotdb.service.
> Fix error log when start confignode and datanode

- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/iot/client/AsyncIoTConsensusServiceClient.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/client/async/AsyncConfigNodeIServiceClient.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/client/async/AsyncDataNodeInternalServiceClient.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/client/async/AsyncDataNodeMPPDataExchangeServiceClient.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/client/async/AsyncPipeDataTransferServiceClient.java
- iotdb-core/node-commons/src/test/java/org/apache/iotdb/commons/client/ClientManagerTest.java
cherry-pick [pull](https://github.com/apache/iotdb/pull/10822)
> [To rel/1.2][IOTDB-6106] Fixed the timeout parameter not working in thrift asyncClient 

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/legacy/loader/TsFileLoader.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/AnalyzeVisitor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/LoadTsfileAnalyzer.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/parser/ASTVisitor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/statement/crud/LoadTsFileStatement.java
> [IOTDB-6105] Load: NPE when analyzing tsfile

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/legacy/loader/TsFileLoader.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/AnalyzeVisitor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/LoadTsfileAnalyzer.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/parser/ASTVisitor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/statement/crud/LoadTsFileStatement.java
(cherry picked from commit 2e6d9527c047bd5487af8e868d156dc511ac4578)
> [To rel/1.2][IOTDB-6105] Load: NPE when analyzing tsfile (#10821)

- consensus/src/main/java/org/apache/iotdb/consensus/iot/client/AsyncIoTConsensusServiceClient.java
- node-commons/src/main/java/org/apache/iotdb/commons/client/async/AsyncConfigNodeHeartbeatServiceClient.java
- node-commons/src/main/java/org/apache/iotdb/commons/client/async/AsyncConfigNodeIServiceClient.java
- node-commons/src/main/java/org/apache/iotdb/commons/client/async/AsyncDataNodeHeartbeatServiceClient.java
- node-commons/src/main/java/org/apache/iotdb/commons/client/async/AsyncDataNodeInternalServiceClient.java
- node-commons/src/main/java/org/apache/iotdb/commons/client/async/AsyncDataNodeMPPDataExchangeServiceClient.java
- node-commons/src/test/java/org/apache/iotdb/commons/client/ClientManagerTest.java
cherry-pick [pull](https://github.com/apache/iotdb/pull/10822)
> [To rel/1.1][IOTDB-6106] Fixed the timeout parameter not working in thrift asyncClient 

- iotdb-client/session/pom.xml
- iotdb-client/session/src/test/java/org/apache/iotdb/session/pool/SessionPoolTest.java
> session module add UT

- integration-test/src/main/java/org/apache/iotdb/it/env/cluster/config/MppCommonConfig.java
- integration-test/src/main/java/org/apache/iotdb/it/env/cluster/config/MppSharedCommonConfig.java
- integration-test/src/main/java/org/apache/iotdb/it/env/remote/config/RemoteCommonConfig.java
- integration-test/src/main/java/org/apache/iotdb/itbase/env/CommonConfig.java
- integration-test/src/test/java/org/apache/iotdb/confignode/it/partition/IoTDBPartitionDurableIT.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/conf/ConfigNodeDescriptor.java
fix parameter schemaRegionPerNode load error
> fix parameter schemaRegionPerNode load error

- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/load/LoadManager.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/load/balancer/RouteBalancer.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/load/service/StatisticsService.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/concurrent/ThreadName.java
post changes only if the relevant information changes
> Enhance the event notification mechanism of StatisticsService

- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/load/LoadManager.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/load/balancer/RouteBalancer.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/load/service/StatisticsService.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/concurrent/ThreadName.java
cherry-pick [pull](https://github.com/apache/iotdb/pull/10829)
> [To rel/1.2] Enhance the event notification mechanism of StatisticsService

- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/TsFileProcessor.java
- server/src/main/java/org/apache/iotdb/db/utils/datastructure/AlignedTVList.java
- server/src/test/java/org/apache/iotdb/db/engine/storagegroup/TsFileProcessorTest.java
> [To rel/1.1][IOTDB-6108] Fix AlignedTVList memory calculation is imprecise

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/HashLastFlushTimeMap.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/tsfile/TsFileManager.java
> [To rel/1.2] Fix a concurrent bug when recover last flush time and compact

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/memtable/TsFileProcessor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/utils/datastructure/AlignedTVList.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/memtable/TsFileProcessorTest.java
> [To rel/1.2][IOTDB-6108] Fix AlignedTVList memory calculation is imprecise

- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/HashLastFlushTimeMap.java
- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/TsFileManager.java
> [To rel/1.1] Fix a concurrent bug when recover last flush time and compact 

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/execution/config/executor/ClusterConfigTaskExecutor.java
cherry-pick: https://github.com/apache/iotdb/pull/10854
> [To rel/1.2][IOTDB-6113] Load: Fix setDatabase does not print logs and set failure except DATABASE_ALREADY_EXISTS

- integration-test/src/main/java/org/apache/iotdb/it/env/cluster/MppCommonConfig.java
- integration-test/src/main/java/org/apache/iotdb/it/env/cluster/MppSharedCommonConfig.java
- integration-test/src/main/java/org/apache/iotdb/it/env/remote/RemoteCommonConfig.java
- integration-test/src/main/java/org/apache/iotdb/itbase/env/CommonConfig.java
- integration-test/src/test/java/org/apache/iotdb/confignode/it/partition/IoTDBPartitionDurableIT.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/conf/ConfigNodeDescriptor.java
- iotdb-core/node-commons/src/assembly/resources/conf/iotdb-common.properties
cherry-pick from https://github.com/apache/iotdb/pull/10841
> [To rel/1.2] fix parameter schemaRegionPerNode load error

- iotdb-core/datanode/src/assembly/resources/tools/schema/print-pb-tree-file.sh
(cherry picked from commit f7ca23cbd00c0888ca3b5716ec4a2fad00bff845)
> [To rel/1.2]Fix SchemaFileSketchTool is not found

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/AlignedSeriesScanUtil.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/read/reader/chunk/MemAlignedPageReader.java
- iotdb-core/tsfile/src/main/java/org/apache/iotdb/tsfile/read/reader/page/AlignedPageReader.java
(cherry picked from commit cdcb4a691d3563f40904db3f2d9b314d573d9c55)
> [To rel/1.2] [IOTDB-6112] Fix Limit & Offset push down doesn't take effect while there exist time filter

- integration-test/src/test/java/org/apache/iotdb/db/it/utils/TestUtils.java
- integration-test/src/test/java/org/apache/iotdb/pipe/it/IoTDBPipeDataSyncIT.java
- integration-test/src/test/java/org/apache/iotdb/pipe/it/IoTDBPipeSingleEnvDemoIT.java
> Pipe IT: fix the usage of Awaitility.awit

- integration-test/src/test/java/org/apache/iotdb/confignode/it/partition/IoTDBAutoRegionGroupExtensionIT.java
- integration-test/src/test/java/org/apache/iotdb/confignode/it/partition/IoTDBAutoRegionGroupExtensionIT2.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/load/balancer/region/GreedyRegionGroupAllocator.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/load/cache/node/DataNodeHeartbeatCache.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/load/cache/region/RegionHeartbeatSample.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/persistence/partition/DatabasePartitionTable.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/persistence/partition/RegionGroup.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/env/ConfigNodeProcedureEnv.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/env/DataNodeRemoveHandler.java
- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/ratis/RatisConsensus.java
- iotdb-core/consensus/src/test/java/org/apache/iotdb/consensus/ratis/RatisConsensusTest.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/thrift/impl/DataNodeInternalRPCServiceImpl.java
The RegionReplicaSet was not updated successfully after migration
> Fix Region migrate bug

- integration-test/src/test/java/org/apache/iotdb/confignode/it/partition/IoTDBAutoRegionGroupExtensionIT.java
- integration-test/src/test/java/org/apache/iotdb/confignode/it/partition/IoTDBAutoRegionGroupExtensionIT2.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/load/balancer/region/GreedyRegionGroupAllocator.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/load/cache/node/DataNodeHeartbeatCache.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/load/cache/region/RegionHeartbeatSample.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/persistence/partition/DatabasePartitionTable.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/persistence/partition/RegionGroup.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/env/ConfigNodeProcedureEnv.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/env/DataNodeRemoveHandler.java
- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/ratis/RatisConsensus.java
- iotdb-core/consensus/src/test/java/org/apache/iotdb/consensus/ratis/RatisConsensusTest.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/thrift/impl/DataNodeInternalRPCServiceImpl.java
The RegionReplicaSet was not updated successfully after migration
> [To rel/1.2] Fix Region migrate bug

- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/consensus/ConsensusManager.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/consensus/DataRegionConsensusImpl.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/consensus/SchemaRegionConsensusImpl.java
cherry-pick of https://github.com/apache/iotdb/pull/10876
> [To rel/1.2][RatisConsensus] Unify read timeout to Thrift connection timeout

- integration-test/src/test/java/org/apache/iotdb/db/it/utils/TestUtils.java
- integration-test/src/test/java/org/apache/iotdb/pipe/it/IoTDBPipeDataSyncIT.java
Now the pipe IT will not fail after first query inconsistent occurs.
<hr>
This PR has:
<hr>
> Pipe IT: Stablelized pipe IT by prohibiting exceptions from assertEqual function

- iotdb-core/consensus/src/test/java/org/apache/iotdb/consensus/simple/SimpleConsensusTest.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/execution/executor/RegionReadExecutorTest.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/execution/executor/RegionWriteExecutorTest.java
> consensus module refactor: fix tests

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/AlignedSeriesScanOperator.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/AlignedSeriesScanUtil.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/Analysis.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/AnalyzeVisitor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/parser/ASTVisitor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/LogicalPlanBuilder.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/LogicalPlanVisitor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/OperatorTreeGenerator.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/plan/node/PlanGraphPrinter.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/plan/node/source/AlignedSeriesScanNode.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/statement/crud/QueryStatement.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/memtable/AlignedReadOnlyMemChunk.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/read/reader/chunk/DiskAlignedChunkLoader.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/read/reader/chunk/MemAlignedChunkLoader.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/read/reader/chunk/MemAlignedChunkReader.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/read/reader/chunk/MemAlignedPageReader.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/read/reader/chunk/metadata/DiskAlignedChunkMetadataLoader.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/read/reader/chunk/metadata/MemAlignedChunkMetadataLoader.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/utils/FileLoaderUtils.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/execution/operator/AlignedSeriesScanOperatorTest.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/execution/operator/OperatorMemoryTest.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/plan/plan/QueryLogicalPlanUtil.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/read/reader/chunk/MemAlignedChunkLoaderTest.java
- iotdb-core/tsfile/src/main/java/org/apache/iotdb/tsfile/read/TsFileAlignedSeriesReaderIterator.java
- iotdb-core/tsfile/src/main/java/org/apache/iotdb/tsfile/read/reader/chunk/AlignedChunkReader.java
- iotdb-core/tsfile/src/main/java/org/apache/iotdb/tsfile/read/reader/page/AlignedPageReader.java
- iotdb-core/tsfile/src/main/java/org/apache/iotdb/tsfile/read/reader/series/FileSeriesReader.java
- iotdb-core/tsfile/src/test/java/org/apache/iotdb/tsfile/write/TsFileIntegrityCheckingTool.java
(cherry picked from commit 97e083efcec556c3ae1e3ba3609496fd4dbb1cbe)
> [To rel/1.2] [IOTDB-6115] Fix Limit & Offset push down doesn't take effect while there exist null value

- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/client/DataNodeRequestType.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/client/async/AsyncDataNodeClientPool.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/client/async/handlers/AsyncClientHandler.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/persistence/pipe/PipeTaskInfo.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/env/ConfigNodeProcedureEnv.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/pipe/AbstractOperatePipeProcedureV2.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/pipe/task/CreatePipeProcedureV2.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/pipe/task/DropPipeProcedureV2.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/pipe/task/StartPipeProcedureV2.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/pipe/task/StopPipeProcedureV2.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/agent/task/PipeTaskAgent.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/thrift/impl/DataNodeInternalRPCServiceImpl.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/task/meta/PipeMetaKeeper.java
- iotdb-protocol/thrift/src/main/thrift/datanode.thrift
cherry-picked from https://github.com/apache/iotdb/pull/10875
> [To rel/1.2][IOTDB-6117] Pipe: Optimize RPC requests from CN to DN

- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/consensus/ConsensusManager.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/node/NodeManager.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/partition/PartitionManager.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/schema/ClusterSchemaManager.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/cq/CreateCQProcedure.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/schema/SetTemplateProcedure.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/trigger/CreateTriggerProcedure.java
- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/IConsensus.java
- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/exception/RatisUnderRecoveryException.java
- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/ratis/RatisConsensus.java
- iotdb-core/consensus/src/test/java/org/apache/iotdb/consensus/simple/SimpleConsensusTest.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/executor/RegionWriteExecutor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/service/IoTDBShutdownHook.java
> consensus module refactor: fix code smells

- integration-test/src/test/java/org/apache/iotdb/db/it/udf/IoTDBUDFManagementIT.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/executable/ExecutableManager.java
> [To rel/1.2] Override existing jar instead of deleting it when registering UDF

- integration-test/src/test/java/org/apache/iotdb/db/it/udf/IoTDBUDFManagementIT.java
- node-commons/src/main/java/org/apache/iotdb/commons/executable/ExecutableManager.java
> [To rel/1.1] Override existing jar instead of deleting it when registering UDF

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/agent/runtime/PipeRuntimeAgent.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/tsfile/TsFileResource.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/wal/recover/file/UnsealedTsFileRecoverPerformer.java
cherry-pick: https://github.com/apache/iotdb/pull/10908
> [To rel/1.2][IOTDB-6122] Pipe: Progress Index markers an incorrect value when load a tsfile with tsfileResource

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/schedule/CompactionTaskManager.java
Four compaction configs support hot-load.
1. compaction_validation_level
2. enable_seq_space_compaction
3. enable_unseq_space_compaction
4. enable_cross_space_compaction
5. compaction_thread_count
6. sub_compaction_thread_count
> Add hot load compaction configs

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/flush/MemTableFlushTask.java
- iotdb-core/metrics/interface/src/main/java/org/apache/iotdb/metrics/AbstractMetricService.java
- iotdb-core/metrics/interface/src/main/java/org/apache/iotdb/metrics/reporter/iotdb/IoTDBReporter.java
(cherry picked from commit 1dce787c39e14973918ee390c470b901b68be73e)
> [To rel/1.2][Metric] Fix flush point statistics

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/Analysis.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/AnalyzeVisitor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/optimization/LimitOffsetPushDown.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/parser/ASTVisitor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/LogicalPlanVisitor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/statement/component/OrderByComponent.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/statement/crud/QueryStatement.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/plan/optimization/LimitOffsetPushDownTest.java
(cherry picked from commit https://github.com/apache/iotdb/commit/51e6d17b82191e6661a91ee1696138480560e532)
> [To rel/1.2][IOTDB-6120] Push down limit/offset in query with group by time

- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/service/ConfigNode.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/service/metrics/DataNodeMetricsHelper.java
- iotdb-core/metrics/interface/src/main/java/org/apache/iotdb/metrics/metricsets/system/SystemMetrics.java
Support hot reload data dir in SystemMetrics.
> [IOTDB-6082] Improve disk space metrics

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/extractor/IoTDBDataRegionExtractor.java
Swapped the startup sequence of realtimeExtractor and historicalExtractor to avoid possible data loss.
<hr>
This PR has:
<hr>
> Pipe: Swapped the start order of realtimeExtractor and historicalExtractor to avoid losing data

- pom.xml
Use new released iotdb-tools-thrift to build thrift files.
> Use new released iotdb-tools-thrift to build thrift files

- metrics/interface/src/main/java/org/apache/iotdb/metrics/AbstractMetricService.java
- metrics/interface/src/main/java/org/apache/iotdb/metrics/reporter/iotdb/IoTDBReporter.java
- server/src/main/java/org/apache/iotdb/db/engine/flush/MemTableFlushTask.java
> [To rel/1.1][Metric] Fix flush point statistics

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/payload/evolvable/PipeRequestType.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/payload/evolvable/builder/IoTDBThriftAsyncPipeTransferBatchReqBuilder.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/payload/evolvable/builder/IoTDBThriftSyncPipeTransferBatchReqBuilder.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/payload/evolvable/builder/PipeTransferBatchReqBuilder.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/payload/evolvable/request/PipeTransferTabletBatchReq.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/payload/evolvable/request/PipeTransferTabletBinaryReq.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/payload/evolvable/request/PipeTransferTabletInsertNodeReq.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/payload/evolvable/request/PipeTransferTabletRawReq.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/protocol/airgap/IoTDBAirGapConnector.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/protocol/thrift/async/IoTDBThriftAsyncConnector.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/protocol/thrift/async/handler/PipeTransferTabletBatchEventHandler.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/protocol/thrift/async/handler/PipeTransferTabletInsertNodeEventHandler.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/protocol/thrift/async/handler/PipeTransferTabletRawEventHandler.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/protocol/thrift/sync/IoTDBThriftSyncConnector.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/event/common/tablet/PipeInsertNodeTabletInsertionEvent.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/receiver/thrift/IoTDBThriftReceiverV1.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/wal/utils/WALEntryHandler.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/wal/utils/WALEntryPosition.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/wal/utils/WALInsertNodeCache.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/pipe/connector/PipeReceiverTest.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/pipe/connector/PipeThriftRequestTest.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/wal/node/WALEntryHandlerTest.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/wal/utils/WALInsertNodeCacheTest.java
cherry-pick: https://github.com/apache/iotdb/pull/10913
> [To rel/1.2][IOTDB-6123] Pipe: reduce the de/ser to slove the slow log transfer problem

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/extractor/realtime/PipeRealtimeDataRegionHybridExtractor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/extractor/realtime/PipeRealtimeDataRegionLogExtractor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/extractor/realtime/PipeRealtimeDataRegionTsFileExtractor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/task/connection/BlockingPendingQueue.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/task/connection/PipeEventCollector.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/task/connection/UnboundedBlockingPendingQueue.java
(cherry picked from commit f1a4012424fef30509ed13e33e1b641ffc5d4ba9)
> [To rel/1.2] Pipe: drop HeartbeatEvent when pipe is stopped to avoid OOM (#10977)

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/utils/executor/fast/SeriesCompactionExecutor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/utils/executor/fast/element/PointElement.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/utils/reader/PointPriorityReader.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/compaction/FastCompactionPerformerWithEmptyPageTest.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/compaction/utils/CompactionTestFileWriter.java
Add hasNextTimeValuePair() check before call nextTimeValuePair() when creating a new instance of PointElement.
> Fix point priority reader array index out of bound exception

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/utils/executor/fast/SeriesCompactionExecutor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/utils/executor/fast/element/PointElement.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/utils/reader/PointPriorityReader.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/compaction/FastCompactionPerformerWithEmptyPageTest.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/compaction/utils/CompactionTestFileWriter.java
https://github.com/apache/iotdb/pull/10919
> [To rel/1.2] Fix point priority reader index out of bound

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/utils/executor/fast/element/PageElement.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/utils/executor/fast/element/PointElement.java
- iotdb-core/tsfile/src/main/java/org/apache/iotdb/tsfile/read/reader/chunk/AlignedChunkReader.java
- iotdb-core/tsfile/src/main/java/org/apache/iotdb/tsfile/read/reader/page/AlignedPageReader.java
- iotdb-core/tsfile/src/main/java/org/apache/iotdb/tsfile/read/reader/page/LazyLoadAlignedPagePointReader.java
- iotdb-core/tsfile/src/test/java/org/apache/iotdb/tsfile/read/reader/LazyLoadAlignedPagePointReaderTest.java
Same as PR https://github.com/apache/iotdb/pull/10966
> [To rel/1.2] add lazy page reader for aligned page reader to avoid huge memory cost when reading rows of aligned timeseries

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/plan/node/write/DeleteDataNode.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/DataRegion.java
> [To rel/1.2] Accelerate the deletion execution

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/rest/utils/InsertRowDataUtils.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/rest/v1/handler/RequestValidationHandler.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/rest/v1/handler/StatementConstructionHandler.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/rest/v1/impl/RestApiServiceImpl.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/rest/v2/handler/RequestValidationHandler.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/rest/v2/handler/StatementConstructionHandler.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/rest/v2/impl/RestApiServiceImpl.java
- iotdb-protocol/openapi/src/main/openapi3/iotdb_rest_v1.yaml
- iotdb-protocol/openapi/src/main/openapi3/iotdb_rest_v2.yaml
Feature add insertRecords method to rest service
> Feature add insertRecords method to rest service

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/rest/utils/InsertRowDataUtils.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/rest/v1/handler/RequestValidationHandler.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/rest/v1/handler/StatementConstructionHandler.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/rest/v1/impl/RestApiServiceImpl.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/rest/v2/handler/RequestValidationHandler.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/rest/v2/handler/StatementConstructionHandler.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/rest/v2/impl/RestApiServiceImpl.java
- iotdb-protocol/openapi/src/main/openapi3/iotdb_rest_v1.yaml
- iotdb-protocol/openapi/src/main/openapi3/iotdb_rest_v2.yaml
[To rel/1.2] Feature add insertRecords method to rest service
> [To rel/1.2] Feature add insertRecords method to rest service

- iotdb-core/datanode/src/assembly/resources/conf/logback-datanode.xml
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/config/constant/PipeConnectorConstant.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/protocol/IoTDBConnector.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/event/common/tsfile/PipeTsFileInsertionEvent.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/extractor/realtime/epoch/TsFileEpochManager.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/memtable/TsFileProcessor.java
- iotdb-core/datanode/src/test/resources/datanode1conf/logback.xml
- iotdb-core/datanode/src/test/resources/datanode2conf/logback.xml
- iotdb-core/datanode/src/test/resources/datanode3conf/logback.xml
> Pipe: fix some minor concurrent issues & collect pipe's logs into a separate file

- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/consensus/statemachine/ConfigRegionStateMachine.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/consensus/ConsensusManager.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/cq/CQManager.java
- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/IStateMachine.java
- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/config/RatisConfig.java
- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/ratis/ApplicationStateMachineProxy.java
- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/ratis/utils/Utils.java
- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/simple/SimpleConsensusServerImpl.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/client/ConfigNodeClient.java
cherry-pick [pull](https://github.com/apache/iotdb/pull/10985)
> [To rel/1.2][IOTDB-6119] Add ConfigNode leader service check

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/protocol/airgap/IoTDBAirGapConnector.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/protocol/thrift/async/IoTDBThriftAsyncConnector.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/protocol/thrift/sync/IoTDBThriftSyncConnector.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/event/EnrichedEvent.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/event/common/tablet/PipeRawTabletInsertionEvent.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/event/common/tsfile/PipeTsFileInsertionEvent.java
cherry-picked from https://github.com/apache/iotdb/pull/11001
> [To rel/1.2] Pipe: Fix start-time and end-time parameters not working when extracting history data

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/schema/ClusterSchemaFetchExecutor.java
More details can be seen in this [issue](https://issues.apache.org/jira/browse/IOTDB-6134)
In this pr, we dispaly like the following:
> [IOTDB-6134] Fill statement content in show queries for inner schema fetch

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/schema/ClusterSchemaFetchExecutor.java
(cherry picked from commit d5450a1e5648699409e1c793035204989d78cfbb)
> [To rel/1.2] [IOTDB-6134] Fill statement content in show queries for inner schema fetch

- .github/workflows/sonar-coveralls.yml
> [To rel/1.2] Use JDK 17 for sonar check

- .github/workflows/client-python.yml
- .gitignore
- iotdb-client/client-py/.gitignore
- iotdb-client/client-py/SessionPoolExample.py
- iotdb-client/client-py/iotdb/IoTDBContainer.py
- iotdb-client/client-py/iotdb/SessionPool.py
- iotdb-client/client-py/pom.xml
- iotdb-client/client-py/release.sh
- iotdb-client/client-py/requirements_dev.txt
- iotdb-client/client-py/resources/setup.py
- iotdb-client/client-py/tests/test_session.py
- iotdb-client/client-py/tests/test_session_pool.py
This pr is optimizing the python client package and release process.
To package a python client, we can simply run `./release.sh` to get a whl.
> Optimize python client package and release process

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/execution/config/metadata/ShowClusterDetailsTask.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/execution/config/metadata/ShowClusterTask.java
cp from https://github.com/apache/iotdb/pull/11020
> [To rel/1.2] Fix possible NPE while executing show cluster or show cluster details

- Jenkinsfile
This pr is moving Jenkins notification to notifications list according to https://lists.apache.org/thread/4vn66jfk4ntmbwfzlfyob7doh77v4jp2 .
> Move Jenkins notification to notifications list

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/extractor/realtime/PipeRealtimeDataRegionHybridExtractor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/extractor/realtime/PipeRealtimeDataRegionLogExtractor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/extractor/realtime/PipeRealtimeDataRegionTsFileExtractor.java
cherry-picked from https://github.com/apache/iotdb/pull/11008
> [To rel/1.2][IOTDB-6135] Pipe: Fix a bug which keeps generating PipeHeartbeatEvent unnecessarily

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/event/common/heartbeat/PipeHeartbeatEvent.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/extractor/realtime/PipeRealtimeDataRegionHybridExtractor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/extractor/realtime/PipeRealtimeDataRegionLogExtractor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/extractor/realtime/PipeRealtimeDataRegionTsFileExtractor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/extractor/realtime/assigner/DisruptorQueue.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/task/connection/PipeEventCollector.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/task/connection/UnboundedBlockingPendingQueue.java
(cherry picked from commit eb43b4909a7df36299b2a9b9e4a95f2fd83ea5d6)
<hr>
This PR has:
<hr>
> [To rel/1.2] Pipe: Report queue size in PipeHeartbeatEvent (#10997)

- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/path/PathPatternTree.java
- iotdb-core/node-commons/src/test/java/org/apache/iotdb/commons/path/PathPatternTreeTest.java
> [To rel/1.2][IOTDB-6130] Delete data by specific pattern didn't work

- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/conf/ConfigNodeConfig.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/conf/ConfigNodeDescriptor.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/consensus/ConsensusManager.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/node/NodeManager.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/consensus/SchemaRegionConsensusImpl.java
- iotdb-core/node-commons/src/assembly/resources/conf/iotdb-common.properties
- iotdb-protocol/thrift-confignode/src/main/thrift/confignode.thrift
refine ratis properties
- add config_node / schema_region_ratis_grpc_leader_outstanding_appends_max
- add config_node / schema_region_ratis_log_force_sync_num
> [IOTDB-6139] Refine Ratis Properties

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/schedule/CompactionTaskManager.java
Four compaction configs support hot-load.
1. compaction_validation_level
2. enable_seq_space_compaction
3. enable_unseq_space_compaction
4. enable_cross_space_compaction
5. compaction_thread_count
6. sub_compaction_thread_count
> [To rel/1.2] add hot load compaction configs

- .github/workflows/client-cpp.yml
- .github/workflows/client-go.yml
- .github/workflows/client-python.yml
- .github/workflows/cluster-it-1c1d.yml
- .github/workflows/cluster-it-1c3d.yml
- .github/workflows/grafana-plugin.yml
- .github/workflows/iotdb-ml.yml
- .github/workflows/pipe-it-2cluster.yml
- .github/workflows/sonar-coveralls.yml
- .github/workflows/unit-test.yml
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/schema/source/DeviceSchemaSource.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/schema/source/LogicalViewSchemaSource.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/schema/source/TimeSeriesSchemaSource.java
Fix scope does not work when query count root.**
> Fix scope does not work when query count root.**

- integration-test/src/test/java/org/apache/iotdb/cli/it/StartClientScriptIT.java
- iotdb-client/cli/src/assembly/resources/sbin/start-cli.sh
- iotdb-client/cli/src/main/java/org/apache/iotdb/cli/AbstractCli.java
- iotdb-client/cli/src/main/java/org/apache/iotdb/cli/Cli.java
- iotdb-client/cli/src/test/java/org/apache/iotdb/cli/AbstractCliIT.java
> [To rel/1.2] Change display nums to fixed 1000

- integration-test/src/test/java/org/apache/iotdb/cli/it/StartClientScriptIT.java
- iotdb-client/cli/src/assembly/resources/sbin/start-cli.sh
- iotdb-client/cli/src/main/java/org/apache/iotdb/cli/AbstractCli.java
- iotdb-client/cli/src/main/java/org/apache/iotdb/cli/Cli.java
- iotdb-client/cli/src/test/java/org/apache/iotdb/cli/AbstractCliIT.java
docs: https://github.com/apache/iotdb-docs/pull/82
> feat(client): change display nums to fixed 1000

- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/persistence/executor/ConfigPlanExecutor.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/persistence/schema/ClusterSchemaInfo.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/persistence/schema/ConfigMTree.java
- iotdb-core/confignode/src/test/java/org/apache/iotdb/confignode/persistence/schema/ConfigMTreeTest.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/statement/metadata/CountNodesStatement.java
> Fix scope does not work when counting nodes 

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/io/CompactionTsFileWriter.java
When an aligned chunk writer of CompactionWriter is too large, the result of integer type conversion of it may be a negative num, which cause the RateLimiter report an IllegalArgumentException.
1. Many value columns in one aligned device.
2. Make the compaction module allocate enough memory.
3. Data of compaction candidate files is big enough.
4. Trigger a compaction.
> Fix negative requested permit of CompactionWriteRateLimiter

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/AnalyzeVisitor.java
> [To rel/1.2] Fix mods file contains writable view

- integration-test/src/test/java/org/apache/iotdb/db/it/IoTDBInsertWithQueryIT.java
- integration-test/src/test/java/org/apache/iotdb/session/it/IoTDBSessionSimpleIT.java
- iotdb-client/service-rpc/src/main/java/org/apache/iotdb/rpc/RpcUtils.java
- iotdb-client/service-rpc/src/test/java/org/apache/iotdb/rpc/RpcUtilsTest.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/partition/PartitionManager.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/thrift/impl/ClientRPCServiceImpl.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/load/AlignedChunkData.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/load/NonAlignedChunkData.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/load/TsFileSplitter.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/AnalyzeVisitor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/parser/ASTVisitor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/plan/node/load/LoadSingleTsFileNode.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/plan/node/write/InsertRowNode.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/plan/node/write/InsertRowsNode.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/plan/node/write/InsertRowsOfOneDeviceNode.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/plan/node/write/InsertTabletNode.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/statement/crud/InsertRowStatement.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/statement/crud/InsertRowsOfOneDeviceStatement.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/statement/crud/InsertTabletStatement.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/StorageEngine.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/utils/TimePartitionUtils.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/plan/plan/node/write/WritePlanNodeSplitTest.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/StorageEngineTest.java
> [To rel/1.2][IOTDB-6138] Fix the support of negative timestamp

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/task/CrossSpaceCompactionTask.java
> [To rel/1.2] Fix compaction speed code

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/io/CompactionTsFileWriter.java
When an aligned chunk writer of CompactionWriter is too large, the result of integer type conversion of it may be a negative num, which cause the RateLimiter report an IllegalArgumentException.
1. Many value columns in one aligned device.
2. Make the compaction module allocate enough memory.
3. Data of compaction candidate files is big enough.
4. Trigger a compaction.
> [To rel/1.2] Fix negative requested permit of CompactionWriteRateLimiter

- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/conf/ConfigNodeConfig.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/conf/ConfigNodeDescriptor.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/consensus/ConsensusManager.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/node/NodeManager.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/consensus/SchemaRegionConsensusImpl.java
- iotdb-core/node-commons/src/assembly/resources/conf/iotdb-common.properties
- iotdb-protocol/thrift-confignode/src/main/thrift/confignode.thrift
cherry-pick [pr](https://github.com/apache/iotdb/pull/11047)
> [To rel/1.2][IOTDB-6139] Refine Ratis Properties

- library-udf/src/main/java/org/apache/iotdb/library/series/UDTFConsecutiveSequences.java
- library-udf/src/main/java/org/apache/iotdb/library/series/UDTFConsecutiveWindows.java
- library-udf/src/main/java/org/apache/iotdb/library/series/util/ConsecutiveUtil.java
This PR is remove some copyright info...
> Remove some copyright info

- library-udf/src/main/java/org/apache/iotdb/library/series/UDTFConsecutiveSequences.java
- library-udf/src/main/java/org/apache/iotdb/library/series/UDTFConsecutiveWindows.java
- library-udf/src/main/java/org/apache/iotdb/library/series/util/ConsecutiveUtil.java
> [To rel/1.2] Remove some copyright info

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/task/InnerSpaceCompactionTask.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/utils/CompactionUtils.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/compaction/utils/CompactionUpdateFileCountTest.java
Fix seq space file num and size statistics
> Fix seq space file num and size statistics

- docs/UserGuide/Operate-Metadata/Auto-Create-MetaData.md
- docs/zh/UserGuide/Operate-Metadata/Auto-Create-MetaData.md
- integration-test/src/test/java/org/apache/iotdb/db/it/schema/IoTDBMetadataFetchIT.java
- integration-test/src/test/java/org/apache/iotdb/db/it/schema/IoTDBSchemaTemplateIT.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
- iotdb-core/node-commons/src/assembly/resources/conf/iotdb-common.properties
> [To rc/1.2.1] Change default encoder of INT32 and INT64 from RLE to TS_2DIFF

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/statement/crud/QueryStatement.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/plan/analyze/AnalyzeFailTest.java
> Fix count_time bug when count_time aggregation using with other aggregation

- integration-test/src/test/java/org/apache/iotdb/db/it/auth/IoTDBSeriesPermissionIT.java
- integration-test/src/test/java/org/apache/iotdb/db/it/schema/IoTDBMetadataFetchIT.java
- integration-test/src/test/java/org/apache/iotdb/db/it/schema/IoTDBSchemaTemplateIT.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
- iotdb-core/node-commons/src/assembly/resources/conf/iotdb-common.properties
cp from https://github.com/apache/iotdb/pull/11099
> Change default encoder of INT32 and INT64 from RLE to TS_2DIFF

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/statement/crud/QueryStatement.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/plan/analyze/AnalyzeFailTest.java
same as https://github.com/apache/iotdb/pull/11112
> [To rel/1.2] Fix count_time bug when count_time aggregation using with other aggregation

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/payload/evolvable/builder/IoTDBThriftSyncPipeTransferBatchReqBuilder.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/protocol/thrift/async/IoTDBThriftAsyncConnector.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/protocol/websocket/WebSocketConnector.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/event/EnrichedEvent.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/event/realtime/PipeRealtimeEvent.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/extractor/realtime/PipeRealtimeDataRegionHybridExtractor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/extractor/realtime/PipeRealtimeDataRegionLogExtractor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/extractor/realtime/PipeRealtimeDataRegionTsFileExtractor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/extractor/realtime/assigner/PipeDataRegionAssigner.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/task/connection/PipeEventCollector.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/task/subtask/PipeSubtask.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/task/subtask/connector/PipeConnectorSubtask.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/task/subtask/processor/PipeProcessorSubtask.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/plan/node/write/PipeEnrichedInsertNode.java
> [IOTDB-6148] Pipe: Fixed the bug that some uncommited progresses may be reported

- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/persistence/pipe/PipeTaskInfo.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/pipe/task/CreatePipeProcedureV2.java
- iotdb-core/confignode/src/test/java/org/apache/iotdb/confignode/consensus/request/ConfigPhysicalPlanSerDeTest.java
- iotdb-core/confignode/src/test/java/org/apache/iotdb/confignode/consensus/response/pipe/PipeTableRespTest.java
- iotdb-core/confignode/src/test/java/org/apache/iotdb/confignode/persistence/PipeInfoTest.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/event/EnrichedEvent.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/event/common/heartbeat/PipeHeartbeatEvent.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/event/common/tablet/PipeInsertNodeTabletInsertionEvent.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/event/common/tablet/PipeRawTabletInsertionEvent.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/event/common/tsfile/PipeTsFileInsertionEvent.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/task/subtask/PipeSubtask.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/tsfile/TsFileResource.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/consensus/index/ProgressIndex.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/consensus/index/impl/HybridProgressIndex.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/consensus/index/impl/MinimumProgressIndex.java
- iotdb-core/node-commons/src/test/java/org/apache/iotdb/commons/pipe/PipeMetaDeSerTest.java
> Pipe: fix NPE when HybridProgressIndex.updateToMinimumIsAfterProgressIndex after system reboot (DR: SimpleConsensus)

- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/persistence/pipe/PipeTaskInfo.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/pipe/task/CreatePipeProcedureV2.java
- iotdb-core/confignode/src/test/java/org/apache/iotdb/confignode/consensus/request/ConfigPhysicalPlanSerDeTest.java
- iotdb-core/confignode/src/test/java/org/apache/iotdb/confignode/consensus/response/pipe/PipeTableRespTest.java
- iotdb-core/confignode/src/test/java/org/apache/iotdb/confignode/persistence/PipeInfoTest.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/event/EnrichedEvent.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/event/common/heartbeat/PipeHeartbeatEvent.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/event/common/tablet/PipeInsertNodeTabletInsertionEvent.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/event/common/tablet/PipeRawTabletInsertionEvent.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/event/common/tsfile/PipeTsFileInsertionEvent.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/task/subtask/PipeSubtask.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/tsfile/TsFileResource.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/consensus/index/ProgressIndex.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/consensus/index/impl/HybridProgressIndex.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/consensus/index/impl/MinimumProgressIndex.java
- iotdb-core/node-commons/src/test/java/org/apache/iotdb/commons/pipe/PipeMetaDeSerTest.java
(cherry picked from commit b49d0fb96f2d4192abb734dd83883dd283ae1fb2)
> [To rel/1.2] Pipe: fix NPE when HybridProgressIndex.updateToMinimumIsAfterProgressIndex after system reboot (DR: SimpleConsensus) (#11126)

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/Analyzer.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/execution/config/ConfigExecution.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/execution/config/ConfigTaskVisitor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/execution/config/executor/ClusterConfigTaskExecutor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/execution/config/executor/IConfigTaskExecutor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/execution/config/metadata/CreateContinuousQueryTask.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/execution/config/metadata/model/CreateModelTask.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/execution/config/metadata/view/AlterLogicalViewTask.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/statement/metadata/view/AlterLogicalViewStatement.java
> [To rel/1.2][IOTDB-6147] Alter view does not check the source path

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/memory/MemoryPool.java
> [To rel/1.2] Remove cancelled/done MemoryReservationFuture from the queue when freeing memory

- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/iot/IoTConsensusServerImpl.java
- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/iot/IoTConsensusServerMetrics.java
- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/iot/client/DispatchLogHandler.java
- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/iot/logdispatcher/LogDispatcher.java
- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/iot/logdispatcher/LogDispatcherThreadMetrics.java
- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/iot/service/IoTConsensusRPCServiceProcessor.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/service/metric/enums/Metric.java
cherry-pick [pr](https://github.com/apache/iotdb/pull/11134)
> [To rel/1.2][IOTDB-6152] Add IoTConsensus Sync Log Timer

- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/schema/ClusterSchemaManager.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/metric/SchemaEngineMemMetric.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/metric/SchemaMetricManager.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/metric/SchemaRegionCachedMetric.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/metric/SchemaRegionMemMetric.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/ISchemaRegion.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/impl/SchemaRegionMemoryImpl.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/impl/SchemaRegionPBTreeImpl.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/memtable/AbstractMemTable.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/memtable/IMemTable.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/memtable/PrimitiveMemTable.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/memtable/TsFileProcessor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/tsfile/TsFileResource.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/wal/recover/file/TsFilePlanRedoer.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/wal/recover/file/UnsealedTsFileRecoverPerformer.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/rescon/memory/MemTableManager.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/memtable/MemTableFlushTaskTest.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/memtable/MemtableBenchmark.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/memtable/PrimitiveMemTableTest.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/wal/checkpoint/CheckpointManagerTest.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/wal/io/CheckpointFileTest.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/wal/node/WALEntryHandlerTest.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/wal/node/WALNodeTest.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/wal/recover/WALRecoverManagerTest.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/wal/utils/WALInsertNodeCacheTest.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/service/metric/enums/Metric.java
cherry-pick [pull](https://github.com/apache/iotdb/pull/11113)
> [To rel/1.2]Add replication factor metrics and add database tag in throughput metrics and schema metrics

- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/client/async/AsyncDataNodeClientPool.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/load/balancer/RouteBalancer.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/pipe/runtime/PipeHeartbeatScheduler.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/env/ConfigNodeProcedureEnv.java
> Pipe: fix pipe procedure stuck because of data node async request forever waiting for response

- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/client/async/AsyncDataNodeClientPool.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/load/balancer/RouteBalancer.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/pipe/runtime/PipeHeartbeatScheduler.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/env/ConfigNodeProcedureEnv.java
(cherry picked from commit bdb6bd6da90c317dc40da8f43e2eeca4d2a75af8)
> [To rel/1.2] Pipe: fix pipe procedure stuck because of data node async request forever waiting for response (#11157)

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/memtable/TsFileProcessor.java
> [To rel/1.2] Fix tag in QUANTITY metric

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/memtable/TsFileProcessor.java
Fix database tag in QUANTITY metric
> Fix tag in QUANTITY metric

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/conf/IoTDBStartCheck.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/client/ConfigNodeInfo.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/service/DataNode.java
https://github.com/apache/iotdb/pull/11153
> [To rel/1.2][IOTDB-6151] Move datanode system.properties (#11153)

- example/flink-sql/pom.xml
- integration-test/pom.xml
> Fix the warn log in IT

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/config/constant/PipeConnectorConstant.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/payload/airgap/AirGapELanguageConstant.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/protocol/airgap/IoTDBAirGapConnector.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/receiver/airgap/IoTDBAirGapReceiver.java
(cherry picked from commit 3313d742104eea3e4be0049b8fb4be0a7e8e40fb)
> [To rel/1.2][IOTDB-6159] Pipe: Supported E-language payload in air gap connector/receiver (#11136)

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/rest/v1/handler/RequestValidationHandler.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/rest/v1/handler/StatementConstructionHandler.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/rest/v1/impl/RestApiServiceImpl.java
- iotdb-protocol/openapi/src/main/openapi3/iotdb_rest_v1.yaml
> [To rel/1.2] rest v1 remove insertRecords

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/thrift/impl/DataNodeInternalRPCServiceImpl.java
This is because statusReason maybe null
> [To rel/1.2]Fix NPE issue when setting system to readonly manually

- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/pipe/runtime/PipeHeartbeatParser.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/pipe/runtime/PipeMetaSyncer.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/pipe/task/PipeTaskCoordinator.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/pipe/task/PipeTaskCoordinatorLock.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/pipe/AbstractOperatePipeProcedureV2.java
> [To rel/1.2] Pipe: fix pipe coordinator deadlock causing CN election timeout

- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/pipe/runtime/PipeHeartbeatParser.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/pipe/runtime/PipeMetaSyncer.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/pipe/task/PipeTaskCoordinator.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/pipe/task/PipeTaskCoordinatorLock.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/pipe/AbstractOperatePipeProcedureV2.java
> Pipe: fix pipe coordinator deadlock causing CN election timeout (#11176)

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/rest/v1/handler/StatementConstructionHandler.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/rest/v2/handler/StatementConstructionHandler.java
cp from https://github.com/apache/iotdb/pull/11178
> [To rel/1.2] [IOTDB-6164] Fix create illegal path through rest api bug

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/thrift/impl/DataNodeInternalRPCServiceImpl.java
cherry-pick [pull](https://github.com/apache/iotdb/pull/11166)
> Fix NPE issue when setting system to readonly manually

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/statement/metadata/CreateAlignedTimeSeriesStatement.java
issue https://jira.infra.timecho.com:8443/browse/TIMECHODB-359
cause: forget to override `checkPermissionBeforeProcess` in `CreateAlignedTimeSeriesStatement`
fix: override the method
> Fix auth check of CreateAlignedTimeSeries

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/service/DataNode.java
https://issues.apache.org/jira/browse/IOTDB-6167
> [IOTDB-6167] DataNode can't register to cluster when fetch system configuration throws NPE

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/auth/AuthorityChecker.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/rest/handler/AuthorizationHandler.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/LoadTsfileAnalyzer.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/cache/partition/PartitionCache.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/schema/AutoCreateSchemaExecutor.java
cause: redundant metric record between `checkAuthority ` & specific checkPermission interfaces
fix: remove the metric record codes in specific checkPermission interfaces
> Fix metric of auth

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/utils/CommonUtils.java
cherry-pick: #11200
remove codes related to integration test
> [To rel/1.2][ISSUE-11199] Pipe: fix NPE when casting from null values in InsertRowNode deserialization

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/statement/crud/PipeEnrichedInsertBaseStatement.java
> [To rel/1.2] Pipe: fix NPE in PipeEnrichedInsertBaseStatement#isQuery when analyzing statement in metadata mismatch scenarios

- iotdb-api/pipe-api/src/main/java/org/apache/iotdb/pipe/api/PipeConnector.java
- iotdb-api/pipe-api/src/main/java/org/apache/iotdb/pipe/api/PipeProcessor.java
- iotdb-api/pipe-api/src/main/java/org/apache/iotdb/pipe/api/event/dml/insertion/TsFileInsertionEvent.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/protocol/airgap/IoTDBAirGapConnector.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/protocol/thrift/async/IoTDBThriftAsyncConnector.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/protocol/websocket/WebSocketConnector.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/event/common/tsfile/PipeTsFileInsertionEvent.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/event/common/tsfile/TsFileInsertionDataContainer.java
(cherry picked from commit 3f8c344b3a837a01fbbf3e46b99da0c4dcd2a303)
> [To rel/1.2] Pipe: fix file handle leak when processing with extractor.pattern (#11209)

- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/service/ConfigNode.java
https://issues.apache.org/jira/browse/IOTDB-6168
> [IOTDB-6168] ConfigNode register retry logic does not worked

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/statement/metadata/view/AlterLogicalViewStatement.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/statement/metadata/view/CreateLogicalViewStatement.java
1. fix NPE when  alter view because of the SourcePaths is null; 
2. fix the logic of getting checked paths from QueryStatement.
> Fix auth check when alter and create view

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/thrift/impl/DataNodeInternalRPCServiceImpl.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/cache/schema/DataNodeSchemaCache.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/cache/schema/DeviceUsingTemplateSchemaCache.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/cache/schema/TimeSeriesSchemaCache.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/cache/schema/dualkeycache/IDualKeyCache.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/cache/schema/dualkeycache/impl/CacheEntryGroupImpl.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/cache/schema/dualkeycache/impl/DualKeyCacheImpl.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/cache/schema/dualkeycache/impl/FIFOCacheEntryManager.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/cache/schema/dualkeycache/impl/ICacheEntryGroup.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/cache/schema/dualkeycache/impl/ICacheEntryManager.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/cache/schema/dualkeycache/impl/LRUCacheEntryManager.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/DataRegion.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/metadata/cache/dualkeycache/DualKeyCacheTest.java
> [To rel/1.2] SchemaCache supports precise eviction #11226

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/event/EnrichedEvent.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/task/connection/PipeEventCollector.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/task/subtask/PipeSubtask.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/task/subtask/connector/PipeConnectorSubtask.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/task/subtask/processor/PipeProcessorSubtask.java
(cherry picked from commit 1c3ab3900c77e53ec4b3ca0ad06651c84e936b47)
> [To rel/1.2] Pipe: fix drop pipe stuck (make connector subtask close faster by early returning) (#11222)

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/SelectIntoUtils.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/parser/ASTVisitor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/statement/component/IntoComponent.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/plan/analyze/AnalyzeFailTest.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/plan/analyze/AnalyzeTest.java
(cherry picked from commit 24dd2b7f2c9267fab2df4b2d4dcb72300d31a59d)
> [To rel/1.2][IOTDB-6160] Correct the target paths verify logic in Select Into

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/task/subtask/connector/PipeConnectorSubtaskManager.java
As title.
<hr>
This PR has:
<hr>
> Pipe: instantiate iotdb-thrift-connector from sync to async

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/task/subtask/connector/PipeConnectorSubtaskManager.java
cherry-pick: https://github.com/apache/iotdb/pull/11248
> [To rel/1.2] Pipe: instantiate iotdb-thrift-connector from sync to async

- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/ProcedureManager.java
cherry-pick: https://github.com/apache/iotdb/pull/11257
> [To rel/1.2] Pipe: add status message for procedure execution timed out

- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/pipe/runtime/PipeHeartbeatParser.java
> [IOTDB-6177] Pipe: Removed the exception time judgement when reporting exceptions to avoid losing failure message

- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/pipe/runtime/PipeHeartbeatParser.java
> [To rel/1.2][IOTDB-6177] Pipe: Removed the exception time judgement when reporting exceptions to avoid losing failure message

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/agent/runtime/PipeRuntimeAgent.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/agent/runtime/SimpleConsensusProgressIndexAssigner.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/extractor/realtime/PipeRealtimeDataRegionHybridExtractor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/memtable/TsFileProcessor.java
> [IOTDB-6176] Pipe: record SimpleProgressIndex for insertion when using SimpleConsensus to avoid wrong advance progress report

- integration-test/src/test/java/org/apache/iotdb/db/it/IoTDBPartialInsertionIT.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/plan/node/write/InsertTabletNode.java
If a partial insert request spans multiple data partitions, the NullPointerException may occur within InsertTabletNode. Use defensive programming to avoid this problem.
> Fix NPE when partially inserting tablet span multiple data partitions

- .github/workflows/grafana-plugin.yml
- iotdb-connector/grafana-plugin/go.mod
- iotdb-connector/grafana-plugin/pkg/plugin/plugin.go
Fixed failed to compile Grafana plugin using the latest version of SDK
> Fixed failed to compile Grafana plugin using the latest version of SDK

- .github/workflows/grafana-plugin.yml
- iotdb-connector/grafana-plugin/go.mod
- iotdb-connector/grafana-plugin/pkg/plugin/plugin.go
[rel/1.2] Fixed failed to compile Grafana plugin using the latest version of SDK
> [rel/1.2] Fixed failed to compile Grafana plugin using the latest version of SDK

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/rest/impl/PingApiServiceImpl.java
[rel/1.2] Fixed ping command for rest service
> [rel/1.2] Fixed ping command for rest service

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/service/metrics/FileMetrics.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/service/metrics/file/CompactionFileMetrics.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/service/metrics/file/ModsFileMetrics.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/service/metrics/file/SystemRelatedFileMetrics.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/service/metrics/file/TsFileMetrics.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/service/metrics/file/WalFileMetrics.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/DataRegion.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/task/CrossSpaceCompactionTask.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/task/InnerSpaceCompactionTask.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/compaction/utils/CompactionFileGeneratorUtils.java
> [To rel/1.2] Add database and region tag in disk file metrics

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/wal/buffer/WALBuffer.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/wal/node/WALNode.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/wal/utils/WALInsertNodeCache.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/wal/utils/WALInsertNodeCacheTest.java
…x multi pipes sharing the same ByteBuffer (#11285)
(cherry picked from commit 5bbe062515cad88d98e0c47bcfb22178041f6cd6)
<hr>
This PR has:
<hr>
> [To rel/1.2] Pipe: fix recovering huge entry from wal with wrong position bug & fix multi pipes sharing the same ByteBuffer (#11285)

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/thrift/impl/DataNodeInternalRPCServiceImpl.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/utils/CompactionUtils.java
- iotdb-core/metrics/interface/src/main/java/org/apache/iotdb/metrics/metricsets/system/SystemMetrics.java
- iotdb-core/metrics/interface/src/main/java/org/apache/iotdb/metrics/utils/SystemMetric.java
Fix SYS_DISK_FREE_SPACE metric and add SYS_AVAILABLE_SPACE metric
> Fix SYS_DISK_FREE_SPACE metric and add SYS_AVAILABLE_SPACE metric

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/thrift/impl/DataNodeInternalRPCServiceImpl.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/utils/CompactionUtils.java
- iotdb-core/metrics/interface/src/main/java/org/apache/iotdb/metrics/metricsets/system/SystemMetrics.java
- iotdb-core/metrics/interface/src/main/java/org/apache/iotdb/metrics/utils/SystemMetric.java
cherry picked from commit 32a1e10b2e40684bd4cd3d3f88603afddfa58ad2
> [To rel/1.2] Fix SYS_DISK_FREE_SPACE metric and add SYS_AVAILABLE_SPACE metric

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/LoadTsfileAnalyzer.java
> [IOTDB-6188] Load: Optimize the return of error codes related to user privileges

- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/consensus/statemachine/ConfigRegionStateMachine.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/ConfigManager.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/IManager.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/node/NodeManager.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/partition/PartitionMetrics.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/schema/ClusterSchemaManager.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/env/DataNodeRemoveHandler.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/schema/DeleteDatabaseProcedure.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/service/ConfigNode.java
1. Move add metrics from init to leader ready
2. Move the management of replication factor metric into PartitionMetrics
> Fix potential loss of metrics when restart confignode

- iotdb-client/cli/src/main/java/org/apache/iotdb/cli/Cli.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/service/metric/JvmGcMonitorMetrics.java
> [To Rel/1.2] Fix the problem of inaccurate GC monitor detection at the beginning and adjusting the alert threshold.

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/wal/recover/WALNodeRecoverTask.java
When the datanode restarts, WalManager restores the maximum searchIndex from the wal file. The consensus layer depends on this value. You should wait until searchIndex recovers before releasing the count lock
> Fixed an issue where searchIndex was not restored properly after IoT protocol restart

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
- iotdb-core/node-commons/src/assembly/resources/conf/iotdb-common.properties
Set default compaction validation level to RESOURCE_ONLY
> Set default compaction validation level to RESOURCE_ONLY

- iotdb-connector/grafana-plugin/backend-compile.sh
[rel/1.2] fixed grafana-plugin compilation failure
> [rel/1.2] fixed grafana-plugin compilation failure

- iotdb-connector/grafana-plugin/backend-compile.sh
fixed grafana-plugin compilation failure
> fixed grafana-plugin compilation failure

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/AbstractOperator.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/AlignedSeriesScanOperator.java
- iotdb-core/tsfile/src/main/java/org/apache/iotdb/tsfile/read/common/block/TsBlockBuilder.java
- iotdb-core/tsfile/src/main/java/org/apache/iotdb/tsfile/read/common/block/column/Int32ArrayColumnEncoder.java
- iotdb-core/tsfile/src/main/java/org/apache/iotdb/tsfile/read/common/block/column/TsBlockSerde.java
- iotdb-core/tsfile/src/main/java/org/apache/iotdb/tsfile/read/reader/page/AlignedPageReader.java
- iotdb-core/tsfile/src/main/java/org/apache/iotdb/tsfile/read/reader/page/ValuePageReader.java
- iotdb-core/tsfile/src/main/java/org/apache/iotdb/tsfile/read/reader/series/PaginationController.java
cp from https://github.com/apache/iotdb/pull/11068
> [IOTDB-6141] Optimize the large time range raw query performance

- integration-test/src/test/java/org/apache/iotdb/db/it/groupby/IoTDBGroupByNaturalMonthIT.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/parser/ASTVisitor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/utils/DateTimeUtils.java
github issue https://github.com/apache/iotdb/issues/11133
doc https://apache-iotdb.feishu.cn/docx/TNBPd8nZUoDsJMxjdOncOUkcnVA
previous discuss https://github.com/apache/iotdb/pull/11309
> [IOTDB-6191] Fix group by year

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/payload/evolvable/request/PipeTransferTabletRawReq.java
> Pipe: fix all tablets become non-aligned when using batch mode

- integration-test/src/test/java/org/apache/iotdb/db/it/auth/IoTDBSystemPermissionIT.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/auth/AuthorityChecker.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/statement/sys/ShowVersionStatement.java
Previously we only permit root to do `show version`, but we should let any user can show version
> Make show version can be used by anyone

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/process/TopKOperator.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/OperatorTreeGenerator.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/plan/plan/PipelineBuilderTest.java
Read batch operators in next method of TopKOperator
> Add batch operators loading in the next method of TopKOperator

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/service/metrics/file/ModsFileMetrics.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/service/metrics/file/TsFileMetrics.java
Rename sequence to seq and unsequence to unseq
> Fix tag value in file metrics

- iotdb-client/cli/src/assembly/resources/sbin/start-cli.bat
- iotdb-client/cli/src/assembly/resources/sbin/start-cli.sh
linux-before:
linux-now:
windows-before:
windows-now:
> fix(start-cli):add  add-opens script

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/common/MPPQueryContext.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/distribution/DistributionPlanContext.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/distribution/ExchangeNodeAdder.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/distribution/NodeGroupContext.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/distribution/SourceRewriter.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/plan/plan/distribution/DistributionPlannerCycleTest.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/plan/plan/distribution/Util2.java
see descriptions in https://issues.apache.org/jira/browse/IOTDB-6201
> [IOTDB-6201] Fix possible query timeout error in TimeJoinNode and possible query cycle in last query.

- docker/src/main/DockerCompose/docker-compose-cluster-1c2d.yml
- docker/src/main/DockerCompose/docker-compose-host-3c3d.yml
- docker/src/main/DockerCompose/docker-compose-standalone.yml
- docker/src/main/Dockerfile-1c1d
- integration-test/src/main/java/org/apache/iotdb/it/env/cluster/env/AbstractEnv.java
- integration-test/src/main/java/org/apache/iotdb/it/env/cluster/node/ConfigNodeWrapper.java
- integration-test/src/main/java/org/apache/iotdb/it/env/cluster/node/DataNodeWrapper.java
- iotdb-core/confignode/src/assembly/resources/conf/iotdb-confignode.properties
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/conf/ConfigNodeConfig.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/conf/ConfigNodeDescriptor.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/conf/ConfigNodeRemoveCheck.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/conf/ConfigNodeStartupCheck.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/node/ClusterNodeStartUtils.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/service/ConfigNode.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/service/ConfigNodeShutdownHook.java
- iotdb-core/confignode/src/test/resources/confignode1conf/iotdb-confignode.properties
- iotdb-core/confignode/src/test/resources/confignode2conf/iotdb-confignode.properties
- iotdb-core/confignode/src/test/resources/confignode3conf/iotdb-confignode.properties
- iotdb-core/datanode/src/assembly/resources/conf/iotdb-datanode.properties
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/service/DataNode.java
- iotdb-core/datanode/src/test/resources/datanode1conf/iotdb-datanode.properties
- iotdb-core/datanode/src/test/resources/datanode2conf/iotdb-datanode.properties
- iotdb-core/datanode/src/test/resources/datanode3conf/iotdb-datanode.properties
- iotdb-core/datanode/src/test/resources/iotdb-datanode.properties
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/conf/IoTDBConstant.java
https://issues.apache.org/jira/browse/IOTDB-6194
> [IOTDB-6194] Remove _list from parameter target_config_node_list

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/exchange/MPPDataExchangeService.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/service/DataNodeInternalRPCService.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/service/MLNodeRPCService.java
https://issues.apache.org/jira/browse/IOTDB-6203
> [IOTDB-6203] Remove rpc_thrift_compression_enable hard code

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/event/common/heartbeat/PipeHeartbeatEvent.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/extractor/realtime/PipeRealtimeDataRegionHybridExtractor.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/conf/CommonConfig.java
> Pipe: fine tune hybrid mode by removing tooManyWALPinned judgement and increasing pipeMaxAllowedPendingTsFileEpochPerDataRegion to 2

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/agent/runtime/PipeRuntimeAgent.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/plan/node/load/LoadSingleTsFileNode.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/tsfile/TsFileResource.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/wal/recover/file/AbstractTsFileRecoverPerformer.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/wal/recover/file/UnsealedTsFileRecoverPerformer.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/utils/FileLoaderUtils.java
> Pipe: assign progress index for sealed tsfile recovery

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/config/constant/PipeExtractorConstant.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/extractor/historical/PipeHistoricalDataRegionTsFileExtractor.java
> Pipe: support parameter extractor.history.sloppy-time-range to improve historical data processing efficiency

- README.md
- README_ZH.md
Fix the error in building the cli described in README.
> docs: update build cli documentation in README

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/tsfile/TsFileResource.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/compaction/ReadPointCompactionPerformerTest.java
We need to add this check to avoid potential inifinite loop.
> check startTime and endTime in isSatisfied of TsFileResource

- library-udf/src/assembly/tools/register-UDF.bat
- library-udf/src/assembly/tools/register-UDF.sh
Same as the title. 
We create `UDTFOutlier` function and add new machine learning function `UDTFAR` on our master branch to shell script and CMD script.
<hr>
This PR has:
> Add missing UDF registration commands in scripts

- integration-test/src/test/java/org/apache/iotdb/confignode/it/cluster/IoTDBClusterRestartIT.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/service/DataNode.java
https://issues.apache.org/jira/browse/IOTDB-6211
> [IOTDB-6211] Restore cluste registered ConfigNodes from system.properties file when restart DataNode

- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/client/async/handlers/heartbeat/ConfigNodeHeartbeatHandler.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/client/async/handlers/heartbeat/DataNodeHeartbeatHandler.java
https://issues.apache.org/jira/browse/IOTDB-6208
> [IOTDB-6208] Node error detection through broken thrift pipe

- iotdb-api/pipe-api/src/main/java/org/apache/iotdb/pipe/api/customizer/parameter/PipeParameters.java
- iotdb-core/antlr/src/main/antlr4/org/apache/iotdb/db/qp/sql/IdentifierParser.g4
- iotdb-core/antlr/src/main/antlr4/org/apache/iotdb/db/qp/sql/IoTDBSqlParser.g4
- iotdb-core/antlr/src/main/antlr4/org/apache/iotdb/db/qp/sql/SqlLexer.g4
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/persistence/pipe/PipePluginInfo.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/agent/plugin/PipePluginAgent.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/config/constant/PipeConnectorConstant.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/config/constant/PipeExtractorConstant.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/payload/evolvable/builder/PipeTransferBatchReqBuilder.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/protocol/IoTDBConnector.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/protocol/airgap/IoTDBAirGapConnector.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/protocol/legacy/IoTDBLegacyPipeConnector.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/protocol/opcua/OpcUaConnector.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/protocol/websocket/WebSocketConnector.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/extractor/IoTDBDataRegionExtractor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/extractor/historical/PipeHistoricalDataRegionTsFileExtractor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/extractor/realtime/PipeRealtimeDataRegionExtractor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/task/stage/PipeTaskExtractorStage.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/task/subtask/connector/PipeConnectorSubtaskManager.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/common/header/ColumnHeaderConstant.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/LoadTsfileAnalyzer.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/pipe/extractor/IoTDBDataRegionExtractorTest.java
> Pipe: rename extractor -> source, connector -> sink, sloppy-time-range -> loose-range

- iotdb-core/datanode/pom.xml
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/rest/filter/AuthorizationFilter.java
- iotdb-protocol/openapi/pom.xml
- pom.xml
> fixed rest start fail

- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/persistence/schema/mnode/factory/ConfigMNodeFactory.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/impl/SchemaRegionPBTreeImpl.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/mtree/impl/mem/MTreeBelowSGMemoryImpl.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/mtree/impl/mem/mnode/factory/MemMNodeFactory.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/mtree/impl/mem/snapshot/MemMTreeSnapshotUtil.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/mtree/impl/pbtree/MTreeBelowSGCachedImpl.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/mtree/impl/pbtree/mnode/container/ICachedMNodeContainer.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/mtree/impl/pbtree/mnode/factory/CacheMNodeFactory.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/mtree/impl/pbtree/schemafile/RecordUtils.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/conf/CommonConfig.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/schema/node/utils/IMNodeFactory.java
PBTree mode support logical view
> PBTree mode support logical view

- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/persistence/quota/QuotaInfo.java
more details can seen in https://apache-iotdb.feishu.cn/docx/L6XNd0HBbo57xFx1DQ0cjkNenhg
> Add fsync for QuotaInfo

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/plan/node/PlanGraphPrinter.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/plan/plan/node/PlanGraphPrinterTest.java
Example - 1:
Before fix:
After fix:
Example -2:
Before fix:
After fix:
> [IOTDB-6219] Fix the display problem of explain that the print result is not aligned

- iotdb-client/cli/src/main/java/org/apache/iotdb/cli/AbstractCli.java
- iotdb-client/cli/src/main/java/org/apache/iotdb/cli/Cli.java
- iotdb-client/jdbc/src/main/java/org/apache/iotdb/jdbc/Config.java
- iotdb-client/jdbc/src/main/java/org/apache/iotdb/jdbc/IoTDBConnection.java
- iotdb-client/jdbc/src/main/java/org/apache/iotdb/jdbc/IoTDBConnectionParams.java
- iotdb-client/jdbc/src/main/java/org/apache/iotdb/jdbc/Utils.java
- iotdb-client/service-rpc/src/main/java/org/apache/iotdb/rpc/RpcTransportFactory.java
- iotdb-client/session/src/main/java/org/apache/iotdb/session/Session.java
- iotdb-client/session/src/main/java/org/apache/iotdb/session/SessionConnection.java
- iotdb-client/session/src/main/java/org/apache/iotdb/session/pool/SessionPool.java
- iotdb-core/datanode/src/assembly/resources/conf/iotdb-datanode.properties
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/conf/rest/IoTDBRestServiceConfig.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/service/RPCService.java
- iotdb-core/node-commons/src/assembly/resources/conf/iotdb-common.properties
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/service/AbstractThriftServiceThread.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/service/ThriftServiceThread.java
datanode's dn_rpc_port supports ssl
> datanode's dn_rpc_port supports ssl

- iotdb-api/pipe-api/src/main/java/org/apache/iotdb/pipe/api/PipeSink.java
- iotdb-api/pipe-api/src/main/java/org/apache/iotdb/pipe/api/PipeSource.java
- iotdb-api/pipe-api/src/main/java/org/apache/iotdb/pipe/api/customizer/configuration/PipeSinkRuntimeConfiguration.java
- iotdb-api/pipe-api/src/main/java/org/apache/iotdb/pipe/api/customizer/configuration/PipeSourceRuntimeConfiguration.java
- iotdb-api/pipe-api/src/main/java/org/apache/iotdb/pipe/api/exception/PipeSinkException.java
- iotdb-core/antlr/src/main/antlr4/org/apache/iotdb/db/qp/sql/IoTDBSqlParser.g4
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/common/header/ColumnHeaderConstant.java
> Pipe: rename PipeExtractor -> PipeSource, PipeConnector -> PipeSink in pipe-api, antlr

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java
- iotdb-core/node-commons/src/assembly/resources/conf/iotdb-common.properties
https://issues.apache.org/jira/browse/IOTDB-6218
> [IOTDB-6218] Rename storage_query_schema_consensus_free_memory_proportion to datanode_memory_proportion

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/task/stage/PipeTaskExtractorStage.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/task/subtask/connector/PipeConnectorSubtaskManager.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/plugin/builtin/BuiltinPipePlugin.java
> Pipe: rename plugins *-extractor -> *-source, *-connector -> *-sink

- iotdb-core/confignode/src/assembly/resources/conf/confignode-env.bat
- iotdb-core/confignode/src/assembly/resources/conf/confignode-env.sh
- iotdb-core/datanode/src/assembly/resources/conf/datanode-env.bat
- iotdb-core/datanode/src/assembly/resources/conf/datanode-env.sh
1. MAX_CACHED_BUFFER_SIZE =  OFF_HEAP_MEMORY / IO_THREADS_NUMBER
2. set IOTDB_ALLOW_HEAP_DUMP=true
> feat(env): set MAX_CACHED_BUFFER_SIZE equals OFF_HEAP_MEMORY / IO_THREADS_NUMBER

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/resource/memory/PipeMemoryManager.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/wal/utils/WALInsertNodeCache.java
> Pipe: remove unnecessary waiting operation for memory alloc calculation

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/event/common/heartbeat/PipeHeartbeatEvent.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/extractor/realtime/PipeRealtimeDataRegionHybridExtractor.java
> Pipe: add connector's pending tsfile event count to help isTsFileEventCountInQueueExceededLimit judgement when hybrid mode is enabled

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/schema/source/TimeSeriesSchemaSource.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/mtree/impl/pbtree/CachedMTreeStore.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/mtree/impl/pbtree/StampedWriterPreferredLock.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/mtree/impl/pbtree/schemafile/SchemaFile.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/mtree/impl/pbtree/schemafile/pagemgr/PageManager.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/metadata/mtree/lock/StampedWriterPreferredLockTest.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/metadata/mtree/schemafile/SchemaFileLogTest.java
This pr cherry picks the following content:
1. lock bug fix from https://github.com/apache/iotdb/pull/11453
2. schema file double write improvement from https://github.com/apache/iotdb/pull/11467
> [To rel/1.2] Fix lock bug and improve schema file write policy in PBTree

- .github/workflows/pipe-it-2cluster.yml
Document reference: https://docs.github.com/zh/actions/using-workflows/about-workflows#using-labels-to-route-workflows
<hr>
This PR has:
<hr>
> Pipe: Enable github machines instead of self-hosted machines to run pipe IT

- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/consensus/request/write/region/CreateRegionGroupsPlan.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/load/balancer/RegionBalancer.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/persistence/partition/DatabasePartitionTable.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/persistence/partition/PartitionInfo.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/statemachine/CreateRegionGroupsProcedure.java
- iotdb-core/confignode/src/test/java/org/apache/iotdb/confignode/consensus/request/ConfigPhysicalPlanSerDeTest.java
- iotdb-core/confignode/src/test/java/org/apache/iotdb/confignode/persistence/PartitionInfoTest.java
- iotdb-core/confignode/src/test/java/org/apache/iotdb/confignode/procedure/impl/CreateRegionGroupsProcedureTest.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/audit/AuditLogger.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/parser/ASTVisitor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/plan/parameter/SeriesScanOptions.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/DataRegion.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/flush/MemTableFlushTask.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/tsfile/TsFileResource.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/utils/DateTimeUtils.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/conf/CommonConfig.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/utils/CommonDateTimeUtils.java
**Jira:** https://issues.apache.org/jira/browse/IOTDB-6239
**Bug fix test:** the create time is correct in this PR.
**Compatibility test:** the ConfigNode is still compatible with earlier version, through the create time of Region can't be fixed to correct.
> [IOTDB-6239] Show regions display error create time

- distribution/src/assembly/library-udf.xml
- Move `ext/udf/library-udf.jar` to `library-udf.jar`;
- Move two register files to root directory;
- Put `LICENSE` and `NOTICE` to `licenses` directory;
- Delete all README files and `RELEASE_NOTES.md`.
<hr>
This PR has:
> Simplify library-udf packaging result

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/exception/LoadReadOnlyException.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/LoadTsfileAnalyzer.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/scheduler/load/LoadTsFileScheduler.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/StorageEngine.java
Previously the Load command would ignore the system READ_ONLY mode, so I add some checks in Analysis, Dispatch and Writing Stage when loading tsfile.
> [IOTDB-6241] Load: Check System mode in Analysis, Dispatch and Writing Stage

- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/consensus/pipe/ConfigPipeListeningPlan.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/consensus/pipe/ConfigPipeListeningQueue.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/consensus/request/write/pipe/task/CreatePipePlanV2.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/consensus/request/write/pipe/task/DropPipePlanV2.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/consensus/request/write/pipe/task/SetPipeStatusPlanV2.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/consensus/response/pipe/task/PipeTableResp.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/pipe/runtime/PipeHeartbeatParser.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/persistence/pipe/PipeTaskInfo.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/pipe/task/CreatePipeProcedureV2.java
- iotdb-core/confignode/src/test/java/org/apache/iotdb/confignode/consensus/request/ConfigPhysicalPlanSerDeTest.java
- iotdb-core/confignode/src/test/java/org/apache/iotdb/confignode/consensus/response/pipe/PipeTableRespTest.java
- iotdb-core/confignode/src/test/java/org/apache/iotdb/confignode/persistence/PipeInfoTest.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/agent/task/PipeTaskAgent.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/config/constant/PipeConnectorConstant.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/protocol/legacy/IoTDBLegacyPipeConnector.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/protocol/thrift/async/IoTDBThriftAsyncConnector.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/protocol/thrift/sync/IoTDBThriftSyncConnector.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/protocol/thrift/sync/IoTDBThriftSyncConnectorClient.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/task/PipeBuilder.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/consensus/index/ProgressIndexType.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/consensus/index/impl/SchemaProgressIndex.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/schema/LinkedListMessageQueue.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/schema/PipeLinkedListQueue.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/task/meta/PipeRuntimeMeta.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/task/meta/PipeRuntimeMetaVersion.java
- iotdb-core/node-commons/src/test/java/org/apache/iotdb/commons/pipe/PipeMetaDeSerTest.java
This PR implemented the PipeMeta change and the related parts of the schema synchronization pipe. It refactors some of the logic of pipe plans as well to solve the maven problem.
<hr>
This PR has:
<hr>
>  Pipe Schema: Updated PipeMeta to record pipe schema progress on configNode

- integration-test/README.md
> Update ReadMe in IT module

- .github/workflows/pipe-it-2cluster.yml
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/conf/CommonConfig.java
> Pipe IT: adjust -DintegrationTest.forkCount & -DDataNodeMaxHeapSize in pipe-it-2cluster.yml to provide more stable env

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/service/metrics/CompactionMetrics.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/DataRegion.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/task/AbstractCompactionTask.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/task/CrossSpaceCompactionTask.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/task/InnerSpaceCompactionTask.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/task/InsertionCrossSpaceCompactionTask.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/schedule/CompactionScheduleSummary.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/schedule/CompactionScheduler.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/schedule/CompactionWorker.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/selector/impl/RewriteCrossSpaceCompactionSelector.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/rescon/memory/SystemInfo.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/compaction/inner/InnerCompactionSchedulerTest.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/service/metric/enums/Metric.java
Add these compaction metrics:
1. memory usage of one compaction task
2. memory distribution of compaction task type
3. selected file num of compaction task
4. selected compaction task num
5. compaction selection time cost
Add these compaction logs:
1. memory usage of InnerSpaceCompactionTask
2. selected compaction task num after schedule compaction
> Add compaction logs and metrics

- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/ratis/ApplicationStateMachineProxy.java
- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/ratis/RatisConsensus.java
- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/ratis/utils/Retriable.java
- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/ratis/utils/RetryPolicy.java
- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/ratis/utils/Utils.java
- iotdb-core/consensus/src/test/java/org/apache/iotdb/consensus/ratis/RecoverReadTest.java
See https://issues.apache.org/jira/browse/IOTDB-6227.
Add retry mechanisms for RatisConsensus::read.
Also unify all retry usages.
> [IOTDB-6227] Add retry for RatisConsensus read

- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/schema/DeleteDatabaseProcedure.java
add database name when set exception
> Fix exception add database name message

- iotdb-core/datanode/src/assembly/resources/conf/iotdb-datanode.properties
1. add e.g. for ssl key_store_path
2. remove ""
> fix(conf): add e.g. for ssl

- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/iot/IoTConsensusServerImpl.java
Description：
- The searchIndex for some regions may be smaller than the safelyDeletedSearchIndex when the node is restarted, which means that the data of the current node is not flushed by the wal, but has been synchronized to other nodes. At this point, different replicas have been inconsistent and cannot be automatically recovered. 
Solution：
- To prevent subsequent logs from marking smaller searchIndex and exacerbating the inconsistency, we manually set the searchIndex to safelyDeletedSearchIndex here to reduce the impact of this problem in the future
> Check and update searchIndex when restarting dataNode if necessary

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/metric/PipeResourceMetrics.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/resource/memory/PipeMemoryManager.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/service/metric/enums/Metric.java
As title, considering the potential dynamic changes in the total memory size with Pipe module in the future, we are collecting raw data here to enhance the flexibility of the Grafana dashboard display.
<hr>
This PR has:
<hr>
> Pipe: collect total memory size with Pipe module instead of memory usage

- iotdb-core/confignode/src/assembly/resources/conf/iotdb-confignode.properties
- iotdb-core/confignode/src/test/resources/confignode1conf/iotdb-confignode.properties
- iotdb-core/confignode/src/test/resources/confignode2conf/iotdb-confignode.properties
- iotdb-core/confignode/src/test/resources/confignode3conf/iotdb-confignode.properties
- iotdb-core/datanode/src/assembly/resources/conf/iotdb-datanode.properties
- iotdb-core/datanode/src/test/resources/datanode1conf/iotdb-datanode.properties
- iotdb-core/datanode/src/test/resources/datanode2conf/iotdb-datanode.properties
- iotdb-core/datanode/src/test/resources/datanode3conf/iotdb-datanode.properties
- iotdb-core/metrics/ReadMe.md
- iotdb-core/metrics/interface/src/test/java/org/apache/iotdb/metrics/config/MetricConfigTest.java
As title, remove duplicate description related to `metric_frame_type`
> Remove duplicate description of metric module

- iotdb-core/confignode/src/assembly/resources/conf/iotdb-confignode.properties
- iotdb-core/datanode/src/assembly/resources/conf/iotdb-datanode.properties
- iotdb-core/metrics/interface/src/main/java/org/apache/iotdb/metrics/metricsets/disk/DoNothingDiskMetricsManager.java
- iotdb-core/metrics/interface/src/main/java/org/apache/iotdb/metrics/metricsets/disk/IDiskMetricsManager.java
- iotdb-core/metrics/interface/src/main/java/org/apache/iotdb/metrics/metricsets/net/DoNothingNetMetricManager.java
- iotdb-core/metrics/interface/src/main/java/org/apache/iotdb/metrics/metricsets/net/INetMetricManager.java
- iotdb-core/metrics/interface/src/main/java/org/apache/iotdb/metrics/metricsets/system/SystemMetrics.java
> Add OFF level

- integration-test/src/test/java/org/apache/iotdb/pipe/it/IoTDBPipeClusterIT.java
- integration-test/src/test/java/org/apache/iotdb/pipe/it/IoTDBPipeSwitchStatusIT.java
- integration-test/src/test/java/org/apache/iotdb/pipe/it/extractor/IoTDBPipeExtractorIT.java
Complement to https://github.com/apache/iotdb/pull/11527/files
<hr>
This PR has:
<hr>
> Pipe IT: Enable IoTDBPipeExtractorIT & IoTDBPipeSwitchStatusIT to tolerate failures caused by resource shortage

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/DataRegion.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/schedule/CompactionScheduleSummary.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/service/metric/enums/Metric.java
1. Fix compaction metric name
2. skip log when no compaction task is submitted
> Fix compaction logs and metrics

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/common/schematree/ClusterSchemaTree.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/common/schematree/ISchemaTree.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/common/schematree/visitor/SchemaTreeDeviceUsingTemplateVisitor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/common/schematree/visitor/SchemaTreeDeviceVisitor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/common/schematree/visitor/SchemaTreeVisitorFactory.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/common/schematree/ClusterSchemaTreeTest.java
ISchemaTree add interface getDeviceUsingTemplate
> ISchemaTree add interface getDeviceUsingTemplate

- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/node/RemoveConfigNodeProcedure.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/schema/AlterLogicalViewProcedure.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/schema/DeleteLogicalViewProcedure.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/schema/SetTemplateProcedure.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/trigger/CreateTriggerProcedure.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/trigger/DropTriggerProcedure.java
Complete the log information for Some Procedure
> Complete the log information for Some Procedure

- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/iot/service/IoTConsensusRPCServiceProcessor.java
- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/ratis/RatisConsensus.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/payload/evolvable/request/PipeTransferTabletRawReq.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/receiver/legacy/IoTDBLegacyPipeReceiverAgent.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/receiver/thrift/IoTDBThriftReceiverV1.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/trigger/service/TriggerInformationUpdater.java
> Fix some code smells

- integration-test/src/main/java/org/apache/iotdb/it/utils/TsFileGenerator.java
- integration-test/src/test/java/org/apache/iotdb/db/it/IOTDBLoadTsFileIT.java
- iotdb-client/jdbc/src/main/java/org/apache/iotdb/jdbc/AbstractIoTDBJDBCResultSet.java
- iotdb-client/jdbc/src/main/java/org/apache/iotdb/jdbc/IoTDBDataSource.java
> Fix some code smells for integration test

- iotdb-client/jdbc/src/main/java/org/apache/iotdb/jdbc/IoTDBJDBCResultSet.java
- iotdb-client/jdbc/src/main/java/org/apache/iotdb/jdbc/StringUtils.java
> Fix some code smells of JDBC module

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/LoadTsfileAnalyzer.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/plan/node/load/LoadSingleTsFileNode.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/plan/node/load/LoadTsFilePieceNode.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/scheduler/load/LoadTsFileDispatcherImpl.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/mtree/impl/pbtree/CachedMTreeStore.java
Fix Some Code Smells of DataNode Module
> Fix Some Code Smells of DataNode Module

- iotdb-client/session/src/main/java/org/apache/iotdb/session/pool/SessionPool.java
Fix Some Code Smells of Client Session Module
> Fix Some Code Smells of Client Session Module

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/exchange/MPPDataExchangeManager.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/exchange/source/LocalSourceHandle.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/exchange/source/SourceHandle.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/AbstractOperator.java
> Add isDebugEnable judgement for each LOGGER.DEBUG

- integration-test/src/test/java/org/apache/iotdb/db/it/aligned/IoTDBAlignedLimitPushDownIT.java
- integration-test/src/test/java/org/apache/iotdb/db/it/aligned/IoTDBAlignedOffsetLimitPushDownIT.java
- iotdb-core/tsfile/src/main/java/org/apache/iotdb/tsfile/read/reader/page/AlignedPageReader.java
- iotdb-core/tsfile/src/main/java/org/apache/iotdb/tsfile/read/reader/page/ValuePageReader.java
more details can be seen in https://issues.apache.org/jira/browse/IOTDB-6254
> [IOTDB-6254] Fix limit push down bug in aligned sensor

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/DataRegion.java
Please refer to https://issues.apache.org/jira/browse/IOTDB-6256
> [IOTDB-6256] Fix FLUSH deadlock

- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/auth/authorizer/BasicAuthorizer.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/client/ClientManager.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/utils/FileUtils.java
Fix Some Code Smells of Node Commons Module
> Fix Some Code Smells of Node Commons Module

- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/config/RatisConfig.java
- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/exception/RatisReadUnavailableException.java
- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/ratis/ApplicationStateMachineProxy.java
- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/ratis/RatisConsensus.java
- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/ratis/utils/Utils.java
- iotdb-core/consensus/src/test/java/org/apache/iotdb/consensus/ratis/RecoverReadTest.java
- iotdb-core/consensus/src/test/java/org/apache/iotdb/consensus/ratis/TestUtils.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/consensus/SchemaRegionConsensusImpl.java
See https://issues.apache.org/jira/browse/IOTDB-6251
See experiments in https://apache-iotdb.feishu.cn/docx/NJ7vdd9Kfo3nx2xwalZcqBeunr8
> [IOTDB-6251] Make read in SchemaRegion linearizable by default

- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/client/async/AsyncDataNodeHeartbeatClientPool.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/client/async/handlers/heartbeat/DataNodeHeartbeatHandler.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/load/cache/node/NodeHeartbeatSample.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/load/cache/node/NodeStatistics.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/load/service/HeartbeatService.java
- iotdb-core/confignode/src/test/java/org/apache/iotdb/confignode/manager/load/balancer/router/priority/GreedyPriorityTest.java
- iotdb-core/confignode/src/test/java/org/apache/iotdb/confignode/manager/load/balancer/router/priority/LeaderPriorityBalancerTest.java
- iotdb-core/confignode/src/test/java/org/apache/iotdb/confignode/manager/load/cache/NodeCacheTest.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/agent/task/PipeTaskAgent.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/thrift/impl/DataNodeInternalRPCServiceImpl.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/SchemaEngine.java
- iotdb-protocol/thrift-datanode/src/main/thrift/datanode.thrift
Now we have TConfigNodeHeartbeat, so old THeartbeat's name also needs changing.
> Rename THeartbeat to TDataNodeHeart

- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/node/NodeManager.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/partition/PartitionManager.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/partition/PartitionMetrics.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/persistence/node/NodeInfo.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/persistence/partition/DatabasePartitionTable.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/persistence/partition/PartitionInfo.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/service/metric/enums/Metric.java
https://issues.apache.org/jira/browse/IOTDB-6255
Also updated the Apache IoTDB ConfigNode Dashboard:
> [IOTDB-6255] Scatter width metric

- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/compaction/inner/InnerSpaceCompactionSelectorTest.java
Fixed the UT running time is too long
> Fix compaction selector ut running time is too long

- integration-test/src/test/java/org/apache/iotdb/db/it/auth/IoTDBAuthIT.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/DataRegion.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/modification/io/LocalTextModificationAccessor.java
In this PR:
1. add an IT to check whether role/user can be created with "head"/"tail".
2. remove some useless comment at code.
> auth.add IT for create role/user with identifier.

- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/metadata/schemaRegion/SchemaStatisticsTest.java
Temporarily ignore testPBTreeMemoryStatistics
> Temporarily ignore testPBTreeMemoryStatistics

- integration-test/src/main/java/org/apache/iotdb/itbase/env/BaseEnv.java
- integration-test/src/test/java/org/apache/iotdb/db/it/metric/IoTDBMetricIT.java
> Add format check for Prometheus Reporter Check

- integration-test/src/test/java/org/apache/iotdb/confignode/it/partition/IoTDBPartitionCreationIT.java
https://issues.apache.org/jira/browse/IOTDB-6263
> [IOTDB-6263] Enhance IoTDBPartitionCreationIT

- iotdb-core/datanode/src/assembly/resources/conf/iotdb-datanode.properties
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/conf/rest/IoTDBRestServiceConfig.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/conf/rest/IoTDBRestServiceDescriptor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/rest/v1/handler/RequestValidationHandler.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/rest/v1/handler/StatementConstructionHandler.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/rest/v1/impl/RestApiServiceImpl.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/rest/v2/impl/RestApiServiceImpl.java
- iotdb-protocol/openapi/src/main/openapi3/iotdb_rest_v1.yaml
Rest is compatible with previous version configurations and fixed insertRecords error prompt returning null issue and rest v1 remove insertRecords
> Rest service code optimization and fixed insertRecords error prompt returning null issue

- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/iot/IoTConsensus.java
- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/iot/IoTConsensusServerImpl.java
- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/iot/client/DispatchLogHandler.java
- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/iot/logdispatcher/IndexController.java
- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/iot/logdispatcher/LogDispatcher.java
- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/iot/logdispatcher/SyncStatus.java
- iotdb-core/consensus/src/test/java/org/apache/iotdb/consensus/iot/logdispatcher/IndexControllerTest.java
- iotdb-core/consensus/src/test/java/org/apache/iotdb/consensus/iot/logdispatcher/SyncStatusTest.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/concurrent/ThreadName.java
see [jira](https://issues.apache.org/jira/browse/IOTDB-6266)
> [IOTDB-6266] Add the ability to flush syncIndex and update reader periodically for IoTConsensus

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/snapshot/SnapshotTaker.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/snapshot/IoTDBSnapshotTest.java
- iotdb-core/datanode/src/test/resources/logback-test.xml
> Fix snapshot UT

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/rest/v2/handler/RequestValidationHandler.java
Featrue add insertRecords and insertTablets to the rest v2 service for data type verification
> Featrue add insertRecords and insertTablets to the rest v2 service for data type verification

- iotdb-client/cli/pom.xml
- pom.xml
add net.java.dev.jna for windows cli
> fix(cli): add jna for windows

- integration-test/src/main/java/org/apache/iotdb/it/env/cluster/ClusterConstant.java
- integration-test/src/main/java/org/apache/iotdb/it/env/cluster/config/MppDataNodeConfig.java
- integration-test/src/main/java/org/apache/iotdb/it/env/cluster/node/DataNodeWrapper.java
- integration-test/src/main/java/org/apache/iotdb/it/env/remote/config/RemoteDataNodeConfig.java
- integration-test/src/main/java/org/apache/iotdb/itbase/env/DataNodeConfig.java
- integration-test/src/test/java/org/apache/iotdb/db/it/GrafanaApiServiceIT.java
- integration-test/src/test/java/org/apache/iotdb/db/it/IoTDBRestServiceIT.java
> IT: enable REST service when needed to fix IT

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
- iotdb-core/node-commons/src/assembly/resources/conf/iotdb-common.properties
change default config value of inner_compaction_task_selection_mods_file_threshold from **50M** to **10M**
> change default config value of inner_compaction_task_selection_mods_file_threshold

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/mtree/impl/pbtree/CachedMTreeStore.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/mtree/impl/pbtree/flush/PBTreeFlushExecutor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/mtree/impl/pbtree/flush/Scheduler.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/concurrent/ThreadName.java
* Ensure PBTree DROP and FLUSH concurrently.
* Rename worker pool.
* Encapsulate limit logic into PBTreeFlushExecutor
> Ensure PBTree DROP and FLUSH concurrently

- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/DataRegionTest.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/compaction/CompactionSchedulerTest.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/compaction/CompactionSchedulerWithFastPerformerTest.java
Fix UT testLargeFileInLowerLevel and DataRegionTest.testMerge
> Fix UT testLargeFileInLowerLevel of CompactionSchedulerTestWithFastCompactionPerformer

- integration-test/src/test/java/org/apache/iotdb/db/it/cq/IoTDBCQExecIT.java
- integration-test/src/test/java/org/apache/iotdb/db/it/cq/IoTDBCQExecInNsIT.java
- integration-test/src/test/java/org/apache/iotdb/db/it/cq/IoTDBCQExecInUsIT.java
1. add if-block before check the CQ result, if after we succeed to create the CQ, the time has already been larger than the expected execution time, it means that there will be some time range won't be queried, in such case, we just return.
2. We change wait time from 5s to 10s to make sure that CQ has already finished.
3. Add a dummy insert before actual data being inserted, just for initializing data region firstly which is time-consuming.
> Try to fix CQ IT

- integration-test/src/test/java/org/apache/iotdb/confignode/it/cluster/IoTDBClusterRestartIT.java
Add ConfigNode-leader connection check between the restart process of ConfigNodes and DataNodes.
> Enhance IoTDBClusterRestartIT

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/process/join/InnerTimeJoinOperator.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/process/join/LeftOuterTimeJoinOperator.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/process/join/RowBasedTimeJoinOperator.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/process/join/merge/AscTimeComparator.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/process/join/merge/DescTimeComparator.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/process/join/merge/TimeComparator.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/execution/operator/process/join/InnerTimeJoinOperatorTest.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/execution/operator/process/join/LeftOuterTimeJoinOperatorTest.java
Add LeftOuterJoinOperator and InnerTimeJoinOperator for ValueFilter Push Down according to the docs https://apache-iotdb.feishu.cn/docx/HCEqdNfdtoW6B1xlpjOcRMwsnce
> [ValueFilter Push Down] Add LeftOuterJoinOperator and InnerTimeJoinOperator for ValueFilter Push Down

- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/ratis/RatisConsensus.java
After https://github.com/apache/ratis/pull/807 is introduced, now we can transfer leadership between nodes with same priorities. 
In this PR, I refactored the transferLeader implementation, remove the step where we first need to change the priority.
It brings a new benefit: since the priority is not changed, the original leader will not step down. If the transfership fails, the original leader can still be the leader and not affect the normal operations.
> Ratis：transfer leader improvement

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/rest/v2/handler/QueryDataSetHandler.java
- iotdb-protocol/openapi/src/main/openapi3/iotdb_rest_v2.yaml
rest v2 query add return  data type
> rest v2 query add return  data type

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/mtree/impl/pbtree/schemafile/pagemgr/BTreePageManager.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/mtree/impl/pbtree/schemafile/pagemgr/PageManager.java
Fix NPE when retrive page from sorted buckets of cache with no lock control.
<hr>
This PR has:
<hr>
> PBTree: Fix conccurent control

- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/load/cache/LoadCache.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/statemachine/CreateRegionGroupsProcedure.java
https://issues.apache.org/jira/secure/RapidBoard.jspa?rapidView=492&view=detail&selectedIssue=IOTDB-6280&quickFilter=2189
The RegionGroup activation is now started simultaneously
> [IOTDB-6280] Parallel RegionGroup activation

- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/pipe/coordinator/PipeManager.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/pipe/receiver/IoTDBConfigReceiverAgent.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/pipe/receiver/IoTDBConfigReceiverV1.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/pipe/transfer/agent/PipeConfigNodeAgent.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/pipe/transfer/agent/receiver/PipeReceiverConfigNodeAgent.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/event/realtime/PipeRealtimeEvent.java
> Pipe Schema: fixed NPE problem

- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/node/ClusterNodeStartUtils.java
https://issues.apache.org/jira/browse/IOTDB-6282
> [IOTDB-6282] Remove DataNode RPC address conflict check

- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/load/cache/LoadCache.java
https://issues.apache.org/jira/browse/IOTDB-6283
> [IOTDB-6283] Adjust the leader election waiting time when create RegionGroup

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/protocol/thrift/IoTDBThriftClientManager.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/protocol/thrift/async/IoTDBThriftAsyncClientManager.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/protocol/thrift/async/IoTDBThriftAsyncConnector.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/protocol/thrift/async/handler/PipeTransferTabletInsertNodeEventHandler.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/protocol/thrift/async/handler/PipeTransferTabletInsertionEventHandler.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/protocol/thrift/async/handler/PipeTransferTabletRawEventHandler.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/protocol/thrift/sync/IoTDBThriftSyncClientManager.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/protocol/thrift/sync/IoTDBThriftSyncConnector.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/client/async/AsyncPipeDataTransferServiceClient.java
For more info, please see: https://github.com/apache/iotdb/pull/11706
> [IOTDB-6261] Pipe: support leader cache in iotdb-thrift-async-connector

- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/iot/IoTConsensusServerImpl.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/event/common/heartbeat/PipeHeartbeatEvent.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/resource/wal/PipeWALResourceManager.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/DataRegion.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/flush/CompressionRatio.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/flush/MemTableFlushTask.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/memtable/TsFileProcessor.java
- iotdb-core/tsfile/src/main/java/org/apache/iotdb/tsfile/write/writer/TsFileIOWriter.java
We analyze logs of iotdb in many scenarios, and we decide to change level of some logs and remove some useless logs, more details in: https://apache-iotdb.feishu.cn/docx/ACRUd32DPozuUTxK7MBcPWCBn0d
> Optimize log according to real scenarios

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/mtree/impl/pbtree/CachedMTreeStore.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/mtree/impl/pbtree/memory/ReleaseFlushMonitor.java
Fix wrong global read lock logic.
> PBTree: Fix unlock logic

- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/ProcedureManager.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/load/cache/LoadCache.java
https://issues.apache.org/jira/browse/IOTDB-6285
> [IOTDB-6285] Alter Procedure timeout

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/event/common/heartbeat/PipeHeartbeatEvent.java
Considering that the various stages of handling the pipe heartbeat event are **asynchronous**, such as the possibility of the assign timestamp being recorded while the publish timestamp has not been recorded, calculating `publishedToAssigned` may result in issues. This PR addresses these problems.
<hr>
This PR has:
<hr>
> Pipe: accurate recording of heartbeat event duration to improve observability

- iotdb-core/node-commons/src/assembly/resources/conf/iotdb-cluster.properties
- iotdb-core/node-commons/src/assembly/resources/sbin/clean-all.bat
- iotdb-core/node-commons/src/assembly/resources/sbin/clean-all.sh
- iotdb-core/node-commons/src/assembly/resources/sbin/clean-confignode.bat
- iotdb-core/node-commons/src/assembly/resources/sbin/clean-confignode.sh
- iotdb-core/node-commons/src/assembly/resources/sbin/clean-datanode.bat
- iotdb-core/node-commons/src/assembly/resources/sbin/clean-datanode.sh
- iotdb-core/node-commons/src/assembly/resources/sbin/start-all.sh
- iotdb-core/node-commons/src/assembly/resources/sbin/stop-all.sh
Add iotdb-cluster.properties, start-all.sh, stop-all.sh, clean-all.sh, clean-all.bat, clean-datanode.sh, clean-datanode.bat, and clea n-confignode.sh and clean-confignode.bat files
> Add the iotdb-cluster.properties configuration file and start stop cleanup script

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/AnalyzeVisitor.java
more details can be seen in https://jira.infra.timecho.com:8443/browse/TIMECHODB-523
> Fix timeout doesn't take effect in schema fetch bug

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/memtable/TsFileProcessor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/wal/node/WALNode.java
https://apache-iotdb.feishu.cn/docx/ACRUd32DPozuUTxK7MBcPWCBn0d
> Imporve some log printing of Storage engine

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/agent/task/PipeTaskDataNodeAgent.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/task/meta/PipeMeta.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/task/meta/PipeTaskMeta.java
> Pipe: reduce log when reporting pipe meta via heartbeat

- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/partition/PartitionManager.java
> Add error logs for NotEnoughDataNodeException and DatabaseNotExistsException

- iotdb-core/datanode/src/assembly/resources/conf/logback-datanode.xml
- iotdb-core/datanode/src/test/resources/datanode1conf/logback.xml
- iotdb-core/datanode/src/test/resources/datanode2conf/logback.xml
- iotdb-core/datanode/src/test/resources/datanode3conf/logback.xml
> Pipe: append logs generated by org.apache.iotdb.pipe.api.* and org.apache.iotdb.commons.pipe.* into PIPE appender

- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/ConfigManager.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/ProcedureManager.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/Procedure.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/ProcedureExecutor.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/ProcedureMetrics.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/statemachine/StateMachineProcedure.java
- iotdb-core/confignode/src/test/java/org/apache/iotdb/confignode/procedure/TestProcedureExecutor.java
- iotdb-core/confignode/src/test/java/org/apache/iotdb/confignode/procedure/entity/StuckProcedure.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/service/metric/enums/Metric.java
The execution status of the Procedure after submission is difficult to detect, and the execution time of the Procedure may be too long. So, we will enhance Procedure metrics in this pr.
We want to enhance Procedure metrics on three levels:
- Thread pool level:
- Total thread pool size
- Number of active threads
- Queue length
- Procedure level:
- Submmit Rate/Failed Rate Counter for different types of Procedures
- The completion time of different types of Procedures is P50/P99/AVG
- Log level: 
-  Do some Log optimization
> [IOTDB-6281] Enhance Procedure metrics

- integration-test/src/main/java/org/apache/iotdb/it/env/cluster/config/MppCommonConfig.java
- integration-test/src/test/java/org/apache/iotdb/confignode/it/cluster/IoTDBClusterNodeGetterIT.java
- integration-test/src/test/java/org/apache/iotdb/confignode/it/utils/ConfigNodeTestUtils.java
https://issues.apache.org/jira/browse/IOTDB-6288
> [IOTDB-6288] Alter default disk_space_warning_threshold in ClusterIT environment

- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/consensus/ConsensusManager.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/node/NodeManager.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/service/ConfigNode.java
https://issues.apache.org/jira/browse/IOTDB-6289
> [IOTDB-6289] Add leader election wait when start SeedConfigNode

- iotdb-client/cli/src/assembly/resources/tools/collection-info.bat
- iotdb-client/cli/src/assembly/resources/tools/collection-info.sh
> Feture collection iotdb info

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
- iotdb-core/node-commons/src/assembly/resources/conf/iotdb-common.properties
Set default config item 'enableInsertionCrossSpaceCompaction' to true
> Set default config item 'enableInsertionCrossSpaceCompaction' to true

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/service/metrics/WritingMetrics.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/StorageEngine.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/DataRegion.java
Some metic levels are not correct...
> Fix more writing metric errors

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/process/join/LeftOuterTimeJoinOperator.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/execution/operator/process/join/LeftOuterTimeJoinOperatorTest.java
> Fix NPE while right side finished

- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/persistence/partition/PartitionInfo.java
The minimal scatter width is 0
> Fix scatter width metric bug

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/service/metrics/WritingMetrics.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/wal/buffer/WALBuffer.java
Remove useless writing metric item "serializeOneWalInfoEntry"
> Remove useless writing metric item

- iotdb-client/cli/src/assembly/resources/tools/collect-info.bat
- iotdb-client/cli/src/assembly/resources/tools/collect-info.sh
fixed collection iotdb info unable to obtain information
> fixed collection iotdb info unable to obtain information

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/mtree/impl/pbtree/flush/Scheduler.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/mtree/impl/pbtree/memory/ReleaseFlushMonitor.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/metadata/schemaRegion/SchemaStatisticsTest.java
Add release logic to fix PBTree UT
> Extract common code and fix PBTree UT

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/agent/runtime/PipePeriodicalJobExecutor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/resource/tsfile/PipeTsFileResourceManager.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/resource/wal/PipeWALResourceManager.java
> Pipe: Fix ConcurrentModificationException occured by ttl check in PipeTsFileResourceManager

- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/ConfigManager.java
https://issues.apache.org/jira/browse/IOTDB-6290
New log:
> [IOTDB-6290] Simplify GetNodePathsPartition log

- iotdb-core/confignode/src/assembly/resources/sbin/daemon-confignode.sh
- iotdb-core/datanode/src/assembly/resources/sbin/daemon-datanode.sh
Improve some descriptions in https://github.com/apache/iotdb/pull/11629
> change the description of daemon-confignode/datanode 

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/load/LoadTsFileManager.java
> Load: Fix the warning of deleting a directory that already deleted

- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/persistence/AuthorInfo.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/auth/authorizer/BasicAuthorizer.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/auth/role/BasicRoleManager.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/auth/role/LocalFileRoleAccessor.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/auth/role/LocalFileRoleManager.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/auth/user/BasicUserManager.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/auth/user/LocalFileUserAccessor.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/auth/user/LocalFileUserManager.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/utils/FileUtils.java
In this pr:
1. add fysnc logic to fileutils.copy
2. remove init logic when boost up and reset after processing snapshot.
> Fix upgrade and add fysnc.

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/event/EnrichedEvent.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/event/common/tablet/PipeInsertNodeTabletInsertionEvent.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/event/common/tablet/PipeRawTabletInsertionEvent.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/event/common/tsfile/PipeTsFileInsertionEvent.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/task/subtask/connector/PipeConnectorSubtask.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/task/subtask/processor/PipeProcessorSubtask.java
> Pipe: print more info about event and task when error occurs in pipe subtasks

- iotdb-core/confignode/src/assembly/resources/sbin/daemon-confignode.sh
- iotdb-core/datanode/src/assembly/resources/sbin/daemon-datanode.sh
Daemon script change default choice from n to y
> Daemon script change default choice from n to y

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/DataRegion.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/task/InsertionCrossSpaceCompactionTask.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/schedule/CompactionScheduler.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/schedule/CompactionTaskManager.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/DataRegionTest.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/compaction/cross/InsertionCrossSpaceCompactionSelectorTest.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/compaction/cross/InsertionCrossSpaceCompactionTest.java
remove insert cross compaction config, make it belong to cross space compaction
> remove insert cross compaction config

- iotdb-core/tsfile/src/main/java/org/apache/iotdb/tsfile/read/reader/page/AlignedPageReader.java
more details can be seen in https://jira.infra.timecho.com:8443/browse/TIMECHODB-551, we need to dicard all null row in AlignedPageReader.
> Dicard all null row

- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/persistence/partition/DatabasePartitionTable.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/common/header/ColumnHeaderConstant.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/execution/config/metadata/ShowRegionTask.java
- iotdb-protocol/thrift-confignode/src/main/thrift/confignode.thrift
https://issues.apache.org/jira/browse/IOTDB-6292
> [IOTDB-6292] Add the internal address column in the result of show regions

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/task/InsertionCrossSpaceCompactionTask.java
Fix insertion compaction target file progress index
> Fix insertion compaction target file progress index

- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/config/RatisConfig.java
- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/ratis/RatisConsensus.java
- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/ratis/utils/Utils.java
- iotdb-core/consensus/src/test/java/org/apache/iotdb/consensus/ratis/RatisConsensusTest.java
- iotdb-core/consensus/src/test/java/org/apache/iotdb/consensus/ratis/RecoverReadTest.java
- pom.xml
Bump ratis version from 3.0.0 to 3.0.1
> [RatisConsensus] Bump ratis version from 3.0.0 to 3.0.1

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/extractor/IoTDBDataRegionExtractor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/extractor/historical/PipeHistoricalDataRegionTsFileExtractor.java
> Pipe: make PipeHistoricalDataRegionExtractor & PipeRealtimeDataRegionExtractor log info much clear with pipe name and region id added

- iotdb-core/node-commons/src/assembly/resources/conf/iotdb-common.properties
remove enable_insertion_cross_space_compaction from iotdb-common.properties
> remove enable_insertion_cross_space_compaction

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/distribution/SourceRewriter.java
RT
This problem is also exist in 1.3.0.
> Fix query result is empty in order by time align by device

- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/iot/logdispatcher/LogDispatcher.java
For a corrupted WAL file, the storage engine will skip the file on restart without affecting the restart. However, IoTConsensus will be trapped in wireless retry when it encounters a corrupted WAL file causing index jump, which will lead to synchronization deadlock.
> Fixed the issue that IoTConsensus synchronization is stuck when WAL file is corrupted

- iotdb-core/node-commons/src/assembly/resources/conf/iotdb-common.properties
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/conf/CommonConfig.java
> Pipe: decrease the default value of pipe_sink_selector_number to 4 for better performance

- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/client/async/handlers/heartbeat/DataNodeHeartbeatHandler.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/load/cache/LoadCache.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/load/cache/node/BaseNodeCache.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/load/cache/node/ConfigNodeHeartbeatCache.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/load/cache/node/DataNodeHeartbeatCache.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/load/cache/node/NodeHeartbeatSample.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/load/cache/node/NodeStatistics.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/load/cache/region/RegionCache.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/load/cache/region/RegionHeartbeatSample.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/load/service/HeartbeatService.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/env/ConfigNodeProcedureEnv.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/service/thrift/ConfigNodeRPCServiceProcessor.java
- iotdb-core/confignode/src/test/java/org/apache/iotdb/confignode/manager/load/balancer/router/priority/GreedyPriorityTest.java
- iotdb-core/confignode/src/test/java/org/apache/iotdb/confignode/manager/load/balancer/router/priority/LeaderPriorityBalancerTest.java
- iotdb-core/confignode/src/test/java/org/apache/iotdb/confignode/manager/load/cache/LoadCacheTest.java
- iotdb-core/confignode/src/test/java/org/apache/iotdb/confignode/manager/load/cache/NodeCacheTest.java
- iotdb-core/confignode/src/test/java/org/apache/iotdb/confignode/manager/load/cache/RegionGroupCacheTest.java
- iotdb-core/confignode/src/test/java/org/apache/iotdb/confignode/manager/load/cache/RegionRouteCacheTest.java
https://issues.apache.org/jira/browse/IOTDB-6293
> [IOTDB-6293] Use nanotime in cluster heartbeat

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/mtree/impl/pbtree/schemafile/pagemgr/BTreePageManager.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/mtree/impl/pbtree/schemafile/pagemgr/PageIOChannel.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/mtree/impl/pbtree/schemafile/pagemgr/PageIndexSortBuckets.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/mtree/impl/pbtree/schemafile/pagemgr/PageManager.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/mtree/impl/pbtree/schemafile/pagemgr/PagePool.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/mtree/impl/pbtree/schemafile/pagemgr/SchemaPageContext.java
Decouple PageManager to PagePool, PageIOChannel, PageIndexSortBuckets and SchemaPageContext, achiving better readibility and maintainability and providing optimazation possibility in further development at coming days.
> PBTree: Decouple PageManager

- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/ConfigManager.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/service/ConfigNode.java
https://issues.apache.org/jira/browse/IOTDB-6295
> [IOTDB-6295] Adjust the timeout period in ConfigNode registration procedure

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/rescon/CachedSchemaRegionStatistics.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/mtree/impl/pbtree/CachedMTreeStore.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/mtree/impl/pbtree/memcontrol/MemoryStatistics.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/mtree/impl/pbtree/memory/IMemoryManager.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/mtree/impl/pbtree/memory/MemoryManager.java
- iotdb-core/node-commons/src/assembly/resources/conf/iotdb-common.properties
Add pbtree configuration and volatile size statistics
> Add pbtree configuration and volatile size statistics

- integration-test/src/test/java/org/apache/iotdb/db/it/alignbydevice/IoTDBOrderByLimitOffsetAlignByDeviceIT.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/process/TopKOperator.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/schedule/DriverScheduler.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/LocalExecutionPlanner.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/LogicalPlanBuilder.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/plan/planner/distribution/AlignByTimeOrderByLimitOffsetTest.java
Add unit byte for no enough query memory, perfect docs of ut and some class.
> Add unit byte for no enough query memory

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/consensus/statemachine/dataregion/IoTConsensusDataRegionStateMachine.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/extractor/historical/PipeHistoricalDataRegionTsFileExtractor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/tsfile/TsFileResource.java
> Pipe: fixed the bug that region follower tsfiles can not record the IoTProgressIndex from region leader

- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/consensus/statemachine/ConfigRegionStateMachine.java
> Revert "Fixed issue where ConfigNode might recover incorrectly under SimpleConsensus"

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/utils/writer/RepairUnsortedFileCompactionWriter.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/compaction/repair/RepairUnsortedFileCompactionTest.java
Fix repairing non aligned series write points of other series to all chunk writer.
> Fix repair non aligned series

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/DataRegion.java
This PR optimized data region recover log output,
> Storage Engine: optimized DataRegion recover log

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/wal/node/WALNode.java
wal file will be deleted when its startSearchIndex is smaller SafelyDeletedSearchIndex, but this operation may delete the wal file which contains nodes for iot consensus. To fix this, we revert some logic to the previous version.
> Avoid deleting wal files pinned by the iot consensus

- pom.xml
see changes in https://github.com/SzyWilliam/ratis/commits/3.1.0-snap/
> Bump ratis to 3.1.0-snapshot

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/selector/estimator/AbstractCompactionEstimator.java
Fix concurrent modification exception of compaction worker by add synchronized block.
> Fix concurrent modification exception of compaction worker

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/selector/estimator/AbstractCompactionEstimator.java
Separate the synchronized block of AbstractCompactionEstimator file info cache.
> Separate the synchronized block of AbstractCompactionEstimator file info cache

- iotdb-client/jdbc/pom.xml
- iotdb-client/jdbc/src/main/java/org/apache/iotdb/jdbc/IoTDBDatabaseMetadata.java
- iotdb-client/jdbc/src/main/java/org/apache/iotdb/jdbc/IoTDBJDBCResultSet.java
1. getDouble Add judgment by type, when type is FLOAT call getFloat
2. fix Metadata some error，Devices without database and timeseries without database
> feat(jdbc):getDouble add type check

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/consensus/statemachine/dataregion/DataRegionStateMachine.java
Remove infinite retry logic to avoid potential problems
> Remove infinite retry logic for replica inconsistency to avoid potential problems

- .github/workflows/client-cpp.yml
- .github/workflows/client-go.yml
- .github/workflows/client-python.yml
- .github/workflows/cluster-it-1c1d.yml
- .github/workflows/cluster-it-1c3d.yml
- .github/workflows/grafana-plugin.yml
- .github/workflows/pipe-it-2cluster.yml
- .github/workflows/sonar-codecov.yml
- .github/workflows/unit-test.yml
This PR is fixing the following warning.
> Upgrade github action version to fix the warning

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/protocol/thrift/sync/IoTDBThriftSyncClientManager.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/event/common/tablet/PipeRawTabletInsertionEvent.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/resource/memory/PipeMemoryManager.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/task/connection/PipeEventCollector.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/task/subtask/PipeDataNodeSubtask.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/task/subtask/processor/PipeProcessorSubtask.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/task/subtask/processor/PipeProcessorSubtaskWorker.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/task/subtask/PipeSubtask.java
> Pipe: fixed the bug that processor dies when encountered memory shortage for tablets in a period of time

- integration-test/src/main/java/org/apache/iotdb/it/env/cluster/config/MppCommonConfig.java
- integration-test/src/main/java/org/apache/iotdb/it/env/cluster/config/MppSharedCommonConfig.java
- integration-test/src/main/java/org/apache/iotdb/it/env/remote/config/RemoteCommonConfig.java
- integration-test/src/main/java/org/apache/iotdb/itbase/env/CommonConfig.java
- integration-test/src/test/java/org/apache/iotdb/pipe/it/autocreate/AbstractPipeDualAutoIT.java
- integration-test/src/test/java/org/apache/iotdb/pipe/it/autocreate/IoTDBPipeClusterIT.java
- integration-test/src/test/java/org/apache/iotdb/pipe/it/autocreate/IoTDBPipeIdempotentIT.java
- integration-test/src/test/java/org/apache/iotdb/pipe/it/autocreate/IoTDBPipeProcessorIT.java
- integration-test/src/test/java/org/apache/iotdb/pipe/it/autocreate/IoTDBPipeProtocolIT.java
- integration-test/src/test/java/org/apache/iotdb/pipe/it/manual/AbstractPipeDualManualIT.java
- integration-test/src/test/java/org/apache/iotdb/pipe/it/manual/IoTDBPipeMetaLeaderChangeIT.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/consensus/statemachine/schemaregion/SchemaExecutionVisitor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/extractor/dataregion/IoTDBDataRegionExtractor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/extractor/schemaregion/IoTDBSchemaRegionExtractor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/processor/downsampling/DownSamplingProcessor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/task/stage/PipeTaskExtractorStage.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/task/subtask/connector/PipeConnectorSubtask.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/plan/node/pipe/OperateSchemaQueueNode.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/datastructure/AbstractPipeListeningQueue.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/datastructure/AbstractSerializableListeningQueue.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/datastructure/ConcurrentIterableLinkedQueue.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/extractor/IoTDBMetaExtractor.java
> Pipe Meta: Fixed concurrent bug of start and close operation for schema region extractor & fixed IT flush problems

- integration-test/src/test/java/org/apache/iotdb/pipe/it/autocreate/AbstractPipeDualAutoIT.java
- integration-test/src/test/java/org/apache/iotdb/pipe/it/autocreate/IoTDBPipeClusterIT.java
- integration-test/src/test/java/org/apache/iotdb/pipe/it/autocreate/IoTDBPipeIdempotentIT.java
- integration-test/src/test/java/org/apache/iotdb/pipe/it/autocreate/IoTDBPipeProcessorIT.java
- integration-test/src/test/java/org/apache/iotdb/pipe/it/manual/AbstractPipeDualManualIT.java
- integration-test/src/test/java/org/apache/iotdb/pipe/it/manual/IoTDBPipeMetaLeaderChangeIT.java
> Pipe Meta: Fixed flush problems caused by IT

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/consensus/statemachine/schemaregion/SchemaExecutionVisitor.java
> Pipe Meta: Fixed schema node operation bug

- integration-test/src/test/java/org/apache/iotdb/pipe/it/autocreate/AbstractPipeDualAutoIT.java
- integration-test/src/test/java/org/apache/iotdb/pipe/it/autocreate/IoTDBPipeClusterIT.java
- integration-test/src/test/java/org/apache/iotdb/pipe/it/autocreate/IoTDBPipeIdempotentIT.java
- integration-test/src/test/java/org/apache/iotdb/pipe/it/autocreate/IoTDBPipeProcessorIT.java
- integration-test/src/test/java/org/apache/iotdb/pipe/it/manual/AbstractPipeDualManualIT.java
- integration-test/src/test/java/org/apache/iotdb/pipe/it/manual/IoTDBPipeMetaLeaderChangeIT.java
> Pipe Meta: Revert auto flush of Pipe IT to reduce the resource occupation

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/rescon/SchemaResourceManager.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/mtree/impl/pbtree/CachedMTreeStore.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/mtree/impl/pbtree/PBTreeFactory.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/mtree/impl/pbtree/memory/page/FIFOPageContainer.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/mtree/impl/pbtree/memory/page/IPageContainer.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/mtree/impl/pbtree/memory/page/PageLifecycleManager.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/mtree/impl/pbtree/schemafile/ISchemaFile.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/mtree/impl/pbtree/schemafile/MockSchemaFile.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/mtree/impl/pbtree/schemafile/SchemaFile.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/mtree/impl/pbtree/schemafile/pagemgr/IPageManager.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/mtree/impl/pbtree/schemafile/pagemgr/PageManager.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/mtree/impl/pbtree/schemafile/pagemgr/PagePool.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/metadata/page/PageLifecycleManagerTest.java
Implement PageLifecycleManager for global page control
> Implement PageLifecycleManager for global page control

- integration-test/src/main/java/org/apache/iotdb/itbase/constant/BuiltinAggregationFunctionEnum.java
- integration-test/src/test/java/org/apache/iotdb/db/it/aggregation/IoTDBAggregationIT.java
- integration-test/src/test/java/org/apache/iotdb/db/it/aggregation/minby/IoTDBMinBy2IT.java
- integration-test/src/test/java/org/apache/iotdb/db/it/aggregation/minby/IoTDBMinBy3IT.java
- integration-test/src/test/java/org/apache/iotdb/db/it/aggregation/minby/IoTDBMinByAlignedSeriesIT.java
- integration-test/src/test/java/org/apache/iotdb/db/it/aggregation/minby/IoTDBMinByIT.java
- iotdb-client/cli/src/main/java/org/apache/iotdb/tool/ExportTsFile.java
- iotdb-client/jdbc/src/main/java/org/apache/iotdb/jdbc/IoTDBDatabaseMetadata.java
- iotdb-connector/flink-sql-iotdb-connector/src/main/java/org/apache/iotdb/flink/sql/factory/IoTDBDynamicTableFactory.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/aggregation/AccumulatorFactory.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/aggregation/MaxMinByBaseAccumulator.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/aggregation/MinByAccumulator.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/aggregation/slidingwindow/SlidingWindowAggregatorFactory.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/ExpressionTypeAnalyzer.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/parser/ASTVisitor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/plan/parameter/AggregationDescriptor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/utils/SchemaUtils.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/utils/TypeInferenceUtils.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/utils/constant/SqlConstant.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/utils/constant/TestConstant.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/execution/aggregation/AccumulatorTest.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/udf/builtin/BuiltinAggregationFunction.java
- iotdb-protocol/thrift-commons/src/main/thrift/common.thrift
A similar function as MaxBy. Details can be found in this pr: https://github.com/apache/iotdb/pull/11986
> Introduce Aggregation Function MinBy

- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/config/constant/PipeExtractorConstant.java
> Pipe Meta: Changed the default sync inclusion to data.insert

- .github/workflows/cluster-it-1c3d.yml
Machine migration, temporary shutdown
Starting migration in two days
Expected to take two weeks
> change ci to github ci

- iotdb-client/cli/src/assembly/resources/sbin/start-cli.bat
- iotdb-client/cli/src/assembly/resources/tools/collect-info.bat
- iotdb-client/cli/src/assembly/resources/tools/export-csv.bat
- iotdb-client/cli/src/assembly/resources/tools/export-tsfile.bat
- iotdb-client/cli/src/assembly/resources/tools/import-csv.bat
- iotdb-client/cli/src/assembly/resources/tools/load-tsfile.bat
- iotdb-core/confignode/src/assembly/resources/sbin/start-confignode.bat
- iotdb-core/datanode/src/assembly/resources/sbin/start-datanode.bat
add title and set format for windows bat script
> feat(bat): add title and set format

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/mtree/impl/pbtree/schemafile/pagemgr/PageManager.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/mtree/impl/pbtree/schemafile/pagemgr/SchemaPageContext.java
A thorough but coarse way to fix dead lock in PBTree.SchemaFile, which is rooted in the lagacy implementation of concurrent page operation and will be refactored in next month.
<hr>
This PR has:
<hr>
> Fix dead lock in PBTree.SchemaFile

- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/utils/FileUtils.java
https://apache-iotdb.feishu.cn/docx/doxcnoNqbTBbhIgP9QbYAW9QTne#doxcn9F8UtJgcxofca5iTGIsxud
> Add FileUtils.moveFileSafe function

- iotdb-client/jdbc/src/main/java/org/apache/iotdb/jdbc/IoTDBConnection.java
- iotdb-client/jdbc/src/main/java/org/apache/iotdb/jdbc/IoTDBPreparedStatement.java
1. IoTDBPreparedStatement implement  addBatch function
2. remove JDBC IoTDBConnection commit  "Does not support commit"
> fix: IoTDBPreparedStatement implement  addBatch function

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/receiver/PipePlanToStatementVisitor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/plan/node/metedata/write/CreateMultiTimeSeriesNode.java
> Pipe Meta: Fixed CreateMultiTimeseries bug

- integration-test/src/test/java/org/apache/iotdb/pipe/it/IoTDBPipeSingleEnvDemoIT.java
- integration-test/src/test/java/org/apache/iotdb/pipe/it/autocreate/AbstractPipeDualAutoIT.java
- integration-test/src/test/java/org/apache/iotdb/pipe/it/autocreate/IoTDBPipeClusterIT.java
- integration-test/src/test/java/org/apache/iotdb/pipe/it/autocreate/IoTDBPipeDataSinkIT.java
- integration-test/src/test/java/org/apache/iotdb/pipe/it/autocreate/IoTDBPipeIdempotentIT.java
- integration-test/src/test/java/org/apache/iotdb/pipe/it/autocreate/IoTDBPipeProcessorIT.java
- integration-test/src/test/java/org/apache/iotdb/pipe/it/autocreate/IoTDBPipeProtocolIT.java
- integration-test/src/test/java/org/apache/iotdb/pipe/it/manual/AbstractPipeDualManualIT.java
- integration-test/src/test/java/org/apache/iotdb/pipe/it/manual/IoTDBPipeMetaLeaderChangeIT.java
> Pipe Meta: Fixed IT contents

- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/datastructure/AbstractSerializableListeningQueue.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/datastructure/ConcurrentIterableLinkedQueue.java
> Pipe Meta: fixed the bug that cleared writeEvents' reference counts can not be cleared

- integration-test/src/test/java/org/apache/iotdb/db/it/IoTDBFilterIT.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/PredicateUtils.java
Issue: https://issues.apache.org/jira/browse/IOTDB-6306
> [IOTDB-6306] Fix the issue that UDTF with boolean type is not supported in filter

- iotdb-core/datanode/pom.xml
- iotdb-core/tsfile/pom.xml
- iotdb-core/tsfile/src/test/java/org/apache/iotdb/tsfile/encoding/BeforeREGERTimeSpaceCostTest.java
- iotdb-core/tsfile/src/test/java/org/apache/iotdb/tsfile/encoding/BeforeREGERValueSpaceCostTest.java
- iotdb-core/tsfile/src/test/java/org/apache/iotdb/tsfile/encoding/EncodeTest.java
- iotdb-core/tsfile/src/test/java/org/apache/iotdb/tsfile/encoding/KernelDensityEstimation.java
- iotdb-core/tsfile/src/test/java/org/apache/iotdb/tsfile/encoding/REGERFloatEachTimeTest.java
- iotdb-core/tsfile/src/test/java/org/apache/iotdb/tsfile/encoding/REGERFloatTest.java
- iotdb-core/tsfile/src/test/java/org/apache/iotdb/tsfile/encoding/REGERMemoryTest.java
- iotdb-core/tsfile/src/test/java/org/apache/iotdb/tsfile/encoding/REGERPartitionSortTest.java
- iotdb-core/tsfile/src/test/java/org/apache/iotdb/tsfile/encoding/REGERPruneTest.java
- iotdb-core/tsfile/src/test/java/org/apache/iotdb/tsfile/encoding/REGERRandomSortTest.java
- iotdb-core/tsfile/src/test/java/org/apache/iotdb/tsfile/encoding/REGERTimeSortTest.java
- iotdb-core/tsfile/src/test/java/org/apache/iotdb/tsfile/encoding/REGERTimeSpaceCostTest.java
- iotdb-core/tsfile/src/test/java/org/apache/iotdb/tsfile/encoding/REGERValueSortTest.java
- iotdb-core/tsfile/src/test/java/org/apache/iotdb/tsfile/encoding/REGERValueSpaceCostTest.java
- iotdb-core/tsfile/src/test/java/org/apache/iotdb/tsfile/encoding/RegerPFloatTest.java
- iotdb-core/tsfile/src/test/java/org/apache/iotdb/tsfile/encoding/decoder/FloatDecoderTest.java
> Icde revision 0301

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/DataRegion.java
Add remove TsFile for DataRegion
> Add remove TsFile for DataRegion

- integration-test/src/test/java/org/apache/iotdb/libudf/it/dmatch/DMatchIT.java
- integration-test/src/test/java/org/apache/iotdb/libudf/it/dprofile/DProfileIT.java
- library-udf/src/main/java/org/apache/iotdb/library/dprofile/UDTFSample.java
Open some ignored ITs, `timeliness` and `sample`
> Fix some ignored ITs of udf lib

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/thrift/impl/DataNodeInternalRPCServiceImpl.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/execution/config/executor/ClusterConfigTaskExecutor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/DataRegion.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/task/InnerSpaceCompactionTask.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/task/InsertionCrossSpaceCompactionTask.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/repair/RepairTimePartitionScanTask.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/schedule/CompactionScheduleTaskManager.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/selector/impl/RewriteCrossSpaceCompactionSelector.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/compaction/cross/InsertionCrossSpaceCompactionSelectorTest.java
Fix compaction schedule task manager cannot stop and modify some output in log
> Fix compaction schedule task manager cannot stop and modify some output in log

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/event/common/tablet/PipeInsertNodeTabletInsertionEvent.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/event/common/tablet/PipeRawTabletInsertionEvent.java
> Pipe: fixed the bug that released PipeRawTabletInsertionEvent's tablet is still referenced and causing OOM

- .github/workflows/cluster-it-1c3d.yml
> Revert "change ci to github ci"

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/wal/checkpoint/CheckpointManager.java
> Ignore log: memtableId -9223372036854775808 not found in MemTableId2Info

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/schedule/CompactionScheduleTaskWorker.java
Fix StorageEngine recover slowly. In pr https://github.com/apache/iotdb/pull/12039, the compaction schedule thread may start work after any recover of one data region. After the fix, the compaction schedule will not work until all data region is ready.
> Fix StorageEngine recover slowly

- .github/workflows/client-cpp.yml
as title
https://github.com/apache/iotdb/actions/runs/8251497932/job/22568681790
> Fix cpp client IT on windows

- integration-test/src/test/java/org/apache/iotdb/pipe/it/autocreate/IoTDBPipeAutoConflictIT.java
- integration-test/src/test/java/org/apache/iotdb/pipe/it/autocreate/IoTDBPipePatternFormatIT.java
- integration-test/src/test/java/org/apache/iotdb/pipe/it/manual/IoTDBPipeInclusionIT.java
> Pipe: Refactored IT to complement necessary flush to all the pipe ITs

- iotdb-client/jdbc/src/main/java/org/apache/iotdb/jdbc/IoTDBDatabaseMetadata.java
when catalog is "Apache IoTDB", No need for this condition
> fix(jdbc): when catalog is "Apache IoTDB", ignore it

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/schedule/CompactionScheduleTaskWorker.java
- iotdb-core/node-commons/src/assembly/resources/conf/iotdb-common.properties
Random schedule compaction of bound data regions in one compaction schedule worker
> Random schedule compaction of bound data regions in one compaction schedule worker

- integration-test/src/test/java/org/apache/iotdb/pipe/it/autocreate/IoTDBPipeIdempotentIT.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/receiver/PipeStatementTSStatusVisitor.java
> Pipe: Fixed create logical view idempotency problem & some IT check coverage missing

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/fragment/FragmentInstanceExecution.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/ExplainAnalyzeOperator.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/Operator.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/OperatorContext.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/LogicalPlanVisitor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/OperatorTreeGenerator.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/plan/node/ExplainAnalyzeNode.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/statistics/FragmentInstanceStatisticsDrawer.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/statistics/StatisticsMergeUtil.java
- iotdb-core/node-commons/src/assembly/resources/conf/iotdb-common.properties
- iotdb-protocol/thrift-datanode/src/main/thrift/datanode.thrift
1. add FragmentInstanceState in result
2. fix the 'input rows' to 'output rows'
> Optimize the result of EXPLAIN ANALYZE

- integration-test/src/main/java/org/apache/iotdb/it/env/cluster/env/AbstractEnv.java
- integration-test/src/main/java/org/apache/iotdb/it/env/cluster/node/AbstractNodeWrapper.java
- integration-test/src/main/java/org/apache/iotdb/itbase/env/BaseNodeWrapper.java
> Integration test cluster stop faster

- iotdb-doap.rdf
> Update iotdb-doap.rdf to update the info in https://projects.apache.org/project.html?iotdb

- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/ConfigManager.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/ProcedureManager.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/schema/ClusterSchemaManager.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/persistence/schema/ClusterSchemaInfo.java
- iotdb-core/confignode/src/test/java/org/apache/iotdb/confignode/persistence/schema/ConfigMTreeTest.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/schema/source/DeviceSchemaSource.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/schema/source/LogicalViewSchemaSource.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/schema/source/TimeSeriesSchemaSource.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/Coordinator.java
- pom.xml
* Environment
```
LOOP=1
BATCH_SIZE_PER_WRITE=1
DEVICE_NAME_PREFIX=d_
DEVICE_NUMBER=10000
SENSOR_NUMBER=166
```
* Before
DeleteTimeSeriesStatement cost time: 2596ms
* After
DeleteTimeSeriesStatement cost time: 1589ms
> Optimize Count/Delete Timeseries root.** or root.db.**

- example/session/src/main/java/org/apache/iotdb/SessionPoolExample.java
- iotdb-client/session/src/main/java/org/apache/iotdb/session/SessionConnection.java
More details can be seen in https://issues.apache.org/jira/browse/IOTDB-6312.
In this pr, if we use wrong password, we will get the following error msg:
> [IOTDB-6312] Throw correct error msg while using wrong password

- iotdb-core/node-commons/src/assembly/resources/conf/iotdb-common.properties
> Change default threshold of slow query from 30s to 10s

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/Analysis.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/optimization/ColumnInjectionPushDown.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/optimization/LimitOffsetPushDown.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/optimization/OrderByExpressionWithLimitChangeToTopK.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/optimization/PredicatePushDown.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/LogicalPlanner.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/plan/node/PlanVisitor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/statement/sys/ExplainAnalyzeStatement.java
Explain Analyze didn't be treated as query, so some optimization won't work.
> [IOTDB-6314] Treat ExplainAnalyze as a query

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/metric/QueryRelatedResourceMetricSet.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/rescon/memory/TsFileResourceManager.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/rescon/memory/ResourceManagerTest.java
Add total resource number, degraded resource number, max index memory size and used index memory size metrics.
> Add Query Metric for TsFileResourceManager

- integration-test/src/test/java/org/apache/iotdb/confignode/it/procedure/IoTDBProcedureIT.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/consensus/request/ConfigPhysicalPlanType.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/consensus/request/write/procedure/UpdateProcedurePlan.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/consensus/statemachine/ConfigRegionStateMachine.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/ConfigManager.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/ProcedureManager.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/consensus/ConsensusManager.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/persistence/ProcedureInfo.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/persistence/executor/ConfigPlanExecutor.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/CompletedProcedureRecycler.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/Procedure.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/ProcedureExecutor.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/TimeoutExecutorThread.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/testonly/AddNeverFinishSubProcedureProcedure.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/testonly/NeverFinishProcedure.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/store/ConfigProcedureStore.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/store/IProcedureStore.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/store/ProcedureType.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/store/ProcedureWAL.java
- iotdb-core/confignode/src/test/java/org/apache/iotdb/confignode/consensus/request/TestOnlyPlan.java
- iotdb-core/confignode/src/test/java/org/apache/iotdb/confignode/persistence/ProcedureInfoTest.java
- iotdb-core/confignode/src/test/java/org/apache/iotdb/confignode/procedure/NoopProcedureStore.java
- iotdb-core/confignode/src/test/java/org/apache/iotdb/confignode/procedure/TestProcedureBase.java
- iotdb-core/confignode/src/test/java/org/apache/iotdb/confignode/procedure/UpgradeFromWALToConsensusLayerTest.java
- iotdb-core/confignode/src/test/java/org/apache/iotdb/confignode/procedure/util/ProcedureTestUtil.java
- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/ratis/RatisConsensus.java
https://apache-iotdb.feishu.cn/docx/QuVKd0IgSokk3CxXThBc9SvRndc
> Refactor Procedure recover framework

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/common/DataNodeEndPoints.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/fragment/FragmentInstanceManager.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/distribution/SimpleFragmentParallelPlanner.java
https://jira.infra.timecho.com:8443/browse/TIMECHODB-617
> Fix NPE problem in EXPLAIN ANALYZE

- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/consensus/request/auth/AuthorPlan.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/PermissionManager.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/persistence/schema/CNPhysicalPlanGenerator.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/persistence/schema/CNSnapshotFileType.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/persistence/schema/ConfignodeSnapshotParser.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/sync/AuthOperationProcedure.java
- iotdb-core/confignode/src/test/java/org/apache/iotdb/confignode/persistence/CNPhysicalPlanGeneratorTest.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/auth/entity/PrivilegeType.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/auth/role/LocalFileRoleAccessor.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/auth/user/BasicUserManager.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/auth/user/LocalFileUserAccessor.java
In this pr:
1. Add some info log in auth module.
2. rename enum SCHEMA_TEMPLATE to SCHEMA.
3. fix bugs and code style in Confignode snapshot parser.
4. add timestamp in authprocedure.
> fix cn parser and code style.

- library-udf/src/main/java/org/apache/iotdb/library/frequency/UDFEnvelopeAnalysis.java
Fix envelope function execution error without frequency parameter.
> UDF: Fix envelope function execution error without frequency parameter

- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/consensus/statemachine/ConfigRegionStateMachine.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/ProcedureExecutor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/consensus/statemachine/schemaregion/SchemaRegionStateMachine.java
> Log: add logs for notifyLeaderReady, notifyLeaderChanged and procedure workers

- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/consensus/ConsensusManager.java
- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/IConsensus.java
- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/iot/IoTConsensus.java
- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/ratis/DiskGuardian.java
- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/ratis/RatisConsensus.java
- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/ratis/utils/Utils.java
- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/simple/SimpleConsensus.java
- iotdb-core/consensus/src/test/java/org/apache/iotdb/consensus/iot/StabilityTest.java
- iotdb-core/consensus/src/test/java/org/apache/iotdb/consensus/ratis/RatisConsensusTest.java
- iotdb-core/consensus/src/test/java/org/apache/iotdb/consensus/simple/SimpleConsensusTest.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/service/IoTDBShutdownHook.java
- pom.xml
mirrors https://github.com/apache/ratis/compare/release-3.0.1...snapshot-3
refactor triggerSnapshot interface to support force flag.
> [RatisConsensus] Bump ratis snapshot version to support force snapshot

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/DataRegion.java
more details can be seen in https://issues.apache.org/jira/browse/IOTDB-6316
> [IOTDB-6316] Fix potential concurrent bug between compaction and load

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/repair/RepairDataFileScanUtil.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/compaction/repair/RepairDataFileScanUtilTest.java
Fix uncompress byte buffer in RepairDataFileScanUtil
> Fix uncompress byte buffer in RepairDataFileScanUtil

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/schedule/comparator/DefaultCompactionTaskComparatorImpl.java
Modify compaction task priority comparator. When compare max file version of compaction task, the data region and time partition should be same.
> Modify compaction task priority comparator

- integration-test/src/test/java/org/apache/iotdb/confignode/it/partition/IoTDBAutoRegionGroupExtensionIT.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/conf/ConfigNodeConfig.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/load/balancer/RegionBalancer.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/load/balancer/region/GreedyCopySetRegionGroupAllocator.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/load/balancer/region/GreedyRegionGroupAllocator.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/load/balancer/region/IRegionGroupAllocator.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/partition/PartitionManager.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/persistence/partition/PartitionInfo.java
- iotdb-core/confignode/src/test/java/org/apache/iotdb/confignode/manager/load/balancer/region/AllocatorScatterWidthManualTest.java
- iotdb-core/confignode/src/test/java/org/apache/iotdb/confignode/manager/load/balancer/region/GreedyCopySetRegionGroupAllocatorTest.java
- iotdb-core/confignode/src/test/java/org/apache/iotdb/confignode/manager/load/balancer/region/GreedyRegionGroupAllocatorTest.java
https://issues.apache.org/jira/browse/IOTDB-6307
> [IOTDB-6307] GCR algorithm for multi-database

- integration-test/src/test/java/org/apache/iotdb/db/it/IOTDBLoadTsFileIT.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/ConfigManager.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/AnalyzeVisitor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/schema/AutoCreateSchemaExecutor.java
Fix Load TsFile with extend template and add template check for internalCreateTimeSeriesStatement
> Fix Load TsFile with extend template & add template check for internalCreateTimeSeriesStatement

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/consensus/statemachine/schemaregion/SchemaRegionStateMachine.java
> Pipe: Fixed the bug that schema region snapshot may not be listened when dataNode restarts

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/SeriesScanUtil.java
more details can be seen in https://jira.infra.timecho.com:8443/browse/TIMECHODB-630
> Fix mismatched dataType with same name bug in query

- integration-test/src/test/java/org/apache/iotdb/db/it/utils/TestUtils.java
- integration-test/src/test/java/org/apache/iotdb/subscription/it/dual/AbstractSubscriptionDualIT.java
- integration-test/src/test/java/org/apache/iotdb/subscription/it/dual/IoTDBSubscriptionConsumerGroupIT.java
> Subscription: refactor `IoTDBSubscriptionConsumerGroupIT` to support multi-protocol pipe sync reference

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/protocol/websocket/WebSocketConnector.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/processor/aggregate/AggregateProcessor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/receiver/protocol/airgap/IoTDBAirGapReceiver.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/event/EnrichedEvent.java
> Pipe: Fixed the bug that CDC connector may report in advance

- .github/workflows/pipe-it-2cluster.yml
> Pipe IT: remove StrongConsistencyClusterMode tests from manual-create-schema IT

- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/conf/CommonConfig.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/conf/CommonDescriptor.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/config/PipeConfig.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/datastructure/queue/listening/AbstractPipeListeningQueue.java
> Pipe: Added parameters to the snapshot transfer threshold from last snapshot to queue's tail index

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/event/common/tablet/PipeRawTabletInsertionEvent.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/processor/aggregate/AggregateProcessor.java
> Pipe: Fixed the NPE when an emit is triggered by a generic event in aggregate processor

- integration-test/src/main/java/org/apache/iotdb/it/env/cluster/config/MppConfigNodeConfig.java
- integration-test/src/main/java/org/apache/iotdb/it/env/remote/config/RemoteConfigNodeConfig.java
- integration-test/src/main/java/org/apache/iotdb/itbase/env/ConfigNodeConfig.java
- integration-test/src/test/java/org/apache/iotdb/pipe/it/autocreate/AbstractPipeDualAutoIT.java
- integration-test/src/test/java/org/apache/iotdb/pipe/it/autocreate/IoTDBPipeClusterIT.java
- integration-test/src/test/java/org/apache/iotdb/pipe/it/autocreate/IoTDBPipeIdempotentIT.java
- integration-test/src/test/java/org/apache/iotdb/pipe/it/autocreate/IoTDBPipeProcessorIT.java
- integration-test/src/test/java/org/apache/iotdb/pipe/it/autocreate/IoTDBPipeProtocolIT.java
- integration-test/src/test/java/org/apache/iotdb/pipe/it/manual/AbstractPipeDualManualIT.java
- integration-test/src/test/java/org/apache/iotdb/pipe/it/manual/IoTDBPipeMetaHistoricalIT.java
- integration-test/src/test/java/org/apache/iotdb/pipe/it/manual/IoTDBPipeMetaLeaderChangeIT.java
- integration-test/src/test/java/org/apache/iotdb/pipe/it/single/AbstractPipeSingleIT.java
- integration-test/src/test/java/org/apache/iotdb/subscription/it/dual/AbstractSubscriptionDualIT.java
> Pipe: Configured the connection timeout ms parameter to avoid premature timeout of pipe creation in ITs

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/processor/aggregate/AggregateProcessor.java
> Pipe: Added output.measurements and output.database format check in AggregateProcessor

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/exchange/sink/ShuffleSinkHandle.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/exchange/source/LocalSourceHandle.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/memory/MemoryPool.java
details could be found at: https://apache-iotdb.feishu.cn/docx/OFq8d4UeMowd68xmalNcaS9bnHh
> Fix potential NPE when concurrently aborting a Query

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/payload/evolvable/builder/IoTDBThriftSyncPipeTransferBatchReqBuilder.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/payload/evolvable/builder/PipeTransferBatchReqBuilder.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/parser/ASTVisitor.java
> Pipe: decrease reference count for untransferred events in batch when closing & fix parsing alter pipe name

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/schedule/CompactionScheduler.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/schedule/CompactionTaskQueue.java
Delay memory estimation of InnerSpaceCompactionTask.
> Delay memory estimation of InnerSpaceCompactionTask

- example/pipe-opc-ua-sink/pom.xml
As the title said. Now you can get a jar with main class and can be directly executed by "mvn clean package -P get-jar-with-dependencies"
<hr>
This PR has:
<hr>
> Pipe: Added get-jar-with-dependencies packaging option for pipe-opc-ua-sink-example

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/exception/CompactionExceptionHandler.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/recover/CompactionRecoverTask.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/task/AbstractCompactionTask.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/task/InnerSpaceCompactionTask.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/selector/impl/RewriteCrossSpaceCompactionSelector.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/compaction/inner/InnerSpaceCompactionExceptionTest.java
1. Do not set read only in compaction module.
2. No longer set allowCompaction to false though the compaction exception recovery is failed.
> Do not set read only in compaction module

- iotdb-core/node-commons/src/assembly/resources/sbin/health_check.bat
- iotdb-core/node-commons/src/assembly/resources/sbin/health_check.sh
> feature add health_check

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java
- iotdb-core/metrics/interface/src/main/java/org/apache/iotdb/metrics/metricsets/system/SystemMetrics.java
- iotdb-core/node-commons/src/assembly/resources/conf/iotdb-common.properties
This PR disign a new calculation method for iot_consensus_throttle_threshold_in_byte.
more detail in https://apache-iotdb.feishu.cn/docx/GOjddCL1QoLP1dxfAgLcMCDtnEh#Xt1Zd66okoth9fxvymSc4vkOncY
> new iot_consensus_throttle_threshold_in_byte

- pom.xml
mirrors https://github.com/apache/ratis/tree/snapshot-3
> [RatisConsensus] Bump Ratis snapshot version to 8eafc4f

- integration-test/src/test/java/org/apache/iotdb/pipe/it/autocreate/IoTDBPipeProtocolIT.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/config/constant/PipeExtractorConstant.java
> Pipe: Reset the inclusion settings to data.insert

- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/ProcedureManager.java
- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/iot/IoTConsensus.java
- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/iot/IoTConsensusServerImpl.java
- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/iot/snapshot/SnapshotFragmentReader.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/utils/DateTimeUtils.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/utils/CommonDateTimeUtils.java
For example:
```
[SNAPSHOT TRANSMISSION] Start to transmit snapshots (2 files, full size 321 bytes) from dir data/datanode1/consensus/data_region/1_1/snapshot_1_1 
[SNAPSHOT TRANSMISSION] The overall progress for dir snapshot_1_1: files 1/2 done, size 236 bytes/321 bytes done, 7 ms pass) 
[SNAPSHOT TRANSMISSION] The overall progress for dir snapshot_1_1: files 2/2 done, size 321 bytes/321 bytes done, 9 ms pass) 
[SNAPSHOT TRANSMISSION] After 9 ms, successfully transmit all snapshots from dir data/datanode1/consensus/data_region/1_1/snapshot_1_1 
```
> Print progress in log during transmitting snapshot for region migration

- README.md
> Update Link of IoTDB Introduction.md

- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/load/balancer/RouteBalancer.java
> Revert "Fix auto leader balance for Ratis protocol judgement bug"

- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/pipe/extractor/IoTDBConfigRegionExtractor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/extractor/schemaregion/IoTDBSchemaRegionExtractor.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/extractor/IoTDBNonDataRegionExtractor.java
> Pipe: Fixed the CPU consuming problem when configNode has nothing to sync

- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/utils/CommonDateTimeUtils.java
- iotdb-core/node-commons/src/test/java/org/apache/iotdb/commons/utils/CommonDateTimeUtilsTest.java
index out of bound when convert 0
> Fix convertMillisecondToDurationStr and add UT

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/schedule/CompactionTaskManager.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/schedule/CompactionWorker.java
Fix compaction worker stopped after drop database
> Fix compaction worker stopped after drop database

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/rescon/disk/TierManager.java
- iotdb-core/metrics/interface/src/main/java/org/apache/iotdb/metrics/metricsets/system/SystemMetrics.java
- iotdb-core/metrics/interface/src/main/java/org/apache/iotdb/metrics/utils/FileStoreUtils.java
fix error when the wal dir is not exist
> fix error when the wal dir is not exist

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/service/RegionMigrateService.java
This pr should make parallel migration run faster
> Increase region migration pool size on DataNode

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/protocol/thrift/async/handler/PipeTransferTsFileInsertionEventHandler.java
> Pipe: Fixed the bug that mod file may not close in async transferring

- iotdb-api/pipe-api/src/main/java/org/apache/iotdb/pipe/api/customizer/parameter/PipeParameters.java
> Pipe: Make the PipeParameters return sorted entries string when "toString" is called

- iotdb-client/jdbc/src/main/java/org/apache/iotdb/jdbc/IoTDBPreparedStatement.java
- iotdb-client/jdbc/src/test/java/org/apache/iotdb/jdbc/IoTDBPreparedStatementTest.java
> fix(jdbc): when parameter is string ,append "\""

- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/compaction/utils/CompactionTaskQueueTest.java
Fix compaction ut dead lock
https://github.com/apache/iotdb/actions/runs/8731450531/job/23956879130
> Fix compaction ut dead lock

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/processor/aggregate/AggregateProcessor.java
> Pipe: Fixed the bug that aggregate processor cannot clear the last received time after drop

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/event/common/tsfile/TsFileInsertionDataContainer.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/repair/RepairDataFileScanUtil.java
Reduce string IDeviceID convert
> Reduce string IDeviceID convert

- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/load/balancer/RouteBalancer.java
The previous NPE bug should be fixed by PR: https://github.com/apache/iotdb/pull/12330
> Remove useless try-catch for RegionPriorityMap

- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/load/LoadManager.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/load/balancer/PartitionBalancer.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/partition/PartitionManager.java
Throw DatabaseNotExistsException when the database cache has been deleted.
> Enhance concurrent control of data partition policy table

- iotdb-client/cli/src/assembly/resources/tools/backup.bat
- iotdb-client/cli/src/assembly/resources/tools/backup.sh
- iotdb-client/cli/src/main/java/org/apache/iotdb/tool/IoTDBDataBackTool.java
> feature add iotdb backup

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/wal/node/WALNode.java
Use wal node disk size instead of wal manager total size.
> Fix effective ratio calculation method

- iotdb-client/cli/src/assembly/resources/tools/backup.bat
- iotdb-client/cli/src/assembly/resources/tools/backup.sh
Fixed backup data backend running issues
> Fixed backup data backend running issues

- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/pipe/extractor/IoTDBConfigRegionExtractor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/extractor/schemaregion/IoTDBSchemaRegionExtractor.java
> Pipe: Fixed the bug that pure data transfer is forbidden when SchemaRegion is in Simple consensus

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/task/subtask/processor/PipeProcessorSubtask.java
We noticed that when the pipe is stuck and restarted, the hashcode of new and old process subtasks is identical. This may lead to a situation where the key and value are inconsistent in the maintenance of ConcurrentHashMap `subtasks -> subtasks` by `PipeProcessorSubtaskWorker`, thereby causing unexpectedly removed subtasks that are NOT in the close state by `cleanupClosedSubtasksIfNecessary` in `org.apache.iotdb.db.pipe.task.subtask.processor.PipeProcessorSubtaskWorker`.
> Pipe: distinguish between old and new process subtasks before and after stuck restart to avoid unexpected hashmap override and removal

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/rest/utils/InsertTabletSortDataUtils.java
Fixed rest service insertTablet  lost data event return SUCCESS_STATUS
> Fixed rest service insertTablet lost data event return SUCCESS_STATUS

- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/ProcedureManager.java
> Pipe: refine procedure timeout message

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/receiver/protocol/legacy/IoTDBLegacyPipeReceiverAgent.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/receiver/IoTDBFileReceiver.java
> Pipe: remove unnecessary fsync operations for file pieces' transferring

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/extractor/dataregion/IoTDBDataRegionExtractor.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/pipe/extractor/IoTDBDataRegionExtractorTest.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/wal/WALManagerTest.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/wal/node/WALNodeTest.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/wal/node/WalDeleteOutdatedNewTest.java
> Pipe: Added check for wal disable and ratis consensus when enabling data region processing

- pom.xml
diff patch https://github.com/apache/ratis/pull/1069
> [RatisConsensus] update ratis snapshot version

- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/consensus/request/ConfigPhysicalPlanVisitor.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/consensus/request/auth/AuthorPlan.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/PermissionManager.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/pipe/event/PipeConfigRegionSnapshotEvent.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/pipe/extractor/ConfigRegionListeningFilter.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/pipe/receiver/protocol/IoTDBConfigNodeReceiver.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/pipe/receiver/visitor/PipeConfigPhysicalPlanTSStatusVisitor.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/persistence/executor/ConfigPlanExecutor.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/persistence/schema/CNPhysicalPlanGenerator.java
- iotdb-core/confignode/src/test/java/org/apache/iotdb/confignode/persistence/CNPhysicalPlanGeneratorTest.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/tools/schema/SRStatementGenerator.java
In this pr:
1. fix null pointer when create aligned timeseries  when sync.
2. pipe sync can create user with his own password instead of DEFAULT_PASSWORD
3. fix num of timeseries and view error.
> fix snapshot parser null point.

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/impl/SchemaRegionMemoryImpl.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/impl/SchemaRegionPBTreeImpl.java
> Fix statistics error when loading snapshot

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/receiver/protocol/airgap/IoTDBAirGapReceiver.java
> Pipe: Fixed air gap receiver non-closing problem when client exits in sender side

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/scheduler/load/LoadTsFileScheduler.java
> Load: Execute tsfile serially to avoid concurrent serialization of the resource file

- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/iot/IoTConsensus.java
- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/iot/IoTConsensusServerImpl.java
- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/iot/logdispatcher/LogDispatcher.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/scheduler/load/LoadTsFileScheduler.java
Use `lastPinnedSearchIndexForMigration` to lock and unlock `safelyDeletedSearchIndex` during region migration to ensure data consistency.
> Ensuring IoTconsensus data consistency during region migration

- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/load/LoadManager.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/load/balancer/RouteBalancer.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/load/balancer/router/leader/AbstractLeaderBalancer.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/load/balancer/router/leader/GreedyLeaderBalancer.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/load/balancer/router/leader/MinCostFlowLeaderBalancer.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/load/cache/LoadCache.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/load/cache/consensus/ConsensusGroupHeartbeatSample.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/load/cache/consensus/ConsensusGroupStatistics.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/load/cache/node/NodeStatistics.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/load/cache/region/RegionCache.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/load/cache/region/RegionGroupCache.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/load/cache/region/RegionHeartbeatSample.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/load/service/EventService.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/node/NodeManager.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/env/ConfigNodeProcedureEnv.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/env/RegionMaintainHandler.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/node/AddConfigNodeProcedure.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/region/AddRegionPeerProcedure.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/region/CreateRegionGroupsProcedure.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/region/RemoveRegionPeerProcedure.java
- iotdb-core/confignode/src/test/java/org/apache/iotdb/confignode/manager/load/FakeSubscriber.java
- iotdb-core/confignode/src/test/java/org/apache/iotdb/confignode/manager/load/LoadManagerTest.java
- iotdb-core/confignode/src/test/java/org/apache/iotdb/confignode/manager/load/balancer/router/leader/CFDLeaderBalancerTest.java
- iotdb-core/confignode/src/test/java/org/apache/iotdb/confignode/manager/load/balancer/router/leader/GreedyLeaderBalancerTest.java
- iotdb-core/confignode/src/test/java/org/apache/iotdb/confignode/manager/load/balancer/router/leader/LeaderBalancerComparisonTest.java
- iotdb-core/confignode/src/test/java/org/apache/iotdb/confignode/manager/load/cache/RegionGroupCacheTest.java
Updations:
1. The lifecircle(including creation and deletion) of all kinds of LoadCaches are directally managed.
2. Add UT for LoadManager.
> Normalize LoadCache interfaces

- iotdb-client/cli/src/assembly/resources/sbin/start-cli.bat
- iotdb-client/cli/src/assembly/resources/tools/backup.bat
- iotdb-client/cli/src/assembly/resources/tools/export-data.bat
- iotdb-client/cli/src/assembly/resources/tools/export-tsfile.bat
- iotdb-client/cli/src/assembly/resources/tools/import-data.bat
- iotdb-client/cli/src/assembly/resources/tools/load-tsfile.bat
- iotdb-core/confignode/src/assembly/resources/conf/confignode-env.bat
- iotdb-core/confignode/src/assembly/resources/sbin/remove-confignode.bat
- iotdb-core/confignode/src/assembly/resources/sbin/start-confignode.bat
- iotdb-core/confignode/src/assembly/resources/sbin/stop-confignode.bat
- iotdb-core/datanode/src/assembly/resources/conf/datanode-env.bat
- iotdb-core/datanode/src/assembly/resources/sbin/remove-datanode.bat
- iotdb-core/datanode/src/assembly/resources/sbin/start-datanode.bat
- iotdb-core/datanode/src/assembly/resources/sbin/stop-datanode.bat
- iotdb-core/node-commons/src/assembly/resources/sbin/destroy-confignode.bat
- iotdb-core/node-commons/src/assembly/resources/sbin/destroy-datanode.bat
- iotdb-core/node-commons/src/assembly/resources/sbin/start-standalone.bat
- iotdb-core/node-commons/src/assembly/resources/sbin/stop-standalone.bat
about https://github.com/apache/iotdb/issues/12309
> pref(bat): support space in path

- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/compaction/cross/CrossSpaceCompactionSelectorTest.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/compaction/inner/InnerSpaceCompactionSelectorTest.java
Fix compaction selector ut 
https://github.com/apache/iotdb/actions/runs/8866997148/job/24345064159
https://github.com/apache/iotdb/actions/runs/8867012898/job/24345120173
> Fix compaction selector ut

- iotdb-core/node-commons/src/assembly/resources/sbin/health_check.bat
- iotdb-core/node-commons/src/assembly/resources/sbin/health_check.sh
Fix the issue of obtaining Windows directory permissions,and the issue of allocating IoTDB memory for configuration, and add the -- help command
> Fix health_chech bug

- integration-test/src/test/java/org/apache/iotdb/pipe/it/manual/IoTDBPipeMetaLeaderChangeIT.java
- integration-test/src/test/java/org/apache/iotdb/pipe/it/manual/IoTDBPipeMetaRestartIT.java
> Pipe IT: Return directly when SQL retry failed in IT to avoid potential fake failure interference

- integration-test/src/test/java/org/apache/iotdb/subscription/it/dual/IoTDBSubscriptionTopicIT.java
- iotdb-client/service-rpc/src/main/java/org/apache/iotdb/rpc/subscription/config/ConsumerConfig.java
- iotdb-client/service-rpc/src/main/java/org/apache/iotdb/rpc/subscription/payload/response/PipeSubscribeHandshakeResp.java
- iotdb-client/session/src/main/java/org/apache/iotdb/session/subscription/SubscriptionConsumer.java
- iotdb-client/session/src/main/java/org/apache/iotdb/session/subscription/SubscriptionEndpointsSyncer.java
- iotdb-client/session/src/main/java/org/apache/iotdb/session/subscription/SubscriptionProvider.java
- iotdb-client/session/src/main/java/org/apache/iotdb/session/subscription/SubscriptionSessionConnection.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/execution/config/executor/ClusterConfigTaskExecutor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/subscription/receiver/SubscriptionReceiverV1.java
> Subscription: randomly generate consumer group id and consumer id if not exist & validate topic config ahead on DN

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/load/LoadTsFileManager.java
> Load: Avoid NPE when load task ends after clean task's execution

- distribution/src/assembly/all.xml
- distribution/src/assembly/cli.xml
- iotdb-client/cli/src/assembly/resources/conf/logback-backup.xml
- iotdb-client/cli/src/assembly/resources/tools/backup.bat
- iotdb-client/cli/src/assembly/resources/tools/backup.sh
fixed start cli output log issue
> fixed start cli output log issue

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/rescon/memory/SystemInfo.java
Modify direct buffer memory proportion 0.5 -> 0.8
> Modify direct buffer memory proportion

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/protocol/thrift/async/IoTDBDataRegionAsyncConnector.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/protocol/thrift/async/handler/PipeTransferTsFileInsertionEventHandler.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/scheduler/load/LoadTsFileDispatcherImpl.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/client/async/AsyncPipeDataTransferServiceClient.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/connector/client/IoTDBClientManager.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/connector/client/IoTDBSyncClientManager.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/progress/PipeEventCommitter.java
> Pipe: Globally adjust timeout when syncing huge tsfiles & Speed up file transfer after sync task failed

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/extractor/dataregion/realtime/PipeRealtimeDataRegionHybridExtractor.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/conf/CommonConfig.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/conf/CommonDescriptor.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/config/PipeConfig.java
> Pipe: Changed the hybrid switching status to avoid first data is not synced realtime in hybrid mode

- iotdb-client/cli/src/assembly/resources/tools/backup.sh
- iotdb-client/cli/src/main/java/org/apache/iotdb/tool/IoTDBDataBackTool.java
> fixed backup bug
