apache/iotdb

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/mtree/impl/pbtree/schemafile/pagemgr/BTreePageManager.java

previously when check read page whether stale, a page read lock is held and another is being obtained, which may lead to a deadlock.
Now the reading thread will unlock the stale page before obtain the latest one.
<hr>
This PR has:
<hr>

PBTree: Prevent SchemaFile deadlock when check read page

---

integration-test/src/test/java/org/apache/iotdb/pipe/it/IoTDBPipeExtractorIT.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/protocol/airgap/IoTDBAirGapConnector.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/protocol/thrift/async/IoTDBThriftAsyncConnector.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/protocol/thrift/sync/IoTDBThriftSyncConnector.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/protocol/writeback/WriteBackConnector.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/event/common/heartbeat/PipeHeartbeatEvent.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/event/common/tablet/PipeInsertNodeTabletInsertionEvent.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/event/common/tablet/PipeRawTabletInsertionEvent.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/event/common/tablet/TabletInsertionDataContainer.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/event/common/tsfile/PipeTsFileInsertionEvent.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/extractor/historical/PipeHistoricalDataRegionTsFileExtractor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/extractor/realtime/PipeRealtimeDataRegionExtractor.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/pipe/extractor/PipeRealtimeExtractTest.java

This PR is a fix and optimization for https://github.com/apache/iotdb/pull/11757, including the following:
1. Fixing the constructor of `PipeTsFileInsertionEvent` that caused issues with incorrect initialization of event time, and enhancing related integration tests.
2. Filtering out empty events on the sender side to reduce data traffic, while lowering the log level for parsing empty events to debug.
<hr>
This PR has:
<hr>

Pipe: fix constructor of `PipeTsFileInsertionEvent` & filter out empty events on sender side

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/mtree/impl/pbtree/MTreeBelowSGCachedImpl.java

When creating logical view, we should double check node not exists using interface `store.hasChild(parent, childName)` instead of `parent.hasChild(childName)`.

Fix duplicated create logical view in PBTree mode

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/schedule/DriverScheduler.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/scheduler/FixedRateFragInsStateTracker.java

Previously, we use BY_QUERY_CASCADING_ABORTED to abort other FI in same query which may cause users got a error msg that is not timeout.

Make timeout error msg more readable

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/DataRegion.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/DataRegionTest.java

https://jira.infra.timecho.com:8443/browse/TIMECHODB-534
When the DataRegion executes the batch insert interface, we should always apply flush when the whole insertNode executed. Otherwise, some parts of sequence data may overlap.
Set `avg_series_point_number_threshold = 2`, then execute the following code.
```
private static void insertRecords() throws IoTDBConnectionException, StatementExecutionException {
String deviceId = ROOT_SG1_D1;
List<String> measurements = new ArrayList<>();
measurements.add("s1");
measurements.add("s2");
measurements.add("s3");
List<String> deviceIds = new ArrayList<>();
List<List<String>> measurementsList = new ArrayList<>();
List<List<Object>> valuesList = new ArrayList<>();
List<Long> timestamps = new ArrayList<>();
List<List<TSDataType>> typesList = new …
```

Fix insertRecords may cause sequence data overlapped

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/distribution/SourceRewriter.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/plan/planner/distribution/AggregationDistributionTest.java

This PR fixes a potential issue with the distributed plan of GroupLevelNode. When the first group of children of GroupByLevel Node is not selected as the primary FI, it could lead to an excessive number of ExchangeNodes when there are a large number of Nodes. This PR adds a GroupByLevelNode for every group of children whose count is greater than one.

Fix distributed plan of GroupLevelNode

---

iotdb-core/consensus/src/test/java/org/apache/iotdb/consensus/ratis/RatisConsensusTest.java

Enable Leader Transfer UT for preparation on load balancing.
100x tests passed locally.

[RatisConsensus] Enable Leader Transfer UT

---

integration-test/src/test/java/org/apache/iotdb/db/it/utils/TestUtils.java
integration-test/src/test/java/org/apache/iotdb/pipe/it/IoTDBPipeNullValueIT.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/event/common/tablet/TabletInsertionDataContainer.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/pipe/event/PipeTabletInsertionEventTest.java

As title.
<hr>
This PR has:
<hr>

Pipe: fix NPE when parsing TabletInsertionData & add IT for null values insertion

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/task/PipeDataNodeTask.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/agent/task/PipeTaskAgent.java

Currently, when creating a pipe, if there is historical data in the cluster, the pipe will be automatically started. This involves **serially** extracting historical data in each data region. When dealing with large data, timeouts may occur, leading to pipe creation failure. To address this, we are considering parallelizing the above operations using `parallelStream` (inspired by @SteveYurongSu).
<hr>
This PR has:
<hr>

Pipe: Utilize `parallelStream` for concurrent execution of create, start, stop, and drop pipe tasks to enhance performance

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/driver/DataDriver.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/driver/DataDriverContext.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/fragment/FragmentInstanceContext.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/execution/QueryExecution.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/LocalExecutionPlanner.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/plan/LogicalQueryPlan.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/plan/PlanFragment.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/scheduler/FragmentInstanceDispatcherImpl.java

In some big query, like select * from root.db.** that query all devices.
1. the query plan will be memory-consuming and actually LogicalPlan and DistributionPlan is useless now after we dispatch all FIs.
2. these queries' Physical Operator Tree will also be very large and we need to set to null as soon as possible. And in most operators (like TopKOperator),  we've already done that, we will set i-th child to null if we detect there will be no data for that child. However, I found that we still save all SourceOperators in DataDriverContext which just used for initializing `QueryDataSource`. So we should set them to null after `QueryDataSource` being initialized.

Clear useless query resource ASAP

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/mtree/impl/pbtree/schemafile/RecordUtils.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/mtree/impl/pbtree/schemafile/WrappedSegment.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/tools/schema/PBTreeFileSketchTool.java

PBTreeSketchTool support view
E.g
```
=============================
== PBTree File Sketch Tool ==
=============================
== Notice: 
==  Internal/Entity presents as (name, is_aligned, child_segment_address)
==  Measurement presents as (name, data_type, encoding, compressor, alias_if_exist)
=============================
Belong to StorageGroup: [NOT SPECIFIED], segment of SG:0, total pages:2
page_id:0, total_seg:1, spare_from:16382, spare_size:0
seg_id:0, offset:32, address:0, next_seg:-1, [length: 16350, total_records: 1, spare_size:16295,(datatest, null, 10000),]
page_id:1, total_seg:2, spare_from:218, spare_size:16162
seg_id:0, offset:32, address:10000, next_seg:-1, [length: 79, total_records: 1, …
```

PBTreeSketchTool support view

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/DataRegion.java

When concurrently insert data of multiple time partitions, there may be a error appeared. 
The reason of this bug is when call releaseFlushTimeMap by the client thread of another dataRegion, a writeLock should be get first.

Fix ConcurrentModificationException when evict time partition info

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/utils/MultiTsFileDeviceIterator.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/compaction/ReadChunkInnerCompactionTest.java
iotdb-core/tsfile/src/main/java/org/apache/iotdb/tsfile/file/metadata/AlignedTimeSeriesMetadata.java
iotdb-core/tsfile/src/main/java/org/apache/iotdb/tsfile/read/TsFileSequenceReader.java

Fix indexOutOfBounds exception with all empty value chunk of one aligned device in seq inner compaction.

Fix index out of bounds exception in seq inner compaction

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/OperatorTreeGenerator.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/plan/planner/PipelineBuilderTest.java

This PR fixes the issue of incorrectly calculating the ExchangeNum when constructing the pipeline. When the dop is set to 1, we should not override the ExchangeNum of the recursively calculated context with the current context's ExchangeNum.

Fix wrong calculation of ExchangeNum for consumeAllPipelineBreaker when dop = 1

---

integration-test/src/test/java/org/apache/iotdb/confignode/it/cluster/IoTDBClusterRestartIT.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/persistence/executor/ConfigPlanExecutor.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/persistence/partition/DatabasePartitionTable.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/persistence/partition/PartitionInfo.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/persistence/partition/RegionGroup.java

https://issues.apache.org/jira/browse/IOTDB-6291
Local simple test:
Before update:
After update:

[IOTDB-6291] Update RegionGroup configuration when update DataNode configuration

---

iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/config/RatisConfig.java
iotdb-core/consensus/src/test/java/org/apache/iotdb/consensus/ratis/RecoverReadTest.java

1. delete the non-used param writeBufferSize
2. rename the UT since it can pass now.

[RatisConsensus ] Fix Trivial Issues When Upgrading to 3.0.1

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/task/subtask/PipeDataNodeSubtask.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/task/subtask/connector/PipeConnectorSubtask.java

Pipe: let non enriched event forever retry when exception occurred to avoid subtask fake running status recorded at data node task agent

---

iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/ratis/RatisConsensus.java

In some operating systems, creating a consensus group takes longer than the default ratis client timeout of 10 seconds, so the current method of using RaftClient to create a consensus group locally will trigger a retry, resulting in a log error.
This PR solves the problem by changing RPC to LPC

Fix the issue where ConfigNode reports 'ConsensusGroupAlreadyExist' error during startup in some scenarios

---

iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/conf/ConfigNodeConfig.java
iotdb-core/node-commons/src/assembly/resources/conf/iotdb-common.properties

The stability of the migration Leader has been significantly improved after Ratis 3.0 was integrated. We plan to turn on automatic balancing of Schema Region Leader in version 1.3.2 to make the load more even in scenarios with more schema regions. We only need to change one of the default parameters.

Enable SchemaRegion Leader Auto Balance

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/agent/runtime/PipePeriodicalJobExecutor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/load/LoadTsFileManager.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/scheduler/load/LoadTsFileScheduler.java
iotdb-core/node-commons/src/assembly/resources/conf/iotdb-common.properties

Support hot modified to configure the maximum duration allowed for a load task.

Load: Support configure load_clean_up_task_execution_delay_time_seconds of a load task

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/wal/node/WALNode.java

Before this pr, PlanNodeIterator cannot skip the last broken files in the filesToSearch.

Skip broken wal files when iterate the PlanNodeIterator

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/performer/impl/ReadChunkCompactionPerformer.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/utils/executor/readchunk/ReadChunkAlignedSeriesCompactionExecutor.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/compaction/inner/NewReadChunkCompactionPerformerWithAlignedSeriesTest.java

Fix a bug of new read chunk aligned series compaction executor. When chunk metadata in memory is too much, the device time index of compaction target file may lost some device.

Fix update time index after compact aligned series

---

iotdb-core/confignode/src/assembly/resources/conf/iotdb-confignode.properties
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/conf/ConfigNodeConfig.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/conf/ConfigNodeDescriptor.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/consensus/ConsensusManager.java
iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/config/IoTConsensusConfig.java
iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/config/RatisConfig.java
iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/iot/client/IoTConsensusClientPool.java
iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/ratis/RatisConsensus.java
iotdb-core/datanode/src/assembly/resources/conf/iotdb-datanode.properties
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/consensus/DataRegionConsensusImpl.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/consensus/SchemaRegionConsensusImpl.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/client/DataNodeClientPoolFactory.java
iotdb-core/node-commons/src/assembly/resources/conf/iotdb-common.properties
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/client/ClientPoolFactory.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/client/property/ClientPoolProperty.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/conf/CommonConfig.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/conf/CommonDescriptor.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/config/PipeConfig.java
iotdb-core/node-commons/src/test/java/org/apache/iotdb/commons/client/ClientManagerTest.java

sub task of https://github.com/apache/iotdb/issues/11949
1. Add eviction thread to evict clients that are idle more than 1 minute.
2. Merge `core_client_num` and `max_client_num` params, only remain `max_client_num`
3. Add eviction UT
Detailed docs: https://timechor.feishu.cn/docx/GJYjd1vuYoxQr8xNJejcC7Q6nTc

Add the ability for ClientManager to periodically clean up idle objects

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/performer/impl/ReadChunkCompactionPerformer.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/utils/executor/readchunk/ReadChunkAlignedSeriesCompactionExecutor.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/compaction/inner/NewReadChunkCompactionPerformerWithAlignedSeriesTest.java

Reduce stack message of last time check exception for read chunk compaction performer.

Reduce stack message of last time check exception for read chunk compaction performer

---

iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/exception/RatisReadUnavailableException.java
iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/ratis/RatisConsensus.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/scheduler/FragmentInstanceDispatcherImpl.java

Currently, when a node goes offline, Ratis linearizable read requests that are blocked on the offline node will get a not leader error. We need to add retry logic in the dispatch and consensus layer for this case.

Enhance the robustness of Ratis linearizable reads for node offline scenarios

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/task/InsertionCrossSpaceCompactionTask.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/selector/utils/InsertionCrossCompactionTaskResource.java

Skip insertion compaction disk space check because the insertion compaction only move files.

Skip insertion compaction disk space check

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/service/DataNode.java

- Increase retry count
- make log more clear

Enhance DataNode startup probing logic

---

integration-test/src/test/java/org/apache/iotdb/db/it/IOTDBLoadTsFileIT.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/common/MPPQueryContext.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/Coordinator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/schema/ClusterSchemaFetcher.java

IOTDB will acquire serval readlocks when loading data. But because of pr:https://github.com/apache/iotdb/pull/11773, It will cause deadlock when delete data after loading tsfile.

Fix deadlock when delete timeseries after loading data.

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/utils/executor/readchunk/ReadChunkAlignedSeriesCompactionExecutor.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/compaction/inner/NewReadChunkCompactionPerformerWithAlignedSeriesTest.java

Fix read chunk compaction performer null pointer exception. If a chunk metadata of one value column in aligned series is null, and other file in compaction does not contain current value column, a null pointer exception may throw.

Fix read chunk compaction performer null pointer exception

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/load/LoadTsFileMemoryManager.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/AnalyzeVisitor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/LoadTsfileAnalyzer.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/scheduler/load/LoadTsFileScheduler.java

use try...finally to ensure releasing memory correctly , especially in READ_ONLY mode

Load: Correctly release memory when system is in READ_ONLY mode

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/wal/node/WALNode.java

NPE occurs because CheckpointManager.getOldestUnpinnedMemTableInfo() may return null.

Fix wal delete npe when calculating effective info ration

---

iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/consensus/statemachine/ConfigRegionStateMachine.java

SimpleConsensus logs are restored in the wrong order during startup.

Fixed issue where ConfigNode might recover incorrectly under SimpleConsensus

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/task/subtask/connector/PipeConnectorSubtask.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/task/subtask/connector/PipeConnectorSubtaskLifeCycle.java

Pipe: fix connector subtasks can not be stopped and restarted after exception reporting by connector subtasks

---

integration-test/src/test/java/org/apache/iotdb/db/it/IoTDBRepairDataIT.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/selector/estimator/AbstractCompactionEstimator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/selector/estimator/AbstractCrossSpaceEstimator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/selector/estimator/AbstractInnerSpaceEstimator.java

1. Fix estimating compaction memory without acquire read lock. This PR acquire the lock of compaction source files and check whether the status is DELETED.
2. Fix RepairDataIT

Fix estimating compaction memory without acquire read lock

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/fragment/QueryContext.java

Fix concurrent bug in QueryContext, use ConcurrentHashMap and CopyOnWriteArraySet instead of HashMap and HashSet.

Fix concurrent bug in QueryContext

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/load/LoadTsFileManager.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/scheduler/load/LoadTsFileScheduler.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/DataRegion.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/flush/MemTableFlushTask.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/tsfile/TsFileResource.java

Pipe: Report load tsfile points to flush point metric timeseries in root.__system 

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/DataRegion.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/LastFlushTimeMapTest.java

Before this fixing, if there is not only one time partition in system, the last flush time of non-latest partition cannot recover because of a redundant `partitionFiles.getKey() == latestPartitionId` judgement condition. 
Execute the following sql.
```
insert into root.sg.d1(time,s1) values(604799999, 1);
flush;
insert into root.sg.d1(time,s1) values(604800000, 1);
flush
```
Then restart IoTDB and execute
```
insert into root.sg.d1(time,s1) values(1, 1);
```
You will see the timestamp 1 was inserted into sequence space.

Fix non-latest partition last flush time cannot recover

---

integration-test/src/test/java/org/apache/iotdb/pipe/it/IoTDBPipeSyntaxIT.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/execution/config/executor/ClusterConfigTaskExecutor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/parser/ASTVisitor.java

1. Filter back quote in pipe name, but it's still necessary to and back quote if there is illegal character in pipe name.
2. Fix bug:  result of pipe's query statement contains back quote is incorrect.

Pipe: result of show pipes statement is incorrect when it contains back quoted pipe names

---

iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/agent/task/PipeTaskAgent.java

Change the execution flow of the `stop pipe` : 
1. drop the pipe task firstly 
2. then create a new pipe task with the same pipeMeta.
When the pipe is dropped and re-created with the same pipeMeta, it will re-trigger the collection of historical data, and most of the files it pins are tsfile files not wal, because the wal files are flushed. By taking advantage of this property, we can make sure that the subsequent pins are new files, not old wal files, thus avoiding the wal stacking.

Pipe: stop pipe using restarting strategy to unpin the wal's reference count to avoid WAL stacking

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/DataRegion.java

The existing mechanism will have multiple threads modify the `partitionMaxFileVersions` property, which may cause a concurrency problem. This PR will fix an exception raised by a concurrency problem
Have a probability will throw a ConcurrentModificationException
ConcurrentModificationException will not happen again

Storage Engine: fix wal delete thread exception because multi thread safety question

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/mtree/impl/pbtree/schemafile/AliasIndexPage.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/mtree/impl/pbtree/schemafile/ISegment.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/mtree/impl/pbtree/schemafile/ISegmentedPage.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/mtree/impl/pbtree/schemafile/InternalPage.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/mtree/impl/pbtree/schemafile/SegmentedPage.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/mtree/impl/pbtree/schemafile/WrappedSegment.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/mtree/impl/pbtree/schemafile/pagemgr/PageManager.java

The recent deadlock issues are primarily attributed to the double-bucket index design. Each thread maintains a local collection that organizes pages into buckets based on available space, while the PageManager maintains another gloabl set. When a write thread requires a page for writing/updating, it first checks its local buckets and retrieves pages without locking(as they are already locked). If no suitable page is found locally, the thread then accesses the global buckets, where it must retrieve pages with a lock.
The issue arises when a page, which is appropriate for the expected size and referred by the thread previously, is recorded in the global buckets but not in the local ones. This results in the page being locked twice but unlocked only once, leading to a deadlock. Specifically, …

PBTree: Fix Dead Lock and Refactor write/update inteface

---

integration-test/src/test/java/org/apache/iotdb/db/it/IoTDBDeletionIT.java
integration-test/src/test/java/org/apache/iotdb/db/it/IoTDBFlushQueryIT.java
integration-test/src/test/java/org/apache/iotdb/db/it/IoTDBInsertMultiRowIT.java
integration-test/src/test/java/org/apache/iotdb/db/it/IoTDBMultiDeviceIT.java
integration-test/src/test/java/org/apache/iotdb/db/it/aligned/IoTDBAlignedDataDeletionIT.java
integration-test/src/test/java/org/apache/iotdb/db/it/auth/IoTDBSystemPermissionIT.java
integration-test/src/test/java/org/apache/iotdb/session/it/IoTDBSessionComplexIT.java
iotdb-core/antlr/src/main/antlr4/org/apache/iotdb/db/qp/sql/IoTDBSqlParser.g4
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/parser/ASTVisitor.java

Remove sql `merge` because it is useless and may cause some performance problems.

Remove sql `merge`

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/load/LoadTsFileManager.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/DataRegion.java

After loading about 1_200_000 files into the storage engine, the system threw OOM exception.
After careful check, it was found that the current load tsfile operation does not trigger the last flush time map & tsfile resource degrading.

Load: Trigger last flush time map & tsfile resource degrading after successful load

---

iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/exception/RatisReadUnavailableException.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/thrift/impl/DataNodeInternalRPCServiceImpl.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/executor/RegionExecutionResult.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/executor/RegionReadExecutor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/scheduler/FragmentInstanceDispatcherImpl.java
iotdb-protocol/thrift-datanode/src/main/thrift/datanode.thrift

Retry the request for ServerNotReadyException

Fixed Ratis query not retrying when DataNode restarts

---

integration-test/src/test/java/org/apache/iotdb/pipe/it/IoTDBPipeAlterIT.java
iotdb-api/pipe-api/src/main/java/org/apache/iotdb/pipe/api/customizer/parameter/PipeParameters.java
iotdb-core/antlr/src/main/antlr4/org/apache/iotdb/db/qp/sql/IoTDBSqlParser.g4
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/persistence/pipe/PipeTaskInfo.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/pipe/task/AlterPipeProcedureV2.java
iotdb-core/confignode/src/test/java/org/apache/iotdb/confignode/procedure/impl/pipe/task/AlterPipeProcedureV2Test.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/execution/config/executor/ClusterConfigTaskExecutor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/parser/ASTVisitor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/statement/metadata/pipe/AlterPipeStatement.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/agent/task/PipeTaskAgent.java
iotdb-protocol/thrift-confignode/src/main/thrift/confignode.thrift

As title.
<hr>
This PR has:
<hr>

Pipe: support replace and modify mode for alter pipe sql

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/cache/schema/DataNodeDevicePathCache.java
iotdb-core/node-commons/src/assembly/resources/conf/iotdb-common.properties

The DataNodeDevicePathCache should not decrease the memory size of memtable. It should use the free memory in instead.

DataNodeDevicePathCache should use free memory of memtable

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/agent/task/PipeTaskDataNodeAgent.java

As the title said. This logic may cause forever restarting when tsFile num is very large or the sending itself is slow.
<hr>
This PR has:
<hr>

Pipe: Removed mayLinkedTsFileCountReachDangerousThreshold judgement from stuck restart logic

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/mqtt/MPPPublishHandler.java

As we can see in the interface java doc: `The receiver MUST release the payload of the message, either by calling super.onPublish, or by calling msg.getPayload.release() directly.`, otherwise the memory will leak.
we use `MQTTClient` in `example/mqtt/src/main/java/org/apache/iotdb/mqtt`, changes like:
```
/*
* Licensed to the Apache Software Foundation (ASF) under one
* or more contributor license agreements.  See the NOTICE file
* distributed with this work for additional information
* regarding copyright ownership.  The ASF licenses this file
* to you under the Apache License, Version 2.0 (the
* "License"); you may not use this file except in compliance
* with the License.  You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by …
```

[IOTDB-6296] Fix memory leak in MQTTService

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/event/common/tsfile/PipeTsFileInsertionEvent.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/extractor/realtime/PipeRealtimeDataRegionHybridExtractor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/extractor/realtime/PipeRealtimeDataRegionLogExtractor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/extractor/realtime/epoch/TsFileEpoch.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/extractor/realtime/epoch/TsFileEpochManager.java

Pipe: fixed potential lose point bug caused by cancelled flush of historical extractor

---

integration-test/src/test/java/org/apache/iotdb/db/it/aligned/IoTDBAlignedSeriesQueryIT.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/SeriesScanUtil.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/read/reader/series/AlignedSeriesScanPredicatePushDownTest.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/read/reader/series/SeriesScanLimitOffsetPushDownTest.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/read/reader/series/SeriesScanPredicatePushDownTest.java
iotdb-core/tsfile/src/main/java/org/apache/iotdb/tsfile/read/common/block/TsBlockUtil.java
iotdb-core/tsfile/src/main/java/org/apache/iotdb/tsfile/read/reader/page/AlignedPageReader.java

**[Reproduction Method]**
- **Config:**
maxNumberOfPointsInPage = 2
maxTsBlockLineNumber = 3
- **Insert:**
```SQL
CREATE DATABASE root.sg1;
create aligned timeseries root.sg1.d1(s1 FLOAT encoding=RLE, s2 INT32 encoding=Gorilla compression=SNAPPY, s3 INT64, s4 BOOLEAN, s5 TEXT);
insert into root.sg1.d1(time, s1, s2, s3, s4, s5) aligned values(9, 9.0, 9, 9, FALSE, 'aligned_test9');
insert into root.sg1.d1(time, s2, s3, s4, s5) aligned values(10, 10, 10, TRUE, 'aligned_test10');
flush;
insert into root.sg1.d1(time, s1, s2, s3) aligned values(11, 11.0, 11, 11);
insert into root.sg1.d1(time, s1, s2, s3) aligned values(12, 12.0, 12, 12);
insert into root.sg1.d1(time, s1, s2, s3) aligned values(13, 13.0, 13, 13);
insert into root.sg1.d1(time, s1, s2, s3) aligned values(14, 14.0, 14, 14);
insert …
```

[IOTDB-6299] Fix bug in merging overlapped data process caused by filter & offset push down

---

example/session/src/main/java/org/apache/iotdb/SessionExample.java
iotdb-core/datanode/src/assembly/resources/conf/iotdb-datanode.properties
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/DataRegion.java

We found the flush submit task would stack a lot when write multiple time partitions concurrently. 
The reason of this phenomenon is that the flush submit task check whether is the TsFileProcessor closing in the **WriteLock**  of DataRegion. This check logic should be move out of the WriteLock. 
Moreover, the closingSequenceTsFileProcessor and closingUnSequenceTsFileProcessor can be simplify to the HashSet instead. 
After this modification, the write performance increased about 10%.

Optimize flushing memtable check

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/utils/DateTimeUtils.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/utils/DateTimeUtilsTest.java

IoTDB doesn't support timestamp format like `2024-02-22T16:36:34.67`, which should be equivalent to `2024-02-22T16:36:34.670`.
After referred the code of JDK below, we can simply support it.

[IOTDB-6302] Enhance the support of ISO_LOCAL_DATE_TIME timestamp format

---

integration-test/src/main/java/org/apache/iotdb/it/env/cluster/env/AbstractEnv.java
integration-test/src/test/java/org/apache/iotdb/confignode/it/cluster/IoTDBClusterRestartIT.java
integration-test/src/test/java/org/apache/iotdb/db/it/IoTDBRecoverIT.java
integration-test/src/test/java/org/apache/iotdb/db/it/IoTDBRecoverUnclosedIT.java
integration-test/src/test/java/org/apache/iotdb/db/it/utils/TestUtils.java
integration-test/src/test/java/org/apache/iotdb/pipe/it/IoTDBPipeClusterIT.java
integration-test/src/test/java/org/apache/iotdb/pipe/it/IoTDBPipeLifeCycleIT.java

in https://github.com/apache/iotdb/pull/12022.
I catch exceptions during the restart cluster check process, then return a boolean value to indicate the result of the restart. This approach makes the error log unclear when there is a problem.
now revert it

IT: revert some changes in restart IT to make the error log clear when failed to restart

---

integration-test/src/test/java/org/apache/iotdb/db/it/auth/IoTDBAuthIT.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/auth/entity/RoleTest.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/auth/authorizer/BasicAuthorizer.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/auth/entity/Role.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/auth/user/BasicUserManager.java

In this pr:
1. Role cannot be granted to root
2. Fix root's privilges lost when upgrade.

fix.root privileges lost and grant role.

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/mtree/impl/pbtree/memory/MemoryManager.java

Fix VolatileSubtreeIterator missing update buffer if all nodes in new buffer are not qualified.

Fix VolatileSubtreeIterator missing update buffer if all nodes in new buffer are not qualified

---

iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/load/balancer/PartitionBalancer.java

Log when the target DataRegionGroup is unavailable currently.

Add logs for data partition allocation

---

integration-test/src/test/java/org/apache/iotdb/confignode/it/cluster/IoTDBClusterStartIT.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/ClusterManager.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/node/NodeManager.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/agent/runtime/PipeRuntimeAgent.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/protocol/airgap/IoTDBAirGapConnector.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/protocol/thrift/async/IoTDBThriftAsyncClientManager.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/protocol/thrift/sync/IoTDBThriftSyncClientManager.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/receiver/thrift/IoTDBThriftReceiverV1.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/execution/config/executor/ClusterConfigTaskExecutor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/execution/config/metadata/ShowClusterIdTask.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/service/DataNode.java
iotdb-protocol/thrift-confignode/src/main/thrift/confignode.thrift

IoTDBDescriptor.getInstance().getConfig().getClusterId()

Cache clusterId in IoTDBConfig

---

iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/consensus/statemachine/ConfigRegionStateMachine.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/ClusterManager.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/ConfigManager.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/consensus/ConsensusManager.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/cq/CQManager.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/pipe/coordinator/runtime/PipeMetaSyncer.java

By splitting the creation and launch of consensusManager, we avoid some redundant code.
We can now ensure that consensusManager.get () is never null when notifyLeaderReady is invoked

Optimize ConfigNode ConsensusManager init logic

---

integration-test/src/test/java/org/apache/iotdb/db/it/IoTDBSimpleQueryIT.java
integration-test/src/test/java/org/apache/iotdb/db/it/IoTDBSimpleQueryStandaloneIT.java
iotdb-core/antlr/src/main/antlr4/org/apache/iotdb/db/qp/sql/IdentifierParser.g4
iotdb-core/antlr/src/main/antlr4/org/apache/iotdb/db/qp/sql/IoTDBSqlParser.g4
iotdb-core/antlr/src/main/antlr4/org/apache/iotdb/db/qp/sql/SqlLexer.g4
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/common/header/ColumnHeaderConstant.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/common/header/DatasetHeaderFactory.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/AnalyzeVisitor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/execution/memory/StatementMemorySourceVisitor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/parser/ASTVisitor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/statement/StatementVisitor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/statement/metadata/ShowCurrentTimestampStatement.java

issue: https://issues.apache.org/jira/browse/IOTDB-6305

[IOTDB-6305] Add show current_timestamp statement 

---

iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/IConsensus.java
iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/iot/IoTConsensus.java
iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/iot/IoTConsensusServerImpl.java
iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/ratis/RatisConsensus.java
iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/simple/SimpleConsensus.java

Split configuration and add resetPeerList for region migration, see [feishu-doc](https://apache-iotdb.feishu.cn/docx/MC8gdgTgOoG9eYx9MIpcrtB9n4e) for details.

Split configuration and add resetPeerList for region migration

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/service/IoTDBShutdownHook.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/StorageEngine.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/wal/WALManager.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/wal/buffer/WALBuffer.java

When the walDeleteThread and a flush command delete the outdated wal file concurrently, the following error may appear.
To fix it, the flush command thread should submit the wal delete task to walDeleteThread instead of executing it by itself.

Fix fail to read memTable ids from the wal file

---

iotdb-connector/flink-iotdb-connector/src/main/java/org/apache/iotdb/flink/IoTDBSink.java

flink-iotdb-connector: IoTDBSink throws NPE

---

iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/load/balancer/RouteBalancer.java

https://issues.apache.org/jira/browse/IOTDB-6309

[IOTDB-6309] Lager interval for auto ratis leader balance

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/mtree/impl/pbtree/mnode/container/CachedMNodeContainer.java

There is a problem with the implementation of the CachedMNodeContainerIterator in CachedMNodeContainer. The problem manifests itself in a logical error in the changestatus function that is repeatedly switched to UpdateBuffer and ignores ChildCache

fix bug : the change logic error of the CachedMNodeContainerIterator

---

integration-test/src/test/java/org/apache/iotdb/confignode/it/procedure/IoTDBProcedureIT.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/ConfigManager.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/IManager.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/ProcedureManager.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/ProcedureExecutor.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/testonly/AddNeverFinishSubProcedureProcedure.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/testonly/CreateManyDatabasesProcedure.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/testonly/MakeChildProcedure.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/testonly/NeverFinishProcedure.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/testonly/ProcedureTestUtils.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/store/ProcedureFactory.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/store/ProcedureType.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/service/thrift/ConfigNodeRPCServiceProcessor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/client/ConfigNodeClient.java
iotdb-protocol/thrift-confignode/src/main/thrift/confignode.thrift

The previous code omitted an `!` when restoring the procedure, allowing the parent procedure to continue executing before the sub-procedure was finished. This issue has been fixed and an integration test has been added.

Fix bug: parent procedure should not execute before sub-procedure finished

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/protocol/legacy/IoTDBLegacyPipeConnector.java

As title.
CI fail examples:
* https://github.com/apache/iotdb/actions/runs/8220193293/job/22479018547
* https://github.com/apache/iotdb/actions/runs/8220193293/job/22479018451

Pipe: fix legacy receiver's unsafe execution race problem (fix IoTDBPipeDataSinkIT.testLegacyConnector)

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/DataRegion.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/tsfile/TsFileManager.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/utils/TimePartitionUtils.java

we use timefilter to filter useless timepartition instead of getting all of them and then filter tsfile in them one by one.
We insert `0~9999` points whose timestamp is also `0~9999` and execute `flush` after each point insert and then insert one point with timestamp now(). As so, we will get two partitions, one contains 10,000 tsfiles, another one contains only one tsfile.
execute the following sql: (only the last tsfile satisfies)
```
select s1 from root.db.d1 where time > now() - 1h;
```
before opt, the time for query init tsfile list are:(about 2.5ms)
```
3057000
2356292
3258834
2415417
2876041
2395750
2564833
```
after opt, the time for query init tsfile list are:(about 0.047 ms)
```
47500
39792
33875
31958
37584
56666
45709
```

[IOTDB-6310] Optimize for query resource init

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/task/InnerSpaceCompactionTask.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/io/CompactionTsFileInput.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/io/CompactionTsFileReader.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/repair/RepairDataFileScanUtil.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/schedule/CompactionScheduler.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/selector/estimator/AbstractCompactionEstimator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/selector/estimator/AbstractCrossSpaceEstimator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/selector/estimator/AbstractInnerSpaceEstimator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/selector/impl/RewriteCrossSpaceCompactionSelector.java
iotdb-core/tsfile/src/main/java/org/apache/iotdb/tsfile/exception/StopReadTsFileByInterruptException.java
iotdb-core/tsfile/src/main/java/org/apache/iotdb/tsfile/read/TsFileSequenceReader.java
iotdb-core/tsfile/src/main/java/org/apache/iotdb/tsfile/read/reader/LocalTsFileInput.java

fix error log caused by ClosedByInterruptException in compaction module

fix error log caused by ClosedByInterruptException in compaction module

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/mtree/impl/mem/snapshot/MemMTreeSnapshotUtil.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/tools/schema/SRStatementGenerator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/tools/schema/SchemaRegionSnapshotParser.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/utils/SchemaRegionSnapshotParserTest.java

In this pr:
1. Support translating snapshot file to statements, so you can use schema region snapshot parser to construct a same Schema tree in another cluster.
2. Add some UTs.
3. refine memory use when translating schema region snapshot. The node num depends on the longest path and Its children num. If one path is root.t1.t2.t3, and It has 100 measurements, so the node num will be 4 + 100.

Support schema region snapshot parser.

---

integration-test/src/test/java/org/apache/iotdb/libudf/it/dprofile/DProfileIT.java
library-udf/pom.xml
library-udf/src/main/java/org/apache/iotdb/library/frequency/UDFEnvelopeAnalysis.java
library-udf/src/test/java/org/apache/iotdb/library/UDFEnvelopeTest.java

This PR adds a UDF function for envelope demodulation analysis. The function of envelope demodulation analysis is designed to realize the demodulation and envelope extraction of the signal by inputting one-dimensional floating-point numbers and the modulation frequency specified by the user. The goal of demodulation is to extract parts of interest from complex signals and make them easier to understand. For example, demodulation can find the envelope of the signal, that is, the trend of amplitude change. The realization principle is to convert the time domain signal into the frequency domain signal, and the algorithms involved include Hilbert transform (Hilbert), fast Fourier transform (FFT), fast Fourier inverse transform (IFFT) and so on.

UDF: add an udf function for envelope demodulation analysis

---

iotdb-client/session/src/main/java/org/apache/iotdb/session/NodesSupplier.java

More details about this bug can be seen in https://jira.infra.timecho.com:8443/browse/TIMECHODB-607.
The reason for this bug is that we call the SessionPool.close() method and in this method we will also call `NodeSupplier.close()` which will call client.close(), so in server, we will clear all the info for this connection. However, at the same time, the NodeSupplier.run is also being called, it will try to do the `show datanodes` query, and then the exception will throw.

Fix Concurrent bug between NodeSupplier.close() and its run()

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/wal/WALManager.java

Because the disk usage of wal nodes may change when comparing their delete priority, which violates comparison method's  general contract. So, I cache the disk usage in a map and use the values in the map to sort wal nodes.

Fix wal delete sort method

---

iotdb-client/jdbc/src/main/java/org/apache/iotdb/jdbc/IoTDBConnection.java
iotdb-client/jdbc/src/main/java/org/apache/iotdb/jdbc/IoTDBStatement.java
iotdb-client/service-rpc/src/main/java/org/apache/iotdb/rpc/BaseRpcTransportFactory.java
iotdb-client/service-rpc/src/main/java/org/apache/iotdb/rpc/DeepCopyRpcTransportFactory.java
iotdb-client/service-rpc/src/main/java/org/apache/iotdb/rpc/TCompressedElasticFramedTransport.java
iotdb-client/service-rpc/src/main/java/org/apache/iotdb/rpc/TElasticFramedTransport.java
iotdb-client/service-rpc/src/main/java/org/apache/iotdb/rpc/TSnappyElasticFramedTransport.java
iotdb-client/service-rpc/src/main/java/org/apache/iotdb/rpc/TimeoutChangeableTFastFramedTransport.java
iotdb-client/service-rpc/src/main/java/org/apache/iotdb/rpc/TimeoutChangeableTSnappyFramedTransport.java
iotdb-client/service-rpc/src/main/java/org/apache/iotdb/rpc/ZeroCopyRpcTransportFactory.java
iotdb-client/session/src/main/java/org/apache/iotdb/session/SessionConnection.java
iotdb-client/session/src/main/java/org/apache/iotdb/session/ThriftConnection.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/service/thrift/ConfigNodeRPCService.java
iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/iot/client/SyncIoTConsensusServiceClient.java
iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/iot/service/IoTConsensusRPCService.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/receiver/legacy/IoTDBLegacyPipeReceiverAgent.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/client/ConfigNodeClient.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/exchange/MPPDataExchangeService.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/service/DataNodeInternalRPCService.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/service/RPCService.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/client/sync/SyncConfigNodeIServiceClient.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/client/sync/SyncDataNodeInternalServiceClient.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/client/sync/SyncDataNodeMPPDataExchangeServiceClient.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/connector/client/IoTDBSyncClient.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/service/AbstractThriftServiceThread.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/service/ThriftServiceThread.java
iotdb-core/node-commons/src/test/java/org/apache/iotdb/commons/client/mock/MockInternalRPCService.java

Previously, these methods of TElasticFramedTransport are not override implemented.
TBinaryProtocol will allocate new byte array and copy from frame buffer. After this pr, TBinaryProtocol can wrap the byte buffer with the reference of frame buffer segment, which eliminates the cost of memory allocation and memory copying. 
We use benchmark to evaluate this optimization (Insert Tablet with text value type):
* Before
* After

Thrift zero-copy optimization for TElasticFramedTransport

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/DataRegion.java

https://apache-iotdb.feishu.cn/docx/RrBrdXHPgoJTcxxoPxMc8eNXndd
When all data in a memtable is deleted, the memtable is flushed by mechanisms such as Timed flush, resulting in an empty Tsfile. When an empty file is generated, the flush thread takes the closeQueryLock and then tries to delete the empty file by taking the TsFileManager write lock. If a query thread holds the TsFileManager read lock and tries to acquire the closeQueryLock read lock, it will block because the flush thread holds the closeQueryLock write lock first, creating a deadlock problem.

Fix deadlock when flush an empty TsFile and query concurrently

---

iotdb-client/service-rpc/src/main/java/org/apache/iotdb/rpc/DeepCopyRpcTransportFactory.java
iotdb-client/service-rpc/src/main/java/org/apache/iotdb/rpc/ZeroCopyRpcTransportFactory.java

Fixed the bug that TimeoutChangeableTFastFramedTransport is unused so that timeout changing is disabled in thrift transferring

---

iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/conf/ConfigNodeConfig.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/wal/WALManager.java

When dataregion using ratis consensus and execute a `flush` command, an 301 error appears.
The reason of this bug is syncDeleteOutdatedFilesInWALNodes doesn't consider that walDeleteThread is null when dataregion using ratis consensus.

Fix flush command failed when dataregion using ratis consensus

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/fragment/FragmentInstanceContext.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/fragment/QueryStatistics.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/SeriesScanUtil.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/metric/QueryRelatedResourceMetricSet.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/metric/SeriesScanCostMetricSet.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/LocalExecutionPlanner.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/read/reader/chunk/MemChunkReader.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/read/reader/common/Element.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/read/reader/common/PriorityMergeReader.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/transformation/builder/EvaluationDAGBuilderTest.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/read/reader/common/FakedSeriesReader.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/service/metric/enums/Metric.java
iotdb-core/tsfile/src/main/java/org/apache/iotdb/tsfile/read/common/BatchData.java
iotdb-core/tsfile/src/main/java/org/apache/iotdb/tsfile/read/common/block/TsBlock.java
iotdb-core/tsfile/src/main/java/org/apache/iotdb/tsfile/read/reader/IPointReader.java
iotdb-core/tsfile/src/main/java/org/apache/iotdb/tsfile/read/reader/page/LazyLoadAlignedPagePointReader.java

Grafana screenshot is as below:
1. query estimated memory size:
2. max unsequence reader used memory:

Add more query metrics for estimated memory and max overlapped page

---

iotdb-client/session/src/main/java/org/apache/iotdb/session/Session.java
iotdb-client/session/src/main/java/org/apache/iotdb/session/SessionConnection.java

more details can be seen in https://jira.infra.timecho.com:8443/browse/TIMECHODB-611.
If a `SessionConnection`'s first node in its nodeurls is unavailable and it will try to reconnect to other nodes in nodeurls, and it will succeed to connect to other nodes, however currently its `endPointToSessionConnection` and `deviceIdToEndpoint` are not inited, so the logic in reconnect may cause NPE.

Fix NPE in SessionConnection while first node in nodeurls is unavailable

---

iotdb-api/udf-api/src/main/java/org/apache/iotdb/udf/api/utils/RowImpl.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/expression/visitor/ColumnTransformerVisitor.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/udf/builtin/String/UDTFConcat.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/udf/builtin/UDTFConst.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/udf/builtin/UDTFConstE.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/udf/builtin/UDTFConstPi.java
iotdb-core/tsfile/src/main/java/org/apache/iotdb/tsfile/read/common/block/column/TimeColumn.java

For single row interface, you can call `row.getTime()` to get the timestamp value of current row.
```java
@Override
public Object transform(Row row) throws Exception {
return row.getTime();
}
```
For batch interface, **the last column is the time column**, use `.getLongs()` to acquire the timestamp values of all rows.
```java
@Override
public void transform(Column[] columns, ColumnBuilder builder) throws Exception {
long[] timestamps = columns[columns.size() - 1].getLongs();
int count = columns[0].getPositionCount();
for (int i = 0; i < count; i++) {
builder.writeLong(timestamps[i]);
}
}
```

Append time column at the end of input columns in mappable UDTF

---

iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/pipe/runtime/PipeMetaSyncProcedure.java

Pipe: avoid executing too many PipeMetaSyncProcedure after system reboot

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/execution/config/metadata/ShowFunctionsTask.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/conf/IoTDBConstant.java

When CNs execute `DROP FUNCTION`, the deletion will fail if one of DNs went down, but other DNs will still be affected, i.e., they will drop relevant information about this function.
After that, CNs consider that the to-be-deleted function still exists, so when it executes `SHOW FUNCTIONS`, it sends its information to DNs. It's DN's responsibility to add more detail on top of that.
However, from DN's perspective, the function is already dropped. So it will throw Null Pointer Exception.
In this PR, we display `UNKNOWN` if DN cannot find function, and thus avoids this issue.

Display 'UNKNOWN' in `SHOW FUNCTIONS` when CN accidentally drop DN's function.

---

example/udf/src/main/java/org/apache/iotdb/udf/UDAFExample.java
integration-test/src/main/java/org/apache/iotdb/db/query/udf/example/UDAFAvg.java
integration-test/src/main/java/org/apache/iotdb/db/query/udf/example/UDAFCount.java
integration-test/src/main/java/org/apache/iotdb/db/query/udf/example/UDAFSum.java
iotdb-api/udf-api/src/main/java/org/apache/iotdb/udf/api/UDAF.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/aggregation/UDAFAccumulator.java

In order to keep consistent with UDTF, which put timestamp value as the last field of row.
We left rotate the first column (i.e. time column) to the end of input columns for UDAF.
If you want to update state, for example, accumulate value for sum UDAF, you may change your implementation from:
```java
// Origin
state.sum += columns[1].getFloat(i);
```
to
```java
// After this PR
state.sum += columns[0].getFloat(i);
```
The latter looks more intuitive.

Left rotate time column to the end of input columns in UDAF

---

integration-test/src/test/java/org/apache/iotdb/pipe/it/autocreate/IoTDBPipeProcessorIT.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/event/common/tsfile/PipeTsFileInsertionEvent.java

Pipe: filtered empty tsFiles which should not be parsed or reported

---

iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/consensus/request/auth/AuthorPlan.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/persistence/schema/CNPhysicalPlanGenerator.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/persistence/schema/CNSnapshotFileType.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/persistence/schema/ConfignodeSnapshotParser.java
iotdb-core/confignode/src/test/java/org/apache/iotdb/confignode/persistence/CNPhysicalPlanGeneratorTest.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/tools/schema/SRStatementGenerator.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/utils/SchemaRegionSnapshotParserTest.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/auth/entity/PathPrivilege.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/auth/entity/Role.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/utils/AuthUtils.java

In this pr:
1. Support Confignode snapshot parser. Pipe can use this parser to translate confignode's snapshot file to ConfignodePhysical Plan.
2.  Fix some bugs in Schemaregion snapshot parser.
3. Support logical view in Schemaregion snapshot parser.

support config snapshot parser

---

iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/ratis/utils/Retriable.java
iotdb-core/consensus/src/test/java/org/apache/iotdb/consensus/ratis/DiskGuardianTest.java
iotdb-core/consensus/src/test/java/org/apache/iotdb/consensus/ratis/TestUtils.java

In the following releases of Ratis, the `JavaUtils.attemptUntilTrue` will be removed.

[RatisConsensus] Remove JavaUtils dependencies

---

iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/service/StartupChecks.java

For more information, visit https://github.com/oracle/graal/issues/8638.
```
125  [main] INFO  o.a.i.commons.service.StartupChecks - JDK version is 17. 
125  [main] INFO  o.a.i.commons.service.StartupChecks - JVM version is Java HotSpot(TM) 64-Bit Server VM 17.0.10+11-LTS-jvmci-23.0-b27. 
126  [main] ERROR  o.a.i.commons.service.StartupChecks - Perhaps you are using GraalVM, which is strongly not recommended. Using GraalVM may cause strange problems after the system runs for a while. Please check your JVM version.
```

Warn user if they use GraalVM

---

iotdb-core/datanode/src/assembly/resources/conf/datanode-env.bat
iotdb-core/datanode/src/assembly/resources/conf/datanode-env.sh

We have observed performance losses after adding `-XX:-UseBiasedLock` in some cases. Thus we remove it.
Detailed docs: https://apache-iotdb.feishu.cn/docx/JNvTdo0oOoOJr7xq3QecRe9Wnhc

Remove -XX:-UseBiasedLock in IoTDB JVM options

---

iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/auth/authorizer/BasicAuthorizer.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/auth/authorizer/LocalFileAuthorizer.java

The visibility of some methods prevented being able to implement custom authenticators outside of the org.apache.iotdb.commons.auth.authorizer package.
This should now be fixed.

feat: Refactored the visibility of some methods to make it possible to add BasicAuthorizer implementations in other packages.

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/driver/DataDriver.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/fragment/FragmentInstanceContext.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/SeriesScanUtil.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/buffer/TimeSeriesMetadataCache.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/performer/impl/ReadPointCompactionPerformer.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/read/QueryDataSource.java
iotdb-core/tsfile/src/main/java/org/apache/iotdb/tsfile/file/metadata/PlainDeviceID.java

We can memorize the order time and satisfied information for each Seq and Unseq Resource instead of getting it from resource ITimeIndex map each time, in which way we can save much time by avoiding time consuming map.get();

Optimize SeriesScanUtil by memorizing the order time and satisfied information for each Seq and Unseq Resource

---

iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/iot/client/DispatchLogHandler.java

When the wal file is damaged, it will cause follower synchronization failure, causing leader synchronization to get stuck and infinite retries until wal blocks writing. The fix is to skip retrying send batches caused by TApplicationException and print a warn log.

IoTConsensus: Skip retry sending batch caused by TApplicationException

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/agent/runtime/PipePeriodicalJobExecutor.java

jstack:
```
"pool-69-IoTDB-IoTConsensusRPC-Processor-3" #932 prio=5 os_prio=0 tid=0x00007faa3000e000 nid=0x1459a9 waiting for monitor entry [0x00007faa8c26c000]
java.lang.Thread.State: BLOCKED (on object monitor)
at org.apache.iotdb.db.pipe.agent.runtime.PipePeriodicalJobExecutor.register(PipePeriodicalJobExecutor.java:63)
- waiting to lock <0x00000001c0154100> (a org.apache.iotdb.db.pipe.agent.runtime.PipePeriodicalJobExecutor)
at org.apache.iotdb.db.pipe.agent.runtime.PipeDataNodeRuntimeAgent.registerPeriodicalJob(PipeDataNodeRuntimeAgent.java:199)
at org.apache.iotdb.db.pipe.resource.memory.PipeMemoryManager.<init>(PipeMemoryManager.java:70)
at org.apache.iotdb.db.pipe.resource.PipeResourceManager.<init>(PipeResourceManager.java:78)
at …
```

Pipe: fix deadlock caused by PipeResourceManagerHolder.<clinit> and PipePeriodicalJobExecutor

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/optimization/LimitOffsetPushDown.java

In EXPLAIN ANALYZE statement, there will be an IdentityNode above LimitNode to transfer result to ExplainAnalyzeOperator.
However, the implementation in LimitOffsetPushDown considers all the node above is SingleChildNode (IdentityNode is MultiChildSinkNode) which leads to an error: 
`Msg: org.apache.iotdb.jdbc.IoTDBSQLException: 305: [INTERNAL_SERVER_ERROR(305)] Exception occurred: "explain analyze select s1 from root.test.sg limit 2". executeStatement failed. class org.apache.iotdb.db.queryengine.plan.planner.plan.node.sink.IdentitySinkNode cannot be cast to class org.apache.iotdb.db.queryengine.plan.planner.plan.node.process.SingleChildProcessNode (org.apache.iotdb.db.queryengine.plan.planner.plan.node.sink.IdentitySinkNode and …

fix: consider more general type of nodes in optimization above LimitNode

---

.github/workflows/pipe-it-2cluster.yml
iotdb-client/service-rpc/src/main/java/org/apache/iotdb/rpc/subscription/payload/response/PipeSubscribePollResp.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/subscription/broker/SerializedEnrichedEvent.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/subscription/receiver/SubscriptionReceiverV1.java

Subscription: fix null ByteBuffer when transferring SerializedEnrichedEvent

---

integration-test/src/test/java/org/apache/iotdb/db/it/IoTDBRepairDataIT.java

Remove Repair Data ClusterIT
The ClusterIT will compare the query result of all nodes, which may cause the repair data test failed.

Remove Repair Data ClusterIT

---

iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/pipe/extractor/ConfigRegionListeningFilter.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/pipe/receiver/protocol/IoTDBConfigNodeReceiver.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/pipe/receiver/visitor/PipeConfigPhysicalPlanTSStatusVisitor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/receiver/visitor/PipeStatementExceptionVisitor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/receiver/visitor/PipeStatementTSStatusVisitor.java

Pipe: Improved handling logic for transferred statements & Allow root.__system.** schemas to reach the receiver side

---

iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/pipe/connector/client/IoTDBConfigNodeSyncClientManager.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/pipe/connector/protocol/IoTDBConfigRegionConnector.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/client/IoTDBDataNodeAsyncClientManager.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/client/IoTDBDataNodeSyncClientManager.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/protocol/thrift/async/IoTDBDataRegionAsyncConnector.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/protocol/thrift/sync/IoTDBDataNodeSyncConnector.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/config/constant/PipeConnectorConstant.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/connector/client/IoTDBSyncClient.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/connector/client/IoTDBSyncClientManager.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/connector/protocol/IoTDBAirGapConnector.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/connector/protocol/IoTDBConnector.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/connector/protocol/IoTDBSslSyncConnector.java

**Supported sinks:** iotdb-airgap-sink, iotdb-ssl-thrift-sink, iotdb-sync-sink, iotdb-async-sink
```
create pipe p1
with sink (
'load-balance-strategy' = 'random'
);
```
Options for `'load-balance-strategy'`: `round-robin`, `random` and `priority`. `round-robin` by default.
**Explaination:**
* `round-robin`:  The connector will select the next client in a round-robin manner. If the current client is dead, the connector will try the next client until it finds an alive client. If all clients are dead, the connector will throw a `PipeConnectionException`.
* `random`: The connector will select a client randomly. If the selected client is dead, the connector will try the next client until it finds an alive client. If all clients are dead, the connector will throw a `PipeConnectionException`.
* …

Pipe: support different load balance strategies for data sync

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/wal/recover/file/TsFilePlanRedoer.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/wal/recover/file/UnsealedTsFileRecoverPerformer.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/wal/recover/file/TsFilePlanRedoerTest.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/wal/recover/file/UnsealedTsFileRecoverPerformerTest.java

This pr fix two problems of recover:
1. When recover a snapshot memTable WALEntry, the overlap check is skipped. 
2. The overlap check of unsequence file is skipped.
If the overlap check is not performed correctly, the TsFile may have repeated data after recover, which cause compaction failed.

Fix recover duplicate

---

iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/path/PathPatternTree.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/path/PathPatternTreeUtils.java

Execute SQL below, it will cost lots of time in construct query pattern tree with authority pattern.
```
explain analyze verbose  select last_value(`PPS_SREP_TotW_mag`),last_value(`PPS_SREP_NumFltRunInv_mag`),last_value(`PPS_SREP_PlnSupWhDay_mag`),last_value(`PPS_LPHD_Num_mag`),last_value(`PPS_SREP_SupWhYear_mag`),last_value(`mpg`),last_value(`PPS_SREP_SupWhDay_mag`),last_value(`PPS_SREP_WCap_mag`),last_value(`nbq_state`),last_value(`PPS_SREP_PlnSupWhYear_mag`),last_value(`PPS_SREP_PlnEqTmhYear_mag`),last_value(`PPS_SREP_NumLowpInv_mag`),last_value(`p`),last_value(`ypg`),last_value(`PPS_SREP_SupWhMon_mag`),last_value(`PPS_SREP_EqTmhYear_mag`),last_value(`PPS_SREP_PlnSupWhMon_mag`),last_value(`PPS_SREP_NumFltStpInv_mag`),last_value(`PPS_SREP_NumNotFltStpInv_mag`),last_value(`PVINV_EnergyLN_ …
```

Optimize time cost on rewrite pattern by authority pattern

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/metric/PipeConnectorMetrics.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/metric/PipeExtractorMetrics.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/metric/PipeProcessorMetrics.java

As title, also replace `synchronized` with `volatile` to improve clarity.

Pipe: check metric service before marking pipe metrics to avoid useless warn logs

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/cache/schema/DataNodeSchemaCache.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/cache/schema/SchemaCacheEntry.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/cache/schema/TimeSeriesSchemaCache.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/cache/schema/dualkeycache/IDualKeyCache.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/cache/schema/dualkeycache/impl/DualKeyCacheImpl.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/cache/schema/lastcache/DataNodeLastCacheManager.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/cache/schema/lastcache/ILastCacheContainer.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/cache/schema/lastcache/LastCacheContainer.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/DataRegion.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/metadata/cache/dualkeycache/DualKeyCacheTest.java

The current system has a deadlock problem when the deletion is concurrent with query and insertion:
1. Query worker 's num is limit as core num.
2. Deletion will acquire Dataregion's write lock and Datanode Schemacache's write lock.
3. Insert or query will request additional queries to obtain metadata in the case of acquiring a read lock.
DeadLock cycle like this:
```mermaid
graph BT
A[#QueryWorker# get one core to run query]
B[#QueryWorker# hold read lock on dataregion]
A-->B
C[#DeleteData# hold write lock on dataregion]
D[#DeleteData# hold write lock on datanode schema]
C-->D
E[#InsertData# holdread lock on datanode schema]
F[#InsertData# get one core to run fetch schema]
E-->F
B-->C
F-->A
D-->E
```
In this pr:
1. Optimize the lock order to prevent deadlocks
5. Add invalidate last cache …

fix delete dead lock.

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/memtable/AlignedWritableMemChunk.java

This PR fixed inaccurate compression ratio when writing duplicate data,
The memory size may be reduced to negative values in aligned sequence scenarios and when writing duplicate data
In the aligned sequence scenario and when writing duplicate data, the memory size will not become negative again

Storage Engine: Fixed inaccurate compression ratio when writing duplicate data

---

example/session/src/main/java/org/apache/iotdb/SubscriptionSessionExample.java
integration-test/src/test/java/org/apache/iotdb/subscription/it/dual/IoTDBSubscriptionTopicIT.java
integration-test/src/test/java/org/apache/iotdb/subscription/it/local/IoTDBSubscriptionBasicIT.java
integration-test/src/test/java/org/apache/iotdb/subscription/it/local/IoTDBSubscriptionIdempotentIT.java
integration-test/src/test/java/org/apache/iotdb/subscription/it/local/IoTDBSubscriptionRestartIT.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/subscription/receiver/SubscriptionReceiverV1.java

Subscription: fix parsing topic name with back quote when using JAVA SDK client

---

iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/iot/logdispatcher/LogDispatcher.java

Removing a single LogDispatcherThread does not clean up the threads in the thread pool, which may cause a memory leak.

Fix IoTConsensus LogDispatcherThread Stop Using Futrue Cancel

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/utils/executor/fast/AlignedSeriesCompactionExecutor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/utils/executor/fast/NonAlignedSeriesCompactionExecutor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/utils/executor/fast/element/AlignedPageElement.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/utils/executor/fast/element/NonAlignedPageElement.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/utils/executor/fast/reader/CompactionChunkReader.java

- Release compressed chunk data buffer when deserializing chunk into page queue.
- Release compressed page data buffer when deserializing page into points.
**Experimental Scenario:**
There is one sequential file and two unsequential files, all of which completely overlap. Each file contains 5 devices, with each device having 80 time series. Each time series has only one chunk, and each chunk has one page, with 250,000 data points per page. Each timeseries adopts GZIP compression and PLAIN encoding. The experiment simulates a compaction scenario of three-way compacting, with 80 sub threads simultaneously compacting 80 timeseries.
**Experimental Procedure:**
Using binary search method, adjust the MAX_HEAP_SIZE parameter of the system gradually until the difference between the upper and …

Optimize fast compaction memory

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/wal/node/WALNode.java

NPE occurs because drop database operation remove dataregion and wal deletion thread gets null. To fix it, I add if clause to avoid using null.

Fix NPE when concurrently dropping database and deleting wal

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/wal/buffer/WALBuffer.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/wal/io/WALMetaData.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/wal/node/WALNode.java

Cannnot delete empty wal file because wal uses empty set to represent active file. To fix this problem, I remove this rule and use null to represent active file.
Besides, I use avg size to calculate effective ratio and exclude active file from the calculation. By doing so, wal deletion can cover more corner cases.

Fix empty wal file deletion

---

iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/iot/IoTConsensusServerImpl.java

- remove duplicate IoTConsensus configuration
- remove delete oldConfiguration in `recoverFromOldConfigurationFile` because it has been deleted in `persistConfiguration`

Deduplication IoTConsensus Configuration And Remove Unuseless File Delete

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/service/RegionMigrateService.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/concurrent/IoTDBThreadPoolFactory.java

The current thread pool is still limited to a single task at most, which makes the parallelism of region migration a big problem

Fixed concurrency issues with RegionMigration thread pool

---

iotdb-core/datanode/src/assembly/resources/conf/logback-datanode.xml
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/exception/metadata/view/BrokenViewException.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/executor/RegionWriteExecutor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/expression/visitor/CompleteMeasurementSchemaVisitor.java

1. chaneg the log level from error to warn when https://jira.infra.timecho.com:8443/browse/TIMECHODB-689
2. opt error msg for source path of view is deleted https://jira.infra.timecho.com:8443/browse/TIMECHODB-693
3. delete useless log file

Change log level and opt error msg for source path of view is deleted

---

iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/consensus/request/ConfigPhysicalPlan.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/consensus/request/ConfigPhysicalPlanType.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/persistence/AuthorInfo.java
iotdb-core/confignode/src/test/java/org/apache/iotdb/confignode/persistence/AuthorInfoTest.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/tools/schema/SRStatementGenerator.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/auth/user/LocalFileUserManagerTest.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/utils/SchemaRegionSnapshotParserTest.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/auth/authorizer/BasicAuthorizer.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/auth/authorizer/IAuthorizer.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/auth/user/BasicUserManager.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/auth/user/IUserManager.java

In this pr:
1. auth model can create user with raw password in pipe.
2. fix pipe snapshot parser will lose aligned timeseries' tags and attributes.

Colin fix pipe snapshot parser.

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/receiver/visitor/PipeStatementTSStatusVisitor.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/connector/PipeReceiverStatusHandler.java

As title.
```
create pipe test11 with source ('source.path'='root.**', 'inclusion'='data,schema' ,'source.realtime.mode'='stream','source.realtime.enable'='true','source.forwarding-pipe-requests'='false','source.batch.enable'='true','source.history.enable'='true') with sink ('sink'='iotdb-thrift-sink', 'sink.node-urls'='iotdb-16:6667');
CREATE DATABASE root.sg_ttl_2;
create timeseries root.sg_ttl_2.dev.status with datatype=double,encoding=PLAIN ;
set ttl to root.sg_ttl_2 5000;
insert into root.sg_ttl_2.dev(time,status) values(1000,2.3);
```
```
2024-04-25 11:43:51,672 [pool-37-IoTDB-Pipe-Connector-Executor-Pool-2] ERROR o.a.i.c.c.t.WrappedThreadPoolExecutor:129 - Exception in thread pool org.apache.iotdb.threadpool:type=Pipe-Connector-Executor-Pool …
```

Pipe: handle OUT_OF_TTL status code when data syncing

---

iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/iot/IoTConsensusServerImpl.java
iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/iot/logdispatcher/LogDispatcher.java
iotdb-core/consensus/src/test/java/org/apache/iotdb/consensus/iot/ReplicateTest.java

- Immediately check `Thread.interrupted()` for interrupts after `getBatch()`
- Fix configuration logic in ReplicateTest

Fix Concurrency Instability When IoTConsensus LogDispatcher Exits

---

iotdb-core/datanode/src/assembly/resources/conf/datanode-env.bat
iotdb-core/datanode/src/assembly/resources/conf/datanode-env.sh

According to https://bugs.openjdk.org/browse/JDK-8304316 and https://bugs.openjdk.org/browse/JDK-8305994, when `-XX:GuaranteedSafepointInterval=0` and certain versions of JDK 15 ~ JDK 17 are used, the JVM's monitor memory may continue to expand, causing Java's non-heap memory to occupy a large amount of RSS. So we revert `-XX:GuaranteedSafepointInterval=0`

Revert `-XX:GuaranteedSafepointInterval=0` JVM option

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/snapshot/SnapshotLoader.java

When using multiple disk data directories, make sure to copy the tsfile and its resources and mods to the same directory.

Copy tsfile, its resources, and mods to the same directory when using multiple data directories

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/exception/metadata/DataTypeMismatchException.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/receiver/visitor/PipeStatementTSStatusVisitor.java

Pipe: handle insert data type mismatch exceptions as idempotent exceptions when partial insert is enabled

---

iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/IConsensus.java
iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/iot/IoTConsensus.java
iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/iot/snapshot/IoTConsensusRateLimiter.java
iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/ratis/RatisConsensus.java
iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/simple/SimpleConsensus.java
iotdb-core/consensus/src/test/java/org/apache/iotdb/consensus/iot/ReplicateTest.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/consensus/DataRegionConsensusImpl.java
iotdb-core/node-commons/src/assembly/resources/conf/iotdb-common.properties

- add hot reload for `region_migration_speed_limit_bytes_per_second`
- values less than or equal to 0 means no limit

Add hot reload for IoTConsensus transit snapshot rate limiter and fix init

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/DataRegion.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/memtable/TsFileProcessor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/rescon/memory/TimePartitionManager.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/DataRegionTest.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/compaction/settle/SettleRequestHandlerTest.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/rescon/memory/TimePartitionManagerTest.java

https://issues.apache.org/jira/browse/IOTDB-1667
Add a UT in DataRegionTest.
Before this PR, syncDeleteDataFiles costs `101ms ~ 1121ms`.
After this PR, syncDeleteDataFiles costs  about `12ms`.
```java
@Test
public void testIoTDBTabletWriteAndDeleteDataRegion()
throws QueryProcessException, IllegalPathException, WriteProcessException,
TsFileProcessorException {
String[] measurements = new String[2];
measurements[0] = "s0";
measurements[1] = "s1";
TSDataType[] dataTypes = new TSDataType[2];
dataTypes[0] = TSDataType.INT32;
dataTypes[1] = TSDataType.INT64;
MeasurementSchema[] measurementSchemas = new MeasurementSchema[2];
measurementSchemas[0] = new MeasurementSchema("s0", TSDataType.INT32, TSEncoding.PLAIN);
measurementSchemas[1] = new MeasurementSchema("s1", TSDataType.INT64, …
```

[IOTDB-1667] Speed up the deletion of database by avoiding flush

---

iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/iot/IoTConsensusServerImpl.java

During the migration of IoTConsensus multiple replicas, the current safeDeletedIndex may be set to searchIndex, resulting in the loss of part of the data that should be deleted to the Follower. This should be separated into two variables, one for pin's safeDeletedIndex and the other for initialSyncIndex

Ensuring IoTconsensus data consistency during region migration 

---

integration-test/src/main/java/org/apache/iotdb/it/env/cluster/config/MppCommonConfig.java
integration-test/src/main/java/org/apache/iotdb/it/env/cluster/config/MppSharedCommonConfig.java
integration-test/src/main/java/org/apache/iotdb/it/env/remote/config/RemoteCommonConfig.java
integration-test/src/main/java/org/apache/iotdb/itbase/env/CommonConfig.java
integration-test/src/test/java/org/apache/iotdb/db/it/schema/IoTDBTagLimitIT.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/impl/SchemaRegionMemoryImpl.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/impl/SchemaRegionPBTreeImpl.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/tag/TagLogFile.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/tag/TagManager.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/tools/schema/SRStatementGenerator.java
iotdb-core/node-commons/src/assembly/resources/conf/iotdb-common.properties
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/conf/CommonConfig.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/conf/CommonDescriptor.java

The goal of this implementation is that for a tagmap that stores more than tagAttributeTotalSize, the program can support continuing to allocate a new space of the length of tagAttributeTotalSize and continue to store it.
- Storage design:
- How to record the newly allocated space with a length of tagAttributeTotalSize: During tagmap serialization, identification is distinguished between tags that exceed tagAttributeTotalSize and those that do not exceed tagAttributeTotalSize. Currently, the identifier is considered to be the first read int value.
- If this tagmap does not exceed tagAttributeTotalSize, it is based on the original storage format (mapsize key-value key-value). The first value is MapSize and is recorded as a positive number, 0, -1. (When map is null, mapsize is -1, map is …

Lift the storage limit for tag and attribute management

---

iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/path/PartialPath.java
iotdb-core/node-commons/src/test/java/org/apache/iotdb/commons/path/PartialPathTest.java

before 
after:
return only `root.db.device.s1`

Fix PartialPath#intersectWithPrefixPattern return wrong result

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/task/subtask/connector/PipeConnectorSubtaskManager.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/subscription/task/subtask/SubscriptionConnectorSubtaskManager.java

Pipe: Fixed connector subtask manager to allow restarted DataRegions to reuse connectors from other not restarted DataRegions

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/protocol/thrift/async/IoTDBDataRegionAsyncConnector.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/protocol/thrift/async/handler/PipeTransferTsFileInsertionEventHandler.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/protocol/thrift/sync/IoTDBDataRegionSyncConnector.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/processor/twostage/exchange/sender/TwoStageAggregateSender.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/receiver/protocol/airgap/IoTDBAirGapReceiver.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/load/LoadTsFileManager.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/scheduler/load/LoadTsFileDispatcherImpl.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/StorageEngine.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/conf/CommonConfig.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/config/PipeConfig.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/connector/client/IoTDBClientManager.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/connector/client/IoTDBSyncClientManager.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/connector/protocol/IoTDBAirGapConnector.java

When synchronizing historical data using pipes, it is often necessary to synchronize large files (>3GB). For data synchronization receivers with poor performance, loading such large files is time-consuming. The loading process can cause timeouts between the sender and receiver connections, timeouts between various DNs on the receiver side, and issues with the receiver's resource cleaning mechanism clearing the resources of the file being loaded. 
However, setting a fixed timeout duration is never sufficient; a fixed duration cannot handle all scenarios. This PR introduces a mechanism for dynamically adjusting the timeout duration in hopes of addressing the pain points encountered.

Pipe: dynamically adjust connection timeout to handle SocketTimeoutException & Avoid resource cleaning when load task is in process

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/AnalyzeVisitor.java

The original implementation caused repeating lock taking for all given devices when checking template compatibility for multi timeseries creation. Therefore, if the count of devices in one creation request exceeds 65535, the state count in ReentrantReadWriteLock will overflow, causing the error shown in the picture.
Make the lock taking only execute once when creating multi timeseries.

Fix redundant lock taking during create multi timeseries

---

integration-test/src/test/java/org/apache/iotdb/db/it/IoTDBRestServiceIT.java
integration-test/src/test/java/org/apache/iotdb/db/it/IoTDBSyntaxConventionIdentifierIT.java
integration-test/src/test/java/org/apache/iotdb/db/it/auth/IoTDBClusterAuthorityIT.java
integration-test/src/test/java/org/apache/iotdb/pipe/it/manual/IoTDBPipeMetaHistoricalIT.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/persistence/AuthorInfo.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/auth/AuthorityChecker.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/common/header/ColumnHeaderConstant.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/conf/IoTDBConstant.java

more details can be seen in https://issues.apache.org/jira/browse/IOTDB-6326.
After this pr merged, we will get table headers like the following:

[IOTDB-6326] Normalize the table headers of Auth related statement

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/DataRegion.java

When some TsFiles is flushing and execute drop database, there is some error occured.
To fix that, we need to wait all closing TsFiles finished their flushing before delete them physically.

Fix tsfile flush error when drop database or remove peer

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/memtable/AbstractMemTable.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/memtable/TsFileProcessor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/memtable/WritableMemChunkGroup.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/memtable/TsFileProcessorTest.java

In https://github.com/apache/iotdb/pull/12271 , there was a bug that causes memtable size smaller and more tsfiles generated than the normal situation when using insertRecords API. 
After this patch, the tsfile number will be back to normal.

Fix insert rows mem control error

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/client/IoTDBDataNodeAsyncClientManager.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/protocol/thrift/async/IoTDBDataRegionAsyncConnector.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/protocol/thrift/async/handler/PipeTransferTsFileInsertionEventHandler.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/client/async/AsyncPipeDataTransferServiceClient.java

Pipe: fix infinite loop with lock when retrying syncing tsfiles in async connector (which may cause selector & connector worker deadlock)

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/client/ConfigNodeClient.java

Degrade configNode leader redirection log level and avoid meaningless log print when ConfigNodeClient is first constructed.

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/schema/ClusterSchemaFetcher.java

```SQL
create device template t1 aligned (attr BOOLEAN, fuel_state DOUBLE, current_load INT32, status INT32);
create database root.template;
set device template t1 to root.template;
create timeseries using device template on root.template.d1;
insert into root.template.d1(time,status) aligned values(1,1);
```
then 
```SQL
select status from root.template.d1 where status <= 1 align by device;
```
return value of fetch schema should include hasNormalTimeSeries=false because all time series is template series

Fix return value of fetch schmea with incorrect template info

---

iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/datastructure/queue/ConcurrentIterableLinkedQueue.java
iotdb-core/node-commons/src/test/java/org/apache/iotdb/commons/pipe/datastructure/ConcurrentIterableLinkedQueueTest.java

Pipe: Fixed the bug that iterator.hasNext() == true after removal from empty ConcurrentIterableLinkedQueue

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/TemplatedLogicalPlanBuilder.java

Before fix, FilterNode is the parent of AlignedSeriesScanNode:
After fix, there is no FilterNode, pushDownFilter is in AlignedSeriesScanNode.

Fix filter push down is not valid in template align by device situation

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/optimization/AggregationPushDown.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/plan/node/source/AlignedSeriesAggregationScanNode.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/plan/optimization/AggregationPushDownTest.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/plan/optimization/TestPlanBuilder.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/plan/planner/distribution/AggregationAlignByDeviceTest.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/plan/planner/distribution/AlignedByDeviceTest.java

The `RawDataAggregation` operator contains the capabilities of the `Project` operator, so it is possible to remove the redundant `Project`.
`RawDataAggregation - Project  => RawDataAggregation`
This allows for more situations where aggregation can be push into scan.

Add new optimization rule: remove `Project` under `RawDataAggregation`

---

pom.xml

We optimize IPageReader's performance in https://github.com/apache/tsfile/pull/77, so we want to IoTDB to depend on a newer version

Change TsFile version

---

pom.xml

This is the latest snapshot that contains all the fixes and commits since 3.0.1

[RatisConsensus] Bump ratis to 3.1.0-2fddd52-snapshot

---

iotdb-client/jdbc/src/main/java/org/apache/iotdb/jdbc/IoTDBStatement.java

In a JDBC statement, when the maxRows is 0 it means that there is no limit, therefore we shall allow to set it to 0 to provide function in this case.
<hr>
This PR has:
<hr>

JDBC: Fix maxRows cannot be set to 0

---

integration-test/src/test/java/org/apache/iotdb/db/it/auth/IoTDBAuthIT.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/common/schematree/ClusterSchemaTree.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/schema/ClusterSchemaFetcher.java

```sql
create device template t1 aligned (temperature FLOAT encoding=Gorilla, status BOOLEAN encoding=PLAIN);
show device templates;
show nodes in device template t1;
set device template t1 to root.sg.aligned_template;
show paths set device template t1;
create timeseries using device template on root.sg.aligned_template;
show paths using device template t1;
insert into root.sg.aligned_template(time,temperature,status) values(1,20,false),(2,22.1,true),(3,18,false);
CREATE USER user03 'pass1234';
LIST PRIVILEGES OF USER `user03`;
GRANT READ_DATA ON root.sg.aligned_template.temperature TO USER user03;
```
then log in with user03:
```sql
[root@xzh-97 iotdb-enterprise-1.3.2-SNAPSHOT-bin]# ./sbin/start-cli.sh -u user03 -pw pass1234
Starting IoTDB Cli …
```

Fix non-root user query data returns unexpected path

---

iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/ratis/RatisConsensus.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/thrift/impl/DataNodeInternalRPCServiceImpl.java

Use the entire peer list may lead to probable shutdown.

[RatisConsensus] Use empty map for create peer

---

integration-test/src/test/java/org/apache/iotdb/session/it/IoTDBSessionSimpleIT.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/AnalyzeVisitor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/parser/ASTVisitor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/statement/crud/InsertBaseStatement.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/statement/crud/InsertMultiTabletsStatement.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/statement/crud/InsertRowStatement.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/statement/crud/InsertRowsOfOneDeviceStatement.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/statement/crud/InsertRowsStatement.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/statement/crud/InsertStatement.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/statement/crud/InsertTabletStatement.java

Previous version only checks the duplicated measurements of one row when using insert SQL statements. However, this check should be in all insert methods.

Check duplicated measurements in one row for all insert APIs

---

iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/ClusterManager.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/consensus/ConsensusManager.java

We found that in some scenarios, when the `stop-confignode.sh` command is executed, confignode does not exit immediately, but hangs for about 90 seconds, printing more than 3 million "Unexpected interruption during waiting for configNode leader ready." warning logs.
This problem is because in the code modified by this PR, the RPC thread of confignode will continue to sleep in the while loop. When the confignode process is killed, the OS will continuously try to interrupt the sleep thread, causing the sleep thread to be continuously interrupted and print logs in the while loop.
So we check the confignode for all threads that are sleeping in the while loop. If these threads will only be interrupted during shutdown during their life cycle, then they need to jump out of the while loop when …

Avoid infinite and unecessary loop when CN RPC processors are killed/interrupted by OS

---

integration-test/src/main/java/org/apache/iotdb/itbase/runtime/RequestDelegate.java

As shown in the figure, using Objects.equals returns the wrong result when T is a byte array. 
Arrays.equals should be used to compare array objects.

Fix error compare method in IT framework

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/optimization/AggregationPushDown.java

accelerate last agg query while we can push down agg to scan node

Fix agg push down bug

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/audit/AuditLogger.java

Fix AuditLogger may cause IoTDB read only when session using incorrect password

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/StorageEngine.java

Fixed an issue where LoadSnapshot could cause out-of-heap memory statistics to leak

---

integration-test/src/test/java/org/apache/iotdb/db/it/schema/IoTDBDisableAutoCreateSchemaIT.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/ClusterPartitionFetcher.java

A little update as the title described

Forbid auto create database when disable auto create schema

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/tsfile/generator/TsFileNameGenerator.java

Generate compaction target file with tier level

Generate compaction target file with tier level

---

iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/TTLManager.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/thrift/impl/DataNodeInternalRPCServiceImpl.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/schema/source/DeviceSchemaSource.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/SeriesScanUtil.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/cache/schema/DataNodeTTLCache.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/execution/config/executor/ClusterConfigTaskExecutor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/OperatorTreeGenerator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/statement/metadata/ShowDatabaseStatement.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/service/DataNode.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/service/metrics/CompactionMetrics.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/StorageEngine.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/DataRegion.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/performer/impl/FastCompactionPerformer.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/utils/MultiTsFileDeviceIterator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/memtable/TsFileProcessor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/utils/TsFileResourceUtils.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/execution/operator/schema/SchemaQueryScanOperatorTest.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/compaction/TsFileValidationCorrectnessTests.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/compaction/settle/SettleCompactionTaskTest.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/schema/ttl/TTLCache.java

This pr accomplishes two things as following:
- support special path for device ttl, eg: `root.db.'test.device'`
- use a more efficient interface for DataNodeTTLCache.

Support special path for device TTL

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/scheduler/AsyncPlanNodeSender.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/scheduler/FragmentInstanceDispatcherImpl.java
iotdb-core/node-commons/src/assembly/resources/conf/iotdb-system.properties
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/conf/CommonConfig.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/conf/CommonDescriptor.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/service/metric/PerformanceOverviewMetrics.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/utils/StatusUtils.java

In this pr, we add two hot loaded configuration:
```
```
And I also add metrics for retry sleeping time.
More details can be seen in https://issues.apache.org/jira/browse/IOTDB-6336

[IOTDB-6336] Add max retry time duration and whether to retry for unknown errors configurations

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/optimization/LimitOffsetPushDown.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/plan/optimization/LimitOffsetPushDownTest.java

Details in https://issues.apache.org/jira/browse/IOTDB-6335.
Wrong way to caculation new startTime leading to a negative value resultinng in redudant rows.

[IOTDB-6335] Redundant rows when using GROUP BY TIME with LIMIT

---

.github/workflows/cluster-it-1c1d.yml
.github/workflows/cluster-it-1c3d.yml
.github/workflows/pipe-it-2cluster.yml
.github/workflows/sonar-codecov.yml
.github/workflows/unit-test.yml
.gitignore
.mvn/develocity.xml
.mvn/extensions.xml

This PR update IoTDB to use the renamed Develocity Maven Extension in place of the replaced Gradle Enterprise Maven Extension. The functionality of this extension is the same as the Gradle Enterprise Maven Extension. The changes in this PR do not modify the configuration of the extension.
This PR also updates to the most recent version of Common Custom User Data Maven Extension.

Migrate to Develocity Maven Extension

---

integration-test/src/test/java/org/apache/iotdb/subscription/it/dual/AbstractSubscriptionDualIT.java
integration-test/src/test/java/org/apache/iotdb/subscription/it/dual/IoTDBSubscriptionConsumerGroupIT.java
integration-test/src/test/java/org/apache/iotdb/subscription/it/dual/IoTDBSubscriptionTimePrecisionIT.java
integration-test/src/test/java/org/apache/iotdb/subscription/it/dual/IoTDBSubscriptionTopicIT.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/subscription/topic/CreateTopicProcedure.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/extractor/dataregion/historical/PipeHistoricalDataRegionTsFileExtractor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/extractor/dataregion/realtime/PipeRealtimeDataRegionExtractor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/execution/config/executor/ClusterConfigTaskExecutor.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/subscription/meta/topic/TopicMeta.java

Subscription: fix topic now timestamp precision

---

integration-test/src/test/java/org/apache/iotdb/db/it/regionscan/IoTDBActiveRegionScanIT.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/process/ActiveRegionScanMergeOperator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/AbstractRegionScanDataSourceOperator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/ActiveDeviceRegionScanOperator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/ActiveTimeSeriesRegionScanOperator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/AnalyzeVisitor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/OperatorTreeGenerator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/distribution/SourceRewriter.java

Details in https://issues.apache.org/jira/browse/IOTDB-6337
1. This pr fixed NPE problem when schema is empty for COUNT
2. The pr supported COUNT push down to regionScan which also fixed the bug of failing of COUNT when there is only one region.

[IOTDB-6337] Refine the count calculation in RegionScan framework

---

integration-test/src/test/java/org/apache/iotdb/pipe/it/autocreate/IoTDBPipeAutoConflictIT.java
integration-test/src/test/java/org/apache/iotdb/pipe/it/autocreate/IoTDBPipeClusterIT.java
integration-test/src/test/java/org/apache/iotdb/pipe/it/autocreate/IoTDBPipeLifeCycleIT.java
integration-test/src/test/java/org/apache/iotdb/pipe/it/manual/IoTDBPipeMetaLeaderChangeIT.java
integration-test/src/test/java/org/apache/iotdb/pipe/it/manual/IoTDBPipeMetaRestartIT.java
integration-test/src/test/java/org/apache/iotdb/subscription/it/local/IoTDBSubscriptionRestartIT.java

Pipe IT: Ignore failed cases caused by cluster restart failure

---

integration-test/src/test/java/org/apache/iotdb/db/it/orderBy/IoTDBOrderByForDebugIT.java
integration-test/src/test/java/org/apache/iotdb/db/it/udaf/IoTDBUDAFOrderByIT.java

`IoTDBUDAFOrderByIT` always fails from time to time. This is most likely caused by floating point precision issue from TsFile.
In this PR, we change the floating point encoding method in `IoTDBUDAFOrderByIT` to make it correct, and add a new IT for debugging. Since the origin `IoTDBOrderByIT` is always correct, we add two `flush` commands to force it to read data from disk. If this test is always passed, then we can assert that something is wrong with UDAF.

Change floating point encoding method in IT

---

iotdb-api/udf-api/src/main/java/org/apache/iotdb/udf/api/utils/RowImpl.java

In old UDTF execution framework, if user only pass one column in UDTF, then whatever column index passed in row, the `getXXX()` method will always return the first column, which can be a little confused.
As contrast, new UDTF execution throws `IndexOutOfBound` exception when user only pass one column in those UDTF which reference multiple columns.

Throw `IndexOutOfBound` exception in single column UDTF

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/metadata/ITableDeviceSchemaValidation.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/metadata/Metadata.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/metadata/TableMetadataImpl.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/plan/relational/analyzer/TestMatadata.java

Setup schema validation interfaces, including table schema validation and device schema validation.

[Table Model] Schema Validation Interface

---

iotdb-core/metrics/interface/src/main/java/org/apache/iotdb/metrics/metricsets/system/SystemMetrics.java

Fix missing of linux memory metrics:

Fix missing of linux memory metrics

---

example/schema/pom.xml
pom.xml

https://github.com/apache/iotdb/security/dependabot
These dependences are not using in IoTDB currently, just remove them to fix the security warning.

Update pom.xml to fix security issue

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/utils/MemUtils.java

When upgrading from an older version(before 1.3), if only sbin is updated without simultaneously updating the env script in the conf directory, a NumberFormatException may occur.

Fix NumberFormatException when upgrade from old version

---

iotdb-core/antlr/src/main/antlr4/org/apache/iotdb/db/qp/sql/IoTDBSqlParser.g4
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/parser/ASTVisitor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/utils/TypeInferenceUtils.java
iotdb-core/node-commons/src/assembly/resources/conf/generate_properties.bat
iotdb-core/node-commons/src/assembly/resources/conf/iotdb-system.properties
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/conf/ConfigurationFileUtils.java

1. Replenish effective mode in iotdb-system.properties
2. Remove '\r' in iotdb-system.properties

Replenish effective mode in iotdb-system.properties

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/task/connection/PipeEventCollector.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/task/subtask/connector/PipeConnectorSubtask.java

Pipe: Fixed the bug that schema events can not report & delete data event may fail to mark at schema metrics

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/event/common/tsfile/PipeTsFileInsertionEvent.java

Pipe: fix threads of IoTDB-Pipe-Processor-Executor-Pool stucked by PipeTsFileInsertionEvent#waitForTsFileClose

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/AnalyzeVisitor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/TemplatedAggregationAnalyze.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/TemplatedAnalyze.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/plan/analyze/QueryTimePartitionTest.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/utils/TimePartitionUtils.java

When querying with GROUP BY, if endTime is massive will result in huge number of time slots leading to Java Heap Space (see in #12499)
This PR  would reject the query which may lead to above problems in advance to avoid system crash.
Relating document: https://apache-iotdb.feishu.cn/docx/IMUWdQZ4CounhEx5Z2UcdXzGnAe

[ISSUE 12499] Reject query with massive time span in limited memroy

---

integration-test/src/test/java/org/apache/iotdb/db/it/alignbydevice/IoTDBAlignByDeviceWithTemplateAggregationIT.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/TemplatedAggregationAnalyze.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/expression/multi/FunctionExpression.java

Before this pr, when all queried devices are in one template, `select agg(*) from root.aligned.** align by device` query will throw exception. 
And this pr fixed this issue, agg(*) query is supported.

Support agg(*) query in templated align by device situation

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/auth/AuthorityChecker.java

Fix config node use IoTDBDescriptor. Using AuthorityChecker.SUPER_USER in the code of confignode will trigger the initialization of ClusterAuthorityFetcher, causing the logic of IoTDBDescriptor initialization to be entered in confignode.

Fix config node use IoTDBDescriptor

---

iotdb-client/client-cpp/README.md

Add instructions of compiling client-cpp with VS2019.

---

iotdb-core/confignode/src/assembly/resources/sbin/stop-confignode.sh
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/client/sync/SyncConfigNodeClientPool.java
iotdb-core/datanode/src/assembly/resources/sbin/stop-datanode.sh
iotdb-core/node-commons/src/assembly/resources/sbin/iotdb-common.sh
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/conf/ConfigurationFileUtils.java

1. Check duplicate in start-node and stop-node scripts
2. Properties.store is not used as Properties.store may generate '\\' automatically
3. Fix config node send showConfiguration to config node throw ClassCastException

Check duplicate in start-node and stop-node scripts

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/consensus/statemachine/schemaregion/SchemaExecutionVisitor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/ClusterPartitionFetcher.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/IAnalysis.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/IPartitionFetcher.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/plan/node/PlanVisitor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/analyzer/Analysis.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/analyzer/StatementAnalyzer.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/metadata/Metadata.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/metadata/TableMetadataImpl.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/planner/LogicalPlanner.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/planner/node/CreateTableDeviceNode.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/sql/ast/AstVisitor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/sql/ast/CreateDevice.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/ISchemaRegion.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/attribute/DeviceAttributeStore.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/attribute/IDeviceAttributeStore.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/impl/SchemaRegionMemoryImpl.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/impl/SchemaRegionPBTreeImpl.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/mtree/impl/mem/MTreeBelowSGMemoryImpl.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/metadata/schemaRegion/SchemaRegionTestUtil.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/plan/analyze/FakePartitionFetcherImpl.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/plan/planner/distribution/Util.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/plan/planner/distribution/Util2.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/plan/relational/analyzer/AnalyzerTest.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/plan/relational/analyzer/TestMatadata.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/partition/SchemaPartition.java

Support Create Table Device, including:
1. Statement CreateDevice
2. PlanNode CreateTableDeviceNode, including ser/deser and split logic
3. LogicalPlan stage logic 
4. execution logic invoking SchemaRegion

[Table Model] Create table device

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/AbstractSeriesScanOperator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/AlignedSeriesScanOperator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/SeriesScanOperator.java

Previously, we will scan until we get at least one satisfied row and then we have chance to do time slice control.
However, when we do the predicate push down optimization, we may need much more time to get a satisfied row from tsfile, so we need to change the control processing of SeriesScanOperator and AlignedSeriesScanOperator.
We will do time check after we got one page data from SeriesScanUtil, even if it's an empty TsBlock.

[IOTDB-6339] Optimize the time slice control of SeriesScanOperator and AlignedSeriesScanOperator

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/exception/CompactionValidationFailedException.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/task/AbstractCompactionTask.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/utils/writer/RepairUnsortedFileCompactionWriter.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/compaction/repair/RepairUnsortedFileCompactionTest.java

1. Fix overlap between tsfile is not correctly marked
2. Fix repair compaction that could generate too large chunks

Fix overlap between tsfile is not correctly marked

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/event/common/tsfile/TsFileInsertionDataContainer.java

Currently we read the metadata of **all** devices and measurements when constructing a TsFileInsertionDataContainer. This is both time-consuming and memory-wasting if only **a few** devices match the pattern. This PR filters the devices by pattern before reading the metadata of devices and measurements, saving memory and I/O cost when there are many unmatched devices.
Note: this only works when TsFile metadata are **not** cached (due to high memory usage of TsFile metadata cache), because cached metadata can not be filtered so that pipes with arbitrary patterns can use it.

Pipe: Filter devices by pattern before reading device metadata from TsFile

---

iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/ratis/RatisConsensus.java

1. Log every successful snapshot actions
2. Synchronize on takeSnapshotAsync so that the daemons will not affect force actions

[RatisConsensus] Synchronize takeSnapshotAsync on RaftGroupID

---

integration-test/src/test/java/org/apache/iotdb/db/it/IoTDBRestServiceIT.java
integration-test/src/test/java/org/apache/iotdb/db/it/auth/IoTDBSeriesPermissionIT.java
integration-test/src/test/java/org/apache/iotdb/pipe/it/autocreate/IoTDBPipeDataSinkIT.java
integration-test/src/test/java/org/apache/iotdb/pipe/it/autocreate/IoTDBPipeExtractorIT.java
integration-test/src/test/java/org/apache/iotdb/pipe/it/manual/IoTDBPipeMetaHistoricalIT.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/TTLManager.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/schema/ClusterSchemaManager.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/common/header/ColumnHeaderConstant.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/schema/source/DeviceSchemaSource.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/cache/schema/DataNodeTTLCache.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/statement/metadata/ShowDatabaseStatement.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/conf/IoTDBConstant.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/schema/ttl/TTLCache.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/utils/CommonDateTimeUtils.java

1. Use milliseconds to express TTL. Eg：
The TTL values are always displayed and stored in milliseconds. They are converted to the corresponding unit based on the `TimestampPrecision` parameter only during filtering and cleaning processes. See details in [link](https://jira.infra.timecho.com:8443/browse/TIMECHODB-778)
2. Remove ttl column when showing databases.

Use milliseconds to express TTL

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/fragment/FragmentInstanceContext.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/relational/TableScanOperator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/TableOperatorGenerator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/plan/FragmentInstance.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/analyzer/Analysis.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/planner/QueryPlanner.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/planner/distribute/TableModelQueryFragmentPlanner.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/planner/node/TableScanNode.java

1. Remove global timefilter in Analysis
2. correct the `TableScanOperator.constructAlignedPath` for Table Model
3. remove duplicated `canPushIntoScan` while constructing TableScanOperator, because we already did this in fe.

Remove global timefilter in Analysis

---

integration-test/src/test/java/org/apache/iotdb/db/it/alignbydevice/IoTDBAlignByDeviceWithTemplateAggregationIT.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/optimization/AggregationPushDown.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/plan/node/PlanGraphPrinter.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/plan/planner/node/PlanGraphPrinterTest.java

Before fix, order by time align by device query with template will meet error. 
The code below can reproduce this problem.
```
CREATE database root.sg3;
CREATE schema template t1 (s1 FLOAT encoding=RLE, s2 BOOLEAN encoding=PLAIN compression=SNAPPY, s3 INT32);
SET SCHEMA TEMPLATE t2 to root.sg3;
INSERT INTO root.sg3.d1(timestamp,s1,s2,s3) values(1,1.1,false,1), (2,2.2,false,2), (5,5.5,true,5), (1314000000000,13.14,true,1314);
delete from root.sg3.d1.s1 where time <= 5;
select count(s1) from root.sg3.** order by time align by device;
```

[IOTDB-6343] Fix the device path construction bug in visitSingleDeviceViewNode of AggragationPushDown

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/planner/PlanBuilder.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/planner/QueryPlanner.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/planner/ir/ExpressionTreeRewriter.java

The `outputSymbols` of `OutputNode` is previously computed by `expression.toString()`,  which may not equals to the symbol of its child after `TranslationMap` introduced. 
This will cause the child node of `OutputNode` cannot detect the column referenced by `OutputNode` .

Fix allocate symbol by Expression

---

iotdb-core/antlr/src/main/antlr4/org/apache/iotdb/db/qp/sql/IoTDBSqlParser.g4
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/common/header/ColumnHeaderConstant.java

1. Fix `show databases details` sql, remove ttl column in the result.
2. Support `unset ttl from | to path` sql.

Support unset ttl from path

---

.github/workflows/multi-language-client.yml
iotdb-client/client-py/iotdb/utils/IoTDBRpcDataSet.py
iotdb-client/client-py/requirements.txt
iotdb-client/client-py/requirements_dev.txt
iotdb-client/client-py/resources/setup.py
iotdb-client/client-py/tests/test_todf.py

This PR allowed using the iotdb client with Python 3.6. 
It also fixed a bug when using a low version of numpy.

Allow using python 3.6 and enable CI

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/AbstractSeriesScanOperator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/AlignedSeriesScanOperator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/relational/TableScanOperator.java

Refactor the TableScanOperator according to https://github.com/apache/iotdb/pull/12750. Optimize the time slice control of TableScanOperator.

Add TimeSlice Control for TableScanOperator

---

iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/wal/node/WALNodeTest.java

Change the number of requests to a fixed number to avoid uncertainty.

Fix WalNodeTest

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/conf/IoTDBStartCheck.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/receiver/protocol/pipeconsensus/PipeConsensusReceiver.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/plan/node/PlanNode.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/plan/node/pipe/PipeEnrichedInsertNode.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/plan/node/write/InsertNode.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/DataRegion.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/wal/WALManager.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/wal/recover/WALNodeRecoverTask.java

As title, and please NOTE:
1. pipe consensus will keep consistent with IoTConsensus regarding to WAL strategy, including register, delete etc.
2. in pipe consensus, followers will try to NOT update last cache when receiving replicates from leader.

PipeConsensus: keep consistent with IoTConsensus in WAL, lastCache and other scenarios

---

iotdb-core/node-commons/src/assembly/resources/conf/iotdb-system.properties.template

Currently, fastiotconsensus is not stable, we do not recommend users to use it, so we can directly hide the introduction in the template file

Delete doc for FastIoTConsensus temporarily

---

iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/persistence/TTLInfo.java
iotdb-core/confignode/src/test/java/org/apache/iotdb/confignode/persistence/TTLInfoTest.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/TTLTest.java
iotdb-core/node-commons/src/assembly/resources/conf/iotdb-system.properties.template
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/conf/CommonDescriptor.java

Hide `ttl_rule_capacity` from properties and modify the error message accordingly.

Hide ttl_rule_capacity from properties and modify the error message

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/receiver/protocol/pipeconsensus/PipeConsensusReceiver.java

Pipe Consensus: Fix failed to read tsfile when counting points on receivers

---

iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/ratis/ApplicationStateMachineProxy.java
iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/ratis/RatisConsensus.java
iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/ratis/utils/Utils.java

Currently, SchemaRegion has LINEARIZABLE reads set up, and its state machine stops writing when the system is readonly, potentially causing the query to freeze indefinitely.
In fact, we only need to process dataRegion, because the semantics of readonly itself does not prevent metadata from being written. In addition, dataregion is not LINEARIZABLE read by default. Therefore, even if the dataregion is ratis, there will be no stuck problem.
In addition, the problem comes from the earliest [issue](https://issues.apache.org/jira/browse/IOTDB-5843), the current shutdownhook would stop the RPC client service at the beginning, Therefore, this change will not cause any worse effects.

Fix schema query stuck when system is readonly

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/wal/io/WALInputStream.java

Fixed issues with using deallocated direct buffer

Enhance wal compression

---

iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/conf/ConfigNodeDescriptor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java
iotdb-core/node-commons/src/assembly/resources/conf/iotdb-system.properties.template

…ers: cn_pipe_receiver_file_dir, dn_pipe_receiver_file_dirs
In the configuration file iotdb-system.properties, the file receiving directory parameters of confignode and datanode are pipe_receiver_file_dir and pipe_receiver_file_dirs respectively, which are not distinguishable. Change them to cn_pipe_receiver_file_dir and dn_pipe_receiver_file_dirs respectively
```java
conf.setPipeReceiverFileDirs(
Arrays.stream(
properties
.getProperty(
"pipe_receiver_file_dirs", String.join(",", conf.getPipeReceiverFileDirs()))
.trim()
.split(","))
.filter(dir -> !dir.isEmpty())
.toArray(String[]::new));
conf.setPipeReceiverFileDir(
properties
.getProperty(
"pipe_receiver_file_dir",
conf.getSystemDir() + File.separator + "pipe" + File.separator + "receiver")
.trim());
```
```java …
```

Pipe: Modified the confignode and datanode receiving file directory parameters: cn_pipe_receiver_file_dir, dn_pipe_receiver_file_dirs

---

iotdb-client/cli/src/main/java/org/apache/iotdb/tool/ImportData.java
iotdb-client/cli/src/main/java/org/apache/iotdb/tool/ImportSchema.java

When importing data and schema data, if a failure occurs and the failure directory does not exist, the failed file will not be placed in the specified directory

fix fail file directory when import tools failed

---

iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/consensus/response/pipe/task/PipeTableResp.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/task/meta/PipeTaskMeta.java

Use map to store and remove duplicates from the logs, with the log as the key and the partition id as the value in order. The final printed log format is as follows:
regionId: [9, 10, 11, 12, 13],2024-07-08T10:33:43.751, All clients are dead, please check the connection to the receiver., root cause: All clients are dead, please check the connection to the receiver.;regionId: [1],2024-07-08T10:50:26.270, Failed to handle pipe meta changes for test104, because Failed to construct PipeConnector, because of Error occurred while connecting to receiver 47.108.188.22:6667, please check network connectivity or SSL configurations when enable SSL transmission;

Pipe: Avoid `show pipes` command returning too much garbage logs

---

iotdb-core/confignode/src/assembly/resources/conf/confignode-env.sh
iotdb-core/confignode/src/assembly/resources/sbin/start-confignode.sh
iotdb-core/datanode/src/assembly/resources/conf/datanode-env.sh

1. fix start-confignode.sh, Support -H
2. Require 8u92 or higher version

fix start-confignode.sh, Support -H

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/consensus/statemachine/dataregion/DataExecutionVisitor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/consensus/statemachine/dataregion/DataRegionStateMachine.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/plan/node/write/DeleteDataNode.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/plan/node/write/InsertNode.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/plan/node/write/SearchNode.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/DataRegion.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/memtable/TsFileProcessor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/wal/node/WALNode.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/wal/recover/WALNodeRecoverTask.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/wal/recover/WALRepairWriter.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/compaction/AbstractCompactionTest.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/compaction/cross/RewriteCrossSpaceCompactionWithFastPerformerTest.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/wal/recover/WALRepairWriterTest.java

The IoTConsensus protocol requires any write or delete operations to be recorded in the WAL file to synchronize data changes to other nodes. 
Currently, if a delete operation cannot correspond to any MemTable, it will not be recorded in the WAL, causing the synchronization between IoTConsensus nodes to be stuck. 
This PR fixes this issue by treating such delete operations as if they have a MemTable id of -1, and records them in the WAL in the same way. During restart recovery, WALs with a MemTable id of -1 will not be recovered.

Fix IoTConsensus sync stuck problem 

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/receiver/protocol/pipeconsensus/PipeConsensusReceiver.java

As title. 
When transmitting tsfile, an exception of no such element was found. After investigation, it was found that when the Leader had a retryEvent and was also sending events in real time, the load on the Follower would exceed the pipeline size, causing an exception in the retrieval process of tsFileWriter.

PipeConsensus: Fix no such element error when transfer tsfile 

---

iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/schema/AlterLogicalViewProcedure.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/schema/DataNodeRegionTaskExecutor.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/schema/DeactivateTemplateProcedure.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/schema/DeleteLogicalViewProcedure.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/schema/DeleteTimeSeriesProcedure.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/schema/SchemaUtils.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/schema/SetTemplateProcedure.java

Optimized the failure logs related to DataNodeRegionTaskExecutor when all replicaset execution failed

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/StorageEngine.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/DataRegion.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/memtable/AbstractMemTable.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/memtable/AlignedWritableMemChunk.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/memtable/IMemTable.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/memtable/IWritableMemChunk.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/memtable/TsFileProcessor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/memtable/WritableMemChunk.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/utils/datastructure/AlignedTVList.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/utils/datastructure/BinaryTVList.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/utils/datastructure/TVList.java

If the length of a TVList is too large, the sort progress in query and flush will takes too much CPU and memory resource. Therefore, we need to limit the row count of a single TVList below the avg_series_point_number_threshold to control it.

Limit the row count of a single TVList to avg_series_point_number_threshold

---

iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/persistence/pipe/PipePluginInfo.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/persistence/pipe/PipeTaskInfo.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/pipe/plugin/DropPipePluginProcedure.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/agent/plugin/PipeDataNodePluginAgent.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/agent/runtime/PipeAgentLauncher.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/pipe/agent/plugin/PipeDataNodePluginAgentTest.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/executable/ExecutableManager.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/agent/plugin/PipePluginConstructor.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/plugin/meta/PipePluginMetaKeeper.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/plugin/service/PipePluginClassLoaderManager.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/plugin/service/PipePluginExecutableManager.java
iotdb-core/node-commons/src/test/java/org/apache/iotdb/commons/pipe/plugin/meta/PipePluginMetaTest.java

Currently, IOTDB allows PipePlugins that are being used by Pipes to be deleted. When users drop a PipePlugin and then create a new PipePlugin with the same fully qualified class name, IOTDB is unable to properly load the newly created PipePlugin. The reason is that after IOTDB drops a PipePlugin, the corresponding jar file is not deleted, and the class loader behavior in loading the same fully qualified class name in the Install directory is random, as there is no unified standard, which leads to the above error.
1. **New Directory Structure**: Adopt a new directory structure `install->pluginName->jar`. The advantage of using this new directory is that the class loader does not need to load all jars. However, using this form will also not support the case where different jars reference …

Pipe Plugin: Pipe Task Safe Deletion, Plugin Directory Structure Reorganization, and Isolated Pipe Plugin ClassLoader Implementation

---

integration-test/src/test/java/org/apache/iotdb/db/it/schema/regionscan/IoTDBActiveRegionScanWithTTLIT.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/AbstractRegionScanForActiveDataUtil.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/ActiveDeviceRegionScanOperator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/ActiveTimeSeriesRegionScanOperator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/RegionScanForActiveDeviceUtil.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/RegionScanForActiveTimeSeriesUtil.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/OperatorTreeGenerator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/utils/TimeFilterForDeviceTTL.java

Data may remains in database even if it's out-dated due to the TTL. We need to filter such data in region scan.
Different from series scan which contains only one device which can use the TTL info of that device to update timeFilter,
a lot of devices share the same timeFilter in region scan.
So we can't update the timeFilter in advance, we need to calculate the real time range by TTL of the specified device one by one. In such procedure, we can use some cache technology to reduce the cost.
In this PR, we use a new timeFilter TimeFilterForDeviceTTL to replace the original timeFilter for above purpose.

Consider TTL of device in Region  scan for active data

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/common/MPPQueryContext.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/fragment/FragmentInstanceExecution.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/fragment/QueryStatistics.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/process/FilterAndProjectOperator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/FileLoaderUtils.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/scheduler/FragmentInstanceDispatcherImpl.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/statement/sys/ExplainAnalyzeStatement.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/statistics/FragmentInstanceStatisticsDrawer.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/statistics/QueryPlanStatistics.java
iotdb-protocol/thrift-datanode/src/main/thrift/datanode.thrift

This PR add some new metrics for EXPLAIN ANALYZE  and fix some bugs:
1. the cost to dispatch FragmentInstance for one query
2. pageReaderMaxUsedMemorySize for one FragmentInstance
3. TimeSeriesMetadataModificationCount/Time for one FragmentInstance
1. Fix wrong filteredRowCount in FilterAndTransformOperator
2. Fix permission of EXPLAIN ANALYZE to keep it the same query SQL.

Extend fucntion of EXPLAIN ANALYZE 

---

integration-test/src/test/java/org/apache/iotdb/subscription/it/local/IoTDBSubscriptionBasicIT.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/task/subtask/connector/PipeRealtimePriorityBlockingQueue.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/conf/CommonConfig.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/conf/CommonDescriptor.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/config/PipeConfig.java

Introduce counter to return TsFileInsertionEvent if event consumption goes over 'pendingQueueConsumeThreshold'
<hr>
This PR has:
<hr>

Pipe: Introduce counter to reduce historical data buildup in PipeRealtimePriorityBlockingQueue

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/common/MPPQueryContext.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/scheduler/FragmentInstanceDispatcherImpl.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/statistics/FragmentInstanceStatisticsDrawer.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/statistics/QueryPlanStatistics.java

an example output:
|Analyze Cost: 26.489 ms                                                                        |
|Fetch Partition Cost: 3.825 ms                                                                 |
|Fetch Schema Cost: 21.259 ms                                                                   |
|Logical Plan Cost: 0.340 ms                                                                    |
|Logical Optimization Cost: 0.010 ms                                                            |
|Distribution Plan Cost: 1.019 ms                                                               |
|Single Dispatch Cost: 0.795 ms                                                                 |
|Fragment Instances Count: 4
|FRAGMENT-INSTANCE[Id: 20240712_140939_00011_1.3.0][IP: …

Perfect the print result of dispatch and timeseries metadata modification in explain analyze

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/wal/io/WALMetaData.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/wal/io/WALFileTest.java

Fix uncaught IllegalArgumentException when reading broken WAL files

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/load/LoadTsFileManager.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/rescon/disk/strategy/SequenceStrategy.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/utils/IOUtils.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/utils/JVMCommonUtils.java

As the title indicates.
The frequent deletion and re-creation of the top-level load dir may cause concurrent issues, which lead to failures of getting disk space.

Do not remove top-level load dir after load & add retry for getting disk space

---

.github/workflows/multi-language-client.yml
iotdb-client/client-py/pom.xml

The maven module of the client-py is missing the dependency of iotdb-thrift. It will cause an unexpected issue when package the python client. 
When we released 1.3.2 python client, we included a local thrift file of the master branch instead of building it again.
A new package https://pypi.org/project/apache-iotdb/1.3.2.post0/ released.

Fix python client dependency issue

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/subscription/agent/SubscriptionBrokerAgent.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/subscription/agent/SubscriptionConsumerAgent.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/subscription/agent/SubscriptionTopicAgent.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/subscription/broker/SubscriptionBroker.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/subscription/broker/SubscriptionPrefetchingTsFileQueue.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/subscription/event/SubscriptionEvent.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/subscription/receiver/SubscriptionReceiverV1.java

Subscription: avoid invalidating cache for null response & improve exception message

---

iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/load/balancer/RegionBalancer.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/load/balancer/region/PartiteGraphReplicationRegionGroupAllocator.java

Better region group allocator with smaller time complexity O(n log n) and promised scatter width lower bound

Cherry pick Partite Graph Replication

---

pom.xml

The org.apache.thrift.tools:maven-thrift-plugin is old and largely unmaintained (last updated 2013). It should not be used anymore. The correct plugin to use is org.apache.thrift:thrift-maven-plugin which was last updated in 2017.

Upgrade thrift plugin and optimize codegen for go client

---

pom.xml

Dependency maven:org.jline:jline:3.23.0 is vulnerable
Upgrade to 3.26.2
CVE-2023-50572,  Score: 5.5
An issue in the component "GroovyEngine.execute" of jline-groovy versions through 3.24.1 allows attackers to cause an OOM (OutofMemory) error.
Read More: https://devhub.checkmarx.com/cve-details/CVE-2023-50572?utm_source=jetbrains&utm_medium=referral

Bump jline version to 3.26.2

---

integration-test/src/test/java/org/apache/iotdb/pipe/it/autocreate/IoTDBPipeAlterIT.java
iotdb-core/antlr/src/main/antlr4/org/apache/iotdb/db/qp/sql/IoTDBSqlParser.g4
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/persistence/pipe/PipeTaskInfo.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/pipe/task/AlterPipeProcedureV2.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/store/ProcedureFactory.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/store/ProcedureType.java
iotdb-core/confignode/src/test/java/org/apache/iotdb/confignode/procedure/impl/pipe/task/AlterPipeProcedureV2Test.java
iotdb-core/confignode/src/test/java/org/apache/iotdb/confignode/procedure/impl/pipe/task/AlterPipeProcedureV3Test.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/execution/config/executor/ClusterConfigTaskExecutor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/parser/ASTVisitor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/statement/metadata/pipe/AlterPipeStatement.java
iotdb-protocol/thrift-confignode/src/main/thrift/confignode.thrift

Enhancing the existing Alter Pipe SQL functionality, the upgrade now permits dynamic adjustments to the Pipe Source configuration. Users can seamlessly adapt their data synchronization strategies to real-time changes in resources and requirements, thus improving the efficiency and effectiveness of their data stream processing.
```SQL
Alter Pipe <pipe_name>
modify|replace source(...)
modify|replace processor(...)
modify|replace sink(...)
```
<hr>
This PR has:
<hr>

Pipe: support alter pipe source

---

iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/iot/log/ConsensusReqReader.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/consensus/statemachine/dataregion/DataExecutionVisitor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/consensus/statemachine/dataregion/DataRegionStateMachine.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/plan/node/PlanNodeType.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/plan/node/write/BatchDoneNode.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/plan/node/write/ContinuousSameSearchIndexSeparatorNode.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/DataRegion.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/wal/buffer/WALEntry.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/wal/buffer/WALEntryType.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/wal/buffer/WALInfoEntry.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/wal/node/IWALNode.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/wal/node/WALFakeNode.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/wal/node/WALNode.java

In the current Write-Ahead Logging (WAL) mechanism, write operations with the same sequence number may be split into multiple WAL entries and written into different WAL files. IoTConsensus constructs synchronization batches from WAL files for synchronization between replicas. Taking a write operation with sequence number `a` as an example, the sync batch constructed by IoTConsensus for operation `a` needs to **completely** include all WAL entries with sequence number `a`.
The problem lies in how to determine "**completely**".
As the flushing of WAL is asynchronous, IoTConsensus currently waits until a write operation with sequence number `a+1` arrives, or some other operation with a sequence number of `-1` (indicating no need for synchronization between replicas) arrives, before …

Fix sync stuck problem of IoTConsensus and WAL

---

iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/pipe/coordinator/runtime/PipeLeaderChangeHandler.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/pipe/task/AlterPipeProcedureV2.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/pipe/task/CreatePipeProcedureV2.java

Pipe: filter out databases whose name starts with `root.__system.`

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/client/ConfigNodeClient.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/service/DataNode.java

If ConfigNode and DataNode are started at the same time, there are still some ports of ConfigNode that have not been bound, and DataNode will enter sleep. We reduce the sleep time and increase the retry times to let DataNode detect the ports bound by ConfigNode as soon as possible.

Modify the default parameters of DataNode to accelerated startup

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/wal/buffer/AbstractWALBuffer.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/wal/buffer/IWALBuffer.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/wal/io/LogWriter.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/wal/io/WALWriter.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/wal/node/WALNode.java

Ensure that the wal file does not trigger a file switch if it contains only a Magic String Header of length 6

Fixed issue where the wal version kept increasing after the write load stopped

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/cache/partition/PartitionCache.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/service/metrics/IoTDBInternalLocalReporter.java
iotdb-core/metrics/interface/src/main/java/org/apache/iotdb/metrics/reporter/iotdb/IoTDBSessionReporter.java

The device paths prefixed with root.__system will no longer be affected by the default_storage_group_level configuration when created automatically. The root.__system system database will always be created automatically.

Enhance the automatic metadata creation logic of root.__system prefixed devices

---

iotdb-core/datanode/src/test/java/org/apache/iotdb/db/utils/DateTimeUtilsTest.java

This is a guess at a fix. There are probably other ways to fix this test too:
- For a UTC timezone via surefire system properties
- Change the timestamps
- probably a few more, with a bit more knowledge of IoTDB...
DateTimeUtilsTest.getConvertDurationIncludingMonthUnit() uses dates conversions that are TZ specfic.
Wrapping the test in a session, allows this single test to use a set timezone, while not affecting the behavior of other tests
Fixes: #12970
<hr>
This PR has:
<hr>

Wraps DateTimeUtilsTest in a session

---

.github/workflows/cluster-it-1c1d.yml
.github/workflows/cluster-it-1c3d.yml
.github/workflows/daily-it.yml
.github/workflows/multi-language-client.yml
.github/workflows/pipe-it-2cluster.yml
.github/workflows/sonar-codecov.yml
.github/workflows/unit-test.yml

The CI builds show artifact download stats as:
```
Downloading from central: https://repo.maven.apache.org/maven2/...
Progress (1): 0.1/18 MB
Progress (1): 0.2/18 MB
Progress (1): 0.3/18 MB
Progress (1): 0.4/18 MB
Progress (1): 0.5/18 MB
...
```
This makes logs difficult to read, these log lines can be removed using '--no-transfer-progress'
This change also sets `--batch-mode` to ensure Maven does not prompt for user input
<hr>
This PR has:
<hr>

Remove verbose download log spam from CI builds

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/wal/buffer/WALBuffer.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/wal/exception/BrokenWALFileException.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/wal/io/WALMetaData.java

Do not print stack traces when the exception is a known one.

Optimize log for broken wal

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/cache/partition/PartitionCache.java

Allows root.__system prefix time series creation

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/service/metrics/IoTDBInternalLocalReporter.java

Add automatic creation logic when internal time series fail to write due to metadata issues

Ensure the flush total points statistic function works correctly when enable_auto_create_schema is false

---

distribution/src/assembly/all.xml
distribution/src/assembly/cli.xml
distribution/src/assembly/client-cpp.xml
distribution/src/assembly/common-files.xml
distribution/src/assembly/confignode.xml
distribution/src/assembly/datanode.xml
distribution/src/assembly/library-udf.xml
integration-test/src/assembly/mpp-test.xml
iotdb-core/confignode/src/assembly/confignode.xml
iotdb-core/datanode/src/assembly/server.xml

The property `maven.multiModuleProjectDirectory` is not officially support and can be removed at any time, it has been removed when using mvnd.
The current alternative with Maven 3 is using path traversal from the current module's directory
Fixes: #12981
<hr>
This PR has:
<hr>

Replaces the internal maven property with an officially supported alternative

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/wal/WALManager.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/wal/io/LogWriter.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/wal/io/WALFileVersion.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/wal/io/WALInputStream.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/wal/io/WALMetaData.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/wal/io/WALWriter.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/wal/recover/WALRepairWriter.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/wal/compression/WALCompressionTest.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/wal/recover/WALRepairWriterTest.java

A broken V1 wal file will be misjudged as UNKNOWN, truncating the whole file.

Remove UNKNOWN from WALFileVersion which fails recovering V1 WAL file

---

iotdb-client/cli/src/test/java/org/apache/iotdb/tool/WriteDataFileTest.java
iotdb-core/consensus/src/test/java/org/apache/iotdb/consensus/ratis/TestUtils.java
iotdb-core/datanode/pom.xml
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/utils/constant/TestConstant.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/wal/io/WALFileTest.java
pom.xml

> [!NOTE]
> This does NOT set Surefire's `forkCount` property, that will be done on an isolated commit
This is to ensure these changes don't negatively affect the existing build.
Details on changes:
- Change to test working directory
The working directory was changed from `${project.build.directory}` to `${project.build.directory}/fork_${surefire.forkNumber}` (single fork builds would be `<module_name>/target/fork_1`),
This isolates any test output written to relative paths.  Long term tests may want to be more explicit where they write output to, (e.g. using JUnit 5's `@TempDir` annotation)
- IOTDB_CONF property
Becuse the working directory change, the IOTDB_CONF directory needs to resolve differently, however, even without parallel tests, this property _should_ use an absolute path
- …

Allows for unit tests to be run in parallel

---

iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/pipe/metric/PipeConfigNodeMetrics.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/pipe/metric/PipeConfigNodeReceiverMetrics.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/pipe/receiver/protocol/IoTDBConfigNodeReceiver.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/metric/PipeDataNodeMetrics.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/metric/PipeDataNodeReceiverMetrics.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/receiver/protocol/thrift/IoTDBDataNodeReceiver.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/service/metric/enums/Metric.java

add ops monitoring metrics for confignode and datanode to measure different pipe receivers
the four indicators are as follows:
1. OPS Of PipeReceiver
2. Time Consumed Of PipeReceiver (avg)
3. Time Consumed Of PipeReceiver (50%)
4. Time Consumed Of PipeReceiver (99%)
the effect is as follows:

Pipe: add ops/latency metrics for different types of pipe operations on receivers (DN / CN)

---

integration-test/src/test/java/org/apache/iotdb/subscription/it/triple/AbstractSubscriptionTripleIT.java
integration-test/src/test/java/org/apache/iotdb/subscription/it/triple/IoTDBSubscriptionSharingIT.java
iotdb-client/service-rpc/src/main/java/org/apache/iotdb/rpc/subscription/config/TopicConfig.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/payload/evolvable/batch/PipeTabletEventTsFileBatch.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/subscription/broker/SubscriptionPrefetchingQueue.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/subscription/broker/SubscriptionPrefetchingTabletQueue.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/subscription/broker/SubscriptionPrefetchingTsFileQueue.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/subscription/event/batch/SubscriptionPipeTabletEventBatch.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/subscription/event/batch/SubscriptionPipeTsFileEventBatch.java

> Special thanks to Chang Xue for providing the test scenarios.
During the process of converting a tablet to tsfile, it is possible that the generated tsfiles contain duplicate data. **Therefore, under normal consumption (no re-consumption situation), the tsfile format data CANNOT ensure that the total consumed data equals the written data. It can only be guaranteed that the total consumed data in the dataset format equals the written data**.
It should be noted that the parameter `updateFunction` of the `getAndUpdate` method of `AtomicReference` is required to be a side-effect-free function, as `updateFunction` may be execute concurrently.
If multiple threads call `batch.onEvent` at the same time, and if one thread returns true and seals the batch, the remaining threads still blocked on …

Subscription: fix concurrent issues related to seal batch & use hybrid realtime extractor for tsfile format topic

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/wal/node/WALNode.java

The previous code of `PlanNodeIterator` was very confusing (especially the `hasNext()` function). This PR organizes and simplifies the logic of the `hasNext()` function, removing some unnecessary special judgments, variables, and loops. Now, PlanNodeIterator works according to the following principles:
As an iterator, it has two "loop invariants". First, the member variable `nextSearchIndex` monotonically increases and always points to the SearchIndex that is currently collecting WalEntry. Once all related WalEntries are collected, `nextSearchIndex` will increment. Second, `filesToSearch[currentFileIndex]` always points to the WAL file currently being read.
Each time hasNext() is called, it will sequentially traverse the files, continuously collecting WalEntries with `nextSearchIndex` …

Optimize WALNode.PlanNodeIterator.hasNext

---

iotdb-client/service-rpc/src/main/java/org/apache/iotdb/rpc/subscription/config/TopicConfig.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/subscription/topic/CreateTopicProcedure.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/execution/config/executor/ClusterConfigTaskExecutor.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/subscription/meta/topic/TopicMeta.java

Subscription: display the now value as the actual timestamp when showing the topic

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/executor/RegionReadExecutor.java

- Fix the exception capture logic in https://github.com/apache/iotdb/pull/13001.
- catch `CONSENSUS_GROUP_NOT_EXIST` directly

[region migration] Fix exception capture processing logic

---

iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/IStateMachine.java
iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/common/Utils.java
iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/iot/IoTConsensusServerImpl.java
iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/ratis/SnapshotStorage.java
iotdb-core/consensus/src/test/java/org/apache/iotdb/consensus/ratis/SnapshotTest.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/consensus/statemachine/dataregion/DataRegionStateMachine.java

the .md5 suffix is not filtered in Path.endWith(".md5"), so we should get the filename of string

fix md5 suffix too many

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/receiver/protocol/pipeconsensus/PipeConsensusReceiver.java

In PipeConsensus, in order to accept tsfile in parallel, the tsfileWriterPool mechanism is introduced: each time a tsfilePiece is written, it will first try to get a tsfileWriter from the pool. If it cannot get one, it will block the polling until it gets a writer. The number of tsfileWriters in the tsfileWriterPool is equal to the number of pipelines.
Under normal circumstances, this mechanism is fine. Because as long as the previous tsfile completes the sealing, it will return the writer to the pool. This ensures that the tsfiles waiting in line for writers will eventually get the writer and will not be blocked all the time.
However, there are **two scenarios** that may cause problems:
1. **Some physical problems occur in the Follower machine, resulting in the tsfile sealing being …

PipeConsensus: Fix replication block when leader restart.

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/metadata/fetcher/cache/TableDeviceCacheEntry.java

Fixed the NPE in TableDeviceCacheEntry when attribute value is null

---

integration-test/src/test/java/org/apache/iotdb/db/it/utils/TestUtils.java
integration-test/src/test/java/org/apache/iotdb/relational/it/db/it/IOTDBInsertWithTimeAtAnyIndexIT.java
integration-test/src/test/java/org/apache/iotdb/relational/it/db/it/IoTDBEncodingIT.java
integration-test/src/test/java/org/apache/iotdb/relational/it/db/it/IoTDBExecuteBatchIT.java
integration-test/src/test/java/org/apache/iotdb/relational/it/db/it/IoTDBFloatPrecisionIT.java
integration-test/src/test/java/org/apache/iotdb/relational/it/db/it/IoTDBFlushQueryIT.java
integration-test/src/test/java/org/apache/iotdb/relational/it/db/it/IoTDBInsertMultiPartitionIT.java
integration-test/src/test/java/org/apache/iotdb/relational/it/db/it/IoTDBInsertMultiRowIT.java
integration-test/src/test/java/org/apache/iotdb/relational/it/db/it/IoTDBInsertNaNIT.java
integration-test/src/test/java/org/apache/iotdb/relational/it/db/it/IoTDBInsertNullIT.java
integration-test/src/test/java/org/apache/iotdb/relational/it/db/it/IoTDBInsertWithoutTimeIT.java
integration-test/src/test/java/org/apache/iotdb/relational/it/db/it/IoTDBMultiDeviceIT.java
integration-test/src/test/java/org/apache/iotdb/relational/it/db/it/IoTDBPartialInsertionIT.java
integration-test/src/test/java/org/apache/iotdb/relational/it/db/it/IoTDBRecoverIT.java
integration-test/src/test/java/org/apache/iotdb/relational/it/db/it/IoTDBRecoverUnclosedIT.java
integration-test/src/test/java/org/apache/iotdb/relational/it/db/it/IoTDBRestartIT.java
integration-test/src/test/java/org/apache/iotdb/relational/it/db/it/IoTDBSameMeasurementsDifferentTypesIT.java
integration-test/src/test/java/org/apache/iotdb/relational/it/db/it/aligned/IoTDBInsertAlignedValues2IT.java
integration-test/src/test/java/org/apache/iotdb/relational/it/db/it/aligned/IoTDBInsertAlignedValues3IT.java
integration-test/src/test/java/org/apache/iotdb/relational/it/db/it/aligned/IoTDBInsertAlignedValues4IT.java
integration-test/src/test/java/org/apache/iotdb/relational/it/db/it/aligned/IoTDBInsertAlignedValuesIT.java
integration-test/src/test/java/org/apache/iotdb/relational/it/db/it/schema/IoTDBAutoCreateSchemaIT.java
integration-test/src/test/java/org/apache/iotdb/relational/it/db/it/schema/IoTDBCreateAlignedTimeseriesIT.java
integration-test/src/test/java/org/apache/iotdb/relational/it/db/it/schema/IoTDBCreateStorageGroupIT.java
integration-test/src/test/java/org/apache/iotdb/relational/it/db/it/schema/IoTDBCreateTimeseriesIT.java

Add relational it

---

integration-test/src/test/java/org/apache/iotdb/relational/it/schema/IoTDBTableIT.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/schema/ClusterSchemaManager.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/persistence/schema/ClusterSchemaInfo.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/persistence/schema/ConfigMTree.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/schema/table/CreateTableProcedure.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/state/schema/CreateTableState.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/exception/metadata/table/TableAlreadyExistsException.java

Fixed the bug that duplicate table creation may delete the original table

---

integration-test/src/test/java/org/apache/iotdb/subscription/it/local/IoTDBSubscriptionBasicIT.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/event/common/tablet/PipeRawTabletInsertionEvent.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/event/common/tsfile/PipeTsFileInsertionEvent.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/event/realtime/PipeRealtimeEventFactory.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/extractor/dataregion/historical/PipeHistoricalDataRegionTsFileExtractor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/subscription/broker/TsFileDeduplicationBlockingPendingQueue.java

Improve #12887.
If two identical tsfiles (one extracted as historical data and one extracted as real-time data) are parsed into PipeRawTabletInsertionEvent in the processor stage, the existing deduplication code cannot detect this situation.

Subscription: improve deduplication logic for PipeRawTabletInsertionEvent

---

iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/iot/IoTConsensus.java
iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/iot/service/IoTConsensusRPCService.java
iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/iot/service/IoTConsensusRPCServiceProcessor.java
iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/pipe/PipeConsensus.java
iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/pipe/service/PipeConsensusRPCService.java
iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/pipe/service/PipeConsensusRPCServiceProcessor.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/service/ThriftService.java

Due to async service have some problems, we just change async method to sync.
The reason why we need change async service to sync can see https://github.com/apache/thrift/pull/3010
In this pr,  we modify IotConsensusRPCServiceProcessor and PipeConsensusRPCServiceProcessor interface  from AsyncIface to IFace so that we can use sync service.  
For async methods, we need a future as arguments and return this future with onCompete, but sync method just return the resp.

[fix] Change IoTConsensusService and PipeConsensusService from async  to sync 

---

iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/iot/IoTConsensus.java
iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/iot/IoTConsensusServerImpl.java
iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/iot/service/IoTConsensusRPCServiceProcessor.java

This PR replace some `throw Exception` to `logger.warn`.
Because during removing region peer step, we always want the migration procedure continue, even if there are some mistake.

Improve robustness of removing peer step of region migration 

---

integration-test/src/main/java/org/apache/iotdb/it/env/cluster/env/AbstractEnv.java
integration-test/src/main/java/org/apache/iotdb/itbase/env/BaseEnv.java
integration-test/src/test/java/org/apache/iotdb/session/it/IoTDBSessionRelationalIT.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/exception/sql/ColumnCreationFailException.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/common/MPPQueryContext.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/AnalyzeUtils.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/AnalyzeVisitor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/Analyzer.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/execution/config/executor/ClusterConfigTaskExecutor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/analyzer/Analyzer.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/metadata/Metadata.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/metadata/MetadataUtil.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/metadata/TableMetadataImpl.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/metadata/fetcher/TableHeaderSchemaValidator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/sql/ast/InsertRow.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/sql/ast/InsertRows.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/sql/ast/InsertTablet.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/sql/ast/Use.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/sql/ast/WrappedInsertStatement.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/sql/parser/AstBuilder.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/statement/crud/InsertBaseStatement.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/statement/crud/InsertRowStatement.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/utils/annotations/TableModel.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/utils/annotations/TreeModel.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/plan/relational/analyzer/AnalyzerTest.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/plan/relational/analyzer/TestMatadata.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/plan/statement/InsertStatementTest.java

Insert statement can specify the database within it.
An exception is thrown when both session and statement do not have db.
Clarify exception message when the table does not exist.
The database name is retrieved from the qualified name correctly.

Multiple fixes regarding database specification

---

integration-test/src/test/java/org/apache/iotdb/relational/it/db/it/IoTDBSetConfigurationIT.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/Coordinator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/execution/config/TableConfigTaskVisitor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/parser/ASTVisitor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/sql/ast/AstVisitor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/sql/ast/SetConfiguration.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/sql/parser/AstBuilder.java
iotdb-core/relational-grammar/src/main/antlr4/org/apache/iotdb/db/relational/grammar/sql/RelationalSql.g4

Add `set configuration` sql, which is different from the usage in tree model. 
```
set configuration a=1,b=2
```
```
set configuration a=1,b='1',c="1","d"=1 on 1
```

Support set configuration sql

---

iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/iot/IoTConsensusServerImpl.java

Fix IoTConsensus log explosion when stoping one node

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/utils/TypeInferenceUtils.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/utils/TypeInferenceUtilsTest.java

String ends with `F` and `L` should be inferred to the same type. In this PR, I unify them to `TEXT`.

Unify string type inference

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/memtable/TsFileProcessor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/wal/allocation/FirstCreateStrategy.java

If the creation of a WAL node is interrupted and FirstCreateStrategy is used, a null WAL node will be returned, causing subsequent insertion to fail with an NPE.

Handle exception when the WAL initializtion is interrupted

---

LICENSE

This PR is adding attribution information of the code modified from lt_downsampling_java8 project. It's also removing the attribution information of the code in tsfile, which should not be in IoTDB repo any more.

Update license information

---

integration-test/src/test/java/org/apache/iotdb/relational/it/query/old/orderBy/IoTDBOrderByTableIT.java
integration-test/src/test/java/org/apache/iotdb/relational/it/query/old/orderBy/IoTDBStreamSortIT.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/planner/RelationPlanner.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/planner/TranslationMap.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/planner/ir/ExpressionRewriter.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/planner/ir/ExpressionTreeRewriter.java

Support below sql: `select Time,num,bigNum,floatNum,str,bool from table0 t where t.device='d1' order by bigNum,t.time`.
Before this pr, this sql will throw error.
<hr>
This PR has:
<hr>

Add AliasRelation support

---

iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/ratis/RatisConsensus.java

Fix a corner case where the group may not exist during the execution of a Ratis read.

[Region Migration] Convert a Ratis exception to enable read retry

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/service/DataNode.java

Sometimes we shut down some machines in the cluster. Due to the high availability provided by the consensus layer, we can still move data from the stopped machines through the CLI. However, when these stopped machines restart, they still think they are in the corresponding consensus group. In fact, since the data has been migrated during the shutdown, we should clean up these invalid data when restarting. 
In this PR, we fix the problem of not cleaning up the invalid schema region

Clear Invalid schema region when restarting

---

iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/region/RegionMigrateProcedure.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/store/ProcedureFactory.java

[region migration] Ignore old region migration procedure during procedure framework updating

---

.github/workflows/multi-language-client.yml

The previous maven command for cpp client is not working on Ubuntu 20. In this PR, I update the maven command for cpp client on Linux and add the CI for Ubuntu 20 and 24.

Add Cpp client CI for Ubuntu 20 and 24

---

iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/load/cache/AbstractLoadCache.java

As the term and leader reported by the Ratis interfaces might inconsistent with a small probability, the ConfigNode might end up with caching incorrect leader location. By caching all heartbeat samples, the ConfigNode can ensure the eventually consistency for all leader locations of all RegionGroups use the Ratis consensus protocol.

Eventually consistent heartbeat samples

---

iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/consensus/statemachine/ConfigRegionStateMachine.java
iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/IStateMachine.java
iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/ratis/ApplicationStateMachineProxy.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/consensus/statemachine/schemaregion/SchemaRegionStateMachine.java

The current Ratis module's Leader may step down voluntarily without knowing who the new Leader is, which will not trigger the state machine's notifyLeaderChange callback. As a result, some modules that rely on this interface to determine whether the current node is no longer the Leader might delay resource release, potentially causing split-brain issues with multiple Leaders.
For example, in a 3-node ConfigNode setup, if a symmetric network partition fault is injected into the Leader node, the other two nodes will elect a new Leader. However, certain services (such as heartbeat, procedure, etc.) on the old Leader will not be cleared, leading to a split-brain scenario, which could cause some unexpected behavior.
After this PR, even if the new Leader is unknown, Ratis will still call the …

Avoid the brain split phenomenon in the symmetric network partition scenario

---

iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/env/RegionMaintainHandler.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/region/RegionMigrateProcedure.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/region/RemoveRegionPeerProcedure.java
iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/ratis/RatisClient.java
iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/ratis/RatisConsensus.java

If the current region configuration is [a, b, c], we execute the migrate region id from c to d, and the leader is a. During the region migration process, due to the need to catch up with the new node d, if the data is large, it may take a long time.
Assuming that the operations before the execution of the Remove phase are successful, the region configuration at this time should be [a, b, c, d], and then start executing RemoveRegion, but due to some reasons, the RemoveRegion operation has not been completed, resulting in the failure of the DELETE_REGION_PEER phase timeout in the executeFromState function of RemoveProcessure, and then enter the DELETE_OLD_REGION_PEER, the new node d has not caught up with a successfully, and the old node c has been deleted. 
If the leaderTransfership is …

RegionMigrate: Fix migrating region with ratisConsensus cause the region is unavailable.

---

integration-test/src/test/java/org/apache/iotdb/relational/it/db/it/IoTDBInsertTableIT.java
integration-test/src/test/java/org/apache/iotdb/relational/it/db/it/IoTDBSetConfigurationTableIT.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/sql/parser/AstBuilder.java

Modify 'set configuration' in relational grammar.
Previous modification is https://github.com/apache/iotdb/pull/13089. Some usages are no longer supported.
```
set configuration "a"='1',b='1' on 1
```
```
set configuration "a"='1',b='1'
```
```
set configuration a='1'
```

Modify 'set configuration' in relational grammar

---

.github/workflows/cluster-it-1c1d.yml
.github/workflows/cluster-it-1c3d.yml
.github/workflows/pipe-it-2cluster.yml
.github/workflows/table-cluster-it-1c1d.yml
.github/workflows/table-cluster-it-1c3d.yml
.github/workflows/unit-test.yml

Pipe IT: Reduce FT runner cost by removing some manual-create-schema test cases

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/client/ConfigNodeClient.java

as title.
there is a case: when **CN1** leader is killed -9, The CN cluster may not be aware of this **immediately**, causing requests sent to the cluster to still be redirected to **CN1**. Due to the lack of waiting machinism in DN, DN may exhaust all retry count(10 times) in a very short time(about 500ms in 16C32G server) and all these retry requests will still be redirected to the 
dead node CN1, causing failure of user request.

Make DN wait when CN cluster's leader is not ready or down.

---

integration-test/src/test/java/org/apache/iotdb/relational/it/query/old/builtinfunction/scalar/IoTDBScalarFunctionTableIT.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/relational/ColumnTransformerBuilder.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/metadata/TableMetadataImpl.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/sql/parser/AstBuilder.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/transformation/dag/column/unary/scalar/AcosColumnTransformer.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/transformation/dag/column/unary/scalar/AsinColumnTransformer.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/transformation/dag/column/unary/scalar/AtanColumnTransformer.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/transformation/dag/column/unary/scalar/CeilColumnTransformer.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/transformation/dag/column/unary/scalar/CosColumnTransformer.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/transformation/dag/column/unary/scalar/CoshColumnTransformer.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/transformation/dag/column/unary/scalar/DegreesColumnTransformer.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/transformation/dag/column/unary/scalar/ExpColumnTransformer.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/transformation/dag/column/unary/scalar/FloorColumnTransformer.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/transformation/dag/column/unary/scalar/LnColumnTransformer.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/transformation/dag/column/unary/scalar/Log10ColumnTransformer.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/transformation/dag/column/unary/scalar/RadiansColumnTransformer.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/transformation/dag/column/unary/scalar/SignColumnTransformer.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/transformation/dag/column/unary/scalar/SinColumnTransformer.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/transformation/dag/column/unary/scalar/SinhColumnTransformer.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/transformation/dag/column/unary/scalar/SqrtColumnTransformer.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/transformation/dag/column/unary/scalar/TanColumnTransformer.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/transformation/dag/column/unary/scalar/TanhColumnTransformer.java

The main purpose of this work is to fix some known issues in scalar functions. 
First, the support for timestamp data type in mathematical scalar functions has been removed, considering that the data type of timestamp does not have practical significance in the use of scalar functions. This part has made modifications to all mathematical scalar functions and also to the related IT.
Secondly, support for the || symbol has been added, as the || symbol is semantically consistent with the concat function, so in astbuilder, || is treated as a function call for concat.
Finally, for the return value types of upper, lower, and trim, they have been modified to return string instand of consistently with the input type, which is a modification made according to the actual application requirements.

fix scalar function args and return type problem

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/payload/evolvable/batch/PipeTabletEventBatch.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/payload/evolvable/batch/PipeTransferBatchReqBuilder.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/protocol/thrift/async/IoTDBDataRegionAsyncConnector.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/protocol/thrift/sync/IoTDBDataRegionSyncConnector.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/task/subtask/connector/PipeConnectorSubtask.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/task/subtask/connector/PipeConnectorSubtaskLifeCycle.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/connector/protocol/IoTDBConnector.java

Try to fix https://jira.infra.timecho.com:8443/browse/TIMECHODB-911

Pipe: discard batched events before restarting pipes

---

integration-test/src/test/java/org/apache/iotdb/relational/it/query/old/builtinfunction/scalar/IoTDBScalarFunctionTableIT.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/metadata/TableMetadataImpl.java
pom.xml

The main focus of this work is to verify the mathematical functions within the IT of the scalar function, using double precision for the verification to avoid issues with different computational accuracies across computers. In addition to this, in the previous modification, support for the timestamp in mathematical functions was removed, but the timestamp information in the error messages was inadvertently left out. This work has fixed this issue.

Compare in double and fix error message

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/receiver/protocol/pipeconsensus/PipeConsensusReceiver.java

as title.
After this pr, every thread response for receiving tsFilePiece will has its own writing dir and file.
For example, if there are 5 tsFileWriters(which means the parallel degree/pipeline of PipeConsensusReceiver for receiving tsFile is 5), these 5 tsFileWriters will have its own dir naming from 0 - 4 respectively

PipeConsensus: build separate dir for each receiver thread.

---

integration-test/src/test/java/org/apache/iotdb/relational/it/db/it/IoTDBMultiIDsWithAttributesTableIT.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/TableOperatorGenerator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/planner/iterative/rule/MergeLimitOverProjectWithMergeSort.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/planner/iterative/rule/MergeLimitOverProjectWithSort.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/planner/iterative/rule/MergeLimitWithMergeSort.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/planner/iterative/rule/MergeLimitWithSort.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/plan/relational/analyzer/SortTest.java

As the title.
Before fix, sql `SELECT time, attr1, s1 FROM table1 order by attr2 limit 5` will throw errors.
<hr>
This PR has:
<hr>

Fix the error that columns in sort is not appear in projection

---

iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/ratis/RatisClient.java

For RatisClient returns reply,  we need to handle these execption in different policy.
In this pr, we use EndLessRetryPolicy and LimitRetryPlicy

[Fix] Add another retryPolicy for RatisClient

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/rescon/quotas/DataNodeSpaceQuotaManager.java

Fixed the heartbeat rewritten bug of space quota usage

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/service/metrics/CompactionMetrics.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/performer/impl/RepairUnsortedFileCompactionPerformer.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/utils/CompactionUtils.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/repair/RepairDataFileScanUtil.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/selector/estimator/AbstractCompactionEstimator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/selector/impl/SettleSelectorImpl.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/selector/utils/TsFileResourceCandidate.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/utils/TsFileResourceUtils.java

1. Add 'deserialize_resource' metric item in compaction
2. Record deserialized resource file size in rate limiter
3. Remove 'totalCompactionReadInfoCounter'(whose tag is not correctly set in past version) and 'totalCompactionWriteInfoCounter'

Add 'deserialize_resource' metric item in compaction

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/driver/Driver.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/fragment/FragmentInstanceExecution.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/fragment/FragmentInstanceState.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/scheduler/FixedRateFragInsStateTracker.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/utils/FileUtils.java

1. while restarting a DN, and meawhile the ongoing query's root FI is on that DN, will cause the query stuck forever, because previously we think FragmentInstanceState.NO_SUCH_INSTANCE is not a failure state.
2. clean sort tmp files more quitely, because we will do clean work in both FI callback and Driver close, so it may concurrently delete same file, but it's ok for cleaning work, so we don't need to print warn log for such case.

Fix query stuck while DN restarting & keep quite while cleaning sort tmp file

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/service/metrics/DataNodeMetricsHelper.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/load/active/ActiveLoadDirScanner.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/load/active/ActiveLoadPendingQueue.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/load/active/ActiveLoadTsFileLoader.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/load/metrics/ActiveLoadingFilesMetricsSet.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/load/metrics/ActiveLoadingFilesNumberMetricsSet.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/load/metrics/ActiveLoadingFilesSizeMetricsSet.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/service/metric/enums/Metric.java

(cherry picked from commit c5b8a59c477fe0bf39a3a8359752f295cdb449c9)

[To rc/1.3.3] Active Load: Add metrics for file size and refactor the code (#13329)

---

integration-test/src/main/java/org/apache/iotdb/it/env/cluster/ClusterConstant.java
integration-test/src/main/java/org/apache/iotdb/it/env/cluster/node/ConfigNodeWrapper.java
integration-test/src/main/java/org/apache/iotdb/it/env/cluster/node/DataNodeWrapper.java

Decrease default direct buffer size in it config

[to rc/1.3.3] Decrease default direct buffer size in it config

---

iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/event/EnrichedEvent.java

Pipe: avoid logging warn when clearing event ref after releasing the event & minor improve for javadoc

---

integration-test/src/main/java/org/apache/iotdb/it/env/cluster/config/MppCommonConfig.java
integration-test/src/main/java/org/apache/iotdb/it/env/cluster/config/MppSharedCommonConfig.java
integration-test/src/main/java/org/apache/iotdb/it/env/remote/config/RemoteCommonConfig.java
integration-test/src/main/java/org/apache/iotdb/itbase/env/CommonConfig.java
integration-test/src/test/java/org/apache/iotdb/pipe/it/autocreate/AbstractPipeDualAutoIT.java
integration-test/src/test/java/org/apache/iotdb/pipe/it/manual/AbstractPipeDualManualIT.java
integration-test/src/test/java/org/apache/iotdb/pipe/it/manual/IoTDBPipeReqAutoSliceIT.java

[To rc/1.3.3] Pipe IT: req size automatic fragmentation integration test (#13342)

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/StorageEngine.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/DataRegion.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/tsfile/TsFileManager.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/tsfile/TsFileResource.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/tsfile/timeindex/FileTimeIndexCacheRecorder.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/utils/fileTimeIndexCache/FileTimeIndexCacheReader.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/utils/fileTimeIndexCache/FileTimeIndexCacheWriter.java

FileTimeIndexCache may open too much file if there is too much time partitions.

Change FileTimeIndexCache to region level

---

.github/workflows/multi-language-client.yml

The free disk space is reduced on macos runner, which may cause the IoTDB start failed. 
Fix this issue by removing some useless xcode.
https://github.com/actions/runner-images/issues/10511

Fix cpp client IT on macos

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/planner/RelationPlanner.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/planner/TranslationMap.java

If not use HierarchyFieldIndex, some cases such as Join situation may cause errors.
<hr>
This PR has:
<hr>

Fix the error usage of HierarchyFieldIndex

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/task/InnerSpaceCompactionTask.java

Files that were skipped during inner compaction have been erroneously reassigned with the wrong parent file, resulting in an inability to create a hard link.

Fix the issue of hard linking to target files in inner compaction

---

iotdb-client/client-cpp/src/main/Session.h

The previous default authentication (username and password) in Client-CPP is inconsistent with Client-Java.

Fix default authentication of C++ Client

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/scheduler/FixedRateFragInsStateTracker.java

If we restart a DN while doing a query and then fetchStateAndUpdate may throw TException and won't record that FI's state.
If that FI is just rootFI, then if we use the old code:
```
boolean queryFinished =
instanceStateMap.values().stream()
.filter(instanceStateMetrics -> instanceStateMetrics.isRootInstance)
.allMatch(
instanceStateMetrics ->
instanceStateMetrics.lastState == FragmentInstanceState.FINISHED);
```
It will return true.

Fix query stuck caused by restarting DN while doing query

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/tsfile/timeindex/FileTimeIndexCacheRecorder.java

When execute the following sqls, there is some error log printed.
```
insert into root.sg.d1(time,s1) values(1,2)
flush
drop database root.**
```
This pr is fixing this issue.

Fix error log when drop database or migrate region

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/consensus/statemachine/dataregion/DataRegionStateMachine.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/consensus/statemachine/dataregion/IoTConsensusDataRegionStateMachine.java

A delete operation involving multiple paths or multiple Regions is split into several PlanNodes for execution and synchronization. On the receiving end of IoTConsensus, these PlanNodes need to be merged back into a single PlanNode for execution.

Properly handle the case where a single IndexedRequest contains multiple “delete PlanNode” operations on the receiving end of IoTConsensus.

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/subscription/broker/SubscriptionPrefetchingQueue.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/subscription/event/SubscriptionEvent.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/subscription/event/batch/SubscriptionPipeTabletEventBatch.java

cherry-pick #13405 to https://github.com/apache/iotdb/tree/rc/1.3.3

[To rc/1.3.3] Subscription: reduce the length of the stringified subscription event & do not print warn logs for eagerly pollable events

---

iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/event/EnrichedEvent.java

cherry-pick #13371 to https://github.com/apache/iotdb/tree/rc/1.3.3

[To rc/1.3.3] Pipe: avoid logging warn when clearing event ref after releasing the event & minor improve for javadoc

---

iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/node/ClusterNodeStartUtils.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/utils/ErrorHandlingUtils.java

1. Currently confignode is lack of the logic for AINode to restart, this PR add relating codes.
2. Add exception information handling for AINode.

Fix AINode restart functionality and enhance error clarity

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/utils/executor/readchunk/ReadChunkAlignedSeriesCompactionExecutor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/wal/io/WALInputStream.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/compaction/inner/NewReadChunkCompactionPerformerWithAlignedSeriesTest.java

https://github.com/apache/iotdb/pull/13380

[to rc/1.3.3] Check decoded page size in compaction

---

.asf.yaml

Attempt to trigger again because the invitation link of some collaborators has expired

Automatically trigger CI for active non-committer again

---

.asf.yaml

Remove two members temporarily to trigger invitation again

Automatically trigger CI for active non-committer 

---

integration-test/src/test/java/org/apache/iotdb/relational/it/schema/IoTDBDeviceIT.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/analyzer/predicate/schema/ConvertSchemaPredicateToFilterVisitor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/metadata/fetcher/TableDeviceSchemaFetcher.java

Fixed the bug that schema related query fails when get from cache with complicated filter

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/selector/utils/TsFileResourceCandidate.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/compaction/cross/InsertionCrossSpaceCompactionSelectorTest.java

https://github.com/apache/iotdb/pull/13453

[to rc/1.3.3] Fix compaction device info cache

---

integration-test/src/test/java/org/apache/iotdb/pipe/it/single/IoTDBPipeOPCUAIT.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/protocol/opcua/OpcUaConnector.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/protocol/opcua/OpcUaNameSpace.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/protocol/opcua/OpcUaServerBuilder.java

[To rc/1.3.3] Pipe: Added conflict detection of params for reusing of OPCUA server

---

iotdb-client/client-py/SessionExample.py
iotdb-client/client-py/iotdb/Session.py
iotdb-client/client-py/iotdb/tsfile/utils/DateUtils.py
iotdb-client/client-py/iotdb/utils/Field.py
iotdb-client/client-py/iotdb/utils/IoTDBConstants.py
iotdb-client/client-py/iotdb/utils/IoTDBRpcDataSet.py
iotdb-client/client-py/iotdb/utils/NumpyTablet.py
iotdb-client/client-py/iotdb/utils/RowRecord.py
iotdb-client/client-py/iotdb/utils/SessionDataSet.py
iotdb-client/client-py/iotdb/utils/Tablet.py
iotdb-client/client-py/tests/integration/test_new_data_types.py

This PR is adding the support of DATE, TIMESTAMP, STRING, BLOB for python client.

[Py-Client] support new data types

---

iotdb-client/client-py/SessionExample.py
iotdb-client/client-py/iotdb/Session.py
iotdb-client/client-py/iotdb/tsfile/utils/DateUtils.py
iotdb-client/client-py/iotdb/utils/Field.py
iotdb-client/client-py/iotdb/utils/IoTDBConstants.py
iotdb-client/client-py/iotdb/utils/IoTDBRpcDataSet.py
iotdb-client/client-py/iotdb/utils/NumpyTablet.py
iotdb-client/client-py/iotdb/utils/RowRecord.py
iotdb-client/client-py/iotdb/utils/SessionDataSet.py
iotdb-client/client-py/iotdb/utils/Tablet.py
iotdb-client/client-py/tests/integration/test_new_data_types.py

cherry-pick 721757503349a991466231d0b8886e6c92c1a33a

[To rc/1.3.3][Py-Client] support new data types

---

iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/iot/logdispatcher/LogDispatcher.java

To avoid unnecessary waiting when close function is called more than one time

Use CountDownLatch to replace Semaphore in IoTConsensus log dispatcher closing

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/plan/node/write/InsertRowsNode.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/DataRegion.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/memtable/AlignedWritableMemChunk.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/memtable/TsFileProcessor.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/memtable/TsFileProcessorTest.java

[To rc/1.3.3] Fix memory calculate error when insertRecords with both aligned and non-aligned devices

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/event/common/tsfile/PipeTsFileInsertionEvent.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/extractor/dataregion/realtime/assigner/PipeDataRegionAssigner.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/extractor/dataregion/realtime/assigner/PipeTimePartitionProgressIndexKeeper.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/tsfile/TsFileResource.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/pipe/extractor/PipeRealtimeExtractTest.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/TsFileResourceProgressIndexTest.java

cherry-pick #13483 to https://github.com/apache/iotdb/tree/rc/1.3.3

[To rc/1.3.3] Pipe: rebind progress index to prematurely flushed tsfile insertion event to avoid data loss when syncing data between clusters

---

integration-test/src/main/java/org/apache/iotdb/it/env/MultiEnvFactory.java
integration-test/src/main/java/org/apache/iotdb/it/env/cluster/ClusterConstant.java
integration-test/src/main/java/org/apache/iotdb/it/env/cluster/EnvUtils.java
integration-test/src/main/java/org/apache/iotdb/it/env/cluster/env/AbstractEnv.java
integration-test/src/main/java/org/apache/iotdb/it/env/cluster/env/MultiClusterEnv.java
integration-test/src/main/java/org/apache/iotdb/it/env/cluster/node/AbstractNodeWrapper.java
integration-test/src/main/java/org/apache/iotdb/it/env/cluster/node/ConfigNodeWrapper.java
integration-test/src/main/java/org/apache/iotdb/it/env/cluster/node/DataNodeWrapper.java
integration-test/src/test/java/org/apache/iotdb/it/framework/IoTDBTestRunner.java
integration-test/src/test/java/org/apache/iotdb/pipe/it/single/IoTDBPipeOPCUAIT.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/extractor/dataregion/historical/PipeHistoricalDataRegionTsFileExtractor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/tools/schema/SchemaRegionSnapshotParser.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/utils/DateTimeUtils.java

This PR has done the following things:
1. Refactored pipe and IT codes.
2. Changed the IT's log_dir from class_method to class(separator)method, and fixed the bug that multiClusterIT's method is not set.
3. Fixed the bug that IoTDBPipeOPCUAIT is not run.
<hr>
This PR has:
<hr>

Pipe & IT : Refactor pipe / IT and improved IT behaviour

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/metric/PipeDataRegionEventCounter.java

fixup #13250, @Caideyipi found that for the following concurrency sequence enqueue -> dequeue -> decrease -> increase, the decrease event counter would fail...

Pipe: fix event counter decrement operations to avoid inconsistent final counts

---

integration-test/src/test/java/org/apache/iotdb/relational/it/query/old/query/IoTDBArithmeticTableIT.java
iotdb-core/datanode/src/main/codegen/templates/ArithmeticColumnTransformerApi.ftl
iotdb-core/datanode/src/main/codegen/templates/ArithmeticUnaryColumnTransformer.ftl

This PR fixe bug in using Negation for Timestamp Type
<hr>
This PR has:
<hr>

Fix the bug in using negation for timestamp type

---

iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/consensus/request/ConfigPhysicalPlan.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/consensus/request/ConfigPhysicalPlanType.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/consensus/request/read/pipe/task/ShowPipePlanV2.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/consensus/request/read/table/ShowTablePlan.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/consensus/response/pipe/task/PipeTableResp.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/consensus/response/table/ShowTableResp.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/ConfigManager.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/pipe/coordinator/task/PipeTaskCoordinator.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/schema/ClusterSchemaManager.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/persistence/executor/ConfigPlanExecutor.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/persistence/schema/ClusterSchemaInfo.java
iotdb-core/confignode/src/test/java/org/apache/iotdb/confignode/consensus/request/ConfigPhysicalPlanSerDeTest.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/table/DataNodeTableCache.java

As the title said. The premise PR for table cache safety guarantee.
<hr>
This PR has:
<hr>

Use consensus read in show table

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/SchemaEngine.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/service/DataNode.java

**### What changes were proposed in this pull request?**
In the previous implementation, only invalid data in the consensus directory was deleted when restarting, resulting in region data that does not belong to the datanode still existing in the data directory.
This PR will completely clean up invalid regions when restarting.

Fix the issue of restarting DataNode to clean up InvalidDataRegion

---

iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/load/cache/LoadCache.java

Fix AINode status error after ConfigNode Leader restarts

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/event/common/tablet/PipeRawTabletInsertionEvent.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/event/common/tsfile/PipeTsFileInsertionEvent.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/extractor/dataregion/realtime/assigner/PipeDataRegionAssigner.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/extractor/dataregion/realtime/assigner/PipeTimePartitionProgressIndexKeeper.java

Pipe: eliminate progress index for raw tablet event to avoid endless rebind

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/extractor/dataregion/historical/PipeHistoricalDataRegionTsFileExtractor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/extractor/dataregion/realtime/assigner/PipeDataRegionAssigner.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/extractor/dataregion/realtime/assigner/PipeTimePartitionProgressIndexKeeper.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/processor/aggregate/AggregateProcessor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/processor/twostage/plugin/TwoStageCountProcessor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/plan/node/write/InsertMultiTabletsNode.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/plan/node/write/InsertNode.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/plan/node/write/InsertRowsNode.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/plan/node/write/InsertRowsOfOneDeviceNode.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/tsfile/TsFileResource.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/TsFileResourceProgressIndexTest.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/consensus/index/ProgressIndex.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/consensus/index/impl/HybridProgressIndex.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/consensus/index/impl/IoTProgressIndex.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/consensus/index/impl/MetaProgressIndex.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/consensus/index/impl/MinimumProgressIndex.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/consensus/index/impl/RecoverProgressIndex.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/consensus/index/impl/SimpleProgressIndex.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/consensus/index/impl/StateProgressIndex.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/consensus/index/impl/TimeWindowStateProgressIndex.java
iotdb-core/node-commons/src/test/java/org/apache/iotdb/commons/pipe/task/meta/PipeMetaDeSerTest.java

In Java, immutable objects have clear requirements:
1. The state of the object cannot be modified after creation.
2. All member variables of the object are final.
3. The object is correctly created (during the creation of the object, the `this` reference does not escape).
This class is designed to be immutable, meaning that instances of ProgressIndex can be treated as value objects. Immutability ensures thread safety, as no external synchronization is required for concurrent access to instances of this class. It also simplifies reasoning about the state of the object as it cannot change once created.
However, if a ProgressIndex instance holds any mutable objects, like a Map, they must be deeply copied during construction or when exposed through accessors to maintain the immutability …

Pipe: make progress index immutable

---

iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/utils/FileUtils.java

(cherry picked from commit 0ea84cadb15f64273151c71994a9c1b2c44ffa13)

[To rc/1.3.3] Don't print warn log for sort tmp file delete

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/receiver/visitor/PipeStatementDataTypeConvertExecutionVisitor.java

Pipe: Avoid type conversion if error on receiver is caused by insufficient memory

---

integration-test/src/test/java/org/apache/iotdb/subscription/it/dual/IoTDBSubscriptionTimePrecisionIT.java
integration-test/src/test/java/org/apache/iotdb/subscription/it/dual/IoTDBSubscriptionTopicIT.java
integration-test/src/test/java/org/apache/iotdb/subscription/it/local/IoTDBSubscriptionBasicIT.java
integration-test/src/test/java/org/apache/iotdb/subscription/it/local/IoTDBSubscriptionDataTypeIT.java
integration-test/src/test/java/org/apache/iotdb/subscription/it/local/IoTDBSubscriptionIdempotentIT.java
integration-test/src/test/java/org/apache/iotdb/subscription/it/local/IoTDBSubscriptionTopicIT.java
integration-test/src/test/java/org/apache/iotdb/subscription/it/triple/regression/param/IoTDBTestParamSubscriptionSessionIT.java

See the logic in `org.apache.iotdb.it.env.cluster.env.AbstractEnv#getTestClassName`, although some pipe tests can also obtain the test class name without being declared, such as `org.apache.iotdb.pipe.it.manual.IoTDBPipeInclusionIT#testPureSchemaInclusion`, which may be caused by the multi-inheritance hierarchy of the subscription IT...

Subscription IT: explicitly declare `setUp` method for test class to avoid `UNKNOWN-IT` test class name

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/utils/fileTimeIndexCache/FileTimeIndexCacheWriter.java

When insert data executed concurrently with migrating region or dropping database, there may be a NPE error log of writing FileTimeIndexCache printed. For these cases, we can skip the writing of FileTimeIndexCache.

Fix potential NPE when write FileTimeIndexCache

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/process/AggregationMergeSortOperator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/OperatorTreeGenerator.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/execution/operator/AggregationMergeSortOperatorTest.java

As the title, when one device locates in multi data regions, the query result may be wrong.
<hr>
This PR has:
<hr>

Fix the error in aggregation merge sort when device locates in multi data regions

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/execution/config/TableConfigTaskVisitor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/execution/config/TreeConfigTaskVisitor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/execution/config/executor/ClusterConfigTaskExecutor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/execution/config/executor/IConfigTaskExecutor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/execution/config/metadata/ShowRegionTask.java

Fixed database names in "show regions" in table model

---

pom.xml

cp from https://github.com/apache/iotdb/pull/13629

[To rc/1.3.3] [RatisConsensus] Bump ratis version to 3.1.1

---

integration-test/src/test/java/org/apache/iotdb/db/it/IoTDBDatetimeFormatIT.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/parser/ASTVisitor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/utils/fileTimeIndexCache/FileTimeIndexCacheWriter.java
iotdb-core/node-commons/src/assembly/resources/conf/iotdb-system.properties.template

cp 24d1191a8e7c7e05cf92c5261a6a8f44ed67d45a & 3c1eace43f0403cffa3916986638db8baa751034

[To rc/1.3.3]Change the error infomation when insert a timestamp over Long.MaxValue && Fix potential NPE when write FileTimeIndexCache

---

iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/iot/logdispatcher/LogDispatcher.java

Cherry-picking PR #13517 into CP/13517

[to rc/1.3.3] Use CountDownLatch to replace Semaphore in IoTConsensus log dispatcher closing (CP 13517)

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/relational/aggregation/Accumulator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/relational/aggregation/AccumulatorFactory.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/relational/aggregation/AggregationOperator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/relational/aggregation/Aggregator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/relational/aggregation/AvgAccumulator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/relational/aggregation/CountAccumulator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/TableOperatorGenerator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/metadata/TableBuiltinAggregationFunction.java

1. Now only support count, avg aggregation function;
2. ITs are not added now, we will do this work after all aggregation operators are developed.

Support global-aggregation in TableModel

---

iotdb-client/cli/src/main/java/org/apache/iotdb/tool/tsfile/ExportTsFile.java

The ExportTsFile tool expects the columns in the result set to be ordered by Device.
However, it is not guaranteed when a wildcard is not used in the SELECT clause (e.g., SELECT s_3, s_9 FROM root.db.**).
In this PR, the assumption of column order is removed, and the construction of Tablets will be based on the actual order of the result set.

Fix unexpected column order in ExportTsFile when wildcard is not used

---

integration-test/src/test/java/org/apache/iotdb/session/it/IoTDBSessionSimpleIT.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/DataRegion.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/performer/impl/FastCompactionPerformer.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/utils/MultiTsFileDeviceIterator.java

1. Fix the issue that expired data can be written to wrong time partition by InsertRowsNode
2. Fix the issue that expired data is not cleaned up by FastCompactionPerformer.

[to rc/1.3.3] Fix ttl bugs

---

iotdb-client/session/src/main/java/org/apache/iotdb/session/SessionConnection.java

While using `use XXX` in Session.executeNonQueryStatement, we should also update the database field in SessionConnection, because while retrying, we will reconnect to any node and then redo request which will use the local database field in SessionConnection.
So, we may see the following error msg in client if retrying phase happens.

Change database in SessionConnection while using db

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/TypeProvider.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/plan/node/PlanNodeType.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/function/BoundSignature.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/function/FunctionKind.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/metadata/ColumnSchema.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/metadata/FunctionNullability.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/metadata/ResolvedFunction.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/planner/node/AggregationNode.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/planner/node/AggregationTableScanNode.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/utils/TypeUtil.java

Attention: 
Serialize and deserialize method of Type  has changed because of the case of `RowType`. You can see details in `org.apache.iotdb.db.queryengine.plan.relational.utils.TypeUtil`

Add serialize and deserialize method for Agg-related Node

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/thrift/impl/DataNodeInternalRPCServiceImpl.java

Use parallel stream to execute config node related schema tasks on multi regions of one node

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/receiver/visitor/PipeStatementDataTypeConvertExecutionVisitor.java

cherry-pick #13569 to https://github.com/apache/iotdb/tree/rc/1.3.3

[To rc/1.3.3] Pipe: Avoid type conversion if error on receiver is caused by insufficient memory (#13569)

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/transformation/dag/column/unary/scalar/DateBinFunctionColumnTransformer.java

This pull request includes changes to the `DateBinFunctionColumnTransformer` class to improve its design and functionality. The most important change is the modification of several static fields to instance fields, which enhances the flexibility and thread-safety of the class.
Design and functionality improvements:
* [`iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/transformation/dag/column/unary/scalar/DateBinFunctionColumnTransformer.java`](diffhunk://#diff-6305624a6309fe575824478b8010ec68c38ebb22f777661699ef252c89f378b0L37-R40): Changed `monthDuration`, `nonMonthDuration`, `origin`, and `zoneId` from static fields to instance fields.

Fix Remove static from variables in DateBin function.

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/agent/task/stage/PipeTaskProcessorStage.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/agent/task/subtask/processor/PipeProcessorSubtask.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/pipe/agent/task/PipeProcessorSubtaskExecutorTest.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/agent/task/progress/PipeEventCommitManager.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/event/EnrichedEvent.java

cherry-pick #13673 to https://github.com/apache/iotdb/tree/rc/1.3.3

[To rc/1.3.3] Pipe: omit region id when marking collect invocation count for remaining time calculation (#13673)

---

integration-test/src/test/java/org/apache/iotdb/relational/it/query/old/builtinfunction/scalar/IoTDBCastFunctionTableIT.java
integration-test/src/test/java/org/apache/iotdb/relational/it/query/old/builtinfunction/scalar/IoTDBCastFunctionTableSpecialIT.java
integration-test/src/test/java/org/apache/iotdb/relational/it/query/old/query/IoTDBArithmeticTableIT.java
iotdb-client/service-rpc/src/main/java/org/apache/iotdb/rpc/TSStatusCode.java
iotdb-core/datanode/src/main/codegen/templates/ArithmeticBinaryColumnTransformer.ftl
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/transformation/dag/column/unary/scalar/CastFunctionColumnTransformer.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/utils/DateTimeUtils.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/utils/ErrorHandlingUtils.java

This pull request introduces several changes to enhance arithmetic operations in the IoTDB project, particularly focusing on handling date arithmetic and overflow scenarios. The key updates include adding a new status code for date out-of-range errors, updating test cases to cover these scenarios, and refining the error handling logic.
* [`iotdb-client/service-rpc/src/main/java/org/apache/iotdb/rpc/TSStatusCode.java`](diffhunk://#diff-02b6f3f950aa3c87eed0b5ec88c3f8724e2b5fbc2c92d897512986f620ec5bd7R139): Added a new status code `DATE_OUT_OF_RANGE` to handle date-related errors.
* [`integration-test/src/test/java/org/apache/iotdb/relational/it/query/old/query/IoTDBArithmeticTableIT.java`](diffhunk://#diff-908fd9921b253d5bad61a0f1e2389379172b0031b3c541be95a08fe2645848f7R72-R75): Added new …

Modify the exception thrown when the date conversion year overflows

---

.github/workflows/multi-language-client.yml
iotdb-client/client-py/iotdb/utils/IoTDBRpcDataSet.py
iotdb-client/client-py/tests/integration/test_new_data_types.py

To reproduce:
1. execute the following sql
```sql
create database root.ln
CREATE ALIGNED TIMESERIES root.ln.g1.d1(BOOLEAN BOOLEAN encoding=PLAIN compressor=SNAPPY, INT32 INT32 encoding=PLAIN compressor=SNAPPY, INT64 INT64 encoding=PLAIN compressor=SNAPPY, FLOAT FLOAT encoding=PLAIN compressor=SNAPPY, DOUBLE DOUBLE encoding=PLAIN compressor=SNAPPY, TEXT TEXT encoding=PLAIN compressor=SNAPPY, TS TIMESTAMP encoding=PLAIN compressor=SNAPPY, DATE DATE encoding=PLAIN compressor=SNAPPY, BLOB BLOB encoding=PLAIN compressor=SNAPPY, STRING STRING encoding=PLAIN compressor=SNAPPY)
insert into root.ln.g1.d1(timestamp, BOOLEAN, INT32, INT64, FLOAT, DOUBLE, TEXT, TS, DATE, BLOB, STRING) aligned values(1, true, 1, 1, 1.0, 1.0, '1', 1, '1971-01-01', X'', '1')
insert into root.ln.g1.d1(timestamp, STRING) …
```

[Py-client] Fix dataset contains null value contract error 

---

integration-test/src/test/java/org/apache/iotdb/ainode/it/AINodeBasicIT.java

Optimization for AINode IT: The model registration of AINode is an asynchronous operation. Sometimes, due to the delay in model registration, the model status is not updated in time, which can cause IT errors. This PR adds retry logic in IT. If it is found that the model status has not been updated, it will continue to retry, avoiding unnecessary IT errors.

AINode: add retry logic in model status check in AINode IT

---

integration-test/src/test/java/org/apache/iotdb/relational/it/db/it/IoTDBMultiIDsWithAttributesTableIT.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/aggregation/timerangeiterator/TableSingleTimeWindowIterator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/relational/TableAggregationTableScanOperator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/relational/aggregation/AvgAccumulator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/TableOperatorGenerator.java

For global aggregation, such as `select count(s1), sum(s1) from table0`, if there is no date in table0, the output result will be `0, null`; 
But for group by with aggregation, such as `select count(s1), sum(s1) from table0 group by id1, id2`, if there is no date in table0, the output result will be empty. 
Besides, this pr also fix the case when only group by date_bin.
<hr>
This PR has:
<hr>

Fix aggregation dealing logic in no data situation

---

integration-test/src/test/java/org/apache/iotdb/relational/it/db/it/IoTDBMultiIDsWithAttributesTableIT.java

As the title.
<hr>
This PR has:
<hr>

Add order by to make the rightness of group by integration test 

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/subscription/broker/SubscriptionPrefetchingQueue.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/subscription/broker/SubscriptionPrefetchingTabletQueue.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/subscription/broker/SubscriptionPrefetchingTsFileQueue.java

cherry-pick #13787 to https://github.com/apache/iotdb/tree/rc/1.3.3

[To rc/1.3.3] Subscription: improve event consistency by operating within the `compute` method (#13787)

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/consensus/statemachine/dataregion/DataExecutionVisitor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/mqtt/PayloadFormatManager.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/DataRegion.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/memtable/TsFileProcessor.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/memtable/TsFileProcessorTest.java
pom.xml

In this PR, we can update write metrics for tablet and tablets in batch.
Benchmark configuration
```
########### Test Mode ###########
BENCHMARK_WORK_MODE=testWithDefaultPath
IoTDB_DIALECT_MODE=TABLE
########### Database Connection Information ###########
DOUBLE_WRITE=false
DBConfig=
DB_SWITCH=IoTDB-200-SESSION_BY_TABLET
HOST=[127.0.0.1]
########### Data Mode ###########
GROUP_NUMBER=1
IoTDB_TABLE_NUMBER=1
DEVICE_NUMBER=10000
REAL_INSERT_RATE=1.0
SENSOR_NUMBER=10
IS_SENSOR_TS_ALIGNMENT=true
IS_OUT_OF_ORDER=true
OUT_OF_ORDER_RATIO=0.5
########### Data Amount ###########
OPERATION_PROPORTION=1:0:0:0:0:0:0:0:0:0:0:0
CLIENT_NUMBER=10
LOOP=10000
BATCH_SIZE_PER_WRITE=1
DEVICE_NUM_PER_WRITE=1000
START_TIME=2024-01-01T00:00:00+08:00
POINT_STEP=1000
OP_MIN_INTERVAL=0
OP_MIN_INTERVAL_RANDOM=false …
```

Optimize write metric update for insertTablets and insertRelationalTablet

---

integration-test/src/test/java/org/apache/iotdb/relational/it/db/it/IoTDBMultiIDsWithAttributesTableIT.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/relational/TableAggregationTableScanOperator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/relational/aggregation/AccumulatorFactory.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/relational/aggregation/FirstAccumulator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/relational/aggregation/LastAccumulator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/relational/aggregation/MaxAccumulator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/relational/aggregation/MinAccumulator.java
iotdb-protocol/thrift-commons/src/main/thrift/common.thrift

as the title
<hr>
This PR has:
<hr>

Add max,min and first aggregation support for table model

---

integration-test/src/test/java/org/apache/iotdb/db/it/query/IoTDBCaseWhenThenIT.java
integration-test/src/test/java/org/apache/iotdb/relational/it/query/old/builtinfunction/scalar/IoTDBCastFunctionTableIT.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/transformation/dag/column/AbstractCaseWhenThenColumnTransformer.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/transformation/dag/column/leaf/TimeColumnTransformer.java

This pull request introduces a new test case and improves the logic for handling `CASE WHEN` transformations. The most important changes include adding a new test to verify multiple `WHEN` clause satisfaction and enhancing the transformation logic to handle uninitialized branches.
* [`integration-test/src/test/java/org/apache/iotdb/db/it/query/IoTDBCaseWhenThenIT.java`](diffhunk://#diff-17d68169af2e9f080b744801580ee66a28ac479b71c49a745460b932f0af5464R890-R909): Added a new test method `testMultipleSatisfyCase` to verify the behavior when multiple `WHEN` clauses are satisfied.
* [`iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/transformation/dag/column/AbstractCaseWhenThenColumnTransformer.java`](diffhunk://#diff-1cea02ca1c6972693f34174ef72701635fa40779c9ec54c328924d5ca4e …

Fix exception when casewhen function meets two conditions

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/load/active/ActiveLoadTsFileLoader.java

Active Load: Fix load tsfile failed when system is read only and not have the error message.

---

integration-test/src/test/java/org/apache/iotdb/relational/it/db/it/IoTDBMultiIDsWithAttributesTableIT.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/relational/aggregation/AccumulatorFactory.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/relational/aggregation/ExtremeAccumulator.java

As the title.
<hr>
This PR has:
<hr>

Add extreme aggregation for table model

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/relational/aggregation/FirstByAccumulator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/relational/aggregation/LastByAccumulator.java

As the title.
<hr>
This PR has:
<hr>

Fix calculation problem in first_by aggregation of table model

---

integration-test/src/test/java/org/apache/iotdb/db/it/query/IoTDBCaseWhenThenIT.java
integration-test/src/test/java/org/apache/iotdb/relational/it/db/it/IoTDBCaseWhenThenTableIT.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/transformation/dag/column/binary/LogicAndColumnTransformer.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/transformation/dag/column/binary/LogicOrColumnTransformer.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/transformation/dag/column/multi/LogicalAndMultiColumnTransformer.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/transformation/dag/column/multi/LogicalOrMultiColumnTransformer.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/transformation/dag/column/multi/MappableUDFColumnTransformer.java

This pull request includes several changes to the `evaluateWithSelection` and `doTransform` methods across multiple transformer classes in the `iotdb-core` module. The changes primarily focus on improving the consistency and correctness of how the position count is obtained from columns.
* [`iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/transformation/dag/column/binary/LogicAndColumnTransformer.java`](diffhunk://#diff-c54acc8c312ac148943810046c419a58e13d57402c8e4dd40dd2d53595a8d01aL39-R40): Moved the assignment of `leftColumn` to ensure it is consistently placed after obtaining the position count.
* [`iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/transformation/dag/column/binary/LogicOrColumnTransformer.java`](diffhunk://#diff-f8664105db52e335df7b400 …

Fix column length may be 0 when using cache fetch

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/schedule/CompactionTaskQueue.java

Fix the issue that tasks with negative estimated memory are executed
https://github.com/apache/iotdb/pull/13856

[to rc/1.3.3] Fix the issue that tasks with negative estimated memory are executed

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/execution/QueryExecution.java

The actual time unit is ms but not ns.
<hr>
This PR has:
<hr>

Fix timeout unit error in QueryExecution

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/StorageEngine.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/memtable/TsFileProcessor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/wal/WALManager.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/wal/allocation/ElasticStrategy.java

When DataRegion uses simple consensus, if users create database, insert some data and drop database in a loop, the number of wal nodes will increase continually until out of memory.

Fix wal node memory leak when using simple consensus

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/agent/task/subtask/connector/PipeConnectorSubtaskManager.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/agent/task/subtask/processor/PipeProcessorSubtask.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/event/common/heartbeat/PipeHeartbeatEvent.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/event/common/tablet/PipeInsertNodeTabletInsertionEvent.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/event/common/tablet/PipeRawTabletInsertionEvent.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/event/common/tsfile/PipeTsFileInsertionEvent.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/extractor/dataregion/IoTDBDataRegionExtractor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/metric/PipeDataNodeRemainingEventAndTimeMetrics.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/metric/PipeDataNodeRemainingEventAndTimeOperator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/subscription/task/subtask/SubscriptionConnectorSubtaskManager.java

…or when the events are too many (#13854)
<hr>
This PR has:
<hr>

[To rc/1.3.3] Pipe: Reduce Calculations for PipeDataNodeRemainingEventAndTimeOperator when the events are too many (#13854)

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/extractor/dataregion/historical/PipeHistoricalDataRegionTsFileAndDeletionExtractor.java

Pipe: Remove already deleted tsfile resource from historical extraction list to prevent FileNotFoundException

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/extractor/dataregion/historical/PipeHistoricalDataRegionTsFileExtractor.java

(cherry picked from commit ce53f9c160e49cebf747151bd6e7b65c53185953)

[To rc/1.3.3] Pipe: Remove already deleted tsfile resource from historical extraction list to prevent FileNotFoundException (#13869)

---

integration-test/src/test/java/org/apache/iotdb/relational/it/db/it/IoTDBMultiIDsWithAttributesTableIT.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/relational/TableAggregationTableScanOperator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/relational/aggregation/AvgAccumulator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/relational/aggregation/FirstAccumulator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/relational/aggregation/FirstByAccumulator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/relational/aggregation/LastAccumulator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/relational/aggregation/LastByAccumulator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/relational/aggregation/TableMaxMinByBaseAccumulator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/relational/aggregation/Utils.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/TableOperatorGenerator.java

1. Use ByteUtils but not DataOutputStream to improve the efficiency of serialize.
2. Support TEXT/BLOB/STRING/BOOLEAN data type for max,min,max_by,min_by.
3. max_by and min_by aggregation can not use statistics.
<hr>
This PR has:
<hr>

Optimize the serialize method of intermedia result of aggregation

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/metadata/Metadata.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/metadata/TableBuiltinAggregationFunction.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/metadata/TableMetadataImpl.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/planner/optimizations/PushAggregationIntoTableScan.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/plan/relational/analyzer/AggregationTest.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/plan/relational/analyzer/TSBSMetadata.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/plan/relational/analyzer/TestMatadata.java

We think all functions can be pre-agg in AggTableScan.

Remove use of canUseStatistics when judge aggregation push-down level in TableModel

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/event/common/tablet/PipeInsertNodeTabletInsertionEvent.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/event/common/tablet/PipeRawTabletInsertionEvent.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/metric/PipeDataNodeRemainingEventAndTimeMetrics.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/metric/PipeDataNodeRemainingEventAndTimeOperator.java

Pipe: fix calculations of PipeDataNodeRemainingEventAndTimeOperator

---

integration-test/src/test/java/org/apache/iotdb/relational/it/db/it/IoTDBInsertTableIT.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/plan/node/write/InsertTabletNode.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/DataRegion.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/plan/planner/node/write/WritePlanNodeSplitTest.java

As title.
When calculate TTL, RelationalInsertTabletNode should make sure the times are sorted.

Keep the order of times after spliting RelationalInsertTabletNode

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/memtable/AbstractMemTable.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/memtable/IMemTable.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/memtable/TsFileProcessor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/wal/recover/file/TsFilePlanRedoer.java

```
----------------------Main Configurations----------------------
########### Test Mode ###########
BENCHMARK_WORK_MODE=testWithDefaultPath
IoTDB_DIALECT_MODE=TABLE
########### Database Connection Information ###########
DOUBLE_WRITE=false
DBConfig=
DB_SWITCH=IoTDB-200-SESSION_BY_TABLET
HOST=[192.168.130.12]
########### Data Mode ###########
GROUP_NUMBER=1
IoTDB_TABLE_NUMBER=1
DEVICE_NUMBER=10000
REAL_INSERT_RATE=1.0
SENSOR_NUMBER=10
IS_SENSOR_TS_ALIGNMENT=true
IS_OUT_OF_ORDER=true
OUT_OF_ORDER_RATIO=0.5
########### Data Amount ###########
OPERATION_PROPORTION=1:0:0:0:0:0:0:0:0:0:0:0
SCHEMA_CLIENT_NUMBER=10
DATA_CLIENT_NUMBER=10
LOOP=50000
BATCH_SIZE_PER_WRITE=1
DEVICE_NUM_PER_WRITE=1000
START_TIME=2024-01-01T00:00:00+08:00
POINT_STEP=1000
OP_MIN_INTERVAL=0
OP_MIN_INTERVAL_RANDOM=false …
```

Batch update inserted point number metric

---

integration-test/src/test/java/org/apache/iotdb/relational/it/db/it/IoTDBMultiIDsWithAttributesTableIT.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/relational/TableAggregationTableScanOperator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/execution/memory/TableModelStatementMemorySourceVisitor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/OperatorTreeGenerator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/plan/node/PlanGraphPrinter.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/analyzer/Analysis.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/planner/distribute/TableDistributedPlanGenerator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/planner/optimizations/PushAggregationIntoTableScan.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/planner/optimizations/PushPredicateIntoTableScan.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/planner/optimizations/TransformAggregationToStreamable.java

As the title.
Before this pr, `select count(*), count(num), sum(num) from table0 where device='d_not_exist'` or `select count(*), count(num), sum(num) from table0 where time>now()` will return empty. In this pr, the sql will return `0,0,null`
<hr>
This PR has:
<hr>

Perfect the aggregation queries when there is no devices or no data partitions.

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/load/LoadTsFileManager.java

This reverts commit dbb99bc88dea50c6effffae4081abbba1ea5f76a.

Revert "Load: Parallelly load files into different target data partitions (#13893)"

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/utils/executor/batch/utils/BatchCompactionPlan.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/selector/estimator/AbstractCompactionEstimator.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/compaction/inner/BatchedAlignedSeriesFastInnerCompactionTest.java

Fix compaction cached time chunk flip twice

Fix compaction cached time chunk flip twice

---

iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/utils/StatusUtils.java

When the region is inactive, the status code returned by write is `WRITE_PROCESS_REJECT`. To enable retries in this situation, the mpp retry policy should also retry on this status code.

[region migration] Retry WRITE_PROCESS_REJECT status code

---

integration-test/src/test/java/org/apache/iotdb/pipe/it/manual/IoTDBPipePermissionIT.java
iotdb-api/pipe-api/src/main/java/org/apache/iotdb/pipe/api/customizer/parameter/PipeParameters.java
iotdb-client/cli/src/main/java/org/apache/iotdb/tool/tsfile/ImportTsFile.java
iotdb-client/cli/src/main/java/org/apache/iotdb/tool/tsfile/ImportTsFileRemotely.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/pipe/connector/client/IoTDBConfigNodeSyncClientManager.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/pipe/connector/protocol/IoTDBConfigRegionAirGapConnector.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/pipe/connector/protocol/IoTDBConfigRegionConnector.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/client/IoTDBDataNodeAsyncClientManager.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/client/IoTDBDataNodeSyncClientManager.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/protocol/airgap/IoTDBDataNodeAirGapConnector.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/protocol/legacy/IoTDBLegacyPipeConnector.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/protocol/opcua/OpcUaConnector.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/protocol/thrift/async/IoTDBDataRegionAsyncConnector.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/protocol/thrift/sync/IoTDBDataNodeSyncConnector.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/receiver/protocol/airgap/IoTDBAirGapReceiver.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/receiver/protocol/thrift/IoTDBDataNodeReceiver.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/config/constant/PipeConnectorConstant.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/connector/client/IoTDBClientManager.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/connector/client/IoTDBSyncClientManager.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/connector/payload/thrift/common/PipeTransferHandshakeConstant.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/connector/protocol/IoTDBConnector.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/connector/protocol/IoTDBSslSyncConnector.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/receiver/IoTDBFileReceiver.java

[To rc/1.3.3] Pipe: Support specifing receiver's username and password when syncing data between clusters

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/plan/node/write/InsertTabletNode.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/plan/node/write/RelationalInsertTabletNode.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/wal/buffer/WALInfoEntry.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/wal/io/WALFileTest.java

No need to split relationalInsertTabletNode when serialize to WAL

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/task/AbstractCompactionTask.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/task/InsertionCrossSpaceCompactionTask.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/compaction/cross/InsertionCrossSpaceCompactionTest.java

https://github.com/apache/iotdb/pull/13900

[to rc/1.3.3] Reduce deserialized file num in compaction validation

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/receiver/protocol/pipeconsensus/PipeConsensusReceiver.java

just addMetricSet after requestExecutor's initialization

Fix IoTV2 metric NPE due to concurrency

---

iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/resource/ref/PipePhantomReferenceManager.java

Pipe: reduce pipe phantom reference logging frequency by omitting printing if count unchanged

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/AbstractSeriesAggregationScanOperator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/AlignedSeriesAggregationScanOperator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/SeriesAggregationScanOperator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/relational/TableAggregationTableScanOperator.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/execution/operator/OperatorMemoryTest.java

For nonAligned series, its page size will contain both time and value column, so TSFileDescriptor.getInstance().getConfig().getPageSizeInByte() is enough.

Correct the memory estimation for SeriesAggregationScanOperator

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/AbstractSeriesAggregationScanOperator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/AlignedSeriesAggregationScanOperator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/SeriesAggregationScanOperator.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/execution/operator/OperatorMemoryTest.java

cp from https://github.com/apache/iotdb/pull/13979

[To rc/1.3.3] Correct the memory estimation for SeriesAggregationScanOperator

---

integration-test/src/test/java/org/apache/iotdb/ainode/it/AINodeBasicIT.java
iotdb-core/ainode/iotdb/ainode/model/built_in_model_factory.py

AINode: Fix built-model inference error

---

iotdb-client/session/src/main/java/org/apache/iotdb/session/Session.java

When an insert request doesn't need to split to small requests, it is better to execute it synchronously.

Optimize cache leader implementation

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/service/DataNode.java

When the remove script passes multiple DataNode IDs, some of them may be invalid. Before removing, invalid IDs should be filtered out in advance and explained in the log.

[remove datanode] Identify and display invalid nodes before removing

---

iotdb-client/service-rpc/src/main/java/org/apache/iotdb/rpc/IoTDBRpcDataSet.java

Print Dataset is closed error msg if user continues to fetch from it.
Previously, the error msg is:
Currently, the error msg is:

Print Dataset is closed error msg if user continues to fetch from it

---

iotdb-client/session/src/main/java/org/apache/iotdb/session/util/SessionUtils.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/event/common/tablet/parser/TabletInsertionEventParser.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/utils/executor/batch/utils/BatchCompactionPlan.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/compaction/CompactionValidationTest.java
pom.xml

Pipe: Fix the problem that SessionUtils calculates Tablet without handling null pointers and update tsfile version

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/client/ConfigNodeInfo.java

The remove-datanode script only supports removing DataNodes in an environment where DataNode has been successfully started. If the remove script fails in an environment with only ConfigNode, a clear error message must be given.

[remove datanode] Enhance remove message on environment with only ConfigNode

---

iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/load/cache/LoadCache.java

When Datanodes are currently removed, the deletion of some maps of cn loadmanager and the callback of asynchronous rpc may have some concurrency conflicts. In this case, some robustness needs to be improved

Fix ConfignNode LoadManager NPE when removing datanodes

---

iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/pipe/consensuspipe/ConsensusPipeManager.java

Currently create consensusPipe on coordinator will failed, because the pre-check detect a consensusPipe from coordinator pointing to coordinator, as this image shows:
Fix this bugs caused by minor mistake...

[Region Migration] Fix Create ConsensusPipe On Coordinator Failed

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/event/realtime/PipeRealtimeEvent.java

(cherry picked from commit caac607464359cb194b07bd1fa6c985bb745826e)

[To dev/1.3] Pipe: GC device2Measurements in PipeRealtimeEvent in time to avoid OOM when insertion is in high load (#14018)

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/driver/Driver.java
library-udf/src/main/java/org/apache/iotdb/library/dprofile/UDAFMedian.java

Due to a race condition in Driver#tryWithLock there was a chance an operator might have end up not being properly closed upon completion.(here is the UDF throw NoSuchElementException)
- Driver#process executes an operator under the Driver#exclusiveLock
- An operator throws an exception and triggers a task failure
- A FIStateMachine listener closes all drivers calling Driver#close
- Driver#close is not able to acquire the Driver#exclusiveLock and assumes the driver will be terminated by the lock owner
- The lock owner throws an exception and never runs `destroyIfNecessary` in Driver#tryWithLock that was expected to close the operators
- Query resource clear async thread stuck to wait for driver to close

Fix query resource clear async thread stuck bug

---

iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/pipe/consensuspipe/ConsensusPipeManager.java

Due to the introduction of a fix for region migration, NPE occurs when a non-region migration creates a pipe.

IoTConsensusV2: Fix Create DataRegion Failed.

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/extractor/dataregion/historical/PipeHistoricalDataRegionTsFileAndDeletionExtractor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/resource/wal/hardlink/PipeWALHardlinkResourceManager.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/utils/FileUtils.java

Pipe: avoid supply event with failed tsfile resource pin & apply double-checked locking for exists-and-mkdirs operation

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/resource/tsfile/PipeTsFileResourceSegmentLock.java

Pipe: atomically publish segment lock to avoid uninitialized volatile variable

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/extractor/dataregion/historical/PipeHistoricalDataRegionTsFileExtractor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/resource/wal/hardlink/PipeWALHardlinkResourceManager.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/utils/FileUtils.java

cherry-pick #13998 to https://github.com/apache/iotdb/tree/dev/1.3

[To dev/1.3] Pipe: avoid supply event with failed tsfile resource pin & apply double-checked locking for exists-and-mkdirs operation (#13998)

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/resource/tsfile/PipeTsFileResourceSegmentLock.java

cherry-pick #14064 to https://github.com/apache/iotdb/tree/dev/1.3

[To dev/1.3] Pipe: atomically publish segment lock to avoid uninitialized volatile variable (#14064)

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/fragment/FragmentInstanceContext.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/fragment/QueryStatistics.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/FileLoaderUtils.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/metric/SeriesScanCostMetricSet.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/statistics/FragmentInstanceStatisticsDrawer.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/buffer/BloomFilterCache.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/buffer/ChunkCache.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/buffer/TimeSeriesMetadataCache.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/read/control/FileReaderManager.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/read/reader/chunk/DiskAlignedChunkLoader.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/read/reader/chunk/DiskChunkLoader.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/buffer/ChunkCacheTest.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/compaction/TestUtilsForAlignedSeries.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/exception/IoTDBIORuntimeException.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/service/metric/enums/Metric.java
iotdb-protocol/thrift-datanode/src/main/thrift/datanode.thrift
pom.xml

1. Add cache hit situation and actual io size for BloomFilter, TimeSeriesMetadata(including ChunkMetadatList) and Chunk
2. print them in explain analyze verbose, like 
```
- BloomFilter 相关（用于判断某个序列在tsfile中是否存在，存储于tsfile尾部）
- loadBloomFilterFromCacheCount: 命中BloomFilterCache的次数
- loadBloomFilterFromDiskCount: 从磁盘中读取BloomFilter的次数
- loadBloomFilterActualIOSize: 从磁盘中读取BloomFilter时耗费的磁盘IO（单位为bytes）
- loadBloomFilterTime: 读取BloomFilter + 计算序列是否存在的总耗时（单位为ms）
- TimeSeriesMetadata相关
- loadTimeSeriesMetadataFromCacheCount: 命中TimeSeriesMetadataCache的次数，注意这里对于对齐设备来讲，每个分量（包括time列，都会去单独请求Cache，所以对于对齐设备来讲，（loadTimeSeriesMetadataFromCacheCount + loadTimeSeriesMetadataFromDiskCount）= tsfile number * subSensor number(包括time列）
- loadTimeSeriesMetadataFromDiskCount: …
```

Add cache hit situation and actual io size for BloomFilter, TimeSeriesMetadata(including ChunkMetadatList) and Chunk

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/fragment/FragmentInstanceContext.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/fragment/QueryStatistics.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/FileLoaderUtils.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/metric/SeriesScanCostMetricSet.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/statistics/FragmentInstanceStatisticsDrawer.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/buffer/BloomFilterCache.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/buffer/ChunkCache.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/buffer/TimeSeriesMetadataCache.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/read/control/FileReaderManager.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/read/reader/chunk/DiskAlignedChunkLoader.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/read/reader/chunk/DiskChunkLoader.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/buffer/ChunkCacheTest.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/compaction/TestUtilsForAlignedSeries.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/exception/IoTDBIORuntimeException.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/service/metric/enums/Metric.java
iotdb-protocol/thrift-datanode/src/main/thrift/datanode.thrift
pom.xml

(cherry picked from commit d6377702c9074283789ede1317e0c46f5ed60a10)

[To dev/1.3] Add cache hit situation and actual io size for BloomFilter, TimeSeriesMetadata(including ChunkMetadatList) and Chunk

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/relational/aggregation/grouped/StreamingAggregationOperator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/relational/aggregation/grouped/StreamingHashAggregationOperator.java

Corner case: method `next()` of child of StreamAggOperator always return null until its process finished.
Fix: return null when this case. 
Verify on test enviorment：

Fix corner case of StreamAggOperator

---

iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/iot/IoTConsensus.java
iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/iot/IoTConsensusServerImpl.java

In previous solutions, IoTConsensus actually only ensured the data consistency of coordinator node. For scenarios where region members change, we need to ensure the data consistency of all nodes. To achieve this, we need to move `notifyPeersToBuildSyncLogChannel` forward.
Master data consistency test result:
This PR:

[region migration] Fix IoTConsensus data consistency during region member changes

---

iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/iot/IoTConsensus.java
iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/iot/IoTConsensusServerImpl.java

cp from https://github.com/apache/iotdb/pull/14084

[To dev/1.3][region migration] Fix IoTConsensus data consistency during region member changes

---

integration-test/src/test/java/org/apache/iotdb/db/it/utils/TestUtils.java
integration-test/src/test/java/org/apache/iotdb/relational/it/schema/IoTDBTableIT.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/schema/ClusterSchemaManager.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/persistence/schema/ClusterSchemaInfo.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/schema/table/AddTableColumnProcedure.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/schema/table/CreateTableProcedure.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/schema/table/DeleteDevicesProcedure.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/schema/table/RenameTableColumnProcedure.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/schema/table/SetTablePropertiesProcedure.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/exception/metadata/DatabaseModelException.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/execution/config/executor/ClusterConfigTaskExecutor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/analyzer/predicate/PredicatePushIntoMetadataChecker.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/analyzer/predicate/schema/CheckSchemaPredicateVisitor.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/plan/relational/analyzer/AnalyzerTest.java

Support all push-able expressions in push down to metaData & Optimized database-related error logs

---

integration-test/src/test/java/org/apache/iotdb/relational/it/query/recent/IoTDBTableAggregationIT.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/relational/aggregation/TableMaxMinByBaseAccumulator.java

Cause: the offset is not correct, it should be determined by length of `yValue`

Fix intermediate output of MaxMinByAccumulator in TableModel

---

integration-test/src/test/java/org/apache/iotdb/relational/it/query/old/query/IoTDBInTableIT.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/relational/ColumnTransformerBuilder.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/analyzer/predicate/ConvertPredicateToFilterVisitor.java

In this pr, we support `select time,device1,device2,timestamp_v from sg where timestamp_v in (1509465600000)` by implicitly converting long-type values to timestamp type.

Support using long to compare timestamp type in  expression

---

integration-test/src/test/java/org/apache/iotdb/relational/it/query/recent/IoTDBTableAggregationIT.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/sql/parser/AstBuilder.java

Fix: Remove the argument check when process syntax sugar.

Fix error message when there is no argument in first, last, first_by and last_by

---

integration-test/src/test/java/org/apache/iotdb/relational/it/query/recent/IoTDBTableAggregationIT.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/relational/aggregation/grouped/GroupedFirstByAccumulator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/relational/aggregation/grouped/GroupedLastByAccumulator.java

Bug: The query will be error if first argument is `BOOLEAN` type in first_by and last_by function with group by.
Fix: Add `break` in switch case.

Fix first_by and last_by with group by in TableModel

---

integration-test/src/test/java/org/apache/iotdb/db/it/IoTDBDeletionIT.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/utils/datastructure/AlignedTVList.java

The row deletion mark is mistakenly used to judge the deletion of a value column, which is fixed in this PR.

Fix that the row deletion mark is mistakenly use

---

integration-test/src/test/java/org/apache/iotdb/relational/it/db/it/IoTDBMultiIDsWithAttributesTableIT.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/planner/distribute/TableDistributedPlanGenerator.java

Fix: Keep same logic with `push-down`

Fix NPE of empty data aggregation query when there is no push-down optimize in TableModel

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/Coordinator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/execution/memory/TableModelStatementMemorySourceVisitor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/TableOperatorGenerator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/planner/TableLogicalPlanner.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/planner/TableModelPlanner.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/planner/distribute/TableDistributedPlanner.java

Optimizers are designed to be stateless, so we can share them among different queries. All stateful fields should be saved in Context instead of optimizer itself.

Change LogicalOptimizer and DistributionOptimizer to singleton

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/extractor/dataregion/historical/PipeHistoricalDataRegionTsFileExtractor.java

cherry-pick #14132 to https://github.com/apache/iotdb/tree/dev/1.3

[To dev/1.3] PipeConsensus: always execute flush for historical data extraction of consensus pipe to reduce data sync delay (#14132)

---

iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/ProcedureManager.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/env/RemoveDataNodeHandler.java
iotdb-core/confignode/src/test/java/org/apache/iotdb/confignode/manager/ProcedureManagerTest.java

1. When there are other unknown or readonly DataNodes in the consensus group that are not the removed node, for security reasons, the current remove peer operation will wait for the unknown node to come online. To optimize this situation, we can check before and refuse to remove.
2. In the future, the two-stage operations of add and remove in region migration can be provided to users as separate instructions. Therefore, for the remove operation, we can consider adding the unsafe instruction to force deletion to avoid stuck situations.

[remove datanode] Refuse to remove when there are any other unknown or readonly DataNodes in the consensus group

---

iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/config/RatisConfig.java
iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/ratis/utils/Utils.java

This is due to we do not configure `RaftServerConfigKeys.Write.setByteLimit`, `RaftServerConfigKeys.Log.setQueueByteLimit` and it's default size is 64MB

Fixed bug where Ratis could not write large requests and could not be configured

---

iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/node/RemoveDataNodesProcedure.java

[remove datanode] Procedure no longer acquires node lock

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/protocol/pipeconsensus/handler/PipeConsensusTabletBatchEventHandler.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/protocol/thrift/async/handler/PipeTransferTabletBatchEventHandler.java

Pipe: Reduce the amount of log information printed after a batch fails

---

iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/env/RegionMaintainHandler.java

get out of the loop when encounter InterruptedException

Fix stopping cn leader stuck when region region migration

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/analyzer/Analysis.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/planner/distribute/TableDistributedPlanGenerator.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/plan/relational/analyzer/AggregationTest.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/plan/relational/analyzer/TestMatadata.java

When find more than one region in one device and AggStep is `SINGLE` when process `AggTableScan`, we need to split it and set sort property.

Fix aggregation query of TableModel when there are numerous regions in one device

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/agent/task/subtask/connector/PipeConnectorSubtaskLifeCycle.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/agent/task/subtask/processor/PipeProcessorSubtask.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/subscription/task/subtask/SubscriptionConnectorSubtask.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/subscription/task/subtask/SubscriptionConnectorSubtaskLifeCycle.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/agent/task/execution/PipeSubtaskExecutor.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/agent/task/subtask/PipeAbstractConnectorSubtask.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/agent/task/subtask/PipeSubtask.java

cherry-pick #14186 to https://github.com/apache/iotdb/tree/dev/1.3

[To dev/1.3] Subscription: revert ScheduledExecutorService to ExecutorService to avoid task queue oom & fix subscription task count (#14186)

---

integration-test/src/test/java/org/apache/iotdb/relational/it/db/it/IoTDBMultiIDsWithAttributesTableIT.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/planner/node/JoinNode.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/planner/optimizations/PushPredicateIntoTableScan.java

In current version, cross join is not supported. 
Sql like below is actual cross join because EquiJoinClauses num is only two.
```
select *
from students s, teachers t, courses c, grades g
where s.time=c.time and c.time=g.time
```
<hr>
This PR has:
<hr>

Fix multi table joins error and add more integration tests

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/relational/aggregation/FirstAccumulator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/relational/aggregation/FirstByAccumulator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/relational/aggregation/FirstByDescAccumulator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/relational/aggregation/FirstDescAccumulator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/relational/aggregation/LastAccumulator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/relational/aggregation/LastByAccumulator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/relational/aggregation/LastByDescAccumulator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/relational/aggregation/LastDescAccumulator.java

For first, first_by, last and last_by aggregations, actually we can only read the first value/statistics and then terminate the process.
There is no need to read all values.
<hr>
This PR has:
<hr>

Optimize first, last, first_by, last_by aggregation process in table model

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/plan/node/write/InsertTabletNode.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/plan/node/write/RelationalInsertTabletNode.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/planner/RelationPlanner.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/sql/ast/InsertTablet.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/statement/crud/InsertTabletStatement.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/DataRegion.java

This PR is optimizing the insertRelationalTablet performance.
1. We don't need to checkTTL for each rows of the RelationalTabletNode.
2. If we can know a RelationalTablet only contains one device, we can optimize the implementation of getIDevices method in RelationalTabletNode.
########### Data Mode ###########
GROUP_NUMBER=1
IoTDB_TABLE_NUMBER=1
DEVICE_NUMBER=4000
REAL_INSERT_RATE=1.0
SENSOR_NUMBER=50
IS_SENSOR_TS_ALIGNMENT=true
IS_OUT_OF_ORDER=false
OUT_OF_ORDER_RATIO=0.5
########### Data Amount ###########
OPERATION_PROPORTION=1:0:0:0:0:0:0:0:0:0:0:0
SCHEMA_CLIENT_NUMBER=20
DATA_CLIENT_NUMBER=20
LOOP=100
BATCH_SIZE_PER_WRITE=1000
DEVICE_NUM_PER_WRITE=1
START_TIME=2022-01-01T00:00:00+08:00
POINT_STEP=1000
OP_MIN_INTERVAL=0
OP_MIN_INTERVAL_RANDOM=false …

Optimize insertRelationalTablet performance

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/DataRegion.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/utils/CompactionUtils.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/modification/DeletionPredicate.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/modification/IDPredicate.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/modification/ModEntry.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/modification/ModificationFile.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/modification/PartitionLevelModFileManager.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/modification/TableDeletionEntry.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/modification/TreeDeletionEntry.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/tsfile/TsFileResource.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/utils/io/BufferSerializable.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/utils/io/StreamSerializable.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/compaction/inner/InnerSpaceCompactionSelectorTest.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/modification/ModificationFileTest.java

Mod-file-related FileMetrics are managed within the Modification to ease the management and reduce potential bugs.

Refactor mod-file-related FileMetric

---

iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/iot/client/IoTConsensusClientPool.java
iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/ratis/RatisConsensus.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/client/DataNodeClientPoolFactory.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/client/ClientManager.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/client/ClientPoolFactory.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/client/IClientPoolFactory.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/client/factory/AsyncThriftClientFactory.java
iotdb-core/node-commons/src/test/java/org/apache/iotdb/commons/client/ClientManagerTest.java

When the pipe task is frequently created and deleted in the current scenario, the clientManager is frequently created and closed without the Selector being released, resulting in thread leakage

Fix AsyncClientManager selector thread leak

---

iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/connector/client/IoTDBSyncClientManager.java

will print the warning message in sendHandshakeReq when handshake failed 
now the message looks like this:

Pipe: make exception message more friendly when creating data sync pipe failed

---

integration-test/src/test/java/org/apache/iotdb/confignode/it/partition/IoTDBPartitionCreationIT.java
integration-test/src/test/java/org/apache/iotdb/confignode/it/partition/IoTDBPartitionDurableIT.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/client/async/handlers/heartbeat/DataNodeHeartbeatHandler.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/load/cache/AbstractLoadCache.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/load/cache/LoadCache.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/load/cache/region/RegionGroupCache.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/env/RemoveDataNodeHandler.java

When removing datanode, datanode status will be updated to Removing and then the region will inherit the datanode status in the heartbeat thread. Not allowing the region to inherit the Removing status can better observe the status of region migration.

[remove datanode] Do not allow regions to inherit the Removing state from datanode

---

integration-test/src/test/java/org/apache/iotdb/relational/it/query/old/IoTDBFilterTableIT.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/function/arithmetic/AdditionResolver.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/function/arithmetic/DivisionResolver.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/function/arithmetic/ModulusResolver.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/function/arithmetic/MultiplicationResolver.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/function/arithmetic/SubtractionResolver.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/metadata/TableMetadataImpl.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/transformation/dag/column/leaf/NullColumnTransformer.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/transformation/dag/column/unary/scalar/AbstractCastFunctionColumnTransformer.java

This pull request primarily focuses on enhancing the handling of `null` values in the query engine and transformation logic, and includes several new test cases to validate these changes. The most important changes include new methods for detecting `null` values in comparisons and calculations, additional imports, and modifications to the transformation logic to handle `null` values correctly.
Enhancements for handling `null` values:
* [`iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/metadata/TableMetadataImpl.java`](diffhunk://#diff-5420ab45f1bfb25708b0cd843b2770256e0671bc180acb7abf7f8a89888a3aa0R815-R823): Added methods `isCompareWithNull` and `isCalculateWithNull` to handle `null` values in comparisons and calculations. …

Fix throw exception when compare with null

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/OperatorContext.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/relational/TableAggregationTableScanOperator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/relational/TableScanOperator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/plan/node/PlanGraphPrinter.java

1. fix potential concurrent exception in Explain Analyze caused by using HashMap in OperatorContext
2. Add `DeviceNumber` and `CurrentDeviceIndex` for `TableScanOperator` and `TableAggregationTableScanOperator`
3. Change `DeviceEntriesSize` to `DeviceNumber` for `TableScanOperator` and `TableAggregationTableScanOperator` in explain statement

Add extra info for TableScanOperator and AggTableScanOperator in Explain Analyze

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/receiver/protocol/pipeconsensus/PipeConsensusReceiver.java

If some reqs find the buffer no longer contains their requestMeta after jumping out from condition.await, it may indicate that during their wait, some reqs with newer pipeTaskStartTimes or rebootTimes came in and refreshed the requestBuffer. In that cases we need to discard these requests.

IoTConsensusV2: Fix reqBuffer reset and receive concurrent bug

---

iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/connector/client/IoTDBSyncClientManager.java

cherry-pick https://github.com/apache/iotdb/pull/14208 to https://github.com/apache/iotdb/tree/dev/1.3

[To dev/1.3] Pipe: make exception message more friendly when creating data sync pipe failed (#14208)

---

iotdb-client/session/src/main/java/org/apache/iotdb/session/subscription/payload/SubscriptionSessionDataSet.java

The usage of bitmap in SubscriptionSessionDataSet may cause npe
master branch: https://github.com/apache/iotdb/pull/14124

[to dev/1.3] Subscription: The usage of bitmap in SubscriptionSessionDataSet may cause npe

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/receiver/protocol/thrift/IoTDBDataNodeReceiver.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/receiver/visitor/PipeStatementDataTypeConvertExecutionVisitor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/receiver/visitor/PipeStatementTSStatusVisitor.java

…for data conversion statements on data sync receiver side (#14220)
<hr>
This PR has:
<hr>

[To dev/1.3] Pipe: Allow STATEMENT_STATUS_VISITOR and STATEMENT_EXCEPTION_VISITOR for data conversion statements on data sync receiver side (#14220)

---

integration-test/src/test/java/org/apache/iotdb/db/it/alignbydevice/IoTDBOrderByLimitOffsetAlignByDeviceIT.java
integration-test/src/test/java/org/apache/iotdb/db/it/utils/TestUtils.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/LogicalPlanBuilder.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/plan/optimization/LimitOffsetPushDownTest.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/plan/optimization/OptimizationTestUtil.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/plan/optimization/TestPlanBuilder.java

Before fix:
After fix:
<hr>
This PR has:
<hr>

Fix error in single device with `sort + offset + limit` align by device query

---

iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/ProcedureExecutor.java

do not need recover finished procedure to `procedures`
see hbase

Enhance procedure recover policy

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/exception/CompactionStatisticsCheckFailedException.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/task/RepairUnsortedFileCompactionTask.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/repair/RepairDataFileScanUtil.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/repair/RepairTimePartitionScanTask.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/compaction/repair/RepairDataFileScanUtilTest.java
pom.xml

https://github.com/apache/iotdb/pull/14167

[to dev/1.3] Enhance repair data file scan util 

---

integration-test/src/test/java/org/apache/iotdb/db/it/selectinto/IoTDBSelectIntoIT.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/AnalyzeVisitor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/SelectIntoUtils.java

cp from https://github.com/apache/iotdb/pull/14269

[To dev/1.3] Fix back-quote remove of Select-Into query when query is not for raw data

---

iotdb-client/session/src/main/java/org/apache/iotdb/session/Session.java
iotdb-client/session/src/main/java/org/apache/iotdb/session/util/SessionUtils.java

Subsequent pr of #13989 
When a Table model tablet contains only single device, we don't need to create a new Tablet and setValue for it.

Optimize table cache leader implement 2

---

iotdb-client/client-py/iotdb/Session.py
iotdb-client/client-py/tests/integration/test_session.py

[Py-client] Support insert_records with None values

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/extractor/dataregion/IoTDBDataRegionExtractor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/metric/PipeDataNodeRemainingEventAndTimeMetrics.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/agent/task/progress/PipeEventCommitManager.java

Downgrade the stale PipeEventCommitter log from WARN to DEBUG and add a register method of IoTDBDataRegionExtractor to PipeDataNodeRemainingEventAndTimeMetrics.

Pipe: fix the issues of excessive stale PipeEventCommitter logs and missing PipeDataNodeRemainingEventAndTimeMetrics 

---

iotdb-core/datanode/src/test/java/org/apache/iotdb/db/utils/ConfigurationFileUtilsTest.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/conf/ConfigurationFileUtils.java

Some configuration items may be commented out when merging old version configuration files.

Some configuration items may be commented out when merging old version configuration files

---

iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/pipe/PipeConsensusServerImpl.java

Considering cluster may have unknown nodes when migrate regions, all action related to migration should not panic exceptons. Instead, we just need to log a warn log

Region Migration: Fix migration failed when there are unknown nodes

---

iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/ProcedureExecutor.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/node/AbstractNodeProcedure.java

Procedure: Fix procedure framework data race

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/extractor/dataregion/IoTDBDataRegionExtractor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/metric/PipeDataNodeRemainingEventAndTimeMetrics.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/agent/task/progress/PipeEventCommitManager.java

cherry-pick #14284 to https://github.com/apache/iotdb/tree/dev/1.3

[To dev/1.3] Pipe: fix the issues of excessive stale PipeEventCommitter logs and missing PipeDataNodeRemainingEventAndTimeMetrics (#14284)

---

iotdb-core/node-commons/src/assembly/resources/conf/iotdb-system.properties.template
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/client/property/ClientPoolProperty.java

This error is reported under too many concurrent loads, so we increase the value appropriately to improve robustness

Increase the default upper bound for ClientManager

---

integration-test/src/test/java/org/apache/iotdb/session/it/IoTDBSessionRelationalIT.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/thrift/impl/ClientRPCServiceImpl.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/AnalyzeUtils.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/execution/config/TableConfigTaskVisitor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/analyzer/StatementAnalyzer.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/sql/ast/WrappedInsertStatement.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/sql/parser/AstBuilder.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/sql/parser/SqlParser.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/statement/crud/InsertRowStatement.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/plan/relational/analyzer/AnalyzerTest.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/plan/relational/analyzer/TestUtils.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/plan/relational/planner/PlanTester.java

When not specifying the column names, the number of inputing columns must be exactly the same as those already defined in the database. Also, they must have the same order, otherwise, the insertion will fail.

Support table model sql insertion without column name

---

integration-test/src/test/java/org/apache/iotdb/pipe/it/tablemodel/IoTDBPipeAlterIT.java
integration-test/src/test/java/org/apache/iotdb/pipe/it/tablemodel/IoTDBPipeAutoDropIT.java
integration-test/src/test/java/org/apache/iotdb/pipe/it/tablemodel/IoTDBPipeClusterIT.java
integration-test/src/test/java/org/apache/iotdb/pipe/it/tablemodel/IoTDBPipeConnectorCompressionIT.java
integration-test/src/test/java/org/apache/iotdb/pipe/it/tablemodel/IoTDBPipeConnectorParallelIT.java
integration-test/src/test/java/org/apache/iotdb/pipe/it/tablemodel/IoTDBPipeDataSinkIT.java
integration-test/src/test/java/org/apache/iotdb/pipe/it/tablemodel/IoTDBPipeExtractorIT.java
integration-test/src/test/java/org/apache/iotdb/pipe/it/tablemodel/IoTDBPipeLifeCycleIT.java
integration-test/src/test/java/org/apache/iotdb/pipe/it/tablemodel/IoTDBPipeNullValueIT.java
integration-test/src/test/java/org/apache/iotdb/pipe/it/tablemodel/IoTDBPipeProtocolIT.java
integration-test/src/test/java/org/apache/iotdb/pipe/it/tablemodel/IoTDBTablePatternFormatIT.java

Pipe IT: Add a Flush operation to the receiving end after each query failure for Pipe Table Model IT

---

iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/pipe/PipeConsensus.java
iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/pipe/PipeConsensusServerImpl.java
iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/pipe/consensuspipe/ConsensusPipeManager.java
iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/pipe/service/PipeConsensusRPCServiceProcessor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/extractor/dataregion/historical/PipeHistoricalDataRegionTsFileAndDeletionExtractor.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/config/constant/PipeExtractorConstant.java
iotdb-protocol/thrift-consensus/src/main/thrift/pipeconsensus.thrift

as title.
We do not need other peers to follow the progress of the coordinator. Other peers can directly extract the data file from the beginning and automatically filter out the part written by the user and transmit it.

IoTV2: Fix addRemotePeer data inconsistency

---

iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/iot/IoTConsensus.java

When removing fails and rollback occurs, both ConfigNode and DataNode may modify the configuration file simultaneously.

[remove datanode] Fix concurrent modification when removing fails and rollback

---

iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/ProcedureManager.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/ProcedureExecutor.java

Currently, there is a bug in the way we use the procedure framework to track task statuses. The current process primarily involves three steps:
* Submit the task to the procedure.
* Retain the procedure ID.
* Use the procedure ID to retrieve the status of the procedure.
The second and third steps in the above process have issues due to the asynchronous nature of procedure completion and cleanup. There are two relevant characteristics here:
* When a procedure is completed, it transitions from the procedures map to the completed map.
A background thread periodically cleans up the completed map.
* As a result, for a procedure that has already been completed, there is a chance that it will be neither in the procedures map nor in the completed map. In this case, the procedure’s status can no …

Restruct procedure waiting strategy to fix NPE bug when completed procedures were cleaned before getting result

---

integration-test/src/test/java/org/apache/iotdb/ainode/it/AINodeBasicIT.java
integration-test/src/test/java/org/apache/iotdb/db/it/udf/IoTDBUDFBlockQueryIT.java
integration-test/src/test/java/org/apache/iotdb/pipe/it/autocreate/IoTDBPipeLifeCycleIT.java
integration-test/src/test/java/org/apache/iotdb/relational/it/db/it/udf/IoTDBSQLFunctionManagementIT.java
integration-test/src/test/java/org/apache/iotdb/relational/it/db/it/udf/scalar/IoTDBScalarFunctionIT.java
iotdb-core/antlr/src/main/antlr4/org/apache/iotdb/db/qp/sql/IoTDBSqlParser.g4
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/execution/config/TableConfigTaskVisitor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/execution/config/TreeConfigTaskVisitor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/execution/config/executor/ClusterConfigTaskExecutor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/parser/ASTVisitor.java
iotdb-core/node-commons/src/assembly/resources/conf/iotdb-system.properties.template
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/conf/CommonConfig.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/executable/ExecutableManager.java

Previously, if one user has USE_UDF privilege, he can create any function from any uri address which may load some unsafe jar file into IoTDB process.
So we add a trusted_uri_pattern parameter in config file which is a Java-style regex, only uri match that pattern can be used to create udf, trigger or pipePlugin. And that parameter defaultly is `file:.*` which only allows for files in local file system

Supprt trusted_uri_pattern in config file

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/metric/PipeDataNodeRemainingEventAndTimeOperator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/service/metrics/file/TsFileMetrics.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/DataRegion.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/DataRegionMetrics.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/memtable/TsFileProcessorInfoMetrics.java
iotdb-core/metrics/core/src/main/java/org/apache/iotdb/metrics/core/IoTDBMetricManager.java
iotdb-core/metrics/interface/src/main/java/org/apache/iotdb/metrics/AbstractMetricManager.java
iotdb-core/metrics/interface/src/main/java/org/apache/iotdb/metrics/AbstractMetricService.java
iotdb-core/metrics/interface/src/main/java/org/apache/iotdb/metrics/impl/DoNothingMetricManager.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/concurrent/ThreadPoolMetrics.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/concurrent/threadpool/WrappedScheduledExecutorService.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/concurrent/threadpool/WrappedSingleThreadExecutorService.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/concurrent/threadpool/WrappedSingleThreadScheduledExecutor.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/concurrent/threadpool/WrappedThreadPoolExecutor.java

Fix four metric leaks when frequently creating and deleting database
* ThreadPoolMetrics
* Points internalReporter
* file_global_count
* mem in dataregionMetrics

Fix ThreadPoolMetrics concurrent NPE bug & Fix metric leaks when frequently creating and deleting database

---

.github/workflows/multi-language-client.yml
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/memtable/TsFileProcessor.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/DataRegionTest.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/LastFlushTimeMapTest.java

cherry-pick https://github.com/apache/iotdb/pull/14225

[To dev/1.3] Fix flaky LastFlushTimeMapTest & Fix go client CI for dev/1.3

---

integration-test/src/test/java/org/apache/iotdb/relational/it/db/it/IoTDBSetConfigurationTableIT.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/ConfigManager.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/execution/config/executor/ClusterConfigTaskExecutor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/StorageEngine.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/conf/ConfigurationFileUtils.java

1. When the config node can not find the configuration file, the set configuration command does not update other nodes' configuration
```
IoTDB> set configuration "enable_seq_space_compaction"="true"
Msg: org.apache.iotdb.jdbc.IoTDBSQLException: 301: Unable to find the configuration file. Some modifications are made only in memory.
```
2. Ignore undefined configuration items.
```
IoTDB> set configuration "enable_seq_space_compaction1"="true" on 1
Msg: org.apache.iotdb.jdbc.IoTDBSQLException: 301: ignored config items: [enable_seq_space_compaction1] because they are immutable or undefined.
```

When the config node can not find the configuration file, the set configuration command does not update other nodes' configuration

---

iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/client/sync/SyncDataNodeClientPool.java
iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/pipe/PipeConsensus.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/thrift/impl/DataNodeRegionManager.java

1. Use segmented locks distinguished by groupid for peer operations instead of large locks
2. Change the cn retry count to 10

IoTV2: Fix consensus pipe operation time out

---

dependencies.json
iotdb-core/node-commons/pom.xml
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/client/sync/ByteBuddyEnhancer.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/client/sync/SyncThriftClientWithErrorHandler.java
pom.xml

The cglib has stopped evolution, The cglib community suggests byte-buddy instead, so we'll do
https://github.com/cglib/cglib
IMPORTANT NOTE: cglib is unmaintained and does not work well (or possibly at all?) in newer JDKs, particularly JDK17+. If you need to support newer JDKs, we will accept well-tested well-thought-out patches... but you'll probably have better luck migrating to something like [ByteBuddy](https://bytebuddy.net/).
_*[https://github.com/raphw/byte-buddy.gi](https://github.com/raphw/byte-buddy.git*_)

[IOTDB-6353] replace cglib to byte-buddy

---

integration-test/src/test/java/org/apache/iotdb/db/it/IoTDBSetConfigurationIT.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/ConfigManager.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/execution/config/executor/ClusterConfigTaskExecutor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/StorageEngine.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/conf/ConfigurationFileUtils.java

https://github.com/apache/iotdb/pull/14390
1. When the config node can not find the configuration file, the set configuration command does not update other nodes' configuration
```
IoTDB> set configuration "enable_seq_space_compaction"="true"
Msg: org.apache.iotdb.jdbc.IoTDBSQLException: 301: Unable to find the configuration file. Some modifications are made only in memory.
```
2. Ignore undefined configuration items.
```
IoTDB> set configuration "enable_seq_space_compaction1"="true" on 1
Msg: org.apache.iotdb.jdbc.IoTDBSQLException: 301: ignored config items: [enable_seq_space_compaction1] because they are immutable or undefined.
```

[to dev/1.3] When the config node can not find the configuration file, the set configuration command does not update other nodes' configuration

---

iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/ratis/utils/Utils.java

The current default speed limit for Ratis writes is 16MB, which is the same size as the bytebuffer, which is unreasonable. We should make it ten times bigger

Fix ratis byte limit configuration too small

---

iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/client/async/handlers/heartbeat/DataNodeHeartbeatHandler.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/load/cache/LoadCache.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/partition/PartitionManager.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/thrift/impl/DataNodeInternalRPCServiceImpl.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/execution/config/metadata/ShowRegionTask.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/service/metrics/FileMetrics.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/service/metrics/file/TsFileMetrics.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/schema/column/ColumnHeaderConstant.java
iotdb-protocol/thrift-confignode/src/main/thrift/confignode.thrift

Add TsfileSize column to 'show regions'

---

integration-test/src/main/java/org/apache/iotdb/it/env/cluster/config/MppCommonConfig.java
integration-test/src/main/java/org/apache/iotdb/it/env/cluster/config/MppSharedCommonConfig.java
integration-test/src/main/java/org/apache/iotdb/it/env/remote/config/RemoteCommonConfig.java
integration-test/src/main/java/org/apache/iotdb/itbase/env/CommonConfig.java
integration-test/src/test/java/org/apache/iotdb/db/it/IoTDBFileTimeIndexIT.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/SeriesScanUtil.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/read/QueryDataSource.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/tsfile/TsFileResource.java

Assuming that we have the following file distribution, and all the files shown have been degraded to FileTimeIndex:
While we do scanning, we will firstly unpack the frist seq file and the first and second unseq file, then while we merge on read, we will continue to get timestamp 4, then we using startTime of the second seq time which is 5 to judge whether it's overlapped with timestamp 4. 5 is larger than 4, so we think that the second seq tsfile isn't overlapped with timestamp 4, and as it's in seq space, so we mistakenly assumend that none of the subsequent files would overlap with timestamp 4.
The above processing is correct while there doesn't exist degraded resource in seq space, however while exsiting degraded resource in seq space, if current seq tsfile's startTime is larger than …

[IOTDB-6355] Fix query scan will return duplicated timestamp or unordered timestamp while TsFileResource degrading

---

iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/binaryallocator/BinaryAllocator.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/binaryallocator/arena/Arena.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/binaryallocator/metric/BinaryAllocatorMetrics.java

This PR introduces new metrics to track memory eviction statistics in the Binary Allocator component. The allocator implements two distinct eviction strategies:
Sample-based eviction: Periodically samples memory regions to identify eviction candidates
GC-based eviction: Leverages garbage collection cycles to reclaim unused memory
The primary enhancement is the addition of metrics that monitor the cumulative size of evicted memory through both strategies. These metrics provide visibility into the allocator's memory reclamation behavior and efficiency.

Add eviction metrics in binary allocator

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/LocalExecutionPlanner.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/load/memory/LoadTsFileAnalyzeSchemaMemoryBlock.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/load/memory/LoadTsFileDataCacheMemoryBlock.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/load/memory/LoadTsFileMemoryManager.java

Removed askForMemoryCount.getAndUpdate to prevent memory over-release

[To dev/1.3] Load: Fix Memory Allocation and Release Mismatch in LoadTsFileDataCacheMemoryBlock (#14375)

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/thrift/impl/DataNodeInternalRPCServiceImpl.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/execution/config/executor/ClusterConfigTaskExecutor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/schedule/CompactionTaskManager.java

Allow hot reloading compaction from disabled status

Allow hot reloading compaction from disabled status

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/resource/memory/InsertNodeMemoryEstimator.java

[To dev/1.3] Pipe: Fixed the issue where partial writing caused the measurement to be null and caused the memory estimator to throw NPE (#14391)

---

integration-test/src/test/java/org/apache/iotdb/relational/it/query/old/builtinfunction/scalar/IoTDBFormatFunctionTableIT.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/relational/ColumnTransformerBuilder.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/metadata/TableMetadataImpl.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/transformation/dag/column/unary/scalar/FormatColumnTransformer.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/utils/DateTimeUtils.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/udf/builtin/relational/TableBuiltinScalarFunction.java

This pull request introduces a new `FORMAT` function to the IoTDB query engine, along with the necessary infrastructure to support it. The primary changes include the addition of the `FormatColumnTransformer` class, updates to the `TableBuiltinScalarFunction` enum, and modifications to various files to incorporate the new function.
**New Functionality:**
* Added the `FormatColumnTransformer` class to handle the `FORMAT` function in query transformations. (`iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/transformation/dag/column/unary/scalar/FormatColumnTransformer.java`)
**Integration with Query Engine:**
* Updated the `TableBuiltinScalarFunction` enum to include the new `FORMAT` function. (`iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/transformation …

Add format function

---

iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/load/LoadManager.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/load/balancer/RouteBalancer.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/load/balancer/router/priority/GreedyPriorityBalancer.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/load/balancer/router/priority/IPriorityBalancer.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/load/balancer/router/priority/LeaderPriorityBalancer.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/load/cache/LoadCache.java
iotdb-core/confignode/src/test/java/org/apache/iotdb/confignode/manager/load/balancer/router/priority/GreedyPriorityTest.java
iotdb-core/confignode/src/test/java/org/apache/iotdb/confignode/manager/load/balancer/router/priority/LeaderPriorityBalancerTest.java
iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/iot/IoTConsensus.java
iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/iot/service/IoTConsensusRPCServiceProcessor.java

After the introduction of DataNode removing, the region status is no longer bound to the Datanode, and the sorting of loadscore will cause the RegionPriority order to be wrong.

[remove datanode] Remove LoadScore sort to fix RegionPriority order

---

integration-test/src/test/java/org/apache/iotdb/subscription/it/local/IoTDBSubscriptionBasicIT.java
integration-test/src/test/java/org/apache/iotdb/subscription/it/triple/regression/param/IoTDBTestParamPullConsumerIT.java
integration-test/src/test/java/org/apache/iotdb/subscription/it/triple/regression/param/IoTDBTestParamPushConsumerIT.java
integration-test/src/test/java/org/apache/iotdb/subscription/it/triple/regression/param/IoTDBTestParamTopicIT.java
iotdb-client/session/src/main/java/org/apache/iotdb/session/subscription/SubscriptionSession.java
iotdb-client/session/src/main/java/org/apache/iotdb/session/subscription/consumer/SubscriptionConsumer.java
iotdb-client/session/src/main/java/org/apache/iotdb/session/subscription/consumer/SubscriptionPullConsumer.java
iotdb-client/session/src/main/java/org/apache/iotdb/session/subscription/util/IdentifierUtils.java

cherry-pick #14493 to https://github.com/apache/iotdb/tree/dev/1.3

[To dev/1.3] Subscription: fix NPE when building consumer with missing id & add more checker for topic operations using session (#14493)

---

iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/load/LoadManager.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/load/balancer/RouteBalancer.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/load/balancer/router/priority/GreedyPriorityBalancer.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/load/balancer/router/priority/IPriorityBalancer.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/load/balancer/router/priority/LeaderPriorityBalancer.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/load/cache/LoadCache.java
iotdb-core/confignode/src/test/java/org/apache/iotdb/confignode/manager/load/balancer/router/priority/GreedyPriorityTest.java
iotdb-core/confignode/src/test/java/org/apache/iotdb/confignode/manager/load/balancer/router/priority/LeaderPriorityBalancerTest.java
iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/iot/IoTConsensus.java
iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/iot/service/IoTConsensusRPCServiceProcessor.java

cp from https://github.com/apache/iotdb/pull/14527

[To dev/1.3][remove datanode] Remove LoadScore sort to fix RegionPriority order

---

iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/node/NodeManager.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/persistence/pipe/PipeTaskInfo.java
iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/IConsensus.java
iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/iot/IoTConsensus.java
iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/iot/IoTConsensusServerImpl.java
iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/iot/service/IoTConsensusRPCServiceProcessor.java
iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/pipe/PipeConsensus.java
iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/ratis/RatisConsensus.java
iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/simple/SimpleConsensus.java
iotdb-core/consensus/src/test/java/org/apache/iotdb/consensus/iot/ReplicateTest.java
iotdb-core/consensus/src/test/java/org/apache/iotdb/consensus/iot/StabilityTest.java
iotdb-core/consensus/src/test/java/org/apache/iotdb/consensus/ratis/RatisConsensusTest.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/consensus/ConsensusPipeDataNodeDispatcher.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/service/DataNode.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/config/constant/PipeRPCMessageConstant.java
iotdb-protocol/thrift-confignode/src/main/thrift/confignode.thrift

[to dev/1.3][region migration] Make peer list correct when IoTConsensus & IoTConsensusV2 & Ratis starting

---

iotdb-client/cli/src/main/java/org/apache/iotdb/cli/AbstractCli.java
iotdb-client/cli/src/main/java/org/apache/iotdb/cli/Cli.java
iotdb-client/jdbc/src/main/java/org/apache/iotdb/jdbc/IoTDBConnection.java

Add database name for table model CLI

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/performer/impl/FastCompactionPerformer.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/schedule/CompactionTaskManager.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/schedule/CompactionWorker.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/compaction/CompactionWorkerTest.java

Compaction task can not stopped when abort compaction

Compaction task can not stopped when abort compaction

---

iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/load/cache/node/DataNodeHeartbeatCache.java
iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/iot/IoTConsensusServerImpl.java

Add more IoTConsensus Configuration logs to enhance observability.

[IoTConsensus] Refine IoTConsensus Configuration logs

---

iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/client/ThriftClient.java

Fixed the issue of NPE caused by unexpected exceptions thrown during the use of AsyncClient

---

.github/workflows/cluster-it-1c1d.yml
.github/workflows/cluster-it-1c1d1a.yml
.github/workflows/cluster-it-1c3d.yml
.github/workflows/compile-check.yml
.github/workflows/dependency-check.yml
.github/workflows/multi-language-client.yml
.github/workflows/pipe-it-2cluster.yml
.github/workflows/sonar-codecov.yml
.github/workflows/table-cluster-it-1c1d.yml
.github/workflows/table-cluster-it-1c3d.yml
.github/workflows/todos-check.yml
.github/workflows/unit-test.yml

After this PR, if you want to create branches that will trigger GitHub CI, you may create them under the "force_ci/" path.
The typical scenario is a massive development involving many people, and they work on a temporary branch before each of their work can be merged into the master branch. By creating the temporary branch under "force_ci/," one does not need to modify the yml file and revert it.

Add branches name pattern that will trigger CI

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/io/CompactionTsFileReader.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/compaction/inner/InnerSequenceCompactionSpeedTest.java

https://github.com/apache/iotdb/pull/14559

[to dev/1.3] Compaction Read Metric and rate limit are bypassed due to parent class modification

---

iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/service/AbstractThriftServiceThread.java

Learn from other big data stacks

Bind 0.0.0.0 for all Thrift Service to enhance extensibility

---

iotdb-api/udf-api/src/main/java/org/apache/iotdb/udf/api/relational/AggregateFunction.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/relational/TableAggregationTableScanOperator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/relational/aggregation/AggregationOperator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/relational/aggregation/TableAccumulator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/relational/aggregation/TableAggregator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/relational/aggregation/UserDefinedAggregateFunctionAccumulator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/relational/aggregation/grouped/GroupedAccumulator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/relational/aggregation/grouped/GroupedAggregator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/relational/aggregation/grouped/GroupedUserDefinedAggregateAccumulator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/relational/aggregation/grouped/HashAggregationOperator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/relational/aggregation/grouped/StreamingAggregationOperator.java

Close Aggregation and State to release resource

Close Aggregation and State to release resource

---

iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/ratis/RatisConsensus.java

Fix RatisConsensus client==null exception when stopping datanode

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/metadata/fetcher/TableDeviceSchemaFetcher.java

Fixed the timeout of device schema fetch to the timeout of the caller query/write operation

---

integration-test/src/test/java/org/apache/iotdb/relational/it/session/IoTDBSessionRelationalIT.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/utils/CommonUtils.java

If the incoming tablet does not contain all tag columns, missing ones will be added as place holders. 
However, they are mistakenly initialized as String[] instead of Binary[], which may cause serialization error.

Fix that place-holder tag column are not Binary[]

---

iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/ConfigManager.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/IManager.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/load/LoadManager.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/load/cache/LoadCache.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/node/NodeManager.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/service/thrift/ConfigNodeRPCServiceProcessor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/client/ConfigNodeClient.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/Analysis.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/AnalyzeVisitor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/LogicalPlanBuilder.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/planner/optimizations/DataNodeLocationSupplierFactory.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/cluster/NodeStatus.java
iotdb-protocol/thrift-confignode/src/main/thrift/confignode.thrift

In the past, show-queries can execute only on `Running` status node. 
But now, more status of node have  been introduced, show-queries can execute on node which is readable (status is `Running`, `Removing` or `ReadOnly`).
Additionally, this PR implements the switch-case judge method of readable to ensure it will be checked if someone introduces more status of node.

Make show-queries can execute on more status node

---

integration-test/src/test/java/org/apache/iotdb/relational/it/query/recent/IoTDBTableAggregationIT.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/relational/aggregation/AccumulatorFactory.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/relational/aggregation/CountIfAccumulator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/relational/aggregation/grouped/GroupedCountIfAccumulator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/metadata/TableMetadataImpl.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/udf/builtin/relational/TableBuiltinAggregationFunction.java

Add aggregate function count_if for relational table
<hr>
This PR has:
<hr>

Add aggregate function count_if for relational table

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/exception/CompactionSourceFileDeletedException.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/task/InnerSpaceCompactionTask.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/selector/estimator/AbstractCrossSpaceEstimator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/selector/estimator/AbstractInnerSpaceEstimator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/selector/estimator/CompactionEstimateUtils.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/selector/estimator/FastCompactionInnerCompactionEstimator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/selector/estimator/FastCrossSpaceCompactionEstimator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/selector/estimator/MetadataInfo.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/selector/estimator/ReadChunkInnerCompactionEstimator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/selector/impl/RewriteCrossSpaceCompactionSelector.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/compaction/cross/CrossSpaceCompactionSelectorTest.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/compaction/utils/CompactionTaskMemCostEstimatorTest.java

Compaction task memory is incorrect when compaction_max_aligned_series_num_in_one_batch <= 0

Compaction task memory is incorrect when compaction_max_aligned_series_num_in_one_batch <= 0

---

integration-test/src/main/java/org/apache/iotdb/it/utils/TsFileTableGenerator.java
integration-test/src/test/java/org/apache/iotdb/db/it/IoTDBLoadTsFileIT.java
integration-test/src/test/java/org/apache/iotdb/pipe/it/tablemodel/IoTDBPipeWithLoadIT.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/receiver/visitor/PipeTableStatementDataTypeConvertExecutionVisitor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/load/converter/LoadTableStatementDataTypeConvertExecutionVisitor.java

In this PR, I've done two things:
1. add data convert on type mismatch IT for table model
2. Fix the bug where the variable `TSInsertTabletReq.writeToTable` is not set True in `PipeTransferTabletRawReq.toTPipeTransferRawReq` when inserting a Tablet in Table mode. This issue causes `columnCategories` to be null and prevents the data type conversion.

Load: add LoadWithConvertOnTypeMismatchIT on Table Model

---

example/udf/src/main/java/org/apache/iotdb/udf/AggregateFunctionExample.java
example/udf/src/main/java/org/apache/iotdb/udf/ScalarFunctionExample.java
integration-test/src/main/java/org/apache/iotdb/db/query/udf/example/relational/AllSum.java
integration-test/src/main/java/org/apache/iotdb/db/query/udf/example/relational/ContainNull.java
integration-test/src/main/java/org/apache/iotdb/db/query/udf/example/relational/DatePlus.java
integration-test/src/main/java/org/apache/iotdb/db/query/udf/example/relational/FirstTwoSum.java
integration-test/src/main/java/org/apache/iotdb/db/query/udf/example/relational/MyAvg.java
integration-test/src/main/java/org/apache/iotdb/db/query/udf/example/relational/MyCount.java
iotdb-api/udf-api/src/main/java/org/apache/iotdb/udf/api/customizer/parameter/FunctionArguments.java

Rename interface name of `FunctionArguments`

Rename interface name of `FunctionArguments`

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/AnalyzeVisitor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/LoadTsFileAnalyzer.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/scheduler/load/LoadTsFileScheduler.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/statement/crud/LoadTsFileStatement.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/load/converter/LoadTsFileDataTypeConverter.java

(cherry picked from commit 90cdf3bbc94224723ba00b0f92b0007d38a84000)

[To dev/1.3] Load: Consider isGeneratedByPipe mark when executing tsfile-tablet conversion in analysis stage (#14651)

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
iotdb-core/node-commons/src/assembly/resources/conf/iotdb-system.properties.template

- wal_throttle_threshold_in_byte: from 50GB to 200GB
- region_migration_speed_limit_bytes_per_second: from 32MB/s to 48MB/s

Adjust default wal_throttle_threshold_in_byte and region_migration_speed_limit_bytes_per_second

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/DataRegion.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/schedule/CompactionScheduleContext.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/schedule/CompactionScheduler.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/selector/impl/RewriteCrossSpaceCompactionSelector.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/compaction/cross/InsertionCrossSpaceCompactionSelectorTest.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/compaction/cross/InsertionCrossSpaceCompactionTest.java

1. Skip insertion task selection when a time partition contains many files.
2. Force executing other compaction task selection when using IoTConsensusV2
3. Determine whether to skip other compaction task selection based on the granularity of time partition.

Modify the condition to skip compaction schdule after insertion compaction task selection

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/consensus/statemachine/schemaregion/SchemaExecutionVisitor.java

Reduced the error log cause by batch activate template when some devices are already activated

---

integration-test/src/test/java/org/apache/iotdb/relational/it/query/recent/IoTDBTableAggregationIT.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/planner/QueryPlanner.java

cause: now only appendProjections when there is order-by, but maybe there is projection before distinct too.

Fix select-distinct when there is no order by and select items contains expression

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/resource/tsfile/PipeTsFileResourceManager.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/subscription/broker/SubscriptionPrefetchingQueue.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/subscription/event/SubscriptionEvent.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/subscription/event/batch/SubscriptionPipeTabletEventBatch.java

Pipe: report linked tsfile size & Subscription: decrease reference count for other enriched events & add logging to observe possible stuck situations

---

iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/schema/ClusterSchemaManager.java

Ignore the DatabaseNotExistsException for adjustMaxRegionGroupNum when querying dataRegionGroupCount

---

iotdb-api/pipe-api/src/main/java/org/apache/iotdb/pipe/api/customizer/parameter/PipeParameterValidator.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/connector/protocol/IoTDBConnector.java

cherry-pick #14694 to https://github.com/apache/iotdb/tree/dev/1.3

[To dev/1.3] Pipe: strict check for synonym pipe parameters to avoid ambiguity (#14694)

---

integration-test/src/test/java/org/apache/iotdb/db/it/utils/TestUtils.java

Pipe IT: Added flush for assertData on targetEnv to avoid IoTV2 batch mode lead to large delay

---

integration-test/src/test/java/org/apache/iotdb/session/it/IoTDBSessionSimpleIT.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/env/ConfigNodeProcedureEnv.java

When executing DELETE DATABASE right after the restart of a data node, cache inconsistency will occur due to:
1. the node status remains UNKNOWN during the execution of DELETE DATABASE;
2. nodes with status UNKNOWN are skipped when invalidating the cache.
'1.' is fixed by adding more retries when finding a node with UNKNOWN status;
'2.'  is fixed by aborting the DELETE DATABASE procedure if any node is UNKNOWN.

Fix cache invalidation failure and add retry

---

.github/workflows/cluster-it-1c1d.yml
.github/workflows/cluster-it-1c1d1a.yml
.github/workflows/cluster-it-1c3d.yml
.github/workflows/compile-check.yml
.github/workflows/daily-it.yml
.github/workflows/daily-ut.yml
.github/workflows/dependency-check.yml
.github/workflows/pipe-it-2cluster.yml
.github/workflows/sonar-codecov.yml
.github/workflows/table-cluster-it-1c1d.yml
.github/workflows/table-cluster-it-1c3d.yml
.github/workflows/unit-test.yml
.github/workflows/vulnerability-check.yml
.mvn/develocity.xml
.mvn/extensions.xml

This PR migrates the IoTDB project to publish Build Scans to the the new Develocity instance at develocity.apache.org.
Additionally, this PR sets a projectId for use by Develocity.
This PR has:
<hr>

Publish build scans to develocity.apache.org

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/subscription/event/batch/SubscriptionPipeTabletEventBatch.java

Subscription: fix `hasNext` method in tablet batch to support multiple tsfile in the same batch

---

iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/read/reader/chunk/MemAlignedChunkLoaderTest.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/read/reader/chunk/MemChunkLoaderTest.java
pom.xml

To revert a change in TsFile that will make the memory calculation of Binary too expensive.

Bump TsFile version to 2.0.0-250118-SNAPSHOT

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/repair/RepairDataFileScanUtil.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/compaction/repair/RepairDataFileScanUtilTest.java

The time range of device in resource file may be larger than the actual time range in tsfile

The time range of device in resource file may be larger than the actual time range in tsfile

---

iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/InternalProcedure.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/Procedure.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/ProcedureExecutor.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/StateMachineProcedure.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/sync/StartPipeProcedure.java
iotdb-core/confignode/src/test/java/org/apache/iotdb/confignode/procedure/entity/IncProcedure.java
iotdb-core/confignode/src/test/java/org/apache/iotdb/confignode/procedure/entity/NoopProcedure.java
iotdb-core/confignode/src/test/java/org/apache/iotdb/confignode/procedure/entity/SimpleLockProcedure.java
iotdb-core/confignode/src/test/java/org/apache/iotdb/confignode/procedure/entity/SleepProcedure.java
iotdb-core/confignode/src/test/java/org/apache/iotdb/confignode/procedure/entity/StuckProcedure.java

- Delete "suspend" operation
- Delete "abort" operation
- Rename KeepAliveWorker to TemporaryWorker
- Refactor StateMachineProcedure:
- Use LinkedList to replace array
- And some other things

Refactor procedure framework (simplified StateMachineProcedure, and some other things)

---

iotdb-client/service-rpc/src/main/java/org/apache/iotdb/rpc/IoTDBRpcDataSet.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/session/ClientSession.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/session/IClientSession.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/session/InternalClientSession.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/thrift/impl/ClientRPCServiceImpl.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/thrift/impl/DataNodeInternalRPCServiceImpl.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/Coordinator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/execution/QueryExecution.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/scheduler/ClusterScheduler.java
iotdb-protocol/thrift-datanode/src/main/thrift/client.thrift

Fix memory leak:
1. inserting using sql
2. fetching all result but forgetting calling Dataset.close

Fix memory leak while inserting using sql

---

iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/persistence/schema/ClusterSchemaInfo.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/table/DataNodeTableCache.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/schema/table/TsTable.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/schema/table/column/TsTableColumnSchema.java

By test, 1000000 columns - 1000000 columns comparison costs 300ms by average.
<hr>
This PR has:
<hr>

Reduced the log of table cache update

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/transformation/dag/column/unary/scalar/AbstractCastFunctionColumnTransformer.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/transformation/dag/column/unary/scalar/CastFunctionColumnTransformer.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/transformation/dag/column/unary/scalar/TryCastFunctionColumnTransformer.java

Correct the Blob data cast error msg

---

integration-test/src/test/java/org/apache/iotdb/relational/it/query/old/builtinfunction/scalar/IoTDBFormatFunctionTableIT.java

This pull request includes updates to the `IoTDBFormatFunctionTableIT` test class to improve date and time formatting in test cases. The changes primarily involve importing necessary utilities and updating test assertions to use dynamic date and time values.
Key changes include:
* Added imports for `DateTimeUtils`, `LocalDate`, `ZoneId`, and `format` to support new date and time formatting functionality. [[1]](diffhunk://#diff-81d6991cc3a2bfadf2a2b018b43dd2101d495ebed67050183b355ce578d14a55R17) [[2]](diffhunk://#diff-81d6991cc3a2bfadf2a2b018b43dd2101d495ebed67050183b355ce578d14a55L25-R46)
* Removed the `@Ignore` annotation to enable the test class for execution.
* Added a `ZoneId` constant to specify the time zone for formatting.
* Updated the `testTimestampFormat` method to use …

Fix format IT

---

integration-test/src/main/java/org/apache/iotdb/it/env/cluster/config/MppDataNodeConfig.java
integration-test/src/main/java/org/apache/iotdb/it/env/remote/config/RemoteDataNodeConfig.java
integration-test/src/main/java/org/apache/iotdb/itbase/env/DataNodeConfig.java
integration-test/src/test/java/org/apache/iotdb/relational/it/db/it/IoTDBDeletionTableIT.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java
iotdb-core/node-commons/src/assembly/resources/conf/iotdb-system.properties.template
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/path/PartialPath.java

The deviceId is re-generated after PartialPath.concatAsMeasurementPath, which may be incorrect because it is recalculated by the default rule.
The result is that the wrong deviceId cannot be matched by existing mod entries, causing data to re-appear after compaction.
To fix it, the result of PartialPath.concatAsMeasurementPath will inherit the deviceId from the parameter.

Fix wrong deviceId after PartialPath.concatAsMeasurementPath

---

integration-test/src/main/java/org/apache/iotdb/it/env/cluster/config/MppCommonConfig.java
integration-test/src/main/java/org/apache/iotdb/it/env/cluster/config/MppSharedCommonConfig.java
integration-test/src/main/java/org/apache/iotdb/it/env/remote/config/RemoteCommonConfig.java
integration-test/src/main/java/org/apache/iotdb/itbase/env/CommonConfig.java
integration-test/src/test/java/org/apache/iotdb/confignode/it/partition/IoTDBPartitionTableAutoCleanTest.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/consensus/request/ConfigPhysicalPlan.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/consensus/request/ConfigPhysicalPlanType.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/consensus/request/write/partition/AutoCleanPartitionTablePlan.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/consensus/statemachine/ConfigRegionStateMachine.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/ProcedureManager.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/TTLManager.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/partition/PartitionManager.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/persistence/TTLInfo.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/persistence/executor/ConfigPlanExecutor.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/persistence/partition/DatabasePartitionTable.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/persistence/partition/PartitionInfo.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/PartitionTableAutoCleaner.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/ProcedureExecutor.java
iotdb-core/confignode/src/test/java/org/apache/iotdb/confignode/consensus/request/ConfigPhysicalPlanSerDeTest.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/schedule/TTLScheduleTask.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/concurrent/ThreadName.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/conf/CommonConfig.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/conf/CommonDescriptor.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/partition/DataPartitionTable.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/partition/SeriesPartitionTable.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/schema/ttl/TTLCache.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/utils/TimePartitionUtils.java

A data partition is not necessary to exist when all corresponding data are expired given the pre-configurated TTL. Hence, this PR added a thread to automatically clean these expired data partitions, making the cache size of the DataPartitionTable is always acceptable! Specifically, the main updates include:
1. In TTLManager, to retrieve the maximum TTL of a specific database, we implement getDatabaseMaxTTL().
2. In TimePartitionUtils, to locate the time partition slot of the current timestamp, we implement the getCurrentTimePartitionSlot().
3. In PartitionManager, we setup a periodically asynchronous thread, which combines the aforementioned interfaces to construct an "AutoCleanPartitionTablePlan." As a result, for each database, any data partition whose data are all expired will be …

Let the DataPartitionTable be automatically cleanable

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
iotdb-core/node-commons/src/assembly/resources/conf/iotdb-system.properties.template

Cherry-picking PR #14653 into CP/14653

[to dev/1.3] Adjust default wal_throttle_threshold_in_byte and region_migration_speed_limit_bytes_per_second (CP 14653)

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/consensus/statemachine/dataregion/DataRegionStateMachine.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/plan/node/pipe/PipeEnrichedDeleteDataNode.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/plan/node/pipe/PipeEnrichedInsertNode.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/plan/node/write/ContinuousSameSearchIndexSeparatorNode.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/plan/node/write/DeleteDataNode.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/plan/node/write/InsertMultiTabletsNode.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/plan/node/write/InsertNode.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/plan/node/write/InsertRowNode.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/plan/node/write/InsertRowsNode.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/plan/node/write/InsertRowsOfOneDeviceNode.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/plan/node/write/InsertTabletNode.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/plan/node/write/SearchNode.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/consensus/statemachine/dataregion/DataRegionStateMachineTest.java

[to dev/1.3] Extract "merge" method for SearchNode

---

integration-test/src/main/java/org/apache/iotdb/it/env/cluster/config/MppCommonConfig.java
integration-test/src/main/java/org/apache/iotdb/it/env/cluster/config/MppSharedCommonConfig.java
integration-test/src/main/java/org/apache/iotdb/it/env/remote/config/RemoteCommonConfig.java
integration-test/src/main/java/org/apache/iotdb/itbase/env/CommonConfig.java
integration-test/src/test/java/org/apache/iotdb/confignode/it/partition/IoTDBPartitionTableAutoCleanTest.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/consensus/request/ConfigPhysicalPlan.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/consensus/request/ConfigPhysicalPlanType.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/consensus/request/write/partition/AutoCleanPartitionTablePlan.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/ProcedureManager.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/TTLManager.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/partition/PartitionManager.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/persistence/TTLInfo.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/persistence/executor/ConfigPlanExecutor.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/persistence/partition/DatabasePartitionTable.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/persistence/partition/PartitionInfo.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/PartitionTableAutoCleaner.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/ProcedureExecutor.java
iotdb-core/confignode/src/test/java/org/apache/iotdb/confignode/consensus/request/ConfigPhysicalPlanSerDeTest.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/schedule/TTLScheduleTask.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/conf/CommonConfig.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/conf/CommonDescriptor.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/partition/DataPartitionTable.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/partition/SeriesPartitionTable.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/schema/ttl/TTLCache.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/utils/TimePartitionUtils.java

[To dev/1.3] Let the DataPartitionTable be automatically cleanable (#14737)

---

integration-test/src/test/java/org/apache/iotdb/confignode/it/removedatanode/IoTDBRemoveDataNodeITFramework.java
integration-test/src/test/java/org/apache/iotdb/confignode/it/removedatanode/IoTDBRemoveDataNodeNormalIT.java
integration-test/src/test/java/org/apache/iotdb/confignode/it/removedatanode/SQLModel.java
iotdb-core/antlr/src/main/antlr4/org/apache/iotdb/db/qp/sql/IdentifierParser.g4
iotdb-core/antlr/src/main/antlr4/org/apache/iotdb/db/qp/sql/IoTDBSqlParser.g4
iotdb-core/antlr/src/main/antlr4/org/apache/iotdb/db/qp/sql/SqlLexer.g4
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/execution/config/ConfigTaskVisitor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/execution/config/executor/ClusterConfigTaskExecutor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/execution/config/executor/IConfigTaskExecutor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/execution/config/metadata/RemoveDataNodeTask.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/parser/ASTVisitor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/statement/StatementVisitor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/statement/metadata/RemoveDataNodeStatement.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/statement/metadata/region/ExtendRegionStatement.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/statement/metadata/region/MigrateRegionStatement.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/statement/metadata/region/ReconstructRegionStatement.java

cp from https://github.com/apache/iotdb/pull/14678

[To dev/1.3][remove datanode] Add Remove DataNode SQL

---

.github/workflows/daily-it.yml
integration-test/pom.xml
integration-test/src/main/java/org/apache/iotdb/it/env/cluster/ClusterConstant.java
integration-test/src/main/java/org/apache/iotdb/it/env/cluster/node/DataNodeWrapper.java

目标：测试表模型在单 region 下的增删功能。
本次改动：
- 新添加的单 region 场景仅测试类别为 TableSimpleIT 的测试用例；
- 添加属性 integrationTest.dataRegionPerDataNode 控制 region 数；

[Daily IT]: Daily IT adds a single region task

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/DataRegion.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/utils/CompactionUtils.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/modification/ModificationFile.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/tsfile/TsFileResource.java

1. update mods file metrics during DataRegion recovery
2. some read of compaction mods file may trigger metrics updates
3. when linking mod file, if the source file has no mods, also add the target file mods as cascadeFiles
4. add removed mark for ModifcationFile

fix mods file metrics & fix the issue of missing mods with concurrent deletion and compaction

---

integration-test/src/test/java/org/apache/iotdb/session/it/IoTDBSessionInsertNullIT.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/flush/MemTableFlushTask.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/memtable/AlignedWritableMemChunk.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/memtable/WritableMemChunkGroup.java

Fix query error after insert an all null aligned tablet and flush

---

integration-test/src/test/java/org/apache/iotdb/relational/it/schema/IoTDBDatabaseIT.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/persistence/schema/ClusterSchemaInfo.java

Fixed the bug that the database is not totally separated in partition cache

---

iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/ratis/RatisConsensus.java

We should forbid adding new peer having same id/address with existing peers.

[RatisConsensus] prevent misuse of addRemotePeer

---

integration-test/src/test/java/org/apache/iotdb/pipe/it/autocreate/IoTDBPipeDataSinkIT.java
iotdb-client/cli/src/main/java/org/apache/iotdb/tool/tsfile/ImportTsFile.java
iotdb-client/cli/src/main/java/org/apache/iotdb/tool/tsfile/ImportTsFileLocally.java
iotdb-client/cli/src/main/java/org/apache/iotdb/tool/tsfile/ImportTsFileRemotely.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/pipe/connector/client/IoTDBConfigNodeSyncClientManager.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/pipe/connector/protocol/IoTDBConfigRegionAirGapConnector.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/pipe/connector/protocol/IoTDBConfigRegionConnector.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/client/IoTDBDataNodeAsyncClientManager.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/client/IoTDBDataNodeSyncClientManager.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/protocol/airgap/IoTDBDataNodeAirGapConnector.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/protocol/thrift/async/IoTDBDataRegionAsyncConnector.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/protocol/thrift/sync/IoTDBDataNodeSyncConnector.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/receiver/protocol/thrift/IoTDBDataNodeReceiver.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/parser/ASTVisitor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/load/active/ActiveLoadTsFileLoader.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/load/config/LoadTsFileConfigurator.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/config/constant/PipeConnectorConstant.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/connector/client/IoTDBClientManager.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/connector/client/IoTDBSyncClientManager.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/connector/payload/thrift/common/PipeTransferHandshakeConstant.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/connector/protocol/IoTDBConnector.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/connector/protocol/IoTDBSslSyncConnector.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/receiver/IoTDBFileReceiver.java

Original: https://github.com/apache/iotdb/pull/14774
<hr>
This PR has:
<hr>

[To dev/1.3] Pipe / Load: Enable validation skip for load tsFile (#14774)

---

integration-test/src/test/java/org/apache/iotdb/relational/it/db/it/IoTDBDeletionTableIT.java
integration-test/src/test/java/org/apache/iotdb/relational/it/query/recent/IoTDBNullValueIT.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/FileLoaderUtils.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/utils/ResourceByPathUtils.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/performer/impl/ReadChunkCompactionPerformer.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/utils/MultiTsFileDeviceIterator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/utils/executor/batch/BatchedFastAlignedSeriesCompactionExecutor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/utils/executor/batch/BatchedReadChunkAlignedSeriesCompactionExecutor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/utils/executor/batch/utils/AlignedSeriesBatchCompactionUtils.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/utils/executor/fast/FastAlignedSeriesCompactionExecutor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/utils/executor/fast/SeriesCompactionExecutor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/utils/executor/readchunk/ReadChunkAlignedSeriesCompactionExecutor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/utils/writer/FastCrossCompactionWriter.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/utils/writer/FastInnerCompactionWriter.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/memtable/AlignedReadOnlyMemChunk.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/memtable/TsFileProcessor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/read/reader/chunk/DiskAlignedChunkLoader.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/read/reader/chunk/MemAlignedChunkReader.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/read/reader/chunk/MemAlignedPageReader.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/read/reader/chunk/metadata/DiskAlignedChunkMetadataLoader.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/utils/ErrorHandlingUtils.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/utils/ModificationUtils.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/compaction/FastCompactionPerformerWithInconsistentCompressionTypeAndEncodingTest.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/compaction/FastInnerCompactionPerformerTest.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/compaction/repair/RepairUnsortedFileCompactionTest.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/compaction/utils/BatchCompactionUtilsTest.java
pom.xml

To replay you can use the following sqls (remember to disable cross_space_compaction)
```
create database db;
use db;
create table table1(id1 tag, s1 string);
insert into table1 values(0, 'd1', null), (1,'d1', 1);
flush;
insert into table1 values(0, 'd1', 0);
flush;
select * from table1;
```
previously, you will get duplicate timestamp 0
```
+-----------------------------+---+----+
|                         time|id1|  s1|
+-----------------------------+---+----+
|1970-01-01T08:00:00.000+08:00| d1|   0|
|1970-01-01T08:00:00.000+08:00| d1|null|
|1970-01-01T08:00:00.001+08:00| d1|   1|
+-----------------------------+---+----+
```

Fix duplicated time in result set bug

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/fragment/FragmentInstanceContext.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/schedule/DriverScheduler.java

previously, we record each block queue enter and exit time, actually we want to record total blocked time for each FI

Correct Block Queue Time metric

---

integration-test/src/test/java/org/apache/iotdb/session/it/IoTDBSessionInsertNullIT.java
iotdb-client/session/src/main/java/org/apache/iotdb/session/Session.java
iotdb-client/session/src/main/java/org/apache/iotdb/session/SessionConnection.java

```
public static void testInsertTablet_schemaListNullIn2() throws IoTDBConnectionException, StatementExecutionException {
int insertCount = 1;
String device="root.params.d_1";
List<MeasurementSchema> schemas = new ArrayList<>(3);
schemas.add(new MeasurementSchema("s_0", TSDataType.BOOLEAN));
schemas.add(new MeasurementSchema("s_1", TSDataType.INT32));
schemas.add(new MeasurementSchema(null, TSDataType.INT32));
Tablet tablet = new Tablet(device, schemas, insertCount);
int rowIndex = 0;
long timestamp = 1635232143960L;
for (int row = 0; row < insertCount; row++) {
timestamp += 3600000;
tablet.addTimestamp(rowIndex, timestamp);
for (int i = 0; i < schemas.size() - 1; i++) {
switch(schemas.get(i).getType()) {
case BOOLEAN:
tablet.addValue(schemas.get(i).getMeasurementId(), rowIndex, true); …
```

Fix null measurement name issue in insertTablet

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/tools/utils/TsFileRewriteOverPrecisedI64Scan.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/tools/utils/TsFileRewriteSmallRangeI64Scan.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/tools/utils/TsFileSequenceScan.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/tools/utils/TsFileStatisticScan.java

1. TsFileRewriteOverPrecisedI64Scan
Rewrite Int64 chunks that can be converted to Int32 losslessly.
2. TsFileRewriteSmallRangeI64Scan
Rewrite Int64 chunks whose ranges are no larger than Int32.MAX_VALUE by replacing the value with the difference with the first value in the chunk.
3. TsFileStatisticScan
It prints:
a. the number of series of each data type;
b. the number of Int64 chunks that are over-precised (can be converted to Int32 losslessly), just-precised (cannot be converted to Int32 losslessly), small range (range not larger than Int32.MAX_VALUE), or large range (range larger than Int32.MAX_VALUE);
c. the number of points of each data type;
d. the total chunk size of each data type;
e. average distinct binary value num of STRING and TEXT chunks;

Add some tsfile-related tools

---

integration-test/src/test/java/org/apache/iotdb/db/it/query/IoTDBQueryDemoIT.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/parser/ASTVisitor.java

Cause: Now we treated `Time` as a special column, and the process of it is different a lot from normal column. Write `Time` in `select clause` explicitly will cause `Time`  to be recognized as a normal column, which led to series of exception.
Fix: We will throw exception to note user not to use `Time` explicitly in `select clause`.

Fix select time in TreeModel

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/fragment/FragmentInstanceContext.java

Previously, we occasionaly got CI failed by error code different in each data node
This may be caused by FragmentInstanceInfo constrcutor.
If FI didn't fail while calling getErrorCode and then failed after calling getErrorCode, this problem may happen.

 Try to fix error code different in each data node problem

---

integration-test/src/test/java/org/apache/iotdb/db/it/auth/IoTDBAuthIT.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/parser/ASTVisitor.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/plan/parser/StatementGeneratorTest.java

Fix bug "Not support Relation statement in tree sql_dialect " when a non-root user grant all on root.** to user other.

fix auth parser error with grant all on root.** from non-root user.

---

docker/src/main/DockerCompose/entrypoint.sh
docker/src/main/DockerCompose/replace-conf-from-env.sh

fix:
1. iotdb-system.properties is no full configuration in iotdb-system.properties. 
2. Not sure stop-standalone.sh will be called anyway.

fix_docker,iotdb-system.properties contains all configuration,stop-standalone.sh will be called anyway

---

pom.xml

[To dev/1.3] Bump net.minidev:json-smart from 2.5.0 to 2.5.2

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/executor/RegionWriteExecutor.java

Fixed the bug that internalCreate(Multi)TimeSeries may write empty device when measurements are all trimmed

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/executor/RegionWriteExecutor.java

Original PR: https://github.com/apache/iotdb/pull/14827
<hr>
This PR has:
<hr>

[To dev/1.3] Fixed the bug that internalCreate(Multi)TimeSeries may write empty device when measurements are all trimmed (#14827)

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/receiver/protocol/pipeconsensus/PipeConsensusReceiver.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/receiver/IoTDBFileReceiver.java

After discussion, we decide to maintain both mods transfer and DAL transfer for DELETION replication.
This pr enhances the support for mods transfer.
As this image shows, when transfer mods may encounter npe.
This is caused by 2 bugs:
1. sync a file after close its handler(we should sync before close)
2. `handleTsFileSealWithMods` doesn't support mods transfer well, need some enhancement.

[IoTConsensusV2] Fix NPE when transfer tsfile mods

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/receiver/visitor/PipePlanToStatementVisitor.java

Pipe: Fix the problem that the receiver constructs InsertStatement causing the MeasurementShcema to not be correctly set to null (NPE)

---

iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/conf/CommonConfig.java

(cherry picked from commit 515991dc9f7c13a569bcd3ebedc8b01720bda35c)

[To dev/1.3] Pipe: adjust default pipeRealTimeQueuePollHistoryThreshold to reduce retransmission upon frequent rebooting

---

integration-test/src/test/java/org/apache/iotdb/db/it/IoTDBSimpleQueryIT.java
integration-test/src/test/java/org/apache/iotdb/subscription/it/triple/regression/param/IoTDBTestParamTopicIT.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/utils/DateTimeUtils.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/utils/DateTimeUtilsTest.java

Reject inserting invalid timestamp string

---

integration-test/src/test/java/org/apache/iotdb/relational/it/session/IoTDBSessionRelationalIT.java
integration-test/src/test/java/org/apache/iotdb/session/it/IoTDBSessionSimpleIT.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/plan/node/write/RelationalInsertRowNode.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/sql/parser/AstBuilder.java

The rows of an insert SQL share the same measurement array.
If one row fails to pass the schema validation, the associated measurements will be marked as null.
Since the measurement array is shared, other rows will also be affected.
This PR fixes this issue by creating a measurement array copy for each row.

Fix that failure of one row in relational InsertRows will fail other rows

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/subscription/broker/SubscriptionPrefetchingTabletQueue.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/subscription/broker/SubscriptionPrefetchingTsFileQueue.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/subscription/event/cache/SubscriptionPollResponseCache.java

cherry-pick #14926 to https://github.com/apache/iotdb/tree/dev/1.3

[To dev/1.3] Subscription: avoid null pointer exception when get current response due to concurrent operations (#14926)

---

iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/persistence/partition/DatabasePartitionTable.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/PartitionTableAutoCleaner.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/partition/DataPartitionTable.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/partition/SeriesPartitionTable.java

Since the log for the PartitionTableAutoCleaner is insufficient, this PR replenish the following logs:
1. The clean cycle is recorded when the PartitionTableAutoCleaner is constructed.
2. The deleted time partitions of each database are recorded.

Add logs for PartitionTableAutoCleaner

---

iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/service/ConfigNode.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/service/DataNode.java

For the sake of cluster security, delete the remove-confignode/datanode logic in ServerCommandLine after adding the remove SQL.

Delete remove node logic in ServerCommandLine

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/memtable/AbstractMemTable.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/memtable/AlignedWritableMemChunkGroup.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/memtable/IMemTable.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/memtable/IWritableMemChunkGroup.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/memtable/TsFileProcessor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/memtable/WritableMemChunkGroup.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/utils/datastructure/AlignedTVList.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/utils/datastructure/BinaryTVList.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/utils/datastructure/BooleanTVList.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/utils/datastructure/DoubleTVList.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/utils/datastructure/FloatTVList.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/utils/datastructure/IntTVList.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/utils/datastructure/LongTVList.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/utils/datastructure/TVList.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/memtable/TsFileProcessorTest.java

Solve peformance regression of sequential inserting (non-aligned time series)
delay indices initialization until sort
mem cost based on whether indices & bitmap is null
<hr>
This PR has:
<hr>

peformance regression of sequential inserting

---

iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/persistence/partition/DatabasePartitionTable.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/PartitionTableAutoCleaner.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/partition/DataPartitionTable.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/partition/SeriesPartitionTable.java

Since the log for the PartitionTableAutoCleaner is insufficient, this PR replenish the following logs:
1. The clean cycle is recorded when the PartitionTableAutoCleaner is constructed.
2. The deleted time partitions of each database are recorded.

[To dev/1.3] Add logs for PartitionTableAutoCleaner

---

iotdb-client/session/src/main/java/org/apache/iotdb/session/subscription/consumer/SubscriptionConsumer.java

cherry-pick #14937 to https://github.com/apache/iotdb/tree/dev/1.3

[To dev/1.3] Subscription: check if all topic messages have been consumed when client polling (#14937)

---

iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/common/request/IConsensusRequest.java
iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/common/request/IndexedConsensusRequest.java
iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/iot/logdispatcher/LogDispatcher.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/plan/node/write/InsertNode.java

The actual memory occupied by IoTConsensus is 2-3 times larger than the statistical memory of memory management, so more detailed statistics of consensus memory are needed.
As shown in the figure, the statistical result of using `getMemorySize` is about twice the size of `buffer`, which makes the result more accurate.

[IoTConsensus] More accurate statistics on IoTConsensus memory management

---

iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/connector/protocol/IoTDBAirGapConnector.java

[To dev/1.3] Pipe: Reduce the frequency of printing logs when AirGapConnector connection fails (#14949)

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/subscription/broker/SubscriptionPrefetchingQueue.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/subscription/broker/SubscriptionPrefetchingTabletQueue.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/subscription/broker/SubscriptionPrefetchingTsFileQueue.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/subscription/event/SubscriptionEvent.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/subscription/event/batch/SubscriptionPipeEventBatch.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/subscription/event/batch/SubscriptionPipeEventBatches.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/subscription/event/batch/SubscriptionPipeTabletEventBatch.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/subscription/event/batch/SubscriptionPipeTabletIterationSnapshot.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/subscription/event/batch/SubscriptionPipeTsFileEventBatch.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/subscription/event/pipe/SubscriptionPipeEmptyEvent.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/subscription/event/pipe/SubscriptionPipeEvents.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/subscription/event/pipe/SubscriptionPipeTabletBatchEvents.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/subscription/event/pipe/SubscriptionPipeTsFileBatchEvents.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/subscription/event/pipe/SubscriptionPipeTsFilePlainEvent.java

As title.
Can eliminate the phantom reference leaks of tsfile events and raw tablet events in the case of a restart.

Subscription: add parameter to the clean up method to distinguish the force close situation & fix reference count management for iteration snapshot

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/relational/aggregation/grouped/hash/HashStrategy.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/plan/relational/analyzer/GroupByLargeDataTest.java

cause: When the processed TsBlock is more than 1024 lines, the offset will not be zero, so the read value is wrong.

Fix group by hash when process TsBlock more than 1024 lines

---

integration-test/src/test/java/org/apache/iotdb/relational/it/query/old/builtinfunction/scalar/IoTDBFormatFunctionTableIT.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/transformation/dag/column/unary/scalar/FormatColumnTransformer.java

This pull request includes a change to the `FormatColumnTransformer` class in the `iotdb-core` module, specifically to the `valueConverter` method. The change simplifies the conversion of `DATE` type values by using a more direct method.
Simplification of date conversion:
* [`iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/transformation/dag/column/unary/scalar/FormatColumnTransformer.java`](diffhunk://#diff-8d2fa9c31ebb1c81d04af40540bd7eb8fcc7acef2283b5d09920c59c8674ce8fL104-R104): Simplified the conversion of `DATE` type values by using `DateUtils.parseIntToLocalDate` instead of a multi-step process involving `DateTimeUtils.correctPrecision` and `DateTimeUtils.convertToLocalDate`.

Fix overflow when using format in ns timestamp precision

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java

Fix Memory NPE when use IDEA to debug. This is mainly because when there are no properties, init method in DataNodeMemoryConfig will never be called.

Fix Memory NPE when use IDEA to debug

---

integration-test/src/test/java/org/apache/iotdb/relational/it/db/it/IoTDBFlushQueryTableIT.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/utils/datastructure/AlignedTVList.java

To reproduce, execute the following sqls.
```sql
create database db1
use db1
create table t2(s1 text field, s2 text field)
insert into t2(time,s2) values(2,'t1')
alter table t2 drop column s2
flush
```

Fix division by zero error when flush memtable

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/receiver/protocol/pipeconsensus/PipeConsensusReceiver.java

There are two TsFile, naming TsFileA and TsFileB respectively.
**Time1:** TsFileB is going to finish replication as it's seal request is being handled by follower.
**Time2:** TsFileB's seal request is handled by follower successfully, and TsFileB returns its TsFileWriter which names TsFileWriterA to TsWriterPool.
**Time3:** TsFileA is being transferred to follower, and TsFileA borrows TsFileWriterA from TsWriterPool.
**Time4:** TsFileA binds its file to TsFileWriterA
**Time5:** TsFileB deletes TsFileWriterA's binding file, which is TsFileA's file.
**Time6:** Any further requests related to TsFileA will cause NPE, because TsFileA's file is deleted.
```txt
2025-03-11 16:57:06,717 [pool-70-IoTDB-PipeConsensusRPC-Processor-40] INFO  o.a.i.d.p.r.p.p.PipeConsensusReceiver$RequestExecutor:1347 - …
```

IoTConsensusV2: Fix borrow tsfileWriter and delete tsfileWriter's file concurrency bug

---

integration-test/src/test/java/org/apache/iotdb/ainode/it/AINodeBasicIT.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/process/ai/InferenceOperator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/AnalyzeVisitor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/parser/ASTVisitor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/LogicalPlanBuilder.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/LogicalPlanVisitor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/OperatorTreeGenerator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/plan/node/process/AI/InferenceNode.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/statement/crud/QueryStatement.java

(cherry picked from commit f16252d8105cab29bbe28b5d8ddf3d3afda6d85b)
#15069

[to dev/1.3] [AINode] Support output time column for model inference

---

iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/schema/view/viewExpression/unary/LikeViewExpression.java

When adding escape functionality to LIKE, the serialization and deserialization methods of LikeViewExpression were modified, which led to compatibility issues during version upgrades. The old Raft logs would cause errors when processed with the new deserialization function. The compatibility issue has now been resolved.

Compatibility modification for LikeViewExpression deserialization

---

integration-test/src/test/java/org/apache/iotdb/relational/it/query/old/builtinfunction/scalar/IoTDBFormatFunctionTableIT.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/metadata/TableMetadataImpl.java

This pull request includes a small but important change to the `iotdb-core/datanode` module. The change updates the error message for a scalar function to provide more accurate information about the required argument types.
* [`iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/metadata/TableMetadataImpl.java`](diffhunk://#diff-5420ab45f1bfb25708b0cd843b2770256e0671bc180acb7abf7f8a89888a3aa0L543-R543): Updated the error message to specify that the first argument pattern must be of type TEXT or STRING instead of just char type.

Modify the error message for when parameters do not match

---

iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/load/cache/detector/PhiAccrualDetector.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/load/cache/node/AINodeHeartbeatCache.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/load/cache/node/ConfigNodeHeartbeatCache.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/load/cache/node/DataNodeHeartbeatCache.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/load/cache/region/RegionCache.java

1. Use debug level log for history dump (workaround)
2. Use copy of history to avoid concurrency issue (workaround also)

[RTO/RPO] Phi logging/concurrency Improvement

---

integration-test/src/test/java/org/apache/iotdb/relational/it/query/old/query/IoTDBArithmeticTableIT.java
iotdb-core/datanode/src/main/codegen/templates/ArithmeticBinaryColumnTransformer.ftl

This pull request includes changes to enhance date handling and error reporting in arithmetic operations within the IoTDB project. The most significant changes involve adding new test cases, importing necessary classes, and handling specific exceptions for date-related operations.
Enhancements to date handling and error reporting:
* [`integration-test/src/test/java/org/apache/iotdb/relational/it/query/old/query/IoTDBArithmeticTableIT.java`](diffhunk://#diff-908fd9921b253d5bad61a0f1e2389379172b0031b3c541be95a08fe2645848f7R357-R368): Added new test cases in `testDateOutOfRange` to verify the correct handling of date arithmetic operations and ensure that the error message "Year must be between 1000 and 9999." is correctly triggered.
* …

Int + Date and Long + Date do not check if the date exceeds the range

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/fragment/FragmentInstanceContext.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/fragment/QueryStatistics.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/relational/aggregation/TableAggregator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/metric/SeriesScanCostMetricSet.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/buffer/TimeSeriesMetadataCache.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/service/metric/enums/Metric.java

1. Remove useless statistics metrics calc logic in AggTableScanOperator.
2. Make the TimeseriesMetadataCache get time as FI level.
<hr>
This PR has:
<hr>

Remove useless metrics in AggTableScan and make the TimeseriesMetadataCache get time as FI level

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/metadata/fetcher/SchemaPredicateUtil.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/metadata/fetcher/TableDeviceSchemaFetcher.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/planner/ir/IrUtils.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/sql/ast/AbstractTraverseDevice.java

Omitted the useless distinct logic for device when determined predicate does not contain "OR"

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/distribution/SimpleFragmentParallelPlanner.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/planner/distribute/TableModelQueryFragmentPlanner.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/scheduler/FragmentInstanceDispatcherImpl.java

Optimized the query logic to make schema or weak data query read from local first & random if without local

---

integration-test/src/test/java/org/apache/iotdb/db/it/schema/IoTDBExtendTemplateIT.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/schema/TemplateSchemaFetcher.java

When extending a template with a null value, the insertion will fail due to an NPE of finding the associated encoding.
Such column is ignored by this PR.

Fix template extension with null value

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/fragment/FragmentInstanceContext.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/buffer/TimeSeriesMetadataCache.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/VirtualDataRegion.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/tsfile/TsFileResource.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/tsfile/timeindex/ArrayDeviceTimeIndex.java

If all seq data, and compaction is well done, we will only need to get one TimeSeriesMetadata to calcuate count for each device. However, according to the profiler result, we found a lot of overhead in SeriesScanUtil, in this pr we will try to save the useless code execution.
1. needless set in initQueryDatasource in some cases
2. save device.toString() if cache hit in TimeSeriesMetadataCache
3. use result of map.get() to judge whether a key exists instead of using map,containsKey before calling map.get

Optimize query execution in easy count(*) cases

---

iotdb-core/confignode/src/assembly/resources/sbin/stop-confignode.bat
iotdb-core/confignode/src/assembly/resources/sbin/stop-confignode.sh
iotdb-core/datanode/src/assembly/resources/conf/datanode-env.sh
iotdb-core/datanode/src/assembly/resources/sbin/stop-datanode.bat
iotdb-core/datanode/src/assembly/resources/sbin/stop-datanode.sh
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java

The scripts of stopping data nodes and config nodes use port from the configuration file but do not trim it, 
which may cause a failure of matching the port in config and the port of the node.
The same occurs when datanode-env.sh tries to make the dir for heap dump.

Trim port in stop scripts & data dir

---

iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/env/ConfigNodeProcedureEnv.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/env/RegionMaintainHandler.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/region/ReconstructRegionProcedure.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/region/RegionMigrateProcedure.java

There are two reasons:
- The concurrency control for region migration and reconstruction has already been handled at a higher level, see ProcedureManager.regionOperationCommonCheck).
- This part of the code conflicts with the unified lock management implemented at the Dec of 2024 (#14250), which may lead to one procedure being executed by multiple threads simultaneously.

RegionMigrateProcedure and RegionReconstructProcedure no longer acquire lock

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/plan/node/PlanGraphPrinter.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/planner/TableLogicalPlanner.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/planner/iterative/rule/PruneExplainAnalyzeColumns.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/planner/node/ExplainAnalyzeNode.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/planner/node/Patterns.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/planner/optimizations/LogicalOptimizeFactory.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/planner/optimizations/UnaliasSymbolReferences.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/plan/relational/analyzer/ExplainAnalyzeTest.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/plan/relational/planner/PlanTester.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/plan/relational/planner/assertions/PlanMatchPattern.java

Target query: `explain analyze select count(s1) from table1 group by tag1`
Before Plan: no column-prune
(The second node without name  is `ExplainAnalyzeNode`)
After:
FixMethod: correct column-prune
Make `ExplainAnalyzeNode` hold symbols that optimizers need and use them when do optimize.

Fix optimizers doesn't work when execute Explain Anzlyze query

---

integration-test/src/test/java/org/apache/iotdb/relational/it/query/recent/IoTDBNullIdQueryIT.java
iotdb-client/session/src/main/java/org/apache/iotdb/session/Session.java
iotdb-client/session/src/main/java/org/apache/iotdb/session/pool/TableSessionWrapper.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/session/IClientSession.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/execution/config/executor/ClusterConfigTaskExecutor.java

Clean databaseName when setSqlDialect

---

integration-test/src/test/java/org/apache/iotdb/relational/it/session/IoTDBSessionRelationalIT.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/sql/parser/AstBuilder.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/sql/util/AstUtil.java

Inserting a null timestamp via SQL will throw an unrecognizable exception.
It now throws a more clear semantic exception.

Fix null timestamp

---

iotdb-client/jdbc/src/main/java/org/apache/iotdb/jdbc/IoTDBConnection.java
iotdb-client/jdbc/src/main/java/org/apache/iotdb/jdbc/IoTDBStatement.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/session/IClientSession.java

Cause: CLI get the current db from JDBC client, we don't clean db in it when change sql_dialect.
Fix: clean databaseName in JDBC client when change sql_dialect
Verify:

Fix database hint of CLI when change sql_dialect back to table

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/agent/task/PipeDataNodeTaskAgent.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/event/common/tsfile/PipeTsFileInsertionEvent.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/event/common/tsfile/parser/TsFileInsertionEventParser.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/event/common/tsfile/parser/TsFileInsertionEventParserProvider.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/event/common/tsfile/parser/query/TsFileInsertionEventQueryParser.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/event/common/tsfile/parser/scan/TsFileInsertionEventScanParser.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/event/common/tsfile/parser/table/TsFileInsertionEventTableParser.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/extractor/dataregion/IoTDBDataRegionExtractor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/metric/PipeDataNodeMetrics.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/metric/overview/PipeTsFileToTabletsMetrics.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/service/metric/enums/Metric.java

Pipe: Add metrics for tsfile to tablets invocation call count and time

---

integration-test/src/test/java/org/apache/iotdb/db/it/schema/IoTDBDeleteAlignedTimeseriesIT.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/memtable/AlignedWritableMemChunk.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/utils/datastructure/AlignedTVList.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/utils/datastructure/TVList.java

1. Do not share data types when create new aligned TVList
2. fix bug - delete column of aligned timeseries, and then insert columns
3. fix bug - bitmap is null when delete column
4. init bitmaps locally when it's null
<hr>
This PR has:
<hr>

fix: clone & delete issues

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/protocol/opcua/OpcUaNameSpace.java

Pipe: Fixed the NPE of OPC UA Sink in table model when there are null values & Deleted the extra folder of opc ua sink in table model

---

integration-test/src/test/java/org/apache/iotdb/db/it/IoTDBRestartIT.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/load/service/TopologyService.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/distribution/SimpleFragmentParallelPlanner.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/exceptions/RootFIPlacementException.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/plan/AbstractFragmentParallelPlanner.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/planner/distribute/TableDistributedPlanner.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/planner/distribute/TableModelQueryFragmentPlanner.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/utils/ErrorHandlingUtils.java

This patch is to fix some small issues in https://github.com/apache/iotdb/pull/15014
1. Fix remaining minor issues suggested by @OneSizeFitsQuorum 
2. Refactor SimpleFragmentParallelPlanner and TableModelQueryFragmentPlanner suggested by @JackieTien97

[RTO/RPO] Chore: Fix remaining issues in PR 15014

---

iotdb-client/client-cpp/src/main/Session.cpp

Fixed an issue where tablet bitmap processing failed to handle null values correctly.
- **The tablet's bitmap is serialized according to tablet.rowSize, not the full byte length.**
- Verified fix in test environment
<hr>
This PR has:
• [x] been self-reviewed.
- table model
```cpp
#include "TableSession.h"
#include "TableSessionBuilder.h"
#include <iostream>
#include <ostream>
using namespace std;
TableSession *session;
int main() {
try {
session = (new TableSessionBuilder())->build();
try {
session->executeNonQueryStatement("CREATE DATABASE test_insert_db1");
session->executeNonQueryStatement("use test_insert_db1");
session->executeNonQueryStatement("CREATE TABLE t1 (tag1 STRING TAG,attr1 STRING ATTRIBUTE,s1 BOOLEAN FIELD,s2 INT32 FIELD,s3 INT64 FIELD,s4 FLOAT FIELD,s5 DOUBLE FIELD,s6 …
```

Fix: Null value settings not applying correctly in tablet.

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/subscription/event/batch/SubscriptionPipeTsFileEventBatch.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/subscription/event/pipe/SubscriptionPipeTsFileBatchEvents.java

As title.
Fix #15188 CI timeout.

Subscription: distinguish between reference count of ack and clean in tsfile batch to avoid cleaning before ack

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/relational/aggregation/grouped/GroupedExtremeAccumulator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/relational/aggregation/grouped/GroupedFirstAccumulator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/relational/aggregation/grouped/GroupedLastAccumulator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/relational/aggregation/grouped/GroupedSumAccumulator.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/plan/relational/analyzer/AggregationCornerCaseTest.java

As title.
Extra: this PR also fix some wrong in `GroupedFirstAccumulator`, it will not cause the incorrectness of query now, but if we introduce filter in AggFunction in later, it will cause.

Fix BigArray NPE of some aggregation functions (first, last, sum, extreme) when groups are more than 1024 in aggregation query

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/subscription/event/batch/SubscriptionPipeTsFileEventBatch.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/subscription/event/pipe/SubscriptionPipeTsFileBatchEvents.java

cherry-pick #15229 to https://github.com/apache/iotdb/tree/dev/1.3

[To dev/1.3] Subscription: distinguish between reference count of ack and clean in tsfile batch to avoid cleaning before ack (#15229)

---

iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/partition/PartitionManager.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/schema/DeleteDatabaseProcedure.java

The process of creating partitions might throw some NPEs when the corresponding database is deleted logically. Thus, we add some logs for clearing the bug suspicion.

Add some supplementary logs during partition allocation

---

iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/conf/ConfigNodeConfig.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java
iotdb-core/node-commons/src/assembly/resources/conf/iotdb-system.properties.template

The default value of rpcMaxConcurrentClientNum 65535 is too large. Reducing the default number of allowed client connections can enhance the self-protection mechanism of the database.
This PR changes the default cn_rpc_max_concurrent_client_num to 3000, changes the default dn_rpc_max_concurrent_client_num to 1000.

Reduce default value of rpcMaxConcurrentClientNum

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/relational/aggregation/AvgAccumulator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/relational/aggregation/CountAccumulator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/relational/aggregation/CountAllAccumulator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/relational/aggregation/ExtremeAccumulator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/relational/aggregation/FirstAccumulator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/relational/aggregation/FirstByAccumulator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/relational/aggregation/LastAccumulator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/relational/aggregation/LastByAccumulator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/relational/aggregation/MaxAccumulator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/relational/aggregation/MinAccumulator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/relational/aggregation/SumAccumulator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/relational/aggregation/TableMaxMinByBaseAccumulator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/relational/aggregation/TableVarianceAccumulator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/relational/aggregation/grouped/GroupedAvgAccumulator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/relational/aggregation/grouped/GroupedExtremeAccumulator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/relational/aggregation/grouped/GroupedFirstAccumulator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/relational/aggregation/grouped/GroupedFirstByAccumulator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/relational/aggregation/grouped/GroupedLastAccumulator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/relational/aggregation/grouped/GroupedLastByAccumulator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/relational/aggregation/grouped/GroupedMaxAccumulator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/relational/aggregation/grouped/GroupedMaxMinByBaseAccumulator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/relational/aggregation/grouped/GroupedMinAccumulator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/relational/aggregation/grouped/GroupedModeAccumulator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/relational/aggregation/grouped/GroupedSumAccumulator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/relational/aggregation/grouped/GroupedVarianceAccumulator.java

This pull request involves several changes to the `iotdb-core` module, specifically related to the naming conventions of aggregation functions in various accumulator classes. The primary change is the standardization of the function names to uppercase.
Standardization of function names:
* [`iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/relational/aggregation/AvgAccumulator.java`](diffhunk://#diff-3157fa86a400bd42336a13dd196a918303865cde90f815178bcc8d00a3bc8365L60-R60): Changed "Avg" to "AVG" in error messages. [[1]](diffhunk://#diff-3157fa86a400bd42336a13dd196a918303865cde90f815178bcc8d00a3bc8365L60-R60) [[2]](diffhunk://#diff-3157fa86a400bd42336a13dd196a918303865cde90f815178bcc8d00a3bc8365L88-R88) …

Harmonizing the case of reported error messages for aggregation 

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/agent/task/PipeDataNodeTaskAgent.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/client/IoTDBDataNodeCacheLeaderClientManager.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/event/common/tsfile/container/TsFileInsertionDataContainerProvider.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/extractor/dataregion/realtime/PipeRealtimeDataRegionHybridExtractor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/metric/overview/PipeResourceMetrics.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/resource/memory/PipeMemoryManager.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/resource/tsfile/PipeTsFileResourceManager.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/subscription/broker/SubscriptionPrefetchingQueueStates.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/subscription/event/cache/SubscriptionPollResponseCache.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/conf/CommonConfig.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/conf/CommonDescriptor.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/agent/task/PipeTaskAgent.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/config/PipeConfig.java

https://github.com/apache/iotdb/pull/15205
<hr>
This PR has:
<hr>

[To dev/1.3] Pipe: Added total floating memory usage for mem-ctrl of linked but deleted tsFile resource and insertNode memory (#15205)

---

integration-test/src/test/java/org/apache/iotdb/relational/it/query/recent/IoTDBTableAggregationIT.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/planner/SymbolAllocator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/planner/iterative/rule/SingleDistinctAggregationToGroupBy.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/planner/node/AggregationTableScanNode.java

Cause: The `AggTableScanOperator` always append the date_bin result in the last of `groupingKeys`, but it is not always the same order with `outputSymbols` refined, typically when do single input distinct optimize.
Fix: Make sure the date_bin is the last of `groupingKeys`, and add argument check when init  `AggTableScanNode`.

Fix the output ordinal of AggTableScanOperator are not consistent with OutputSymbols of AggTableScanNode when do single input distinct optimize

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/service/metrics/FileMetrics.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/service/metrics/file/ModsFileMetrics.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/tsfile/TsFileResource.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/compaction/ReadChunkInnerCompactionTest.java

Fix mods file metrics.
The 'closeWithoutSettingStatus' method sets exclusiveModFile to null, and the mods file metric will be updated again when other modules call getExclusiveModFile.

Fix mods file metrics

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/relational/LastQueryAggTableScanOperator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/TableOperatorGenerator.java

As the title, before fix, method `updateLastCacheIfExists` is invoked after method `initOrInvalidateLastCache` immediately, this may cause that `older query result` updates `newer write data cache`.
```
TABLE_DEVICE_SCHEMA_CACHE.initOrInvalidateLastCache(
dbName, currentDeviceEntry.getDeviceID(), updateMeasurementArray, false);    
TABLE_DEVICE_SCHEMA_CACHE.updateLastCacheIfExists(
dbName,
currentDeviceEntry.getDeviceID(),
updateMeasurementArray,
updateTimeValuePairArray);
```
<hr>
This PR has:
<hr>

Fix the usage of method initOrInvalidateLastCache in table last query process.

---

iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/iot/IoTConsensus.java
iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/iot/IoTConsensusServerImpl.java

In region migration, if the target node restarts before the “addRegionPeer” phase within 1 minutes, the client in the ClientManager will become invalid.
This PR adds 1 retry at this point to ensure that region migration can still proceed correctly in such cases.

Add retry for inactivePeer of region migration

---

iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/pipe/PipeConsensus.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/protocol/pipeconsensus/PipeConsensusAsyncConnector.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/protocol/pipeconsensus/PipeConsensusSyncConnector.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/client/container/PipeConsensusClientMgrContainer.java

as title.
I also set selector num max(3, conf), considering all pipe connectors and pipeConsensus use a single client manager.

IoTV2: Use global singleton ClientManager to avoid too many thrift threads which leads to Direct Memory OOM.

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/agent/task/subtask/connector/PipeRealtimePriorityBlockingQueue.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/subscription/broker/SubscriptionBlockingPendingQueue.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/subscription/broker/SubscriptionPrefetchingQueue.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/subscription/broker/TsFileDeduplicationBlockingPendingQueue.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/agent/task/connection/BlockingPendingQueue.java

cherry-pick #15307 to https://github.com/apache/iotdb/tree/dev/1.3

[To dev/1.3] Subscription: poll heartbeat event when there are no consumers (#15307)

---

integration-test/src/test/java/org/apache/iotdb/relational/it/query/old/query/IoTDBGreatestLeastTableIT.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/transformation/dag/column/multi/BooleanGreatestColumnTransformer.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/transformation/dag/column/multi/BooleanLeastColumnTransformer.java

This pull request includes changes to the `IoTDBGreatestLeastTableIT` integration test and improvements to the `BooleanGreatestColumnTransformer` and `BooleanLeastColumnTransformer` classes. The most important changes are the addition of new test cases and improvements to the boolean transformation logic.
Improvements to integration tests:
* [`integration-test/src/test/java/org/apache/iotdb/relational/it/query/old/query/IoTDBGreatestLeastTableIT.java`](diffhunk://#diff-3ebb39862466df9835f4759c18ce131c3bf343a81bc3f07102b35dc25e7d1472R55-R56): Added new boolean values to the `boolean_table` and updated the expected results in the `testBooleanTypeGreatestFunction` and `testBooleanTypeLeastFunction` methods to reflect these changes. [[1]](diffhunk://#diff-3ebb39862466df9835f4759c18ce131c3bf343 …

Fix Greatest's looping logic bug in Boolean types.

---

iotdb-client/cli/src/main/java/org/apache/iotdb/cli/utils/JlineUtils.java

pref: Set the maximum number of history records in the history file / memory to 1,000 lines.

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/schedule/CompactionScheduler.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/selector/impl/SettleSelectorImpl.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/compaction/settle/SettleCompactionSelectorTest.java

Currently, during the settle phase of file selection, all files in a partition are traversed and categorized based on the amount of remaining data. Files are classified as either fully dirty or partial dirty. A fully dirty file is one from which all data can be deleted, while a partial dirty file contains only some deletable data. In the final compaction tasks, fully dirty files are expected to be deleted first, followed by the cleanup of partial dirty files through inner-space compaction tasks.
A large number of partial dirty files may be selected within a single partition. These files are not all submitted in one compaction task. Instead, they are split into multiple tasks based on their size and count. The current splitting strategy submits all fully dirty files along with the first …

Separate fully dirty files by partially dirty files task

---

iotdb-client/service-rpc/src/main/java/org/apache/iotdb/rpc/subscription/payload/poll/ErrorPayload.java
iotdb-client/session/src/main/java/org/apache/iotdb/session/subscription/consumer/base/AbstractSubscriptionConsumer.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/subscription/agent/SubscriptionBrokerAgent.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/subscription/broker/SubscriptionBroker.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/subscription/broker/SubscriptionPrefetchingQueue.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/subscription/broker/SubscriptionPrefetchingTabletQueue.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/subscription/broker/SubscriptionPrefetchingTsFileQueue.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/subscription/receiver/SubscriptionReceiverV1.java

Subscription: detect outdated subscription event for better consumer exception control

---

integration-test/src/test/java/org/apache/iotdb/db/it/aggregation/IoTDBCountIfIT.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/plan/parameter/AggregationDescriptor.java

Before fix, if the attributes of AggregationFunction is more than one, the ordinal of attributes will miss, it causes the `OutputColumnName` is different from  from before serialization.

Make deserialize of AggregationDescriptor AttributesMap use LinkedHashMap

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/relational/LastQueryAggTableScanOperator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/TableOperatorGenerator.java

cause: 
The first last query failed to hit the last cache. And this placeholder `EMPTY_PRIMITIVE_TYPE` will be marked in the last cache, and then the last cache will be updated after the subsequent queries read the disk. 
However, before the last cache was updated in the previous query, a new query (with the same content as the previous one) read this placeholder.
Before this fix, we think the last cache is hit when the placeholder is read, it is not correct.

Fix process of last query if intermediate state of last cache is read when query concurrently

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java

fix an encrypt_key_import bug(the parameter's name is wrong and lead to import useless). Correct it and move the set-parameter part to a more proper place.

fix an encrypt_key_import bug

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/util/builder/PipeTableModeTsFileBuilder.java

In `PipeTableModeTsFileBuilder.tryBestToWriteTabletsIntoOneFile(...)`, we collect per‑device lists of tablets into a `LinkedHashSet<LinkedList<T>>` and then peel off entries by calling `iterator.remove()` when a list becomes empty. However, because `LinkedList`’s `hashCode()`/`equals()` depend on its contents, repeatedly polling elements from the list changes its hash code. Once its hash no longer matches its original bucket, `iterator.remove()` silently fails to expunge the “empty” list, leaving behind a zero‑length `LinkedList` in the set.
- Mutating a `LinkedList` stored in a hash‑based set invalidates the set’s internal invariants.
- After polling all elements, `iterator.remove()` cannot locate the entry by its mutated hash code.
- **The set ends up retaining empty lists and the loop …

Pipe: switch to IdentityHashMap backed set to avoid infinite loop in table tsfile builder

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/util/builder/PipeTreeModelTsFileBuilderV2.java

Pipe: fix potential ClassCastException when casting LocalDate[] in PipeTreeModelTsFileBuilderV2

---

example/udf/src/main/java/org/apache/iotdb/udf/table/RepeatExample.java
integration-test/src/main/java/org/apache/iotdb/db/query/udf/example/relational/MySelectColumn.java
integration-test/src/test/java/org/apache/iotdb/relational/it/db/it/IoTDBWindowTVFIT.java
integration-test/src/test/java/org/apache/iotdb/relational/it/db/it/udf/IoTDBUserDefinedTableFunctionIT.java
iotdb-api/udf-api/src/main/java/org/apache/iotdb/udf/api/relational/table/argument/ScalarArgumentChecker.java
iotdb-api/udf-api/src/main/java/org/apache/iotdb/udf/api/relational/table/processor/TableFunctionDataProcessor.java
iotdb-api/udf-api/src/main/java/org/apache/iotdb/udf/api/relational/table/specification/ScalarParameterSpecification.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/process/function/TableFunctionOperator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/TableOperatorGenerator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/analyzer/StatementAnalyzer.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/plan/function/Repeat.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/udf/builtin/relational/tvf/CapacityTableFunction.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/udf/builtin/relational/tvf/CumulateTableFunction.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/udf/builtin/relational/tvf/HOPTableFunction.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/udf/builtin/relational/tvf/SessionTableFunction.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/udf/builtin/relational/tvf/TumbleTableFunction.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/udf/builtin/relational/tvf/VariationTableFunction.java

1. Add ScalarArgumentChecker 
2. Auto build pass through columns for table function which is not declared with `PASS_THROUGH_COLUMNS` but invoked with `PARTITION BY`. Currently, developers only need to write passThroughIndexBuilder if table function is declared with `PASS_THROUGH_COLUMNS` .

Add ScalarArgumentChecker and auto-built pass through index for TVF

---

integration-test/src/test/java/org/apache/iotdb/relational/it/query/recent/IoTDBTableAggregationIT.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/relational/aggregation/AccumulatorFactory.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/relational/aggregation/ApproxCountDistinctAccumulator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/relational/aggregation/HyperLogLog.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/relational/aggregation/HyperLogLogState.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/relational/aggregation/HyperLogLogStateFactory.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/relational/aggregation/grouped/GroupedApproxCountDistinctAccumulator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/relational/aggregation/grouped/array/BinaryBigArray.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/relational/aggregation/grouped/array/HyperLogLogBigArray.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/relational/aggregation/grouped/array/MapBigArray.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/relational/aggregation/grouped/array/ObjectBigArray.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/metadata/TableMetadataImpl.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/sql/parser/AstBuilder.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/utils/constant/SqlConstant.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/udf/builtin/relational/TableBuiltinAggregationFunction.java
iotdb-protocol/thrift-commons/src/main/thrift/common.thrift

This pull request introduces the `ApproxCountDistinctAccumulator` and its associated classes to support the `APPROX_COUNT_DISTINCT` aggregation function in the IoTDB query engine. The changes include the addition of new classes and modifications to existing factory methods to incorporate the new accumulator.
**New Classes:**
* [`ApproxCountDistinctAccumulator`](diffhunk://#diff-24c6e2b1ec5522790e49b72c6a8fb6c2c7618905a685fa633552ee87709b1200R1-R262): Implements the logic for the `APPROX_COUNT_DISTINCT` aggregation function, including methods for adding input data, merging intermediate results, and evaluating the final result.
* [`HyperLogLog`](diffhunk://#diff-e386b0d69ef98e3c9b262715f258c19fb22e033a82364a7143bfdf3285f1e3b3R1-R265): A probabilistic data structure used by …

Add APPROX_COUNT_DISTINCT Function

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/protocol/pipeconsensus/PipeConsensusSyncConnector.java

as title.
All global client managers should only be closed in `PipeConsensus`

IoTV2: Fix global client manager close by mistake when running

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/consensus/deletion/persist/PageCacheDeletionBuffer.java

We should use `shutdownNow` instead of `shutdown` to send an interruption signal to thread.
Test has shown results as expected:

DAL: Fix thread leak when DN exit.

---

iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/load/balancer/region/GreedyCopySetRegionGroupAllocator.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/load/balancer/region/GreedyRegionGroupAllocator.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/load/balancer/region/IRegionGroupAllocator.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/load/balancer/region/PartiteGraphPlacementRegionGroupAllocator.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/env/RemoveDataNodeHandler.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/node/RemoveDataNodesProcedure.java
iotdb-core/confignode/src/test/java/org/apache/iotdb/confignode/manager/load/balancer/region/GreedyCopySetDestNodeSelectorTest.java
iotdb-core/confignode/src/test/java/org/apache/iotdb/confignode/manager/load/balancer/region/GreedyCopySetRemoveNodeReplicaSelectTest.java

Add region migration dest datanode selection algorithm for load balancing during removing datanode.
Please see https://apache-iotdb-project.feishu.cn/docx/G5aPdZJ4QozqmkxO9dsc7sEsnTe for detail design.

[remove datanode] GCR load balancing implement for removing datanode

---

iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/StateMachineProcedure.java

If the status list is updated during the snapshot process, it will cause parallel read and write errors. This will cause the State Machine Server to showdown.
<hr>
This PR has:
<hr>

Procedure: Fix the concurrency error during StateMachineProcedure snapshot

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/consensus/deletion/persist/PageCacheDeletionBuffer.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/wal/buffer/WALBuffer.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/wal/io/WALInputStream.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/wal/compression/WALCompressionTest.java

After calling `org.apache.iotdb.db.storageengine.dataregion.wal.io.WALInputStream#skipToGivenLogicalPosition`, the compressed buffer is cleaned but not nullified.
As a result, the succinct call of `org.apache.iotdb.db.storageengine.dataregion.wal.io.WALInputStream#loadNextSegmentV2` may use the cleaned buffer and cause memory issues.

Fix memory leak in wal compressed buffer

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/ClusterPartitionFetcher.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/cache/partition/PartitionCache.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/plan/analyze/cache/PartitionCacheTest.java

We found that on physical machines with good configuration, if there are a large number of regions and devices, and each write operation writes only one row of data per device, the PartitionCache's regionLock becomes a bottleneck. Although all operations are using read locks, on a machine with 96 cores and 192 threads, high-concurrency read operations involving CAS (Compare-And-Swap) on a read lock still turn into a bottleneck.
To address this, we batched the logic, reducing the number of times each thread needs to acquire a read lock from region num to just once overall. This eliminated the read lock bottleneck.
* 96C 192 Thread 768GB Memory
* data_region_group_extension_policy=CUSTOM
* default_data_region_group_num_per_database=192
* LOOP=100
* DEVICE_NUMBER=4500000
* SENSOR_NUMBER=2
* …

Optimize partition cache getRegionReplicaSet interface performance by batching

---

iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/env/ConfigNodeProcedureEnv.java

We found that the partition cache is not invalidated for datanodes that are neither "Running" nor "Unknown" when deleting the database. As a result, those applications use the partition cache will eventually hit the dirty cache and incur further errors.
To address this bug, we should invalidate partition cache for all datanodes except the unknown ones when deleting database.

Invalidating partition cache for all datanodes except the unknown ones when deleting database

---

integration-test/src/main/java/org/apache/iotdb/db/query/udf/example/relational/MySplit.java
iotdb-api/udf-api/src/main/java/org/apache/iotdb/udf/api/relational/table/specification/ParameterSpecification.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/execution/config/executor/ClusterConfigTaskExecutor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/analyzer/StatementAnalyzer.java

1. When registering TVF, check parameter case-intensively.
2. When invoking TVF, fill parameter case-intensively.

Check TVF parameter case-intensively during invocation and declaration.

---

iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/rescon/memory/ResourceManagerTest.java

Refactor ResourceManagerTest to make it insensitive to the change of TsFileResource size

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/wal/WALManager.java

Interrupt wal-delete thread when WALManager is closed

---

integration-test/src/test/java/org/apache/iotdb/pipe/it/single/IoTDBPipeAggregateIT.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/processor/aggregate/operator/aggregatedresult/standardstatistics/MaxValueOperator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/processor/aggregate/operator/aggregatedresult/standardstatistics/MinValueOperator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/processor/aggregate/operator/intermediateresult/sametype/numeric/MaxOperator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/processor/aggregate/operator/intermediateresult/sametype/numeric/MinOperator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/processor/aggregate/operator/processor/StandardStatisticsOperatorProcessor.java

https://github.com/apache/iotdb/pull/15459
<hr>
This PR has:
<hr>

[To dev/1.3] Pipe: Added max / min function to aggregate-processor (#15459)

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/receiver/protocol/pipeconsensus/PipeConsensusReceiver.java

as title.
we should update tsFileWriter's lastUsedTime every time it is borrowed.

IoTV2: Fix NPE as tsFileWriter is regarded as a zombie writer and cleaned by mistake.

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/agent/runtime/PipeDataNodeRuntimeAgent.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/event/common/terminate/PipeTerminateEvent.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/conf/CommonConfig.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/config/PipeConfig.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/config/PipeDescriptor.java

https://github.com/apache/iotdb/pull/15465
<hr>
This PR has:
<hr>

[To dev/1.3] Pipe: Enable flushing storage engine after last terminate event reported (#15465)

---

integration-test/src/test/java/org/apache/iotdb/relational/it/query/recent/IoTDBTableAggregationIT.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/relational/aggregation/HyperLogLog.java

This pull request includes a minor but important fix to the `HyperLogLog` class in the `iotdb-core` module. The change ensures that the bounds check for `maxStandardError` is inclusive of the lowest and highest allowed values.
* [`iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/relational/aggregation/HyperLogLog.java`](diffhunk://#diff-e386b0d69ef98e3c9b262715f258c19fb22e033a82364a7143bfdf3285f1e3b3L108-R109): Adjusted the conditional check in the `standardErrorToBuckets` method to use inclusive bounds for `LOWEST_MAX_STANDARD_ERROR` and `HIGHEST_MAX_STANDARD_ERROR`, ensuring correct validation of `maxStandardError`.

fix: Boundary checks for maxStandardError in APPROX_COUNT_DISTINCT.

---

integration-test/src/test/java/org/apache/iotdb/confignode/it/partition/IoTDBPartitionTableAutoCleanUSIT.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/PartitionTableAutoCleaner.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/utils/TimePartitionUtils.java

Currently, the PartitionTableAutoCleaner uses an absolute time position to judge whether a data partition is expired. However, as the time partition interval stored in the ConfigNode can be only configured to "ms" precision, the calculation of the absolute time position is not correct. As a result, we should employ the reference time position.

Use reference time position for PartitionTableAutoCleaner

---

iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/binaryallocator/BinaryAllocator.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/binaryallocator/PooledBinaryPhantomReference.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/binaryallocator/arena/Arena.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/binaryallocator/autoreleaser/Releaser.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/binaryallocator/config/AllocatorConfig.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/binaryallocator/evictor/Evictor.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/concurrent/ThreadName.java
iotdb-core/node-commons/src/test/java/org/apache/iotdb/commons/binaryallocator/BinaryAllocatorTest.java

It's often challenging to properly manage PooledBinary object lifecycles, which can lead to resource leaks or logic errors.
Implemented auto-release mechanism using PhantomReference to automatically return the byte array in PooledBinary to the pool when they become unreachable.
Method changed:
* BinaryAllocator::allocate(int reqCapacity) -> BinaryAllocator::allocate(int reqCapacity, boolean autoRelease)

Implememt auto release technique for Blob Allocator

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/transformation/dag/column/AbstractCaseWhenThenColumnTransformer.java

This pull request includes a minor change to the `doTransform` method in the `AbstractCaseWhenThenColumnTransformer` class. The change ensures proper cache clearing for the `elseTransformer` by moving its `clearCache` call outside the loop for better clarity and correctness.
* **Cache management improvement:**
- [`iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/transformation/dag/column/AbstractCaseWhenThenColumnTransformer.java`](diffhunk://#diff-1cea02ca1c6972693f34174ef72701635fa40779c9ec54c328924d5ca4ef95b3R216-R223): Added a comment explaining the short-circuit evaluation behavior of CaseWhen and adjusted the placement of `elseTransformer.clearCache()` to ensure it is executed after the loop for consistent cache clearing.

CaseWhen :Optimize the code structure and add comments

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/util/PipeTabletEventSorter.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/pipe/connector/PipeTabletEventSorterTest.java

https://github.com/apache/iotdb/pull/15488
<hr>
This PR has:
<hr>

[To dev/1.3] Pipe: Fixed the bug that sorter may use wrong value when there are duplicated timestamps & Refactor (#15488)

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/conf/DataNodeMemoryConfig.java

Datanode cannot start when metaDataCacheEnable=false
```
java.lang.NullPointerException: null
at org.apache.iotdb.db.conf.DataNodeMemoryConfig.initQueryEngineMemoryAllocate(DataNodeMemoryConfig.java:476)
at org.apache.iotdb.db.conf.DataNodeMemoryConfig.init(DataNodeMemoryConfig.java:219)
at org.apache.iotdb.db.conf.IoTDBDescriptor.loadProperties(IoTDBDescriptor.java:311)
at org.apache.iotdb.db.conf.IoTDBDescriptor.loadProps(IoTDBDescriptor.java:229)
at org.apache.iotdb.db.conf.IoTDBDescriptor.<init>(IoTDBDescriptor.java:134)
at org.apache.iotdb.db.conf.IoTDBDescriptor$IoTDBDescriptorHolder.<clinit>(IoTDBDescriptor.java:2648)
at org.apache.iotdb.db.conf.IoTDBDescriptor.getInstance(IoTDBDescriptor.java:166)
at org.apache.iotdb.db.service.DataNode.<clinit>(DataNode.java:142)
```

Datanode cannot start when metaDataCacheEnable=false

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/agent/task/builder/PipeDataNodeTaskBuilder.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/agent/task/connection/PipeEventCollector.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/subscription/broker/SubscriptionPrefetchingTsFileQueue.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/subscription/event/batch/SubscriptionPipeTsFileEventBatch.java

Subscription: fully managed tsfile parsing process for tsfile format topic

---

example/mqtt-customize/src/main/java/org/apache/iotdb/mqtt/server/CustomizedJsonPayloadFormatter.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/mqtt/JSONPayloadFormatter.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/mqtt/LinePayloadFormatter.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/mqtt/MPPPublishHandler.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/mqtt/PayloadFormatter.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/protocol/mqtt/JSONPayloadFormatterTest.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/protocol/mqtt/LinePayloadFormatterTest.java

Enable the kernel to support passing topics to MQTT custom plugins.

Enable the kernel to support passing topics to MQTT custom plugins

---

integration-test/src/main/java/org/apache/iotdb/it/env/cluster/node/DataNodeWrapper.java

ConfigNodeWrapper set Timezone but not in DataNodeWrapper.
https://github.com/apache/iotdb/blob/a5e7d7b30c993c0657566f817e84f767656b4c23/integration-test/src/main/java/org/apache/iotdb/it/env/cluster/node/ConfigNodeWrapper.java#L108-L116

Fix DataNodeWrapper didn't set Timezone

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/scheduler/load/LoadTsFileScheduler.java

(cherry picked from commit 417ddd0becd8f85103d0776d47450f9936241e86)

[To dev/1.3] Load: fix memory leak when failed to send chunk data in first phase

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/LogicalPlanVisitor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/planner/RelationPlanner.java

Fix the problem of null pointer below: 
sql覆盖 IoTV2 3副本 DN
NullPointerException: Cannot invoke "org.apache.tsfile.write.schema.MeasurementSchema.serializeTo(java.io.OutputStream)" because "this.measurementSchemas[i]" is null
`
2025-05-06 13:19:02,468 [pool-35-IoTDB-into-operation-executor-2] ERROR o.a.i.d.u.ErrorHandlingUtils:67 - Status code: EXECUTE_STATEMENT_ERROR(301), operation: insertTablets failed
java.lang.NullPointerException: Cannot invoke "org.apache.tsfile.write.schema.MeasurementSchema.serializeTo(java.io.OutputStream)" because "this.measurementSchemas[i]" is null
at org.apache.iotdb.db.queryengine.plan.planner.plan.node.write.InsertTabletNode.writeMeasurementsOrSchemas(InsertTabletNode.java:502)
at org.apache.iotdb.db.queryengine.plan.planner.plan.node.write.InsertTabletNode. …

Fix null pointer exception casued by measurements values and measureSchemas values are not consistent

---

integration-test/src/test/java/org/apache/iotdb/db/it/IoTDBSetConfigurationIT.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/cache/partition/PartitionCache.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/utils/ErrorHandlingUtils.java

In the conf/iotdb-system.properties files, add these configs below
default_storage_group_level=2 
enable_audit_log=true 
Start up 1C1D, enter CLI
```
Starting IoTDB Cli
 _____       _________  ______   ______    
|_   _|     |  _   _  ||_   _ `.|_   _ \   
  | |   .--.|_/ | | \_|  | | `. \ | |_) |  
  | | / .'`\ \  | |      | |  | | |  __'.  
 _| |_| \__. | _| |_    _| |_.' /_| |__) | 
|_____|'.__.' |_____|  |______.'|_______/  version 1.3.3-SNAPSHOT (Build: 16c2856)
                                           Successfully login at 127.0.0.1:6667
IoTDB> create timeseries root.db.s1 with datatype=INT32;
Msg: org.apache.iotdb.jdbc.IoTDBSQLException: 305: [INTERNAL_SERVER_ERROR(305)] Exception occurred: "create timeseries root.db.s1 with datatype=INT32". executeStatement …
```

[To dev/1.3] Correct error messages when encountered IllegalPathException

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/receiver/protocol/pipeconsensus/PipeConsensusReceiver.java

as title. 
In one case, we found that one region receiver's pending tsFileEvent num has reached an unexpected `66` value, which is far greater than receiver's buffer len `5`.
This case is caused by buffer reset. We need to reset event counter as well when we clear buffer

IoTV2: Reset receiver's metric when clear receiver's buffer

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/service/DataNode.java

Make it easier for users to extend ClientRPCServiceImpl to export more rpc services.
After being merged, others only need to extend ClientRPCServiceImpl  and then implement customized rpc interfaces and then override `protected String getClientRPCServiceImplClassName()`

Make it easier for users to extend ClientRPCServiceImpl to export more rpc services

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/subscription/event/batch/SubscriptionPipeTsFileEventBatch.java

As title.
Consider the historical data export snapshot scenario
1. The events delivered upstream are, in order, the tsfile event and the termination event.  
2. The tsfile event is parsed into multiple tablet events, and then the reference count of the tsfile event is set to 0 (should report as false).  
3. Assuming that for some reason the tablet events were not sent to the peer in time, the reference count of the transfer termination event is set to 0 (should report as true).  
4. At this point, because the tablet events were not enriched with a commit id (see #15524), the termination event successfully marks the corresponding DR complete, which in turn leads to data loss.

Subscription: retain tsfile events in tsfile batch to avoid premature commit

---

integration-test/src/test/java/org/apache/iotdb/subscription/it/triple/treemodel/regression/pullconsumer/mode/IoTDBSnapshotDevicePullConsumerDataSetIT.java
iotdb-client/service-rpc/src/main/java/org/apache/iotdb/rpc/subscription/payload/response/PipeSubscribeHeartbeatResp.java
iotdb-client/session/src/main/java/org/apache/iotdb/session/subscription/consumer/base/AbstractSubscriptionProviders.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/subscription/agent/SubscriptionBrokerAgent.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/subscription/broker/SubscriptionBroker.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/subscription/receiver/SubscriptionReceiverV1.java

Subscription: support unsubscribe from completed topics under client heartbeat thread

---

integration-test/src/test/java/org/apache/iotdb/ainode/it/AINodeBasicIT.java
integration-test/src/test/java/org/apache/iotdb/relational/it/schema/IoTDBDatabaseIT.java
iotdb-core/ainode/ainode/core/constant.py
iotdb-core/ainode/ainode/core/model/built_in_model_factory.py
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/persistence/ModelInfo.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/function/tvf/ForecastTableFunction.java

[AINode] Add Holt-Winters algorithm and fix related bugs

---

integration-test/src/test/java/org/apache/iotdb/relational/it/schema/IoTDBDatabaseIT.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/persistence/ModelInfo.java

[AINode] Remove TimerXL from the builtin list

---

iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/pipe/metric/overview/PipeConfigNodeRemainingTimeOperator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/metric/overview/PipeDataNodeRemainingEventAndTimeOperator.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/conf/CommonConfig.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/enums/PipeRateAverage.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/config/PipeConfig.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/config/PipeDescriptor.java

Pipe: Unbinded the default meter for remaining insertion event count for hybrid degrading & Changed some default values of related properties

---

integration-test/src/test/java/org/apache/iotdb/relational/it/query/view/old/alignbydevice/IoTDBAlignByDeviceTableViewIT.java
integration-test/src/test/java/org/apache/iotdb/relational/it/query/view/old/alignbydevice/IoTDBOrderByWithAlignByDeviceTableViewIT.java
integration-test/src/test/java/org/apache/iotdb/relational/it/query/view/recent/IoTDBTableViewQueryWithNotMatchedDataTypeIT.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/utils/ResourceByPathUtils.java

Ignore mem chunks whose data type is not matched

Ignore mem chunks whose data type is not matched

---

integration-test/src/test/java/org/apache/iotdb/relational/it/query/view/recent/IoTDBTableViewQueryIT.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/planner/distribute/TableDistributedPlanGenerator.java

Skip generate distributed plan when treeDBName is null

Skip generate distributed plan when treeDBName is null

---

integration-test/src/test/java/org/apache/iotdb/relational/it/query/view/recent/IoTDBTableViewQueryWithNotMatchedDataTypeIT.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/utils/ResourceByPathUtils.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/memtable/AlignedWritableMemChunk.java

When the queried aligned series has some inconsistent types in memtable, the other column will also be ignored.  Related previous PR is https://github.com/apache/iotdb/pull/15617.

When the queries aligned series has some inconsistent data types in memtable, the other column will also be ignored

---

iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/load/balancer/region/GreedyCopySetRegionGroupAllocator.java
iotdb-core/confignode/src/test/java/org/apache/iotdb/confignode/manager/load/balancer/region/GreedyCopySetRemoveNodeReplicaSelectTest.java

Accelerate the algorithm by pre-calculating, sorting, pruning and batching DFS.
Timeout
Able to handle five-node and one-hundred-region scenarios within milliseconds.

[remove datanode] Accelerate GCR load balancing implement

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/relational/LastQueryAggTableScanOperator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/TableOperatorGenerator.java

let last cache hit, even if any sensor of one device is null in last row

Revert "Fix process of last query if intermediate state of last cache is read when query concurrently

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/plan/node/write/InsertRowNode.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/plan/node/write/InsertTabletNode.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/wal/buffer/WALEntry.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/wal/io/WALInputStream.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/wal/utils/WALEntryPosition.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/wal/utils/WALPrintTool.java
scripts/tools/wal/print-wal.sh
scripts/tools/windows/wal/print-wal.bat

https://timechor.feishu.cn/docx/NapddOuCcoEtx6xRz1rcswSdnYb

Add print-wal tool and logs when failures of reading wal files

---

iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/iot/logdispatcher/Batch.java
iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/iot/logdispatcher/LogDispatcher.java
iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/iot/logdispatcher/SyncStatus.java
iotdb-protocol/thrift-consensus/src/main/thrift/iotconsensus.thrift

The actual memory occupied by IoTConsensus is 2-3 times larger than the statistical memory of memory management, so more detailed statistics of consensus memory are needed.
As shown in the figure, the statistical result of using getMemorySize is about twice the size of buffer, which makes the result more accurate.

[IoTConsensus] More accurate statistics on IoTConsensus memory management 

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/protocol/pipeconsensus/PipeConsensusAsyncConnector.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/protocol/pipeconsensus/handler/PipeConsensusDeleteEventHandler.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/protocol/pipeconsensus/handler/PipeConsensusTabletInsertionEventHandler.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/protocol/pipeconsensus/handler/PipeConsensusTsFileInsertionEventHandler.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/event/realtime/PipeRealtimeEventFactory.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/extractor/dataregion/historical/PipeHistoricalDataRegionTsFileAndDeletionExtractor.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/event/EnrichedEvent.java

IoTV2: Remove events that do not retry in leader's transfer buffer & fix concurrency bug of retryQueue & fix retry interval & refine log

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/subscription/receiver/SubscriptionReceiverV1.java

cherry-pick #15660 to https://github.com/apache/iotdb/tree/dev/1.3

[To dev/1.3] Subscription: unsubscribe completed topics when remove consumer config (#15660)

---

integration-test/src/test/java/org/apache/iotdb/subscription/it/Retry.java
integration-test/src/test/java/org/apache/iotdb/subscription/it/RetryRule.java
integration-test/src/test/java/org/apache/iotdb/subscription/it/triple/regression/pushconsumer/mode/IoTDBSnapshotTSPatternDatasetPushConsumerIT.java
integration-test/src/test/java/org/apache/iotdb/subscription/it/triple/regression/pushconsumer/mode/IoTDBSnapshotTSPatternTsfilePushConsumerIT.java
integration-test/src/test/java/org/apache/iotdb/subscription/it/triple/regression/pushconsumer/multi/IoTDBOneConsumerMultiTopicsTsfileIT.java

cherry-pick #15698 to https://github.com/apache/iotdb/tree/dev/1.3

[To dev/1.3] Subscription IT: intro retry rule for flaky tests (#15698)

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/OperatorTreeGenerator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/distribution/SourceRewriter.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/plan/planner/distribution/AggregationAlignByDeviceTest.java

cp https://github.com/apache/iotdb/pull/15723

[To dev/1.3]Support order by time for Agg align by device query with cross region data

---

iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/load/balancer/region/GreedyCopySetRegionGroupAllocator.java
iotdb-core/confignode/src/test/java/org/apache/iotdb/confignode/manager/load/balancer/region/GreedyCopySetRemoveNodeReplicaSelectTest.java

The replicaSets used in `computeInitialDbLoad` come from `databaseAllocatedRegionGroupMap`, and the removed datanode ID need to be excluded.

[remove datanode] Fix ArrayIndexOutOfBoundsException in computeInitialDbLoad

---

integration-test/src/test/java/org/apache/iotdb/relational/it/query/view/recent/IoTDBTableViewQueryIT.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/TableOperatorGenerator.java

Using join to query views of non-aligned series may throw NullPointerException
```
2025-06-04 17:35:38,451 [pool-33-IoTDB-DataNodeInternalRPC-Processor-128$20250604_093526_10262_6.6.0] WARN  o.a.i.d.q.e.f.FragmentInstanceManager:202 - error when create FragmentInstanceExecution.
java.lang.NullPointerException: Cannot invoke "java.util.List.get(int)" because the return value of "java.util.Map.get(Object)" is null
at org.apache.iotdb.db.queryengine.execution.relational.ColumnTransformerBuilder.lambda$visitSymbolReference$17(ColumnTransformerBuilder.java:1280)
at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
at org.apache.iotdb.db.queryengine.execution.relational.ColumnTransformerBuilder.visitSymbolReference(ColumnTransformerBuilder.java:1276)
at …
```

Using join to query views of non-aligned series may throw NullPointerException

---

iotdb-core/node-commons/src/assembly/resources/conf/iotdb-system.properties.template

Conf Template: Fix wrong symbol

---

integration-test/src/test/java/org/apache/iotdb/confignode/it/removeconfignode/IoTDBRemoveConfigNodeITFramework.java
integration-test/src/test/java/org/apache/iotdb/confignode/it/removedatanode/IoTDBRemoveDataNodeNormalIT.java
integration-test/src/test/java/org/apache/iotdb/confignode/it/removedatanode/IoTDBRemoveDataNodeUtils.java
integration-test/src/test/java/org/apache/iotdb/confignode/it/removedatanode/IoTDBRemoveUnknownDataNodeIT.java
integration-test/src/test/java/org/apache/iotdb/confignode/it/utils/ConfigNodeTestUtils.java
iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/pipe/PipeConsensusServerImpl.java

To make our project more robustness, in this PR, we:
1. Create integration tests with remove datanode & IoTV2 consensus protocol.
2. Setup test cases for removing a unknown DataNode.

Add more tests for removing datanode

---

integration-test/src/test/java/org/apache/iotdb/relational/it/query/recent/IoTDBTableAggregationIT.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/sql/parser/AstBuilder.java

This pull request refines the validation logic for the `approx_most_frequent` function in the SQL parser. The primary change ensures that the second and third arguments are explicitly validated as positive integer literals, improving clarity and correctness.
* In `AstBuilder.java`, updated the validation logic for the `approx_most_frequent` function to check that the second and third arguments are positive integer literals (`LongLiteral`) when three arguments are provided. This replaces the previous generic numeric literal check.
* Removed the `isNumericLiteral` helper method, as it is no longer used following the updated validation logic.

Improve argument validation for approx_most_frequent function

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/fragment/FragmentInstanceContext.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/schedule/DriverScheduler.java

(cherry picked from commit e7d009cb725c1c030820da4415c7f08e6b742245)

[To dev/1.3] Correct Block Queue Time metric

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/TableOperatorGenerator.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/execution/operator/NonAlignedTreeDeviceViewScanOperatorTreeTest.java

Fixed the issue with deeply nested Or Filter in NonAlignedTreeViewScan

Fixed the issue with deeply nested Or Filter in NonAlignedTreeViewScan

---

iotdb-core/antlr/src/main/antlr4/org/apache/iotdb/db/qp/sql/IoTDBSqlParser.g4
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/ConfigManager.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/execution/config/TableConfigTaskVisitor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/execution/config/TreeConfigTaskVisitor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/execution/config/executor/ClusterConfigTaskExecutor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/execution/config/executor/IConfigTaskExecutor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/execution/config/metadata/ai/CreateTrainingTask.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/parser/ASTVisitor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/sql/ast/CreateTraining.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/sql/parser/AstBuilder.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/statement/metadata/model/CreateTrainingStatement.java
iotdb-core/relational-grammar/src/main/antlr4/org/apache/iotdb/db/relational/grammar/sql/RelationalSql.g4
iotdb-protocol/thrift-ainode/src/main/thrift/ainode.thrift
iotdb-protocol/thrift-confignode/src/main/thrift/confignode.thrift

In this PR, we remove the useless "model_type" identifier in the CREATE MODEL SQL for model training

[AINode] Simplify the CREATE MODEL SQL for model training

---

integration-test/src/test/java/org/apache/iotdb/relational/it/db/it/IoTDBWindowFunctionIT.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/process/window/TableWindowOperator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/process/window/partition/PartitionExecutor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/planner/optimizations/SymbolMapper.java

This PR fix two bugs in window function:
- *Index out of partition bound*: this is caused by multiple partitions sharing the same window function instance, as well as their frames states. For efficiency purpose, frames do not re-caclulate for each iteration. They may remove some data if the frame shrinks, which may cause IndexOutOfPartitionBoundError.
- *Symbol not found*: window functions need OrderBy channels. The OrderBy symbols are added at QueryPlan stage, and would be looked up their channel by child operator's outputs' layout in OperatorGenerate stage. However, the symbols generate by child operator would be optimized by UnaliasSymbolReferences pass, and the window functions do not optimized their symbols in this pass.

Resolve IndexOutOfPartitionBound and symbol not found in window functions.

---

iotdb-core/ainode/ainode/core/model/model_storage.py

Support for loading, saving, and registering user-defined models.
Completed the TODO parts in `ModelStorage`, including `_retrieve_user_defined_models` and `load_model` / `save_model` logic.

[AINode] Fix bug that AINode cannot register and invoke user_defined model

---

iotdb-core/ainode/ainode/core/ingress/dataset.py
iotdb-core/ainode/ainode/core/ingress/iotdb.py

In this PR, we add a new parameter `window_step` for AINode's dataset, since the adjacent time series data window are tend to similar.

[AINode] Add window_step options for dataset

---

iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/conf/CommonConfig.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/config/PipeConfig.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/config/PipeDescriptor.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/connector/payload/thrift/request/PipeTransferCompressedReq.java

cherry-pick #15699  to https://github.com/apache/iotdb/tree/dev/1.3

[To dev/1.3] Pipe: Add upper bound check for Pipe request decompression buffer (#15699)

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/mqtt/MPPPublishHandler.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/execution/config/executor/ClusterConfigTaskExecutor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/service/MQTTService.java

Disable the parameter 'ALLOW_ZERO-BYTE_CITE_SIDED_PROPERTY1 NAME' and fix null pointer exception.

Disable the parameter 'ALLOW_ZERO-BYTE_CITE_SIDED_PROPERTY1 NAME' and fix null pointer exception.

---

iotdb-core/ainode/ainode/core/ingress/iotdb.py

Fix a small bug that the tree model dataset does not convert the result into torch.tensor when first invoked

[AINode] IoTDBTreeModelDataset bug fix

---

integration-test/src/test/java/org/apache/iotdb/confignode/it/IoTDBConfigNodeSnapshot2IT.java
integration-test/src/test/java/org/apache/iotdb/confignode/it/IoTDBConfigNodeSnapshotIT.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/persistence/TriggerInfo.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/persistence/UDFInfo.java

cp https://github.com/apache/iotdb/pull/15879

[To dev/1.3] Fix dead lock when take snapshot for Trigger and UDF

---

iotdb-core/ainode/ainode/core/exception.py
iotdb-core/ainode/ainode/core/model/built_in_model_factory.py
iotdb-core/ainode/ainode/core/model/model_storage.py

+ Fix the bug that the built-in model be deleted
+ Fix bug that holtwinter cannot be loaded

[AINode] Fix the bug that the built-in model be deleted

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/agent/task/PipeDataNodeTaskAgent.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/service/DataNodeShutdownHook.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/agent/task/meta/PipeRuntimeMeta.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/agent/task/meta/PipeTaskMeta.java

(cherry picked from commit e227a53a726e2401de7924df15face54f6a31c95)

[To dev/1.3] Pipe/IoTV2: Persist progress index locally before shutdown to accurate recovery after restart (#15779)

---

iotdb-core/ainode/ainode/core/config.py
iotdb-core/ainode/ainode/core/constant.py
iotdb-core/ainode/ainode/core/handler.py
iotdb-core/ainode/ainode/core/manager/inference_manager.py
iotdb-core/ainode/ainode/core/manager/model_manager.py
iotdb-core/ainode/ainode/core/model/model_storage.py
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/ModelManager.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/model/DropModelProcedure.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/client/ainode/AINodeClient.java
iotdb-protocol/thrift-ainode/src/main/thrift/ainode.thrift

This PR fixes the following bugs:
1. The SQL `show models <model_id>` is invalid.
2. Unify the lifecycle of user-defined models, corresponding to our state machine.

[AINode] Fix model management bugs

---

example/session/src/main/java/org/apache/iotdb/TableModelSessionPoolExample.java
iotdb-client/isession/src/main/java/org/apache/iotdb/isession/ITableSession.java
iotdb-client/session/src/main/java/org/apache/iotdb/session/Session.java
iotdb-client/session/src/main/java/org/apache/iotdb/session/SessionConnection.java
iotdb-client/session/src/main/java/org/apache/iotdb/session/TableSession.java
iotdb-client/session/src/main/java/org/apache/iotdb/session/pool/TableSessionWrapper.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/thrift/impl/ClientRPCServiceImpl.java
iotdb-protocol/thrift-datanode/src/main/thrift/client.thrift

In this PR, we create a new session interface `fetchDeviceLeader`. The user can get the device leader's DataNode client RPC location through inputing `databaseName, deviceName, time`. This interface is self-tested, we left the test codes in TableModelSessionPoolExample. You can find following results after executing the test codes:
Correct device leader URL: 0.0.0.0:6667
Error dbName device leader URL: :
Error deviceId device leader URL: :
Error time device leader URL: :

Support fetch the device's leader through corresponding database and time

---

example/session/src/main/java/org/apache/iotdb/TableModelSessionPoolExample.java
iotdb-client/isession/src/main/java/org/apache/iotdb/isession/ITableSession.java
iotdb-client/session/src/main/java/org/apache/iotdb/session/Session.java
iotdb-client/session/src/main/java/org/apache/iotdb/session/TableSession.java
iotdb-client/session/src/main/java/org/apache/iotdb/session/pool/TableSessionWrapper.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/thrift/impl/ClientRPCServiceImpl.java
iotdb-protocol/thrift-datanode/src/main/thrift/client.thrift

Plz refer the usage from `TableModelSessionPoolExample`:
Correct device leader URL: 0.0.0.0:6667
Error dbName device leader URL: :
Error deviceId device leader URL: :
Error tag device leader URL: :
Error time device leader URL: :

Support null tag for device fetch leader interface

---

iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/pipe/connector/protocol/IoTDBConfigRegionConnector.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/agent/task/subtask/connector/PipeConnectorSubtask.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/client/IoTDBDataNodeAsyncClientManager.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/protocol/thrift/async/IoTDBDataRegionAsyncConnector.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/protocol/thrift/async/handler/PipeTransferTrackableHandler.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/protocol/thrift/async/handler/PipeTransferTsFileHandler.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/client/ClientManager.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/client/async/AsyncPipeDataTransferServiceClient.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/connector/client/IoTDBSyncClientManager.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/connector/protocol/IoTDBSslSyncConnector.java

This pull request introduces several changes across multiple files to improve connection management, enhance error handling, and ensure proper resource cleanup. The most notable updates include replacing direct `clientManager` calls with a `getClientManager()` method for safer access, adding checks to prevent operations after closure, and improving logging for debugging purposes.
* [`iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/connector/protocol/IoTDBSslSyncConnector.java`](diffhunk://#diff-571e6f3b28edec52b9532e699c7564cf00f1700f3178264b7d94b2fd63b4ce67L69-R76): Replaced direct `clientManager` access with a `getClientManager()` method that throws an exception if the client manager is closed, ensuring safer access.
* …

Pipe: Fix connection leak caused by clients not closed after task dropped (2 situations)

---

example/session/src/main/java/org/apache/iotdb/TableModelSessionPoolExample.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/thrift/impl/ClientRPCServiceImpl.java

In this PR, we replace the `getDataPartition` with `getOrCreateDataPartition` when executing FetchDeviceLeader. As a result, the behavior of this interface is as follows:
1. Return the corresponding region leader when both database and data partition are existed. Correct device leader URL: 0.0.0.0:6667
2. Throw `StatementExecutionException` when database not existed. 301: Failed to fetch device leader: An error occurred when executing getOrCreateDataPartition():Create DataPartition failed because the database: test3 is not exists
3. Automatically create a new data partition when the specified deviceId does not exist. Error deviceId device leader URL: 0.0.0.0:6667
4. Automatically create a new data partition when the specified deviceId does not exist. Error tag device leader URL: …

Use getOrCreateDataPartition when executing FetchDeviceLeader

---

pom.xml

Bumps org.apache.commons:commons-lang3 from 3.13.0 to 3.18.0.
Fixing CVE-2025-48924

[To dev/1.3] Bump org.apache.commons:commons-lang3 from 3.13.0 to 3.18.0 

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/AbstractSeriesAggregationScanOperator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/AbstractSeriesScanOperator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/SeriesScanUtil.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/utils/reader/SeriesDataBlockReader.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/read/reader/series/AlignedSeriesScanLimitOffsetPushDownTest.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/read/reader/series/AlignedSeriesScanPredicatePushDownTest.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/read/reader/series/AlignedSingleColumnSeriesScanLimitOffsetPushDownTest.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/read/reader/series/SeriesReaderTestUtil.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/read/reader/series/SeriesScanLimitOffsetPushDownTest.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/read/reader/series/SeriesScanPredicatePushDownTest.java

https://github.com/apache/iotdb/pull/15856

[to dev/1.3] Add more checkpoints in series scan

---

.github/workflows/multi-language-client.yml

The runner of windows-2019 is retired. https://github.com/actions/runner-images?tab=readme-ov-file

Remove CI on windows-2019

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/SchemaEngine.java

We found that the schemaRegionMap in a DataNode might be null when it is shutting down while the cluster is migrating regions. This is because the schemaRegionMap is cleared and our cluster wants to create a new schema region in this DataNode. To avoid this NPE, we:
1. Synchronize the schema region creation and clear process.
2. Throw a `MetadataException` to indicate that the DataNode is closing.

Avoid NPE while stop DN

---

iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/pipe/connector/protocol/IoTDBConfigRegionConnector.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/agent/task/subtask/connector/PipeConnectorSubtask.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/client/IoTDBDataNodeAsyncClientManager.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/protocol/thrift/async/IoTDBDataRegionAsyncConnector.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/protocol/thrift/async/handler/PipeTransferTrackableHandler.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/protocol/thrift/async/handler/PipeTransferTsFileHandler.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/client/ClientManager.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/client/async/AsyncPipeDataTransferServiceClient.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/connector/protocol/IoTDBSslSyncConnector.java

(cherry picked from commit bf8329b15179bead9bb50c731274fae3dad816e9)

[To dev/1.3] Pipe: Fix connection leak caused by clients not closed after task dropped (2 situations) (#15910)

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/load/splitter/TsFileSplitter.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/compaction/BatchedCompactionWithTsFileSplitterTest.java

Fix the handling of empty value chunk when load splitting time partitions

Fix the handling of empty value chunk when load splitting time partitions

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/extractor/dataregion/realtime/assigner/PipeDataRegionAssigner.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/resource/tsfile/PipeTsFileResourceManager.java

[To dev/1.3] Pipe: Fixed hard-link problem (#15984)

---

integration-test/src/test/java/org/apache/iotdb/db/it/IoTDBRestartRatisIT.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/service/DataNodeShutdownHook.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/rescon/memory/AbstractPoolManager.java

When using Ratis as the data region consensus, during stopping a datanode, concurrent Ratis requests may trigger a snapshot after the FlushManager is closed.
As a result, the snapshot process cannot submit flush tasks and is stuck there.
To fix this, if any flush task is submitted after the flush manager is closed, we will use the common pool to execute it.

Fix that stopping ratis may get stuck due to closed FlushManager

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/extractor/dataregion/realtime/PipeRealtimeDataRegionHybridExtractor.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/conf/CommonConfig.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/config/PipeConfig.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/config/PipeDescriptor.java

[To dev/1.3] Pipe: Simplified the hybrid down-grading logic

---

integration-test/src/main/java/org/apache/iotdb/it/env/cluster/env/AbstractEnv.java
integration-test/src/main/java/org/apache/iotdb/it/env/cluster/node/AINodeWrapper.java

We add cluster_ingress_port to AINodeWrapper, so that the AINode can fetch data from DataNode in the CI environment

[AINode] Add cluster_ingress_port for AINodeWrapper

---

iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/load/cache/LoadCache.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/load/cache/detector/PhiAccrualDetector.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/ClusterTopology.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/plan/AbstractFragmentParallelPlanner.java

We found that the topology service will throw a NPE at AbstractFragmentParallelPlanner, when the query target region replica set is unreachable. The reason leads to this issue is passing the wrong replica set. This PR fixes this NPE, while appending more logs for cluster topology service. As a result, log will be recorded to each node as long as the topology status changed.

Address NPE cause by topology service

---

integration-test/src/test/java/org/apache/iotdb/relational/it/db/it/IoTDBCaseWhenThenTableIT.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/planner/IrTypeAnalyzer.java
pom.xml

This pull request introduces improvements to error handling and testing for CASE expressions in the IoTDB query engine. The changes ensure stricter type validation for CASE expressions and enhance test coverage for edge cases.
* [`iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/planner/IrTypeAnalyzer.java`](diffhunk://#diff-13930271f6daa99066c9dfe57eb9ba951f2d76eadbefc9523851080ecbaca476L244-R247): Replaced `checkArgument` with a more descriptive `SemanticException` to provide clearer error messages when CASE expression result types are not consistent in both `visitSearchedCaseExpression` and `visitSimpleCaseExpression` methods. [[1]](diffhunk://#diff-13930271f6daa99066c9dfe57eb9ba951f2d76eadbefc9523851080ecbaca476L244-R247) …

Fix wrong status code of case when

---

integration-test/src/test/java/org/apache/iotdb/confignode/it/regionmigration/pass/commit/IoTDBRegionReconstructForIoTV1IT.java

The resultSet might be empty at the end of this test, due to the reconstruction is not fully finished yet. Therefore, we should append a judgement.

Enhance the robustness of  IoTDBRegionReconstructForIoTV1IT

---

integration-test/src/test/java/org/apache/iotdb/relational/it/db/it/IoTDBWindowTVFIT.java

This pull request makes a small change to the `integration-test/src/test/java/org/apache/iotdb/relational/it/db/it/IoTDBWindowTVFIT.java` file. The change sets the sort buffer size to `512 * 1024` in the `setUp` method to configure the environment before running tests.

Allocate less sort memory for IoTDBWindowTVFIT to avoid CI failed occationally

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/rest/table/v1/impl/RestApiServiceImpl.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/rest/v1/impl/RestApiServiceImpl.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/rest/v2/impl/RestApiServiceImpl.java

RestAPI remove getCurrSessionAndUpdateIdleTime, because RestAPI is not a long connection

RestAPI remove getCurrSessionAndUpdateIdleTime

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/agent/task/subtask/sink/PipeSinkSubtask.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/agent/task/subtask/sink/PipeSinkSubtaskLifeCycle.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/agent/task/subtask/PipeAbstractSinkSubtask.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/agent/task/subtask/PipeReportableSubtask.java

[To dev/1.3] Pipe: Fix the stuck state caused by unfair lock in Sink start phase (#16100)

---

integration-test/src/test/java/org/apache/iotdb/session/it/IoTDBSessionCompressedIT.java
iotdb-client/session/src/main/java/org/apache/iotdb/session/util/SessionUtils.java

To increase encoding efficiency, when encoding nulls in a Tablet, the previous value will be used as the placeholder for nulls.
When the previous value itself is null, an exception will be raised.
Instead of using the previous value, the last non-null value (or a default value if none exists) is used as the placeholder.

Fix NPE when encoding continous nulls in Tablets

---

integration-test/src/test/java/org/apache/iotdb/pipe/it/manual/IoTDBPipeTypeConversionISessionIT.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/receiver/visitor/PipeStatementDataTypeConvertExecutionVisitor.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/conf/CommonConfig.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/config/PipeConfig.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/config/PipeDescriptor.java
pom.xml

[To dev/1.3] Pipe: Totally banned the receiver conversion (#16086)

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/metric/overview/PipeDataNodeRemainingEventAndTimeOperator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/metric/overview/PipeDataNodeSinglePipeMetrics.java

[To dev/1.3] Pipe: Delete the heartbeat event count in Remaining Count #16115

---

iotdb-client/client-cpp/src/main/IoTDBRpcDataSet.cpp
iotdb-client/client-cpp/src/main/IoTDBRpcDataSet.h
iotdb-client/client-cpp/src/test/cpp/sessionRelationalIT.cpp

Fix getTimestampByIndex to use boost::optional for non-first-column timestamps

fix cpp-client-gettimestamp

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/tsfile/generator/TsFileNameGenerator.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/rescon/disk/FolderManagerTest.java

The issue occurs because mkdirs() fails silently - it returns false rather than throwing an IOException when unable to create directories.
```
try {
return folderManager.getNextWithRetry(
baseDir -> {
String tsFileDir =
baseDir
+ File.separator
+ logicalStorageGroup
+ File.separator
+ virtualStorageGroup
+ File.separator
+ timePartitionId;
fsFactory.getFile(tsFileDir).mkdirs();
return tsFileDir
+ File.separator
+ generateNewTsFileName(
time,
version,
innerSpaceCompactionCount,
crossSpaceCompactionCount,
customSuffix);
});
} catch (DiskSpaceInsufficientException e) {
LOGGER.error("All disks are full, cannot create tsfile directory", e);
throw new IOException("Disk space insufficient", e);
} catch (Exception e) {
LOGGER.warn("Failed to create tsfile directory after retries", e);
throw new …
```

fix: Failed to remove unwritable directories when creating tsfile

---

integration-test/src/main/java/org/apache/iotdb/it/env/cluster/config/MppCommonConfig.java
integration-test/src/main/java/org/apache/iotdb/it/env/cluster/config/MppSharedCommonConfig.java
integration-test/src/main/java/org/apache/iotdb/it/env/remote/config/RemoteCommonConfig.java
integration-test/src/main/java/org/apache/iotdb/itbase/env/CommonConfig.java
integration-test/src/test/java/org/apache/iotdb/db/it/orderBy/IoTDBOrderByIT.java
integration-test/src/test/java/org/apache/iotdb/relational/it/db/it/IoTDBAsofJoinTableIT.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/plan/node/PlanGraphPrinter.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/plan/node/source/LastQueryScanNode.java

This pull request introduces a new configuration option for setting the DataNode memory proportion, updates related interfaces and test setups to use this option, and refines a utility import in the query engine code. The main changes add the new `setDataNodeMemoryProportion` method to configuration classes and update test classes to utilize this new setting, while also cleaning up a dependency in the `LastQueryScanNode` class.
Configuration enhancements:
* Added the `setDataNodeMemoryProportion` method to the `CommonConfig` interface and its implementations (`MppCommonConfig`, `MppSharedCommonConfig`, `RemoteCommonConfig`) to allow setting DataNode memory proportions programmatically. [[1]](diffhunk://#diff-adc438fd7a7c566e75afd7ed2abfb2d5ad8c2fc50be94494ecf3e08a48f52f29R175-R176) …

Change IT configuration to make CI more stable

---

integration-test/src/test/java/org/apache/iotdb/db/it/schema/IoTDBCreateTimeseriesIT.java
pom.xml

Temporarily banned some PBTree IT to avoid CI failure

---

integration-test/src/test/java/org/apache/iotdb/db/it/orderBy/IoTDBOrderBy2IT.java
integration-test/src/test/java/org/apache/iotdb/db/it/orderBy/IoTDBOrderByForDebugIT.java
integration-test/src/test/java/org/apache/iotdb/db/it/orderBy/IoTDBOrderByIT.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/common/MPPQueryContext.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/common/schematree/ClusterSchemaTree.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/common/schematree/ISchemaTree.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/common/schematree/node/SchemaEntityNode.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/common/schematree/node/SchemaInternalNode.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/common/schematree/node/SchemaMeasurementNode.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/common/schematree/node/SchemaNode.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/schema/SchemaFetchScanOperator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/AnalyzeVisitor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/Analyzer.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/schema/ClusterSchemaFetchExecutor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/template/Template.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/execution/operator/schema/SchemaFetchScanOperatorTest.java
pom.xml

https://github.com/apache/iotdb/pull/16035

[to dev/1.3] Transfer schema tree in batches & add memory control for schema tree

---

iotdb-client/session/src/main/java/org/apache/iotdb/session/Session.java
iotdb-client/session/src/test/java/org/apache/iotdb/session/SessionTest.java

NodeUrls may be an unmodifiable List, shuffle it directly may throw an exception.

Fix nodeUrls shuffle error

---

iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/iot/logdispatcher/IoTConsensusMemoryManager.java
iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/iot/logdispatcher/LogDispatcher.java
iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/iot/logdispatcher/SyncStatus.java
iotdb-core/consensus/src/test/java/org/apache/iotdb/consensus/iot/logdispatcher/IoTConsensusMemoryManagerTest.java

When a request fails to allocate memory for entering the queue of the first follower, its reference count is not decreased.
Thus, when entering the queues of other followers, its memory allocation is also omitted, resulting in uncontrolled memory of the IoTConsensus request queue and OOM.

Fix ref count of IoTConsensus request not decreased in allocation failure

---

example/session/src/main/java/org/apache/iotdb/SessionExample.java
example/session/src/main/java/org/apache/iotdb/SessionPoolExample.java
example/session/src/main/java/org/apache/iotdb/TableModelSessionExample.java
example/session/src/main/java/org/apache/iotdb/TableModelSessionPoolExample.java

This pull request refactors the IoTDB Java session examples to improve code reuse and consistency in how query results are printed. The main enhancement is the introduction of a shared `printDataSet` utility method, which standardizes the output of query results across multiple example classes. Additionally, some redundant or outdated query methods are removed for clarity.
Key changes:
**Code reuse and consistency improvements:**
* Introduced a new `printDataSet(SessionDataSet dataSet)` method in `SessionExample.java` to handle printing of query results, including column names, types, and handling of null values. This method is now used throughout the example code to ensure consistent output formatting. (Fc9e8d42L812R812)
* Updated `TableModelSessionExample.java` and …

Change all query example into iterator style

---

integration-test/src/test/java/org/apache/iotdb/db/it/utils/TestUtils.java
integration-test/src/test/java/org/apache/iotdb/pipe/it/autocreate/IoTDBPipeDataSinkIT.java

cherry-pick https://github.com/apache/iotdb/pull/16202 to https://github.com/apache/iotdb/tree/dev/1.3

[To dev/1.3] Pipe CI: always flush for IoTDBPipeDataSinkIT.testReceiverAutoCreate with batch mode (#16202)

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/Analysis.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/distribution/SourceRewriter.java

This pull request updates the device view aggregation logic in the query engine to better handle User-Defined Table Functions (UDTFs) and clarifies when special processing is needed. The main changes involve extending the special-case handling to include UDTFs and refactoring related method names for clarity.
**Device view aggregation logic improvements:**
* Updated the comment in `Analysis.java` to clarify that `deviceViewSpecialProcess` applies when all Aggregation Functions, UDTFs, and DIFF are present, not just Aggregation Functions and DIFF.
* Modified the logic in `SourceRewriter.java` so that special processing for device views is triggered when UDTFs are present, in addition to existing conditions. This is achieved by checking for the UDTF function type in the relevant method.
* …

Fix error of non-mappable udtf query in align by device while existing any devices' data cross region

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/DataRegion.java

This pull request improves the robustness of the `tryGetFLushLock` method in `DataRegion.java` by handling cases where a `TsFileProcessor` is null, which indicates the file is in the process of closing. The new logic introduces a busy-wait loop to check for the file's closed status before proceeding, ensuring thread safety and correctness during concurrent file operations.
**Concurrency and file closing handling:**
* Added a check for `tsFileProcessor == null` to detect if a tsfile is being closed, and implemented a busy-wait loop that waits for the file to finish closing before proceeding. If the file closes within the wait time, the loop continues; otherwise, it clears the lock list and returns `false` to prevent unsafe operations. …

Fix potential NPE in tryGetFLushLock

---

integration-test/src/test/java/org/apache/iotdb/relational/it/query/recent/IoTDBCteIT.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/analyzer/StatementAnalyzer.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/planner/RelationPlanner.java

This pull request introduces a new integration test suite for Common Table Expressions (CTEs) and adds support for implicit type coercion when resolving CTEs in query planning. The main focus is to ensure correct CTE handling, including type mismatches between CTE definitions and their usage, and to improve test coverage for CTE-related features.
**CTE Testing and Type Coercion Improvements:**
* Added a comprehensive integration test class `IoTDBCteIT` to verify CTE functionality, including basic queries, partial column aliasing, nested and multi-reference CTEs, privilege checks, JDBC/session compatibility, and error scenarios.
* In `RelationPlanner.java`, updated the logic for visiting a table to detect and process named queries (CTEs), including handling recursive CTEs and applying …

with_clause feature

---

iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/pipe/agent/runtime/PipeConfigNodeRuntimeAgent.java
iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/pipe/agent/task/PipeConfigNodeTaskAgent.java

[To dev/1.3] Pipe: Fixed the config meta transfer problem (#16280)

---

.gitignore
integration-test/src/test/java/org/apache/iotdb/relational/it/session/IoTDBSessionRelationalIT.java
iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/iot/client/DispatchLogHandler.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/scheduler/FragmentInstanceDispatcherImpl.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/DataRegion.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/receiver/PipeReceiverStatusHandler.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/utils/RetryUtils.java

The dispatcher retries when a write meets non-recoverable errors like out-of-ttl, which is unnecessary. 
The retries are controlled based on the same logic as the consensus layer.
When a row fails to insert due to TTL expiration, its failure count is set, but its measurements are not set to null, which may cause incorrect serialization.

Fix improper retries in dispatcher & measurements not set to null when inserting row out-of-ttl

---

iotdb-core/ainode/ainode/core/model/built_in_model_factory.py

As shown in the following figure, when performing inference tasks using a large time series model, the Cli reports an error. The reason is that only the model.safetensor file was downloaded, but not the config.json file.

[Bug Fix] Download config.json for Large TimeSeries Model

---

integration-test/src/test/java/org/apache/iotdb/pipe/it/dual/tablemodel/manual/basic/IoTDBPipeWithLoadIT.java

Pipe IT: enlarge timeout in `testLoadWhenIncomingIdColumnsArePrefixOfExisting`

---

iotdb-client/session/src/main/java/org/apache/iotdb/session/ThriftConnection.java

This pull request makes a small but important change to the `ThriftConnection` class to ensure resources are properly released. The change moves the transport closing logic into a `finally` block, guaranteeing that the transport is closed even if an exception occurs during session closing.
- Resource management improvement:
* Ensured that `transport.close()` is always called by moving it into a `finally` block in the `close()` method of `ThriftConnection`, improving reliability and preventing potential resource leaks.

Fix NodeSupplier connection leaky while encountering exception

---

integration-test/src/test/java/org/apache/iotdb/db/it/aligned/IoTDBAlignedMemQueryIT.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/utils/datastructure/AlignedTVList.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/utils/datastructure/MergeSortMultiAlignedTVListIterator.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/memtable/AlignedTVListIteratorTest.java

Fix some bugs in AlignedTVListIterator. In the tree model, some all-null rows may be found unexpectedly.
```
IoTDB> insert into root.test.d1(time,s1,s2) aligned values (1,1,1)
IoTDB> insert into root.test.d1(time,s1) aligned values (2,2)
IoTDB> insert into root.test.d1(time,s2) aligned values (3,3)
IoTDB> flush
IoTDB> insert into root.test.d1(time,s1,s2) aligned values (1,1,1)
IoTDB> insert into root.test.d1(time,s1) aligned values (2,2)
IoTDB> insert into root.test.d1(time,s2) aligned values (3,3)
Msg: The statement is …
```

Fix some bugs in AlignedTVListIterator

---

integration-test/src/test/java/org/apache/iotdb/relational/it/db/it/IoTDBPatternAggregationIT.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/process/rowpattern/expression/CastComputation.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/process/rowpattern/expression/ComparisonOperator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/process/rowpattern/expression/Computation.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/process/rowpattern/expression/PatternExpressionComputation.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/planner/LiteralEncoder.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/execution/operator/process/rowpattern/PatternExpressionTest.java

Fix the issue where string & date & blob filtering cannot be used in the DEFINE clause

Fix the issue where string filtering cannot be used in the DEFINE clause

---

docker/src/main/DockerCompose/docker-compose-ainode.yml
docker/src/main/DockerCompose/docker-compose-cluster-1c1d1a.yml
docker/src/main/DockerCompose/docker-compose-cluster-1c2d.yml
docker/src/main/DockerCompose/docker-compose-host-3c3d.yml
docker/src/main/DockerCompose/docker-compose-standalone.yml

Note: Some environments set an extremely high container nofile limit (~2^30 = 1073741824).
This can make the startup step "Checking whether the ports are already occupied..." appear to hang (lsof slow).
If you see that line for a long time, lower the nofile limit by uncommenting below:

Add comments in docker-compose for startup hang

---

.github/workflows/cluster-it-1c1d1a.yml
iotdb-core/ainode/pom.xml

Since the AINode now relies on iotdb-python-api module, while this python dependencies cannot be detected by maven, we should ignore the corresponding verify check.

[AINode] Fix maven verify bug

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/performer/impl/FastCompactionPerformer.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/utils/CompactionUtils.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/utils/MultiTsFileDeviceIterator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/utils/executor/fast/SeriesCompactionExecutor.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/utils/writer/AbstractCompactionWriter.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/selector/estimator/AbstractCompactionEstimator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/selector/estimator/RepairUnsortedFileCompactionEstimator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/selector/impl/NewSizeTieredCompactionSelector.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/selector/impl/SettleSelectorImpl.java
iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/path/PatternTreeMap.java

1. Optimize ttl deletion in fast compaction performer
2. Fixed a bug for read point compaction performer

[to dev/1.3] Optimize ttl deletion in fast compaction performer

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/process/InsertTabletStatementGenerator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/process/TableInsertTabletStatementGenerator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/process/TreeInsertTabletStatementGenerator.java

…nerator
Notice: times and columns in the InsertTabletStatementGenerator cannot be reused. When insertTabletStatements is constructed, we copy the times and columns from InsertTabletStatementGenerator. However serveral InsertTabletStatements may be held by WAL or PIPE. They're constructed concurrently and lead to problems. 
<hr>
This PR has:
<hr>

Revert: cannot reuse time and column array in InsertTabletStatementGenerator

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/DataRegion.java

Always employ try-with-resource grammar when invoking ConfigNodeClient.

Fix ConfigNodeClient thread leak at DataRegion.java

---

example/client-cpp-example/src/TableModelSessionExample.cpp
iotdb-client/client-cpp/src/main/SessionBuilder.h
iotdb-client/client-cpp/src/main/TableSession.h
iotdb-client/client-cpp/src/main/TableSessionBuilder.h

fix cpp sesssion builder memory leak
<hr>
This PR has:
- [√] been tested
```
try {
auto builder = std::make_shared<TableSessionBuilder>();
auto session = std::shared_ptr<TableSession>(builder->username("root")
->password("root")
->nodeUrls(node_urls)
->build());
session->executeNonQueryStatement("show timeseries");
session->close();
}
catch (const exception &e) {
printf("exception: %s\n", e.what());
}
```
```
$ valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes ./iotdbapp 
==95960== Memcheck, a memory error detector
==95960== Copyright (C) 2002-2022, and GNU GPL'd, by Julian Seward et al.
==95960== Using Valgrind-3.22.0 and LibVEX; rerun with -h for copyright info
==95960== Command: ./iotdbapp
==95960== 
Thrift: Fri Sep 19 10:37:16 2025 TSocket::open() timed out <Host: …
```

fix cpp session mem leak

---

iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/common/schematree/DeviceSchemaInfo.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/cache/schema/dualkeycache/impl/DualKeyCacheImpl.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/schema/ClusterSchemaFetcher.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/OperatorTreeGenerator.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/metadata/fetcher/cache/TableDeviceLastCache.java
iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/relational/metadata/fetcher/cache/TreeDeviceSchemaCacheManager.java
iotdb-core/datanode/src/test/java/org/apache/iotdb/db/metadata/cache/TreeDeviceSchemaCacheManagerTest.java
pom.xml

Refactored the schema cache

---

iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/load/TimeseriesMetadataIteratorTest.java
pom.xml

[To dev/1.3] fix: Updated TSFile version to fix Load failure in creating aligned time series (#16502)

---

distribution/src/assembly/ainode.xml
iotdb-core/ainode/pyproject.toml

Make a hotfix to the bug that `venv` for ainode would be put in the distribution package in 2.0.6-SNAPSHOT. If this fix is applied, the size of ainode package will decrease to 346mb.
Since the pull request did not change any pom file, several fixes will be pushed in few days.
This PR has:

[AINode] Fix: remove venv out of the target directory. 
