docs/SystemDesign/SchemaManager/SchemaManager.md, docs/zh/SystemDesign/SchemaManager/SchemaManager.md
=> modified the description of tlog

cluster/src/main/java/org/apache/iotdb/cluster/coordinator/Coordinator.java, cluster/src/main/java/org/apache/iotdb/cluster/metadata/CMManager.java, cluster/src/main/java/org/apache/iotdb/cluster/utils/PartitionUtils.java, server/src/main/java/org/apache/iotdb/db/metadata/MManager.java, server/src/main/java/org/apache/iotdb/db/metadata/MTree.java, server/src/main/java/org/apache/iotdb/db/metadata/logfile/MLogTxtWriter.java, server/src/main/java/org/apache/iotdb/db/metadata/logfile/MLogWriter.java, server/src/main/java/org/apache/iotdb/db/metadata/mnode/IMNode.java, server/src/main/java/org/apache/iotdb/db/metadata/mnode/InternalMNode.java, server/src/main/java/org/apache/iotdb/db/metadata/mnode/MeasurementMNode.java, server/src/main/java/org/apache/iotdb/db/metadata/template/TemplateManager.java, server/src/main/java/org/apache/iotdb/db/qp/executor/PlanExecutor.java, server/src/main/java/org/apache/iotdb/db/qp/physical/PhysicalPlan.java, server/src/main/java/org/apache/iotdb/db/qp/physical/crud/SetSchemaTemplatePlan.java, server/src/main/java/org/apache/iotdb/db/qp/physical/sys/SetUsingSchemaTemplatePlan.java, server/src/main/java/org/apache/iotdb/db/service/TSServiceImpl.java, server/src/main/java/org/apache/iotdb/db/tools/mlog/MLogParser.java, server/src/test/java/org/apache/iotdb/db/metadata/MManagerBasicTest.java, server/src/test/java/org/apache/iotdb/db/qp/physical/InsertRowPlanTest.java, server/src/test/java/org/apache/iotdb/db/qp/physical/InsertTabletPlanTest.java, server/src/test/java/org/apache/iotdb/db/query/reader/series/SeriesReaderTestUtil.java, server/src/test/java/org/apache/iotdb/db/tools/MLogParserTest.java, server/src/test/java/org/apache/iotdb/db/writelog/recover/SeqTsFileRecoverTest.java, session/src/test/java/org/apache/iotdb/session/SessionTest.java, tsfile/src/main/java/org/apache/iotdb/tsfile/write/TsFileWriter.java, tsfile/src/main/java/org/apache/iotdb/tsfile/write/schema/Schema.java, tsfile/src/test/java/org/apache/iotdb/tsfile/write/DefaultSchemaTemplateTest.java, tsfile/src/test/java/org/apache/iotdb/tsfile/write/schema/converter/SchemaBuilderTest.java
All the "deviceTemplate" has been replaced by "schemaTemplate". The occurrence include metadata module and template query plans.  
<hr>
This PR has:
<hr>
=> [IOTDB-1511] Rename DeviceTemplate to SchemaTemplate

site/src/main/.vuepress/theme/global-components/Contributor.vue
=> add committer wangchao316

server/src/main/java/org/apache/iotdb/db/qp/strategy/PhysicalGenerator.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBAlignByDeviceIT.java
=> [To rel/0.12] Skip non exist measurement in where clause in align by device

server/src/main/java/org/apache/iotdb/db/qp/logical/crud/QueryOperator.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBAlignByDeviceIT.java
=> [To master] Skip non exist measurement in where clause in align by device

CONTRIBUTING.md, README.md, README_ZH.md
Update the expired links for the following documents
=> [Docs] Update expired link

client-cpp/src/main/Session.cpp, client-cpp/src/main/Session.h
JIRA: https://issues.apache.org/jira/browse/IOTDB-1542
I made 2 changes in this PR:
1. format code
2. remove `char buf[[111]`
=> [IOTDB-1542] Cpp client segment fault: char[] buffer overflow caused by long exception message

client-cpp/src/main/Session.cpp, client-cpp/src/main/Session.h
JIRA: https://issues.apache.org/jira/browse/IOTDB-1542
I made 2 changes in this PR:
format code
remove char buf[[111]
=> [To rel/0.12][IOTDB-1542] Cpp client segment fault: char[] buffer overflow caused by long exception message 

Jenkinsfile
https://ci-builds.apache.org/job/IoTDB/job/IoTDB-Pipe/job/master/
=> Add Jenkins CI timeout threshold

server/src/main/java/org/apache/iotdb/db/metadata/MManager.java, server/src/main/java/org/apache/iotdb/db/metadata/MTree.java, server/src/test/java/org/apache/iotdb/db/metadata/MManagerBasicTest.java
=> [To rel/0.12]add Template Constraint

server/src/main/java/org/apache/iotdb/db/engine/storagegroup/StorageGroupProcessor.java
=> [To autoai] only submit task in LEVEL_COMPACTION

server/src/assembly/resources/conf/iotdb-engine.properties, server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java, server/src/main/java/org/apache/iotdb/db/engine/compaction/CompactionMergeTaskPoolManager.java
We'd better close compaction before it is stable
=> close compaction by default

server/src/main/java/org/apache/iotdb/db/auth/AuthorityChecker.java
JIRA:https://issues.apache.org/jira/browse/IOTDB-1537
=> [To rel/0.12][IOTDB-1537]fix insertTablet premission

example/session/src/main/java/org/apache/iotdb/SessionExample.java
We need a new session example to show how to use template to create Univariable Timeseries.
Cherry-pick from #3536 .
=> [IOTDB-1486] Add a createTemplate Session example

server/src/main/java/org/apache/iotdb/db/engine/storagegroup/StorageGroupProcessor.java, server/src/main/java/org/apache/iotdb/db/engine/upgrade/UpgradeTask.java, server/src/main/java/org/apache/iotdb/db/service/UpgradeSevice.java, server/src/main/java/org/apache/iotdb/db/tools/TsFileRewriteTool.java, server/src/main/java/org/apache/iotdb/db/tools/upgrade/TsFileOnlineUpgradeTool.java, server/src/main/java/org/apache/iotdb/db/utils/UpgradeUtils.java, tsfile/src/main/java/org/apache/iotdb/tsfile/write/chunk/ChunkWriterImpl.java
Cherry-pick #3186 , #3319 , #3329 , #3376 .
=> Cherry-pick 4 bug-fixing commits about upgrade tool from rel/0.12 to master branch

server/src/main/java/org/apache/iotdb/db/tools/TsFileRewriteTool.java, server/src/main/java/org/apache/iotdb/db/tools/upgrade/TsFileOnlineUpgradeTool.java
=> [IOTDB-1546] Optimize the Upgrade/Rewrite Tool rewrite logic to reduce the temp memory cost

server/src/main/java/org/apache/iotdb/db/auth/AuthorityChecker.java
=> [IOTDB-1537]fix insertTablet permission

RELEASE_NOTES.md
=> [To rel/0.12] Release note of 0.12.2

server/src/main/java/org/apache/iotdb/db/qp/logical/crud/BasicFunctionOperator.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBQueryDemoIT.java, server/src/test/java/org/apache/iotdb/db/query/dataset/groupby/GroupByFillDataSetTest.java
JIRA:https://issues.apache.org/jira/browse/IOTDB-1552
For text type,Only equal and not equal should be supported
=> [IOTDB-1552]Some basic operators should not be applied to text time series

server/src/assembly/resources/conf/iotdb-engine.properties, server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java, server/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java, server/src/main/java/org/apache/iotdb/db/engine/storagegroup/TsFileProcessor.java, server/src/main/java/org/apache/iotdb/db/service/IoTDB.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBRestartIT.java, server/src/test/java/org/apache/iotdb/db/utils/EnvironmentUtils.java, spark-iotdb-connector/src/test/scala/org/apache/iotdb/spark/db/EnvironmentUtils.java
=> [IOTDB-1485] Replace tsfile_size_threshold by unseq_tsfile_size/seq_tsfile_size

server/src/main/java/org/apache/iotdb/db/qp/logical/crud/BasicFunctionOperator.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBQueryDemoIT.java, server/src/test/java/org/apache/iotdb/db/query/dataset/groupby/GroupByFillDataSetTest.java
=> [To rel/0.12][IOTDB-1552]Some basic operators should not be applied to text time series

RELEASE_NOTES.md, server/src/main/java/org/apache/iotdb/db/qp/sql/IoTDBSqlVisitor.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBDeletionIT.java
Co-authored-by: 还真 <huanzhen.gy@alibaba-inc.com>
Cherry pick #3719 .
=> [IOTDB-1539] [To rel/0.12] Fix delete operation with value filter is abnormal

antlr/src/main/antlr4/org/apache/iotdb/db/qp/sql/SqlBase.g4, docs/UserGuide/IoTDB-SQL-Language/DML-Data-Manipulation-Language.md, docs/zh/UserGuide/IoTDB-SQL-Language/DML-Data-Manipulation-Language.md, server/src/main/java/org/apache/iotdb/db/qp/sql/IoTDBSqlVisitor.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBFillIT.java
problem sql：
insert into root.sg.d1(timestamp,systemtime,value) values(2021-07-25 14:15:00,1627193720000,131.0);
in #3621  Value is set as the keyword
In the current pr：
delete value keyword
=> [IOTDB-1561][To rel/0.12]Fix problems caused by keywords

antlr/src/main/antlr4/org/apache/iotdb/db/qp/sql/SqlBase.g4, docs/UserGuide/System-Tools/Load-External-Tsfile.md, docs/zh/UserGuide/System-Tools/Load-External-Tsfile.md, pom.xml, server/src/main/java/org/apache/iotdb/db/engine/storagegroup/StorageGroupProcessor.java, server/src/main/java/org/apache/iotdb/db/qp/executor/PlanExecutor.java, server/src/main/java/org/apache/iotdb/db/qp/logical/sys/LoadFilesOperator.java, server/src/main/java/org/apache/iotdb/db/qp/physical/sys/OperateFilePlan.java, server/src/main/java/org/apache/iotdb/db/qp/sql/IoTDBSqlVisitor.java, server/src/main/java/org/apache/iotdb/db/qp/strategy/PhysicalGenerator.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBLoadExternalTsfileIT.java, server/src/test/java/org/apache/iotdb/db/qp/physical/PhysicalPlanTest.java, server/src/test/java/org/apache/iotdb/db/utils/TsFileRewriteToolTest.java
cherry pick [IOTDB-1519]add metadata checking option and change grammar for loading tsfile #3576
=> [IOTDB-1519][To rel/0.12] add metadata checking option and change grammar for loading tsfile

antlr/src/main/antlr4/org/apache/iotdb/db/qp/sql/SqlBase.g4, docs/UserGuide/IoTDB-SQL-Language/DML-Data-Manipulation-Language.md, docs/zh/UserGuide/IoTDB-SQL-Language/DML-Data-Manipulation-Language.md, server/src/main/java/org/apache/iotdb/db/qp/sql/IoTDBSqlVisitor.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBFillIT.java
=> [IOTDB-1561]Fix problems caused by keywords (#3756)

docs/SystemDesign/SchemaManager/SchemaManager.md, docs/zh/SystemDesign/SchemaManager/SchemaManager.md
Cherry-picked from e4a2926865c6e013de863b8e4323a04bb23e08f7.
See #3651 for detail.
=> Modified the description of tlog (#3651)

server/src/main/java/org/apache/iotdb/db/engine/storagegroup/StorageGroupProcessor.java
Output .mods file path in log.
=> [To rel/0.12] Edit deletion log

server/src/main/java/org/apache/iotdb/db/engine/storagegroup/StorageGroupProcessor.java
Output .mods file path in log.
=> Edit deletion log

docs/zh/UserGuide/IoTDB-SQL-Language/DDL-Data-Definition-Language.md, docs/zh/UserGuide/IoTDB-SQL-Language/DML-Data-Manipulation-Language.md
Cherry-picked from aa5c8396ac75fca8457cd3fa20204e0cd66e33ef (#3683).
=> Fix incorrect descriptions in DDL-Data-Definition-Language(Chinses) and a typo in DML-Data-Manipulation-Language(Chinses)

server/src/assembly/resources/conf/iotdb-engine.properties, server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java, server/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java, server/src/main/java/org/apache/iotdb/db/engine/storagegroup/StorageGroupProcessor.java
Cherry-picked from 349656c8159337007d9ead09393331b4e14105c5.
See #3749 for detail.
=> [IOTDB-1566] Do not restrict concurrent write partitions

server/src/main/java/org/apache/iotdb/db/writelog/node/ExclusiveWriteLogNode.java
=> [cherry-pick from rel/0.12] new ExclusiveWriteLogNode

server/src/main/java/org/apache/iotdb/db/service/TSServiceImpl.java, server/src/test/java/org/apache/iotdb/db/integration/aggregation/IoTDBAggregationSmallDataIT.java, tsfile/src/main/java/org/apache/iotdb/tsfile/read/expression/util/ExpressionOptimizer.java, tsfile/src/test/java/org/apache/iotdb/tsfile/write/MetadataIndexConstructorTest.java
644e520439399a26d065cc840e27d92798382ba9
=> [cherry-pick from rel/0.12] add log for StackOverflowError in eExpressionOptimizer

.gitattributes
https://stackoverflow.com/questions/29435156/what-will-text-auto-eol-lf-in-gitattributes-do
=> [To rel/0.12]Fix gitattribute covert pictures

.gitattributes
https://stackoverflow.com/questions/29435156/what-will-text-auto-eol-lf-in-gitattributes-do
<hr>
This PR has:
<hr>
=> Fix gitattribute covert picture

cluster/src/main/java/org/apache/iotdb/cluster/coordinator/Coordinator.java, cluster/src/main/java/org/apache/iotdb/cluster/metadata/CMManager.java, cluster/src/main/java/org/apache/iotdb/cluster/server/MetaClusterServer.java, server/src/main/java/org/apache/iotdb/db/metadata/MManager.java, server/src/main/java/org/apache/iotdb/db/service/IoTDB.java, session/src/main/java/org/apache/iotdb/session/Session.java
There are some bug-fixs needing to be cherry-picked from 0.12 to master
For #3580, it has been merged to master in #3579.
For #3538, it needs more tests before being cherry-picked to master.
For #3532, I cherry-pick this commit in this PR.
For #3657, there are three cluster-related bug-fixs in this PR,and I have already cherry-picked them to master, which is #3560, #3525 and #3595.
=> [Cherry-Pick] Cherry Pick some cluster bug-fixs from rel/0.12 to master

docs/zh/UserGuide/API/Programming-JDBC.md
=> Fix typo in #3783

server/src/main/java/org/apache/iotdb/db/engine/compaction/level/LevelCompactionTsFileManagement.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBTimePartitionIT.java
The bug is caused by we didn't traverse the tsfile seqeunce in time partition order.
=> [IOTDB-1580] Error result of order by time desc when enable time partition

server/src/main/java/org/apache/iotdb/db/engine/memtable/WritableMemChunk.java, server/src/test/java/org/apache/iotdb/db/engine/memtable/PrimitiveMemTableTest.java
https://issues.apache.org/jira/browse/IOTDB-1572
=> [IOTDB-1572]Should not change object's state in toString()

server/src/main/java/org/apache/iotdb/db/qp/logical/crud/QueryOperator.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBAlignByDeviceIT.java
IoTDBAlignByDeviceIT.selectSlimitTest have problem, Old IT didn't test out problems
JIRA:https://issues.apache.org/jira/browse/IOTDB-1592
=> [IOTDB-1592]BugFix: SLimit Not effective in align by device

docs/zh/UserGuide/Advanced-Features/Continuous-Query.md
=> Fix format of Chinese CQ user doc

README.md, README_ZH.md, docs/Download/README.md, docs/zh/Download/README.md, server/src/assembly/resources/conf/iotdb-env.sh
For more detail, please see #3865.
=> [To rel/0.12][ISSUE-3865] Meaningless connection reset issues caused by low default value for SOMAXCONN

server/src/main/java/org/apache/iotdb/db/tools/TsFileRewriteTool.java, tsfile/src/main/java/org/apache/iotdb/tsfile/write/writer/TsFileIOWriter.java
=> Fix load TsFile failed when time partition enabled caused by TsFileReWriteTool NPE

docs/SystemDesign/DataQuery/RawDataQuery.md, docs/SystemDesign/DataQuery/SeriesReader.md, docs/zh/SystemDesign/DataQuery/OrderByTimeQuery.md, docs/zh/SystemDesign/DataQuery/RawDataQuery.md, docs/zh/SystemDesign/DataQuery/SeriesReader.md
When reading the design document of data query, part of the code in the document has been optimized
=> update design document of data query

RELEASE_NOTES.md
=> [To rel/0.12] Update release note for 0.12.2 RC2

server/src/assembly/resources/conf/iotdb-engine.properties, server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
Change flush/close interval from 12h to 1h and flush/close check interval to from 1h to 10min.
=> [To rel/0.12] Change default value for timed flush memtable and timed close tsfile

server/src/assembly/resources/conf/iotdb-engine.properties, server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
Change flush/close interval from 12h to 1h and flush/close check interval to from 1h to 10min.
=> Change default value for timed flush memtable and timed close tsfile

docs/UserGuide/Appendix/Config-Manual.md, docs/UserGuide/Data-Concept/Auto-Create-MetaData.md, docs/UserGuide/Data-Concept/Time-Partition.md, docs/zh/UserGuide/Appendix/Config-Manual.md, docs/zh/UserGuide/Data-Concept/Auto-Create-MetaData.md, docs/zh/UserGuide/Data-Concept/Time-Partition.md
Update docs for time partition and auto create metadata.
=> Update docs for time partition and auto create metadata

cluster/src/main/java/org/apache/iotdb/cluster/server/ClientServer.java, cluster/src/main/java/org/apache/iotdb/cluster/utils/PartitionUtils.java, server/src/main/java/org/apache/iotdb/db/qp/physical/PhysicalPlan.java, server/src/main/java/org/apache/iotdb/db/qp/physical/sys/SetSystemModePlan.java, testcontainer/src/test/java/org/apache/iotdb/db/sql/Cases.java
In #3771   we need the sql  Adaptive cluster
=> [IOTDB-1565]set system to readonly / writable Adaptive cluster

server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java, server/src/main/java/org/apache/iotdb/db/tools/TsFileRewriteTool.java, server/src/main/java/org/apache/iotdb/db/tools/upgrade/TsFileOnlineUpgradeTool.java, server/src/test/java/org/apache/iotdb/db/utils/TsFileRewriteToolTest.java, tsfile/src/main/java/org/apache/iotdb/tsfile/read/TsFileSequenceReader.java, tsfile/src/main/java/org/apache/iotdb/tsfile/v2/read/TsFileSequenceReaderForV2.java
=> [IOTDB-1610][To rel/0.12] Fix TsFileRewriteTool writing incorrect data file

site/src/main/.vuepress/theme/global-components/IoTDB.vue, site/src/main/.vuepress/theme/global-components/IoTDBZH.vue
Update the the QuickStart link in Home page from v0.10.0 to latest.
=> Update the QuickStart link in Home page

cluster/src/main/java/org/apache/iotdb/cluster/server/ClientServer.java, cluster/src/main/java/org/apache/iotdb/cluster/utils/PartitionUtils.java, server/src/main/java/org/apache/iotdb/db/qp/physical/PhysicalPlan.java, server/src/main/java/org/apache/iotdb/db/qp/physical/sys/SetSystemModePlan.java
=> [To rel/0.12][IOTDB-1565]Cherry Pick: set system to readonly / writable Adaptive cluster

server/src/main/java/org/apache/iotdb/db/tools/TsFileRewriteTool.java, server/src/main/java/org/apache/iotdb/db/tools/upgrade/TsFileOnlineUpgradeTool.java, server/src/test/java/org/apache/iotdb/db/utils/TsFileRewriteToolTest.java, tsfile/src/main/java/org/apache/iotdb/tsfile/read/TsFileSequenceReader.java, tsfile/src/main/java/org/apache/iotdb/tsfile/v2/read/TsFileSequenceReaderForV2.java
=> [IOTDB-1610] Fix TsFileRewriteTool writing incorrect data file

site/pom.xml
=> [IOTDB-1616] Fix website cannot update rel/0.12 documents

cluster/src/main/java/org/apache/iotdb/cluster/ClusterIoTDB.java
just change entrance, split server module and cluster.
=> [cluster-refactor] change the entrance

cluster/pom.xml
=> Revert "[IOTDB-1534] fix surefire ci by increasing memory"

cluster/src/main/java/org/apache/iotdb/cluster/query/ClusterPlanRouter.java, server/src/main/java/org/apache/iotdb/db/qp/physical/PhysicalPlan.java, server/src/main/java/org/apache/iotdb/db/qp/physical/crud/InsertRowsOfOneDevicePlan.java, server/src/test/java/org/apache/iotdb/db/qp/physical/InsertRowsOfOneDevicePlanTest.java, testcontainer/src/test/java/org/apache/iotdb/db/sql/Cases.java
See JIRA https://issues.apache.org/jira/browse/IOTDB-1600 .
This PR has:
=> [IOTDB-1600] Support InsertRowsOfOneDevicePlan in cluster

RELEASE_NOTES.md, cluster/src/main/java/org/apache/iotdb/cluster/query/ClusterPlanRouter.java, server/src/main/java/org/apache/iotdb/db/qp/physical/PhysicalPlan.java, server/src/main/java/org/apache/iotdb/db/qp/physical/crud/InsertRowsOfOneDevicePlan.java, server/src/test/java/org/apache/iotdb/db/qp/physical/InsertRowsOfOneDevicePlanTest.java
See JIRA: https://issues.apache.org/jira/browse/IOTDB-1600 . Cherry-picked from https://github.com/apache/iotdb/pull/3877
=> [To rel/0.12][IOTDB-1600] Support InsertRowsOfOneDevicePlan in cluster

cli/src/main/java/org/apache/iotdb/cli/Cli.java, cli/src/main/java/org/apache/iotdb/cli/WinCli.java, cli/src/test/java/org/apache/iotdb/cli/StartClientScriptIT.java
=> [IOTDB-1659] Fix Windows CLI cannot set maxPRC less than or equal to 0

cluster/src/main/java/org/apache/iotdb/cluster/log/manage/serializable/SyncLogDequeSerializer.java
cherry pick [#3930](https://github.com/apache/iotdb/pull/3930)
=> [To rel/0.12][IOTDB-1619] Cherry Pick: There is an error msg when I restart iotdb-cluster

cli/src/main/java/org/apache/iotdb/cli/Cli.java, cli/src/main/java/org/apache/iotdb/cli/WinCli.java
=> [To rel/0.12] [IOTDB-1670] Fix cli -e mode didn't fetch timestamp_precision from server

cli/src/main/java/org/apache/iotdb/cli/AbstractCli.java, cli/src/main/java/org/apache/iotdb/cli/Cli.java, cli/src/main/java/org/apache/iotdb/cli/WinCli.java, cli/src/test/java/org/apache/iotdb/cli/StartClientScriptIT.java
=> [To rel/0.12] cherry-pick two CLI bug fix PRs

cluster/src/main/java/org/apache/iotdb/cluster/query/ClusterQueryRouter.java, cluster/src/main/java/org/apache/iotdb/cluster/query/fill/ClusterFillExecutor.java, cluster/src/test/java/org/apache/iotdb/cluster/query/ClusterFillExecutorTest.java, server/src/main/java/org/apache/iotdb/db/query/executor/FillQueryExecutor.java, server/src/main/java/org/apache/iotdb/db/query/executor/QueryRouter.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBFillIT.java
For detailed descriptions: https://issues.apache.org/jira/browse/IOTDB-1632
=> [IOTDB-1632] fill only if the value is missing

server/src/assembly/resources/conf/iotdb-env.sh
See JIRA https://issues.apache.org/jira/browse/IOTDB-1674
=> [IOTDB-1674] Fix command interpreting error causing somaxconn warning failed

docker/src/main/Dockerfile-0.12.2-cluster, docker/src/main/Dockerfile-0.12.2-node, docs/Download/README.md, docs/zh/Download/README.md
This PR finish some tasks of releasing iotdb v0.12.2.
NOTICE: LEAVE "merge this PR" ACTION TO ME.
=> [IoTDB-1671] modify dockerfile and Download file for releasing v0.12.2

cluster/src/main/java/org/apache/iotdb/cluster/query/fill/ClusterFillExecutor.java, cluster/src/test/java/org/apache/iotdb/cluster/query/fill/ClusterFillExecutorTest.java
For more detailed descriptions: https://issues.apache.org/jira/browse/IOTDB-1629
=> [IOTDB-1629] fix the NPE when using value fill in cluster mode

cluster/src/main/java/org/apache/iotdb/cluster/query/ClusterQueryRouter.java, cluster/src/main/java/org/apache/iotdb/cluster/query/fill/ClusterFillExecutor.java, cluster/src/test/java/org/apache/iotdb/cluster/query/ClusterFillExecutorTest.java, server/src/main/java/org/apache/iotdb/db/query/executor/FillQueryExecutor.java, server/src/main/java/org/apache/iotdb/db/query/executor/QueryRouter.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBFillIT.java
=> [To rel/0.12][IOTDB-1632] fill only if the value is missing (#3914)

server/src/main/java/org/apache/iotdb/db/qp/logical/crud/LikeOperator.java, server/src/main/java/org/apache/iotdb/db/qp/logical/crud/RegexpOperator.java, server/src/main/java/org/apache/iotdb/db/qp/strategy/PhysicalGenerator.java, server/src/main/java/org/apache/iotdb/db/qp/strategy/optimizer/ConcatPathOptimizer.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBFuzzyQueryIT.java
ISSUE : #3945
Fuzzy query support multiDevice and alignByDevice
=> [To rel/0.12][ISSUE-3945] Fuzzy query support multiDevices and alignByDevice Dataset

cluster/src/main/java/org/apache/iotdb/cluster/query/fill/ClusterFillExecutor.java, cluster/src/test/java/org/apache/iotdb/cluster/query/fill/ClusterFillExecutorTest.java
=> [To rel/0.12][IOTDB-1629] fix the NPE when using value fill in cluster mode (#3913)

server/src/main/java/org/apache/iotdb/db/qp/logical/crud/LikeOperator.java, server/src/main/java/org/apache/iotdb/db/qp/logical/crud/QueryOperator.java, server/src/main/java/org/apache/iotdb/db/qp/logical/crud/RegexpOperator.java, server/src/main/java/org/apache/iotdb/db/qp/strategy/optimizer/ConcatPathOptimizer.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBFuzzyQueryIT.java
cherry-pick #3953
Since there is no operator.getType() method, use else if instead of switch
=> [ISSUE-3945] Fuzzy query support multiDevices and alignByDevice Dataset

example/client-cpp-example/src/SessionExample.cpp
fix CPP mem-leak in SessionExample.cpp insertRecords()
<hr>
This PR has:
<hr>
=> [IOTDB-1289] fix CPP mem-leak in SessionExample.cpp insertRecords()

client-cpp/src/main/Session.cpp, client-cpp/src/main/Session.h
[IOTDB-1678] client-cpp session bug: can cause connection leak.
=> [IOTDB-1678] client-cpp session bug: can cause connection leak.

client-cpp/src/main/Session.cpp, client-cpp/src/main/Session.h, example/client-cpp-example/src/SessionExample.cpp
=> [IOTDB-1679] [To rel/0.12] client-cpp: Session descontruction need release server resource

client-cpp/src/main/Session.cpp, client-cpp/src/main/Session.h
=> [IOTDB-1678] [To rel/0.12] Fix client-cpp session bug: can cause connection leak

server/src/main/java/org/apache/iotdb/db/conf/IoTDBConstant.java, server/src/main/java/org/apache/iotdb/db/sync/receiver/transfer/SyncServiceImpl.java, server/src/main/java/org/apache/iotdb/db/sync/sender/transfer/SyncClient.java
change version checking rule for sync process
before:
- Check full version number between sender and receiver.
- Stop sync process if full version number does not match
Now:
- Check major version number between sender and receiver
- Stop sync process if major version number does not match
=> [To rel/0.12] change sync version check

RELEASE_NOTES.md
Update release note for 0.12.3.
=> Release note for 0.12.3

RELEASE_NOTES.md, server/src/main/java/org/apache/iotdb/db/metadata/MManager.java
=> [To 0.12][IOTDB-1690] Fix align by device type cast error

docs/UserGuide/IoTDB-SQL-Language/DDL-Data-Definition-Language.md, docs/zh/UserGuide/IoTDB-SQL-Language/DDL-Data-Definition-Language.md
=> [IOTDB-1338] The content of DDL viewing sub-nodes in the user guide module is wrong

docs/UserGuide/IoTDB-SQL-Language/DDL-Data-Definition-Language.md, docs/zh/UserGuide/IoTDB-SQL-Language/DDL-Data-Definition-Language.md
=> [IOTDB-1338][To rel/0.12] The content of DDL viewing sub-nodes in the user guide module is wrong

server/src/main/java/org/apache/iotdb/db/metadata/mnode/MNode.java, server/src/main/java/org/apache/iotdb/db/metadata/tag/TagManager.java
=> [IOTDB-1703] Fix MManager slow recover with tag

cluster/src/assembly/resources/sbin/add-node.bat, cluster/src/assembly/resources/sbin/add-node.sh, cluster/src/assembly/resources/sbin/remove-node.bat, cluster/src/assembly/resources/sbin/remove-node.sh, cluster/src/assembly/resources/sbin/start-node.bat, cluster/src/assembly/resources/sbin/start-node.sh, cluster/src/assembly/resources/sbin/stop-node.bat, cluster/src/assembly/resources/sbin/stop-node.sh, cluster/src/main/java/org/apache/iotdb/cluster/ClusterIoTDB.java, cluster/src/main/java/org/apache/iotdb/cluster/server/ClusterTSServiceImpl.java
As main class name is changed from `ClusterMain` to `ClusterIoTDB`, update the names in scripts.
=> [cluster-refactor] update start class name in shell/bat script and apply spotless

server/src/assembly/resources/conf/iotdb-engine.properties, server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java, server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfigCheck.java, server/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java, server/src/main/java/org/apache/iotdb/db/metadata/tag/TagLogFile.java
=> [IOTDB-1727] Fix Slow creation of timeseries with tag

client-cpp/src/main/Session.cpp, client-cpp/src/main/Session.h, example/client-cpp-example/src/SessionExample.cpp
enhance codes in  client-cpp/src/main/Session.cpp and  client-cpp/src/main/Session.h
1)  correct some risk CPP codes
2)  correct some CPP codes that break basic CPP rule.
3)  enhance some Inefficient codes for better perfromance 
4) Accommodate more CPU types (bigEndian and LittleEndian)
=> [IOTDB-1720] client-cpp: enhance Session codes

docs/UserGuide/UserGuideReadme.md
Corrected the "In Progress Version" link in the top page of the live User Guide
<hr>
This PR has:
Testing: Load the .md and confirmed the link now works. 
<hr>
=> UserGuideReadme.md: fix "In Progress Version" link

docs/Development/ContributeGuide.md, docs/Development/HowToCommit.md, docs/zh/Development/ContributeGuide.md, docs/zh/Development/HowToCommit.md
1. Add main links.
2. Add submission considerations in git.
=> Update ContributeGuide.md and HowToCommit.md

server/src/main/java/org/apache/iotdb/db/query/udf/service/UDFRegistrationService.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBUDFManagementIT.java
This is the cherry-pick of #4026 
Related JIRA: https://issues.apache.org/jira/browse/IOTDB-1733
=> [To rel/0.12][IOTDB-1733] Fix dropping built-in function

cli/pom.xml, flink-iotdb-connector/pom.xml
Add mockito dependency for cli and flink connector module.
=> [cluster-refactor] add mockito dependency for cli module

server/src/main/java/org/apache/iotdb/db/engine/storagegroup/TsFileResource.java, tsfile/src/main/java/org/apache/iotdb/tsfile/file/header/PageHeader.java, tsfile/src/main/java/org/apache/iotdb/tsfile/file/metadata/ChunkMetadata.java, tsfile/src/main/java/org/apache/iotdb/tsfile/file/metadata/IChunkMetadata.java, tsfile/src/main/java/org/apache/iotdb/tsfile/file/metadata/TimeseriesMetadata.java, tsfile/src/main/java/org/apache/iotdb/tsfile/file/metadata/statistics/BinaryStatistics.java, tsfile/src/main/java/org/apache/iotdb/tsfile/file/metadata/statistics/BooleanStatistics.java, tsfile/src/main/java/org/apache/iotdb/tsfile/file/metadata/statistics/DoubleStatistics.java, tsfile/src/main/java/org/apache/iotdb/tsfile/file/metadata/statistics/FloatStatistics.java, tsfile/src/main/java/org/apache/iotdb/tsfile/file/metadata/statistics/IntegerStatistics.java, tsfile/src/main/java/org/apache/iotdb/tsfile/file/metadata/statistics/LongStatistics.java, tsfile/src/main/java/org/apache/iotdb/tsfile/file/metadata/statistics/Statistics.java, tsfile/src/main/java/org/apache/iotdb/tsfile/file/metadata/statistics/TimeStatistics.java, tsfile/src/main/java/org/apache/iotdb/tsfile/read/TsFileSequenceReader.java, tsfile/src/main/java/org/apache/iotdb/tsfile/v2/file/header/PageHeaderV2.java, tsfile/src/main/java/org/apache/iotdb/tsfile/v2/file/metadata/ChunkMetadataV2.java, tsfile/src/main/java/org/apache/iotdb/tsfile/v2/file/metadata/statistics/StatisticsV2.java, tsfile/src/main/java/org/apache/iotdb/tsfile/write/chunk/ChunkWriterImpl.java, tsfile/src/main/java/org/apache/iotdb/tsfile/write/chunk/ValueChunkWriter.java, tsfile/src/main/java/org/apache/iotdb/tsfile/write/page/PageWriter.java, tsfile/src/main/java/org/apache/iotdb/tsfile/write/page/ValuePageWriter.java, tsfile/src/main/java/org/apache/iotdb/tsfile/write/writer/TsFileIOWriter.java, tsfile/src/test/java/org/apache/iotdb/tsfile/file/metadata/utils/TestHelper.java
=> [ISSUE-4047]: Generic type in Statistics extend Serializable

cluster/src/main/java/org/apache/iotdb/cluster/metadata/CMManager.java, cluster/src/main/java/org/apache/iotdb/cluster/metadata/MetaPuller.java, server/src/main/java/org/apache/iotdb/db/qp/physical/crud/InsertMultiTabletPlan.java, server/src/main/java/org/apache/iotdb/db/qp/physical/crud/InsertRowPlan.java, server/src/main/java/org/apache/iotdb/db/qp/physical/crud/InsertRowsOfOneDevicePlan.java, server/src/main/java/org/apache/iotdb/db/qp/physical/crud/InsertRowsPlan.java, server/src/main/java/org/apache/iotdb/db/qp/physical/sys/CreateMultiTimeSeriesPlan.java
See JIRA https://issues.apache.org/jira/browse/IOTDB-1738
=> [IOTDB-1738] Cache paths list in batched insert plan

RELEASE_NOTES.md
=> [To rel/0.12] add release note for IOTDB-1723

server/src/main/java/org/apache/iotdb/db/sync/sender/transfer/SyncClient.java
[IOTDB-1749] sync-tool's lockInstance() dose not take effect
=> [IOTDB-1749] sync-tool's lockInstance() dose not take effect

cluster/src/main/java/org/apache/iotdb/cluster/server/raft/AbstractDataRaftService.java
=> [cluster-refactor] fix the bug that data heartbeat handler is null

server/src/main/java/org/apache/iotdb/db/qp/sql/IoTDBSqlVisitor.java
=> [ISSUE-4059]: IoTDBSqlVisitor#visitTopClause add top range restriction

README.md, README_ZH.md
=> [ISSUE-4069] Link of SQL Reference in README is 404

example/mqtt-customize/src/main/java/org/apache/iotdb/mqtt/server/CustomizedJsonPayloadFormatter.java, server/src/main/java/org/apache/iotdb/db/mqtt/JSONPayloadFormatter.java, server/src/main/java/org/apache/iotdb/db/mqtt/PayloadFormatter.java, server/src/test/java/org/apache/iotdb/db/mqtt/JSONPayloadFormatterTest.java
=> [ISSUE-4065] Reduce JSONPayloadFormatter#format deserialize measurements times

.github/workflows/client.yml
=> fix cpp client ci on macos

.github/workflows/client.yml
=> [To rel/0.12] fix Cpp client ci on macos

cluster/src/main/java/org/apache/iotdb/cluster/ClusterIoTDB.java, cluster/src/main/java/org/apache/iotdb/cluster/server/member/MetaGroupMember.java, cluster/src/main/java/org/apache/iotdb/cluster/server/service/DataGroupEngine.java, cluster/src/main/java/org/apache/iotdb/cluster/server/service/DataGroupEngineMBean.java, cluster/src/main/java/org/apache/iotdb/cluster/server/service/DataGroupServiceImpls.java, cluster/src/test/java/org/apache/iotdb/cluster/server/member/MetaGroupMemberTest.java
split DataGroupServiceImpls into engine and impls
=> [cluster-refactor]split DataGroupServiceImpls into engine and impls 

server/src/main/java/org/apache/iotdb/db/utils/FileLoaderUtils.java
Print the file path while meeting error in case of reading chunk
=> [To rel/0.12] Print the file path while meeting error in case of reading chunk

docs/zh/UserGuide/Comparison/TSDB-Comparison.md
=> 修改中文文档 TSDB-Comparison.md 中一处语句不通的地方

hive-connector/pom.xml, pom.xml
Solution :
- https://github.com/apache/hive/pull/2326
<hr>
This PR has:
<hr>
=> [ISSUE-4288] Fix CI issue caused by the invalid pentaho download url

server/src/assembly/resources/conf/iotdb-env.bat
=> [IOTDB-1914] fix information when start iotdb on windows 

server/src/assembly/resources/conf/iotdb-env.bat
=> [rel/0.12][IOTDB-1914] fix information when start iotdb on windows

server/src/assembly/resources/conf/iotdb-env.bat
=> [IOTDB-1714] fix Could not find or load main class when start with jmx on win

server/src/assembly/resources/conf/iotdb-env.bat
=> [To rel/0.12][IOTDB-1714] fix Could not find or load main class when start with jmx on win

example/session/src/main/java/org/apache/iotdb/AlignedTimeseriesSessionExample.java, example/session/src/main/java/org/apache/iotdb/HybridTimeseriesSessionExample.java, session/src/main/java/org/apache/iotdb/session/Session.java, session/src/main/java/org/apache/iotdb/session/pool/SessionPool.java, session/src/test/java/org/apache/iotdb/session/IoTDBSessionVectorAggregationIT.java, session/src/test/java/org/apache/iotdb/session/IoTDBSessionVectorInsertIT.java
Separate AlignedInsertPlan from current InsertPlan
=> [IOTDB-1672] Separate AlignedInsertPlan from current InsertPlan

server/src/main/java/org/apache/iotdb/db/qp/physical/PhysicalPlan.java, server/src/main/java/org/apache/iotdb/db/qp/physical/crud/UDTFPlan.java, server/src/main/java/org/apache/iotdb/db/service/TSServiceImpl.java, server/src/test/java/org/apache/iotdb/db/integration/auth/IoTDBAuthorizationIT.java
See ISSUE-4308 for more detail.
=> [To rel/0.12][ISSUE-4308] READ_TIMESERIES privilege granted to users and roles can not take effect when quering by UDFs

server/src/main/java/org/apache/iotdb/db/qp/physical/PhysicalPlan.java, server/src/main/java/org/apache/iotdb/db/qp/physical/crud/QueryPlan.java, server/src/main/java/org/apache/iotdb/db/qp/physical/crud/UDTFPlan.java, server/src/main/java/org/apache/iotdb/db/query/expression/ResultColumn.java, server/src/main/java/org/apache/iotdb/db/service/TSServiceImpl.java, server/src/test/java/org/apache/iotdb/db/integration/auth/IoTDBAuthorizationIT.java
See ISSUE-4308 for more detail.
=> [ISSUE-4308] READ_TIMESERIES privilege granted to users and roles can not take effect when quering by UDFs

cli/src/main/java/org/apache/iotdb/tool/ExportCsv.java
=> [To rel/0.12][IoTDB-1913] When exporting a amount of data, it will report network error or OOM

server/src/main/java/org/apache/iotdb/db/engine/StorageEngine.java, server/src/main/java/org/apache/iotdb/db/engine/storagegroup/virtualSg/VirtualStorageGroupManager.java, server/src/main/java/org/apache/iotdb/db/exception/StorageGroupNotReadyException.java, server/src/main/java/org/apache/iotdb/db/service/TSServiceImpl.java
There are too many logs like "sg may not ready now ", so i add StorageGroupNotReadyException and exclude it from server log.
=> [To rel/0.12][IOTDB-1958] Add storage group not ready exception

server/src/main/java/org/apache/iotdb/db/engine/StorageEngine.java, server/src/main/java/org/apache/iotdb/db/engine/storagegroup/virtualSg/VirtualStorageGroupManager.java, server/src/main/java/org/apache/iotdb/db/exception/StorageGroupNotReadyException.java, server/src/main/java/org/apache/iotdb/db/service/TSServiceImpl.java
There are too many logs like "sg may not ready now ", so i add StorageGroupNotReadyException and exclude it from server log.
=> [IOTDB-1958] Add storage group not ready exception

server/src/main/java/org/apache/iotdb/db/qp/physical/crud/UDTFPlan.java, server/src/main/java/org/apache/iotdb/db/query/expression/unary/TimeSeriesOperand.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBAliasIT.java
see https://issues.apache.org/jira/browse/IOTDB-1986
=> [IOTDB-1986] Support `select UDF as alisa` clauses

server/src/main/java/org/apache/iotdb/db/query/dataset/AlignByDeviceDataSet.java
Refactor the interaction with MManager while executing AlignByDevicePlan.
=> [To new_vector] Refactor the interaction with MManager while executing AlignByDevicePlan

cluster/src/main/java/org/apache/iotdb/cluster/query/fill/ClusterFillExecutor.java, server/src/main/java/org/apache/iotdb/db/query/dataset/RawQueryDataSetWithValueFilter.java, server/src/main/java/org/apache/iotdb/db/query/executor/AggregationExecutor.java
See JIRA: https://issues.apache.org/jira/browse/IOTDB-1990
=> [IOTDB-1990] Fix uncheck null result by calling IReaderByTimestamp

cluster/src/main/java/org/apache/iotdb/cluster/query/reader/DataSourceInfo.java, cluster/src/main/java/org/apache/iotdb/cluster/query/reader/mult/MultDataSourceInfo.java, server/src/main/java/org/apache/iotdb/db/query/control/QueryFileManager.java
I will add detailed docs later.
=> [To rel.0.12][IoTDB-1865]【Cluster】Compaction is blocking when removing old files

server/src/main/java/org/apache/iotdb/db/concurrent/threadpool/WrappedSingleThreadScheduledExecutor.java, server/src/main/java/org/apache/iotdb/db/engine/compaction/cross/AbstractCrossSpaceCompactionSelector.java, server/src/main/java/org/apache/iotdb/db/engine/compaction/inner/AbstractInnerSpaceCompactionSelector.java, server/src/main/java/org/apache/iotdb/db/engine/compaction/inner/sizetiered/SizeTieredCompactionRecoverTask.java, server/src/main/java/org/apache/iotdb/db/engine/compaction/task/AbstractCompactionTask.java, server/src/main/java/org/apache/iotdb/db/engine/flush/FlushManager.java, server/src/main/java/org/apache/iotdb/db/engine/modification/utils/TracedBufferedReader.java, server/src/main/java/org/apache/iotdb/db/metadata/mnode/EntityMNode.java, server/src/main/java/org/apache/iotdb/db/metadata/mnode/IEntityMNode.java, server/src/main/java/org/apache/iotdb/db/metadata/mnode/InternalMNode.java, server/src/main/java/org/apache/iotdb/db/qp/physical/crud/InsertMultiTabletPlan.java, server/src/main/java/org/apache/iotdb/db/qp/physical/crud/InsertRowsOfOneDevicePlan.java, server/src/main/java/org/apache/iotdb/db/qp/physical/crud/InsertRowsPlan.java, server/src/main/java/org/apache/iotdb/db/qp/physical/sys/CreateMultiTimeSeriesPlan.java, server/src/main/java/org/apache/iotdb/db/qp/utils/EmptyOutputStream.java
Add overwrite methods with @Override.  
@Override can improve code readability and help compiler check method relationship between superclass and subclass.
=> [IOTDB-2003] add overwrite method with @Override

cluster/src/main/java/org/apache/iotdb/cluster/query/reader/DataSourceInfo.java, cluster/src/main/java/org/apache/iotdb/cluster/query/reader/mult/MultDataSourceInfo.java, server/src/main/java/org/apache/iotdb/db/query/control/QueryFileManager.java
see[ analysis doc](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=195726564)
=> [IoTDB-1865]【Cluster】Compaction is blocking when removing old files 

server/src/main/java/org/apache/iotdb/db/engine/StorageEngine.java
Add redundant StorageGroupNotReadyException judgement In IOTDB-1958, so i remove it
=> [IOTDB-2001] Remove redundant StorageGroupNotReadyException

cli/src/main/java/org/apache/iotdb/tool/ImportCsv.java, cluster/src/main/java/org/apache/iotdb/cluster/log/applier/BaseApplier.java, cluster/src/main/java/org/apache/iotdb/cluster/query/reader/mult/RemoteMultSeriesReader.java, hive-connector/src/main/java/org/apache/iotdb/hive/TSFHiveRecordWriter.java, jdbc/src/main/java/org/apache/iotdb/jdbc/AbstractIoTDBJDBCResultSet.java, jdbc/src/main/java/org/apache/iotdb/jdbc/IoTDBDatabaseMetadata.java, jdbc/src/main/java/org/apache/iotdb/jdbc/StringUtils.java, server/src/main/java/org/apache/iotdb/db/engine/memtable/WritableMemChunk.java, server/src/main/java/org/apache/iotdb/db/engine/modification/io/LocalTextModificationAccessor.java, server/src/main/java/org/apache/iotdb/db/engine/modification/utils/TracedBufferedReader.java, server/src/main/java/org/apache/iotdb/db/engine/storagegroup/TsFileResource.java, server/src/main/java/org/apache/iotdb/db/metadata/template/Template.java, server/src/main/java/org/apache/iotdb/db/metadata/template/TemplateManager.java, server/src/main/java/org/apache/iotdb/db/qp/executor/PlanExecutor.java, server/src/main/java/org/apache/iotdb/db/qp/logical/crud/LikeOperator.java, server/src/main/java/org/apache/iotdb/db/qp/logical/crud/RegexpOperator.java, server/src/main/java/org/apache/iotdb/db/tools/settle/TsFileAndModSettleTool.java, session/src/main/java/org/apache/iotdb/session/template/InternalNode.java, tsfile/src/main/java/org/apache/iotdb/tsfile/read/filter/GroupByFilter.java, tsfile/src/main/java/org/apache/iotdb/tsfile/read/filter/operator/Like.java, tsfile/src/main/java/org/apache/iotdb/tsfile/utils/FilePathUtils.java, tsfile/src/main/java/org/apache/iotdb/tsfile/utils/StringContainer.java
JIRA: https://issues.apache.org/jira/browse/IOTDB-2005  
Braces are used with if, else, for, do and while statements, even if the body contains only a single statement.
=> [IOTDB-2005] use braces with if, else, for, do and while statements

cluster/src/main/java/org/apache/iotdb/cluster/query/LocalQueryExecutor.java, server/src/main/java/org/apache/iotdb/db/query/aggregation/AggregateResult.java, server/src/main/java/org/apache/iotdb/db/query/aggregation/impl/FirstValueAggrResult.java, server/src/main/java/org/apache/iotdb/db/query/aggregation/impl/FirstValueDescAggrResult.java, server/src/test/java/org/apache/iotdb/db/query/aggregation/DescAggregateResultTest.java
This is the cherry-pick of #4373 
JIRA: https://issues.apache.org/jira/browse/IOTDB-1997
As 0.12.3 RC2 codes have been frozen, this fix may be published in v0.12.4. So the RELEASE_NOTE.md is not updated.
=> [To rel/0.12][IOTDB-1997]Fix bug of descending aggregation query

cluster/src/main/java/org/apache/iotdb/cluster/query/ClusterQueryRouter.java, cluster/src/main/java/org/apache/iotdb/cluster/query/LocalQueryExecutor.java, cluster/src/main/java/org/apache/iotdb/cluster/query/groupby/ClusterGroupByFillNoVFilterDataSet.java, cluster/src/main/java/org/apache/iotdb/cluster/query/groupby/ClusterGroupByVFilterDataSet.java, cluster/src/main/java/org/apache/iotdb/cluster/query/groupby/RemoteGroupByExecutor.java, cluster/src/test/java/org/apache/iotdb/cluster/query/groupby/ClusterGroupByNoVFilterDataSetTest.java, cluster/src/test/java/org/apache/iotdb/cluster/query/groupby/ClusterGroupByVFilterDataSetTest.java, server/src/main/java/org/apache/iotdb/db/query/dataset/groupby/GroupByFillWithoutValueFilterDataSet.java, server/src/main/java/org/apache/iotdb/db/query/dataset/groupby/GroupByWithValueFilterDataSet.java, server/src/main/java/org/apache/iotdb/db/query/dataset/groupby/GroupByWithoutValueFilterDataSet.java, server/src/main/java/org/apache/iotdb/db/query/executor/QueryRouter.java
See JIRA: https://issues.apache.org/jira/browse/IOTDB-2008
Because the `GroupByFillDataSet` has been refined totally, I don't know whether BUG1 described in JIRA has been fixed.
If so, I will open a new PR to fix it in rel/0.12 branch.
=> [IOTDB-2008] Fix null result bug of GROUP BY FILL query

cluster/src/main/java/org/apache/iotdb/cluster/query/fill/ClusterFillExecutor.java, cluster/src/main/java/org/apache/iotdb/cluster/query/fill/ClusterLinearFill.java, cluster/src/main/java/org/apache/iotdb/cluster/query/fill/ClusterPreviousFill.java, cluster/src/main/java/org/apache/iotdb/cluster/server/handlers/caller/PreviousFillHandler.java, server/src/main/java/org/apache/iotdb/db/query/executor/FillQueryExecutor.java, server/src/main/java/org/apache/iotdb/db/query/executor/fill/IFill.java, server/src/main/java/org/apache/iotdb/db/query/executor/fill/PreviousFill.java
See: https://issues.apache.org/jira/browse/IOTDB-2009
=> [IOTDB-2009] fix incorrect previous filling

session/src/test/resources/iotdb-rest.properties, site/src/main/.vuepress/config.js
Fix the missing iotdb-rest.properties file during session module testing, and add the rest service user manual reference in the API
=> [IOTDB-1859][Minor Fix] Fixed REST config read bug in Session IT && Added REST service user doc into the API module

docs/UserGuide/Cluster/Cluster-Setup-Example.md, docs/zh/UserGuide/Cluster/Cluster-Setup-Example.md
remove the unnecessary modification such as data dir
=> Make the cluster setup example doc clear

metrics/micrometer-metrics/src/main/java/org/apache/iotdb/metrics/micrometer/MicrometerMetricManager.java
see jira
https://issues.apache.org/jira/browse/IOTDB-2015
=> [IOTDB-2015] [metric] micrometer jvmGcMetrics cannot get gc pause time and counter

metrics/dropwizard-metrics/src/main/java/org/apache/iotdb/metrics/dropwizard/DropwizardMetricManager.java, metrics/dropwizard-metrics/src/test/java/org/apache/iotdb/metrics/dropwizard/DropwizardMetricManagerTest.java, metrics/interface/src/main/java/org/apache/iotdb/metrics/MetricManager.java, metrics/interface/src/main/java/org/apache/iotdb/metrics/impl/DoNothingMetricManager.java, metrics/micrometer-metrics/src/main/java/org/apache/iotdb/metrics/micrometer/MicrometerMetricManager.java, metrics/micrometer-metrics/src/main/java/org/apache/iotdb/metrics/micrometer/reporter/MicrometerPrometheusReporter.java
see jira
https://issues.apache.org/jira/browse/IOTDB-2014
=> [IOTDB-2014] MicrometerPrometheusReporter#getReporterType return null

example/session/src/main/java/org/apache/iotdb/SessionExample.java, session/src/main/java/org/apache/iotdb/session/SessionDataSet.java
see https://issues.apache.org/jira/browse/IOTDB-2022
=> [IOTDB-2022] SessionDataSet implements AutoCloseable

client-py/SessionExample.py, client-py/iotdb/utils/SessionDataSet.py
1. implements contextor for SessionDataSet
2. update SessionExample
**JIRA**: https://issues.apache.org/jira/browse/IOTDB-2026
=> [IOTDB-2026] Python API: SessionDataSet implements Contextor

cluster/src/main/java/org/apache/iotdb/cluster/query/ClusterPlanExecutor.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBMetadataFetchIT.java
See JIRA: https://issues.apache.org/jira/browse/IOTDB-2025
Fix the following bugs:
1. **COUNT DEVICES** in cluster mode.
2. **COUNT NODES** in cluster mode.
=> [IOTDB-2025] Fix count nodes and devices incorrectly in cluster

docs/Download/README.md, docs/zh/Download/README.md
=> add v0.12.3 download links

site/pom.xml, site/src/main/.vuepress/config.js
This PR is fixing two issues.
1. Fix Measurement-Template to Schema-Template in config.js.
2. Fix removing non-existing sourceFile.
=> Fix website build errors

server/src/main/java/org/apache/iotdb/db/engine/querycontext/AlignedReadOnlyMemChunk.java, server/src/main/java/org/apache/iotdb/db/query/reader/chunk/MemAlignedChunkLoader.java, server/src/main/java/org/apache/iotdb/db/query/reader/chunk/MemAlignedChunkReader.java, server/src/main/java/org/apache/iotdb/db/query/reader/chunk/MemAlignedPageReader.java, server/src/main/java/org/apache/iotdb/db/query/reader/series/SeriesReader.java, tsfile/src/main/java/org/apache/iotdb/tsfile/read/reader/IAlignedPageReader.java, tsfile/src/main/java/org/apache/iotdb/tsfile/read/reader/page/AlignedPageReader.java
Fix exception when getting Statistics of aligned time series in memory.
=> Fix exception when getting Statistics of aligned time series in memory

cluster/src/main/java/org/apache/iotdb/cluster/server/ClusterTSServiceImpl.java, server/src/main/java/org/apache/iotdb/db/conf/IoTDBConstant.java, server/src/main/java/org/apache/iotdb/db/rest/handler/AuthorizationHandler.java, server/src/main/java/org/apache/iotdb/db/rest/impl/RestApiServiceImpl.java, server/src/main/java/org/apache/iotdb/db/service/basic/BasicServiceProvider.java
see :https://issues.apache.org/jira/browse/IOTDB-2036
=> [IOTDB-2036] RestApiServiceImpl accesses to BasicServiceProvider

tsfile/src/main/java/org/apache/iotdb/tsfile/read/filter/GroupByMonthFilter.java, tsfile/src/main/java/org/apache/iotdb/tsfile/read/filter/factory/FilterFactory.java, tsfile/src/main/java/org/apache/iotdb/tsfile/read/filter/factory/FilterSerializeId.java, tsfile/src/main/java/org/apache/iotdb/tsfile/read/filter/operator/In.java, tsfile/src/test/java/org/apache/iotdb/tsfile/read/filter/FilterSerializeTest.java
A cherry-pick of #4414 
JIRA: https://issues.apache.org/jira/browse/IOTDB-2023
=> [To rel/0.12][IOTDB-2023] Fix serializing and deserializing bugs of Filters

cluster/src/main/java/org/apache/iotdb/cluster/query/ClusterPlanExecutor.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBMetadataFetchIT.java
A cherry-pick of #4416 
JIRA: https://issues.apache.org/jira/browse/IOTDB-2025
=> [To rel/0.12][IOTDB-2025] Fix count nodes and devices incorrectly in cluster

server/src/main/java/org/apache/iotdb/db/mqtt/PublishHandler.java, server/src/main/java/org/apache/iotdb/db/service/basic/BasicServiceProvider.java, server/src/test/java/org/apache/iotdb/db/mqtt/PublishHandlerTest.java
see : https://issues.apache.org/jira/browse/IOTDB-2038
=> [IOTDB-2038] MqttService accesses to BasicServiceProvider

site/pom.xml
The previous v12.16.2 didn't support ARM macos machine, upgrade the node version to fix it. 
<hr>
This PR has:
<hr>
=> Bump nodeVersion in site deploy to v16.9.1 to support building website on ARM mac

server/src/main/java/org/apache/iotdb/db/utils/MemUtils.java, server/src/test/java/org/apache/iotdb/db/utils/MemUtilsTest.java, session/src/test/java/org/apache/iotdb/session/IoTDBDisableMemControlSessionIT.java, session/src/test/java/org/apache/iotdb/session/IoTDBSessionDisableMemControlIT.java
=> [To rel/0.12] [IOTDB-2047] Fix NPE when memControl is disabled and insert TEXT value to a non-TEXT series

server/src/main/java/org/apache/iotdb/db/engine/memtable/AbstractMemTable.java, server/src/main/java/org/apache/iotdb/db/metadata/MManager.java, server/src/main/java/org/apache/iotdb/db/qp/physical/crud/InsertPlan.java, server/src/main/java/org/apache/iotdb/db/utils/MemUtils.java, server/src/test/java/org/apache/iotdb/db/metadata/MManagerBasicTest.java, server/src/test/java/org/apache/iotdb/db/utils/MemUtilsTest.java, session/src/test/java/org/apache/iotdb/session/IoTDBSessionDisableMemControlIT.java, session/src/test/java/org/apache/iotdb/session/IoTDBSessionSimpleIT.java, session/src/test/java/org/apache/iotdb/session/IoTDBSessionVectorInsertIT.java
Fixing IOTDB-2047 .
This pr is also fixing NPE when insert aligned tablet in similar scene.
=> [IOTDB-2047] Fix Partial insert NPE for aligned and non-aligned series

cluster/src/main/java/org/apache/iotdb/cluster/query/ClusterDataQueryExecutor.java, cluster/src/main/java/org/apache/iotdb/cluster/query/reader/mult/AssignPathAscPriorityMergeReader.java, cluster/src/main/java/org/apache/iotdb/cluster/query/reader/mult/AssignPathDescPriorityMergeReader.java, cluster/src/main/java/org/apache/iotdb/cluster/query/reader/mult/AssignPathManagedMergeReader.java, cluster/src/main/java/org/apache/iotdb/cluster/query/reader/mult/IAssignPathPriorityMergeReader.java, cluster/src/main/java/org/apache/iotdb/cluster/query/reader/mult/MultElement.java, cluster/src/test/java/org/apache/iotdb/cluster/query/reader/mult/AssignPathManagedMergeReaderTest.java
See JIRA: https://issues.apache.org/jira/browse/IOTDB-2032
=> [IOTDB-2031] Fix incorrect result of descending query with multiple time partitions

cluster/src/main/java/org/apache/iotdb/cluster/query/reader/ClusterReaderFactory.java, server/src/main/java/org/apache/iotdb/db/query/reader/series/SeriesReader.java, server/src/main/java/org/apache/iotdb/db/query/reader/series/SeriesReaderByTimestamp.java, tsfile/src/main/java/org/apache/iotdb/tsfile/read/filter/TimeFilter.java
See JIRA: https://issues.apache.org/jira/browse/IOTDB-2031
=> [IOTDB-2031] Fix incorrect result of descending query with value filter in cluster

cluster/src/main/java/org/apache/iotdb/cluster/query/reader/ClusterReaderFactory.java, server/src/main/java/org/apache/iotdb/db/query/reader/series/SeriesReaderByTimestamp.java, tsfile/src/main/java/org/apache/iotdb/tsfile/read/filter/TimeFilter.java
The cherry-pick of #4431 
JIRA: https://issues.apache.org/jira/browse/IOTDB-2031
=> [To rel/0.12][IOTDB-2031] Fix incorrect result of descending query with value filter in cluster

cluster/src/main/java/org/apache/iotdb/cluster/query/ClusterDataQueryExecutor.java, cluster/src/main/java/org/apache/iotdb/cluster/query/reader/mult/AssignPathAscPriorityMergeReader.java, cluster/src/main/java/org/apache/iotdb/cluster/query/reader/mult/AssignPathDescPriorityMergeReader.java, cluster/src/main/java/org/apache/iotdb/cluster/query/reader/mult/AssignPathManagedMergeReader.java, cluster/src/main/java/org/apache/iotdb/cluster/query/reader/mult/IAssignPathPriorityMergeReader.java, cluster/src/main/java/org/apache/iotdb/cluster/query/reader/mult/MultElement.java, cluster/src/test/java/org/apache/iotdb/cluster/query/reader/mult/AssignPathManagedMergeReaderTest.java
The cherry-pick of #4432 
JIRA: https://issues.apache.org/jira/browse/IOTDB-2032
=> [To rel/0.12][IOTDB-2032] Fix incorrect result of descending query with multiple time partitions

server/src/main/java/org/apache/iotdb/db/engine/memtable/AbstractMemTable.java, server/src/main/java/org/apache/iotdb/db/engine/memtable/WritableMemChunkGroup.java, server/src/test/java/org/apache/iotdb/db/engine/memtable/PrimitiveMemTableTest.java
To reproduce, see IOTDB-2056.
Fix avgSeriesPointNumThreshold calculate error.
=> [IOTDB-2056] Fix totalPointsNumThreshold calculation error causes too many tsfile flushed

cluster/src/main/java/org/apache/iotdb/cluster/metadata/CMManager.java, cluster/src/main/java/org/apache/iotdb/cluster/server/handlers/caller/ShowTimeSeriesHandler.java, cluster/src/main/java/org/apache/iotdb/cluster/server/handlers/caller/ShowTimeseriesHandler.java
See: https://issues.apache.org/jira/browse/IOTDB-2010
=> [IOTDB-2010] fix incomplete show timeseries result

tsfile/src/main/java/org/apache/iotdb/tsfile/utils/ReadWriteIOUtils.java, tsfile/src/test/java/org/apache/iotdb/tsfile/utils/ReadWriteIOUtilsTest.java
See: https://issues.apache.org/jira/browse/IOTDB-2064
=> [IOTDB-2064] fix the NPE caused by map serde

server/src/main/java/org/apache/iotdb/db/query/aggregation/impl/MinTimeDescAggrResult.java
See JIRA: https://issues.apache.org/jira/browse/IOTDB-2063
=> [IOTDB-2063] Fix MinTimeDescAggrResult implementation

server/src/main/java/org/apache/iotdb/db/engine/storagegroup/StorageGroupProcessor.java, server/src/main/java/org/apache/iotdb/db/engine/storagegroup/TsFileProcessor.java
Add writelock, wal, memtable cost time
=> Add writelock, wal, memtable time

server/src/main/java/org/apache/iotdb/db/query/aggregation/impl/MinTimeDescAggrResult.java
=> [To rel/0.12][IOTDB-2063] Fix MinTimeDescAggregationResult implementation

pom.xml, tsfile/pom.xml
=> Upgrade lz4 from 1.3.0 to 1.8.0 due to CVE-2019-17543

server/src/assembly/resources/conf/iotdb-env.bat, server/src/assembly/resources/conf/iotdb-env.sh
=> [To rel/0.12] [IOTDB-2061] Add max cached buffer size configuration

tsfile/src/main/java/org/apache/iotdb/tsfile/read/TsFileSequenceReader.java
cherry pick from https://github.com/apache/iotdb/pull/4490
=> [To rel/0.12] [IOTDB-2061] Read data in batches to limit max IO

cli/src/main/java/org/apache/iotdb/cli/utils/JlineUtils.java
See: https://issues.apache.org/jira/browse/IOTDB-2070
=> [IOTDB-2070] fix CLI doesn't accept statements with unclosed brackets

tsfile/src/main/java/org/apache/iotdb/tsfile/utils/ReadWriteIOUtils.java, tsfile/src/test/java/org/apache/iotdb/tsfile/utils/ReadWriteIOUtilsTest.java
=> [To rel/0.12][IOTDB-2064] fix the NPE caused by map serde (#4473)

server/src/main/java/org/apache/iotdb/db/qp/logical/crud/FillQueryOperator.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBFillIT.java, server/src/test/java/org/apache/iotdb/db/qp/physical/PhysicalPlanTest.java
See: https://issues.apache.org/jira/browse/IOTDB-2060
=> [IOTDB-2060] NPE when using fill without a filter

antlr/src/main/antlr4/org/apache/iotdb/db/qp/sql/SqlBase.g4, client-cpp/pom.xml, compile-tools/pom.xml, distribution/pom.xml, example/client-cpp-example/pom.xml, example/udf/pom.xml, grafana/pom.xml, jdbc/pom.xml, pom.xml, server/src/main/java/org/apache/iotdb/db/qp/logical/crud/GroupByLevelController.java, server/src/main/java/org/apache/iotdb/db/qp/logical/crud/QueryOperator.java, server/src/main/java/org/apache/iotdb/db/qp/logical/crud/SFWOperator.java, server/src/main/java/org/apache/iotdb/db/qp/logical/crud/SelectOperator.java, server/src/main/java/org/apache/iotdb/db/qp/physical/crud/AggregationPlan.java, server/src/main/java/org/apache/iotdb/db/qp/sql/IoTDBSqlVisitor.java, server/src/main/java/org/apache/iotdb/db/qp/strategy/PhysicalGenerator.java, server/src/main/java/org/apache/iotdb/db/qp/strategy/optimizer/ConcatPathOptimizer.java, server/src/main/java/org/apache/iotdb/db/query/dataset/groupby/GroupByTimeDataSet.java, server/src/main/java/org/apache/iotdb/db/query/executor/AggregationExecutor.java, server/src/main/java/org/apache/iotdb/db/query/executor/QueryRouter.java, server/src/main/java/org/apache/iotdb/db/service/TSServiceImpl.java, server/src/main/java/org/apache/iotdb/db/utils/AggregateUtils.java, server/src/test/java/org/apache/iotdb/db/integration/aggregation/IoTDBAggregationByLevelIT.java, server/src/test/java/org/apache/iotdb/db/query/dataset/groupby/GroupByLevelDataSetTest.java
=> [To rel/0.12] IOTDB-1823 group by multi level

server/src/main/java/org/apache/iotdb/db/query/reader/series/SeriesReader.java
JIRA link: https://issues.apache.org/jira/browse/IOTDB-2077
=> [IOTDB-2077] Unexpected exception when executing raw data query without VF with limit clause

integration/src/test/java/org/apache/iotdb/db/integration/aggregation/IoTDBAggregationByLevelIT.java, integration/src/test/java/org/apache/iotdb/db/integration/aggregation/IoTDBAggregationSmallDataIT.java, server/src/main/java/org/apache/iotdb/db/qp/physical/crud/AggregationPlan.java
See JIRA: https://issues.apache.org/jira/browse/IOTDB-2088
=> [IOTDB-2088] Fix IndexOutOfBound exception in AggregationPlan.groupAggResultByLevel

server/src/main/java/org/apache/iotdb/db/query/dataset/RawQueryDataSetWithoutValueFilter.java, server/src/main/java/org/apache/iotdb/db/query/dataset/UDFRawQueryInputDataSetWithoutValueFilter.java, server/src/main/java/org/apache/iotdb/db/query/udf/core/input/InputLayer.java
=> [To rel/0.12] [IOTDB-2102] Push down limit to ReadTask in RawDataSetWithoutValueFilter

Jenkinsfile
https://ci-builds.apache.org/job/IoTDB/job/IoTDB-Pipe/job/master/
=> Fix deploying site fail caused by CI issue

integration/src/test/java/org/apache/iotdb/db/integration/IoTDBAliasIT.java, server/src/main/java/org/apache/iotdb/db/qp/physical/crud/UDTFPlan.java, server/src/main/java/org/apache/iotdb/db/query/expression/unary/TimeSeriesOperand.java
see https://issues.apache.org/jira/browse/IOTDB-2129
=> [IOTDB-2129] Wrong result returned when querying by nested expressions with aliases

server/src/test/java/org/apache/iotdb/db/sink/MQTTSinkTest.java
See IOTDB-2130 for more detail.
=> [IOTDB-2130] IT fails on MQTTSinkTest.onEventUsingMultiSensorsHandler

server/src/assembly/resources/conf/iotdb-engine.properties, server/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java
See: https://issues.apache.org/jira/browse/IOTDB-2135
=> [IOTDB-2135] Add configuration for influx DB RPC service

server/src/main/java/org/apache/iotdb/db/query/dataset/UDTFDataSet.java
See JIRA: https://issues.apache.org/jira/browse/IOTDB-2137
=> [IOTDB-2137] Fix incorrect column num in UDTFDataSet

integration/src/main/java/org/apache/iotdb/integration/env/ClusterEnvBase.java, integration/src/main/java/org/apache/iotdb/integration/env/ClusterNode.java
1. disable Influx DB RPC service to avoid port conflict
=> Fix IT framework

integration/src/test/java/org/apache/iotdb/db/integration/aggregation/IoTDBUDFNestAggregationIT.java, server/src/main/java/org/apache/iotdb/db/utils/TypeInferenceUtils.java
See JIRA: https://issues.apache.org/jira/browse/IOTDB-2151
=> [IOTDB-2151] Fix extreme() not supported in nested expression query

integration/src/test/java/org/apache/iotdb/session/IoTDBSessionSimpleIT.java, server/src/main/java/org/apache/iotdb/db/metadata/MManager.java, server/src/test/java/org/apache/iotdb/db/metadata/MManagerBasicTest.java
See: https://issues.apache.org/jira/browse/IOTDB-2136
=> [IOTDB-2136] fix timeseries deletion issue

cluster/src/main/java/org/apache/iotdb/cluster/query/ClusterPlanExecutor.java, cluster/src/main/java/org/apache/iotdb/cluster/query/aggregate/ClusterAggregator.java, cluster/src/main/java/org/apache/iotdb/cluster/query/reader/ClusterReaderFactory.java, cluster/src/main/java/org/apache/iotdb/cluster/server/service/DataSyncService.java, cluster/src/main/java/org/apache/iotdb/cluster/utils/PartitionUtils.java, integration/src/test/java/org/apache/iotdb/db/integration/IoTDBMetadataFetchIT.java, integration/src/test/java/org/apache/iotdb/db/integration/IoTDBTtlIT.java, integration/src/test/java/org/apache/iotdb/db/integration/aggregation/IoTDBAggregationLargeDataIT.java, integration/src/test/java/org/apache/iotdb/db/integration/aggregation/IoTDBAggregationSmallDataIT.java, server/src/main/java/org/apache/iotdb/db/utils/ErrorHandlingUtils.java, tsfile/src/main/java/org/apache/iotdb/tsfile/exception/write/UnSupportedDataTypeException.java
See JIRA: https://issues.apache.org/jira/browse/IOTDB-2141
Some IT cases related issues have been fixed.
=> [IOTDB-2141] Fix some issues in cluster test

cluster/src/main/java/org/apache/iotdb/cluster/query/reader/ClusterReaderFactory.java
See [jira2160](https://issues.apache.org/jira/browse/IOTDB-2160)
=> [To rel/0.12][IOTDB-2160] Fix cluster groupby memory leak

cluster/src/main/java/org/apache/iotdb/cluster/query/reader/ClusterReaderFactory.java
See [jira2160](https://issues.apache.org/jira/browse/IOTDB-2160)
=> [IOTDB-2160] Fix cluster groupby memory leak

cluster/src/main/java/org/apache/iotdb/cluster/server/ClusterTSServiceImpl.java, cluster/src/main/java/org/apache/iotdb/cluster/utils/StatusUtils.java, integration/src/test/java/org/apache/iotdb/db/integration/IoTDBSetSystemReadOnlyWritableIT.java, server/src/main/java/org/apache/iotdb/db/exception/StorageEngineReadonlyException.java, server/src/main/java/org/apache/iotdb/db/service/basic/BasicServiceProvider.java, testcontainer/src/test/java/org/apache/iotdb/db/sql/Cases.java
See JIRA: https://issues.apache.org/jira/browse/IOTDB-2159
=> [IOTDB-2159] Fix wrong status code when inserting data to a read-only cluster

integration/src/test/java/org/apache/iotdb/db/integration/IoTDBFlushQueryMergeIT.java
See JIRA: https://issues.apache.org/jira/browse/IOTDB-2164
=> [IOTDB-2164] Fix IoTDBFlushQueryMergeIT

cluster/src/assembly/resources/sbin/start-node.bat, server/src/assembly/resources/conf/iotdb-env.bat, server/src/assembly/resources/sbin/start-server.bat
See JIRA: https://issues.apache.org/jira/browse/IOTDB-2169
=> [IOTDB-2169] Fix iotdb-env.bat error in Windows platform

cluster/src/assembly/resources/sbin/start-node.bat, server/src/assembly/resources/conf/iotdb-env.bat, server/src/assembly/resources/sbin/start-server.bat
=> [To rel/0.12][IOTDB-2169] Fix iotdb-env.bat error in Windows platform

tsfile/src/main/java/org/apache/iotdb/tsfile/read/filter/factory/FilterFactory.java, tsfile/src/main/java/org/apache/iotdb/tsfile/read/filter/operator/Regexp.java, tsfile/src/test/java/org/apache/iotdb/tsfile/read/filter/FilterSerializeTest.java
See JIRA: https://issues.apache.org/jira/browse/IOTDB-2174
=> [IOTDB-2174] Fix Regexp filter serializing and deserializing error

server/src/main/java/org/apache/iotdb/db/qp/utils/WildcardsRemover.java
See JIRA: https://issues.apache.org/jira/browse/IOTDB-2163
=> [IOTDB-2163] Fix unexpected amount of columns in a cluster slimit query

cluster/src/main/java/org/apache/iotdb/cluster/metadata/CMManager.java, cluster/src/main/java/org/apache/iotdb/cluster/query/LocalQueryExecutor.java
See: https://issues.apache.org/jira/browse/IOTDB-2143
=> [IOTDB-2143] fix wrong precision in cluster mode

cluster/src/main/java/org/apache/iotdb/cluster/server/handlers/caller/ShowTimeSeriesHandler.java, server/src/main/java/org/apache/iotdb/db/metadata/MManager.java, server/src/main/java/org/apache/iotdb/db/query/dataset/ShowTimeSeriesResult.java, server/src/test/java/org/apache/iotdb/db/query/dataset/ShowTimeSeriesResultTest.java
See JIRA: https://issues.apache.org/jira/browse/IOTDB-2180
=> [IOTDB-2180] Fix show latest timeseries in cluster

site/src/main/.vuepress/theme/global-components/Contributor.vue
I am now realizing that my committer information on the website is wrong :D
=> Site: Update committer info for SteveYurongSu

antlr/src/main/antlr4/org/apache/iotdb/db/qp/sql/SqlBase.g4, cluster/src/test/java/org/apache/iotdb/cluster/query/groupby/MergeGroupByExecutorTest.java, cluster/src/test/java/org/apache/iotdb/cluster/query/groupby/RemoteGroupByExecutorTest.java, cluster/src/test/java/org/apache/iotdb/cluster/server/member/DataGroupMemberTest.java, docs/UserGuide/Appendix/SQL-Reference.md, docs/UserGuide/IoTDB-SQL-Language/DML-Data-Manipulation-Language.md, docs/zh/UserGuide/Appendix/SQL-Reference.md, docs/zh/UserGuide/IoTDB-SQL-Language/DML-Data-Manipulation-Language.md, server/src/main/java/org/apache/iotdb/db/qp/constant/SQLConstant.java, server/src/main/java/org/apache/iotdb/db/query/aggregation/AggregationType.java, server/src/main/java/org/apache/iotdb/db/query/aggregation/impl/ExtremeAggrResult.java, server/src/main/java/org/apache/iotdb/db/query/factory/AggregateResultFactory.java, server/src/test/java/org/apache/iotdb/db/constant/TestConstant.java, server/src/test/java/org/apache/iotdb/db/integration/aggregation/IoTDBAggregationIT.java, server/src/test/java/org/apache/iotdb/db/integration/aggregation/IoTDBAggregationLargeDataIT.java, server/src/test/java/org/apache/iotdb/db/integration/aggregation/IoTDBAggregationSmallDataIT.java, server/src/test/java/org/apache/iotdb/db/query/aggregation/AggregateResultTest.java
Support extreme function in v0.12
cherry-pick from [#3289](https://github.com/apache/iotdb/pull/3289)
=> [To rel/0.12] [IOTDB-2192] Support extreme function

docs/SystemDesign/TsFile/Format.md, docs/zh/SystemDesign/TsFile/Format.md
Correct an error in the TsFile format document.
=> [Docs] Correct an error in the TsFile format document

tsfile/src/main/java/org/apache/iotdb/tsfile/read/filter/factory/FilterFactory.java, tsfile/src/main/java/org/apache/iotdb/tsfile/read/filter/operator/Regexp.java, tsfile/src/test/java/org/apache/iotdb/tsfile/read/filter/FilterSerializeTest.java
=> [To rel/0.12][IOTDB-2174] Fix Regexp filter serializing and deserializing error

server/src/main/java/org/apache/iotdb/db/qp/physical/crud/AggregationPlan.java, server/src/main/java/org/apache/iotdb/db/qp/physical/crud/AlignByDevicePlan.java, server/src/main/java/org/apache/iotdb/db/qp/physical/crud/GroupByTimePlan.java, server/src/main/java/org/apache/iotdb/db/qp/physical/crud/UDAFPlan.java, server/src/main/java/org/apache/iotdb/db/qp/physical/crud/UDTFPlan.java, server/src/main/java/org/apache/iotdb/db/service/thrift/impl/TSServiceImpl.java
I did some work based on #4640
=> [IOTDB-2208] Reconstruct the process of generating resultset header of query - Part2

cluster/src/test/java/org/apache/iotdb/cluster/query/ClusterDataQueryExecutorTest.java, cluster/src/test/java/org/apache/iotdb/cluster/query/reader/ClusterReaderFactoryTest.java, server/src/main/java/org/apache/iotdb/db/query/control/QueryResourceManager.java
=> [To rel/0.12] [IOTDB-2219] Bug fix: query in-memory data is incorrect in cluster mode

server/src/main/java/org/apache/iotdb/db/service/RegisterManager.java, server/src/main/java/org/apache/iotdb/db/utils/EnvironmentUtils.java
See JIRA: https://issues.apache.org/jira/browse/IOTDB-2220
=> [IOTDB-2220] Fix unit tests too slow issue caused by the MQTTService

cluster/src/main/java/org/apache/iotdb/cluster/metadata/CMManager.java, cluster/src/main/java/org/apache/iotdb/cluster/query/ClusterPlanExecutor.java, server/src/main/java/org/apache/iotdb/db/engine/StorageEngine.java, server/src/main/java/org/apache/iotdb/db/metadata/MManager.java, server/src/main/java/org/apache/iotdb/db/metadata/mtree/MTree.java, server/src/main/java/org/apache/iotdb/db/metadata/path/PartialPath.java, server/src/test/java/org/apache/iotdb/db/metadata/PartialPathTest.java
See: https://issues.apache.org/jira/browse/IOTDB-2153 and https://issues.apache.org/jira/browse/IOTDB-2157
=> [IOTDB-2153][IOTDB-2157] fix wildcard issues

cluster/src/test/java/org/apache/iotdb/cluster/query/reader/mult/AssignPathManagedMergeReaderTest.java, cluster/src/test/java/org/apache/iotdb/cluster/query/reader/mult/RemoteMultSeriesReaderTest.java, cluster/src/test/java/org/apache/iotdb/cluster/server/member/DataGroupMemberTest.java, integration/src/test/java/org/apache/iotdb/db/integration/IoTDBDeletionIT.java, integration/src/test/java/org/apache/iotdb/db/integration/IoTDBMergeIT.java, integration/src/test/java/org/apache/iotdb/db/integration/IoTDBMultiDeviceIT.java, integration/src/test/java/org/apache/iotdb/db/integration/IoTDBRestartIT.java, integration/src/test/java/org/apache/iotdb/db/integration/aligned/IoTDBDeletionIT.java, session/src/test/java/org/apache/iotdb/session/IoTDBSessionVectorInsertIT.java, tsfile/src/test/java/org/apache/iotdb/tsfile/encoding/decoder/IntRleDecoderTest.java, tsfile/src/test/java/org/apache/iotdb/tsfile/encoding/decoder/regular/RegularDataEncoderLongTest.java
See JIRA: https://issues.apache.org/jira/browse/IOTDB-2224
=> [IOTDB-2224] Accelerate tests by using batch insert

Jenkinsfile
Fix ci in https://ci-builds.apache.org/job/IoTDB/job/IoTDB-Pipe/job/master/
=> fix jenkins CI disable testcontainer

Jenkinsfile
=> Fix jenkins ci

tsfile/src/main/java/org/apache/iotdb/tsfile/read/TsFileSequenceReader.java, tsfile/src/test/java/org/apache/iotdb/tsfile/write/MetadataIndexConstructorTest.java
* Provide an iterator to return timeseries Path in dictionary order
* Add unit tests accordingly with all occasions
=> [IOTDB-2217] Provide an iterator to return timeseries Path in dictionary order

grafana-plugin/src/datasource.ts
fixed issue-4651，Adding supports querying an un created time series
=> [ISSUE-4651][grafana-plugin] Failed to display data when executing aggregation queries on non-existed timeseries

server/src/main/java/org/apache/iotdb/db/qp/strategy/PhysicalGenerator.java
=> [To rel/0.12] [IOTDB-2232] Throw an exception when use last and align by device together

tsfile/src/main/java/org/apache/iotdb/tsfile/read/TsFileSequenceReader.java, tsfile/src/test/java/org/apache/iotdb/tsfile/read/GetAllDevicesTest.java, tsfile/src/test/java/org/apache/iotdb/tsfile/utils/FileGenerator.java, tsfile/src/test/java/org/apache/iotdb/tsfile/write/MetadataIndexConstructorTest.java
* Provide an iterator to return devices in dictionary order, with whether the device is aligned
* Add unit tests accordingly with all occasions
=> [IOTDB-2228] Provide an iterator to return devices in dictionary order

code-coverage/pom.xml
see https://issues.apache.org/jira/browse/IOTDB-2237
=> [IOTDB-2237] coverage check encludes influxdb target

site/src/main/.vuepress/config.js
Fixed a bug that homepage doesn't show correctly.
<hr>
This PR has:
<hr>
=> [IOTDB-2239] Hompage Sidebar Rearrangement

server/src/assembly/resources/conf/iotdb-engine.properties, server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java, server/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java, server/src/main/java/org/apache/iotdb/db/engine/storagegroup/StorageGroupProcessor.java, server/src/main/java/org/apache/iotdb/db/writelog/manager/MultiFileLogNodeManager.java, server/src/test/java/org/apache/iotdb/db/qp/physical/InsertTabletMultiPlanTest.java
wait awhile for bytebuffers ready when creating wal node and meeting OOM
=> [To rel/0.12][IOTDB-1297] Refactor the memory control when enabling time partitions

server/src/main/java/org/apache/iotdb/db/metadata/path/MeasurementPath.java, server/src/main/java/org/apache/iotdb/db/query/reader/series/SeriesRawDataBatchReader.java, server/src/main/java/org/apache/iotdb/db/query/reader/series/SeriesReader.java
In this PR,
1. Fix error in the test-only constructor of AlignedSeriesReader.
2. Edit java doc in SeriesReader.
=> Fix error in the test-only constructor of AlignedSeriesReader

integration/src/test/java/org/apache/iotdb/db/integration/aligned/IOTDBInsertAlignedValuesIT.java, server/src/main/java/org/apache/iotdb/db/utils/datastructure/AlignedTVList.java
=> [IOTDB-2259] Fix Error information is incorrect when aligned timeseries Data type mismatch

client-cpp/src/main/Session.cpp, client-cpp/src/main/Session.h, client-cpp/src/test/CMakeLists.txt, example/client-cpp-example/pom.xml, example/client-cpp-example/src/AlignedTimeseriesSessionExample.cpp, example/client-cpp-example/src/CMakeLists.txt, example/client-cpp-example/src/SessionExample.cpp
Add aligned timeseries APIs for C++ client.
=> [IOTDB-1802] Add aligned timeseries APIs for C++ client

server/src/main/java/org/apache/iotdb/db/metadata/MManager.java, server/src/main/java/org/apache/iotdb/db/metadata/tag/TagManager.java, server/src/test/java/org/apache/iotdb/db/metadata/MManagerBasicTest.java
=> [IOTDB-2282]fix tag recovery bug after tag upsert

grafana/pom.xml
Revert "Bump spring-boot.version from 1.5.15.RELEASE to 2.5.5 (#4130)"
=> grafana connector revert spring boot from 2.5.5 to 1.5.15

NOTICE, NOTICE-binary
=> Updated Notice file to 2022

integration/src/test/java/org/apache/iotdb/db/integration/IoTDBDeletionIT.java, integration/src/test/java/org/apache/iotdb/db/integration/aligned/IoTDBDeletionIT.java, server/src/main/java/org/apache/iotdb/db/engine/memtable/AlignedWritableMemChunk.java, server/src/main/java/org/apache/iotdb/db/engine/memtable/AlignedWritableMemChunkGroup.java, server/src/main/java/org/apache/iotdb/db/utils/datastructure/AlignedTVList.java
=> [IOTDB-2301] Fix IndexOutOfBoundException when delete aligned values

server/src/main/java/org/apache/iotdb/db/engine/storagegroup/VirtualStorageGroupProcessor.java
Fix dead lock in setDataTTL method
JIRA:  https://issues.apache.org/jira/browse/IOTDB-2317
=> Fix dead lock in setDataTTL method

docs/UserGuide/Appendix/SQL-Reference.md, docs/UserGuide/IoTDB-SQL-Language/DML-Data-Manipulation-Language.md, docs/zh/UserGuide/Appendix/SQL-Reference.md, docs/zh/UserGuide/IoTDB-SQL-Language/DML-Data-Manipulation-Language.md
=> [To rel/0.12][IOTDB-2318] Fix Some contents in the user guide docs

example/udf/src/main/java/org/apache/iotdb/udf/UDTFExample.java, server/src/main/java/org/apache/iotdb/db/utils/ErrorHandlingUtils.java
See IOTDB-2267 for more detail.
=> [IOTDB-2267] UDF: Error code 500 caused by user logic

docs/UserGuide/Advanced-Features/Triggers.md, docs/zh/UserGuide/Advanced-Features/Triggers.md
See IOTDB-2273 for more detail.
=> [IOTDB-2273] Trigger doc: quotation marks are required on the id

server/src/assembly/resources/conf/iotdb-engine.properties, server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java, server/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java, server/src/main/java/org/apache/iotdb/db/engine/storagegroup/VirtualStorageGroupProcessor.java, server/src/main/java/org/apache/iotdb/db/writelog/manager/MultiFileLogNodeManager.java, server/src/test/java/org/apache/iotdb/db/qp/physical/InsertTabletMultiPlanTest.java
wait awhile for bytebuffers ready when creating wal node and meeting OOM
=> [IOTDB-1297] Refactor the memory control when enabling time partitions

integration/src/test/java/org/apache/iotdb/db/integration/IoTDBTriggerManagementIT.java, server/src/main/java/org/apache/iotdb/db/engine/trigger/service/TriggerRegistrationService.java
See IOTDB-2284 for more detail.
=> [IOTDB-2284] Trigger: Multiple triggers can be registered on the same timeseries

Jenkinsfile
=> Fix JenkinsCI

example/trigger/src/main/java/org/apache/iotdb/trigger/TriggerExample.java
See IOTDB-2274 for more detail.
=> [IOTDB-2274] TriggerExample: deadlock between trigger recovery and MQTT service starting

server/src/main/java/org/apache/iotdb/db/engine/storagegroup/VirtualStorageGroupProcessor.java
```
Found one Java-level deadlock:
=============================
"pool-12-IoTDB-RPC-Client-101":
waiting for ownable synchronizer 0x00000003d04c5c68, (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync),
which is held by "pool-12-IoTDB-RPC-Client-52"
"pool-12-IoTDB-RPC-Client-52":
waiting for ownable synchronizer 0x00000003d04c5d58, (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync),
which is held by "pool-12-IoTDB-RPC-Client-101"
Java stack information for the threads listed above:
===================================================
"pool-12-IoTDB-RPC-Client-101":
at sun.misc.Unsafe.park(Native Method)
- parking to wait for  <0x00000003d04c5c68> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
at …
```
=> [IOTDB-2317] Deadlock between set ttl and create new TsFileProcessor

antlr/src/main/antlr4/org/apache/iotdb/db/qp/sql/IoTDBSqlParser.g4, docs/UserGuide/Advanced-Features/Select-Into.md, docs/zh/UserGuide/Advanced-Features/Select-Into.md, integration/src/test/java/org/apache/iotdb/db/integration/IoTDBSelectIntoIT.java, server/src/main/java/org/apache/iotdb/db/engine/selectinto/InsertTabletPlanGenerator.java, server/src/main/java/org/apache/iotdb/db/engine/selectinto/InsertTabletPlansIterator.java, server/src/main/java/org/apache/iotdb/db/qp/logical/crud/SelectIntoOperator.java, server/src/main/java/org/apache/iotdb/db/qp/physical/crud/SelectIntoPlan.java, server/src/main/java/org/apache/iotdb/db/qp/sql/IoTDBSqlVisitor.java, server/src/main/java/org/apache/iotdb/db/service/thrift/impl/TSServiceImpl.java
See IOTDB-2262 for more detail.
=> [IOTDB-2262][Aligned timeseries] support  in select ... into ... clauses

Jenkinsfile, jenkins.pom
=> Fix JenkinsCI deploying error

integration/src/test/java/org/apache/iotdb/db/integration/IoTDBContinuousQueryIT.java, server/src/main/java/org/apache/iotdb/db/cq/ContinuousQueryService.java, server/src/main/java/org/apache/iotdb/db/cq/ContinuousQueryTask.java, server/src/main/java/org/apache/iotdb/db/cq/ContinuousQueryTaskPoolManager.java, server/src/main/java/org/apache/iotdb/db/exception/ContinuousQueryException.java, server/src/main/java/org/apache/iotdb/db/qp/strategy/LogicalChecker.java
See IOTDB-2277 for more detail.
=> [IOTDB-2277] CQ: No warn message when aggregate function and timeseries types do not match

client-cpp/src/main/Session.cpp, client-cpp/src/main/Session.h, example/client-cpp-example/src/AlignedTimeseriesSessionExample.cpp, example/client-cpp-example/src/SessionExample.cpp, session/src/main/java/org/apache/iotdb/session/util/SessionUtils.java
Currently, java session API can support insert nullable Tablet to IoTDB server. It's time to implement this feature in c++ client.
=> [IOTDB-1803] Support insert Tablet with null value in c++ client

cli/src/main/java/org/apache/iotdb/tool/ExportCsv.java
=> [IOTDB-2279] Query timeout when exporting csv 

integration/src/test/java/org/apache/iotdb/db/integration/IoTDBSelectIntoIT.java, server/src/main/java/org/apache/iotdb/db/engine/selectinto/InsertTabletPlanGenerator.java
See IOTDB-2346 for more details.
=> [IOTDB-2346] Select INTO Reports NPE for time series containing binary values of NULL

server/src/main/java/org/apache/iotdb/db/qp/physical/crud/InsertRowsOfOneDevicePlan.java, server/src/main/java/org/apache/iotdb/db/service/thrift/impl/TSServiceImpl.java
Optimize the constructor of InsertRowsOfOneDevicePlan,replaceing array with list
=> [IOTDB-2235]Optimize the constructor of InsertRowsOfOneDevicePlan

example/session/src/main/java/org/apache/iotdb/SessionExample.java, integration/src/test/java/org/apache/iotdb/db/integration/IoTDBContinuousQueryIT.java, server/src/main/java/org/apache/iotdb/db/cq/ContinuousQueryService.java, server/src/main/java/org/apache/iotdb/db/cq/ContinuousQueryTask.java, server/src/main/java/org/apache/iotdb/db/metadata/MManager.java, server/src/main/java/org/apache/iotdb/db/qp/Planner.java, server/src/main/java/org/apache/iotdb/db/qp/executor/PlanExecutor.java, server/src/main/java/org/apache/iotdb/db/qp/logical/crud/SelectComponent.java, server/src/main/java/org/apache/iotdb/db/qp/logical/sys/CreateContinuousQueryOperator.java, server/src/main/java/org/apache/iotdb/db/qp/physical/sys/CreateContinuousQueryPlan.java, server/src/main/java/org/apache/iotdb/db/qp/sql/IoTDBSqlVisitor.java
It also fixes 
* IOTDB-2319 [CQ/SYNC] Report error in sync task when CQ is used in iotdb.
---
See IOTDB-2278 and IOTDB-2319 for more detail.
=> [IOTDB-2278][IOTDB-2319] CQ doesn't work in master branch

docs/UserGuide/API/Programming-Java-Native-API.md, docs/zh/UserGuide/API/Programming-Java-Native-API.md, session/src/main/java/org/apache/iotdb/session/Session.java, tsfile/src/main/java/org/apache/iotdb/tsfile/write/record/Tablet.java
I update Session docs for 0.13.
=> [IOTDB-2352] Update Session docs for 0.13

server/src/assembly/resources/conf/iotdb-rest.properties, server/src/test/resources/iotdb-rest.properties, session/src/test/resources/iotdb-rest.properties
Cache configuration order adjustment in iotdb-rest.properties
=> [IOTDB-2280] Cache configuration order adjustment in iotdb-rest.properties

example/pulsar/pom.xml, example/pulsar/src/main/java/org/apache/iotdb/pulsar/Constant.java, example/pulsar/src/main/java/org/apache/iotdb/pulsar/PulsarConsumer.java, example/pulsar/src/main/java/org/apache/iotdb/pulsar/PulsarConsumerThread.java, example/pulsar/src/main/java/org/apache/iotdb/pulsar/PulsarProducer.java
Update code of pulsar example with session api
=> [IOTDB-2187] Update code of pulsar example with session API

server/src/main/java/org/apache/iotdb/db/engine/storagegroup/VirtualStorageGroupProcessor.java
Get TsfileResource's writelock, then remove it from TsFileManager.
=> [IOTDB-2356] TTL doesn't work

docs/Development/ContributeGuide.md
=> Add Jprofiler link in Contribute guide

server/src/main/java/org/apache/iotdb/db/engine/storagegroup/StorageGroupProcessor.java
=> [To rel/0.12][IOTDB-2381] Fix deadlock caused by incorrect buffer pool size counter

server/src/main/java/org/apache/iotdb/db/engine/storagegroup/StorageGroupProcessor.java
start trim task after recovering tsfiles
=> [To rel/0.12][IOTDB-2320] MemoryLeak cause by wal Scheduled trim task thread

server/src/main/java/org/apache/iotdb/db/engine/storagegroup/VirtualStorageGroupProcessor.java
start trim task after recovering tsfiles
=> [IOTDB-2320] MemoryLeak cause by wal Scheduled trim task thread

server/src/main/java/org/apache/iotdb/db/metadata/MManager.java, server/src/main/java/org/apache/iotdb/db/metadata/mtree/MTree.java, server/src/test/java/org/apache/iotdb/db/metadata/MManagerBasicTest.java
=> [IOTDB-2384]Enhanced data type check on creating schema template

example/mqtt/src/main/java/org/apache/iotdb/mqtt/MQTTClient.java, server/src/main/java/org/apache/iotdb/db/engine/trigger/sink/mqtt/MQTTConfiguration.java, server/src/main/java/org/apache/iotdb/db/engine/trigger/sink/mqtt/MQTTHandler.java
see https://issues.apache.org/jira/browse/IOTDB-2373
=> [IOTDB-2373][Trigger] MQTTSink: there should be a timeout rule

server/src/main/java/org/apache/iotdb/db/engine/storagegroup/VirtualStorageGroupProcessor.java, server/src/main/java/org/apache/iotdb/db/service/SettleService.java
Avoid thread name conflict of different vsg's wal-trim thread and compaction-schedule thread
=> [IOTDB-2395] Thread Name Conflict

client-py/iotdb/Session.py
=> [IOTDB-2393][PY] Distinguish client version via version number in TSOpenSessionReq

integration/src/test/java/org/apache/iotdb/db/integration/aligned/IOTDBInsertAlignedValuesIT.java, integration/src/test/java/org/apache/iotdb/db/integration/aligned/IoTDBRawQueryWithoutValueFilter3IT.java, server/src/main/java/org/apache/iotdb/db/query/reader/series/SeriesReader.java
The details can be found in https://issues.apache.org/jira/browse/IOTDB-2400
=> [IOTDB-2400] Fix series reader bug

example/pulsar/src/main/java/org/apache/iotdb/pulsar/PulsarConsumerThread.java
=> [IOTDB-2379]Fix code of pulsar example

server/src/test/java/org/apache/iotdb/db/engine/storagegroup/StorageGroupProcessorTest.java
Fix timed flush memtable and timed close tsfile test.
=> Fix timed flush memtable and timed close tsfile test

cluster/src/assembly/resources/conf/iotdb-cluster.properties, cluster/src/main/java/org/apache/iotdb/cluster/client/ClientPoolFactory.java, cluster/src/main/java/org/apache/iotdb/cluster/config/ClusterConfig.java, cluster/src/main/java/org/apache/iotdb/cluster/config/ClusterDescriptor.java, cluster/src/test/java/org/apache/iotdb/cluster/client/ClientPoolFactoryTest.java
see [jira](https://issues.apache.org/jira/browse/IOTDB-2394)
=> [IOTDB-2394] Fixed temporary network unavailability caused by frequent closed connections

integration/src/test/java/org/apache/iotdb/db/integration/IoTDBLoadExternalTsfileIT.java, integration/src/test/java/org/apache/iotdb/db/integration/aligned/IoTDBLoadExternalAlignedTsFileIT.java, server/src/main/java/org/apache/iotdb/db/engine/storagegroup/VirtualStorageGroupProcessor.java
fix bug and add unit test case for load tsfile with .mods file
=> [IOTDB-2407] When there is an xxx.tsfile.mods, using load tsfile will lose all data

server/src/main/java/org/apache/iotdb/db/protocol/rest/handler/PhysicalPlanValidationHandler.java, server/src/main/java/org/apache/iotdb/db/protocol/rest/handler/RequestValidationHandler.java, server/src/main/java/org/apache/iotdb/db/protocol/rest/impl/GrafanaApiServiceImpl.java, server/src/main/java/org/apache/iotdb/db/protocol/rest/impl/RestApiServiceImpl.java, server/src/main/java/org/apache/iotdb/db/qp/Planner.java
This PR fixes:
IOTDB-2310 [grafana-plugin] NPE, Using aggregate queries with "group by level=*"
IOTDB-2311 [grafana-plugin] NPE, Using queries with "align by device"
IOTDB-2372 [rest api] disable align not return value, no error
=> [IOTDB-2310][IOTDB-2311][IOTDB-2372] Add query type check for REST query API

server/src/main/java/org/apache/iotdb/db/protocol/rest/handler/RequestValidationHandler.java, server/src/main/java/org/apache/iotdb/db/protocol/rest/impl/RestApiServiceImpl.java
This is another patch for IOTDB-2313.
=> [IOTDB-2313] REST: GC overhead limit when select * from root.**

cli/src/main/java/org/apache/iotdb/cli/Cli.java, cli/src/main/java/org/apache/iotdb/cli/utils/JlineUtils.java, cli/src/main/java/org/apache/iotdb/tool/ExportCsv.java
See IOTDB-2287 .
Already tested on my computer.
=> [IOTDB-2287] Separate CLI history by different hosts, ports and usernames 

docs/SystemDesign/SchemaManager/SchemaManager.md, docs/zh/SystemDesign/SchemaManager/SchemaManager.md, integration/src/test/java/org/apache/iotdb/db/integration/IoTDBTagAlterIT.java, integration/src/test/java/org/apache/iotdb/db/integration/IoTDBTagIT.java, server/src/main/java/org/apache/iotdb/db/metadata/tag/TagManager.java, testcontainer/src/test/java/org/apache/iotdb/db/sql/Cases.java
See: https://issues.apache.org/jira/browse/IOTDB-2181
=>  [IOTDB-2181] Fix cluster tag

metrics/ReadMe.md, metrics/interface/src/main/assembly/resources/conf/iotdb-metric.yml, metrics/interface/src/main/java/org/apache/iotdb/metrics/CompositeReporter.java, metrics/interface/src/main/java/org/apache/iotdb/metrics/type/Gauge.java
See: https://issues.apache.org/jira/browse/IOTDB-2418
=> [IOTDB-2418][Doc] fix some doc problems in metric module.

pom.xml
see https://lists.apache.org/thread/x77z7282o9vl1ossgkkb19645tsxt0rf
=> disable library-udf temporary because there is no codes under the module now

server/src/main/java/org/apache/iotdb/db/writelog/node/ExclusiveWriteLogNode.java
1. get new FileWriter before switchBufferWorkingToFlushing
2. set system to read-only when error occurs in flushBuffer method
=> [IOTDB-2426] WAL deadlock caused by too many open files

server/src/main/java/org/apache/iotdb/db/protocol/rest/handler/ExceptionHandler.java
fixed [IOTDB-2362] Use noQuery to execute "count", return "SHOW is not supported"
=> [IOTDB-2362] Use noQuery to execute "count", return "SHOW is not supported"

docs/UserGuide/API/Programming-JDBC.md, docs/UserGuide/API/Programming-Java-Native-API.md, docs/zh/UserGuide/API/Programming-JDBC.md, docs/zh/UserGuide/API/Programming-Java-Native-API.md, example/jdbc/src/main/java/org/apache/iotdb/JDBCExample.java, example/session/src/main/java/org/apache/iotdb/SessionExample.java, server/src/main/java/org/apache/iotdb/db/query/control/SessionManager.java
Update session doc about compatible 0.13
=> Update session and JDBC doc about compatible with 0.13

antlr/src/main/antlr4/org/apache/iotdb/db/qp/sql/IoTDBSqlParser.g4, docs/UserGuide/Reference/Syntax-Conventions.md, docs/zh/UserGuide/Reference/Syntax-Conventions.md, integration/src/test/java/org/apache/iotdb/db/integration/IoTDBSyntaxConventionIT.java, server/src/main/java/org/apache/iotdb/db/qp/sql/IoTDBSqlVisitor.java, server/src/test/java/org/apache/iotdb/db/query/dataset/groupby/GroupByLevelDataSetTest.java, server/src/test/java/org/apache/iotdb/db/query/dataset/groupby/GroupByTimeDataSetTest.java
See JIRA https://issues.apache.org/jira/browse/IOTDB-2429
=> [IOTDB-2429] Fix string literal constant being treated as node name in SELECT expression

docs/UserGuide/Write-And-Delete-Data/Delete-Data.md, docs/zh/UserGuide/Write-And-Delete-Data/Delete-Data.md
=> [IOTDB-2427] Fix document of deleting non-existing time series values

grafana-connector/src/main/java/org/apache/iotdb/web/grafana/dao/impl/BasicDaoImpl.java
See IOTDB-2437 for more detail.
=> [IOTDB-2437][Grafana Connector] can't get timeseries

site/src/main/.vuepress/config.js
Checkout User Guide documents for 0.13
=> Checkout User Guide documents for 0.13

docs/UserGuide/Administration-Management/Administration.md, docs/zh/UserGuide/Administration-Management/Administration.md
Add more SQL in Administration doc
=> Add more SQL in Administration doc

docs/UserGuide/Data-Concept/Compression.md, docs/zh/SystemDesign/StorageEngine/FileLists.md, docs/zh/UserGuide/Data-Concept/Compression.md
=> Update compression ratio doc

docs/UserGuide/System-Tools/TsFile-Split-Tool.md, docs/zh/UserGuide/System-Tools/TsFile-Split-Tool.md, server/src/assembly/resources/tools/tsfileToolSet/split-tsfile-tool.bat, server/src/assembly/resources/tools/tsfileToolSet/split-tsfile-tool.sh, server/src/main/java/org/apache/iotdb/db/tools/TsFileSplitTool.java, site/src/main/.vuepress/config.js, tsfile/src/main/java/org/apache/iotdb/tsfile/read/TsFileSequenceReader.java
=> [IOTDB-2078] [To rel/0.12] Split large TsFile tool

site/src/main/.vuepress/config.js
=> [Site] Fix an error in site

.github/workflows/influxdb-protocol.yml, server/src/assembly/resources/conf/iotdb-engine.properties, server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
see https://issues.apache.org/jira/browse/IOTDB-2443
=> [IOTDB-2443] The influx service is closed by default

server/src/main/java/org/apache/iotdb/db/protocol/rest/handler/QueryDataSetHandler.java, server/src/main/java/org/apache/iotdb/db/protocol/rest/impl/GrafanaApiServiceImpl.java, server/src/test/java/org/apache/iotdb/db/protocol/rest/GrafanaApiServiceIT.java, server/src/test/java/org/apache/iotdb/db/protocol/rest/IoTDBRestServiceIT.java
fixed [IOTDB-2310] NPE, Using aggregate queries with "group by level=*"
=> [IOTDB-2310] NPE, Using aggregate queries with "group by level=*"

.github/workflows/cluster.yml, .github/workflows/e2e.yml
=> disable e2e and cluster workflow

server/src/assembly/resources/conf/iotdb-engine.properties
Set default ttl back to 36000000
=> Set default ttl back to 36000000

docs/UserGuide/API/RestService.md, docs/UserGuide/Ecosystem Integration/Grafana Plugin.md, docs/zh/UserGuide/API/RestService.md, docs/zh/UserGuide/Ecosystem Integration/Grafana Plugin.md
grafana plugin.md and RestService.md added to avoid oom prompt
=> [IOTDB-2313][REST API Doc] how to avoid GC overhead

RELEASE_NOTES.md
=> Add 0.13.0 release note

server/src/main/java/org/apache/iotdb/db/qp/executor/PlanExecutor.java, server/src/main/java/org/apache/iotdb/db/qp/physical/PhysicalPlan.java, server/src/main/java/org/apache/iotdb/db/qp/physical/sys/ShowPlan.java
=> [IOTDB-2362] [REST API] Use noQuery to execute "count", return "SHOW is not supported"

server/src/main/java/org/apache/iotdb/db/engine/storagegroup/timeindex/V012FileTimeIndex.java
=> Fix compile error

cli/src/assembly/resources/sbin/start-cli.bat, cli/src/assembly/resources/sbin/start-cli.sh, cli/src/assembly/resources/tools/export-csv.bat, cli/src/assembly/resources/tools/export-csv.sh, cli/src/assembly/resources/tools/import-csv.bat, cli/src/assembly/resources/tools/import-csv.sh
See: https://issues.apache.org/jira/browse/IOTDB-2425
=> [IOTDB-2425][env] rename IOTDB_CLI_HOME to IOTDB_HOME

cli/src/assembly/resources/sbin/start-cli.bat, cli/src/assembly/resources/sbin/start-cli.sh, cli/src/assembly/resources/tools/export-csv.bat, cli/src/assembly/resources/tools/export-csv.sh, cli/src/assembly/resources/tools/import-csv.bat, cli/src/assembly/resources/tools/import-csv.sh
=> Revert "[IOTDB-2425][env] rename IOTDB_CLI_HOME to IOTDB_HOME"

docs/UserGuide/Maintenance-Tools/Maintenance-Command.md, docs/zh/UserGuide/Maintenance-Tools/Maintenance-Command.md, server/src/main/java/org/apache/iotdb/db/qp/physical/sys/StorageGroupMNodePlan.java
see IOTDB-2463
Clean dirty code and snapshot will work again
=> [IOTDB-2463] Fix snapshot compatibility

docs/UserGuide/API/Programming-Java-Native-API.md, docs/zh/UserGuide/API/Programming-Java-Native-API.md, session/src/main/java/org/apache/iotdb/session/Session.java
=> [DOC] Update executeLastDataQuery in API doc

server/src/main/java/org/apache/iotdb/db/utils/ErrorHandlingUtils.java
Remove the log 'sg may not ready now'
=> [IOTDB-2475] Remove the log of: sg may not ready now

server/src/main/java/org/apache/iotdb/db/service/TSServiceImpl.java
Remove the log 'sg may not ready now'
=> [To rel/0.12][IOTDB-2475] Remove the log of: sg may not ready now

docs/UserGuide/Administration-Management/Administration.md, docs/zh/UserGuide/Administration-Management/Administration.md
Issue: [[IOTDB-2430] Add example of revoke Privilege](https://issues.apache.org/jira/browse/IOTDB-2430?jql=project%20%3D%20IOTDB%20AND%20resolution%20%3D%20Unresolved%20AND%20labels%20in%20(easy-fix%2C%20easy-fixed%2C%20EasyFix%2C%20easyfix%2C%20easytest%2C%20easytask%2C%20easytext)%20ORDER%20BY%20priority%20DESC%2C%20updated%20DESC)
I was actually not sure if I should add single or double quote string literals for the privilege names (e.g. revoke user sgcc_write_user privileges 'INSERT_TIMESERIES' on root.sgcc). 
I did see the string literals for INSERT_TIMESERIES in the documents of the previous versions, but I didn't see the string literals in the latest version, which I think is weird. So I just left it the same as the current version.
<hr>
This PR has:
for …
=> [IOTDB-2430] Add example of revoke Privilege

server/src/assembly/resources/conf/iotdb-engine.properties, server/src/main/java/org/apache/iotdb/db/concurrent/ThreadName.java, server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java, server/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java, server/src/main/java/org/apache/iotdb/db/engine/storagegroup/VirtualStorageGroupProcessor.java, server/src/main/java/org/apache/iotdb/db/engine/storagegroup/virtualSg/StorageGroupManager.java
Use scheduled logging service to log the recover progress.
=> [IOTDB-2474] Add progress logger when restarting IoTDB

docs/UserGuide/QuickStart/Command-Line-Interface.md, docs/zh/UserGuide/QuickStart/Command-Line-Interface.md
fixed  user 's manual of openid
=> fixed  user 's manual of openid

tsfile/src/main/java/org/apache/iotdb/tsfile/write/writer/LocalTsFileOutput.java
current getPosition() will trigger flush which cause the bufferStream doesn't take effect as getPosition is triggered in too many times.
Fix the issue to help improve flush performance.
=> Avoid flush stream in getPosition() to improve flush performance

server/src/main/java/org/apache/iotdb/db/utils/ErrorHandlingUtils.java
Remove sg not ready log in batch process.
=> [IOTDB-2475] Remove sg not ready log in batch process

server/src/main/java/org/apache/iotdb/db/service/TSServiceImpl.java
Remove sg not ready log in batch process.
=> [To rel/0.12][IOTDB-2475] Remove sg not ready log in batch process

docs/UserGuide/Maintenance-Tools/TsFile-Split-Tool.md, docs/zh/UserGuide/Maintenance-Tools/TsFile-Split-Tool.md, site/src/main/.vuepress/config.js
Add unit of `-size` param and give an example
=> Fix doc of TsFileSplitTool

docs/UserGuide/System-Tools/TsFile-Split-Tool.md, docs/zh/UserGuide/System-Tools/TsFile-Split-Tool.md
=> [TO rel/0.12] Fix doc of TsFileSplitTool

site/src/main/.vuepress/config.js, site/src/main/package.json
fix a bug where npm cannot install correctly
<hr>
This PR has:
<hr>
=> Website bug fix

integration/src/test/java/org/apache/iotdb/db/integration/aggregation/IoTDBAggregationLargeDataIT.java, integration/src/test/java/org/apache/iotdb/db/integration/aggregation/IoTDBAggregationSmallDataIT.java, tsfile/src/main/java/org/apache/iotdb/tsfile/file/metadata/statistics/BinaryStatistics.java, tsfile/src/main/java/org/apache/iotdb/tsfile/file/metadata/statistics/BooleanStatistics.java, tsfile/src/main/java/org/apache/iotdb/tsfile/file/metadata/statistics/DoubleStatistics.java, tsfile/src/main/java/org/apache/iotdb/tsfile/file/metadata/statistics/FloatStatistics.java, tsfile/src/main/java/org/apache/iotdb/tsfile/file/metadata/statistics/IntegerStatistics.java, tsfile/src/main/java/org/apache/iotdb/tsfile/file/metadata/statistics/LongStatistics.java, tsfile/src/main/java/org/apache/iotdb/tsfile/file/metadata/statistics/Statistics.java, tsfile/src/main/java/org/apache/iotdb/tsfile/file/metadata/statistics/TimeStatistics.java
This pull request removes some methods that are never used.
=> Removing some useless codes in Statistics

site/src/main/.vuepress/config.js
=> Link SystemDesign to confluence page

cli/src/assembly/resources/sbin/start-cli.bat, cli/src/assembly/resources/tools/export-csv.bat, cli/src/assembly/resources/tools/import-csv.bat, cli/src/main/java/org/apache/iotdb/cli/AbstractCli.java, cli/src/main/java/org/apache/iotdb/cli/Cli.java, cli/src/main/java/org/apache/iotdb/tool/AbstractCsvTool.java, cli/src/main/java/org/apache/iotdb/tool/ExportCsv.java, cli/src/main/java/org/apache/iotdb/tool/ImportCsv.java, cli/src/test/java/org/apache/iotdb/cli/AbstractScript.java, cli/src/test/java/org/apache/iotdb/cli/StartClientScriptIT.java, cli/src/test/java/org/apache/iotdb/tool/integration/ExportCsvTestIT.java, cli/src/test/java/org/apache/iotdb/tool/integration/ImportCsvTestIT.java
See JIRA: https://issues.apache.org/jira/browse/IOTDB-2523
After this fix being applied, we got this result in my desktop with Windows 10 installed, which is as our expected.
=> [IOTDB-2523] Fix exiting with 0 when executing error in cli

tsfile/src/main/java/org/apache/iotdb/tsfile/common/conf/TSFileConfig.java, tsfile/src/main/java/org/apache/iotdb/tsfile/encoding/decoder/FloatDecoder.java, tsfile/src/main/java/org/apache/iotdb/tsfile/encoding/decoder/PlainDecoder.java, tsfile/src/main/java/org/apache/iotdb/tsfile/utils/BytesUtils.java, tsfile/src/main/java/org/apache/iotdb/tsfile/utils/StringContainer.java, tsfile/src/main/java/org/apache/iotdb/tsfile/v2/file/metadata/MetadataIndexNodeV2.java
The pr is some small changes, just fix some typos.
=> fix some typos

docs/UserGuide/Appendix/Config-Manual.md, docs/zh/UserGuide/Appendix/Config-Manual.md, server/src/assembly/resources/conf/iotdb-engine.properties, server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java, server/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java, server/src/main/java/org/apache/iotdb/db/metadata/MManager.java, server/src/main/java/org/apache/iotdb/db/metadata/MTree.java, server/src/main/java/org/apache/iotdb/db/metadata/logfile/MLogWriter.java, server/src/main/java/org/apache/iotdb/db/writelog/io/SingleFileLogReader.java, server/src/test/java/org/apache/iotdb/db/metadata/MManagerBasicTest.java, server/src/test/java/org/apache/iotdb/db/writelog/io/LogWriterReaderTest.java
Timed force mlog and truncate broken logs.
=> [To rel/0.12][IOTDB-2528] MLog corruption and recovery bug after killing system

integration/src/main/java/org/apache/iotdb/integration/env/ClusterEnvBase.java, integration/src/main/java/org/apache/iotdb/integration/env/ClusterNode.java
See JIRA: https://issues.apache.org/jira/browse/IOTDB-2530
=> [IOTDB-2530] Fix port conflict when starting nodes in cluster IT

docs/UserGuide/Reference/Config-Manual.md, docs/zh/UserGuide/Reference/Config-Manual.md, server/src/assembly/resources/conf/iotdb-engine.properties, server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java, server/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java, server/src/main/java/org/apache/iotdb/db/metadata/MManager.java, server/src/main/java/org/apache/iotdb/db/metadata/logfile/MLogWriter.java, server/src/main/java/org/apache/iotdb/db/writelog/io/SingleFileLogReader.java, server/src/test/java/org/apache/iotdb/db/writelog/io/LogWriterReaderTest.java
Timed force mlog and truncate broken logs.
=> [IOTDB-2528] MLog corruption and recovery bug after killing system

cli/src/main/java/org/apache/iotdb/tool/AbstractCsvTool.java, cli/src/main/java/org/apache/iotdb/tool/ExportCsv.java, cli/src/main/java/org/apache/iotdb/tool/ImportCsv.java, cross-tests/src/test/java/org/apache/iotdb/cross/tests/tools/importCsv/AbstractScript.java
There are some code smells in csv-tool module, such as useless boxing and unboxing, deprecated or useless method calls.
=> [IOTDB-2508] Fix csv tool code smells

server/src/test/java/org/apache/iotdb/db/engine/memtable/MemtableBenchmark.java
Fix the issues #5049  and introduce the JMH for benchmark.
<hr>
This PR has:
<hr>
=> [ISSUE-5049] fix MemtableBenchmark

integration/src/test/java/org/apache/iotdb/db/integration/IoTDBCreateTimeseriesIT.java, integration/src/test/java/org/apache/iotdb/session/IoTDBSessionSimpleIT.java, server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java, server/src/test/java/org/apache/iotdb/db/metadata/MManagerBasicTest.java
Chery-pick from #5041 and adapt to v0.13
=> [IOTDB-2534] Add character support while using quote

server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBCreateTimeseriesIT.java, server/src/test/java/org/apache/iotdb/db/metadata/MManagerBasicTest.java, session/src/test/java/org/apache/iotdb/session/IoTDBSessionSimpleIT.java
=> [To rel/0.12][IOTDB-2534]add character support while using double quote

server/src/main/java/org/apache/iotdb/db/metadata/MManager.java, server/src/test/java/org/apache/iotdb/db/metadata/MManagerBasicTest.java
=> [To rel/0.12][IOTDB-2544] Fix tag info sync error during metadata sync

cluster/src/main/java/org/apache/iotdb/cluster/query/ClusterQueryRouter.java, cluster/src/test/java/org/apache/iotdb/cluster/query/ClusterQueryRouterTest.java, integration/src/test/java/org/apache/iotdb/db/integration/IoTDBAlignByDeviceIT.java, server/src/main/java/org/apache/iotdb/db/qp/executor/PlanExecutor.java, server/src/main/java/org/apache/iotdb/db/qp/logical/crud/GroupByFillQueryOperator.java, server/src/main/java/org/apache/iotdb/db/qp/logical/crud/GroupByQueryOperator.java, server/src/main/java/org/apache/iotdb/db/qp/logical/crud/QueryOperator.java, server/src/main/java/org/apache/iotdb/db/qp/physical/crud/GroupByTimePlan.java, server/src/main/java/org/apache/iotdb/db/qp/physical/crud/RawDataQueryPlan.java, server/src/main/java/org/apache/iotdb/db/query/dataset/AlignByDeviceDataSet.java, server/src/main/java/org/apache/iotdb/db/query/dataset/groupby/GroupByEngineDataSet.java, server/src/main/java/org/apache/iotdb/db/query/executor/QueryRouter.java, server/src/test/java/org/apache/iotdb/db/qp/physical/PhysicalPlanTest.java
Path in where clause is not included in measurements of specific device.
=> [IOTDB-2532] Query with align by device can't get value after clear cache

server/src/main/java/org/apache/iotdb/db/qp/physical/crud/RawDataQueryPlan.java, server/src/main/java/org/apache/iotdb/db/qp/strategy/PhysicalGenerator.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBAlignByDeviceIT.java
Path in where clause is not included in measurements of specific device.
=> [To rel/0.12] [IOTDB-2532] Query with align by device can't get value after clear cache

integration/src/main/java/org/apache/iotdb/db/query/udf/example/WindowStartEnd.java, integration/src/test/java/org/apache/iotdb/db/integration/IoTDBUDFWindowQueryIT.java, server/src/main/java/org/apache/iotdb/db/query/udf/api/access/RowWindow.java, server/src/main/java/org/apache/iotdb/db/query/udf/core/access/ElasticSerializableRowRecordListBackedMultiColumnWindow.java, server/src/main/java/org/apache/iotdb/db/query/udf/core/access/ElasticSerializableTVListBackedSingleColumnWindow.java, server/src/main/java/org/apache/iotdb/db/query/udf/core/layer/MultiInputColumnIntermediateLayer.java, server/src/main/java/org/apache/iotdb/db/query/udf/core/layer/SingleInputColumnMultiReferenceIntermediateLayer.java, server/src/main/java/org/apache/iotdb/db/query/udf/core/layer/SingleInputColumnSingleReferenceIntermediateLayer.java
See IOTDB-2538 for more detail.
=> [IOTDB-2538] The UDTF Transform method supports getting the start and end times of rowWindow

server/src/main/java/org/apache/iotdb/db/service/thrift/impl/TSServiceImpl.java, server/src/main/java/org/apache/iotdb/db/utils/ErrorHandlingUtils.java
=> [IOTDB-2502] Remove redundant query warn log

docs/zh/UserGuide/Data-Concept/Schema-Template.md, server/src/main/java/org/apache/iotdb/db/qp/logical/sys/SetTemplateOperator.java, server/src/main/java/org/apache/iotdb/db/qp/logical/sys/UnsetTemplateOperator.java, server/src/main/java/org/apache/iotdb/db/qp/physical/sys/SetTemplatePlan.java, server/src/main/java/org/apache/iotdb/db/qp/physical/sys/UnsetTemplatePlan.java, server/src/main/java/org/apache/iotdb/db/service/thrift/impl/TSServiceImpl.java, server/src/test/java/org/apache/iotdb/db/metadata/MManagerBasicTest.java, session/src/test/java/org/apache/iotdb/session/SessionTest.java
Check path in SetTemplatePlan.
Fix template doc 404 link meanwhile.
=> [IOTDB-2551]Prevent to sent template on wildcard path

docs/UserGuide/Appendix/Config-Manual.md, docs/zh/UserGuide/Appendix/Config-Manual.md, server/src/assembly/resources/conf/iotdb-engine.properties, server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
Change default value of sync mlog period parameter from 0 to 100.
=> [To rel/0.12][IOTDB-2562] Change default value of sync mlog period parameter

session/src/main/java/org/apache/iotdb/session/Session.java, testcontainer/src/test/java/org/apache/iotdb/db/sql/Cases.java, tsfile/src/main/java/org/apache/iotdb/tsfile/write/TsFileWriter.java, tsfile/src/main/java/org/apache/iotdb/tsfile/write/record/Tablet.java
(1) change prefixPath in Tablet to deviceId
(2) fix some sonar issue in Tablet
=> change prefixPath in Tablet to deviceId

.github/workflows/client.yml
Windows server 2022 cannot install boost successfully…
<hr>
This PR has:
<hr>
=> Fix windows cpp-client CI

.github/workflows/client.yml
=> [To rel/0.12] Fix windows cpp-client CI

docs/UserGuide/API/RestService.md, docs/zh/UserGuide/API/RestService.md, server/src/main/java/org/apache/iotdb/db/protocol/rest/impl/PingApiServiceImpl.java, server/src/main/java/org/apache/iotdb/db/service/thrift/ThriftService.java, server/src/test/java/org/apache/iotdb/db/protocol/rest/IoTDBRestServiceIT.java
See JIRA: https://issues.apache.org/jira/browse/IOTDB-2541
=> [IOTDB-2541] Enhance /ping API to liveness probe

server/src/main/java/org/apache/iotdb/db/concurrent/ThreadName.java, server/src/main/java/org/apache/iotdb/db/engine/StorageEngine.java, server/src/main/java/org/apache/iotdb/db/engine/storagegroup/StorageGroupProcessor.java, server/src/main/java/org/apache/iotdb/db/engine/storagegroup/virtualSg/VirtualStorageGroupManager.java, server/src/main/java/org/apache/iotdb/db/utils/ThreadUtils.java, server/src/main/java/org/apache/iotdb/db/writelog/manager/MultiFileLogNodeManager.java, server/src/main/java/org/apache/iotdb/db/writelog/node/ExclusiveWriteLogNode.java, server/src/main/java/org/apache/iotdb/db/writelog/node/WriteLogNode.java
See JIRA: https://issues.apache.org/jira/browse/IOTDB-2567.
=> [To rel/0.12][IOTDB-2567]  Fix thread and ByteBuffer leak after service stopped

cluster/src/main/java/org/apache/iotdb/cluster/metadata/CMManager.java, cluster/src/test/java/org/apache/iotdb/cluster/client/sync/SyncClientAdaptorTest.java, thrift-cluster/src/main/thrift/cluster.thrift
See JIRA: https://issues.apache.org/jira/browse/IOTDB-2546
=> [IOTDB-2546] Fix GetAllPaths() RPC call missing isUnderAligendEntity

cluster/src/main/java/org/apache/iotdb/cluster/client/sync/SyncClientAdaptor.java, cluster/src/main/java/org/apache/iotdb/cluster/metadata/CMManager.java, cluster/src/main/java/org/apache/iotdb/cluster/query/LocalQueryExecutor.java, cluster/src/main/java/org/apache/iotdb/cluster/server/service/DataAsyncService.java, cluster/src/main/java/org/apache/iotdb/cluster/server/service/DataGroupServiceImpls.java, cluster/src/main/java/org/apache/iotdb/cluster/server/service/DataSyncService.java, cluster/src/test/java/org/apache/iotdb/cluster/client/sync/SyncClientAdaptorTest.java, cluster/src/test/java/org/apache/iotdb/cluster/common/TestAsyncDataClient.java, thrift-cluster/src/main/thrift/cluster.thrift
See JIRA https://issues.apache.org/jira/browse/IOTDB-2557
=> [IOTDB-2557] Fix non-data-read QueryContext in getAllMeasurementSchema

server/src/main/java/org/apache/iotdb/db/metadata/template/TemplateManager.java, server/src/test/java/org/apache/iotdb/db/metadata/TemplateTest.java
=> [IOTDB-2577]Clearer message for alignment conflict of template and mounted node

server/src/main/java/org/apache/iotdb/db/engine/StorageEngine.java
stop scheduler pool when deleting storage group
=> [To rel/0.12][IOTDB-2580] Fix DirectByteBuffer and thread leak when deleting storage group

server/src/main/java/org/apache/iotdb/db/engine/compaction/cross/rewrite/selector/RewriteCompactionFileSelector.java, server/src/test/java/org/apache/iotdb/db/engine/compaction/cross/RewriteCompactionFileSelectorTest.java
Filter out not closed source seq file in cross space compaction selector.
=> [IOTDB-2585]Fix Cross space compaction selector of not closed file

metrics/dropwizard-metrics/src/main/java/org/apache/iotdb/metrics/dropwizard/DropwizardMetricManager.java, metrics/dropwizard-metrics/src/test/java/org/apache/iotdb/metrics/dropwizard/DropwizardMetricManagerTest.java
see more details: [IOTDB-2594](https://issues.apache.org/jira/browse/IOTDB-2594)
=> [IOTDB-2594][Metric] fix implement of histogram of dropwizard to UniformReservoir.

example/session/src/main/java/org/apache/iotdb/AlignedTimeseriesSessionExample.java, example/session/src/main/java/org/apache/iotdb/HybridTimeseriesSessionExample.java, integration/src/test/java/org/apache/iotdb/session/IoTDBSessionSimpleIT.java, session/src/main/java/org/apache/iotdb/session/Session.java, session/src/main/java/org/apache/iotdb/session/pool/SessionPool.java, session/src/test/java/org/apache/iotdb/session/IoTDBSessionVectorAggregationIT.java, session/src/test/java/org/apache/iotdb/session/IoTDBSessionVectorInsertIT.java, testcontainer/src/test/java/org/apache/iotdb/db/sql/Cases.java, tsfile/src/main/java/org/apache/iotdb/tsfile/write/record/Tablet.java
=> [IOTDB-2599] Fix example of insertAlignedTablet is incorrect

README.md, README_ZH.md
=> Fix invalid URL in README

example/session/src/main/java/org/apache/iotdb/AlignedTimeseriesSessionExample.java
=> [IOTDB-2607] Fix session example error

server/src/main/java/org/apache/iotdb/db/engine/compaction/TsFileIdentifier.java, server/src/main/java/org/apache/iotdb/db/engine/compaction/inner/utils/SizeTieredCompactionLogger.java, server/src/test/java/org/apache/iotdb/db/engine/compaction/recover/SizeTieredCompactionRecoverCompatibleTest.java
see [IOTDB-2581](https://issues.apache.org/jira/browse/IOTDB-2581)
=> [IOTDB-2581] Fix compaction recover in 0.13.0 is not compatible with 0.12.5

server/src/main/java/org/apache/iotdb/db/auth/AuthorityChecker.java
See IOTDB-2620 for more detail.
=> [IOTDB-2620] Unrecognizable operator type (SHOW) for AuthorityChecker

server/src/main/java/org/apache/iotdb/db/auth/AuthorityChecker.java
See IOTDB-2620 for more detail.
=> [To rel/0.12][IOTDB-2620] Unrecognizable operator type (SHOW) for AuthorityChecker

cluster/src/main/java/org/apache/iotdb/cluster/server/member/RaftMember.java
See JIRA: https://issues.apache.org/jira/browse/IOTDB-2625
=> [IOTDB-2625] Fix election deadlock when updating partition table

RELEASE_NOTES.md, server/src/assembly/resources/conf/iotdb-engine.properties, server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java, server/src/main/java/org/apache/iotdb/db/engine/compaction/cross/AbstractCrossSpaceCompactionTask.java, server/src/main/java/org/apache/iotdb/db/engine/compaction/cross/rewrite/task/RewriteCrossSpaceCompactionTask.java, server/src/main/java/org/apache/iotdb/db/engine/compaction/inner/AbstractInnerSpaceCompactionTask.java, server/src/main/java/org/apache/iotdb/db/engine/compaction/inner/sizetiered/SizeTieredCompactionTask.java
see [IOTDB-2612](https://issues.apache.org/jira/browse/IOTDB-2612)
=> [IOTDB-2612] Fix cannot select compaction candidate after exception occurrence in previous compaction

cluster/src/main/java/org/apache/iotdb/cluster/server/member/RaftMember.java, cluster/src/test/java/org/apache/iotdb/cluster/server/heartbeat/HeartbeatThreadTest.java
The follow up of https://issues.apache.org/jira/browse/IOTDB-2625
=> [IOTDB-2625] Optimize RaftMember initialization

Jenkinsfile, site/src/main/.vuepress/config.js
=> Fix website compile error

server/src/main/java/org/apache/iotdb/db/qp/sql/IoTDBSqlVisitor.java
1) IOTDB-2629, IoTDBSqlVisitor.java need consider `xxx` as CMD parameter
2) IOTDB-2631, fix some UT/IT error.
=> [To new_sync][IOTDB-2629][IOTDB-2631] new_sync branch, fix bugs of CMD & Test

cli/src/assembly/resources/sbin/start-cli.bat, cli/src/assembly/resources/tools/export-csv.bat, cli/src/assembly/resources/tools/import-csv.bat, cli/src/test/java/org/apache/iotdb/cli/StartClientScriptIT.java, cli/src/test/java/org/apache/iotdb/tool/integration/ExportCsvTestIT.java, cli/src/test/java/org/apache/iotdb/tool/integration/ImportCsvTestIT.java
See JIRA: https://issues.apache.org/jira/browse/IOTDB-2634
=> [IOTDB-2634] Fix batch script exit directly from cmd.exe

grafana-plugin/pom.xml
fixed mvn clean can not clean folder "grafana-plugin"
=> [IOTDB-2579] fixed mvn clean can not clean folder "grafana-plugin"

integration/src/test/java/org/apache/iotdb/db/integration/aligned/IoTDBAlignByDeviceIT.java, server/src/main/java/org/apache/iotdb/db/query/dataset/AlignByDeviceDataSet.java
Msg: 500: [INTERNAL_SERVER_ERROR(500)] Exception occurred: "select * from root.line4.pv where lat > 1 limit 5 align by device". executeStatement failed. java.lang.ClassCastException: org.apache.iotdb.db.metadata.path.AlignedPath cannot be cast to org.apache.iotdb.db.metadata.path.MeasurementPath
=> [IOTDB-2668] Exception while query aligned series with value filter align by device

cluster/src/main/java/org/apache/iotdb/cluster/log/manage/PartitionedSnapshotLogManager.java, cluster/src/main/java/org/apache/iotdb/cluster/server/handlers/caller/ElectionHandler.java, cluster/src/main/java/org/apache/iotdb/cluster/utils/nodetool/ClusterMonitor.java, docs/UserGuide/Maintenance-Tools/Metric-Tool.md, docs/zh/UserGuide/Maintenance-Tools/Metric-Tool.md, metrics/ReadMe.md, metrics/dropwizard-metrics/src/test/java/org/apache/iotdb/metrics/dropwizard/DropwizardMetricManagerTest.java, metrics/interface/src/main/assembly/resources/conf/iotdb-metric.yml, metrics/interface/src/main/java/org/apache/iotdb/metrics/config/MetricConfig.java, metrics/interface/src/test/java/org/apache/iotdb/metrics/config/MetricConfigTest.java, metrics/interface/src/test/resources/iotdb-metric.yml, metrics/micrometer-metrics/src/test/java/org/apache/iotdb/metrics/micrometer/MicrometerMetricManagerTest.java, server/src/main/java/org/apache/iotdb/db/engine/cache/ChunkCache.java, server/src/main/java/org/apache/iotdb/db/engine/cache/TimeSeriesMetadataCache.java, server/src/main/java/org/apache/iotdb/db/engine/compaction/CompactionTaskManager.java, server/src/main/java/org/apache/iotdb/db/engine/compaction/task/AbstractCompactionTask.java, server/src/main/java/org/apache/iotdb/db/engine/flush/FlushManager.java, server/src/main/java/org/apache/iotdb/db/engine/flush/MemTableFlushTask.java, server/src/main/java/org/apache/iotdb/db/engine/memtable/AbstractMemTable.java, server/src/main/java/org/apache/iotdb/db/engine/storagegroup/TsFileProcessorInfo.java, server/src/main/java/org/apache/iotdb/db/engine/storagegroup/VirtualStorageGroupProcessor.java, server/src/main/java/org/apache/iotdb/db/metadata/MManager.java, server/src/main/java/org/apache/iotdb/db/query/pool/RawQueryReadTaskPoolManager.java, server/src/main/java/org/apache/iotdb/db/service/metrics/MetricsService.java, server/src/main/java/org/apache/iotdb/db/service/thrift/ProcessorWithMetrics.java, server/src/main/java/org/apache/iotdb/db/service/thrift/impl/TSServiceImpl.java
See more details: https://issues.apache.org/jira/browse/IOTDB-2691
=> [IOTDB-2691][Metric]update metric doc

confignode/pom.xml, confignode/src/main/java/org/apache/iotdb/confignode/manager/ConfigManager.java, confignode/src/main/java/org/apache/iotdb/confignode/partition/DataPartitionRule.java, confignode/src/main/java/org/apache/iotdb/confignode/partition/PartitionTable.java, confignode/src/main/java/org/apache/iotdb/confignode/service/balancer/LoadBalancer.java, confignode/src/main/java/org/apache/iotdb/confignode/service/basic/ConfigServiceProvider.java, confignode/src/main/java/org/apache/iotdb/confignode/service/thrift/impl/ConfigServiceImpl.java, pom.xml, thrift-confignode/pom.xml, thrift-confignode/src/main/thrift/confignode.thrift
Document: [Partition interfaces](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=199536930)
=> [IOTDB-1656] Basic framework of ConfigNode

docs/Download/README.md, docs/zh/Download/README.md
=> [Doc] Update download links for release v0.12.5

integration/src/test/java/org/apache/iotdb/db/integration/IoTDBWithoutAnyNullIT.java, server/src/main/java/org/apache/iotdb/db/query/dataset/RawQueryDataSetWithValueFilter.java, tsfile/src/main/java/org/apache/iotdb/tsfile/read/common/RowRecord.java
You can see details in [JIRA-2694](https://issues.apache.org/jira/browse/IOTDB-2694)
=> [IOTDB-2694] fix without null any bug in raw query with value filter

server/src/main/java/org/apache/iotdb/db/engine/compaction/CompactionUtils.java, server/src/main/java/org/apache/iotdb/db/engine/compaction/inner/utils/InnerSpaceCompactionUtils.java, server/src/main/java/org/apache/iotdb/db/engine/compaction/inner/utils/SingleSeriesCompactionExecutor.java, server/src/test/java/org/apache/iotdb/db/engine/compaction/CompactionUtilsTest.java, server/src/test/java/org/apache/iotdb/db/engine/compaction/inner/InnerSpaceCompactionUtilsNoAlignedTest.java, server/src/test/java/org/apache/iotdb/db/engine/compaction/utils/CompactionCheckerUtils.java
See JIRA: https://issues.apache.org/jira/browse/IOTDB-2692
=> [IOTDB-2692] Fix compaction exception caused by deleted timeseries

server/src/main/java/org/apache/iotdb/db/engine/compaction/CompactionTaskManager.java, server/src/main/java/org/apache/iotdb/db/engine/compaction/cross/AbstractCrossSpaceCompactionTask.java, server/src/main/java/org/apache/iotdb/db/engine/compaction/cross/rewrite/RewriteCrossSpaceCompactionSelector.java, server/src/main/java/org/apache/iotdb/db/engine/compaction/cross/rewrite/task/RewriteCrossSpaceCompactionTask.java, server/src/main/java/org/apache/iotdb/db/engine/compaction/inner/AbstractInnerSpaceCompactionTask.java, server/src/main/java/org/apache/iotdb/db/engine/compaction/inner/sizetiered/SizeTieredCompactionSelector.java, server/src/main/java/org/apache/iotdb/db/engine/compaction/inner/sizetiered/SizeTieredCompactionTask.java, server/src/main/java/org/apache/iotdb/db/engine/compaction/task/AbstractCompactionTask.java, server/src/main/java/org/apache/iotdb/db/engine/storagegroup/TsFileResource.java, server/src/test/java/org/apache/iotdb/db/engine/compaction/CompactionTaskManagerTest.java
see [IOTDB-2651](https://issues.apache.org/jira/browse/IOTDB-2651)
=> [IOTDB-2651] Fix write performance deteriorates severely

integration/src/test/java/org/apache/iotdb/db/integration/IoTDBQueryWithRecreatedTimeseriesIT.java, server/src/main/java/org/apache/iotdb/db/query/reader/series/SeriesReader.java
See JIRA: https://issues.apache.org/jira/browse/IOTDB-2697
This commit also refines the IT cases of IoTDBQueryWithComplexValueFilterIT.
=> [IOTDB-2697] Add metadata modification validation before accelerating query by statistics

client-py/setup.py, docs/UserGuide/API/Programming-Python-Native-API.md, docs/zh/UserGuide/API/Programming-Python-Native-API.md
=> [IOTDB-2707] Update Python API userguide

cluster/src/main/java/org/apache/iotdb/cluster/log/Snapshot.java, cluster/src/main/java/org/apache/iotdb/cluster/log/snapshot/MetaSimpleSnapshot.java, cluster/src/main/java/org/apache/iotdb/cluster/log/snapshot/PartitionedSnapshot.java, cluster/src/main/java/org/apache/iotdb/cluster/server/handlers/caller/HeartbeatHandler.java, cluster/src/main/java/org/apache/iotdb/cluster/server/member/RaftMember.java, cluster/src/test/java/org/apache/iotdb/cluster/log/snapshot/MetaSimpleSnapshotTest.java, cluster/src/test/java/org/apache/iotdb/cluster/log/snapshot/PartitionedSnapshotTest.java, cluster/src/test/java/org/apache/iotdb/cluster/server/handlers/caller/HeartbeatHandlerTest.java, thrift-cluster/src/main/thrift/cluster.thrift
See JIRA: https://issues.apache.org/jira/browse/IOTDB-2711
=> [IOTDB-2711] Fix memory allocation deadlock caused by concurrent snapshot requests

.github/dependabot.yml
Update dependabot to check rel/0.13 branch.
=> Update dependabot to check rel/0.13

.github/workflows/influxdb-protocol.yml
see https://issues.apache.org/jira/browse/IOTDB-2728
=> [IOTDB-2728] fix influxdb-protocol yaml

antlr/src/main/antlr4/org/apache/iotdb/db/qp/sql/SqlLexer.g4, client-cpp/src/main/Session.h, integration/src/test/java/org/apache/iotdb/db/integration/IoTDBEncodingIT.java
Additional code of PR #4939 
Add cpp and sql support for ZIGZAG encoding.
=> [IOTDB-2461] Add cpp and sql support for ZIGZAG encoding

tsfile/src/main/java/org/apache/iotdb/tsfile/write/record/Tablet.java
=> [IOTDB-2735] Remove the redundant code in Tablet

tsfile/src/main/java/org/apache/iotdb/tsfile/write/record/Tablet.java
=> [To rel/0.13][IOTDB-2735] Remove the redundant code in Tablet

integration/src/test/java/org/apache/iotdb/db/integration/IOTDBInsertIT.java, server/src/main/java/org/apache/iotdb/db/utils/CommonUtils.java
See IOTDB-2732
Cherry pick #5210
=> [To rel/0.13][IOTDB-2732] Reject inserting an invalid infinity float value 

server/src/main/java/org/apache/iotdb/mpp/memory/LocalMemoryManager.java, server/src/main/java/org/apache/iotdb/mpp/memory/MemoryPool.java, server/src/test/java/org/apache/iotdb/mpp/memory/MemoryPoolTest.java
=> [To_new_mpp] Basic query memory control

.github/dependabot.yml
=> Fix depandabot

docs/UserGuide/Administration-Management/Administration.md, docs/zh/UserGuide/Administration-Management/Administration.md
Add a DELETE_STORAGE_GROUP;
Modify LIST_USER about descriptions.
=> Rel/0.13-update UserGuide about Administration

docs/UserGuide/Administration-Management/Administration.md, docs/zh/UserGuide/Administration-Management/Administration.md
Add a DELETE_STORAGE_GROUP;
Modify LIST_USER about descriptions.
=> Update UserGuide descriptions

tsfile/src/main/java/org/apache/iotdb/tsfile/write/chunk/AlignedChunkGroupWriterImpl.java, tsfile/src/main/java/org/apache/iotdb/tsfile/write/chunk/NonAlignedChunkGroupWriterImpl.java, tsfile/src/main/java/org/apache/iotdb/tsfile/write/chunk/ValueChunkWriter.java, tsfile/src/test/java/org/apache/iotdb/tsfile/write/TsFileWriteApiTest.java
=> Revert "[IOTDB-2614]Fix inserting tablet with null value in TsFileWriter"

pom.xml
=> [IOTDB-1593] Fix generated files in client-py have unapproved license

server/src/main/java/org/apache/iotdb/db/metadata/mtree/MTree.java, server/src/test/java/org/apache/iotdb/db/metadata/MManagerBasicTest.java
ISSUE link: https://issues.apache.org/jira/browse/IOTDB-2749
=> [To rel/0.13][IOTDB-2749]Fix isPathExist check on MTree

server/src/main/java/org/apache/iotdb/db/metadata/mtree/MTree.java, server/src/test/java/org/apache/iotdb/db/metadata/MManagerBasicTest.java
ISSUE link:
https://issues.apache.org/jira/browse/IOTDB-2749
=> [IOTDB-2749]Fix isPathExist check on MTree

flink-tsfile-connector/src/test/java/org/apache/iotdb/flink/tsfile/RowTSRecordOutputFormatIntegrationTest.java, flink-tsfile-connector/src/test/java/org/apache/iotdb/flink/tsfile/RowTsFileInputFormatIT.java, flink-tsfile-connector/src/test/java/org/apache/iotdb/flink/tsfile/RowTsFileInputFormatIntegrationTest.java, tsfile/src/main/java/org/apache/iotdb/tsfile/utils/MeasurementGroup.java
The following failed tests not be executed in CI.
=> [IOTDB-2755] Fix tests of flink-tsfile-connector not executed in CI

testcontainer/pom.xml
=> Fix rel/0.13 compile error

.github/workflows/grafana-plugin.yml, grafana-plugin/package.json, grafana-plugin/src/componments/ControlValue.tsx, grafana-plugin/src/componments/FromValue.tsx, grafana-plugin/src/componments/SelectValue.tsx, grafana-plugin/src/componments/WhereValue.tsx, grafana-plugin/src/datasource.ts, grafana-plugin/yarn.lock
Upgrade node-sass to 7.0.1.
Fix the following error
=> [IOTDB-2765] Fix grafana plugin compile error on lastest arm macos

server/src/main/java/org/apache/iotdb/db/protocol/influxdb/constant/InfluxConstant.java, server/src/main/java/org/apache/iotdb/db/protocol/influxdb/handler/QueryHandler.java
see https://issues.apache.org/jira/browse/IOTDB-2772
=> [IOTDB-2772] Fix influxdb build error

server/src/main/java/org/apache/iotdb/db/mpp/sql/planner/plan/node/metedata/read/ShowDevicesNode.java, server/src/main/java/org/apache/iotdb/db/mpp/sql/planner/plan/node/metedata/read/ShowNode.java, server/src/main/java/org/apache/iotdb/db/mpp/sql/planner/plan/node/metedata/write/CreateTimeSeriesNode.java, server/src/main/java/org/apache/iotdb/db/mpp/sql/planner/plan/node/write/InsertMultiTabletNode.java, server/src/main/java/org/apache/iotdb/db/mpp/sql/planner/plan/node/write/InsertNode.java, server/src/main/java/org/apache/iotdb/db/mpp/sql/planner/plan/node/write/InsertRowNode.java, server/src/main/java/org/apache/iotdb/db/mpp/sql/planner/plan/node/write/InsertRowsNode.java, server/src/main/java/org/apache/iotdb/db/mpp/sql/planner/plan/node/write/InsertRowsOfOneDeviceNode.java, server/src/main/java/org/apache/iotdb/db/mpp/sql/planner/plan/node/write/InsertTabletNode.java
In this pr, we add all insert related PlanNode and some metadata related PlanNode.
It's just an example PlanNode, should be implemented carefully by others in the future.
=> Add write node and metadata node

compile-tools/thrift/pom.xml
https://github.com/apache/iotdb/runs/5622681131?check_suite_focus=true
=> [To rel/0.13] Fix c++ compile error for macos

metrics/interface/src/main/assembly/resources/conf/iotdb-metric.yml, server/src/main/java/org/apache/iotdb/db/metrics/micrometer/registry/IoTDBRegistryConfig.java, server/src/main/java/org/apache/iotdb/db/service/IoTDB.java
https://issues.apache.org/jira/browse/IOTDB-2777
=> [IOTDB-2777][metrics]Fix NPE and sample frequency

tsfile/src/main/java/org/apache/iotdb/tsfile/write/chunk/NonAlignedChunkGroupWriterImpl.java
You can see details in [JIRA-2776](https://issues.apache.org/jira/browse/IOTDB-2776)
=> [IOTDB-2776] Improve the TsFileWriter's method: write(Tablet tablet)

server/src/main/java/org/apache/iotdb/db/engine/memtable/AlignedWritableMemChunk.java, server/src/main/java/org/apache/iotdb/db/engine/memtable/IWritableMemChunk.java
Aligned mem chunk is not synchronized properly. This pr is to fix this problem.
=> [To 0.13][IOTDB-2787] Fix aligned mem chunk concurrent problem

server/src/main/java/org/apache/iotdb/db/engine/memtable/AlignedWritableMemChunk.java, server/src/main/java/org/apache/iotdb/db/engine/memtable/IWritableMemChunk.java
Aligned mem chunk is not synchronized properly. This pr is to fix this problem.
=> [IOTDB-2787] Fix aligned mem chunk concurrent problem

server/src/main/java/org/apache/iotdb/db/mpp/common/FragmentInstanceId.java, server/src/main/java/org/apache/iotdb/db/mpp/schedule/task/FragmentInstanceTask.java, server/src/main/java/org/apache/iotdb/db/mpp/schedule/task/FragmentInstanceTaskID.java, server/src/main/java/org/apache/iotdb/db/mpp/sql/planner/plan/FragmentInstance.java
The PR[https://github.com/apache/iotdb/pull/5327] led to compile error after merge with master.
This PR is used to fix the issue.
=> [IoTDB-2260] Fix the compile error after merge PR 5327

server/src/main/java/org/apache/iotdb/db/mpp/buffer/IDataBlockManager.java, thrift/src/main/thrift/mpp.thrift
1. Add IDataBlockManager for mock testing
2. Rename FragmentInstanceId to ThriftFragmentInstanceId to avoid conflicts
=> [IOTDB-2727] add interface for mock testing

server/src/main/java/org/apache/iotdb/db/engine/cache/TimeSeriesMetadataCache.java, server/src/main/java/org/apache/iotdb/db/utils/FileLoaderUtils.java
=> [To rel/0.13] [IOTDB-2775] Fix throwing exception when query non-exist device in TsFileSequenceReader

server/src/main/java/org/apache/iotdb/db/mpp/buffer/IDataBlockManager.java, server/src/main/java/org/apache/iotdb/db/mpp/common/MPPQueryContext.java, server/src/main/java/org/apache/iotdb/db/mpp/execution/Coordinator.java, server/src/main/java/org/apache/iotdb/db/mpp/execution/QueryExecution.java, server/src/main/java/org/apache/iotdb/db/service/InternalServiceImpl.java, server/src/test/java/org/apache/iotdb/db/mpp/sql/plan/DistributionPlannerTest.java, thrift/src/main/thrift/mpp.thrift
* Add InternalService definition to mpp.thrift.
* Add QueryType to MPPQueryContext
=> [IOTDB-2666] Add InternalService to mpp.thrift

consensus/src/main/resources/logback-test.xml
Open Ratis logging to debug CI fail.
=> open ratis log

server/src/assembly/resources/sbin/stop-server.sh
https://issues.apache.org/jira/browse/IOTDB-2824
=> [IOTDB-2824] fix stop-server.sh that wrongly kill process

server/src/assembly/resources/sbin/stop-server.sh
https://issues.apache.org/jira/browse/IOTDB-2824
=> [To rel/0.13][IOTDB-2824] fix stop-server.sh that wrongly kill process

server/src/main/java/org/apache/iotdb/db/metadata/path/MeasurementPath.java, server/src/main/java/org/apache/iotdb/db/mpp/common/schematree/SchemaEntityNode.java, server/src/main/java/org/apache/iotdb/db/mpp/common/schematree/SchemaInternalNode.java, server/src/main/java/org/apache/iotdb/db/mpp/common/schematree/SchemaMeasurementNode.java, server/src/main/java/org/apache/iotdb/db/mpp/common/schematree/SchemaNode.java, server/src/main/java/org/apache/iotdb/db/mpp/common/schematree/SchemaTree.java, server/src/main/java/org/apache/iotdb/db/mpp/common/schematree/SchemaTreeVisitor.java, server/src/test/java/org/apache/iotdb/db/mpp/common/SchemaTreeTest.java, server/src/test/java/org/apache/iotdb/db/mpp/sql/plan/QueryPlannerTest.java
Implement the local search interface of SchemaTree via SchemaTreeVisitor. Now it support * and **, slimit and offset, and alias.
Implement SchemaTree serialize and deserialize, and ISchemaFetcher.
=> Implement SchemaTree Search

confignode/src/main/java/org/apache/iotdb/confignode/service/thrift/server/ConfigNodeRPCServerProcessor.java, node-commons/src/main/java/org/apache/iotdb/commons/partition/DataPartitionQueryParam.java, server/src/main/java/org/apache/iotdb/db/mpp/sql/analyze/Analyzer.java, server/src/main/java/org/apache/iotdb/db/mpp/sql/analyze/ClusterPartitionFetcher.java, server/src/main/java/org/apache/iotdb/db/mpp/sql/analyze/FakePartitionFetcherImpl.java, server/src/main/java/org/apache/iotdb/db/mpp/sql/analyze/IPartitionFetcher.java, server/src/main/java/org/apache/iotdb/db/mpp/sql/analyze/StandalonePartitionFetcher.java, thrift-confignode/src/main/thrift/confignode.thrift
Add some interfaces in ConfigIService, which are used in IPartitionFetcher.
=> Add interface in ConfigIService

client-py/README.md, client-py/SessionExample.py, client-py/SessionTest.py, docs/UserGuide/API/Programming-Python-Native-API.md, docs/zh/UserGuide/API/Programming-Python-Native-API.md
Update python client doc and code for NumpyTablet.
=> [To rel/0.13] Update python client doc and code for NumpyTablet

client-py/README.md, client-py/SessionExample.py, client-py/SessionTest.py, docs/UserGuide/API/Programming-Python-Native-API.md, docs/zh/UserGuide/API/Programming-Python-Native-API.md
Update python client doc and code for NumpyTablet.
=> Update python client doc and code for NumpyTablet

docs/UserGuide/Maintenance-Tools/Metric-Tool.md, docs/zh/UserGuide/Maintenance-Tools/Metric-Tool.md, metrics/dropwizard-metrics/src/main/java/org/apache/iotdb/metrics/dropwizard/reporter/IoTDBReporter.java, metrics/interface/src/main/assembly/resources/conf/iotdb-metric.yml, metrics/interface/src/main/java/org/apache/iotdb/metrics/config/MetricConfig.java, metrics/interface/src/test/resources/iotdb-metric.yml, metrics/micrometer-metrics/src/main/java/org/apache/iotdb/metrics/micrometer/reporter/IoTDBMeterRegistry.java
See more details: https://issues.apache.org/jira/browse/IOTDB-2819
=> [IOTDB-2819][metrics] modify session to session pool.

server/src/main/java/org/apache/iotdb/db/utils/ErrorHandlingUtils.java
See JIRA: https://issues.apache.org/jira/browse/IOTDB-2836
=> [IOTDB-2836] Fix ErrorHandlingUtils exception stacktrace logging

integration/src/test/java/org/apache/iotdb/session/IoTDBSessionSimpleIT.java, tsfile/src/main/java/org/apache/iotdb/tsfile/write/record/Tablet.java
This PR creates syntactic sugar by supporting String value insertion to Tablet. #[IOTDB-2650]
=> [IOTDB-2650] Tablet supports adding String value

consensus/README.md
Add README.md to consensus package, including the overview and usage.
=> [IOTDB-2833] Add readme to consensus

example/rest-client-c-example/README.md, example/rest-client-c-example/base64.c, example/rest-client-c-example/base64.h, example/rest-client-c-example/main.c
=> Add c rest client example

cli/pom.xml
I found that this dependency is not used in code.
=> [IOTDB-2843] remove unused jna dependency in cli

server/src/main/java/org/apache/iotdb/db/utils/EnvironmentUtils.java, server/src/test/java/org/apache/iotdb/db/engine/modification/DeletionFileNodeTest.java
Cherry pick #5435
<hr>
This PR has:
<hr>
=> [To rel/0.13][IOTDB-2855] Fix DeletionFileNodeTest error

server/src/assembly/resources/conf/iotdb-engine.properties, server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java, server/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java, server/src/main/java/org/apache/iotdb/db/mpp/buffer/DataBlockManager.java, server/src/main/java/org/apache/iotdb/db/mpp/buffer/DataBlockService.java, server/src/main/java/org/apache/iotdb/db/mpp/buffer/DataBlockServiceClientFactory.java, server/src/main/java/org/apache/iotdb/db/mpp/buffer/DataBlockServiceThriftHandler.java, server/src/main/java/org/apache/iotdb/db/mpp/buffer/IDataBlockManager.java, server/src/main/java/org/apache/iotdb/db/mpp/buffer/ISinkHandle.java, server/src/main/java/org/apache/iotdb/db/mpp/buffer/ISourceHandle.java, server/src/main/java/org/apache/iotdb/db/mpp/buffer/SinkHandle.java, server/src/main/java/org/apache/iotdb/db/mpp/buffer/SourceHandle.java, server/src/main/java/org/apache/iotdb/db/mpp/buffer/StubSinkHandle.java, server/src/main/java/org/apache/iotdb/db/mpp/buffer/TsBlockSerde.java, server/src/main/java/org/apache/iotdb/db/mpp/buffer/TsBlockSerdeFactory.java, server/src/main/java/org/apache/iotdb/db/mpp/execution/DataDriver.java, server/src/main/java/org/apache/iotdb/db/mpp/execution/SchemaDriver.java, server/src/main/java/org/apache/iotdb/db/mpp/memory/LocalMemoryManager.java, server/src/main/java/org/apache/iotdb/db/mpp/memory/MemoryPool.java, server/src/test/java/org/apache/iotdb/db/mpp/buffer/SinkHandleTest.java, server/src/test/java/org/apache/iotdb/db/mpp/buffer/SourceHandleTest.java, server/src/test/java/org/apache/iotdb/db/mpp/buffer/Utils.java, server/src/test/java/org/apache/iotdb/db/mpp/memory/MemoryPoolTest.java, thrift/src/main/thrift/mpp.thrift
Design: https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=199538158
=> [IOTDB-2727] data block manager impl

server/src/main/java/org/apache/iotdb/db/mpp/buffer/DataBlockService.java
Add a static getInstance method for DataBlockService.
=> [IOTDB-2727] add DataBlockService#getInstance

grafana-connector/src/main/java/org/apache/iotdb/web/grafana/controller/DatabaseConnectController.java, grafana-connector/src/main/java/org/apache/iotdb/web/grafana/dao/impl/BasicDaoImpl.java
See JIRA: https://issues.apache.org/jira/browse/IOTDB-2862
=> [IOTDB-2862] Fix SQL injection and XSS risks of grafana-connector

site/src/main/.vuepress/config.js
rollback config.js
<hr>
This PR has:
<hr>
=> Site Rollback

server/src/main/java/org/apache/iotdb/db/protocol/influxdb/handler/QueryHandler.java, server/src/main/java/org/apache/iotdb/db/protocol/mqtt/PublishHandler.java, server/src/main/java/org/apache/iotdb/db/protocol/rest/handler/AuthorizationHandler.java, server/src/main/java/org/apache/iotdb/db/protocol/rest/impl/GrafanaApiServiceImpl.java, server/src/main/java/org/apache/iotdb/db/protocol/rest/impl/RestApiServiceImpl.java, server/src/main/java/org/apache/iotdb/db/query/control/SessionManager.java, server/src/main/java/org/apache/iotdb/db/service/basic/ServiceProvider.java, server/src/main/java/org/apache/iotdb/db/service/thrift/impl/InfluxDBServiceImpl.java, server/src/main/java/org/apache/iotdb/db/service/thrift/impl/TSServiceImpl.java
In order to clarify the responsibility of serviceProvider, we need to move some session related methods to sessionManager.
=> [IOTDB-2857] Move methods in serviceProvider to sessionManager

confignode/src/main/java/org/apache/iotdb/confignode/physical/sys/AuthorPlan.java, server/src/main/java/org/apache/iotdb/db/mpp/sql/planner/plan/node/metedata/write/AuthorNode.java
user SerializeDeserializeUtil in confignode/AuthorPlan
fix bug NullPointerException in confignode/AuthorPlan.serialize
=> [IOTDB-2869] use SerializeDeserializeUtil in confignode/AuthorPlan

client-py/README.md, client-py/SessionExample.py, client-py/iotdb/utils/IoTDBConstants.py, client-py/iotdb/utils/NumpyTablet.py, client-py/tests/test_numpy_tablet.py, docs/UserGuide/API/Programming-Python-Native-API.md, docs/zh/UserGuide/API/Programming-Python-Native-API.md
Cherry-pick (#5448)
<hr>
This PR has:
<hr>
=> [To rel/0.13][IOTDB-2838] Check and auto correct endian type for NumpyTablet

server/src/main/java/org/apache/iotdb/db/mpp/common/schematree/PathPatternNode.java, server/src/main/java/org/apache/iotdb/db/mpp/common/schematree/PathPatternTree.java, server/src/test/java/org/apache/iotdb/db/mpp/common/PathPatternTreeTest.java
Implement serialize and deserialize method for PathPatternTree.
=> Implement serialize and deserialize method for PathPatternTree

example/rest-client-c-example/CMakeLists.txt
=> Add the ignore CMakeLists.txt

server/src/main/java/org/apache/iotdb/db/mpp/buffer/DataBlockManager.java, server/src/main/java/org/apache/iotdb/db/mpp/buffer/IDataBlockManager.java, server/src/main/java/org/apache/iotdb/db/mpp/execution/QueryExecution.java, server/src/main/java/org/apache/iotdb/db/mpp/sql/planner/LocalExecutionPlanner.java
Please see: https://issues.apache.org/jira/projects/IOTDB/issues/IOTDB-2890
=> [IOTDB-2890] Dynamic port support for DataBlockManager

server/src/main/java/org/apache/iotdb/db/engine/StorageEngineV2.java
=> fix StorageEngineV2 cannot start

example/rest-client-c-example/main.c
Update the deviceId name in c rest example.
=> Update the deviceId in c rest example

confignode/pom.xml
remove unnecessary dependencies
=> Consensus dep

integration/src/test/java/org/apache/iotdb/db/integration/IoTDBMetadataFetchIT.java, server/src/main/java/org/apache/iotdb/db/metadata/lastCache/LastCacheManager.java
=> [IOTDB-2903] Fix last value fetch failure during show timesereis

integration/src/test/java/org/apache/iotdb/session/IoTDBSessionDisableMemControlIT.java, integration/src/test/java/org/apache/iotdb/session/IoTDBSessionSimpleIT.java, integration/src/test/java/org/apache/iotdb/session/IoTDBSessionVectorInsertIT.java, server/src/main/java/org/apache/iotdb/db/exception/metadata/DataTypeMismatchException.java, server/src/main/java/org/apache/iotdb/db/metadata/idtable/IDTableHashmapImpl.java, server/src/main/java/org/apache/iotdb/db/metadata/schemaregion/SchemaRegion.java, server/src/main/java/org/apache/iotdb/db/metadata/schemaregion/SchemaRegionUtils.java, server/src/main/java/org/apache/iotdb/db/metadata/schemaregion/rocksdb/RSchemaRegion.java, server/src/main/java/org/apache/iotdb/db/mpp/sql/statement/crud/InsertRowStatement.java, server/src/main/java/org/apache/iotdb/db/mpp/sql/statement/crud/InsertTabletStatement.java, server/src/main/java/org/apache/iotdb/db/wal/recover/file/TsFilePlanRedoer.java, server/src/test/java/org/apache/iotdb/db/metadata/idtable/IDTableTest.java
See JIRA: https://issues.apache.org/jira/browse/IOTDB-2901
=> [IOTDB-2901] Refine codes of DataTypeMismatchException and checkDataTypeMatch

integration/src/test/java/org/apache/iotdb/db/integration/IoTDBDeleteStorageGroupIT.java, server/src/main/java/org/apache/iotdb/db/engine/storagegroup/VirtualStorageGroupProcessor.java, server/src/main/java/org/apache/iotdb/db/qp/executor/PlanExecutor.java
=> [To rel/0.13][IOTDB-2910] Fix Count aggregate is not right after delete sg bug

server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfigCheck.java
=> [To rel/0.13][IOTDB-2828] Update system_version in system.properties after upgrading finished

tsfile/src/main/java/org/apache/iotdb/tsfile/read/common/block/column/BinaryArrayColumnEncoder.java, tsfile/src/main/java/org/apache/iotdb/tsfile/read/common/block/column/ByteArrayColumnEncoder.java, tsfile/src/main/java/org/apache/iotdb/tsfile/read/common/block/column/ColumnEncoder.java, tsfile/src/main/java/org/apache/iotdb/tsfile/read/common/block/column/ColumnEncoderFactory.java, tsfile/src/main/java/org/apache/iotdb/tsfile/read/common/block/column/Int32ArrayColumnEncoder.java, tsfile/src/test/java/org/apache/iotdb/tsfile/common/block/BinaryArrayColumnEncoderTest.java, tsfile/src/test/java/org/apache/iotdb/tsfile/common/block/ByteArrayColumnEncoderTest.java, tsfile/src/test/java/org/apache/iotdb/tsfile/common/block/Int32ArrayColumnEncoderTest.java, tsfile/src/test/java/org/apache/iotdb/tsfile/common/block/Int64ArrayColumnEncoderTest.java, tsfile/src/test/java/org/apache/iotdb/tsfile/common/block/TsBlockSerdeTest.java
Please see: https://issues.apache.org/jira/browse/IOTDB-2909
=> [IOTDB-2909] ColumnEncoder(s) for BOOLEAN and TEXT

.github/workflows/influxdb-protocol.yml, antlr/src/main/antlr4/org/apache/iotdb/db/qp/sql/InfluxDBSqlParser.g4, docker/src/main/Dockerfile-single-influxdb, docs/UserGuide/API/InfluxDB-Protocol.md, docs/zh/UserGuide/API/InfluxDB-Protocol.md, influxdb-protocol/src/main/java/org/apache/iotdb/influxdb/IoTDBInfluxDB.java, influxdb-protocol/src/main/java/org/apache/iotdb/influxdb/protocol/dto/SessionPoint.java, influxdb-protocol/src/test/java/org/apache/iotdb/influxdb/integration/IoTDBInfluxDBIT.java, server/src/main/java/org/apache/iotdb/db/protocol/influxdb/handler/QueryHandler.java, server/src/main/java/org/apache/iotdb/db/protocol/influxdb/meta/InfluxDBMetaManager.java, server/src/main/java/org/apache/iotdb/db/protocol/influxdb/util/QueryResultUtils.java
see [[IOTDB-2913]](https://issues.apache.org/jira/browse/IOTDB-2913)
=> [IOTDB-2913] Add InfluxDB Protocol Test Framework

integration/src/test/java/org/apache/iotdb/db/integration/sync/IoTDBSyncReceiverIT.java, integration/src/test/java/org/apache/iotdb/db/integration/sync/SyncTestUtil.java
cause by tsfiles with same name
=> [IOTDB-2923] fix CI IoTDBSyncReceiverIT.testReceiveDataAndLoad

confignode/src/main/java/org/apache/iotdb/confignode/persistence/PartitionInfoPersistence.java, server/src/main/java/org/apache/iotdb/db/mpp/sql/planner/plan/FragmentInstance.java
Fix the spotless issue in PR 5540
=> Fix the spotless issue in PR 5540

server/src/main/java/org/apache/iotdb/db/auth/AuthorityChecker.java
See IOTDB-2902 for more detail.
=> [IOTDB-2902] Handling user privileges for aligned timeseries related features

server/src/main/java/org/apache/iotdb/db/query/udf/core/layer/MultiInputColumnIntermediateLayer.java, server/src/main/java/org/apache/iotdb/db/query/udf/core/layer/SingleInputColumnMultiReferenceIntermediateLayer.java, server/src/main/java/org/apache/iotdb/db/query/udf/core/layer/SingleInputColumnSingleReferenceIntermediateLayer.java
See IOTDB-2924 for more details.
=> [IOTDB-2924] UDF Framework: index overflow while iterating sliding size windows

metrics/dropwizard-metrics/pom.xml, pom.xml, server/pom.xml
See more details: https://issues.apache.org/jira/browse/IOTDB-2927.
=> [IOTDB-2927][to rel/0.13] fix metric related dependency.

server/src/main/java/org/apache/iotdb/db/auth/AuthorityChecker.java
See IOTDB-2902 for more detail.
(cherry picked from commit 8ed3f3ad5d46e2b822092a328a84b8d2a35bde1c)
=> [To rel/0.13][IOTDB-2902] Handling user privileges for aligned timeseries related features (#5556)

server/src/main/java/org/apache/iotdb/db/engine/compaction/inner/utils/MultiTsFileDeviceIterator.java, server/src/main/java/org/apache/iotdb/db/service/IoTDBShutdownHook.java
Same as [PR-5553](https://github.com/apache/iotdb/pull/5553)
=> [To rel/0.13] [IOTDB-2922] Fix NPE when compacting with files that contains zero device

distribution/src/assembly/all.xml, distribution/src/assembly/server.xml, docs/UserGuide/Maintenance-Tools/Metric-Tool.md, docs/zh/UserGuide/Maintenance-Tools/Metric-Tool.md, grafana-metrics-example/Apache IoTDB Dashboard v0.13.1.json
See more details: https://issues.apache.org/jira/browse/IOTDB-2873.
Thanks for the help from @xinzhongtianxia during the creation of Apache IoTDB Dashboard.
=> [IOTDB-2873][to rel/0.13]add Apache IoTDB Dashboard grafana template

server/src/main/java/org/apache/iotdb/db/engine/flush/ApproximateFlushGroupingEngine.java
=> add column-groups storage with exact and approximate evaluations

server/src/main/java/org/apache/iotdb/db/wal/buffer/WALBuffer.java, server/src/main/java/org/apache/iotdb/db/wal/node/WALNode.java
Make SerializeTask look more clear.
=> Format SerializeTask in WALBuffer

server/src/main/java/org/apache/iotdb/db/mpp/execution/config/ConfigExecution.java, server/src/main/java/org/apache/iotdb/db/mpp/execution/scheduler/ClusterScheduler.java, server/src/test/java/org/apache/iotdb/db/mpp/execution/ConfigExecutionTest.java
Fix 2 sonar issues in PR https://github.com/apache/iotdb/pull/5596
=> Add Thread re-interrupt when catching exception

docs/zh/UserGuide/Ecosystem Integration/Grafana Plugin.md
=> [IOTDB-2619][User Docs] Grafana Plugin: Alerting 

docs/UserGuide/Ecosystem Integration/Grafana Plugin.md
[User Docs -EN] Grafana Plugin: Alerting
=> [User Docs -EN] Grafana Plugin: Alerting

server/src/main/java/org/apache/iotdb/db/mpp/buffer/DataBlockManager.java, server/src/main/java/org/apache/iotdb/db/mpp/buffer/ISinkHandle.java, server/src/main/java/org/apache/iotdb/db/mpp/buffer/ISourceHandle.java, server/src/main/java/org/apache/iotdb/db/mpp/buffer/SinkHandle.java, server/src/main/java/org/apache/iotdb/db/mpp/buffer/SourceHandle.java, server/src/test/java/org/apache/iotdb/db/mpp/buffer/SinkHandleTest.java, server/src/test/java/org/apache/iotdb/db/mpp/buffer/SourceHandleTest.java
1. Fix sink handle memory leak
2. Add UT(s)
3. Fix docs
=> [IOTDB-2971] Fix sink handle memory leak

procedure/src/main/java/org/apache/iotdb/procedure/CompletedProcedureCleaner.java, procedure/src/main/java/org/apache/iotdb/procedure/Procedure.java, procedure/src/main/java/org/apache/iotdb/procedure/ProcedureExecutor.java, procedure/src/main/java/org/apache/iotdb/procedure/store/ProcedureWAL.java
=> [IOTDB-2880] Fix import check style

checkstyle.xml, docs/UserGuide/Operate-Metadata/Node.md, docs/UserGuide/Operate-Metadata/Storage-Group.md, docs/zh/UserGuide/Operate-Metadata/Node.md, docs/zh/UserGuide/Operate-Metadata/Storage-Group.md
You can see the [details](https://issues.apache.org/jira/browse/IOTDB-2976).
=> [IOTDB-2976] Add English and Chinese docs for count devices and count storage groups

server/src/main/java/org/apache/iotdb/db/mpp/sql/planner/plan/node/write/InsertNode.java, server/src/main/java/org/apache/iotdb/db/mpp/sql/planner/plan/node/write/InsertRowNode.java, server/src/main/java/org/apache/iotdb/db/mpp/sql/planner/plan/node/write/InsertTabletNode.java, server/src/main/java/org/apache/iotdb/db/wal/recover/file/TsFilePlanRedoer.java, server/src/main/java/org/apache/iotdb/db/wal/utils/WALWriteUtils.java
Support recovering TsFile from InsertNode.
=> [IOTDB-2982] Recover tsfile after datanode restart

confignode/src/test/resources/confignode1conf/iotdb-confignode.properties, confignode/src/test/resources/confignode1conf/logback.xml, confignode/src/test/resources/confignode2conf/iotdb-confignode.properties, confignode/src/test/resources/confignode2conf/logback.xml, confignode/src/test/resources/confignode3conf/iotdb-confignode.properties, confignode/src/test/resources/confignode3conf/logback.xml, server/src/test/resources/datanode1conf/iotdb-engine.properties, server/src/test/resources/datanode1conf/iotdb-metric.yml, server/src/test/resources/datanode1conf/logback.xml, server/src/test/resources/datanode2conf/iotdb-engine.properties, server/src/test/resources/datanode2conf/iotdb-metric.yml, server/src/test/resources/datanode2conf/logback.xml, server/src/test/resources/datanode3conf/iotdb-engine.properties, server/src/test/resources/datanode3conf/iotdb-metric.yml, server/src/test/resources/datanode3conf/logback.xml
Give a config example for new cluster(3 confignode and 3 datanode)
Developer can use these config files when debug in IDEA
=> Add config example for new cluster

consensus/src/main/java/org/apache/iotdb/consensus/ratis/RatisConsensus.java, consensus/src/test/java/org/apache/iotdb/consensus/ratis/RatisConsensusTest.java
Remove RaftGroupMap and RaftClientMap, which are unable to auto recovery during restart.
=> [IOTDB-2984] RatisConsensus Recovery Logic

metrics/interface/src/main/java/org/apache/iotdb/metrics/config/MetricConfig.java, server/src/main/java/org/apache/iotdb/db/service/metrics/MetricsService.java
see more details: https://issues.apache.org/jira/browse/IOTDB-2999
=> [IOTDB-2999][Metric] remove useless config and fix default value error.

metrics/interface/src/main/java/org/apache/iotdb/metrics/config/MetricConfig.java, server/src/main/java/org/apache/iotdb/db/service/metrics/MetricsService.java
See more details:https://issues.apache.org/jira/browse/IOTDB-2999
=> [IOTDB-2999][to rel/0.13][Metric] remove useless config and fix default value error.

node-commons/src/main/java/org/apache/iotdb/commons/conf/IoTDBConstant.java, server/src/main/java/org/apache/iotdb/db/service/DataNode.java, server/src/main/java/org/apache/iotdb/db/service/IoTDB.java
=> [IOTDB-3007] Separate DataNode and IoTDB

server/src/main/java/org/apache/iotdb/db/sync/pipedata/queue/BufferedPipeDataQueue.java, server/src/main/java/org/apache/iotdb/db/sync/receiver/manager/ReceiverManager.java, server/src/test/java/org/apache/iotdb/db/sync/receiver/manager/ReceiverManagerTest.java, server/src/test/java/org/apache/iotdb/db/sync/receiver/recovery/ReceiverLogAnalyzerTest.java
https://issues.apache.org/jira/browse/IOTDB-3003
=> [IOTDB-3003]  data sync pipe recover bug & other issues

docs/UserGuide/Ecosystem Integration/DBeaver.md, docs/zh/UserGuide/Ecosystem Integration/DBeaver.md
Update the dbeaver-IoTDB user guide.
=> Update dbeaver user guide

integration/src/test/java/org/apache/iotdb/db/integration/IoTDBPartialInsertionIT.java, server/src/main/java/org/apache/iotdb/db/qp/physical/crud/InsertRowPlan.java, server/src/main/java/org/apache/iotdb/db/qp/physical/crud/InsertTabletPlan.java
Serialization of failed data types and values causes error when redoing wal, so remove serialization of failed data types and values.
=> [To rel/0.13][IOTDB-2983] Serialization error in Partial insert

integration/src/test/java/org/apache/iotdb/db/integration/IoTDBPartialInsertionIT.java, server/src/main/java/org/apache/iotdb/db/qp/physical/crud/InsertRowPlan.java, server/src/main/java/org/apache/iotdb/db/qp/physical/crud/InsertTabletPlan.java
Serialization of failed data types and values causes error when redoing wal, so remove serialization of failed data types and values.
=> [IOTDB-2983] Serialization error in Partial insert 

docs/UserGuide/Maintenance-Tools/Sync-Tool.md, docs/zh/UserGuide/Maintenance-Tools/Sync-Tool.md
update user guide for sync
user guide:https://y8dp9fjm8f.feishu.cn/docs/doccnC12jS88aYWnmlmXkYstZAd
=> [IOTDB-2701]User guide for Sync

integration/src/test/java/org/apache/iotdb/db/integration/IoTDBInsertNullIT.java, server/src/main/java/org/apache/iotdb/db/engine/memtable/AbstractMemTable.java
Judge null value and skip its' schema when inserting non-aligned row.
=> [To rel/0.13][IOTDB-2753] Insert a time series with a null value and report 500

cluster/src/main/java/org/apache/iotdb/cluster/query/manage/ClusterSessionManager.java, confignode/src/main/java/org/apache/iotdb/confignode/manager/ConfigManager.java, confignode/src/main/java/org/apache/iotdb/confignode/manager/Manager.java, confignode/src/main/java/org/apache/iotdb/confignode/persistence/AuthorInfo.java, confignode/src/main/java/org/apache/iotdb/confignode/service/thrift/ConfigNodeRPCServiceProcessor.java, server/src/main/java/org/apache/iotdb/db/auth/authorizer/AuthorizerManager.java, server/src/main/java/org/apache/iotdb/db/auth/authorizer/ClusterAuthorizer.java, server/src/main/java/org/apache/iotdb/db/client/ConfigNodeClient.java, server/src/main/java/org/apache/iotdb/db/service/thrift/impl/DataNodeTSIServiceImpl.java, service-rpc/src/main/java/org/apache/iotdb/rpc/ConfigNodeConnectionException.java, thrift-confignode/src/main/thrift/confignode.thrift
Authenticate login via confignode
=> [IOTDB-3015] Authenticate login via confignode

integration/src/test/java/org/apache/iotdb/db/integration/IoTDBInsertNullIT.java, server/src/main/java/org/apache/iotdb/db/engine/memtable/AbstractMemTable.java
Judge null value and skip its' schema when inserting non-aligned row.
=> [IOTDB-2753] Insert a time series with a null value and report 500

server/src/main/java/org/apache/iotdb/db/service/thrift/impl/DataNodeTSIServiceImpl.java
=> fix typo in DataNodeTSIServiceImpl

server/src/main/java/org/apache/iotdb/db/utils/QueryDataSetUtils.java
https://issues.apache.org/jira/browse/IOTDB-3023
=> [iotdb-3023][new-cluster]Fix write bitmap when converting TsBlock to DataSet

.github/workflows/sonar-coveralls.yml
=> Disable sonar check for PRs from fork repo

server/src/main/java/org/apache/iotdb/db/mpp/sql/analyze/ClusterPartitionFetcher.java
https://issues.apache.org/jira/browse/IOTDB-3032
=> [IOTDB-3032]Fix storage group cache

server/src/main/java/org/apache/iotdb/db/metadata/tree/AbstractTreeVisitor.java, server/src/test/java/org/apache/iotdb/db/mpp/common/schematree/SchemaTreeTest.java
=> fix root.**.*

server/src/main/java/org/apache/iotdb/db/mpp/sql/analyze/ClusterPartitionFetcher.java
See more details: https://issues.apache.org/jira/browse/IOTDB-3036
=> [IOTDB-3036][Partition Cache] Add auto create judge when get deviceToStorageGroupMap

node-commons/src/test/java/org/apache/iotdb/commons/ClientManagerTest.java
See JIRA: https://issues.apache.org/jira/browse/IOTDB-3046
=> [IOTDB-3046] Fix port binding error in ClientManagerTest

server/src/main/java/org/apache/iotdb/db/engine/compaction/CompactionTaskManager.java, server/src/main/java/org/apache/iotdb/db/engine/compaction/cross/rewrite/task/RewriteCrossSpaceCompactionTask.java, server/src/main/java/org/apache/iotdb/db/engine/compaction/inner/sizetiered/SizeTieredCompactionTask.java, server/src/main/java/org/apache/iotdb/db/engine/compaction/inner/utils/InnerSpaceCompactionUtils.java, server/src/main/java/org/apache/iotdb/db/engine/compaction/task/AbstractCompactionTask.java, server/src/main/java/org/apache/iotdb/db/engine/compaction/task/CompactionTaskSummary.java, server/src/test/java/org/apache/iotdb/db/engine/compaction/CompactionTaskManagerTest.java, server/src/test/java/org/apache/iotdb/db/engine/compaction/inner/InnerCompactionEmptyTsFileTest.java
=> [To rel/0.13][IOTDB-3018] Fix compation bugs on handling deleted target file

server/src/main/java/org/apache/iotdb/db/mpp/buffer/DataBlockManager.java, server/src/main/java/org/apache/iotdb/db/mpp/buffer/IDataBlockManager.java, server/src/main/java/org/apache/iotdb/db/mpp/buffer/LocalSinkHandle.java, server/src/main/java/org/apache/iotdb/db/mpp/buffer/LocalSourceHandle.java, server/src/main/java/org/apache/iotdb/db/mpp/buffer/SharedTsBlockQueue.java, server/src/test/java/org/apache/iotdb/db/mpp/buffer/DataBlockManagerTest.java, server/src/test/java/org/apache/iotdb/db/mpp/buffer/LocalSinkHandleTest.java, server/src/test/java/org/apache/iotdb/db/mpp/buffer/LocalSourceHandleTest.java, server/src/test/java/org/apache/iotdb/db/mpp/buffer/SharedTsBlockQueueTest.java, server/src/test/java/org/apache/iotdb/db/mpp/buffer/SourceHandleTest.java, server/src/test/java/org/apache/iotdb/db/mpp/buffer/Utils.java
Please see: https://issues.apache.org/jira/browse/IOTDB-2972
=> [IOTDB-2972] implement local sink/source handle

server/src/main/java/org/apache/iotdb/db/mpp/sql/planner/DistributionPlanner.java, server/src/main/java/org/apache/iotdb/db/mpp/sql/planner/LogicalPlanner.java
Fix incorrect columnToTsBlockIndexMap for query result set
=> Fix incorrect columnToTsBlockIndexMap for query result set

server/src/main/java/org/apache/iotdb/db/query/expression/Expression.java
Make every method and every field clearer.
=> Refactor abstract class Expression

confignode/src/main/java/org/apache/iotdb/confignode/conf/ConfigNodeDescriptor.java, server/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java
See more details: https://issues.apache.org/jira/browse/IOTDB-3096
=> [IOTDB-3096] [Auth] fix default config of user folder and role folder

server/src/assembly/resources/sbin/stop-server.sh, server/src/main/java/org/apache/iotdb/db/service/IoTDBShutdownHook.java
https://issues.apache.org/jira/browse/IOTDB-3016
=> [IOTDB-3016] do flush when graceful stop IoTDB

server/src/main/java/org/apache/iotdb/db/engine/compaction/cross/CrossSpaceCompactionTask.java, server/src/main/java/org/apache/iotdb/db/engine/compaction/inner/InnerSpaceCompactionTask.java
See [IOTDB-3113](https://issues.apache.org/jira/browse/IOTDB-3113)
=> [IOTDB-3113] Add speed log for compaction

server/src/main/java/org/apache/iotdb/db/engine/compaction/cross/rewrite/task/RewriteCrossSpaceCompactionTask.java, server/src/main/java/org/apache/iotdb/db/engine/compaction/inner/sizetiered/SizeTieredCompactionTask.java
See [IOTDB-3113](https://issues.apache.org/jira/browse/IOTDB-3113)
=> [to rel/0.13][IOTDB-3113] Add speed log for compaction

server/src/main/java/org/apache/iotdb/db/query/control/SessionManager.java
See more details: https://issues.apache.org/jira/browse/IOTDB-3112
After fixed:
=> [IOTDB-3112] fix login log.

grafana-plugin/src/QueryEditor.tsx
Fixed bug when switching query style
=> Grafana Plugin: fixed NPE when switching query style

docs/UserGuide/Ecosystem Integration/Grafana Plugin.md, docs/zh/UserGuide/Ecosystem Integration/Grafana Plugin.md
grafana connector input style doc
=> [IOTDB-2285][User docs] IoTDB Grafana Plugin: Grafana Connector Input Style

docs/Development/HowToJoin.md, docs/zh/Development/HowToJoin.md, site/src/main/.vuepress/config.js
=> Doc file update

server/src/main/java/org/apache/iotdb/db/mpp/plan/parser/StatementGenerator.java, server/src/main/java/org/apache/iotdb/db/service/thrift/impl/DataNodeTSIServiceImpl.java
This pr implements the follow API for new cluster.
* SetStorageGroup
* CreateTimeseries
* CreateAlignedTimeseries
=> Support create sg and timeseries by session API in new cluster

confignode/src/main/java/org/apache/iotdb/confignode/conf/ConfigNodeDescriptor.java, node-commons/src/main/java/org/apache/iotdb/commons/auth/role/LocalFileRoleAccessor.java, node-commons/src/main/java/org/apache/iotdb/commons/auth/user/LocalFileUserAccessor.java, node-commons/src/main/java/org/apache/iotdb/commons/conf/CommonConfig.java, server/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java
See more details: https://issues.apache.org/jira/browse/IOTDB-3139
=> [IOTDB-3139] fix place of auth folder.

library-udf/pom.xml, library-udf/src/main/java/org/apache/iotdb/library/dprofile/UDTFPACF.java, library-udf/src/main/java/org/apache/iotdb/library/dprofile/UDTFQLB.java, library-udf/src/main/java/org/apache/iotdb/library/dprofile/util/MADSketch.java, library-udf/src/main/java/org/apache/iotdb/library/dprofile/util/Resampler.java, library-udf/src/main/java/org/apache/iotdb/library/dquality/util/TimeSeriesQuality.java, library-udf/src/main/java/org/apache/iotdb/library/drepair/util/ARFill.java, library-udf/src/main/java/org/apache/iotdb/library/drepair/util/LikelihoodFill.java, library-udf/src/main/java/org/apache/iotdb/library/drepair/util/LsGreedy.java, library-udf/src/main/java/org/apache/iotdb/library/drepair/util/Screen.java, library-udf/src/main/java/org/apache/iotdb/library/drepair/util/ScreenFill.java, library-udf/src/main/java/org/apache/iotdb/library/drepair/util/TimestampRepair.java, library-udf/src/main/java/org/apache/iotdb/library/drepair/util/ValueFill.java, library-udf/src/main/java/org/apache/iotdb/library/drepair/util/ValueRepair.java, library-udf/src/main/java/org/apache/iotdb/library/frequency/util/FFTUtil.java, library-udf/src/main/java/org/apache/iotdb/library/util/LinearRegression.java, library-udf/src/main/java/org/apache/iotdb/library/util/Util.java
This PR contains some bug fixing for library-udf.
<hr>
This PR has:
<hr>
=> [IOTDB-3143] Potential bug fix for library-udf

cluster/src/main/java/org/apache/iotdb/cluster/query/groupby/ClusterGroupByNoVFilterDataSet.java, integration/src/test/java/org/apache/iotdb/db/integration/aligned/IoTDBGroupByQueryWithoutValueFilterIT.java, server/src/main/java/org/apache/iotdb/db/query/aggregation/AggregateResult.java, server/src/main/java/org/apache/iotdb/db/query/aggregation/impl/AvgAggrResult.java, server/src/main/java/org/apache/iotdb/db/query/aggregation/impl/CountAggrResult.java, server/src/main/java/org/apache/iotdb/db/query/aggregation/impl/ExtremeAggrResult.java, server/src/main/java/org/apache/iotdb/db/query/aggregation/impl/FirstValueAggrResult.java, server/src/main/java/org/apache/iotdb/db/query/aggregation/impl/FirstValueDescAggrResult.java, server/src/main/java/org/apache/iotdb/db/query/aggregation/impl/LastValueAggrResult.java, server/src/main/java/org/apache/iotdb/db/query/aggregation/impl/LastValueDescAggrResult.java, server/src/main/java/org/apache/iotdb/db/query/aggregation/impl/MaxTimeAggrResult.java, server/src/main/java/org/apache/iotdb/db/query/aggregation/impl/MaxTimeDescAggrResult.java, server/src/main/java/org/apache/iotdb/db/query/aggregation/impl/MaxValueAggrResult.java, server/src/main/java/org/apache/iotdb/db/query/aggregation/impl/MinTimeAggrResult.java, server/src/main/java/org/apache/iotdb/db/query/aggregation/impl/MinTimeDescAggrResult.java, server/src/main/java/org/apache/iotdb/db/query/aggregation/impl/MinValueAggrResult.java, server/src/main/java/org/apache/iotdb/db/query/aggregation/impl/SumAggrResult.java, server/src/main/java/org/apache/iotdb/db/query/dataset/groupby/GroupByWithoutValueFilterDataSet.java, server/src/main/java/org/apache/iotdb/db/query/dataset/groupby/LocalAlignedGroupByExecutor.java, server/src/main/java/org/apache/iotdb/db/query/dataset/groupby/LocalGroupByExecutor.java, server/src/main/java/org/apache/iotdb/db/utils/QueryUtils.java, server/src/test/java/org/apache/iotdb/db/query/aggregation/DescAggregateResultTest.java, tsfile/src/main/java/org/apache/iotdb/tsfile/read/common/BatchData.java, tsfile/src/main/java/org/apache/iotdb/tsfile/read/common/IBatchDataIterator.java
=> [To rel/0.13] [ISSUE-5773] Fix missing data in group by query

confignode/src/main/java/org/apache/iotdb/confignode/persistence/NodeInfo.java
=> Fix config node compile error

metrics/dropwizard-metrics/src/main/java/org/apache/iotdb/metrics/dropwizard/reporter/IoTDBReporter.java, metrics/micrometer-metrics/src/main/java/org/apache/iotdb/metrics/micrometer/reporter/IoTDBMeterRegistry.java
The problem:
See more details: https://issues.apache.org/jira/browse/IOTDB-3158
=> [IOTDB-3158][metric] fix NPE exception.

metrics/dropwizard-metrics/src/main/java/org/apache/iotdb/metrics/dropwizard/reporter/IoTDBReporter.java, metrics/micrometer-metrics/src/main/java/org/apache/iotdb/metrics/micrometer/reporter/IoTDBMeterRegistry.java
See more details: [IOTDB-3158](https://issues.apache.org/jira/browse/IOTDB-3158)
=> [IOTDB-3158][to rel/0.13][metric] fix NPE exception.

server/src/main/java/org/apache/iotdb/db/mpp/plan/parser/StatementGenerator.java, server/src/main/java/org/apache/iotdb/db/service/thrift/impl/DataNodeTSIServiceImpl.java
This PR also fixes some incorrect OperateType in exception massage.
=> [IOTDB-3186] Support DeleteStorageGroups API for new cluster

confignode/src/main/java/org/apache/iotdb/confignode/consensus/statemachine/PartitionRegionStateMachine.java, confignode/src/main/java/org/apache/iotdb/confignode/manager/ClusterSchemaManager.java, confignode/src/main/java/org/apache/iotdb/confignode/manager/ConfigManager.java, confignode/src/main/java/org/apache/iotdb/confignode/manager/ConsensusManager.java, confignode/src/main/java/org/apache/iotdb/confignode/manager/Manager.java, confignode/src/main/java/org/apache/iotdb/confignode/manager/NodeManager.java, confignode/src/main/java/org/apache/iotdb/confignode/manager/PartitionManager.java, confignode/src/main/java/org/apache/iotdb/confignode/manager/PermissionManager.java, confignode/src/main/java/org/apache/iotdb/confignode/manager/ProcedureManager.java, confignode/src/main/java/org/apache/iotdb/confignode/persistence/AuthorInfo.java, confignode/src/main/java/org/apache/iotdb/confignode/persistence/ClusterSchemaInfo.java, confignode/src/main/java/org/apache/iotdb/confignode/persistence/NodeInfo.java, confignode/src/main/java/org/apache/iotdb/confignode/persistence/PartitionInfo.java, confignode/src/main/java/org/apache/iotdb/confignode/persistence/ProcedureInfo.java, confignode/src/main/java/org/apache/iotdb/confignode/persistence/executor/ConfigRequestExecutor.java, confignode/src/main/java/org/apache/iotdb/confignode/procedure/ConfigProcedureStore.java, confignode/src/main/java/org/apache/iotdb/confignode/procedure/DeleteStorageGroupProcedure.java, confignode/src/main/java/org/apache/iotdb/confignode/procedure/DeleteStorageGroupState.java, confignode/src/test/java/org/apache/iotdb/confignode/manager/hash/DeviceGroupHashExecutorManualTest.java, confignode/src/test/java/org/apache/iotdb/confignode/persistence/AuthorInfoTest.java, confignode/src/test/java/org/apache/iotdb/confignode/persistence/ClusterSchemaInfoTest.java, confignode/src/test/java/org/apache/iotdb/confignode/persistence/NodeInfoTest.java, confignode/src/test/java/org/apache/iotdb/confignode/persistence/PartitionInfoTest.java, confignode/src/test/java/org/apache/iotdb/confignode/service/thrift/ConfigNodeRPCServiceProcessorTest.java
Cancel singleton mode of the following classes:
1. AuthorInfo
2. ClusterSchemaInfo
3. NodeInfo
4. PartitionInfo
5. ProcedureInfo
=> [IOTDB-3183] Cancel the singleton mode in the ConfigNode's persistence module

confignode/src/assembly/resources/sbin/stop-confignode.bat, server/src/assembly/resources/sbin/stop-server.bat
On windows, stop-server.bat not work
=> [IOTDB-3219] fix stop-server on windows

integration/src/test/java/org/apache/iotdb/db/integration/sync/IoTDBSyncReceiverIT.java, server/src/main/java/org/apache/iotdb/db/sync/conf/SyncConstant.java, server/src/main/java/org/apache/iotdb/db/sync/receiver/ReceiverService.java, server/src/main/java/org/apache/iotdb/db/sync/receiver/collector/Collector.java, server/src/main/java/org/apache/iotdb/db/sync/receiver/recovery/ReceiverLogAnalyzer.java, server/src/main/java/org/apache/iotdb/db/sync/sender/pipe/Pipe.java, server/src/main/java/org/apache/iotdb/db/sync/sender/service/TransportHandler.java, server/src/test/java/org/apache/iotdb/db/sync/receiver/recovery/ReceiverLogAnalyzerTest.java
[IOTDB-3144][IOTDB-3130][IOTDB-3133]
=> [IOTDB-3144][IOTDB-3130][IOTDB-3133] Set the default pipe status of receiver after reboot to STOP

consensus/src/main/java/org/apache/iotdb/consensus/wal/ConsensusReqReader.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/write/InsertNode.java, server/src/main/java/org/apache/iotdb/db/wal/node/IWALNode.java, server/src/main/java/org/apache/iotdb/db/wal/node/WALFakeNode.java, server/src/main/java/org/apache/iotdb/db/wal/node/WALNode.java
1. Add ConsensusReqReader in consensus module
2. Serialize via IConsensusRequest#serializeRequest
3. Deserialize via PlanNodeType#deserialize
=> [IOTDB-3196] Add wal read interface for consensus group

schema-engine-rocksdb/src/main/java/org/apache/iotdb/db/metadata/schemaregion/rocksdb/RSchemaRegion.java, server/src/main/java/org/apache/iotdb/db/consensus/statemachine/SchemaRegionStateMachine.java, server/src/main/java/org/apache/iotdb/db/metadata/MetadataConstant.java, server/src/main/java/org/apache/iotdb/db/metadata/logfile/MLogWriter.java, server/src/main/java/org/apache/iotdb/db/metadata/schemaregion/ISchemaRegion.java, server/src/main/java/org/apache/iotdb/db/metadata/schemaregion/SchemaRegionMemoryImpl.java, server/src/main/java/org/apache/iotdb/db/metadata/schemaregion/SchemaRegionSchemaFileImpl.java, server/src/main/java/org/apache/iotdb/db/metadata/tag/TagLogFile.java, server/src/main/java/org/apache/iotdb/db/metadata/tag/TagManager.java, server/src/test/java/org/apache/iotdb/db/metadata/schemaRegion/SchemaRegionTest.java
Implement snapshot feature for SchemaRegion Memory mode to speed up schemaRegion consensus group recovery
=> [IOTDB-3024] Implement SchemaRegion Memory mode snapshot

server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/write/InsertMultiTabletsNode.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/write/InsertNode.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/write/InsertRowNode.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/write/InsertRowsNode.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/write/InsertRowsOfOneDeviceNode.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/write/InsertTabletNode.java, server/src/test/java/org/apache/iotdb/db/mpp/plan/plan/node/write/InsertTabletNodeSerdeTest.java
Add search index in InsertNode
=> [IOTDB-3196] Add search index in InsertNode

confignode/src/main/java/org/apache/iotdb/confignode/persistence/NodeInfo.java, confignode/src/main/java/org/apache/iotdb/confignode/persistence/PartitionInfo.java, node-commons/src/main/java/org/apache/iotdb/commons/partition/DataPartition.java, node-commons/src/main/java/org/apache/iotdb/commons/partition/SchemaPartition.java, node-commons/src/test/java/org/apache/iotdb/commons/partition/DataPartitionTest.java, node-commons/src/test/java/org/apache/iotdb/commons/partition/SchemaPartitionTest.java
Remove dataOutputStream and dataInputStream and use ReadWriteIOUtils instead.
=> remove dataOutputStream

tsfile/src/main/java/org/apache/iotdb/tsfile/read/common/Path.java
For aligned path, sensor is "". see more details at: [IOTDB-3239](https://issues.apache.org/jira/browse/IOTDB-3239)
=> [IOTDB-3239] fix missing aligned data

confignode/src/main/java/org/apache/iotdb/confignode/conf/ConfigNodeDescriptor.java, confignode/src/test/java/org/apache/iotdb/confignode/persistence/AuthorInfoTest.java, node-commons/src/main/java/org/apache/iotdb/commons/conf/CommonConfig.java, node-commons/src/main/java/org/apache/iotdb/commons/conf/CommonDescriptor.java, node-commons/src/main/java/org/apache/iotdb/commons/conf/IoTDBConstant.java, server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java, server/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java
See more details: https://issues.apache.org/jira/browse/IOTDB-3241
=> [IOTDB-3241] Fix default value in common config

server/src/main/java/org/apache/iotdb/db/service/thrift/impl/InternalServiceImpl.java, thrift-commons/src/main/thrift/common.thrift
See more details: https://issues.apache.org/jira/browse/IOTDB-3202
=> [IOTDB-3202] Add cpu load and memory load into heartbeat.

grafana-connector/src/main/java/org/apache/iotdb/web/grafana/controller/DatabaseConnectController.java
fix grafana conncetor sql injection
=> [Vulnerability] Fix grafana conncetor SQL injection issue

site/src/main/.vuepress/theme/global-components/IoTDB.vue
[[IOTDB-3128] Homepage does not work well on mobile](https://issues.apache.org/jira/browse/IOTDB-3128?jql=project%20%3D%20IOTDB%20AND%20resolution%20%3D%20Unresolved%20AND%20assignee%20in%20(currentUser()%2C%20EMPTY)%20ORDER%20BY%20created%20DESC%2C%20priority%20DESC%2C%20updated%20DESC)
<hr>
This PR has:
- [] added documentation for new or modified features or behaviors.
<hr>
=> [IOTDB-3128] Homepage does not work well on mobile

server/src/main/java/org/apache/iotdb/db/mpp/common/schematree/PathPatternTree.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/Analyzer.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/parser/ASTVisitor.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/LogicalPlanBuilder.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/PlanNodeType.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/metedata/write/DeleteTimeSeriesNode.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/metedata/write/InvalidateSchemaCacheNode.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/write/DeleteDataNode.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/statement/StatementVisitor.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/statement/metadata/DeleteTimeSeriesStatement.java, server/src/test/java/org/apache/iotdb/db/mpp/plan/plan/node/metadata/write/DeleteTimeSeriesNodeSerdeTest.java, server/src/test/java/org/apache/iotdb/db/mpp/plan/plan/node/write/DeleteDataNodeSerdeTest.java, server/src/test/java/org/apache/iotdb/db/mpp/plan/plan/node/write/InvalidateSchemaCacheNodeSerdeTest.java
see https://apache-iotdb.feishu.cn/docs/doccnbJ6DD4OXgoHNAX9WzbxcDb#
Set up the following classes.
=> [IOTDB-3184] Set up Delete timeseries statement and PlanNodes

integration/src/test/java/org/apache/iotdb/session/IoTDBSessionSyntaxConventionIT.java, server/src/main/java/org/apache/iotdb/db/service/thrift/impl/DataNodeTSIServiceImpl.java, server/src/main/java/org/apache/iotdb/db/service/thrift/impl/TSServiceImpl.java
This PR aims to ensure that restrictions on path in  RPC is the same as SQL statement.
=> [IOTDB-3072] add measurement syntax check in TSServiceImpl and DataNodeTSIServiceImpl

grafana-connector/src/main/java/org/apache/iotdb/web/grafana/controller/DatabaseConnectController.java, grafana-connector/src/main/java/org/apache/iotdb/web/grafana/dao/impl/BasicDaoImpl.java
fixed grafana connector sql inject
=> fixed grafana connector sql inject

server/src/assembly/resources/tools/tsfileToolSet/validate-tsfile.bat, server/src/assembly/resources/tools/tsfileToolSet/validate-tsfile.sh, server/src/main/java/org/apache/iotdb/db/tools/validate/TsFileValidationTool.java
**This tool can be used to check the correctness of tsfile and point out errors in specific timeseries or devices. The types of errors include the following:**
Device overlap between files
Timeseries overlap between files
Timeseries overlap between chunks
Timeseries overlap between pages
Timeseries overlap within one page
See docs in https://apache-iotdb.feishu.cn/docs/doccnMEahfencKFr6Uat2Mpwevf?from=from_copylink
=> [IOTDB-3246]TsFile Validation Tool

server/src/test/java/org/apache/iotdb/db/engine/compaction/cross/RewriteCompactionFileSelectorTest.java
=> Temporarily disable testDeleteinSelection in RewriteCompactionFileSelectorTest

spark-tsfile/src/main/java/org/apache/iotdb/spark/tsfile/qp/common/SQLConstant.java
https://github.com/apache/iotdb/security/code-scanning
=> Fix code scanning issue in spark tsfile SQLConstant

confignode/src/main/java/org/apache/iotdb/confignode/client/SyncDataNodeClientPool.java, confignode/src/main/java/org/apache/iotdb/confignode/consensus/request/ConfigRequest.java, confignode/src/main/java/org/apache/iotdb/confignode/consensus/request/ConfigRequestType.java, confignode/src/main/java/org/apache/iotdb/confignode/consensus/request/write/PreDeleteStorageGroupReq.java, confignode/src/main/java/org/apache/iotdb/confignode/manager/ConfigManager.java, confignode/src/main/java/org/apache/iotdb/confignode/manager/PartitionManager.java, confignode/src/main/java/org/apache/iotdb/confignode/manager/ProcedureManager.java, confignode/src/main/java/org/apache/iotdb/confignode/persistence/PartitionInfo.java, confignode/src/main/java/org/apache/iotdb/confignode/persistence/executor/ConfigRequestExecutor.java, confignode/src/main/java/org/apache/iotdb/confignode/procedure/env/ConfigNodeProcedureEnv.java, confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/DeleteStorageGroupProcedure.java, confignode/src/test/java/org/apache/iotdb/confignode/persistence/PartitionInfoTest.java, confignode/src/test/java/org/apache/iotdb/confignode/procedure/TestProcedureBase.java, confignode/src/test/java/org/apache/iotdb/confignode/procedure/TestProcedureExecutor.java, confignode/src/test/java/org/apache/iotdb/confignode/procedure/TestSTMProcedure.java, confignode/src/test/java/org/apache/iotdb/confignode/procedure/entity/IncProcedure.java, confignode/src/test/java/org/apache/iotdb/confignode/procedure/entity/NoopProcedure.java, confignode/src/test/java/org/apache/iotdb/confignode/procedure/entity/SimpleLockProcedure.java, confignode/src/test/java/org/apache/iotdb/confignode/procedure/entity/SimpleSTMProcedure.java, confignode/src/test/java/org/apache/iotdb/confignode/procedure/entity/SleepProcedure.java, confignode/src/test/java/org/apache/iotdb/confignode/procedure/entity/StuckProcedure.java, confignode/src/test/java/org/apache/iotdb/confignode/procedure/entity/StuckSTMProcedure.java, confignode/src/test/java/org/apache/iotdb/confignode/procedure/env/TestConfigNodeEnv.java, confignode/src/test/java/org/apache/iotdb/confignode/procedure/env/TestProcEnv.java, confignode/src/test/java/org/apache/iotdb/confignode/procedure/store/TestProcedureStore.java, confignode/src/test/java/org/apache/iotdb/confignode/service/thrift/ConfigNodeRPCServiceProcessorTest.java, confignode/src/test/resources/confignode1conf/iotdb-confignode.properties, node-commons/src/main/java/org/apache/iotdb/commons/partition/DataPartition.java, node-commons/src/main/java/org/apache/iotdb/commons/partition/SchemaPartition.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/ClusterSchemaFetcher.java
Related Document: https://apache-iotdb.feishu.cn/docs/doccnNfLy04a485TYEXaYIkGr8b
1. create schema and data
```SQL
set storage group to root.sg; 
create timeseries root.sg.d.s1 with datatype=INT32,encoding=RLE,compression=snappy;
create timeseries root.sg.d.s2 with datatype=INT32,encoding=RLE,compression=snappy;
create timeseries root.sg.d.s3 with datatype=INT32,encoding=RLE,compression=snappy; 
insert into root.sg.d(time,s1,s2,s3) values(1,1,2,3); 
insert into root.sg.d(time,s1,s2,s3) values(2,1,2,3); 
insert into root.sg.d(time,s1,s2,s3) values(3,1,2,3); 
insert into root.sg.d(time,s1,s2,s3) values(4,1,2,3); 
set storage group to root.sg1; 
create timeseries root.sg1.d.s1 with datatype=INT32,encoding=RLE,compression=snappy;
create timeseries root.sg1.d.s2 with …
```
=> [IOTDB-2919] Refactor delete storage group

site/src/main/.vuepress/theme/components/Page.vue, site/src/main/.vuepress/theme/global-components/IoTDB.vue, site/src/main/.vuepress/theme/global-components/IoTDBZH.vue
[[IOTDB-3265] Button Text of Main Features Section Overflow on Mobile Version Homepage](https://issues.apache.org/jira/browse/IOTDB-3265)
In addition to resolving the issue above, I've also made the following changes to the homepage enabling a more responsive layout on mobile:
1. Adjust the title (Apache IoTDB) font size to make it more suitable for viewing on mobile.
2. Resize the "Download" and "Quickstart" buttons to make them aligned on mobile.
3. Resize the carousel to make the whole text visible on mobile and adjust the content position for the desktop view to prevent large empty space.
The following screenshots are the comparison between the mobile (on my 6.1 inches phone) and desktop versions after the changes:
Original (mobile version):
New (mobile version):
Old (desktop …
=> [IOTDB-3265] Button Text of Main Features Section Overflow on Mobile Version Homepage

server/src/main/java/org/apache/iotdb/db/metadata/cache/DataNodeLastCacheManager.java
See more details: https://issues.apache.org/jira/browse/IOTDB-3270
=> [IOTDB-3270] add lastCacheEnable in use.

confignode/src/main/java/org/apache/iotdb/confignode/manager/PartitionManager.java
1. Change regionCleaner work interval from 5s to 300s
2. Change method name and extract fields
=> [IOTDB-2919] Delete StorageGroup / Change regionCleaner work interval from 5s to 300s

library-udf/pom.xml, pom.xml
[IOTDB-3281] Replacing log4j with reload4j
=> [IOTDB-3281] Replacing log4j with reload4j

site/src/main/.vuepress/theme/global-components/IoTDB.vue, site/src/main/.vuepress/theme/global-components/IoTDBZH.vue
=> Revert "[IOTDB-3286] False Carousel Ratio on Desktop Version Homepage"

site/src/main/.vuepress/theme/global-components/IoTDB.vue, site/src/main/.vuepress/theme/global-components/IoTDBZH.vue
Issue: [[IOTDB-3286] False Carousel Ratio on Desktop Version Homepage](https://issues.apache.org/jira/browse/IOTDB-3286)
Hi,
This is the improved version without using DOM in Javascript which cannot be performed on node.js on the server-side. Instead, I applied CSS media properties on the carousel to make it responsive to the device. 
Besides, I believe the image size should also be responsive to the screen ratio instead of being out of shape viewing on mobile. I thus made it adjust its size due to the screen size.
Hope it works this time :-)
These are the final results after applying CSS media properties:
Mobile:
Desktop:
<hr>
This PR has:
<hr>
=> [IOTDB-3286] False Carousel Ratio on Desktop Version Homepage

docs/UserGuide/Reference/TSDB-Comparison.md, docs/zh/UserGuide/Reference/TSDB-Comparison.md
Modify the statement in the reference subsection of the Chinese and English documentation: remove the 2 PR that have not been merged, leaving 1 statement that has indeed been merged. Because saying PR have been submitted which is unserious, code only has two state :merged or not merged, the content submitted for review is meaningless to the user.
=> [iotdb-3294]sentence deletion in dos

server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/distribution/ExchangeNodeAdder.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/distribution/SourceRewriter.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/process/LastQueryMergeNode.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/source/AlignedLastQueryScanNode.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/source/LastQueryScanNode.java, server/src/test/java/org/apache/iotdb/db/mpp/plan/plan/distribution/DistributionPlannerBasicTest.java, server/src/test/java/org/apache/iotdb/db/mpp/plan/plan/distribution/LastQueryTest.java
* Refactor some common logic in `SourceRewriter`
* Complete the distribution planning for last query
=> [IoTDB-3304] complete last query distribution plan

server/src/main/java/org/apache/iotdb/db/engine/compaction/utils/CompactionUtils.java, server/src/test/java/org/apache/iotdb/db/engine/compaction/LevelCompactionMergeTest.java
See [IOTDB-3292](https://issues.apache.org/jira/browse/IOTDB-3292)
=> [To rel/0.12][IOTDB-3292] Fix chunk size overflow in level compaction

server/src/main/java/org/apache/iotdb/db/service/DataNode.java
see [jira3240](https://issues.apache.org/jira/projects/IOTDB/issues/IOTDB-3240?filter=allopenissues)
=> [IOTDB-3240] [ErrorMSG]java.lang.IllegalStateException: Client has an error!Caused by: java.net.ConnectException: Connection refused

server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/LogicalPlanBuilder.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/LogicalPlanner.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/distribution/SourceRewriter.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/process/AggregationNode.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/process/GroupByLevelNode.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/source/AlignedSeriesAggregationScanNode.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/source/SeriesAggregationScanNode.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/source/SeriesAggregationSourceNode.java, server/src/test/java/org/apache/iotdb/db/mpp/plan/plan/QueryLogicalPlanUtil.java, server/src/test/java/org/apache/iotdb/db/mpp/plan/plan/distribution/AggregationDistributionTest.java, server/src/test/java/org/apache/iotdb/db/mpp/plan/plan/node/process/GroupByLevelNodeSerdeTest.java
* Add `GroupbyTimeParameter` in `GroupByLevelNode`
* Add `GroupbyTimeParameter` transition in distribution planning stage for Aggregation Query
=> Add GroupbyTimeParameter in GroupByLevelNode

node-commons/src/main/java/org/apache/iotdb/commons/conf/IoTDBConstant.java, server/src/main/java/org/apache/iotdb/db/mpp/common/header/HeaderConstant.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/execution/config/ShowStorageGroupTask.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/execution/config/ShowTTLTask.java
See more details: https://issues.apache.org/jira/browse/IOTDB-3287
Test on 3c3d:
=> [IOTDB-3287] update show ttl related sql.

consensus/src/main/java/org/apache/iotdb/consensus/ratis/Utils.java
Fix: https://github.com/apache/iotdb/issues/5883 https://github.com/apache/iotdb/issues/5882
=> fix: combine the byte value with 0xff and cast one of the operands of addition to long

integration/src/test/java/org/apache/iotdb/session/IoTDBSessionSimpleIT.java, integration/src/test/java/org/apache/iotdb/session/IoTDBSessionSyntaxConventionIT.java, node-commons/src/main/java/org/apache/iotdb/commons/conf/IoTDBConstant.java, node-commons/src/main/java/org/apache/iotdb/commons/utils/PathUtils.java, server/src/main/java/org/apache/iotdb/db/service/thrift/impl/DataNodeTSIServiceImpl.java, server/src/main/java/org/apache/iotdb/db/service/thrift/impl/TSServiceImpl.java
try to check measurement using pattern
=> [IOTDB-3300] improve measurement check performance in session api

antlr/src/main/antlr4/org/apache/iotdb/db/qp/sql/IoTDBSqlParser.g4, server/src/main/java/org/apache/iotdb/db/mpp/plan/parser/ASTVisitor.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/LogicalPlanner.java
- support `CREATE STORAGE GROUP`
- fix bug when combining GroupBytime and Fill
- fix bug when using nested expressions in aggregate query
=> [IOTDB-3277] [IOTDB-3310] [IOTDB-3311] Fix some SQL parser bugs in new cluster

server/src/main/java/org/apache/iotdb/db/engine/StorageEngineV2.java, server/src/test/java/org/apache/iotdb/db/engine/StorageEngineV2Test.java
detail reason see:
https://github.com/apache/iotdb/issues/6057
=> [ISSUES-6057] Add a method(getAllDataRegionID) to StorageEngineV2

server/src/main/java/org/apache/iotdb/db/mpp/aggregation/slidingwindow/SmoothQueueSlidingWindowAggregator.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/statement/crud/QueryStatement.java, server/src/main/java/org/apache/iotdb/db/service/thrift/impl/DataNodeTSIServiceImpl.java
An exception should be thrown when using group by in raw data query.
=> [IOTDB-3325] Thrown an exception when using group by in raw data query

server/src/main/java/org/apache/iotdb/db/mpp/execution/schedule/AbstractDriverThread.java, server/src/main/java/org/apache/iotdb/db/mpp/execution/schedule/DriverScheduler.java, server/src/main/java/org/apache/iotdb/db/mpp/execution/schedule/FragmentInstanceAbortedException.java, server/src/test/java/org/apache/iotdb/db/mpp/execution/schedule/DefaultDriverSchedulerTest.java, server/src/test/java/org/apache/iotdb/db/mpp/execution/schedule/DriverSchedulerTest.java, server/src/test/java/org/apache/iotdb/db/mpp/execution/schedule/DriverTaskTimeoutSentinelThreadTest.java
See JIRA: https://issues.apache.org/jira/browse/IOTDB-3346
=> [IOTDB-3346] Clear DriverTask when any RuntimeException is thrown

confignode/src/main/java/org/apache/iotdb/confignode/persistence/executor/ConfigRequestExecutor.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/Analyzer.java
See more details: https://issues.apache.org/jira/browse/IOTDB-3336
=> [IOTDB-3336] Optimize the code 

server/src/assembly/resources/tools/tsfileToolSet/validate-tsfile.bat, server/src/assembly/resources/tools/tsfileToolSet/validate-tsfile.sh, server/src/main/java/org/apache/iotdb/db/tools/validate/TsFileValidationTool.java
See details in [IOTDB-3246](https://issues.apache.org/jira/browse/IOTDB-3246)
=> [IOTDB-3246][To rel/0.13]Validation tool

server/src/main/java/org/apache/iotdb/db/consensus/statemachine/visitor/DataExecutionVisitor.java, server/src/main/java/org/apache/iotdb/db/engine/StorageEngineV2.java, server/src/main/java/org/apache/iotdb/db/engine/storagegroup/DataRegion.java, server/src/test/java/org/apache/iotdb/db/engine/storagegroup/DataRegionTest.java
Fix IOTDB-3337
After then
<hr>
This PR has:
<hr>
=> [IOTDB-3337] return error message when insert wrong type of data

jdbc/src/main/java/org/apache/iotdb/jdbc/IoTDBDatabaseMetadata.java, tsfile/src/main/java/org/apache/iotdb/tsfile/read/query/dataset/QueryDataSet.java
detail see： https://issues.apache.org/jira/browse/IOTDB-3362
<hr>
This PR has:
<hr>
=> [IOTDB-3362]JDBC getSchemas interface return ArrayIndexOutOfBoundsException

server/src/main/java/org/apache/iotdb/db/mpp/plan/parser/ASTVisitor.java
=> [IOTDB-3357] Throw an exception when using the select-into statement

server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/process/RawDataAggregationOperator.java, server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/process/SlidingWindowAggregationOperator.java, server/src/test/java/org/apache/iotdb/db/mpp/execution/operator/RawDataAggregationOperatorTest.java, server/src/test/java/org/apache/iotdb/db/mpp/execution/operator/SlidingWindowAggregationOperatorTest.java
INCLUDING AggregationOperator and SlidingWindowAggregationOperator
=> [IOTDB-3356]  The next() of child can only be invoked once in AggregationOperator and SlidingWindowAggregationOperator

jdbc/src/main/java/org/apache/iotdb/jdbc/IoTDBDatabaseMetadata.java
small bug fix when I read this code.
<hr>
This PR has:
<hr>
=> fix IoTDBDatabaseMetadata.java spelling error

server/src/main/java/org/apache/iotdb/db/wal/node/WALNode.java
Invoke StorageEngineV2 when cluster mode enabled.
=> Adapt wal memtabe snapshot to new cluster

server/src/main/java/org/apache/iotdb/db/mpp/plan/expression/multi/FunctionExpression.java, server/src/test/resources/datanode1conf/iotdb-engine.properties, server/src/test/resources/datanode2conf/iotdb-engine.properties, server/src/test/resources/datanode3conf/iotdb-engine.properties
1. fix aggregation bug
2. change datanode test port to avoid conflict with wxwork application
<hr>
This PR has:
<hr>
=> fix aggregation bug

server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/write/InsertRowsNode.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/write/InsertRowsOfOneDeviceNode.java, server/src/main/java/org/apache/iotdb/db/service/thrift/impl/DataNodeTSIServiceImpl.java
Jira : https://issues.apache.org/jira/projects/IOTDB/issues/IOTDB-3375
=> [IOTDB-3375] Fix NPE when inserting multi-rows by SQL

server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/process/LastQueryMergeOperator.java, server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/schema/SchemaQueryOrderByHeatOperator.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/LocalExecutionPlanner.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/LogicalPlanner.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/metedata/read/SchemaQueryOrderByHeatNode.java
Problem see: [IOTDB-3366](https://issues.apache.org/jira/browse/IOTDB-3366)
After fixing, test on 3C3D:
=> [IOTDB-3366] fix npe when no data when show latest timeseries.

confignode/src/main/java/org/apache/iotdb/confignode/manager/PartitionManager.java, confignode/src/main/java/org/apache/iotdb/confignode/manager/ProcedureManager.java
Delete regions at once besides schedule in 300s interval
after deletion
=> [IOTDB-2919] Delete regions at once besides schedule in 300s interval

rewriteFileTool/src/main/java/org/apache/iotdb/RewriteFileTool.java
This PR modifies:
1. limit the size of each tablet
2. add user and password constraint
3. if file already in the backup dir, don't unload it from iotdb again.
=> Update RewriteFileTool: limit the size of each tablet

server/src/main/java/org/apache/iotdb/db/engine/compaction/CompactionTaskManager.java, server/src/main/java/org/apache/iotdb/db/engine/storagegroup/DataRegion.java, server/src/main/java/org/apache/iotdb/db/sync/sender/service/TransportHandler.java, server/src/main/java/org/apache/iotdb/db/wal/WALManager.java
See JIRA: https://issues.apache.org/jira/browse/IOTDB-3402
=> [IOTDB-3402] Fix abuse of scheduleWithFixedDelay()

confignode/src/main/java/org/apache/iotdb/confignode/conf/ConfigNodeStartupCheck.java
The confignode-system.properties file can be created if and only if ConfigNode is connected to the ConfigNodeGroup or it is confirmed that the current ConfigNode is seed.
=> [IOTDB-3209] Update ConfigNode startup process

confignode/src/main/java/org/apache/iotdb/confignode/manager/ClusterSchemaManager.java, confignode/src/main/java/org/apache/iotdb/confignode/persistence/ClusterSchemaInfo.java, server/src/main/java/org/apache/iotdb/db/metadata/mtree/MTreeAboveSG.java
See more details: https://issues.apache.org/jira/browse/IOTDB-3259
Test on 3C3D:
=> [IOTDB-3259] fix sg already exists check.

docs/UserGuide/Maintenance-Tools/Metric-Tool.md, docs/zh/UserGuide/Maintenance-Tools/Metric-Tool.md, server/src/main/java/org/apache/iotdb/db/engine/compaction/CompactionTaskManager.java, server/src/main/java/org/apache/iotdb/db/engine/compaction/inner/utils/AlignedSeriesCompactionExecutor.java, server/src/main/java/org/apache/iotdb/db/engine/compaction/inner/utils/SingleSeriesCompactionExecutor.java, server/src/main/java/org/apache/iotdb/db/engine/compaction/writer/AbstractCompactionWriter.java, server/src/main/java/org/apache/iotdb/db/metadata/cache/DataNodeSchemaCache.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/ClusterPartitionFetcher.java, server/src/main/java/org/apache/iotdb/db/service/DataNode.java, server/src/main/java/org/apache/iotdb/db/service/metrics/enums/Metric.java, server/src/main/java/org/apache/iotdb/db/service/metrics/recorder/CacheMetricsRecorder.java, server/src/main/java/org/apache/iotdb/db/service/metrics/recorder/CompactionMetricsRecorder.java
Add metrics of partition cache and schema cache.
See more detais: https://issues.apache.org/jira/browse/IOTDB-3394.
In 3C3D, it will like:
=> [IOTDB-3394] add cache metrics.

docs/UserGuide/Ecosystem Integration/Grafana Plugin.md, docs/zh/UserGuide/Ecosystem Integration/Grafana Plugin.md
=> Fixed 0.13 grafana doc

server/src/main/java/org/apache/iotdb/db/engine/storagegroup/TsFileResource.java
=> [ISSUE-5885] Synchronize this method to match the synchronization on "setModFile".

node-commons/src/main/java/org/apache/iotdb/commons/partition/DataPartition.java
=> Fix missing import in DataPartition

server/src/main/java/org/apache/iotdb/db/engine/compaction/CompactionTaskManager.java
See [IOTDB-3451](https://issues.apache.org/jira/browse/IOTDB-3451).
Current compaction task execution thread pool and sub task execution thread pool are scheduled thread pool, but we don't use them to execute any timed task.This pr changes them to normal fix size thread pool.
=> [IOTDB-3451] Set the type of compaction execution thread pool to fixed size thread pool

consensus/src/main/java/org/apache/iotdb/consensus/ratis/SnapshotStorage.java
RatisConsensus now allows application statemachine snapshot to have a nested file or folder hierarchy.
=> [IOTDB-3410] Support Snapshot Folder Hierarchy

client-py/SessionExample.py, client-py/iotdb/Session.py, client-py/iotdb/tsfile/__init__.py, client-py/iotdb/tsfile/common/__init__.py
1. Implements executeStatement method
2. Fix the problem that the tsfile package could not be found
**JIRA**: https://issues.apache.org/jira/browse/IOTDB-3441
=> [IOTDB-3441] Python API: Session implements executeStatement method

server/src/assembly/resources/sbin/start-datanode.sh, server/src/assembly/resources/sbin/start-new-server.sh, server/src/assembly/resources/sbin/start-server.sh, server/src/main/java/org/apache/iotdb/db/service/IoTDB.java, server/src/main/java/org/apache/iotdb/db/service/NewIoTDB.java
https://issues.apache.org/jira/browse/IOTDB-3424
=> [IOTDB-3424] avoid running duplicated IotDB servers

server/src/main/java/org/apache/iotdb/db/engine/StorageEngineV2.java, server/src/main/java/org/apache/iotdb/db/localconfignode/LocalConfigNode.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/execution/config/FlushTask.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/parser/ASTVisitor.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/statement/sys/FlushStatement.java, server/src/main/java/org/apache/iotdb/db/service/thrift/impl/InternalServiceImpl.java
=> Support flush in new standalone IoTDB

confignode/src/main/java/org/apache/iotdb/confignode/consensus/request/auth/AuthorReq.java
=> [IOTDB-5879]Override hashCode of AuthorReq

.github/workflows/cluster-it.yml, integration-test/README.md, integration-test/pom.xml, integration-test/src/main/java/org/apache/iotdb/it/env/ClusterEnvBase.java, integration-test/src/main/java/org/apache/iotdb/it/env/ConfigNode.java, integration-test/src/main/java/org/apache/iotdb/it/env/DataNode.java, integration-test/src/main/java/org/apache/iotdb/it/env/EnvFactory.java, integration-test/src/main/java/org/apache/iotdb/itbase/runtime/ClusterResultSetMetaData.java, integration-test/src/main/java/org/apache/iotdb/itbase/runtime/ClusterTestConnection.java, integration-test/src/main/java/org/apache/iotdb/itbase/runtime/ClusterTestResultSet.java, integration-test/src/main/java/org/apache/iotdb/itbase/runtime/ClusterTestStatement.java, integration-test/src/main/java/org/apache/iotdb/itbase/runtime/InconsistentDataException.java, integration-test/src/main/java/org/apache/iotdb/itbase/runtime/NodeConnection.java, integration-test/src/main/java/org/apache/iotdb/itbase/runtime/ParallelRequestDelegate.java, integration-test/src/main/java/org/apache/iotdb/itbase/runtime/RequestDelegate.java, integration-test/src/main/java/org/apache/iotdb/itbase/runtime/RequestThreadPool.java, integration-test/src/main/java/org/apache/iotdb/itbase/runtime/SerialRequestDelegate.java, metrics/pom.xml
JIRA: https://issues.apache.org/jira/browse/IOTDB-3463
=> [IOTDB-3463] IT framework supports read and compare from multi data nodes

tsfile/src/main/java/org/apache/iotdb/tsfile/read/common/block/column/BinaryArrayColumnEncoder.java, tsfile/src/main/java/org/apache/iotdb/tsfile/read/common/block/column/ByteArrayColumnEncoder.java, tsfile/src/main/java/org/apache/iotdb/tsfile/read/common/block/column/ColumnEncoder.java, tsfile/src/main/java/org/apache/iotdb/tsfile/read/common/block/column/ColumnEncoderFactory.java, tsfile/src/main/java/org/apache/iotdb/tsfile/read/common/block/column/ColumnEncoding.java, tsfile/src/main/java/org/apache/iotdb/tsfile/read/common/block/column/Int32ArrayColumnEncoder.java, tsfile/src/main/java/org/apache/iotdb/tsfile/read/common/block/column/Int64ArrayColumnEncoder.java, tsfile/src/main/java/org/apache/iotdb/tsfile/read/common/block/column/RunLengthColumnEncoder.java, tsfile/src/main/java/org/apache/iotdb/tsfile/read/common/block/column/RunLengthEncodedColumn.java, tsfile/src/main/java/org/apache/iotdb/tsfile/read/common/block/column/TsBlockSerde.java, tsfile/src/test/java/org/apache/iotdb/tsfile/common/block/BinaryArrayColumnEncoderTest.java, tsfile/src/test/java/org/apache/iotdb/tsfile/common/block/Int32ArrayColumnEncoderTest.java, tsfile/src/test/java/org/apache/iotdb/tsfile/common/block/Int64ArrayColumnEncoderTest.java, tsfile/src/test/java/org/apache/iotdb/tsfile/common/block/RunLengthColumnEncoderTest.java
Please see: https://issues.apache.org/jira/browse/IOTDB-3384
=> [IOTDB-3384] fix run length tsblock serde

server/src/main/java/org/apache/iotdb/db/localconfignode/LocalConfigNode.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/execution/config/executor/StandsloneConfigTaskExecutor.java
=> [IOTDB-3486] Support deleteStorageGroup for new standalone IoTDB

integration-test/src/main/java/org/apache/iotdb/it/env/ClusterEnvBase.java, integration-test/src/main/java/org/apache/iotdb/it/env/IoTDBTestRunner.java, integration-test/src/main/java/org/apache/iotdb/it/env/RemoteServerEnv.java, integration-test/src/main/java/org/apache/iotdb/itbase/env/BaseEnv.java, integration-test/src/main/java/org/apache/iotdb/itbase/runtime/ClusterTestResultSet.java, integration-test/src/test/java/org/apache/iotdb/db/it/IoTDBExampleIT.java, integration-test/src/test/java/org/apache/iotdb/db/it/IoTDBUDTFBuiltinFunctionIT.java, integration-test/src/test/java/org/apache/iotdb/db/it/aligned/IoTDBAlignedSeriesQuery2IT.java, integration-test/src/test/java/org/apache/iotdb/db/it/aligned/IoTDBAlignedSeriesQuery3IT.java, integration-test/src/test/java/org/apache/iotdb/db/it/aligned/IoTDBAlignedSeriesQueryIT.java, integration-test/src/test/java/org/apache/iotdb/db/it/aligned/IoTDBInsertAlignedValues2IT.java, integration-test/src/test/java/org/apache/iotdb/db/it/aligned/IoTDBInsertAlignedValues3IT.java, integration-test/src/test/java/org/apache/iotdb/db/it/aligned/IoTDBInsertAlignedValues4IT.java, integration-test/src/test/java/org/apache/iotdb/db/it/aligned/IoTDBInsertAlignedValuesIT.java, integration-test/src/test/java/org/apache/iotdb/db/it/aligned/IoTDBLastQueryWithDeletion2IT.java, integration-test/src/test/java/org/apache/iotdb/db/it/aligned/IoTDBLastQueryWithDeletionIT.java, integration-test/src/test/java/org/apache/iotdb/db/it/aligned/IoTDBLastQueryWithoutLastCache2IT.java, integration-test/src/test/java/org/apache/iotdb/db/it/aligned/IoTDBLastQueryWithoutLastCacheIT.java, integration-test/src/test/java/org/apache/iotdb/db/it/aligned/IoTDBLastQueryWithoutLastCacheWithDeletion2IT.java, integration-test/src/test/java/org/apache/iotdb/db/it/aligned/IoTDBLastQueryWithoutLastCacheWithDeletionIT.java, integration-test/src/test/java/org/apache/iotdb/db/it/aligned/IoTDBRawQueryWithoutValueFilterWithDeletion2IT.java, integration-test/src/test/java/org/apache/iotdb/db/it/aligned/IoTDBRawQueryWithoutValueFilterWithDeletionIT.java, integration-test/src/test/java/org/apache/iotdb/db/it/env/StandaloneEnv.java
=> [IOTDB-3489] Add test name to log folder in cluster test

server/src/main/java/org/apache/iotdb/db/mpp/plan/parser/StatementGenerator.java
=> [IOTDB-3285] Fix IndexOutOfBoundsException when creating aligned timeseries with session API

server/src/main/java/org/apache/iotdb/db/mpp/plan/execution/QueryExecution.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/FragmentInstance.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/PlanNodeUtil.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/metedata/read/SchemaFetchScanNode.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/metedata/read/SchemaQueryScanNode.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/sink/FragmentSinkNode.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/source/AlignedLastQueryScanNode.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/source/AlignedSeriesAggregationScanNode.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/source/AlignedSeriesScanNode.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/source/LastQueryScanNode.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/source/SeriesAggregationScanNode.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/source/SeriesScanNode.java
1. Add detailed Endpoint for each FragmentInstance
2. Supply missed toString() for some node
=> Optimize log for mpp process

integration-test/src/test/java/org/apache/iotdb/db/it/aligned/IoTDBInsertAlignedValuesIT.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/Analyzer.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/statement/crud/InsertStatement.java
=> [IOTDB-3470] [IOTDB-3471] Add some semantic checks for InsertStatement

server/src/main/java/org/apache/iotdb/db/localconfignode/LocalDataPartitionTable.java, server/src/main/java/org/apache/iotdb/db/metadata/schemaregion/SchemaEngine.java
=> [IOTDB-3500] Fix delete storage group failure in new standalone IoTDB

server/src/main/java/org/apache/iotdb/db/mpp/plan/execution/config/ConfigExecution.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/execution/config/FlushTask.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/execution/config/executor/StandaloneConfigTaskExecutor.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/parser/ASTVisitor.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/statement/sys/FlushStatement.java
`Flush` command in cluster should flush data on all data nodes.
=> Change the meaning of `Flush` on cluster mode

server/src/main/java/org/apache/iotdb/db/protocol/mqtt/MPPPublishHandler.java, server/src/main/java/org/apache/iotdb/db/protocol/mqtt/PublishHandler.java, server/src/main/java/org/apache/iotdb/db/service/MQTTService.java, server/src/test/java/org/apache/iotdb/db/protocol/mqtt/PublishHandlerTest.java
See [IOTDB-3506](https://issues.apache.org/jira/browse/IOTDB-3506).
=> [IOTDB-3323][IOTDB-3506] Support MQTT for MPP framework

confignode/src/assembly/resources/conf/iotdb-confignode.properties, confignode/src/main/java/org/apache/iotdb/confignode/client/ConfigNodeClientPoolFactory.java, confignode/src/main/java/org/apache/iotdb/confignode/conf/ConfigNodeConfig.java, confignode/src/main/java/org/apache/iotdb/confignode/conf/ConfigNodeDescriptor.java, confignode/src/main/java/org/apache/iotdb/confignode/conf/ConfigNodeStartupCheck.java, confignode/src/main/java/org/apache/iotdb/confignode/manager/ConfigManager.java, confignode/src/main/java/org/apache/iotdb/confignode/manager/ConsensusManager.java, confignode/src/main/java/org/apache/iotdb/confignode/manager/PartitionManager.java, confignode/src/main/java/org/apache/iotdb/confignode/manager/ProcedureManager.java, confignode/src/main/java/org/apache/iotdb/confignode/persistence/UDFInfo.java, confignode/src/main/java/org/apache/iotdb/confignode/service/ConfigNode.java, confignode/src/main/java/org/apache/iotdb/confignode/service/thrift/ConfigNodeRPCService.java, confignode/src/test/java/org/apache/iotdb/confignode/service/thrift/ConfigNodeRPCServiceProcessorTest.java, server/src/assembly/resources/conf/iotdb-engine.properties, server/src/main/java/org/apache/iotdb/db/mpp/plan/scheduler/ClusterScheduler.java, server/src/main/java/org/apache/iotdb/db/service/DataNode.java
uncomment the data_block_manager_port=8777
add final to some field
change default data region consensus to standalone
remove some unused field in ClusterScheduler
rename ConfigNodeConf to ConfigNodeConfig
rename DataNode startup process of prepareJoin() and join() to register() and active()
=> uncomment the data_block_manager_port and change default data region to StandAlone Consensus

server/src/main/java/org/apache/iotdb/db/engine/snapshot/SnapshotTaker.java
See [IOTDB-3344](https://issues.apache.org/jira/browse/IOTDB-3344).
This PR fix the problem by accquiring read lock of tsfile manager before taking snapshot.
=> [IOTDB-3344] Fix dataRegion snapshot may meet file not found due to compaction

.github/workflows/cluster-it.yml, confignode/src/assembly/resources/conf/confignode-env.bat, confignode/src/assembly/resources/conf/logback.xml, integration-test/src/main/java/org/apache/iotdb/it/env/ClusterEnvBase.java, integration-test/src/main/java/org/apache/iotdb/it/env/ClusterNodeBase.java, integration-test/src/main/java/org/apache/iotdb/it/env/ConfigNode.java, integration-test/src/main/java/org/apache/iotdb/it/env/DataNode.java, integration-test/src/main/java/org/apache/iotdb/itbase/runtime/ClusterTestStatement.java, integration-test/src/main/java/org/apache/iotdb/itbase/runtime/ParallelRequestDelegate.java, integration-test/src/test/java/org/apache/iotdb/db/it/aligned/IoTDBAggregationWithoutValueFilterWithDeletion2IT.java, integration-test/src/test/java/org/apache/iotdb/db/it/aligned/IoTDBAggregationWithoutValueFilterWithDeletionIT.java, integration-test/src/test/java/org/apache/iotdb/db/it/aligned/IoTDBGroupByQueryWithoutValueFilterWithDeletion2IT.java, integration-test/src/test/java/org/apache/iotdb/db/it/aligned/IoTDBGroupByQueryWithoutValueFilterWithDeletionIT.java, server/src/assembly/resources/conf/iotdb-env.bat, server/src/assembly/resources/conf/logback.xml
JIRA: https://issues.apache.org/jira/browse/IOTDB-2179
=> [IOTDB-2179] New IT framework supports Windows platform

integration/src/test/java/org/apache/iotdb/db/integration/sync/IoTDBSyncSenderIT.java, server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java, server/src/main/java/org/apache/iotdb/db/engine/StorageEngineV2.java, server/src/main/java/org/apache/iotdb/db/engine/storagegroup/DataRegion.java, server/src/main/java/org/apache/iotdb/db/service/DataNode.java, server/src/main/java/org/apache/iotdb/db/wal/recover/WALRecoverManager.java, server/src/test/java/org/apache/iotdb/db/mpp/plan/StandaloneCoordinatorTest.java, server/src/test/java/org/apache/iotdb/db/utils/EnvironmentUtils.java, server/src/test/java/org/apache/iotdb/db/wal/recover/WALRecoverManagerTest.java
=> [IOTDB-3513] Avoid double-writing of the write ahead log for data under RatisConsensus

server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/Analyzer.java
The implementation of delete data for cluster mode use the slotId to get dataPartition. Although this saves the duplicated device slotId calculation, the standalonePartitionFetcher doesn't support this.
Use device path to get data partition in new standalone.
Make the behavior of partition fetcher and configNode of standalone consistent with those of cluster
=> [IOTDB-3549] Fix delete data in new standalone

client-py/iotdb/Session.py, client-py/iotdb/utils/IoTDBRpcDataSet.py, client-py/tests/test_dataframe.py, client-py/tests/test_tablet.py, client-py/tests/test_todf.py
See [IOTDB-3494](https://issues.apache.org/jira/browse/IOTDB-3494) and [PR-6292](https://github.com/apache/iotdb/pull/6292)
=> [To rel/0.13] [IOTDB-3494] Fix TypeError in py-session

client-py/tests/test_dataframe.py, client-py/tests/test_one_device.py, client-py/tests/test_tablet.py, client-py/tests/test_todf.py
See [IOTDB-3494](https://issues.apache.org/jira/browse/IOTDB-3494).
=> [IOTDB-3494] Fix Python-Client test

server/src/main/java/org/apache/iotdb/db/localconfignode/LocalConfigNode.java
=> fix the issue that ALTER timeseries is not correct in NewIoTDB

docs/UserGuide/Administration-Management/Administration.md, docs/zh/UserGuide/Administration-Management/Administration.md
1、add sql doc
2、add operations restricted by non root users
=> [IOTDB-3545] Add permission and SQL relation table in doc

integration-test/pom.xml, integration-test/src/main/java/org/apache/iotdb/it/env/AbstractEnv.java, integration-test/src/main/java/org/apache/iotdb/it/env/AbstractNodeWrapper.java, integration-test/src/main/java/org/apache/iotdb/it/env/ConfigNodeWrapper.java, integration-test/src/main/java/org/apache/iotdb/it/env/DataNodeWrapper.java, integration-test/src/main/java/org/apache/iotdb/it/env/IoTDBTestRunner.java, integration-test/src/main/java/org/apache/iotdb/it/env/RemoteServerEnv.java, integration-test/src/main/java/org/apache/iotdb/it/env/StandaloneDataNodeWrapper.java, integration-test/src/main/java/org/apache/iotdb/it/env/StandaloneOnMppEnv.java, integration-test/src/main/java/org/apache/iotdb/itbase/env/BaseEnv.java, integration-test/src/main/java/org/apache/iotdb/itbase/env/BaseNodeWrapper.java, integration-test/src/main/java/org/apache/iotdb/itbase/runtime/InconsistentDataException.java, integration-test/src/main/java/org/apache/iotdb/itbase/runtime/ParallelRequestDelegate.java, integration-test/src/main/java/org/apache/iotdb/itbase/runtime/RequestDelegate.java, integration-test/src/test/java/org/apache/iotdb/db/it/env/StandaloneEnv.java
JIRA: https://issues.apache.org/jira/browse/IOTDB-3558
For any test case failed by request timeout, a thread dump file will be output to `cluster-logs` dir of every node.
=> [IOTDB-3558] Dump node stacks if IT test request timeout

server/src/main/java/org/apache/iotdb/db/conf/directories/DirectoryManager.java, server/src/main/java/org/apache/iotdb/db/engine/storagegroup/DataRegion.java
Delete tsfiles when recovering data region.
=> [IOTDB-3513] Delete tsfiles when recovering data region

server/src/main/java/org/apache/iotdb/db/metadata/schemaregion/SchemaRegionMemoryImpl.java
When IoTDB been shutdown, the file in schemaRegion dir should be deleted during recovery, otherwise it will affect the raftlog redo.
=> delete file before recovery in ratis mode

integration-test/src/test/java/org/apache/iotdb/db/it/IoTDBCreateTimeseriesIT.java, server/src/main/java/org/apache/iotdb/db/localconfignode/LocalConfigNode.java
=> [IOTDB-3601] Fix error when query data from empty series on new standalone iotdb

server/src/main/java/org/apache/iotdb/db/engine/snapshot/SnapshotLoader.java, server/src/main/java/org/apache/iotdb/db/engine/snapshot/SnapshotTaker.java
See [IOTDB-3632](https://issues.apache.org/jira/browse/IOTDB-3632).
=> [IOTDB-3632] Add log for snapshot taker and loader

server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/schema/SchemaQueryMergeOperator.java
=> [IOTDB-3598] Fix isBlocked check in SchemaQueryMergeOperator

confignode/src/main/java/org/apache/iotdb/confignode/conf/ConfigNodeStartupCheck.java
see 
https://issues.apache.org/jira/browse/IOTDB-3641
=> [IOTDB-3641] Fix BadNodeUrlException when loadConfigNodeList

confignode/src/main/java/org/apache/iotdb/confignode/service/ConfigNode.java
see https://issues.apache.org/jira/browse/IOTDB-3638
=> [IOTDB-3638]  ConfigNode deactivate NPE

docs/UserGuide/Integration-Test/Integration-Test-refactoring-tutorial.md, docs/zh/UserGuide/Integration-Test/Integration-Test-refactoring-tutorial.md
This pull request updates the document for writing IT.
=> [IOTDB-3405] Document for IT developer

server/src/main/java/org/apache/iotdb/db/metadata/mtree/MTreeAboveSG.java
The memory statistic warning was reported by MTreeAboveSG used in configNode. 
There was memory control mechanism in MemMTreeStore to record the memory usage of memory MTree. MTreeAboveSG used this. In configNode, the memory statistic cannot get the memory threshold from IoTDBConfig, which results in the threshold always being 0, so comes the warning.
The MTreeAboveSG use the MemMTreeStore to help adapt to the MTree Traverser, and there's no need to statistic the memory of MTreeAboveSG since the number of storage group is small. 
Avoid using the write interface provided by MemMTreeStore which is bounded with the memory statistic.
=> [IOTDB-3262]Remove memory control info of MTreeAboveSG

integration/src/test/java/org/apache/iotdb/db/integration/aligned/IoTDBGroupByQueryWithoutValueFilter3IT.java, integration/src/test/java/org/apache/iotdb/db/integration/aligned/IoTDBGroupByQueryWithoutValueFilterIT.java, server/src/main/java/org/apache/iotdb/db/query/dataset/groupby/LocalAlignedGroupByExecutor.java, server/src/main/java/org/apache/iotdb/db/query/dataset/groupby/LocalGroupByExecutor.java
=> [To rel/0.13] [IOTDB-3645] Fix use statistics bug in aggregation query

confignode/src/main/java/org/apache/iotdb/confignode/client/SyncConfigNodeClientPool.java, node-commons/src/main/java/org/apache/iotdb/commons/client/ClientManager.java
* Only log the last exception stack in SyncConfigNodeClientPool when retry
* Change exception of log.error in ClientManager to log.warn
=> Only log the last exception stack in SyncConfigNodeClientPool when retry

server/src/main/java/org/apache/iotdb/db/engine/storagegroup/DataRegion.java
See [IOTDB-3651](https://issues.apache.org/jira/browse/IOTDB-3651).
=> [IOTDB-3651] Stop compaction schedule when all compaction is disable

server/src/main/java/org/apache/iotdb/db/engine/compaction/CompactionTaskManager.java, server/src/main/java/org/apache/iotdb/db/engine/storagegroup/VirtualStorageGroupProcessor.java
Same as [PR-6437](https://github.com/apache/iotdb/pull/6437).
=> [To rel/0.13] [IOTDB-3651] Stop compaction schedule when all compaction is disable

server/src/test/java/org/apache/iotdb/db/mpp/execution/datatransfer/SharedTsBlockQueueTest.java
Previously, SharedTsBlockQueue is a thread-safe class, but now it's not and concurrency safety should be ensured by caller.
=> [IOTDB-3653] Fix SharedTsBlockQueueTest.concurrencyTest failed in CI

docs/UserGuide/Maintenance-Tools/Maintenance-Command.md, docs/zh/UserGuide/Maintenance-Tools/Maintenance-Command.md
=> update Maintenance-Command.md (show regions)

docs/UserGuide/Integration-Test/Integration-Test-refactoring-tutorial.md, docs/zh/UserGuide/Integration-Test/Integration-Test-refactoring-tutorial.md
=> Image in English for IT document

server/src/main/java/org/apache/iotdb/db/engine/compaction/CompactionTaskManager.java
See [IOTDB-3651](https://issues.apache.org/jira/browse/IOTDB-3651).
=> [IOTDB-3651] Not initialize thread pool in CompactionTaskManager if all compaction is disable

distribution/pom.xml, distribution/src/assembly/all.xml, distribution/src/assembly/datanode.xml, docker/src/main/Dockerfile-single, docker/src/main/Dockerfile-single-influxdb, docker/src/main/Dockerfile-single-tc
After execute `mvn clean package -pl distribution -am -DskipTests`, the following binary packages will be builded.
=> Remove grafana connector and rename server to datanode in distribution package

server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/Analyzer.java
=> [IOTDB-3597] Infer types for expressions in where clause

server/src/main/java/org/apache/iotdb/db/query/expression/unary/FunctionExpression.java
=> [To rel/0.13] [IOTDB-3523] Fix the count and COUNT not equal bug when querying with group by level

server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java, server/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java, tsfile/src/main/java/org/apache/iotdb/tsfile/common/conf/TSFileConfig.java, tsfile/src/main/java/org/apache/iotdb/tsfile/common/conf/TSFileDescriptor.java
=> 0.13.0 Edge configuration

docs/UserGuide/Cluster/Cluster-Setup.md, docs/zh/UserGuide/Cluster/Cluster-Setup.md, site/src/main/.vuepress/config.js
Add how to start/add confignode
Add how to start/add datanode
Add how to start cli
=> Add cluster setup command in UserGuide

docs/UserGuide/Cluster/Cluster-Setup.md, docs/zh/UserGuide/Cluster/Cluster-Setup.md
Add a 1C1D cluster setup case.
=> update quickstart of cluster

server/src/main/java/org/apache/iotdb/db/engine/compaction/cross/rewrite/CrossSpaceCompactionResource.java, server/src/main/java/org/apache/iotdb/db/engine/compaction/cross/rewrite/RewriteCrossSpaceCompactionSelector.java
See details in [IOTDB-3690](https://issues.apache.org/jira/browse/IOTDB-3690).
=> [IOTDB-3690]fix cross compaction logs

tsfile/src/main/java/org/apache/iotdb/tsfile/read/TsFileSequenceReader.java
When device is not in tsfile, we log a debug log.
=> [To rel/0.12] [IOTDB-3398] Change device not in TsFile logger from warn to debug

grafana-connector/src/main/java/org/apache/iotdb/web/grafana/conf/MyConfiguration.java, grafana-connector/src/main/java/org/apache/iotdb/web/grafana/interceptor/LoginInterceptor.java
=> add login interceptor

grafana-connector/src/main/java/org/apache/iotdb/web/grafana/conf/MyConfiguration.java, grafana-connector/src/main/java/org/apache/iotdb/web/grafana/interceptor/LoginInterceptor.java
=> [To rel/0.13] add login interceptor

server/src/main/java/org/apache/iotdb/db/service/TSServiceImpl.java
=> [To rel/0.12] Optimize login check.

grafana-plugin/backend-compile.sh, grafana-plugin/pom.xml
=> fixed grafana plugin workflow failed

openapi/pom.xml, server/src/main/java/org/apache/iotdb/db/conf/rest/IoTDBRestServiceConfig.java, server/src/main/java/org/apache/iotdb/db/protocol/mpprest/MPPRestService.java, server/src/main/java/org/apache/iotdb/db/protocol/mpprest/filter/ApiOriginFilter.java, server/src/main/java/org/apache/iotdb/db/protocol/mpprest/filter/AuthorizationFilter.java, server/src/main/java/org/apache/iotdb/db/protocol/mpprest/filter/BasicSecurityContext.java, server/src/main/java/org/apache/iotdb/db/protocol/mpprest/filter/User.java, server/src/main/java/org/apache/iotdb/db/protocol/mpprest/filter/UserCache.java, server/src/main/java/org/apache/iotdb/db/protocol/mpprest/handler/AuthorizationHandler.java, server/src/main/java/org/apache/iotdb/db/protocol/mpprest/handler/ExceptionHandler.java, server/src/main/java/org/apache/iotdb/db/protocol/mpprest/handler/QueryDataSetHandler.java, server/src/main/java/org/apache/iotdb/db/protocol/mpprest/handler/RequestValidationHandler.java, server/src/main/java/org/apache/iotdb/db/protocol/mpprest/handler/StatementConstructionHandler.java, server/src/main/java/org/apache/iotdb/db/protocol/mpprest/impl/GrafanaApiServiceImpl.java, server/src/main/java/org/apache/iotdb/db/protocol/mpprest/impl/PingApiServiceImpl.java, server/src/main/java/org/apache/iotdb/db/protocol/mpprest/impl/RestApiServiceImpl.java, server/src/main/java/org/apache/iotdb/db/service/DataNode.java, server/src/main/java/org/apache/iotdb/db/service/NewIoTDB.java
=> [IOTDB-3322] Support RestApi for MPP framework

confignode/src/main/java/org/apache/iotdb/confignode/client/AsyncDataNodeClientPool.java, confignode/src/main/java/org/apache/iotdb/confignode/client/SyncDataNodeClientPool.java, confignode/src/main/java/org/apache/iotdb/confignode/client/handlers/SetTTLHandler.java, confignode/src/main/java/org/apache/iotdb/confignode/consensus/request/ConfigPhysicalPlan.java, confignode/src/main/java/org/apache/iotdb/confignode/consensus/request/write/CreateRegionGroupsPlan.java, confignode/src/main/java/org/apache/iotdb/confignode/manager/ClusterSchemaManager.java, confignode/src/main/java/org/apache/iotdb/confignode/manager/ConfigManager.java, confignode/src/main/java/org/apache/iotdb/confignode/manager/PartitionManager.java, confignode/src/main/java/org/apache/iotdb/confignode/manager/load/LoadManager.java, confignode/src/main/java/org/apache/iotdb/confignode/manager/load/balancer/RegionBalancer.java, confignode/src/main/java/org/apache/iotdb/confignode/persistence/executor/ConfigPlanExecutor.java, confignode/src/main/java/org/apache/iotdb/confignode/persistence/partition/PartitionInfo.java, confignode/src/main/java/org/apache/iotdb/confignode/persistence/partition/StorageGroupPartitionTable.java, confignode/src/test/java/org/apache/iotdb/confignode/consensus/request/ConfigPhysicalPlanSerDeTest.java, confignode/src/test/java/org/apache/iotdb/confignode/persistence/PartitionInfoTest.java
1. Rename Region to RegionGroup in ConfigNode
2. Use AsyncDataNodeClientPool to send SetTTLReq
=> [IOTDB-3529] Rename Region to RegionGroup and optimize the SetTTL process

server/src/assembly/resources/sbin/stop-datanode.sh
Stop datanode by getting the rpc_port
=> [IOTDB-3660] stop-datanode.sh/bat should only stop the process of IoTDB

confignode/src/main/java/org/apache/iotdb/confignode/manager/load/LoadManager.java
The current load balancing is bound to the heartbeat. In fact, the load balancing should be a separate scheduled task
=> [IOTDB-3703] Decouple load balancing from heartbeat

server/src/main/java/org/apache/iotdb/db/query/aggregation/impl/SumAggrResult.java, server/src/test/java/org/apache/iotdb/db/integration/IOTDBGroupByIT.java, server/src/test/java/org/apache/iotdb/db/integration/aggregation/IoTDBAggregationSmallDataIT.java
=> [To rel/0.12] [ISSUE-5809] Fix bug: sum aggregation result return 0 when no data

server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/LogicalPlanBuilder.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/LogicalPlanner.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/process/FillNode.java, server/src/test/java/org/apache/iotdb/db/mpp/plan/plan/node/process/FillNodeSerdeTest.java
=> Add scanOrder in FillNode

confignode/src/main/java/org/apache/iotdb/confignode/manager/ClusterSchemaManager.java, confignode/src/main/java/org/apache/iotdb/confignode/manager/ConfigManager.java, confignode/src/main/java/org/apache/iotdb/confignode/manager/ConsensusManager.java, confignode/src/main/java/org/apache/iotdb/confignode/manager/NodeManager.java, confignode/src/main/java/org/apache/iotdb/confignode/manager/PartitionManager.java, confignode/src/main/java/org/apache/iotdb/confignode/manager/PermissionManager.java, confignode/src/main/java/org/apache/iotdb/confignode/manager/UDFManager.java, confignode/src/main/java/org/apache/iotdb/confignode/manager/load/LoadManager.java, confignode/src/main/java/org/apache/iotdb/confignode/manager/load/balancer/RegionBalancer.java, confignode/src/main/java/org/apache/iotdb/confignode/persistence/NodeInfo.java, confignode/src/main/java/org/apache/iotdb/confignode/procedure/env/ConfigNodeProcedureEnv.java, confignode/src/test/java/org/apache/iotdb/confignode/persistence/NodeInfoTest.java
see details : https://issues.apache.org/jira/browse/IOTDB-3557
=> [IOTDB-3557] Maintain online data nodes by load manager

confignode/src/main/java/org/apache/iotdb/confignode/manager/ConfigManager.java, confignode/src/main/java/org/apache/iotdb/confignode/manager/NodeManager.java, docs/UserGuide/Maintenance-Tools/Maintenance-Command.md, docs/zh/UserGuide/Maintenance-Tools/Maintenance-Command.md
1、make the result sequential（show datanodes，show cluster）
2、update doc
**Monitoring tool for cluster Node distributionl**
--**Show all DataNode information**
--**Show all Node information**
=> [IOTDB-3737] Update cluster tools: make the result sequential

server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/ClusterPartitionFetcher.java
see [IOTDB-3744](https://issues.apache.org/jira/browse/IOTDB-3744)
=> [IOTDB-3744] fix potential NPE

server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/schema/NodePathsConvertOperator.java, server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/schema/SchemaQueryMergeOperator.java
See IOTDB-3550
The duplicate result has been fixed in #6530.
Besides, there is still NPE problem, which is fixed in this pr.
=> [IOTDB-3550]Fix show child nodes

server/src/main/java/org/apache/iotdb/db/tools/validate/TsFileValidationTool.java
Print paths of all bad files, including the previous file that overlap with later files.
=> [IOTDB-3387]Print all bad files in Validation Tool

server/src/test/java/org/apache/iotdb/db/engine/merge/MergeNewSeriesTest.java
Add one test of the scene: 
(1) timeseries is only in the unseq files 
(2) timeseries is in the unseq files and only in the last seq file.
=> [IOTDB-3762][To rel/0.12]add test of cross compaction

antlr/src/main/antlr4/org/apache/iotdb/db/qp/sql/IoTDBSqlParser.g4, confignode/src/main/java/org/apache/iotdb/confignode/consensus/request/read/GetRegionInfoListPlan.java, confignode/src/main/java/org/apache/iotdb/confignode/persistence/ClusterSchemaInfo.java, confignode/src/main/java/org/apache/iotdb/confignode/persistence/executor/ConfigPlanExecutor.java, confignode/src/main/java/org/apache/iotdb/confignode/persistence/partition/PartitionInfo.java, confignode/src/main/java/org/apache/iotdb/confignode/persistence/partition/StorageGroupPartitionTable.java, confignode/src/main/java/org/apache/iotdb/confignode/service/thrift/ConfigNodeRPCServiceProcessor.java, confignode/src/test/java/org/apache/iotdb/confignode/consensus/request/ConfigPhysicalPlanSerDeTest.java, confignode/src/test/java/org/apache/iotdb/confignode/persistence/PartitionInfoTest.java, docs/UserGuide/Maintenance-Tools/Maintenance-Command.md, docs/zh/UserGuide/Maintenance-Tools/Maintenance-Command.md, server/src/main/java/org/apache/iotdb/db/mpp/plan/execution/config/executor/ClusterConfigTaskExecutor.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/parser/ASTVisitor.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/statement/metadata/ShowRegionStatement.java, thrift-confignode/src/main/thrift/confignode.thrift, tsfile/src/main/java/org/apache/iotdb/tsfile/utils/ReadWriteIOUtils.java
Support grammar SHOW (SCHEMA | DATA)? REGIONS (OF STORAGE GROUP prefixPath? (COMMA prefixPath)*)?
=> [IOTDB-3792] Show region tool support query condition of storage group

server/src/main/java/org/apache/iotdb/db/qp/physical/crud/InsertPlan.java, server/src/main/java/org/apache/iotdb/db/writelog/recover/LogReplayer.java, server/src/test/java/org/apache/iotdb/db/writelog/recover/LogReplayerTest.java, server/src/test/java/org/apache/iotdb/db/writelog/recover/SeqTsFileRecoverTest.java
https://apache-iotdb.feishu.cn/docx/doxcnRUNBYxmamBCr0Sy3SAiV0M
=> [To rel/0.13][IOTDB-3618] StorageEngine failed to recover: / by zero

integration/src/test/java/org/apache/iotdb/db/integration/IoTDBRestartIT.java, server/src/main/java/org/apache/iotdb/db/engine/flush/MemTableFlushTask.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/write/InsertNode.java, server/src/main/java/org/apache/iotdb/db/qp/physical/crud/InsertPlan.java, server/src/main/java/org/apache/iotdb/db/wal/recover/file/TsFilePlanRedoer.java, server/src/main/java/org/apache/iotdb/db/wal/recover/file/UnsealedTsFileRecoverPerformer.java, server/src/test/java/org/apache/iotdb/db/wal/recover/file/UnsealedTsFileRecoverPerformerTest.java
https://apache-iotdb.feishu.cn/docx/doxcnRUNBYxmamBCr0Sy3SAiV0M
The same as #6672 and #6664
=> [IOTDB-3618] StorageEngine failed to recover: / by zero

server/src/main/java/org/apache/iotdb/db/protocol/mpprest/handler/QueryDataSetHandler.java
[IOTDB-3834] fixed [0.14]grafana-plugin display data error
=> [IOTDB-3834] fixed [0.14]grafana-plugin display data error

server/src/main/java/org/apache/iotdb/db/protocol/mpprest/handler/StatementConstructionHandler.java
[IOTDB-3836] REST API for data type in a case-insensitive
=> [IOTDB-3836] REST API for data type in a case-insensitive

confignode/src/main/java/org/apache/iotdb/confignode/consensus/request/write/RemoveDataNodePlan.java, confignode/src/test/java/org/apache/iotdb/confignode/consensus/request/write/RemoveDataNodePlanTest.java
when remove datanode, the follower confignodes has exception in error log file, remove does not succeed
RemoveDataNodePlan，RemoveDataNodePlanTest
=> [IOTDB-3840]  deserialize RemoveDataNodePlan exception

client-cpp/src/main/Session.cpp
C++ client method of tablet sorting optimization
=> [IOTDB-3851] C++ client method of tablet sorting optimization

server/src/main/java/org/apache/iotdb/db/metadata/cache/DataNodeSchemaCache.java
See: https://issues.apache.org/jira/browse/IOTDB-3854
=> [IOTDB-3854] add interface to provide getOrCreate SchemaEntry when update lastCache.

client-cpp/src/main/Session.cpp
C++ client method of tablet sorting optimization
=> [To rel/0.13] [IOTDB-3851] C++ client method of tablet sorting optimization

confignode/src/main/java/org/apache/iotdb/confignode/client/sync/confignode/SyncConfigNodeClientPool.java, confignode/src/main/java/org/apache/iotdb/confignode/manager/ConfigManager.java, confignode/src/main/java/org/apache/iotdb/confignode/manager/ConsensusManager.java, confignode/src/main/java/org/apache/iotdb/confignode/manager/NodeManager.java, confignode/src/main/java/org/apache/iotdb/confignode/manager/ProcedureManager.java, confignode/src/main/java/org/apache/iotdb/confignode/procedure/Procedure.java, confignode/src/main/java/org/apache/iotdb/confignode/procedure/StateMachineProcedure.java, confignode/src/main/java/org/apache/iotdb/confignode/procedure/env/ConfigNodeProcedureEnv.java, confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/RemoveConfigNodeProcedure.java, confignode/src/main/java/org/apache/iotdb/confignode/procedure/state/RemoveConfigNodeState.java, confignode/src/main/java/org/apache/iotdb/confignode/procedure/store/ProcedureFactory.java, confignode/src/main/java/org/apache/iotdb/confignode/service/thrift/ConfigNodeRPCServiceProcessor.java, server/src/main/java/org/apache/iotdb/db/client/ConfigNodeClient.java, thrift-confignode/src/main/thrift/confignode.thrift
refactoring remove confignode to Procedure and support rollback
IoTDB> show cluster
show cluster
+------+----------+-------+---------+-----+
|NodeID|  NodeType| Status|     Host| Port|
+------+----------+-------+---------+-----+
|     0|ConfigNode|Running|  0.0.0.0|22277|
|     1|ConfigNode|Running|  0.0.0.0|22279|
|     2|ConfigNode|Running|  0.0.0.0|22281|
|     3|  DataNode|Running|127.0.0.1| 9003|
|     4|  DataNode|Running|127.0.0.1| 9005|
|     5|  DataNode|Running|127.0.0.1| 9007|
+------+----------+-------+---------+-----+
Total line number = 6
It costs 0.763s
remove-confignode.sh -r 127.0.0.1:22277
IoTDB> show cluster
show cluster
+------+----------+-------+---------+-----+
|NodeID|  NodeType| Status|     Host| Port|
+------+----------+-------+---------+-----+
| …
=> [IOTDB-3869] refactoring remove confignode to Procedure and support rollback

docs/UserGuide/API/Programming-Cpp-Native-API.md, docs/zh/UserGuide/API/Programming-Cpp-Native-API.md
C + + interface descriptions about insertRecord/insertRecords/insertRecordsOfOneDevice errors.
The interface about Data Manipulation Interface and the interface about Insert with type inference description information is upside down.
=> [IOTDB-3879] Modify document about the Programming-Cpp-Native-API

integration-test/src/test/java/org/apache/iotdb/db/it/IoTDBSimpleQueryIT.java, integration-test/src/test/java/org/apache/iotdb/db/it/query/IoTDBResultSetIT.java, server/src/main/java/org/apache/iotdb/db/mpp/common/header/DatasetHeader.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/execution/memory/StatementMemorySourceVisitor.java, server/src/main/java/org/apache/iotdb/db/utils/QueryDataSetUtils.java
=> [IOTDB-3475] Fix ResultSet format for empty query

integration/src/test/java/org/apache/iotdb/db/integration/IoTDBFillIT.java, server/src/main/java/org/apache/iotdb/db/query/executor/AggregationExecutor.java, server/src/main/java/org/apache/iotdb/db/query/executor/FillQueryExecutor.java, server/src/main/java/org/apache/iotdb/db/query/executor/fill/LastPointReader.java, server/src/main/java/org/apache/iotdb/db/query/executor/fill/LinearFill.java, server/src/main/java/org/apache/iotdb/db/query/executor/fill/PreviousFill.java
see IOTDB-3873.
After this PR, aligned timeseries support single point fill query.
=> [To rel/0.13] [IOTDB-3873] Aligned timeseries support single point fill query

confignode/src/main/java/org/apache/iotdb/confignode/persistence/AuthorInfo.java, docs/UserGuide/Administration-Management/Administration.md, docs/zh/UserGuide/Administration-Management/Administration.md, node-commons/src/main/java/org/apache/iotdb/commons/utils/AuthUtils.java, server/src/main/java/org/apache/iotdb/db/localconfignode/LocalConfigNode.java, server/src/main/java/org/apache/iotdb/db/qp/executor/PlanExecutor.java
see [IOTDB-3889](https://issues.apache.org/jira/browse/IOTDB-3889)
After fixed:
<hr>
This PR has:
<hr>
=> [IOTDB-3889]List Privileges Role on Path cannot display a wider range path pattern

client-cpp/src/main/Session.cpp
C++ client method of insertRecordsOfOneDevice sorting optimization
=> [To rel/0.13] [IOTDB-3901] C++ client method of insertRecordsOfOneDevice sorting optimization

client-cpp/src/main/Session.cpp
C++ client method of insertRecordsOfOneDevice sorting optimization
=> [IOTDB-3901] C++ client method of insertRecordsOfOneDevice sorting optimization

server/src/main/java/org/apache/iotdb/db/service/RegionMigrateService.java
=> [IOTDB-3899] Remove 1 datanode，add peer failed，but continue to shrink（remove peer , remove region,delete region）

server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/distribution/SourceRewriter.java
Before this change, the value filter cannot be used when executing GroupByLevel query. It is because the distribution planning didn't cover this scenario where the aggregation operation should be calculated from raw data.
In this PR, I give a fix for it to use the naive query planning method when combining GroupByLevel and RawDataQuery.
See the test below:
=> [IoTDB-3842] Fix the issue that GroupByLevel cannot use value filter

server/src/main/java/org/apache/iotdb/db/mpp/plan/scheduler/FixedRateFragInsStateTracker.java
During our test, we found that sometimes the FixedRateStateTracker cannot be terminated after execution of Query. We infer that it is because the `abort()` is invoked before the `start()` is invoked.
We give this fix and try to see whether this issue will show again or not
Basic Test for this PR:
=> Fix the potential issue for StateTracker that it cannot be terminated

confignode/src/main/java/org/apache/iotdb/confignode/manager/ConfigManager.java
=> [IOTDB-3954] Show datanodes shows nothing

README.md
- can provide users with... -> provides users with...
- removed some unnecessary commas
- minor pluralization corrections
- Fixed two sentences spliced by a comma
=> Minor Grammar Changes to README.md

server/src/main/java/org/apache/iotdb/db/wal/buffer/WALBuffer.java
I add metadata after each wal file, SyncBufferTask in the WALBuffer may call two fsync in one task to fsync buffer and metadata.So, to avoid performance decline caused by fsync twice, I only fsync after metadata when buffer fsync and metadata fsync both exist.
=> [IOTDB-3938] Avoid performance decline caused by fsync twice

integration/src/test/java/org/apache/iotdb/db/integration/IoTDBTtlIT.java, server/src/main/java/org/apache/iotdb/db/engine/StorageEngine.java, server/src/main/java/org/apache/iotdb/db/metadata/MManager.java, server/src/main/java/org/apache/iotdb/db/metadata/lastCache/LastCacheManager.java, server/src/main/java/org/apache/iotdb/db/metadata/mtree/MTree.java, server/src/main/java/org/apache/iotdb/db/query/executor/LastQueryExecutor.java, server/src/test/java/org/apache/iotdb/db/metadata/MManagerAdvancedTest.java
1. Add lastCache check in TTLTask in StorageEngine
2. Add lastValue filter to lastPointReader
=> [To rel/0.13][IOTDB-3831]Fix ttl on last cache

confignode/src/main/java/org/apache/iotdb/confignode/persistence/AuthorInfo.java
bug fix
<hr>
This PR has:
<hr>
=> [IOTDB-3967]fix-bug for user permission info

confignode/src/main/java/org/apache/iotdb/confignode/client/async/datanode/AsyncDataNodeClientPool.java
See more details: https://issues.apache.org/jira/browse/IOTDB-3945
=> [IOTDB-3945] Fix Set TTL Operation Failed

server/src/main/java/org/apache/iotdb/db/mpp/plan/expression/multi/FunctionExpression.java
Bug fix: FunctionExpression updateStatisticsForMemoryAssigner. 
Take `memoryAssigner.increaseExpressionReference(this);` out of for loop.
<hr>
This PR has:
<hr>
=> Fix bug in FunctionExpression updateStatisticsForMemoryAssigner.

integration-test/src/test/java/org/apache/iotdb/db/it/IoTDBInsertWithoutTimeIT.java
Fix https://github.com/apache/iotdb/runs/7514848453?check_suite_focus=true
=> Fix IoTDBInsertWithoutTimeIT failure on CI

server/src/main/java/org/apache/iotdb/db/mpp/plan/parser/ASTVisitor.java, server/src/main/java/org/apache/iotdb/db/qp/sql/IoTDBSqlVisitor.java
=>   [IOTDB-3977] Solve the problem of permission type lower case execution failure when granting permission

antlr/src/main/antlr4/org/apache/iotdb/db/qp/sql/IdentifierParser.g4, antlr/src/main/antlr4/org/apache/iotdb/db/qp/sql/IoTDBSqlParser.g4, antlr/src/main/antlr4/org/apache/iotdb/db/qp/sql/SqlLexer.g4, confignode/src/main/java/org/apache/iotdb/confignode/manager/ConfigManager.java, confignode/src/main/java/org/apache/iotdb/confignode/manager/IManager.java, confignode/src/main/java/org/apache/iotdb/confignode/manager/NodeManager.java, confignode/src/main/java/org/apache/iotdb/confignode/service/thrift/ConfigNodeRPCServiceProcessor.java, docs/UserGuide/Maintenance-Tools/Maintenance-Command.md, docs/zh/UserGuide/Maintenance-Tools/Maintenance-Command.md, server/src/main/java/org/apache/iotdb/db/client/ConfigNodeClient.java, server/src/main/java/org/apache/iotdb/db/mpp/common/header/HeaderConstant.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/execution/config/ConfigTaskVisitor.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/execution/config/ShowConfigNodesTask.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/execution/config/executor/ClusterConfigTaskExecutor.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/execution/config/executor/IConfigTaskExecutor.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/execution/config/executor/StandaloneConfigTaskExecutor.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/parser/ASTVisitor.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/statement/StatementVisitor.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/statement/metadata/ShowConfigNodesStatement.java, thrift-confignode/src/main/thrift/confignode.thrift
=> [IOTDB-3865] Cluster tool show confignodes

node-commons/src/main/java/org/apache/iotdb/commons/concurrent/WrappedCallable.java, node-commons/src/main/java/org/apache/iotdb/commons/concurrent/WrappedRunnable.java
https://issues.apache.org/jira/browse/IOTDB-3979
=> [IOTDB-3979] Let WrappedCallable/WrappedRunnable catch Throwable
