- LICENSE-binary
- pom.xml
There is a cve report about logback version < 1.2.9. 
See https://cve.report/CVE-2021-42550
> [IOTDB-2209] Fix logback CVE-2021-42550 issue

- code-coverage/pom.xml
- pom.xml
Failed to fix the CI last time (see #4690) because of the missing declaration of thrift-influxdb/target/thrift
Let's have another try.
> [IOTDB-2237] coverage check encludes influxdb target 

- cluster/src/main/java/org/apache/iotdb/cluster/query/ClusterUDTFQueryExecutor.java
- cluster/src/main/java/org/apache/iotdb/cluster/query/LocalQueryExecutor.java
- cluster/src/test/java/org/apache/iotdb/cluster/server/member/DataGroupMemberTest.java
- server/src/main/java/org/apache/iotdb/db/engine/StorageEngine.java
- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/StorageGroupProcessor.java
- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/TsFileResource.java
- server/src/main/java/org/apache/iotdb/db/metadata/MManager.java
- server/src/main/java/org/apache/iotdb/db/query/control/QueryResourceManager.java
- server/src/main/java/org/apache/iotdb/db/query/dataset/groupby/GroupByFillDataSet.java
- server/src/main/java/org/apache/iotdb/db/query/dataset/groupby/GroupByWithValueFilterDataSet.java
- server/src/main/java/org/apache/iotdb/db/query/dataset/groupby/GroupByWithoutValueFilterDataSet.java
- server/src/main/java/org/apache/iotdb/db/query/dataset/groupby/LocalGroupByExecutor.java
- server/src/main/java/org/apache/iotdb/db/query/executor/AggregationExecutor.java
- server/src/main/java/org/apache/iotdb/db/query/executor/FillQueryExecutor.java
- server/src/main/java/org/apache/iotdb/db/query/executor/LastQueryExecutor.java
- server/src/main/java/org/apache/iotdb/db/query/executor/RawDataQueryExecutor.java
- server/src/main/java/org/apache/iotdb/db/query/executor/UDTFQueryExecutor.java
- server/src/main/java/org/apache/iotdb/db/query/reader/series/SeriesReader.java
- server/src/main/java/org/apache/iotdb/db/query/timegenerator/ServerTimeGenerator.java
- server/src/test/java/org/apache/iotdb/db/engine/merge/ConcurrentMergeTest.java
- server/src/test/java/org/apache/iotdb/db/engine/modification/DeletionFileNodeTest.java
- server/src/test/java/org/apache/iotdb/db/engine/storagegroup/StorageGroupProcessorTest.java
- server/src/test/java/org/apache/iotdb/db/engine/storagegroup/TTLTest.java
- server/src/test/java/org/apache/iotdb/db/integration/IoTDBQueryWithComplexValueFilterIT.java
- tsfile/src/main/java/org/apache/iotdb/tsfile/read/query/timegenerator/TimeGenerator.java
- tsfile/src/main/java/org/apache/iotdb/tsfile/read/query/timegenerator/TsFileTimeGenerator.java
- tsfile/src/test/java/org/apache/iotdb/tsfile/read/reader/FakedTimeGenerator.java
In this PR,
1. When all the selected series are under the same device, we use the time range of the device to filter QueryDataSource.
2. In query with value filter, we construct time filter from expression to filter QueryDataSource.
> [To rel/0.12] [IOTDB-2221] Accelerate query by reducing the number of files in QueryDataSource

- client-cpp/pom.xml
- compile-tools/pom.xml
- distribution/pom.xml
- example/client-cpp-example/pom.xml
- example/udf/pom.xml
- grafana/pom.xml
- jdbc/pom.xml
- pom.xml
- server/src/assembly/resources/conf/iotdb-engine.properties
- server/src/main/java/org/apache/iotdb/db/concurrent/ThreadName.java
- server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
- server/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java
- server/src/main/java/org/apache/iotdb/db/query/dataset/NonAlignEngineDataSet.java
- server/src/main/java/org/apache/iotdb/db/query/dataset/RawQueryDataSetWithoutValueFilter.java
- server/src/main/java/org/apache/iotdb/db/query/pool/QueryTaskManager.java
- server/src/main/java/org/apache/iotdb/db/query/pool/RawQueryReadTaskPoolManager.java
- server/src/main/java/org/apache/iotdb/db/service/TSServiceImpl.java
In this pr:
1. Complete QueryTaskThreadPool to control the concurrent query execution thread. Even if hundreds of clients execute query together, the thread number that execute query actully is limited by the pool size.
2. Introduce the `concurrentQueryThread` parameter to adjust the thread number that execute query statement, and rename `concurrent_sub_rawQuery_thread` to represent the read data task for raw data query.
On my machine（6 cores and 12 threads CPU), the threads of query are like:
Query threads are limited to 12, and read data threads of raw query are limited to 8.
> [To rel/0.12] [IOTDB-2195] Control the concurrent query execution thread

- integration/src/test/java/org/apache/iotdb/session/IoTDBSessionSimpleIT.java
- server/src/main/java/org/apache/iotdb/db/metadata/MManager.java
- server/src/main/java/org/apache/iotdb/db/metadata/mtree/MTree.java
- server/src/test/java/org/apache/iotdb/db/metadata/MManagerBasicTest.java
Forbid use createTimeseries to create aligned timeseries or create new timeseries under aligned device.
Forbid use createAlignedTimeseries to create nonAligned timeseries or create new timeseries under nonAligned device.
Forbid use aligned InsertPlan to insert nonAligned timeseries data.
Forbid use nonAligned InsertPlan to insert aligned timeseries data.
> Fix aligned bug of metadata module

- server/src/main/java/org/apache/iotdb/db/metadata/MManager.java
- server/src/test/java/org/apache/iotdb/db/metadata/MManagerBasicTest.java
Currently, the tagIndex in metadata module uses mlog to recover.
However, if user alters one timeseries' tag, the tag will only be updated to the tagLogFile rather than mlog.
Thus, after tag update operation, the recover won't use the up-to-date tag information in tagLogFile but use the outdated tag information in mlog.
use tagLogFile to recover tagIndex rather than mlog
> [To rel/0.12][IOTDB-2282] fix tag recover bug after tag update

- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/TsFileProcessor.java
lock flushQueryLock.writeLock() when calling flushOneMemTable
> [IOTDB-2291] Conccurent modification exception of memtables's mods

- cli/src/main/java/org/apache/iotdb/cli/utils/JlineUtils.java
Fix IOTDB-2266 , according to https://github.com/jline/jline3/issues/291 .
> [IOTDB-2266] Remove warning info when CLI runs on `-e` mode

- docs/UserGuide/Appendix/SQL-Reference.md
- docs/UserGuide/IoTDB-SQL-Language/DML-Data-Manipulation-Language.md
- docs/zh/UserGuide/Appendix/SQL-Reference.md
- docs/zh/UserGuide/IoTDB-SQL-Language/DML-Data-Manipulation-Language.md
- integration/src/test/java/org/apache/iotdb/db/integration/auth/IoTDBAuthorizationIT.java
- server/src/main/java/org/apache/iotdb/db/service/thrift/impl/TSServiceImpl.java
When authority module checks a query plan with empty path sets, which is caused by path pattern matching non timeseries, the system will return "user no permission", which should not happen.
Add check on path nums before authority check. If empty path sets, authority check is unnecessary.
Fix some mistakes in UserGuide doc
> [IOTDB-2256][IOTDB-2318] Fix permission check bug while query with non timeseries & Fix doc

- client-py/iotdb/Session.py
It‘s inappropriate to use debug level when error occurs in verify_success method, I change it to error level.
> [IOTDB-2334] Unreasonable debug log level of python client Session

- client-py/iotdb/utils/IoTDBConstants.py
if you define __eq__, the default __hash__ (namely, hashing the address of the object in memory) goes away. This is important because hashing needs to be consistent with equality: equal objects need to hash the same.
The solution is simple: just define __hash__ along with defining __eq__.
See IOTDB-2333 for more detail.
See also: https://docs.python.org/3.1/reference/datamodel.html#object.__hash__
> [IOTDB-2333] Python client: the todf method throws exception

- client-py/SessionAlignedTimeseriesExample.py
- client-py/SessionAlignedTimeseriesTest.py
- client-py/iotdb/Session.py
This PR implements the following python APIs for aligned timeseries:
```
create_aligned_timeseries
insert_aligned_record
insert_aligned_records
insert_aligned_tablet
insert_aligned_tablets
insert_aligned_records_of_one_device
insert_aligned_str_record
```
<hr>
This PR has:
<hr>
> [IOTDB-1801] Python APIs for aligned timeseries

- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/VirtualStorageGroupProcessor.java
- server/src/test/java/org/apache/iotdb/db/engine/storagegroup/TTLTest.java
Checking TTL in setTTL method may cost a lot of time, so I remove it and let scheduled thread to check it.
> [IOTDB-2317] Avoid checking TTL when setting TTL

- server/src/main/java/org/apache/iotdb/db/metadata/MManager.java
- server/src/test/java/org/apache/iotdb/db/metadata/MManagerBasicTest.java
When trying to auto create aligned timeseries during insertion, MManager will throw PathAlreadyExistException if one of the timeseries in aligned InsertPlan already exists, which should be ignored and should not impact the auto creation of the rest timeseries.
Check each timeseries in aligned InsertPlan and try auto create one by one.
> [IOTDB-2347] Fix aligned timeseries auto create bug

- integration/src/test/java/org/apache/iotdb/db/integration/aligned/IOTDBInsertAlignedValuesIT.java
- tsfile/src/main/java/org/apache/iotdb/tsfile/write/chunk/ValueChunkWriter.java
- tsfile/src/main/java/org/apache/iotdb/tsfile/write/page/ValuePageWriter.java
At present, when the server flush the aligned timeseries, it serializes the pageHeader, size, and bitmap of the page if there is an empty page. To save disk space, we serialize only an unCompressedSize of 0 when meeting an empty page.
> [IOTDB-2288] Modify serializing an empty page

- docs/zh/UserGuide/Ecosystem Integration/Grafana Plugin.md
- grafana-plugin/pom.xml
- pom.xml
When execute `mvn clean package -pl distribution -am -DskipTests`, compiling grafana plugin may take too much time.
I think we should only build grafana plugin by adding `-P compile-grafana-plugin` in mvn command, like we deal with cpp-client.
<hr>
This PR has:
<hr>
> [IOTDB-2275] Don't compile grafana plugin when execute mvn clean package -pl distribution -am -DskipTests

- integration/src/test/java/org/apache/iotdb/db/integration/IoTDBQueryMemoryControlIT.java
- integration/src/test/java/org/apache/iotdb/db/integration/aggregation/IoTDBAggregationIT.java
- integration/src/test/java/org/apache/iotdb/db/integration/aggregation/IoTDBAggregationLargeDataIT.java
- integration/src/test/java/org/apache/iotdb/db/integration/aggregation/IoTDBAggregationSmallDataIT.java
- integration/src/test/java/org/apache/iotdb/db/integration/aggregation/IoTDBUserDefinedAggregationFunctionIT.java
- server/src/main/java/org/apache/iotdb/db/qp/logical/crud/AggregationQueryOperator.java
- tsfile/src/main/java/org/apache/iotdb/tsfile/file/metadata/enums/TSDataType.java
Aggregate [AVG, SUM, EXTREME, MIN_VALUE, MAX_VALUE] only support numeric data types [INT32, INT64, FLOAT, DOUBLE].
> [IOTDB-2349] An exception should be thrown when aggregate function and data type do not match

- antlr/src/main/antlr4/org/apache/iotdb/db/qp/sql/IoTDBSqlParser.g4
- docs/UserGuide/Appendix/SQL-Reference.md
- docs/UserGuide/IoTDB-SQL-Language/DDL-Data-Definition-Language.md
- docs/zh/UserGuide/Appendix/SQL-Reference.md
- docs/zh/UserGuide/IoTDB-SQL-Language/DDL-Data-Definition-Language.md
- integration/src/test/java/org/apache/iotdb/db/integration/IoTDBSchemaTemplateIT.java
- server/src/main/java/org/apache/iotdb/db/qp/logical/sys/CreateTemplateOperator.java
- server/src/main/java/org/apache/iotdb/db/qp/sql/IoTDBSqlVisitor.java
After PR #4326 & #4391, the feature of the schema template has changed. So, we should refactor SQL of schema templates to adapt it.
> [IOTDB-2298] Refactor SQL of schema template

- tsfile/src/main/java/org/apache/iotdb/tsfile/read/reader/page/AlignedPageReader.java
- tsfile/src/main/java/org/apache/iotdb/tsfile/read/reader/page/TimePageReader.java
- tsfile/src/main/java/org/apache/iotdb/tsfile/read/reader/page/ValuePageReader.java
AlignedPageReader reads data twice in memory which leads to a bad perormance.
Performance test:
Environment:
MacOS, 6 cores 12 threads, with default configuration but close compaction.
Data:
1 storage group, 1 device, 10 time series, 100 million points each series.
Result:
SQL1 : select s1 from root.sg.d1
SQL2：select * from root.sg.d1 where time < 20000000
循环 20 次平均结果：
|                                                       | single_sensor_raw_query | 10_sensors_raw_query |
| ---------------------------------- | ----------------------- | ---------------------- |
| 对齐时间序列（未优化分支）               | 28698ms                 | 26349ms                |
| 对齐时间序列（raw_query 优化分支） | 24557ms                 | 23229ms                |
| 非对齐时间序列                                       | 20611ms …
> [IOTDB-2365] Improve Vector performance: raw data query without value filter

- tsfile/src/main/java/org/apache/iotdb/tsfile/utils/BytesUtils.java
注意到在现有的代码中，BytesUtils中非对齐的int/long的读写函数一次循环只能处理一个比特，效率较低，可以对其进行优化，使得一次循环可以处理一个字节。
该优化改动了下面的函数：
+ void longToBytes(long srcNum, byte[] result, int pos, int width)
+ void intToBytes(int srcNum, byte[] result, int pos, int width)
+ long bytesToLong(byte[] result, int pos, int width)
+ int bytesToInt(byte[] result, int pos, int width)
通过对用例的查找，发现该优化将会对使用TS_2DIFF编码的数据读写产生影响。
单元性能测试表明，该优化可以提高函数接近5倍的性能。总体性能测试表明，对于采用TS_2DIFF编码且不压缩的INT32/INT64数据，该优化可以减少约40%的读取时间开销。
--------------------------------------------------------------------------------------------------------------------------
In the current codes, the read and write functions of unaligned int/long in BytesUtils can only process one bit per loop, which is inefficient. It can be optimized to one byte per loop.
The following functions are …
> [IOTDB-2205] Optimize unaligned int/long read/write functions in BytesUtils

- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/VirtualStorageGroupProcessor.java
See JIRA: https://issues.apache.org/jira/browse/IOTDB-2381
> [IOTDB-2381] Fix deadlock caused by incorrect buffer pool size counter

- server/src/main/java/org/apache/iotdb/db/sync/sender/transfer/SyncClient.java
Problem:
When I try to use "ctrl+c"to exit a sync task,I met an error like below:[Connection refused is right,because the receiver does not started correctly ]
2022-01-10 11:43:00,105 [Thread-1] ERROR o.a.i.d.s.s.t.SyncClient:184 - Unable to remove lock file: /home/cluster/apache-iotdb-0.13.0-SNAPSHOT-all-bin/data/system/sync/172.20.70.25_5555/sync_lock
java.nio.channels.ClosedChannelException: null
at sun.nio.ch.FileLockImpl.release(FileLockImpl.java:58)
at org.apache.iotdb.db.sync.sender.transfer.SyncClient.lambda$lockInstance$0(SyncClient.java:181)
at java.lang.Thread.run(Thread.java:748)
Solution:
remove the error log, this error will not affect the process of sync
> [IOTDB-2323] Fix remove lock file in syncClient error

- client-cpp/src/main/Session.cpp
- client-cpp/src/main/Session.h
- example/session/src/main/java/org/apache/iotdb/SessionExample.java
- jdbc/src/main/java/org/apache/iotdb/jdbc/Config.java
- jdbc/src/main/java/org/apache/iotdb/jdbc/Constant.java
- jdbc/src/main/java/org/apache/iotdb/jdbc/IoTDBConnection.java
- jdbc/src/main/java/org/apache/iotdb/jdbc/IoTDBConnectionParams.java
- jdbc/src/main/java/org/apache/iotdb/jdbc/Utils.java
- server/src/main/java/org/apache/iotdb/db/conf/IoTDBConstant.java
- server/src/main/java/org/apache/iotdb/db/query/control/SessionManager.java
- server/src/main/java/org/apache/iotdb/db/service/basic/ServiceProvider.java
- server/src/main/java/org/apache/iotdb/db/service/thrift/impl/TSServiceImpl.java
- session/src/main/java/org/apache/iotdb/session/Config.java
- session/src/main/java/org/apache/iotdb/session/Session.java
- session/src/main/java/org/apache/iotdb/session/SessionConnection.java
- session/src/main/java/org/apache/iotdb/session/util/Version.java
- session/src/test/java/org/apache/iotdb/session/SessionCacheLeaderUT.java
- session/src/test/java/org/apache/iotdb/session/SessionTest.java
To be compatible with different version clients, we need to obtain the version number of the client in the IoTDB server.
> [IOTDB-2393] Distinguish client version via version nubmer in TSOpenSessionReq

- docs/UserGuide/IoTDB-SQL-Language/DDL-Data-Definition-Language.md
- docs/zh/UserGuide/IoTDB-SQL-Language/DDL-Data-Definition-Language.md
- integration/src/test/java/org/apache/iotdb/db/integration/IoTDBMetadataFetchIT.java
- server/src/main/java/org/apache/iotdb/db/metadata/mtree/traverser/collector/MNodeCollector.java
- server/src/main/java/org/apache/iotdb/db/metadata/mtree/traverser/counter/MNodeLevelCounter.java
- server/src/test/java/org/apache/iotdb/db/metadata/MTreeTest.java
Please refer to https://issues.apache.org/jira/browse/IOTDB-2363.
Before:
After:
> [IOTDB-2363] LEVEL can be specified at non-last level in metadata queries

- docs/UserGuide/System-Tools/Load-External-Tsfile.md
- docs/zh/UserGuide/System-Tools/Load-External-Tsfile.md
- server/src/main/java/org/apache/iotdb/db/engine/StorageEngine.java
- server/src/main/java/org/apache/iotdb/db/qp/executor/PlanExecutor.java
1. Fix incorrect docs
* " -> '
* use absolute path as example 
2. Use more accurate error messages
* if target file doesn't exist
```
IoTDB> load '/root.sg1/1642237791044-1-0-0.tsfile'
Msg: 411: File path '/root.sg1/1642237791044-1-0-0.tsfile' doesn't exists.
IoTDB> unload '/Users/chenyanze/projects/JavaProjects/iotdb/iotdb/data/data/root.sg1/0/0' '/'
Msg: 411: File '/Users/chenyanze/projects/JavaProjects/iotdb/iotdb/data/data/root.sg1/0/0' doesn't exist.
```
* if remove/unload file exists but not an internal tsfile
```
IoTDB> unload '/Users/chenyanze/projects/JavaProjects/iotdb/iotdb/data/data/sequence/root.sg1/0/0' '/'
Msg: 411: Cannot unload file '/Users/chenyanze/projects/JavaProjects/iotdb/iotdb/data/data/sequence/root.sg1/0/0' to target directory '/' because …
```
> [IOTDB-2406] Incorrect docs; Incorrect error-log

- jdbc/src/main/java/org/apache/iotdb/jdbc/Utils.java
- jdbc/src/test/java/org/apache/iotdb/jdbc/UtilsTest.java
One small syntax bug cause jdbc can't recognize rpc_compress configuration
> [IOTDB-2416] Fix jdbc config bug

- integration/src/test/java/org/apache/iotdb/db/integration/IoTDBInsertMultiRowIT.java
- integration/src/test/java/org/apache/iotdb/db/integration/aligned/IOTDBInsertAlignedValuesIT.java
- server/src/main/java/org/apache/iotdb/db/metadata/path/AlignedPath.java
- server/src/main/java/org/apache/iotdb/db/qp/logical/crud/InsertOperator.java
see IOTDB-2414
solution: make each insertRowPlan in insertRowsPlan not share measurements array
see IOTDB-2419
solution: override the getDevicePath in AlignedPath
> [IOTDB-2414][IOTDB-2419]Fix partial insert failure exception message && Fix three level aligned path query bug

- server/src/main/java/org/apache/iotdb/db/qp/physical/PhysicalPlan.java
The serialize method cannot be overwritten. If it is overwritten, reset will be affected.Therefore, you need to set this method to final.
> [IOTDB-2421] Optimize serialize method in PhysicalPlan class

- server/src/main/java/org/apache/iotdb/db/engine/compaction/cross/inplace/InplaceCompactionSelector.java
When all source files are being merged, cross compaction may select the source seq file list and source unseq file list, which is empty.
> [IOTDB-2417]Cross compaction selector bug

- server/src/main/java/org/apache/iotdb/db/engine/trigger/service/TriggerLogWriter.java
This PR fix the incorrect log buffer size for TriggerLogWriter as mentioned by #4858.
> [ISSUE-4858] Fix incorrect configuration for TriggerLogWriter

- server/src/main/java/org/apache/iotdb/db/service/thrift/impl/TSServiceImpl.java
Now we control the query execution thread, but we forgot the fecthResult interface, which means we cannot take control of that. When the client fetches the second batch, the query threads will increase to the connection numbers.
Related PR: #4660 & #4664
> [IOTDB-2412] Fetch Result Task is not taken account into query execution control

- integration/src/test/java/org/apache/iotdb/db/integration/IoTDBContinuousQueryIT.java
See IOTDB-2434 for more detail.
> [IOTDB-2434] IT fails on IoTDBContinuousQueryIT caused by double precision loss

- server/src/main/java/org/apache/iotdb/db/engine/memtable/AlignedWritableMemChunkGroup.java
- server/src/test/java/org/apache/iotdb/db/engine/storagegroup/TsFileProcessorTest.java
This bug causes aligned timeseries memtable is much more smaller than normal.
Before
After
Non_alignedTimeseries
> [IOTDB-2433] Fix aligned timeseries mem control bug

- integration/src/test/java/org/apache/iotdb/db/integration/IoTDBContinuousQueryIT.java
See IOTDB-2435 for more detail.
> [IOTDB-2435] CI fails on testCreateAlignedTimeseries() because data generator is not stopped in a CQ's test

- server/src/main/java/org/apache/iotdb/db/metadata/template/Template.java
- server/src/test/java/org/apache/iotdb/db/metadata/MManagerBasicTest.java
- server/src/test/java/org/apache/iotdb/db/qp/physical/InsertRowPlanTest.java
Fix bug about measurement path in template.
JIRA: https://issues.apache.org/jira/browse/IOTDB-2440
<hr>
This PR has:
<hr>
> [IOTDB-2440] Fix the query result is incorrect when using Template with aligned timeseries 

- integration/src/test/java/org/apache/iotdb/db/integration/IoTDBLoadExternalTsfileIT.java
- integration/src/test/java/org/apache/iotdb/db/integration/aligned/IoTDBLoadExternalAlignedTsFileIT.java
- server/src/main/java/org/apache/iotdb/db/engine/StorageEngine.java
* It caused by the wrong way of files' comparison in `getSgByEngineFile`.
* Use `Files.isSameFile()` instead of comparing strings of absolute paths.
> [IOTDB-2448] unload doesn't work correctly: it's not an internal tsfile

- server/src/main/java/org/apache/iotdb/db/engine/cq/ContinuousQueryTask.java
- server/src/main/java/org/apache/iotdb/db/engine/selectinto/InsertTabletPlansIterator.java
- server/src/main/java/org/apache/iotdb/db/service/thrift/impl/TSServiceImpl.java
- server/src/main/java/org/apache/iotdb/db/sync/receiver/transfer/SyncServiceImpl.java
problem:
First, I used CQ in an IoTDB instance.Then I start to sync the data in this instance to a new iotdb.
I found a error when I try to start sync process. Please refer to below picture and help me to check this issue.Thanks!
error picture in receiver:
The process of sync is to sync schema firstly, and when the physical plan of CQ is sent to receiver, the CQ will got nothing to select because the data is not sent to receiver at this moment.
solution:
Because the data produced by CQ in sender will be sent to receiver, so the CQ physical plan has no need to sync to receiver, just ignore this physical plan when loading schemas in receiver.
> [IOTDB-2442] Ignore CQ physical plan in sync receiver

- server/src/main/java/org/apache/iotdb/db/engine/memtable/AbstractMemTable.java
- server/src/main/java/org/apache/iotdb/db/engine/memtable/AlignedWritableMemChunk.java
- server/src/main/java/org/apache/iotdb/db/engine/memtable/AlignedWritableMemChunkGroup.java
- server/src/main/java/org/apache/iotdb/db/engine/memtable/IMemTable.java
- server/src/main/java/org/apache/iotdb/db/engine/memtable/IWritableMemChunkGroup.java
- server/src/main/java/org/apache/iotdb/db/engine/memtable/WritableMemChunk.java
- server/src/main/java/org/apache/iotdb/db/engine/memtable/WritableMemChunkGroup.java
- server/src/main/java/org/apache/iotdb/db/engine/querycontext/AlignedReadOnlyMemChunk.java
- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/TsFileProcessor.java
- server/src/main/java/org/apache/iotdb/db/metadata/path/AlignedPath.java
- server/src/main/java/org/apache/iotdb/db/metadata/path/MeasurementPath.java
- server/src/main/java/org/apache/iotdb/db/utils/datastructure/AlignedTVList.java
- server/src/main/java/org/apache/iotdb/db/utils/datastructure/BinaryTVList.java
- server/src/main/java/org/apache/iotdb/db/utils/datastructure/BooleanTVList.java
- server/src/main/java/org/apache/iotdb/db/utils/datastructure/DoubleTVList.java
- server/src/main/java/org/apache/iotdb/db/utils/datastructure/FloatTVList.java
- server/src/main/java/org/apache/iotdb/db/utils/datastructure/IntTVList.java
- server/src/main/java/org/apache/iotdb/db/utils/datastructure/LongTVList.java
- server/src/main/java/org/apache/iotdb/db/utils/datastructure/TVList.java
- server/src/test/java/org/apache/iotdb/db/engine/storagegroup/TsFileProcessorTest.java
- server/src/test/java/org/apache/iotdb/db/utils/datastructure/BinaryTVListTest.java
- server/src/test/java/org/apache/iotdb/db/utils/datastructure/BooleanTVListTest.java
- server/src/test/java/org/apache/iotdb/db/utils/datastructure/DoubleTVListTest.java
- server/src/test/java/org/apache/iotdb/db/utils/datastructure/FloatTVListTest.java
- server/src/test/java/org/apache/iotdb/db/utils/datastructure/IntTVListTest.java
- server/src/test/java/org/apache/iotdb/db/utils/datastructure/LongTVListTest.java
- server/src/test/java/org/apache/iotdb/db/utils/datastructure/VectorTVListTest.java
> [IOTDB-2433] Fix aligned timeseries mem control bug 2

- server/src/assembly/resources/conf/iotdb-engine.properties
It's a mistake, we should not let users to set `FILE_TIME_INDEX`, we only support automatically degraded from `DEVICE_TIME_INDEX` to `FILE_TIME_INDEX`.
> [IOTDB-2457] Fix write is blocked after set time_index_level=FILE_TIME_INDEX

- metrics/dropwizard-metrics/src/main/java/org/apache/iotdb/metrics/dropwizard/DropwizardMetricManager.java
- metrics/dropwizard-metrics/src/test/java/org/apache/iotdb/metrics/dropwizard/DropwizardMetricManagerTest.java
When run CI, there are following problems:
It's because the implementation of snapshot for dropwizard use wighted one as default, so I change to uniform one now.
> [IOTDB-2465][imple] fix implement of snapshot of dropwizard to UniformReservoir.

- cluster/src/main/java/org/apache/iotdb/cluster/client/sync/SyncClientAdaptor.java
- cluster/src/main/java/org/apache/iotdb/cluster/metadata/CMManager.java
- cluster/src/main/java/org/apache/iotdb/cluster/server/service/DataAsyncService.java
- cluster/src/main/java/org/apache/iotdb/cluster/server/service/DataGroupServiceImpls.java
- cluster/src/main/java/org/apache/iotdb/cluster/server/service/DataSyncService.java
- cluster/src/test/java/org/apache/iotdb/cluster/client/sync/SyncClientAdaptorTest.java
- server/src/main/java/org/apache/iotdb/db/metadata/MManager.java
- server/src/main/java/org/apache/iotdb/db/tools/virtualsg/DeviceMappingViewer.java
- server/src/test/java/org/apache/iotdb/db/metadata/MManagerBasicTest.java
- thrift-cluster/src/main/thrift/cluster.thrift
See JIRA: https://issues.apache.org/jira/browse/IOTDB-2462
The Thrift interface `getAllDevices()` is changed. Does it cause imcompatiable with previsous version, or Thrift framework can handle this upgrade?
> [IOTDB-2462] Fix ALIGN BY DEVICE query in cluster mode

- server/src/main/java/org/apache/iotdb/db/engine/compaction/cross/rewrite/selector/RewriteCompactionFileSelector.java
- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/TsFileResource.java
- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/timeindex/DeviceTimeIndex.java
- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/timeindex/FileTimeIndex.java
- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/timeindex/ITimeIndex.java
- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/timeindex/V012FileTimeIndex.java
- server/src/main/java/org/apache/iotdb/db/query/control/FileReaderManager.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/CompactionSchedulerTest.java
* While one TsFileResouece's ITimeIndex degrade from DeviceTimeIndex to FileTimeIndex, each time a query arrived, it will read from tsfile to judge whether this tsfile contains current device. However, this is totally unnecessary. We can simply return true here, and then do this judgement in the following query process, while getting the TimeseriesMetadata, it can also use the bloomfilter in tsfile footer to accelerate this process.
* Encapsulate the process of opening and releasing file handles into `FileReaderManager`.
> Make FileTimeIndex directly return true while doing containsDevice() 

- integration/src/test/java/org/apache/iotdb/db/integration/aligned/IoTDBDeletionIT.java
- server/src/main/java/org/apache/iotdb/db/engine/memtable/AlignedWritableMemChunk.java
There is code logic optimization. When insert aligned time series data and check the measurements order in insertPlan, we can use the HashMap instead of the ArrayList. 
The indexOf method in ArrayList seems taking too much time.... :(
> [IOTDB-2433] Fix insert aligned timeseries performance reduction

- integration/src/test/java/org/apache/iotdb/db/integration/IoTDBUnseqOverlappedPageIT.java
- server/src/main/java/org/apache/iotdb/db/query/reader/series/SeriesReader.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/CompactionSchedulerTest.java
You can see the test data in [here](https://docs.google.com/spreadsheets/d/1kfrSR1_paSd9B1Z0jnPBD3WQIMDslDuNm4R0mpWx9Ms/edit?usp=sharing).
> [IOTDB-2445] Fix overlapped data should be consumed first bug

- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/TsFileProcessorInfo.java
- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/VirtualStorageGroupProcessor.java
- server/src/main/java/org/apache/iotdb/db/service/IoTDB.java
Fix some metrics bugs:
1. Memory size of mtree、current number of timeseries/sg/deivces is always 0.
2. Memory size of sg is always 0
3. Memory size of chunkMetaData continuously increase
jira: https://issues.apache.org/jira/browse/IOTDB-2490
> [IoTDB-2490] Fix some metrics bugs

- server/src/main/java/org/apache/iotdb/db/metadata/mnode/InternalMNode.java
- server/src/test/java/org/apache/iotdb/db/metadata/mnode/MNodeTest.java
During concurrent timeseries auto creation, MTree will throw NPE.
See  IOTDB-2476
The replacement operation of EntityMNode is not a synchronized operation, thus a thread will read a null between the deletion and addition, which is the existing implementation of repalcement.
Use replace method of ConcurrentHashMap to make the node replacement a synchronized operation and make the replace method of MNode a synchronized operation.
> [IOTDB-2476] Fix concurrent bug during entityMNode replacement

- cli/src/main/java/org/apache/iotdb/cli/utils/JlineUtils.java
> [IOTDB-2498] Fix cli history filename too long when using OpenID

- server/src/main/java/org/apache/iotdb/db/query/aggregation/impl/FirstValueAggrResult.java
- server/src/test/java/org/apache/iotdb/db/query/dataset/groupby/GroupByLevelDataSetTest.java
Fix a bug in FirstValueAggrResult.updateResultUsingValues()
The behaviour of FirstValueAggrResult.updateResultUsingValues() and LastValueDescAggrResult.updateResultUsingValues() should be the same.
Update the timestamp of FirstValueAggrResult when the result is updated from ValueIterator.
The result of first_value aggregation may be wrong when query with "value filter + group by level", since the merge() of FirstValueAggrResults is no-op when timestamps of two FirstValueAggrResults are both Long.MAX_VALUE.
Add a test case in GroupByLevelDataSetTest.java. The query statementis like "select first_value(s0) from root.** where s0!=0 or time<10 group by level=3". The result before the fix is wrong.
> [IOTDB-2501]Fix timestamp not updated bug in FirstValueAggrResult.updateResultUsingValues()

- server/src/main/java/org/apache/iotdb/db/query/reader/series/SeriesReader.java
I think the root problem is since #4819 we put only 100% overlapped page to mergeReader, therefore we have to ensure that the sequence of page is correct.
> [IOTDB-2445] [IOTDB-2502] Fix overlapped data should be consumed firstly bug

- server/src/main/java/org/apache/iotdb/db/metadata/tag/TagManager.java
- server/src/main/java/org/apache/iotdb/db/query/dataset/groupby/GroupByWithValueFilterDataSet.java
- server/src/main/java/org/apache/iotdb/db/query/dataset/groupby/GroupByWithoutValueFilterDataSet.java
- server/src/main/java/org/apache/iotdb/db/query/executor/AggregationExecutor.java
- server/src/main/java/org/apache/iotdb/db/query/executor/FillQueryExecutor.java
- server/src/main/java/org/apache/iotdb/db/query/executor/LastQueryExecutor.java
- server/src/main/java/org/apache/iotdb/db/query/executor/RawDataQueryExecutor.java
- server/src/main/java/org/apache/iotdb/db/query/timegenerator/ServerTimeGenerator.java
Currently, the data aggregation process will hold the readlock of storage group, which blocks insertion.
We need to separate the getQueryDataSource (holding readlock of sg) with reading data in aggregation.
> [IOTDB-2506] Refine the lock granularity of query

- server/src/main/java/org/apache/iotdb/db/exception/query/QueryProcessException.java
- server/src/main/java/org/apache/iotdb/db/metadata/MManager.java
- server/src/main/java/org/apache/iotdb/db/query/dataset/groupby/GroupByFillDataSet.java
- server/src/main/java/org/apache/iotdb/db/query/dataset/groupby/GroupByWithValueFilterDataSet.java
- server/src/main/java/org/apache/iotdb/db/query/dataset/groupby/GroupByWithoutValueFilterDataSet.java
- server/src/main/java/org/apache/iotdb/db/query/executor/AggregationExecutor.java
- server/src/main/java/org/apache/iotdb/db/query/executor/FillQueryExecutor.java
- server/src/main/java/org/apache/iotdb/db/query/executor/LastQueryExecutor.java
- server/src/main/java/org/apache/iotdb/db/query/executor/RawDataQueryExecutor.java
- server/src/main/java/org/apache/iotdb/db/query/timegenerator/ServerTimeGenerator.java
Currently, the data aggregation process will hold the readlock of storage group, which blocks insertion.
We need to separate the getQueryDataSource (holding readlock of sg) with reading data in aggregation.
> [IOTDB-2506] [To rel/0.12] Refine the lock granularity of the aggregation query

- .asf.yaml
When we merge PR to a main branch, I think we should always use squash merge option. Therefore, I disabled the merge commit and the rebase merge buttons.
> Disable merge commit button by default

- docs/UserGuide/Reference/TSDB-Comparison.md
- docs/zh/UserGuide/Reference/TSDB-Comparison.md
The figure should be the write latency, however, it is a throughput figure.
> remove incorrect img in TSDB-Comparison

- tsfile/src/main/java/org/apache/iotdb/tsfile/file/metadata/statistics/BinaryStatistics.java
- tsfile/src/main/java/org/apache/iotdb/tsfile/file/metadata/statistics/BooleanStatistics.java
- tsfile/src/main/java/org/apache/iotdb/tsfile/file/metadata/statistics/DoubleStatistics.java
- tsfile/src/main/java/org/apache/iotdb/tsfile/file/metadata/statistics/FloatStatistics.java
- tsfile/src/main/java/org/apache/iotdb/tsfile/file/metadata/statistics/IntegerStatistics.java
- tsfile/src/main/java/org/apache/iotdb/tsfile/file/metadata/statistics/LongStatistics.java
Replaced Boolean, Double and Float with TSDataType.toString in those 3 classes respectively.
> [IOTDB-2512]Replaced some static variables with TSDataType.toString

- tsfile/src/main/java/org/apache/iotdb/tsfile/common/conf/TSFileDescriptor.java
- tsfile/src/test/java/org/apache/iotdb/tsfile/common/conf/TSFileDescriptorTest.java
Skip the corrupted custom property when loading TSFileConfig from the properties file.
#5030  
1. Refactoring the code, disassembling the big method.
2. Handling the corrupted properties file in a more intuitive approach.
<hr>
This PR has:
<hr>
`org.apache.iotdb.tsfile.common.conf.TSFileDescriptor`
> [ISSUE-5030]optimize the tsfile configuration loading

- server/src/main/java/org/apache/iotdb/db/engine/compaction/CompactionUtils.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/cross/CrossSpaceCompactionExceptionHandler.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/cross/rewrite/recover/RewriteCrossSpaceCompactionLogAnalyzer.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/cross/rewrite/selector/RewriteCompactionFileSelector.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/cross/rewrite/task/RewriteCrossCompactionRecoverTask.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/cross/rewrite/task/RewriteCrossSpaceCompactionTask.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/inner/InnerSpaceCompactionExceptionHandler.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/inner/sizetiered/SizeTieredCompactionRecoverTask.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/inner/sizetiered/SizeTieredCompactionTask.java
- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/TsFileManager.java
- server/src/main/java/org/apache/iotdb/db/rescon/TsFileResourceManager.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/cross/CrossSpaceCompactionExceptionTest.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/cross/RewriteCompactionFileSelectorTest.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/cross/RewriteCrossSpaceCompactionRecoverTest.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/inner/InnerSpaceCompactionExceptionTest.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/inner/sizetiered/SizeTieredCompactionRecoverTest.java
- server/src/test/java/org/apache/iotdb/db/engine/storagegroup/StorageGroupProcessorTest.java
After compaction, we have some operations as following:
(1) move tmp target files to final target files
(2) update memory, make it atomic.
(3) delete source files and its corresponding files
> [IOTDB-2500] [ query & cross-compaction ] cross-compaction stuck

- docs/UserGuide/Administration-Management/Administration.md
- docs/UserGuide/Reference/Config-Manual.md
- docs/zh/UserGuide/Administration-Management/Administration.md
- docs/zh/UserGuide/Reference/Config-Manual.md
- server/src/assembly/resources/conf/iotdb-engine.properties
#5001 added the configuration of changing password encrypt algorithm. However we have still only one encrypt algorithm MD5 in IoTDB currently. These configs are meaningless for normal users. Therefore, I think we should hide them until more encryption methods added.
> [IOTDB-2540] Hide password encrypt configuration until more encryption added

- server/src/main/java/org/apache/iotdb/db/metadata/MManager.java
- server/src/test/java/org/apache/iotdb/db/metadata/MManagerBasicTest.java
The createTimeseriesPlan received from sender may contains tagOffset, which results in MManager mistaken this plan as recovering plan. 
Add isRecover check before processing the tag info in the plan
> [IOTDB-2544] Fix tag info sync error during metadata sync

- server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfigCheck.java
The wal of 0.12 is not compatible with 0.13. Therefore, we need to check whether the WAL file existed before upgrading to 0.13.
> [IOTDB-2522] Check WAL files before upgrading 0.12 to 0.13

- server/src/main/java/org/apache/iotdb/db/writelog/node/ExclusiveWriteLogNode.java
1. get new FileWriter before switchBufferWorkingToFlushing
2. set system to read-only when error occurs in flushBuffer method
> [To rel/0.12][IOTDB-2426] WAL deadlock caused by too many open files

- integration/src/test/java/org/apache/iotdb/db/integration/IoTDBCheckConfigIT.java
- server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfigCheck.java
Users can upgrade to 0.13 from 0.12. For other versions before 0.12, users should firstly upgrade to 0.12 because they are too old.
> [IOTDB-2565] Only support upgrading 0.13 from 0.12

- server/src/main/java/org/apache/iotdb/db/qp/physical/crud/GroupByTimeFillPlan.java
- server/src/main/java/org/apache/iotdb/db/query/executor/QueryRouter.java
After #5045 , initFillRange() is invoked twice, which may bring some risk. The things we only need to do is reset the query startTime and Endtime.
> [IOTDB-2532] Fix group by fill logic

- server/src/main/java/org/apache/iotdb/db/concurrent/ThreadName.java
- server/src/main/java/org/apache/iotdb/db/engine/StorageEngine.java
- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/VirtualStorageGroupProcessor.java
- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/virtualSg/StorageGroupManager.java
- server/src/main/java/org/apache/iotdb/db/utils/ThreadUtils.java
- server/src/main/java/org/apache/iotdb/db/writelog/manager/MultiFileLogNodeManager.java
- server/src/main/java/org/apache/iotdb/db/writelog/node/ExclusiveWriteLogNode.java
- server/src/main/java/org/apache/iotdb/db/writelog/node/WriteLogNode.java
See JIRA: https://issues.apache.org/jira/browse/IOTDB-2567
In this patch, the thread count is back to normal and the tests are all successful.
> [IOTDB-2567] Fix thread and ByteBuffer leak after service stopped

- .github/workflows/client-go.yml
- .github/workflows/client.yml
- .github/workflows/grafana-plugin.yml
- .github/workflows/main-unix.yml
- .github/workflows/main-win.yml
- .github/workflows/sonar-coveralls.yml
We can enable github actions workflow for all important new features branches.  For example, `new_sync`, `new_cluster`, `new_wal`, etc.
> enable workflow for branchs start with `new_`

- server/src/main/java/org/apache/iotdb/db/metadata/template/TemplateManager.java
Clearer message for alignment conflict of template and mounted node.
Now message will carry template name and specified conflit node path.
> [IOTDB-2577]Clearer message for alignment conflict of template and mounted node

- server/src/main/java/org/apache/iotdb/db/engine/compaction/TsFileManagement.java
- server/src/main/java/org/apache/iotdb/db/engine/merge/manage/MergeResource.java
- server/src/main/java/org/apache/iotdb/db/engine/merge/selector/MaxFileMergeFileSelector.java
- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/TsFileResource.java
- server/src/test/java/org/apache/iotdb/db/engine/merge/MaxFileMergeFileSelectorTest.java
- server/src/test/java/org/apache/iotdb/db/engine/merge/MergeTaskTest.java
(1) Fix Cross space compaction selector bug, which can avoid unseq data exists in target files.
(2) Accelerate and optimize selecting files in cross space compaction.
> [To rel/0.12][IOTDB-2584]Fix cross space compaction selector

- integration/src/test/java/org/apache/iotdb/db/integration/IOTDBInsertIT.java
- integration/src/test/java/org/apache/iotdb/db/integration/aligned/IOTDBInsertAlignedValuesIT.java
- server/src/main/java/org/apache/iotdb/db/qp/physical/crud/InsertPlan.java
Currently, if we insert multiple same measurements in one row, it'll succeed for non-aligned timeseries but not for aligned timeseries. 
```
IoTDB> insert into root.sg.d1(time,s1,s1) values(1,2,3)
insert into root.sg.d1(time,s1,s1) values(1,2,3)
select ** from root
+-----------------------------+-------------+
|                         Time|root.sg.d1.s1|
+-----------------------------+-------------+
|1970-01-01T08:00:00.001+08:00|          3.0|
+-----------------------------+-------------+
It costs 0.058s
IoTDB> insert into root.sg.d2(time,s1,s1) aligned values(1,2,3)
insert into root.sg.d2(time,s1,s1) aligned values(1,2,3)
Msg: 500: [INTERNAL_SERVER_ERROR(500)] Exception occurred: …
```
> [IOTDB-2600] Ban inserting duplicated columns in one row

- docs/UserGuide/Reference/Config-Manual.md
- server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
Keep Consistent between IoTDBConfig and iotdb-engine.properties
> [IOTDB-2601] fix default max_thrift_frame_size from 64M to 512M

- server/src/assembly/resources/conf/iotdb-engine.properties
- server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
- server/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/TsFileManagement.java
- server/src/main/java/org/apache/iotdb/db/engine/merge/recover/MergeLogAnalyzer.java
- server/src/main/java/org/apache/iotdb/db/engine/merge/task/CompactionMergeRecoverTask.java
- server/src/main/java/org/apache/iotdb/db/engine/merge/task/RecoverMergeTask.java
- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/StorageGroupProcessor.java
- server/src/test/java/org/apache/iotdb/db/engine/merge/MergeRecoverTest.java
- server/src/test/java/org/apache/iotdb/db/engine/merge/MergeTest.java
Fix 2 problems:
1. There may be more data after iotdb restart. The reason is that cross space compaction recovery did not consisder one case, which is when some source files lost.
2. If there is deletion during cross space compaction process, if the iOTDB is stopped then and all the source files are not deleted, then the deleted data will be queried during the next restart.
> [To rel/0.12][IOTDB-2603]Fix compaction recover

- server/src/main/java/org/apache/iotdb/db/engine/StorageEngine.java
stop scheduler pool when deleting storage group.
> [IOTDB-2580] Fix DirectByteBuffer and thread leak when deleting storage group

- server/src/main/java/org/apache/iotdb/db/conf/IoTDBConstant.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/TsFileIdentifier.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/cross/rewrite/RewriteCrossSpaceCompactionSelector.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/cross/rewrite/recover/RewriteCrossSpaceCompactionLogAnalyzer.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/cross/rewrite/recover/RewriteCrossSpaceCompactionLogger.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/cross/rewrite/task/RewriteCrossCompactionRecoverTask.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/task/CompactionRecoverTask.java
- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/TsFileNameGenerator.java
So far, the 0.13 compaction log parser cannot read the 0.12 compaction log. Therefore, we need to make compaction restart recovery and log reading forward compatible with 0.12.
> [IOTDB-2578]Fix cross space compaction recover and log read compatible with 0.12

- server/src/main/java/org/apache/iotdb/db/engine/merge/recover/MergeLogAnalyzer.java
- server/src/test/java/org/apache/iotdb/db/engine/merge/MergeRecoverTest.java
Query less data after compaction recovery. When handling recover, add the source tsfiles which have been deleted at the last cross space compaction.
> [To rel/0.12][IOTDB-2640]Fix cross compaction recover bug

- docs/UserGuide/UDF-Library/Quick-Start.md
- docs/zh/UserGuide/UDF-Library/Quick-Start.md
It's not proper for UDF Library to put the unreviewed downloadable binary jar in the docs. Therefore, the links are removed.
> [IOTDB-2647] UDF Library in Apache Way

- server/src/main/java/org/apache/iotdb/db/engine/merge/selector/MaxFileMergeFileSelector.java
- server/src/test/java/org/apache/iotdb/db/engine/merge/MaxFileMergeFileSelectorTest.java
see [IOTDB-2624](https://issues.apache.org/jira/browse/IOTDB-2624)
> [To rel/0.12][IOTDB-2624] Fix "overlapped data should be consumed first" occurs when executing query

- server/src/main/java/org/apache/iotdb/db/engine/compaction/cross/rewrite/RewriteCrossSpaceCompactionSelector.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/cross/rewrite/manage/CrossSpaceCompactionResource.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/cross/rewrite/recover/RewriteCrossSpaceCompactionLogger.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/cross/rewrite/selector/RewriteCompactionFileSelector.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/inner/utils/InnerSpaceCompactionUtils.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/cross/CrossSpaceCompactionTest.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/cross/MergeUpgradeTest.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/cross/RewriteCompactionFileSelectorTest.java
see [IOTDB-2653](https://issues.apache.org/jira/browse/IOTDB-2653)
> [IOTDB-2653] Fix "overlapped data should be consumed first" occurs when executing query

- server/src/main/java/org/apache/iotdb/db/qp/executor/PlanExecutor.java
- server/src/test/java/org/apache/iotdb/db/qp/PlannerTest.java
IoTDB> list user privileges root
+-----------------------+
|              privilege|
+-----------------------+
|      SET_STORAGE_GROUP|
|      INSERT_TIMESERIES|
|      UPDATE_TIMESERIES|
|        READ_TIMESERIES|
|      CREATE_TIMESERIES|
|      DELETE_TIMESERIES|
|            CREATE_USER|
|            DELETE_USER|
|        MODIFY_PASSWORD|
|              LIST_USER|
|   GRANT_USER_PRIVILEGE|
|  REVOKE_USER_PRIVILEGE|
|        GRANT_USER_ROLE|
|       REVOKE_USER_ROLE|
|            CREATE_ROLE|
|            DELETE_ROLE|
|              LIST_ROLE|
|   GRANT_ROLE_PRIVILEGE|
|  REVOKE_ROLE_PRIVILEGE|
|        CREATE_FUNCTION|
|          DROP_FUNCTION|
|         CREATE_TRIGGER|
|           DROP_TRIGGER|
|          START_TRIGGER|
|           STOP_TRIGGER|
|CREATE_CONTINUOUS_QUERY|
| …
> [IOTDB-2520] list user privilege root returns empty

- client-py/SessionExample.py
- client-py/SessionTest.py
- client-py/iotdb/Session.py
Support the following usage:
```python
session.create_time_series(
"root.sg_test_01.d_02.s_01",
TSDataType.INT64,
TSEncoding.PLAIN,
Compressor.SNAPPY,
None,
{"tag1": "v1"},
{"description": "v1"},
"temperature"
)
```
The result after execute the tests:
```
IoTDB> show timeseries
+-------------------------+-----------+---------------+--------+--------+-----------+-------------+--------------------+
|               timeseries|      alias|  storage group|dataType|encoding|compression|         tags|          attributes|
+-------------------------+-----------+---------------+--------+--------+-----------+-------------+--------------------+
|root.sg_test_01.d_01.s_05|       null|root.sg_test_01|  DOUBLE|   PLAIN|     SNAPPY|         null|                null|
|root.sg_test_01.d_01.s_04| …
```
> [IOTDB-2357] Support create timeseries interface with tags in python client

- client-py/SessionExample.py
- client-py/SessionTest.py
- client-py/iotdb/utils/NumpyTablet.py
- client-py/iotdb/utils/Tablet.py
- client-py/requirements.txt
- client-py/tests/tablet_performance_comparison.py
Refactor #3700 code of insert ndarray Tablet in Python API.
```python
measurements_ = ["s_01", "s_02", "s_03", "s_04", "s_05", "s_06"]
data_types_ = [
TSDataType.BOOLEAN,
TSDataType.INT32,
TSDataType.INT64,
TSDataType.FLOAT,
TSDataType.DOUBLE,
TSDataType.TEXT,
]
np_values_ = [
np.array([False, True, False, True], np.dtype('>?')),
np.array([10, 100, 100, 0], np.dtype('>i4')),
np.array([11, 11111, 1, 0], np.dtype('>i8')),
np.array([1.1, 1.25, 188.1, 0], np.dtype('>f4')),
np.array([10011.1, 101.0, 688.25, 6.25], np.dtype('>f8')),
["test01", "test02", "test03", "test04"],
]
np_timestamps_ = np.array([1, 2, 3, 4], np.dtype('>i8'))
np_tablet_ = NumpyTablet(
"root.sg_test_01.d_02", measurements_, data_types_, np_values_, np_timestamps_
)
session.insert_tablet(np_tablet_)
```
> [IOTDB-2703] Support insert ndarray Tablet in Python API

- server/src/main/java/org/apache/iotdb/db/engine/compaction/inner/sizetiered/SizeTieredCompactionRecoverTask.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/TsFileIdentifierUT.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/recover/SizeTieredCompactionRecoverCompatibleTest.java
Merge.mods file is produced by cross compaction in 0.12, and we do not need to read it in inner cocmpaction recovery at 0.13.
> [IOTDB-2712]Remove reading merge.mods in inner compaction recover

- server/src/main/java/org/apache/iotdb/db/qp/logical/crud/SFWOperator.java
- server/src/main/java/org/apache/iotdb/db/qp/physical/PhysicalPlan.java
- server/src/main/java/org/apache/iotdb/db/qp/physical/crud/QueryPlan.java
- server/src/main/java/org/apache/iotdb/db/qp/strategy/PhysicalGenerator.java
- server/src/main/java/org/apache/iotdb/db/service/TSServiceImpl.java
- server/src/test/java/org/apache/iotdb/db/integration/auth/IoTDBAuthorizationIT.java
[ISSUE-4399](https://github.com/apache/iotdb/issues/4399)
TO reproduce:
user admin user:
SET STORAGE GROUP TO root.sg1;
CREATE TIMESERIES root.sg1.d1.s1 WITH DATATYPE=INT32, ENCODING=PLAIN;
CREATE TIMESERIES root.sg1.d1.s2 WITH DATATYPE=INT32, ENCODING=PLAIN;
INSERT INTO root.sg1.d1(timestamp, s1, s2) VALUES (0, -1, 1);
INSERT INTO root.sg1.d1(timestamp, s1, s2) VALUES (1, -2, 2);
INSERT INTO root.sg1.d1(timestamp, s1, s2) VALUES (2, -3, 3);
CREATE FUNCTION example AS "org.apache.iotdb.udf.UDTFExample";
SET STORAGE GROUP TO root.sg2;
CREATE TIMESERIES root.sg2.d1.s1 WITH DATATYPE=INT32, ENCODING=PLAIN;
CREATE TIMESERIES root.sg2.d1.s2 WITH DATATYPE=INT32, ENCODING=PLAIN;
INSERT INTO root.sg2.d1(timestamp, s1, s2) VALUES (0, -1, 1);
INSERT INTO root.sg2.d1(timestamp, s1, s2) VALUES (1, -2, …
> [To rel/0.12][ISSUE-4399] When non-root user returns a null value, return no permission error message

- consensus/pom.xml
- consensus/src/main/java/org/apache/iotdb/consensus/IConsensus.java
- consensus/src/main/java/org/apache/iotdb/consensus/common/ConsensusGroup.java
- consensus/src/main/java/org/apache/iotdb/consensus/common/ConsensusGroupId.java
- consensus/src/main/java/org/apache/iotdb/consensus/common/DataSet.java
- consensus/src/main/java/org/apache/iotdb/consensus/common/Endpoint.java
- consensus/src/main/java/org/apache/iotdb/consensus/common/GroupType.java
- consensus/src/main/java/org/apache/iotdb/consensus/common/Peer.java
- consensus/src/main/java/org/apache/iotdb/consensus/common/request/IConsensusRequest.java
- consensus/src/main/java/org/apache/iotdb/consensus/common/response/ConsensusGenericResponse.java
- consensus/src/main/java/org/apache/iotdb/consensus/common/response/ConsensusReadResponse.java
- consensus/src/main/java/org/apache/iotdb/consensus/common/response/ConsensusResponse.java
- consensus/src/main/java/org/apache/iotdb/consensus/common/response/ConsensusWriteResponse.java
- consensus/src/main/java/org/apache/iotdb/consensus/exception/ConsensusException.java
- consensus/src/main/java/org/apache/iotdb/consensus/exception/ConsensusGroupAlreadyExistException.java
- consensus/src/main/java/org/apache/iotdb/consensus/exception/ConsensusGroupNotExistException.java
- consensus/src/main/java/org/apache/iotdb/consensus/exception/IllegalPeerNumException.java
- consensus/src/main/java/org/apache/iotdb/consensus/ratis/RatisConsensus.java
- consensus/src/main/java/org/apache/iotdb/consensus/standalone/StandAloneConsensus.java
- consensus/src/main/java/org/apache/iotdb/consensus/standalone/StandAloneServerImpl.java
- consensus/src/main/java/org/apache/iotdb/consensus/statemachine/EmptyStateMachine.java
- consensus/src/main/java/org/apache/iotdb/consensus/statemachine/IStateMachine.java
- consensus/src/test/java/org/apache/iotdb/consensus/standalone/StandAloneConsensusTest.java
- pom.xml
- server/pom.xml
- server/src/main/java/org/apache/iotdb/db/consensus/ConsensusMain.java
- server/src/main/java/org/apache/iotdb/db/consensus/ratis/RatisDataRegionStateMachine.java
- server/src/main/java/org/apache/iotdb/db/consensus/ratis/RatisSchemaRegionStateMachine.java
- server/src/main/java/org/apache/iotdb/db/qp/physical/PhysicalPlan.java
- Create consensus Module
- Encapsulate the consensus layer interface implementation and implement the related class structure
- A consensus layer implementation `StandAloneConsensus` containing basic logic is implemented to facilitate the early use of other modules, any module can use`IConsensus consensusImpl = new StandAloneConsensus(id -> new EmptyStateMachine());` to perform an initialization implementation
see [doc](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=199536093) for class diagram
> [IOTDB-2673] Implement the consensus layer basic framework

- integration/src/test/java/org/apache/iotdb/db/integration/IOTDBInsertIT.java
- server/src/main/java/org/apache/iotdb/db/utils/CommonUtils.java
See IOTDB-2732.
Repetition steps:
1. create timeseries root.wt04.PLAIN1 WITH DATATYPE=FLOAT,ENCODING=PLAIN,COMPRESSOR=UNCOMPRESSED
2. insert into root.wt04(timestamp,PLAIN1) values(5,3.4028235E300)
3. select PLAIN1 from root.wt04
```
Time     |root.wt04.PLAIN1    |
5        |Infinity            |
```
The reason of this problem is 3.4028235E300 is too large for float type but not for double type.
When parse String `3.4028235E300` to float value, JVM will not throw an exception but parse it to a special value `Infinity`.
Therefore, I added a check for it.
> [IOTDB-2732] Reject inserting an invalid infinity float value

- integration/src/test/java/org/apache/iotdb/db/integration/IoTDBResultMetadataIT.java
- jdbc/src/main/java/org/apache/iotdb/jdbc/IoTDBResultMetadata.java
You can see details in [JIRA](https://issues.apache.org/jira/browse/IOTDB-2734).
The reason that cause this bug is that we shouldn't minus 2 while calculating column index even if `ignoreTimestamp` is `false` because we already have time column in both `columnInfoList` and `columnTypeList`.
> [IOTDB-2734] Correct result type name in ResultMetadata

- integration/src/test/java/org/apache/iotdb/db/integration/IoTDBResultMetadataIT.java
- jdbc/src/main/java/org/apache/iotdb/jdbc/IoTDBResultMetadata.java
You can see details in [JIRA](https://issues.apache.org/jira/browse/IOTDB-2734).
The reason that cause this bug is that we shouldn't minus 2 while calculating column index even if `ignoreTimestamp` is `false` because we already have time column in both `columnInfoList` and `columnTypeList`.
> [To rel/0.13] [IOTDB-2734] Correct result type name in ResultMetadata

- docs/UserGuide/Reference/Config-Manual.md
- docs/zh/UserGuide/Reference/Config-Manual.md
- server/src/assembly/resources/conf/iotdb-engine.properties
- server/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java
Since IDTable is not formal feature of 0.13, we need to hide the configuration and not allow users to open it.
> [To rel/0.13][IOTDB-2742] Hide IDTable configurations

- docs/UserGuide/Reference/Config-Manual.md
- docs/zh/UserGuide/Reference/Config-Manual.md
- server/src/assembly/resources/conf/iotdb-engine.properties
The argument "compaction_priority" in iotdb-engine.properties file should be uppercase.
> [IOTDB-2745]Fix compaction priority param incorrect bug

- docs/UserGuide/Reference/Config-Manual.md
- docs/zh/UserGuide/Reference/Config-Manual.md
- server/src/assembly/resources/conf/iotdb-engine.properties
The argument "compaction_priority" in iotdb-engine.properties file should be uppercase.
> [To rel/0.13][IOTDB-2745]Fix compaction priority param incorrect bug

- server/src/main/java/org/apache/iotdb/db/engine/compaction/inner/utils/SingleSeriesCompactionExecutor.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/inner/InnerSpaceCompactionUtilsNoAlignedTest.java
When executing inner space compaction for sequence files, the chunks of a series are read into memory one by one, and the program uses three ways to determine how to process a chunk:
1. If the chunk is small or part of data in the chunk is deleted, the chunk will be deserialized into points and rewritten into chunk writer. The following chunk will be written into chunk writer util the size of chunk writer is large enough to flush.
2. If the chunk is too large, the program just flush it to the disk.
3. If the chunk is neither too small nor too large, the program just caches it in memory and merges it with the chunk following. The cached chunk will not be flush util its size is large enough.
Of course, these are rough descriptions. When the program reads a chunk that satisfies the condition …
> [IOTDB-2723] Fix sequence inner space compaction lose data

- example/session/src/main/java/org/apache/iotdb/SessionExample.java
- tsfile/src/main/java/org/apache/iotdb/tsfile/write/chunk/AlignedChunkGroupWriterImpl.java
- tsfile/src/main/java/org/apache/iotdb/tsfile/write/chunk/NonAlignedChunkGroupWriterImpl.java
- tsfile/src/main/java/org/apache/iotdb/tsfile/write/chunk/ValueChunkWriter.java
- tsfile/src/main/java/org/apache/iotdb/tsfile/write/record/Tablet.java
- tsfile/src/test/java/org/apache/iotdb/tsfile/write/TsFileWriteApiTest.java
**Bug description：**
When encapsulating TEXT type data in a tablet and using tsFileWriter to write it with null value may cause NPE in page writer and also may report "Flushed data size is inconsistent with computation!" exception.
> [IOTDB-2614]Fix inserting tablet with null value in TsFileWriter

- server/src/main/java/org/apache/iotdb/db/metadata/MManager.java
Reason of the ISSUE:
During recovery from mlog.bin, MManager::MLogWrite is not initialized since there is no need to write a new entry into mlog, which directly causes the NPE of this issue. This may be caused by nonstandard usage of Templates or originate from disharmonious implementation between MManager and TemplateManager. We will make a thorough refactor to these modules soon.
To fix this issue, we enhanced the check statement before writing entry into mlog.
> [To rel/0.13][IOTDB-2750] Enhance check statement before writing mlog

- cluster/src/main/java/org/apache/iotdb/cluster/metadata/CMManager.java
- docs/UserGuide/Operate-Metadata/Timeseries.md
- docs/zh/UserGuide/Operate-Metadata/Timeseries.md
- example/session/src/main/java/org/apache/iotdb/AlignedTimeseriesSessionExample.java
- integration/src/test/java/org/apache/iotdb/session/IoTDBSessionSimpleIT.java
- server/src/main/java/org/apache/iotdb/db/metadata/MManager.java
- server/src/main/java/org/apache/iotdb/db/metadata/mtree/MTree.java
- server/src/main/java/org/apache/iotdb/db/qp/logical/sys/CreateAlignedTimeSeriesOperator.java
- server/src/main/java/org/apache/iotdb/db/qp/physical/sys/CreateAlignedTimeSeriesPlan.java
- server/src/main/java/org/apache/iotdb/db/qp/sql/IoTDBSqlVisitor.java
- server/src/main/java/org/apache/iotdb/db/service/thrift/impl/TSServiceImpl.java
- server/src/test/java/org/apache/iotdb/db/metadata/idtable/IDTableTest.java
- server/src/test/java/org/apache/iotdb/db/qp/physical/PhysicalPlanSerializeTest.java
- session/src/main/java/org/apache/iotdb/session/Session.java
- session/src/test/java/org/apache/iotdb/session/IoTDBSessionDisableMemControlIT.java
- session/src/test/java/org/apache/iotdb/session/IoTDBSessionVectorABDeviceIT.java
- session/src/test/java/org/apache/iotdb/session/IoTDBSessionVectorAggregationWithUnSeqIT.java
- session/src/test/java/org/apache/iotdb/session/IoTDBSessionVectorInsertIT.java
- thrift/src/main/thrift/rpc.thrift
```
IoTDB> create aligned timeseries root.sg1.d1(s1 INT32 tags(tag1=v1, tag2=v2) attributes(attr1=v1, attr2=v2), s2 DOUBLE tags(tag3=v3, tag4=v4) attributes(attr3=v3, attr4=v4))
IoTDB> show timeseries
+--------------+-----+-------------+--------+--------+-----------+-------------------------+---------------------------+
| timeseries|alias|storage group|dataType|encoding|compression| tags| attributes|
+--------------+-----+-------------+--------+--------+-----------+-------------------------+---------------------------+
|root.sg1.d1.s1| null| root.sg1| INT32| RLE| SNAPPY|{"tag1":"v1","tag2":"v2"}|{"attr2":"v2","attr1":"v1"}|
|root.sg1.d1.s2| null| root.sg1| DOUBLE| GORILLA| SNAPPY|{"tag4":"v4","tag3":"v3"}|{"attr4":"v4","attr3":"v3"}| …
```
> [IOTDB-2524] Aligned Timeseries support tags and attributes

- server/src/main/java/org/apache/iotdb/db/metadata/MManager.java
Reason of the ISSUE:
During recovery from mlog.bin, MManager::MLogWrite is not initialized since there is no need to write a new entry into mlog, which directly causes the NPE of this issue. This may be caused by nonstandard usage of Templates or originate from disharmonious implementation between MManager and TemplateManager. We will make a thorough refactor to these modules soon.
To fix this issue, we enhanced the check statement before writing entry into mlog.
> [IOTDB-2750] Enhance check statement before writing mlog

- integration/src/test/java/org/apache/iotdb/db/integration/IoTDBCompactionITWithIDTable.java
- integration/src/test/java/org/apache/iotdb/db/integration/IoTDBCompactionWithIDTableIT.java
- server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfigCheck.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/CompactionUtils.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/cross/rewrite/manage/CrossSpaceCompactionResource.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/inner/utils/InnerSpaceCompactionUtils.java
- server/src/main/java/org/apache/iotdb/db/metadata/idtable/AppendOnlyDiskSchemaManager.java
- server/src/main/java/org/apache/iotdb/db/metadata/idtable/IDTable.java
- server/src/main/java/org/apache/iotdb/db/metadata/idtable/IDTableHashmapImpl.java
- server/src/main/java/org/apache/iotdb/db/metadata/idtable/IDTableManager.java
Fix ID Table compaction bug
Related JIRA: https://issues.apache.org/jira/browse/IOTDB-2737
Let compaction module use id table to find schema by SHA256 ID
Related JIRA: https://issues.apache.org/jira/browse/IOTDB-2741
Recover as much logs as we can in IDTable, rather than throw an exception when find log file is incomplete.
> [IOTDB-2737] Fix ID Table compaction bug

- .github/workflows/client-go.yml
- .github/workflows/client.yml
- .github/workflows/cluster.yml
- .github/workflows/e2e.yml
- .github/workflows/grafana-plugin.yml
- .github/workflows/greetings.yml
- .github/workflows/influxdb-protocol.yml
- .github/workflows/main-unix.yml
- .github/workflows/main-win.yml
- .github/workflows/sonar-coveralls.yml
Currently, each push of our pr will trigger a batch of CI actions, which takes too much resource. 
We refer to https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency and add the concurrency config to our CI.
With provided configs, only the actions triggered by our latest push on our pr will be executed and the actions triggered before will be cancelled. 
This has been tested on my own repository, illustrated in the following picture. The actions of different PR won't affect each other. Only the actions of latest push will cancel the previous actions of the same pr.
> Add Concurrency Control On CI

- pom.xml
Change the Windows Thrift download url to http://archive.apache.org/dist/thrift/0.14.1/thrift-0.14.1.exe .
> [To rel/0.12] Fix windows CI failed

- pom.xml
Change the Windows Thrift download url to http://archive.apache.org/dist/thrift/0.14.1/thrift-0.14.1.exe .
> [To rel/0.13] Fix windows CI failed

- server/src/main/java/org/apache/iotdb/db/metadata/mtree/MTree.java
- server/src/main/java/org/apache/iotdb/db/metadata/mtree/traverser/Traverser.java
- session/src/test/java/org/apache/iotdb/session/template/TemplateUT.java
This issue is fixed on 0.13 by a extra check on the related storage group of the target template.
On 0.14 or further version, this issue will be avoided by a refactored Traverser.
> [To rel/0.13][IOTDB-2759]Complete result of show template using or set on template

- server/src/main/java/org/apache/iotdb/db/engine/cache/TimeSeriesMetadataCache.java
- server/src/main/java/org/apache/iotdb/db/utils/FileLoaderUtils.java
After introducing FileTimeIndex, it does not filter for device. Therefore, when querying a non-exist device in TsFileSequenceReader, it should not throw exception that the device does not exist.
> [IOTDB-2775] Fix throwing exception when query non-exist device in TsFileSequenceReader

- integration/src/test/java/org/apache/iotdb/db/integration/IoTDBMaxTimeQueryIT.java
- server/src/main/java/org/apache/iotdb/db/query/reader/series/SeriesReader.java
`max_time` aggregation query will use desc read order to accelerate. But there exist a bug in SeriesReader while using desc order. In `unpackOneChunkMetaData` function of `SeriesReader`, we iterate all page readers of this chunk in asc order and add them into `seqPageReaders`'s tail while in asc order reader, however, we will also iterate page readers of this chunk in asc order and add them into `seqPageReaders`'s head while in desc order reader which is incorrect. 
For example, if we have chunkA which contains two pages(pageA-1 which has two time point [1, 2], pageA-2 which has two time point[3, 4]) and another chunkB which contains two pages(pageB-1 which has two time point [5, 6], pageA-2 which has two time point[7, 8]), if in desc order reader, we want them in `seqPageReaders` in this …
> [To rel/0.13] [IOTDB-2773] Fix overlapped data should be consumed first bug

- integration/src/test/java/org/apache/iotdb/db/integration/IoTDBMaxTimeQueryIT.java
- server/src/main/java/org/apache/iotdb/db/query/reader/series/SeriesReader.java
`max_time` aggregation query will use desc read order to accelerate. But there exist a bug in SeriesReader while using desc order. In `unpackOneChunkMetaData` function of `SeriesReader`, we iterate all page readers of this chunk in asc order and add them into `seqPageReaders`'s tail while in asc order reader, however, we will also iterate page readers of this chunk in asc order and add them into `seqPageReaders`'s head while in desc order reader which is incorrect. 
For example, if we have chunkA which contains two pages(pageA-1 which has two time point [1, 2], pageA-2 which has two time point[3, 4]) and another chunkB which contains two pages(pageB-1 which has two time point [5, 6], pageA-2 which has two time point[7, 8]), if in desc order reader, we want them in `seqPageReaders` in this …
> [IOTDB-2773] Fix overlapped data should be consumed first bug

- server/src/main/java/org/apache/iotdb/db/utils/SchemaUtils.java
Due to the mistake of solving conflicts, the support is missed. This PR fixes the bug that encoding FREQ does not support data type FLOAT and DOUBLE.
> Fix the bug that FREQ does not support DOUBLE.

- consensus/src/main/java/org/apache/iotdb/consensus/ratis/RequestMessage.java
- consensus/src/main/java/org/apache/iotdb/consensus/ratis/ResponseMessage.java
- consensus/src/main/java/org/apache/iotdb/consensus/ratis/Utils.java
- consensus/src/test/java/org/apache/iotdb/consensus/ratis/UtilsTest.java
In this PR, I fix two bugs:
1. Add volatile & synchronize to Response and Request to prevent parallel serialization race condition.
2. Use abbreviations to name Ratis Group, in case of the group-name length overflows
> Ratis Consensus Impl Bug Fix

- server/src/main/java/org/apache/iotdb/db/query/reader/series/SeriesReader.java
`max_time` aggregation query will use desc read order to accelerate. But there exist a bug in SeriesReader while using desc order. In `unpackOneChunkMetaData` function of `SeriesReader`, we iterate all page readers of this chunk in asc order and add them into `seqPageReaders`'s tail while in asc order reader, however, we will also iterate page readers of this chunk in asc order and add them into `seqPageReaders`'s head while in desc order reader which is incorrect. 
For example, if we have chunkA which contains two pages(pageA-1 which has two time point [1, 2], pageA-2 which has two time point[3, 4]) and another chunkB which contains two pages(pageB-1 which has two time point [5, 6], pageA-2 which has two time point[7, 8]), if in desc order reader, we want them in `seqPageReaders` in this …
> [To rel/0.12] [IOTDB-2773] Fix overlapped data should be consumed first bug

- confignode/src/main/java/org/apache/iotdb/confignode/conf/ConfigNodeConf.java
- confignode/src/main/java/org/apache/iotdb/confignode/conf/ConfigNodeDescriptor.java
- confignode/src/test/java/org/apache/iotdb/confignode/consensus/RatisConsensusDemo.java
- consensus/src/main/java/org/apache/iotdb/consensus/common/ConsensusType.java
Demo code for showing integration of ConfigNode and ratis-consensus.
- ratisConsensusDemo: Shows that ConfigNode can register Datanodes and set StorageGroups using the ratis consensus protocol.
> Demo for integration of ConfigNode and ratis-consensus

- server/src/test/java/org/apache/iotdb/db/mpp/operator/LimitOperatorTest.java
- tsfile/src/main/java/org/apache/iotdb/tsfile/read/common/block/column/ColumnBuilderStatus.java
`jacoco` in `maven` which is used to calculate code coverage will add some synthetic fields in class, you can see in the following picture:
the last two fields: boolean[] and `$jacocoData` is not defined in my class, so when I iterate the fields in this class using `Class<?>.getDeclaredFields()` method, we will get this unexpected one.
>  Fix NoClassDefFound CI error

- server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfigCheck.java
Currently after upgrading from 0.12 or 0.13 to newest version, the system.properties file is updated, but the `iotdb_version` still remains the same. It may cause the future upgrading incorrectly.
> [IOTDB-2828] Update iotdb_version after upgrading finished

- consensus/src/main/java/org/apache/iotdb/consensus/IConsensus.java
- consensus/src/main/java/org/apache/iotdb/consensus/ratis/RatisConsensus.java
- consensus/src/main/java/org/apache/iotdb/consensus/ratis/Utils.java
- consensus/src/main/java/org/apache/iotdb/consensus/standalone/StandAloneConsensus.java
- consensus/src/test/java/org/apache/iotdb/consensus/ratis/RatisConsensusTest.java
In this PR, I add a new interface method `isLeaderOf` to IConsensus to determine whether current peer is the leader of a given consensus group.
Also, I fixed a bug related to previous transferLeader method
Ratis assign every peer a default priority 0. When transferring leadership, it won't allow any peer with (peer.priority <= currentLeader.priority) to become the new leader. Thus before call transferLeader, we should first upgrade newLeader's priority and degrade every others.
> Add isLeaderOf to Consensus

- integration/src/test/java/org/apache/iotdb/db/integration/versionadaption/IoTDBDDLVersionAdaptionIT.java
- server/src/main/java/org/apache/iotdb/db/metadata/LocalConfigManager.java
- server/src/main/java/org/apache/iotdb/db/metadata/LocalSchemaProcessor.java
- server/src/main/java/org/apache/iotdb/db/metadata/mtree/MTreeAboveSG.java
- server/src/main/java/org/apache/iotdb/db/metadata/mtree/MTreeBelowSG.java
- server/src/main/java/org/apache/iotdb/db/metadata/mtree/traverser/Traverser.java
- server/src/main/java/org/apache/iotdb/db/metadata/mtree/traverser/counter/MNodeLevelCounter.java
- server/src/main/java/org/apache/iotdb/db/metadata/schemaregion/SchemaRegion.java
- server/src/main/java/org/apache/iotdb/db/metadata/storagegroup/IStorageGroupSchemaManager.java
- server/src/main/java/org/apache/iotdb/db/metadata/storagegroup/StorageGroupSchemaManager.java
- server/src/test/java/org/apache/iotdb/db/metadata/SchemaBasicTest.java
- server/src/test/java/org/apache/iotdb/db/metadata/mtree/MTreeAboveSGTest.java
- server/src/test/java/org/apache/iotdb/db/metadata/mtree/MTreeBelowSGTest.java
When counting nodes above sg, the node cannot be counted correctly because the existing method in MTreeBelowSG won't check the node above sg and also mistaken the level comparision.
Enable MTreeBelowSG to check the node above sg, remove duplicated nodes in SchemaProcessor and finally return the num of matched nodes.
> [IOTDB-2825] Fix count node by level

- consensus/src/test/java/org/apache/iotdb/consensus/ratis/RatisConsensusTest.java
Fix bugs in current RatisConsensusTest:
1. Use CountDownLatch to wait for all writes complete instead of shutting down executor-service after timeout. 
2. Read from leader instead of a random picked peer.
> fix bug in ratis consensus test

- server/src/main/java/org/apache/iotdb/db/metadata/LocalConfigManager.java
- server/src/main/java/org/apache/iotdb/db/metadata/template/Template.java
- server/src/main/java/org/apache/iotdb/db/metadata/template/TemplateManager.java
- server/src/test/java/org/apache/iotdb/db/metadata/TemplateTest.java
In Template, we mark which storage group this template is set, this is act as a cache to accelerate related traverse.
When a storage group is deleted, we need to discard this cache in related templates.
> [IOTDB-2826]Unmark storage group among templates when deleted

- tsfile/src/test/java/org/apache/iotdb/tsfile/read/TsFileReaderTest.java
- tsfile/src/test/java/org/apache/iotdb/tsfile/utils/TsFileGeneratorForTest.java
Solution: setGroupSizeInByte(oldGroupSizeInByte) and setMaxNumberOfPointsInPage(oldPointNumInPage) after modifing it in test.
> [IOTDB-2851]ChunkReaderTest failed in CI

- server/src/main/java/org/apache/iotdb/db/utils/EnvironmentUtils.java
- server/src/test/java/org/apache/iotdb/db/engine/modification/DeletionFileNodeTest.java
https://github.com/apache/iotdb/runs/5852474920?check_suite_focus=true
The default wal buffer size `16MB` is too large in CI env, and may cause OOM error. Therefore change the size to `4MB` to fix it.
<hr>
This PR has:
<hr>
> [IOTDB-2855] Fix DeletionFileNodeTest error

- client-py/README.md
- client-py/SessionAlignedTimeseriesExample.py
- client-py/SessionExample.py
- client-py/iotdb/Session.py
- client-py/iotdb/utils/NumpyTablet.py
- client-py/iotdb/utils/Tablet.py
- client-py/tests/tablet_performance_comparison.py
- client-py/tests/test_aligned_timeseries.py
- client-py/tests/test_session.py
- docs/UserGuide/API/Programming-Python-Native-API.md
- docs/zh/UserGuide/API/Programming-Python-Native-API.md
- testcontainer/src/tool/parser.py
Add check and sort for NumpyTablet to make sure timestamps are ordered and format code with `black .`
<hr>
This PR has:
<hr>
> [IoTDB-2837] Add check and sort for NumpyTablet to make sure timestamps are ordered

- client-py/iotdb/utils/IoTDBRpcDataSet.py
- client-py/iotdb/utils/Tablet.py
- client-py/tests/test_tablet.py
- client-py/tests/test_todf.py
IOTDB-2859
The serialization method of nullable tablet in python client is incorrect.
> [IOTDB-2859] Fix python tablet with None value is incorrect

- server/src/main/java/org/apache/iotdb/db/metadata/MManager.java
- server/src/main/java/org/apache/iotdb/db/metadata/template/Template.java
- server/src/test/java/org/apache/iotdb/db/metadata/TemplateTest.java
In Template, we mark which storage group this template is set, this is act as a cache to accelerate related traverse.
When a storage group is deleted, we need to discard this cache in related templates.
> [To rel/0.13][IOTDB-2826]Unmark storage group among templates when deleted

- client-py/README.md
- client-py/SessionExample.py
- client-py/iotdb/utils/IoTDBConstants.py
- client-py/iotdb/utils/NumpyTablet.py
- client-py/tests/test_numpy_tablet.py
- docs/UserGuide/API/Programming-Python-Native-API.md
- docs/zh/UserGuide/API/Programming-Python-Native-API.md
NumpyTablet only supports the big-endian type of timestamps and values.
It will be better if we can check endian type of the input from users, and convert it to big-endian if the endian type is wrong.
> [IOTDB-2838] Check and auto correct endian type for NumpyTablet

- server/src/main/java/org/apache/iotdb/db/mpp/execution/FragmentInstanceManager.java
- server/src/main/java/org/apache/iotdb/db/mpp/operator/Operator.java
- server/src/main/java/org/apache/iotdb/db/mpp/operator/process/LimitOperator.java
- server/src/main/java/org/apache/iotdb/db/mpp/operator/process/TimeJoinOperator.java
- server/src/main/java/org/apache/iotdb/db/mpp/operator/source/SeriesScanOperator.java
- server/src/main/java/org/apache/iotdb/db/mpp/sql/planner/LocalExecutionPlanner.java
- server/src/test/java/org/apache/iotdb/db/mpp/operator/LimitOperatorTest.java
- server/src/test/java/org/apache/iotdb/db/mpp/operator/SeriesScanOperatorTest.java
- server/src/test/java/org/apache/iotdb/db/mpp/operator/TimeJoinOperatorTest.java
1. Construct SinkHandle in LocalExecutionPlanner
2. Remove the IOExecption in next and hasNext method of Operator
> [IOTDB-2858] Construct SinkHandle in LocalExecutionPlanner and remove the IOExecption in Operator

- integration/src/test/java/org/apache/iotdb/db/integration/aligned/IoTDBInsertAlignedValuesIT.java
- server/src/main/java/org/apache/iotdb/db/utils/datastructure/AlignedTVList.java
When extending column in AlignedTVList, we need to supply bitmaps for the extending column. There is a bug causes the last supplying bitmap doesn't be marked, which will cause NPE when the extending column is TEXT dataType and execute flushing. Finally the server will turn to read-only because of it.
> [IOTDB-2864] Fix Read-only occurred when insert Text values to aligned timeseries

- integration/src/test/java/org/apache/iotdb/db/integration/aggregation/IoTDBAggregationIT.java
- service-rpc/src/main/java/org/apache/iotdb/rpc/IoTDBRpcDataSet.java
When the query statement is executed with jdbc, when the last column of the previous row is empty, the next row last Read Was Null will still be true, resulting in the Timestamp column not displaying time information
> Modify the jdbc query time column to be empty

- consensus/src/main/java/org/apache/iotdb/consensus/IConsensus.java
- consensus/src/main/java/org/apache/iotdb/consensus/ratis/RatisConsensus.java
- consensus/src/main/java/org/apache/iotdb/consensus/ratis/Utils.java
- consensus/src/main/java/org/apache/iotdb/consensus/standalone/StandAloneConsensus.java
- consensus/src/test/java/org/apache/iotdb/consensus/ratis/RatisConsensusTest.java
Currently `IConsensus::isLeader` is not enough for application scenarios. In this PR I add getLeader interface, which can return the POSSIBLE leader peer of a ConsensusGroup.
> [IOTDB-2878] Add getLeader interface to IConsensus

- confignode/src/main/java/org/apache/iotdb/confignode/consensus/response/DataNodeConfigurationDataSet.java
- confignode/src/main/java/org/apache/iotdb/confignode/consensus/response/DataNodesInfoDataSet.java
- confignode/src/main/java/org/apache/iotdb/confignode/consensus/response/DataPartitionDataSet.java
- confignode/src/main/java/org/apache/iotdb/confignode/consensus/response/StorageGroupSchemaDataSet.java
- confignode/src/main/java/org/apache/iotdb/confignode/manager/ConfigManager.java
- confignode/src/main/java/org/apache/iotdb/confignode/manager/ConsensusManager.java
- confignode/src/main/java/org/apache/iotdb/confignode/manager/DataNodeManager.java
- confignode/src/main/java/org/apache/iotdb/confignode/service/thrift/server/ConfigNodeRPCServerProcessor.java
- confignode/src/test/java/org/apache/iotdb/confignode/consensus/RatisConsensusDemo.java
- confignode/src/test/java/org/apache/iotdb/confignode/service/thrift/server/ConfigNodeRPCServerProcessorTest.java
The ConfigNode only accept RPC requests when it's the leader of the ConfigNodeGroup. And return TSStatusCode.NEED_REDIRECTION otherwise.
> [IOTDB-2867] Response leader redirect when the current ConfigNode is not leader 

- integration/src/test/java/org/apache/iotdb/db/integration/IoTDBDeleteStorageGroupIT.java
- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/DataRegion.java
- server/src/main/java/org/apache/iotdb/db/qp/executor/PlanExecutor.java
In 0.13 and master, we add BloomFilterCache, but we forgot to add clear cache for it in `operateClearCache`.
> [IOTDB-2910] Fix Count aggregate is not right after delete sg bug

- integration/src/test/java/org/apache/iotdb/db/integration/IoTDBMetadataFetchIT.java
- server/src/main/java/org/apache/iotdb/db/metadata/lastCache/LastCacheManager.java
When trying to get last value during show timeseries, ```PartialPath``` rather than ```MeasurementPath``` was passed, which results in the failure of query.
Replace ```node.getPartialPath``` with ```node.getMeasurementPath```.
> [To rel/0.13][IOTDB-2903] Fix last value fetch failure during show timesereis

- server/src/assembly/resources/conf/iotdb-engine.properties
- server/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/CompactionScheduler.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/constant/CrossCompactionPerformer.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/constant/CrossCompactionSelector.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/constant/InnerSeqCompactionPerformer.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/constant/InnerSequenceCompactionSelector.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/constant/InnerUnseqCompactionPerformer.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/constant/InnerUnsequenceCompactionSelector.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/cross/CrossSpaceCompactionTask.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/inner/InnerSpaceCompactionTask.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/log/TsFileIdentifier.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/performer/impl/ReadChunkCompactionPerformer.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/performer/impl/ReadPointCompactionPerformer.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/task/AbstractCompactionTask.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/cross/CrossSpaceCompactionTest.java
See [IOTDB-2896](https://issues.apache.org/jira/projects/IOTDB/issues/IOTDB-2896?filter=myopenissues).
The reason for this bug is as following, in [pr-5437](https://github.com/apache/iotdb/pull/5437) we refactor the compaction frame work, and separate the compaction configuration _inner_space_compaction_strategy_ and _cross_space_compaction_strategy_ into multiple configuration items, which enables us to configurate compaction more flexiblely. But in `CrossSpaceCompactionSelector` and `InnerSequenceCompactionSelector`, we forgot to modify the code that checks the configuration items, thus causing errors during configuration checks.
> [IOTDB-2896] Fix warning of illegal cross compaction strategy

- server/src/main/java/org/apache/iotdb/db/metadata/logfile/MLogTxtWriter.java
- server/src/main/java/org/apache/iotdb/db/service/IoTDBShutdownHook.java
When kill system, the hook will be invoke before killing the mlog force thread and the npe was produced when the thread invoke a cleared schemaRegion
Shutdown the thread in hook before region clear.
rename the plan name and fix the stream collect
> [IOTDB-2914][IOTDB-2915]Fix npe of MLog force during killing system & Fix MLogTxtWriter while parsing CreateAlignedTimeseriesPlan

- server/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java
The reason is same as [pr-5503](https://github.com/apache/iotdb/pull/5503)
> [IOTDB-2896] Fix warning of illegal seq compaction performer

- server/src/main/java/org/apache/iotdb/db/metadata/logfile/MLogTxtWriter.java
MLogTxtWriter will serialize wrong plan name and schema while paring  CreateAlignedTimeseriesPlan
> [To rel/0.13][IOTDB-2915]MLogTxtWriter error while parsing CreateAlignedTimeseriesPlan

- server/src/test/java/org/apache/iotdb/db/wal/node/WALNodeTest.java
See JIRA: https://issues.apache.org/jira/browse/IOTDB-2921
> [IOTDB-2921] Fix WALNodeTest of concurrently accessing ArrayList

- server/src/main/java/org/apache/iotdb/db/engine/compaction/cross/rewrite/selector/RewriteCompactionFileSelector.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/cross/RewriteCompactionFileSelectorTest.java
When the total number of selected files exceeds the parameter `maxCrossCompactionCandidateFileNum`, no files will be selected, resulting in cross-space compaction never selecting files. At least one batch of files should be selected for compacting.
> [IOTDB-2861] Improve Cross compaction selector file number restrict

- cluster/src/main/java/org/apache/iotdb/cluster/log/snapshot/FileSnapshot.java
- cluster/src/test/java/org/apache/iotdb/cluster/log/snapshot/FileSnapshotTest.java
- server/src/main/java/org/apache/iotdb/db/engine/StorageEngine.java
- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/DataRegion.java
- server/src/main/java/org/apache/iotdb/db/qp/executor/PlanExecutor.java
- server/src/main/java/org/apache/iotdb/db/sync/receiver/load/TsFileLoader.java
The reason for this error message is that the system deletes the file when it is loaded successfully. So `commit()` function in PipeDataQueue can not find tsfile that has been loaded to system.
I add a parameters to config whether to delete file after loading.
* If true, use move
* If false, create hardlink
> [IOTDB-2906] Commit pipe data serial number error, Can not find tsfile

- server/src/main/java/org/apache/iotdb/db/engine/compaction/inner/utils/MultiTsFileDeviceIterator.java
- server/src/main/java/org/apache/iotdb/db/metadata/LocalConfigNode.java
- server/src/main/java/org/apache/iotdb/db/service/IoTDBShutdownHook.java
See [IOTDB-2922](https://issues.apache.org/jira/browse/IOTDB-2922).
The reason for this bug is that, when compacting with files that contains zero device, the variable `currentDevice` in `TsFileDeviceIterator` is initialized as null, and if we visit it, NPE will occurs.
> [IOTDB-2922] Fix NPE when compacting with files that contains zero device

- server/src/main/java/org/apache/iotdb/db/query/udf/core/layer/MultiInputColumnIntermediateLayer.java
- server/src/main/java/org/apache/iotdb/db/query/udf/core/layer/SingleInputColumnMultiReferenceIntermediateLayer.java
- server/src/main/java/org/apache/iotdb/db/query/udf/core/layer/SingleInputColumnSingleReferenceIntermediateLayer.java
See IOTDB-2924 and #5520 for more detail.
(cherry picked from commit 90cd903f9bfd6b3f6c15f4e3674cabfea35a5058)
> [To rel/0.13][IOTDB-2924] UDF Framework: index overflow while iterating sliding windows (#5555)

- server/src/assembly/resources/conf/iotdb-engine.properties
- server/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java
- server/src/main/java/org/apache/iotdb/db/service/DataNode.java
We don't mpp_mode property because if we start from `DataNode` Class, it must be mpp mode.
> Remove mpp_mode property in iotdb-engine.properties

- cluster/src/main/java/org/apache/iotdb/cluster/coordinator/Coordinator.java
- cluster/src/main/java/org/apache/iotdb/cluster/server/member/DataGroupMember.java
- cluster/src/main/java/org/apache/iotdb/cluster/server/member/MetaGroupMember.java
- cluster/src/main/java/org/apache/iotdb/cluster/server/service/BaseAsyncService.java
- cluster/src/main/java/org/apache/iotdb/cluster/utils/StatusUtils.java
- confignode/src/main/java/org/apache/iotdb/confignode/consensus/response/DataNodesInfoDataSet.java
- confignode/src/test/java/org/apache/iotdb/confignode/consensus/RatisConsensusDemo.java
- confignode/src/test/java/org/apache/iotdb/confignode/manager/ConfigManagerManualTest.java
- confignode/src/test/java/org/apache/iotdb/confignode/service/thrift/server/ConfigNodeRPCServerProcessorTest.java
- consensus/src/main/java/org/apache/iotdb/consensus/ratis/RatisConsensus.java
- influxdb-protocol/src/main/java/org/apache/iotdb/influxdb/protocol/dto/SessionPoint.java
- node-commons/src/main/java/org/apache/iotdb/commons/partition/RegionReplicaSet.java
- server/src/main/java/org/apache/iotdb/db/query/dataset/AlignByDeviceDataSet.java
- server/src/main/java/org/apache/iotdb/db/service/DataNode.java
- server/src/main/java/org/apache/iotdb/db/service/thrift/impl/InternalServiceImpl.java
- server/src/main/java/org/apache/iotdb/db/service/thrift/impl/TSServiceImpl.java
- service-rpc/src/main/java/org/apache/iotdb/rpc/RedirectException.java
- service-rpc/src/main/java/org/apache/iotdb/rpc/RpcUtils.java
- session/src/main/java/org/apache/iotdb/session/Session.java
- session/src/main/java/org/apache/iotdb/session/SessionConnection.java
- session/src/main/java/org/apache/iotdb/session/util/SessionUtils.java
- session/src/test/java/org/apache/iotdb/session/SessionCacheLeaderUT.java
- thrift-confignode/src/main/thrift/confignode.thrift
- thrift/src/main/thrift/common.thrift
It is quite confusing when there are 2 classes named "EndPoint". They are org.apache.iotdb.commons.cluster.EndPoint and org.apache.iotdb.common.rpc.thrift.EndPoint.
By convention, the name of thrift generated classes should start with "T", so I renamed the org.apache.iotdb.common.rpc.thrift.EndPoint to org.apache.iotdb.common.rpc.thrift.TEndPoint.
> Rename thrift endpoint

- influxdb-protocol/src/main/java/org/apache/iotdb/influxdb/session/InfluxDBSession.java
- influxdb-protocol/src/test/java/org/apache/iotdb/influxdb/integration/IoTDBInfluxDBIT.java
- server/src/main/java/org/apache/iotdb/db/protocol/influxdb/handler/QueryHandler.java
- server/src/main/java/org/apache/iotdb/db/protocol/influxdb/util/JacksonUtils.java
- server/src/main/java/org/apache/iotdb/db/protocol/influxdb/util/StringUtils.java
see : https://issues.apache.org/jira/browse/IOTDB-2954
- Use Jackson instead of Gosn, because Gosn will convert all number type in the object into double type
- Fixed a problem where the value of a single quote could not be resolved
> [IOTDB-2954] fix influxdb protocol bug found in benchmark test of verificationQueryMode

- server/src/main/java/org/apache/iotdb/db/engine/compaction/CompactionTaskManager.java
See [IOTDB-2943](https://issues.apache.org/jira/projects/IOTDB/issues/IOTDB-2943?filter=allopenissues).
The reason for this bug is that, the `awaitTerminate` function in `CompactionTaskManager` is synchronized, which cause a deadlock with `removeRunningTaskFuture`.
> [IOTDB-2943] Fix cannot use stop-server.sh to stop IoTDB

- server/src/main/java/org/apache/iotdb/db/mpp/execution/config/AuthorizerConfigTask.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/config/ConfigExecution.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/config/ConfigTaskResult.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/config/IConfigTask.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/config/SetStorageGroupTask.java
- server/src/test/java/org/apache/iotdb/db/mpp/execution/ConfigExecutionTest.java
Some execution which need to be run in ConfigNode will have resultSet such as `show storage group`. We need to make the ConfigExecution has the ability of returning result set after executing.
Change the body of `Future` of IConfigTask from `Void` to `ConfigTaskResult`. And `ConfigTaskResult` will contains two params: 1. the status code; 2. the result set if it has.
> Change the result of ConfigExecution from Void to TsBlock

- server/src/main/java/org/apache/iotdb/db/metadata/upgrade/MetadataUpgrader.java
- server/src/test/java/org/apache/iotdb/db/metadata/upgrade/MetadataUpgradeTest.java
After this fix, the `MetadataUpgrader` will not throw any exceptions if recovering one plan from snapshot or mlog.bin failed.
I think it's better to tell DBAs to backup the `system` directory before upgrading to new version.
> [IOTDB-2965] Skip failed mlog and snapshot items when upgrading happens

- server/src/main/java/org/apache/iotdb/db/metadata/LocalConfigNode.java
- server/src/main/java/org/apache/iotdb/db/metadata/LocalSchemaPartitionTable.java
- server/src/main/java/org/apache/iotdb/db/metadata/schemaregion/SchemaEngine.java
There are three components involved in timeseries creation: storage group, schemaRegionId, and schemaRegion.
The three components are managed respectively by storageGroupSchemaManager, localSchemaPartitionTable and SchemaEngine.
The creation of each component are separated, while the timeseries creation requires all the three components be prepared well atomically.
Strengthen the auto create method to cover existence check of all the three component.
Refactor the recover logic of localSchemaParitionTable. The SchemaEngine now is enabled to check the local schema partition info while recovering, and the localSchemaParitionTable will be init based on the info returned by SchemaEngine.
> [IOTDB-2932]Fix localPartitionTable concurrent bug

- server/src/assembly/resources/tools/schema/SchemaFileSketcher.sh
- server/src/assembly/resources/tools/schema/mLogParser.sh
Since the path of the class to sketch SchemaFile and MLog has been changed to org.apache.iotdb.db.tools.schema from org.apache.iotdb.db.tools.mlog, corresponding script should modify the classpath parameter as well.
> Fix class path in SchemaFileSketcher.sh and mLogParser.sh

- server/src/test/java/org/apache/iotdb/db/mpp/execution/ConfigExecutionTest.java
Before this fix, the test `exceptionAfterInvokeGetStatusTest` may fail() in some scenario. It is because this UT simulates a multi-thread scenario which may not throw InterruptedException.
> Fix the UT of ConfigExecution which may block CI

- server/src/main/java/org/apache/iotdb/db/qp/executor/PlanExecutor.java
- server/src/main/java/org/apache/iotdb/db/tools/TsFileSketchTool.java
- tsfile/src/main/java/org/apache/iotdb/tsfile/read/TsFileSequenceReader.java
- tsfile/src/main/java/org/apache/iotdb/tsfile/write/TsFileWriter.java
- tsfile/src/test/java/org/apache/iotdb/tsfile/read/TsFileSequenceReaderTest.java
See details in [IOTDB-2835](https://issues.apache.org/jira/browse/IOTDB-2835).
Solution: skip empty page in aligned chunk in selfcheck method.
> [IOTDB-2835]Fix empty page in selfcheck method of TsFileSequenceReader

- server/src/main/java/org/apache/iotdb/db/mpp/common/schematree/SchemaTreeVisitor.java
- server/src/test/java/org/apache/iotdb/db/mpp/common/schematree/SchemaTreeTest.java
When matching `**.xx` with a `node`, we need to push two times. 
1. One push for `xx` and `node.children()`; 
2. the other push for `**.xx` and `node.children()`.
Before this change, if the `xx` cannot match `node.children`, the second push is lost. This PR fix this scenario.
> Fix the bug when matching pattern tree using multi-wildcard

- server/src/main/java/org/apache/iotdb/db/mpp/buffer/SourceHandle.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/QueryExecution.java
A scenario will lead to the invoker wait permanently when using SourceHandle. That is, the SourceHandle's EOS has been received while the GetDataBlockTask is still in progress. And then, the GetDataBlockTask throws exception. If the invoker is waiting the `blocked` future it will be blocked permanently here.
Cancel the `blocked` if the GetDataBlockTask threw exception
> Add block cancel when GetBlockTask throws exception

- procedure/src/main/java/org/apache/iotdb/procedure/ProcedureExecutor.java
- procedure/src/test/java/org/apache/iotdb/procedure/TestProcedureBase.java
- procedure/src/test/java/org/apache/iotdb/procedure/store/TestProcedureStore.java
Test directory clean may failed occasionally at _After()_ method. Ensure it at last.
> [IOTDB-2880] Fix NPE occured in ci test

- server/src/main/java/org/apache/iotdb/db/metadata/mtree/store/disk/CachedMNodeContainer.java
The ```CachedMNodeContainer.putIfAbsent``` is not thread-safe, which may results in subTree loss or unexpected replacement when creating timeseries concurrently.
Rewrite ```CachedMNodeContainer.putIfAbsent``` and make it synchronized.
> [IOTDB-2950]Fix concurrent bug of CachedMNodeContainer.putIfAbsent

- server/src/main/java/org/apache/iotdb/db/mpp/execution/Coordinator.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/FragmentInstanceContext.java
- server/src/main/java/org/apache/iotdb/db/service/thrift/impl/DataNodeTSIServiceImpl.java
1. When the FragmentInstance is not complete, its `endTime` is not set. It will lead to NPE when parse it to `long` when fetching FragmentInstance status.
2. Fix an issue that the coordinator cannot cleanup QueryExecution if the QueryExecution throws exception when constructing, which will lead to client stuck.
> Fix the issue that EndTime in FragmentInstanceContext is not set

- server/src/main/java/org/apache/iotdb/db/metadata/schemaregion/SchemaEngine.java
In Mac os, there are hidden dirs or files, named with ```.DS_Store``` suffix. When recover schemaEngine and such dirs or files is scanned, NumberFormatException will be thrown.
When encountering NumberFormatException, ignore this and skip this dir, since a schemaRegion dir is named after a numeric number.
> Filter non schemaRegionDir

- server/src/main/java/org/apache/iotdb/db/metadata/mtree/IMTreeBelowSG.java
- server/src/main/java/org/apache/iotdb/db/metadata/mtree/MTreeBelowSGCachedImpl.java
- server/src/main/java/org/apache/iotdb/db/metadata/mtree/MTreeBelowSGMemoryImpl.java
- server/src/main/java/org/apache/iotdb/db/metadata/mtree/store/disk/cache/CacheManager.java
- server/src/main/java/org/apache/iotdb/db/metadata/schemaregion/SchemaRegionMemoryImpl.java
- server/src/main/java/org/apache/iotdb/db/metadata/schemaregion/SchemaRegionSchemaFileImpl.java
After a thread unPin a node, it should check the cache status of the node. If the node is now not Pinned, then its parent should be unPin once, which means one of the children is not pinned any more. However, the operation and check should be synchronized, otherwise the change may result in multi threads get wrong cache status and do extra unpin, which may result in negative semaphore value.
The old implementation of template check during insert takes low performance and is hard to understand. Thus the implementation is rewritten.
> [IOTDB-2930]Fix concurrent UnPin bug & Improve template implementation

- server/src/main/java/org/apache/iotdb/db/metadata/mtree/store/disk/schemafile/SchemaFile.java
Before this PR, SchemaFileSketcher will delete an empty .pst file since it is useless. Then we found it is confusing for users, so now it will leave the empty file as it was.
> [IOTDB-2995]SchemaFileSketcher will not delete empty .pst now

- server/src/main/java/org/apache/iotdb/db/metadata/mtree/store/disk/schemafile/SchemaFile.java
- server/src/test/java/org/apache/iotdb/db/metadata/mtree/schemafile/SchemaFileTest.java
Before this pull request, schema file stores all pages in a map, and only flushes dirty pages if the cache had no more space for new pages. 
With the cache map of size 1, a dirty page may be evicted from the cache during a method which modifies multi pages (like creating a new multi-page segment) and this makes a exception unexpected.
Now, schema file uses an extra map called dirtyPages to collect all pages modified during write or delete method within the file instance, and flushes will occur before the method ends.
> Fix schema file with cache of size 1

- example/tsfile/src/main/java/org/apache/iotdb/tsfile/TsFileSequenceRead.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/CompactionTaskManager.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/inner/InnerCompactionTest.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/inner/ReadChunkCompactionPerformerOldTest.java
**Bug Description**
See details in [IOTDB-2966](https://issues.apache.org/jira/browse/IOTDB-2966). 
**Reason**
(1) the created unseq file has the same name with the first seq file.
(2) the main test thread occupies the object lock of the CompactTaskManager, causing the compaction sub thread to be blocked.
**Solution**
(1) create different name of unseq file.
(2) use obj.wait() to release lock instead of Thread.sleep().
> [IOTDB-2966]fix CompactionTaskManagerTest CI

- server/src/main/java/org/apache/iotdb/db/mpp/buffer/DataBlockManager.java
- server/src/main/java/org/apache/iotdb/db/mpp/buffer/IDataBlockManager.java
- server/src/main/java/org/apache/iotdb/db/mpp/buffer/IDataBlockManagerCallback.java
- server/src/main/java/org/apache/iotdb/db/mpp/buffer/ISinkHandle.java
- server/src/main/java/org/apache/iotdb/db/mpp/buffer/ISourceHandle.java
- server/src/main/java/org/apache/iotdb/db/mpp/buffer/SinkHandle.java
- server/src/main/java/org/apache/iotdb/db/mpp/buffer/SourceHandle.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/QueryExecution.java
- server/src/main/java/org/apache/iotdb/db/mpp/operator/source/ExchangeOperator.java
- server/src/main/java/org/apache/iotdb/db/mpp/sql/planner/LocalExecutionPlanner.java
- server/src/test/java/org/apache/iotdb/db/mpp/buffer/SinkHandleTest.java
- server/src/test/java/org/apache/iotdb/db/mpp/buffer/SourceHandleTest.java
- server/src/test/java/org/apache/iotdb/db/mpp/buffer/StubSinkHandle.java
Add `SourceHandleListener#onFailure`. The method will be called when fatal exceptions happen during data transmission.
> Optimize source handle error handling

- server/src/main/java/org/apache/iotdb/db/mpp/buffer/SinkHandle.java
In some scenario, the FragmentInstance's status is always `FLUSHING`, although the corresponding query is finished. It is because there is a corner case in SinkHandle which lead to the `onFinish()` method cannot be invoked.
The corner case is:
There are two conditions to be satisfied that the FragmentInstance's status will be set to FINISHED:
1. The `noMoreTsBlocks` is true
2. The cached TsBlocks has been sent.
And these two conditions will be checked every time the `acknowledge event` is received in SinkHandle; the `noMoreTsBlocks` will be set to true when the `close()` is invoked.
Before this change, if the last `acknowledge event` is received but the `close()` is still not invoked, we will lost the chance to set the FragmentInstance's status to FINISHED. 
Fix the issue by adding …
> Fix the issue that FragmentInstance's status cannot be set to FINISHED

- cluster/src/main/java/org/apache/iotdb/cluster/query/reader/ClusterReaderFactory.java
- server/src/main/java/org/apache/iotdb/db/engine/memtable/AbstractMemTable.java
- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/TsFileProcessor.java
- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/TsFileResource.java
- server/src/main/java/org/apache/iotdb/db/metadata/path/AlignedPath.java
- server/src/main/java/org/apache/iotdb/db/metadata/path/MeasurementPath.java
- server/src/main/java/org/apache/iotdb/db/metadata/path/PartialPath.java
- server/src/main/java/org/apache/iotdb/db/metadata/utils/ResourceByPathUtils.java
- server/src/main/java/org/apache/iotdb/db/query/executor/LastQueryExecutor.java
- server/src/main/java/org/apache/iotdb/db/query/reader/series/SeriesAggregateReader.java
- server/src/main/java/org/apache/iotdb/db/query/reader/series/SeriesRawDataBatchReader.java
- server/src/main/java/org/apache/iotdb/db/query/reader/series/SeriesReaderByTimestamp.java
see [IOTDB-3008](https://issues.apache.org/jira/projects/IOTDB/issues/IOTDB-3008)
When moving the `PartialPath` to the `Commons` module, we need to extract the server-related interfaces from the `Partial Path` first.
I'll move the `PartialPath` to the `node-commons` directory when work on the new architecture is finished.
> [IOTDB-3008] move partial path to commons

- node-commons/src/main/java/org/apache/iotdb/commons/client/ClientFactoryProperty.java
- node-commons/src/main/java/org/apache/iotdb/commons/client/ClientPoolProperty.java
- node-commons/src/test/java/org/apache/iotdb/commons/ClientManagerTest.java
Sometimes the CI is unstable, and calculating the time using physical time may cause the CI to fail
> Use logical clock to fix clientManager test

- cluster/src/main/java/org/apache/iotdb/cluster/server/ClusterRPCService.java
- cluster/src/main/java/org/apache/iotdb/cluster/server/clusterinfo/ClusterInfoServer.java
- cluster/src/main/java/org/apache/iotdb/cluster/server/raft/DataRaftHeartBeatService.java
- cluster/src/main/java/org/apache/iotdb/cluster/server/raft/DataRaftService.java
- cluster/src/main/java/org/apache/iotdb/cluster/server/raft/MetaRaftHeartBeatService.java
- cluster/src/main/java/org/apache/iotdb/cluster/server/raft/MetaRaftService.java
- confignode/src/main/java/org/apache/iotdb/confignode/service/ConfigNode.java
- confignode/src/main/java/org/apache/iotdb/confignode/service/ConfigNodeCommandLine.java
- confignode/src/main/java/org/apache/iotdb/confignode/service/thrift/ConfigNodeRPCService.java
- confignode/src/test/java/org/apache/iotdb/confignode/utils/ConfigNodeEnvironmentUtils.java
- node-commons/src/main/java/org/apache/iotdb/commons/service/ThriftService.java
- procedure/src/main/java/org/apache/iotdb/procedure/service/ProcedureServer.java
- server/src/main/java/org/apache/iotdb/db/mpp/buffer/DataBlockService.java
- server/src/main/java/org/apache/iotdb/db/service/InfluxDBRPCService.java
- server/src/main/java/org/apache/iotdb/db/service/InternalService.java
- server/src/main/java/org/apache/iotdb/db/service/RPCService.java
- server/src/main/java/org/apache/iotdb/db/sync/transport/server/TransportServerManager.java
As have discussed, singleton pattern is making code inflexible, hard to make UI and IT tests. We shouldn't use singleton pattern too much. 
I'd like to propose several PRs to remove the singleton pattern for most of singleton pattern implementations before the `getInstance()` are widely used. This one is the first.
> [IOTDB-3012][De-Singleton-1] remove singleton pattern for some classes

- .github/workflows/client-cpp.yml
node commons tests should not be in C++ client CI. 
https://github.com/apache/iotdb/runs/6178041177?check_suite_focus=true
> Skip node commons test in C++ client CI

- server/src/assembly/resources/conf/iotdb-engine.properties
- server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
- server/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java
- server/src/main/java/org/apache/iotdb/db/mpp/sql/analyze/ClusterPartitionFetcher.java
- server/src/main/java/org/apache/iotdb/db/mpp/sql/analyze/FakePartitionFetcherImpl.java
- server/src/main/java/org/apache/iotdb/db/mpp/sql/analyze/IPartitionFetcher.java
- server/src/main/java/org/apache/iotdb/db/mpp/sql/analyze/StandalonePartitionFetcher.java
Add partition cache in clusterParitionFetcher.
StorageGroupCache: storageGroupName
SchemaPartitionCache: device -> TRegionReplicaSet.
DataPartitionCache: TSeriesPartitionSlot, TTimePartitionSlot -> List
Notice: if there are no TTimePartitionSlot in DataPartitionQueryParam, it's means fetch all data so cache will miss all the time.
Besides, I have do test in 3 confifnodes and 3 datanodes cluster and run some scripts as follows:
> [IOTDB-2960]Add partition cache

- server/src/main/java/org/apache/iotdb/db/mpp/execution/DataDriver.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/Driver.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/FragmentInstanceExecution.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/FragmentInstanceManager.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/IDriver.java
- server/src/main/java/org/apache/iotdb/db/mpp/schedule/AbstractDriverThread.java
- server/src/main/java/org/apache/iotdb/db/mpp/schedule/DriverScheduler.java
- server/src/main/java/org/apache/iotdb/db/mpp/schedule/DriverTaskThread.java
- server/src/main/java/org/apache/iotdb/db/mpp/schedule/DriverTaskTimeoutSentinelThread.java
- server/src/main/java/org/apache/iotdb/db/mpp/schedule/ExecutionContext.java
- server/src/main/java/org/apache/iotdb/db/mpp/schedule/IDriverScheduler.java
- server/src/main/java/org/apache/iotdb/db/mpp/schedule/ITaskScheduler.java
- server/src/main/java/org/apache/iotdb/db/mpp/schedule/task/DriverTask.java
- server/src/main/java/org/apache/iotdb/db/mpp/schedule/task/DriverTaskID.java
- server/src/main/java/org/apache/iotdb/db/mpp/schedule/task/DriverTaskStatus.java
- server/src/main/java/org/apache/iotdb/db/service/DataNode.java
- server/src/main/java/org/apache/iotdb/db/service/IoTDB.java
- server/src/test/java/org/apache/iotdb/db/mpp/execution/DataDriverTest.java
- server/src/test/java/org/apache/iotdb/db/mpp/schedule/DefaultTaskSchedulerTest.java
- server/src/test/java/org/apache/iotdb/db/mpp/schedule/DriverSchedulerTest.java
- server/src/test/java/org/apache/iotdb/db/mpp/schedule/DriverTaskTimeoutSentinelThreadTest.java
A FragmentInstance may have more than one Driver in the future. Therefore, the FragmentInstanceScheduler could be renamed to DriverScheduler.
An illustration
https://y8dp9fjm8f.feishu.cn/docs/doccnIW7CZkFf5ZGdMoV7nv16xb
> Add javadoc and rename some class in FragmentInstanceManager and Driver related

- client-py/SessionAlignedTimeseriesExample.py
- client-py/SessionExample.py
- client-py/iotdb/Session.py
- client-py/tests/tablet_performance_comparison.py
- client-py/tests/test_one_device.py
[IOTDB-3033](https://issues.apache.org/jira/browse/IOTDB-3033)
Add a one device string insert interface; 
one device insert aligned string interface;
an interface for querying data by time, 
and an interface for querying the latest time.
Submit unit test script.
Submit a python client interface example.
In python, the query and insert interface is completed.
In the second commit, reformat code by black and flake8
> [IOTDB-3033] Completing the query and writing interface compared to java

- server/src/main/java/org/apache/iotdb/db/mpp/buffer/DataBlockManager.java
- server/src/main/java/org/apache/iotdb/db/mpp/buffer/ISinkHandle.java
- server/src/main/java/org/apache/iotdb/db/mpp/buffer/ISourceHandle.java
- server/src/main/java/org/apache/iotdb/db/mpp/buffer/SinkHandle.java
- server/src/main/java/org/apache/iotdb/db/mpp/buffer/SourceHandle.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/Driver.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/QueryExecution.java
- server/src/main/java/org/apache/iotdb/db/mpp/memory/MemoryPool.java
- server/src/main/java/org/apache/iotdb/db/mpp/operator/source/ExchangeOperator.java
- server/src/test/java/org/apache/iotdb/db/mpp/buffer/SinkHandleTest.java
- server/src/test/java/org/apache/iotdb/db/mpp/buffer/SourceHandleTest.java
- server/src/test/java/org/apache/iotdb/db/mpp/buffer/StubSinkHandle.java
- server/src/test/java/org/apache/iotdb/db/mpp/memory/MemoryPoolTest.java
1. Fix sink/source handle memory leak
2. Fix SourceHandle#setNoMoreTsBlocks doesn't trigger listener
3. rename SinkHandle#close to setNoMoreTsBlocks
4. rename SourceHandle#close to abort for consistency
> [IOTDB-3021] Fix sink/source handle memory leak

- integration/src/test/java/org/apache/iotdb/db/integration/IoTDBDeleteStorageGroupIT.java
- server/src/main/java/org/apache/iotdb/db/localconfignode/LocalConfigNode.java
problem:
When disable sync, we still splitDeleteTimeseriesPlanByDevice in delete storage group, this is not needed.
solution:
Only splitDeleteTimeseriesPlanByDevice in delete storage group when sync is enabled.
> [IOTDB-3030] delete storage group with ** error

- cluster/src/test/java/org/apache/iotdb/cluster/log/snapshot/FileSnapshotTest.java
- cluster/src/test/java/org/apache/iotdb/cluster/log/snapshot/PartitionedSnapshotTest.java
- cluster/src/test/java/org/apache/iotdb/cluster/log/snapshot/PullSnapshotTaskTest.java
- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/DataRegion.java
The version number should start from 1, not from 0. Otherwise, partitionMaxFileVersions cannot be computed correctly after iotdb restart(in `updatePartitionFileVersion`). If load tsfile, the version number will be 0, which is duplicated.
> [IOTDB-3026] fix cannot load tsfile correctly after restart iotdb

- server/src/main/java/org/apache/iotdb/db/mpp/sql/planner/plan/node/metedata/write/AlterTimeSeriesNode.java
- server/src/main/java/org/apache/iotdb/db/mpp/sql/planner/plan/node/metedata/write/CreateAlignedTimeSeriesNode.java
1 config node 1 datanode mode:
Do as the IoTDB User Guide:
All look good!
> [IOTDB-2803] support AlterTimeseries sql

- integration/src/test/java/org/apache/iotdb/db/integration/sync/IoTDBSyncSenderIT.java
- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/DataRegion.java
- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/TsFileManager.java
- server/src/main/java/org/apache/iotdb/db/sync/sender/manager/TsFileSyncManager.java
- server/src/main/java/org/apache/iotdb/db/sync/sender/pipe/TsFilePipe.java
- server/src/main/java/org/apache/iotdb/db/sync/sender/recovery/TsFilePipeLogger.java
problem:
Data loss happens when sender shutdowns with data in working memtable.
When restarting IoTDB, WAL will restore all data in unsealed tsfile and close it, but this tsfile is not collected by running pipe.
solution:
add TsfFileSyncManager#collectRealTimeTsFile in DataRegion#callbackAfterUnsealedTsFileRecovered
add TsFilePipeLogger#isHardlinkExist to judge if the tsfile hardlink is created or not, and simplified the process of collecting history tsfile.
add IT
> [IOTDB-3049]Sync Sender loss data when restart IoTDB with data in working memtable

- consensus/src/main/java/org/apache/iotdb/consensus/ratis/Utils.java
Currently in Ratis, it requires 16-bytes-long ByteString as the unique RaftGroupID of a consensus raft group. However, internally Ratis extracts and only uses 6 bytes of the given RaftGroupID. In current group id encoding schema, we may encounter the situation where two 16bytes-id differ while there underlying 6bytes-id equals. Thus we need to reverse engineer and encode the total group information into 6bytes, uniquely.
> [IOTDB-3075] RatisConsensus UUID bugfix

- server/src/main/java/org/apache/iotdb/db/localconfignode/LocalConfigNode.java
- server/src/main/java/org/apache/iotdb/db/metadata/LocalSchemaProcessor.java
- server/src/main/java/org/apache/iotdb/db/metadata/schemaregion/SchemaEngine.java
When isAutoCreateSchemaEnabled, the testInsertMultiTabletPlanParallel may throw npe, due to one of the resources, storage group, schemaRegionId table and schemaRegion, is not prepared ready by another thread.
Ensure the resources during insert.
> Fix concurrent failure of testInsertMultiTabletPlanParallel

- node-commons/src/main/java/org/apache/iotdb/commons/partition/DataPartition.java
- node-commons/src/main/java/org/apache/iotdb/commons/partition/Partition.java
- node-commons/src/main/java/org/apache/iotdb/commons/partition/SchemaPartition.java
- server/src/main/java/org/apache/iotdb/db/mpp/common/schematree/SchemaTree.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/Analysis.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/Analyzer.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/execution/QueryExecution.java
Before this change, there are 2 scenarios which are not handled by query.
1. Query schema if the storage group exists but there is no timeseries inside it.
2. Query the data if the storage group exists but there is no timeseries and data inside it.
After this change, the query in these two scenarios are like:
1. query schema
2. query data
> Handle the scenarios that there is no data for storage group

- server/src/main/java/org/apache/iotdb/db/mpp/plan/execution/config/SetTTLTask.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/execution/config/ShowTTLTask.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/statement/metadata/SetTTLStatement.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/statement/metadata/ShowTTLStatement.java
This PR fix the compilation problem caused by [PR-5780](https://github.com/apache/iotdb/pull/5780).
> [IOTDB-2865] Move `PartialPath` to node-commons module

- server/src/test/java/org/apache/iotdb/db/mpp/execution/operator/OffsetOperatorTest.java
This PR fix the compilation problem caused by [PR-5780](https://github.com/apache/iotdb/pull/5780).
> [IOTDB-2865] Move PartialPath to node-commons module

- server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/ClusterSchemaFetcher.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/execution/IQueryExecution.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/execution/QueryExecution.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/execution/config/ConfigExecution.java
- server/src/main/java/org/apache/iotdb/db/utils/QueryDataSetUtils.java
- server/src/test/java/org/apache/iotdb/db/mpp/execution/ConfigExecutionTest.java
Return Option<TsBlock> instead of TsBlock to let caller clearly be aware of that the method will return null.
> Return Option<TsBlock> instead of TsBlock

- server/src/main/java/org/apache/iotdb/db/mpp/execution/datatransfer/DataBlockManager.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/datatransfer/SourceHandle.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/ClusterSchemaFetcher.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/execution/QueryExecution.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/scheduler/SimpleQueryTerminator.java
- server/src/main/java/org/apache/iotdb/db/service/thrift/impl/InternalServiceImpl.java
- thrift/src/main/thrift/mpp.thrift
In some scenario, some FragmentInstance may stuck in FLUSHING state, although the corresponding QueryExecution has already output the final results.
It is because in some query contains `LimitOperator`, the downstream fragment instance will only consume part of TsBlocks produced by its upstream and won't fetch all the TsBlocks. Therefore, the upstream's SinkHandle won't be finished because its TsBlocks are not consumed totally and it also won't receive all the ACK events. So the Fragment Instance which contains this SinkHandle will always stuck in the `FLUSHING` state.
1. Do `SendACK` in SourceHandle once it receives corresponding TsBlocks to avoid the inconsistency that it receives the TsBlock but doesn't send the ACK due to being aborted.
2. When the `ResultHandle` in QueryExecution is …
> Fix the issue that sometimes the FragmentInstance may stuck in FLUSHING states

- server/src/main/java/org/apache/iotdb/db/wal/WALManager.java
https://issues.apache.org/jira/browse/IOTDB-3125
IT 报 RejectedExecutionException 的原因是：
1)  一些 IT case 使用 EnvironmentUtils#cleanEnv 去主动关闭一些 service。
2)  而进程退出时，又会触发运行一遍  showdown 流程，导致 WALManager 做了两次资源释放动作导致的。
3)  IT case 完成后，进程退出时才会触发这个 error log，所以 IT cases  仍然认为自己 test 结果是 passed。
这个问题只会出现在 IT 中。
> [IOTDB-3125] IT case report Error RejectedExecutionException

- confignode/src/main/java/org/apache/iotdb/confignode/client/handlers/InitRegionHandler.java
- confignode/src/main/java/org/apache/iotdb/confignode/persistence/ClusterSchemaInfo.java
- server/src/main/java/org/apache/iotdb/db/metadata/mtree/MTreeAboveSG.java
- server/src/main/java/org/apache/iotdb/db/metadata/schemaregion/SchemaEngine.java
- server/src/main/java/org/apache/iotdb/db/metadata/storagegroup/IStorageGroupSchemaManager.java
- server/src/main/java/org/apache/iotdb/db/metadata/storagegroup/StorageGroupSchemaManager.java
The storage group info management of dataNode went wrong when createSchemaRegion. The localStorageGroupSchemaManager go through the auto create sg logic with normal path rather than specified storage group path. It means when the target storage group path is root.a.sg, the sg created by ensureStorageGroup method is root.a since the default sg level is 1.
rewrite the logic of localStorageGroupSchemaManager.ensureStorageGroup
rename it to ensureStorageGroupByStorageGroupPath
> Fix multi level sg creation bug

- node-commons/src/main/java/org/apache/iotdb/commons/schema/tree/AbstractTreeVisitor.java
- node-commons/src/main/java/org/apache/iotdb/commons/schema/tree/AbstractTreeVisitorWithLimitOffset.java
- node-commons/src/main/java/org/apache/iotdb/commons/schema/tree/ITreeNode.java
- server/src/main/java/org/apache/iotdb/db/mpp/common/schematree/node/SchemaNode.java
- server/src/main/java/org/apache/iotdb/db/mpp/common/schematree/visitor/SchemaTreeDeviceVisitor.java
- server/src/main/java/org/apache/iotdb/db/mpp/common/schematree/visitor/SchemaTreeMeasurementVisitor.java
- server/src/main/java/org/apache/iotdb/db/mpp/common/schematree/visitor/SchemaTreeVisitor.java
- server/src/test/java/org/apache/iotdb/db/mpp/common/schematree/SchemaTreeTest.java
In ```findLastMatch``` procedure, the node matching will be repeated, implemented as nested loop. Add status record to reduce repeating check.
Before consuming the device node, the algorithm pushed the children into visitStack and the device node to ancestorStack. This will bring repeating device node name when constructing the result.
Add ```shouldVisitSubtree``` variable to help control the process. When meeting a matched device node, save its matching info and context before return. After consuming the device node, process its subtree based on the saved info and context.
> [IOTDB-3127] Fix tree traverse algorithm

- confignode/src/main/java/org/apache/iotdb/confignode/conf/ConfigNodeConf.java
- confignode/src/main/java/org/apache/iotdb/confignode/conf/ConfigNodeDescriptor.java
- confignode/src/main/java/org/apache/iotdb/confignode/conf/ConfigNodeStartupCheck.java
- confignode/src/main/java/org/apache/iotdb/confignode/manager/ConfigManager.java
- confignode/src/main/java/org/apache/iotdb/confignode/service/thrift/ConfigNodeRPCServiceProcessor.java
- integration/src/test/java/org/apache/iotdb/db/integration/IoTDBTtlIT.java
- node-commons/src/main/java/org/apache/iotdb/commons/auth/authorizer/BasicAuthorizer.java
- node-commons/src/main/java/org/apache/iotdb/commons/auth/authorizer/LocalFileAuthorizer.java
- node-commons/src/main/java/org/apache/iotdb/commons/auth/authorizer/OpenIdAuthorizer.java
- node-commons/src/main/java/org/apache/iotdb/commons/auth/user/BasicUserManager.java
- node-commons/src/main/java/org/apache/iotdb/commons/conf/CommonConfig.java
- node-commons/src/main/java/org/apache/iotdb/commons/conf/CommonDescriptor.java
- node-commons/src/main/java/org/apache/iotdb/commons/file/SystemFileFactory.java
- node-commons/src/main/java/org/apache/iotdb/commons/utils/AuthUtils.java
- schema-engine-rocksdb/src/main/java/org/apache/iotdb/db/metadata/schemaregion/rocksdb/mnode/RStorageGroupMNode.java
- server/src/main/java/org/apache/iotdb/db/auth/AuthorityChecker.java
- server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
- server/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java
- server/src/main/java/org/apache/iotdb/db/metadata/mtree/MTreeAboveSG.java
- server/src/main/java/org/apache/iotdb/db/metadata/mtree/store/MemMTreeStore.java
- server/src/main/java/org/apache/iotdb/db/metadata/mtree/store/disk/schemafile/MockSchemaFile.java
- server/src/main/java/org/apache/iotdb/db/metadata/mtree/store/disk/schemafile/SchemaFile.java
- server/src/main/java/org/apache/iotdb/db/qp/executor/PlanExecutor.java
- server/src/main/java/org/apache/iotdb/db/qp/physical/crud/InsertMultiTabletsPlan.java
- server/src/test/java/org/apache/iotdb/db/auth/authorizer/LocalFileAuthorizerTest.java
- server/src/test/java/org/apache/iotdb/db/auth/authorizer/OpenIdAuthorizerTest.java
- server/src/test/java/org/apache/iotdb/db/auth/user/LocalFileUserManagerTest.java
- server/src/test/java/org/apache/iotdb/db/security/encrypt/MessageDigestEncryptTest.java
The config should be managed by a descriptor rather than make itself as a single tone.
Implement CommonDescriptor and encapsulate the related init and load logic into it. Refactor the commonConfig access to CommonDescriptor.getInstance().getConfig
> Implement CommonDescriptor and refactor CommonConfig usage

- server/src/main/java/org/apache/iotdb/db/exception/mpp/FragmentInstanceDispatchException.java
- server/src/main/java/org/apache/iotdb/db/mpp/common/PlanFragmentId.java
- server/src/main/java/org/apache/iotdb/db/mpp/common/schematree/PathPatternTree.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/fragment/FragmentInstanceManager.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/Coordinator.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/execution/QueryExecution.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/metedata/read/SchemaFetchScanNode.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/process/ExchangeNode.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/scheduler/ClusterScheduler.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/scheduler/FragmentInstanceDispatcherImpl.java
- server/src/test/java/org/apache/iotdb/db/mpp/plan/plan/QueryPlannerTest.java
1. Use separate threadPool for write operation to avoid the dead-lock issue when dispatching WRITE FragmentInstance
2. Optimize the unnecessary RPC when dispatch FragmentInstance to local node. When the fragment instance is executed in local node, skip the RPC layer and put it into the Consensus layer directly.
Fix three bugs which block the local dispatch process. Before this change, some logic was put in the `serialize()` method. If the `serialize()` method is not invoked, the necessary code logic is lost and the bug appears.
> [IOTDB-3155] Optimize the schedule of MPP framework

- .github/workflows/main-unix.yml
- .github/workflows/sonar-coveralls.yml
- distribution/pom.xml
- distribution/src/assembly/all.xml
- distribution/src/assembly/confignode.xml
- pom.xml
- testcontainer/pom.xml
In this PR
* Add confignode in distribution package, we can now execute `mvn clean package -pl distribution -am -DskipTests` to get the compiled confignode package.
* fix CI still runs old cluster tests
* Add confignode in all-in-one package
Now the all-in-one structure is
> [IOTDB-3146] add confignode to distribution package

- confignode/src/main/java/org/apache/iotdb/confignode/consensus/response/DataPartitionResp.java
- confignode/src/main/java/org/apache/iotdb/confignode/consensus/response/SchemaPartitionResp.java
- confignode/src/main/java/org/apache/iotdb/confignode/manager/ConfigManager.java
Currently, we don't know what PartitionTable that ConfigNode returns to DataNode, which is not conducive to development debug. So I have temporarily added logs for getSchemaPartition getOrCreateSchemaPartition getDataPartition, getOrCreateDataPartition  interfaces.
> [IOTDB-3179] Printing logs when get/getOrCreate Partition in ConfigNode

- integration/src/test/java/org/apache/iotdb/db/integration/IoTDBRestartIT.java
- server/src/main/java/org/apache/iotdb/db/service/IoTDB.java
- server/src/main/java/org/apache/iotdb/db/utils/MemUtils.java
Deleted timeseries are created again after restart because auto create timeseries is enabled when wal checks the timeseries schema. To fix this problem, I disable auto create timeseries and enable partial insert when recovering.
> [To rel/0.13][IOTDB-3045] Deleted timeseries are created again after restart

- integration/src/test/java/org/apache/iotdb/db/integration/IoTDBRestartIT.java
- server/src/main/java/org/apache/iotdb/db/service/IoTDB.java
Deleted timeseries are created again after restart because auto create timeseries is enabled when wal checks the timeseries schema. To fix this problem, I disable auto create timeseries and enable partial insert when recovering.
> [IOTDB-3045] Deleted timeseries are created again after restart

- server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/process/FilterOperator.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/process/TransformOperator.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/Analyzer.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/LocalExecutionPlanner.java
- server/src/main/java/org/apache/iotdb/db/query/expression/Expression.java
- server/src/main/java/org/apache/iotdb/db/query/expression/binary/BinaryExpression.java
- server/src/main/java/org/apache/iotdb/db/query/expression/leaf/ConstantOperand.java
- server/src/main/java/org/apache/iotdb/db/query/expression/leaf/TimeSeriesOperand.java
- server/src/main/java/org/apache/iotdb/db/query/expression/leaf/TimestampOperand.java
- server/src/main/java/org/apache/iotdb/db/query/expression/multi/FunctionExpression.java
- server/src/main/java/org/apache/iotdb/db/query/expression/unary/UnaryExpression.java
- server/src/main/java/org/apache/iotdb/db/query/udf/core/executor/UDTFExecutor.java
- server/src/main/java/org/apache/iotdb/db/query/udf/core/layer/EvaluationDAGBuilder.java
Bugfix list:
[reused TypeProvider in converting Expression->Transformer stage](https://github.com/apache/iotdb/commit/279f96667d85240f0d16df4e9be92bf9e5c7da9d)
[bind transformer input column with operator column input index](https://github.com/apache/iotdb/commit/5a3e4512f48a28cc6ededb13933ff6aa5b30cdf4)
[fix FilterOperator#iterateFilterReaderToNextValid()](https://github.com/apache/iotdb/commit/53b4c0f0e3b5a39688495a4e938bf5a1fa4c4b2a)
[invoke declarePositions(rowCount) in Operator#next()](https://github.com/apache/iotdb/commit/6b3fabfd29d1711d6c77617b6ba2171e88d72bc3)
[invoke readyForFirstIteration() in hasNext() instead of in constructor](https://github.com/apache/iotdb/commit/7e47110c8d6a151e2c411faf507c81e3a48c5fca)
[infer types in …
> [MPP][Bug hotfix] Support expressions in select and filter causes 

- metrics/interface/src/main/assembly/resources/conf/iotdb-metric.yml
- metrics/interface/src/main/java/org/apache/iotdb/metrics/config/MetricConfig.java
- server/src/assembly/resources/conf/iotdb-engine.properties
- server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
- server/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java
- server/src/main/java/org/apache/iotdb/db/service/thrift/impl/DataNodeTSIServiceImpl.java
- server/src/main/java/org/apache/iotdb/db/service/thrift/impl/TSServiceImpl.java
1. Remove enable_performance_stat parameter in iotdb-engine.
2. Add enablePerformanceStat in iotdb-metric.
> [IOTDB-3199][Metric]Move metric-related parameter from iotdb-engine to iotdb-metric.

- integration/src/test/java/org/apache/iotdb/db/integration/IoTDBRestartIT.java
- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/TsFileProcessor.java
- server/src/main/java/org/apache/iotdb/db/writelog/manager/MultiFileLogNodeManager.java
- tsfile/src/main/java/org/apache/iotdb/tsfile/write/writer/RestorableTsFileIOWriter.java
Corrupted TsFile doesn't recover when exceptions occurs in the flushing memtable procedure, because we only interrupt and do nothing else. To fix this problem, I drop the memTable and skip ending tsfile when meeting flush error.
> [To rel/0.13][IOTDB-3160] TsFile will be corrupted when flushing memtable appears OOM

- consensus/src/main/java/org/apache/iotdb/consensus/ratis/ApplicationStateMachineProxy.java
RatisConsensus is supposed to delete the snapshotDir on statemachine failure
> BugFix: Delete snapshotDir on failure

- server/src/main/java/org/apache/iotdb/db/service/IoTDBShutdownHook.java
see IOTDB-3210
When shutDown the system, the metadata component will be cleared, during which some attributes and variables will be set to null to release resource. If there's insertion during system shutdown, it may encounter a cleared metadata module and trigger auto create schema, and this is why there's npe.
The metadata clear in shutDownHook is aimed to shut down rocksdb when using rocksdb schema engine mode. Thus add the check before execution.
Add some client connection and request execution control, and Polish the elegant system exit/shutdown process.
> [IOTDB-3210]fix npe

- server/src/main/java/org/apache/iotdb/db/client/ConfigNodeInfo.java
- server/src/main/java/org/apache/iotdb/db/conf/IoTDBStartCheck.java
- `ConfigNodeInfo.storeConfigNode()` and `IoTDBStartCheck.serializeDataNodeId()` will both update the file system.properties, we forget to close fileInputStream and cause "file has opened" problem.
- Update the properties in memory when updating system.properties
> Fix a file opening conflict bug

- confignode/src/main/java/org/apache/iotdb/confignode/persistence/ClusterSchemaInfo.java
- confignode/src/main/java/org/apache/iotdb/confignode/persistence/NodeInfo.java
- confignode/src/main/java/org/apache/iotdb/confignode/persistence/PartitionInfo.java
- confignode/src/main/java/org/apache/iotdb/confignode/persistence/executor/ConfigRequestExecutor.java
- confignode/src/test/java/org/apache/iotdb/confignode/persistence/PartitionInfoTest.java
- node-commons/src/main/java/org/apache/iotdb/commons/partition/DataPartition.java
- node-commons/src/main/java/org/apache/iotdb/commons/partition/SchemaPartition.java
- node-commons/src/test/java/org/apache/iotdb/commons/partition/DataPartitionTest.java
- node-commons/src/test/java/org/apache/iotdb/commons/partition/SchemaPartitionTest.java
> [IOTDB-3200] [PartitionInfo] replace bytebuffer with stream

- server/src/main/java/org/apache/iotdb/db/consensus/statemachine/DataRegionStateMachine.java
- server/src/main/java/org/apache/iotdb/db/consensus/statemachine/visitor/DataExecutionVisitor.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/PlanVisitor.java
See [IOTDB-3213](https://issues.apache.org/jira/browse/IOTDB-3213).
Visitor pattern is used to process plan node in SchemaRegionStateMachine and DistributedPlanner, this issue aims to apply visitor pattern to DataRegionStateMachine.
Attachments
> [IOTDB-3213] Apply visitor pattern for DataRegionStateMachine

- confignode/src/main/java/org/apache/iotdb/confignode/persistence/ClusterSchemaInfo.java
- node-commons/src/main/java/org/apache/iotdb/commons/utils/ThriftConfigNodeSerDeUtils.java
- server/src/main/java/org/apache/iotdb/db/metadata/mtree/MTreeAboveSG.java
- server/src/main/java/org/apache/iotdb/db/metadata/mtree/traverser/collector/MNodeAboveSGCollector.java
- server/src/test/java/org/apache/iotdb/db/metadata/mtree/MTreeAboveSGTest.java
Bytebuffer doesn't support capacity dynamic extension and will occupy more memory resource.
Use BufferedOutputStream and BufferedInputStream to implement serialize and deserialize of MTreeAboveSG separately.
If a storageGroupNode matches the given node query and it doesn't have any schemaPartition, it will be missed since it has not been put to result set while traverse the MTreeAboveSG and there's no related schemaRegion to traverse.
Try add node to result set before storage group check.
> Modify the serialize/deserialize of MTreeAboveSG with stream & Add storageGroupNode to the result of MNodeAboveSGCollector

- server/src/main/java/org/apache/iotdb/db/mpp/plan/scheduler/FragmentInstanceDispatcherImpl.java
Before this change, we only compare the target IP with localhost IP to judge whether to dispatch the fragment instance locally. But it will lead unexpected behaviors when several DataNodes run in the same Host with different Port.
We add the InternalPort compare as another condition to fix this issue.
> Add internal port compare when dispatching locally

- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/write/InsertMultiTabletsNode.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/write/InsertRowNode.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/write/InsertRowsNode.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/write/InsertRowsOfOneDeviceNode.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/write/InsertTabletNode.java
See [IOTDB-3238](https://issues.apache.org/jira/projects/IOTDB/issues/IOTDB-3238).
The reason for this bug is that we did not implement `accept` method for plan node executed in DataRegionStateMachine.
> [IOTDB-3238] Fix cannot insert data into data node

- integration/src/test/java/org/apache/iotdb/db/integration/aligned/IoTDBAggregationWithoutValueFilterIT.java
- server/src/main/java/org/apache/iotdb/db/engine/querycontext/AlignedReadOnlyMemChunk.java
Fix the bug ISSUE-5964 .
<hr>
This PR has:
<hr>
> [To rel/0.13][ISSUE-5964] Fix bug of aligned timeseries time duplicated aggregation

- server/src/main/java/org/apache/iotdb/db/sync/sender/service/TransportHandler.java
Problem:
Wrong IP of sender is shown on the receiver.
Solution:
Java will get IP from /etc/hosts, which can be modified by user. To obtain correct IP of sender, I add if statement in TransportHandler to judge the InetAddress.getLocalHost() is loopback address or not. If the IP address is loopback address, it will establish a UDP socket to receiver to get the correct IP.
Reference:
https://stackoverflow.com/questions/2381316/java-inetaddress-getlocalhost-returns-127-0-0-1-how-to-get-real-ip
https://stackoverflow.com/questions/9481865/getting-the-ip-address-of-the-current-machine-using-java
> [IOTDB-3109]Fix wrong sender IP shown in receiver

- docs/UserGuide/Reference/Config-Manual.md
- docs/zh/UserGuide/Reference/Config-Manual.md
- server/src/assembly/resources/conf/iotdb-engine.properties
- server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
https://lists.apache.org/thread/s3rm5z5yzjcws8cns87bs2vod041nyg5
> [IOTDB-3087] enlarge default value of avg_series_point_number_threhold

- server/src/assembly/resources/sbin/stop-server.sh
Datanodes can be killed by stop-server.sh, but we predict datanodes will be stopped by stop-datanode.sh
After this commit, the scripts of server can:
- stop-server.sh: stop iotdb instance by the rpc_port
- stop-datanode.sh: stop all data nodes process
> [IOTDB-3218] Datanode can not be stoped by using stop-server.sh

- consensus/pom.xml
- consensus/src/main/java/org/apache/iotdb/consensus/ratis/ApplicationStateMachineProxy.java
- consensus/src/main/java/org/apache/iotdb/consensus/ratis/RatisConsensus.java
- consensus/src/main/java/org/apache/iotdb/consensus/ratis/SnapshotStorage.java
- consensus/src/main/java/org/apache/iotdb/consensus/ratis/Utils.java
- consensus/src/main/resources/logback-test.xml
- consensus/src/test/java/org/apache/iotdb/consensus/ratis/SnapshotTest.java
Recently Apache Ratis Community releases 2.3.0, which includes bugfix to known InstallSnapshot issues.
In this PR, I upgrade Ratis version to 2.3.0.
Notice:
Currently, we name the snapshotDir with Term_Index so that we can tell which directory contains
the latest snapshot files. Unfortunately, when leader install snapshot to a slow follower,
current Ratis implementation will flatten the directory and place all the snapshots directly
under statemachine dir. Under this scenario, we cannot restore Term_Index from directory name.
We decided to add an empty metadata file containing only Term_Index into the snapshotDir. his
metadata file will be installed along with application snapshot files, so that Term_Index
information is kept during InstallSnapshot.
> [IOTDB-3253] Upgrade dependency: Ratis from 2.2.0 to 2.3.0

- site/src/main/.vuepress/theme/global-components/IoTDB.vue
- site/src/main/.vuepress/theme/global-components/IoTDBZH.vue
[[IOTDB-3286] False Carousel Ratio on Desktop Version Homepage](https://issues.apache.org/jira/browse/IOTDB-3286)
I've implemented a script that could automatically adjust the carousel height due to the browser width. Please see the screenshots below:
Original (desktop version):
New (desktop version):
New (mobile version):
<hr>
This PR has:
<hr>
> [IOTDB-3286] False Carousel Ratio on Desktop Version Homepage

- node-commons/src/main/java/org/apache/iotdb/commons/conf/IoTDBConstant.java
- server/src/main/java/org/apache/iotdb/db/mpp/common/header/HeaderConstant.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/execution/config/ShowStorageGroupTask.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/execution/config/ShowTTLTask.java
See more details: https://issues.apache.org/jira/browse/IOTDB-3315
Test on 3C3D:
> [IOTDB-3315] Make unset of ttl in cluster mode same as 0.13.0 version.

- integration/src/test/java/org/apache/iotdb/db/integration/sync/IoTDBSyncReceiverIT.java
- server/src/main/java/org/apache/iotdb/db/sync/sender/service/TransportHandler.java
- server/src/main/java/org/apache/iotdb/db/sync/transport/client/TransportClient.java
- server/src/test/java/org/apache/iotdb/db/sync/transport/TransportServiceTest.java
Problem:
1、In Receiver，set 127.0.1.1 to hostname in "/etc/hosts".
2、In Sender， start pipserver；
In Receiver，create pipesink ...， create pip ...，start pip ...
ERROR:  3、Now, in Receiver, at "data/sync/receiver" , created two folder
I think， The two folders point to the same host(Sender，192.168.130.12
ERROR:  4、 start writing data...
In Receiver，the data will sync to folder  ***-127.0.1.1, not the truth folder(192.168.130.12)
And, the sent data was not automatically moved to the data folder
ERROR: 5、
In this commit，The first start pipe is worked，After that, stop pipe and start pipe are not working
Solution:
Two different IP in TransportClient, change them into one.
> [IOTDB-3271] Wrong multi IP for one sender in receiver

- server/src/main/java/org/apache/iotdb/db/query/reader/chunk/MemAlignedPageReader.java
Fix the query result of the mem data from aligned time series may less than they should be.
Before:
Alfter:
To reproduce, use the test file below:
[AlignedWriteUtil.txt](https://github.com/apache/iotdb/files/8795248/AlignedWriteUtil.txt)
> Fix aligned data in memory query bug

- server/src/main/java/org/apache/iotdb/db/engine/memtable/AbstractMemTable.java
- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/DataRegion.java
- server/src/main/java/org/apache/iotdb/db/wal/WALManager.java
- server/src/main/java/org/apache/iotdb/db/wal/allocation/AbstractNodeAllocationStrategy.java
- server/src/main/java/org/apache/iotdb/db/wal/allocation/FirstCreateStrategy.java
- server/src/main/java/org/apache/iotdb/db/wal/buffer/AbstractWALBuffer.java
- server/src/main/java/org/apache/iotdb/db/wal/buffer/WALBuffer.java
- server/src/main/java/org/apache/iotdb/db/wal/checkpoint/CheckpointManager.java
- server/src/main/java/org/apache/iotdb/db/wal/checkpoint/MemTableInfo.java
- server/src/main/java/org/apache/iotdb/db/wal/io/CheckpointReader.java
- server/src/main/java/org/apache/iotdb/db/wal/node/WALNode.java
- server/src/main/java/org/apache/iotdb/db/wal/recover/CheckpointRecoverUtils.java
- server/src/main/java/org/apache/iotdb/db/wal/recover/WALNodeRecoverTask.java
- server/src/main/java/org/apache/iotdb/db/wal/utils/CheckpointFileUtils.java
- server/src/main/java/org/apache/iotdb/db/wal/utils/WALFileUtils.java
- server/src/test/java/org/apache/iotdb/db/wal/allocation/FirstCreateStrategyTest.java
- server/src/test/java/org/apache/iotdb/db/wal/checkpoint/CheckpointManagerTest.java
- server/src/test/java/org/apache/iotdb/db/wal/io/CheckpointFileTest.java
- server/src/test/java/org/apache/iotdb/db/wal/node/ConsensusReqReaderTest.java
- server/src/test/java/org/apache/iotdb/db/wal/node/WALNodeTest.java
Some data will be recovered wrongly because wal is kept, but memtable id still starts from 0 when using multi-leader consensus. So, I recover memtable id when using multi-leader consensus.
> [IOTDB-3335] Redundant data recovered by wal in multi-leader consensus

- node-commons/src/main/java/org/apache/iotdb/commons/service/AbstractThriftServiceThread.java
- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/TsFileProcessor.java
- server/src/main/java/org/apache/iotdb/db/service/DataNode.java
- server/src/main/java/org/apache/iotdb/db/service/IoTDB.java
Some users may starting same IoTDB twice, it may causes the TsFile flushed by two IoTDB processes.
In this PR, I made the following changes.
1. start the rpc service first, then the second IoTDB will stoped because of getting rpc port failed
2. removed the retry logic of getting rpc port
> [IOTDB-3306] Use rpc port check to avoid starting same IoTDB twice

- integration/src/test/java/org/apache/iotdb/db/integration/IOTDBInsertIT.java
- server/src/main/java/org/apache/iotdb/db/metadata/utils/MetaFormatUtils.java
- server/src/main/java/org/apache/iotdb/db/service/IoTDB.java
/**  check whether the node name uses "*" correctly */
private static void checkNameFormatIfHasstar(String name) throws MetadataException {
if (!((name.startsWith("'") && name.endsWith("'"))
|| (name.startsWith("\"") && name.endsWith("\"")))
&&  name.contains("*")
) {
throw new MetadataException(String.format("%s is an illegal name.", name));
}
}
/** check whether the given path is well formatted */
public static void checkTimeseries(PartialPath timeseries) throws IllegalPathException {
try {
checkCharacters(timeseries.getFullPath());
} catch (MetadataException e) {
throw new IllegalPathException(timeseries.getFullPath(), e.getMessage());
}
for (String name : timeseries.getNodes()) {
try {
checkReservedNames(name);
checkNameFormatIfHasstar(name);
checkNameFormat(name);
} catch …
> [IOTDB-3168][To rel/0.13] Fix the path with * could be executed successfully when inserting

- server/src/main/java/org/apache/iotdb/db/utils/CommonUtils.java
See IOTDB-3358
Before
After
<hr>
This PR has:
<hr>
> [IOTDB-3358] Fix error message of insert wrong type of data by sql is meaningless

- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/DataRegion.java
- server/src/main/java/org/apache/iotdb/db/wal/WALManager.java
- server/src/main/java/org/apache/iotdb/db/wal/allocation/AbstractNodeAllocationStrategy.java
- server/src/main/java/org/apache/iotdb/db/wal/allocation/FirstCreateStrategy.java
- server/src/main/java/org/apache/iotdb/db/wal/buffer/AbstractWALBuffer.java
- server/src/main/java/org/apache/iotdb/db/wal/buffer/WALBuffer.java
- server/src/main/java/org/apache/iotdb/db/wal/node/WALNode.java
- server/src/main/java/org/apache/iotdb/db/wal/recover/WALNodeRecoverTask.java
- server/src/test/java/org/apache/iotdb/db/wal/allocation/FirstCreateStrategyTest.java
Currently, the wal search index is always 0 when restart, causing some data unreachable. We should recover the search index when multi-leader consensus enabled.
> [IOTDB-3350] Recover wal search index when recovering from multi-leader

- integration/pom.xml
This bug skips the Standalone IT in the integration module.
> [IOTDB-3178] Emergency Bug Fix For IT framework

- confignode/src/main/java/org/apache/iotdb/confignode/persistence/NodeInfo.java
<hr>
This PR has:
Close #5881 
<hr>
> [ISSUE-5881] Fix `FileOutputStream` not close automatically

- tsfile/src/main/java/org/apache/iotdb/tsfile/read/reader/LocalTsFileInput.java
When a thread is been interrupted, it will throw:
(1) InterruptedException, when it is in sleep, wait, join blocking, etc.
(2) ClosedByInterruptException, when it is in the process of calling a blocking I/O operation on an interruptible channel (eg: serverSocketChannel.accept(), socketChannel.connect, socketChannel.open, socketChannel.read, socketChannel.write, fileChannel.read, fileChannel.write)
So here, we catch the InterruptedException and ClosedByInterruptException in compaction process and print warn logs.
> [IOTDB-2978][compaction error log ] Log level and "null" error message handling

- server/src/main/java/org/apache/iotdb/db/engine/compaction/TsFileManagement.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/level/LevelCompactionTsFileManagement.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/no/NoCompactionTsFileManagement.java
See [IOTDB-3389](https://issues.apache.org/jira/browse/IOTDB-3389).
The reason for this bug is that, when IoTDB is set up with NO_COMPACTION, it will not recover the uncompleted compaction.
> [To rel/0.12] [IOTDB-3389] Fix not completed target file in compaction can be accessed by query

- server/src/main/java/org/apache/iotdb/db/mpp/aggregation/timerangeiterator/TimeRangeIteratorFactory.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/process/AggregationOperator.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/source/SeriesAggregationScanOperator.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/Analyzer.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/GroupByLevelController.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/LocalExecutionPlanner.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/parameter/AggregationDescriptor.java
- server/src/test/java/org/apache/iotdb/db/mpp/execution/operator/AggregationOperatorTest.java
- server/src/test/java/org/apache/iotdb/db/mpp/plan/analyze/AggregationDescriptorTest.java
In this PR, I refactor calcInputLocationList() in LocalExecutionPlanner.
**Test result:**
```SQL
select last_value(s5), sum(s2), max_value(s3) from root.sg1.**;
```
```SQL
select last_value(s5), sum(s2), max_value(s3) from root.sg1.** group by level = 1;
```
```SQL
select last_value(s5), sum(s2), max_value(s3) from root.sg1.** group by ([1,41), 10ms);
```
```SQL
select last_value(s5), sum(s2), max_value(s3) from root.sg1.** group by ([1,41), 10ms), level = 1;
```
```SQL
select last_value(s5), sum(s2), max_value(s3) from root.sg1.** group by ([1,41), 10ms, 5ms);
```
```SQL
select last_value(s5), sum(s2), max_value(s3) from root.sg1.** group by ([1,41), 10ms, 5ms), level = 1;
```
> [IOTDB-3383] Refactor calcInputLocationList() in LocalExecutionPlanner

- confignode/src/main/java/org/apache/iotdb/confignode/exception/TimeoutException.java
- confignode/src/main/java/org/apache/iotdb/confignode/manager/ClusterSchemaManager.java
- confignode/src/main/java/org/apache/iotdb/confignode/manager/PartitionManager.java
- confignode/src/main/java/org/apache/iotdb/confignode/manager/load/LoadManager.java
- confignode/src/main/java/org/apache/iotdb/confignode/manager/load/balancer/RegionBalancer.java
- confignode/src/main/java/org/apache/iotdb/confignode/manager/load/balancer/allocator/CopySetRegionAllocator.java
- confignode/src/main/java/org/apache/iotdb/confignode/manager/load/balancer/allocator/IRegionAllocator.java
- confignode/src/main/java/org/apache/iotdb/confignode/persistence/ClusterSchemaInfo.java
- confignode/src/main/java/org/apache/iotdb/confignode/service/thrift/ConfigNodeRPCServiceProcessor.java
- confignode/src/test/java/org/apache/iotdb/confignode/persistence/ClusterSchemaInfoTest.java
The first Region allocation is triggered by the first getOrCreatePartition request. Therefore we need to maintain two kinds of allocation particles(SchemaRegion and DataRegion) for each StorageGroup. When the ConfigNode receives concurrent getOrCreatePartition requests who aim to some StorageGroups without any Region. They'll contend the allocation particle. The one who get the particle then do Region allocation, while others'll wait until allocation finished.
> [IOTDB-3261][IOTDB-3332][IOTDB-3372] Ensure the concurrency security of Region alloction

- tsfile/src/main/java/org/apache/iotdb/tsfile/read/TsFileSequenceReader.java
When a device should be in a TsFile, we throw an exception when query. 
I change this to a warn log with file name.
> [To rel/0.12] add log in query when a file does not contain a device that should in

- confignode/src/main/java/org/apache/iotdb/confignode/service/thrift/ConfigNodeRPCServiceProcessor.java
- thrift-confignode/src/main/thrift/confignode.thrift
Some thrift fields about Authorization must be optional but not required.
> [IOTDB-3363][IOTDB-3252] Update thrift fileds about Authorization

- confignode/src/main/java/org/apache/iotdb/confignode/persistence/ClusterSchemaInfo.java
- integration/src/test/java/org/apache/iotdb/db/integration/IoTDBTtlIT.java
before：
IoTDB> set ttl to root.sgcc 3600
Msg: 500: [INTERNAL_SERVER_ERROR(500)] Exception occurred: "set ttl to root.sgcc 3600". executeStatement failed. error code: TSStatus(code:500, message:322: null)
after：
IoTDB> set ttl to root.sgcc 3600
Msg: 500: [INTERNAL_SERVER_ERROR(500)] Exception occurred: "set ttl to root.sgcc 3600". executeStatement failed. error code: TSStatus(code:500, message:322: StorageGroup does not exist)
> Add an error message for setting TTL when the storagegroup does not exist

- server/src/main/java/org/apache/iotdb/db/mpp/common/schematree/SchemaTree.java
- server/src/test/java/org/apache/iotdb/db/mpp/common/schematree/SchemaTreeTest.java
To reproduce, add the following UT in SchemaTreeTest.
```java
@Test
public void testMergeSchemaTreeAndSearchDeviceSchemaInfo() throws Exception {
SchemaTree schemaTree = new SchemaTree();
for (SchemaTree tree : generateSchemaTrees()) {
schemaTree.mergeSchemaTree(tree);
}
PartialPath devicePath = new PartialPath("root.sg.d99999");
List<String> measurements = new ArrayList<>();
measurements.add("s1");
measurements.add("s2");
schemaTree.searchDeviceSchemaInfo(devicePath, measurements);
}
```
> Fix SchemaTree SearchDeviceSchema NPE

- server/src/main/java/org/apache/iotdb/db/engine/merge/task/MergeMultiChunkTask.java
- server/src/test/java/org/apache/iotdb/db/engine/merge/MergeNewSeriesTest.java
- server/src/test/java/org/apache/iotdb/db/engine/merge/MergeOverLapTest.java
- server/src/test/java/org/apache/iotdb/db/engine/merge/MergeTaskTest.java
- server/src/test/java/org/apache/iotdb/db/engine/merge/MergeTest.java
- tsfile/src/main/java/org/apache/iotdb/tsfile/read/TsFileSequenceReader.java
- tsfile/src/main/java/org/apache/iotdb/tsfile/utils/PreviewIterator.java
Please refer to https://issues.apache.org/jira/browse/IOTDB-3326
New timeseries in unseq files are merged into the last seq file, which results in a problematic device time range in the last seq file. After this fix, new time series in unseq files will be merged into seq files according to the device-level time range overlap.
> [To rel/0.12][IOTDB-3326] fix new series in unseq files are not merged into correct seqfiles

- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/distribution/DistributionPlanContext.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/distribution/SourceRewriter.java
After this change, it is ensured that every LastQueryScanNode will belong to a LastQueryMergeNode in one Fragment Instance, even though there is only one child for the parent LastQueryMergeNode
> Fix the issue that LastQuery lack MergeNode in some FI

- server/src/main/java/org/apache/iotdb/db/mpp/aggregation/timerangeiterator/TimeRangeIteratorFactory.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/Analyzer.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/parameter/GroupByTimeParameter.java
- server/src/test/java/org/apache/iotdb/db/mpp/aggregation/TimeRangeIteratorTest.java
interval and slidingStep is always in timestamp unit before transforming to timeRangeIterator even if it's by month unit.
> [IOTDB-3417] Group by month unit bug in MPP

- server/src/main/java/org/apache/iotdb/db/exception/sql/MeasurementNotExistException.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/Analyzer.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/ExpressionAnalyzer.java
If some measurements are not exist in some devices in where clause in align by device, we just exclude these devices from query rather than throwing an exception.
Before:
After:
> [IOTDB-3361] Exception if measurement is not exist in where clause in align by device

- integration/src/test/java/org/apache/iotdb/session/template/TemplateUT.java
- server/src/main/java/org/apache/iotdb/db/service/thrift/impl/TSServiceImpl.java
- session/src/main/java/org/apache/iotdb/session/Session.java
- session/src/main/java/org/apache/iotdb/session/SessionConnection.java
- session/src/main/java/org/apache/iotdb/session/pool/SessionPool.java
- thrift/src/main/thrift/rpc.thrift
As issue-#6171 suggested, this PR adds an interface in `Session` and `SessionPool` to support create timeseries of schema template on a designated path if had been set a template, which acts like the sql-statement sharing the same syntax.
> [To rel/0.13][ISSUE-6171]Support createTimeseriesOfTemplate in Session

- server/src/main/java/org/apache/iotdb/db/metadata/mtree/MTree.java
see detail: https://issues.apache.org/jira/browse/IOTDB-3420
after:
IoTDB> create timeseries root.sg.device1.t with datatype=BOOLEAN,encoding=PLAIN,compression=UNCOMPRESSED;
IoTDB> create timeseries root.sg.device2.t1 with datatype=BOOLEAN,encoding=PLAIN,compression=UNCOMPRESSED;
IoTDB> create schema template t1 (temperature FLOAT encoding=RLE, status BOOLEAN encoding=PLAIN compression=SNAPPY)
IoTDB> set schema template t1 to root.sg.device1
IoTDB> show paths set schema template t1
+----------------+
|    child paths      |
+----------------+
|root.sg.device1|
+----------------+
It costs …
> [IOTDB-3420] [TO rel/0.13] fix show paths set schema template t1 error

- node-commons/src/main/java/org/apache/iotdb/commons/partition/DataPartition.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/distribution/ExchangeNodeAdder.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/PlanFragment.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/PlanGraphPrinter.java
- server/src/test/java/org/apache/iotdb/db/mpp/plan/plan/distribution/NoDataRegionPlanningTest.java
Currently, if a query contains some series which has no data, it will throw NPE when doing the distribution planning.
It is because that there is no DataRegion is allocated for the series with no data. And thus we cannot do the distribution planning for it because it doesn't belong to any existed data region.
To solve this issue, we defined a mock DataRegion named `NOT_ASSIGNED`. When doing distribution planning, the node with that no-data series will be marked as `NOT_ASSIGNED`. And the real data region it runs will be its parent's read data region. If its parent's data region is also `NOT_ASSIGNED`, we will select the data region of the parent of its parent... If the `root` of the PlanNode tree is also `NOT_ASSIGNED`, that means all the series related to this query have no data and the …
> [IoTDB-3308] Fix the issue that NPE will be threw when query the series with no data

- node-commons/src/main/java/org/apache/iotdb/commons/partition/DataPartition.java
- server/src/main/java/org/apache/iotdb/db/service/DataNode.java
1. 启动 InternalService (`prepareJoinCluster()`)
2. DataNode 本地 setup (`active()`)
*  SchemaEngine 根据本地 data/system/schema 目录获得sg名和regionId，恢复 SchemaRegion
*  StorageEngine 根据本地 data/system/storage_group 目录获得sg名和regionId，恢复 DataRegion
*  DataNode 根据 data/system/schema/system.properties 恢复DataNodeID
*  根据共识组日志恢复 Region 共识组
*  恢复并启动其他IService
3. DataNode 向 ConfigNode 汇报本地状态并注册（`joinCluster()`）
* DataNode首先需要成功连接上config node集群
1. 根据iotdb-engine.properties读取配置文件中的target config node，连接target config node进行注册。
2. 若连接失败，则根据data/system/schema/system.properties读取持久化的confignode list，尝试进行连接。（data/system/schema/system.properties中的config node list会在每次confignode-datanode心跳时更新，进行持久化）
3. 若能成功连接上config node，则无论注册成功与否，config node都会返回完整的config node list给datanode，datanode在内存中保存config node list。若连接失败，datanode …
> [IOTDB-3439] Move Setting up RPC Service to the last step of starting DataNode

- checkstyle.xml
- node-commons/src/main/java/org/apache/iotdb/commons/concurrent/threadpool/ScheduledExecutorUtil.java
- server/src/main/java/org/apache/iotdb/db/engine/StorageEngine.java
- server/src/main/java/org/apache/iotdb/db/engine/StorageEngineV2.java
- server/src/main/java/org/apache/iotdb/db/localconfignode/LocalConfigNode.java
- server/src/main/java/org/apache/iotdb/db/wal/WALManager.java
Here we add two another unsafe wrapper methods to let those tasks which wants to quit schedule once an unexcepted exception happens. Next step is to ensure all the periodic services use the correct error handling strategy.
> [IOTDB-3444] Make periodic serivce be scheduled more flexible

- server/src/main/java/org/apache/iotdb/db/wal/buffer/WALBuffer.java
See JIRA: https://issues.apache.org/jira/projects/IOTDB/issues/IOTDB-3459?filter=myopenissues
> [IOTDB-3459] Make sure SignalWALEntry be pushed to the queue successfully in close()

- server/src/main/java/org/apache/iotdb/db/engine/StorageEngine.java
- server/src/main/java/org/apache/iotdb/db/engine/StorageEngineV2.java
- server/src/main/java/org/apache/iotdb/db/wal/WALManager.java
The following tasks has been fixed according to the doc https://apache-iotdb.feishu.cn/docx/doxcnT0NAd2Ug80JXQ68HaTpo3g
- timedForceMLogThread: From continuously to abort.
- Timed-Flush-Seq-Memtable(Both in StorageEngine and StorageEngineV2):  From continuously to abort, and remove outer try-catch.
- Timed-Flush-UnSeq-Memtable(Both in StorageEngine and StorageEngineV2):  From continuously to abort, and remove outer try-catch.
- TTL-check(Both in StorageEngine and StorageEngineV2): From abort to continuously.
- WAL-delete: From abort to continuously.
> [IOTDB-3458] Fix incorrect error handling strategy of some periodic services

- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/FragmentInstance.java
- server/src/test/java/org/apache/iotdb/db/mpp/plan/plan/FragmentInstanceSerdeTest.java
Skip `RegionReplicaSet` in serialization of Fragment Instance
> [IoTDB-3437]Skip RegionReplicaSet in serialization of Fragment Instance

- server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/ClusterSchemaFetcher.java
For `WRITE` operation, we changed to not storing it in coordinator's query execution map. So we need to cleanup the code which invoking the getQueryExecution() regarding WRITE operation. Or it will lead to NPE
> fix the issue that AutoCreateTimeSeries throws NPE

- client-py/README.md
- client-py/iotdb/dbapi/Connection.py
- client-py/iotdb/dbapi/Cursor.py
- client-py/iotdb/dbapi/Exceptions.py
- client-py/iotdb/dbapi/__init__.py
- client-py/iotdb/dbapi/tests/__init__.py
- client-py/iotdb/dbapi/tests/test_connection.py
- client-py/iotdb/dbapi/tests/test_cursor.py
- docs/UserGuide/API/Programming-Python-Native-API.md
- docs/zh/UserGuide/API/Programming-Python-Native-API.md
1. Implement the methods specified in DBAPI2.0
2. Add test code for the DBAPI module
**JIAR:** https://issues.apache.org/jira/browse/IOTDB-3460
**DBAPI2.0:** https://peps.python.org/pep-0249/
> [IOTDB-3460] Python API: Add support for DBAPI

- server/src/main/java/org/apache/iotdb/db/mpp/plan/parser/ASTVisitor.java
Currently abandon set ttl, schema replication factor, data replication factor, time partition interval to specific storage group.
Test on 3C3D:
> Abandon set ttl, schema replication factor, data replication factor, time partition interval to specific storage group

- server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/ClusterPartitionFetcher.java
See more details: https://issues.apache.org/jira/browse/IOTDB-3476.
If storage group is null, means that the device may not exist in iotdb and there are no need to update cache, so it isn't a error log.
> [IOTDB-3476] remove error log when update cache

- server/src/main/java/org/apache/iotdb/db/mpp/plan/Coordinator.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/ClusterSchemaFetcher.java
- server/src/main/java/org/apache/iotdb/db/service/thrift/impl/DataNodeTSIServiceImpl.java
In current implementation, the query won't be removed from QueryExecutionMap, which lead to lots of memory usage for schema fetching.
This PR added a method to remove specific QueryExecution according to its QueryId.
> (DONE): The query from client is still not be removed when finished. We'll consider how to handle this issue smoothly later
> Fix the issue that query is not removed from QueryExecutionMap

- server/src/main/java/org/apache/iotdb/db/service/thrift/impl/DataNodeTSIServiceImpl.java
Fix the bug that the judgement of hasResultSet is skipped. 
There is a bug in last PR https://github.com/apache/iotdb/pull/6278. We can only remove the queryExecution when the query has no more result set
> Fix the bug that the judgement of hasResultSet is skipped

- server/src/main/java/org/apache/iotdb/db/localconfignode/LocalConfigNode.java
- server/src/main/java/org/apache/iotdb/db/metadata/schemaregion/SchemaEngine.java
- server/src/main/java/org/apache/iotdb/db/service/DataNode.java
The localConfigNode is unnecessary to be initialized in cluster mode.
The old implementation of SchemaEngine Recovery is based on ```StorageGroupSchemaManager```, which coupled it with the LocalConfigNode Recovery. 
The mlog force depends on the timed thread in LocalConfigNode.
Replace the ```StorageGroupSchemaManager``` in SchemaEngine with an individual ```MTreeAboveSG```, which is used for the prefix share of schemaRegions.
Add a timedMLogForceThread to SchemaEngine, which enables the schemaEngine to force schemaRegions' mlogs.
After the modification, SchemaEngine can be used without LocalConfigNode in new Cluster.
> [IOTDB-3490] Eliminate LocalConfigNode Usage in New Cluster

- client-py/iotdb/Session.py
See [IOTDB-3494](https://issues.apache.org/jira/browse/IOTDB-3494).
The reason the this bug is that session does not format the string properly when printing logs using the python-logging library.
> [IOTDB-3494] Fix TypeError in python session

- consensus/src/main/java/org/apache/iotdb/consensus/multileader/MultiLeaderConsensus.java
- consensus/src/main/java/org/apache/iotdb/consensus/standalone/StandAloneConsensus.java
- consensus/src/test/java/org/apache/iotdb/consensus/EmptyStateMachine.java
- consensus/src/test/java/org/apache/iotdb/consensus/multileader/RecoveryTest.java
- consensus/src/test/java/org/apache/iotdb/consensus/standalone/StandAloneConsensusTest.java
- node-commons/src/main/java/org/apache/iotdb/commons/utils/FileUtils.java
see [jira3505](https://issues.apache.org/jira/browse/IOTDB-3505)
> [IOTDB-3505] The region dirs are not deleted when the storage group is deleted in MultiLeaderConsensus

- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/DataRegion.java
- server/src/main/java/org/apache/iotdb/db/wal/buffer/AbstractWALBuffer.java
- server/src/main/java/org/apache/iotdb/db/wal/buffer/IWALBuffer.java
- server/src/main/java/org/apache/iotdb/db/wal/buffer/WALBuffer.java
- server/src/main/java/org/apache/iotdb/db/wal/io/ILogWriter.java
- server/src/main/java/org/apache/iotdb/db/wal/io/LogWriter.java
- server/src/main/java/org/apache/iotdb/db/wal/node/WALNode.java
The empty wal file is produced by wal delete thread when dataregion's memtables are all flushed. To avoid this, wal delete thread will only roll wal file when wal file is not empty.
> [IOTDB-3438] Fix empty WAL file

- server/src/main/java/org/apache/iotdb/db/metadata/schemaregion/SchemaEngine.java
_deletedRegionSet_  is not cleared but the schema regions has been deleted  because client is closed accidently. And When do deletion again, NPE occurs.
After fixed, deleted schemaRegions are skipped:
2022-06-16 19:38:14,758 [pool-1-IoTDB-InternalServiceRPC-Client-4] WARN o.a.i.d.m.s.SchemaEngine:334 - SchemaRegion(id = SchemaRegion[0]) has been deleted, skiped 
2022-06-16 19:38:14,758 [pool-1-IoTDB-InternalServiceRPC-Client-4] WARN o.a.i.d.m.s.SchemaEngine:334 - SchemaRegion(id = SchemaRegion[26]) has been deleted, skiped
> [IOTDB-3505] Fix NPE when regionCleaner deletes schema regions after restart.

- server/src/main/java/org/apache/iotdb/db/mpp/execution/datatransfer/DataBlockManager.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/ClusterSchemaFetcher.java
1. In DataBlockServiceImpl, the target fragment instance may not be found because of finishing before receiving the event, which is possible. So we need to handle this scenario rather than throw Exception here.
2. In ClusterSchemaFetcher, we need to ensure the QueryExecution is always be removed so we use `try-finally` here to avoid runtime exception.
> Fix the issue that the QueryExecution may not be released

- consensus/src/main/java/org/apache/iotdb/consensus/standalone/StandAloneServerImpl.java
See description of [IOTDB-3521](https://issues.apache.org/jira/browse/IOTDB-3521)
> [IOTDB-3521] Procedure doesn't start when ConfigNode set the consensus protocol to StandAlone

- server/src/main/java/org/apache/iotdb/db/service/basic/ServiceProvider.java
- server/src/main/java/org/apache/iotdb/db/service/basic/StandaloneServiceProvider.java
- server/src/main/java/org/apache/iotdb/db/service/thrift/impl/TSServiceImpl.java
Move operation sync related from TSServiceImpl to ServiceProvider to cover all protocols, such as RPC, MQTT, and Influxdb protocol.
Test sync MQTT insertions.
> [To rel/0.13] make operation sync cover all protocols

- docs/UserGuide/API/Programming-MQTT.md
- docs/zh/UserGuide/API/Programming-MQTT.md
- example/mqtt/src/main/java/org/apache/iotdb/mqtt/MQTTClient.java
- server/src/main/java/org/apache/iotdb/db/protocol/mqtt/JSONPayloadFormatter.java
- server/src/test/java/org/apache/iotdb/db/protocol/mqtt/JSONPayloadFormatterTest.java
See [IOTDB-3388](https://issues.apache.org/jira/browse/IOTDB-3388).
Optimize JSONPayloadFormatter. Now MQTT Service could parse not only JSON object, but JSON array.
> [IOTDB-3388] Let MQTT Service could parse JSON array of existed format

- server/src/main/java/org/apache/iotdb/db/engine/compaction/CompactionScheduler.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/comparator/DefaultCompactionTaskComparatorImpl.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/cross/CrossSpaceCompactionTask.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/inner/InnerSpaceCompactionTask.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/task/AbstractCompactionTask.java
- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/TsFileManager.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/CompactionTaskComparatorTest.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/CompactionTaskManagerTest.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/cross/CrossSpaceCompactionTest.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/cross/RewriteCrossSpaceCompactionTest.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/inner/InnerCompactionEmptyTsFileTest.java
- server/src/test/java/org/apache/iotdb/db/engine/storagegroup/DataRegionTest.java
- server/src/test/java/org/apache/iotdb/db/engine/storagegroup/StorageGroupProcessorTest.java
See [IOTDB-3189](https://issues.apache.org/jira/browse/IOTDB-3189).
In present IoTDB compaction task submitted order set by the `ICompactionTaskComparator`, currently this interface only has `DefaultCompactionTaskComparator` an implementation. `DefaultCompactionTaskComparator` compares the compaction task priority with following several aspects:
- Whether the compaction priority of the system is Balance. If not, the prior one is inner space task or cross space task.
- For inner space compaction, compare whether the tasks are sequence, compaction task level,compaction files version number, total number of compaction files, and total size of compaction files
- For cross space compaction, compare the total number of files and the total size of them.
- 
Different storage groups are not …
> [IOTDB-3189] Fix compaction is not well-distributed across sgs

- udf-api/pom.xml
See JIRA: https://issues.apache.org/jira/browse/IOTDB-3544
As we want to release udf-api as a dependency jar for users, it should be packaged during the build.
> [IOTDB-3544] Packaging udf-api as dependency jar in build

- confignode/src/main/java/org/apache/iotdb/confignode/client/SyncDataNodeClientPool.java
Use try-with-resources to return client
During executing test.sh, client threads did not increase rapidly.
_test.sh_ and _suite.sql_ are attached to https://issues.apache.org/jira/browse/IOTDB-3582
> [IOTDB-3582] Fix client connections leak caused by delete storage group

- consensus/src/main/java/org/apache/iotdb/consensus/config/RatisConfig.java
When 400000 raft logs append, Ratis will ask statemachine to take a snapshot and purge the logs.
Currently, log segment size is 8MB, which means 400000 logs will add to 10000+ logs files, and purge them will take up to 10 seconds, which is longer enough to cause the current leader to step down.
Therefore, in this PR I change to segment size to 128 MB to reduce file numbers and corresponding purge time.
> [IOTDB-3584] Snapshot unstable due to segment size

- .github/workflows/standalone-it-for-mpp.yml
- integration-test/pom.xml
- integration-test/src/main/java/org/apache/iotdb/it/env/AbstractEnv.java
- integration-test/src/main/java/org/apache/iotdb/it/env/AbstractNodeWrapper.java
- integration-test/src/main/java/org/apache/iotdb/itbase/runtime/ClusterTestStatement.java
- jdbc/src/main/java/org/apache/iotdb/jdbc/Config.java
- jdbc/src/main/java/org/apache/iotdb/jdbc/IoTDBConnection.java
- jdbc/src/main/java/org/apache/iotdb/jdbc/IoTDBConnectionParams.java
- jdbc/src/main/java/org/apache/iotdb/jdbc/Utils.java
- server/src/test/java/org/apache/iotdb/db/protocol/rest/GrafanaApiServiceTest.java
- server/src/test/java/org/apache/iotdb/db/protocol/rest/IoTDBRestServiceTest.java
- server/src/test/java/org/apache/iotdb/db/script/EnvScriptIT.java
This PR fixes:
1. Add a `network_timeout` parameter in JDBC URL to init the underlying transport with a non-zero network timeout.
2. Refine integration-test/pom.xml.
3. Rename some *IT files from IT to UT.
> [IOTDB-3573] Fix IT test stucked by JDBC infinite network timeout

- server/src/main/java/org/apache/iotdb/db/engine/snapshot/SnapshotLoader.java
- server/src/main/java/org/apache/iotdb/db/engine/snapshot/SnapshotTaker.java
See [IOTDB-3589](https://issues.apache.org/jira/browse/IOTDB-3589).
Before this PR, data region takes snapshot without a directory structure, the info is stored in the filename, which is not elegant. This PR changes the way DataRegion creates snapshots which has a directory structure, and changes how DataRegion loads snapshot.
> [IOTDB-3589] Fix dataRegion cannot recover from snapshot

- server/src/main/java/org/apache/iotdb/db/engine/StorageEngineV2.java
- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/DataRegion.java
- server/src/main/java/org/apache/iotdb/db/wal/WALManager.java
- server/src/main/java/org/apache/iotdb/db/wal/allocation/FirstCreateStrategy.java
- server/src/main/java/org/apache/iotdb/db/wal/node/WALNode.java
Fix two problem:
1. Delete wal node when deleting storage group
2. Make data region deletion thread-safe
> [IOTDB-3599] Delete storage group should delete wal node when using multi-leader consensus

- confignode/src/main/java/org/apache/iotdb/confignode/manager/ConfigManager.java
- confignode/src/main/java/org/apache/iotdb/confignode/manager/ConsensusManager.java
- confignode/src/main/java/org/apache/iotdb/confignode/manager/NodeManager.java
ConsensusManager's getLeader interface returns the result for the consensusLayer. However, the consensusLayer's getLeader interface may return null when the consensusLayer is on leader election or when ConfigNode isn't added to any consensusGroup. Therefore, this PR optimizes the stability logic of the ConsensusManager's getLeader interface.
> [IOTDB-3635][IOTDB-3583] Increase the stability of the getLeader interface

- server/src/main/java/org/apache/iotdb/db/mpp/common/schematree/SchemaTree.java
- server/src/main/java/org/apache/iotdb/db/mpp/common/schematree/node/SchemaEntityNode.java
- server/src/main/java/org/apache/iotdb/db/mpp/common/schematree/node/SchemaInternalNode.java
- server/src/main/java/org/apache/iotdb/db/mpp/common/schematree/node/SchemaMeasurementNode.java
- server/src/main/java/org/apache/iotdb/db/mpp/common/schematree/node/SchemaNode.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/schema/SchemaFetchScanOperator.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/ClusterSchemaFetcher.java
- server/src/test/java/org/apache/iotdb/db/mpp/common/schematree/SchemaTreeTest.java
- server/src/test/java/org/apache/iotdb/db/mpp/execution/operator/schema/SchemaFetchScanOperatorTest.java
The byteBuffer doesn't support size extension, which is not friendly to scenarios with huge data size. 
Replace the byteBuffer usage in schemaFetcher with IOStream.
> [IOTDB-3643] Replace bytebuffer with IOStream in schemaFetcher

- confignode/src/main/java/org/apache/iotdb/confignode/client/SyncConfigNodeClientPool.java
- confignode/src/main/java/org/apache/iotdb/confignode/manager/ConsensusManager.java
1. Avoid getLeader NPE from consensusLayer
2. Using exponential retry logic in SyncConfigNodeClient
> Fix getLeader NPE and ConfigNode expension failure

- server/src/main/java/org/apache/iotdb/db/wal/node/WALNode.java
1. WAL delete thread should wait when memTable flush task is submitted or memtable is flushing.
2. WAL stop recursively calling deletion when memTables are not snapshot or flushed
> [IOTDB-3649] Fix stack overflow when deleting wal

- confignode/src/test/java/org/apache/iotdb/confignode/consensus/request/ConfigRequestSerDeTest.java
- confignode/src/test/java/org/apache/iotdb/confignode/persistence/PartitionInfoTest.java
- confignode/src/test/java/org/apache/iotdb/confignode/service/thrift/ConfigNodeRPCServiceProcessorTest.java
- node-commons/src/test/java/org/apache/iotdb/commons/partition/SerializeTest.java
- node-commons/src/test/java/org/apache/iotdb/commons/utils/ThriftCommonsSerDeUtilsTest.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/distribution/DistributionPlanner.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/distribution/SimpleFragmentParallelPlanner.java
- server/src/main/java/org/apache/iotdb/db/service/DataNode.java
- server/src/test/java/org/apache/iotdb/db/mpp/plan/plan/FragmentInstanceSerdeTest.java
- server/src/test/java/org/apache/iotdb/db/mpp/plan/plan/distribution/Util.java
- server/src/test/java/org/apache/iotdb/db/mpp/plan/scheduler/StandaloneSchedulerTest.java
- server/src/test/java/org/apache/iotdb/db/service/InternalServiceImplTest.java
- thrift-commons/src/main/thrift/common.thrift
By renaming mppDataExchangeEndPoint to mPPDataExchangeEndPoint.
We could use setMPPDataExchangeEndPoint and getMPPDataExchangeEndPoint.
> Rename mppDataExchangeEndPoint to mPPDataExchangeEndPoint in common.thrift

- README.md
- README_ZH.md
- docs/Development/ContributeGuide.md
- pom.xml
Since https://github.com/diffplug/spotless/issues/834 resolved, upgrade spotless version for suppressing jvmargs issue on JDK17+.
> upgrade spotless to fix jvmargs issue

- consensus/src/test/java/org/apache/iotdb/consensus/multileader/MultiLeaderConsensusTest.java
- server/src/assembly/resources/conf/iotdb-engine.properties
- server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
1. After the fix from @SpriCoder for PartitionCache, let's enable the partition cache
> Enable partition cache and change default size to 10000

- confignode/src/main/java/org/apache/iotdb/confignode/persistence/partition/PartitionInfo.java
When executing predelete and delete sg on partitionInfo, the target storageGroupPartitionTable will be taken from a concurrentHashMap. If the deletion is executed concurrently, the taken table may be null since there may be some thread else delete the table, which may results in NPE if there's no check.
Before invoke any interface of storageGroupPartitionTable taken from the map, check whether the table is null.
> [IOTDB-3260] Fix npe while concurrent delete storage group

- client-py/tests/test_template.py
[IOTDB-3664](https://issues.apache.org/jira/browse/IOTDB-3664) In python-client, test_template.py incidental occur the bug: “storage group is not set for current seriesPath”,  now through manual create timeseries of schema template to avoid this issue.
> [IOTDB-3664] Modify python client test code

- confignode/src/main/java/org/apache/iotdb/confignode/persistence/ClusterSchemaInfo.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/ClusterPartitionFetcher.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/execution/config/ConfigExecution.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/execution/config/executor/ClusterConfigTaskExecutor.java
- server/src/main/java/org/apache/iotdb/db/service/thrift/impl/DataNodeTSIServiceImpl.java
- server/src/main/java/org/apache/iotdb/db/utils/ErrorHandlingUtils.java
The exception handle mechanism cannot reveal the correct and clear message to client. Wrong error code and wrong message occurs.
See IOTDB-3254, IOTDB-3492
Modify some exception handling methods to help bubbling the desired message.
Fix the auto create storage group bug in ClusterPartitionFetcher.
> [IOTDB-3254][IOTDB-3492] Fix storage group related error message

- server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/ClusterPartitionFetcher.java
see [IOTDB-3548](https://issues.apache.org/jira/browse/IOTDB-3548)
The partitionCache doesn't do any exception handle while the result returned by configNode is fail. Add the related check.
1C1D，with data_replica_factor=3 and schema_replica_factor=3
> [IOTDB-3548] Fix not enough dataNode error msg

- confignode/src/main/java/org/apache/iotdb/confignode/manager/ConfigManager.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/execution/config/executor/ClusterConfigTaskExecutor.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/execution/config/executor/StandaloneConfigTaskExecutor.java
To stick with 0.13. While trying to delete non existing storage group, in other words the input path patterns doesn't match any existing storage group, message like "path not exists" should be returned.
Result
> [IOTDB-3636] Fix delete non existing sg error msg

- confignode/src/assembly/resources/conf/iotdb-confignode.properties
- confignode/src/main/java/org/apache/iotdb/confignode/conf/ConfigNodeDescriptor.java
- confignode/src/main/java/org/apache/iotdb/confignode/conf/ConfigNodeStartupCheck.java
- confignode/src/test/resources/confignode1conf/iotdb-confignode.properties
- confignode/src/test/resources/confignode2conf/iotdb-confignode.properties
- confignode/src/test/resources/confignode3conf/iotdb-confignode.properties
- docs/UserGuide/Cluster/Cluster-Setup.md
- docs/UserGuide/Reference/ConfigNode-Config-Manual.md
- docs/UserGuide/Reference/DataNode-Config-Manual.md
- docs/zh/UserGuide/Cluster/Cluster-Setup.md
- docs/zh/UserGuide/Reference/ConfigNode-Config-Manual.md
- docs/zh/UserGuide/Reference/DataNode-Config-Manual.md
- integration-test/src/main/java/org/apache/iotdb/it/env/ConfigNodeWrapper.java
- integration-test/src/main/java/org/apache/iotdb/it/env/DataNodeWrapper.java
- server/src/assembly/resources/conf/iotdb-datanode.properties
- server/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java
- server/src/test/resources/datanode1conf/iotdb-datanode.properties
- server/src/test/resources/datanode2conf/iotdb-datanode.properties
- server/src/test/resources/datanode3conf/iotdb-datanode.properties
The current name config_nodes is misleading. This pair of parameters represent only one or more target ConfigNodes that can communicate with when the node needs to join the cluster during startup. Furthermore, the modification of ConfigNode list caused by the cluster capacity expansion are controlled by internal logic. We don't need to change these parameters every time.
> [IOTDB-3687] Rename config_nodes to target_config_nodes

- confignode/src/assembly/resources/conf/iotdb-confignode.properties
- confignode/src/main/java/org/apache/iotdb/confignode/conf/ConfigNodeConfig.java
- confignode/src/main/java/org/apache/iotdb/confignode/conf/ConfigNodeDescriptor.java
- confignode/src/main/java/org/apache/iotdb/confignode/conf/ConfigNodeStartupCheck.java
- confignode/src/main/java/org/apache/iotdb/confignode/manager/ClusterSchemaManager.java
- confignode/src/main/java/org/apache/iotdb/confignode/manager/ConfigManager.java
- thrift-confignode/src/main/thrift/confignode.thrift
We add two parameters schema_region_per_data_node and  data_region_per_processor which makes the maxRegionCount configurable
> [IOTDB-3685] Create parameter schema_region_per_data_node and data_region_per_processor in ConfigNode

- server/src/main/java/org/apache/iotdb/db/wal/buffer/AbstractWALBuffer.java
- server/src/main/java/org/apache/iotdb/db/wal/buffer/WALBuffer.java
- server/src/main/java/org/apache/iotdb/db/wal/io/WALWriter.java
- server/src/main/java/org/apache/iotdb/db/wal/node/WALNode.java
- server/src/main/java/org/apache/iotdb/db/wal/utils/WALFileUtils.java
- server/src/test/java/org/apache/iotdb/db/wal/node/ConsensusReqReaderTest.java
- server/src/test/java/org/apache/iotdb/db/wal/node/WALNodeTest.java
Some outdated wal files doesn't contains search index are deleted by wal-delete thread, so FileNotFoundException may occur when searching. Fix it by searching again.
> [IOTDB-3684] Fail to read wal from wal file caused by FileNotFoundException

- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/TsFileResourceList.java
See [IOTDB-3709](https://issues.apache.org/jira/browse/IOTDB-3709).
The loop occured in TsFileResourceList is because a same TsFileResource is inserted twice.
> [To rel/0.13] [IOTDB-3709] Fix a loop occurred in TsFileResourceList, causing the query to fail and oom occurs

- server/src/main/java/org/apache/iotdb/db/wal/recover/WALRecoverManager.java
To accelerate recovery , use thread pool to recover broken tsfiles without wal.
> [IOTDB-3702] Use thread pool to recover broken tsfiles without wal

- server/src/main/java/org/apache/iotdb/db/rescon/PrimitiveArrayManager.java
- server/src/main/java/org/apache/iotdb/db/utils/datastructure/AlignedTVList.java
- server/src/main/java/org/apache/iotdb/db/utils/datastructure/BinaryTVList.java
- server/src/main/java/org/apache/iotdb/db/utils/datastructure/BooleanTVList.java
- server/src/main/java/org/apache/iotdb/db/utils/datastructure/DoubleTVList.java
- server/src/main/java/org/apache/iotdb/db/utils/datastructure/FloatTVList.java
- server/src/main/java/org/apache/iotdb/db/utils/datastructure/IntTVList.java
- server/src/main/java/org/apache/iotdb/db/utils/datastructure/LongTVList.java
- server/src/test/java/org/apache/iotdb/db/utils/datastructure/PrimitiveArrayManagerTest.java
The problem is caused by a loss of precision in converting integers to floating point numbers
> [To rel/0.13][IOTDB-3730][ISSUE-6551] ArrayIndexOutOfBounds when flushing a memtable

- server/src/main/java/org/apache/iotdb/db/rescon/PrimitiveArrayManager.java
- server/src/main/java/org/apache/iotdb/db/utils/datastructure/AlignedTVList.java
- server/src/main/java/org/apache/iotdb/db/utils/datastructure/BinaryTVList.java
- server/src/main/java/org/apache/iotdb/db/utils/datastructure/BooleanTVList.java
- server/src/main/java/org/apache/iotdb/db/utils/datastructure/DoubleTVList.java
- server/src/main/java/org/apache/iotdb/db/utils/datastructure/FloatTVList.java
- server/src/main/java/org/apache/iotdb/db/utils/datastructure/IntTVList.java
- server/src/main/java/org/apache/iotdb/db/utils/datastructure/LongTVList.java
- server/src/test/java/org/apache/iotdb/db/utils/datastructure/PrimitiveArrayManagerTest.java
The problem is caused by a loss of precision in converting integers to floating point numbers
> [IOTDB-3730][ISSUE-6551] ArrayIndexOutOfBounds when flushing a memtable

- cluster/src/main/java/org/apache/iotdb/cluster/query/reader/mult/IAssignPathPriorityMergeReader.java
- server/src/main/java/org/apache/iotdb/db/engine/cache/BloomFilterCache.java
- server/src/main/java/org/apache/iotdb/db/engine/cache/TimeSeriesMetadataCache.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/source/SeriesScanUtil.java
- server/src/main/java/org/apache/iotdb/db/query/reader/series/SeriesReader.java
- server/src/main/java/org/apache/iotdb/db/query/reader/universal/PriorityMergeReader.java
- tsfile/src/main/java/org/apache/iotdb/tsfile/file/metadata/AlignedChunkMetadata.java
- tsfile/src/main/java/org/apache/iotdb/tsfile/file/metadata/ChunkMetadata.java
- tsfile/src/main/java/org/apache/iotdb/tsfile/file/metadata/IChunkMetadata.java
- tsfile/src/main/java/org/apache/iotdb/tsfile/utils/FilePathUtils.java
Now bloomFilterCache, chunkCache and timeseriesMetadataCache is based on sg, version and compactionVersion as the key, and for now the version allows duplicates, which will cause  fetching a wrong cache.
Solution: add timestamp of TsFile in the key.
> [IOTDB-3608]Modify key of cache with new TsFile version rule

- server/src/main/java/org/apache/iotdb/db/engine/merge/recover/MergeFileInfo.java
- server/src/main/java/org/apache/iotdb/db/engine/merge/recover/MergeLogAnalyzer.java
- server/src/main/java/org/apache/iotdb/db/exception/compaction/CompactionException.java
- server/src/main/java/org/apache/iotdb/db/exception/compaction/InvalidCompactionLogException.java
See [IOTDB-3738](https://issues.apache.org/jira/browse/IOTDB-3738).
The exception occurs because we didn't make MergeLogAnalyzer compatible with old version merge log which contains the info of merge progress.
> [To rel/0.12] [IOTDB-3738] Fix ArrayIndexOutOfBoundException in recovering cross space compaction

- server/src/main/java/org/apache/iotdb/db/rescon/PrimitiveArrayManager.java
- server/src/main/java/org/apache/iotdb/db/utils/datastructure/BinaryTVList.java
- server/src/main/java/org/apache/iotdb/db/utils/datastructure/BooleanTVList.java
- server/src/main/java/org/apache/iotdb/db/utils/datastructure/DoubleTVList.java
- server/src/main/java/org/apache/iotdb/db/utils/datastructure/FloatTVList.java
- server/src/main/java/org/apache/iotdb/db/utils/datastructure/IntTVList.java
- server/src/main/java/org/apache/iotdb/db/utils/datastructure/LongTVList.java
- server/src/test/java/org/apache/iotdb/db/utils/datastructure/PrimitiveArrayManagerTest.java
The problem is caused by a loss of precision in converting integers to floating point numbers
> [To rel/0.12][IOTDB-3730][ISSUE-6551] ArrayIndexOutOfBounds when flushing a memtable

- server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/schema/SchemaQueryMergeOperator.java
see https://issues.apache.org/jira/browse/IOTDB-3750
> [IOTDB-3750] Fix NPE caused by SchemaQueryMergeOperator#next returning null

- confignode/src/main/java/org/apache/iotdb/confignode/client/AsyncDataNodeClientPool.java
- confignode/src/main/java/org/apache/iotdb/confignode/client/handlers/ConfigNodeHeartbeatHandler.java
- confignode/src/main/java/org/apache/iotdb/confignode/client/handlers/DataNodeHeartbeatHandler.java
- confignode/src/main/java/org/apache/iotdb/confignode/client/handlers/UpdateRegionRouteMapHandler.java
- confignode/src/main/java/org/apache/iotdb/confignode/manager/ConfigManager.java
- confignode/src/main/java/org/apache/iotdb/confignode/manager/NodeManager.java
- confignode/src/main/java/org/apache/iotdb/confignode/manager/load/LoadManager.java
- confignode/src/main/java/org/apache/iotdb/confignode/manager/load/heartbeat/ConfigNodeHeartbeatCache.java
- confignode/src/main/java/org/apache/iotdb/confignode/manager/load/heartbeat/DataNodeHeartbeatCache.java
- confignode/src/main/java/org/apache/iotdb/confignode/manager/load/heartbeat/INodeCache.java
- confignode/src/main/java/org/apache/iotdb/confignode/manager/load/heartbeat/NodeHeartbeatSample.java
- confignode/src/main/java/org/apache/iotdb/confignode/manager/load/heartbeat/RegionGroupCache.java
- confignode/src/main/java/org/apache/iotdb/confignode/manager/load/heartbeat/RegionHeartbeatSample.java
Update the RegionRouteMap cache in PartitionCache based on the heartbeat sample. Update algorithms are distinguished according to different routing policies:
1. For greedy policy, update RegionRouteMap when there exists some DataNodes fail down.
2. For leader policy, update RegionRouteMap when the leadership of Regions changed.
We'll see log like this when a DataNode fails down:
`2022-07-05 23:48:21,104 [pool-3-IoTDB-LoadManager-1] INFO  o.a.i.c.m.l.LoadManager:302 - Begin to broadcast RegionRouteMap: {TConsensusGroupId(type:DataRegion, id:1)=TRegionReplicaSet(regionId:TConsensusGroupId(type:DataRegion, id:1), dataNodeLocations:[TDataNodeLocation(dataNodeId:2, clientRpcEndPoint:TEndPoint(ip:127.0.0.1, port:6668), internalEndPoint:TEndPoint(ip:127.0.0.1, port:9004), …
> [IOTDB-3711] Update RegionRouteMap based on heartbeat sample

- server/src/main/java/org/apache/iotdb/db/engine/compaction/CompactionUtils.java
- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/TsFileNameGenerator.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/cross/RewriteCrossSpaceCompactionTest.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/inner/InnerSeqCompactionTest.java
In a compaction task, compaction modifications from all source files are added to the target mods file. This included duplicate modifications, resulting in a large target mods file.
The solution is to deduplicate the modifications and then write to the target mods file.
> [IOTDB-3745]Deduplicate mods of target files in compaction

- confignode/src/main/java/org/apache/iotdb/confignode/manager/PartitionManager.java
- confignode/src/main/java/org/apache/iotdb/confignode/persistence/partition/PartitionInfo.java
- confignode/src/main/java/org/apache/iotdb/confignode/persistence/partition/StorageGroupPartitionTable.java
- node-commons/src/main/java/org/apache/iotdb/commons/partition/DataPartitionTable.java
The triggering conditions for Region expansion in PartitionManager is currently redundant. Therefore, I made a little optimization:
1. Filter the unassigned Partitions
2. Calculate the Region allotment for each StorageGroups
3. Create Regions on DataNode
4. Assign new Partitions
You can get more details from the [SchemaPartition](https://apache-iotdb.feishu.cn/docs/doccnt1EO3N30PyiOgMUp0nAZZg) doc and the [DataPartition](https://apache-iotdb.feishu.cn/docs/doccnzlKpkxhuRw52P9pp6SfELf#) doc
> [IOTDB-3637] Optimize getOrCreatePartition process

- confignode/src/main/java/org/apache/iotdb/confignode/consensus/request/read/GetDataPartitionPlan.java
- confignode/src/main/java/org/apache/iotdb/confignode/consensus/request/read/GetOrCreateDataPartitionPlan.java
- confignode/src/main/java/org/apache/iotdb/confignode/consensus/request/read/GetOrCreateSchemaPartitionPlan.java
- confignode/src/main/java/org/apache/iotdb/confignode/consensus/request/read/GetSchemaPartitionPlan.java
- confignode/src/main/java/org/apache/iotdb/confignode/consensus/response/DataPartitionResp.java
- confignode/src/main/java/org/apache/iotdb/confignode/consensus/response/SchemaPartitionResp.java
- confignode/src/main/java/org/apache/iotdb/confignode/manager/ConfigManager.java
- confignode/src/main/java/org/apache/iotdb/confignode/manager/IManager.java
- confignode/src/main/java/org/apache/iotdb/confignode/service/thrift/ConfigNodeRPCServiceProcessor.java
- confignode/src/test/java/org/apache/iotdb/confignode/consensus/request/ConfigPhysicalPlanSerDeTest.java
- node-commons/src/main/java/org/apache/iotdb/commons/partition/DataPartitionTable.java
- server/src/main/java/org/apache/iotdb/db/client/ConfigNodeClient.java
- thrift-confignode/src/main/thrift/confignode.thrift
We've created SchemaPartitionTable and DataPartitionTable whose last level points to the TConsensusGroupId rather than a specific TRegionReplicaSet, in order to reduce the memory overhead for PartitionTable in both ConfigNode and DataNode. Therefore we should add getPartitionTable and getOrCreatePartitionTable interfaces to correspond these updates. And these interfaces will eventually take the place of getPartition and getOrCreatePartition.
> [IOTDB-3767] Add getPartitionTable and getOrCreatePartitionTable interfaces

- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/TsFileResource.java
Fail to rename the mods file at the second time, and compaction mods file does not rename.
**Solution**
Regardless of whether the `mods` attribute in `TsFileResource` is null or not, rename the mods file. Also rename the compaction mods file generated by deletion during compaction.
> [IOTDB-3770]Fix rename bug in TsFileResource

- confignode/src/main/java/org/apache/iotdb/confignode/consensus/response/DataNodeConfigurationResp.java
- confignode/src/main/java/org/apache/iotdb/confignode/manager/NodeManager.java
- confignode/src/main/java/org/apache/iotdb/confignode/persistence/NodeInfo.java
- confignode/src/main/java/org/apache/iotdb/confignode/service/thrift/ConfigNodeRPCServiceProcessor.java
Follow the following process for IoTDB cluster startup test:
1. Start 3C3D, Datanodes may be redirected during registration, but they always succeed
2. Shutdown DataNodes and restart, success
Then I check the logs in DataNodes:
1. For the registration:
2. For the activation:
> [IOTDB-3747] Fix log bug

- consensus/src/main/java/org/apache/iotdb/consensus/common/request/IndexedConsensusRequest.java
- consensus/src/main/java/org/apache/iotdb/consensus/multileader/MultiLeaderServerImpl.java
- consensus/src/main/java/org/apache/iotdb/consensus/multileader/logdispatcher/LogDispatcher.java
- consensus/src/main/java/org/apache/iotdb/consensus/multileader/wal/ConsensusReqReader.java
- consensus/src/test/java/org/apache/iotdb/consensus/multileader/util/FakeConsensusReqReader.java
- consensus/src/test/java/org/apache/iotdb/consensus/multileader/util/TestStateMachine.java
- server/src/main/java/org/apache/iotdb/db/consensus/statemachine/DataRegionStateMachine.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/write/InsertMultiTabletsNode.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/write/InsertNode.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/write/InsertRowsNode.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/write/InsertRowsOfOneDeviceNode.java
- server/src/main/java/org/apache/iotdb/db/wal/allocation/FirstCreateStrategy.java
- server/src/main/java/org/apache/iotdb/db/wal/node/WALFakeNode.java
- server/src/main/java/org/apache/iotdb/db/wal/node/WALNode.java
Set safely deleted search index directly in multi-leader to delete outdated wal files.
> [IOTDB-3734] Set safely deleted search index directly in multi-leader

- consensus/src/main/java/org/apache/iotdb/consensus/multileader/client/DispatchLogHandler.java
- consensus/src/main/java/org/apache/iotdb/consensus/multileader/logdispatcher/IndexController.java
- consensus/src/main/java/org/apache/iotdb/consensus/multileader/logdispatcher/LogDispatcher.java
Fix this problem by updating safely deleted search index after current sync index is updated by removeBatch.
> [IOTDB-3787] Multi-leader consensus follower's wal accumulates

- docs/zh/UserGuide/QuickStart/QuickStart.md
I have deleted a redundant symbol in the Chinese version. Copying will report an error if not removed, and the English version is correct without this symbol.
> for the Chinese version of User Guide，delete an extra symbol

- confignode/src/main/java/org/apache/iotdb/confignode/client/ConfigNodeRequestType.java
- confignode/src/main/java/org/apache/iotdb/confignode/client/DataNodeRequestType.java
- confignode/src/main/java/org/apache/iotdb/confignode/client/SyncConfigNodeClientPool.java
- confignode/src/main/java/org/apache/iotdb/confignode/client/SyncDataNodeClientPool.java
- confignode/src/main/java/org/apache/iotdb/confignode/conf/ConfigNodeRemoveCheck.java
- confignode/src/main/java/org/apache/iotdb/confignode/manager/PermissionManager.java
- confignode/src/main/java/org/apache/iotdb/confignode/procedure/env/ConfigNodeProcedureEnv.java
- confignode/src/main/java/org/apache/iotdb/confignode/service/ConfigNode.java
- confignode/src/main/java/org/apache/iotdb/confignode/service/thrift/ConfigNodeRPCServiceProcessor.java
Unify retry logic of SyncClientPool in ConfigNode
see details : https://issues.apache.org/jira/browse/IOTDB-3718
> [IOTDB-3718] Unify retry logic of SyncClientPool in ConfigNode

- server/src/main/java/org/apache/iotdb/db/engine/compaction/CompactionExceptionHandler.java
See [IOTDB-3795](https://issues.apache.org/jira/browse/IOTDB-3795)
> [IOTDB-3795] Remove setting read-only when handling compaction exception

- server/src/main/java/org/apache/iotdb/db/engine/memtable/AbstractMemTable.java
- server/src/main/java/org/apache/iotdb/db/engine/memtable/AlignedWritableMemChunk.java
- server/src/main/java/org/apache/iotdb/db/engine/memtable/AlignedWritableMemChunkGroup.java
- server/src/main/java/org/apache/iotdb/db/engine/memtable/IMemTable.java
- server/src/main/java/org/apache/iotdb/db/engine/memtable/IWritableMemChunk.java
- server/src/main/java/org/apache/iotdb/db/engine/memtable/IWritableMemChunkGroup.java
- server/src/main/java/org/apache/iotdb/db/engine/memtable/WritableMemChunk.java
- server/src/main/java/org/apache/iotdb/db/engine/memtable/WritableMemChunkGroup.java
- server/src/main/java/org/apache/iotdb/db/qp/physical/crud/InsertPlan.java
- server/src/test/java/org/apache/iotdb/db/engine/memtable/MemTableTestUtils.java
- server/src/test/java/org/apache/iotdb/db/engine/memtable/MemtableBenchmark.java
- server/src/test/java/org/apache/iotdb/db/engine/memtable/PrimitiveMemTableTest.java
- server/src/test/java/org/apache/iotdb/db/writelog/recover/LogReplayerTest.java
This issue is related to aligned time series restart recovery. For unsealed TsFile, the system performs recovery by redoing the physical plan in WAL. During the redo, columnIndexArray is generated to map the measurements in the physical plan to the measurements in the actual metadata engine.
However, if one of the aligned time series measurement has been deleted, the system will modify the physical plan based on the latest metadata, and the columnIndexArray generation is buggy. To resolve this bug, I use `failedIndices` to generate the correct mapping.
This pr contains:
* BUG FIX
* UT for TsFile recovery(LogReplayerTest is equivalent to the problem described in the issue)
> [To rel/0.13][IOTDB-3247] Recover aligned sensors after deleting timeseries, query lost data

- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/DataRegion.java
In current 0.13 version, we have a logic of blocking insert if system rejected before holding writelock. See
https://github.com/apache/iotdb/blob/203b15bae6a007416f5ad8bd40f64571b238a5d4/server/src/main/java/org/apache/iotdb/db/engine/StorageEngine.java#L608-L630
We should add the logic back to 0.14 new standalone and new cluster.
> Add back the logic of blocking insert before holding writelock

- session/src/main/java/org/apache/iotdb/session/SessionConnection.java
Jira: https://issues.apache.org/jira/projects/IOTDB/issues/IOTDB-3797
When client connects server timeout, it is better print the ip and port that the client trying to connect in error log.
> [IOTDB-3797] Print detailed info in session when connection fails

- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/StorageGroupProcessor.java
- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/TsFileResource.java
- server/src/test/java/org/apache/iotdb/db/engine/storagegroup/StorageGroupProcessorTest.java
The resource file will be reserialized every time data is deleted
When there is no device corresponding to the timeseries to be deleted in the tsfile, there will still be mods records.
**Solution**
Reserialize resource file only when `planIndex` is less then `minPlanIndex` or larger then `maxPlanIndex`.
When the device of the timeseries to be deleted is not in the tsfile, skip it and do not add mods to it.
> [To rel/0.12]Avoid serializing resource file and adding mods to file that don't contain the device when deleting data

- server/src/main/java/org/apache/iotdb/db/engine/flush/MemTableFlushTask.java
- server/src/main/java/org/apache/iotdb/db/writelog/recover/TsFileRecoverPerformer.java
Memtable's seriesNumber is 0, we need to avoid "/ by zero".
<hr>
This PR has:
<hr>
> [To rel/0.13] [IOTDB-3816] Fix /zero bug in recover

- confignode/src/main/java/org/apache/iotdb/confignode/manager/load/heartbeat/RegionGroupCache.java
Now the leader policy will broadcast RegionRouteMap only if the leadership has changed. However, if we use MultiLeader protocol, the ConfigNode-leader still broadcast RegionRouteMap continually since each Region always takes of itself as the leader.
> [IOTDB-3823] Optimize leader routing policy

- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/distribution/ExchangeNodeAdder.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/process/TransformNode.java
The TransformNode is not considered in ExchangeNodeAddr, which will lead to some planning error if the plan contains TransformNode and will be distributed in several regions.
See the test here:
> [IoTDB-3674] Fix the issue that TransformNode is not considered in ExchangeNodeAddr

- server/src/main/java/org/apache/iotdb/db/mpp/common/MPPQueryContext.java
- server/src/main/java/org/apache/iotdb/db/mpp/common/SessionInfo.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/distribution/SimpleFragmentParallelPlanner.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/FragmentInstance.java
- server/src/main/java/org/apache/iotdb/db/query/control/SessionManager.java
- server/src/test/java/org/apache/iotdb/db/mpp/plan/plan/QueryPlannerTest.java
- server/src/test/java/org/apache/iotdb/db/mpp/plan/scheduler/StandaloneSchedulerTest.java
Add weak consistency level read policy for MPP framework.
That is, the DataNode in one ConsensusGroup will be selected randomly in weak consistency level.
And on the other hand, we will try to keep the session consistency that the selected DataNode will be same for one Region from one session.
> Add weak read consistency policy for MPP

- server/src/main/java/org/apache/iotdb/db/engine/compaction/cross/rewrite/task/ReadPointPerformerSubTask.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/performer/impl/ReadPointCompactionPerformer.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/reader/IDataBlockReader.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/reader/SeriesDataBlockReader.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/fragment/FragmentInstanceContext.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/source/SeriesScanUtil.java
- server/src/main/java/org/apache/iotdb/db/query/context/QueryContext.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/ReadPointCompactionPerformerTest.java
In new MPP query framework, we create a new scan util called SeriesScanUtil and the old SeriesReader will be removed together with old standalone IoTDB.
However, current compaction still depends on the SeriesReader, we need to change it to depend on SeriesScanUtil instead.
> [IOTDB-3778] Use SeriesScanUtil in compaction for point reader

- tsfile/src/main/java/org/apache/iotdb/tsfile/read/TsFileSequenceReader.java
The catch throwalbe is intended to log the file name when file is corrupt. But we could ignore the ClosedByInterruptException.
> [To rel/0.13] [IOTDB-3813] Ignore the ClosedByInterruptException log when shutdown IoTDB

- confignode/src/main/java/org/apache/iotdb/confignode/manager/ConfigManager.java
- confignode/src/main/java/org/apache/iotdb/confignode/manager/load/LoadManager.java
- confignode/src/main/java/org/apache/iotdb/confignode/manager/load/balancer/RouteBalancer.java
- confignode/src/main/java/org/apache/iotdb/confignode/manager/load/balancer/router/IRouter.java
- confignode/src/main/java/org/apache/iotdb/confignode/manager/load/balancer/router/LeaderRouter.java
- confignode/src/main/java/org/apache/iotdb/confignode/manager/load/balancer/router/LoadScoreGreedyRouter.java
- confignode/src/main/java/org/apache/iotdb/confignode/manager/load/heartbeat/ConfigNodeHeartbeatCache.java
- confignode/src/main/java/org/apache/iotdb/confignode/manager/load/heartbeat/DataNodeHeartbeatCache.java
- confignode/src/main/java/org/apache/iotdb/confignode/manager/load/heartbeat/INodeCache.java
- confignode/src/main/java/org/apache/iotdb/confignode/service/thrift/ConfigNodeRPCServiceProcessor.java
- confignode/src/test/java/org/apache/iotdb/confignode/manager/load/balancer/router/LeaderRouterTest.java
- confignode/src/test/java/org/apache/iotdb/confignode/manager/load/balancer/router/LoadScoreGreedyRouterTest.java
We found that the realTimeRegionRoutingMap is incorrect when some DataNodes fall down. I then discovered that this bug was caused by float not being able to express the timestamp of long. Therefore I replace the unit of loadScore by long for temporary fix this bug. Finally, I also reinforce the router test to simulate the real production environment as much as possible.
> [IOTDB-3839] Fix genRealTimeRegionRoutingMap bug

- tsfile/src/main/java/org/apache/iotdb/tsfile/utils/BloomFilter.java
This bug is caused by `Math.abs(Integer.MIN_VALUE)` returning a negative number.
Avoid using hash value `Integer.MIN_VALUE` and set to 0. (as same as master version)
> [To rel/0.13][IOTDB-3858] IndexOutOfBoundsException: bitIndex < 0

- server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/schema/SchemaFetchMergeOperator.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/schema/SchemaFetchScanOperator.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/AnalyzeVisitor.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/ClusterSchemaFetcher.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/FakeSchemaFetcherImpl.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/ISchemaFetcher.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/StandaloneSchemaFetcher.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/LocalExecutionPlanner.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/LogicalPlanBuilder.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/LogicalPlanVisitor.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/metedata/read/SchemaFetchMergeNode.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/statement/internal/SchemaFetchStatement.java
- server/src/test/java/org/apache/iotdb/db/mpp/execution/operator/schema/SchemaFetchScanOperatorTest.java
The schemaPartition will change during statement execution retry, thus refactor the process of schema fetch.
Originally, the schemaParition taken by schema fetcher is to get the storage group info. Now, the storage group info is returned  as part of  the schemaFetch result.
> [IOTDB-3830] Refactor schema fetch

- server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/CompactionUtils.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/cross/rewrite/RewriteCrossSpaceCompactionSelector.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/cross/rewrite/selector/ICrossSpaceCompactionFileSelector.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/cross/rewrite/selector/RewriteCompactionFileSelector.java
- server/src/main/java/org/apache/iotdb/db/tools/validate/TsFileValidationTool.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/AbstractCompactionTest.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/cross/CrossSpaceCompactionTest.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/cross/CrossSpaceCompactionValidationTest.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/cross/RewriteCompactionFileSelectorTest.java
**Bug description:**
timeseries overlap within one page
timeseries overlap between pages
timeseries overlap between files
device overlap between files
**Reason**
The reason for the problem is that there are bugs in the process of selecting files in cross space compaction. For example, there are seq files 1 2 and unseq files 1. The timestamps of the unseq file is both smaller than those of seq files 1 2. When unseq file 1 has d1, d2 , while seq file 1 has d2 and seq file 2 has d1, d2. If seq file 2 is selected first, then file 1 will be skipped. So solution is to select both of the seq files 1 and 2.
> [IOTDB-3822]Fix cross compaction overlap bug

- server/src/test/java/org/apache/iotdb/db/utils/EnvironmentUtils.java
When I run the test class  DataNodeInternalRPCServiceImplTest 
it will occur NullPointerException at tearDownAfterClass() method
> [IOTDB-3877] Fix DataNodeInternalRPCServiceImplTest NullPointerException

- server/src/main/java/org/apache/iotdb/db/metadata/mtree/MTree.java
- server/src/test/java/org/apache/iotdb/db/metadata/MManagerBasicTest.java
- server/src/test/java/org/apache/iotdb/db/metadata/MTreeTest.java
see IOTDB-3826
The check and creation operation on device node is not locked. Although the operation of upgrading an internal node to device node is locked, different threads may take the internal node before upgrading when entering the synchronized code block, and then all the synchronized check is on the invalidate internal node. The actual device node has already been set to MTree. 
Lock the check and creation operation on device node.
> [To rel/0.13][IOTDB-3826]Fix duplicate success when concurrent creating same timeseries

- integration-test/src/test/java/org/apache/iotdb/db/it/aggregation/IoTDBAggregationIT.java
- integration-test/src/test/java/org/apache/iotdb/db/it/aligned/IoTDBAlignedSeriesQueryIT.java
- integration-test/src/test/java/org/apache/iotdb/db/it/aligned/IoTDBLastQueryWithDeletion2IT.java
- integration-test/src/test/java/org/apache/iotdb/db/it/aligned/IoTDBLastQueryWithDeletionIT.java
- server/src/main/java/org/apache/iotdb/db/metadata/path/AlignedPath.java
- server/src/main/java/org/apache/iotdb/db/metadata/path/MeasurementPath.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/process/UpdateLastCacheOperator.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/LocalExecutionPlanner.java
I redo the benchmark Q8 test, this pr's performance is much better than master and is very close to 0.13, you can see the results [here](https://apache-iotdb.feishu.cn/docx/doxcn6xEgTopkvsLsG3TXjwlx0c).
> [IOTDB-3871] Make last query be able to update last cache even if there is no other write happens after restarting

- docs/UserGuide/API/Programming-Cpp-Native-API.md
- docs/zh/UserGuide/API/Programming-Cpp-Native-API.md
C + + interface descriptions about insertRecord/insertRecords/insertRecordsOfOneDevice errors.
The interface about Data Manipulation Interface and the interface about Insert with type inference description information is upside down.
> [To rel/0.13][IOTDB-3879] Modify document about the Programming-Cpp-Native-API

- antlr/src/main/antlr4/org/apache/iotdb/db/qp/sql/IoTDBSqlParser.g4
- cluster/src/main/java/org/apache/iotdb/cluster/query/ClusterPlanExecutor.java
- docs/UserGuide/Operate-Metadata/Node.md
- docs/UserGuide/Operate-Metadata/Timeseries.md
- docs/zh/UserGuide/Operate-Metadata/Node.md
- docs/zh/UserGuide/Operate-Metadata/Timeseries.md
- integration/src/test/java/org/apache/iotdb/db/integration/IoTDBMetadataFetchIT.java
- server/src/main/java/org/apache/iotdb/db/metadata/MManager.java
- server/src/main/java/org/apache/iotdb/db/metadata/mtree/MTree.java
- server/src/main/java/org/apache/iotdb/db/metadata/mtree/traverser/collector/MNodeCollector.java
- server/src/main/java/org/apache/iotdb/db/qp/executor/PlanExecutor.java
- server/src/main/java/org/apache/iotdb/db/qp/logical/sys/ShowChildNodesOperator.java
- server/src/main/java/org/apache/iotdb/db/qp/logical/sys/ShowChildPathsOperator.java
- server/src/main/java/org/apache/iotdb/db/qp/logical/sys/ShowDevicesOperator.java
- server/src/main/java/org/apache/iotdb/db/qp/logical/sys/ShowTimeSeriesOperator.java
- server/src/main/java/org/apache/iotdb/db/qp/sql/IoTDBSqlVisitor.java
- server/src/test/java/org/apache/iotdb/db/metadata/MManagerBasicTest.java
- server/src/test/java/org/apache/iotdb/db/metadata/MTreeTest.java
There's no paging mechanism for most schema query operation, which is dangerous once querying massive schema.
1. Support limit and offset mechanism for all schema query
2. Set default page size 1000 for all schema query
> [To rel/0.13][IOTDB-3741][IOTDB-3747] Default Paging of Schema Query

- server/src/main/java/org/apache/iotdb/db/metadata/mtree/MTree.java
- server/src/main/java/org/apache/iotdb/db/metadata/mtree/traverser/Traverser.java
- server/src/main/java/org/apache/iotdb/db/metadata/mtree/traverser/collector/EntityCollector.java
- server/src/main/java/org/apache/iotdb/db/metadata/mtree/traverser/collector/MNodeCollector.java
- server/src/main/java/org/apache/iotdb/db/metadata/mtree/traverser/collector/MeasurementCollector.java
- server/src/main/java/org/apache/iotdb/db/metadata/mtree/traverser/counter/EntityCounter.java
- server/src/main/java/org/apache/iotdb/db/metadata/mtree/traverser/counter/MeasurementCounter.java
see IOTDB-3742
The node management feature is to help manage the instantiated nodes on MTree, excluding the nodes inside template. 
Since there's memory protection on schema storage, the node info won't be a heavy load to system.
Therefore, remove the node traversal logic inside template.
> [To rel/0.13][IOTDB-3742]Fix count nodes

- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/TsFileProcessor.java
- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/TsFileResource.java
- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/VirtualStorageGroupProcessor.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/cross/RewriteCrossSpaceCompactionTest.java
- server/src/test/java/org/apache/iotdb/db/engine/storagegroup/StorageGroupProcessorTest.java
1. The resource file will be reserialized every time data is deleted
2. When there is no device corresponding to the timeseries to be deleted in the tsfile, there will still be mods records.
3. For unsealed files, add records to the mods file regardless of whether the conditions are met.
**Improvements**
1. Do not reserialize the resource file, because `planIndex` will be discard in the future.
2. When the device of the timeseries to be deleted is not in the tsfile, skip it and do not add mods to it.
4. For unsealed files, the data in the work memtable will be deleted, and no records will be added to the mods file. When there is flushing memtable, it will always add deletion records to the mods file.
See more details in doc …
> [To rel/0.13][IOTDB-3775][IOTDB-3776]Avoid serializing resource file and adding mods to file that don't contain the device when deleting data

- server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/process/AggregationOperator.java
- server/src/test/java/org/apache/iotdb/db/mpp/execution/operator/AggregationOperatorTest.java
see IOTDB-3859
In the previous implementation, we only wait for the first blocked child operator to end blocking. But there may be other child operators still blocked. We need to wait for all child operators to end blocking.
> [IOTDB-3859] Fix wrong isBlocked() method implementation in AggregationOperator

- consensus/src/main/java/org/apache/iotdb/consensus/ratis/SnapshotStorage.java
Ratis requires to send snapshot file together with its md5 digest. We decide to calculate it once and store md5 in file under the snapshot dir. However, when send snapshot second time, ratis will consider these md5 file also one part of the snapshot. So we have to exclude the md5 file when fetching the latest snapshot.
> [IOTDB-3837] Exclude md5 file when get latest snapshot

- server/src/main/java/org/apache/iotdb/db/mpp/execution/QueryStateMachine.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/execution/QueryExecution.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/scheduler/ClusterScheduler.java
During recent change, we add more detailed error message when dispatching. And in this PR, we will only make the QueryExecution's retry triggered when the failure status is `SYNC_CONNECTION_EXCEPTION`
> Refine the Retry logic for QueryExecution because of Execption changed.

- confignode/src/main/java/org/apache/iotdb/confignode/persistence/partition/PartitionInfo.java
> Modified the processing of metrics for collecting the number of storage groups

- integration/src/test/java/org/apache/iotdb/db/integration/IoTDBSchemaTemplateIT.java
- server/src/main/java/org/apache/iotdb/db/metadata/mtree/MTree.java
see IOTDB-3894
The last value was cached in the measurementMNode inside template, which means different timeseries represented by one template shared the same measurementMNode instance and this mistakes the last cache value.
Since the template is only used as one level, the measurementMNode instance will be cloned and returned for last query and last cache execution.
> [To rel/0.13][IOTDB-3894]Fix last cache with template

- session/src/main/java/org/apache/iotdb/session/pool/SessionPool.java
There is a missing `return` in the interface about template set/unset, drop, deactivate and activate within `sessionPool`, which may produce duplicated operation and unexpected exception.
This PR has fixed the issue in the title, along with issue IOTDB-3905 and IOTDB-3907.
> [To rel/0.13][IOTDB-3904]fix set/unset, drop, and deactivate template api in sessionPool

- node-commons/src/main/java/org/apache/iotdb/commons/concurrent/WrappedCallable.java
- node-commons/src/main/java/org/apache/iotdb/commons/concurrent/threadpool/ScheduledExecutorUtil.java
- node-commons/src/main/java/org/apache/iotdb/commons/concurrent/threadpool/WrappedScheduledExecutorService.java
- node-commons/src/main/java/org/apache/iotdb/commons/concurrent/threadpool/WrappedSingleThreadExecutorService.java
- node-commons/src/main/java/org/apache/iotdb/commons/concurrent/threadpool/WrappedSingleThreadScheduledExecutor.java
- node-commons/src/main/java/org/apache/iotdb/commons/concurrent/threadpool/WrappedThreadPoolExecutor.java
See JIRA: https://issues.apache.org/jira/browse/IOTDB-3958 .
I refactor the WrappedCallable to make sure every task submitted to thread pool will log any uncaught exceptions.
> [IOTDB-3958] Add error logging in thread pool

- metrics/dropwizard-metrics/src/main/java/org/apache/iotdb/metrics/dropwizard/reporter/IoTDBReporter.java
- metrics/interface/src/main/java/org/apache/iotdb/metrics/utils/IoTDBMetricsUtils.java
- metrics/micrometer-metrics/src/main/java/org/apache/iotdb/metrics/micrometer/reporter/IoTDBMeterRegistry.java
In the initialization, IoTDB Reporter need to check the existence of storage group and create if not exists.
See: https://issues.apache.org/jira/browse/IOTDB-3937
> [IOTDB-3937] Fix the initialization of IoTDB Reporter in metric framework.

- server/src/main/java/org/apache/iotdb/db/auth/AuthorizerManager.java
- server/src/main/java/org/apache/iotdb/db/auth/BasicAuthorityCache.java
- server/src/main/java/org/apache/iotdb/db/auth/ClusterAuthorityFetcher.java
- server/src/main/java/org/apache/iotdb/db/auth/IAuthorCache.java
- server/src/main/java/org/apache/iotdb/db/auth/StandaloneAuthorityFetcher.java
- server/src/test/java/org/apache/iotdb/db/auth/AuthorizerManagerTest.java
1、AuthorityFetcher class is not necessary to use Singleton pattern because AuthorizerManager is already a singleton.
2、Extract the cache from the ClusterAuthorityFetcher, people can implement their cache class in their own permission model.
3、Add getAuthorCache() to IAuthorityFetcher interface, because I think every authorityFetcher should has an author cache even a standalone mode, it will avoid unnecessary I/O to the authority file.
<hr>
This PR has:
<hr>
> [IOTDB-3975]refactoring cache from authorityFetcher

- confignode/src/main/java/org/apache/iotdb/confignode/consensus/statemachine/PartitionRegionStateMachine.java
- confignode/src/main/java/org/apache/iotdb/confignode/manager/PartitionManager.java
- confignode/src/main/java/org/apache/iotdb/confignode/manager/ProcedureManager.java
- confignode/src/main/java/org/apache/iotdb/confignode/manager/load/LoadManager.java
The regionCleaner task in ConfigNode's PartitionManager will start as soon as the PartitionManager is initialized, which is unsafe however. Ever interior ScheduledExecutor should not be started until the current ConfigNode confirms it's leadership. And these inner ScheduleExecutor should be shutdown immediatly when the current ConfigNode loses it's leadership.
Test result, all ScheduledExecutor started after the current ConfigNode becomes leader:
> [IOTDB-3781] Reinforce the regionCleaner task's startup logic

- server/src/main/java/org/apache/iotdb/db/doublelive/OperationSyncPlanTypeUtils.java
Add support for create/drop, set/unset, activate/deactivate, append/prune template operation when considering whether to invoke a double-live session during process of a DDL statement.
> [To rel/0.13][IOTDB-3906][IOTDB-3921]Support template DDL under DoubleLive mode

- docs/UserGuide/Maintenance-Tools/Metric-Tool.md
- docs/zh/UserGuide/Maintenance-Tools/Metric-Tool.md
- integration/src/test/java/org/apache/iotdb/session/IoTDBSessionSimpleIT.java
- server/src/main/java/org/apache/iotdb/db/exception/metadata/MeasurementInsideTemplateException.java
- server/src/main/java/org/apache/iotdb/db/metadata/MManager.java
- server/src/main/java/org/apache/iotdb/db/metadata/mtree/MTree.java
- server/src/main/java/org/apache/iotdb/db/metadata/mtree/traverser/Traverser.java
- server/src/test/java/org/apache/iotdb/db/metadata/MManagerBasicTest.java
When delete storage group, the timeseries represent by template will be counted and the result will be used to update the timeseries statistic number. The number doesn't update when activate template. Thus the number will be negative.
Use two number to statistic template series and normal series separately.
> [To rel/0.13][IOTDB-3969]Fix timeseries statistic bug

- confignode/src/main/java/org/apache/iotdb/confignode/client/sync/confignode/SyncConfigNodeClientPool.java
2022-07-20 15:22:39,073 [main] ERROR o.a.i.c.c.s.c.SyncConfigNodeClientPool:106 - REGISTER_CONFIG_NODE failed on ConfigNode TEndPoint(ip:192.168.130.3, port:22277)
java.io.IOException: Borrow client from pool for node TEndPoint(ip:192.168.130.3, port:22277) failed.
at org.apache.iotdb.commons.client.ClientManager.borrowClient(ClientManager.java:61)
at org.apache.iotdb.confignode.client.sync.confignode.SyncConfigNodeClientPool.sendSyncRequestToConfigNodeWithRetry(SyncConfigNodeClientPool.java:73)
at org.apache.iotdb.confignode.service.ConfigNode.registerConfigNode(ConfigNode.java:195)
at org.apache.iotdb.confignode.service.ConfigNode.active(ConfigNode.java:117)
at org.apache.iotdb.confignode.service.ConfigNodeCommandLine.run(ConfigNodeCommandLine.java:75)
at …
> [IOTDB-3900] start-confignode ，Failed to execute system command

- metrics/dropwizard-metrics/src/main/java/org/apache/iotdb/metrics/dropwizard/reporter/IoTDBReporter.java
- metrics/interface/src/main/java/org/apache/iotdb/metrics/config/MetricConfig.java
- metrics/interface/src/main/java/org/apache/iotdb/metrics/utils/IoTDBMetricsUtils.java
- metrics/micrometer-metrics/src/main/java/org/apache/iotdb/metrics/micrometer/reporter/IoTDBMeterRegistry.java
- server/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java
1. Add checkOrCreateStorageGroup method to init storage group
2. Fix the update of the value of InstanceHost and Instance Port
After Fixed:（IoTDB's Port is 6666)
> [To rel/0.13][IOTDB-3937][IOTDB-3974] Fix the problem of IoTDB Reporter in metric framework

- docs/UserGuide/Maintenance-Tools/Metric-Tool.md
- docs/zh/UserGuide/Maintenance-Tools/Metric-Tool.md
- server/src/main/java/org/apache/iotdb/db/service/metrics/recorder/CompactionMetricsRecorder.java
In Prometheus, all meters with the same name need to have the same set of tag keys.
The description of problem: https://issues.apache.org/jira/browse/IOTDB-3994
> [IOTDB-3994] Fix the format of COMPACTION_TASK_COUNT metric.

- server/src/main/java/org/apache/iotdb/db/engine/compaction/CompactionUtils.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/cross/rewrite/manage/CrossSpaceCompactionResource.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/cross/rewrite/task/SubCompactionTask.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/inner/utils/InnerSpaceCompactionUtils.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/inner/utils/SingleSeriesCompactionExecutor.java
- server/src/main/java/org/apache/iotdb/db/service/IoTDB.java
- server/src/main/java/org/apache/iotdb/db/service/IoTDBShutdownHook.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/inner/InnerSpaceCompactionUtilsNoAlignedTest.java
See [IOTDB-3813](https://issues.apache.org/jira/browse/IOTDB-3813).
The reason we need to shutdown CompactionManager when we shutdown IoTDB is that, compaction threads access to meta manager during compaction. When the IoTDB shuts down, the meta manager will be terminated, at which time compaction threads may throw exception. If we remove the access to meta manager, the exception will not be thrown, and we need not to interrupt compaction threads when IoTDB shutdown.
> [To rel/0.13] [IOTDB-3813] Remove access to meta manager in compaction

- confignode/src/main/java/org/apache/iotdb/confignode/service/ConfigNode.java
> [IOTDB-3992] After the restart, previous storage groups are not marked as Metrics

- server/src/main/java/org/apache/iotdb/db/engine/compaction/cross/rewrite/RewriteCrossSpaceCompactionSelector.java
See details in [IOTDB-3927](https://issues.apache.org/jira/secure/RapidBoard.jspa?rapidView=492&projectKey=IOTDB&view=detail&selectedIssue=IOTDB-3927&quickFilter=2202).
When no files can be selected in the cross space compaction, it is not because the memory exceeds the threshold, but the seq files or unseen files are being occupied by other compaction tasks. 
In addition, even if the memory exceeds the threshold, at least one group of unseq file and its overlapping seq files will be selected.
> [IOTDB-3927]Fix incorrect cross compaction selector log

- server/src/main/java/org/apache/iotdb/db/metadata/logfile/MLogTxtWriter.java
- server/src/main/java/org/apache/iotdb/db/tools/mlog/MLogParser.java
A missing `break` produce an exception when parsing a mlog.bin while not corrupting correctness of the log. This PR fix this problem and add more `,` in `mLogTxtWrite` to make output file more human-friendly.
> [To rel/0.13]Fix mLogParser and mLogTxtWriter

- session/src/main/java/org/apache/iotdb/session/pool/SessionPool.java
There is a missing return in the interface about template set/unset, and drop within sessionPool, which may produce duplicated operation and unexpected exception.
> Fix template API in SessionPool 

- integration-test/src/test/java/org/apache/iotdb/db/it/aligned/IoTDBInsertAlignedValuesIT.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/AnalyzeVisitor.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/write/InsertMultiTabletsNode.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/write/InsertRowNode.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/write/InsertRowsNode.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/write/InsertRowsOfOneDeviceNode.java
See IOTDB-3814.
After fixing
```
IoTDB> insert into root.sg1.d1(time, s1, s2) aligned values(10, 2, 2), (11, 3, '3'), (12,12.11,false);
Msg: 411: failed to insert measurements [s2] caused by data type is not consistent, input '3', registered FLOAT
+-----------------------------+--------------+--------------+
|                         Time|root.sg1.d1.s1|root.sg1.d1.s2|
+-----------------------------+--------------+--------------+
|1970-01-01T08:00:00.010+08:00|           2.0|           2.0|
|1970-01-01T08:00:00.011+08:00|           3.0|          null|
|1970-01-01T08:00:00.012+08:00|         12.11|          null|
+-----------------------------+--------------+--------------+
Total line number = 3
It costs 0.107s
```
> [IOTDB-3814] Fix insert rows by sql with wrong data type NPE

- confignode/src/main/java/org/apache/iotdb/confignode/service/ConfigNode.java
I am very sorry that I wrote a line of code wrong in resolving the conflict of [IOTDB-3844](https://github.com/apache/iotdb/pull/6831)
The ConfigNodes can startup successfully now:
> Fix ConfigNode startup bug

- server/src/assembly/resources/conf/iotdb-datanode.properties
- server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
- server/src/main/java/org/apache/iotdb/db/service/NewIoTDB.java
Change default query execute threads to cpu cores and don't set up DataExchangeService in standalone mode.
> [IOTDB-4037] Change default query execute threads to cpu cores

- confignode/src/main/java/org/apache/iotdb/confignode/manager/NodeManager.java
- confignode/src/main/java/org/apache/iotdb/confignode/manager/load/LoadManager.java
- confignode/src/main/java/org/apache/iotdb/confignode/persistence/NodeInfo.java
> [IOTDB-4028] Npe in updateNodeLoadStatistic of LoadManager when cluster first starts.

- server/src/main/java/org/apache/iotdb/db/mpp/plan/scheduler/AbstractFragInsStateTracker.java
A simple optimization for both New-server and cluster.
Use method call rather than RPC when the instance is running locally for state tracker
Test locally:
> Use method call rather than RPC when the instance is running locally for state tracker

- session/src/main/java/org/apache/iotdb/session/SessionConnection.java
when session reconnect,some method lose verify logic.
<hr>
This PR has:
<hr>
> [To rel/0.13][IOTDB-3970]fix when session reconnect,lose verify code

- confignode/src/main/java/org/apache/iotdb/confignode/persistence/NodeInfo.java
If the leader switchover occurs on the confignode, and the remove and add operations are performed, duplicate node IDs occur.
because "nextNodeId.set(info.getLocation().getDataNodeId());",  follwer set nodeid,  
generateNextNodeId will use the same id.
IoTDB> show cluster
show cluster
+------+----------+-------+---------+-----+
|NodeID|  NodeType| Status|     Host| Port|
+------+----------+-------+---------+-----+
|     0|ConfigNode|Running|  0.0.0.0|22277|
|     1|ConfigNode|Running|  0.0.0.0|22279|
|     2|ConfigNode|Running|  0.0.0.0|22281|
|     3|  DataNode|Running|127.0.0.1| 9003|
|     4|  DataNode|Running|127.0.0.1| 9005|
|     5|  DataNode|Running|127.0.0.1| 9007|
+------+----------+-------+---------+-----+
Total line number = 6
It costs 0.476s
1. remove-datanode.sh …
> [IOTDB-4051] nodeid duplicated

- server/src/main/java/org/apache/iotdb/db/mpp/plan/scheduler/FixedRateFragInsStateTracker.java
Previously, we use the `error` log to make the debug easily and now it is unnecessary
> Disable the log in state tracker for previous debug

- confignode/src/assembly/resources/sbin/remove-confignode.sh
- confignode/src/assembly/resources/sbin/start-confignode.sh
- confignode/src/assembly/resources/sbin/stop-confignode.sh
see details in https://issues.apache.org/jira/browse/IOTDB-4056
The problem is that the conf and lib directory is different in `confignode` and `distribution`.
change codes are shown as below
---
- 1.1 start-confignode in confignode directory
- 1.2 remove-confignode in confignode directory
- 1.3 stop-confignode in confignode directory
- 2.1 start-confignode in distribution directory
- 2.2 remove-confignode in distribution directory
- 2.3 stop-confignode in distribution directory
> [IOTDB-4056] Fix the problem that could not find or load main class in shell `remove-confignode.sh`

- confignode/src/main/java/org/apache/iotdb/confignode/client/async/confignode/AsyncConfigNodeHeartbeatClientPool.java
- confignode/src/main/java/org/apache/iotdb/confignode/client/async/datanode/AsyncDataNodeClientPool.java
- confignode/src/main/java/org/apache/iotdb/confignode/client/async/datanode/AsyncDataNodeHeartbeatClientPool.java
- confignode/src/main/java/org/apache/iotdb/confignode/client/sync/datanode/SyncDataNodeClientPool.java
- confignode/src/main/java/org/apache/iotdb/confignode/conf/ConfigNodeConfig.java
- confignode/src/main/java/org/apache/iotdb/confignode/conf/ConfigNodeDescriptor.java
- confignode/src/main/java/org/apache/iotdb/confignode/service/thrift/ConfigNodeRPCService.java
- node-commons/src/main/java/org/apache/iotdb/commons/client/ClientPoolFactory.java
- node-commons/src/main/java/org/apache/iotdb/commons/conf/CommonConfig.java
- node-commons/src/main/java/org/apache/iotdb/commons/conf/CommonDescriptor.java
- server/src/main/java/org/apache/iotdb/db/client/ConfigNodeClient.java
moveConfigNodeClientPoolFactory to commons
This is to move confignodeclientpoolfactory to Commons. An optimization of renaming clientpoolfactory. Datanodeclientpoolfactory contains a special confignodeclient. It has not been decided whether to migrate
> IOTDB-4043 Unify ClientPool Factory

- consensus/src/main/java/org/apache/iotdb/consensus/config/RatisConfig.java
Currently, when leader takes a snapshot, it can purge the logs included in the snapshot. However, by default, if group contains a slow follower, leader will preserve all the raft logs this slow follower doesn't have. This will cause the log in leader accumulate and take a lot of disk space.
> [IOTDB-3871] purge log instantly when take a snapshot

- confignode/src/main/java/org/apache/iotdb/confignode/manager/ConfigManager.java
- confignode/src/main/java/org/apache/iotdb/confignode/manager/IManager.java
- confignode/src/main/java/org/apache/iotdb/confignode/service/thrift/ConfigNodeRPCServiceProcessor.java
https://issues.apache.org/jira/browse/IOTDB-4077
1.when remove DataNode, the leader ConfigNode will send region migrate task to DataNode
2. if DN finished the region migrate task, it will report result to ConfigNode, and ConfigNode will contined.
but some times,  the DataNode report region migrate result to FOLLOWER ConfigNode, so the leader ConfigNode is still waiting
> [IOTDB-4077] DataNode report region migrate result to FOLLOWER ConfigNode sometimes, the LEADER Confignode is still waiting

- confignode/src/main/java/org/apache/iotdb/confignode/manager/NodeManager.java
add handling of null pointer when NodeCacheMap doesn't find the NodeId, and set the status as  "Unknown".
> [IOTDB-4067] Handle null pointer in getRegisteredNodeInfoList

- consensus/src/main/java/org/apache/iotdb/consensus/IStateMachine.java
- server/src/main/java/org/apache/iotdb/db/consensus/statemachine/DataRegionStateMachine.java
DataRegionStateMachine has cross-disk snapshot, using a single log file to record all file paths in another disk. Under this situation, we cannot directly use this log file as snapshot and transfer to other peers. So I propose to add a interface, which can let state machine decide which files are really contained in a given snapshot.
> [IOTDB-4090] Add getLatestSnapshotFiles interface in consensus

- consensus/src/main/java/org/apache/iotdb/consensus/multileader/client/AsyncMultiLeaderServiceClient.java
- consensus/src/main/java/org/apache/iotdb/consensus/multileader/client/MultiLeaderConsensusClientPool.java
- node-commons/src/main/java/org/apache/iotdb/commons/client/AsyncBaseClientFactory.java
- node-commons/src/main/java/org/apache/iotdb/commons/client/ClientPoolFactory.java
- node-commons/src/main/java/org/apache/iotdb/commons/client/async/AsyncConfigNodeHeartbeatServiceClient.java
- node-commons/src/main/java/org/apache/iotdb/commons/client/async/AsyncConfigNodeIServiceClient.java
- node-commons/src/main/java/org/apache/iotdb/commons/client/async/AsyncDataNodeHeartbeatServiceClient.java
- node-commons/src/main/java/org/apache/iotdb/commons/client/async/AsyncDataNodeInternalServiceClient.java
- node-commons/src/main/java/org/apache/iotdb/commons/client/async/AsyncDataNodeMPPDataExchangeServiceClient.java
- node-commons/src/test/java/org/apache/iotdb/commons/client/ClientManagerTest.java
- server/src/main/java/org/apache/iotdb/db/client/DataNodeClientPoolFactory.java
1、We can view online threads：
Example：
meanwhile
2、Delete a duplicate class
AsyncDataNodeInternalServiceClientPoolFactory
> [IOTDB-4039] Unify thread-name of ClientPools

- schema-engine-rocksdb/src/main/java/org/apache/iotdb/db/metadata/schemaregion/rocksdb/RSchemaRegion.java
- server/src/main/java/org/apache/iotdb/db/metadata/schemaregion/ISchemaRegion.java
- server/src/main/java/org/apache/iotdb/db/metadata/schemaregion/SchemaRegionMemoryImpl.java
- server/src/main/java/org/apache/iotdb/db/metadata/schemaregion/SchemaRegionSchemaFileImpl.java
- server/src/main/java/org/apache/iotdb/db/mpp/common/schematree/ClusterSchemaTree.java
- server/src/main/java/org/apache/iotdb/db/mpp/common/schematree/DeviceGroupSchemaTree.java
- server/src/main/java/org/apache/iotdb/db/mpp/common/schematree/DeviceSchemaInfo.java
- server/src/main/java/org/apache/iotdb/db/mpp/common/schematree/MeasurementSchemaInfo.java
- server/src/main/java/org/apache/iotdb/db/mpp/common/schematree/visitor/SchemaTreeDeviceVisitor.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/StandaloneSchemaFetcher.java
The mechanism of schema fetch in cluster mode is not that efficient in standalone mode, comparing with that of old standalone. The main cause is the redundant process on pattern tree and schema tree.
1. Set up a data insertion specified ```DeviceGroupSchemaTree```, which only serves standalone data insertion.
2. Add an interface in schemaRegion to implement deviceInfo fetch and auto create.
The final cpu sample result is illustrated in following picture. The time consumption of schema validation decreased from 20% to only 2%.
> [IOTDB-3938] Optimize Standalone schema fetch performance

- integration/src/test/java/org/apache/iotdb/session/template/TemplateUT.java
- server/src/main/java/org/apache/iotdb/db/metadata/template/Template.java
- server/src/main/java/org/apache/iotdb/db/qp/physical/sys/CreateTemplatePlan.java
The root cause of #6937 is that the information of whether the template which has only one measurement inside is directly aligned is indeed regrettably lost within the former version of MLog. At the very begining, this information is supposed to be deduced by the structure of nested lists indicating measurement hierarchy, and the template with only one measurement was considered as a trivial case which  however occurs the issue today.
This PR added an extra constant flag `DIR_ALI_FLG` to indicate to indicate whether the template is directly aligned. The flag reuses bits which are used to indicate `schemaNames` are deprecated.  Considering the reason above and that the template with only one measurement is not that prevalent, the fix affects only few classes, while leaving other files …
> [To rel/0.13][ISSUE-6937]Add alignment flag for single measurement template

- metrics/interface/src/main/assembly/resources/conf/iotdb-metric.yml
- metrics/interface/src/main/java/org/apache/iotdb/metrics/MetricService.java
- metrics/interface/src/main/java/org/apache/iotdb/metrics/config/MetricConfig.java
- metrics/interface/src/main/java/org/apache/iotdb/metrics/config/MetricConfigDescriptor.java
- metrics/interface/src/main/java/org/apache/iotdb/metrics/predefined/IMetricSet.java
- server/src/main/java/org/apache/iotdb/db/service/metrics/MetricsService.java
- server/src/main/java/org/apache/iotdb/db/service/metrics/predefined/FileMetrics.java
- server/src/main/java/org/apache/iotdb/db/service/metrics/predefined/SystemMetrics.java
See more details: https://issues.apache.org/jira/browse/IOTDB-3980.
Use asynchronous way to collect some predefined metrics. they are `file_count`, `file_size`, `sys_disk_total_space`, `sys_disk_free_space`.
Also, I add `asyncCollectPeriodInSecond` param for use to control the task that updated the metrics above.
> [IOTDB-3980][Metric] Use asynchronous way to collect some predefined metrics.

- consensus/src/main/java/org/apache/iotdb/consensus/common/response/ConsensusWriteResponse.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/scheduler/FragmentInstanceDispatcherImpl.java
Before this change, the FragmentDispatcher may encounter NPE error when processing `writeResponse` because of TSStatus lack in the Object. 
This PR gives a check for the null variables in ConsensusWriteResponse to avoid NPE from its dependents.
**We need to refine the ConsensusWriteResponse later in the Consensus write method for each implementations to avoid null variable**
> Fix the NPE error when write failed using Ratis

- schema-engine-rocksdb/src/main/java/org/apache/iotdb/db/metadata/schemaregion/rocksdb/RSchemaRegion.java
- server/src/main/java/org/apache/iotdb/db/metadata/schemaregion/ISchemaRegion.java
- server/src/main/java/org/apache/iotdb/db/metadata/schemaregion/SchemaRegionMemoryImpl.java
- server/src/main/java/org/apache/iotdb/db/metadata/schemaregion/SchemaRegionSchemaFileImpl.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/ClusterSchemaFetcher.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/FakeSchemaFetcherImpl.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/ISchemaFetcher.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/SchemaValidator.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/StandaloneSchemaFetcher.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/write/InsertNode.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/write/InsertRowNode.java
When the timeseries does exist in system, there's no need to infer data types of an InsertNode. The redundant type infer brings performance loss.
Change the interface of schemaFetcher for schema validation. InsertNode provides a function object for schema fetcher, and it will only be invoked when auto creating schema.
> [IOTDB-4111][IOTDB-3461] Improve data type infer and auto create schema logic in schema fetcher

- docker/src/main/Dockerfile-0.13.1-node-multi-platform
use docker-buildx to  compile docker images for multi-platform
docker buildx build --platform linux/amd64,linux/arm64/v8,linux/arm/v7 -t apache/iotdb:0.13.1-node -f Dockerfile-0.13.1-node-multi-platform . --push
> add dockerfile to compile docker with multi-platform

- server/src/main/java/org/apache/iotdb/db/service/IoTDBShutdownHook.java
See [IOTDB-4034](https://issues.apache.org/jira/browse/IOTDB-4034).
The reason for this bug is the same as [PR-6788](https://github.com/apache/iotdb/pull/6788).
> [IOTDB-4034] Fix throwing compaction exception when shutting down IoTDB

- server/src/main/java/org/apache/iotdb/db/mpp/execution/exchange/LocalSourceHandle.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/exchange/MPPDataExchangeManager.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/exchange/SinkHandle.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/exchange/SourceHandle.java
We should ignore all the operations after the sinkHandle is aborted or closed. The `close` state is newly added, in some places we forgot to add its judgement.
> [IOTDB-4118] Fix SinkHandle bug

- server/src/main/java/org/apache/iotdb/db/wal/io/WALReader.java
- server/src/main/java/org/apache/iotdb/db/wal/recover/WALNodeRecoverTask.java
The last wal file may corrupt, it's better to remove it's redundant warning log.
> [IOTDB-3983] Prune inappropriate warn log in WALReader

- grafana-metrics-example/cluster/Apache IoTDB ConfigNode Dashboard v0.14.0.json
For the presentation of these indicators, if the leader of the confignode appears in the timeframe displayed by the graffana, the indicators may appear duplicated on the panel. At present, there is no good solution, which can only allow users to avoid the time of leader transformation when using it. Since the utility of this data is still greater than the cost of adjusting the grafana time frame operation that the user may have, I personally feel that it can be shown in this way for the time being.
> [IOTDB-4072] Updated the ConfigNode Dashboard to add a display of node online and offline information and the distribution of leaders

- server/src/main/java/org/apache/iotdb/db/mpp/execution/QueryState.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/QueryStateMachine.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/execution/QueryExecution.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/scheduler/ClusterScheduler.java
Before this change, we use `exeuctor` threadPool to execute the `retry()` logic. retry() will submit another dispatcher task which is also need to run by `executor` threadPool, which will lead to deadlock if so many retry() from different queries are triggered together.
In this PR, we leverage the ClientRPC thread to do the retry logic and it won't lead to the deadlock in above scenario
By the way, we change the `RETRYING` to `PENDING_RETRY` to make the state more concrete.
> [IoTDB-4118] leverage client RPC to do the retry logic rather than threadPool

- confignode/src/main/java/org/apache/iotdb/confignode/consensus/statemachine/PartitionRegionStateMachine.java
- confignode/src/main/java/org/apache/iotdb/confignode/manager/ConfigManager.java
- confignode/src/main/java/org/apache/iotdb/confignode/manager/NodeManager.java
- confignode/src/main/java/org/apache/iotdb/confignode/manager/PartitionManager.java
- confignode/src/main/java/org/apache/iotdb/confignode/manager/load/LoadManager.java
- confignode/src/main/java/org/apache/iotdb/confignode/manager/load/LoadManagerMetrics.java
- confignode/src/main/java/org/apache/iotdb/confignode/manager/load/balancer/RegionBalancer.java
- confignode/src/main/java/org/apache/iotdb/confignode/manager/load/balancer/RouteBalancer.java
- confignode/src/main/java/org/apache/iotdb/confignode/manager/load/heartbeat/ConfigNodeHeartbeatCache.java
- confignode/src/main/java/org/apache/iotdb/confignode/procedure/env/ConfigNodeProcedureEnv.java
- confignode/src/main/java/org/apache/iotdb/confignode/procedure/env/DataNodeRemoveHandler.java
The following changes will bring NodeManager, PartitionManager and LoadManager more in line with their respective functional definitions:
1. Let NodeManager maintains the heartbeat ScheduledExecutorService
2. Let NodeManager maintains the NodeCache
3. Let PartitionManager maintains the RegionGroupCache
Such that the LoadManager can focus more on the load balancing policies.
You can see the [ConfigNode framwork](https://apache-iotdb.feishu.cn/docs/doccnUzGLXivqOoNjAo8Ole3cQe#) doc for more details
> [IOTDB-4112] Decoupling heartbeat scheduled executor service from LoadManager

- server/src/main/java/org/apache/iotdb/db/metadata/cache/DataNodeSchemaCache.java
See: https://issues.apache.org/jira/browse/IOTDB-4119
> [IOTDB-4119] Fix concurrency problem when auto create schemaCacheEntry in updateLastCache method.

- docs/UserGuide/Administration-Management/Administration.md
- docs/zh/UserGuide/Administration-Management/Administration.md
- integration/src/test/java/org/apache/iotdb/db/integration/IoTDBAuthorizationIT.java
- server/src/main/java/org/apache/iotdb/db/auth/AuthorityChecker.java
- server/src/main/java/org/apache/iotdb/db/auth/authorizer/BasicAuthorizer.java
- server/src/main/java/org/apache/iotdb/db/auth/entity/Role.java
- server/src/main/java/org/apache/iotdb/db/auth/entity/User.java
- server/src/main/java/org/apache/iotdb/db/qp/executor/PlanExecutor.java
- server/src/main/java/org/apache/iotdb/db/utils/AuthUtils.java
create user, grant insert_timeseries
login new user
login root,grant read_timeseries
login newuser
> [TO rel/0.13] [IOTDB-4018] The path in the permissions contains wildcards * and ** path adaptation does not work

- confignode/src/assembly/resources/conf/iotdb-confignode.properties
- server/src/assembly/resources/conf/iotdb-datanode.properties
Authorization configuration parameters should also use in confignode.properties.
> Add Authorization parameters to confignode.properties

- node-commons/src/main/java/org/apache/iotdb/commons/partition/Partition.java
- node-commons/src/main/java/org/apache/iotdb/commons/partition/executor/SeriesPartitionExecutor.java
- schema-engine-rocksdb/src/main/java/org/apache/iotdb/db/metadata/schemaregion/rocksdb/RSchemaRegion.java
- server/src/main/java/org/apache/iotdb/db/metadata/idtable/IDTableHashmapImpl.java
- server/src/main/java/org/apache/iotdb/db/metadata/schemaregion/SchemaRegionMemoryImpl.java
- server/src/main/java/org/apache/iotdb/db/metadata/schemaregion/SchemaRegionSchemaFileImpl.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/Coordinator.java
- server/src/main/java/org/apache/iotdb/db/service/DataNode.java
- server/src/main/java/org/apache/iotdb/db/service/IoTDB.java
- server/src/main/java/org/apache/iotdb/db/service/IoTDBShutdownHook.java
The initialization of SeriesSlotExecutor in Partition seriously affects the insertion performance, causing 6% performance loss in new standalone comparing with that in old standalone.
Since the param of SeriesSlotExecutor is immutable during system running and it is stateless, the SeriesSlotExecutor is implemented as a singleton.
Remove the ```isClusterMode``` in ```IoTDB.class``` and use IoTDBConfig to store the state instead. Decouple DataNode.class from IoTDB.class
> [IOTDB-3938] Fix SeriesSlotExecutor initialization logic for insertion performance

- integration/src/test/java/org/apache/iotdb/db/integration/aligned/IoTDBDeleteTimeseriesIT.java
- server/src/main/java/org/apache/iotdb/db/engine/memtable/AbstractMemTable.java
IOTDB-4047
After fixing
```
IoTDB> insert into root.sg.d1(time,s1,s2) aligned values(1,2,3)
IoTDB> show devices
+----------+---------+
|   devices|isAligned|
+----------+---------+
|root.sg.d1|     true|
+----------+---------+
It costs 0.031s
IoTDB> delete timeseries root.sg.d1.s1
IoTDB> delete timeseries root.sg.d1.s2
IoTDB> insert into root.sg.d1(time,s1,s2) values(1,2,3)
IoTDB> show devices
+----------+---------+
|   devices|isAligned|
+----------+---------+
|root.sg.d1|    false|
+----------+---------+
It costs 0.003s
IoTDB> select * from root.** …
```
> [IOTDB-4047] Fix query NPE after change device alignment

- node-commons/src/main/java/org/apache/iotdb/commons/utils/PathUtils.java
- server/src/main/java/org/apache/iotdb/db/service/thrift/impl/ClientRPCServiceImpl.java
The wrong use of measurements check results serious performance loss in new standalone, only 50% of that of old standalone.
The wrong method causes redundant and unnecessary path split. 
Fix the measurements check methods.
> [IOTDB-3938]Fix measurements check of batch insertion

- server/src/main/java/org/apache/iotdb/db/auth/ClusterAuthorityFetcher.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/execution/config/executor/ClusterConfigTaskExecutor.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/execution/config/executor/StandaloneConfigTaskExecutor.java
[IOTDB-4150](https://issues.apache.org/jira/browse/IOTDB-4150)
If use StatementExecutionException in future.setException(), it will combine message and code as a new message, when client end outputs the exception, the client will use StatementExecutionException again so there are two error codes have been combined.
Before fix:
After fix:
> [IOTDB-4150] Client output has double error code

- confignode/src/main/java/org/apache/iotdb/confignode/manager/ConsensusManager.java
- confignode/src/main/java/org/apache/iotdb/confignode/service/thrift/ConfigNodeRPCServiceProcessor.java
- consensus/src/main/java/org/apache/iotdb/consensus/IConsensus.java
- consensus/src/main/java/org/apache/iotdb/consensus/multileader/MultiLeaderConsensus.java
- consensus/src/main/java/org/apache/iotdb/consensus/ratis/RatisConsensus.java
- consensus/src/main/java/org/apache/iotdb/consensus/standalone/StandAloneConsensus.java
- consensus/src/test/java/org/apache/iotdb/consensus/multileader/MultiLeaderConsensusTest.java
- consensus/src/test/java/org/apache/iotdb/consensus/multileader/RecoveryTest.java
- consensus/src/test/java/org/apache/iotdb/consensus/ratis/RatisConsensusTest.java
- consensus/src/test/java/org/apache/iotdb/consensus/standalone/RecoveryTest.java
- consensus/src/test/java/org/apache/iotdb/consensus/standalone/StandAloneConsensusTest.java
- server/src/main/java/org/apache/iotdb/db/service/RegionMigrateService.java
- server/src/main/java/org/apache/iotdb/db/service/thrift/impl/DataNodeInternalRPCServiceImpl.java
- server/src/test/java/org/apache/iotdb/db/service/DataNodeInternalRPCServiceImplTest.java
Currently in IConsensus, addConsensusGroup and removeConsensusGroup is  ambiguous and often cause misunderstandings. We should change its name and add a javadoc to describe its usage and implementations. 
see https://issues.apache.org/jira/browse/IOTDB-4138
> [IOTDB-4138] Refactor consensus api and add javadoc

- server/src/main/java/org/apache/iotdb/db/wal/node/WALNode.java
Add recursionTime before recursively calling deletion method. Otherwise, this method may crash because of StackOverflowError.
> [IOTDB-4155] StackOverflowError occurs when deleting wal files

- node-commons/src/main/java/org/apache/iotdb/commons/ServerCommandLine.java
- server/src/main/java/org/apache/iotdb/db/service/DataNodeServerCommandLine.java
https://issues.apache.org/jira/browse/IOTDB-4084
remove datanode by shell : remove-datanode.sh, it implements in DataNodeServerCommandLine, the class has no exit code ,so I can not use '$?' to show if the remove datanode request is accept or not
'$?' is linux shell command, it can get the last command result, if last command run succeed, '$?' is 0, if  failed ,'$?' is not 0
ex:
A. list a exit path
[root@host-XXX iotdbserver]# ls /tmp/11
/tmp/11
[root@host-XXX iotdbserver]# echo $?
0
B. list a nonexit path
[root@host-XXX iotdbserver]# ls /tmp/tmp/tmp
ls: cannot access /tmp/tmp/tmp: No such file or directory
[root@host-XXX iotdbserver]# echo $?
2
> [IOTDB-4084] remove DataNode with exit code

- antlr/src/main/antlr4/org/apache/iotdb/db/qp/sql/IoTDBSqlParser.g4
- docs/UserGuide/Administration-Management/Administration.md
- docs/zh/UserGuide/Administration-Management/Administration.md
- integration/src/test/java/org/apache/iotdb/db/integration/IoTDBAuthorizationIT.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/parser/ASTVisitor.java
- server/src/main/java/org/apache/iotdb/db/qp/sql/IoTDBSqlVisitor.java
[IOTDB-4153](https://issues.apache.org/jira/browse/IOTDB-4153)
If meet path independent privileges likes 'ALL', 'CREATE_ROLE', we cannot grant or revoke on any path except for root.**.
> [IOTDB-4153]Grant ALL privileges to different paths return privilege exists

- confignode/src/test/resources/confignode1conf/iotdb-confignode.properties
- consensus/src/main/java/org/apache/iotdb/consensus/config/MultiLeaderConfig.java
- consensus/src/main/java/org/apache/iotdb/consensus/multileader/MultiLeaderServerImpl.java
- consensus/src/main/java/org/apache/iotdb/consensus/multileader/logdispatcher/LogDispatcher.java
- server/src/assembly/resources/conf/iotdb-datanode.properties
- server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
- server/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java
- server/src/main/java/org/apache/iotdb/db/consensus/DataRegionConsensusImpl.java
Use a simple parameter to throttle the write when WAL size reaches the threshold when using MultiLeaderConsensus
> Optimize ml WAL limitation for MultiLeader

- server/src/main/java/org/apache/iotdb/db/engine/compaction/CompactionScheduler.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/constant/InnerSequenceCompactionSelector.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/constant/InnerUnsequenceCompactionSelector.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/inner/sizetiered/SizeTieredCompactionSelector.java
- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/TsFileManager.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/inner/sizetiered/SizeTieredCompactionSelectorTest.java
- server/src/test/java/org/apache/iotdb/db/engine/storagegroup/FakedTsFileResource.java
See [IOTDB-4166](https://issues.apache.org/jira/browse/IOTDB-4166).
This PR fixs this issue by submitting compaction task when there is next time partition exists, even the selected files don't meet the requirement for the file num or the file size.
> [IOTDB-4166] Fix select no files when time partition interval is too small

- confignode/src/main/java/org/apache/iotdb/confignode/manager/load/balancer/RegionBalancer.java
- confignode/src/main/java/org/apache/iotdb/confignode/persistence/partition/PartitionInfo.java
Filter the specific consensusGroupType‘s allocatedRegions so that we can focus on the specified type of region allocation.
> [IOTDB-4074] Allocate SchemaRegion and DataRegion seperately

- server/src/main/java/org/apache/iotdb/db/localconfignode/LocalConfigNode.java
If a batch insert have timestamps in two time partition slots, this bug would cause all data be inserted into the last time partition slot.
IOTDB-4152 is caused by the same reason.
> [IOTDB-4177][IOTDB-4152] Fix INSERT Failed when using SESSION_BY_RECORDS

- server/src/main/java/org/apache/iotdb/db/mpp/common/MPPQueryContext.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/ExpressionAnalyzer.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/execution/QueryExecution.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/distribution/SimpleFragmentParallelPlanner.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/scheduler/ClusterScheduler.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/scheduler/FragmentInstanceDispatcherImpl.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/scheduler/SimpleQueryTerminator.java
Before this change, when some DataNode cannot be connected, the retry logic will re-dispatch the FragmentInstance to other DataNode according to the result from `ConfigNode`. But it is not reliable sometimes when using MultiLeaderConsensus because the leader only be changed after 20s. It is not user-friendly to make the query retry waiting more than 20s for users because we actually have some other alive DataNode replicas.
In this change, I added the redirect logic in planning side to make the request try another DataNode replica according to its query process. That is, if dispatching of FragmentInstance failed for some DataNode, it will select another one DataNode who owns the same Region replicas even if the ConfigNode's result is not changed.
On the other hand, this PR fixed a bug in …
> Add query redirect logic in planning side when retrying

- node-commons/pom.xml
- server/pom.xml
#7004 removed modules `iotdb-thrift-sync` but forgot to clear `iotdb-thrift-sync` from the pom file.
> [IOTDB-4179] Clear iotdb-thrift-sync in pom file

- server/src/main/java/org/apache/iotdb/db/wal/recover/WALNodeRecoverTask.java
- server/src/main/java/org/apache/iotdb/db/wal/recover/WALRecoverManager.java
This error is caused by using absolute path because it contains "." and "..", making it not unique.
> [IOTDB-4020] Use canonical path when recovering wal

- server/src/main/java/org/apache/iotdb/db/engine/compaction/CompactionUtils.java
While ITimeIndex degrading from DeviceIndex to FileIndex, `tsFileResource.mayContainsDevice(device)` may return true even if this tsfile doesn't contain this `device`
> [To rel/0.13] [IOTDB-4194] Fix IOException happened in Compaction

- node-commons/src/main/java/org/apache/iotdb/commons/partition/SchemaPartition.java
When alter not exist timeseries path it will occurs internal server error message:
Msg: 500: [INTERNAL_SERVER_ERROR(500)] Exception occurred: "ALTER timeseries root.turbine.d1.s1 RENAME tag1 TO newTag1". executeStatement failed. null
actually, it just need to tell us paths not exist and that will be clear.
After fix：
> [IOTDB-4195]improve error message of NPE from schema partition

- server/src/main/java/org/apache/iotdb/db/mpp/plan/statement/crud/DeleteDataStatement.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/statement/crud/InsertMultiTabletsStatement.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/statement/crud/InsertRowsOfOneDeviceStatement.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/statement/crud/InsertRowsStatement.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/statement/crud/InsertTabletStatement.java
When give root.wf01.wt01 path delete_timeseries privileges, but run below sql, error occurs:
IoTDB> delete from root.ln.wf01.wt01 where time >= 1;
delete from root.ln.wf01.wt01 where time >= 1;
Msg: 602: No permissions for this operation NULL
After fix:
IoTDB> delete from root.ln.wf01.wt01 where time >= 1;
delete from root.ln.wf01.wt01 where time >= 1;
Also find cannot import csv data when giving read and insert privileges, so fix it together.
> [IOTDB-4191]delete and insert data sql do not has permission

- confignode/src/main/java/org/apache/iotdb/confignode/consensus/response/DataPartitionResp.java
- confignode/src/main/java/org/apache/iotdb/confignode/consensus/response/SchemaPartitionResp.java
- confignode/src/main/java/org/apache/iotdb/confignode/manager/ConfigManager.java
- confignode/src/main/java/org/apache/iotdb/confignode/manager/IManager.java
- confignode/src/main/java/org/apache/iotdb/confignode/service/thrift/ConfigNodeRPCServiceProcessor.java
- server/src/main/java/org/apache/iotdb/db/client/ConfigNodeClient.java
- thrift-confignode/src/main/thrift/confignode.thrift
1. remove `getSchemaPartition`, `getOrCreateSchemaPartition`, `getDataPartition`, `getOrCreateDataPartition` methods in  ConfigNodeRPCServiceProcessor.
2. modify `getSchemaPartition`, `getOrCreateSchemaPartition`, `getDataPartition`, `getOrCreateDataPartition` methods in  ConfigManager: modify the type of response of methods, remove `isContainedReplicaSet` parameter.
See more details: https://issues.apache.org/jira/browse/IOTDB-4100.
> [IOTDB-4100] remove and modify some methods in ConfigNodeRPCServiceProcessor and ConfigManager.

- server/src/main/java/org/apache/iotdb/db/mpp/execution/QueryStateMachine.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/fragment/FragmentInstanceManager.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/execution/QueryExecution.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/distribution/DistributionPlanner.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/distribution/SimpleFragmentParallelPlanner.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/distribution/WriteFragmentParallelPlanner.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/FragmentInstance.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/PlanFragment.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/SubPlan.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/scheduler/ClusterScheduler.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/scheduler/FixedRateFragInsStateTracker.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/scheduler/FragmentInstanceDispatcherImpl.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/scheduler/StandaloneScheduler.java
- server/src/main/java/org/apache/iotdb/db/service/thrift/impl/DataNodeInternalRPCServiceImpl.java
- server/src/test/java/org/apache/iotdb/db/mpp/execution/QueryStateMachineTest.java
- server/src/test/java/org/apache/iotdb/db/mpp/plan/plan/distribution/AggregationDistributionTest.java
- server/src/test/java/org/apache/iotdb/db/mpp/plan/plan/distribution/LastQueryTest.java
1. Fix the bug that the state of FragmentInstance is always printed when fetched.
2. Add the logic of FINISH judgement of Query. That is, if all the `root` instance are finished, the query can be transited to FINISHED instead of judging all the FragmentInstances.
3. Transit query into `Failed` state when some unexpected exception occurs during waiting the batch result to unblock client RPC.
4. Rename `root` to `planNodeTree` in `PlanFragment`
**Basic Test**：
> Optimize StateTracker for query

- consensus/src/main/java/org/apache/iotdb/consensus/ratis/ApplicationStateMachineProxy.java
- consensus/src/main/java/org/apache/iotdb/consensus/ratis/SnapshotStorage.java
- consensus/src/test/java/org/apache/iotdb/consensus/ratis/SnapshotTest.java
Currently, when fetching latest snapshot, RatisConsensus will visit snapshot directory by order and pick the largest term_index directory as the latest snapshot. However, this snapshot might be incomplete if state machine crashed during the middle of snapshotting. 
Thus, we have to decide whether a snapshot dir contains a complete snapshot by testing the existence of meta file (which is added to the snapshot dir last).
> [IOTDB-4027] Guarantee atomicity for latest snapshot

- integration/src/test/java/org/apache/iotdb/db/integration/IoTDBFlushQueryMergeIT.java
- node-commons/src/main/java/org/apache/iotdb/commons/path/PartialPath.java
- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/dataregion/HashVirtualPartitioner.java
- server/src/test/java/org/apache/iotdb/db/mpp/plan/plan/QueryLogicalPlanUtil.java
The hashcode computation costs a quantity of time when update last cache in new standalone data insertion process.
Rewrite the hashCode computation method.
> [IOTDB-3938] Accelerate hashcode computation of partialPath for new Standalone data insertion

- server/src/main/java/org/apache/iotdb/db/wal/recover/WALNodeRecoverTask.java
See JIRA: https://issues.apache.org/jira/browse/IOTDB-4210
If there's no suitable walFiles to recover, the recover task will end without notifying the listeners.
> [IOTDB-4210] Fix deadlock during WALNode recover

- server/src/main/java/org/apache/iotdb/db/query/executor/AggregationExecutor.java
- server/src/main/java/org/apache/iotdb/db/utils/QueryUtils.java
- server/src/test/java/org/apache/iotdb/db/integration/aggregation/IoTDBAggregationScanOrderIT.java
see [IOTDB-4215](https://issues.apache.org/jira/browse/IOTDB-4215).
> [To rel/0.12] [IOTDB-4215] Fix incorrect aggregate query results due to wrong unseq file traversal order

- consensus/src/main/java/org/apache/iotdb/consensus/IStateMachine.java
- consensus/src/main/java/org/apache/iotdb/consensus/common/Utils.java
- consensus/src/main/java/org/apache/iotdb/consensus/ratis/SnapshotStorage.java
- consensus/src/test/java/org/apache/iotdb/consensus/ratis/SnapshotTest.java
- server/src/main/java/org/apache/iotdb/db/consensus/statemachine/DataRegionStateMachine.java
DataRegionStateMachine sometimes create cross disk snapshots by recording all link paths in another disk.
Please refer to jira https://issues.apache.org/jira/browse/IOTDB-3771 and PR https://github.com/apache/iotdb/pull/6782 for more details.
I propose to support cross disk snapshots in RatisConsensus. 
Currently, Ratis list all files under given snapshot root dir and take them all as snapshot files. Now Ratis will first call `IStateMachine.getSnapshotFiles` to let statemachine decides which files should be included in the actual snapshot.  If this method returns null, Ratis will still follow the old way.
> [IOTDB-4027] Support cross disk link in RatisConsensus

- pom.xml
After this change, thrift will generates Python and Go code for session client only.
The Python and Go code for node communication is unnecessary.
> Thrift only generates Python and Go code for session client

- server/src/main/java/org/apache/iotdb/db/query/context/QueryContext.java
See [IOTDB-4225](https://issues.apache.org/jira/browse/IOTDB-4225).
The reason is that QueryContext add modification to the cache even when the modification file doesn't exist.
> [To rel/0.13][IOTDB-4225] Fix QueryContext occupy too much memory

- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/virtualSg/StorageGroupManager.java
Synchronize ready condition rather than MNode.
> [To rel/0.13][IOTDB-4222] Create data region repeatedly when concurrently deleting and creating storage groups

- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/dataregion/StorageGroupManager.java
Synchronize ready condition rather than MNode. Besides, StorageEngineV2 doesn‘t have this problem.
> [IOTDB-4222] Create data region repeatedly when concurrently deleting and creating storage groups

- antlr/src/main/antlr4/org/apache/iotdb/db/qp/sql/IdentifierParser.g4
> [IOTDB-4234] implicit definition of token PIPESERVER in parser

- server/src/main/java/org/apache/iotdb/db/query/context/QueryContext.java
See [IOTDB-4225](https://issues.apache.org/jira/browse/IOTDB-4225).
It's the same as [PR-7113](https://github.com/apache/iotdb/pull/7113)
> [IOTDB-4225] Fix QueryContext occupies too much memory

- server/src/main/java/org/apache/iotdb/db/mpp/execution/schedule/DriverTaskThread.java
- server/src/test/java/org/apache/iotdb/db/mpp/execution/schedule/DriverTaskTimeoutSentinelThreadTest.java
details can be seen in this [feishu](https://apache-iotdb.feishu.cn/docx/doxcnbUyfLosIQhnjn6kQAOceCe) doc
> [IOTDB-4235] Fix deadlock in cancel query and timeout detect thread

- confignode/src/main/java/org/apache/iotdb/confignode/manager/ConfigManager.java
- confignode/src/main/java/org/apache/iotdb/confignode/manager/NodeManager.java
- confignode/src/main/java/org/apache/iotdb/confignode/manager/PartitionManager.java
Race condition detected as follows:
1. PartitionRegionStateMachine is initialized.
2. ConsensusManager constructor is called, but not returned.
3. Inside ConsensusManager ctor, RaftServer is initialized in ConsensusManager and start election.
4. Inside ConsensusManager ctor, RaftServer is elected and notifies PartitionRegionStateMachine.
5. PartitionRegionStateMachine starts heartbeat service, which uses ConsensusManager.
6. However, in Step5, ConsensusManager Constructor is not returned, which means the ref is null. It can cause NPE
> [IOTDB-4185] Prevent RatisConsensus Start Race

- server/src/main/java/org/apache/iotdb/db/engine/snapshot/SnapshotLogger.java
See [IOTDB-4027](https://issues.apache.org/jira/browse/IOTDB-4027).
This PR check and create the parent dir for log file in the initial function of SnapshotLogger.
> [IOTDB-4027] Fix FileNotFoundException when taking snapshot

- integration-test/src/test/java/org/apache/iotdb/db/it/query/IoTDBResultSetIT.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/AnalyzeVisitor.java
After fix:
Keep table head the same in new cluster mode.
> [IOTDB-4246]select last query without schema data only return time column

- session/src/main/java/org/apache/iotdb/session/SessionConnection.java
There is a missing `setSessionId` in `SessionConnection` within api `querySchemaTemplate`. It does't turn out any exception since there is no authority check for `querySchemaTemplate` in 0.13.x, but throw exception under the check in 0.14. 
This PR fixed the issue mentioned above.
The pictures below show the difference between before and after the missing statement fixed.
Before:
After:
> [IOTDB-4262] Fix missing setSessionId when `showAllTemplates`

- confignode/src/main/java/org/apache/iotdb/confignode/manager/load/heartbeat/ConfigNodeHeartbeatCache.java
- confignode/src/main/java/org/apache/iotdb/confignode/manager/load/heartbeat/DataNodeHeartbeatCache.java
- confignode/src/main/java/org/apache/iotdb/confignode/manager/load/heartbeat/NodeHeartbeatSample.java
- node-commons/src/main/java/org/apache/iotdb/commons/cluster/NodeStatus.java
The reason why cause this bug is that, I use NodeStatus.valueOf to parse the NodeStatus code, which is incorrect. I also tested the validity of show cluster and leader shifting after one DataNode's status is changed: 
1. I started a 1C3D cluster on my local machine, where the consensus protocol of DataRegion is MultiLeader:
2. I inserted some data in three different StorageGroups in order to ensure that each DataNode has exactly one leader of DataRegion:
3. I changed one DataNode's status into Read-Only, and the result of show cluster is correct:
4. ConfigNode shifted DataRegion's leader and broadcasted the latest RegionRouteMap immediately:
> [IOTDB-4271] Fix heartbeat error after setting a DataNode's status to Read-Only

- server/src/main/java/org/apache/iotdb/db/consensus/statemachine/DataRegionStateMachine.java
Fix the issue that `DeleteDataNode` is not processed when using MultiLeaderConsensus.
Besides, other PlanNode which does not belong to InsertNode won't be processed before this PR.
**Test：**
1. Execute delete operation using client when inserting data by BenchMark.
2. Finally, I verified the result for each replica
> [IOTDB-4267]Add the logic to process other PlanNode besides InsertNode in MultiLeaderConsensus

- consensus/src/main/java/org/apache/iotdb/consensus/ratis/SnapshotStorage.java
- consensus/src/test/java/org/apache/iotdb/consensus/ratis/SnapshotTest.java
Currently RatisConsensus uses a metafile to control snapshot atomicity. That is, a metafile is added to snapshot directory last, and we judge a snapshot directory's completeness by the existence of this metafile.
Therefore, we have to guarantee this order when sending snapshot directory via network. That is, the metafile must be transmitted last.
> Guarantee Atomicity in Ratis InstallSnapshot RPC

- server/src/main/java/org/apache/iotdb/db/auth/AuthorityChecker.java
add create mult timeseries privileges, as well as add TTL in standalone mode which should be consistant with in cluster mode.
> [IOTDB-4280]no privilege when using benchmark create timeseries

- consensus/src/main/java/org/apache/iotdb/consensus/ratis/ApplicationStateMachineProxy.java
Previous code 
1. create metafile
2. judge snapshotSuccess & metafileSuccess at same time.
If the program crashes when 1 completes but 2 fails, than atomicity is affected.
> [IOTDB-4027] Ratis snapshot atomicity: Reorder

- docs/UserGuide/Write-And-Delete-Data/Delete-Data.md
- docs/zh/UserGuide/Write-And-Delete-Data/Delete-Data.md
- integration-test/src/test/java/org/apache/iotdb/db/it/IoTDBDeletionIT.java
- integration-test/src/test/java/org/apache/iotdb/db/it/aligned/IoTDBAlignedDataDeletionIT.java
- integration/src/test/java/org/apache/iotdb/db/integration/versionadaption/IoTDBDeletionVersionAdaptionIT.java
After discussion, we think we should return some warn messages and still let it return success.
If this way works, I think we should consider some pervious error codes and let these return success but with warn message because of this rule:
"It should be noted that when the deleted path does not exist, IoTDB will not prompt that the path does not exist, but that the execution is successful, because SQL is a declarative programming method. Unless it is a syntax error, insufficient permissions and so on, it is not considered an error".
Thanks!
previous:
IoTDB> delete from root.sgcc.wf01.wt01.ts0
IoTDB> delete from root.sgcc.wf01.wt01.ts0abcefg
after fix:
> [IOTDB-4202]fix delete from sql IT and user-guide

- integration-test/src/test/java/org/apache/iotdb/db/it/schema/IoTDBSchemaTemplateIT.java
- server/src/main/java/org/apache/iotdb/db/metadata/mtree/MTreeBelowSGMemoryImpl.java
If a `StroageGroupNode` being set to `StorageGroupEntityNode`, it shall be replaced by some methods. 
Before this PR, although the local variable of the node has been replaced, but the member field  `storageGroupMNode` and `store` within `MTreeBelowSGMemoryImpl` has not been updated, which turned out that some insert seemed to be lost.
This PR fixed the issue, and corresponding IT has been added.
> [IOTDB-4258]Replace StorageGroupNode inside cache member if setToEntity

- server/src/main/java/org/apache/iotdb/db/service/DataNode.java
- server/src/main/java/org/apache/iotdb/db/service/DataNodeServerCommandLine.java
Datanode PID can't be shut down completely when execute remove-datanode.sh. Now we add `System.exit(0);` in the stop method of DataNode.
```java
public void stop() {
deactivate();
try {
MetricService.getInstance().stop();
SchemaRegionConsensusImpl.getInstance().stop();
DataRegionConsensusImpl.getInstance().stop();
} catch (Exception e) {
logger.error("stop data node error", e);
}
// kill the datanode process 5 seconds later
// if remove this step, datanode process will still alive
new Thread(
() -> {
try {
TimeUnit.SECONDS.sleep(5);
} catch (InterruptedException e) {
logger.error("Meets InterruptedException in stop method of DataNode");
} finally {
System.exit(0);
}
})
.start();
}
```
before executed remove-datanode.sh
after executed remove-datanode.sh
the logs on removed datanode, and …
> [IOTDB-4219] Add system.exit(0) for the stop method of datanode

- docs/Development/HowtoContributeCode.md
- docs/UserGuide/Data-Concept/Data-Type.md
- docs/UserGuide/Data-Concept/Time-Partition.md
- docs/UserGuide/Data-Modeling/DataRegion.md
- docs/UserGuide/QuickStart/Files.md
- docs/UserGuide/QuickStart/QuickStart.md
- docs/zh/Development/HowtoContributeCode.md
- docs/zh/UserGuide/Data-Concept/Data-Type.md
- docs/zh/UserGuide/Data-Concept/Time-Partition.md
- docs/zh/UserGuide/Data-Modeling/DataRegion.md
- docs/zh/UserGuide/QuickStart/Files.md
In #6460 Config-Manual.md was renamed DataNode-Config-Manual.md. This makes Config-Manual.md unavailable.
> [Doc] Fix unavailable references

- confignode/src/main/java/org/apache/iotdb/confignode/persistence/partition/PartitionInfo.java
- docs/UserGuide/Maintenance-Tools/Metric-Tool.md
- docs/zh/UserGuide/Maintenance-Tools/Metric-Tool.md
data_written
data_read
compaction_task_count
jvm_classes_unloaded_classes_total
jvm_compilation_time_ms_total
quantity{name="storageGroup"}
“ storage_group{name="number",} 1.0 ” is modified to “ quantity{name="storageGroup",} 2.0 ”
> UpdateUserGuide And Update storageGroupCount

- server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
- server/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java
- server/src/main/java/org/apache/iotdb/db/service/DataNode.java
The init of IoTDBConfig is always before the DataNode cluster mode init, which results in the schema memory is always allocated  as the default config for standalone mode, 8:1:0:1 for schema region, schema cache, partition cache and last cache.
Recheck and update schema memory allocation when DataNode init the cluster config.
> [IOTDB-4298] Fix schema memory allocate for cluster

- influxdb-protocol/src/main/java/org/apache/iotdb/influxdb/session/InfluxDBSession.java
- server/src/main/java/org/apache/iotdb/db/client/ConfigNodeClient.java
- session/src/main/java/org/apache/iotdb/session/SessionConnection.java
We have written an SSL transport, which risks being opened repeatedly. The judgment is made in jdbconnection, and no problem occurs.
> Fix transport open bug

- integration-test/src/test/java/org/apache/iotdb/db/it/schema/IoTDBSchemaTemplateIT.java
- server/src/main/java/org/apache/iotdb/db/metadata/mtree/MTreeBelowSGMemoryImpl.java
When querying for paths using template, DataNode will traverse the tree of MNodes and call method `getSchemaTemplateId` on every nodes accessed ignoring whether it is a measurement, which may throw an `RuntimeException` since measurement node cannot set or using any template.
This PR handled the situation by an extra `if statement`, and fixed related methods which works in standalone mode as well.
Corresponding issue on rel/0.13 had been fixed previously.
> [IOTDB-4275]Handle measurement when traversing for paths using template

- integration/src/test/java/org/apache/iotdb/session/IoTDBSessionInsertNullT.java
- service-rpc/src/main/java/org/apache/iotdb/rpc/NoValidValueException.java
- session/src/main/java/org/apache/iotdb/session/Session.java
Using the following session API, a null value exception will be reported when we pass a null value
insertRecord,
insertAlignedRecord,
insertRecords,
insertAlignedRecords,
insertRecordsOfOneDevice,
insertAlignedRecordsOfOneDevice,
insertStringRecordsOfOneDevice,
insertAlignedStringRecordsOfOneDevice
solution:
1. When the passed part is null, remove the inserted data for the null part
2. When all the null values passed in are null, the WARNING log is printed and nothing else is done
<hr>
This PR has:
<hr>
> [IOTDB-4278] null value processing to the Session API

- consensus/src/main/java/org/apache/iotdb/consensus/exception/NodeReadOnlyException.java
- consensus/src/main/java/org/apache/iotdb/consensus/ratis/RatisConsensus.java
When receiving a write request from upper layer, RatisConsensus should see whether current Peer
1. is in ReadOnly state.
2. is leader of the given group.
If the above two conditions both hold, reject the write request and fail immediately.
> [IOTDB-4137] Reject write when Peer in ReadOnly state in RatisConsensus

- server/src/main/java/org/apache/iotdb/db/engine/snapshot/SnapshotLoader.java
See [IOTDB-4337](https://issues.apache.org/jira/browse/IOTDB-4337).
The reason for this bug is that SnapshotLoader does not remove origin data files before moving the snapshot files to the data dirs.
> [IOTDB-4337] Fix failed to query data after loading snapshot from other node

- confignode/src/assembly/resources/conf/iotdb-confignode.properties
- confignode/src/main/java/org/apache/iotdb/confignode/conf/ConfigNodeConfig.java
- confignode/src/main/java/org/apache/iotdb/confignode/conf/ConfigNodeDescriptor.java
- confignode/src/main/java/org/apache/iotdb/confignode/conf/ConfigNodeStartupCheck.java
- node-commons/src/main/java/org/apache/iotdb/commons/exception/ConfigurationException.java
- node-commons/src/main/java/org/apache/iotdb/commons/utils/NodeUrlUtils.java
- server/src/assembly/resources/conf/iotdb-datanode.properties
- server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
- server/src/main/java/org/apache/iotdb/db/conf/IoTDBStartCheck.java
- server/src/main/java/org/apache/iotdb/db/service/DataNode.java
We make some constraints on node ip addresses:
1. DataNode's rpc_address: could set 0.0.0.0, 127.0.0.1 or ipv4 address(default is 0.0.0.0)
2. DataNode's internal_address: could set 0.0.0.0, 127.0.0.1 or ipv4 address(default is 0.0.0.0)
3. DataNode's target_config_nodes: the ip should never be 0.0.0.0(default is 127.0.0.1)
4. ConfigNode's internal_address: could set 0.0.0.0, 127.0.0.1 or ipv4 address(default is 0.0.0.0)
5. ConfigNode's target_config_nodes: the ip should never be 0.0.0.0(default is 127.0.0.1)
I performed some simple tests on my local machine:
1. Start 1C1D with default configuration, success:
2. Start 1C1D with rpc_address and internal_address set to 127.0.0.1, success:
3. Start 1C with target_config_nodes set to 0.0.0.0, failed:
4. Start 1C1D with DataNode's …
> [IOTDB-4223] Maintain default node ip config

- node-commons/src/main/java/org/apache/iotdb/commons/path/PartialPath.java
- node-commons/src/test/java/org/apache/iotdb/commons/path/PartialPathTest.java
* `PatialPath#overlapWith` supports MULTI_LEVEL_PATH_WILDCARD in PatialPath.
* Add UT case for `PatialPath#overlapWith`.
> [IOTDB-4352] PatialPath#overlapWith supports MULTI_LEVEL_PATH_WILDCARD

- server/src/main/java/org/apache/iotdb/db/protocol/rest/handler/PhysicalPlanConstructionHandler.java
When using the API tool to execute the REST API test, when writing data through the interface rest/v1/insertTablet, the BOOLEAN type is written through 1 and 0, and finally the result is abnormal.
> [To rel/0.13][IOTDB-4318][RESTAPI]when writing data through the interface rest/v1/insertTablet ,data type conversion failed 

- node-commons/src/main/java/org/apache/iotdb/commons/path/PartialPath.java
Use dynamic programming algorithm to optimize recursive algorithm:
* O(n) without `MULTI_LEVEL_PATH_WILDCARD`
* O(n^2) with  `MULTI_LEVEL_PATH_WILDCARD`
> [IOTDB-4352] Optimize PatialPath#overlapWith with MULTI_LEVEL_PATH_WILDCARD

- server/src/main/java/org/apache/iotdb/db/utils/datastructure/AlignedTVList.java
- server/src/main/java/org/apache/iotdb/db/utils/datastructure/BinaryTVList.java
- server/src/main/java/org/apache/iotdb/db/utils/datastructure/BooleanTVList.java
- server/src/main/java/org/apache/iotdb/db/utils/datastructure/DoubleTVList.java
- server/src/main/java/org/apache/iotdb/db/utils/datastructure/FloatTVList.java
- server/src/main/java/org/apache/iotdb/db/utils/datastructure/IntTVList.java
- server/src/main/java/org/apache/iotdb/db/utils/datastructure/LongTVList.java
- server/src/main/java/org/apache/iotdb/db/utils/datastructure/TVList.java
- server/src/main/java/org/apache/iotdb/db/utils/datastructure/TimAlignedTVList.java
- server/src/main/java/org/apache/iotdb/db/utils/datastructure/TimBinaryTVList.java
- server/src/main/java/org/apache/iotdb/db/utils/datastructure/TimBooleanTVList.java
- server/src/main/java/org/apache/iotdb/db/utils/datastructure/TimDoubleTVList.java
- server/src/main/java/org/apache/iotdb/db/utils/datastructure/TimFloatTVList.java
- server/src/main/java/org/apache/iotdb/db/utils/datastructure/TimIntTVList.java
- server/src/main/java/org/apache/iotdb/db/utils/datastructure/TimLongTVList.java
- server/src/main/java/org/apache/iotdb/db/utils/datastructure/TimSort.java
- server/src/test/java/org/apache/iotdb/db/utils/datastructure/BinaryTVListTest.java
- server/src/test/java/org/apache/iotdb/db/utils/datastructure/BooleanTVListTest.java
- server/src/test/java/org/apache/iotdb/db/utils/datastructure/DoubleTVListTest.java
- server/src/test/java/org/apache/iotdb/db/utils/datastructure/FloatTVListTest.java
- server/src/test/java/org/apache/iotdb/db/utils/datastructure/IntTVListTest.java
- server/src/test/java/org/apache/iotdb/db/utils/datastructure/LongTVListTest.java
- server/src/test/java/org/apache/iotdb/db/utils/datastructure/VectorTVListTest.java
restructure TVList: Pull Timsort out of the structure and make it a separate interface
The final design is like TVList<-IntTVList<-TimIntTVList/QuickIntTVList/BackwardIntTVList
<hr>
This PR has:
<hr>
> [IOTDB-4346] restructure TVList, add TimSort interface

- server/src/main/java/org/apache/iotdb/db/engine/snapshot/SnapshotTaker.java
- server/src/test/java/org/apache/iotdb/db/engine/snapshot/IoTDBSnapshotTest.java
See [IOTDB-4348](https://issues.apache.org/jira/browse/IOTDB-4348).
The reason for this bug is that, the writing process of IoTDB does not stop when taking snapshot, which causes the SnapshotTaker gets the unclosed TsFileResource. The SnapshotTaker tries to create hard link for the resource file, while the unclosed tsfile doesn't have one. Then it comes to a NoSuchFileException.
> [IOTDB-4348] Fix NoSuchFileException when taking snapshot

- docs/UserGuide/QuickStart/QuickStart.md
- docs/zh/UserGuide/QuickStart/QuickStart.md
In the start IoTDB command:
-rpc_port :The specified port number does not take effect.
-c: The specified conf file path takes effect.
> Delete information about rpc_port in UserGuide

- README.md
- README_ZH.md
- docs/UserGuide/QuickStart/QuickStart.md
- docs/zh/UserGuide/QuickStart/QuickStart.md
In the start IoTDB command:
-rpc_port :The specified port number does not take effect
-c: The specified conf file path takes effect
> Rel/0.13-Delete information about rpc_port in UserGuide

- server/src/main/java/org/apache/iotdb/db/engine/memtable/AlignedWritableMemChunk.java
- tsfile/src/main/java/org/apache/iotdb/tsfile/write/chunk/AlignedChunkWriterImpl.java
Comparative experiment before and after this PR:
- Configuration of benchmark
- Storage_group = 10
- DB_SWITCH=IoTDB-013-SESSION_BY_TABLET
- Device_num = 50
- Sensor_num = 500
- Insert_data_type = 1:1:1:1:1:1(boolean:int:long:float:double:Text)
- VECTOR = True
- Configuration of IoTDB Server
- enable_seq_space_compaction=false
- enable_unseq_space_compaction=false
- enable_cross_space_compaction=false
- write_read_schema_free_memory_proportion=7:1:1:1
- flush_proportion=0.7
- memtable_size_threshold=1073741824(default)
- avg_series_point_number_threshold=1000/5000/10000
1. avg_series_point_number_threshold=1000
before 17578533.54 points/s
after 19968317.28 points/s
2. avg_series_point_number_threshold=5000
before 17939349.93 points/s
after 20227324.97 points/s
3. …
> [IOTDB-4036] Encode aligned memory chunk in columnar format

- server/src/main/java/org/apache/iotdb/db/engine/compaction/CompactionUtils.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/cross/rewrite/task/SubCompactionTask.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/inner/utils/MultiTsFileDeviceIterator.java
- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/TsFileResource.java
- tsfile/src/main/java/org/apache/iotdb/tsfile/file/metadata/TimeseriesMetadata.java
- tsfile/src/main/java/org/apache/iotdb/tsfile/read/TsFileDeviceIterator.java
- tsfile/src/main/java/org/apache/iotdb/tsfile/read/TsFileSequenceReader.java
In massive timeseries scenarios, each device has 20 timeseries, and each file has tens of thousands of devices, that is, millions of timeseries. Read throughput in cross compaction is 100~1000 times greater than write throughput.
**Solution**
When compacting, it is necessary to obtain devices and timeseries from all source files, as well as the metadata of each timeseries. To avoid traversing the Zesong tree multiple times, we record the intermediate nodes of the Zesong tree. Please refer to [IOTDB-4364](https://issues.apache.org/jira/browse/IOTDB-4364) for the experimental results.
> [To rel/0.13][IOTDB-4364]Reduce read amplication in compaction

- server/src/main/java/org/apache/iotdb/db/utils/TypeInferenceUtils.java
- server/src/test/java/org/apache/iotdb/db/utils/TypeInferenceUtilsTest.java
Fix wrong integer upper bound about data type inferring of timeseries. According to userdoc, it should be 2^24, not 2^25.
> [IOTDB-4245] Fix wrong integer upper bound about data type inferring of timeseries

- confignode/src/main/java/org/apache/iotdb/confignode/consensus/statemachine/PartitionRegionStateMachine.java
- consensus/src/main/java/org/apache/iotdb/consensus/IStateMachine.java
- consensus/src/test/java/org/apache/iotdb/consensus/ratis/TestUtils.java
- server/src/main/java/org/apache/iotdb/db/consensus/statemachine/BaseStateMachine.java
- server/src/main/java/org/apache/iotdb/db/consensus/statemachine/DataRegionStateMachine.java
- server/src/main/java/org/apache/iotdb/db/consensus/statemachine/SchemaRegionStateMachine.java
To guarantee consistency in RatisConsensus, we should retry some failed apply write result.
refer to design doc: https://apache-iotdb.feishu.cn/docx/doxcnj0pH6Jm9pFWEEexa4opdXb
> [IOTDB-4403] Add retry interface for IStateMachine

- server/src/main/java/org/apache/iotdb/db/engine/compaction/cross/rewrite/selector/RewriteCompactionFileSelector.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/cross/rewrite/task/RewriteCrossSpaceCompactionTask.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/cross/RewriteCompactionFileSelectorTest.java
See [IOTDB-4451](https://issues.apache.org/jira/browse/IOTDB-4451).
> [To rel/0.13] [IOTDB-4451] Add log for cross space compaction selection when a file has been compacted too many times

- server/src/main/java/org/apache/iotdb/db/service/metrics/predefined/SystemMetrics.java
`File.listroots()` can't get all root disks in machine.
See: https://issues.apache.org/jira/browse/IOTDB-4395
> [IOTDB-4395] fix size statistic of disk.

- tsfile/src/main/java/org/apache/iotdb/tsfile/read/common/TimeRange.java
- tsfile/src/test/java/org/apache/iotdb/tsfile/read/common/TimeRangeTest.java
The original implementation used the result value calculated by `this.min - r.min` or`this.max - r.max`. This may encounter Long type overflow.
> [IOTDB-4453] Fix the overflow of compareTo in TimeRange

- server/src/assembly/resources/conf/iotdb-datanode.properties
- server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
- server/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java
support config MAX_PLAN_NODE_SIZE in datanode.properties
`# max plan node size, note that thrift max frame size must be larger than max plan node size.`
`# Datatype: int`
`# max_plan_node_size=536870912`
> [IOTDB-3656] mpp load with supporting modify MAX_PLAN_NODE_SIZE

- server/src/assembly/resources/conf/iotdb-datanode.properties
- server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
- server/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/ClusterPartitionFetcher.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/load/LoadTsFilePieceNode.java
problem:
Transporting frame size of LoadTsFilePieceNode is larger than MAX FRAME SIZE
too much log info of LoadTsFilePieceNode
solution:
set the max data size of LoadTsFilePieceNode is the half of MAX FRAME SIZE
delete info about chunk data.
> [IOTDB-4469] Frame size larger than protect max size!

- server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/schema/NodePathsConvertOperator.java
fix show child nodes failed issue, the fragment instance exec has exception:
Failed to execute fragment instance 20220919_014959_00084_3.1.0 | org.apache.iotdb.db.mpp.execution.driver.Driver (Driver.java:199) 
java.lang.IllegalStateException: Declared positions (1) does not match column 1's number of entries (0)
at org.apache.iotdb.tsfile.read.common.block.TsBlockBuilder.build(TsBlockBuilder.java:310)
at org.apache.iotdb.db.mpp.execution.operator.schema.NodePathsConvertOperator.next(NodePathsConvertOperator.java:99)
at org.apache.iotdb.db.mpp.execution.driver.Driver.processInternal(Driver.java:192)
at org.apache.iotdb.db.mpp.execution.driver.Driver.lambda$processFor$1(Driver.java:131)
at org.apache.iotdb.db.mpp.execution.driver.Driver.tryWithLock(Driver.java:277)
at …
> [IOTDB-4435] Fix show child nodes failed

- server/src/main/java/org/apache/iotdb/db/query/control/SessionManager.java
When session has expired, the error code is incorrect:
IoTDB > select s_70, top_k(s_70, 'k'='2'), bottom_k(s_70, 'k'='2') from root.test.g_19.d_59 where time > 2018-05-21T08:40:25.976+08:00;
Msg: 303: Check metadata error: Input time format 2018-05-21T08:40:25.976+08:00 error. Input like yyyy-MM-dd HH:mm:ss, yyyy-MM-ddTHH:mm:ss or refer to user document for more info.
It happens on zoneId is null when session has expired and occurs NPE when we get org.apache.iotdb.db.qp.utils.DatetimeUtils#toZoneOffset().
> [IOTDB-4466]error code is incorrect in query with time when session has expired

- server/src/main/java/org/apache/iotdb/db/engine/compaction/cross/rewrite/task/ReadPointPerformerSubTask.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/inner/utils/MultiTsFileDeviceIterator.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/performer/impl/ReadPointCompactionPerformer.java
- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/TsFileResource.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/AbstractCompactionTest.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/ReadPointCompactionPerformerTest.java
- tsfile/src/main/java/org/apache/iotdb/tsfile/file/metadata/TimeseriesMetadata.java
- tsfile/src/main/java/org/apache/iotdb/tsfile/read/TsFileDeviceIterator.java
- tsfile/src/main/java/org/apache/iotdb/tsfile/read/TsFileSequenceReader.java
- tsfile/src/main/java/org/apache/iotdb/tsfile/utils/TsFileGeneratorUtils.java
In massive timeseries scenarios, each device has 20 timeseries, and each file has tens of thousands of devices, that is, millions of timeseries. Read throughput in cross compaction is 100~1000 times greater than write throughput.
**Solution**
When compacting, it is necessary to obtain devices and timeseries from all source files, as well as the metadata of each timeseries. To avoid traversing the Zesong tree multiple times, we record the intermediate nodes of the Zesong tree. Please refer to [IOTDB-4364](https://issues.apache.org/jira/browse/IOTDB-4364) for the experimental results.
> [IOTDB-4364]Reduce read amplication in compaction

- integration-test/src/test/java/org/apache/iotdb/db/it/schema/IoTDBDeleteTimeseriesIT.java
- server/src/main/java/org/apache/iotdb/db/service/thrift/impl/DataNodeInternalRPCServiceImpl.java
The input path patterns may cross different storage groups. SchemaRegion doesn't need to execute unrelated path pattern.
Before executing in schemaRegion, filter out all path patterns that overlap with schemaRegion's storage group pattern.
> [IOTDB-4479] Add pattern overlap check when deleting timeseries

- confignode/src/assembly/resources/conf/iotdb-confignode.properties
- confignode/src/main/java/org/apache/iotdb/confignode/conf/ConfigNodeConfig.java
- confignode/src/main/java/org/apache/iotdb/confignode/conf/ConfigNodeDescriptor.java
- confignode/src/main/java/org/apache/iotdb/confignode/manager/NodeManager.java
- server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
- server/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java
- server/src/main/java/org/apache/iotdb/db/consensus/DataRegionConsensusImpl.java
- thrift-confignode/src/main/thrift/confignode.thrift
Currently, there are many config parameters available for RatisConsensus. All params can refer to `RatisConfig`.
In this PR, I propose to expose **workload-related** params in confignode.properties so that the user can tune these params according to their workloads.
1. ratis_snapshot_trigger_threshold, determine how many logs written to trigger a snapshot.
2. ratis_log_unsafe_flush_enable, determine whether we can flush raft log asynchronous without wait FileChannel.force to return.
3. ratis_log_segment_size_max, determine max capacity of a single Raft Log segment.
4. ratis_grpc_flow_control_window, determine gRPC log appender's flow control window size
5. ratis_rpc_leader_election_timeout_min_ms, determine min election timeout
6. ratis_rpc_leader_election_timeout_max_ms, determine max …
> [IOTDB-4478] [Ratis] Add RatisConsensus config parameters in confignode.properties

- server/src/main/java/org/apache/iotdb/db/query/control/SessionTimeoutManager.java
When session_timeout_threshold is set, SessionTimeoutManager will continue output cleaning log and check cleanup() function even though there is not session exist. So add a judgment before it to save printing redundancy log.
> print redundancy clean session log when no session exist

- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/LogicalPlanBuilder.java
We find there are no need to deduplicate path in planSchemaFetchSource.
**Tests:**
**ENV:** 5 DEVICES and 10000 SENSOR each.
Before this PR:
After this PR:
> [IOTDB-4449][IOTDB-4450] Optimize SchemaFetch

- consensus/src/main/java/org/apache/iotdb/consensus/common/request/BatchIndexedConsensusRequest.java
- consensus/src/main/java/org/apache/iotdb/consensus/multileader/logdispatcher/LogDispatcher.java
- consensus/src/main/java/org/apache/iotdb/consensus/multileader/service/MultiLeaderRPCServiceProcessor.java
- server/src/main/java/org/apache/iotdb/db/consensus/statemachine/DataRegionStateMachine.java
- thrift-multi-leader-consensus/src/main/thrift/mutlileader.thrift
Before this change, the `CacheQueue` is shared in follower side because we thought there is only one sender at the same time. 
Let's say we have 3 peers named A、B、C. From our test, we found that sometimes the leader may changed occasionally between A and B. And C's cache queue may be shared by the requests from both A and B, which will led to out-of-order data with large time range overlap.
We use separate cache queue to solve this issue.
**Write Speed Test:**
> [IOTDB-4392] build separate cache queue for MultiLeader log sync

- confignode/src/main/java/org/apache/iotdb/confignode/manager/partition/PartitionManager.java
- consensus/src/main/java/org/apache/iotdb/consensus/multileader/MultiLeaderServerImpl.java
See: https://issues.apache.org/jira/browse/IOTDB-4493
> [IOTDB-4493] Fix null message in TSStatus.

- server/src/main/java/org/apache/iotdb/db/mpp/common/MPPQueryContext.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/execution/QueryExecution.java
Before this change, the FragmentId of ResultHandle won't change when retrying, which will lead to conflicts in DataBlockManager.
> Reset ResultHandleContext before retry

- integration-test/src/main/java/org/apache/iotdb/it/framework/IoTDBTestReporter.java
In some CI environment, if integraiton-test is skipped, the test reporter will still run and fail by lacking of the integration test output directory.
> Test reporter will never fail due to path

- server/src/main/java/org/apache/iotdb/db/engine/compaction/task/CompactionRecoverTask.java
- tsfile/src/main/java/org/apache/iotdb/tsfile/write/writer/TsFileIOWriter.java
- tsfile/src/test/java/org/apache/iotdb/tsfile/write/writer/TsFileIOWriterMemoryControlTest.java
See [IOTDB-4518](https://issues.apache.org/jira/browse/IOTDB-4518).
Temporal files for chunk metadata should be deleted in `TsFileIOWriter::endFile`.
> [IOTDB-4518] Fix cannot delete .cmt file in disk

- server/src/main/java/org/apache/iotdb/db/engine/snapshot/SnapshotTaker.java
When we use snapshot to backup data, when a snapshotTsFile already has a hard link and point to the same tsfile, it will occurs FileAlreadyExistsException. So each time when we do hard link function, we need to check and delete.
> [IOTDB-4501]fix FileAlreadyExistsException when taking snapshot

- server/src/main/java/org/apache/iotdb/db/metadata/path/MeasurementPath.java
- server/src/main/java/org/apache/iotdb/db/metadata/visitor/SchemaExecutionVisitor.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/ClusterSchemaFetcher.java
- server/src/test/java/org/apache/iotdb/db/metadata/path/MeasurementPathTest.java
The consensus layer only supports passing message by TSStatus when executing writing operation. The existing measurement info can only be passed by string format in TSStatus. The transformation between string and bytes won't work if the encoding method use double-byte charsets. 
When transform measurementPath to String, use single-byte charsets.
> [IOTDB-4519] Fix existing measurement check during auto creating schema

- integration-test/src/test/java/org/apache/iotdb/db/it/IOTDBLoadTsFileIT.java
- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/DataRegion.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/AnalyzeVisitor.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/parser/ASTVisitor.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/scheduler/load/LoadTsFileDispatcherImpl.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/statement/crud/LoadTsFileStatement.java
problem:
- throw NPE when autoregister=false and enableAutoCreateSchema =false
- sill auto creating schema while autoregister=false
- file is deleted after load into local machine
- throw NPE when loading tsfile is not on local machine
solution:
- mandalically verify the metadata when registering metadata
- change `Files.createLink` to `Files.copy`
- return message to user to notice load function can only load local machine files.
> [IOTDB-4503] fix load error when autoregister is false

- metrics/dropwizard-metrics/src/main/java/org/apache/iotdb/metrics/dropwizard/reporter/DropwizardPrometheusReporter.java
- metrics/micrometer-metrics/src/main/java/org/apache/iotdb/metrics/micrometer/reporter/MicrometerPrometheusReporter.java
Now, when metric service stop, we simply call `DisposableServer#disposeNow()` to close all inactive connections.
After some search, I find setting channelGroup when create DisposableServer makes it possible to close active connections at the same time when call `DisposableServer#disposeNow()`.
Related issues in reactor:
1. [Use the new Transport API for TCP/UDP/HTTP implementations](https://github.com/reactor/reactor-netty/pull/1046)
2. [Connections are not disposed when server is closed](https://github.com/reactor/reactor-netty/issues/495)
3. [HTTP client connection is not disposed on server side](https://github.com/reactor/reactor-netty/issues/581)
Related Comments in code:
> [IOTDB-4529] Close active connections in prometheus reporter's disposable server when metric service stop.

- node-commons/src/main/java/org/apache/iotdb/commons/path/PatternTreeMap.java
- server/src/test/java/org/apache/iotdb/db/metadata/path/PatternTreeMapTest.java
Add new interface:
```java
/**
* Get a list of value lists related to PathPattern that overlapped with measurements under the
* same device.
*
* @param devicePath device path without wildcard
* @param measurements list of measurements
* @return value list
*/
public List<List<V>> getOverlapped(PartialPath devicePath, List<String> measurements) ;
```
If there are N measurements under the same device, this interface can save N times to search device node.
> [IOTDB-4465] Add interface for PatternTreeMap to optimize getOverlapped

- server/src/main/java/org/apache/iotdb/db/engine/compaction/CompactionTaskManager.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/CompactionUtils.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/inner/utils/InnerSpaceCompactionUtils.java
See [IOTDB-4554](https://issues.apache.org/jira/browse/IOTDB-4554).
> [To rel/0.13][IOTDB-4554] Start compaction only when IoTDB is fully recovered

- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/VirtualStorageGroupProcessor.java
We found that when memory is limited and there are too many TsFileResources, during restart prcessing, there are too much time spent on deserializing devices from TsFile, because `ITimeIndex` degrade to `FileTimeIndex`.
Dive into the restart process, we found that deserializing devices is for updating flush time of each device, so we can improve restarting by updating it before TsFileResource being added to `TsFileResourceManagement` when it can be degraded.
> [To rel/0.13] Accelerate restart process

- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/DataRegion.java
We found that when memory is limited and there are too many TsFileResources, during restart prcessing, there are too much time spent on deserializing devices from TsFile, because `ITimeIndex` degrade to `FileTimeIndex`.
Dive into the restart process, we found that deserializing devices is for updating flush time of each device, so we can improve restarting by updating it before TsFileResource being added to `TsFileResourceManagement` when it can be degraded.
> Accelerate restart proces

- integration-test/src/test/java/org/apache/iotdb/db/it/schema/IoTDBSchemaTemplateIT.java
- server/src/main/java/org/apache/iotdb/db/metadata/mtree/traverser/Traverser.java
During planning stage of schema query or schema fetch, the related template will be taken and set to the plan node. The unrelated template used in involved schemaRegion won't be taken, which results in the npe occurring during traversing the MTree in schemaRegion.
When traversing the MTree and meet template not provided in templateMap which passed in by schema query or fetch plan, ignore this node using such unrelated template.
> [IOTDB-4551] Fix schema query npe with template

- server/src/main/java/org/apache/iotdb/db/engine/compaction/performer/impl/ReadPointCompactionPerformer.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/writer/CrossSpaceCompactionWriter.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/writer/InnerSpaceCompactionWriter.java
- tsfile/src/main/java/org/apache/iotdb/tsfile/file/metadata/ChunkMetadata.java
- tsfile/src/main/java/org/apache/iotdb/tsfile/write/chunk/ChunkWriterImpl.java
- tsfile/src/main/java/org/apache/iotdb/tsfile/write/writer/TsFileIOWriter.java
See [IOTDB-4517](https://issues.apache.org/jira/browse/IOTDB-4517).
The fisrt reason is that the `currentChunkSize` does not reset when flushing chunk metadata to temp file in disk, leading to frequent flushing of chunk metadata.
The second reason is the concurrent issue caused by update to the start time and end time of tsfile resource in the compaction sub-task.
> [IOTDB-4517] Fix cross_space and unseq_space compaction are slower at common timeseries and template timeseries

- integration-test/src/test/java/org/apache/iotdb/session/IoTDBSessionComplexIT.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/AnalyzeVisitor.java
When analysing batch insert statement, we will generate a List\<DataPartitionQueryParam\> to fetch partition. This list includes several devices and their time slots. The method PartitionFetcher.getDataPartition(List\<DataPartitionQueryParam\> dataPartitionQueryParams) can not process multiple DataPartitionQueryParams in a single device.
So when generating this list, we merge all DataPartitionQueryParams in a single device into one.
And this pr also adds some IT to test batch writing covering multiple time slots.
> [IOTDB-4547] Fix error in routing batch insert plannode

- grafana-metrics-example/Apache IoTDB Dashboard v0.13.1.json
1. remove some useless "instance" name in dashboard.
2. divide timesereis in 2 type: normal timeseries and template timeseries.
> [To rel/0.13][IOTDB-4436] Fix inconsistency in grafana dashboard

- server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/schema/CountMergeOperator.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/schema/DevicesSchemaScanOperator.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/schema/LevelTimeSeriesCountOperator.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/schema/PathsUsingTemplateScanOperator.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/schema/SchemaQueryScanOperator.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/schema/SchemaTsBlockUtil.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/schema/TimeSeriesSchemaScanOperator.java
- server/src/test/java/org/apache/iotdb/db/mpp/execution/operator/schema/CountMergeOperatorTest.java
The result of schema query in one schemaRegion is always transferred by only on TsBlock no matter how many the records there are. In specific scenarios, especially the timeseries schema query, too many records may results in the size of result tsblock beyond the sink constraint of mpp.
Split the result records of schema query into several tsBlocks, the max size of which is default tsblock size.
> [IOTDB-4544] Implement tsblock split for schema query

- server/src/assembly/resources/conf/iotdb-datanode.properties
- server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
- server/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java
- server/src/main/java/org/apache/iotdb/db/utils/datastructure/AlignedTVList.java
- server/src/main/java/org/apache/iotdb/db/utils/datastructure/BinaryTVList.java
- server/src/main/java/org/apache/iotdb/db/utils/datastructure/TVList.java
The target_chunk_size is the only one we control the size of chunk in IoTDB, which could be used in all modules.
> [IOTDB-4575] Remove max_chunk_raw_size_threshold by target_chunk_size

- server/src/main/java/org/apache/iotdb/db/engine/compaction/CompactionUtils.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/CompactionSchedulerTest.java
See [IOTDB-4579](https://issues.apache.org/jira/browse/IOTDB-4579).
> [To rel/0.13] [IOTDB-4579] Remove the update of start time and end time in the target file after cross space compaction

- server/src/main/java/org/apache/iotdb/db/mpp/execution/fragment/FragmentInstanceExecution.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/schedule/DriverTaskTimeoutSentinelThread.java
I found a strange thing in CI failure.
The root cause is that the FI is aborted by `DriverTaskTimeoutSentinelThread`. I guess it's caused by Thread.sleep() may not  sleep that long, so I add a while loop and some debug logs if it happens again after I add this while loop.
> Make sure FI won't be aborted by timeout checker by mistake

- server/src/main/java/org/apache/iotdb/db/metadata/MManager.java
see https://github.com/apache/iotdb/issues/7552
The already existing timeseries shall directly be used in schema validation rather than causing a PathAlreadyExistException, thus ignore the exception generated by concurrent creation.
> [To rel/0.13] Fix PathAlreadyExistException during concurrent auto creating aligned timeseries

- integration-test/src/test/java/org/apache/iotdb/db/it/aligned/IoTDBCountMultiTimesWithDeletionIT.java
- server/src/main/java/org/apache/iotdb/db/utils/QueryUtils.java
More details can be seen in [JIRA](https://issues.apache.org/jira/projects/IOTDB/issues/IOTDB-4585?filter=allopenissues).
The root cause is that we update the AlignedChunkMetadata modified field even if it has already been `true`.
> [IOTDB-4585] Fix Delete bug in aligned time series

- server/src/main/java/org/apache/iotdb/db/query/context/QueryContext.java
- tsfile/src/main/java/org/apache/iotdb/tsfile/file/metadata/ChunkMetadata.java
- tsfile/src/test/java/org/apache/iotdb/tsfile/file/metadata/ChunkMetadataTest.java
ChunkMetadata#getDeleteIntervalList() return redundant and unordered intervals.
This is caused by an error in the sorting algorithm. 
This PR fix it and add UT for `ChunkMetadata#insertIntoSortedDeletions()`.
> [IOTDB-4598] Illegal deleteIntervalList generated from mods file

- integration-test/src/test/java/org/apache/iotdb/db/it/IoTDBDeletionIT.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/write/DeleteDataNode.java
See IOTDB-4600.
When delete data from non-existed series, we shouldn't generate the deleteDataPlanNode for it.
> [IOTDB-4600] Fix NPE occurred when deleting data

- server/src/main/java/org/apache/iotdb/db/engine/compaction/inner/utils/MultiTsFileDeviceIterator.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/performer/impl/ReadPointCompactionPerformer.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/ReadPointCompactionPerformerTest.java
If file 1 has d0 and d3, file 2 has d1 and d4, when compacting d0 and obtaining the sensors under it, it will mistakenly take the sensors under d1 in file 2.
**Reason**
There is bug in `MultiTsFileDeviceIterator` class. This class is used to obtain the devices in all source files in lexicographic order from small to large. There is a problem with the logic of judging whether the current device exists in a certain file.
> [IOTDB-4606]Fix getting wrong sensors and schemas in compaction

- server/src/main/java/org/apache/iotdb/db/engine/compaction/inner/utils/MultiTsFileDeviceIterator.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/CompactionUtilsTest.java
If file 1 has d0 and d3, file 2 has d1 and d4, when compacting d0 and obtaining the sensors under it, it will mistakenly take the sensors under d1 in file 2.
**Reason**
There is bug in `MultiTsFileDeviceIterator` class. This class is used to obtain the devices in all source files in lexicographic order from small to large. There is a problem with the logic of judging whether the current device exists in a certain file.
> [To rel/0.13][IOTDB-4606]Fix getting wrong sensors and schemas in compaction

- confignode/src/main/java/org/apache/iotdb/confignode/conf/ConfigNodeConstant.java
- confignode/src/main/java/org/apache/iotdb/confignode/conf/ConfigNodeRemoveCheck.java
- confignode/src/main/java/org/apache/iotdb/confignode/persistence/NodeInfo.java
- confignode/src/main/java/org/apache/iotdb/confignode/procedure/env/DataNodeRemoveHandler.java
- confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/node/RemoveDataNodeProcedure.java
- confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/statemachine/RegionMigrateProcedure.java
- node-commons/src/main/java/org/apache/iotdb/commons/utils/NodeUrlUtils.java
- server/src/main/java/org/apache/iotdb/db/client/ConfigNodeClient.java
- server/src/main/java/org/apache/iotdb/db/service/DataNodeServerCommandLine.java
1. Fix the problem when ratis 1 replica is migrated failed. Now support Ratis 1 replica SchemaRegion deleteOldRegionPeer.
2. Add `REMOVE_DATANODE_PROCESS` logs for the progress of removing datanode and region migration.
3. Now can choose the Removing datanode to execute `addPeer` process.
> [IOTDB-4609] Add more progress tips for remove-datanode and make deleteOldPeer available in ratis 1 replica situation

- cluster/src/main/java/org/apache/iotdb/cluster/partition/PartitionTable.java
- server/src/main/java/org/apache/iotdb/db/conf/IoTDBConstant.java
- server/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java
- server/src/main/java/org/apache/iotdb/db/engine/StorageEngine.java
- server/src/main/java/org/apache/iotdb/db/engine/archiving/ArchivingManager.java
- server/src/main/java/org/apache/iotdb/db/engine/archiving/ArchivingTask.java
- server/src/main/java/org/apache/iotdb/db/engine/cq/ContinuousQueryService.java
- server/src/main/java/org/apache/iotdb/db/engine/querycontext/QueryDataSource.java
- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/TsFileResource.java
- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/VirtualStorageGroupProcessor.java
- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/virtualSg/StorageGroupManager.java
- server/src/main/java/org/apache/iotdb/db/protocol/influxdb/input/InfluxLineParser.java
- server/src/main/java/org/apache/iotdb/db/protocol/influxdb/sql/InfluxDBSqlVisitor.java
- server/src/main/java/org/apache/iotdb/db/qp/executor/PlanExecutor.java
- server/src/main/java/org/apache/iotdb/db/qp/physical/sys/CreateContinuousQueryPlan.java
- server/src/main/java/org/apache/iotdb/db/qp/sql/IoTDBSqlVisitor.java
- server/src/main/java/org/apache/iotdb/db/qp/utils/DateTimeUtils.java
- server/src/main/java/org/apache/iotdb/db/qp/utils/DatetimeUtils.java
- server/src/main/java/org/apache/iotdb/db/query/executor/fill/LinearFill.java
- server/src/main/java/org/apache/iotdb/db/query/executor/fill/PreviousFill.java
- server/src/main/java/org/apache/iotdb/db/query/udf/api/customizer/strategy/SlidingTimeWindowAccessStrategy.java
- server/src/main/java/org/apache/iotdb/db/tools/IoTDBDataDirViewer.java
- server/src/main/java/org/apache/iotdb/db/tools/TsFileResourcePrinter.java
- server/src/main/java/org/apache/iotdb/db/tools/watermark/WatermarkDetector.java
- server/src/test/java/org/apache/iotdb/db/engine/archiving/ArchivingOperateWriterReaderTest.java
- server/src/test/java/org/apache/iotdb/db/engine/archiving/ArchivingTest.java
- server/src/test/java/org/apache/iotdb/db/protocol/rest/IoTDBRestServiceIT.java
- server/src/test/java/org/apache/iotdb/db/qp/utils/DatetimeQueryDataSetUtilsTest.java
- zeppelin-interpreter/src/test/java/org/apache/zeppelin/iotdb/IoTDBInterpreterTest.java
Convert ttl(ms) according to the time precision.
> [To rel/0.13][IOTDB-4615] TTL supports timestamp precision

- server/src/assembly/resources/conf/iotdb-datanode.properties
- server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
- server/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/cross/rewrite/RewriteCrossSpaceCompactionSelector.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/performer/impl/ReadChunkCompactionPerformer.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/writer/CrossSpaceCompactionWriter.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/writer/InnerSpaceCompactionWriter.java
- server/src/main/java/org/apache/iotdb/db/engine/flush/MemTableFlushTask.java
- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/TsFileProcessor.java
- server/src/main/java/org/apache/iotdb/db/wal/recover/file/AbstractTsFileRecoverPerformer.java
- tsfile/src/main/java/org/apache/iotdb/tsfile/write/writer/TsFileIOWriter.java
See [IOTDB-4584](https://issues.apache.org/jira/browse/IOTDB-4584).
This PR calculates the budget of metadata by the size of memtable before flushing memtable, the external size for metadata is managed by `SystemInfo`.
> [IOTDB-4584] Correct the ChunkMetadata proportion in writing TsFile

- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/write/InsertRowNode.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/write/InsertTabletNode.java
The schema may not exit when doing schema validation, which causes the deviceShemaInfo taken from schemaTree being null.
Add null check and throw PathNodeExistsException if null.
> [IOTDB-4565] Fix NPE of schema validation

- server/src/main/java/org/apache/iotdb/db/engine/compaction/inner/utils/MultiTsFileDeviceIterator.java
- server/src/main/java/org/apache/iotdb/db/engine/flush/MemTableFlushTask.java
- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/TsFileProcessor.java
- server/src/main/java/org/apache/iotdb/db/writelog/recover/TsFileRecoverPerformer.java
See [IOTDB-4635](https://issues.apache.org/jira/browse/IOTDB-4635).
The reason for this bug is that the chunk metadata is persisted in disk when flushing memtable to control the memory usage, the query cannot get access to the chunk metadata.
> [To Rel/0.13][IOTDB-4635] Fix data cannot be queried when flushing memtable

- integration/src/test/java/org/apache/iotdb/db/integration/IoTDBArchivingIT.java
- server/src/main/java/org/apache/iotdb/db/engine/StorageEngine.java
- server/src/main/java/org/apache/iotdb/db/engine/archiving/ArchivingManager.java
- server/src/main/java/org/apache/iotdb/db/qp/executor/PlanExecutor.java
1. Judge active info when comparing two archiving task
2. Return info to the client when failing to set archiving task
> [To rel/0.13][IOTDB-4640] Allow setting the same data archiving task after canceling it

- example/kafka/pom.xml
There are 1 security vulnerabilities found in org.apache.kafka:kafka_2.13 2.8.1
- [CVE-2022-34917](https://www.oscs1024.com/hd/CVE-2022-34917)
Upgrade org.apache.kafka:kafka_2.13 from 2.8.1 to 2.8.2 for vulnerability fix
Ideally, no insecure libs should be used.
Run `mvn compile` failed locally, couldn't complete the build process.
Run `mvn clean test` failed locally, unit-test couldn't pass.
[PR Specification](https://www.oscs1024.com/docs/pr-specification/) from OSCS
> fix(sec): upgrade org.apache.kafka:kafka_2.13 to 2.8.2

- server/src/main/java/org/apache/iotdb/db/query/reader/chunk/metadata/DiskAlignedChunkMetadataLoader.java
- server/src/main/java/org/apache/iotdb/db/query/reader/chunk/metadata/DiskChunkMetadataLoader.java
- server/src/main/java/org/apache/iotdb/db/utils/QueryUtils.java
- tsfile/src/main/java/org/apache/iotdb/tsfile/file/metadata/AlignedTimeSeriesMetadata.java
- tsfile/src/main/java/org/apache/iotdb/tsfile/file/metadata/ChunkMetadata.java
- tsfile/src/main/java/org/apache/iotdb/tsfile/file/metadata/TimeseriesMetadata.java
Each query requires regenerating the `deleteIntervalList` and `modified` for the `ChunkMetadata`. Since the same `ChunkMetadata` is shared, the `deleteIntervalList` and `modified` will be modified at the same time between multiple threads, resulting in incorrect query result.
**Solution:** Construct new `ChunkMetadataList` for each query.
> [IOTDB-4654] Fix concurrent bug caused by sharing same ChunkMetadata

- server/src/main/java/org/apache/iotdb/db/exception/query/QueryTimeoutRuntimeException.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/execution/QueryExecution.java
I found a strange thing in failed CI logs. The execution time of this query doesn't exceed 60s(default query time out limit).
So in this pr, I add more detailed error messaes in QueryTimeoutExecption if this strange thing happen again, I can figure out the reason.
> Add detailed error messages while query is time out

- integration-test/src/test/java/org/apache/iotdb/db/it/IoTDBFilterIT.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/AnalyzeVisitor.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/expression/leaf/ConstantOperand.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/expression/leaf/TimeSeriesOperand.java
- server/src/main/java/org/apache/iotdb/db/mpp/transformation/dag/input/ConstantInputReader.java
- server/src/main/java/org/apache/iotdb/db/mpp/transformation/dag/util/TransformUtils.java
- server/src/test/java/org/apache/iotdb/db/mpp/common/schematree/NodeRefTest.java
Before this PR, we use expressionString to distinguish the expressions. However, Long value 1 and String value "1" has the same expressionString. The details could be found at: https://issues.apache.org/jira/browse/IOTDB-4649
> [IOTDB-4649] Fix the problem that constants which have same valueString but different types can not be distinguished.

- server/src/main/java/org/apache/iotdb/db/engine/compaction/performer/impl/ReadChunkCompactionPerformer.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/inner/ReadChunkCompactionPerformerAlignedTest.java
See [IOTDB-4636](https://issues.apache.org/jira/browse/IOTDB-4636).
The reason for this bug is that there is an aligned chunk group in which every chunk is empty. This pr fixes that by checking aligned chunk metadata before compacting it.
> [IOTDB-4636] Fix IndexOutOfBoundsException when compacting aligned series

- server/src/main/java/org/apache/iotdb/db/mpp/plan/statement/crud/LoadTsFileStatement.java
problem:
if load error, a "%s" will be printed to user as follow:
solution:
fix a correct format in msg.
and
NoSuchFileException has been fix in #7354
> [IOTDB-4680] fix error msg "%s" in load statement

- consensus/pom.xml
- consensus/src/test/java/org/apache/iotdb/consensus/ratis/SnapshotTest.java
Recently Ratis Community releases its new version 2.4.0.
Ratis 2.4.0 includes multiple bug-fixes and improvements.
This PR only updates version (and fixes incompatibilities). Run CI to verify its correctness.
> [IOTDB-3462] Update ratis version to 2.4.0

- server/src/main/java/org/apache/iotdb/db/mpp/execution/exchange/MPPDataExchangeService.java
Currently, MPPDataExchangeService uses the `rpc_address` which should be `internal_address`.
> [IOTDB-4679] Make MPPDataExchangeService use internal_address instead of rpc_address

- server/src/main/java/org/apache/iotdb/db/rescon/SystemInfo.java
- server/src/test/java/org/apache/iotdb/db/engine/storagegroup/DataRegionTest.java
REJECT_THERSHOLD is initialized to 0.
> [IOTDB-4683] Fix REJECT_THERSHOLD init error in SystemInfo

- consensus/src/main/java/org/apache/iotdb/consensus/ratis/Utils.java
Currently, AppendEntries and Heartbeat uses the same gRPC channel.
Under heavy workloads, AppendEntries with lots of logs will consume a lot of processing time, so the follower may respond to this AppendEntries after a long latency. The leader would consider this long latency abnormal and step down.
So uses a separate channel can avoid heartbeat being blocked by AppendEntries.
We need two channels which means we have to establish a new http2 connection.
> [IOTDB-4689] Use seperate channel for heartbeat / appendEntries

- integration-test/src/test/java/org/apache/iotdb/session/it/IoTDBSessionInsertNulIT.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/execution/QueryExecution.java
Sometimes, IoTDBSessionInsertNulIT will timeout because its timeout parameter is set to 1s which is too small, especially in github CI container, so I change it to 60s.
> Make default timeout parameter in SessionIT from 1s to 60s

- .github/workflows/standalone-it-for-mpp.yml
Since we don't decide the structure of final standalone version, StandaloneMppIT cannot test all IT cases. Therefore, we should disable it temporarily.
> Disable StandaloneMppIT

- consensus/src/main/java/org/apache/iotdb/consensus/common/Peer.java
Peer contains a new member `nodeId`. Override the equals and hashcode method.
Otherwise the remove datanode would not function.
> [IOTDB-4699] Override peer's equals and hashcode

- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/TsFileProcessor.java
- server/src/main/java/org/apache/iotdb/db/wal/node/WALNode.java
Memtable flush may occur when snapshoting, but rowCount in the TVList will be set to 0 when memtable is flushed and released, so the snapshot will throw an ArrayIndexOutOfBoundsException. 
- Synchronize memTable when snapshoting, make sure mamtable will not be released.
- Call flushed listener after memtable is released safely.
> [IOTDB-4694] Make sure memTable snapshot is made before flush operation

- server/src/main/java/org/apache/iotdb/db/mpp/plan/execution/config/metadata/ShowClusterTask.java
- server/src/main/java/org/apache/iotdb/db/service/DataNodeInternalRPCService.java
The reason for this error is that the DataNodeInternalService binds to `rpc_address` instead of `internal_address`. Thus the ConfigNode can't send heartbeat to DataNode correctly. By the way, I also make the shown `host` information of cluster DataNodes consistent both in `show cluster` and `show datanodes`.
Local test screenshot:
> [IOTDB-4711] Bind DataNodeInternalService to correct address

- server/src/main/java/org/apache/iotdb/db/metadata/plan/schemaregion/impl/ActivateTemplateInClusterPlanImpl.java
- server/src/main/java/org/apache/iotdb/db/metadata/plan/schemaregion/write/IActivateTemplateInClusterPlan.java
- server/src/main/java/org/apache/iotdb/db/metadata/schemaregion/SchemaRegionMemoryImpl.java
- server/src/main/java/org/apache/iotdb/db/metadata/schemaregion/SchemaRegionSchemaFileImpl.java
- server/src/main/java/org/apache/iotdb/db/qp/physical/sys/ActivateTemplateInClusterPlan.java
1. There's mistake when check the operation result of schema region recover. The check condition is opposite.
2. When recover ActivateTemplateInClusterPlan, the set method templateId and templateSetLevel attributes has been mistakened.
> Fix schema region recover bug

- server/src/main/java/org/apache/iotdb/db/sync/pipedata/queue/BufferedPipeDataQueue.java
- server/src/test/java/org/apache/iotdb/db/sync/pipedata/BufferedPipeDataQueueTest.java
Add commit(long serialNumber) to interface PipeDataQueue
When serialNum is not discontinuous (e.g. 1, 2, 5, 8, 10),  the correctness of the interface in PipeDataQueue should be ensured.
Add UT for discontinuous serialNumber case
> [IOTDB-4293] BufferedPipeDataQueue supports discontinuous serialNumber

- server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
- server/src/main/java/org/apache/iotdb/db/writelog/node/ExclusiveWriteLogNode.java
- server/src/test/java/org/apache/iotdb/db/engine/modification/DeletionFileNodeTest.java
- server/src/test/java/org/apache/iotdb/db/utils/EnvironmentUtils.java
We found error like this, `java.nio.file.FileSystemException: target\wal\root.vehicle.d0\root.vehicle.d0-1666293644043-2-0-0.tsfile\wal2: The process cannot access the file because it is being used by another process.`
I assume this is caused by last wal file's discard operation is called before it has been closed. To fix it, discard operation will wait until last file has been close, which means `deleteFileId < fileId`.
> [To rel/0.13] Fix wal delete error in the DeletionFileNodeTest 

- confignode/src/main/java/org/apache/iotdb/confignode/manager/ConfigManager.java
The level of Partition related logs can lower now since these interfaces are steady and been covered by ClusterIT
> Lowering Partition related logs' level

- server/src/main/java/org/apache/iotdb/db/mpp/execution/schedule/AbstractDriverThread.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/schedule/DriverScheduler.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/schedule/DriverTaskThread.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/schedule/DriverTaskTimeoutSentinelThread.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/schedule/ThreadProducer.java
- server/src/test/java/org/apache/iotdb/db/mpp/execution/schedule/DriverTaskTimeoutSentinelThreadTest.java
I found a strange thing in a timeout CI logs that there are no `Query-Worker-Thread-i` threads in thread dump file.
After digging into related codes, I found that if the `Query-Worker-Thread-i` is interrupted by others, it will exit quitely and will not print any logs. Then I refer to related codes in `Trino` and find that `Trino` will submit another execution thread in such case, so I did so in this pr.
> Rerun a new query execution thread while previous one is interrupted

- integration-test/src/main/java/org/apache/iotdb/it/env/AbstractEnv.java
The ClusterIT environment is now full of client related error logs due to unsafe client borrow logic: 
In this PR I optimizedd the client borrow logic and add function annotation to remind the caller how to use this interface safely.
> [IOTDB-4732] Optimize client borrow logic in ClusterIT environment

- confignode/src/main/java/org/apache/iotdb/confignode/conf/ConfigNodeConfig.java
- confignode/src/main/java/org/apache/iotdb/confignode/conf/ConfigNodeDescriptor.java
- confignode/src/main/java/org/apache/iotdb/confignode/manager/ConsensusManager.java
Support serialization and deserialization for confignode standalone mode.
We used local file to complete the data persistence.
This pr only add `if (ConsensusFactory.StandAloneConsensus.equals(CONF.getConfigNodeConsensusProtocolClass())) {` judgement, and this branch will never be reached.
> [IOTDB-4616] Support serialization and deserialization for confignode standalone mode

- node-commons/src/main/java/org/apache/iotdb/commons/client/async/AsyncDataNodeInternalServiceClient.java
The original implementation prints a lot of stack information on retry. So I change AsyncDataNodeInternalServiceClient level from info to error and make it simple.
> Change AsyncDataNodeInternalServiceClient level from info to error and make it simple

- tsfile/src/main/java/org/apache/iotdb/tsfile/utils/BytesUtils.java
- tsfile/src/test/java/org/apache/iotdb/tsfile/utils/BytesUtilsTest.java
Since I have met a problem of "unequal value after bytes transformation by BytesUtils in tsfile" as mentioned in IOTDB-4633. After modifying the right arithmetic shift (算术右移) to right logical shift (逻辑右移) in longToBytes function of BytesUtils in tsfile, the problem has been solved successfully.
> [IOTDB-4633] Fix bugs of longToBytes in BytesUtils of tsfile

- server/src/assembly/resources/conf/iotdb-datanode.properties
- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/DataRegion.java
- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/TsFileProcessor.java
- server/src/main/java/org/apache/iotdb/db/rescon/SystemInfo.java
- server/src/main/java/org/apache/iotdb/db/wal/WALManager.java
- server/src/main/java/org/apache/iotdb/db/wal/allocation/ElasticStrategy.java
- server/src/main/java/org/apache/iotdb/db/wal/node/WALNode.java
- server/src/test/java/org/apache/iotdb/db/wal/allocation/ElasticStrategyTest.java
- server/src/test/java/org/apache/iotdb/db/wal/allocation/FirstCreateStrategyTest.java
- server/src/test/java/org/apache/iotdb/db/wal/allocation/RoundRobinStrategyTest.java
1. ElasticStrategy creates wal nodes according to the number of memTables. Each wal node manages fixed number of memTable. MemTables sharing the same unique id will be allocated to the same wal node.
2. WAL node wil trigger old memTables‘ flush when new time partition's memTable coming and wal_min_effective_info_ratio is below the threshold.
> [IOTDB-4237] Add new wal node allocation strategy to reduce wal size

- metrics/interface/src/main/assembly/resources/conf/iotdb-confignode-metric.yml
- metrics/interface/src/main/assembly/resources/conf/iotdb-datanode-metric.yml
- metrics/interface/src/main/java/org/apache/iotdb/metrics/config/MetricConfig.java
- metrics/interface/src/main/java/org/apache/iotdb/metrics/utils/IoTDBMetricsUtils.java
There are some built-in storage, such as: root._metric(metrics), root.system.audit(system audit log). We need to unify the prefix of the built-int system storage group which is `root.system`. So we will modify the default write path of iotdb metric reporter from `root.${database}` to `root.system.${database}`.
> [IOTDB-4747][IOTDB-4776] Modify default write path of iotdb metric reporter

- docs/UserGuide/Maintenance-Tools/Sync-Tool.md
- docs/zh/UserGuide/Maintenance-Tools/Sync-Tool.md
- integration-test/src/test/java/org/apache/iotdb/db/it/sync/IoTDBPipeIT.java
- integration-test/src/test/java/org/apache/iotdb/db/it/sync/IoTDBPipeSinkIT.java
- node-commons/src/main/java/org/apache/iotdb/commons/sync/pipe/TsFilePipeInfo.java
- server/src/main/java/org/apache/iotdb/db/mpp/common/header/ColumnHeaderConstant.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/execution/config/executor/ClusterConfigTaskExecutor.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/execution/config/sys/sync/ShowPipeTask.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/execution/memory/StatementMemorySourceVisitor.java
- server/src/main/java/org/apache/iotdb/db/sync/SyncService.java
- thrift-confignode/src/main/thrift/confignode.thrift
* Update sync-tool docs.
* Print more detailed pipe information in show pipe
* Add a column attributes to show pipe attributes
* For receiver, show connection of sender
```
IoTDB> SHOW PIPES
IoTDB>
+-----------------------+--------+--------+-------------+---------+-----------------------------------+-------+
|            create time|   name |    role|       remote|   status|                         attributes|message|
+-----------------------+--------+--------+-------------+---------+-----------------------------------+-------+
|2022-03-30T20:58:30.689|my_pipe1|  sender|  my_pipesink|     STOP|syncDelOp=true,dataStartTimestamp=0|       |
+-----------------------+--------+--------+-------------+---------+-----------------------------------+-------+ …
```
> [IOTDB-4137][IOTDB-4799] Update sync-tool docs and print more detailed pipe information in show pipe

- server/src/assembly/resources/tools/tsfileToolSet/print-tsfile-sketch.bat
`print-tsfile-sketch.bat` went wrong when reading measurementID with Chinese characters.
Specifically, it is the following code that does not return correct results:
```
int measurementIdLength = measurementID.getBytes(TSFileConfig.STRING_CHARSET).length; 
```
For example, if measurementID="电机绕组温度1", the correct measurementIdLength is 20,
while `print-tsfile-sketch.bat` assigns measurementIdLength as 30, which is wrong.
This pr fixes this bug by adding JAVA_OPTS -Dfile.encoding=UTF-8 in `print-tsfile-sketch.bat`.
> [IOTDB-4810] Fix print-tsfile-sketch.bat bug when reading measurementID containing Chinese

- docs/UserGuide/UDF-Library/M4.md
Fix a typo in `docs/UserGuide/UDF-Library/M4.md`. (I need to conserve the website link of docs/UserGuide/UDF-Library/M4.md for some time, so I don't remove that doc right now.)
> fix a document typo

- confignode/src/main/java/org/apache/iotdb/confignode/persistence/AuthorInfo.java
- confignode/src/test/java/org/apache/iotdb/confignode/persistence/AuthorInfoTest.java
- integration-test/src/test/java/org/apache/iotdb/confignode/it/IoTDBClusterAuthorityIT.java
- node-commons/src/main/java/org/apache/iotdb/commons/utils/AuthUtils.java
- server/src/main/java/org/apache/iotdb/db/localconfignode/LocalConfigNode.java
- server/src/main/java/org/apache/iotdb/db/qp/executor/PlanExecutor.java
This problem has been solved, but new problems have been found.
The user checks the permissions on the root. sg. ** path, and the root. ** is also matched
after:
> [IOTDB-3149] There is a difference between adding ** path and without a path to list user privileges

- server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/schema/CountMergeOperator.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/schema/NodePathsCountOperator.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/schema/SchemaQueryOrderByHeatOperator.java
- server/src/test/java/org/apache/iotdb/db/mpp/execution/operator/schema/CountMergeOperatorTest.java
The isBlocked ListenableFuture of child will change status after returned from current merge operator to query driver, which results in the driver may directly start invoking hasNext and next method of current merge operator before all data prepared well.
> Fix isBlocked bug of schema query

- cli/src/assembly/resources/sbin/start-cli.sh
this pr fix "-e can not be used in start-cli.sh" bug introduced in https://github.com/apache/iotdb/pull/7802
> [IOTDB-4230]fix start-cli.sh does not support -e

- node-commons/src/assembly/resources/conf/iotdb-common.properties
Since SchemaFile has not been finished, all config entries has been hide from iotdb-common.properties.
> Hide all SchemaFile options in config file

- jdbc/src/main/java/org/apache/iotdb/jdbc/IoTDBDatabaseMetadata.java
- jdbc/src/main/java/org/apache/iotdb/jdbc/IoTDBJDBCResultSet.java
- jdbc/src/main/java/org/apache/iotdb/jdbc/IoTDBStatement.java
- jdbc/src/test/java/org/apache/iotdb/jdbc/IoTDBJDBCResultSetTest.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/Coordinator.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/execution/IQueryExecution.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/execution/QueryExecution.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/execution/config/ConfigExecution.java
- server/src/main/java/org/apache/iotdb/db/service/thrift/impl/ClientRPCServiceImpl.java
- server/src/main/java/org/apache/iotdb/db/utils/QueryDataSetUtils.java
- service-rpc/src/main/java/org/apache/iotdb/rpc/IoTDBRpcDataSet.java
- session/src/main/java/org/apache/iotdb/session/SessionConnection.java
- session/src/main/java/org/apache/iotdb/session/SessionDataSet.java
- thrift/src/main/thrift/client.thrift
In this pr, i did two optimization
1. [[IOTDB-3773]](https://issues.apache.org/jira/browse/IOTDB-3773) previously we will print slow query time cost after the first batch is returned which is totally wrong because the printed time is not the real time it cost. So, in this pr, I move the print logics into cleanUpQuery which is the end point of this query.
2. [[IOTDB-4831]](https://issues.apache.org/jira/browse/IOTDB-4831) previously, even if there is no more data in server side, client will still need one more rpc call to fetch result and then client found that this rpc call return no data, it will end.
However, we can add a `moreData` field in response to indicate that there is no more data in server side after this rpc call and client can use this filed to decide whether to do another …
> [IOTDB-3773] [IOTDB-4831] Optimize the rpc call numbers in query processing & make query cost time print more accurate

- client-cpp/pom.xml
- compile-tools/pom.xml
- distribution/pom.xml
- example/client-cpp-example/pom.xml
- example/trigger/pom.xml
- example/udf/pom.xml
- grafana-connector/pom.xml
- integration/pom.xml
- jdbc/pom.xml
- pom.xml
- server/src/main/java/org/apache/iotdb/db/utils/TypeInferenceUtils.java
- server/src/test/java/org/apache/iotdb/db/utils/TypeInferenceUtilsTest.java
```
IoTDB> create timeseries root.sg.d1.s2 with datatype=double
IoTDB> insert into root.sg.d1(time,s2) values(1,271840880000000000000000)
Msg: 500: [INTERNAL_SERVER_ERROR(500)] Exception occurred: executeNonQueryPlan failed. For input string: "271840880000000000000000"
```
After fixing
```
IoTDB> insert into root.sg.d1(time,s2) values(1,271840880000000000000000)
+-----------------------------+-------------+
|                         Time|root.sg.d1.s2|
+-----------------------------+-------------+
|1970-01-01T08:00:00.001+08:00| 2.7184088E23|
+-----------------------------+-------------+
It costs 0.085s
```
> [To rel/0.13] Fix String number infer bug

- integration-test/src/test/java/org/apache/iotdb/db/it/aligned/IoTDBInsertAlignedValuesIT.java
- server/src/main/java/org/apache/iotdb/db/utils/TypeInferenceUtils.java
- server/src/test/java/org/apache/iotdb/db/utils/TypeInferenceUtilsTest.java
See IOTDB-4842 
After fixing:
```
IoTDB> insert into root.sg.d1(time,s2) values(1,271840880000000000000000)
+-----------------------------+-------------+
|                         Time|root.sg.d1.s2|
+-----------------------------+-------------+
|1970-01-01T08:00:00.001+08:00| 2.7184088E23|
+-----------------------------+-------------+
It costs 0.085s
```
> [IOTDB-4842] Fix type infer error when insert a large number

- cli/src/main/java/org/apache/iotdb/cli/AbstractCli.java
- cli/src/main/java/org/apache/iotdb/cli/Cli.java
The user can set timeout in Cli through -timeout in command line.
> [IOTDB-4597] add option to set query timeout in Cli

- confignode/src/main/java/org/apache/iotdb/confignode/consensus/response/TemplateSetInfoResp.java
- server/src/main/java/org/apache/iotdb/db/metadata/mtree/IMTreeBelowSG.java
- server/src/main/java/org/apache/iotdb/db/metadata/mtree/MTreeBelowSGCachedImpl.java
- server/src/main/java/org/apache/iotdb/db/metadata/mtree/MTreeBelowSGMemoryImpl.java
- server/src/main/java/org/apache/iotdb/db/metadata/mtree/store/disk/schemafile/RecordUtils.java
- server/src/main/java/org/apache/iotdb/db/metadata/plan/schemaregion/impl/DeactivateTemplatePlanImpl.java
- server/src/main/java/org/apache/iotdb/db/metadata/plan/schemaregion/impl/PreDeactivateTemplatePlanImpl.java
- server/src/main/java/org/apache/iotdb/db/metadata/plan/schemaregion/impl/RollbackPreDeactivateTemplatePlanImpl.java
- server/src/main/java/org/apache/iotdb/db/metadata/plan/schemaregion/impl/SchemaRegionPlanFactory.java
- server/src/main/java/org/apache/iotdb/db/metadata/schemaregion/SchemaRegionMemoryImpl.java
- server/src/main/java/org/apache/iotdb/db/metadata/schemaregion/SchemaRegionSchemaFileImpl.java
- server/src/main/java/org/apache/iotdb/db/metadata/template/ClusterTemplateManager.java
- server/src/main/java/org/apache/iotdb/db/metadata/template/Template.java
- server/src/test/java/org/apache/iotdb/db/metadata/SchemaBasicTest.java
- server/src/test/java/org/apache/iotdb/db/metadata/schemaRegion/SchemaRegionBasicTest.java
* Extract the common code about logWriter in `SchemaRegionSchemaFileImpl` to make it consistent with `SchemaRegionMemoryImpl`.
* Implement following interfaces in `SchemaRegionSchemaFileImpl` and add UT in `SchemaRegionBasicTest`:
* activateSchemaTemplate ☑️
* getPathsUsingTemplate ☑️
* constructSchemaBlackListWithTemplate ☑️
* rollbackSchemaBlackListWithTemplate ☑️
* deactivateTemplateInBlackList ☑️
* countPathsUsingTemplate ☑️
* getAllTimeseriesCount with template ☑️
* Update the semantics of templateId in SchemaFile to use `SchemaTemplateManager` for management.
* Split MLog entry about `IPreDeactivateTemplatePlan`, `IRollbackPreDeactivateTemplatePlan` and `IDeactivateTemplatePlan` into actual fullPath and templateId.`
> [IOTDB-4827][IOTDB-4840] Adaptation and fix mlog logic for for cluster template 

- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/TsFileResource.java
- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/timeindex/DeviceTimeIndex.java
- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/timeindex/FileTimeIndex.java
- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/timeindex/ITimeIndex.java
- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/timeindex/V012FileTimeIndex.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/execution/QueryExecution.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/scheduler/ClusterScheduler.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/scheduler/FixedRateFragInsStateTracker.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/scheduler/IFragInstanceStateTracker.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/scheduler/SimpleQueryTerminator.java
- server/src/main/java/org/apache/iotdb/db/utils/FileLoaderUtils.java
In this pr, i did the following performance improvement:
1. Avoid duplicated map.get in TsResource.isSatisfied() method by adding a new method to directly return a long array. If the long array is null, it means that this device doesn't exist. And the index 0 is startTime, index 1 is endTime.
2. Avoid needless cancelQuery rpc call. Previously, we will send cancelQuery request whenever possible. However, if the query is finished normally(all FIs are in done state), we don't need to do that.
3. Remove a useless File.exist() check in FileLoaderUtils, tsfile must exist and will never be deleted because we have already lock it before putting it into query resource list.
> Improve query performance

- integration-test/src/test/java/org/apache/iotdb/db/it/IoTDBFilterIT.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/ExpressionAnalyzer.java
cause: The case where predicate is a TimeSeries is not considered in method `extractGlobalTimeFilter()`
> [IOTDB-4848] fix Bug: TimeSeries cannot be used in logical operator

- confignode/src/main/java/org/apache/iotdb/confignode/procedure/env/ConfigNodeProcedureEnv.java
- confignode/src/main/java/org/apache/iotdb/confignode/procedure/store/ConfigProcedureStore.java
see: https://issues.apache.org/jira/browse/IOTDB-4703
check nodes' status when execute INVALIDATE_CACHE  in the deleteStorageGroupProcedure.
> [IOTDB-4807] Check nodes' status at the INVALIDATE_CACHE state

- docs/UserGuide/Cluster/Cluster-Setup.md
- docs/UserGuide/Maintenance-Tools/Maintenance-Command.md
- docs/zh/UserGuide/Cluster/Cluster-Setup.md
- docs/zh/UserGuide/Maintenance-Tools/Maintenance-Command.md
- server/src/main/java/org/apache/iotdb/db/mpp/common/header/ColumnHeaderConstant.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/execution/config/metadata/ShowClusterTask.java
1. rename `Host` to `InternalAddress`
2. show datanodes' Internal Address:Port when executing show cluster
> [IOTDB-4861] Show DataNodes' Internal Address:Port when executing show cluster

- node-commons/src/main/java/org/apache/iotdb/commons/concurrent/ThreadName.java
- server/src/main/java/org/apache/iotdb/db/engine/StorageEngine.java
- server/src/main/java/org/apache/iotdb/db/engine/StorageEngineV2.java
Use cached thread pool to accelerate short-lived asynchronous tasks
1. Recover data region
2. Close tsfile processor
> [IOTDB-4700] Improve flush performance by using thread pool

- server/src/main/java/org/apache/iotdb/db/mpp/common/schematree/ClusterSchemaTree.java
- server/src/main/java/org/apache/iotdb/db/mpp/common/schematree/node/SchemaEntityNode.java
- server/src/test/java/org/apache/iotdb/db/mpp/common/schematree/ClusterSchemaTreeTest.java
When appending nested devices into one schema tree in sequence, for example non-aligned device ``` root.sg1.d2.others.ver``` and aligned device ``` root.sg1.d2```, the device node d2 in final schema tree won't be aligned.
This problem is caused by info missing during node replacement. Add the check when replace internal node d2 with device node d2.
> [IOTDB-4866] Fix schema tree bug when append nested device

- node-commons/src/main/java/org/apache/iotdb/commons/trigger/TriggerTable.java
- server/src/main/java/org/apache/iotdb/db/service/DataNode.java
- server/src/main/java/org/apache/iotdb/db/service/thrift/impl/DataNodeInternalRPCServiceImpl.java
- server/src/main/java/org/apache/iotdb/db/trigger/service/TriggerManagementService.java
When drop trigger failed on DataNode, ConfigNode will send a retry rpc. We need to remove trigger in map after successfully exectuing trigger.OnDrop()
> [IOTDB-4868] Drop trigger should fail when trigger.OnDrop throws an exception 

- server/src/main/java/org/apache/iotdb/db/mpp/plan/scheduler/FragmentInstanceDispatcherImpl.java
Since the most frequent requests of IoTDB is aimed to be executed on one region, the concurrent execution of sub requests generated by raw request split is unnecessary, and the sub requests are bound to be executed in sequence.
> Rollback modification of FrangmentInstanceDispatherImpl.dispatchWriteSync 

- consensus/src/main/java/org/apache/iotdb/consensus/multileader/logdispatcher/MultiLeaderMemoryManager.java
Try to use CAS in reserve method of MultiLeaderMemoryManager to avoid `synchronized` way.
> [IOTDB-4879] Use CAS in reserve method of MultiLeaderMemoryManager

- .gitmodules
Current submodule settings cause:
```
Cloning into '/Users/chenzili/Brittani/iotdb/client-go'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:apache/iotdb-client-go.git' into submodule path '/Users/chenzili/Brittani/iotdb/client-go' failed
Failed to clone 'client-go'. Retry scheduled
Cloning into '/Users/chenzili/Brittani/iotdb/client-go'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:apache/iotdb-client-go.git' into submodule path '/Users/chenzili/Brittani/iotdb/client-go' …
```
> fix: submodule url

- server/src/main/java/org/apache/iotdb/db/mpp/execution/fragment/FragmentInstanceExecution.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/fragment/FragmentInstanceManager.java
In read and write mixed load, after about 90 mins, the query will be much slower than before and the memory keeps highing and gc will keep active.
After dumping the memory heap, I found that instanceExecution Map in FragmentInstanceManager is too large. Previously, it can be removed by cancel rpc call from Coordinator, but after optimizing, Coordinator won't call cancel rpc if the FI is already in done state. Unfortunately, when FI's state changing to done, it doesn't remove itself from instanceExecution Map in FragmentInstanceManager which causes this memory leak.
> [IOTDB-4880] Fix memory leak in query

- consensus/src/main/java/org/apache/iotdb/consensus/ratis/RatisConsensus.java
- consensus/src/test/java/org/apache/iotdb/consensus/ratis/RatisConsensusTest.java
Ratis supports to transfer leader quietly.
That is, the new leader can start the election immediately without waiting for an election timeout.
Add new unit tests to verify.
> [IOTDB-4862] optimize transfer leader implementation

- node-commons/src/main/java/org/apache/iotdb/commons/path/PathPatternNode.java
- node-commons/src/main/java/org/apache/iotdb/commons/path/PathPatternTree.java
- node-commons/src/test/java/org/apache/iotdb/commons/path/PathPatternTreeTest.java
After appending root.sg.d and root.sg.d.** to an empty pathPatternTree and invoking constructTree(), only root.sg.d.** can be taken by invoking getAllPathPatterns() and root.sg.d is missing.
In the original design, only the leaf nodes on the PathPatternTree are considered as measurement. However, the information is lost when there is a subpath for measurement. e.g. root->sg->d(measurement)->**(measurement).
So we use an additional roleType field to identify whether the node in the tree is internal or measurement.
To avoid compatibility problema, new semantics are given to the original valueSet field in the serialization method.
> [IOTDB-4876] Fix PathPatternTree missing information on subpaths

- server/src/main/java/org/apache/iotdb/db/engine/load/AlignedChunkData.java
- server/src/main/java/org/apache/iotdb/db/engine/load/NonAlignedChunkData.java
- tsfile/src/main/java/org/apache/iotdb/tsfile/file/header/PageHeader.java
problem:
The error estimating of TsFileData memory causes the actual Thrift Frame to be greater than the limited value, which further leads to the following problems:
solution:
> [IOTDB-4753] Error serialized data size in TsFileData

- confignode/src/main/java/org/apache/iotdb/confignode/manager/load/balancer/RouteBalancer.java
fix problem in greedySelectLeader, only use DataRegion but not DataRegion + SchemaRegion
Before fix:
After fix:
> Fix problem in greedySelectLeader

- node-commons/src/main/java/org/apache/iotdb/commons/conf/CommonConfig.java
The test result is as follow.
Before:
After:
After the fix, please place "setStatusReason" right after "setNodeStatus" if you want to grant the new status a reason, hence the setNodeStatus function will clear the previous status reason.
<hr>
This PR has:
<hr>
> [IOTDB-4920] Fixed the bug that show cluster returns wrong answer

- confignode/src/main/java/org/apache/iotdb/confignode/manager/ConfigManager.java
- confignode/src/main/java/org/apache/iotdb/confignode/manager/node/NodeManager.java
- confignode/src/main/java/org/apache/iotdb/confignode/service/ConfigNode.java
Fix the problem that internal_address is not consistent with target_confignode when first starts.
Before fix, the run result is as below:
After fix, the run result is as below:
> [IOTDB-4849] Fix the problem that internal_address is not consistent with target_confignode when first starts Seed-ConfigNode.

- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/DataRegion.java
- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/HashLastFlushTimeMap.java
- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/IDTableLastFlushTimeMap.java
- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/ILastFlushTimeMap.java
- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/TsFileProcessor.java
- server/src/test/java/org/apache/iotdb/db/engine/storagegroup/DataRegionTest.java
- server/src/test/java/org/apache/iotdb/db/engine/storagegroup/TsFileProcessorV2Test.java
Now, when executing some inserting requests and then deleting all data, there will be an empty memtable in the tsfileProcessor. When executing flush request and closing this tsfileProcessor,  this request will be blocked.
> [IOTDB-4896] Fix error in closing a TsFileProcessor with an empty memtable

- integration/src/test/java/org/apache/iotdb/db/integration/sync/IoTDBSyncSenderIT.java
- server/src/main/java/org/apache/iotdb/db/sync/pipedata/DeletionPipeData.java
- server/src/main/java/org/apache/iotdb/db/sync/pipedata/PipeData.java
- server/src/main/java/org/apache/iotdb/db/sync/pipedata/TsFilePipeData.java
- server/src/main/java/org/apache/iotdb/db/sync/pipedata/queue/BufferedPipeDataQueue.java
- server/src/main/java/org/apache/iotdb/db/sync/transport/server/ReceiverManager.java
Prevent compatibility problems in PipeData beacause of ordinal of PipeDataType.
> [IOTDB-4941] Prevent compatibility problems in PipeData

- server/src/main/java/org/apache/iotdb/db/service/DataNode.java
- server/src/main/java/org/apache/iotdb/db/service/DataNodeServerCommandLine.java
Only checkDirectory when start DataNode because remove-datanode.sh will cause error.
> [IOTDB-4942] Only checkDirectory when start DataNode

- server/src/main/java/org/apache/iotdb/db/doublelive/OperationSyncConsumer.java
- server/src/main/java/org/apache/iotdb/db/doublelive/OperationSyncDDLProtector.java
- server/src/main/java/org/apache/iotdb/db/doublelive/OperationSyncDMLProtector.java
Start primary db and backup db, maintain write requests, and stop backup db for 5 minutes(write requests for primary db is not stopped), then restart backup db, then meets exception 'org.apache.iotdb.rpc.BatchExecutionException: 506: org.apache.iotdb.db.exception.StorageGroupNotReadyException: the sg root.sg1 may not ready now, please wait and retry later; '.   And these data are not persistent in operation sync log, so these data are lost.
Persistent the data in operation sync log when meets `StorageGroupNotReadyException`.
> [To rel/0.13] [IOTDB-4938] Fix error for storage group not ready

- server/src/main/java/org/apache/iotdb/db/mpp/execution/executor/RegionWriteExecutor.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/ClusterSchemaFetcher.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/metedata/write/MeasurementGroup.java
see IOTDB-4901 IOTDB-4860
The index of measurement in measurementGroup will go invalid during removing some measurement, thus fix it by moving the needed measurements to new list.
> [IOTDB-4901][IOTDB-4860] Fix concurrent auto create schema bug

- confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/sync/DropPipeProcedure.java
- integration-test/src/test/java/org/apache/iotdb/db/it/sync/IoTDBPipeIT.java
Even if pipe does not exist, drop pipe always succeed. But if pipesink does not exist，drop pipesink report error.
After this PR change, drop non-existent pipe operetion will fail and response `PIPE [aa] does not exist`.
> [IOTDB-4951] Response failure if drop non-existent pipe

- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/TsFileResource.java
- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/TsFileResourceStatus.java
See [IOTDB-4950](https://issues.apache.org/jira/browse/IOTDB-4950).
If we do not use a `DELETED` status for a deleted tsfile resource, every time the program call `isDelete` method in TsFileResource, it has to access the file system to check whether a tsfile exists or not, which may lead to bad performance.
> [IOTDB-4950] Add TsFileResourceStatus DELETED

- server/src/main/java/org/apache/iotdb/db/mpp/plan/parser/ASTVisitor.java
> [IOTDB-4934]Modify error message of use 'null' directly in SQL

- consensus/src/main/java/org/apache/iotdb/consensus/ratis/Utils.java
see https://issues.apache.org/jira/browse/IOTDB-4727
see also https://issues.apache.org/jira/browse/RATIS-1743
When TSStatus serialization size exceeds 1024 Bytes, the serialization will fail and the ByteBuffer returned is null. We should use the AutoScalingBufferWriteTransport to support arbitrary TSStatus size.
> [IOTDB-4727] use AutoScalingBufferWriteTransport to avoid byte buffer overflow

- integration-test/src/test/java/org/apache/iotdb/session/it/IoTDBSessionSchemaTemplateIT.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/parser/StatementGenerator.java
- server/src/test/java/org/apache/iotdb/db/metadata/SchemaBasicTest.java
- server/src/test/java/org/apache/iotdb/db/metadata/plan/SchemaRegionPlanCompatibilityTest.java
- tsfile/src/main/java/org/apache/iotdb/tsfile/file/metadata/enums/CompressionType.java
See [IOTDB-4939](https://issues.apache.org/jira/browse/IOTDB-4939).
This pr removes LZO, SDT, PAA, PLA compression.
> [IOTDB-4939] Remove unsupported compression type

- integration/src/test/java/org/apache/iotdb/db/integration/IoTDBMetadataFetchIT.java
- server/src/main/java/org/apache/iotdb/db/metadata/utils/MetaUtils.java
To stay consistent with the format of compressors in show timeseries result, change the deadband field result to upper case.
> [IOTDB-4946] Change SDT to Upper case

- service-rpc/src/main/java/org/apache/iotdb/rpc/IoTDBRpcDataSet.java
- session/src/main/java/org/apache/iotdb/session/SessionDataSet.java
The curves show the cost of time in constructRowRecordFromValueArray() method comparing with version 0.13
> [IOTDB-4973] add a copy of time instead of calling getTimestamp

- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/PlanGraphPrinter.java
> [IOTDB-4975] Explain support last query

- confignode/src/main/java/org/apache/iotdb/confignode/manager/SyncManager.java
- confignode/src/main/java/org/apache/iotdb/confignode/persistence/sync/ClusterSyncInfo.java
- confignode/src/test/java/org/apache/iotdb/confignode/persistence/ClusterSyncInfoTest.java
- confignode/src/test/resources/confignode1conf/iotdb-common.properties
- node-commons/src/main/java/org/apache/iotdb/commons/sync/metadata/SyncMetadata.java
- node-commons/src/main/java/org/apache/iotdb/commons/sync/pipe/TsFilePipeInfo.java
- node-commons/src/main/java/org/apache/iotdb/commons/sync/pipesink/IoTDBPipeSink.java
- node-commons/src/main/java/org/apache/iotdb/commons/sync/pipesink/PipeSink.java
- node-commons/src/main/java/org/apache/iotdb/commons/sync/utils/SyncConstant.java
- node-commons/src/test/java/org/apache/iotdb/commons/sync/metedata/SyncMetadataTest.java
- server/src/main/java/org/apache/iotdb/db/sync/common/LocalSyncInfo.java
- server/src/main/java/org/apache/iotdb/db/sync/sender/pipe/ExternalPipeSink.java
- server/src/main/java/org/apache/iotdb/db/sync/sender/pipe/TsFilePipe.java
- server/src/main/java/org/apache/iotdb/db/sync/transport/client/IoTDBSyncClient.java
- server/src/main/java/org/apache/iotdb/db/sync/transport/client/SenderManager.java
- server/src/main/java/org/apache/iotdb/db/sync/transport/client/SyncClientFactory.java
https://issues.apache.org/jira/browse/IOTDB-4957
1. Add check for create pipesink. For IoTDBPipeSink, it will response exception if ip address is not standard IPv4 address.
2. To avoid busy waiting and large amount of duplicate logs. I optimize logic of re-connection. If sender lost connection to receiver, it will hang up until scheduled heartbeat task successfully reconnect to receiver. Default interval of heartbeat is 30 seconds.
> [IOTDB-4957] Add check for create pipesink and optimize re-connection

- consensus/src/main/java/org/apache/iotdb/consensus/ratis/Utils.java
- node-commons/src/assembly/resources/conf/iotdb-common.properties
First election is a new feature recently introduced by Ratis 2.4.0, the original issue is https://issues.apache.org/jira/browse/RATIS-1638. The motivation of first election is to reduce unavailable time during start up.
However, this new feature is experimental. There are some known issues when applying in IoTDB. For example, when first election timeout is 50ms, migrate region will first call createPeer then call addPeer. If election timeouts before addPeer (after createPeer), the leader will tell it to shutdown and the migration will fail.
failure examples can be seen at https://github.com/apache/iotdb/actions/runs/3478206562/jobs/5815284797. 
Therefore, this PR proposes to disable first election feature.
This feature may be re-opened when addNewNodeToExistedGroup is implemented and …
> [IOTDB-4850] Disable first election feature

- confignode/src/main/java/org/apache/iotdb/confignode/manager/ConsensusManager.java
Remove createPeer process when confignode restart to remove this ERROR as the screenshot.
> [IOTDB-4959] Remove createPeer state when confignode restart

- confignode/src/main/java/org/apache/iotdb/confignode/procedure/ProcedureExecutor.java
- confignode/src/main/java/org/apache/iotdb/confignode/procedure/env/ConfigNodeProcedureEnv.java
Make the log level of `thread group in ProcedureExecutor` as warn.
These threads cannot be stopped may be used by other module such as ASyncClientManger, and it's no need to destroy it.
> [IOTDB-3671] Make thread group of ProcedureExecutor warn

- server/src/main/java/org/apache/iotdb/db/metadata/mtree/store/disk/schemafile/SchemaFile.java
- server/src/main/java/org/apache/iotdb/db/metadata/mtree/store/disk/schemafile/pagemgr/PageManager.java
- server/src/test/java/org/apache/iotdb/db/metadata/mtree/schemafile/SchemaFileTest.java
This pr fixs a bug involved from https://github.com/apache/iotdb/pull/7726 where tried to optimize performance by an extra segment estimation method. The method takes into account the size of write batch but ignores to compare it with the original size, which throws an exception with message that cannot extend a segment into a smaller buffer.
The problem is fixed by this pr, in comany with a new ut to verify it.
> Fix Segment size estimation in SchemaFile

- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/distribution/SourceRewriter.java
- server/src/test/java/org/apache/iotdb/db/mpp/plan/plan/distribution/AggregationDistributionTest.java
Before this change, if the logical plan contains only 1 series and the series belongs to serval DataRegions, the distribution plan will always set the AggragtionStep to `FINAL`, which is not correct. This PR fixed this issue and add two more unit tests for this scenarios.
> Fix the bug that the AggregationNode is always Final 

- server/src/main/java/org/apache/iotdb/db/service/DataNode.java
When use iotdb reporter in metric module, there are session connection failure because the start of reporter is earlier than the set up of RPC service
> [IOTDB-5011] Fix session connection failure when start datanode using iotdb reporter

- consensus/src/main/java/org/apache/iotdb/consensus/ratis/RatisConsensus.java
- consensus/src/test/java/org/apache/iotdb/consensus/ratis/RatisConsensusTest.java
When adding a new member to an existed group, the correct order is:
1. call createPeer on new member with **EMPTY GROUP**.
2. call addPeer on original group with full group.
This PR enables RatisConsensus to handle EMPTY GROUP create peer requests.
> [IOTDB-5008] Fix SHUTDOWN errors in ratis create peer

- node-commons/src/main/java/org/apache/iotdb/commons/conf/CommonConfig.java
- node-commons/src/main/java/org/apache/iotdb/commons/conf/CommonDescriptor.java
- node-commons/src/main/java/org/apache/iotdb/commons/sync/utils/SyncPathUtil.java
- server/src/assembly/resources/conf/iotdb-datanode.properties
- server/src/main/java/org/apache/iotdb/db/sync/sender/pipe/TsFilePipe.java
- server/src/test/java/org/apache/iotdb/db/utils/EnvironmentUtils.java
- server/src/test/resources/datanode1conf/iotdb-datanode.properties
- server/src/test/resources/datanode2conf/iotdb-datanode.properties
- server/src/test/resources/datanode3conf/iotdb-datanode.properties
The sync_dir parameter is used to configure the directory used by sync-tool, which was forgotten to be placed in the new iotdb-common.properties file.
> Add dn_sync_dir in iotdb-datanode.properties

- server/src/main/java/org/apache/iotdb/db/service/metrics/recorder/CompactionMetricsRecorder.java
When I check metrics, I find `data_written` metrics has same tag keys which is not recommend.
> [IOTDB-5024] Fix same tag keys in metrics

- antlr/src/main/antlr4/org/apache/iotdb/db/qp/sql/IoTDBSqlParser.g4
- docs/UserGuide/Data-Concept/Schema-Template.md
- docs/UserGuide/Operate-Metadata/Template.md
- docs/zh/UserGuide/Data-Concept/Schema-Template.md
- docs/zh/UserGuide/Operate-Metadata/Template.md
- integration-test/src/test/java/org/apache/iotdb/db/it/IoTDBSyntaxConventionIdentifierIT.java
- integration-test/src/test/java/org/apache/iotdb/db/it/schema/IoTDBDeactivateTemplateIT.java
1. Add schema template lifecycle description to help user better understand the usage of schema template
2. Strengthen SQL constraints of schema template to make ```schema``` keyword obligatory
> Add schema template lifecycle description and strengthen sql constraints

- server/src/main/java/org/apache/iotdb/db/engine/compaction/CompactionMetricsManager.java
1. `data_written`, `cost_task` metrics has same tag keys which is not recommend.
2. `cross_compaction_count` metrics has different tag keys in specific metrics.
> [IOTDB-5025][To rel/0.13] Fix the tag of metrics in 0.13 version

- server/src/main/java/org/apache/iotdb/db/metadata/mtree/store/disk/schemafile/AliasIndexPage.java
- server/src/main/java/org/apache/iotdb/db/metadata/mtree/store/disk/schemafile/InternalPage.java
- server/src/main/java/org/apache/iotdb/db/metadata/mtree/store/disk/schemafile/SchemaFile.java
- server/src/main/java/org/apache/iotdb/db/metadata/mtree/store/disk/schemafile/pagemgr/IPageManager.java
- server/src/main/java/org/apache/iotdb/db/metadata/mtree/store/disk/schemafile/pagemgr/PageManager.java
- server/src/main/java/org/apache/iotdb/db/tools/schema/SchemaFileSketchTool.java
- server/src/test/java/org/apache/iotdb/db/metadata/mtree/schemafile/SchemaFileTest.java
- server/src/test/java/org/apache/iotdb/db/tools/SchemaFileSketchTest.java
Previously SchemaFile provide a sketch method by building all text content into one single String, which may take unnecessary memory overhead. Now SchemaFile will flush sketched text into a PrintWriter in a page by page way so that even huge SchemaFile could be handled with a limited memory resource.
> Better schema file printer, not limited by length anymore

- thrift-commons/src/main/thrift/common.thrift
- thrift/src/main/thrift/client.thrift
No the generated go files have their packages.
However as the stupid plugin we used to generate thrift codes, we can't specify the parameter to generate with  full import path, which results the package `rpc` imports `common` but can't be used in iotdb-client-go directly, we should just change the import path manually as a workaround.
> Set namespace to generated go files

- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/write/InsertNode.java
When the auto create schema is closing, some schema of target measurement may be missing in fetched schema tree, which results in the npe when trying to get dataType from fetched schema.
> [IOTDB-4972] Fix NPE when validate schema without auto create schema

- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/distribution/DistributionPlanner.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/distribution/ExchangeNodeAdder.java
- server/src/test/java/org/apache/iotdb/db/mpp/plan/plan/distribution/AggregationDistributionTest.java
Before this PR, lots of FI will be generated even though they are only be distributed to several DataRegions. It is because some FI will be distributed to same DataRegion. It is limited by current implementation of Aggregation PlanNode/Operator.
In this PR, I made a separate distribution planning method for `Aggregation align by device`. That is, most of the device will only have one DataRegion related in one query, so we can group the node with the same DataRegion with one DeviceViewNode. And then add a DeviceMergeViewNode on all DeviceViewNodes. See the snapshot below:
(each color represents one different DataRegion)
> optimize the distribution plan for aggregation with align by device

- server/src/main/java/org/apache/iotdb/db/mpp/execution/executor/RegionWriteExecutor.java
When there's some internal runtime error, not caught, thrift will return an TException to the client and miss the meaningless message.
> Catch Throwable in DataNodeInternalService to avoid ambiguous TException

- server/src/main/java/org/apache/iotdb/db/service/IoTDBShutdownHook.java
See [IOTDB-5031](https://issues.apache.org/jira/browse/IOTDB-5031).
Trigger a snapshot when shutting down IoTDB could help reserve the compaction result, this pr makes it parallel to accelerate thisp process.
> [IOTDB-5031] Make snapshot taking in shutdown hook parallel

- server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
- server/src/test/java/org/apache/iotdb/db/mpp/execution/exchange/SinkHandleTest.java
- server/src/test/java/org/apache/iotdb/db/mpp/execution/exchange/SourceHandleTest.java
Currently, if we only change `storage_query_schema_consensus_free_memory_proportion`, it won't successfully change its corresponding children's memory if we don't change `chunk_timeseriesmeta_free_memory_proportion`, because they were already inited at first using default configuration.
> Make memory portion take effect after change the default ratio

- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/metedata/write/CreateMultiTimeSeriesNode.java
The abstract map, generated by Collections.singletonMap, is immutable, which will bring exception  when the schema registration check try to remove failing measurement from it. 
Therefore, replace it with hashmap.
> Fix abstract map bug when remove failing measurement

- consensus/src/main/java/org/apache/iotdb/consensus/multileader/logdispatcher/IndexController.java
Talked with @HeimingZ , this is a normal behavior when the log occurs. It is not a bug. So we change the log level from warn to info to avoid confusing users.
> [IOTDB-4556] change the log level from warn to info in IndexController

- consensus/src/main/java/org/apache/iotdb/consensus/ratis/RatisConsensus.java
Currently RatisConsensus treats failed consensus operations all as error level. However, some failures are expected and can be retries by caller. So I changed the level to INFO, leaving the ERROR/WARN decision to caller.
> [IOTDB-5034] Change log level

- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/distribution/SourceRewriter.java
The PlanNode should be cast to the parent class of Aggregation source rather a detailed implementation.
Before this fix:
After this fix:
> Fix the issue when doing distribution plan for aggregation

- confignode/src/main/java/org/apache/iotdb/confignode/consensus/statemachine/ConfigNodeRegionStateMachine.java
- node-commons/src/assembly/resources/conf/iotdb-common.properties
Make simple consensuse as default for confignode.
1. The file structure is as shown below:
2. The performance of simple is better than ratis 1 replica(DEVICE_NUMBER=5, SENSOR_NUMBER=10, GROUP_NUMBER=5). 
test result of simple
test result of ratis 1 replica
> Make simple consensuse as default for confignode

- server/src/main/java/org/apache/iotdb/db/engine/TsFileMetricManager.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/cross/CrossSpaceCompactionTask.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/inner/InnerSpaceCompactionTask.java
See [IOTDB-5004](https://issues.apache.org/jira/browse/IOTDB-5004).
The reason for this bug is that, when reducing the size of deleted tsfile after compaction, the deleted files return a size of zero. This pr fixes it by calculating the total size of deleted file before they are deleted, and reducing it after deletion of the files.
> [IOTDB-5004] [Metrics] Fix the seq file size in grafana is inconsistent with the actual query

- server/src/main/java/org/apache/iotdb/db/mpp/plan/scheduler/FragmentInstanceDispatcherImpl.java
Currently the error message only contains the int value of the statusCode, which is not very clear for operators.
> [IOTDB-4971] Print status code name when dispatch failed

- confignode/src/main/java/org/apache/iotdb/confignode/manager/ConfigManager.java
The problem described in IOTDB-5045 is mostly derived by concurrent operations on databases, thus add concurrent control.
Since database is a global heavy management unit, the sequence operation on it is fine.
> [IOTDB-5045] Add concurrent control to database create and drop operation

- server/src/main/java/org/apache/iotdb/db/mpp/execution/exchange/MPPDataExchangeManager.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/process/join/merge/MultiColumnMerger.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/source/AlignedSeriesScanOperator.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/source/SeriesScanOperator.java
- server/src/main/java/org/apache/iotdb/db/utils/ErrorHandlingUtils.java
- server/src/test/java/org/apache/iotdb/db/mpp/execution/DataDriverTest.java
- server/src/test/java/org/apache/iotdb/db/mpp/execution/operator/AlignedSeriesScanOperatorTest.java
- server/src/test/java/org/apache/iotdb/db/mpp/execution/operator/DeviceMergeOperatorTest.java
- server/src/test/java/org/apache/iotdb/db/mpp/execution/operator/DeviceViewOperatorTest.java
- server/src/test/java/org/apache/iotdb/db/mpp/execution/operator/LimitOperatorTest.java
- server/src/test/java/org/apache/iotdb/db/mpp/execution/operator/OffsetOperatorTest.java
- server/src/test/java/org/apache/iotdb/db/mpp/execution/operator/RawDataAggregationOperatorTest.java
- server/src/test/java/org/apache/iotdb/db/mpp/execution/operator/SeriesScanOperatorTest.java
- server/src/test/java/org/apache/iotdb/db/mpp/execution/operator/TimeJoinOperatorTest.java
- tsfile/src/main/java/org/apache/iotdb/tsfile/read/common/block/column/BinaryColumn.java
- tsfile/src/main/java/org/apache/iotdb/tsfile/read/common/block/column/BooleanColumn.java
- tsfile/src/main/java/org/apache/iotdb/tsfile/read/common/block/column/ColumnBuilder.java
- tsfile/src/main/java/org/apache/iotdb/tsfile/read/common/block/column/DoubleColumn.java
- tsfile/src/main/java/org/apache/iotdb/tsfile/read/common/block/column/FloatColumn.java
- tsfile/src/main/java/org/apache/iotdb/tsfile/read/common/block/column/IntColumn.java
- tsfile/src/main/java/org/apache/iotdb/tsfile/read/common/block/column/LongColumn.java
- tsfile/src/main/java/org/apache/iotdb/tsfile/read/common/block/column/RunLengthEncodedColumn.java
- tsfile/src/main/java/org/apache/iotdb/tsfile/read/common/block/column/TimeColumn.java
- tsfile/src/test/java/org/apache/iotdb/tsfile/common/block/NullColumnUnitTest.java
- tsfile/src/test/java/org/apache/iotdb/tsfile/read/common/ColumnTest.java
We do improvements in this pr:
1. make TsBlock returned by ScanOperator larger
2. fix a bug in MultiColumnMerger if there exist timestamp belonging to more than one DataRegion, currently we simply choose the first values as the final value
3. turn query error log to warn level
4. delete useless safety check in Column
> [IOTDB-5050] Try to make TsBlock returned by ScanOperator larger

- confignode/src/main/java/org/apache/iotdb/confignode/manager/ConsensusManager.java
Only SIMPLE_CONSENSUS need invoking `createPeerForConsensusGroup` when restarted, but RATIS_CONSENSUS doesn't need it
> fix restart problem in confignode simple

- server/src/test/java/org/apache/iotdb/db/engine/compaction/CompactionSchedulerTest.java
See [IOTDB-5068](https://issues.apache.org/jira/browse/IOTDB-5068).
The assertion at line 432 is not reasonable. Before this assertion, the test waits for all sequence space compaction task finish. After that, it asserts all unsequence files is compacted to sequence space, which doesn't have to happend, so it may fail some times.  We don't need this assertion, just remove it and the test has already assertted the num of sequence files and unsequence files in the end of the test.
> [To rel/1.0] [IOTDB-5068] Fix CompactionSchedulerTest

- integration-test/pom.xml
- testcontainer/pom.xml
Currently when user executes `mvn clean install -DskipTests`, the tests in integration-test and testcontainer are still running.  This PR will fix it.
> [To rel/1.0] Disable integration-tests and testcontainer in mvn install

- schema-engine-rocksdb/src/main/java/org/apache/iotdb/db/metadata/schemaregion/rocksdb/RSchemaRegion.java
- server/src/main/java/org/apache/iotdb/db/metadata/mtree/MTreeBelowSGCachedImpl.java
- server/src/main/java/org/apache/iotdb/db/metadata/mtree/MTreeBelowSGMemoryImpl.java
- server/src/main/java/org/apache/iotdb/db/metadata/schemaregion/RSchemaRegionLoader.java
- server/src/main/java/org/apache/iotdb/db/metadata/schemaregion/SchemaEngine.java
- server/src/main/java/org/apache/iotdb/db/metadata/schemaregion/SchemaRegionMemoryImpl.java
- server/src/main/java/org/apache/iotdb/db/metadata/schemaregion/SchemaRegionSchemaFileImpl.java
- server/src/test/java/org/apache/iotdb/db/metadata/mtree/MTreeBelowSGTest.java
Since the database name has already been checked on configNode when creating database, there's no need to check it again in SchemaEngine. We suppose all the internal requests are legal and SchemaEngine only need to execute them.
The async physical deletion of schemaRegion affects the creation of new region of new database with nested name, e.g. old db is root.udf and new db is root.udf.load, which results in the creation failure of new region and this shall not happen.
> [To rel/1.0] [IOTDB-5059] Remove redundant database check in SchemaEngine

- server/src/main/java/org/apache/iotdb/db/engine/compaction/cross/rewrite/CrossSpaceCompactionResource.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/cross/rewrite/RewriteCrossSpaceCompactionSelector.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/cross/CrossSpaceCompactionValidationTest.java
target file overlap with previous file 
**Reason**
In the process of getting the file list and starting to select files, the file list is updated (the file is deleted or the status is updated). When a seq file is occupied and deleted by other compaction thread, and it happens to select files in cross space compaction, the deleted file will be filtered out, resulting in an overlap target file.
**Solution**
Do not filter out any seq files before selecting the files. After selecting the files, judge whether the seq files have been deleted or being compacted. If there are any, the task will be discarded.
> [To rel/1.0][IOTDB-5093]Fix compaction selector bug

- docs/UserGuide/UDF-Library/M4.md
Valid the reference link used in a paper for some time.
Afterwards I'll remove this doc.
> add back the M4 doc temporarily

- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/DataRegion.java
Tested locally. We have verified that after this fix, the unsealed file's update for `LastFlushTime` will always be executed at the last step.
> [To rel/1.0][IOTDB-5101] Last flush time may replaced by previous files when recovering

- confignode/src/main/java/org/apache/iotdb/confignode/manager/ConfigManager.java
- confignode/src/main/java/org/apache/iotdb/confignode/service/ConfigNode.java
Create more databases to adjust The least number of DataRegionGroups per Database:
Add new ConfigNode:
> [To rel/1.0][IOTDB-5105] Remove least_data_region_group_num check when register Non-Seed-ConfigNode

- node-commons/src/main/java/org/apache/iotdb/commons/auth/role/LocalFileRoleAccessor.java
In ratis, it will not copy empty directory through snapshot which may cause NullPointerException when load.
Now, we temporarily check whether the folder is emty
> [To rel/1.0] [IOTDB-5109] Fix the load of role snapshot 

- .github/workflows/main-unix.yml
- node-commons/src/main/java/org/apache/iotdb/commons/path/AlignedPath.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/process/last/AbstractUpdateLastCacheOperator.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/process/last/AlignedUpdateLastCacheOperator.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/process/last/LastQueryOperator.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/process/last/LastQuerySortOperator.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/process/last/LastQueryUtil.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/AnalyzeVisitor.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/LogicalPlanBuilder.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/OperatorTreeGenerator.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/SubPlanTypeExtractor.java
- server/src/test/java/org/apache/iotdb/db/mpp/execution/operator/OperatorMemoryTest.java
Previously, we construct a PlanNode for every measurement of an AlignedPath which is unnecessary. This PR aims to reduce the cost of construcing unnecessary PlanNode for last query on aligned timeseries.
> [IOTDB-5026] Improve last query on aligned timeseries

- server/src/main/java/org/apache/iotdb/db/mpp/plan/execution/memory/StatementMemorySourceVisitor.java
When explain the sql with align by device, the server will return a null result because of the judgement in visitExplain ingore the situation of align by device.
This PR adjust the conditions.
> [To rel/1.0] [IOTDB-5102] Support Align by deivce in VisitExplain

- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/distribution/SourceRewriter.java
In raw data query for local data in device view, only one deviceViewNode is enough for the querying task. However in distribution plan, a redundant deviceMergeNode is generated although there is only one child of deiviceViewNode.
After this PR, visitDeviceView in SourceRewriter return deviceViewNode directly if it's the only one.
> [To rel/1.0] [IOTDB-5114] Redundant planNode after distribution plan in raw data query with align by device

- server/src/main/java/org/apache/iotdb/db/service/DataNode.java
When fail to start a Datanode, `SchemaRegionConsensusImpl` and `DataRegionConsensusImpl` will be null instead of being init , so need to add a check whether they are nullpoints when stop the datanode.
> [IOTDB-5090] Add npe check in DataNode

- confignode/src/main/java/org/apache/iotdb/confignode/persistence/ProcedureInfo.java
- confignode/src/main/java/org/apache/iotdb/confignode/procedure/store/ProcedureStore.java
- server/src/main/java/org/apache/iotdb/db/service/metrics/FileMetrics.java
- server/src/main/java/org/apache/iotdb/db/wal/WALManager.java
- server/src/main/java/org/apache/iotdb/db/wal/buffer/AbstractWALBuffer.java
- server/src/main/java/org/apache/iotdb/db/wal/node/WALNode.java
- server/src/main/java/org/apache/iotdb/db/wal/recover/WALNodeRecoverTask.java
FileUtils.listFiles in the commons io doesn't use Files.walk with try-with-resources contract, this error is same as [JDK-8250785](https://bugs.openjdk.org/browse/JDK-8250785)
> [IOTDB-5118] FileMetric opens too many file descriptors

- confignode/src/main/java/org/apache/iotdb/confignode/persistence/ProcedureInfo.java
- confignode/src/main/java/org/apache/iotdb/confignode/procedure/store/ProcedureStore.java
- server/src/main/java/org/apache/iotdb/db/service/metrics/FileMetrics.java
- server/src/main/java/org/apache/iotdb/db/wal/WALManager.java
- server/src/main/java/org/apache/iotdb/db/wal/buffer/AbstractWALBuffer.java
- server/src/main/java/org/apache/iotdb/db/wal/node/WALNode.java
- server/src/main/java/org/apache/iotdb/db/wal/recover/WALNodeRecoverTask.java
FileUtils.listFiles in the commons io doesn't use Files.walk with try-with-resources contract, this error is same as [JDK-8250785](https://bugs.openjdk.org/browse/JDK-8250785)
> [To rel/1.0][IOTDB-5118] FileMetric opens too many file descriptors

- server/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java
remove the method `replaceHostnameWithIP` in IoTDBDescriptor
> [IOTDB-5126] Fix show datanodes' rpcAddress IP but not hostname bug

- server/src/main/java/org/apache/iotdb/db/service/DataNode.java
When fail to start a Datanode, SchemaRegionConsensusImpl and DataRegionConsensusImpl will be null instead of being init , so need to add a check whether they are nullpoints when stop the datanode.
> [To rel/1.0][IOTDB-5090] Add npe check in DataNode

- server/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java
remove the method replaceHostnameWithIP in IoTDBDescriptor
> [To rel/1.0][IOTDB-5126] Fix show datanodes' rpcAddress IP but not hostname bug 

- confignode/src/test/java/org/apache/iotdb/confignode/persistence/ClusterSyncInfoTest.java
- node-commons/src/main/java/org/apache/iotdb/commons/sync/metadata/SyncMetadata.java
- node-commons/src/main/java/org/apache/iotdb/commons/sync/persistence/SyncLogWriter.java
This problem is caused by the fact that when `ClusterSyncInfo` is empty, `SyncLogWriter` will not generate a tmpFile and `tmpFile.renameTo(snapshotFile)` will return false.
Force the file to be initialised when taking a snapshot.
> [To rel/1.0][IOTDB-5135] Sync snapshot fails when sync file is empty

- client-cpp/pom.xml
- compile-tools/pom.xml
- distribution/pom.xml
- example/client-cpp-example/pom.xml
- example/trigger/pom.xml
- example/udf/pom.xml
- grafana-connector/pom.xml
- grafana-plugin/pom.xml
- integration-test/src/test/java/org/apache/iotdb/session/it/IoTDBSessionSyntaxConventionIT.java
- integration/pom.xml
- jdbc/pom.xml
- node-commons/src/main/java/org/apache/iotdb/commons/utils/PathUtils.java
- pom.xml
- server/src/main/java/org/apache/iotdb/db/mpp/plan/parser/ASTVisitor.java
- server/src/main/java/org/apache/iotdb/db/service/thrift/impl/ClientRPCServiceImpl.java
- server/src/main/java/org/apache/iotdb/db/service/thrift/impl/TSServiceImpl.java
Previously we forget to update the checked measurements as node name  like \`aa\` should be stored as aa.
> update nodenames if necessary in ClientRpcServiceImpl

- server/src/main/java/org/apache/iotdb/db/sync/externalpipe/ExtPipePluginRegister.java
problem:
https://apache-iotdb.feishu.cn/docx/YOGldZTBionIBIxCmKrcP6WNnzg
The same situation in ExtPipePluginRegister.
solution:
replace FileUtils.listFiles with try-catch and FileUtils.steamFiles.
>  replace FileUtils.listFiles in ExtPipePluginRegister with try-catch 

- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/timeindex/DeviceTimeIndex.java
- tsfile/src/main/java/org/apache/iotdb/tsfile/file/header/ChunkHeader.java
- tsfile/src/main/java/org/apache/iotdb/tsfile/utils/ReadWriteIOUtils.java
- tsfile/src/test/java/org/apache/iotdb/tsfile/utils/ReadWriteIOUtilsTest.java
`InputStream` may skip over some smaller number of bytes. So I implement a skip method in ReadWriteIOUtils to guarantee skip n bytes or reach end of file.
> [IOTDB-5158] Fix InputStream may skip over some smaller number of bytes 

- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/timeindex/DeviceTimeIndex.java
- tsfile/src/main/java/org/apache/iotdb/tsfile/file/header/ChunkHeader.java
- tsfile/src/main/java/org/apache/iotdb/tsfile/utils/ReadWriteIOUtils.java
- tsfile/src/test/java/org/apache/iotdb/tsfile/utils/ReadWriteIOUtilsTest.java
`InputStream` may skip over some smaller number of bytes. So I implement a skip method in ReadWriteIOUtils to guarantee skip n bytes or reach end of file.
> [To rel/1.0][IOTDB-5158] Fix InputStream may skip over some smaller number of bytes

- integration-test/src/test/java/org/apache/iotdb/db/it/aggregation/IoTDBAggregationIT.java
- integration-test/src/test/java/org/apache/iotdb/db/it/groupby/IOTDBGroupByIT.java
- node-commons/src/main/java/org/apache/iotdb/commons/partition/ExecutorType.java
- node-commons/src/main/java/org/apache/iotdb/commons/partition/QueryExecutor.java
- node-commons/src/main/java/org/apache/iotdb/commons/partition/StorageExecutor.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/executor/RegionReadExecutor.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/Analysis.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/distribution/SimpleFragmentParallelPlanner.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/distribution/WriteFragmentParallelPlanner.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/FragmentInstance.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/scheduler/FragmentInstanceDispatcherImpl.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/scheduler/load/LoadTsFileScheduler.java
- server/src/main/java/org/apache/iotdb/db/service/thrift/impl/DataNodeInternalRPCServiceImpl.java
- server/src/test/java/org/apache/iotdb/db/mpp/plan/plan/FragmentInstanceSerdeTest.java
- server/src/test/java/org/apache/iotdb/db/mpp/plan/scheduler/StandaloneSchedulerTest.java
- thrift/src/main/thrift/datanode.thrift
The FI of AggQuery with no dataRegion will has  `QueryExecutor` to indicate it will be executed locally with no use of Consensus.
> [To rel/1.0] [IOTDB-5116] Fix wrong empty result set in aggregation query

- integration-test/src/test/java/org/apache/iotdb/db/it/alignbydevice/IoTDBOrderByWithAlignByDeviceIT.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/OperatorTreeGenerator.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/distribution/ExchangeNodeAdder.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/process/SingleDeviceViewNode.java
- server/src/test/java/org/apache/iotdb/db/mpp/plan/plan/node/process/SingleDeviceViewNodeSerdeTest.java
1. add cacheOutputColumnNames to SingleDeviceViewNode to judge if the Node should cache outputColumnNames
2. currently the fix refers to code changing of visitMergeSort in ExchangeNodeAdder. May be there is a better way.
> [IOTDB-5172] Fix SingleDeviceViewNode can't get outputColumnTypes when it's isolated

- node-commons/src/main/java/org/apache/iotdb/commons/partition/ExecutorType.java
- node-commons/src/main/java/org/apache/iotdb/commons/partition/StorageExecutor.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/distribution/WriteFragmentParallelPlanner.java
cause: The `RegionReplicset` of `StorageExecutor` may be null.
> [IOTDB-5199]fix NPE in StorageExector inLoading process

- server/src/main/java/org/apache/iotdb/db/metadata/schemaregion/SchemaRegionMemoryImpl.java
- server/src/main/java/org/apache/iotdb/db/metadata/schemaregion/SchemaRegionSchemaFileImpl.java
When the schemaRegion is not initialized or has been cleared, the create snapshot operation may result in NPE.
> [IOTDB-5061] Add initialize state check when create snapshot

- server/src/main/java/org/apache/iotdb/db/engine/compaction/CompactionTaskManager.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/cross/CrossSpaceCompactionTest.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/inner/InnerSeqCompactionTest.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/inner/InnerUnseqCompactionTest.java
OutOfMemory unable to create new native thread
**Reason**
The sub threads in `CompactionTaskManager` are not closed. During the test, new sub compaction thread pool is constantly created and the number of sub-threads increases, which causes OOM.
**Solution**
Close the sub compaction threads in `CompactionTaskManager` after each test.
> [To rel/0.13][IOTDB-5183]Fix CI OOM

- server/src/main/java/org/apache/iotdb/db/engine/compaction/CompactionTaskManager.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/task/ICompactionSelector.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/CompactionSchedulerTest.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/CompactionSchedulerWithFastPerformerTest.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/utils/CompactionConfigRestorer.java
OutOfMemory unable to create new native thread
**Reason**
The sub threads in `CompactionTaskManager` are not closed. During the test, new sub compaction thread pool is constantly created and the number of sub-threads increases, which causes OOM.
**Solution**
Close the sub compaction threads in `CompactionTaskManager` after each test.
> [To rel/1.0][IOTDB-5183]Fix CI OOM

- consensus/src/main/java/org/apache/iotdb/consensus/iot/logdispatcher/IndexController.java
- consensus/src/main/java/org/apache/iotdb/consensus/iot/logdispatcher/LogDispatcher.java
- consensus/src/test/java/org/apache/iotdb/consensus/iot/logdispatcher/IndexControllerTest.java
- consensus/src/test/java/org/apache/iotdb/consensus/iot/logdispatcher/SyncStatusTest.java
see [jira5174](https://issues.apache.org/jira/browse/IOTDB-5174)
> [IOTDB-5174] Use filename format such as NodeID-Index rather than Endpoint-Index to track follower sync progress

- consensus/src/main/java/org/apache/iotdb/consensus/exception/RatisRequestFailedException.java
Currently cause is not serialized and returned to confignode. Add detailed message so that the cause is contained in the error message.
> [IOTDB-5061] Add message in RatisRequestFailed

- docs/UserGuide/Reference/Common-Config-Manual.md
- docs/zh/UserGuide/Reference/Common-Config-Manual.md
- node-commons/src/assembly/resources/conf/iotdb-common.properties
- server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
- server/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/CompactionTaskManager.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/cross/utils/AlignedSeriesCompactionExecutor.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/cross/utils/NonAlignedSeriesCompactionExecutor.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/inner/utils/AlignedSeriesCompactionExecutor.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/inner/utils/SingleSeriesCompactionExecutor.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/writer/AbstractCompactionWriter.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/utils/CompactionConfigRestorer.java
See [IOTDB-5209](https://issues.apache.org/jira/browse/IOTDB-5209).
This PR limits both the read rate and write rate of compaction execution.
> [IOTDB-5209] Limit the read rate of compaction execution

- server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
Currently, when user assigns a customized data_dir in iotdb-datanode.properties, the ratis snapshot dir is not updated with this customized value, so that there will be inconsistent snapshot dirs.
In this pr I propose to update ratis snapshot dir togather with data_dir.
> [IOTDB-5176] Change ratis snapshot dir with datadir 

- docs/Development/ContributeGuide.md
> add instruction about how to allow large java file generated by Thrift in IDEA

- integration-test/import-control.xml
- integration-test/pom.xml
- integration-test/src/test/java/org/apache/iotdb/db/it/sync/IoTDBPipeIT.java
Fix errors in IoTDBPipeIT.
This error may be caused by an asynchronous operation that has not completed. According to the writing specification., I use `Awaitility.await` to avoid this error.
> [IOTDB-5054] Fix errors in IoTDBPipeIT

- confignode/src/assembly/resources/sbin/start-confignode.bat
- confignode/src/assembly/resources/sbin/start-confignode.sh
- confignode/src/assembly/resources/sbin/stop-confignode.sh
- node-commons/src/assembly/resources/sbin/iotdb-common.sh
- node-commons/src/assembly/resources/sbin/start-standalone.bat
- node-commons/src/assembly/resources/sbin/stop-standalone.bat
- server/src/assembly/resources/sbin/start-datanode.bat
- server/src/assembly/resources/sbin/start-datanode.sh
- server/src/assembly/resources/sbin/stop-datanode.bat
- server/src/assembly/resources/sbin/stop-datanode.sh
> [To rel/1.0] [IOTDB-5125] Change default port and stop the process when port is already in use

- server/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java
Use internal address and port which is consistent with confignode
> [IOTDB-5250] Unify the address or port of metric module in DataNode

- confignode/src/main/java/org/apache/iotdb/confignode/conf/ConfigNodeConfig.java
- confignode/src/main/java/org/apache/iotdb/confignode/conf/SystemPropertiesUtils.java
- integration-test/src/test/java/org/apache/iotdb/confignode/it/cluster/IoTDBClusterNodeErrorStartUpIT.java
- server/src/main/java/org/apache/iotdb/db/client/ConfigNodeClient.java
- server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
- server/src/main/java/org/apache/iotdb/db/service/DataNode.java
I have test the upgrate from 1.0 to master.
system file of 1.0
> Start ConfigNode and DataNode successfully when cluster_name is missed

- server/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java
Use internal address and port which is consistent with confignode
(cherry picked from commit 47aac84dc9c51cf6e68ea053f8bfe0e4c185f59d)
> [To rel/1.0][IOTDB-5250] Unify the address or port of metric module in DataNode (#8541)

- node-commons/src/assembly/resources/conf/iotdb-common.properties
- server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
Modify the default value of `iot_consensus_cache_window_time_in_ms` to 10*1000 which is 10s
> [IOTDB-5256] Modify the default value of `iot_consensus_cache_window_time_in_ms`

- server/src/main/java/org/apache/iotdb/db/qp/physical/sys/ShowDevicesPlan.java
- server/src/main/java/org/apache/iotdb/db/qp/physical/sys/ShowTimeSeriesPlan.java
- server/src/test/java/org/apache/iotdb/db/mpp/execution/operator/schema/CountMergeOperatorTest.java
- server/src/test/java/org/apache/iotdb/db/mpp/execution/operator/schema/SchemaCountOperatorTest.java
- server/src/test/java/org/apache/iotdb/db/mpp/execution/operator/schema/SchemaFetchScanOperatorTest.java
- server/src/test/java/org/apache/iotdb/db/mpp/execution/operator/schema/SchemaQueryScanOperatorTest.java
Use Mockito to mock schemaRegion rather than rely on SchemaEngine or LocalConfigNode.
> [IOTDB-5226] Correct the style and reliance of schema operator UT

- node-commons/src/main/java/org/apache/iotdb/commons/path/PathPatternTree.java
- node-commons/src/test/java/org/apache/iotdb/commons/path/PathPatternTreeTest.java
see https://issues.apache.org/jira/browse/IOTDB-5269
Add special judge when encountering \*\* during the process of pattern tree.
> [To rel/1.0][IOTDB-5269] Fix PathPatternTree.getAllDevicePatterns bug

- node-commons/src/main/java/org/apache/iotdb/commons/path/PathPatternTree.java
- node-commons/src/test/java/org/apache/iotdb/commons/path/PathPatternTreeTest.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/AnalyzeVisitor.java
see https://issues.apache.org/jira/browse/IOTDB-5269
Add special judge when encountering \*\* during the process of pattern tree.
> [IOTDB-5269] Fix PathPatternTree.getAllDevicePatterns

- node-commons/src/assembly/resources/conf/iotdb-common.properties
- server/src/main/java/org/apache/iotdb/db/mpp/execution/memory/MemoryPool.java
- server/src/test/java/org/apache/iotdb/db/mpp/execution/exchange/SinkHandleTest.java
- server/src/test/java/org/apache/iotdb/db/mpp/execution/operator/OperatorMemoryTest.java
- tsfile/src/main/java/org/apache/iotdb/tsfile/common/conf/TSFileConfig.java
- tsfile/src/main/java/org/apache/iotdb/tsfile/read/common/block/TsBlockBuilder.java
In default, pageSizeInByte is 64K, but maxTsBlockSizeInBytes is 1M, which brings much memory pressure since we have reserver memory space for it in advance.
Therefore, I suggest to turn down this config to 128K, which can contain 2 pages at most.
For more detail, refer to https://apache-iotdb.feishu.cn/docx/O5XCdvEHPoDdtNxFHlXcV6xlnoh
> Turn down the max capacity of tsblock from scanOperator

- server/src/main/java/org/apache/iotdb/db/metadata/MetadataConstant.java
- server/src/main/java/org/apache/iotdb/db/metadata/mtree/snapshot/MemMTreeSnapshotUtil.java
- server/src/test/java/org/apache/iotdb/db/metadata/schemaRegion/SchemaRegionBasicTest.java
This problem is caused by loading empty storage group snaptshot. 
When the `childrenNum` of root node is 0, it still needs to be added into `ancestors` and processed by `inorderDeserialize`. Otherwise the root node returned would be null.
```
private static IMNode inorderDeserialize(
InputStream inputStream, Consumer<IMeasurementMNode> measurementProcess) throws IOException {
MNodeDeserializer deserializer = new MNodeDeserializer();
Deque<IMNode> ancestors = new ArrayDeque<>();
Deque<Integer> restChildrenNum = new ArrayDeque<>();
deserializeMNode(ancestors, restChildrenNum, deserializer, inputStream, measurementProcess);
int childrenNum;
IMNode root = ancestors.peek();
while (!ancestors.isEmpty()) {
childrenNum = restChildrenNum.pop();
if (childrenNum == 0) {
ancestors.pop();
} else { …
```
> [To rel/1.0][IOTDB-5277] SchemaRegion throws NPE when loading snapshot

- server/src/main/java/org/apache/iotdb/db/engine/compaction/cross/rewrite/manage/CrossSpaceCompactionResource.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/cross/rewrite/selector/RewriteCompactionFileSelector.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/inner/sizetiered/SizeTieredCompactionSelector.java
- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/TsFileResource.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/cross/RewriteCompactionFileSelectorTest.java
Throw RunTimeException during selecting files in compaction: Cannot set the status of TsFileResource to COMPACTION_ CANDIDATE while its status is DELETED.
**Solution**
Filter out the deleted file when selecting files.
> [To rel/0.13][IOTDB-5281]Fix selecting deleted files in 0.13

- server/src/main/java/org/apache/iotdb/db/engine/compaction/CompactionUtils.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/cross/CrossSpaceCompactionTask.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/performer/impl/FastCompactionPerformer.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/writer/AbstractCrossCompactionWriter.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/writer/FastCrossCompactionWriter.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/writer/ReadPointCrossCompactionWriter.java
- server/src/main/java/org/apache/iotdb/db/query/control/FileReaderManager.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/FastCrossCompactionPerformerTest.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/FastInnerCompactionPerformerTest.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/ReadPointCompactionPerformerTest.java
If TsFileResource is degraded to FileTimeIndex and then compacted with fast performer, it will create more file handles. To solve this problem, we should remove the usage of FileReaderManager in fast compaction.
> [To rel/1.0][IOTDB-5208]Fix file handles increase when TsFileResource is degraded and compacted with fast performer

- server/src/main/java/org/apache/iotdb/db/engine/compaction/CompactionUtils.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/cross/CrossSpaceCompactionTask.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/performer/impl/FastCompactionPerformer.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/writer/AbstractCrossCompactionWriter.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/writer/FastCrossCompactionWriter.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/writer/ReadPointCrossCompactionWriter.java
- server/src/main/java/org/apache/iotdb/db/query/control/FileReaderManager.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/FastCrossCompactionPerformerTest.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/FastInnerCompactionPerformerTest.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/ReadPointCompactionPerformerTest.java
If TsFileResource is degraded to FileTimeIndex and then compacted with fast performer, it will create more file handles. To solve this problem, we should remove the usage of FileReaderManager in fast compaction.
> [IOTDB-5208]Fix file handles increase when TsFileResource is degraded and compacted with fast performer

- integration-test/src/test/java/org/apache/iotdb/confignode/it/cluster/IoTDBClusterNodeErrorStartUpIT.java
See JIRA: https://issues.apache.org/jira/browse/IOTDB-5297
This PR is a small fix of #8481
> [IOTDB-5297] Add maxRetryTimes for IoTDBClusterNodeErrorStartUpIT to avoid infinite loop

- server/src/main/java/org/apache/iotdb/db/wal/buffer/WALBuffer.java
This bug is caused by isClosed flag. After isClosed is set to true, the wal node won‘t submmit serialize task any more, and close method will block at the put method when the walEntries queue is full. So, we should set isClosed to true after the put method.
> [To rel/1.0][IOTDB-5294] WAL Node close method blocks

- server/src/main/java/org/apache/iotdb/db/wal/buffer/WALBuffer.java
This bug is caused by isClosed flag. After isClosed is set to true, the wal node won‘t submmit serialize task any more, and close method will block at the put method when the walEntries queue is full. So, we should set isClosed to true after the put method.
> [IOTDB-5294] WAL Node close method blocks

- server/src/main/java/org/apache/iotdb/db/engine/compaction/cross/rewrite/TsFileDeviceInfoStore.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/cross/rewrite/selector/RewriteCompactionFileSelector.java
- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/TsFileResource.java
- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/timeindex/DeviceTimeIndex.java
- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/timeindex/ITimeIndex.java
Before this change, the FileTimeIndex may be used to judge the overlap of one device between two TsFiles when selecting cross space compaction task, which is not accurate and may lead to omission of related `seqFile`s.
This PR will use the DeviceTimeIndex in force when doing the selection and will load the DeviceTimeIndex from resource file for one TsFile if its DeviceTimeIndex is not cached in memory.
We use a `deviceInfoStore` to cache all DeviceTimeIndex for seq files.
In this PR, we follow the principle to keep the original code logic as much as possible to avoid new bugs introduced
1. basic test
2. local debug test
From the local debug case, we make the TimeIndex load from resource file in force. And we can see that the method can load the DeviceTimeIndex successfully.
The compaction …
> [To rel/0.13] Fix the issue that the TimeIndex may not be accurate for one device when selecting cross space compaction task

- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/VirtualStorageGroupProcessor.java
The process of compaction selecting files may throws No Such File exception and RunTimeException, causing compaction schedule thread to get stuck.
**Reason**
The process of selecting file does not add read locks of the source files. Assuming that the file was not deleted at the moment the deleted file was filtered, but was later deleted, No such file exception would be thrown when the reader for the file was built, and a RunTimeException would be thrown when the state was set to CompactionCandidate. Among them, the fix scheduled thread of compaction stops on 0.13, but not on master and 1.0.
**Solution**
Do an exception catch in compaction schedule method.
When building a reader for a file, throw IOException instead of NPE if the file does not exist.
> [To rel/0.13][IOTDB-5311]Fix RunTimeException and NoSuchFile Exception when selecting files causing compaction scheduled thread to get stuck

- server/src/main/java/org/apache/iotdb/db/engine/compaction/cross/rewrite/RewriteCrossSpaceCompactionSelector.java
- tsfile/src/main/java/org/apache/iotdb/tsfile/fileSystem/fileInputFactory/FileInputFactory.java
- tsfile/src/main/java/org/apache/iotdb/tsfile/fileSystem/fileInputFactory/HDFSInputFactory.java
- tsfile/src/main/java/org/apache/iotdb/tsfile/fileSystem/fileInputFactory/LocalFSInputFactory.java
- tsfile/src/main/java/org/apache/iotdb/tsfile/read/TsFileSequenceReader.java
因TsFileResource状态修改存在并发问题，导致ttl删除文件和合并冲突，最终导致合并定时任务卡死，原因是未捕获到npe异常
当前PR实现内容：
1、捕获文件不存在异常
2、捕获跨区合并Exception异常
未解决内容：
修改TsFileResource状态时需要增加并发控制
> [To rel/0.13][IOTDB-5307] Failed to get TsFile input of file: NoSuchFileException

- server/src/main/java/org/apache/iotdb/db/metadata/mtree/store/disk/schemafile/ISchemaPage.java
- server/src/main/java/org/apache/iotdb/db/metadata/mtree/store/disk/schemafile/ISegmentedPage.java
- server/src/main/java/org/apache/iotdb/db/metadata/mtree/store/disk/schemafile/InternalPage.java
- server/src/main/java/org/apache/iotdb/db/metadata/mtree/store/disk/schemafile/SchemaPage.java
- server/src/main/java/org/apache/iotdb/db/metadata/mtree/store/disk/schemafile/SegmentedPage.java
- server/src/main/java/org/apache/iotdb/db/metadata/mtree/store/disk/schemafile/pagemgr/PageManager.java
- server/src/main/java/org/apache/iotdb/db/metadata/mtree/traverser/Traverser.java
The root of this issue is that `SegmentedPage` missed the width of segments offset when check spare size with the requested segment within method `isCapableFor`(renamed to `isCapableForSegSize` now). It only turns up with the segment size steps implemented by https://github.com/apache/iotdb/pull/7726 which was meant to improve space utilization, and under certain work load where a `SegmentedPage` was requested to allocate a 1020B segment with another fifteen 1020B segment alive along with one invliad segment offset. In the previous implementation, modification to the headmost segment offset will contaminate last few bytes of the last segment thus an **out of bound exception** was buried and will only be exposed as those bytes was accessed.
The exception may come up as any erroneous state …
> Fix out of bound Segment access in SchemaFile

- server/src/main/java/org/apache/iotdb/db/mpp/plan/execution/QueryExecution.java
This PR fixes two issues.
1. redirect writing only if the redirectEndPoint is not the current node
2. when statusCode == TSStatusCode.SUCCESS_STATUS, a 'no detailed failure reason in QueryStateMachine' message was set in TSStatus
> Optimize write redirection logic

- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/DataRegion.java
- tsfile/src/main/java/org/apache/iotdb/tsfile/fileSystem/fileInputFactory/FileInputFactory.java
- tsfile/src/main/java/org/apache/iotdb/tsfile/fileSystem/fileInputFactory/HDFSInputFactory.java
- tsfile/src/main/java/org/apache/iotdb/tsfile/fileSystem/fileInputFactory/LocalFSInputFactory.java
The process of compaction selecting files may throws No Such File exception and RunTimeException, causing compaction schedule thread to get stuck.
**Reason**
The process of selecting file does not add read locks of the source files. Assuming that the file was not deleted at the moment the deleted file was filtered, but was later deleted, No such file exception would be thrown when the reader for the file was built, and a RunTimeException would be thrown when the state was set to CompactionCandidate. Among them, the fix scheduled thread of compaction stops on 0.13, but not on master and 1.0.
**Solution**
Do an exception catch in compaction schedule method.
When building a reader for a file, throw IOException instead of NPE if the file does not exist.
> [To rel/1.0][IOTDB-5311]Fix RunTimeException and NoSuchFile Exception when selecting files causing compaction scheduled thread to get stuck

- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/DataRegion.java
- tsfile/src/main/java/org/apache/iotdb/tsfile/fileSystem/fileInputFactory/FileInputFactory.java
- tsfile/src/main/java/org/apache/iotdb/tsfile/fileSystem/fileInputFactory/HDFSInputFactory.java
- tsfile/src/main/java/org/apache/iotdb/tsfile/fileSystem/fileInputFactory/LocalFSInputFactory.java
The process of compaction selecting files may throws No Such File exception and RunTimeException, causing compaction schedule thread to get stuck.
**Reason**
The process of selecting file does not add read locks of the source files. Assuming that the file was not deleted at the moment the deleted file was filtered, but was later deleted, No such file exception would be thrown when the reader for the file was built, and a RunTimeException would be thrown when the state was set to CompactionCandidate. Among them, the fix scheduled thread of compaction stops on 0.13, but not on master and 1.0.
**Solution**
Do an exception catch in compaction schedule method.
When building a reader for a file, throw IOException instead of NPE if the file does not exist.
> [IOTDB-5311]Fix RunTimeException and NoSuchFile Exception when selecting files causing compaction scheduled thread to get stuck

- isession/src/main/java/org/apache/iotdb/isession/SessionDataSet.java
- session/src/main/java/org/apache/iotdb/session/SessionConnection.java
Session.setFetchSize only applies for the first query execution request and the following fetch request uses the default fetch size 5000. The reason is that the construction method of SessionDataSet in `SessionConnection.executeQueryStatement` uses `SessionConfig.DEFAULT_FETCH_SIZE` instead of the actual `session.fetchSize`. So this pr fixes this bug.
> [IOTDB-5316] fix bug that Session.setFetchSize is not used in the following fetch requests

- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/DataRegion.java
See [IOTDB-5160](https://issues.apache.org/jira/browse/IOTDB-5160), [IOTDB-5279](https://issues.apache.org/jira/browse/IOTDB-5279).
The reason for this bug is the program fails to traverse the whole file list in recovering. As a result, the number and size of the files in metrics are smaller than the actual value.
> [IOTDB-5160] [Metric] Fix the file count of datanode become negative number

- node-commons/src/assembly/resources/conf/iotdb-common.properties
> [IOTDB-5333] Fix a typo of max_tsblock_line_number in iotdb-common.properties

- server/src/main/java/org/apache/iotdb/db/metadata/utils/MetaUtils.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/OperatorTreeGenerator.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/distribution/SourceRewriter.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/process/last/LastQueryNode.java
While there exist multi data regions for one series slot, we will add LastMergeSortNode to merge all last query result from different data regions, it will select max time for the same time-series.
However, if so, we still need to add default order by parameter for each LastQueryNode in each DataRegion and sort its children by timeseries asc, because `LastQueryMergeOperator` will assume that all its children returning TsBlock has already been sorted.
> [IOTDB-5245] Fix bug in last query

- node-commons/src/main/java/org/apache/iotdb/commons/conf/IoTDBConstant.java
- server/src/main/java/org/apache/iotdb/db/conf/IoTDBStartCheck.java
- server/src/main/java/org/apache/iotdb/db/mpp/common/header/ColumnHeaderConstant.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/execution/config/metadata/ShowClusterDetailsTask.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/execution/config/metadata/ShowClusterParametersTask.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/execution/config/metadata/ShowClusterTask.java
Changes:
1. Remove `CLUSTER_NAME` definition in IoTDBStartupCheck.
2. Definition `CLUSTER_NAME = "cluster_name"` is in IoTDBConstant, which will be used for reading configuration files.
3. Definition `COLUMN_CLUSTER_NAME = "ClusterName"` is in ColumnHeaderConstant, which will be used for indicating a row result of SQL: `SHOW VARIABLES`.
> Fix cluster_name definition conflict

- server/src/main/java/org/apache/iotdb/db/query/control/SessionManager.java
2022-12-10 00:00:25,353 [pool-16-IoTDB-RPC-Client-2074] ERROR o.a.t.ProcessFunction:47 - Internal error processing closeSession 
java.lang.NullPointerException: null
at org.apache.iotdb.db.service.thrift.impl.TSServiceImpl.closeSession(TSServiceImpl.java:343)
at org.apache.iotdb.service.rpc.thrift.TSIService$Processor$closeSession.getResult(TSIService.java:3076)
at org.apache.iotdb.service.rpc.thrift.TSIService$Processor$closeSession.getResult(TSIService.java:3056)
at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:38)
at org.apache.iotdb.db.service.thrift.ProcessorWithMetrics.process(ProcessorWithMetrics.java:64)
at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:248)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown …
> [To rel/0.13][IOTDB-5296]fix close session npe when session is null

- integration-test/src/test/java/org/apache/iotdb/confignode/it/partition/IoTDBPartitionGetterIT.java
Modify a test configuration to avoid local test bug. Since our local computers always have sufficient CPUs, this IT will create DataRegionGroups for each StorageGroups that more than expected(leastDataRegionGroupNum).
> Fix testGetSlots IT bug

- server/src/main/java/org/apache/iotdb/db/conf/IoTDBStartCheck.java
The system writes system.properties before pulling config from the confignode, which causes error when the first startup. So, I overwrite the system.properties when the first startup.
> [IOTDB-5285] Modifying system properties before the initial startup causes the datanode to fail to start

- schema-engine-rocksdb/src/main/java/org/apache/iotdb/db/metadata/schemaregion/rocksdb/RSchemaRegion.java
- schema-engine-tag/src/main/java/org/apache/iotdb/db/metadata/tagSchemaRegion/TagSchemaRegion.java
- server/src/main/java/org/apache/iotdb/db/metadata/mtree/IMTreeBelowSG.java
- server/src/main/java/org/apache/iotdb/db/metadata/mtree/MTreeBelowSGCachedImpl.java
- server/src/main/java/org/apache/iotdb/db/metadata/mtree/MTreeBelowSGMemoryImpl.java
- server/src/main/java/org/apache/iotdb/db/metadata/mtree/traverser/collector/EntityCollector.java
- server/src/main/java/org/apache/iotdb/db/metadata/plan/schemaregion/impl/read/SchemaRegionReadPlanFactory.java
- server/src/main/java/org/apache/iotdb/db/metadata/plan/schemaregion/impl/read/ShowDevicesPlanImpl.java
- server/src/main/java/org/apache/iotdb/db/metadata/plan/schemaregion/read/IShowDevicesPlan.java
- server/src/main/java/org/apache/iotdb/db/metadata/schemaregion/ISchemaRegion.java
- server/src/main/java/org/apache/iotdb/db/metadata/schemaregion/SchemaRegionMemoryImpl.java
- server/src/main/java/org/apache/iotdb/db/metadata/schemaregion/SchemaRegionSchemaFileImpl.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/schema/DevicesSchemaScanOperator.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/schema/PathsUsingTemplateScanOperator.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/schema/SchemaQueryScanOperator.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/schema/TimeSeriesSchemaScanOperator.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/OperatorTreeGenerator.java
- server/src/test/java/org/apache/iotdb/db/metadata/schemaRegion/SchemaRegionTemplateTest.java
- server/src/test/java/org/apache/iotdb/db/metadata/schemaRegion/SchemaRegionTestUtil.java
- server/src/test/java/org/apache/iotdb/db/mpp/execution/operator/OperatorMemoryTest.java
- server/src/test/java/org/apache/iotdb/db/mpp/execution/operator/schema/SchemaQueryScanOperatorTest.java
The origin implementation for devices and timeseries schema query may cost huge memory peak occupation, since all the results should be retrieved and temporarily cached.
Implement iterating query based on schema reader in DeviceSchemaScanOperator, TimeSeriesSchemaScanOperator and PathsUsingTemplateScanOperator.
> [IOTDB-5347] Implement iterating query for devices and timeseries schema query

- server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
When the user defines the dn_data_dir, this option will not take effect for the load folder
> [IOTDB-5358]dn_data_dir failed to be effectively set when executing load

- docs/UserGuide/Operators-Functions/User-Defined-Function.md
- docs/zh/UserGuide/Operators-Functions/User-Defined-Function.md
- server/src/main/java/org/apache/iotdb/db/mpp/transformation/dag/udf/UDTFExecutor.java
- server/src/main/java/org/apache/iotdb/db/trigger/executor/TriggerExecutor.java
(cherry picked from commit 11c489bc254d47137e028e8135be10ac7ed0f290)
> [To rel/1.0] [IOTDB-4933] More detailed error message for udf/trigger executor and fix typo in udf doc

- schema-engine-rocksdb/src/main/java/org/apache/iotdb/db/metadata/schemaregion/rocksdb/RSchemaRegion.java
- schema-engine-tag/src/main/java/org/apache/iotdb/db/metadata/tagSchemaRegion/TagSchemaRegion.java
- schema-engine-tag/src/main/java/org/apache/iotdb/db/metadata/tagSchemaRegion/utils/ShowTimeSeriesResultUtils.java
- server/src/main/java/org/apache/iotdb/db/localconfignode/LocalConfigNode.java
- server/src/main/java/org/apache/iotdb/db/localconfignode/LocalSchemaPartitionTable.java
- server/src/main/java/org/apache/iotdb/db/metadata/LocalSchemaProcessor.java
- server/src/main/java/org/apache/iotdb/db/metadata/mtree/ConfigMTree.java
- server/src/main/java/org/apache/iotdb/db/metadata/mtree/IMTreeBelowSG.java
- server/src/main/java/org/apache/iotdb/db/metadata/mtree/MTreeBelowSGCachedImpl.java
- server/src/main/java/org/apache/iotdb/db/metadata/mtree/MTreeBelowSGMemoryImpl.java
- server/src/main/java/org/apache/iotdb/db/metadata/mtree/traverser/Traverser.java
- server/src/main/java/org/apache/iotdb/db/metadata/plan/schemaregion/result/ShowTimeSeriesResult.java
- server/src/main/java/org/apache/iotdb/db/metadata/query/info/ITimeSeriesSchemaInfo.java
- server/src/main/java/org/apache/iotdb/db/metadata/schemaregion/ISchemaRegion.java
- server/src/main/java/org/apache/iotdb/db/metadata/schemaregion/SchemaRegionMemoryImpl.java
- server/src/main/java/org/apache/iotdb/db/metadata/schemaregion/SchemaRegionSchemaFileImpl.java
- server/src/main/java/org/apache/iotdb/db/metadata/storagegroup/IStorageGroupSchemaManager.java
- server/src/main/java/org/apache/iotdb/db/metadata/storagegroup/StorageGroupSchemaManager.java
- server/src/test/java/org/apache/iotdb/db/metadata/mtree/ConfigMTreeTest.java
- server/src/test/java/org/apache/iotdb/db/metadata/mtree/MTreeBelowSGTest.java
- server/src/test/java/org/apache/iotdb/db/tools/MLogParserTest.java
- server/src/test/java/org/apache/iotdb/db/utils/SchemaTestUtils.java
see IOTDB-5373
There're some interfaces and methods in SchemaRegion only used by LocalConfigNode and LocalSchemaProcessor, which are all deprecated. The stale code will bring burdens to the future refactor in SchemaRegion (see [IOTDB-4982](https://issues.apache.org/jira/browse/IOTDB-4982)).
1. Delete useless code in LocalConfigNode and ConfigMTree
2. Refactor some implementations of LocalSchemaProcessor methods, which are still used for UT, for example delete and query timeseries.
3. Remove deprecated interfaces and implementations in SchemaRegion
> [IOTDB-5373] Eliminate stale code in LocalConfigNode and LocalSchemaProcessor to simplify interfaces of ISchemaRegion

- schema-engine-rocksdb/src/main/java/org/apache/iotdb/db/metadata/schemaregion/rocksdb/RSchemaRegion.java
- schema-engine-tag/src/main/java/org/apache/iotdb/db/metadata/tagSchemaRegion/TagSchemaRegion.java
- server/src/main/java/org/apache/iotdb/db/metadata/mtree/IMTreeBelowSG.java
- server/src/main/java/org/apache/iotdb/db/metadata/mtree/MTreeBelowSGCachedImpl.java
- server/src/main/java/org/apache/iotdb/db/metadata/mtree/MTreeBelowSGMemoryImpl.java
- server/src/main/java/org/apache/iotdb/db/metadata/plan/schemaregion/impl/read/SchemaRegionReadPlanFactory.java
- server/src/main/java/org/apache/iotdb/db/metadata/plan/schemaregion/impl/read/ShowNodesPlanImpl.java
- server/src/main/java/org/apache/iotdb/db/metadata/plan/schemaregion/read/IShowNodesPlan.java
- server/src/main/java/org/apache/iotdb/db/metadata/plan/schemaregion/result/ShowNodesResult.java
- server/src/main/java/org/apache/iotdb/db/metadata/query/info/INodeSchemaInfo.java
- server/src/main/java/org/apache/iotdb/db/metadata/schemaregion/ISchemaRegion.java
- server/src/main/java/org/apache/iotdb/db/metadata/schemaregion/SchemaRegionMemoryImpl.java
- server/src/main/java/org/apache/iotdb/db/metadata/schemaregion/SchemaRegionSchemaFileImpl.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/schema/NodePathsSchemaScanOperator.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/schema/SchemaQueryScanOperator.java
- server/src/test/java/org/apache/iotdb/db/metadata/mtree/MTreeBelowSGTest.java
- server/src/test/java/org/apache/iotdb/db/metadata/schemaRegion/SchemaRegionBasicTest.java
- server/src/test/java/org/apache/iotdb/db/metadata/schemaRegion/SchemaRegionTestUtil.java
The original implementation of MTree node query, including show child nodes/paths and count nodes xxx level=xxx, is based on taking all results via invoking SchemaRegion Interface. Such implementation is not friendly for resource control and process control, and has higher memory peek than iterating query.
1. Setup IShowNodesPlan and INodeSchemaInfo
2. Implement fake NodeReader based on traverser
3. Refactor the implementation of NodePathsSchemaScanOperator and related UT
> [IOTDB-5378] Implement Iterating Query for MTree Node Query

- server/src/main/java/org/apache/iotdb/db/engine/compaction/CompactionUtils.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/cross/rewrite/task/RewriteCrossSpaceCompactionTask.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/inner/sizetiered/SizeTieredCompactionTask.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/task/CompactionExceptionHandler.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/writer/CrossSpaceCompactionWriter.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/writer/InnerSpaceCompactionWriter.java
- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/TsFileManager.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/CompactionUtilsTest.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/cross/CrossSpaceCompactionExceptionTest.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/cross/RewriteCrossSpaceCompactionRecoverTest.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/cross/RewriteCrossSpaceCompactionTest.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/inner/InnerSpaceCompactionExceptionTest.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/inner/sizetiered/SizeTieredCompactionRecoverTest.java
After compaction, if the target file is empty, its corresponding disk file will be deleted. If an exception or system interruption occurs, there will be problems in restart recovery and set allowCompaction to false.
2022-12-20 09:23:53,086 [pool-12-IoTDB-Recovery-Thread-Pool-1] ERROR o.a.i.d.e.c.t.CompactionRecoverTask:300 - root.iot-0 [Compaction][ExceptionHandler] target file sequence/root.iot/0/0/1670572962795-1051-2-1.inner is not complete, and some source files is lost, do nothing. Set allowCompaction to false
2022-12-20 09:23:53,087 [pool-12-IoTDB-Recovery-Thread-Pool-1] ERROR o.a.i.d.e.c.t.CompactionRecoverTask:133 - root.iot-0 [Compaction][Recover] Failed to recover compaction, set allowCompaction to false
**Reason**
Empty target files will be deleted in …
> [To rel/0.13][IOTDB-5206] Set empty target resource to DELETED and then delete it after compaction 

- server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/task/CrossSpaceCompactionTask.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/task/InnerSpaceCompactionTask.java
See [IOTDB-5288](https://issues.apache.org/jira/browse/IOTDB-5288), [IOTDB-5163](https://issues.apache.org/jira/browse/IOTDB-5163).
This PR moves the edition of metrics to the end of compaction, in case of any exception occurs after the metrics is editted.
> [IOTDB-5288][IOTDB-5163] Fix the file metrics is wrong

- server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
- server/src/test/java/org/apache/iotdb/db/mpp/execution/exchange/SourceHandleTest.java
Before this pr, maxBytesCanReserve of SourceHandle is a constant in SourceHandleTest. When calling sourceHandle.setMaxBytesCanReserve(5 * mockTsBlockSize), if IoTDBDescriptor.getInstance().getConfig().getMaxBytesPerFragmentInstance() is less than 5 * mockTsBlockSize, it will set maxBytesCanReserve of SourceHandle to IoTDBDescriptor.getInstance().getConfig().getMaxBytesPerFragmentInstance() instead of wanted 5 * mockTsBlockSiz, which could lead to UT error.
> Change config in SourceHandleTest according to IoTDBDescriptor

- server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/task/CrossSpaceCompactionTask.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/task/InnerSpaceCompactionTask.java
See [IOTDB-5288](https://issues.apache.org/jira/browse/IOTDB-5288), [IOTDB-5163](https://issues.apache.org/jira/browse/IOTDB-5163).
This PR moves the edition of metrics to the end of compaction, in case of any exception occurs after the metrics is editted.
> [To Rel/1.0][Metrics][IOTDB-5288][IOTDB-5163] Fix the file metrics is wrong

- server/src/main/java/org/apache/iotdb/db/conf/IoTDBStartCheck.java
cherry-pick [pull/8798](https://github.com/apache/iotdb/pull/8798)
> [To rel/1.0][IOTDB-5389] Cause DataNode startup to fail when wal_mode is disabled in IoTConsensus

- server/src/main/java/org/apache/iotdb/db/conf/IoTDBStartCheck.java
see [jira5389](https://issues.apache.org/jira/browse/IOTDB-5389)
> [IOTDB-5389] Cause DataNode startup to fail when wal_mode is disabled in IoTConsensus

- schema-engine-rocksdb/src/main/java/org/apache/iotdb/db/metadata/schemaregion/rocksdb/RSchemaRegion.java
- schema-engine-tag/src/main/java/org/apache/iotdb/db/metadata/tagSchemaRegion/TagSchemaRegion.java
- server/src/main/java/org/apache/iotdb/db/metadata/mtree/IMTreeBelowSG.java
- server/src/main/java/org/apache/iotdb/db/metadata/mtree/MTreeBelowSGCachedImpl.java
- server/src/main/java/org/apache/iotdb/db/metadata/mtree/MTreeBelowSGMemoryImpl.java
- server/src/main/java/org/apache/iotdb/db/metadata/plan/schemaregion/result/ShowTimeSeriesResult.java
- server/src/main/java/org/apache/iotdb/db/metadata/query/info/ITimeSeriesSchemaInfo.java
- server/src/main/java/org/apache/iotdb/db/metadata/schemaregion/ISchemaRegion.java
- server/src/main/java/org/apache/iotdb/db/metadata/schemaregion/SchemaRegionMemoryImpl.java
- server/src/main/java/org/apache/iotdb/db/metadata/schemaregion/SchemaRegionSchemaFileImpl.java
- server/src/main/java/org/apache/iotdb/db/metadata/tag/TagManager.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/schema/source/TimeSeriesSchemaSource.java
- server/src/test/java/org/apache/iotdb/db/metadata/schemaRegion/SchemaRegionAliasAndTagTest.java
- server/src/test/java/org/apache/iotdb/db/metadata/schemaRegion/SchemaRegionBasicTest.java
- server/src/test/java/org/apache/iotdb/db/metadata/schemaRegion/SchemaRegionManagementTest.java
- server/src/test/java/org/apache/iotdb/db/metadata/schemaRegion/SchemaRegionTemplateTest.java
- server/src/test/java/org/apache/iotdb/db/metadata/schemaRegion/SchemaRegionTestUtil.java
- server/src/test/java/org/apache/iotdb/db/mpp/execution/operator/schema/SchemaQueryScanOperatorTest.java
The current SchemaReader uses the result set returned from the original SchemaRegion to generate an iterator; however, the new Traverser supports the iterator pattern, allowing the SchemaReader to be implemented using an iterative Traverser, avoiding the overhead of repeated traversals.
> [IOTDB-5391] Implement SchemaReader using iterative Traverser

- server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
- server/src/main/java/org/apache/iotdb/db/metadata/mtree/store/disk/schemafile/SchemaFile.java
- server/src/main/java/org/apache/iotdb/db/metadata/mtree/store/disk/schemafile/pagemgr/BTreePageManager.java
- server/src/main/java/org/apache/iotdb/db/metadata/mtree/store/disk/schemafile/pagemgr/PageManager.java
This PR bases on the fact that `FileChannel` would be closed if the executing thread was interrupted.
Previously, `SchemaFile`/`PageManager` holds a `FileChannel` variable to read from or write to disk. With high cardinality workload and limited `query_timeout_threshold`, the channel would be interrupted while executing Channel.read(more likely on HDD), which would close the channel and corrupt later access.
After this fix, `SchemaFile` will always check whether the channel is closed and open a new one if so.
Related test figures as below.
For whom may need verify or reproduce, better to test on HDD, lower the query timeout threshold and max heap size.
Before:
After:
Besides, few lines had been fixed for better sync behaviour within SchemaFile write and update methods.
A refactor of …
> [IOTDB-4960]SchemaFile implements separate FileChannel for read/write operation

- node-commons/src/main/java/org/apache/iotdb/commons/schema/tree/AbstractTreeVisitor.java
- server/src/main/java/org/apache/iotdb/db/metadata/mtree/MTreeBelowSGCachedImpl.java
- server/src/main/java/org/apache/iotdb/db/metadata/mtree/MTreeBelowSGMemoryImpl.java
- server/src/main/java/org/apache/iotdb/db/metadata/mtree/traverser/TraverserWithLimitOffsetWrapper.java
- server/src/main/java/org/apache/iotdb/db/metadata/query/reader/ISchemaReader.java
- server/src/main/java/org/apache/iotdb/db/metadata/schemaregion/SchemaRegionMemoryImpl.java
- server/src/main/java/org/apache/iotdb/db/metadata/schemaregion/SchemaRegionSchemaFileImpl.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/schema/CountGroupByLevelScanOperator.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/schema/SchemaCountOperator.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/schema/SchemaQueryScanOperator.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/schema/source/PathsUsingTemplateSource.java
- server/src/test/java/org/apache/iotdb/db/mpp/execution/operator/schema/CountGroupByLevelMergeOperatorTest.java
- server/src/test/java/org/apache/iotdb/db/mpp/execution/operator/schema/SchemaCountOperatorTest.java
- server/src/test/java/org/apache/iotdb/db/mpp/execution/operator/schema/SchemaOperatorTestUtil.java
- server/src/test/java/org/apache/iotdb/db/mpp/execution/operator/schema/SchemaQueryScanOperatorTest.java
* Handle failure in schema query if there is exception occurs during the iteration.
* Add UT to mock exception and check whether Operator throws runtime exception correctlly.
> [IOTDB-5398] Handle failure in schema query if there is exception occurs during the iteration

- server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/utils/reader/PointPriorityReader.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/FastAlignedCrossCompactionTest.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/FastNonAlignedCrossCompactionTest.java
In the fast compaction, the overlapping pages will be put into the pointPriorityReader, and the points are spit out in order. Every time a point is spit out, an element must be popped out from the priority queue, and then added into the queue. When the points do not overlap, it will cause a lot of invalid heap sort, which will reduce the compaction rate. For example: there are two pages, one is a sparse page with a range of 100 to 500, which has only  two points (100 and 500). The other is a  dense page with a range of 0 to 400. the data of 0 to 99 and 101 to 400 can be spit out directly, instead of adding into the queue and popping them out every time.
> [IOTDB-5392] accelerate pointPriorityReader in fast compaction

- server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/utils/reader/PointPriorityReader.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/FastAlignedCrossCompactionTest.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/FastNonAlignedCrossCompactionTest.java
In the fast compaction, the overlapping pages will be put into the pointPriorityReader, and the points are spit out in order. Every time a point is spit out, an element must be popped out from the priority queue, and then added into the queue. When the points do not overlap, it will cause a lot of invalid heap sort, which will reduce the compaction rate. For example: there are two pages, one is a sparse page with a range of 100 to 500, which has only two points (100 and 500). The other is a dense page with a range of 0 to 400. the data of 0 to 99 and 101 to 400 can be spit out directly, instead of adding into the queue and popping them out every time.
> [To rel/1.0][IOTDB-5392] accelerate pointPriorityReader in fast compaction

- server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/source/AbstractSeriesAggregationScanOperator.java
- server/src/test/java/org/apache/iotdb/db/mpp/execution/operator/OperatorMemoryTest.java
Reduce the estimated size of memory retained after calling next.
> [IOTDB-5401] Reduce the estimated size of memory retained after calling next in SeriesAggregationScanOperator

- server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/source/AbstractSeriesAggregationScanOperator.java
- server/src/test/java/org/apache/iotdb/db/mpp/execution/operator/OperatorMemoryTest.java
(cherry picked from commit 3c01a934376eacf655c23508ae85f7eee926772e)
> [To rel/1.0] [IOTDB-5401] Reduce the estimated size of memory retained after calling next in SeriesAggregationScanOperator

- docs/UserGuide/API/Programming-MQTT.md
- docs/zh/UserGuide/API/Programming-MQTT.md
- node-commons/src/assembly/resources/conf/iotdb-common.properties
- server/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java
see https://issues.apache.org/jira/browse/IOTDB-5390
Set the default mqtt host to be the same as dn_rpc_address, so the mqtt client on other devices can connect to iotdb without setting the mqtt_host config.
> [IOTDB-5390] Keep mqtt_host same with rpc_address

- docs/UserGuide/API/Programming-MQTT.md
- docs/zh/UserGuide/API/Programming-MQTT.md
- node-commons/src/assembly/resources/conf/iotdb-common.properties
- server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
- server/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java
see https://issues.apache.org/jira/browse/IOTDB-5390
Set the default mqtt host to be the same as dn_rpc_address, so the mqtt client on other devices can connect to iotdb without setting the mqtt_host config.
> [To rel/1.0][IOTDB-5390] Keep mqtt_host being same with rpc_address

- server/src/main/java/org/apache/iotdb/db/metadata/mtree/MTreeBelowSGCachedImpl.java
- server/src/main/java/org/apache/iotdb/db/metadata/mtree/MTreeBelowSGMemoryImpl.java
- server/src/test/java/org/apache/iotdb/db/metadata/schemaRegion/SchemaRegionAliasAndTagTest.java
* Cause by delete alias child incorrectly.
* Fix and add UT.
Reproduce Step:
```
IoTDB> create timeseries root.turbine.d1.s1(temprature) with datatype=FLOAT, encoding=RLE, compression=SNAPPY
IoTDB> create timeseries root.turbine.d1.s2 with datatype=FLOAT, encoding=RLE, compression=SNAPPY
IoTDB> SHOW TIMESERIES root.**
+------------------+----------+------------+--------+--------+-----------+----+----------+--------+------------------+
|        Timeseries|     Alias|    Database|DataType|Encoding|Compression|Tags|Attributes|Deadband|DeadbandParameters|
+------------------+----------+------------+--------+--------+-----------+----+----------+--------+------------------+ …
```
> [IOTDB-5414] Timeseries with alias deleted success but can still be queried by alias

- confignode/src/main/java/org/apache/iotdb/confignode/conf/ConfigNodeConfig.java
- confignode/src/main/java/org/apache/iotdb/confignode/manager/ClusterSchemaManager.java
- confignode/src/test/java/org/apache/iotdb/confignode/manager/ClusterSchemaManagerTest.java
This PR is used to fix a regression issue that the max Region number is not calculated correctly. This issue does not exist in release-1.0 because it is introduced by the commit [358be12](https://github.com/apache/iotdb/commit/358be12ca728bf6ff704a000e8d8f8d36f95b4bf).
So we doesn't need to add more items in `Release Notes`
> Fix a regression issue that the max Region number is not calculated correctly

- consensus/src/main/java/org/apache/iotdb/consensus/iot/IoTConsensusServerImpl.java
see [jira5324](https://issues.apache.org/jira/browse/IOTDB-5324)
> [IOTDB-5324] Fix wal cann't be deleted in destDataNode after region migration when data_replication_factor is 1 in IoTConsensus

- consensus/src/main/java/org/apache/iotdb/consensus/iot/IoTConsensus.java
- consensus/src/main/java/org/apache/iotdb/consensus/iot/IoTConsensusServerImpl.java
- consensus/src/main/java/org/apache/iotdb/consensus/iot/IoTConsensusServerMetrics.java
- consensus/src/main/java/org/apache/iotdb/consensus/iot/logdispatcher/LogDispatcher.java
- consensus/src/main/java/org/apache/iotdb/consensus/iot/service/IoTConsensusRPCServiceProcessor.java
- consensus/src/test/java/org/apache/iotdb/consensus/iot/ReplicateTest.java
cherry-pick [pull/8837](https://github.com/apache/iotdb/pull/8837)
> [To rel/1.0][IOTDB-5400] IoTConsensus loses data when replica number change from 1 to several 

- server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/AnalyzeVisitor.java
Print Help Message when loading empty tsfile
when tsfile is empty
Msg: 701: TsFile E:\IoTDB\data\load\mpp_load\IOTDB-5412\1-0-0-0.tsfile is empty, please check it be flushed to disk correctly.
when tsfile is incomplete.
Msg: 701: TsFile E:\IoTDB\data\load\mpp_load\IOTDB-5412\1-0-0-0.tsfile  is empty or incomplete.
> [IOTDB-5412][To rel/1.0]Print Help Message when loading empty tsfile

- consensus/src/main/java/org/apache/iotdb/consensus/iot/IoTConsensusServerImpl.java
cherry-pick [pull/8836](https://github.com/apache/iotdb/pull/8836)
> [To rel/1.0][IOTDB-5324] Fix wal cann't be deleted in destDataNode after region migration when data_replication_factor is 1 in IoTConsensus 

- server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/AnalyzeVisitor.java
Print Help Message when loading empty tsfile
when tsfile is empty
Msg: 701: TsFile E:\IoTDB\data\load\mpp_load\[IOTDB-5412](https://issues.apache.org/jira/browse/IOTDB-5412)\1-0-0-0.tsfile is empty, please check it be flushed to disk correctly.
when tsfile is incomplete.
Msg: 701: TsFile E:\IoTDB\data\load\mpp_load\[IOTDB-5412](https://issues.apache.org/jira/browse/IOTDB-5412)\1-0-0-0.tsfile is empty or incomplete.
> [IOTDB-5412]Print Help Message when loading empty tsfile

- server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/process/TagAggregationOperator.java
See JIRA: https://issues.apache.org/jira/browse/IOTDB-5417
> [IOTDB-5417] Fix missing hasNext() before next() in TagAggregationOperator

- server/src/main/java/org/apache/iotdb/db/engine/compaction/schedule/CompactionScheduler.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/selector/ICompactionSelector.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/selector/ICrossSpaceSelector.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/selector/impl/CrossCompactionTaskResource.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/selector/impl/CrossSpaceCompactionCandidate.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/selector/impl/RewriteCrossSpaceCompactionSelector.java
- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/TsFileResource.java
- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/timeindex/DeviceTimeIndex.java
- server/src/main/java/org/apache/iotdb/db/exception/MergeException.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/cross/CrossSpaceCompactionWithFastPerformerTest.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/cross/CrossSpaceCompactionWithFastPerformerValidationTest.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/cross/CrossSpaceCompactionWithReadPointPerformerTest.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/cross/CrossSpaceCompactionWithReadPointPerformerValidationTest.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/cross/MergeUpgradeTest.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/cross/RewriteCompactionFileSelectorTest.java
* refine the code of cross selector
* fix the bug that some seq files may be lost when selecting cross compaction task if the seq file using FileTimeIndex
See this issue for details https://issues.apache.org/jira/browse/IOTDB-5266
> [To rel/1.0][IOTDB-5266] Refine the code of cross selector and fix the bug when using FileTImeIndex

- consensus/src/test/java/org/apache/iotdb/consensus/ratis/RatisConsensusTest.java
First election in CI env is causing frequent elections that will interrupt the normal operations of Raft progressing. To make matters worse, together with a recently spotted bug in matchIndex https://github.com/apache/ratis/pull/805, it may cause permanent inconsistency issues.
The erroneous event sequence are as follows,
1. Member 1 becomes the leader.
2. Leader 1 initializes the state, writes the first log (index=0) as an configuration entry.
3. This entry is mistakenly committed and be applied to Leader 1's StateMachine due to incorrect matchIndex.
Before 1 could appendEntries to 2/3, 2 & 3 both timeout and started election.
4. 2‘s requestVote has a higher term and forces Leader 1 down.
5. 2 becomes the new Leader, also writing the first log (index = 0) as an configuration entry. …
> [IOTDB-5429] Disable first election in RatisConsensus UT to avoid inconsistency states

- consensus/src/test/java/org/apache/iotdb/consensus/ratis/RatisConsensusTest.java
cherry pick of https://github.com/apache/iotdb/pull/8896
> [To rel/1.0][IOTDB-5429] Disable first election in RatisConsensus UT to avoid inconsistency states

- pom.xml
Users in China may have trouble to download thrift compile tool due to the github download url. 
This PR change the url to the gitbox one.
> Use gitbox thrift url instead of github to avoid download issue

- pom.xml
Users in China may have trouble to download thrift compile tool due to the github download url. This PR change the url to
the gitbox one.
> [To rel/1.0] Use gitbox thrift url instead of github to avoid download issue

- server/src/main/java/org/apache/iotdb/db/mpp/execution/exchange/MPPDataExchangeManager.java
If closing operators failed, then the FI won't be scheduled again, and downstream FI will never receive finished signal.
Failed closing is caused by concurrently removing of sourceHandles in `MPPDataExchangeManager` which causing NPE.
> [IOTDB-5434] Fix occasional timeout error in CI

- confignode/src/main/java/org/apache/iotdb/confignode/consensus/statemachine/ConfigNodeRegionStateMachine.java
**Test in windows environment:**
before:
after:
> [IOTDB-5435] Add close method for logWriter of ConfigNodeRegionStateMachine

- server/src/main/java/org/apache/iotdb/db/rescon/SystemInfo.java
This bug occurs when there are few insert operations and the timed flush memtable is open. The lastReportedSize is reset by the timed flush operation and needToReportToSystem method always return false, because the memtable flush are caused by the time threshold rather than the memory threshold and the memory cost increase cannot reach storageGroupSizeReportThreshold before next timed flush.
To solve this problem, we @HTHou  decide to delete setLastReportedSize when resetStorageGroupStatus.
> [IOTDB-5426] Cannot trigger flush for sequence file when timed flush enabled

- docs/UserGuide/Monitor-Alert/Apache-IoTDB-DataNode-Dashboard.json
- rewrite-tsfile-tool/src/main/java/org/apache/iotdb/RewriteTsFileTool.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/performer/impl/FastCompactionPerformer.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/performer/impl/ReadChunkCompactionPerformer.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/task/AbstractCompactionTask.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/task/CompactionTaskSummary.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/task/CrossSpaceCompactionTask.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/task/InnerSpaceCompactionTask.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/task/subtask/FastCompactionPerformerSubTask.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/task/subtask/FastCompactionTaskSummary.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/utils/executor/fast/AlignedSeriesCompactionExecutor.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/utils/executor/fast/NonAlignedSeriesCompactionExecutor.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/utils/executor/fast/SeriesCompactionExecutor.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/utils/executor/fast/element/ChunkMetadataElement.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/utils/executor/readchunk/AlignedSeriesCompactionExecutor.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/utils/executor/readchunk/SingleSeriesCompactionExecutor.java
- server/src/main/java/org/apache/iotdb/db/service/metrics/recorder/CompactionMetricsRecorder.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/FastCrossCompactionPerformerTest.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/cross/CrossSpaceCompactionWithFastPerformerValidationTest.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/inner/FastCompactionPerformerAlignedTest.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/inner/FastCompactionPerformerNoAlignedTest.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/inner/InnerSeqCompactionWithFastPerformerTest.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/inner/InnerSeqCompactionWithReadChunkPerformerTest.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/inner/InnerSpaceCompactionExceptionTest.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/inner/InnerUnseqCompactionWithFastPerformerTest.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/inner/sizetiered/SizeTieredCompactionRecoverTest.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/recover/SizeTieredCompactionRecoverTest.java
- tsfile/src/main/java/org/apache/iotdb/tsfile/read/TsFileAlignedSeriesReaderIterator.java
See [IOTDB-5140](https://issues.apache.org/jira/browse/IOTDB-5140).
This PR add serveral metrics for compaction execution, especially for the method that the chunk is processed. There are three types of chunk process method, which are directly-flush, merged, and deserialized into points. Monitoring the method the chunk is compacted can benifit the tuning of compaction.
> [IOTDB-5140][To Rel/1.0] Add metrics for compaction deserializing pages or writing chunks
