integration-test/src/test/java/org/apache/iotdb/db/it/query/IoTDBAliasIT.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/AnalyzeVisitor.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/ExpressionAnalyzer.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/GroupByLevelController.java, server/src/main/java/org/apache/iotdb/db/qp/utils/GroupByLevelController.java
=> [IOTDB-3922] Fix incorrect column name in some scenarios for GroupByLevel

integration-test/src/test/java/org/apache/iotdb/db/it/alignbydevice/IoTDBAlignByDeviceIT.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/distribution/ExchangeNodeAdder.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/process/FilterNode.java
=> [IOTDB-3960] Fix the issue that FilterNode is not considered in ExchangeNodeAddr

docs/UserGuide/Maintenance-Tools/Metric-Tool.md, docs/zh/UserGuide/Maintenance-Tools/Metric-Tool.md, server/src/main/java/org/apache/iotdb/db/service/metrics/enums/Metric.java, server/src/main/java/org/apache/iotdb/db/service/thrift/handler/RPCServiceThriftHandler.java
Add thrift connection metric, now only count the number of RPCs
=> [To rel/0.13][IOTDB-3978] Add thrift connection metric.

session/src/main/java/org/apache/iotdb/session/Session.java
=> Remove the useless code in Session

cli/pom.xml, confignode/pom.xml, cross-tests/pom.xml, flink-iotdb-connector/pom.xml, hadoop/pom.xml, hive-connector/pom.xml, influxdb-protocol/pom.xml, integration/pom.xml, library-udf/pom.xml, node-commons/pom.xml, pom.xml, schema-engine-rocksdb/pom.xml, server/pom.xml, spark-iotdb-connector/pom.xml, tsfile/pom.xml, zeppelin-interpreter/pom.xml
https://issues.apache.org/jira/browse/IOTDB-3993
=> [IOTDB-3993] Adjust pom.xml files' <dependency> <version>

consensus/src/main/java/org/apache/iotdb/consensus/common/request/IndexedConsensusRequest.java, consensus/src/main/java/org/apache/iotdb/consensus/multileader/MultiLeaderServerImpl.java, consensus/src/main/java/org/apache/iotdb/consensus/multileader/logdispatcher/LogDispatcher.java
See: https://issues.apache.org/jira/browse/IOTDB-3990
=> [IOTDB-3990] Remove useless param in IndexedConsensusRequest and add some logs.

confignode/src/main/java/org/apache/iotdb/confignode/manager/ProcedureManager.java, confignode/src/main/java/org/apache/iotdb/confignode/persistence/NodeInfo.java, confignode/src/main/java/org/apache/iotdb/confignode/procedure/env/DataNodeRemoveHandler.java, confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/RegionMigrateProcedure.java, server/src/main/java/org/apache/iotdb/db/service/RegionMigrateService.java
the retry  logic in removePeer() method exist bug, if retry happen the method always return failed status, need to fix.
class: RegionMigrateService.java
=> [IOTDB-3985] Retry removePeer for region bug

docs/UserGuide/Maintenance-Tools/Metric-Tool.md, docs/zh/UserGuide/Maintenance-Tools/Metric-Tool.md, server/src/main/java/org/apache/iotdb/db/engine/compaction/CompactionWorker.java, server/src/main/java/org/apache/iotdb/db/service/metrics/recorder/CompactionMetricsRecorder.java
https://issues.apache.org/jira/projects/IOTDB/issues/IOTDB-3961
=> [IOTDB-3961] fix bug of Tsfile compact

checkstyle.xml, server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/PlanNodeType.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/write/InsertRowNode.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/write/InsertTabletNode.java, server/src/test/java/org/apache/iotdb/db/mpp/plan/plan/node/write/InsertMultiTabletsNodeSerdeTest.java, server/src/test/java/org/apache/iotdb/db/mpp/plan/plan/node/write/InsertRowNodeSerdeTest.java, server/src/test/java/org/apache/iotdb/db/mpp/plan/plan/node/write/InsertRowsNodeSerdeTest.java, server/src/test/java/org/apache/iotdb/db/mpp/plan/plan/node/write/InsertRowsOfOneDeviceNodeSerdeTest.java, server/src/test/java/org/apache/iotdb/db/mpp/plan/plan/node/write/InsertTabletNodeSerdeTest.java
See JIRA: https://issues.apache.org/jira/projects/IOTDB/issues/IOTDB-3999
=> [IOTDB-3999] Avoid using PlanNodeType.ordinal()

confignode/src/main/java/org/apache/iotdb/confignode/manager/load/LoadManager.java
The THeartbeatReq generated in each heartbeat loop is independent for each node after several code iteration, which is against the original design. Therefore, we should unify the THeartbeatReq used in each heartbeat cycle.
=> [IOTDB-3986] Unified ConfigNode heartbeat request

server/src/main/java/org/apache/iotdb/db/engine/compaction/performer/impl/ReadPointCompactionPerformer.java, server/src/main/java/org/apache/iotdb/db/engine/compaction/writer/AbstractCompactionWriter.java, server/src/main/java/org/apache/iotdb/db/engine/compaction/writer/CrossSpaceCompactionWriter.java, server/src/main/java/org/apache/iotdb/db/engine/compaction/writer/InnerSpaceCompactionWriter.java, tsfile/src/main/java/org/apache/iotdb/tsfile/file/metadata/statistics/Statistics.java, tsfile/src/main/java/org/apache/iotdb/tsfile/file/metadata/statistics/TimeStatistics.java, tsfile/src/main/java/org/apache/iotdb/tsfile/read/common/block/TsBlock.java, tsfile/src/main/java/org/apache/iotdb/tsfile/read/common/block/column/BinaryColumn.java, tsfile/src/main/java/org/apache/iotdb/tsfile/read/common/block/column/BooleanColumn.java, tsfile/src/main/java/org/apache/iotdb/tsfile/read/common/block/column/Column.java, tsfile/src/main/java/org/apache/iotdb/tsfile/read/common/block/column/DoubleColumn.java, tsfile/src/main/java/org/apache/iotdb/tsfile/read/common/block/column/FloatColumn.java, tsfile/src/main/java/org/apache/iotdb/tsfile/read/common/block/column/IntColumn.java, tsfile/src/main/java/org/apache/iotdb/tsfile/read/common/block/column/LongColumn.java, tsfile/src/main/java/org/apache/iotdb/tsfile/read/common/block/column/RunLengthEncodedColumn.java, tsfile/src/main/java/org/apache/iotdb/tsfile/read/common/block/column/TimeColumn.java, tsfile/src/main/java/org/apache/iotdb/tsfile/write/chunk/AlignedChunkWriterImpl.java, tsfile/src/main/java/org/apache/iotdb/tsfile/write/chunk/TimeChunkWriter.java, tsfile/src/main/java/org/apache/iotdb/tsfile/write/chunk/ValueChunkWriter.java, tsfile/src/main/java/org/apache/iotdb/tsfile/write/page/TimePageWriter.java, tsfile/src/main/java/org/apache/iotdb/tsfile/write/page/ValuePageWriter.java
see jira: https://issues.apache.org/jira/projects/IOTDB/issues/IOTDB-3884
=> [IOTDB-3971] Improve the process of writing chunks in compaction for aligned series

server/src/main/java/org/apache/iotdb/db/query/expression/unary/FunctionExpression.java
Bug fix: FunctionExpression updateStatisticsForMemoryAssigner.
Take `memoryAssigner.increaseExpressionReference(this);` out of for loop.
<hr>
This PR has:
<hr>
=> [To rel/0.13] Fix bug in FunctionExpression updateStatisticsForMemoryAssigner

library-udf/pom.xml, pom.xml
https://issues.apache.org/jira/projects/IOTDB/issues/IOTDB-4003
=> [IOTDB-4003] del duplicated dependency defination in pom.xml

docs/UserGuide/Maintenance-Tools/Metric-Tool.md, docs/zh/UserGuide/Maintenance-Tools/Metric-Tool.md, server/src/main/java/org/apache/iotdb/db/engine/memtable/AbstractMemTable.java, server/src/main/java/org/apache/iotdb/db/metadata/MManager.java
See more details: https://issues.apache.org/jira/browse/IOTDB-3995
=> [To rel/0.13][IOTDB-3995] Specific the type of quantity metric.

confignode/src/main/java/org/apache/iotdb/confignode/service/thrift/ConfigNodeRPCServiceProcessor.java
=> [IOTDB-4008] fix printRegionRouteMap NullPointerException

grafana-metrics-example/cluster/Apache IoTDB ConfigNode Dashboard v0.14.0.json, grafana-metrics-example/cluster/Apache IoTDB DataNode Dashboard v0.14.0.json
=>  Add the CPU load status, memory status, disk status in DashBoard

antlr/src/main/antlr4/org/apache/iotdb/db/qp/sql/IoTDBSqlParser.g4, confignode/src/main/java/org/apache/iotdb/confignode/consensus/request/auth/AuthorPlan.java, confignode/src/main/java/org/apache/iotdb/confignode/persistence/AuthorInfo.java, confignode/src/main/java/org/apache/iotdb/confignode/service/thrift/ConfigNodeRPCServiceProcessor.java, confignode/src/test/java/org/apache/iotdb/confignode/consensus/request/ConfigPhysicalPlanSerDeTest.java, confignode/src/test/java/org/apache/iotdb/confignode/persistence/AuthorInfoTest.java, confignode/src/test/java/org/apache/iotdb/confignode/service/thrift/ConfigNodeRPCServiceProcessorTest.java, docs/UserGuide/Administration-Management/Administration.md, docs/zh/UserGuide/Administration-Management/Administration.md, node-commons/src/main/java/org/apache/iotdb/commons/utils/BasicStructureSerDeUtil.java, server/src/main/java/org/apache/iotdb/db/auth/ClusterAuthorityFetcher.java, server/src/main/java/org/apache/iotdb/db/localconfignode/LocalConfigNode.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/parser/ASTVisitor.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/statement/sys/AuthorStatement.java, server/src/main/java/org/apache/iotdb/db/qp/executor/PlanExecutor.java, server/src/main/java/org/apache/iotdb/db/qp/logical/sys/AuthorOperator.java, server/src/main/java/org/apache/iotdb/db/qp/physical/sys/AuthorPlan.java, server/src/main/java/org/apache/iotdb/db/qp/sql/IoTDBSqlVisitor.java, server/src/test/java/org/apache/iotdb/db/qp/physical/PhysicalPlanTest.java, thrift-confignode/src/main/thrift/confignode.thrift
demo:
All looks good.
<hr>
This PR has:
<hr>
=> [IOTDB-4007]Support multiple paths in privilege control

confignode/src/main/java/org/apache/iotdb/confignode/manager/NodeManager.java, confignode/src/main/java/org/apache/iotdb/confignode/persistence/NodeInfo.java
=> [IOTDB-3847] Clear up interfaces in NodeManager

server/src/main/java/org/apache/iotdb/db/mpp/plan/execution/config/executor/StandaloneConfigTaskExecutor.java
=> [IOTDB-4032] fix show all ttl display is empty in stand

docs/UserGuide/Reference/Config-Manual.md, docs/zh/UserGuide/Reference/Config-Manual.md, server/src/assembly/resources/conf/iotdb-engine.properties, server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
=> [To rel/0.13][IOTDB-3087] enlarge default value of avg_series_point_number_threhold

confignode/src/main/java/org/apache/iotdb/confignode/consensus/request/ConfigPhysicalPlan.java, confignode/src/main/java/org/apache/iotdb/confignode/manager/ProcedureManager.java, confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/RegionMigrateProcedure.java, server/src/main/java/org/apache/iotdb/db/service/thrift/impl/DataNodeInternalRPCServiceImpl.java
when remove datanode, confignode log has IOException:
java.io.IOException: unknown PyhsicalPlan type: 51
=> [IOTDB-4026] unknown PhysicalPlan type: 51

server/src/assembly/resources/conf/iotdb-datanode.properties, server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java, server/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/Coordinator.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/execution/QueryExecution.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/execution/config/ConfigExecution.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/scheduler/AbstractFragInsStateTracker.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/scheduler/ClusterScheduler.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/scheduler/FixedRateFragInsStateTracker.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/scheduler/SimpleQueryTerminator.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/scheduler/StandaloneScheduler.java, server/src/test/java/org/apache/iotdb/db/mpp/execution/ConfigExecutionTest.java, server/src/test/java/org/apache/iotdb/db/mpp/plan/scheduler/StandaloneSchedulerTest.java
* Clean up useless code and parameters for new standalone server
* Reduce the thread number for new standalone server
=> [IOTDB-4037] reduce thread count for new standalone server

server/src/main/java/org/apache/iotdb/db/mpp/execution/driver/Driver.java, server/src/main/java/org/apache/iotdb/db/mpp/execution/exchange/ISinkHandle.java, server/src/main/java/org/apache/iotdb/db/mpp/execution/exchange/LocalSinkHandle.java, server/src/main/java/org/apache/iotdb/db/mpp/execution/exchange/SinkHandle.java, server/src/main/java/org/apache/iotdb/db/mpp/execution/memory/MemoryPool.java, server/src/test/java/org/apache/iotdb/db/mpp/execution/exchange/LocalSinkHandleTest.java, server/src/test/java/org/apache/iotdb/db/mpp/execution/exchange/SinkHandleTest.java, server/src/test/java/org/apache/iotdb/db/mpp/execution/exchange/StubSinkHandle.java, server/src/test/java/org/apache/iotdb/db/mpp/execution/exchange/Utils.java
More analyzing details can be found in this [feishu doc](https://apache-iotdb.feishu.cn/docx/doxcn03DAhSqM0LgNc7NcUslGvg).
=> [IOTDB-4017] Fix Error happened while calling onAcknowledgeDataBlockEvent

server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/schema/SchemaFetchMergeOperator.java, server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/schema/SchemaFetchScanOperator.java, server/src/test/java/org/apache/iotdb/db/mpp/execution/ConfigExecutionTest.java, tsfile/src/main/java/org/apache/iotdb/tsfile/read/common/block/column/BinaryArrayColumnEncoder.java, tsfile/src/main/java/org/apache/iotdb/tsfile/read/common/block/column/ByteArrayColumnEncoder.java, tsfile/src/main/java/org/apache/iotdb/tsfile/read/common/block/column/Int32ArrayColumnEncoder.java, tsfile/src/main/java/org/apache/iotdb/tsfile/read/common/block/column/Int64ArrayColumnEncoder.java, tsfile/src/test/java/org/apache/iotdb/tsfile/common/block/TsBlockSerdeTest.java
More analyzing details and solution designing can be found in this [feishu doc](https://apache-iotdb.feishu.cn/docx/doxcnkAgA1ur5JxkhmRQPcFpnQh).
=> [IOTDB-4016] Fix Calculating size for same TsBlock is not consistent between SinkHandle and SourceHandle

client-cpp/src/main/Session.cpp, client-cpp/src/test/cpp/sessionIT.cpp
To solve the problem “C++ interface execute SQL query statement and the returned result set records error”
=> [IOTDB-4023]C++ interface execute SQL query statement and the returned result set records error

client-cpp/src/main/Session.cpp, client-cpp/src/test/cpp/sessionIT.cpp
To solve the problem “C++ interface execute SQL query statement and the returned result set records error”.
=> [To rel/0.13] [IOTDB-4023]C++  interface  execute SQL query statement and the returned result set records error

confignode/src/main/java/org/apache/iotdb/confignode/manager/ClusterSchemaManager.java, confignode/src/main/java/org/apache/iotdb/confignode/manager/ConfigManager.java, confignode/src/main/java/org/apache/iotdb/confignode/manager/PartitionManager.java, confignode/src/main/java/org/apache/iotdb/confignode/manager/ProcedureManager.java, confignode/src/main/java/org/apache/iotdb/confignode/persistence/NodeInfo.java, confignode/src/main/java/org/apache/iotdb/confignode/persistence/executor/ConfigPlanExecutor.java, confignode/src/main/java/org/apache/iotdb/confignode/procedure/env/DataNodeRemoveHandler.java, confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/RegionMigrateProcedure.java, confignode/src/main/java/org/apache/iotdb/confignode/service/thrift/ConfigNodeRPCServiceProcessor.java, thrift-confignode/src/main/thrift/confignode.thrift
Ad interface annotation in confignode.thrift file
=> [IOTDB-3845] Add annotations in confignode.thrift

antlr/src/main/antlr4/org/apache/iotdb/db/qp/sql/IoTDBSqlParser.g4, server/src/main/java/org/apache/iotdb/db/mpp/plan/parser/ASTVisitor.java, server/src/main/java/org/apache/iotdb/db/qp/sql/IoTDBSqlVisitor.java, server/src/test/java/org/apache/iotdb/db/qp/PlannerTest.java
https://issues.apache.org/jira/browse/IOTDB-4065
=> [IOTDB-4065] support negative timestamp (before 1970 year.)

server/src/main/java/org/apache/iotdb/db/protocol/rest/handler/PhysicalPlanValidationHandler.java
[IOTDB-3996] REST API nonQuery support CQ
=> [IOTDB-3996] Forbidden CQ in REST query API 

server/src/main/java/org/apache/iotdb/db/protocol/rest/handler/PhysicalPlanValidationHandler.java
[IOTDB-3996] REST API nonQuery support CQ
=> [To rel/0.13] [IOTDB-3996] Forbidden CQ in REST query API

server/src/main/java/org/apache/iotdb/db/sync/pipedata/DeletionPipeData.java, server/src/main/java/org/apache/iotdb/db/sync/pipedata/PipeData.java, server/src/main/java/org/apache/iotdb/db/sync/pipedata/SchemaPipeData.java, server/src/main/java/org/apache/iotdb/db/sync/pipedata/TsFilePipeData.java, server/src/main/java/org/apache/iotdb/db/sync/pipedata/queue/BufferedPipeDataQueue.java, server/src/main/java/org/apache/iotdb/db/sync/transport/server/TransportServiceImpl.java, server/src/test/java/org/apache/iotdb/db/sync/pipedata/PipeDataTest.java
https://issues.apache.org/jira/browse/IOTDB-4046
=> [IOTDB-4046] Enhance PipeData serialize()/deserialize() codes

confignode/src/main/java/org/apache/iotdb/confignode/manager/ConfigManager.java, confignode/src/main/java/org/apache/iotdb/confignode/manager/load/LoadManager.java, confignode/src/main/java/org/apache/iotdb/confignode/manager/load/balancer/RouteBalancer.java, confignode/src/main/java/org/apache/iotdb/confignode/manager/load/balancer/router/LazyGreedyRouter.java, confignode/src/main/java/org/apache/iotdb/confignode/persistence/partition/PartitionInfo.java, confignode/src/main/java/org/apache/iotdb/confignode/persistence/partition/StorageGroupPartitionTable.java, confignode/src/main/java/org/apache/iotdb/confignode/service/thrift/ConfigNodeRPCServiceProcessor.java, docs/UserGuide/Maintenance-Tools/Maintenance-Command.md, docs/zh/UserGuide/Maintenance-Tools/Maintenance-Command.md, node-commons/src/main/java/org/apache/iotdb/commons/cluster/RegionRoleType.java, server/src/main/java/org/apache/iotdb/db/mpp/common/header/HeaderConstant.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/execution/config/metadata/ShowRegionTask.java, thrift-confignode/src/main/thrift/confignode.thrift
add leadership
fix region id duplicated,like nodeid duplicated[https://github.com/apache/iotdb/pull/6909](url)
=> [IOTDB-3966] [IOTDB-4079]Show leadership when show Regions && fix region id duplicated

confignode/src/main/java/org/apache/iotdb/confignode/manager/NodeManager.java, node-commons/src/main/java/org/apache/iotdb/commons/client/ClientPoolFactory.java, node-commons/src/main/java/org/apache/iotdb/commons/concurrent/ThreadName.java, server/src/main/java/org/apache/iotdb/db/client/DataNodeClientPoolFactory.java, thrift-confignode/src/main/thrift/confignode.thrift
1、Add annotations in confignode.thrift for Authorize and Maintenance Tools
2、move threadName to ThreadName.java and remove duplicate created thread names(Cluster_Monitor("ClusterMonitor"))
=> [IOTDB-4052] Add annotations in confignode.thrift and move threadname to ThreadName.java

jdbc/src/main/java/org/apache/iotdb/jdbc/IoTDBDatabaseMetadata.java
The error popover has been fixed
=> [ISSUE-6774] Fix connection error when using DBeaver with JDBC driver

jdbc/src/main/java/org/apache/iotdb/jdbc/IoTDBDatabaseMetadata.java, tsfile/src/main/java/org/apache/iotdb/tsfile/read/query/dataset/QueryDataSet.java
connection error when using DBeaver with JDBC driver
=> [To rel/0.13][ISSUE-6774]connection error when using DBeaver with JDBC driver

confignode/src/main/java/org/apache/iotdb/confignode/service/ConfigNodeCommandLine.java, docs/UserGuide/Cluster/Cluster-Setup.md, docs/UserGuide/Maintenance-Tools/Maintenance-Command.md, docs/zh/UserGuide/Cluster/Cluster-Setup.md, docs/zh/UserGuide/Maintenance-Tools/Maintenance-Command.md
Update IoTDB-Cluster docs, including:
1. Cluster setup doc
2. Maintenance command doc by the way
=> [IOTDB-4113] Update Cluster-Setup UserGuide

confignode/src/main/java/org/apache/iotdb/confignode/manager/load/heartbeat/ConfigNodeHeartbeatCache.java, confignode/src/main/java/org/apache/iotdb/confignode/manager/load/heartbeat/DataNodeHeartbeatCache.java, integration-test/src/main/java/org/apache/iotdb/it/env/AbstractEnv.java
Check Nodes' states by using showCluster, and the test fails when states are not "Running".
=> [IOTDB-3825] Reinforce Cluster IT framework's startup check

server/src/main/java/org/apache/iotdb/db/engine/compaction/cross/CrossSpaceCompactionTask.java, server/src/main/java/org/apache/iotdb/db/engine/compaction/cross/utils/ReadPointCrossCompactionEstimator.java, server/src/main/java/org/apache/iotdb/db/engine/compaction/performer/impl/ReadPointCompactionPerformer.java
https://issues.apache.org/jira/browse/IOTDB-4117
=> [IOTDB-4117] fix compact bug ArithmeticException: / by zero

server/src/main/java/org/apache/iotdb/db/auth/ClusterAuthorityFetcher.java
=> [IOTDB-4123]Authority query will be stuck when confignode is down

client-cpp/src/main/Session.cpp, client-cpp/src/main/Session.h, client-cpp/src/test/cpp/sessionIT.cpp, example/client-cpp-example/src/AlignedTimeseriesSessionExample.cpp, example/client-cpp-example/src/SessionExample.cpp
C++ client optimize the values type in tablet class.
The old values type is:
std::vector<std::vector<std::string>> values;
The new values type is:
std::vector<void*> values;
For eliminating two bytes conversion, so the performance is improved.
[performance test.xlsx](https://github.com/apache/iotdb/files/9198932/performance.test.xlsx)
=> [IOTDB-2669] C++ client optimize the values type in tablet class

client-cpp/src/main/Session.cpp, client-cpp/src/main/Session.h, client-cpp/src/test/cpp/sessionIT.cpp, example/client-cpp-example/src/AlignedTimeseriesSessionExample.cpp, example/client-cpp-example/src/SessionExample.cpp
C++ client optimize the values type in tablet class.
The old values type is:
std::vector<std::vector<std::string>> values;
The new values type is:
std::vector<void*> values;
For eliminating two bytes conversion, so the performance is improved.
[performance test.xlsx](https://github.com/apache/iotdb/files/9198838/performance.test.xlsx)
=> [To rel/0.13] [IOTDB-2669] C++ client optimize the values type in tablet class

confignode/src/assembly/resources/sbin/remove-confignode.bat, docs/UserGuide/Cluster/Cluster-Setup.md, docs/zh/UserGuide/Cluster/Cluster-Setup.md
1. Add remove-confignode.bat
2. update UserGuide
=> [IOTDB-4055] Add remove-confignode.bat

server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/PlanGraphPrinter.java
See JIRA: https://issues.apache.org/jira/browse/IOTDB-4165
=> [IOTDB-4165] PlanGraphPrinter supports TransformNode

cli/pom.xml, cli/src/assembly/cli.xml, cli/src/main/java/org/apache/iotdb/tool/ImportCsv.java, docs/UserGuide/Write-And-Delete-Data/CSV-Tool.md, docs/zh/UserGuide/Write-And-Delete-Data/CSV-Tool.md, server/src/main/java/org/apache/iotdb/db/qp/utils/DatetimeUtils.java, server/src/test/java/org/apache/iotdb/db/qp/utils/DatetimeQueryDataSetUtilsTest.java
Add a option "tp" to specify timestamp precision (ms/ns/us)
=> [IOTDB-4156] import csv has error time after timestamp_precision set ns

server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/AnalyzeVisitor.java
fix [IOTDB-jira 7015]
I've submitted a PR for ISSUE-7015.
fix Checkstyle issues: Local variable name 'RawPathToGroupedPathMapInHaving' 
<hr>
This PR has:
<hr>
=> [ISSUE-7015] Rename variable 'RawPathToGroupedPathMapInHaving'

example/pulsar/pom.xml
=> Fix pulsar example compile error

server/src/main/java/org/apache/iotdb/db/engine/storagegroup/DataRegion.java, server/src/main/java/org/apache/iotdb/db/metadata/schemaregion/SchemaRegionUtils.java, server/src/main/java/org/apache/iotdb/db/wal/recover/WALRecoverManager.java
=> [IOTDB-4210] Fix deadlock during WALNode recover if there's another one already running

docs/UserGuide/Operate-Metadata/Node.md, docs/UserGuide/Operate-Metadata/Storage-Group.md, docs/UserGuide/Operate-Metadata/Timeseries.md, docs/zh/UserGuide/Operate-Metadata/Node.md, docs/zh/UserGuide/Operate-Metadata/Storage-Group.md, docs/zh/UserGuide/Operate-Metadata/Timeseries.md
update document on website, because some samples has mistakes
see: https://issues.apache.org/jira/browse/IOTDB-4214
=> [IOTDB-4214] Document has some mistakes on iotdb web site

example/session/src/main/java/org/apache/iotdb/AlignedTimeseriesSessionExample.java, server/src/main/java/org/apache/iotdb/db/service/thrift/impl/ClientRPCServiceImpl.java, server/src/main/java/org/apache/iotdb/db/service/thrift/impl/TSServiceImpl.java
=> [IOTDB-4216] Fix execute create aligned timeseries but a non-aligned timeseries created

example/session/src/main/java/org/apache/iotdb/AlignedTimeseriesSessionExample.java, server/src/main/java/org/apache/iotdb/db/service/thrift/impl/TSServiceImpl.java
=> [To rel/0.13][IOTDB-4216] Fix execute create aligned timeseries but a non-aligned timeseries created

jdbc/src/main/java/org/apache/iotdb/jdbc/IoTDBDatabaseMetadata.java
I've submitted a PR for issue ISSUE-7001
use String#replace replace String#replaceAll
<hr>
This PR has:
<hr>
=> [ISSUE-7001] "String#replace" should be preferred to "String#replaceAll"

integration/src/test/java/org/apache/iotdb/db/integration/aggregation/IoTDBAggregationScanOrderIT.java, server/src/main/java/org/apache/iotdb/db/query/executor/AggregationExecutor.java
=> [To rel/0.13] [IOTDB-4215] Fix incorrect aggregate query results due to wrong unseq file traversal order

server/src/main/java/org/apache/iotdb/db/protocol/rest/handler/PhysicalPlanHandler.java, server/src/main/java/org/apache/iotdb/db/protocol/rest/impl/RestApiServiceImpl.java
REST API nonQuery add select into
=> [To rel/0.13] REST API nonQuery add select into

integration-test/src/test/java/org/apache/iotdb/db/it/aggregation/IoTDBAggregationScanOrderIT.java, server/src/main/java/org/apache/iotdb/db/query/executor/AggregationExecutor.java
=> [IOTDB-4215] Fix incorrect aggregate query results due to wrong unseq file traversal order

integration/src/test/java/org/apache/iotdb/db/integration/sync/IoTDBSyncReceiverIT.java, integration/src/test/java/org/apache/iotdb/db/integration/sync/IoTDBSyncSenderIT.java, integration/src/test/java/org/apache/iotdb/db/integration/sync/MockSyncClient.java, server/src/main/java/org/apache/iotdb/db/sync/sender/pipe/Pipe.java, server/src/main/java/org/apache/iotdb/db/sync/transport/client/ISyncClient.java, server/src/main/java/org/apache/iotdb/db/sync/transport/client/IoTDBSinkSyncClient.java, server/src/main/java/org/apache/iotdb/db/sync/transport/client/IoTDBSyncClient.java, server/src/main/java/org/apache/iotdb/db/sync/transport/client/SenderManager.java, server/src/main/java/org/apache/iotdb/db/sync/transport/client/SyncClientFactory.java, server/src/test/java/org/apache/iotdb/db/sync/transport/SyncTransportTest.java
Rename TransportClient to SyncClient
=> [IOTDB-4229] Rename TransportClient to SyncClient

tsfile/src/main/java/org/apache/iotdb/tsfile/read/TsFileSequenceReader.java
=> [IOTDB-4196] Fix concurrent bug in TsFileSequenceReader

tsfile/src/main/java/org/apache/iotdb/tsfile/read/TsFileSequenceReader.java
=> [To rel/0.13] [IOTDB-4196] Fix concurrent bug in TsFileSequenceReader

client-cpp/pom.xml, compile-tools/pom.xml, distribution/pom.xml, example/client-cpp-example/pom.xml, example/trigger/pom.xml, example/udf/pom.xml, grafana-connector/pom.xml, integration/pom.xml, jdbc/pom.xml, pom.xml, server/src/main/java/org/apache/iotdb/db/tools/validate/TsFileValidationTool.java, server/src/test/java/org/apache/iotdb/db/engine/compaction/cross/CrossSpaceCompactionValidationTest.java
Support validating TsFiles not only in one time partition, but also between time partitions.
=> [To rel/0.13][IOTDB-4201]Support TsFiles Validation between time partitions

cli/src/assembly/resources/sbin/start-cli.sh, server/src/assembly/resources/conf/logback.xml, server/src/assembly/resources/sbin/start-server.sh
this pr add checking iotdb.in.sh into start-server.sh,
and use iotdb_log_dir system variable to replace iotdb_home/logs
=> [To rel/0.13][IOTDB-4230]add checking iotdb.in.sh file, add iotdb_log_dir system variable

server/src/main/java/org/apache/iotdb/db/mpp/plan/parser/StatementGenerator.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/statement/crud/InsertBaseStatement.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/statement/crud/InsertMultiTabletsStatement.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/statement/crud/InsertRowStatement.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/statement/crud/InsertRowsOfOneDeviceStatement.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/statement/crud/InsertRowsStatement.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/statement/crud/InsertTabletStatement.java, server/src/main/java/org/apache/iotdb/db/service/thrift/impl/ClientRPCServiceImpl.java
Return directly when insert statements are empty.
=> [IOTDB-4181] Check empty insert statement and return directly

example/ext-pipe-plugin-example/pom.xml, example/ext-pipe-plugin-example/src/main/java/org/apache/iotdb/extpipe/ExtPipeSinkWriterImpl.java, example/ext-pipe-plugin-example/src/main/resources/META-INF/services/org.apache.iotdb.pipe.external.api.IExternalPipeSinkWriterFactory, external-pipe-api/src/main/java/org/apache/iotdb/pipe/external/api/IExternalPipeSinkWriter.java, node-commons/src/main/java/org/apache/iotdb/commons/path/PartialPath.java, node-commons/src/test/java/org/apache/iotdb/commons/path/PartialPathTest.java, server/src/main/java/org/apache/iotdb/db/engine/storagegroup/DataRegion.java, server/src/main/java/org/apache/iotdb/db/engine/storagegroup/TsFileProcessor.java, server/src/main/java/org/apache/iotdb/db/metadata/schemaregion/SchemaRegionMemoryImpl.java, server/src/main/java/org/apache/iotdb/db/metadata/schemaregion/SchemaRegionSchemaFileImpl.java, server/src/main/java/org/apache/iotdb/db/sync/datasource/AbstractOpBlock.java, server/src/main/java/org/apache/iotdb/db/sync/datasource/DeletionOpBlock.java, server/src/main/java/org/apache/iotdb/db/sync/datasource/PipeOpManager.java, server/src/main/java/org/apache/iotdb/db/sync/datasource/PipeOpSgManager.java, server/src/main/java/org/apache/iotdb/db/sync/datasource/TsFileOpBlock.java, server/src/main/java/org/apache/iotdb/db/sync/externalpipe/ExtPipePlugin.java, server/src/main/java/org/apache/iotdb/db/sync/externalpipe/ExtPipePluginManager.java, server/src/main/java/org/apache/iotdb/db/sync/externalpipe/operation/DeleteOperation.java, server/src/main/java/org/apache/iotdb/db/sync/externalpipe/operation/InsertOperation.java, server/src/main/java/org/apache/iotdb/db/sync/externalpipe/operation/Operation.java, server/src/main/java/org/apache/iotdb/db/sync/pipedata/DeletionPipeData.java, server/src/main/java/org/apache/iotdb/db/sync/sender/manager/TsFileSyncManager.java, server/src/main/java/org/apache/iotdb/db/sync/sender/pipe/TsFilePipe.java, server/src/test/java/org/apache/iotdb/db/sync/datasource/DeletionOpBlockTest.java, server/src/test/java/org/apache/iotdb/db/sync/datasource/PipeOpManagerTest.java
https://issues.apache.org/jira/browse/IOTDB-3465
=> [IOTDB-3465] ext pipe support DeletionPipeData

client-cpp/src/main/Session.cpp, client-cpp/src/main/Session.h, example/client-cpp-example/src/AlignedTimeseriesSessionExample.cpp, example/client-cpp-example/src/SessionExample.cpp
https://issues.apache.org/jira/projects/IOTDB/issues/IOTDB-4193
=> [IOTDB-4193] fix bug/risk/inefficient codes in client-cpp

integration/src/test/java/org/apache/iotdb/db/integration/IoTDBCheckConfigIT.java, server/src/assembly/resources/conf/iotdb-datanode.properties, server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
https://apache-iotdb.feishu.cn/docx/doxcn7T8hpJaWiNLyPuBzd4p5Pg
=> Turn off time partition on data node

server/src/main/java/org/apache/iotdb/db/qp/logical/crud/AggregationQueryOperator.java, server/src/main/java/org/apache/iotdb/db/qp/logical/crud/GroupByFillQueryOperator.java, server/src/main/java/org/apache/iotdb/db/qp/logical/crud/GroupByQueryOperator.java, server/src/main/java/org/apache/iotdb/db/qp/physical/crud/AggregationPlan.java
=> [IOTDB-4141] Add semantic checks for aggregate query in old standalone

cluster/src/main/java/org/apache/iotdb/cluster/utils/StatusUtils.java, cluster/src/test/java/org/apache/iotdb/cluster/integration/SingleNodeTest.java, docs/UserGuide/API/Status-Codes.md, docs/UserGuide/Administration-Management/Administration.md, docs/zh/UserGuide/Administration-Management/Administration.md, integration/src/test/java/org/apache/iotdb/db/integration/IoTDBAuthorizationIT.java, integration/src/test/java/org/apache/iotdb/session/template/TemplateUT.java, jdbc/README.md, server/src/main/java/org/apache/iotdb/db/auth/AuthorityChecker.java, server/src/main/java/org/apache/iotdb/db/service/basic/ServiceProvider.java, server/src/main/java/org/apache/iotdb/db/service/thrift/impl/TSServiceImpl.java
=> [To rel/0.13] [IOTDB-2782] When users are not granted READ_TIMESERIES or INSERT_TIMESERIES, the verification prompt needs to be unified

integration-test/src/test/java/org/apache/iotdb/db/it/schema/IoTDBSchemaTemplateIT.java, schema-engine-rocksdb/src/main/java/org/apache/iotdb/db/metadata/schemaregion/rocksdb/RSchemaRegion.java, server/src/main/java/org/apache/iotdb/db/metadata/mtree/MTreeBelowSGMemoryImpl.java, server/src/main/java/org/apache/iotdb/db/metadata/schemaregion/ISchemaRegion.java, server/src/main/java/org/apache/iotdb/db/metadata/schemaregion/SchemaRegionMemoryImpl.java, server/src/main/java/org/apache/iotdb/db/metadata/schemaregion/SchemaRegionSchemaFileImpl.java, server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/schema/TimeSeriesCountOperator.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/AnalyzeVisitor.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/execution/config/executor/ClusterConfigTaskExecutor.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/execution/config/executor/StandaloneConfigTaskExecutor.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/LogicalPlanBuilder.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/LogicalPlanVisitor.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/OperatorTreeGenerator.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/metedata/read/TimeSeriesCountNode.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/statement/metadata/CountStatement.java, server/src/test/java/org/apache/iotdb/db/mpp/execution/operator/OperatorMemoryTest.java, server/src/test/java/org/apache/iotdb/db/mpp/execution/operator/schema/CountMergeOperatorTest.java, server/src/test/java/org/apache/iotdb/db/mpp/execution/operator/schema/SchemaCountOperatorTest.java
The ```count timeseries``` with schema template feature hasn't been adapt to new cluster. This pr implements it.
=> [IOTDB-4272]Fix count timeseries with template

integration-test/src/test/java/org/apache/iotdb/db/it/IoTDBAuthIT.java
Add Auth IT Test when grant user role.
=> [IOTDB-2769] Add Auth IT Test when grant user role.

confignode/src/main/java/org/apache/iotdb/confignode/manager/NodeManager.java, docs/UserGuide/Maintenance-Tools/Maintenance-Command.md, docs/zh/UserGuide/Maintenance-Tools/Maintenance-Command.md, server/src/main/java/org/apache/iotdb/db/mpp/common/header/ColumnHeaderConstant.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/execution/config/metadata/ShowConfigNodesTask.java, thrift-confignode/src/main/thrift/confignode.thrift
=> [IOTDB-4295] add confignode leader for show confignodes

node-commons/src/main/java/org/apache/iotdb/commons/trigger/TriggerInformation.java, node-commons/src/main/java/org/apache/iotdb/commons/trigger/TriggerTable.java, thrift-confignode/src/main/thrift/confignode.thrift
Signed-off-by: Weihao Li <18110526956@163.com>
=> [IOTDB-4304]Add TriggerTable and TriggerInformation

docs/UserGuide/Process-Data/Triggers.md, docs/zh/UserGuide/Process-Data/Triggers.md, example/trigger/src/main/java/org/apache/iotdb/trigger/AlertingExample.java, example/trigger/src/main/java/org/apache/iotdb/trigger/TriggerExample.java, integration/src/main/java/org/apache/iotdb/db/engine/trigger/example/Accumulator.java, integration/src/main/java/org/apache/iotdb/db/engine/trigger/example/Counter.java, node-commons/pom.xml, pom.xml, server/src/main/java/org/apache/iotdb/db/engine/trigger/api/Trigger.java, server/src/main/java/org/apache/iotdb/db/engine/trigger/builtin/ForwardTrigger.java, server/src/main/java/org/apache/iotdb/db/engine/trigger/executor/TriggerExecutor.java, server/src/test/java/org/apache/iotdb/db/metadata/idtable/trigger_example/Counter.java, trigger-api/pom.xml, trigger-api/src/main/java/org/apache/iotdb/trigger/api/Trigger.java, trigger-api/src/main/java/org/apache/iotdb/trigger/api/TriggerAttributes.java
Migrate Trigger-API into a seperate module.
=> [IOTDB-4321] Migrate Trigger-API into a seperate module

confignode/src/main/java/org/apache/iotdb/confignode/consensus/request/write/CreateRegionGroupsPlan.java, confignode/src/main/java/org/apache/iotdb/confignode/consensus/request/write/DeleteRegionGroupsPlan.java, confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/CreateRegionGroupsProcedure.java, confignode/src/main/java/org/apache/iotdb/confignode/procedure/state/RemoveConfigNodeState.java, confignode/src/main/java/org/apache/iotdb/confignode/procedure/store/ProcedureFactory.java, confignode/src/test/java/org/apache/iotdb/confignode/procedure/impl/CreateRegionGroupsProcedureTest.java
see details in the jira: 
https://issues.apache.org/jira/browse/IOTDB-4303?page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel&focusedCommentId=17599234#comment-17599234,
https://issues.apache.org/jira/browse/IOTDB-4301?page=com.atlassian.jira.plugin.system.issuetabpanels%3Aall-tabpanel
=> [IOTDB-4301] [IOTDB-4303] fix bug in create regions group procedure

integration-test/src/test/java/org/apache/iotdb/db/it/IoTDBFilterIT.java, integration-test/src/test/java/org/apache/iotdb/db/it/IoTDBNestedQueryIT.java, server/src/main/java/org/apache/iotdb/db/mpp/transformation/dag/column/binary/CompareBinaryColumnTransformer.java
Comparation between NaN and number should not be kept in filter.
=> [IOTDB-4325] NaN and Infinity will be regard as positive Infinity in where clause in 0.14.0

metrics/interface/src/main/java/org/apache/iotdb/metrics/utils/IoTDBMetricsUtils.java
See more details: https://issues.apache.org/jira/browse/IOTDB-4342
=> [To rel/0.13][IOTDB-4342] Fix iotdb reporter in metric module.

server/src/main/java/org/apache/iotdb/db/protocol/mqtt/MPPPublishHandler.java, server/src/main/java/org/apache/iotdb/db/protocol/mqtt/PublishHandler.java, server/src/test/java/org/apache/iotdb/db/protocol/mqtt/PublishHandlerTest.java
1. Fix PublishHandler: add clientId -> sessionId map.
2. Fix MPPPublishHandler: add clientId -> sessionId map.
See: https://issues.apache.org/jira/browse/IOTDB-4343
=> [IOTDB-4343] Fix session manager in MQTT module.

server/src/main/java/org/apache/iotdb/db/protocol/mqtt/PublishHandler.java, server/src/test/java/org/apache/iotdb/db/protocol/mqtt/PublishHandlerTest.java
1. Fix PublishHandler: add clientId -> sessionId map.
See: https://issues.apache.org/jira/browse/IOTDB-4343
=> [To rel/0.13][IOTDB-4343] Fix session manager in MQTT module. 

server/src/assembly/resources/sbin/start-server.bat
https://issues.apache.org/jira/browse/IOTDB-4357
=> [To rel/0.13][IOTDB-4357]fix start in windows, IOTDB_LOG_DIR_IS_UNDEFINED

consensus/src/main/java/org/apache/iotdb/consensus/multileader/logdispatcher/LogDispatcher.java
See: https://issues.apache.org/jira/browse/IOTDB-4372
=> [IOTDB-4372] adapt PlanNodeIterator.

site/src/main/.vuepress/config.js
Needed to be merged after #7292 merged.
=> [IOTDB-4345] Update Metric Related Doc config js.

openapi/src/main/openapi3/iotdb-rest.yaml
Fix warning messages by openapi specification.
https://swagger.io/specification/
=> fix restapi compile warning messages

server/src/main/java/org/apache/iotdb/db/service/metrics/predefined/FileMetrics.java, server/src/main/java/org/apache/iotdb/db/service/metrics/predefined/SystemMetrics.java
See: https://issues.apache.org/jira/browse/IOTDB-4373
=> [IOTDB-4373] Fix statistic of disk in metric.

server/src/main/java/org/apache/iotdb/db/mpp/execution/exchange/LocalSinkHandle.java, server/src/main/java/org/apache/iotdb/db/mpp/execution/exchange/LocalSourceHandle.java, server/src/main/java/org/apache/iotdb/db/mpp/execution/exchange/MPPDataExchangeManager.java, server/src/main/java/org/apache/iotdb/db/mpp/execution/exchange/SharedTsBlockQueue.java, server/src/main/java/org/apache/iotdb/db/mpp/execution/exchange/SinkHandle.java, server/src/main/java/org/apache/iotdb/db/mpp/execution/exchange/SourceHandle.java, server/src/main/java/org/apache/iotdb/db/mpp/execution/fragment/FragmentInstanceExecution.java, server/src/main/java/org/apache/iotdb/db/mpp/execution/fragment/FragmentInstanceManager.java, server/src/main/java/org/apache/iotdb/db/mpp/execution/fragment/FragmentInstanceStateMachine.java, server/src/main/java/org/apache/iotdb/db/mpp/execution/schedule/AbstractDriverThread.java, server/src/main/java/org/apache/iotdb/db/mpp/execution/schedule/DriverScheduler.java, server/src/main/java/org/apache/iotdb/db/mpp/execution/schedule/DriverTaskThread.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/Coordinator.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/AnalyzeVisitor.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/ClusterSchemaFetcher.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/execution/QueryExecution.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/LocalExecutionPlanner.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/scheduler/FixedRateFragInsStateTracker.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/scheduler/FragmentInstanceDispatcherImpl.java, server/src/main/java/org/apache/iotdb/db/protocol/mpprest/impl/GrafanaApiServiceImpl.java, server/src/main/java/org/apache/iotdb/db/protocol/mpprest/impl/RestApiServiceImpl.java, server/src/main/java/org/apache/iotdb/db/service/thrift/impl/ClientRPCServiceImpl.java, server/src/main/java/org/apache/iotdb/db/service/thrift/impl/DataNodeInternalRPCServiceImpl.java, server/src/main/java/org/apache/iotdb/db/utils/SetThreadName.java
Log will be like 原始线程名$QueryID名: [event]
=> Add log event and change Thread Name Format 

server/src/assembly/resources/conf/iotdb-datanode.properties, server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java, server/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java, server/src/main/java/org/apache/iotdb/db/consensus/statemachine/DataRegionStateMachine.java
See: https://issues.apache.org/jira/browse/IOTDB-4412
=> [IOTDB-4412][MultiLeader] add `cacheWindowTimeInMs` into config.

server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/StandaloneSchemaFetcher.java
this bug may cause an OutOfBoundException in SchemaFetcher
=> [IOTDB-4408] fix OutOfBoundException in SchemaFetcher

library-udf/pom.xml
=> Fix mvn complie warning message

integration/src/test/java/org/apache/iotdb/session/IoTDBSessionSimpleIT.java, server/src/main/java/org/apache/iotdb/db/engine/memtable/AbstractMemTable.java, server/src/main/java/org/apache/iotdb/db/engine/memtable/WritableMemChunkGroup.java
=> [IOTDB-4428] Fix partial insert by session NPE

confignode/src/main/java/org/apache/iotdb/confignode/consensus/statemachine/PartitionRegionStateMachine.java, confignode/src/main/java/org/apache/iotdb/confignode/manager/ProcedureManager.java, confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/DeleteStorageGroupProcedure.java, confignode/src/test/java/org/apache/iotdb/confignode/consensus/request/ConfigPhysicalPlanSerDeTest.java, confignode/src/test/java/org/apache/iotdb/confignode/procedure/impl/CreateRegionGroupsProcedureTest.java, confignode/src/test/java/org/apache/iotdb/confignode/procedure/impl/DeleteStorageGroupProcedureTest.java
See the error details in https://issues.apache.org/jira/browse/IOTDB-4413
=> Catch exception in the write method of PartitionRegionStateMachine

server/src/main/java/org/apache/iotdb/db/utils/ErrorHandlingUtils.java
Do not print stack when meeting sql error
=> [IOTDB-2519] Do not print stack when meeting sql error

confignode/src/test/resources/confignode1conf/iotdb-confignode.properties, confignode/src/test/resources/confignode2conf/iotdb-confignode.properties, confignode/src/test/resources/confignode3conf/iotdb-confignode.properties, server/src/test/resources/datanode1conf/iotdb-rest.properties, server/src/test/resources/datanode2conf/iotdb-rest.properties, server/src/test/resources/datanode3conf/iotdb-rest.properties
See: https://issues.apache.org/jira/browse/IOTDB-4426
=> [IOTDB-4426] Fix default config in test folder of 3C3D cluster

server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/scheduler/ClusterScheduler.java
1. only read operation is allowed to retry
2. Change the default timeout from MAX_VALUE to 1 minute
=> Fix two issues in retry and multileader

consensus/src/main/java/org/apache/iotdb/consensus/ratis/SnapshotStorage.java
When we let statemachine decide which files are included in a snapshot, statemachine won't include ratis meta files. We should check it manually and guarantee the metafile be added last.
=> [IOTDB-3862] Fix: Guarantee to add Ratis MetaFile

server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/load/LoadSingleTsFileNode.java
problem:
calculate plan node size error, cause missing of entire chunk data size.
solution:
add data size of entire chunk.
=> [IOTDB-4469]add data size while loading enire chunk

server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/write/InsertMultiTabletsNode.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/write/InsertNode.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/write/InsertRowNode.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/write/InsertRowsNode.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/write/InsertRowsOfOneDeviceNode.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/write/InsertTabletNode.java, server/src/main/java/org/apache/iotdb/db/utils/CommonUtils.java
https://issues.apache.org/jira/browse/IOTDB-4477
Support
cast INT32 -> INT64, FLOAT, DOUBLE
cast INT64 -> DOUBLE
cast FLOAT -> DOUBLE
=> [IOTDB-4477] Support datatype cast while inserting with schema mismatch

example/ext-pipe-plugin-example/pom.xml, example/ext-pipe-plugin-example/src/main/java/org/apache/iotdb/extpipe/ExtPipeSinkWriterFactory.java, example/ext-pipe-plugin-example/src/main/java/org/apache/iotdb/extpipe/ExtPipeSinkWriterImpl.java, example/pom.xml, external-pipe-api/src/main/java/org/apache/iotdb/pipe/external/api/IExternalPipeSinkWriter.java, server/src/main/java/org/apache/iotdb/db/sync/datasource/TsFileOpBlock.java, server/src/main/java/org/apache/iotdb/db/sync/externalpipe/ExtPipePlugin.java, server/src/test/java/org/apache/iotdb/db/sync/datasource/PipeOpManagerTest.java, server/src/test/java/org/apache/iotdb/db/sync/datasource/TsFileOpBlockTest.java
https://issues.apache.org/jira/browse/IOTDB-3586
=> [IOTDB-3586] ext pipe FWK support Time-Aligned data

server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/cache/PartitionCache.java
See: https://issues.apache.org/jira/browse/IOTDB-4495
=> [IOTDB-4495][PartitionCache] Add auto create schema judgement.

consensus/src/main/java/org/apache/iotdb/consensus/multileader/MultiLeaderServerImpl.java
See https://issues.apache.org/jira/browse/IOTDB-4510.
=> [IOTDB-4510] add some logs and potential memory leak in ml.

server/src/main/java/org/apache/iotdb/db/service/DataNodeServerCommandLine.java
=> Make comments and logs tidy

docs/UserGuide/Cluster/Cluster-Setup.md, docs/zh/UserGuide/Cluster/Cluster-Setup.md
=> [DOC] Change the port name of show cluster to InternalPort

node-commons/src/main/java/org/apache/iotdb/commons/partition/DataPartition.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/cache/PartitionCache.java
See: https://issues.apache.org/jira/browse/IOTDB-4495
=> [IOTDB-4495] Fix NPE when enable_auto_create_schema is false

integration-test/src/test/java/org/apache/iotdb/db/it/schema/IoTDBSchemaTemplateIT.java, server/src/main/java/org/apache/iotdb/db/metadata/mtree/MTreeBelowSGMemoryImpl.java, server/src/main/java/org/apache/iotdb/db/metadata/mtree/traverser/Traverser.java, server/src/main/java/org/apache/iotdb/db/metadata/schemaregion/SchemaRegionMemoryImpl.java
When executing deleting timeseries, mtree traversal should skip template.
=> [IOTDB-4511] Fix NPE while deleting timeseries  with template

consensus/src/main/java/org/apache/iotdb/consensus/multileader/MultiLeaderConsensus.java
1. Make the `transferLeader()` api available in MultiLeaderConsensus
2. Add the logic for api `takeSnapshot` in MultiLeaderConsensus
=> Make the transferLeader api available for MultiLeaderConsensus

.github/workflows/main-unix.yml, integration-test/src/main/java/org/apache/iotdb/it/env/AbstractEnv.java, integration-test/src/main/java/org/apache/iotdb/it/env/Cluster1Env.java, integration-test/src/main/java/org/apache/iotdb/it/env/MppConfig.java, integration-test/src/main/java/org/apache/iotdb/it/env/RemoteServerEnv.java, integration-test/src/main/java/org/apache/iotdb/it/env/StandaloneOnMppEnv.java, integration-test/src/main/java/org/apache/iotdb/itbase/env/BaseConfig.java, integration-test/src/main/java/org/apache/iotdb/itbase/env/BaseEnv.java, integration-test/src/test/java/org/apache/iotdb/confignode/IoTDBConfigNodeSnapshotIT.java, integration-test/src/test/java/org/apache/iotdb/db/it/env/StandaloneEnv.java
Add ConfigNode snapshot test code. The ConfigNode will trigger snapshot if we getOrCreatePartition continuously.
=> ConfigNode snapshot integration test

integration-test/src/test/java/org/apache/iotdb/db/it/aligned/IoTDBInsertAlignedValuesIT.java, integration/src/test/java/org/apache/iotdb/session/IoTDBSessionSimpleIT.java, schema-engine-rocksdb/src/main/java/org/apache/iotdb/db/metadata/schemaregion/rocksdb/RSchemaRegion.java, server/src/main/java/org/apache/iotdb/db/conf/rest/IoTDBRestServiceConfig.java, server/src/main/java/org/apache/iotdb/db/metadata/schemaregion/SchemaRegionMemoryImpl.java, server/src/main/java/org/apache/iotdb/db/metadata/schemaregion/SchemaRegionSchemaFileImpl.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/SchemaValidator.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/write/InsertMultiTabletsNode.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/write/InsertNode.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/write/InsertRowNode.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/write/InsertRowsNode.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/write/InsertRowsOfOneDeviceNode.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/write/InsertTabletNode.java, server/src/test/java/org/apache/iotdb/db/metadata/SchemaBasicTest.java
IOTDB-4542
<hr>
This PR has:
<hr>
=> [IOTDB-4542] Optimize schema validate error message

docs/UserGuide/Data-Concept/Schema-Template.md, docs/zh/UserGuide/Data-Concept/Schema-Template.md
Add a panoramic introduction about the lifetime of the schema template, as well as a picture depicting the example.
Anyone discombobulated by the dazzling terms of the schema template may feel it effortless to figure out when or how to UNSET or DEACTIVATE a template after read the documentation.
=> [To rel/0.13]Add more docs about schema template

server/src/main/java/org/apache/iotdb/db/engine/TsFileMetricManager.java, server/src/main/java/org/apache/iotdb/db/engine/compaction/cross/CrossSpaceCompactionTask.java, server/src/main/java/org/apache/iotdb/db/engine/compaction/inner/InnerSpaceCompactionTask.java, server/src/main/java/org/apache/iotdb/db/engine/compaction/writer/CrossSpaceCompactionWriter.java, server/src/main/java/org/apache/iotdb/db/engine/storagegroup/DataRegion.java, server/src/main/java/org/apache/iotdb/db/engine/storagegroup/TsFileProcessor.java, server/src/main/java/org/apache/iotdb/db/service/metrics/predefined/FileMetrics.java
See [IOTDB-4423](https://issues.apache.org/jira/browse/IOTDB-4423).
=> [IOTDB-4423] Add TsFileMetricManager to take care of the tsfile status

server/src/main/java/org/apache/iotdb/db/engine/load/LoadTsFileManager.java
problem:
solution:
delete /data/data/load if there is no loading task running.
=> [IOTDB-4533] delete an unexpected folder is added

server/src/main/java/org/apache/iotdb/db/mpp/execution/exchange/MPPDataExchangeManager.java, server/src/main/java/org/apache/iotdb/db/mpp/execution/exchange/SourceHandle.java
More details can be seen in this [ISSUE](https://issues.apache.org/jira/browse/IOTDB-4552).
=> [IOTDB-4552] Fix NPE in SourceHandle

site/src/main/.vuepress/config.js
As HDFS-integration is not recommended, we'd better remove it from website.
=> Remove hdfs in UserGuide

docs/UserGuide/Maintenance-Tools/Metric-Tool.md, docs/zh/UserGuide/Maintenance-Tools/Metric-Tool.md
=> [To rel/0.13][IOTDB-4555] Fix metric name.

server/src/main/java/org/apache/iotdb/db/engine/compaction/CompactionTaskManager.java, server/src/main/java/org/apache/iotdb/db/service/DataNode.java, server/src/main/java/org/apache/iotdb/db/service/IoTDB.java, server/src/main/java/org/apache/iotdb/db/service/NewIoTDB.java
See [IOTDB-4554](https://issues.apache.org/jira/browse/IOTDB-4554).
=> [IOTDB-4554] Start compaction only when IoTDB is fully recovered

server/src/main/java/org/apache/iotdb/db/service/metrics/predefined/FileMetrics.java, server/src/main/java/org/apache/iotdb/db/service/metrics/predefined/SystemMetrics.java
Fix file and system metrics in metric service.
=> [To rel/0.13][IOTDB-4555] Fix File/System metrics in Metric Service.

confignode/src/main/java/org/apache/iotdb/confignode/consensus/request/ConfigPhysicalPlan.java, node-commons/src/main/java/org/apache/iotdb/commons/exception/runtime/SerializationRunTimeException.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/FragmentInstance.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/PlanNode.java, server/src/main/java/org/apache/iotdb/db/qp/physical/PhysicalPlan.java
Move SerializationRunTimeException to node-commons
=> [IOTDB-4570] Move SerializationRunTimeException to node-commons

.github/workflows/greetings.yml
greetings github action fails recently, let's try to v1.1.0.
=> upgrade greetings github action to v1.1.0

antlr/src/main/antlr4/org/apache/iotdb/db/qp/sql/IdentifierParser.g4, antlr/src/main/antlr4/org/apache/iotdb/db/qp/sql/IoTDBSqlParser.g4, antlr/src/main/antlr4/org/apache/iotdb/db/qp/sql/SqlLexer.g4, docs/UserGuide/Write-Data/Load-External-Tsfile.md, docs/zh/UserGuide/Write-Data/Load-External-Tsfile.md, integration-test/src/test/java/org/apache/iotdb/db/it/IOTDBLoadTsFileIT.java, integration/src/test/java/org/apache/iotdb/db/integration/IoTDBLoadExternalTsfileIT.java, integration/src/test/java/org/apache/iotdb/db/integration/aligned/IoTDBLoadExternalAlignedTsFileIT.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/AnalyzeVisitor.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/parser/ASTVisitor.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/load/LoadSingleTsFileNode.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/load/LoadTsFileNode.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/scheduler/load/LoadTsFileDispatcherImpl.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/scheduler/load/LoadTsFileScheduler.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/statement/crud/LoadTsFileStatement.java, server/src/main/java/org/apache/iotdb/db/qp/executor/PlanExecutor.java, server/src/main/java/org/apache/iotdb/db/qp/logical/sys/LoadFilesOperator.java, server/src/main/java/org/apache/iotdb/db/qp/physical/sys/OperateFilePlan.java, server/src/main/java/org/apache/iotdb/db/qp/sql/IoTDBSqlVisitor.java, server/src/main/java/org/apache/iotdb/db/sync/receiver/load/TsFileLoader.java, server/src/test/java/org/apache/iotdb/db/qp/physical/PhysicalPlanTest.java, server/src/test/java/org/apache/iotdb/db/utils/TsFileRewriteToolTest.java
origin load statement:
`load '<path/dir>' [autoregister=true/false][,sglevel=int][,verify=true/false]`
new load statement:
`load '<path/dir>' [sglevel=int] [verify=true/false] [onSuccess=delete/none]`
=> [IOTDB-3656] mpp load change grammar

server/src/main/java/org/apache/iotdb/db/utils/datastructure/AlignedTVList.java, server/src/main/java/org/apache/iotdb/db/utils/datastructure/BackAlignedTVList.java, server/src/main/java/org/apache/iotdb/db/utils/datastructure/BackBinaryTVList.java, server/src/main/java/org/apache/iotdb/db/utils/datastructure/BackBooleanTVList.java, server/src/main/java/org/apache/iotdb/db/utils/datastructure/BackDoubleTVList.java, server/src/main/java/org/apache/iotdb/db/utils/datastructure/BackFloatTVList.java, server/src/main/java/org/apache/iotdb/db/utils/datastructure/BackIntTVList.java, server/src/main/java/org/apache/iotdb/db/utils/datastructure/BackLongTVList.java, server/src/main/java/org/apache/iotdb/db/utils/datastructure/BackwardSort.java, server/src/main/java/org/apache/iotdb/db/utils/datastructure/BinaryTVList.java, server/src/main/java/org/apache/iotdb/db/utils/datastructure/BooleanTVList.java, server/src/main/java/org/apache/iotdb/db/utils/datastructure/DoubleTVList.java, server/src/main/java/org/apache/iotdb/db/utils/datastructure/FloatTVList.java, server/src/main/java/org/apache/iotdb/db/utils/datastructure/IntTVList.java, server/src/main/java/org/apache/iotdb/db/utils/datastructure/LongTVList.java, server/src/main/java/org/apache/iotdb/db/utils/datastructure/TimAlignedTVList.java
=> [IOTDB-4504] Add BackwardSort algorithm for disordered time series

.github/workflows/greetings.yml
=> [To rel/0.13] upgrade greetings github action to v1.1.0

integration/src/test/java/org/apache/iotdb/db/integration/IoTDBArchivingIT.java, server/src/main/java/org/apache/iotdb/db/engine/archiving/ArchivingManager.java, server/src/test/java/org/apache/iotdb/db/utils/EnvironmentUtils.java
Data archiving it fails because the sleep time is too short.
=> [To rel/0.13][IOTDB-4577] Fix data archiving IT

tsfile/src/main/java/org/apache/iotdb/tsfile/utils/BytesUtils.java
=> [ISSUE-7522] Fix wrong annotation of BytesUtil.getByteN

server/src/main/java/org/apache/iotdb/db/protocol/mpprest/handler/ExceptionHandler.java, server/src/main/java/org/apache/iotdb/db/protocol/mpprest/impl/RestApiServiceImpl.java
[IOTDB-4490] Msg does not match CLI when creating invalid storage group
=> [IOTDB-4490] [RESTApi] Msg does not match CLI when creating invalid storage group

server/src/main/java/org/apache/iotdb/db/protocol/mpprest/impl/GrafanaApiServiceImpl.java, server/src/main/java/org/apache/iotdb/db/protocol/mpprest/impl/RestApiServiceImpl.java
[IOTDB-4499] Unsupported to insert multiple rows of data
=> [IOTDB-4499] Unsupported to insert multiple rows of data

integration/src/test/java/org/apache/iotdb/db/integration/IoTDBArchivingIT.java
Check archiving result after all tasks are finished.
=> [To rel/0.13][IOTDB-4577] Check archiving result after all tasks are finished

integration-test/src/test/java/org/apache/iotdb/db/it/aligned/IoTDBGroupByLevelQueryIT.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/ExpressionAnalyzer.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/GroupByLevelController.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/LogicalPlanBuilder.java
=> [IOTDB-3818] Support nested expressions in GROUP BY LEVEL

server/src/main/java/org/apache/iotdb/db/mpp/plan/scheduler/FragmentInstanceDispatcherImpl.java
Simple change. 
Add TSStatus when print err message for write operation
=> [IOTDB-4331] Print status when write failed both in remote and local

.github/workflows/greetings.yml
=> Revert "Disable greetings workflow"

integration-test/src/test/java/org/apache/iotdb/db/it/IOTDBLoadTsFileIT.java, server/src/main/java/org/apache/iotdb/db/engine/storagegroup/DataRegion.java
solution:
when loading tsfiles successfully, it will clean up all schema cache in datanode.
=> [IOTDB-3656] mpp load supports last cache

server/src/main/java/org/apache/iotdb/db/consensus/statemachine/SchemaRegionStateMachine.java
See: https://issues.apache.org/jira/browse/IOTDB-4599
=> [IOTDB-4599] remove useless log in SchemaRegionStateMachine

flink-tsfile-connector/src/test/java/org/apache/iotdb/flink/util/TSFileConfigUtilCompletenessTest.java, integration/src/test/java/org/apache/iotdb/db/integration/IoTDBLargePatternNameIT.java, server/src/assembly/resources/conf/iotdb-engine.properties, server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java, server/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java, tsfile/src/main/java/org/apache/iotdb/tsfile/common/conf/TSFileConfig.java, tsfile/src/main/java/org/apache/iotdb/tsfile/read/filter/operator/Regexp.java
Optimize the pattern matching process in `Regexp`.
=> [To rel/0.13] Optimize pattern matching in Regexp

server/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java, server/src/main/java/org/apache/iotdb/db/engine/StorageEngine.java, server/src/main/java/org/apache/iotdb/db/engine/StorageEngineV2.java, server/src/main/java/org/apache/iotdb/db/engine/querycontext/QueryDataSource.java, server/src/main/java/org/apache/iotdb/db/engine/storagegroup/DataRegion.java, server/src/main/java/org/apache/iotdb/db/engine/storagegroup/TsFileResource.java, server/src/main/java/org/apache/iotdb/db/engine/storagegroup/dataregion/StorageGroupManager.java, server/src/main/java/org/apache/iotdb/db/mpp/common/header/ColumnHeaderConstant.java, server/src/main/java/org/apache/iotdb/db/qp/utils/DatetimeUtils.java
Convert ttl(ms) according to the time precision.
=> [IOTDB-4615] TTL supports timestamp precision

node-commons/src/main/java/org/apache/iotdb/commons/utils/AuthUtils.java
see [IOTDB-4646](https://issues.apache.org/jira/browse/IOTDB-4646)
=> [IOTDB-4646] Illegal privilege APPLY_TEMPLATE on seriesPath root.ln.**

server/src/main/java/org/apache/iotdb/db/engine/flush/MemTableFlushTask.java
Avoid the issue related with [IOTDB-4636](https://issues.apache.org/jira/browse/IOTDB-4636).
=> [To rel/0.13][IOTDB-4636] Add check to avoid flush empty chunk group

server/src/main/java/org/apache/iotdb/db/engine/storagegroup/DataRegion.java
=> [IOTDB-4659] Fix time unit in the ttl log

server/src/main/java/org/apache/iotdb/db/engine/storagegroup/VirtualStorageGroupProcessor.java
=> [To rel/0.13][IOTDB-4659] Fix time unit in the ttl log

server/src/main/java/org/apache/iotdb/db/query/reader/chunk/metadata/DiskAlignedChunkMetadataLoader.java, server/src/main/java/org/apache/iotdb/db/query/reader/chunk/metadata/DiskChunkMetadataLoader.java, server/src/main/java/org/apache/iotdb/db/utils/QueryUtils.java, tsfile/src/main/java/org/apache/iotdb/tsfile/file/metadata/AlignedTimeSeriesMetadata.java, tsfile/src/main/java/org/apache/iotdb/tsfile/file/metadata/ChunkMetadata.java, tsfile/src/main/java/org/apache/iotdb/tsfile/file/metadata/TimeseriesMetadata.java
=> [To rel/0.13] [IOTDB-4654] Fix concurrent bug caused by sharing same ChunkMetadata

node-commons/src/main/java/org/apache/iotdb/commons/path/PatternTreeMap.java, server/src/test/java/org/apache/iotdb/db/metadata/path/PatternTreeMapTest.java
1. Fix BUG about PatternTreeMap#getOverlapped does not return correct values
2. De-duplicate resut list of PatternTreeMap#getOverlapped
3. Add some UT
=> [IODB-4657] Fix PatternTreeMap#getOverlapped does not return correct values

cli/src/main/java/org/apache/iotdb/tool/ImportCsv.java, cross-tests/src/test/java/org/apache/iotdb/cross/tests/tools/importCsv/ImportCsvTestIT.java
see [https://issues.apache.org/jira/browse/IOTDB-4647](https://issues.apache.org/jira/browse/IOTDB-4647)
fix
=> [IOTDB-4647] Fix CSV import error when import header name with type

rewrite-tsfile-tool/src/main/java/org/apache/iotdb/RewriteTsFileTool.java
See [IOTDB-4650](https://issues.apache.org/jira/browse/IOTDB-4650).
=> [IOTDB-4650] Support starting reading from tail in RewriteTsFileTool

server/src/main/java/org/apache/iotdb/db/engine/flush/MemTableFlushTask.java
=> [IOTDB-4636] Add check to avoid flush empty chunk group

confignode/src/main/java/org/apache/iotdb/confignode/consensus/request/ConfigPhysicalPlan.java, confignode/src/main/java/org/apache/iotdb/confignode/consensus/request/ConfigPhysicalPlanType.java, confignode/src/main/java/org/apache/iotdb/confignode/consensus/request/read/GetTriggerLocationPlan.java, confignode/src/main/java/org/apache/iotdb/confignode/consensus/response/TriggerLocationResp.java, confignode/src/main/java/org/apache/iotdb/confignode/manager/ConfigManager.java, confignode/src/main/java/org/apache/iotdb/confignode/manager/IManager.java, confignode/src/main/java/org/apache/iotdb/confignode/manager/TriggerManager.java, confignode/src/main/java/org/apache/iotdb/confignode/persistence/TriggerInfo.java, confignode/src/main/java/org/apache/iotdb/confignode/persistence/executor/ConfigPlanExecutor.java, confignode/src/main/java/org/apache/iotdb/confignode/service/thrift/ConfigNodeRPCServiceProcessor.java, confignode/src/test/java/org/apache/iotdb/confignode/consensus/request/ConfigPhysicalPlanSerDeTest.java, node-commons/src/main/java/org/apache/iotdb/commons/trigger/TriggerTable.java, server/src/main/java/org/apache/iotdb/db/client/ConfigNodeClient.java, thrift-confignode/src/main/thrift/confignode.thrift
Two results of this interface returns: 
1.success TSStatus
2.error TSStatus with error message
=> [IOTDB-4698]Implement interface of getLocationOfStatefulTrigger

grafana-plugin/README.md, grafana-plugin/src/plugin.json
Grafana plugin Modify pluginId and readme files
=> Grafana plugin Modify pluginId and readme files

.github/workflows/main-unix.yml, .github/workflows/main-win.yml
Use maven `test` intead of maven `verify`.
=> Disable the IT of the original standalone architecture

server/src/main/java/org/apache/iotdb/db/service/DataNode.java, server/src/main/java/org/apache/iotdb/db/trigger/executor/TriggerExecutor.java, server/src/main/java/org/apache/iotdb/db/trigger/service/TriggerManagementService.java
We leave an interface recover() for user to recover the state of Trigger when recovering trigger instances.
=> [IOTDB-4706] Call Trigger.restore() when recovering trigger instances

confignode/src/main/java/org/apache/iotdb/confignode/manager/ConfigManager.java, confignode/src/main/java/org/apache/iotdb/confignode/manager/IManager.java, confignode/src/main/java/org/apache/iotdb/confignode/manager/ProcedureManager.java, confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/sync/CreatePipeProcedure.java, confignode/src/main/java/org/apache/iotdb/confignode/service/thrift/ConfigNodeRPCServiceProcessor.java, confignode/src/test/java/org/apache/iotdb/confignode/procedure/impl/OperatePipeProcedureTest.java, node-commons/src/main/java/org/apache/iotdb/commons/utils/ThriftConfigNodeSerDeUtils.java, server/src/main/java/org/apache/iotdb/db/client/ConfigNodeClient.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/execution/config/executor/ClusterConfigTaskExecutor.java, server/src/main/java/org/apache/iotdb/db/utils/sync/SyncPipeUtil.java, thrift-confignode/src/main/thrift/confignode.thrift
* Rename `TPipeInfo` to `TCreatePipeReq`
* Delete useless codes
=> [IOTDB-4714] Rename TPipeInfo to TCreatePipeReq

docs/UserGuide/Ecosystem-Integration/NiFi-IoTDB.md, docs/zh/UserGuide/Ecosystem-Integration/NiFi-IoTDB.md
Update IoTDB nifi process doc. 
Include 
PutIoTDBRecord
QueryIoTDBRecord
<hr>
This PR has:
<hr>
=> Update IoTDB nifi process doc

antlr/src/main/antlr4/org/apache/iotdb/db/qp/sql/IoTDBSqlParser.g4, integration-test/src/test/java/org/apache/iotdb/db/it/aggregation/IoTDBTagAggregationIT.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/AnalyzeVisitor.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/parser/ASTVisitor.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/statement/crud/QueryStatement.java, server/src/test/java/org/apache/iotdb/db/mpp/plan/plan/LogicalPlannerTest.java
See JIRA: https://issues.apache.org/jira/browse/IOTDB-4751
=> [IOTDB-4751] Fix tag aggregation  being without any error message

confignode/src/main/java/org/apache/iotdb/confignode/service/thrift/ConfigNodeRPCServiceProcessor.java, node-commons/src/main/java/org/apache/iotdb/commons/udf/service/UDFManagementService.java, server/src/main/java/org/apache/iotdb/db/client/ConfigNodeClient.java, server/src/main/java/org/apache/iotdb/db/service/DataNode.java, server/src/main/java/org/apache/iotdb/db/service/ResourcesInformationHolder.java, thrift-confignode/src/main/thrift/confignode.thrift
Get UDFInformationList and jar file from configNode when restart/register DataNode.
=> [IOTDB-4756] Register UDF when restart/register DataNode

confignode/src/main/java/org/apache/iotdb/confignode/consensus/request/ConfigPhysicalPlan.java, confignode/src/main/java/org/apache/iotdb/confignode/consensus/request/ConfigPhysicalPlanType.java, confignode/src/main/java/org/apache/iotdb/confignode/consensus/request/read/GetFunctionTablePlan.java, confignode/src/main/java/org/apache/iotdb/confignode/consensus/response/FunctionTableResp.java, confignode/src/main/java/org/apache/iotdb/confignode/manager/ConfigManager.java, confignode/src/main/java/org/apache/iotdb/confignode/manager/IManager.java, confignode/src/main/java/org/apache/iotdb/confignode/manager/UDFManager.java, confignode/src/main/java/org/apache/iotdb/confignode/persistence/UDFInfo.java, confignode/src/main/java/org/apache/iotdb/confignode/persistence/executor/ConfigPlanExecutor.java, confignode/src/main/java/org/apache/iotdb/confignode/service/thrift/ConfigNodeRPCServiceProcessor.java, confignode/src/test/java/org/apache/iotdb/confignode/consensus/request/ConfigPhysicalPlanSerDeTest.java, node-commons/src/main/java/org/apache/iotdb/commons/udf/UDFTable.java
=> [IOTDB-4722][IOTDB-4723]modify Show & Drop UDF process on ConfigNode

example/tsfile/src/main/java/org/apache/iotdb/tsfile/TsFileSequenceRead.java, integration/src/test/java/org/apache/iotdb/db/integration/IoTDBRewriteTsFileToolIT.java, rewrite-tsfile-tool/src/main/java/org/apache/iotdb/RewriteTsFileTool.java
See [IOTDB-4693](https://issues.apache.org/jira/browse/IOTDB-4693).
=> [IOTDB-4693] Support broken tsfile rewrite

cli/src/test/java/org/apache/iotdb/cli/StartClientScriptIT.java, zeppelin-interpreter/src/test/java/org/apache/zeppelin/iotdb/IoTDBInterpreterTest.java
In this pr, I ignore two ITs(which pretend itself to be UT) in old standalone stylue.
=> Ignore some old standalone style IT

grafana-metrics-example/cluster/Apache IoTDB ConfigNode Dashboard v0.14.0.json, grafana-metrics-example/cluster/Apache IoTDB DataNode Dashboard v0.14.0.json
Update multiLeader metrics in grafana dashboard
=> [IOTDB-4651] Add multiLeader metrics into grafana dashboard

confignode/src/main/java/org/apache/iotdb/confignode/conf/ConfigNodeDescriptor.java
=> [RatisConsensus] fix snapshot param mistake

integration/src/test/java/org/apache/iotdb/db/integration/IoTDBFuzzyQueryIT.java, server/src/main/java/org/apache/iotdb/db/qp/logical/crud/LikeOperator.java, server/src/main/java/org/apache/iotdb/db/qp/logical/crud/RegexpOperator.java, server/src/main/java/org/apache/iotdb/db/qp/sql/IoTDBSqlVisitor.java, server/src/main/java/org/apache/iotdb/db/qp/strategy/optimizer/ConcatPathOptimizer.java, server/src/test/java/org/apache/iotdb/db/qp/physical/PhysicalPlanTest.java, tsfile/src/main/java/org/apache/iotdb/tsfile/read/filter/ValueFilter.java, tsfile/src/main/java/org/apache/iotdb/tsfile/read/filter/operator/Like.java, tsfile/src/main/java/org/apache/iotdb/tsfile/read/filter/operator/Regexp.java, tsfile/src/test/java/org/apache/iotdb/tsfile/read/filter/FilterSerializeTest.java
=> [To rel/0.13][IOTDB-4781] Implement NOT LIKE value filter

metrics/dropwizard-metrics/src/main/java/org/apache/iotdb/metrics/dropwizard/DropwizardMetricManager.java, metrics/interface/src/main/java/org/apache/iotdb/metrics/AbstractMetricManager.java, metrics/interface/src/main/java/org/apache/iotdb/metrics/impl/DoNothingMetricManager.java, metrics/interface/src/main/java/org/apache/iotdb/metrics/utils/MetricInfo.java, metrics/micrometer-metrics/src/main/java/org/apache/iotdb/metrics/micrometer/MicrometerMetricManager.java, server/src/test/java/org/apache/iotdb/db/metric/MetricServiceTest.java
See: https://issues.apache.org/jira/browse/IOTDB-4779
=> [IOTDB-4779] Fix remove metrics in Metric Module

server/src/main/java/org/apache/iotdb/db/query/control/SessionManager.java
https://issues.apache.org/jira/browse/IOTDB-4773
=> [IOTDB-4773] New session trigger memory-leak

antlr/src/main/antlr4/org/apache/iotdb/db/qp/sql/IoTDBSqlParser.g4, confignode/src/main/java/org/apache/iotdb/confignode/manager/UDFManager.java, confignode/src/main/java/org/apache/iotdb/confignode/persistence/TriggerInfo.java, confignode/src/main/java/org/apache/iotdb/confignode/persistence/UDFInfo.java, node-commons/src/main/java/org/apache/iotdb/commons/executable/ExecutableManager.java, node-commons/src/main/java/org/apache/iotdb/commons/udf/UDFInformation.java, node-commons/src/main/java/org/apache/iotdb/commons/udf/UDFTable.java, node-commons/src/main/java/org/apache/iotdb/commons/udf/service/UDFExecutableManager.java, node-commons/src/main/java/org/apache/iotdb/commons/udf/service/UDFManagementService.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/execution/config/executor/ClusterConfigTaskExecutor.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/parser/ASTVisitor.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/statement/metadata/CreateFunctionStatement.java, server/src/main/java/org/apache/iotdb/db/service/DataNode.java, server/src/main/java/org/apache/iotdb/db/trigger/service/TriggerManagementService.java, thrift-confignode/src/main/thrift/confignode.thrift, thrift/src/main/thrift/datanode.thrift
Make Using clause in CREATE FUNCTION optional, which is compatible with previous version.
=> [IOTDB-4787] Make Using clause in CREATE FUNCTION optional

confignode/src/main/java/org/apache/iotdb/confignode/service/ConfigNode.java, server/src/main/java/org/apache/iotdb/db/service/metrics/DataNodeMetricsHelper.java, server/src/main/java/org/apache/iotdb/db/service/metrics/SystemMetrics.java
See: https://issues.apache.org/jira/browse/IOTDB-4782
=> [IOTDB-4782] Fix systemMetrics in confignode

confignode/src/main/java/org/apache/iotdb/confignode/manager/TriggerManager.java, confignode/src/main/java/org/apache/iotdb/confignode/persistence/TriggerInfo.java, confignode/src/main/java/org/apache/iotdb/confignode/persistence/executor/ConfigPlanExecutor.java, confignode/src/main/java/org/apache/iotdb/confignode/procedure/env/ConfigNodeProcedureEnv.java, confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/CreateTriggerProcedure.java, node-commons/src/main/java/org/apache/iotdb/commons/trigger/TriggerInformation.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/execution/config/executor/ClusterConfigTaskExecutor.java, server/src/main/java/org/apache/iotdb/db/trigger/service/TriggerManagementService.java
=> [IOTDB-4788] Make Using clause in CREATE TRIGGER optional (ConfigNode)

integration-test/src/test/java/org/apache/iotdb/db/it/selectinto/IoTDBSelectInto3IT.java, integration-test/src/test/java/org/apache/iotdb/db/it/selectinto/IoTDBSelectIntoIT.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/AnalyzeVisitor.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/PlanGraphPrinter.java
In this PR:
1. add more test configs
2. implement explain
3. ignore ORDER BY
=> SELECT INTO: implement explain & ignore ORDER BY

integration-test/src/test/java/org/apache/iotdb/db/it/IoTDBNestedQueryIT.java, integration-test/src/test/java/org/apache/iotdb/db/it/IoTDBSyntaxConventionIdentifierIT.java, integration-test/src/test/java/org/apache/iotdb/db/it/IoTDBSyntaxConventionStringLiteralIT.java, integration-test/src/test/java/org/apache/iotdb/db/it/udf/IoTDBUDFManagementIT.java, integration-test/src/test/java/org/apache/iotdb/db/it/udf/IoTDBUDFOtherWindowQueryIT.java, integration-test/src/test/java/org/apache/iotdb/db/it/udf/IoTDBUDFWindowQueryIT.java, integration-test/src/test/java/org/apache/iotdb/db/it/udf/IoTDBUDTFAlignByTimeQueryIT.java, integration-test/src/test/java/org/apache/iotdb/db/it/udf/IoTDBUDTFBuiltinFunctionIT.java, integration-test/src/test/java/org/apache/iotdb/db/it/udf/IoTDBUDTFHybridQueryIT.java, integration-test/src/test/java/org/apache/iotdb/db/it/udf/IoTDBUDTFNonAlignQueryIT.java
some error message are changed, so the corresponding Tests are changed.
=> remove  Ignore of UDFManagementIT

confignode/pom.xml, confignode/src/main/java/org/apache/iotdb/confignode/procedure/store/ProcedureFactory.java, confignode/src/main/java/org/apache/iotdb/confignode/service/ConfigNode.java, confignode/src/test/java/org/apache/iotdb/confignode/procedure/impl/CreateCQProcedureTest.java
Add UT for CreateCQProcedure and fix a serde bug for procedure that missing a break in switch-case.
=> Add UT for CreateCQProcedure

client-cpp/pom.xml, compile-tools/pom.xml, distribution/pom.xml, example/client-cpp-example/pom.xml, example/trigger/pom.xml, example/udf/pom.xml, grafana-connector/pom.xml, integration/pom.xml, jdbc/pom.xml, pom.xml, server/src/main/java/org/apache/iotdb/db/engine/compaction/cross/rewrite/task/SubCompactionTask.java
Add log for sub-compaction-task when meeting exception.
=> [To rel/0.13] Add error log for subtask 0.13

confignode/src/assembly/resources/sbin/stop-confignode.bat, confignode/src/assembly/resources/sbin/stop-confignode.sh, server/src/assembly/resources/sbin/stop-datanode.bat, server/src/assembly/resources/sbin/stop-datanode.sh
=> Fix shell problem in start-confignode.sh and start-datanode.sh

server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/AnalyzeVisitor.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/PlanGraphPrinter.java, server/src/test/java/org/apache/iotdb/db/mpp/plan/plan/QueryLogicalPlanUtil.java
see IOTDB-4802.
**Before:**
**After:**
=> [IOTDB-4802] Optimize the logical plan of query with only time filter

node-commons/src/main/java/org/apache/iotdb/commons/executable/ExecutableManager.java, node-commons/src/main/java/org/apache/iotdb/commons/udf/service/UDFManagementService.java
It's possible that the same file is locked by a classLoader. This pr tries to fix it.
=> Fix IoTDBConfigNodeSnapshotIT.testCreateUDF

antlr/pom.xml
Remove the file generated by antlr plugin.
=> [IOTDB-4142] Add delete generated file logic in pom of antlr

confignode/src/main/java/org/apache/iotdb/confignode/consensus/request/ConfigPhysicalPlan.java, confignode/src/main/java/org/apache/iotdb/confignode/consensus/request/write/procedure/UpdateProcedurePlan.java, confignode/src/main/java/org/apache/iotdb/confignode/manager/ProcedureManager.java, confignode/src/main/java/org/apache/iotdb/confignode/manager/UDFManager.java
=> [IOTDB-4806]	Add size limit of UDF jar when create UDF on ConfigNode

confignode/src/main/java/org/apache/iotdb/confignode/client/async/AsyncDataNodeClientPool.java
After sending specific data node request, it shall be break in switch block.
=> Fix client bug during deactivate template

integration/src/test/java/org/apache/iotdb/db/integration/IoTDBInsertWithoutTimeIT.java, server/src/main/java/org/apache/iotdb/db/qp/sql/IoTDBSqlVisitor.java
fix bug
https://issues.apache.org/jira/browse/IOTDB-3624
cherry pick with https://github.com/apache/iotdb/pull/6642
<hr>
This PR has:
<hr>
=> [To rel/0.13] [IOTDB-3624] Meet error when inserting data in SQL without timestamp

integration-test/src/test/java/org/apache/iotdb/db/it/aggregation/IoTDBAggregationByLevelIT.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/AnalyzeVisitor.java
see : [https://issues.apache.org/jira/browse/IOTDB-4695](https://issues.apache.org/jira/browse/IOTDB-4695)
=> [IOTDB-4695] GROUP LEVEL query de-duplicates result columns unexpected

confignode/src/test/resources/confignode1conf/iotdb-metric.yml, confignode/src/test/resources/confignode2conf/iotdb-metric.yml, confignode/src/test/resources/confignode3conf/iotdb-metric.yml, docs/UserGuide/Maintenance-Tools/Metric-Tool.md, docs/zh/UserGuide/Maintenance-Tools/Metric-Tool.md, metrics/interface/src/main/assembly/resources/conf/iotdb-confignode-metric.yml, metrics/interface/src/main/assembly/resources/conf/iotdb-datanode-metric.yml, metrics/interface/src/main/java/org/apache/iotdb/metrics/config/MetricConfig.java, metrics/interface/src/main/java/org/apache/iotdb/metrics/utils/IoTDBMetricsUtils.java, metrics/interface/src/test/java/org/apache/iotdb/metrics/config/MetricConfigTest.java, metrics/interface/src/test/resources/iotdb-metric.yml, server/src/test/resources/datanode1conf/iotdb-metric.yml, server/src/test/resources/datanode2conf/iotdb-metric.yml, server/src/test/resources/datanode3conf/iotdb-metric.yml
Rollback default path of iotdb metric reporter
=> Modify default path of iotdb metric reporter

integration-test/src/test/java/org/apache/iotdb/session/it/IoTDBSessionAlignedInsertIT.java
see https://github.com/apache/iotdb/issues/7803
=> Fixing unexpected actions in IoTDBSessionAlignedInsertIT

server/src/test/java/org/apache/iotdb/db/sync/pipedata/BufferedPipeDataQueueTest.java, server/src/test/java/org/apache/iotdb/db/sync/pipedata/PipeDataTest.java
remove the class of old standalone.
=> [IOTDB-4801] rewrite UT PipeDataTest & BufferedPipeDataQueueTest

integration/src/test/java/org/apache/iotdb/db/integration/IoTDBArchivingIT.java
Fix while loop in the waitUntilAllFinished method.
=> [To rel/0.13] Fix IoTDBArchivingIT

confignode/src/main/java/org/apache/iotdb/confignode/conf/ConfigNodeConfig.java, confignode/src/main/java/org/apache/iotdb/confignode/conf/ConfigNodeStartupCheck.java, confignode/src/main/java/org/apache/iotdb/confignode/manager/ConsensusManager.java, confignode/src/main/java/org/apache/iotdb/confignode/procedure/env/DataNodeRemoveHandler.java, consensus/src/main/java/org/apache/iotdb/consensus/ConsensusFactory.java, consensus/src/main/java/org/apache/iotdb/consensus/simple/SimpleConsensus.java, consensus/src/main/java/org/apache/iotdb/consensus/simple/SimpleServerImpl.java, consensus/src/test/java/org/apache/iotdb/consensus/simple/RecoveryTest.java, consensus/src/test/java/org/apache/iotdb/consensus/simple/SimpleConsensusTest.java, docs/UserGuide/Reference/ConfigNode-Config-Manual.md, docs/zh/UserGuide/Reference/ConfigNode-Config-Manual.md, integration-test/src/main/java/org/apache/iotdb/it/env/ConfigNodeWrapper.java, integration-test/src/main/java/org/apache/iotdb/itbase/env/BaseConfig.java, node-commons/src/assembly/resources/conf/iotdb-common.properties, server/src/main/java/org/apache/iotdb/db/mpp/execution/exchange/SharedTsBlockQueue.java
Rename StandAloneConsensus to OneCopyConsensus
=> Rename OneCopyConsensus to SimpleConsensus

integration-test/src/test/java/org/apache/iotdb/db/it/schema/IoTDBAutoCreateSchemaIT.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/ClusterSchemaFetcher.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/write/InsertRowNode.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/write/InsertTabletNode.java
=> [IOTDB-4824] Fix error when insert a null value into a non-existed timeseries

confignode/src/main/java/org/apache/iotdb/confignode/conf/ConfigNodeConstant.java, confignode/src/main/java/org/apache/iotdb/confignode/manager/load/LoadManagerMetrics.java
add define a constant instead #7013.
=> add: define a constant instead load manager metrics.

.github/dependabot.yml, .github/workflows/client-cpp.yml, .github/workflows/client-go.yml, .github/workflows/client-python.yml, .github/workflows/cluster-it-1c1d.yml, .github/workflows/cluster-it-1c3d.yml, .github/workflows/e2e.yml, .github/workflows/grafana-plugin.yml, .github/workflows/influxdb-protocol.yml, .github/workflows/main-unix.yml, .github/workflows/main-win.yml, .github/workflows/sonar-coveralls.yml, .github/workflows/sync.yml
Upgrade actions/checkout, actions/cache, actions/setup-java to v3
=> Upgrade github action version

integration-test/src/test/java/org/apache/iotdb/db/it/IoTDBSettleIT.java
Settle does not support mpp currently, so ignore it.
=> [IOTDB-4821]Move settleIT

server/src/main/java/org/apache/iotdb/db/protocol/rest/filter/AuthorizationFilter.java, server/src/main/java/org/apache/iotdb/db/protocol/rest/handler/ExceptionHandler.java, server/src/main/java/org/apache/iotdb/db/protocol/rest/handler/ExecuteStatementHandler.java, server/src/main/java/org/apache/iotdb/db/protocol/rest/handler/QueryDataSetHandler.java, server/src/main/java/org/apache/iotdb/db/protocol/rest/handler/StatementConstructionHandler.java, server/src/main/java/org/apache/iotdb/db/protocol/rest/impl/RestApiServiceImpl.java
restServer module adaptation and optimization
[IOTDB-4778][IOTDB-4031][IOTDB-4764][IOTDB-4514]
=> [IOTDB-4778][IOTDB-4031][IOTDB-4764][IOTDB-4514] restServer module adaptation and optimization

metrics/interface/src/main/java/org/apache/iotdb/metrics/config/MetricConfigDescriptor.java, server/src/main/java/org/apache/iotdb/db/engine/compaction/CompactionTaskManager.java, server/src/main/java/org/apache/iotdb/db/engine/compaction/inner/InnerSpaceCompactionTask.java, server/src/test/java/org/apache/iotdb/db/engine/compaction/AbstractCompactionTest.java, server/src/test/java/org/apache/iotdb/db/engine/compaction/CompactionSchedulerTest.java, server/src/test/java/org/apache/iotdb/db/engine/compaction/ReadPointCompactionPerformerTest.java, server/src/test/java/org/apache/iotdb/db/engine/compaction/cross/CrossSpaceCompactionExceptionTest.java, server/src/test/java/org/apache/iotdb/db/engine/compaction/cross/CrossSpaceCompactionTest.java, server/src/test/java/org/apache/iotdb/db/engine/compaction/cross/CrossSpaceCompactionValidationTest.java, server/src/test/java/org/apache/iotdb/db/engine/compaction/cross/RewriteCrossSpaceCompactionRecoverTest.java, server/src/test/java/org/apache/iotdb/db/engine/compaction/cross/RewriteCrossSpaceCompactionTest.java, server/src/test/java/org/apache/iotdb/db/engine/compaction/inner/InnerCompactionEmptyTsFileTest.java, server/src/test/java/org/apache/iotdb/db/engine/compaction/inner/InnerCompactionMoreDataTest.java, server/src/test/java/org/apache/iotdb/db/engine/compaction/inner/InnerCompactionSchedulerTest.java, server/src/test/java/org/apache/iotdb/db/engine/compaction/inner/InnerCompactionTest.java, server/src/test/java/org/apache/iotdb/db/engine/compaction/inner/ReadChunkCompactionPerformerNoAlignedTest.java, server/src/test/java/org/apache/iotdb/db/engine/compaction/recover/RewriteCrossSpaceCompactionRecoverCompatibleTest.java, server/src/test/java/org/apache/iotdb/db/engine/compaction/recover/SizeTieredCompactionRecoverCompatibleTest.java, server/src/test/java/org/apache/iotdb/db/engine/compaction/utils/CompactionCheckerUtils.java, tsfile/src/test/java/org/apache/iotdb/tsfile/write/TsFileWriteApiTest.java
See [IOTDB-4800](https://issues.apache.org/jira/browse/IOTDB-4800).
Rewrite some UT to remove the use of old stand-alone.
=> [IOTDB-4800] [Rewrite UT] Rewrite some UT in compaction module

integration-test/import-control.xml, integration-test/src/main/java/org/apache/iotdb/it/env/AbstractEnv.java, integration-test/src/main/java/org/apache/iotdb/itbase/env/BaseEnv.java, integration-test/src/test/java/org/apache/iotdb/db/it/IoTDBDatetimeFormatIT.java, integration-test/src/test/java/org/apache/iotdb/db/it/IoTDBEncodingIT.java, integration-test/src/test/java/org/apache/iotdb/db/it/IoTDBExecuteBatchIT.java, integration-test/src/test/java/org/apache/iotdb/db/it/IoTDBFloatPrecisionIT.java, integration-test/src/test/java/org/apache/iotdb/db/it/IoTDBFlushQueryMergeIT.java, integration-test/src/test/java/org/apache/iotdb/db/it/IoTDBInsertMultiRowIT.java, integration-test/src/test/java/org/apache/iotdb/db/it/IoTDBInsertNaNIT.java, integration-test/src/test/java/org/apache/iotdb/db/it/IoTDBInsertNullIT.java, integration-test/src/test/java/org/apache/iotdb/db/it/IoTDBInsertWithQueryIT.java, integration-test/src/test/java/org/apache/iotdb/db/it/IoTDBPartialInsertionIT.java, integration-test/src/test/java/org/apache/iotdb/db/it/IoTDBRecoverIT.java, integration-test/src/test/java/org/apache/iotdb/db/it/IoTDBRecoverUnclosedIT.java, integration-test/src/test/java/org/apache/iotdb/db/it/IoTDBRestartIT.java, integration-test/src/test/java/org/apache/iotdb/session/it/IoTDBSessionAlignedInsertIT.java, integration-test/src/test/java/org/apache/iotdb/session/it/pool/SessionPoolIT.java
see https://issues.apache.org/jira/browse/IOTDB-4826
=> [IOTDB-4826] Move some IT to integration-test

confignode/src/main/java/org/apache/iotdb/confignode/persistence/schema/TemplateTable.java, docs/UserGuide/Operate-Metadata/Template.md, docs/zh/UserGuide/Operate-Metadata/Template.md, thrift-confignode/src/main/thrift/confignode.thrift
1. add some description on template usage to User-Guide
2. fix template usage error msg
3. add schema related annotations to confignode.thrift
=> [IOTDB-4846][IOTDB-4053] Fix docs and error msg

consensus/src/main/java/org/apache/iotdb/consensus/multileader/logdispatcher/LogDispatcher.java
Fix the NPE when addPeer to a MultiLeader Group with 1 replica. 
1 replica.
Before removing:
After removing:
=> [IOTDB-4874] Fix the NPE when addPeer to a MultiLeader Group with 1 replic

integration-test/src/test/java/org/apache/iotdb/db/it/aligned/IoTDBInsertAlignedValues2IT.java, integration-test/src/test/java/org/apache/iotdb/db/it/aligned/IoTDBInsertAlignedValues3IT.java, integration-test/src/test/java/org/apache/iotdb/db/it/aligned/IoTDBInsertAlignedValues4IT.java, integration-test/src/test/java/org/apache/iotdb/db/it/aligned/IoTDBInsertAlignedValuesIT.java
Change initBeforeClass to initBeforeTest in @Before IT setup
=> Change initBeforeClass to initBeforeTest

server/src/main/java/org/apache/iotdb/db/tools/TsFileSketchTool.java
As shown in the following figure, this pr mainly makes four changes to the TsFile sketch tool:
1. Fix the bug that TsFileSketchTool prints only the first page info when there are multiple pages in a chunk, as the red arrow shows. (When there is only one page in a chunk, print the same information as the old version.)
2. Remove redundant information and complement the actual serialized information, as the orange arrow shows.
3. Modify the print order of TimeseriesIndex and IndexOfTimeseriesIndex to make them printed in increasing order of disk position, as the blue arrow shows.
4. Modify the print of TsFileMetadata to make it more clear, as the green arrow shows.
To clarify the third point, the following figure shows how TimeseriesIndex and IndexOfTimeseriesIndex are serialized on disk: …
=> [IOTDB-4894] Fix bug that TsFileSketchTool prints only the first page info when there are multiple pages in a chunk

server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/AnalyzeVisitor.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/write/InsertRowsOfOneDeviceNode.java
see https://issues.apache.org/jira/browse/IOTDB-4558
=> [IOTDB-4558] Use insertRowsOfOneDevice to execute insert multi rows sql statement

server/src/main/java/org/apache/iotdb/db/sync/pipedata/queue/BufferedPipeDataQueue.java, server/src/test/java/org/apache/iotdb/db/sync/pipedata/BufferedPipeDataQueueTest.java
problem:
BufferedPipeDataQueueTest.testOfferWhileTakingWithDiscontinuousSerialNumber fail.
=> [IOTDB-4771]BufferedPipeDataQueueTest.testOfferWhileTakingWithDiscontinuousSerialNumber fail

example/session/src/main/java/org/apache/iotdb/SessionExample.java, node-commons/src/assembly/resources/conf/iotdb-common.properties, node-commons/src/main/java/org/apache/iotdb/commons/conf/CommonConfig.java, node-commons/src/main/java/org/apache/iotdb/commons/conf/CommonDescriptor.java, server/src/main/java/org/apache/iotdb/db/mpp/common/header/ColumnHeaderConstant.java, session/src/main/java/org/apache/iotdb/session/ISession.java, session/src/main/java/org/apache/iotdb/session/Session.java, session/src/main/java/org/apache/iotdb/session/pool/SessionPool.java
=> Add session method of database and make header config

server/src/main/java/org/apache/iotdb/db/engine/compaction/CompactionTaskManager.java
https://issues.apache.org/jira/browse/IOTDB-4789
<hr>
This PR has:
<hr>
=> [IOTDB-4789]Fix the bug of termination timing log can not be logged

confignode/src/main/java/org/apache/iotdb/confignode/conf/ConfigNodeConfig.java, confignode/src/main/java/org/apache/iotdb/confignode/consensus/statemachine/ConfigNodeRegionStateMachine.java, confignode/src/main/java/org/apache/iotdb/confignode/manager/ConfigManager.java, confignode/src/main/java/org/apache/iotdb/confignode/manager/ConsensusManager.java, confignode/src/main/java/org/apache/iotdb/confignode/persistence/partition/StorageGroupPartitionTable.java, confignode/src/main/java/org/apache/iotdb/confignode/procedure/env/DataNodeRemoveHandler.java, confignode/src/main/java/org/apache/iotdb/confignode/service/thrift/ConfigNodeRPCServiceProcessor.java, confignode/src/test/java/org/apache/iotdb/confignode/consensus/request/ConfigPhysicalPlanSerDeTest.java, consensus/README.md, consensus/src/test/java/org/apache/iotdb/consensus/ratis/UtilsTest.java, consensus/src/test/java/org/apache/iotdb/consensus/simple/SimpleConsensusTest.java, integration-test/src/main/java/org/apache/iotdb/itbase/env/BaseConfig.java, integration-test/src/test/java/org/apache/iotdb/confignode/it/IoTDBClusterPartitionIT.java, integration-test/src/test/java/org/apache/iotdb/confignode/it/IoTDBConfigNodeSwitchLeaderIT.java, node-commons/src/main/java/org/apache/iotdb/commons/consensus/ConfigNodeRegionId.java, node-commons/src/main/java/org/apache/iotdb/commons/consensus/ConsensusGroupId.java, node-commons/src/test/java/org/apache/iotdb/commons/utils/ThriftCommonsSerDeUtilsTest.java, server/src/main/java/org/apache/iotdb/db/auth/ClusterAuthorityFetcher.java, server/src/main/java/org/apache/iotdb/db/client/ConfigNodeClient.java, server/src/main/java/org/apache/iotdb/db/client/ConfigNodeInfo.java, server/src/main/java/org/apache/iotdb/db/client/DataNodeClientPoolFactory.java, server/src/main/java/org/apache/iotdb/db/metadata/template/ClusterTemplateManager.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/ClusterPartitionFetcher.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/cache/PartitionCache.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/execution/config/executor/ClusterConfigTaskExecutor.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/parser/ASTVisitor.java, server/src/main/java/org/apache/iotdb/db/sync/common/ClusterSyncInfoFetcher.java, server/src/main/java/org/apache/iotdb/db/trigger/executor/TriggerFireVisitor.java, server/src/main/java/org/apache/iotdb/db/trigger/service/TriggerInformationUpdater.java, thrift-commons/src/main/thrift/common.thrift
Rename PartitionRegion to ConfigNodeRegion
=> Rename PartitionRegion to ConfigNodeRegion

integration-test/src/test/java/org/apache/iotdb/db/it/IoTDBInsertMultiRowIT.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/AnalyzeVisitor.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/parser/StatementGenerator.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/write/InsertRowsOfOneDeviceNode.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/statement/crud/InsertRowsOfOneDeviceStatement.java
=> [IOTDB-4913] Fix NPE when insert multi rows with null by sql

integration-test/src/test/java/org/apache/iotdb/db/it/sync/IoTDBPipeIT.java, integration-test/src/test/java/org/apache/iotdb/db/it/sync/IoTDBPipeSinkIT.java, node-commons/src/main/java/org/apache/iotdb/commons/sync/pipe/TsFilePipeInfo.java, server/src/main/java/org/apache/iotdb/db/sync/SyncService.java, server/src/main/java/org/apache/iotdb/db/sync/externalpipe/ExtPipePluginManager.java, server/src/main/java/org/apache/iotdb/db/sync/pipedata/DeletionPipeData.java, server/src/main/java/org/apache/iotdb/db/sync/pipedata/TsFilePipeData.java, server/src/main/java/org/apache/iotdb/db/sync/receiver/load/TsFileLoader.java, server/src/main/java/org/apache/iotdb/db/sync/transport/client/IoTDBSyncClient.java, server/src/main/java/org/apache/iotdb/db/sync/transport/server/ReceiverManager.java, thrift/src/main/thrift/client.thrift
* Rename some variables names in sync module from `stroage group` to `database`
=> Rename storage group to database in sync module

docker/src/main/DockerCompose/GrafanaPlugin/iotdb/conf/iotdb-rest.properties, docs/UserGuide/API/RestService.md, docs/zh/UserGuide/API/RestService.md, server/src/assembly/resources/conf/iotdb-rest.properties, server/src/main/java/org/apache/iotdb/db/conf/rest/IoTDBRestServiceConfig.java, server/src/main/java/org/apache/iotdb/db/conf/rest/IoTDBRestServiceDescriptor.java, server/src/main/java/org/apache/iotdb/db/protocol/rest/filter/AuthorizationFilter.java, server/src/test/resources/iotdb-rest.properties, session/src/test/resources/iotdb-rest.properties
[IOTDB-4601] Add configuration to close swagger
=> [IOTDB-4601] Add configuration to close swagger

server/src/main/java/org/apache/iotdb/db/mpp/execution/executor/RegionWriteExecutor.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/AnalyzeVisitor.java
=> [IOTDB-4875][IOTDB-4918] Fix timeseries creation check bug

docs/UserGuide/Data-Concept/Compression.md, docs/UserGuide/QuickStart/ServerFileList.md, docs/zh/UserGuide/Data-Concept/Compression.md, docs/zh/UserGuide/QuickStart/ServerFileList.md, server/src/main/java/org/apache/iotdb/db/engine/StorageEngineV2.java, server/src/main/java/org/apache/iotdb/db/engine/snapshot/SnapshotLoader.java, server/src/main/java/org/apache/iotdb/db/engine/storagegroup/DataRegion.java, server/src/main/java/org/apache/iotdb/db/metadata/idtable/IDTableManager.java, server/src/test/java/org/apache/iotdb/db/utils/EnvironmentUtils.java
Rename storage_groups dir name to databases
=> [IOTDB-4937] Rename storage_groups dir name to databases

docs/UserGuide/Administration-Management/Administration.md, docs/zh/UserGuide/Administration-Management/Administration.md, server/src/main/java/org/apache/iotdb/db/auth/AuthorityChecker.java
see [IOTDB-4921](https://issues.apache.org/jira/browse/IOTDB-4921)
=> [IOTDB-4921]Add auth check to deactivate and unset and drop template

server/src/main/java/org/apache/iotdb/db/tools/schema/SchemaFileSketchTool.java
Clear useless code in SchemaFileSketchTool
=> Clear useless code in SchemaFileSketchTool

.github/workflows/client-cpp.yml, .github/workflows/client-go.yml, .github/workflows/client-python.yml, .github/workflows/cluster-it-1c1d.yml, .github/workflows/cluster-it-1c3d.yml, .github/workflows/e2e.yml, .github/workflows/grafana-plugin.yml, .github/workflows/influxdb-protocol.yml, .github/workflows/main-unix.yml, .github/workflows/main-win.yml, .github/workflows/site-build.yml, .github/workflows/sonar-coveralls.yml, .github/workflows/sync.yml, site/src/main/.vuepress/config.js
1. add a CI workflow to check website compile issue
2. fix the current compile error
=> Add website compile CI and fix website compile error

.github/workflows/client-cpp.yml, .github/workflows/client-go.yml, .github/workflows/client-python.yml, .github/workflows/influxdb-protocol.yml, .github/workflows/site-build.yml, .github/workflows/sonar-coveralls.yml
=> Clean some usage of Java in CI workflows

node-commons/src/main/java/org/apache/iotdb/commons/conf/CommonDescriptor.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/write/InsertNode.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/write/InsertRowNode.java, server/src/test/java/org/apache/iotdb/db/wal/allocation/ElasticStrategyTest.java, server/src/test/java/org/apache/iotdb/db/wal/allocation/FirstCreateStrategyTest.java, server/src/test/java/org/apache/iotdb/db/wal/allocation/RoundRobinStrategyTest.java
1. Info lost when setting wal dirs
2. Use measurements to serialize and deserialize instead of measurementSchemas
=> Fix wal ut error when serializing and deserializing

metrics/interface/src/main/java/org/apache/iotdb/metrics/config/MetricConfigDescriptor.java
When hot load configuration, there are NPE in metric module.
=> [IOTDB-5009] Fix NPE when hot load configuration

confignode/src/main/java/org/apache/iotdb/confignode/conf/ConfigNodeConfig.java, confignode/src/main/java/org/apache/iotdb/confignode/conf/ConfigNodeDescriptor.java, confignode/src/main/java/org/apache/iotdb/confignode/manager/node/NodeManager.java, consensus/src/main/java/org/apache/iotdb/consensus/ratis/RatisClient.java, consensus/src/main/java/org/apache/iotdb/consensus/ratis/RatisConsensus.java, node-commons/src/assembly/resources/conf/iotdb-common.properties
Fix some params that don't take effect.
=> [IOTDB-5014] fix ratis param

docs/UserGuide/Edge-Cloud-Collaboration/Sync-Tool.md, docs/UserGuide/Write-Data/TsFile-Tool.md, docs/zh/UserGuide/Edge-Cloud-Collaboration/Sync-Tool.md, docs/zh/UserGuide/Write-Data/TsFile-Tool.md, server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/AnalyzeVisitor.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/scheduler/load/LoadTsFileScheduler.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/statement/crud/LoadTsFileStatement.java, server/src/main/java/org/apache/iotdb/db/service/thrift/impl/ClientRPCServiceImpl.java, server/src/main/java/org/apache/iotdb/db/service/thrift/impl/TSServiceImpl.java, server/src/main/java/org/apache/iotdb/db/sync/SyncService.java, server/src/main/java/org/apache/iotdb/db/sync/receiver/load/TsFileLoader.java, server/src/main/java/org/apache/iotdb/db/sync/transport/server/ReceiverManager.java
problem:
auto register sg error in sync receiver.
OOM in load statement.
solution:
auto register sg only once when handshaking with receiver.
=> [IOTDB-4968] Auto register sg error in sync receiver and OOM

server/src/assembly/resources/conf/datanode-env.bat
=> [IOTDB-5022] Deleted the redundant Xlog:gc in datanode-env.bat

confignode/src/main/java/org/apache/iotdb/confignode/client/ConfigNodeRequestType.java, confignode/src/main/java/org/apache/iotdb/confignode/client/sync/SyncConfigNodeClientPool.java, confignode/src/main/java/org/apache/iotdb/confignode/manager/ConfigManager.java, confignode/src/main/java/org/apache/iotdb/confignode/manager/ConsensusManager.java, confignode/src/main/java/org/apache/iotdb/confignode/procedure/env/ConfigNodeProcedureEnv.java, confignode/src/main/java/org/apache/iotdb/confignode/procedure/env/DataNodeRemoveHandler.java, confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/node/AddConfigNodeProcedure.java, confignode/src/main/java/org/apache/iotdb/confignode/procedure/state/AddConfigNodeState.java, confignode/src/main/java/org/apache/iotdb/confignode/service/thrift/ConfigNodeRPCServiceProcessor.java, consensus/src/main/java/org/apache/iotdb/consensus/ratis/RatisConsensus.java, consensus/src/test/java/org/apache/iotdb/consensus/ratis/RatisConsensusTest.java, integration-test/src/main/java/org/apache/iotdb/it/env/AbstractEnv.java, server/src/main/java/org/apache/iotdb/db/client/ConfigNodeClient.java, thrift-confignode/src/main/thrift/confignode.thrift
=> [IOTDB-5008] Fix SHUTDOWN errors in ratis create peer (#8076)

integration-test/src/test/java/org/apache/iotdb/db/it/aligned/IoTDBGroupByLevelQueryIT.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/AnalyzeVisitor.java
=> [IOTDB-5018] Fix NPE when using uppercase function name in GROUP BY LEVEL

consensus/pom.xml, consensus/src/main/java/org/apache/iotdb/consensus/IStateMachine.java, consensus/src/main/java/org/apache/iotdb/consensus/ratis/ApplicationStateMachineProxy.java, consensus/src/main/java/org/apache/iotdb/consensus/ratis/SnapshotStorage.java, server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java, server/src/main/java/org/apache/iotdb/db/consensus/statemachine/DataRegionStateMachine.java
Support DataRegion Snapshot transfer
=> [IOTDB-4980] Ratis support DataRegion snapshot transfer

docs/UserGuide/Ecosystem-Integration/Grafana-Plugin.md, docs/zh/UserGuide/Ecosystem-Integration/Grafana-Plugin.md, grafana-plugin/pkg/plugin/plugin.go
Adjust background parameters according to the parameter rules of the latest rest interface
=> Grafana plugin request and return parameter adjustment

server/src/main/java/org/apache/iotdb/db/mpp/execution/memory/MemoryPool.java
There exists dead lock case in current MemoryPool implementation.
```java
Found one Java-level deadlock:
=============================
"pool-25-IoTDB-ClientRPC-Processor-50$20221123_152410_87128_5.0.0.0":
waiting to lock monitor 0x00007ff16c00ec78 (object 0x00000005cbe177d8, a org.apache.iotdb.db.mpp.execution.memory.MemoryPool),
which is held by "pool-25-IoTDB-ClientRPC-Processor-43$20221123_152410_87142_5.0.0.0"
"pool-25-IoTDB-ClientRPC-Processor-43$20221123_152410_87142_5.0.0.0":
waiting to lock monitor 0x00007ff16c010278 (object 0x00000005dc0ba760, a org.apache.iotdb.db.mpp.execution.exchange.SharedTsBlockQueue),
which is held by "pool-25-IoTDB-ClientRPC-Processor-22$20221123_152410_87114_5.0.0.0"
"pool-25-IoTDB-ClientRPC-Processor-22$20221123_152410_87114_5.0.0.0":
waiting to lock …
```
=> [IOTDB-5033] Fix deadlock in memory pool

consensus/pom.xml, consensus/src/main/java/org/apache/iotdb/consensus/IStateMachine.java, consensus/src/main/java/org/apache/iotdb/consensus/ratis/ApplicationStateMachineProxy.java, consensus/src/main/java/org/apache/iotdb/consensus/ratis/SnapshotStorage.java, server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java, server/src/main/java/org/apache/iotdb/db/consensus/statemachine/DataRegionStateMachine.java, server/src/main/java/org/apache/iotdb/db/engine/snapshot/SnapshotTaker.java
See [IOTDB-5010](https://issues.apache.org/jira/browse/IOTDB-5010).
This PR support snapshot transfer for ratis.
=> [IOTDB-5010] DataRegion StateMachine support for Ratis Snapshot

server/src/main/java/org/apache/iotdb/db/mpp/plan/scheduler/FragmentInstanceDispatcherImpl.java
Add dispatch node endpoint msg to error log
=> Add dispatch node endpoint msg to error log

server/src/main/java/org/apache/iotdb/db/mpp/plan/execution/memory/StatementMemorySourceVisitor.java
Before this PR:
After this fix:
=> [IOTDB-4877]Fix the issue that client get 305 when explain non-existing series

docs/UserGuide/Reference/Common-Config-Manual.md, docs/zh/UserGuide/Reference/Common-Config-Manual.md
Update common config manual about auth
=> [IOTDB-5046] Update common config manual about auth

docs/UserGuide/Reference/Common-Config-Manual.md, docs/UserGuide/Reference/DataNode-Config-Manual.md, docs/zh/UserGuide/Reference/Common-Config-Manual.md, docs/zh/UserGuide/Reference/DataNode-Config-Manual.md
Update config manual (hot-load part)
=> Update config manual (hot-load part)

confignode/src/assembly/resources/conf/iotdb-confignode.properties, confignode/src/main/java/org/apache/iotdb/confignode/persistence/metric/PartitionInfoMetrics.java, confignode/src/test/resources/confignode1conf/iotdb-confignode.properties, confignode/src/test/resources/confignode2conf/iotdb-confignode.properties, confignode/src/test/resources/confignode3conf/iotdb-confignode.properties, docs/UserGuide/Monitor-Alert/Metric-Tool.md, docs/zh/UserGuide/Monitor-Alert/Metric-Tool.md, metrics/interface/src/main/java/org/apache/iotdb/metrics/config/MetricConfig.java, metrics/interface/src/main/java/org/apache/iotdb/metrics/config/MetricConfigDescriptor.java, metrics/interface/src/main/java/org/apache/iotdb/metrics/metricsets/jvm/JvmClassLoaderMetrics.java, metrics/interface/src/main/java/org/apache/iotdb/metrics/metricsets/jvm/JvmCompileMetrics.java, metrics/interface/src/main/java/org/apache/iotdb/metrics/metricsets/jvm/JvmGcMetrics.java, metrics/interface/src/main/java/org/apache/iotdb/metrics/metricsets/jvm/JvmMemoryMetrics.java, metrics/interface/src/main/java/org/apache/iotdb/metrics/metricsets/jvm/JvmThreadMetrics.java, metrics/interface/src/main/java/org/apache/iotdb/metrics/metricsets/logback/LogbackMetrics.java, metrics/interface/src/main/java/org/apache/iotdb/metrics/metricsets/logback/MetricsTurboFilter.java, metrics/interface/src/test/java/org/apache/iotdb/metrics/config/MetricConfigTest.java, node-commons/src/main/java/org/apache/iotdb/commons/service/metric/enums/Metric.java, server/src/assembly/resources/conf/iotdb-datanode.properties, server/src/main/java/org/apache/iotdb/db/engine/storagegroup/DataRegionMetrics.java, server/src/main/java/org/apache/iotdb/db/service/metrics/SystemMetrics.java, server/src/main/java/org/apache/iotdb/db/service/thrift/impl/ClientRPCServiceImpl.java, server/src/main/java/org/apache/iotdb/db/service/thrift/impl/TSServiceImpl.java, server/src/test/resources/datanode1conf/iotdb-datanode.properties, server/src/test/resources/datanode2conf/iotdb-datanode.properties, server/src/test/resources/datanode3conf/iotdb-datanode.properties
1. Update metric doc
2. Remove `enablePerformanceStat` parameter
3. Unify some predefined metric name
=> [IOTDB-5053] Update Metric Doc and fix.

integration-test/src/test/java/org/apache/iotdb/db/it/groupby/IoTDBGroupByNaturalMonthIT.java, node-commons/src/main/java/org/apache/iotdb/commons/partition/DataPartitionQueryParam.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/AnalyzeVisitor.java, server/src/test/java/org/apache/iotdb/db/mpp/plan/analyze/AnalyzeTest.java, server/src/test/java/org/apache/iotdb/db/mpp/plan/analyze/QueryTimePartitionTest.java, tsfile/src/main/java/org/apache/iotdb/tsfile/read/common/TimeRange.java, tsfile/src/main/java/org/apache/iotdb/tsfile/read/filter/GroupByFilter.java, tsfile/src/main/java/org/apache/iotdb/tsfile/read/filter/TimeFilter.java, tsfile/src/main/java/org/apache/iotdb/tsfile/read/filter/basic/Filter.java, tsfile/src/main/java/org/apache/iotdb/tsfile/read/filter/operator/AndFilter.java, tsfile/src/main/java/org/apache/iotdb/tsfile/read/filter/operator/NotFilter.java, tsfile/src/main/java/org/apache/iotdb/tsfile/read/filter/operator/OrFilter.java
details can be seen in this [issue](https://issues.apache.org/jira/browse/IOTDB-4940)
=> [IOTDB-4940] Optimize PartitonFetch Process in query

server/src/main/java/org/apache/iotdb/db/mpp/plan/statement/metadata/ShowTriggersStatement.java
=> [IOTDB-5044] Correct the show triggers error message if the user doesn't have corresponding auth

confignode/src/main/java/org/apache/iotdb/confignode/conf/ConfigNodeConfig.java, confignode/src/main/java/org/apache/iotdb/confignode/conf/ConfigNodeDescriptor.java, confignode/src/main/java/org/apache/iotdb/confignode/conf/SystemPropertiesUtils.java, confignode/src/main/java/org/apache/iotdb/confignode/manager/ConfigManager.java, confignode/src/main/java/org/apache/iotdb/confignode/manager/node/NodeManager.java, confignode/src/main/java/org/apache/iotdb/confignode/manager/partition/PartitionManager.java, confignode/src/main/java/org/apache/iotdb/confignode/service/ConfigNode.java, docs/UserGuide/Reference/Common-Config-Manual.md, docs/zh/UserGuide/Reference/Common-Config-Manual.md, integration-test/src/main/java/org/apache/iotdb/it/env/MppConfig.java, integration-test/src/main/java/org/apache/iotdb/itbase/env/BaseConfig.java, integration-test/src/test/java/org/apache/iotdb/confignode/it/partition/IoTDBRegionGroupExtensionIT.java, node-commons/src/assembly/resources/conf/iotdb-common.properties
Updates:
1. Rename: series_partition_slot_num -> series_slot_num
2. Default value: data_region_group_num_per_database = 1
3. Default value: schema_region_per_data_node = 1.0(The system will use schema_replication_factor instead)
4. Add description: data_region_group_extension_policy
5. Add description: data_region_group_num_per_database
=> [IOTDB-4513] Improve load balance UserGuide

confignode/src/main/java/org/apache/iotdb/confignode/manager/ConfigManager.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/parser/ASTVisitor.java
=> Fix slot query bug; add optimization for getSchemaPartition

server/src/main/java/org/apache/iotdb/db/client/ConfigNodeClient.java
Query performance decrease caused by Thread.sleep(1000) in confignode client init.
=> Try to fix query performance

confignode/src/main/java/org/apache/iotdb/confignode/procedure/env/ConfigNodeProcedureEnv.java, confignode/src/main/java/org/apache/iotdb/confignode/procedure/state/CreateRegionGroupsState.java, consensus/src/main/java/org/apache/iotdb/consensus/common/request/IndexedConsensusRequest.java, consensus/src/main/java/org/apache/iotdb/consensus/iot/wal/ConsensusReqReader.java, node-commons/src/main/java/org/apache/iotdb/commons/service/ServiceType.java, server/src/main/java/org/apache/iotdb/db/engine/storagegroup/DataRegion.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/write/InsertNode.java, server/src/main/java/org/apache/iotdb/db/wal/WALManager.java, server/src/main/java/org/apache/iotdb/db/wal/buffer/WALEntry.java, server/src/main/java/org/apache/iotdb/db/wal/node/WALNode.java, thrift-iot-consensus/pom.xml
=> rename Multi Leader Conesensus to IoTConsensus for RPC service name

server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/write/InsertNode.java
When disable auto create schema and insert data directly, the timeseries schema may not exists and the dataType check shall fail with PathNotExistsException.
=> [To rel/1.0] [IOTDB-4972] Fix NPE caused by timeseries not exists when disable auto create schema

server/src/main/java/org/apache/iotdb/db/mpp/plan/scheduler/load/LoadTsFileDispatcherImpl.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/scheduler/load/LoadTsFileScheduler.java
problem:
TsFile take too much time to seal, and dn_connect_timeout_ms is not enough to get result.
solution:
print help message to user, suggest a longer dn_connect_timeout_ms is useful.
=> [To rel/1.0][IOTDB-5039] Add info when load tsfile error

server/src/main/java/org/apache/iotdb/db/mpp/plan/scheduler/load/LoadTsFileDispatcherImpl.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/scheduler/load/LoadTsFileScheduler.java
change logger.error to logger.warn
=> [To rel/1.0][IOTDB-5039] Change load log error to warn

server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/process/TagAggregationOperator.java
Fix IOTDB-5070.
In the previous implementation, the isBlock() method only blocks children that do not have cached data.
But for those children with cached data, when the cached data is exhausted, they will try to call next() to pull a new batch of data, which causes bugs.
=> [To rel/1.0] [IOTDB-5070] Fix wrong isBlocked() method implementation in TagAggregationOperator

server/src/main/java/org/apache/iotdb/db/mpp/plan/parser/StatementGenerator.java
There's no check of raw string of database name passed in Session, which may result in some internal execution error. 
Add the check when generating statement.
=> [To rel/1.0][IOTDB-4730] Database name check when passed in Session

integration-test/src/test/java/org/apache/iotdb/session/it/IoTDBSessionSimpleIT.java, node-commons/src/main/java/org/apache/iotdb/commons/path/PartialPath.java
Add IT for DB name check passed in by Session
=> [To rel/1.0][IOTDB-4730] Add IT for DB name check passed in by Session 

site/src/main/package.json
=> Fix site compile OOM

confignode/src/main/java/org/apache/iotdb/confignode/persistence/executor/ConfigPlanExecutor.java
=> Revert "Fix snapshot bug"

docs/UserGuide/Cluster/Cluster-Concept.md, docs/UserGuide/Cluster/Cluster-Setup.md, docs/zh/UserGuide/Cluster/Cluster-Concept.md, docs/zh/UserGuide/Cluster/Cluster-Setup.md
Update DataRegion usage on RatisConsensus
=> [To rel/1.0] Update doc on DataRegion using RatisConsensus

docs/UserGuide/Cluster/Cluster-Concept.md, docs/zh/UserGuide/Cluster/Cluster-Concept.md
Notice user that over half of ConfigNode is Running could the cluster work.
=> [To rel/1.0] Add confignode doc

.github/workflows/main-unix.yml
(cherry picked from commit 5510c79fbf45be87e658f30363b6b80bdd6da6bc)
=> [To rel/1.0] Fix linux CI

site/src/main/.vuepress/config.js, site/src/main/.vuepress/theme/components/Page.vue, site/src/main/package.json
=> Update Site,Add 'Edit this page on GitHub'

consensus/src/main/java/org/apache/iotdb/consensus/ratis/RatisConsensus.java, consensus/src/test/java/org/apache/iotdb/consensus/ratis/RatisConsensusTest.java
See https://issues.apache.org/jira/browse/IOTDB-5122.
=> [IOTDB-5122] forward exception when Ratis request failed

site/src/main/.vuepress/theme/components/Page.vue
change editLinkText size to 16px
12px：
change to16px：
<hr>
This PR has:
<hr>
=> Update Page.vue：change editLinkText size to 16px

confignode/src/main/java/org/apache/iotdb/confignode/conf/ConfigNodeConfig.java, confignode/src/main/java/org/apache/iotdb/confignode/conf/ConfigNodeDescriptor.java, confignode/src/main/java/org/apache/iotdb/confignode/manager/ConsensusManager.java, confignode/src/main/java/org/apache/iotdb/confignode/manager/node/NodeManager.java, server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java, server/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java, server/src/main/java/org/apache/iotdb/db/consensus/DataRegionConsensusImpl.java, server/src/main/java/org/apache/iotdb/db/consensus/SchemaRegionConsensusImpl.java
See https://issues.apache.org/jira/browse/IOTDB-5123
=> [IOTDB-5123] fix ratis disk control param mismatch

server/src/main/java/org/apache/iotdb/db/consensus/statemachine/DataRegionStateMachine.java, server/src/main/java/org/apache/iotdb/db/engine/StorageEngine.java, server/src/main/java/org/apache/iotdb/db/engine/load/LoadTsFileManager.java, server/src/main/java/org/apache/iotdb/db/engine/snapshot/SnapshotTaker.java, server/src/main/java/org/apache/iotdb/db/engine/storagegroup/DataRegion.java, server/src/main/java/org/apache/iotdb/db/engine/storagegroup/DataRegionMetrics.java, server/src/main/java/org/apache/iotdb/db/engine/storagegroup/IDataRegionForQuery.java, server/src/main/java/org/apache/iotdb/db/engine/storagegroup/TsFileProcessorInfo.java, server/src/main/java/org/apache/iotdb/db/engine/storagegroup/VirtualDataRegion.java, server/src/main/java/org/apache/iotdb/db/mpp/execution/driver/DataDriver.java, server/src/main/java/org/apache/iotdb/db/mpp/execution/driver/DataDriverContext.java, server/src/main/java/org/apache/iotdb/db/mpp/execution/fragment/FragmentInstanceManager.java, server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/process/last/AbstractUpdateLastCacheOperator.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/LocalExecutionPlanner.java, server/src/main/java/org/apache/iotdb/db/rescon/SystemInfo.java, server/src/main/java/org/apache/iotdb/db/sync/sender/manager/LocalSyncManager.java, server/src/main/java/org/apache/iotdb/db/sync/sender/pipe/TsFilePipe.java, server/src/main/java/org/apache/iotdb/db/sync/transport/client/SyncClientFactory.java, server/src/test/java/org/apache/iotdb/db/engine/snapshot/IoTDBSnapshotTest.java, server/src/test/java/org/apache/iotdb/db/engine/storagegroup/DataRegionTest.java
=> Add an interface for query engine which storage engine must provide

confignode/src/main/java/org/apache/iotdb/confignode/conf/ConfigNodeConfig.java, confignode/src/main/java/org/apache/iotdb/confignode/conf/ConfigNodeDescriptor.java, confignode/src/main/java/org/apache/iotdb/confignode/manager/ConsensusManager.java, confignode/src/main/java/org/apache/iotdb/confignode/manager/node/NodeManager.java, server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java, server/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java, server/src/main/java/org/apache/iotdb/db/consensus/DataRegionConsensusImpl.java, server/src/main/java/org/apache/iotdb/db/consensus/SchemaRegionConsensusImpl.java
https://github.com/apache/iotdb/pull/8339 exported to rel/1.0
=> [To rel/1.0] Fix disk control param error 

client-cpp/pom.xml, compile-tools/pom.xml, distribution/pom.xml, example/client-cpp-example/pom.xml, example/trigger/pom.xml, example/udf/pom.xml, grafana-connector/pom.xml, grafana-plugin/pom.xml, integration/pom.xml, jdbc/pom.xml, node-commons/src/main/java/org/apache/iotdb/commons/udf/service/UDFClassLoader.java, pom.xml, server/src/main/java/org/apache/iotdb/db/trigger/service/TriggerClassLoader.java
see https://apache-iotdb.feishu.cn/docx/YOGldZTBionIBIxCmKrcP6WNnzg?from=space_home_recent&pre_pathname=%2Fdrive%2Fhome%2F
=> replace FileUtils.listFiles in TriggerClassLoader and UDFClassLoader with Files.walk

node-commons/src/main/java/org/apache/iotdb/commons/udf/service/UDFClassLoader.java, server/src/main/java/org/apache/iotdb/db/trigger/service/TriggerClassLoader.java
see https://apache-iotdb.feishu.cn/docx/YOGldZTBionIBIxCmKrcP6WNnzg?from=space_home_recent&pre_pathname=%2Fdrive%2Fhome%2F
=> [To rel/1.0] replace FileUtils.listFiles in TriggerClassLoader and UDFClassLoader with Files.walk

client-cpp/pom.xml, compile-tools/pom.xml, distribution/pom.xml, example/client-cpp-example/pom.xml, example/trigger/pom.xml, example/udf/pom.xml, grafana-connector/pom.xml, grafana-plugin/pom.xml, integration-test/src/test/java/org/apache/iotdb/session/it/IoTDBSessionSyntaxConventionIT.java, integration/pom.xml, jdbc/pom.xml, node-commons/src/main/java/org/apache/iotdb/commons/utils/PathUtils.java, pom.xml, server/src/main/java/org/apache/iotdb/db/mpp/plan/parser/ASTVisitor.java, server/src/main/java/org/apache/iotdb/db/service/thrift/impl/ClientRPCServiceImpl.java, server/src/main/java/org/apache/iotdb/db/service/thrift/impl/TSServiceImpl.java
Previously we forget to update the checked measurements as node name like \`aa\` should be stored as aa.
=> [To rel/1.0] update nodenames if necessary in ClientRpcServiceImpl

thrift-influxdb/src/main/thrift/influxdb.thrift, thrift/src/main/thrift/client.thrift
see https://issues.apache.org/jira/browse/IOTDB-5136
=> [IOTDB-5136] NPE when use a null as username in session

jdbc/src/main/java/org/apache/iotdb/jdbc/IoTDBDatabaseMetadata.java
=> [IOTDB-5144] Fix ClassCastException

jdbc/src/main/java/org/apache/iotdb/jdbc/IoTDBDatabaseMetadata.java
ISSUE:https://github.com/apache/iotdb/issues/8377
=> [To rel/1.0] [IOTDB-5144] Fix ClassCastException

cluster/src/main/java/org/apache/iotdb/cluster/ClientMain.java, thrift-influxdb/src/main/thrift/influxdb.thrift, thrift/src/main/thrift/rpc.thrift
see https://issues.apache.org/jira/browse/IOTDB-5136
=> [To rel/0.13][IOTDB-5136] Set "username" to be required

docs/README.md
=> Revert "Delete README.md"

integration-test/src/test/java/org/apache/iotdb/db/it/aggregation/IoTDBAggregationIT.java, integration-test/src/test/java/org/apache/iotdb/db/it/groupby/IOTDBGroupByIT.java, node-commons/src/main/java/org/apache/iotdb/commons/partition/ExecutorType.java, node-commons/src/main/java/org/apache/iotdb/commons/partition/QueryExecutor.java, node-commons/src/main/java/org/apache/iotdb/commons/partition/StorageExecutor.java, server/src/main/java/org/apache/iotdb/db/mpp/execution/executor/RegionReadExecutor.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/Analysis.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/distribution/SimpleFragmentParallelPlanner.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/distribution/WriteFragmentParallelPlanner.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/FragmentInstance.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/scheduler/FragmentInstanceDispatcherImpl.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/scheduler/load/LoadTsFileScheduler.java, server/src/main/java/org/apache/iotdb/db/service/thrift/impl/DataNodeInternalRPCServiceImpl.java, server/src/test/java/org/apache/iotdb/db/mpp/plan/plan/FragmentInstanceSerdeTest.java, server/src/test/java/org/apache/iotdb/db/mpp/plan/scheduler/StandaloneSchedulerTest.java, thrift/src/main/thrift/datanode.thrift
cherry-pick from https://github.com/apache/iotdb/pull/8376
=> [IOTDB-5116] Fix wrong empty result set in aggregation query

docs/Community/Community-Powered By.md
Original issue link (https://github.com/apache/iotdb/issues/748) is moved to Discussion session (Link: https://github.com/apache/iotdb/discussions/4040)
This PR has:
=> Fixed Companies and Organizations Info Submit Link

library-udf/src/main/java/org/apache/iotdb/library/query/UDTFAggCWindow.java, library-udf/src/main/java/org/apache/iotdb/library/query/UDTFAggEvent.java, library-udf/src/main/java/org/apache/iotdb/library/query/UDTFAggMap.java, library-udf/src/main/java/org/apache/iotdb/library/query/UDTFAggRWindow.java, library-udf/src/main/java/org/apache/iotdb/library/query/UDTFClosedRange.java, library-udf/src/main/java/org/apache/iotdb/library/query/UDTFClosedValue.java, library-udf/src/main/java/org/apache/iotdb/library/query/UDTFMerge.java, library-udf/src/main/java/org/apache/iotdb/library/query/UDTFOpenRange.java, library-udf/src/main/java/org/apache/iotdb/library/query/UDTFOpenValue.java, library-udf/src/main/java/org/apache/iotdb/library/query/UDTFPatternCWindow.java, library-udf/src/main/java/org/apache/iotdb/library/query/UDTFPatternRWindow.java, library-udf/src/main/java/org/apache/iotdb/library/query/UDTFRelJoinDict.java, library-udf/src/main/java/org/apache/iotdb/library/query/UDTFRelJoinTemporal.java, library-udf/src/main/java/org/apache/iotdb/library/query/UDTFSample.java, library-udf/src/main/java/org/apache/iotdb/library/query/UDTFSimAlignMulti.java, library-udf/src/main/java/org/apache/iotdb/library/query/UDTFSimJoin.java
##Description
This is the baseline udf implementations to query time-series on various data types.
The benchmark project is github.com/thssdb/algebra for recurrence.
The baseline aims to obtain the time for loading and merging all data ahead of any filterings and optimizations.
###Content1 
Time-series queries:
(Q-S1) Selection contains 2 types: by (closed/open) time range and value, benchmarked by ClosedRange/Value and OpenRange/Value, input 1d time-series, out: 1d.
(Q-S2) Projection: ClosedRange with 2-d time-series in, 1d out.
(Q-S3) Merge: Merge 2 series with a pivot of concatenated ranges.
(Q-S4) Time equality join: ClosedRange, 2d in
(Q-S5) Aggregation by time-based sliding window: AggRWindow
(Q-A1) Sampling over time: Sample, fixed ranged window, taking 1 tuple.
(Q-A2) Generalized …
=> [research/algebra] To include UDF functions for queries on different data types

integration-test/src/test/java/org/apache/iotdb/db/it/IoTDBFilterIT.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/AnalyzeVisitor.java
=> [IOTDB-5161] Add output type check for WHERE & HAVING clause

thrift-influxdb/src/main/thrift/influxdb.thrift, thrift/src/main/thrift/client.thrift
see https://issues.apache.org/jira/browse/IOTDB-5136
=> [To rel/1.0][IOTDB-5136] Fix NPE when use a null as username in session

integration-test/src/test/java/org/apache/iotdb/db/it/IoTDBFilterIT.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/AnalyzeVisitor.java
(cherry picked from commit 14d4cc1d7d2d94c0bcde4f811d2071538539ab24)
=> [To rel/1.0] [IOTDB-5161] Add output type check for WHERE & HAVING clause (#8381)

confignode/src/assembly/resources/sbin/stop-confignode.bat
=> [IOTDB-5170] stop-confignode.bat, datanode will be closed at the same time

cluster/src/main/java/org/apache/iotdb/cluster/query/LocalQueryExecutor.java, server/src/main/java/org/apache/iotdb/db/metadata/logfile/MLogWriter.java, server/src/main/java/org/apache/iotdb/db/qp/physical/sys/AppendTemplatePlan.java, server/src/main/java/org/apache/iotdb/db/qp/physical/sys/CreateAlignedTimeSeriesPlan.java, server/src/main/java/org/apache/iotdb/db/qp/physical/sys/CreateMultiTimeSeriesPlan.java, server/src/main/java/org/apache/iotdb/db/qp/physical/sys/CreateTemplatePlan.java, server/src/main/java/org/apache/iotdb/db/qp/physical/sys/CreateTimeSeriesPlan.java, server/src/main/java/org/apache/iotdb/db/service/thrift/impl/TSServiceImpl.java, session/src/main/java/org/apache/iotdb/session/Session.java
CompressionType.values()[x]  -> CompressionType.deserialize(x)
compressor.ordinal() -> compressor.serialize()
=> [To rel/0.13][IOTDB-5184] Fix CompressionType ArrayIndexOutOfBounds

docs/UserGuide/Monitor-Alert/Metric-Tool.md, docs/zh/UserGuide/Monitor-Alert/Metric-Tool.md
See: https://issues.apache.org/jira/browse/IOTDB-5186
=> [IOTDB-5186] Update metric doc

docs/UserGuide/Monitor-Alert/Metric-Tool.md, docs/zh/UserGuide/Monitor-Alert/Metric-Tool.md
https://issues.apache.org/jira/browse/IOTDB-5186
=> [IOTDB-5186][To rel/1.0] update metric doc

server/src/main/java/org/apache/iotdb/db/query/control/SessionManager.java
https://issues.apache.org/jira/browse/IOTDB-5157
=> [To rel/0.13][IOTDB-5157] BugFix "nValid ID for ZoneOffset, invalid format:" 

server/src/main/java/org/apache/iotdb/db/qp/physical/sys/AppendTemplatePlan.java, session/src/main/java/org/apache/iotdb/session/Session.java
CompressionType.values()[x] -> CompressionType.deserialize(x)
compressor.ordinal() -> compressor.serialize()
=> [IOTDB-5184]Fix CompressionType ArrayIndexOutOfBounds

server/src/assembly/resources/sbin/start-server.sh
Problem description:
Solved pictures:
1） 2)   3)  4)    is already verified.
<hr>
This PR has:
<hr>
=> [To rel/0.13] [IOTDB-5128] Perfected the -p option in start-server.sh

confignode/src/main/java/org/apache/iotdb/confignode/manager/ConsensusManager.java, consensus/src/main/java/org/apache/iotdb/consensus/config/RatisConfig.java, consensus/src/main/java/org/apache/iotdb/consensus/ratis/RatisClient.java, consensus/src/main/java/org/apache/iotdb/consensus/ratis/RatisConsensus.java, consensus/src/test/java/org/apache/iotdb/consensus/ratis/RatisConsensusTest.java, server/src/main/java/org/apache/iotdb/db/consensus/DataRegionConsensusImpl.java, server/src/main/java/org/apache/iotdb/db/consensus/SchemaRegionConsensusImpl.java
see https://issues.apache.org/jira/browse/IOTDB-5191.
The config class name of RatisConsensus is the same with RatisConsensus Main class. It may lead to misunderstandings.
=> [IOTDB-5191] Rename RatisConfig.RatisConsensus

docs/UserGuide/Cluster/Cluster-Setup.md, docs/UserGuide/QuickStart/ClusterQuickStart.md, docs/zh/UserGuide/Cluster/Cluster-Setup.md, docs/zh/UserGuide/QuickStart/ClusterQuickStart.md, site/src/main/.vuepress/config.js
Updates:
1. Refactor the Cluster-Setup doc.
2. Create the Cluster-Quick-Start doc.
You can see [this doc](https://apache-iotdb.feishu.cn/docx/WlYGdiSGboZvWMxvHmpcHQuPnNb) to get more details about this refactor.
=> [IOTDB-5159] Refactor the structure of Cluster Deploy DOC

.github/workflows/main-unix.yml, .github/workflows/main-win.yml, Jenkinsfile, integration-test/pom.xml, integration-test/src/test/java/org/apache/iotdb/libudf/it/anomaly/AnomalyIT.java, integration-test/src/test/java/org/apache/iotdb/libudf/it/dmatch/DMatchIT.java, integration-test/src/test/java/org/apache/iotdb/libudf/it/dprofile/DProfileIT.java, integration-test/src/test/java/org/apache/iotdb/libudf/it/dquality/DQualityIT.java, integration-test/src/test/java/org/apache/iotdb/libudf/it/drepair/DRepairIT.java, integration-test/src/test/java/org/apache/iotdb/libudf/it/frequency/FrequencyIT.java, integration-test/src/test/java/org/apache/iotdb/libudf/it/series/SeriesIT.java, integration-test/src/test/java/org/apache/iotdb/libudf/it/string/StringIT.java, library-udf/pom.xml
=> [To rel/1.0][IOTDB-5190] Move Library-udf IT to integration-test

consensus/src/main/java/org/apache/iotdb/consensus/iot/IoTConsensus.java, consensus/src/main/java/org/apache/iotdb/consensus/iot/IoTConsensusServerImpl.java, consensus/src/test/java/org/apache/iotdb/consensus/iot/ReplicateTest.java, consensus/src/test/java/org/apache/iotdb/consensus/iot/StabilityTest.java, consensus/src/test/java/org/apache/iotdb/consensus/iot/util/TestStateMachine.java, server/src/main/java/org/apache/iotdb/db/service/IoTDBShutdownHook.java
see [jira5185](https://issues.apache.org/jira/browse/IOTDB-5185)
=> [To rel/1.0][IOTDB-5185] The old snapshot is not deleted after “ take snapshot ” is complete 

consensus/src/main/java/org/apache/iotdb/consensus/iot/IoTConsensus.java, consensus/src/main/java/org/apache/iotdb/consensus/iot/IoTConsensusServerImpl.java, consensus/src/test/java/org/apache/iotdb/consensus/iot/ReplicateTest.java, consensus/src/test/java/org/apache/iotdb/consensus/iot/StabilityTest.java, consensus/src/test/java/org/apache/iotdb/consensus/iot/util/TestStateMachine.java, server/src/main/java/org/apache/iotdb/db/service/IoTDBShutdownHook.java
see [jira5185](https://issues.apache.org/jira/browse/IOTDB-5185)
=> [IOTDB-5185] The old snapshot is not deleted after “ take snapshot ” is complete

integration-test/src/test/java/org/apache/iotdb/db/it/udf/IoTDBUDFM4IT.java, node-commons/src/main/java/org/apache/iotdb/commons/udf/builtin/UDTFM4.java
=> [To rel/1.0] [IOTDB-5119] fix bug that M4 throws exception when the window is empty

node-commons/src/main/java/org/apache/iotdb/commons/partition/ExecutorType.java, node-commons/src/main/java/org/apache/iotdb/commons/partition/StorageExecutor.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/distribution/WriteFragmentParallelPlanner.java
cherry-pick https://github.com/apache/iotdb/pull/8440
=> [IOTDB-5199]fix NPE in StorageExector inLoading process

antlr/src/main/antlr4/org/apache/iotdb/db/qp/sql/IoTDBSqlParser.g4
now show regions supports database sql.
=> [IOTDB-5202] Show regions support database sql

antlr/src/main/antlr4/org/apache/iotdb/db/qp/sql/IoTDBSqlParser.g4
now show regions supports database sql.
=> [To rel/1.0][IOTDB-5202] Show regions support database sql

integration-test/src/test/java/org/apache/iotdb/db/it/groupby/IOTDBGroupByIT.java, integration-test/src/test/java/org/apache/iotdb/db/it/query/IoTDBNullOperandIT.java
(cherry picked from commit 616af5240bcb7cb5edeccb7ce3d44f9bdc591a7d)
=> [To rel/1.0] Fix IOTDBGroupByIT & IoTDBNullOperandIT

server/src/assembly/resources/sbin/start-server.sh
Changed -b to -d, in accordance with 1.0 settings
<hr>
This PR has:
<hr>
=> [To rel/0.13] Update start-server.sh, change -b to -d

server/src/main/java/org/apache/iotdb/db/metadata/schemaregion/SchemaRegionMemoryImpl.java, server/src/main/java/org/apache/iotdb/db/metadata/schemaregion/SchemaRegionSchemaFileImpl.java
=> [To rel/1.0][IOTDB-5061] Add initialize state check when create snapshot

server/src/main/java/org/apache/iotdb/db/conf/IoTDBStartCheck.java, server/src/main/java/org/apache/iotdb/db/conf/directories/DirectoryChecker.java
Check data directories cross-disk under RatisConsensus
=> [IOTDB-5223] Check data directories cross-disk under RatisConsensus

confignode/src/main/java/org/apache/iotdb/confignode/consensus/response/ConfigurationResp.java, confignode/src/main/java/org/apache/iotdb/confignode/consensus/response/DataNodeRegisterResp.java, confignode/src/main/java/org/apache/iotdb/confignode/manager/ConfigManager.java, confignode/src/main/java/org/apache/iotdb/confignode/manager/IManager.java, confignode/src/main/java/org/apache/iotdb/confignode/manager/node/NodeManager.java, confignode/src/main/java/org/apache/iotdb/confignode/service/thrift/ConfigNodeRPCServiceProcessor.java, server/src/main/java/org/apache/iotdb/db/client/ConfigNodeClient.java, server/src/main/java/org/apache/iotdb/db/conf/IoTDBStartCheck.java, server/src/main/java/org/apache/iotdb/db/conf/directories/DirectoryChecker.java, server/src/main/java/org/apache/iotdb/db/service/DataNode.java, server/src/main/java/org/apache/iotdb/db/service/DataNodeServerCommandLine.java, thrift-confignode/src/main/thrift/confignode.thrift
Cherry pick from #8441 and #8469
=> [To rel/1.0][IOTDB-5201][IOTDB-5223] Extract DataNode getConfig and add check for cross-disk directories 

metrics/interface/src/main/java/org/apache/iotdb/metrics/config/MetricConfigDescriptor.java, metrics/interface/src/test/java/org/apache/iotdb/metrics/config/MetricConfigTest.java
See: https://issues.apache.org/jira/browse/IOTDB-5222
=> [IOTDB-5222] Fix the load of metric related configuration

server/src/main/java/org/apache/iotdb/db/engine/compaction/CompactionUtils.java, server/src/test/java/org/apache/iotdb/db/engine/compaction/cross/CrossSpaceCompactionWithFastPerformerValidationTest.java
Throw the 'tsfiles overlap with each other'  exception wrongly after compaction that don't actually have.
**Reason**
When part of TsFileResource is degraded from deviceTimeIndex to FileTimeIndex, an error will be reported.
**Solution**
Skip validating files with file time index.
=> [IOTDB-5165]Failed to pass compaction validation

server/src/main/java/org/apache/iotdb/db/engine/compaction/CompactionUtils.java, server/src/test/java/org/apache/iotdb/db/engine/compaction/cross/CrossSpaceCompactionWithFastPerformerValidationTest.java
Throw the 'tsfiles overlap with each other' exception wrongly after compaction that don't actually have.
**Reason**
When part of TsFileResource is degraded from deviceTimeIndex to FileTimeIndex, an error will be reported.
**Solution**
Skip validating files with file time index.
=> [To rel/1.0][IOTDB-5165]Failed to pass compaction validation 

docs/UserGuide/Monitor-Alert/Metric-Tool.md, docs/zh/UserGuide/Monitor-Alert/Metric-Tool.md, node-commons/src/main/java/org/apache/iotdb/commons/service/metric/enums/Metric.java, node-commons/src/main/java/org/apache/iotdb/commons/service/metric/enums/Tag.java, server/src/main/java/org/apache/iotdb/db/engine/flush/MemTableFlushTask.java
Add the metric of flush point in important level with internal reporter support
=> [IOTDB-5173][To rel/1.0] Add statistic of flush point

metrics/interface/src/main/java/org/apache/iotdb/metrics/config/MetricConfigDescriptor.java, metrics/interface/src/test/java/org/apache/iotdb/metrics/config/MetricConfigTest.java
=> [To rel/1.0] [IOTDB-5222] Fix the load of metric related configuration (#8466)

docs/UserGuide/Monitor-Alert/Metric-Tool.md, docs/zh/UserGuide/Monitor-Alert/Metric-Tool.md, node-commons/src/main/java/org/apache/iotdb/commons/service/metric/enums/Metric.java, node-commons/src/main/java/org/apache/iotdb/commons/service/metric/enums/Tag.java, server/src/main/java/org/apache/iotdb/db/engine/flush/MemTableFlushTask.java
Add the metric of flush point in important level with internal reporter support
=> [IOTDB-5173] Add statistic of flush point

antlr/src/main/antlr4/org/apache/iotdb/db/qp/sql/IoTDBSqlParser.g4, server/src/main/java/org/apache/iotdb/db/mpp/plan/parser/ASTVisitor.java
In this PR, I remove deprecated syntax in CQ.
=> [IOTDB-5212] Remove deprecated syntax in CQ

client-py/iotdb/utils/IoTDBRpcDataSet.py
=> [IOTDB-5229] Fix python ITs

docs/UserGuide/Maintenance-Tools/Metric-Tool.md, docs/zh/UserGuide/Maintenance-Tools/Metric-Tool.md
Make metric related doc consistent with implementation
=> [IOTDB-5173][To rel/0.13] Make metric related doc consistent with implementation

server/src/main/java/org/apache/iotdb/db/service/thrift/impl/ClientRPCServiceImpl.java
=> [IOTDB-5233] Correct the message of unsupported thrift interface of schema template

server/src/main/java/org/apache/iotdb/db/service/thrift/impl/ClientRPCServiceImpl.java
see [IOTDB-5233](https://issues.apache.org/jira/browse/IOTDB-5233)
=> [To rel/1.0][IOTDB-5233] Correct the message of unsupported thrift interface of schema template

client-py/iotdb/Session.py, client-py/tests/test_delete_data.py
=> [To rel/0.13][IOTDB-5236] Fix DeleteData Python API cannot work

integration-test/src/test/java/org/apache/iotdb/confignode/it/IoTDBClusterRegionLeaderBalancingIT.java
Remove SchemaRegionGroup(which uses Ratis consensus protocol) check
=> Simplify RegionLeaderBalancingIT

server/src/main/java/org/apache/iotdb/db/metadata/mtree/snapshot/MemMTreeSnapshotUtil.java, server/src/main/java/org/apache/iotdb/db/metadata/plan/schemaregion/impl/SchemaRegionPlanFactory.java, server/src/test/java/org/apache/iotdb/db/metadata/schemaRegion/SchemaRegionBasicTest.java
see [IOTDB-5240](https://issues.apache.org/jira/browse/IOTDB-5240)
=> [To rel/1.0][IOTDB-5240] Add template id to schema region snapshot

client-py/iotdb/Session.py, client-py/tests/test_delete_data.py
=> [IOTDB-5236] Fix DeleteData Python API cannot work

server/src/main/java/org/apache/iotdb/db/metadata/schemaregion/ISchemaRegion.java, server/src/test/java/org/apache/iotdb/db/metadata/schemaRegion/SchemaRegionBasicTest.java
UT related to delete timeseries.
* Add `@Deprecated` annotation for useless interface
* Add javadoc
* Fix logic bug in testDeleteTimeseries
=> [IOTDB-5239] UT related to delete timeseries

server/src/main/java/org/apache/iotdb/db/metadata/utils/MetaUtils.java, server/src/test/java/org/apache/iotdb/db/metadata/MetaUtilsTest.java
Some of the tests in the original SchemaBasicTest were only for MetaUtils, now they have been migrated to MetaUtilsTest.
=> [IOTDB-5242] UT related to MetaUtils

docs/UserGuide/Monitor-Alert/Metric-Tool.md, docs/zh/UserGuide/Monitor-Alert/Metric-Tool.md, server/src/main/java/org/apache/iotdb/db/engine/flush/MemTableFlushTask.java
Upgrade the level of flush metric from important to core
=> [IOTDB-5173] Upgrade the level of flush metric from important to core

schema-engine-rocksdb/src/main/java/org/apache/iotdb/db/metadata/schemaregion/rocksdb/RSchemaRegion.java, schema-engine-tag/src/main/java/org/apache/iotdb/db/metadata/tagSchemaRegion/TagSchemaRegion.java, server/src/main/java/org/apache/iotdb/db/metadata/LocalSchemaProcessor.java, server/src/main/java/org/apache/iotdb/db/metadata/schemaregion/ISchemaRegion.java, server/src/main/java/org/apache/iotdb/db/metadata/schemaregion/SchemaRegionMemoryImpl.java, server/src/main/java/org/apache/iotdb/db/metadata/schemaregion/SchemaRegionSchemaFileImpl.java, server/src/main/java/org/apache/iotdb/db/metadata/tag/TagManager.java, server/src/main/java/org/apache/iotdb/db/metadata/visitor/SchemaExecutionVisitor.java, server/src/test/java/org/apache/iotdb/db/metadata/schemaRegion/SchemaRegionAliasAndTagTest.java, server/src/test/java/org/apache/iotdb/db/metadata/schemaRegion/SchemaRegionTestUtil.java
Add UT related to alias and tags and attributes interface in `ISchemaRegion`.
=> [IOTDB-5238] UT related to alias and tags and attributes

server/src/main/java/org/apache/iotdb/db/mpp/plan/parser/ASTVisitor.java
In this PR, I modify the CQ syntax compatibility prompt.
=> [To rel/1.0] [IOTDB-5212] Modify the CQ syntax compatibility prompt

server/src/assembly/resources/conf/iotdb-engine.properties, server/src/main/java/org/apache/iotdb/db/audit/AuditLogOperation.java, server/src/main/java/org/apache/iotdb/db/audit/AuditLogStorage.java, server/src/main/java/org/apache/iotdb/db/audit/AuditLogger.java, server/src/main/java/org/apache/iotdb/db/auth/authorizer/BasicAuthorizer.java, server/src/main/java/org/apache/iotdb/db/auth/role/BasicRoleManager.java, server/src/main/java/org/apache/iotdb/db/auth/user/BasicUserManager.java, server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java, server/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java, server/src/main/java/org/apache/iotdb/db/protocol/mqtt/PublishHandler.java, server/src/main/java/org/apache/iotdb/db/protocol/rest/impl/RestApiServiceImpl.java, server/src/main/java/org/apache/iotdb/db/qp/executor/PlanExecutor.java, server/src/main/java/org/apache/iotdb/db/qp/physical/PhysicalPlan.java, server/src/main/java/org/apache/iotdb/db/query/control/SessionManager.java, server/src/main/java/org/apache/iotdb/db/service/basic/ServiceProvider.java, server/src/main/java/org/apache/iotdb/db/service/thrift/impl/TSServiceImpl.java, server/src/test/java/org/apache/iotdb/db/qp/physical/InsertTabletMultiPlanTest.java
1. add master switch control;
2. add output logs to both the IOTDB and LOGGER
3. nonQuery log on PlanExecutor,query log on TsServiceIml
=> [To rel/0.13][IOTDB-3662] upgrade audit log

docs/UserGuide/Cluster/Deployment-Recommendation.md, docs/zh/UserGuide/Cluster/Deployment-Recommendation.md
see [IOTDB-5234](https://issues.apache.org/jira/browse/IOTDB-5234)
=> [To rel/1.0][IOTDB-5234] Add schema config recommendation when upgrading from 0.13

consensus/src/main/java/org/apache/iotdb/consensus/config/IoTConsensusConfig.java, consensus/src/main/java/org/apache/iotdb/consensus/iot/client/DispatchLogHandler.java, consensus/src/main/java/org/apache/iotdb/consensus/iot/logdispatcher/Batch.java, consensus/src/main/java/org/apache/iotdb/consensus/iot/logdispatcher/LogDispatcher.java, consensus/src/main/java/org/apache/iotdb/consensus/iot/logdispatcher/LogDispatcherThreadMetrics.java, consensus/src/main/java/org/apache/iotdb/consensus/iot/logdispatcher/SyncStatus.java, consensus/src/main/java/org/apache/iotdb/consensus/iot/service/IoTConsensusRPCService.java, consensus/src/main/java/org/apache/iotdb/consensus/iot/service/IoTConsensusRPCServiceProcessor.java, consensus/src/test/java/org/apache/iotdb/consensus/iot/StabilityTest.java, consensus/src/test/java/org/apache/iotdb/consensus/iot/logdispatcher/SyncStatusTest.java, thrift-iot-consensus/src/main/thrift/iotconsensus.thrift
cherry-pick [pull/8534](https://github.com/apache/iotdb/pull/8534)
=> [To rel/1.0][IOTDB-5246] Enhance IoTConsensus field name 

consensus/src/main/java/org/apache/iotdb/consensus/config/IoTConsensusConfig.java, consensus/src/main/java/org/apache/iotdb/consensus/iot/client/DispatchLogHandler.java, consensus/src/main/java/org/apache/iotdb/consensus/iot/logdispatcher/Batch.java, consensus/src/main/java/org/apache/iotdb/consensus/iot/logdispatcher/LogDispatcher.java, consensus/src/main/java/org/apache/iotdb/consensus/iot/logdispatcher/LogDispatcherThreadMetrics.java, consensus/src/main/java/org/apache/iotdb/consensus/iot/logdispatcher/SyncStatus.java, consensus/src/main/java/org/apache/iotdb/consensus/iot/service/IoTConsensusRPCService.java, consensus/src/main/java/org/apache/iotdb/consensus/iot/service/IoTConsensusRPCServiceProcessor.java, consensus/src/test/java/org/apache/iotdb/consensus/iot/StabilityTest.java, consensus/src/test/java/org/apache/iotdb/consensus/iot/logdispatcher/SyncStatusTest.java, thrift-iot-consensus/src/main/thrift/iotconsensus.thrift
see [jira5246](https://issues.apache.org/jira/browse/IOTDB-5246)
=> [IOTDB-5246] Enhance IoTConsensus field name

server/src/main/java/org/apache/iotdb/db/metadata/schemaregion/SchemaRegionSchemaFileImpl.java, server/src/test/java/org/apache/iotdb/db/metadata/schemaRegion/SchemaRegionAliasAndTagTest.java
Leaf node should be pinned when creating if there are tags or attributes.
=> [IOTDB-5247] Fix drop tags or attributes throw NPE in SchemaFile

docs/UserGuide/Maintenance-Tools/Metric-Tool.md, docs/zh/UserGuide/Maintenance-Tools/Metric-Tool.md, server/src/main/java/org/apache/iotdb/db/metadata/MManager.java, server/src/main/java/org/apache/iotdb/db/metadata/MManagerMetrics.java
Add the following metric
1. devices using template
2. schema memory usage
3. schema memory remainning
=> [To rel/0.13][IOTDB-5232] Add schema memory metric

docs/UserGuide/Monitor-Alert/Metric-Tool.md, docs/zh/UserGuide/Monitor-Alert/Metric-Tool.md, server/src/main/java/org/apache/iotdb/db/metadata/rescon/SchemaResourceManager.java, server/src/main/java/org/apache/iotdb/db/metadata/rescon/SchemaResourceManagerMetrics.java
Add the following metric
1. schema region memory usage
2. schema region memory remaining
=> [To rel/1.0][IOTDB-5232] Add schema memory metric

docs/UserGuide/Monitor-Alert/Metric-Tool.md, docs/zh/UserGuide/Monitor-Alert/Metric-Tool.md, server/src/main/java/org/apache/iotdb/db/metadata/rescon/SchemaResourceManager.java, server/src/main/java/org/apache/iotdb/db/metadata/rescon/SchemaResourceManagerMetrics.java
Add the following metric
1. schema region memory usage
2. schema region memory remaining
=> [IOTDB-5232] Add schema memory metric

server/src/main/java/org/apache/iotdb/db/protocol/mqtt/MPPPublishHandler.java, server/src/main/java/org/apache/iotdb/db/protocol/mqtt/Message.java
see https://issues.apache.org/jira/browse/IOTDB-5249
=> [IOTDB-5249] Add interface to set datatype when users customize the payload formatter of mqtt

server/src/main/java/org/apache/iotdb/db/protocol/mqtt/MPPPublishHandler.java, server/src/main/java/org/apache/iotdb/db/protocol/mqtt/Message.java
see https://issues.apache.org/jira/browse/IOTDB-5249
=> [To rel/1.0][IOTDB-5249] Add interface to set datatype when users customize the payload formatter of mqtt

docs/UserGuide/Monitor-Alert/Metric-Tool.md, docs/zh/UserGuide/Monitor-Alert/Metric-Tool.md, server/src/main/java/org/apache/iotdb/db/engine/flush/MemTableFlushTask.java
=> [To rel/1.0][IOTDB-5173] Upgrade the metric of flush from important to core (#8524)

metrics/interface/src/main/java/org/apache/iotdb/metrics/reporter/iotdb/InternalIoTDBReporter.java, metrics/interface/src/main/java/org/apache/iotdb/metrics/reporter/iotdb/MemoryInternalIoTDBReporter.java, metrics/interface/src/main/java/org/apache/iotdb/metrics/reporter/iotdb/SessionIoTDBReporter.java, metrics/interface/src/main/java/org/apache/iotdb/metrics/reporter/prometheus/PrometheusReporter.java, metrics/micrometer-metrics/src/main/java/org/apache/iotdb/metrics/micrometer/reporter/MicrometerJmxReporter.java, node-commons/src/main/java/org/apache/iotdb/commons/service/metric/MetricService.java, server/src/main/java/org/apache/iotdb/db/service/metrics/IoTDBInternalReporter.java
1. Add the handle of exception when metric reporter fails
2. Specify the code of start/stop process
=> [IOTDB-5231]Add the handle of exception when metric reporter failed to start

node-commons/src/assembly/resources/conf/iotdb-common.properties, server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
(cherry picked from commit 394ecc0fe6b3801942be8441728689d5be23c57b)
=> [To rel/1.0][IOTDB-5256] Modify the default value of iot_consensus_cache_window_time_in_ms

confignode/src/test/java/org/apache/iotdb/confignode/consensus/request/ConfigPhysicalPlanSerDeTest.java, confignode/src/test/java/org/apache/iotdb/confignode/persistence/ClusterSchemaInfoTest.java, confignode/src/test/java/org/apache/iotdb/confignode/persistence/TemplateTableTest.java, schema-engine-rocksdb/src/main/java/org/apache/iotdb/db/metadata/schemaregion/rocksdb/mnode/RMNode.java, server/src/main/java/org/apache/iotdb/db/metadata/idtable/entry/InsertMeasurementMNode.java, server/src/main/java/org/apache/iotdb/db/metadata/mnode/IMNode.java, server/src/main/java/org/apache/iotdb/db/metadata/mnode/InternalMNode.java, server/src/main/java/org/apache/iotdb/db/metadata/mnode/MeasurementMNode.java, server/src/main/java/org/apache/iotdb/db/metadata/mtree/MTreeBelowSGCachedImpl.java, server/src/main/java/org/apache/iotdb/db/metadata/mtree/snapshot/MemMTreeSnapshotUtil.java, server/src/main/java/org/apache/iotdb/db/metadata/mtree/store/disk/schemafile/RecordUtils.java, server/src/main/java/org/apache/iotdb/db/metadata/mtree/store/disk/schemafile/SchemaFile.java, server/src/main/java/org/apache/iotdb/db/metadata/mtree/traverser/collector/MeasurementCollector.java, server/src/main/java/org/apache/iotdb/db/metadata/plan/schemaregion/impl/SchemaRegionPlanFactory.java, server/src/main/java/org/apache/iotdb/db/metadata/template/ClusterTemplateManager.java, server/src/main/java/org/apache/iotdb/db/metadata/template/Template.java, server/src/test/java/org/apache/iotdb/db/metadata/schemaRegion/SchemaRegionManagementTest.java, server/src/test/java/org/apache/iotdb/db/metadata/schemaRegion/SchemaRegionTemplateTest.java
1. Refactor the constructor of Template to decuple it with CreateSchemaTemplateStatement
2. Add template id to schema region memory mode snapshot
3. Add template id to schema region schema_file mode snapshot
1. refine the activation process
2. fix the snapshot load process
3. fix the show timeseries without templateMap
4. add template id to schema file
=> [IOTDB-5240] Add template id to schema region snapshot

metrics/interface/src/main/java/org/apache/iotdb/metrics/reporter/iotdb/InternalIoTDBReporter.java, metrics/interface/src/main/java/org/apache/iotdb/metrics/reporter/iotdb/MemoryInternalIoTDBReporter.java, metrics/interface/src/main/java/org/apache/iotdb/metrics/reporter/iotdb/SessionIoTDBReporter.java, metrics/interface/src/main/java/org/apache/iotdb/metrics/reporter/prometheus/PrometheusReporter.java, metrics/micrometer-metrics/src/main/java/org/apache/iotdb/metrics/micrometer/reporter/MicrometerJmxReporter.java, node-commons/src/main/java/org/apache/iotdb/commons/service/metric/MetricService.java, server/src/main/java/org/apache/iotdb/db/service/metrics/IoTDBInternalReporter.java
(cherry picked from commit 7b92bd295e1fd9afdd86b162d28080fe9c6a6a13)
=> [To rel/1.0][IOTDB-5231]Add the handle of exception when metric reporter failed to start

consensus/src/main/java/org/apache/iotdb/consensus/config/IoTConsensusConfig.java, consensus/src/main/java/org/apache/iotdb/consensus/iot/client/IoTConsensusClientPool.java, server/src/main/java/org/apache/iotdb/db/consensus/DataRegionConsensusImpl.java
=> [IOTDB-5261]support modify the dn_max_connection_for_internal_servic of IoTConsensus

server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/LocalExecutionPlanner.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/MemoryDistributionCalculator.java
details could be found at: https://apache-iotdb.feishu.cn/docx/O5XCdvEHPoDdtNxFHlXcV6xlnoh
=> [IOTDB-5117] Fix some issues in MemoryDistributionCalculator

server/src/main/java/org/apache/iotdb/db/metadata/mtree/IMTreeBelowSG.java, server/src/main/java/org/apache/iotdb/db/metadata/mtree/MTreeBelowSGCachedImpl.java, server/src/main/java/org/apache/iotdb/db/metadata/mtree/MTreeBelowSGMemoryImpl.java, server/src/main/java/org/apache/iotdb/db/metadata/schemaregion/SchemaRegionMemoryImpl.java, server/src/main/java/org/apache/iotdb/db/metadata/schemaregion/SchemaRegionSchemaFileImpl.java, server/src/test/java/org/apache/iotdb/db/metadata/mtree/MTreeBelowSGTest.java
Eliminate all useless and test only code in SchemaRegion and MTree, and make sure all the rest code serve cluster features.
=> Eliminate useless code in SchemaRegion and MTree

server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/LocalExecutionPlanner.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/MemoryDistributionCalculator.java
details could be found at: https://apache-iotdb.feishu.cn/docx/O5XCdvEHPoDdtNxFHlXcV6xlnoh
=> [To rel/1.0] [IOTDB-5117] Fix some issues in MemoryDistributionCalculator

confignode/src/main/java/org/apache/iotdb/confignode/manager/ConsensusManager.java, confignode/src/main/java/org/apache/iotdb/confignode/manager/node/heartbeat/ConfigNodeHeartbeatCache.java, confignode/src/main/java/org/apache/iotdb/confignode/persistence/schema/ClusterSchemaInfo.java, confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/node/AddConfigNodeProcedure.java, confignode/src/main/java/org/apache/iotdb/confignode/service/ConfigNode.java
=> [IOTDB-5284] Fix some code smells

confignode/src/main/java/org/apache/iotdb/confignode/manager/ConsensusManager.java, confignode/src/main/java/org/apache/iotdb/confignode/manager/node/heartbeat/ConfigNodeHeartbeatCache.java, confignode/src/main/java/org/apache/iotdb/confignode/persistence/schema/ClusterSchemaInfo.java, confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/node/AddConfigNodeProcedure.java, confignode/src/main/java/org/apache/iotdb/confignode/service/ConfigNode.java
* fix some code smells
cherry-pick from master. https://github.com/apache/iotdb/pull/8612
=> [To rel/1.0][IOTDB-5284] Fix some code smells (#8612)

tsfile/src/main/java/org/apache/iotdb/tsfile/read/common/block/column/NullColumn.java, tsfile/src/test/java/org/apache/iotdb/tsfile/read/common/ColumnTest.java
=> modify implement of Null Column

jdbc/src/main/java/org/apache/iotdb/jdbc/IoTDBDatabaseMetadata.java
The dbeaver can connect normally after the PR.
And the dbeaver can show the device and column now.
Can be accessed through:
[iotdb-jdbc-1.0.1-SNAPSHOT-jar-with-dependencies.zip](https://github.com/apache/iotdb/files/10306840/iotdb-jdbc-1.0.1-SNAPSHOT-jar-with-dependencies.zip)
=> [To rel/1.0][IOTDB-5278] fix connection problem of dbeaver and supports more functions

jdbc/src/main/java/org/apache/iotdb/jdbc/IoTDBDatabaseMetadata.java
The dbeaver can connect normally after the PR.
And the dbeaver can show the device and column now.
Can be accessed through: 
[iotdb-jdbc-1.0.1-SNAPSHOT-jar-with-dependencies.zip](https://github.com/apache/iotdb/files/10306840/iotdb-jdbc-1.0.1-SNAPSHOT-jar-with-dependencies.zip)
=> [IOTDB-5278] fix connection problem of dbeaver and supports more functions

integration-test/src/test/java/org/apache/iotdb/confignode/it/cluster/IoTDBClusterNodeErrorStartUpIT.java
=> [To rel/1.0][IOTDB-5297] Add maxRetryTimes for IoTDBClusterNodeErrorStartUpIT to avoid infinite loop

grafana-connector/src/main/java/org/apache/iotdb/web/grafana/interceptor/LoginInterceptor.java
=> [To rel/0.13] fix grafana-connector bug

grafana-connector/src/main/java/org/apache/iotdb/web/grafana/interceptor/LoginInterceptor.java
=> fix grafana-connector bug

grafana-connector/src/main/java/org/apache/iotdb/web/grafana/interceptor/LoginInterceptor.java
=> [To rel/1.0] fix grafana-connector bug

docs/UserGuide/Operators-Functions/Overview.md, docs/UserGuide/Operators-Functions/User-Defined-Function.md, docs/zh/UserGuide/Operators-Functions/Overview.md, docs/zh/UserGuide/Operators-Functions/User-Defined-Function.md
1. 更清晰的UDF注册流程；
2. 配置项及内部目录不再出现在注册流程里，配置项统一到配置项章节
=> modify doc of register UDF

.github/workflows/client-cpp.yml, client-cpp/pom.xml, client-cpp/src/main/Session.cpp, client-cpp/src/main/Session.h, client-cpp/src/test/CMakeLists.txt, client-cpp/src/test/cpp/sessionIT.cpp
1. Fix cpp sdk bug, see #8555 
2. enable cpp sdk IT
=> Fix cpp SDK bug & enable cpp IT

server/src/main/java/org/apache/iotdb/db/mpp/plan/execution/QueryExecution.java
cherry pick from https://github.com/apache/iotdb/pull/8687
redirect writing only if the redirectEndPoint is not the current node
when statusCode == TSStatusCode.SUCCESS_STATUS, a 'no detailed failure reason in QueryStateMachine' message was set in TSStatus
=> [To rel/1.0] Optimize write redirection logic (#8687)

site/src/main/.vuepress/config.js
Add 0.13 Export-Schema document to website config
=> [IOTDB-5133] Add 0.13 Export-Schema document to website config

server/src/main/java/org/apache/iotdb/db/engine/storagegroup/TsFileProcessorInfo.java, server/src/main/java/org/apache/iotdb/db/engine/storagegroup/TsFileProcessorInfoMetrics.java
https://issues.apache.org/jira/browse/IOTDB-5253
=> [IOTDB-5253] Fix chunkMetadata mem metric

server/src/main/java/org/apache/iotdb/db/engine/storagegroup/TsFileProcessorInfo.java, server/src/main/java/org/apache/iotdb/db/engine/storagegroup/TsFileProcessorInfoMetrics.java
https://issues.apache.org/jira/browse/IOTDB-5253
=> [To rel/1.0][IOTDB-5253] Fix chunkMetadata mem metric

server/src/main/java/org/apache/iotdb/db/engine/storagegroup/TsFileProcessorInfo.java, server/src/main/java/org/apache/iotdb/db/engine/storagegroup/TsFileProcessorInfoMetrics.java
https://issues.apache.org/jira/browse/IOTDB-5253
=> [To rel/0.13][IOTDB-5253] Fix chunkMetadata mem metric

docs/UserGuide/Operate-Metadata/Template.md, docs/UserGuide/Operate-Metadata/Timeseries.md, docs/zh/UserGuide/Operate-Metadata/Template.md, docs/zh/UserGuide/Operate-Metadata/Timeseries.md
Update SQL result example for deadband column
=> [To rel/0.13] Update SQL result example for deadband column

docs/UserGuide/Operate-Metadata/Template.md, docs/UserGuide/Operate-Metadata/Timeseries.md, docs/zh/UserGuide/Operate-Metadata/Template.md, docs/zh/UserGuide/Operate-Metadata/Timeseries.md
Add deadband column to User-Guide SQL examples.
=> [To rel/1.0] Add deadband column to User-Guide SQL examples

docs/UserGuide/Operate-Metadata/Template.md, docs/UserGuide/Operate-Metadata/Timeseries.md, docs/zh/UserGuide/Operate-Metadata/Template.md, docs/zh/UserGuide/Operate-Metadata/Timeseries.md
Add deadband column to User-Guide SQL examples
=> Add deadband columns to User-Guide SQL examples

node-commons/src/main/java/org/apache/iotdb/commons/schema/tree/AbstractTreeVisitor.java, node-commons/src/main/java/org/apache/iotdb/commons/schema/tree/AbstractTreeVisitorWithLimitOffset.java
Exception handler for AbstractTreeVisitor
=> [IOTDB-5329] Exception handler for AbstractTreeVisitor

confignode/src/main/java/org/apache/iotdb/confignode/conf/SystemPropertiesUtils.java, integration-test/src/main/java/org/apache/iotdb/it/utils/TsFileGenerator.java, integration-test/src/test/java/org/apache/iotdb/confignode/it/IoTDBConfigNodeSnapshotIT.java, integration-test/src/test/java/org/apache/iotdb/confignode/it/cluster/IoTDBClusterRestartIT.java, integration-test/src/test/java/org/apache/iotdb/confignode/it/partition/IoTDBPartitionDurableIT.java, integration-test/src/test/java/org/apache/iotdb/confignode/it/partition/IoTDBPartitionGetterIT.java, integration-test/src/test/java/org/apache/iotdb/confignode/it/partition/IoTDBPartitionInheritPolicyIT.java, integration-test/src/test/java/org/apache/iotdb/db/it/IOTDBLoadTsFileIT.java, node-commons/src/main/java/org/apache/iotdb/commons/conf/IoTDBConstant.java, server/src/main/java/org/apache/iotdb/db/client/ConfigNodeInfo.java, server/src/main/java/org/apache/iotdb/db/conf/IoTDBStartCheck.java, server/src/main/java/org/apache/iotdb/db/service/DataNode.java
If time partition interval is changed, error log is like below:
=> [IOTDB-5285] TimePartition may be error when restarting with different time partition configuration

server/src/main/java/org/apache/iotdb/db/metadata/utils/MetaUtils.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/OperatorTreeGenerator.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/distribution/SourceRewriter.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/process/last/LastQueryNode.java
(cherry picked from commit bc887772cdf0a0fe4a091bab221b2ff36271d73b)
=> [To rel/1.0] [IOTDB-5245] Fix bug in last query

confignode/src/main/java/org/apache/iotdb/confignode/client/async/handlers/rpc/AbstractAsyncRPCHandler.java, confignode/src/main/java/org/apache/iotdb/confignode/consensus/statemachine/ConfigNodeRegionStateMachine.java, confignode/src/main/java/org/apache/iotdb/confignode/exception/ConfigNodeException.java, confignode/src/main/java/org/apache/iotdb/confignode/manager/ClusterSchemaManager.java, confignode/src/main/java/org/apache/iotdb/confignode/manager/cq/CQScheduleTask.java, confignode/src/main/java/org/apache/iotdb/confignode/manager/load/balancer/region/CopySetRegionGroupAllocator.java, confignode/src/main/java/org/apache/iotdb/confignode/manager/node/heartbeat/BaseNodeCache.java, confignode/src/main/java/org/apache/iotdb/confignode/persistence/cq/CQInfo.java
- cherry-pick from master. 
- https://github.com/apache/iotdb/pull/8647
=> [To rel/1.0][IOTDB-5284] Fix some code smells

server/src/main/java/org/apache/iotdb/db/wal/recover/file/UnsealedTsFileRecoverPerformer.java
=> [IOTDB-5346] Fix log error in MemtableFlushTask when recovering

server/src/main/java/org/apache/iotdb/db/writelog/recover/TsFileRecoverPerformer.java
=> [To rel/0.13][IOTDB-5346] Fix log error in MemtableFlushTask when recovering

server/src/main/java/org/apache/iotdb/db/wal/recover/file/UnsealedTsFileRecoverPerformer.java
=> [To rel/1.0][IOTDB-5346] Fix log error in MemtableFlushTask when recovering

server/src/main/java/org/apache/iotdb/db/wal/utils/WALFileUtils.java, server/src/test/java/org/apache/iotdb/db/wal/utils/WALFileUtilsTest.java
=> fix the wal comment

antlr/src/main/antlr4/org/apache/iotdb/db/qp/sql/IoTDBSqlParser.g4, antlr/src/main/antlr4/org/apache/iotdb/db/qp/sql/SqlLexer.g4, docs/UserGuide/Cluster/Cluster-Maintenance.md, docs/zh/UserGuide/Cluster/Cluster-Maintenance.md, server/src/main/java/org/apache/iotdb/db/mpp/plan/execution/config/executor/ClusterConfigTaskExecutor.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/parser/ASTVisitor.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/statement/metadata/ShowRegionStatement.java
now we support new command `SHOW (DATA|SCHEMA)? REGIONS (OF DATABASE <sg1,sg2,...>)? (ON NODEID <id1,id2,...>)?` to show the region on specified node.
=> [IOTDB-5077] Support new command formats in  SHOW REGIONS

integration-test/src/test/java/org/apache/iotdb/db/it/IoTDBFloatPrecisionIT.java, node-commons/src/assembly/resources/conf/iotdb-common.properties, server/src/main/java/org/apache/iotdb/db/mpp/execution/memory/MemoryPool.java, server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/AbstractOperator.java, server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/process/AbstractProcessOperator.java, server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/process/join/RowBasedTimeJoinOperator.java, server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/process/join/TimeJoinOperator.java, server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/source/AbstractDataSourceOperator.java, server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/source/AbstractSeriesAggregationScanOperator.java, server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/source/AbstractSourceOperator.java, server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/source/AlignedSeriesScanOperator.java, server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/source/SeriesScanOperator.java, server/src/test/java/org/apache/iotdb/db/mpp/execution/exchange/SinkHandleTest.java, server/src/test/java/org/apache/iotdb/db/mpp/execution/operator/OperatorMemoryTest.java, tsfile/src/main/java/org/apache/iotdb/tsfile/common/conf/TSFileConfig.java, tsfile/src/main/java/org/apache/iotdb/tsfile/read/common/block/TsBlock.java, tsfile/src/main/java/org/apache/iotdb/tsfile/read/common/block/TsBlockBuilder.java, tsfile/src/main/java/org/apache/iotdb/tsfile/read/common/block/column/BinaryColumn.java, tsfile/src/main/java/org/apache/iotdb/tsfile/read/common/block/column/BooleanColumn.java, tsfile/src/main/java/org/apache/iotdb/tsfile/read/common/block/column/Column.java, tsfile/src/main/java/org/apache/iotdb/tsfile/read/common/block/column/DoubleColumn.java, tsfile/src/main/java/org/apache/iotdb/tsfile/read/common/block/column/FloatColumn.java, tsfile/src/main/java/org/apache/iotdb/tsfile/read/common/block/column/IntColumn.java, tsfile/src/main/java/org/apache/iotdb/tsfile/read/common/block/column/LongColumn.java, tsfile/src/main/java/org/apache/iotdb/tsfile/read/common/block/column/NullColumn.java, tsfile/src/main/java/org/apache/iotdb/tsfile/read/common/block/column/RunLengthEncodedColumn.java, tsfile/src/main/java/org/apache/iotdb/tsfile/read/common/block/column/TimeColumn.java
=> [To rel/1.0] [IOTDB-5308] Limit the output tsblock's size of each operator[Part1]

docs/UserGuide/Cluster/Cluster-Maintenance.md, docs/zh/UserGuide/Cluster/Cluster-Maintenance.md
Add more detailed NodeStatus definition on user docs.
=> [IOTDB-4497] Improve NodeStatus definition

docs/UserGuide/Monitor-Alert/Apache-IoTDB-ConfigNode-Dashboard.json, docs/UserGuide/Monitor-Alert/Apache-IoTDB-DataNode-Dashboard.json, metrics/dropwizard-metrics/src/main/java/org/apache/iotdb/metrics/dropwizard/type/DropwizardHistogramSnapshot.java, metrics/interface/src/main/java/org/apache/iotdb/metrics/impl/DoNothingHistogramSnapshot.java, metrics/interface/src/main/java/org/apache/iotdb/metrics/type/HistogramSnapshot.java, metrics/micrometer-metrics/src/main/java/org/apache/iotdb/metrics/micrometer/type/MicrometerTimer.java, metrics/micrometer-metrics/src/main/java/org/apache/iotdb/metrics/micrometer/type/MicrometerTimerHistogramSnapshot.java, server/src/test/java/org/apache/iotdb/db/metric/MetricServiceTest.java
See JIRA: https://issues.apache.org/jira/browse/IOTDB-5379
=> [IOTDB-5379] Fix the unit of Prometheus timer metric values

docs/UserGuide/Monitor-Alert/Apache-IoTDB-ConfigNode-Dashboard.json, docs/UserGuide/Monitor-Alert/Apache-IoTDB-DataNode-Dashboard.json, metrics/dropwizard-metrics/src/main/java/org/apache/iotdb/metrics/dropwizard/type/DropwizardHistogramSnapshot.java, metrics/interface/src/main/java/org/apache/iotdb/metrics/impl/DoNothingHistogramSnapshot.java, metrics/interface/src/main/java/org/apache/iotdb/metrics/type/HistogramSnapshot.java, metrics/micrometer-metrics/src/main/java/org/apache/iotdb/metrics/micrometer/type/MicrometerTimer.java, metrics/micrometer-metrics/src/main/java/org/apache/iotdb/metrics/micrometer/type/MicrometerTimerHistogramSnapshot.java, server/src/test/java/org/apache/iotdb/db/metric/MetricServiceTest.java
=> [To rel/1.0][IOTDB-5379] Fix the unit of Prometheus timer metric values

docs/UserGuide/Reference/Common-Config-Manual.md, docs/zh/UserGuide/Reference/Common-Config-Manual.md, node-commons/src/assembly/resources/conf/iotdb-common.properties, server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java, server/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java, server/src/main/java/org/apache/iotdb/db/engine/compaction/CompactionTaskManager.java, server/src/main/java/org/apache/iotdb/db/engine/compaction/cross/utils/AlignedSeriesCompactionExecutor.java, server/src/main/java/org/apache/iotdb/db/engine/compaction/cross/utils/NonAlignedSeriesCompactionExecutor.java, server/src/main/java/org/apache/iotdb/db/engine/compaction/inner/utils/AlignedSeriesCompactionExecutor.java, server/src/main/java/org/apache/iotdb/db/engine/compaction/inner/utils/SingleSeriesCompactionExecutor.java, server/src/main/java/org/apache/iotdb/db/engine/compaction/writer/AbstractCompactionWriter.java, server/src/test/java/org/apache/iotdb/db/engine/compaction/utils/CompactionConfigRestorer.java
Revert the commit 5126711 because this commit made the performance change regarding write/read
=> Revert the commit 5126711

docs/UserGuide/Reference/Common-Config-Manual.md, docs/zh/UserGuide/Reference/Common-Config-Manual.md, node-commons/src/assembly/resources/conf/iotdb-common.properties, server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java, server/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java, server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/utils/executor/fast/AlignedSeriesCompactionExecutor.java, server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/utils/executor/fast/NonAlignedSeriesCompactionExecutor.java, server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/utils/executor/readchunk/AlignedSeriesCompactionExecutor.java, server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/utils/executor/readchunk/SingleSeriesCompactionExecutor.java, server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/utils/writer/AbstractCompactionWriter.java, server/src/main/java/org/apache/iotdb/db/engine/compaction/schedule/CompactionTaskManager.java, server/src/test/java/org/apache/iotdb/db/engine/compaction/utils/CompactionConfigRestorer.java
revert commit 5126711 because this commit decrease the performance of read/write
=> Revert commit 5126711 on master

docs/UserGuide/Reference/Config-Manual.md, docs/zh/UserGuide/Reference/Config-Manual.md, server/src/assembly/resources/conf/iotdb-engine.properties, server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java, server/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java, server/src/main/java/org/apache/iotdb/db/engine/compaction/CompactionTaskManager.java, server/src/main/java/org/apache/iotdb/db/engine/compaction/CompactionUtils.java, server/src/main/java/org/apache/iotdb/db/engine/compaction/cross/rewrite/task/SubCompactionTask.java, server/src/main/java/org/apache/iotdb/db/engine/compaction/inner/utils/AlignedSeriesCompactionExecutor.java, server/src/main/java/org/apache/iotdb/db/engine/compaction/inner/utils/SingleSeriesCompactionExecutor.java, server/src/main/java/org/apache/iotdb/db/engine/compaction/writer/AbstractCompactionWriter.java, server/src/test/java/org/apache/iotdb/db/engine/compaction/utils/CompactionConfigRestorer.java
This reverts commit c5d91a8c284eff1674b42fa049a2b3beec1df616.
=> Revert "[IOTDB-5209] Limit the read rate of compaction execution"

docs/UserGuide/Reference/Common-Config-Manual.md, docs/zh/UserGuide/Reference/Common-Config-Manual.md, node-commons/src/assembly/resources/conf/iotdb-common.properties, server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java, server/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java, server/src/main/java/org/apache/iotdb/db/engine/compaction/CompactionTaskManager.java, server/src/main/java/org/apache/iotdb/db/engine/compaction/cross/utils/AlignedSeriesCompactionExecutor.java, server/src/main/java/org/apache/iotdb/db/engine/compaction/cross/utils/NonAlignedSeriesCompactionExecutor.java, server/src/main/java/org/apache/iotdb/db/engine/compaction/inner/utils/AlignedSeriesCompactionExecutor.java, server/src/main/java/org/apache/iotdb/db/engine/compaction/inner/utils/SingleSeriesCompactionExecutor.java, server/src/main/java/org/apache/iotdb/db/engine/compaction/writer/AbstractCompactionWriter.java, server/src/test/java/org/apache/iotdb/db/engine/compaction/utils/CompactionConfigRestorer.java
As we talked, we need to ensure all commits in `rc-x.y.z` exists in `rel/x.y`. Let's do the merge back to `1.0`.
1. Check out a new branch (`1.0.1_to_1.0`) based on `rc/1.0.1`
2. Rebase branch `rel/1.0` from the newly created branch
3. Merge the newly created branch to `rel/1.0`
=> Merge back new commits from 1.0.1 to 1.0 to keep that 1.0 includes all commits of 1.0.1

integration-test/src/main/java/org/apache/iotdb/it/env/cluster/AbstractEnv.java, integration-test/src/main/java/org/apache/iotdb/it/env/cluster/AbstractNodeWrapper.java, integration-test/src/main/java/org/apache/iotdb/it/env/cluster/ConfigNodeWrapper.java, integration-test/src/main/java/org/apache/iotdb/it/env/cluster/DataNodeWrapper.java, integration-test/src/main/java/org/apache/iotdb/it/env/cluster/EnvUtils.java, integration-test/src/main/java/org/apache/iotdb/it/env/cluster/MppClusterConfig.java, integration-test/src/main/java/org/apache/iotdb/it/env/cluster/MppJVMConfig.java, integration-test/src/main/java/org/apache/iotdb/it/env/remote/RemoteClusterConfig.java, integration-test/src/main/java/org/apache/iotdb/it/env/remote/RemoteJVMConfig.java, integration-test/src/main/java/org/apache/iotdb/itbase/env/ClusterConfig.java, integration-test/src/main/java/org/apache/iotdb/itbase/env/JVMConfig.java, integration-test/src/test/java/org/apache/iotdb/confignode/it/cluster/IoTDBClusterNodeErrorStartUpIT.java, integration-test/src/test/java/org/apache/iotdb/confignode/it/cluster/IoTDBClusterRestartIT.java
See JIRA: https://issues.apache.org/jira/browse/IOTDB-5387
=> [IOTDB-5387] Refine IT: Make JVM parameters mutable easily

confignode/src/main/java/org/apache/iotdb/confignode/conf/ConfigNodeConstant.java, confignode/src/main/java/org/apache/iotdb/confignode/manager/ProcedureManager.java, confignode/src/main/java/org/apache/iotdb/confignode/procedure/env/DataNodeRemoveHandler.java, confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/statemachine/RegionMigrateProcedure.java
1、Renaming
2、Bug fix
<hr>
This PR has:
<hr>
=> [IOTDB-5328] Rename "REMOVE_DATANODE_PROCESS" in MIGRATE_REGION_PROCEDURE to "REGION_MIGRATE_PROCESS"

integration-test/src/main/java/org/apache/iotdb/it/utils/TsFileGenerator.java, integration-test/src/test/java/org/apache/iotdb/confignode/it/IoTDBConfigNodeSnapshotIT.java, integration-test/src/test/java/org/apache/iotdb/confignode/it/cluster/IoTDBClusterRestartIT.java, integration-test/src/test/java/org/apache/iotdb/confignode/it/partition/IoTDBPartitionDurableIT.java, integration-test/src/test/java/org/apache/iotdb/confignode/it/partition/IoTDBPartitionGetterIT.java, integration-test/src/test/java/org/apache/iotdb/confignode/it/partition/IoTDBPartitionInheritPolicyIT.java, integration-test/src/test/java/org/apache/iotdb/db/it/IOTDBLoadTsFileIT.java, server/src/main/java/org/apache/iotdb/db/client/ConfigNodeInfo.java, server/src/main/java/org/apache/iotdb/db/conf/IoTDBStartCheck.java, server/src/main/java/org/apache/iotdb/db/service/DataNode.java
=> [To rel/1.0][IOTDB-5285] TimePartition may be error when restarting with different time partition configuration

integration-test/src/test/java/org/apache/iotdb/confignode/it/partition/IoTDBPartitionGetterIT.java
A case in current testGetSlots test is often failed due to the different number of CPU cores on the test machine. Therefore this is a small commit to fix this bug.
=> Fix testGetSlots bug

docs/UserGuide/Maintenance-Tools/Maintenance-Command.md, docs/UserGuide/Operators-Functions/User-Defined-Function.md, docs/zh/UserGuide/Maintenance-Tools/Maintenance-Command.md
KillQuery and Show Queries are not supported in rel/1.0, but has implemented in master.
=> modify doc of KillQuery & ShowQueries as not supported

.github/workflows/client-cpp.yml, .github/workflows/client-go.yml, .github/workflows/client-python.yml, .github/workflows/cluster-it-1c1d.yml, .github/workflows/cluster-it-1c3d.yml, .github/workflows/grafana-plugin.yml, .github/workflows/influxdb-protocol.yml, .github/workflows/main-unix.yml, .github/workflows/main-win.yml, integration-test/src/main/java/org/apache/iotdb/it/utils/TsFileGenerator.java, integration-test/src/test/java/org/apache/iotdb/confignode/it/IoTDBConfigNodeSnapshotIT.java, integration-test/src/test/java/org/apache/iotdb/confignode/it/cluster/IoTDBClusterRestartIT.java, integration-test/src/test/java/org/apache/iotdb/confignode/it/partition/IoTDBPartitionDurableIT.java, integration-test/src/test/java/org/apache/iotdb/confignode/it/partition/IoTDBPartitionGetterIT.java, integration-test/src/test/java/org/apache/iotdb/confignode/it/partition/IoTDBPartitionInheritPolicyIT.java, integration-test/src/test/java/org/apache/iotdb/db/it/IOTDBLoadTsFileIT.java, server/src/main/java/org/apache/iotdb/db/client/ConfigNodeInfo.java, server/src/main/java/org/apache/iotdb/db/conf/IoTDBStartCheck.java, server/src/main/java/org/apache/iotdb/db/service/DataNode.java
Cherry-pick commit `78a8528` and `c06147e`.
=> [IOTDB-5285][IOTDB-5389]Cherry-pick commit `78a8528` and `c06147e` from rel/1.0 to rc/1.0.1

consensus/src/main/java/org/apache/iotdb/consensus/iot/IoTConsensusServerImpl.java, consensus/src/test/java/org/apache/iotdb/consensus/iot/StabilityTest.java
=> [IOTDB-5345] Use the logical clock to identify the snapshot version of IoTConsensus

metrics/interface/src/main/java/org/apache/iotdb/metrics/AbstractMetricService.java
https://issues.apache.org/jira/browse/IOTDB-5404
=> [IOTDB-5404] Fix concurrency problem of `metricSets` in `AbstractMetricService`

metrics/interface/src/main/java/org/apache/iotdb/metrics/AbstractMetricService.java
=> [To rel/1.0][IOTDB-5404] Fix concurrency problem of metricSets in AbstractMetricService

docs/UserGuide/API/Programming-MQTT.md, docs/zh/UserGuide/API/Programming-MQTT.md
Fixed the wrong class path in MQTT documents.
=> Fix mqtt docs

integration-test/src/main/java/org/apache/iotdb/it/env/cluster/AbstractEnv.java, integration-test/src/main/java/org/apache/iotdb/it/env/cluster/AbstractNodeWrapper.java, integration-test/src/main/java/org/apache/iotdb/it/env/remote/RemoteServerEnv.java, integration-test/src/main/java/org/apache/iotdb/itbase/env/BaseEnv.java, integration-test/src/main/java/org/apache/iotdb/itbase/env/BaseNodeWrapper.java, integration-test/src/test/java/org/apache/iotdb/confignode/it/cluster/IoTDBClusterNodeErrorStartUpIT.java, integration-test/src/test/java/org/apache/iotdb/confignode/it/load/IoTDBClusterRegionLeaderBalancingIT.java, integration-test/src/test/java/org/apache/iotdb/confignode/it/partition/IoTDBPartitionDurableIT.java
See JIRA: https://issues.apache.org/jira/browse/IOTDB-5403
=> [IOTDB-5403] Refine IT: Add ensureNodeStatus to test status after starting or stopping

docs/UserGuide/Ecosystem-Integration/Flink-IoTDB.md, docs/zh/UserGuide/Ecosystem-Integration/Flink-IoTDB.md, example/flink/src/main/java/org/apache/iotdb/flink/FlinkIoTDBSink.java
=> Fix flink docs

confignode/src/main/java/org/apache/iotdb/confignode/manager/ClusterSchemaManager.java, consensus/src/main/java/org/apache/iotdb/consensus/iot/IoTConsensusServerImpl.java, consensus/src/test/java/org/apache/iotdb/consensus/iot/StabilityTest.java
- cherry-pick from master.
- https://github.com/apache/iotdb/pull/8807
=> [To rel/1.0][IOTDB-5345] Use the logical clock to identify the snapshot version of IoTConsensus

Jenkinsfile
https://ci-builds.apache.org/job/IoTDB/job/IoTDB-pip-new/job/master/30/console
sonar report requires jdk11
=> Fix jenkins sonar report error

docs/UserGuide/Monitor-Alert/Metric-Tool.md, docs/zh/UserGuide/Monitor-Alert/Metric-Tool.md
https://issues.apache.org/jira/browse/IOTDB-5289
=> [IOTDB-5289] Add Metric Doc about ConfigNode Dashboard

server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/process/TagAggregationOperator.java
=> [To rel/1.0][IOTDB-5417] Fix missing hasNext() before next() in TagAggregationOperator

server/src/main/java/org/apache/iotdb/db/service/metrics/predefined/FileMetrics.java, server/src/main/java/org/apache/iotdb/db/utils/FileUtils.java
Too many.mods files may indicate abnormal service deletion, so add.mods file count metrics
=> [To rel/0.13][IOTDB-5407] metrics for .mods file count

integration-test/src/test/java/org/apache/iotdb/db/it/IoTDBMultiDeviceIT.java, node-commons/src/main/java/org/apache/iotdb/commons/conf/CommonConfig.java, server/src/main/java/org/apache/iotdb/db/mpp/execution/memory/MemoryPool.java, server/src/test/java/org/apache/iotdb/db/mpp/execution/exchange/SourceHandleTest.java
See JIRA: https://issues.apache.org/jira/browse/IOTDB-5424
This PR also includes a logging enhancement, and IT fixes.
=> [IOTDB-5424] Fix FI memory allocation limit calculation

cli/pom.xml, confignode/pom.xml, consensus/pom.xml, influxdb-protocol/pom.xml, jdbc/pom.xml, metrics/pom.xml, node-commons/pom.xml, server/pom.xml, server/src/test/java/org/apache/iotdb/db/security/encrypt/MessageDigestEncryptTest.java, service-rpc/pom.xml, session/pom.xml, tsfile/pom.xml
See JIRA: https://issues.apache.org/jira/browse/IOTDB-5423
=> [IOTDB-5423] Disable reusing same JVM and processing in random order in tests

server/src/test/java/org/apache/iotdb/db/auth/authorizer/OpenIdAuthorizerTest.java, server/src/test/resources/iotdb-datanode.properties
The issue caused by OpenIdAuthorizerTest didn't call EnvironmentUtils.envSetUp() before tests.
=> Fix files with unapporved license error after running OpenIdAuthorizerTest

confignode/src/main/java/org/apache/iotdb/confignode/persistence/executor/ConfigPlanExecutor.java
Cherry pick of https://github.com/apache/iotdb/pull/8470
=> [To rel/1.0][IOTDB-5153] Fix dead lock in confignode 

consensus/src/main/java/org/apache/iotdb/consensus/exception/RatisRequestFailedException.java
cherry pick of https://github.com/apache/iotdb/pull/8449
=> [To rel/1.0][IOTDB-5061] Add message in RatisRequestFailed

server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
cherry pick of https://github.com/apache/iotdb/pull/8489
=> [To rel/1.0][IOTDB-5176] Change ratis snapshot dir with datadir 

.github/workflows/main-win.yml
Remove unnecessary hadoop environment.
=> fix win CI

server/src/main/java/org/apache/iotdb/db/mpp/execution/schedule/DriverScheduler.java
cp from this [pr](https://github.com/apache/iotdb/pull/8908)
=> [To rel/1.0] [IOTDB-5431] Fix concurrent bug caused by using synchronizedSet() in DriverScheduler

server/src/main/java/org/apache/iotdb/db/wal/buffer/WALBuffer.java
1. use serialized size to control fsync.
2. use timeout poll method to increase batch size.
=> [IOTDB-5338] WAL buffer flush threshold optimaztion

server/src/main/java/org/apache/iotdb/db/mpp/execution/exchange/MPPDataExchangeManager.java
cp from this [pr](https://github.com/apache/iotdb/pull/8915)
=> [To rel/1.0] [IOTDB-5434] Fix occasional timeout error in CI

node-commons/src/main/java/org/apache/iotdb/commons/client/ClientManager.java, server/src/main/java/org/apache/iotdb/db/client/ConfigNodeClient.java, server/src/main/java/org/apache/iotdb/db/service/DataNode.java, server/src/main/java/org/apache/iotdb/db/service/DataNodeServerCommandLine.java, server/src/main/java/org/apache/iotdb/db/service/RegionMigrateService.java
cherry-pick [pull/8891](https://github.com/apache/iotdb/pull/8891)
=> [To rel/1.0][IOTDB-5425] Consolidate all ConfigNodeClient to be managed by clientManager 

example/flink/src/main/java/org/apache/iotdb/flink/FlinkIoTDBSource.java, example/rabbitmq/src/main/java/org/apache/iotdb/rabbitmq/RabbitMQConsumer.java, example/session/src/main/java/org/apache/iotdb/SessionExample.java, node-commons/src/main/java/org/apache/iotdb/commons/udf/builtin/UDTFEqualSizeBucketOutlierSample.java, server/src/main/java/org/apache/iotdb/db/metadata/mtree/store/disk/schemafile/pagemgr/PageManager.java, tsfile/src/main/java/org/apache/iotdb/tsfile/read/TsFileRestorableReader.java, tsfile/src/main/java/org/apache/iotdb/tsfile/write/writer/TsFileIOWriterEndFileTest.java
- Math operands should be cast before assignment
- Resources should be closed
=> [IOTDB-5284] Fix some sonar bugs

server/src/main/java/org/apache/iotdb/db/rescon/SystemInfo.java
cherry-pick [PR-8921](https://github.com/apache/iotdb/pull/8921)
=> [To rel/1.0][IOTDB-5426] Cannot trigger flush for sequence file when timed flush enabled

confignode/src/main/java/org/apache/iotdb/confignode/consensus/statemachine/ConfigNodeRegionStateMachine.java
cherry-pick https://github.com/apache/iotdb/pull/8917
=> [To rel/1.0][IOTDB-5435] Add close method for logWriter of ConfigNodeRegionStateMachine

server/src/main/java/org/apache/iotdb/db/rescon/SystemInfo.java
cherry-pick https://github.com/apache/iotdb/pull/8921
=> [To rel/0.13][IOTDB-5426] Cannot trigger flush for sequence file when timed flush enabled

server/src/main/java/org/apache/iotdb/db/rescon/SystemInfo.java
=> Revert "[To rel/0.13][IOTDB-5426] Cannot trigger flush for sequence file when timed flush enabled"

server/src/main/java/org/apache/iotdb/db/rescon/SystemInfo.java
=> Revert "[To rel/1.0][IOTDB-5426] Cannot trigger flush for sequence file when timed flush enabled"

example/flink/src/main/java/org/apache/iotdb/flink/FlinkIoTDBSource.java, example/rabbitmq/src/main/java/org/apache/iotdb/rabbitmq/RabbitMQConsumer.java, example/session/src/main/java/org/apache/iotdb/SessionExample.java, node-commons/src/main/java/org/apache/iotdb/commons/udf/builtin/UDTFEqualSizeBucketOutlierSample.java, server/src/main/java/org/apache/iotdb/db/metadata/mtree/store/disk/schemafile/pagemgr/PageManager.java, tsfile/src/main/java/org/apache/iotdb/tsfile/read/TsFileRestorableReader.java, tsfile/src/main/java/org/apache/iotdb/tsfile/write/writer/TsFileIOWriterEndFileTest.java
- cherry-pick from master.
- https://github.com/apache/iotdb/pull/8846
=> [To rel/1.0][IOTDB-5284] Fix some sonar bugs

docs/UserGuide/Monitor-Alert/Metric-Tool.md, docs/zh/UserGuide/Monitor-Alert/Metric-Tool.md, server/src/main/java/org/apache/iotdb/db/engine/TsFileMetricManager.java, server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/task/CrossSpaceCompactionTask.java, server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/utils/CompactionUtils.java, server/src/main/java/org/apache/iotdb/db/engine/modification/ModificationFile.java, server/src/main/java/org/apache/iotdb/db/engine/storagegroup/DataRegion.java, server/src/main/java/org/apache/iotdb/db/service/metrics/FileMetrics.java
See [IOTDB-5418](https://issues.apache.org/jira/browse/IOTDB-5418).
This PR add metrics for modification files.
Scene of modification file generation:
- Deletion
- Compaction finish(compaction modification converts to modification)
Scene of modification file elimination:
- Compaction finish
- SG is deleted.
=> [To Rel/1.0] [IOTDB-5418] Add metric for mods file

example/session/src/main/java/org/apache/iotdb/SessionExample.java, example/session/src/main/java/org/apache/iotdb/SyntaxConventionRelatedExample.java, integration/src/test/java/org/apache/iotdb/db/integration/versionadaption/IoTDBDDLVersionAdaptionIT.java, integration/src/test/java/org/apache/iotdb/db/integration/versionadaption/IoTDBDeletionVersionAdaptionIT.java, integration/src/test/java/org/apache/iotdb/db/integration/versionadaption/IoTDBQueryVersionAdaptionIT.java, isession/src/main/java/org/apache/iotdb/isession/SessionConfig.java, isession/src/main/java/org/apache/iotdb/isession/util/Version.java, jdbc/src/main/java/org/apache/iotdb/jdbc/Config.java, jdbc/src/main/java/org/apache/iotdb/jdbc/Constant.java, node-commons/src/main/java/org/apache/iotdb/commons/conf/IoTDBConstant.java, server/src/main/java/org/apache/iotdb/db/client/DataNodeInternalClient.java, server/src/main/java/org/apache/iotdb/db/protocol/mqtt/MPPPublishHandler.java, server/src/main/java/org/apache/iotdb/db/service/thrift/impl/DataNodeInternalRPCServiceImpl.java, session/src/test/java/org/apache/iotdb/session/pool/SessionPoolTest.java
Add V_1_0 version and update version used in IoTDB
=> [IOTDB-5446] Add V_1_0 version and update version used in IoTDB

confignode/src/main/java/org/apache/iotdb/confignode/conf/ConfigNodeConfig.java, confignode/src/main/java/org/apache/iotdb/confignode/conf/ConfigNodeDescriptor.java, confignode/src/main/java/org/apache/iotdb/confignode/manager/ClusterSchemaManager.java
cherry-pick some code of https://github.com/apache/iotdb/pull/8901
=> [To rel/1.0] Add setLeastDataRegionGroupNumSetByUser judgement

integration-test/src/test/java/org/apache/iotdb/db/it/query/IoTDBNullOperandIT.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/TypeProvider.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/statement/component/WhereCondition.java, server/src/main/java/org/apache/iotdb/db/utils/TypeInferenceUtils.java
Partially cherry-picked from https://github.com/apache/iotdb/pull/8956
=> [IOTDB-5455] Fix NPE when series in where/having is not exist (#8956)

server/src/main/java/org/apache/iotdb/db/mpp/plan/scheduler/FragmentInstanceDispatcherImpl.java
Currently, one FI dispatch failure will result in the dispatch of rest FI being skipped, which cannot bring complete result for mpp client.
Therefore, improve the dispatch process to dispatch all FI of one mpp task and collect all the result for return.
=> [IOTDB-5399] Collect complete dispatch result for return

confignode/src/main/java/org/apache/iotdb/confignode/conf/ConfigNodeConfig.java, confignode/src/main/java/org/apache/iotdb/confignode/conf/ConfigNodeDescriptor.java, confignode/src/main/java/org/apache/iotdb/confignode/manager/ConfigManager.java
=> [IOTDB-5448] Formatting getOrCreatePartitionTables log

confignode/src/main/java/org/apache/iotdb/confignode/consensus/statemachine/ConfigNodeRegionStateMachine.java, consensus/src/main/java/org/apache/iotdb/consensus/IStateMachine.java, consensus/src/main/java/org/apache/iotdb/consensus/common/request/DeserializedBatchIndexedConsensusRequest.java, consensus/src/main/java/org/apache/iotdb/consensus/config/IoTConsensusConfig.java, consensus/src/main/java/org/apache/iotdb/consensus/iot/IoTConsensusServerImpl.java, consensus/src/main/java/org/apache/iotdb/consensus/iot/client/IoTConsensusClientPool.java, consensus/src/main/java/org/apache/iotdb/consensus/iot/logdispatcher/IndexController.java, consensus/src/main/java/org/apache/iotdb/consensus/iot/logdispatcher/LogDispatcher.java, consensus/src/main/java/org/apache/iotdb/consensus/iot/logdispatcher/SyncStatus.java, consensus/src/main/java/org/apache/iotdb/consensus/iot/service/IoTConsensusRPCServiceProcessor.java, consensus/src/main/java/org/apache/iotdb/consensus/ratis/ApplicationStateMachineProxy.java, consensus/src/main/java/org/apache/iotdb/consensus/simple/SimpleServerImpl.java, consensus/src/test/java/org/apache/iotdb/consensus/EmptyStateMachine.java, consensus/src/test/java/org/apache/iotdb/consensus/iot/util/TestStateMachine.java, consensus/src/test/java/org/apache/iotdb/consensus/ratis/TestUtils.java, consensus/src/test/java/org/apache/iotdb/consensus/simple/SimpleConsensusTest.java, server/src/main/java/org/apache/iotdb/db/consensus/DataRegionConsensusImpl.java, server/src/main/java/org/apache/iotdb/db/consensus/statemachine/BaseStateMachine.java, server/src/main/java/org/apache/iotdb/db/consensus/statemachine/DataRegionStateMachine.java, server/src/main/java/org/apache/iotdb/db/consensus/statemachine/IoTConsensusDataRegionStateMachine.java, server/src/main/java/org/apache/iotdb/db/consensus/statemachine/SchemaRegionStateMachine.java
=> [To rel/1.0][IOTDB-5257] Optimize SyncLog Logic in IoT Consensus (#8863)

server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/exception/CompactionExceptionHandler.java, server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/task/CrossSpaceCompactionTask.java, server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/task/InnerSpaceCompactionTask.java, server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/utils/CompactionUtils.java, server/src/main/java/org/apache/iotdb/db/engine/compaction/schedule/CompactionScheduler.java, server/src/main/java/org/apache/iotdb/db/engine/settle/SettleRequestHandler.java, server/src/main/java/org/apache/iotdb/db/engine/storagegroup/DataRegion.java, server/src/main/java/org/apache/iotdb/db/engine/storagegroup/HashLastFlushTimeMap.java, server/src/main/java/org/apache/iotdb/db/engine/storagegroup/IDTableLastFlushTimeMap.java, server/src/main/java/org/apache/iotdb/db/engine/storagegroup/TsFileManager.java, server/src/test/java/org/apache/iotdb/db/engine/compaction/cross/CrossSpaceCompactionExceptionTest.java, server/src/test/java/org/apache/iotdb/db/engine/compaction/cross/CrossSpaceCompactionWithFastPerformerValidationTest.java, server/src/test/java/org/apache/iotdb/db/engine/compaction/inner/InnerSpaceCompactionExceptionTest.java, server/src/test/java/org/apache/iotdb/db/engine/compaction/inner/sizetiered/SizeTieredCompactionSelectorTest.java
=> [IOTDB-5447]fix the ConcurrentModificationException

server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/exception/CompactionExceptionHandler.java, server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/task/CrossSpaceCompactionTask.java, server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/task/InnerSpaceCompactionTask.java, server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/utils/CompactionUtils.java, server/src/main/java/org/apache/iotdb/db/engine/compaction/schedule/CompactionScheduler.java, server/src/main/java/org/apache/iotdb/db/engine/storagegroup/DataRegion.java, server/src/main/java/org/apache/iotdb/db/engine/storagegroup/HashLastFlushTimeMap.java, server/src/main/java/org/apache/iotdb/db/engine/storagegroup/IDTableLastFlushTimeMap.java, server/src/main/java/org/apache/iotdb/db/engine/storagegroup/TsFileManager.java, server/src/test/java/org/apache/iotdb/db/engine/compaction/cross/CrossSpaceCompactionExceptionTest.java, server/src/test/java/org/apache/iotdb/db/engine/compaction/cross/CrossSpaceCompactionWithFastPerformerValidationTest.java, server/src/test/java/org/apache/iotdb/db/engine/compaction/inner/InnerSpaceCompactionExceptionTest.java, server/src/test/java/org/apache/iotdb/db/engine/compaction/inner/sizetiered/SizeTieredCompactionSelectorTest.java
cherry-pick https://github.com/apache/iotdb/pull/8955
=> [IOTDB-5447][To rel/1.0]fix the ConcurrentModificationException 

server/src/main/java/org/apache/iotdb/db/engine/storagegroup/DataRegionInfo.java, server/src/main/java/org/apache/iotdb/db/rescon/SystemInfo.java
Add needToReportToSystem status to avoid issue like https://github.com/apache/iotdb/pull/8921
=> [IOTDB-5426] Cannot trigger flush for sequence file when timed flush enabled

docs/UserGuide/Maintenance-Tools/Maintenance-Command.md, docs/zh/UserGuide/Maintenance-Tools/Maintenance-Command.md
doc: https://apache-iotdb.feishu.cn/docx/MB1KdUeqDoujZqxs4M7cHPbOnib
=> [IOTDB-5476] Modify user doc of 'Show Queries' with more accurate description

confignode/src/main/java/org/apache/iotdb/confignode/procedure/env/DataNodeRemoveHandler.java
Fix the bug that some "REGION_MIGRATE_PROCESS“ still displays "REMOVE_DATANODE_PROCESS".
<hr>
This PR has:
<hr>
=> Renaming some variable `REMOVE_DATANODE_PROCESS` to `REGION_MIGRATE_PROCESS`

server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/AnalyzeVisitor.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/ExpressionAnalyzer.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/expression/ExpressionFactory.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/statement/crud/QueryStatement.java, server/src/test/java/org/apache/iotdb/db/mpp/plan/analyze/ExpressionAnalyzerTest.java
=> [IOTDB-5478] Fix incorrect query filter after binding schema and removing wildcard

integration-test/pom.xml, integration-test/src/main/java/org/apache/iotdb/it/env/cluster/MppCommonConfig.java, integration-test/src/test/java/org/apache/iotdb/db/it/IoTDBSimpleQueryIT.java, integration-test/src/test/java/org/apache/iotdb/db/it/schema/IoTDBAutoCreateSchemaIT.java, integration-test/src/test/java/org/apache/iotdb/db/it/schema/IoTDBCreateAlignedTimeseriesIT.java, integration-test/src/test/java/org/apache/iotdb/db/it/schema/IoTDBCreateStorageGroupIT.java, integration-test/src/test/java/org/apache/iotdb/db/it/schema/IoTDBDeactivateTemplateIT.java, integration-test/src/test/java/org/apache/iotdb/db/it/schema/IoTDBDeleteAlignedTimeseriesIT.java, integration-test/src/test/java/org/apache/iotdb/db/it/schema/IoTDBDeleteTimeseriesIT.java, integration-test/src/test/java/org/apache/iotdb/db/it/schema/IoTDBSchemaTemplateIT.java
Disable thread-level parallel test in IT. And refine some test codes.
=> Fix IT error by parallel suites

isession/src/main/java/org/apache/iotdb/isession/ISession.java, session/src/main/java/org/apache/iotdb/session/Session.java, session/src/main/java/org/apache/iotdb/session/pool/SessionPool.java
=> [To rel/1.0][IOTDB-5498] Fix SessionPool OOM when the numbers of devices and sessions are large

server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/AnalyzeVisitor.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/ClusterPartitionFetcher.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/distribution/DistributionPlanContext.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/distribution/SourceRewriter.java, server/src/test/java/org/apache/iotdb/db/mpp/plan/analyze/AnalyzeTest.java
cherry-pick from https://github.com/apache/iotdb/pull/8953
=> [To rel/1.0] Correct DataPartiton Fetch request parameter contruction

confignode/src/main/java/org/apache/iotdb/confignode/conf/ConfigNodeConfig.java, confignode/src/main/java/org/apache/iotdb/confignode/conf/ConfigNodeDescriptor.java, confignode/src/main/java/org/apache/iotdb/confignode/consensus/statemachine/ConfigNodeRegionStateMachine.java
TODO: need more experiments
1. disk io comparison:  ratis 1 replica v.s. simple
=> [IOTDB-5479] Optimize the wal impl of confignode simple consensus

server/src/main/java/org/apache/iotdb/db/engine/storagegroup/DataRegion.java, server/src/main/java/org/apache/iotdb/db/wal/recover/file/AbstractTsFileRecoverPerformer.java
cherry-pick https://github.com/apache/iotdb/pull/9000
=> [To rel/1.0][IOTDB-5492] Skip broken tsfile when recovering system

server/src/main/java/org/apache/iotdb/db/engine/storagegroup/DataRegion.java, server/src/main/java/org/apache/iotdb/db/wal/recover/file/AbstractTsFileRecoverPerformer.java
cherry-pick https://github.com/apache/iotdb/pull/9000
=> [IOTDB-5492] Skip broken tsfile when recovering system

server/src/main/java/org/apache/iotdb/db/engine/StorageEngine.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/execution/config/executor/ClusterConfigTaskExecutor.java, server/src/main/java/org/apache/iotdb/db/service/thrift/impl/DataNodeInternalRPCServiceImpl.java
=> [IOTDB-5488] Fix set system to readonly on local

server/src/main/java/org/apache/iotdb/db/mpp/execution/memory/MemoryPool.java
See JIRA: https://issues.apache.org/jira/browse/IOTDB-5514
=> [IOTDB-5514] Fix race condition in MemoryPool without synchronized block

integration-test/src/test/java/org/apache/iotdb/db/it/IoTDBSimpleQueryIT.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/distribution/ExchangeNodeAdder.java
see https://issues.apache.org/jira/browse/IOTDB-5513
=> [IOTDB-5513] Fix duplicate LastQueryNode due to change of partition slot algorithm

consensus/src/main/java/org/apache/iotdb/consensus/iot/IoTConsensusServerImpl.java, consensus/src/main/java/org/apache/iotdb/consensus/iot/IoTConsensusServerMetrics.java, consensus/src/main/java/org/apache/iotdb/consensus/iot/logdispatcher/Batch.java, consensus/src/main/java/org/apache/iotdb/consensus/iot/logdispatcher/LogDispatcher.java, docs/UserGuide/Monitor-Alert/Metric-Tool.md, docs/zh/UserGuide/Monitor-Alert/Metric-Tool.md
Please see details in [IOTDB-5502](https://issues.apache.org/jira/browse/IOTDB-5502).
=> [IOTDB-5502] Source counters for construct batches in IoTConsensus

consensus/src/main/java/org/apache/iotdb/consensus/common/Utils.java, consensus/src/main/java/org/apache/iotdb/consensus/ratis/ApplicationStateMachineProxy.java, consensus/src/main/java/org/apache/iotdb/consensus/ratis/RatisClient.java, consensus/src/main/java/org/apache/iotdb/consensus/ratis/RatisConsensus.java, consensus/src/main/java/org/apache/iotdb/consensus/ratis/RequestMessage.java, consensus/src/main/java/org/apache/iotdb/consensus/ratis/ResponseMessage.java, consensus/src/main/java/org/apache/iotdb/consensus/ratis/SnapshotStorage.java
refactor some non-read/write-related part.
=> [IOTDB-5506] refactor RatisConsensus attempt 1

server/src/main/java/org/apache/iotdb/db/wal/buffer/AbstractWALBuffer.java
cherry-pick https://github.com/apache/iotdb/pull/8994
=> [To rel/1.0] Update wal file version after next file has been created

isession/src/main/java/org/apache/iotdb/isession/ISession.java, server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java, server/src/main/java/org/apache/iotdb/db/mpp/common/FragmentInstanceId.java, server/src/main/java/org/apache/iotdb/db/mpp/execution/exchange/SharedTsBlockQueue.java, server/src/main/java/org/apache/iotdb/db/mpp/execution/exchange/SinkHandle.java, server/src/main/java/org/apache/iotdb/db/mpp/execution/exchange/SourceHandle.java, server/src/main/java/org/apache/iotdb/db/mpp/execution/memory/MemoryPool.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/AnalyzeVisitor.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/ClusterPartitionFetcher.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/distribution/DistributionPlanContext.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/distribution/SourceRewriter.java, server/src/test/java/org/apache/iotdb/db/mpp/execution/exchange/LocalSinkHandleTest.java, server/src/test/java/org/apache/iotdb/db/mpp/execution/exchange/SinkHandleTest.java, server/src/test/java/org/apache/iotdb/db/mpp/execution/exchange/SourceHandleTest.java, server/src/test/java/org/apache/iotdb/db/mpp/plan/analyze/AnalyzeTest.java, session/src/main/java/org/apache/iotdb/session/Session.java, session/src/main/java/org/apache/iotdb/session/pool/SessionPool.java
cherry-pick 
a37da33： https://issues.apache.org/jira/browse/IOTDB-5498
0b65f4d： https://issues.apache.org/jira/browse/IOTDB-5501
8af48e3： https://issues.apache.org/jira/browse/IOTDB-5525
=> [To rc/1.0.1] Cherry-pick a37da33、0b65f4d、8af48e3 to rc/1.0.1

consensus/src/main/java/org/apache/iotdb/consensus/iot/IoTConsensusServerImpl.java, consensus/src/main/java/org/apache/iotdb/consensus/iot/client/DispatchLogHandler.java, consensus/src/main/java/org/apache/iotdb/consensus/iot/logdispatcher/LogDispatcher.java, docs/UserGuide/Monitor-Alert/Apache-IoTDB-DataNode-Dashboard.json
https://issues.apache.org/jira/browse/IOTDB-5531
=> [IOTDB-5531] Update IoT Consensus Metric from ms precision to ns precision

docs/Download/README.md, docs/zh/Download/README.md
Update the download url of 0.13.4.
=> update download url in website

docs/UserGuide/Monitor-Alert/Apache-IoTDB-DataNode-Dashboard.json
=> [IOTDB-5480][IOTDB-5491][IOTDB-5502] Update DataNode Dashboard

RELEASE_NOTES.md, client-py/setup.py, jdbc/src/main/feature/feature.xml
=> add release notes; change version of setup.py and feature.xml

confignode/src/main/java/org/apache/iotdb/confignode/conf/ConfigNodeStartupCheck.java, confignode/src/main/java/org/apache/iotdb/confignode/manager/node/ClusterNodeStartUtils.java, integration-test/src/test/java/org/apache/iotdb/confignode/it/cluster/IoTDBClusterNodeErrorStartUpIT.java, integration-test/src/test/java/org/apache/iotdb/confignode/it/cluster/IoTDBClusterNodeGetterIT.java, integration-test/src/test/java/org/apache/iotdb/confignode/it/cluster/IoTDBClusterRestartIT.java
See the difference between old protocol at [jira](https://issues.apache.org/jira/browse/IOTDB-5507)
See the latest protocol at [Feishu](https://apache-iotdb.feishu.cn/docx/BWAtdxAZ8oflr7xcJXncAAyAnMc)
=> [IOTDB-5507] Simplify Cluster Node restart protocol

metrics/interface/src/main/java/org/apache/iotdb/metrics/AbstractMetricService.java, node-commons/src/main/java/org/apache/iotdb/commons/service/metric/MetricService.java
Fix concurrency problem when start, stop and restart metric service.
https://issues.apache.org/jira/browse/IOTDB-5544
=> [IOTDB-5544] Fix metric service concurrency problem

server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/AnalyzeVisitor.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/ExpressionAnalyzer.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/expression/ExpressionFactory.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/statement/crud/QueryStatement.java, server/src/test/java/org/apache/iotdb/db/mpp/plan/analyze/ExpressionAnalyzerTest.java
=> [To rel/1.0] [IOTDB-5478] Fix incorrect query filter after binding schema and removing wildcard

metrics/interface/src/main/java/org/apache/iotdb/metrics/AbstractMetricService.java, node-commons/src/main/java/org/apache/iotdb/commons/service/metric/MetricService.java
(cherry picked from commit 1fff33b31782266465f1a611080dbe3c32213c49)
From #9076
=> [To rel/1.0][IOTDB-5544] Fix metric service concurrency problem

server/src/main/java/org/apache/iotdb/db/mpp/plan/parser/ASTVisitor.java, server/src/main/java/org/apache/iotdb/db/service/thrift/impl/ClientRPCServiceImpl.java
Identifier not enclosed with back quotes should not be a real number.
=> [IOTDB-5548] fix typo in ASTVisitor.createSchemaTemplate and ASTvisitor.parseIdentifier

server/src/main/java/org/apache/iotdb/db/metadata/mtree/IMTreeBelowSG.java, server/src/main/java/org/apache/iotdb/db/metadata/mtree/MTreeBelowSGCachedImpl.java, server/src/main/java/org/apache/iotdb/db/metadata/mtree/MTreeBelowSGMemoryImpl.java, server/src/main/java/org/apache/iotdb/db/metadata/schemaregion/SchemaRegionMemoryImpl.java, server/src/main/java/org/apache/iotdb/db/metadata/schemaregion/SchemaRegionSchemaFileImpl.java, server/src/test/java/org/apache/iotdb/db/metadata/mtree/MTreeBelowSGTest.java
There's redundant unpin operation during deleting empty internal node. Fix it.
=> [IOTDB-5561] Fix NPE of SchemaRegionTemplateTest.testDeactivateTemplate

confignode/src/main/java/org/apache/iotdb/confignode/manager/load/balancer/RegionBalancer.java, confignode/src/main/java/org/apache/iotdb/confignode/manager/load/balancer/region/CopySetRegionGroupAllocator.java, confignode/src/main/java/org/apache/iotdb/confignode/manager/load/balancer/region/GreedyRegionGroupAllocator.java, confignode/src/main/java/org/apache/iotdb/confignode/manager/load/balancer/region/IRegionGroupAllocator.java, confignode/src/main/java/org/apache/iotdb/confignode/manager/node/NodeManager.java, confignode/src/main/java/org/apache/iotdb/confignode/manager/node/heartbeat/DataNodeHeartbeatCache.java, confignode/src/test/java/org/apache/iotdb/confignode/manager/load/balancer/region/GreedyRegionGroupAllocatorTest.java, metrics/dropwizard-metrics/src/main/java/org/apache/iotdb/metrics/dropwizard/DropwizardMetricManager.java, metrics/dropwizard-metrics/src/main/java/org/apache/iotdb/metrics/dropwizard/type/DropwizardAutoGauge.java, metrics/interface/src/main/java/org/apache/iotdb/metrics/AbstractMetricManager.java, metrics/interface/src/main/java/org/apache/iotdb/metrics/AbstractMetricService.java, metrics/interface/src/main/java/org/apache/iotdb/metrics/impl/DoNothingAutoGauge.java, metrics/interface/src/main/java/org/apache/iotdb/metrics/impl/DoNothingMetricManager.java, metrics/interface/src/main/java/org/apache/iotdb/metrics/type/AutoGauge.java, metrics/micrometer-metrics/src/main/java/org/apache/iotdb/metrics/micrometer/MicrometerMetricManager.java, metrics/micrometer-metrics/src/main/java/org/apache/iotdb/metrics/micrometer/type/MicrometerAutoGauge.java, server/src/main/java/org/apache/iotdb/db/service/metrics/SystemMetrics.java, server/src/main/java/org/apache/iotdb/db/service/thrift/impl/DataNodeInternalRPCServiceImpl.java, server/src/test/java/org/apache/iotdb/db/metric/MetricServiceTest.java, thrift/src/main/thrift/datanode.thrift
see [jira5562](https://issues.apache.org/jira/browse/IOTDB-5562)
=> [IOTDB-5562] Change the data type of AutoGuage from long to double in metric module

docs/Download/README.md, docs/zh/Download/README.md
=> Modify README.md for release 1.0.1

site/src/main/.eslintignore, site/src/main/.eslintrc.cjs, site/src/main/.vuepress/config.js, site/src/main/.vuepress/theme/components/AlgoliaSearchBox.vue, site/src/main/.vuepress/theme/components/Page.vue, site/src/main/.vuepress/theme/components/RightMenu.vue, site/src/main/.vuepress/theme/styles/palette.styl, site/src/main/package.json
=> feat(site): 1. Add Page RightMenu 2. Enable Algolia Search 3. Add ESLint And Fix `config.js`

confignode/src/main/java/org/apache/iotdb/confignode/consensus/request/ConfigPhysicalPlan.java, confignode/src/main/java/org/apache/iotdb/confignode/consensus/request/ConfigPhysicalPlanType.java, confignode/src/main/java/org/apache/iotdb/confignode/consensus/request/write/region/PollSpecificRegionMaintainTaskPlan.java, confignode/src/main/java/org/apache/iotdb/confignode/manager/partition/PartitionManager.java, confignode/src/main/java/org/apache/iotdb/confignode/persistence/executor/ConfigPlanExecutor.java, confignode/src/main/java/org/apache/iotdb/confignode/persistence/partition/PartitionInfo.java, confignode/src/main/java/org/apache/iotdb/confignode/persistence/partition/maintainer/RegionCreateTask.java, confignode/src/main/java/org/apache/iotdb/confignode/persistence/partition/maintainer/RegionMaintainTask.java, confignode/src/test/java/org/apache/iotdb/confignode/consensus/request/ConfigPhysicalPlanSerDeTest.java
Implement batch deleting dataRegion via async client for RegionMaintainer.
=> [IOTDB-5516] Accelerate async delete DataRegion during dropping database

site/src/main/.vuepress/theme/components/AlgoliaSearchBox.vue
DocSearch Filter By Version
搜索时只搜索当前版本
=> feat(WebSite) :DocSearch Filter By Version

docs/UserGuide/Monitor-Alert/Metric-Tool.md, docs/zh/UserGuide/Monitor-Alert/Metric-Tool.md
Update metric docs for schema module
=> [IOTDB-5524] Update metric docs for schema module

antlr/src/main/antlr4/org/apache/iotdb/db/qp/sql/IdentifierParser.g4, antlr/src/main/antlr4/org/apache/iotdb/db/qp/sql/IoTDBSqlParser.g4, antlr/src/main/antlr4/org/apache/iotdb/db/qp/sql/SqlLexer.g4, docs/UserGuide/Query-Data/Group-By.md, docs/UserGuide/Query-Data/Overview.md, docs/zh/UserGuide/Query-Data/Group-By.md, docs/zh/UserGuide/Query-Data/Overview.md, integration-test/src/test/java/org/apache/iotdb/db/it/groupby/IoTDBGroupByConditionIT.java, integration-test/src/test/java/org/apache/iotdb/db/it/groupby/IoTDBGroupByFilterIT.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/parser/ASTVisitor.java
https://iotdb.apache.org/zh/UserGuide/Master/Query-Data/Group-By.html
Fix some typo problem.
=> Modify Group-By UserGuide

server/src/main/java/org/apache/iotdb/db/mpp/plan/parser/StatementGenerator.java
=> Use req.getName() as templateName in ClientRpcServiceImpl

server/src/main/java/org/apache/iotdb/db/engine/flush/MemTableFlushTask.java, server/src/main/java/org/apache/iotdb/db/engine/storagegroup/TsFileProcessor.java, server/src/main/java/org/apache/iotdb/db/wal/recover/file/UnsealedTsFileRecoverPerformer.java, server/src/test/java/org/apache/iotdb/db/engine/memtable/MemTableFlushTaskTest.java
=> [IOTDB-5587] Add dataRegionId into Memtable and update flush point metrics

integration-test/src/test/java/org/apache/iotdb/db/it/path/IoTDBFullPathIT.java, integration-test/src/test/java/org/apache/iotdb/db/it/path/IoTDBQuotedPathIT.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/parser/ASTVisitor.java
cause: error use of code about 'inWithoutNull'
=> [IOTDB-5592]Fix unexpected error when use full Path in having/where

server/src/main/java/org/apache/iotdb/db/engine/storagegroup/DataRegion.java, server/src/main/java/org/apache/iotdb/db/engine/storagegroup/TsFileProcessorInfo.java, server/src/main/java/org/apache/iotdb/db/engine/storagegroup/TsFileProcessorInfoMetrics.java
see [jira](https://issues.apache.org/jira/browse/IOTDB-5595)
=> [IOTDB-5595] Fix memory leak for TsFileProcessorInfoMetrics in TsFileProcessorInfo

docs/UserGuide/API/Programming-Go-Native-API.md, docs/zh/UserGuide/API/Programming-Go-Native-API.md
=> user guide adds sessionPool description

server/src/main/java/org/apache/iotdb/db/rescon/TsFileResourceManager.java, server/src/test/java/org/apache/iotdb/db/rescon/ResourceManagerTest.java
Add TsFileResource back to TsFileResourceManager when all time index are file level.
=> Add TsFileResource back to TsFileResourceManager when all time index are file level

confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/schema/DeleteDatabaseProcedure.java
When prepare the requests for deleting schema regions, the origin implementation only deletes one replica of one raft group.
Fix this to delete all replicas.
=> [IOTDB-5516] Fix delete schema region bug during drop database

server/src/main/java/org/apache/iotdb/db/rescon/TsFileResourceManager.java, server/src/test/java/org/apache/iotdb/db/rescon/ResourceManagerTest.java
Add TsFileResource back to TsFileResourceManager when all time index are file level
=> [To rel/1.0] Add TsFileResource back to TsFileResourceManager when all time index are file level

.github/workflows/site-build.yml
Update website deploy command for v1.1.
=> Update website deploy command

docs/UserGuide/Monitor-Alert/Apache-IoTDB-ConfigNode-Dashboard.json
1. Error titlle: 
2. Miss "instance" in metrics SQL:
=> [IOTDB-5542] Fix ConfigNode Dashboard bug

integration-test/src/main/java/org/apache/iotdb/it/env/remote/RemoteServerEnv.java, integration-test/src/test/java/org/apache/iotdb/db/it/aggregation/IoTDBAggregationIT.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/distribution/NodeGroupContext.java
same as https://github.com/apache/iotdb/pull/9183
=> [To rel/1.1][IOTDB-5604]Fix NPE when execute Agg + align by device query without assigned DataRegion

docs/README.md, docs/zh/README.md, site/src/main/.vuepress/components/IoTDB.vue, site/src/main/.vuepress/components/IoTDBZH.vue, site/src/main/.vuepress/theme.ts
1、 fix home url error
2、add dark mode
=> fix(site):fix home url error

server/src/main/java/org/apache/iotdb/db/metadata/mtree/store/disk/cache/CacheMemoryManager.java
Try to fix timeout in Schema UT.
=> Fix timeout in Schema UT

server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/ExpressionUtils.java
The logic between reconstructExpressions and reconstructExpression are same.
So let reconstructExpressions use reconstructExpression will make it simple.
=> Remove redundant logic in reconstructExpressions()

docs/UserGuide/Query-Data/Pagination.md, docs/UserGuide/Query-Data/Select-Into.md, docs/zh/UserGuide/Query-Data/Pagination.md, docs/zh/UserGuide/Query-Data/Select-Into.md
In this PR, I update query user guide.
=> Update query user guide

docs/UserGuide/Query-Data/Pagination.md, docs/UserGuide/Query-Data/Select-Into.md, docs/zh/UserGuide/Query-Data/Pagination.md, docs/zh/UserGuide/Query-Data/Select-Into.md
=> [To rel/1.1] Update query user guide

docs/UserGuide/Monitor-Alert/Apache-IoTDB-ConfigNode-Dashboard.json, docs/UserGuide/Monitor-Alert/Apache-IoTDB-DataNode-Dashboard.json, metrics/interface/src/main/java/org/apache/iotdb/metrics/metricsets/disk/DiskMetrics.java, metrics/interface/src/main/java/org/apache/iotdb/metrics/metricsets/disk/LinuxDiskMetricsManager.java
This pr fix error in grafana sql and remove one unused panel.
=> [IOTDB-5517] Add metrics for disk io

integration-test/src/main/java/org/apache/iotdb/it/env/cluster/MppCommonConfig.java, integration-test/src/main/java/org/apache/iotdb/it/env/cluster/MppSharedCommonConfig.java, integration-test/src/main/java/org/apache/iotdb/it/env/remote/RemoteCommonConfig.java, integration-test/src/main/java/org/apache/iotdb/itbase/env/CommonConfig.java, integration-test/src/test/java/org/apache/iotdb/db/it/IoTDBInsertMultiPartitionIT.java, server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java, server/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java, server/src/main/java/org/apache/iotdb/db/engine/storagegroup/TimePartitionManager.java
=> [To rel/1.1][IOTDB-5620] Fix flush stuck when there is a lot of time partitions in each DataRegion

cli/src/main/java/org/apache/iotdb/cli/AbstractCli.java, cli/src/main/java/org/apache/iotdb/tool/AbstractCsvTool.java, cli/src/test/java/org/apache/iotdb/cli/AbstractCliIT.java, confignode/src/main/java/org/apache/iotdb/confignode/client/async/AsyncDataNodeClientPool.java, flink-tsfile-connector/src/main/java/org/apache/iotdb/flink/tsfile/TsFileOutputFormat.java, server/src/main/java/org/apache/iotdb/db/metadata/mtree/store/disk/cache/CacheMemoryManager.java, tsfile/src/main/java/org/apache/iotdb/tsfile/write/record/datapoint/DataPoint.java
fix some code smells，please see in [JIRA5616](https://issues.apache.org/jira/browse/IOTDB-5616).
=> [IOTDB-5616] Fix some code smells

server/src/main/java/org/apache/iotdb/db/rescon/SystemInfo.java
=> [To rel/1.1] Fix memory calculation is not accurate in SystemInfo

integration-test/src/test/java/org/apache/iotdb/db/it/aggregation/IoTDBTagAggregationIT.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/OperatorTreeGenerator.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/SubPlanTypeExtractor.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/process/GroupByTagNode.java, server/src/test/java/org/apache/iotdb/db/mpp/plan/plan/node/process/GroupByTagNodeSerdeTest.java
See JIRA: https://issues.apache.org/jira/browse/IOTDB-5619
=> [IOTDB-5619] Fix NPE in processing GroupByTagNode

docs/UserGuide/Maintenance-Tools/TsFile-Settle-Tool.md, docs/zh/UserGuide/Maintenance-Tools/TsFile-Settle-Tool.md, server/src/main/java/org/apache/iotdb/db/tools/settle/TsFileSettleByCompactionTool.java
Add docs of settle tool and modify the default port of the tool(9003 -> 10730)
=> Add Tsfile-settle-tool docs and modify the default port of the tool

server/src/main/java/org/apache/iotdb/db/mpp/execution/driver/DataDriver.java, server/src/main/java/org/apache/iotdb/db/mpp/execution/fragment/FragmentInstanceContext.java, server/src/main/java/org/apache/iotdb/db/mpp/execution/fragment/FragmentInstanceExecution.java, server/src/main/java/org/apache/iotdb/db/mpp/execution/fragment/FragmentInstanceManager.java
cp from https://github.com/apache/iotdb/pull/9240
=> [To rel/1.1] Set some runtime fields in FIConetxt to null when the FI is done

site/src/main/.vuepress/components/IoTDBZH.vue
=> fix(home): fix home url error

integration-test/src/test/java/org/apache/iotdb/db/it/aggregation/IoTDBTagAggregationIT.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/OperatorTreeGenerator.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/SubPlanTypeExtractor.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/process/GroupByTagNode.java, server/src/test/java/org/apache/iotdb/db/mpp/plan/plan/node/process/GroupByTagNodeSerdeTest.java
=> [To rel/1.1][IOTDB-5619] Fix NPE in processing GroupByTagNode

docs/UserGuide/Maintenance-Tools/Maintenance-Command.md, docs/zh/UserGuide/Maintenance-Tools/Maintenance-Command.md
cp from https://github.com/apache/iotdb/pull/9264
=> [To rel/1.1][Doc] Add example of 'kill query' in doc

cli/src/main/java/org/apache/iotdb/cli/AbstractCli.java, cli/src/main/java/org/apache/iotdb/tool/AbstractCsvTool.java, cli/src/test/java/org/apache/iotdb/cli/AbstractCliIT.java, confignode/src/main/java/org/apache/iotdb/confignode/client/async/AsyncDataNodeClientPool.java, flink-tsfile-connector/src/main/java/org/apache/iotdb/flink/tsfile/TsFileOutputFormat.java, server/src/main/java/org/apache/iotdb/db/metadata/mtree/store/disk/cache/CacheMemoryManager.java, tsfile/src/main/java/org/apache/iotdb/tsfile/write/record/datapoint/DataPoint.java
cherry pick from master
https://github.com/apache/iotdb/pull/9217
=> [To rel/1.1][IOTDB-5616] Fix some code smells

confignode/src/main/java/org/apache/iotdb/confignode/manager/ProcedureManager.java
Fixed the bug that readOnly regions cannot be migrated.
<hr>
This PR has:
<hr>
=> [To rel/1.1] [IOTDB-5300] Fix an error occurs when migrating readonly data region

integration-test/src/test/java/org/apache/iotdb/db/it/query/IoTDBNoSelectExpressionAfterAnalyzedIT.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/AnalyzeVisitor.java
cp from https://github.com/apache/iotdb/pull/9242
Signed-off-by: Weihao Li <18110526956@163.com>
(cherry picked from commit b1f66fb711b6a859c797059bf9a882a0669f9b74)
=> [To rel/1.1][IOTDB-5644] Fix unexpected result when there are no select expressions after analyzed in query

server/src/main/java/org/apache/iotdb/db/exception/metadata/DatabaseAlreadySetException.java, server/src/main/java/org/apache/iotdb/db/exception/metadata/DatabaseNotSetException.java, server/src/main/java/org/apache/iotdb/db/metadata/mtree/ConfigMTree.java, server/src/main/java/org/apache/iotdb/db/protocol/rest/handler/ExceptionHandler.java
Rename StorageGroup related expcetion name to Database
=> [IOTDB-5660] Rename StorageGroup related expcetion name to Database

docs/UserGuide/Cluster/Cluster-Maintenance.md, docs/zh/UserGuide/Cluster/Cluster-Maintenance.md
Fixed some old documents in the "cluster" folder.
<hr>
This PR has:
<hr>
=> [To rel/1.1][IOTDB-5661] Update Docs

docs/UserGuide/Cluster/Cluster-Maintenance.md, docs/zh/UserGuide/Cluster/Cluster-Maintenance.md
Fixed some old documents.
<hr>
This PR has:
<hr>
=> [IOTDB-5661] Update docs

grafana-plugin/pkg/main.go, grafana-plugin/pkg/plugin/iotdb_resource_handler.go, grafana-plugin/pkg/plugin/plugin.go, grafana-plugin/src/ConfigEditor.tsx, grafana-plugin/src/QueryEditor.tsx, grafana-plugin/src/datasource.ts, grafana-plugin/src/types.ts, grafana-plugin/yarn.lock
1、The wrong plugin id is used to initialize the backend
2、Remove the usage of "LegacyForms" 
3、Add user input checksum error handling
4、the backend http client is reused across queries (and healthcheck)
5、Add exception handling
=> [grafana-plugin]  Preparing grafana-plugin launching in Grafana Marketplace: serveral bug fixes & code optimization

docs/UserGuide/Monitor-Alert/Metric-Tool.md, docs/zh/UserGuide/Monitor-Alert/Metric-Tool.md
Add zh docs of write metric and modify the corresponding en docs.
=> Modify docs of write metric

confignode/src/main/java/org/apache/iotdb/confignode/service/ConfigNode.java, docs/UserGuide/Monitor-Alert/Apache-IoTDB-Network-Dashboard.json, metrics/interface/src/main/java/org/apache/iotdb/metrics/metricsets/disk/DiskMetrics.java, metrics/interface/src/main/java/org/apache/iotdb/metrics/metricsets/net/INetMetricManager.java, metrics/interface/src/main/java/org/apache/iotdb/metrics/metricsets/net/LinuxNetMetricManager.java, metrics/interface/src/main/java/org/apache/iotdb/metrics/metricsets/net/MacNetMetricManager.java, metrics/interface/src/main/java/org/apache/iotdb/metrics/metricsets/net/NetMetrics.java, metrics/interface/src/main/java/org/apache/iotdb/metrics/metricsets/net/WindowsNetMetricManager.java, server/src/main/java/org/apache/iotdb/db/service/metrics/DataNodeMetricsHelper.java
See [IOTDB-5663](https://issues.apache.org/jira/browse/IOTDB-5663).
This PR support monitoring network throughput, process data and process packets.
=> [IOTDB-5663] Add network metric

client-py/iotdb/Session.py
When IoTDB server return an error to Python Client, the exception didn't throw out.
=> Python client should throw exception when meets error

integration-test/src/test/java/org/apache/iotdb/db/it/last/IoTDBLastQueryWithLimitOffsetIT.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/optimization/LimitOffsetPushDown.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/LogicalPlanVisitor.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/statement/crud/QueryStatement.java
cherry pick from https://github.com/apache/iotdb/commit/57c47f9d19e127ba12c64989fbd06df4cbf7e190
=> [To rel/1.1][IOTDB-5657] Fix LIMIT&OFFSET does not take effect in last query

confignode/src/main/java/org/apache/iotdb/confignode/service/ConfigNode.java, docs/UserGuide/Monitor-Alert/Apache-IoTDB-Network-Dashboard.json, metrics/interface/src/main/java/org/apache/iotdb/metrics/metricsets/net/INetMetricManager.java, metrics/interface/src/main/java/org/apache/iotdb/metrics/metricsets/net/LinuxNetMetricManager.java, metrics/interface/src/main/java/org/apache/iotdb/metrics/metricsets/net/NetMetrics.java, server/src/main/java/org/apache/iotdb/db/service/metrics/DataNodeMetricsHelper.java
Add connection num metrics for single process.
=> [IOTDB-5663] Add connection num metrics

pom.xml
Fix the display error of the rest service swagger
=> [hotfix][REST Service] Fix the display error of the swagger page 

antlr/src/main/antlr4/org/apache/iotdb/db/qp/sql/IdentifierParser.g4, antlr/src/main/antlr4/org/apache/iotdb/db/qp/sql/IoTDBSqlParser.g4, antlr/src/main/antlr4/org/apache/iotdb/db/qp/sql/SqlLexer.g4, integration-test/src/main/java/org/apache/iotdb/itbase/constant/BuiltinScalarFunctionEnum.java, integration-test/src/test/java/org/apache/iotdb/db/it/builtinfunction/scalar/IoTDBReplaceFunctionIT.java, node-commons/src/main/java/org/apache/iotdb/commons/udf/builtin/BuiltinScalarFunction.java, server/src/main/java/org/apache/iotdb/db/constant/SqlConstant.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/expression/multi/FunctionExpression.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/expression/multi/builtin/BuiltInScalarFunctionHelper.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/expression/multi/builtin/BuiltInScalarFunctionHelperFactory.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/expression/multi/builtin/helper/CastFunctionHelper.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/expression/multi/builtin/helper/DiffFunctionHelper.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/expression/multi/builtin/helper/ReplaceFunctionHelper.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/parser/ASTVisitor.java, server/src/main/java/org/apache/iotdb/db/mpp/transformation/dag/column/unary/scalar/CastFunctionColumnTransformer.java, server/src/main/java/org/apache/iotdb/db/mpp/transformation/dag/column/unary/scalar/ReplaceFunctionColumnTransformer.java, server/src/main/java/org/apache/iotdb/db/mpp/transformation/dag/transformer/unary/scalar/CastFunctionTransformer.java, server/src/main/java/org/apache/iotdb/db/mpp/transformation/dag/transformer/unary/scalar/ReplaceFunctionTransformer.java
https://apache-iotdb.feishu.cn/docx/N4EqdXba0o0UWhxlCxicNo2Bn3f
=> [IOTDB-5643] Add REPLACE as a built-in scalar function

metrics/micrometer-metrics/src/main/java/org/apache/iotdb/metrics/micrometer/type/MicrometerAutoGauge.java
see [jira](https://issues.apache.org/jira/browse/IOTDB-5674)
=> [IOTDB-5674] Remove useless log in MicrometerAutoGauge

confignode/src/main/java/org/apache/iotdb/confignode/conf/ConfigNodeDescriptor.java, confignode/src/main/java/org/apache/iotdb/confignode/service/ConfigNode.java, metrics/interface/src/main/java/org/apache/iotdb/metrics/config/MetricConfig.java, server/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java, server/src/main/java/org/apache/iotdb/db/service/DataNode.java
Fix the update of nodeId Metrics: we need to update nodeId after registry
=> [IOTDB-5682] Fix the update of nodeId in Metrics

server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/task/CrossSpaceCompactionTask.java, server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/task/InnerSpaceCompactionTask.java
Delete compaction logs after closing its input stream.
=> [IOTDB-5651] Fix compaction UT

docs/UserGuide/Monitor-Alert/Apache-IoTDB-ConfigNode-Dashboard.json, docs/UserGuide/Monitor-Alert/Apache-IoTDB-DataNode-Dashboard.json, docs/UserGuide/Monitor-Alert/Apache-IoTDB-Disk-IO-Dashboard.json, docs/UserGuide/Monitor-Alert/Apache-IoTDB-Network-Dashboard.json, metrics/interface/src/main/java/org/apache/iotdb/metrics/metricsets/disk/DiskMetrics.java
This pr seperate io dashboard from datanode dashboard and confignode dashboard.
=> Seperate IO Dashboard apart

site/src/main/.vuepress/styles/config.scss
change pc width to 1280px，for TOC
修改pc宽度为1280，用于响应式TOC
=> change pc width to 1280px

README.md
Modified the link in section installation and slack to hyperlink.
<hr>
This PR has:
<hr>
=> [doc](readme)Enhancement in links

consensus/src/main/java/org/apache/iotdb/consensus/ratis/ApplicationStateMachineProxy.java, consensus/src/main/java/org/apache/iotdb/consensus/ratis/RatisConsensus.java, consensus/src/main/java/org/apache/iotdb/consensus/ratis/Utils.java, consensus/src/main/java/org/apache/iotdb/consensus/ratis/metrics/IoTDBMetricRegistry.java, consensus/src/main/java/org/apache/iotdb/consensus/ratis/metrics/RatisMetricsManager.java, consensus/src/main/java/org/apache/iotdb/consensus/simple/SimpleConsensus.java, server/src/main/java/org/apache/iotdb/db/consensus/statemachine/DataRegionStateMachine.java
see [jira](https://issues.apache.org/jira/browse/IOTDB-5697)
=> [IOTDB-5697] Only record engine cost for DataRegion in Performance Overview Dashboard

confignode/src/main/java/org/apache/iotdb/confignode/conf/ConfigNodeStartupCheck.java, confignode/src/main/java/org/apache/iotdb/confignode/service/ConfigNodeCommandLine.java, integration-test/src/test/java/org/apache/iotdb/confignode/it/cluster/IoTDBClusterNodeErrorStartUpIT.java, node-commons/src/main/java/org/apache/iotdb/commons/service/StartupChecks.java, server/src/main/java/org/apache/iotdb/db/conf/DataNodeStartupCheck.java, server/src/main/java/org/apache/iotdb/db/service/DataNode.java
cherry pick from master
https://github.com/apache/iotdb/pull/9270
=> [To rel/1.1][IOTDB-5368] add port check for confignode and datanode (#9270)

server/src/main/java/org/apache/iotdb/db/mpp/transformation/dag/udf/UDTFContext.java
https://issues.apache.org/jira/browse/IOTDB-5700
=> [IOTDB-5700] Clean temporary files created by UDF query after it finishes

server/src/main/java/org/apache/iotdb/db/service/metrics/IoTDBInternalLocalReporter.java
(cherry picked from commit be23689cceab4ab8eeb0d27fcdab49b1ed693edd)
=> [To rel/1.1][IOTDB-5681] Fix the creation of system database used by IoTDB Internal Reporter

consensus/src/main/java/org/apache/iotdb/consensus/ratis/ApplicationStateMachineProxy.java, consensus/src/main/java/org/apache/iotdb/consensus/ratis/RatisConsensus.java, consensus/src/main/java/org/apache/iotdb/consensus/ratis/Utils.java, consensus/src/main/java/org/apache/iotdb/consensus/ratis/metrics/IoTDBMetricRegistry.java, consensus/src/main/java/org/apache/iotdb/consensus/ratis/metrics/RatisMetricsManager.java, consensus/src/main/java/org/apache/iotdb/consensus/simple/SimpleConsensus.java, server/src/main/java/org/apache/iotdb/db/consensus/statemachine/DataRegionStateMachine.java
cherry-pick [pull](https://github.com/apache/iotdb/pull/9366)
=> [To rel/1.1][IOTDB-5697] Only record engine cost for DataRegion in Performance Overview Dashboard

server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/distribution/DistributionPlanner.java
cause: forget the case of `VirtualSource`
=> [IOTDB-5702] fix show queries after introduce Shuffle

server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/distribution/DistributionPlanner.java
cp from https://github.com/apache/iotdb/pull/9383
=> [IOTDB-5702] fix show queries after introduce Shuffle #9383

server/src/main/java/org/apache/iotdb/db/mpp/transformation/dag/udf/UDTFContext.java
=> [To rel/1.1][IOTDB-5700] Clean temporary files created by UDF query after it finishes

server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/performer/impl/ReadChunkCompactionPerformer.java, server/src/test/java/org/apache/iotdb/db/engine/compaction/AbstractCompactionTest.java, server/src/test/java/org/apache/iotdb/db/engine/compaction/FastAlignedCrossCompactionTest.java, server/src/test/java/org/apache/iotdb/db/engine/compaction/FastNonAlignedCrossCompactionTest.java, server/src/test/java/org/apache/iotdb/db/engine/compaction/utils/MultiTsFileDeviceIteratorTest.java
See details in [IOTDB-5686](https://issues.apache.org/jira/browse/IOTDB-5686)
=> [IOTDB-5686] Fix devices with the same name but different alignment properties meets error in inner seq compaction

server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/performer/impl/ReadChunkCompactionPerformer.java, server/src/test/java/org/apache/iotdb/db/engine/compaction/AbstractCompactionTest.java, server/src/test/java/org/apache/iotdb/db/engine/compaction/FastAlignedCrossCompactionTest.java, server/src/test/java/org/apache/iotdb/db/engine/compaction/FastNonAlignedCrossCompactionTest.java, server/src/test/java/org/apache/iotdb/db/engine/compaction/utils/MultiTsFileDeviceIteratorTest.java
See details in [IOTDB-5686](https://issues.apache.org/jira/browse/IOTDB-5686)
=> [To rel/1.1][IOTDB-5686] Fix devices with the same name but different alignment properties meets error in inner seq compaction

node-commons/src/assembly/resources/conf/iotdb-common.properties
Fix default comments for previously changed parameters
=> [TO rel/1.1][IOTDB-5704] fix default comments for previously changed parameters

server/src/test/java/org/apache/iotdb/db/metadata/schemaRegion/SchemaStatisticsTest.java
Ignore flaky test  SchemaStatisticsTest.testMemoryStatistics()
=> Ignore flaky test testMemoryStatistics

client-py/SessionExample.py, client-py/iotdb/Session.py, client-py/tests/test_aligned_timeseries.py, client-py/tests/test_session.py, docs/UserGuide/API/Programming-Python-Native-API.md, docs/zh/UserGuide/API/Programming-Python-Native-API.md
This PR removes the python example about tree template. And add retry logic for template interfaces.
=> Remove redundent template example in Python example

client-py/SessionExample.py, client-py/iotdb/Session.py, client-py/tests/test_dataframe.py, client-py/tests/test_delete_data.py, docs/UserGuide/API/Programming-Python-Native-API.md, docs/zh/UserGuide/API/Programming-Python-Native-API.md
=> [To rel/0.13][IOTDB-5711] Support connecting multiple nodes in Python API

server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/process/join/RowBasedTimeJoinOperator.java, server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/process/join/merge/AscTimeComparator.java, server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/process/join/merge/DescTimeComparator.java, server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/process/join/merge/TimeComparator.java
cp from https://github.com/apache/iotdb/pull/9412
=> [To rel/1.1] [IOTDB-5715] Improve the performance of query order by time desc

server/src/main/java/org/apache/iotdb/db/mpp/execution/schedule/DriverScheduler.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/OperatorTreeGenerator.java, server/src/test/java/org/apache/iotdb/db/mpp/plan/plan/PipelineBuilderTest.java
=> [To rel/1.1][IOTDB-5716] Wrong dependency when pipeline consumeOneByOneOperator

server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/source/SeriesScanUtil.java, server/src/test/java/org/apache/iotdb/db/query/reader/series/SeriesScanLimitOffsetPushDownTest.java, tsfile/src/main/java/org/apache/iotdb/tsfile/read/reader/series/PaginationController.java
cp from https://github.com/apache/iotdb/pull/9434
=> [IOTDB-5717] Fix incorrect result when querying with limit push-downing & order by time desc

integration-test/src/test/java/org/apache/iotdb/db/it/alignbydevice/IoTDBAlignByDeviceIT.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/PlanVisitor.java
=> [To rel/1.1] [IOTDB-5722] Fix wrong default execution branch in PlanVisitor

isession/src/main/java/org/apache/iotdb/isession/pool/ISessionPool.java, session/src/main/java/org/apache/iotdb/session/pool/SessionPool.java
add executeLastDataQuery() to ISessionPool and SessionPool
=> [To rel/0.13] Add executeLastDataQuery() to ISessionPool and SessionPool

node-commons/src/main/java/org/apache/iotdb/commons/service/metric/enums/PerformanceOverviewMetrics.java
Fix typo in Performance Overview Related Metrics
=> [IOTDB-5701] Fix typo in Performance Overview Related Metrics

node-commons/src/main/java/org/apache/iotdb/commons/service/metric/enums/PerformanceOverviewMetrics.java
Fix typo in Performance Overview Related Metrics
=> [To rel/1.1][IOTDB-5701] Fix typo in Performance Overview Related Metrics

RELEASE_NOTES.md
Update Release notes for 1.1.0
=> Update Release notes for 1.1.0

RELEASE_NOTES.md
Update Release notes for 1.1.0
=> [To rel/1.1] Update Release notes for 1.1.0

consensus/src/main/java/org/apache/iotdb/consensus/ratis/ApplicationStateMachineProxy.java
cherry pick of https://github.com/apache/iotdb/pull/9452
=> [To rel/1.1][IOTDB-5729] Fix RatisConsensus ResponseMessage conversion error

client-cpp/src/main/Session.cpp, client-cpp/src/main/Session.h, client-cpp/src/test/cpp/sessionIT.cpp, example/client-cpp-example/src/AlignedTimeseriesSessionExample.cpp, example/client-cpp-example/src/SessionExample.cpp
https://issues.apache.org/jira/browse/IOTDB-5714
=> [IOTDB-5714] fix some IoTDB C++ SDK bugs

server/src/main/java/org/apache/iotdb/db/protocol/rest/v1/handler/ExceptionHandler.java
fixed iotdb rest DatabaseNotSetException not found
=> fixed iotdb rest DatabaseNotSetException not found

compile-tools/README.md, server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
Fixed the bug that ext/pipe is created at the shell running dir.
<hr>
This PR has:
<hr>
=> [IOTDB-5743] Fixed the bug that the pipe plugin directory creates at the shell running directory

server/src/main/java/org/apache/iotdb/db/metadata/mtree/MTreeBelowSGCachedImpl.java, server/src/main/java/org/apache/iotdb/db/metadata/mtree/MTreeBelowSGMemoryImpl.java
Recover template activation statistiscs when redoing MLog
=> [IOTDB-5675] Recover template activation statistics when redoing MLog

confignode/src/main/java/org/apache/iotdb/confignode/service/ConfigNode.java, metrics/interface/src/main/java/org/apache/iotdb/metrics/metricsets/net/INetMetricManager.java, metrics/interface/src/main/java/org/apache/iotdb/metrics/metricsets/net/LinuxNetMetricManager.java, metrics/interface/src/main/java/org/apache/iotdb/metrics/metricsets/net/MacNetMetricManager.java, metrics/interface/src/main/java/org/apache/iotdb/metrics/metricsets/net/NetMetrics.java, metrics/interface/src/main/java/org/apache/iotdb/metrics/metricsets/net/WindowsNetMetricManager.java, server/src/main/java/org/apache/iotdb/db/service/metrics/DataNodeMetricsHelper.java
Cherry pick https://github.com/apache/iotdb/pull/9298 to rel/1.1
=> cherry pick network metrics

docker/src/main/DockerCompose/docker-compose-cluster-1c2d.yml, docker/src/main/DockerCompose/docker-compose-host-3c3d.yml, docker/src/main/DockerCompose/docker-compose-standalone.yml, docker/src/main/Dockerfile-1.0.0-datanode, docs/UserGuide/QuickStart/WayToGetIoTDB.md, docs/zh/UserGuide/QuickStart/WayToGetIoTDB.md
=> docker deploy for v1.1.0, update docs and docker-compose files

consensus/src/main/java/org/apache/iotdb/consensus/common/Utils.java, consensus/src/main/java/org/apache/iotdb/consensus/iot/logdispatcher/IndexController.java, consensus/src/main/java/org/apache/iotdb/consensus/ratis/ApplicationStateMachineProxy.java, consensus/src/main/java/org/apache/iotdb/consensus/ratis/RatisConsensus.java, consensus/src/main/java/org/apache/iotdb/consensus/ratis/ResponseMessage.java, consensus/src/main/java/org/apache/iotdb/consensus/ratis/SnapshotStorage.java, consensus/src/main/java/org/apache/iotdb/consensus/ratis/Utils.java, consensus/src/main/java/org/apache/iotdb/consensus/ratis/metrics/IoTDBMetricRegistry.java, consensus/src/main/java/org/apache/iotdb/consensus/ratis/utils/RatisLogMonitor.java, consensus/src/main/java/org/apache/iotdb/consensus/ratis/utils/Utils.java, consensus/src/test/java/org/apache/iotdb/consensus/iot/logdispatcher/IndexControllerTest.java, consensus/src/test/java/org/apache/iotdb/consensus/ratis/SnapshotTest.java, consensus/src/test/java/org/apache/iotdb/consensus/ratis/UtilsTest.java
see https://issues.apache.org/jira/browse/IOTDB-5466
=> [IOTDB-5466] Refactor RaftLog disk monitor to avoid unnecessary snapshots

server/src/main/java/org/apache/iotdb/db/mpp/execution/driver/DriverContext.java, server/src/main/java/org/apache/iotdb/db/mpp/execution/exchange/MPPDataExchangeManager.java
cp from https://github.com/apache/iotdb/pull/9540
=> [To rel/1.1] Fix a memory free bug and delete useless O(N^2) check in DriverContext

server/src/main/java/org/apache/iotdb/db/mpp/execution/fragment/FragmentInstanceContext.java, server/src/main/java/org/apache/iotdb/db/mpp/execution/fragment/FragmentInstanceExecution.java
cp from https://github.com/apache/iotdb/pull/9540
=> [To rel/1.1] Fix Context release source NPE

integration-test/src/test/java/org/apache/iotdb/db/it/query/IoTDBNullOperandIT.java, server/src/main/java/org/apache/iotdb/db/mpp/transformation/dag/column/binary/CompareNonEqualColumnTransformer.java, server/src/main/java/org/apache/iotdb/db/mpp/transformation/dag/column/binary/LogicBinaryColumnTransformer.java
cp https://github.com/apache/iotdb/pull/9539
=> [To rel/1.1][IOTDB-5756] NPE when where predicate is NotEqualExpression and one of subExpression is not exist

docs/UserGuide/Reference/Common-Config-Manual.md, docs/zh/UserGuide/Reference/Common-Config-Manual.md, node-commons/src/assembly/resources/conf/iotdb-common.properties, server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java, server/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java, server/src/main/java/org/apache/iotdb/db/mpp/common/SessionInfo.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/execution/QueryExecution.java, server/src/main/java/org/apache/iotdb/db/query/control/SessionManager.java
cherry-pick 78ee634f17adc27787ee50693dc1c02643bc4f03
=> Adapt insert data by 0.13 client

server/src/main/java/org/apache/iotdb/db/mpp/execution/exchange/sink/ShuffleSinkHandle.java
=> [To rel/1.1][IOTDB-5761] Open channel of ShuffleSinkHandle after the drivertask begins

consensus/src/main/java/org/apache/iotdb/consensus/common/Utils.java, consensus/src/main/java/org/apache/iotdb/consensus/iot/logdispatcher/IndexController.java, consensus/src/main/java/org/apache/iotdb/consensus/ratis/ApplicationStateMachineProxy.java, consensus/src/main/java/org/apache/iotdb/consensus/ratis/RatisConsensus.java, consensus/src/main/java/org/apache/iotdb/consensus/ratis/ResponseMessage.java, consensus/src/main/java/org/apache/iotdb/consensus/ratis/SnapshotStorage.java, consensus/src/main/java/org/apache/iotdb/consensus/ratis/metrics/IoTDBMetricRegistry.java, consensus/src/main/java/org/apache/iotdb/consensus/ratis/utils/RatisLogMonitor.java, consensus/src/main/java/org/apache/iotdb/consensus/ratis/utils/Utils.java, consensus/src/test/java/org/apache/iotdb/consensus/iot/logdispatcher/IndexControllerTest.java, consensus/src/test/java/org/apache/iotdb/consensus/ratis/SnapshotTest.java, consensus/src/test/java/org/apache/iotdb/consensus/ratis/UtilsTest.java
cherry-pick of https://github.com/apache/iotdb/pull/9515
=> [To rel/1.1][IOTDB-5466] Refactor RaftLog disk monitor to avoid unnecessary snapshots

tsfile/src/main/java/org/apache/iotdb/tsfile/read/common/block/column/ColumnEncoderFactory.java
cp from https://github.com/apache/iotdb/pull/9580
=> [To rel/1.1] Improve ineffective check in ColumnEncoderFactory

server/src/main/java/org/apache/iotdb/db/mpp/execution/exchange/sink/ShuffleSinkHandle.java, server/src/main/java/org/apache/iotdb/db/mpp/execution/exchange/sink/SinkChannel.java
cp from https://github.com/apache/iotdb/pull/9589
=> [To rel/1.1] Fix potential NPE in SinkChannel

server/src/main/java/org/apache/iotdb/db/mpp/execution/exchange/sink/SinkChannel.java
cp from https://github.com/apache/iotdb/pull/9591
=> [To rel/1.1] Fix MemoryPool free NPE

docs/UserGuide/Reference/Common-Config-Manual.md, docs/zh/UserGuide/Reference/Common-Config-Manual.md, server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java, server/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java, server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/process/AbstractIntoOperator.java, server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/process/DeviceViewIntoOperator.java, server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/process/IntoOperator.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/OperatorTreeGenerator.java, server/src/test/java/org/apache/iotdb/db/mpp/execution/operator/OperatorMemoryTest.java
(cherry picked from commit 40f00c6cbb8a03cfa77477f3f8763a1e64a422ae)
=> [To rel/1.1] [IOTDB-5763] Optimize the memory estimate for INTO operations

server/src/main/java/org/apache/iotdb/db/query/control/SessionManager.java
Remove session idle metrics when close
=> [IOTDB-5762][Metric] remove session metrics when close

integration-test/src/test/java/org/apache/iotdb/db/it/aggregation/IoTDBTagAggregationIT.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/statement/crud/QueryStatement.java
cp from https://github.com/apache/iotdb/pull/9593/files
=> [To rel/1.1] Fix unexcepted error message when use raw query with Group By Tag

integration-test/src/test/java/org/apache/iotdb/db/it/aggregation/IoTDBTagAggregationIT.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/LogicalPlanBuilder.java
cp https://github.com/apache/iotdb/pull/9603
=> [To rel/1.1] Fix Group By Tag with empty grouped timeseries

metrics/interface/src/main/java/org/apache/iotdb/metrics/utils/MetricLevel.java
=> [IOTDB-5762][Metric] add do nothing level

LICENSE-binary, client-cpp/src/main/Session.h, client-py/iotdb/utils/IoTDBConstants.py, docs/UserGuide/Data-Concept/Compression.md, docs/UserGuide/Ecosystem-Integration/NiFi-IoTDB.md, docs/UserGuide/Reference/Common-Config-Manual.md, docs/zh/UserGuide/Data-Concept/Compression.md, docs/zh/UserGuide/Ecosystem-Integration/NiFi-IoTDB.md, docs/zh/UserGuide/Reference/Common-Config-Manual.md, jdbc/src/main/java/org/apache/iotdb/jdbc/IoTDBDatabaseMetadata.java, node-commons/src/assembly/resources/conf/iotdb-common.properties, pom.xml, tsfile/pom.xml, tsfile/src/main/java/org/apache/iotdb/tsfile/common/conf/TSFileConfig.java, tsfile/src/main/java/org/apache/iotdb/tsfile/compress/ICompressor.java, tsfile/src/main/java/org/apache/iotdb/tsfile/compress/IUnCompressor.java, tsfile/src/main/java/org/apache/iotdb/tsfile/file/metadata/enums/CompressionType.java, tsfile/src/test/java/org/apache/iotdb/tsfile/compress/CompressTest.java, tsfile/src/test/java/org/apache/iotdb/tsfile/compress/ZstdTest.java
=> [To rel/1.1][IOTDB-2569]Support ZSTD Compression (#9231)

server/src/main/java/org/apache/iotdb/db/query/control/SessionManager.java
remove session metrics when close session
=> [To rel/1.1][IOTDB-5762][Metric] remove session metrics when close

confignode/src/main/java/org/apache/iotdb/confignode/manager/pipe/PipeManager.java, confignode/src/main/java/org/apache/iotdb/confignode/manager/pipe/PipeTaskCoordinator.java, confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/pipe/task/CreatePipeProcedureV2.java, confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/pipe/task/DropPipeProcedureV2.java, confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/pipe/task/StartPipeProcedureV2.java, confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/pipe/task/StopPipeProcedureV2.java, confignode/src/test/java/org/apache/iotdb/confignode/consensus/request/ConfigPhysicalPlanSerDeTest.java, confignode/src/test/java/org/apache/iotdb/confignode/persistence/PipeInfoTest.java, node-commons/src/main/java/org/apache/iotdb/commons/pipe/task/meta/PipeRuntimeMeta.java, node-commons/src/main/java/org/apache/iotdb/commons/pipe/task/meta/PipeStaticMeta.java, node-commons/src/main/java/org/apache/iotdb/commons/pipe/task/meta/PipeTaskMeta.java
See https://github.com/apache/iotdb/pull/9533 for more detail.
=> [IOTDB-5727][hotfix] Hide PipeInfo from PipeManager

library-udf/src/main/java/org/apache/iotdb/library/anomaly/UDTFMasterDetect.java, library-udf/src/main/java/org/apache/iotdb/library/anomaly/UDTFMasterTrain.java, library-udf/src/main/java/org/apache/iotdb/library/anomaly/util/KDTreeUtil.java, library-udf/src/main/java/org/apache/iotdb/library/anomaly/util/MasterDetector.java, library-udf/src/main/java/org/apache/iotdb/library/anomaly/util/MasterTrainUtil.java, library-udf/src/main/java/org/apache/iotdb/library/anomaly/util/VAR.java
=> Add two new UDFs: MasterTrain and MasterDetector

docs/UserGuide/Write-And-Delete-Data/Load-External-Tsfile.md, docs/zh/UserGuide/Write-And-Delete-Data/Load-External-Tsfile.md, server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java, server/src/main/java/org/apache/iotdb/db/engine/storagegroup/TsFileResource.java, server/src/main/java/org/apache/iotdb/db/qp/executor/PlanExecutor.java, server/src/main/java/org/apache/iotdb/db/qp/logical/sys/LoadFilesOperator.java, server/src/main/java/org/apache/iotdb/db/qp/physical/sys/OperateFilePlan.java, server/src/main/java/org/apache/iotdb/db/qp/sql/IoTDBSqlVisitor.java
load statement:
load 'filePath'
filePath option: it supports HTTP style URI now, but it only support transporting by HTTP protocal, and can't recognize .mods file.
=> [To rel/0.13][IOTDB-5797] Load remote TsFile

integration-test/src/test/java/org/apache/iotdb/db/it/udf/IoTDBUDTFBuiltinScalarFunctionIT.java, integration-test/src/test/java/org/apache/iotdb/libudf/it/dprofile/DProfileIT.java, node-commons/src/main/java/org/apache/iotdb/commons/udf/builtin/BuiltinTimeSeriesGeneratingFunction.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/AnalyzeVisitor.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/ExpressionAnalyzer.java
see https://apache-iotdb.feishu.cn/docx/VRW9dF5XMog9D2xqZMrczjMvnAg
=> [IOTDB-5735] Fix result of some UDF with align by device is incorrect

confignode/src/main/java/org/apache/iotdb/confignode/manager/ClusterQuotaManager.java, confignode/src/main/java/org/apache/iotdb/confignode/persistence/quota/QuotaInfo.java, integration-test/src/main/java/org/apache/iotdb/it/env/cluster/MppCommonConfig.java, integration-test/src/main/java/org/apache/iotdb/it/env/cluster/MppSharedCommonConfig.java, integration-test/src/main/java/org/apache/iotdb/it/env/remote/RemoteCommonConfig.java, integration-test/src/main/java/org/apache/iotdb/itbase/env/CommonConfig.java, integration-test/src/test/java/org/apache/iotdb/db/it/quotas/IoTDBSpaceQuotaIT.java, node-commons/src/main/java/org/apache/iotdb/commons/conf/IoTDBConstant.java, server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/execution/config/sys/quota/ShowSpaceQuotaTask.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/execution/config/sys/quota/ShowThrottleQuotaTask.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/parser/ASTVisitor.java
docs：[https://apache-iotdb.feishu.cn/docx/BHu0dnhN6oi7ndxcAxMccuDVnEf](https://apache-iotdb.feishu.cn/docx/BHu0dnhN6oi7ndxcAxMccuDVnEf)
The issues raised regarding this document have been fixed：
[https://apache-iotdb.feishu.cn/docx/IerZdPFHroEbRYxKvihcBpncnie](https://apache-iotdb.feishu.cn/docx/IerZdPFHroEbRYxKvihcBpncnie)
=> [IOTDB-5773] fix set space quota problem

server/src/main/java/org/apache/iotdb/db/mpp/execution/exchange/sink/SinkChannel.java
(cherry picked from commit 544a33b0a6cbf5cc136d2861d5de6159b803474c)
=> [To rel/1.1] Fix potential Npe of ShuffleSinkHandle

metrics/interface/src/main/java/org/apache/iotdb/metrics/utils/MetricLevel.java
(cherry picked from commit 935b5106ed1dbbc0641eace92e499120b07a684a)
=> [To rel/1.1][IOTDB-5762][Metric] add do nothing level(#9615)

server/src/main/java/org/apache/iotdb/db/mpp/execution/schedule/DriverScheduler.java
cherry-picked from https://github.com/apache/iotdb/commit/b9fa37c912975340533ea8927afad4b99886df58
=> [To rel/1.1][IOTDB-5786] Fix potential deadlock in DriverScheduler

site/src/main/.vuepress/styles/index.scss
feat(site): fix display error for docs has table
=> feat(site): fix display error for docs has table

docs/UserGuide/Operate-Metadata/Template.md, docs/zh/UserGuide/Operate-Metadata/Template.md
Update the content defined in https://apache-iotdb.feishu.cn/docx/EGNhdVaZYo7KwrxIzUlcCoH2noe to User-Guide.
=> [IOTDB-3565] Update User-Guide for Dynamic Template

server/src/main/java/org/apache/iotdb/db/mpp/execution/QueryStateMachine.java, server/src/main/java/org/apache/iotdb/db/mpp/execution/exchange/sink/ShuffleSinkHandle.java, server/src/main/java/org/apache/iotdb/db/mpp/execution/exchange/source/SourceHandle.java, server/src/test/java/org/apache/iotdb/db/mpp/execution/QueryStateMachineTest.java
cp from https://github.com/apache/iotdb/pull/9656
=> [To rel/1.1] Fix concurrent state change bug in QueryStateMachine

consensus/src/main/java/org/apache/iotdb/consensus/ratis/SnapshotStorage.java
cp of https://github.com/apache/iotdb/pull/9692
=> [To rel/1.1][IOTDB-5183] Use default snapshot installation path for confignode & schema region

integration-test/src/test/java/org/apache/iotdb/db/it/udf/IoTDBUDTFBuiltinFunctionIT.java, integration-test/src/test/java/org/apache/iotdb/libudf/it/dprofile/DProfileIT.java, node-commons/src/main/java/org/apache/iotdb/commons/udf/builtin/BuiltinTimeSeriesGeneratingFunction.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/AnalyzeVisitor.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/ExpressionAnalyzer.java
cp https://github.com/apache/iotdb/pull/9642
(cherry picked from commit e12afecd6ebaa4d9cb267df29787ad2933016841)
=> [To rel/1.1][IOTDB-5735] Fix result of some UDF with align by device is incorrect

node-commons/src/main/java/org/apache/iotdb/commons/concurrent/ThreadName.java
cp from https://github.com/apache/iotdb/pull/9710
=> [To rel/1.1] Correct ASYNC_DATANODE_IOT_CONSENSUS_CLIENT_POOL name

node-commons/src/main/java/org/apache/iotdb/commons/udf/service/UDFClassLoaderManager.java, server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/process/TransformOperator.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/expression/visitor/ColumnTransformerVisitor.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/expression/visitor/IntermediateLayerVisitor.java, server/src/main/java/org/apache/iotdb/db/mpp/transformation/dag/builder/EvaluationDAGBuilder.java, server/src/main/java/org/apache/iotdb/db/mpp/transformation/dag/input/QueryDataSetInputLayer.java, server/src/main/java/org/apache/iotdb/db/mpp/transformation/dag/intermediate/ConstantIntermediateLayer.java, server/src/main/java/org/apache/iotdb/db/mpp/transformation/dag/intermediate/IntermediateLayer.java, server/src/main/java/org/apache/iotdb/db/mpp/transformation/dag/intermediate/MultiInputColumnIntermediateLayer.java, server/src/main/java/org/apache/iotdb/db/mpp/transformation/dag/intermediate/SingleInputColumnMultiReferenceIntermediateLayer.java, server/src/main/java/org/apache/iotdb/db/mpp/transformation/dag/intermediate/SingleInputColumnSingleReferenceIntermediateLayer.java, server/src/main/java/org/apache/iotdb/db/mpp/transformation/dag/udf/UDTFContext.java, server/src/main/java/org/apache/iotdb/db/mpp/transformation/dag/udf/UDTFExecutor.java, server/src/main/java/org/apache/iotdb/db/mpp/transformation/datastructure/SerializableList.java, server/src/main/java/org/apache/iotdb/db/mpp/transformation/datastructure/row/ElasticSerializableRowRecordList.java, server/src/main/java/org/apache/iotdb/db/mpp/transformation/datastructure/row/SerializableRowRecordList.java, server/src/main/java/org/apache/iotdb/db/mpp/transformation/datastructure/tv/ElasticSerializableBinaryTVList.java, server/src/main/java/org/apache/iotdb/db/mpp/transformation/datastructure/tv/ElasticSerializableTVList.java, server/src/main/java/org/apache/iotdb/db/mpp/transformation/datastructure/tv/SerializableTVList.java, server/src/main/java/org/apache/iotdb/db/query/control/QueryResourceManager.java, server/src/main/java/org/apache/iotdb/db/service/TemporaryQueryDataFileService.java, server/src/test/java/org/apache/iotdb/db/query/udf/datastructure/SerializableListTest.java
cherry-picked from [5d77c44](https://github.com/apache/iotdb/commit/5d77c446ea797536ed99632149b37a197e50ed6c)
=> [To rel/1.1][IOTDB-5815] Fix Npe when UDF spilling data to disk

integration-test/src/test/java/org/apache/iotdb/db/it/last/IoTDBLastQueryLastCache2IT.java, integration-test/src/test/java/org/apache/iotdb/db/it/last/IoTDBLastQueryLastCacheIT.java, node-commons/src/main/java/org/apache/iotdb/commons/path/AlignedPath.java, server/src/main/java/org/apache/iotdb/db/metadata/utils/MetaUtils.java, server/src/main/java/org/apache/iotdb/db/mpp/execution/exchange/sink/LocalSinkChannel.java, server/src/main/java/org/apache/iotdb/db/mpp/execution/exchange/sink/SinkChannel.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/distribution/SourceRewriter.java
=> [To rel/1.1] Sort the result of AlignedUpdateLastCacheOperator for LastQueryMergeOperator

server/src/main/java/org/apache/iotdb/db/mpp/execution/driver/Driver.java, server/src/main/java/org/apache/iotdb/db/mpp/execution/schedule/AbstractDriverThread.java
cp  from https://github.com/apache/iotdb/pull/9728
=> [To rel/1.1] Forbid the query executor thread interrupted by other threads

consensus/src/main/java/org/apache/iotdb/consensus/iot/IoTConsensusServerImpl.java
see [jira](https://issues.apache.org/jira/browse/IOTDB-5835)
=> [IOTDB-5835] Fix wal accumulation caused by datanode restart 

consensus/src/main/java/org/apache/iotdb/consensus/iot/IoTConsensusServerImpl.java
see [jira](https://issues.apache.org/jira/browse/IOTDB-5835)
=> [To rel/1.1][IOTDB-5835] Fix wal accumulation caused by datanode restart

server/src/main/java/org/apache/iotdb/db/wal/WALManager.java, server/src/main/java/org/apache/iotdb/db/wal/allocation/FirstCreateStrategy.java, server/src/main/java/org/apache/iotdb/db/wal/buffer/AbstractWALBuffer.java, server/src/main/java/org/apache/iotdb/db/wal/node/WALNode.java, server/src/main/java/org/apache/iotdb/db/wal/recover/WALNodeRecoverTask.java
- add disk usage and file num params in the wal node
- update total disk usage and file num when deleting the wal node
=> [IOTDB-5830] Update disk usage and file num when deleting the wal node

client-py/SessionExample.py, client-py/iotdb/Session.py, client-py/iotdb/utils/IoTDBConnectionException.py, client-py/iotdb/utils/IoTDBRpcDataSet.py
This pr is fixing the issue that IOTDB-5817 mentioned.
Some exception messages are not clear and readable.
=> [IOTDB-5817] Optimize error message of python client

node-commons/src/main/java/org/apache/iotdb/commons/schema/tree/AbstractTreeVisitor.java, server/src/main/java/org/apache/iotdb/db/metadata/mtree/traverser/Traverser.java, server/src/main/java/org/apache/iotdb/db/metadata/mtree/traverser/TraverserWithLimitOffsetWrapper.java, server/src/main/java/org/apache/iotdb/db/metadata/mtree/traverser/basic/DatabaseTraverser.java, server/src/main/java/org/apache/iotdb/db/metadata/mtree/traverser/basic/EntityTraverser.java, server/src/main/java/org/apache/iotdb/db/metadata/mtree/traverser/basic/MNodeTraverser.java, server/src/main/java/org/apache/iotdb/db/metadata/mtree/traverser/basic/MeasurementTraverser.java, server/src/main/java/org/apache/iotdb/db/mpp/common/schematree/visitor/SchemaTreeDeviceVisitor.java, server/src/main/java/org/apache/iotdb/db/mpp/common/schematree/visitor/SchemaTreeMeasurementVisitor.java, server/src/main/java/org/apache/iotdb/db/mpp/common/schematree/visitor/SchemaTreeVisitorWithLimitOffsetWrapper.java, server/src/test/java/org/apache/iotdb/db/metadata/schemaRegion/SchemaRegionBasicTest.java
=> [To rel/1.1][IOTDB-5824] Fix show devices with * cannot display satisfied devices

server/src/main/java/org/apache/iotdb/db/engine/flush/MemTableFlushTask.java, server/src/main/java/org/apache/iotdb/db/service/metrics/CompactionMetrics.java, server/src/main/java/org/apache/iotdb/db/service/metrics/recorder/CompactionMetricsManager.java, server/src/main/java/org/apache/iotdb/db/service/thrift/ProcessorWithMetrics.java, server/src/main/java/org/apache/iotdb/db/service/thrift/impl/ClientRPCServiceImpl.java, server/src/test/java/org/apache/iotdb/db/metric/MetricServiceTest.java
Upgrade Performance Overview Metrics to Core
#9741
=> [To rel/1.1][IOTDB-5701] Upgrade Performance Overview Metrics to Core

consensus/src/main/java/org/apache/iotdb/consensus/config/IoTConsensusConfig.java, consensus/src/main/java/org/apache/iotdb/consensus/iot/logdispatcher/LogDispatcher.java, consensus/src/main/java/org/apache/iotdb/consensus/iot/logdispatcher/LogDispatcherThreadMetrics.java, consensus/src/main/java/org/apache/iotdb/consensus/iot/logdispatcher/SyncStatus.java
see [jira](https://issues.apache.org/jira/browse/IOTDB-5841)
=> [To rel/1.1][IOTDB-5841] Modify IoTConsensus default parameters to improve performance in more scenarios 

integration-test/src/test/java/org/apache/iotdb/db/it/selectinto/IoTDBSelectIntoIT.java, server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/process/DeviceViewIntoOperator.java
=> [IOTDB-5837] Fix exception in select-into of ALIGN BY DEVICE query

consensus/src/main/java/org/apache/iotdb/consensus/config/IoTConsensusConfig.java, consensus/src/main/java/org/apache/iotdb/consensus/iot/logdispatcher/LogDispatcher.java, consensus/src/main/java/org/apache/iotdb/consensus/iot/logdispatcher/LogDispatcherThreadMetrics.java, consensus/src/main/java/org/apache/iotdb/consensus/iot/logdispatcher/SyncStatus.java
see [jira](https://issues.apache.org/jira/browse/IOTDB-5841)
=> [IOTDB-5841] Modify IoTConsensus default parameters to improve performance in more scenarios

consensus/pom.xml
cherry-pick of https://github.com/apache/iotdb/pull/9785
=> [To rel/1.1]Bump ratis version to 2.5.1

node-commons/src/main/java/org/apache/iotdb/commons/path/PartialPath.java, server/src/main/java/org/apache/iotdb/db/metadata/template/ClusterTemplateManager.java, server/src/main/java/org/apache/iotdb/db/service/thrift/impl/DataNodeInternalRPCServiceImpl.java
Clear template cache on DataNode when deleting database
=> [IOTDB-5740] Fix drop database does not delete its template

docs/UserGuide/QuickStart/WayToGetIoTDB.md
The original path to the Dockefile no longer exists, so update the directory to https://github.com/apache/iotdb/tree/master/docker
<hr>
This PR has:
<hr>
=> Fix error path of Dockerfile

confignode/src/main/java/org/apache/iotdb/confignode/manager/schema/ClusterSchemaManager.java
same as https://github.com/apache/iotdb/pull/9800
=> [To rel/1.1][IOTDB-5831] Fix create region failure after recreate db

server/src/main/java/org/apache/iotdb/db/wal/WALManager.java, server/src/main/java/org/apache/iotdb/db/wal/allocation/FirstCreateStrategy.java, server/src/main/java/org/apache/iotdb/db/wal/buffer/AbstractWALBuffer.java, server/src/main/java/org/apache/iotdb/db/wal/node/WALNode.java, server/src/main/java/org/apache/iotdb/db/wal/recover/WALNodeRecoverTask.java
- add disk usage and file num params in the wal node
- update total disk usage and file num when deleting the wal node
=> [To rel/1.1][IOTDB-5830] Update disk usage and file num when deleting the wal node

server/src/main/java/org/apache/iotdb/db/mpp/execution/exchange/SharedTsBlockQueue.java
=> [To rel/1.1] [IOTDB-5851] Fix Npe with limit clause

confignode/src/main/java/org/apache/iotdb/confignode/consensus/request/ConfigPhysicalPlan.java, confignode/src/main/java/org/apache/iotdb/confignode/consensus/request/ConfigPhysicalPlanType.java, confignode/src/main/java/org/apache/iotdb/confignode/consensus/request/read/pipe/task/ShowPipePlanV2.java, confignode/src/main/java/org/apache/iotdb/confignode/consensus/response/pipe/task/PipeTableResp.java, confignode/src/main/java/org/apache/iotdb/confignode/manager/pipe/PipeTaskCoordinator.java, confignode/src/main/java/org/apache/iotdb/confignode/persistence/executor/ConfigPlanExecutor.java, confignode/src/main/java/org/apache/iotdb/confignode/persistence/pipe/PipeTaskInfo.java, thrift-confignode/src/main/thrift/confignode.thrift
See IOTDB-5799 for more detail.
In this PR:
1. implement showPipes in Pipe module
=> [IOTDB-5799] Pipe: Implement showPipes

server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/process/join/HorizontallyConcatOperator.java, server/src/test/java/org/apache/iotdb/db/mpp/execution/operator/OperatorMemoryTest.java
=> [IOTDB-5846] Optimize the memory estimate for HorizontallyConcatOperator

session/src/main/java/org/apache/iotdb/session/pool/SessionPool.java
1. add catch Throwable for OutOfMemoryError、StackOverflowError、BootstrapMethodError、InternalError
2. add this.notify() in getSession()
3. add formattedNodeUrls for logging formatted nodeUrls for logging e.g. "host:port" or "[host:port, host:port, host:port]"
=> [To rel/1.1][IOTDB-5880] add catch Throwable 

server/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java
=> [To rel/1.1] Fix only loading one data directory when start iotdb

consensus/src/main/java/org/apache/iotdb/consensus/iot/IoTConsensusServerImpl.java, consensus/src/main/java/org/apache/iotdb/consensus/iot/logdispatcher/LogDispatcher.java, consensus/src/main/java/org/apache/iotdb/consensus/iot/logdispatcher/SyncStatus.java, consensus/src/test/java/org/apache/iotdb/consensus/iot/logdispatcher/SyncStatusTest.java
- cherry-pick from master.
- https://github.com/apache/iotdb/pull/9844
=> [To rel/1.1][IOTDB-5872] Reduce some IoTConsensus index logs

confignode/src/main/java/org/apache/iotdb/confignode/conf/ConfigNodeConfig.java, confignode/src/main/java/org/apache/iotdb/confignode/conf/ConfigNodeDescriptor.java, confignode/src/main/java/org/apache/iotdb/confignode/manager/node/NodeManager.java, docs/UserGuide/Reference/Common-Config-Manual.md, docs/zh/UserGuide/Reference/Common-Config-Manual.md, node-commons/src/assembly/resources/conf/iotdb-common.properties, server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java, server/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java, server/src/main/java/org/apache/iotdb/db/consensus/DataRegionConsensusImpl.java, thrift-confignode/src/main/thrift/confignode.thrift
- cherry-pick from master.
- https://github.com/apache/iotdb/pull/9797
=> [To rel/1.1][IOTDB-5852] Add some IoTConsensus and RatisConsensus properties

server/src/main/java/org/apache/iotdb/db/service/thrift/ProcessorWithMetrics.java
=> [IOTDB-5862] optimize thrift metrics precision

node-commons/src/main/java/org/apache/iotdb/commons/schema/filter/impl/PathContainsFilter.java, server/src/main/java/org/apache/iotdb/db/metadata/mtree/traverser/basic/EntityTraverser.java, server/src/main/java/org/apache/iotdb/db/metadata/mtree/traverser/basic/MeasurementTraverser.java
=> [IOTDB-5881] Schema query supports case-insensitive path contains filter

session/src/main/java/org/apache/iotdb/session/pool/SessionPool.java
1. add catch Throwable for OutOfMemoryError、StackOverflowError、BootstrapMethodError、InternalError
2. add this.notify() in getSession()
3. add formattedNodeUrls for logging formatted nodeUrls for logging e.g. "host:port" or "[host:port, host:port, host:port]"
=> [IOTDB-5880] Catch Throwable in SessionPool  (#9856)

integration-test/src/test/java/org/apache/iotdb/db/it/aligned/IoTDBAlignedDataDeletionIT.java, server/src/main/java/org/apache/iotdb/db/utils/datastructure/AlignedTVList.java, server/src/test/java/org/apache/iotdb/db/utils/datastructure/VectorTVListTest.java
=> [To rel/1.1][IOTDB-5896] Fix delete aligned TEXT data in TVList NPE

server/src/main/java/org/apache/iotdb/db/conf/OperationType.java, server/src/main/java/org/apache/iotdb/db/engine/cache/BloomFilterCache.java, server/src/main/java/org/apache/iotdb/db/engine/cache/CacheHitRatioMonitor.java, server/src/main/java/org/apache/iotdb/db/engine/cache/TimeSeriesMetadataCache.java, server/src/main/java/org/apache/iotdb/db/mpp/execution/driver/Driver.java, server/src/main/java/org/apache/iotdb/db/mpp/metric/TimeSeriesMetadataCacheMetrics.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/Coordinator.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/execution/IQueryExecution.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/execution/QueryExecution.java, server/src/main/java/org/apache/iotdb/db/service/thrift/impl/ClientRPCServiceImpl.java
1. Change cost time unit from milli to nano
2. merge operator metric together in one driver
3. correct the bloomfilter cache hit ratio and timeseries metadata cache hit ratio
=> Change cost time unit from milli to nano & merge operator metric together in one driver

integration-test/src/test/java/org/apache/iotdb/db/it/orderBy/IoTDBOrderByIT.java, node-commons/src/assembly/resources/conf/iotdb-common.properties, server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/statement/crud/QueryStatement.java
1. change the default size of sort buffer
2. add more semantic check in order by
=> [IOTDB-5890] [IOTDB-5891] Fix messages problem in order by

node-commons/src/main/java/org/apache/iotdb/commons/path/PathPatternTree.java, node-commons/src/test/java/org/apache/iotdb/commons/path/PathPatternTreeTest.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/AnalyzeVisitor.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/parser/ASTVisitor.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/statement/crud/QueryStatement.java
see https://timechor.feishu.cn/docx/MxjAd0Hbro8brZxtMopcZ7HRnCe
=> [IOTDB-5887] Optimize the construction performance of PathPatternTree without wildcards

consensus/src/main/java/org/apache/iotdb/consensus/ratis/ApplicationStateMachineProxy.java, consensus/src/main/java/org/apache/iotdb/consensus/ratis/RatisConsensus.java, consensus/src/main/java/org/apache/iotdb/consensus/ratis/utils/Utils.java, server/src/main/java/org/apache/iotdb/db/consensus/statemachine/DataRegionStateMachine.java
cherry-pick of https://github.com/apache/iotdb/pull/9819
=> [To rel/1.1][IOTDB-5843] Stall write requests when system shutting down

consensus/src/main/java/org/apache/iotdb/consensus/ratis/RatisClient.java
Current retry policy blocks retry when IOExceptions except RaftExceptions are thrown. However, when gRPC channel is disconnected, another type of IOException (StatusRuntimeException) is thrown. We should allow it to be retried.
=> [IOTDB-5848] Allow ratis-client retry when gRPC IO Unavailable

isession/src/main/java/org/apache/iotdb/isession/util/ClusterStatus.java, session/src/main/java/org/apache/iotdb/session/pool/HASessionPool.java
Function description:
Add configuration item (backupNodeurls，backupUsername，backupPassword) to configure the main cluster IP and backup cluster IP, where the main cluster IP is required (can have more than one IP, required) and the backup cluster IP is optional (can have more than one IP, optional)
Function definition:
When the primary cluster is normally connected, the client connects to the primary cluster
When the primary cluster is disconnected, it switches to the backup cluster
When the primary cluster is reconnected, it switches to the primary cluster again
Create a new HASessionPool, use the same as SessionPool, 
Example：
`List<String> nodeUrls = new ArrayList<>();
nodeUrls.add("127.0.0.1:6667");
nodeUrls.add("127.0.0.1:6668");
List<String> backupNodeUrls = new ArrayList<>(); …
=> [To Backup_cluster] ZYSD Backup Cluster

docs/UserGuide/Ecosystem-Integration/Grafana-Plugin.md, docs/zh/UserGuide/Ecosystem-Integration/Grafana-Plugin.md
Update the Grafana plugin user manual using screenshots of Grafana 9.3 version
=> Update the Grafana plugin user manual using screenshots of Grafana 9.3 version

consensus/src/main/java/org/apache/iotdb/consensus/ratis/RatisClient.java
cherry-pick of https://github.com/apache/iotdb/pull/9898
=> [To rel/1.1][IOTDB-5878] Allow ratis-client retry when gRPC IO Unavailable

server/src/main/java/org/apache/iotdb/db/engine/storagegroup/DataRegion.java, server/src/main/java/org/apache/iotdb/db/exception/query/OutOfTTLException.java, server/src/main/java/org/apache/iotdb/db/tools/IoTDBDataDirViewer.java, server/src/main/java/org/apache/iotdb/db/tools/TsFileResourcePrinter.java
cherry-pick 1e6475dac175459d88a034a81dd780c79e2653da
=> [To rel/1.1][IOTDB-5888] Fix some logs didn't consider timestamp precision

integration-test/src/test/java/org/apache/iotdb/db/it/last/IoTDBLastQueryLastCacheIT.java, node-commons/src/main/java/org/apache/iotdb/commons/path/AlignedPath.java, server/src/main/java/org/apache/iotdb/db/metadata/utils/MetaUtils.java, tsfile/src/main/java/org/apache/iotdb/tsfile/utils/Binary.java
=> [To rel/1.1][IoTDB-5861] Use Compartor<Binary> instead of Comparator<String> in last query

server/src/main/java/org/apache/iotdb/db/metadata/plan/schemaregion/impl/SchemaRegionPlanDeserializer.java, server/src/main/java/org/apache/iotdb/db/metadata/plan/schemaregion/impl/SchemaRegionPlanSerializer.java
https://issues.apache.org/jira/browse/IOTDB-5902
=> [IOTDB-5902] fix cluster restart bug about mlog.bin

service-rpc/src/main/java/org/apache/iotdb/rpc/AutoResizingBuffer.java, session/src/main/java/org/apache/iotdb/session/Session.java, session/src/main/java/org/apache/iotdb/session/pool/SessionPool.java
There are too many redundant debug logs printed when running Session client program. This PR is for removing them.
=> [IOTDB-5914] Remove redundant debug log in Session

server/src/main/java/org/apache/iotdb/db/mpp/plan/scheduler/FixedRateFragInsStateTracker.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/scheduler/IFragInstanceStateTracker.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/scheduler/SimpleQueryTerminator.java
=> Avoid rpc invoking for SimpleQueryTerminator when endpoint is local address

confignode/src/main/java/org/apache/iotdb/confignode/manager/ConfigManager.java, node-commons/src/main/java/org/apache/iotdb/commons/conf/CommonConfig.java, node-commons/src/main/java/org/apache/iotdb/commons/conf/CommonDescriptor.java, server/src/main/java/org/apache/iotdb/db/mpp/common/header/ColumnHeaderConstant.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/execution/config/metadata/ShowVariablesTask.java, thrift-confignode/src/main/thrift/confignode.thrift
show variables add a variable timestamp_precision
see more information in [IOTDB-5919](https://issues.apache.org/jira/browse/IOTDB-5919)
=> [IOTDB-5919]show variables add a variable timestamp_precision

integration-test/pom.xml, integration-test/src/test/java/org/apache/iotdb/confignode/it/IoTDBConfigNodeConsensusEfficiencyIT.java
See issue https://issues.apache.org/jira/browse/IOTDB-5906
=> [IOTDB-5906] Resolve metric dependency conflicts for IT module

example/session/pom.xml, example/session/src/main/java/org/apache/iotdb/DataMigrationExample.java, isession/src/main/java/org/apache/iotdb/isession/SessionDataSet.java
cherry pick from master
https://github.com/apache/iotdb/pull/9916
=> [To rel/1.1][IOTDB-5915] Adjust the granularity of data migration example from timeseries to device

consensus/src/main/java/org/apache/iotdb/consensus/iot/IoTConsensusServerImpl.java, node-commons/src/main/java/org/apache/iotdb/commons/consensus/index/impl/IoTConsensusIndex.java, server/src/main/java/org/apache/iotdb/db/consensus/statemachine/IoTConsensusDataRegionStateMachine.java
set peerId and searchIndex in IoTConsensusIndex.
=> [IOTDB-5723] Pipe: Consensus Index

confignode/src/main/java/org/apache/iotdb/confignode/service/ConfigNode.java, docs/UserGuide/Monitor-Alert/Metric-Tool.md, docs/zh/UserGuide/Monitor-Alert/Metric-Tool.md, metrics/interface/src/main/java/org/apache/iotdb/metrics/config/MetricConfig.java, metrics/interface/src/main/java/org/apache/iotdb/metrics/metricsets/UpTimeMetrics.java, server/src/main/java/org/apache/iotdb/db/service/metrics/DataNodeMetricsHelper.java
Add up time metrics to statistic the running time of IoTDB Node
=> [IOTDB-5927] Add up time metric

confignode/src/main/java/org/apache/iotdb/confignode/manager/ConfigManager.java, integration-test/src/test/java/org/apache/iotdb/confignode/it/utils/ConfigNodeTestUtils.java, node-commons/src/main/java/org/apache/iotdb/commons/conf/CommonConfig.java, node-commons/src/main/java/org/apache/iotdb/commons/conf/CommonDescriptor.java, server/src/main/java/org/apache/iotdb/db/mpp/common/header/ColumnHeaderConstant.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/execution/config/metadata/ShowVariablesTask.java, thrift-confignode/src/main/thrift/confignode.thrift
cherry pick from master
https://github.com/apache/iotdb/pull/9936 and https://github.com/apache/iotdb/pull/9946
=> [To rel/1.1][IOTDB-5919]show variables add a variable timestamp_precision (#9936)

consensus/src/main/java/org/apache/iotdb/consensus/common/request/BatchIndexedConsensusRequest.java, consensus/src/main/java/org/apache/iotdb/consensus/iot/IoTConsensusServerImpl.java, consensus/src/main/java/org/apache/iotdb/consensus/iot/logdispatcher/LogDispatcher.java, iotdb-protocol/thrift-iot-consensus/src/main/thrift/iotconsensus.thrift, server/src/main/java/org/apache/iotdb/db/consensus/statemachine/IoTConsensusDataRegionStateMachine.java
Fix [pr](https://github.com/apache/iotdb/pull/9954) error
=> [IOTDB-5723] Pipe progress index: fix NumberFormatException when using IoTConsensus in DataRegion

iotdb-client/isession/src/main/java/org/apache/iotdb/isession/pool/ISessionPool.java, iotdb-client/session/src/main/java/org/apache/iotdb/session/pool/SessionPool.java
SessionPool deletion API
- createAlignedTimeseries
- createAlignedTimeseries
- SessionDataSet executeLastDataQuery(List<String> paths, long lastTime)
- getTimestampPrecision
- insertRecord(String deviceId, long time, List<String> measurements, List<TSDataType> types, Object... values)
- sortTablet
=> [IOTDB-5924] feat(SessionPool): add deletion API 

confignode/src/main/java/org/apache/iotdb/confignode/service/ConfigNode.java, docs/UserGuide/Monitor-Alert/Metric-Tool.md, docs/zh/UserGuide/Monitor-Alert/Metric-Tool.md, metrics/interface/src/main/java/org/apache/iotdb/metrics/config/MetricConfig.java, metrics/interface/src/main/java/org/apache/iotdb/metrics/metricsets/UpTimeMetrics.java, server/src/main/java/org/apache/iotdb/db/service/metrics/DataNodeMetricsHelper.java
Add up time metrics to statistic the running time of IoTDB Node
=> [To rel/1.1][IOTDB-5927] Add up time metric

consensus/src/main/java/org/apache/iotdb/consensus/iot/IoTConsensusServerImpl.java, node-commons/src/main/java/org/apache/iotdb/commons/consensus/index/ProgressIndex.java, node-commons/src/main/java/org/apache/iotdb/commons/consensus/index/ProgressIndexType.java, node-commons/src/main/java/org/apache/iotdb/commons/consensus/index/impl/HybridProgressIndex.java, node-commons/src/main/java/org/apache/iotdb/commons/consensus/index/impl/IoTProgressIndex.java, node-commons/src/main/java/org/apache/iotdb/commons/consensus/index/impl/MinimumProgressIndex.java, node-commons/src/main/java/org/apache/iotdb/commons/consensus/index/impl/RecoverProgressIndex.java, node-commons/src/main/java/org/apache/iotdb/commons/consensus/index/impl/SimpleProgressIndex.java, server/src/main/java/org/apache/iotdb/db/consensus/statemachine/IoTConsensusDataRegionStateMachine.java, server/src/main/java/org/apache/iotdb/db/pipe/agent/runtime/PipeRuntimeAgent.java, server/src/main/java/org/apache/iotdb/db/pipe/agent/runtime/SimpleConsensusProgressIndexAssigner.java, server/src/main/java/org/apache/iotdb/db/service/DataNode.java, server/src/main/java/org/apache/iotdb/db/wal/recover/file/UnsealedTsFileRecoverPerformer.java, server/src/test/java/org/apache/iotdb/db/engine/storagegroup/TsFileResourceProgressIndexTest.java
- Implement of RecoverProgressIndex, used for recovery of StorageEngine
- Implement of HybridProgressIndex, used for hybrid progress index update and compare.
- Update progress index for recovering TsFileResource.
=> [IOTDB-5935] Pipe: RecoverProgressIndex and HybridProgressIndex

confignode/src/main/java/org/apache/iotdb/confignode/conf/SystemPropertiesUtils.java
Now the parameters in system.properties will force cover the user configurations.
=> [IOTDB-5934] Let series_slot_num compatible

server/src/main/java/org/apache/iotdb/db/mpp/execution/driver/DataDriver.java, server/src/main/java/org/apache/iotdb/db/mpp/execution/driver/SchemaDriver.java, server/src/main/java/org/apache/iotdb/db/mpp/execution/fragment/FragmentInstanceContext.java, server/src/main/java/org/apache/iotdb/db/mpp/execution/fragment/FragmentInstanceExecution.java, server/src/main/java/org/apache/iotdb/db/mpp/execution/fragment/FragmentInstanceManager.java, server/src/test/java/org/apache/iotdb/db/mpp/execution/DataDriverTest.java
=> [To rel/1.1] Release resource of FI after all drivers have been closed

grafana-plugin/pkg/plugin/plugin.go
Fix the display milliseconds issue with the Grafana plugin
=> Fix the display milliseconds issue with the Grafana plugin

server/src/main/java/org/apache/iotdb/db/rescon/PrimitiveArrayManager.java
Some process on data type in PrimitiveArrayManager are left out when add new data type Unknown, which results in UnsupportedException
=> Fix data type error during data insertion

server/src/main/java/org/apache/iotdb/db/rescon/PrimitiveArrayManager.java, server/src/test/java/org/apache/iotdb/db/utils/datastructure/PrimitiveArrayManagerTest.java
Add UT for PrimitiveArrayManager adaption for UNKNOWN data type
=> Add UT for PrimitiveArrayManager adaption for UNKNOWN data type

integration-test/src/test/java/org/apache/iotdb/db/it/groupby/IoTDBGroupByCountIT.java, server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/parameter/GroupByParameter.java
(cherry picked from commit 710e7fb6acf5176f2511570812aae818e18b9be0)
=> [To rel/1.2][IOTDB-5960] Fix bug in groupByCount in 1C3D

server/src/main/java/org/apache/iotdb/db/mpp/execution/exchange/SharedTsBlockQueue.java
ListableFuture sets the future state to done and then executes the callbacks. We need to make sure that TsBlock blocked on memory is added in queue before the next TsBlock returned by root operator, otherwise we may get the wrong ordered TsBlock.
=> [IOTDB-5963] Make sure that TsBlock blocked on memory is added in queue before the next TsBlock returned by root operator

server/src/main/java/org/apache/iotdb/db/mpp/execution/exchange/SharedTsBlockQueue.java
=> [To rel/1.2][IOTDB-5963] Make sure that TsBlock blocked on memory is added in queue before the next TsBlock returned by root operator

server/src/main/java/org/apache/iotdb/db/mpp/common/schematree/ClusterSchemaTree.java, server/src/test/java/org/apache/iotdb/db/mpp/common/schematree/ClusterSchemaTreeTest.java
same as https://github.com/apache/iotdb/pull/10039
=> Fix SchemaTree.hasView check during query analysis

docs/UserGuide/Reference/Common-Config-Manual.md, docs/zh/UserGuide/Reference/Common-Config-Manual.md, node-commons/src/assembly/resources/conf/iotdb-common.properties
same as https://github.com/apache/iotdb/pull/10047/
=> Add schema_ engine_mode config to iotdb-commons.properties and User-Guide

tsfile/src/main/java/org/apache/iotdb/tsfile/write/record/Tablet.java, tsfile/src/test/java/org/apache/iotdb/tsfile/write/record/TabletTest.java
- Revision of Tablet serialize and deserialize
- add UT
=> [IOTDB-5966] Pipe: Revision of Tablet serialize and deserialize

node-commons/src/assembly/resources/conf/iotdb-common.properties, server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java, server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/task/CrossSpaceCompactionTask.java, server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/task/InnerSpaceCompactionTask.java, server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/utils/CompactionUtils.java, server/src/test/java/org/apache/iotdb/db/engine/compaction/CompactionValidationTest.java
This PR add tsfile validation after compaction.
=> [IOTDB-5969] [To rel/1.1] Add tsfile validate after compaction

node-commons/src/main/java/org/apache/iotdb/commons/consensus/index/impl/RecoverProgressIndex.java, server/src/main/java/org/apache/iotdb/db/pipe/agent/runtime/PipeRuntimeAgent.java, server/src/main/java/org/apache/iotdb/db/pipe/agent/runtime/SimpleConsensusProgressIndexAssigner.java, server/src/main/java/org/apache/iotdb/db/wal/recover/file/UnsealedTsFileRecoverPerformer.java
- Fix RecoverProgressIndex not working for recovery
=> [IOTDB-5974] Pipe: Fix Recover ProgressIndex 

server/src/main/java/org/apache/iotdb/db/engine/storagegroup/TsFileProcessor.java, server/src/main/java/org/apache/iotdb/db/engine/storagegroup/TsFileResource.java, server/src/test/java/org/apache/iotdb/db/engine/settle/SettleRequestHandlerTest.java, server/src/test/java/org/apache/iotdb/db/engine/storagegroup/DataRegionTest.java
=> [To rel/1.2]Fix TsfileResource error after delete device in sequence working memtable

server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java, server/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java
Use a better manner to process default storage engine memory proportion.
=> Fix storage engine memory config initialization

server/src/main/java/org/apache/iotdb/db/pipe/agent/task/PipeTaskAgent.java, server/src/main/java/org/apache/iotdb/db/pipe/collector/historical/PipeHistoricalDataRegionTsFileCollector.java, server/src/main/java/org/apache/iotdb/db/pipe/event/common/row/PipeBinaryTransformer.java, server/src/main/java/org/apache/iotdb/db/pipe/event/common/row/PipeRow.java, server/src/main/java/org/apache/iotdb/db/pipe/event/common/row/PipeRowCollector.java, server/src/main/java/org/apache/iotdb/db/pipe/event/common/tsfile/PipeTsFileInsertionEvent.java, server/src/main/java/org/apache/iotdb/db/pipe/event/common/tsfile/TsFileInsertionDataContainer.java, server/src/main/java/org/apache/iotdb/db/pipe/event/common/tsfile/TsFileInsertionDataTabletIterator.java, server/src/main/java/org/apache/iotdb/db/pipe/processor/PipeDoNothingProcessor.java, server/src/main/java/org/apache/iotdb/db/pipe/task/PipeTaskBuilder.java, server/src/main/java/org/apache/iotdb/db/pipe/task/stage/PipeTaskCollectorStage.java, server/src/main/java/org/apache/iotdb/db/pipe/task/stage/PipeTaskProcessorStage.java, server/src/test/java/org/apache/iotdb/db/pipe/event/TsFileInsertionDataContainerTest.java
* [IOTDB-5979] Pipe: validation and customization failures during the first run of the PipeProcessor will affect the creation of subsequent pipes
* [IOTDB-5977] Pipe: start-time and end-time in collector.history are not working correctly 
* [IOTDB-5981] Pipe: fail to process realtime TEXT data with pattern filter
=> [IOTDB-5977][IOTDB-5979][IOTDB-5981] Pipe: serveral bug fixes in pipe execution engine

server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java, server/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java
Use a better manner to process default schema memory proportion.
=> [To rel/1.2] Fix schema memory config initialization

server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java, server/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java
=> [To rel/1.2]Fix storage engine memory config initialization
