apache/iotdb

grafana/pom.xml, iotdb-cli/pom.xml, iotdb-cli/src/test/java/org/apache/iotdb/cli/client/AbstractClientIT.java, iotdb-cli/src/test/java/org/apache/iotdb/cli/client/StartClientScriptIT.java, iotdb/pom.xml, iotdb/src/test/java/org/apache/iotdb/db/integration/IoTDBAuthorizationIT.java, iotdb/src/test/java/org/apache/iotdb/db/integration/IoTDBCompleteIT.java, iotdb/src/test/java/org/apache/iotdb/db/integration/IoTDBDaemonIT.java, iotdb/src/test/java/org/apache/iotdb/db/integration/IoTDBEngineTimeGeneratorIT.java, iotdb/src/test/java/org/apache/iotdb/db/integration/IoTDBLargeDataIT.java, iotdb/src/test/java/org/apache/iotdb/db/integration/IoTDBLimitSlimitIT.java, iotdb/src/test/java/org/apache/iotdb/db/integration/IoTDBMetadataFetchIT.java, iotdb/src/test/java/org/apache/iotdb/db/integration/IoTDBMultiSeriesIT.java, iotdb/src/test/java/org/apache/iotdb/db/integration/IoTDBSequenceDataQueryIT.java, iotdb/src/test/java/org/apache/iotdb/db/integration/IoTDBSeriesReaderIT.java, iotdb/src/test/java/org/apache/iotdb/db/integration/IoTDBTimeZoneIT.java, jdbc/pom.xml, service-rpc/pom.xml, tsfile/pom.xml
Fix https://issues.apache.org/jira/browse/IOTDB-2
Now we can use :
* `mvn test` to run all UTs.
* `mvn package -DskipTests` to skip all UTs.
* `mvn package -Dtsfile.test.skip` to skip all UTs in Tsfile Module.
** `-Diotdb.test.skip`, `-Djdbc.test.skip`, `-Drpc.test.skip`, `-Dgrafana.test.skip` and  `-Dcli.test.skip` are similar.
* `mvn verify` to run all ITs.
* `mvn verify -Dtsfile.it.skip` to skip all ITs.
** similarly, you can use`-Diotdb.it.skip`, `-Djdbc.it.skip`, `-Drpc.it.skip`, `-Dgrafana.it.skip` and  `-Dcli.it.skip`
* `mvn install` to run all Tests (both UTs and ITs).
What are UTs: java files which are in `src/test/java/` and have suffix with `Test.java` 
What are ITs: java files which are in `src/test/java/` and have suffix with `IT.java`
=> fix issue IOTDB-2, separate UTs and ITs

iotdb/iotdb/conf/iotdb-engine.properties, iotdb/src/main/java/org/apache/iotdb/db/concurrent/ThreadName.java, iotdb/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java, iotdb/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java, iotdb/src/main/java/org/apache/iotdb/db/writelog/io/ILogWriter.java, iotdb/src/main/java/org/apache/iotdb/db/writelog/io/LogWriter.java, iotdb/src/main/java/org/apache/iotdb/db/writelog/manager/MultiFileLogNodeManager.java, iotdb/src/main/java/org/apache/iotdb/db/writelog/node/ExclusiveWriteLogNode.java, iotdb/src/main/java/org/apache/iotdb/db/writelog/node/WriteLogNode.java, iotdb/src/test/java/org/apache/iotdb/db/writelog/PerformanceTest.java
1. Use thread to call outputStream.force periodically to solve WAL perf issue. See https://issues.apache.org/jira/browse/IOTDB-4
2. Add a new parameter ```forceWalPeriodInMs```
3. Remove redundant parameter  ```wal_cleanup_threshold```
=> [IOTDB-4] Force WAL in thread periodically

iotdb/iotdb/conf/iotdb-env.bat, iotdb/iotdb/conf/iotdb-env.sh
I have tested on Mac for jdk8, jdk11 and openjdk11, on windows for jdk8, jdk11 and openjdk11
Especially,openjdk11 is downloaded from http://jdk.java.net/11/
java -version
openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)
=> [IOTDB-18] Improve startup script compatible for jdk11

.travis.yml
By applying this PR,  Travis-CI will have the following jobs:
* osx-oraclejdk8 
* osx-oraclejdk11 
* osx-openjdk8
* osx-openjdk11
* linux-oraclejdk8 (ubuntu)
* linux-oraclejdk11 (ubuntu)
* linux-openjdk8 (ubuntu)
* linux-openjdk11 (ubuntu)
* Windows-jdk8 (oracle JDK)
* WIndows-jdk11 (oracle JDK)
=> Add 3 OS platforms and 2 JDK versions on Travis

iotdb/src/main/java/org/apache/iotdb/db/service/JDBCService.java, iotdb/src/test/java/org/apache/iotdb/db/integration/IoTDBAuthorizationIT.java, iotdb/src/test/java/org/apache/iotdb/db/integration/IoTDBCompleteIT.java, iotdb/src/test/java/org/apache/iotdb/db/integration/IoTDBDaemonIT.java, iotdb/src/test/java/org/apache/iotdb/db/integration/IoTDBEngineTimeGeneratorIT.java, iotdb/src/test/java/org/apache/iotdb/db/integration/IoTDBLargeDataIT.java, iotdb/src/test/java/org/apache/iotdb/db/integration/IoTDBLimitSlimitIT.java, iotdb/src/test/java/org/apache/iotdb/db/integration/IoTDBMetadataFetchIT.java, iotdb/src/test/java/org/apache/iotdb/db/integration/IoTDBMultiSeriesIT.java, iotdb/src/test/java/org/apache/iotdb/db/integration/IoTDBSequenceDataQueryIT.java, iotdb/src/test/java/org/apache/iotdb/db/integration/IoTDBSeriesReaderIT.java, iotdb/src/test/java/org/apache/iotdb/db/integration/IoTDBTimeZoneIT.java
Before this commit, if you run `mvn clean verify` to trigger IT, you will see some logs like
```
ERROR [2019-02-13 11:42:31,571] [JDBC-ServerServiceImpl] org.apache.iotdb.db.service.JDBCService$JDBCServiceThread:181 - IoTDB: failed to start JDBC ServerService, because  
org.apache.thrift.transport.TTransportException: Could not create ServerSocket on address 0.0.0.0/0.0.0.0:6667.
at org.apache.thrift.transport.TServerSocket.<init>(TServerSocket.java:109)
at org.apache.thrift.transport.TServerSocket.<init>(TServerSocket.java:91)
at org.apache.thrift.transport.TServerSocket.<init>(TServerSocket.java:83)
at org.apache.thrift.transport.TServerSocket.<init>(TServerSocket.java:76)
at org.apache.iotdb.db.service.JDBCService$JDBCServiceThread.run(JDBCService.java:171)
Caused by: …
```
=> [WAIT FOR JENKINS PIPELINE]add sync function for jdbc server to  close and remove sleep fuction in ITs

grafana/pom.xml, iotdb-cli/pom.xml, iotdb/pom.xml, jdbc/pom.xml, service-rpc/pom.xml, tsfile/pom.xml
without the parameter, we have to skip UTs and run ITs by: 
`mvn integration-test -Dtsfile.ut.test=true -Djdbc.ut.test.test=true -Diotdb.ut.test=true -Dcli.ut.test=true -Drpc.ut.test=true`
Using `skipUTs`, we can skip all UTs by:
`mvn integration-test -DskipUTs`
Tips: skip all tests: `mvn integration-test -DskipTests` or `mvn package -DskipTests` or `mvn package -DskipUTs`
just skip all ITs: `mvn package`
=> add  to skip all UTs: maven integration-test -DskipUTS=true

iotdb/iotdb/bin/start-server.bat
I optimized the jdk version checking logic in this PR, and checked on Win 10 with Oracle JDK8 and OpenJDK11+28
=> [IOTDB-18] Fix start script for jdk 11 on Win OS

iotdb/src/main/java/org/apache/iotdb/db/utils/OpenFileNumUtil.java, iotdb/src/test/java/org/apache/iotdb/db/utils/OpenFileNumUtilTest.java
1.Remove usage of `com.sun.management.UnixOperatingSystemMXBean` and use lsof command for all open file number statistics. 
2.Check the output of lsof command to exam whether the lsof command is valid.
=> [IOTDB-7] Fix OpenFileNumUtilTest

tsfile/src/main/java/org/apache/iotdb/tsfile/read/ReadOnlyTsFile.java, tsfile/src/main/java/org/apache/iotdb/tsfile/read/controller/MetadataQuerierByFileImpl.java, tsfile/src/test/java/org/apache/iotdb/tsfile/read/controller/MetadataQuerierByFileImplTest.java
Add partition start and end offset constraints when loading chunkGroupMetaData.
This interface will be used by updated spark-tsfile-connector when querying partitioned file.
=> add partition start and end offset constraints when loading chunkGroupMetaData 

pom.xml
This is a better way to implement #62 .
Now users can define their location of the thrift compiler:
`mvn clean package -DskipTests -Dthrift.download-url="<any file you like>" -Dthrift.exec.absolute.path="<Your thrift compiler>"`
For example, on my Mac, I have installed thrift by:
`brew install thrift@0.9`
Then we can skip downloading a thrift compiler again by:
`mvn clean package -DskipTests -Dthrift.download-url="http://w.apache.org/licenses/LICENSE-2.0.txt" -Dthrift.exec.absolute.path="/usr/local/opt/thrift@0.9/bin/thrift"`
=> enable users define the location of their thrift compiler

.travis.yml
because Travis has something wrong with installing oracleJDK11 (by using `choco install`), I deactive the environment temporary.
=> temporary deactive win10+oracleJDK11 on travis

jdbc/src/main/java/org/apache/iotdb/jdbc/IoTDBMetadataResultSet.java
Since IoTDBMetadataResultSet  extends ResultSetMetaData, it can use close() function in super class.
=> [IOTDB-34] implement close function for IoTDBMetadataResultSet

tsfile/src/main/java/org/apache/iotdb/tsfile/write/writer/NativeRestorableIOWriter.java, tsfile/src/main/java/org/apache/iotdb/tsfile/write/writer/TsFileIOWriter.java, tsfile/src/test/java/org/apache/iotdb/tsfile/write/writer/NativeRestorableIOWriterTest.java
By default the autoRepair is true.
Notice that, if the file does not contain a correct magic string header, we will never repair it.
=> [IOTDB-39]add autoRepair option for NativeRestorableIOWriter

iotdb/src/main/java/org/apache/iotdb/db/engine/memtable/TimeValuePairInMemTable.java, iotdb/src/main/java/org/apache/iotdb/db/engine/memtable/WritableMemChunk.java, iotdb/src/main/java/org/apache/iotdb/db/utils/PrimitiveArrayList.java, iotdb/src/main/java/org/apache/iotdb/db/utils/TimeValuePair.java
Now, when we write data into memory, the data is not sorted.
Before we flush data on disk, we need to call getSortedTimeValuePairList() to get the sorted data.
However, current method is implemented by:
```
Map<> tmp = new TreeMap();
tmp.putAll();
List<> result = new ArrayList();
tmp.forEach( x -> result.add(x));
```
TreeMap.put() is O(N), the total time complexity is O(N^2), which is not good for this scenario.
We can change it to 
```
Map<> tmp = new HashMap(length);
tmp.putAll();
List<> result = new ArrayList(length);
tmp.forEach( x -> result.add(x));
result.sort();
```
Then, the time complexity is O(N) + O(Nlog(N)).
In my experiments, it can save 1/3 time.
=> [IOTDB-56] faster memtable.getSortedTimeValuePairList

tsfile/example/src/main/java/org/apache/iotdb/tsfile/TsFileSequenceRead.java
tsfile/example/src/main/java/org/apache/iotdb/tsfile/TsFileSequenceRead has a bug:
if the data type is Float and the TsFile uses RLE encoding, when we read data by using this class, an exception will occur if there are more than 2 pages in a chunk. 
It is because that for each page, we need to either call `valueDecoder.reset()` or generate a new decoder. However, the example java file does not.
=> [IOTDB-67] call valueDecoder reset() when reading data from a new Page

iotdb/src/main/java/org/apache/iotdb/db/metadata/MGraph.java, iotdb/src/main/java/org/apache/iotdb/db/metadata/MManager.java, iotdb/src/main/java/org/apache/iotdb/db/metadata/MTree.java, iotdb/src/test/java/org/apache/iotdb/db/metadata/MManagerBasicTest.java, iotdb/src/test/java/org/apache/iotdb/db/metadata/MTreeTest.java
Add a method to check whether a input path has already been set to storage level or not. This method will be used in Cluster module. It helps a node to decide whether it is able to execute a cammand or not.
=> add check SG for MManager, MGraph and MTree

iotdb/src/main/java/org/apache/iotdb/db/query/control/OpenedFilePathsManager.java, iotdb/src/main/java/org/apache/iotdb/db/query/control/QueryDataSourceManager.java, iotdb/src/main/java/org/apache/iotdb/db/query/control/QuerySession.java, iotdb/src/main/java/org/apache/iotdb/db/query/control/QueryTokenManager.java, iotdb/src/main/java/org/apache/iotdb/db/query/executor/EngineQueryRouter.java, iotdb/src/main/java/org/apache/iotdb/db/service/TSServiceImpl.java, iotdb/src/test/java/org/apache/iotdb/db/integration/IoTDBEngineTimeGeneratorIT.java, iotdb/src/test/java/org/apache/iotdb/db/integration/IoTDBSequenceDataQueryIT.java, iotdb/src/test/java/org/apache/iotdb/db/integration/IoTDBSeriesReaderIT.java, iotdb/src/test/java/org/apache/iotdb/db/query/control/FileReaderManagerTest.java, iotdb/src/test/java/org/apache/iotdb/db/utils/EnvironmentUtils.java
I move the threadLocal jobId out of OpenedFilePathsManager and QueryTokenManager, and put it into a class QuerySession.
Notice, this PR is for modifying branch `aggregate`, because the branch has too many modifications already..
=> refactor QueryTokenManager: move threadlocal as QuerySession

iotdb/src/main/java/org/apache/iotdb/db/metadata/MGraph.java, iotdb/src/main/java/org/apache/iotdb/db/metadata/MManager.java, iotdb/src/main/java/org/apache/iotdb/db/metadata/MTree.java, iotdb/src/test/java/org/apache/iotdb/db/metadata/MManagerBasicTest.java, iotdb/src/test/java/org/apache/iotdb/db/metadata/MTreeTest.java
Add a method to check whether the storage group of a input path exists or not. This method will be used in Cluster module. It helps data state machine to decide whether it needs to execute null-read in meta group while applying a task of adding path or not.
=> Add check existence of storage group of path for MManager, MGraph and MTree

iotdb/src/main/java/org/apache/iotdb/db/metadata/MGraph.java, iotdb/src/main/java/org/apache/iotdb/db/metadata/MManager.java, iotdb/src/main/java/org/apache/iotdb/db/metadata/MTree.java, iotdb/src/test/java/org/apache/iotdb/db/metadata/MManagerBasicTest.java, iotdb/src/test/java/org/apache/iotdb/db/metadata/MTreeTest.java
Add method getAllSGByFile() for MManager. If it only returns one SG, then one of the input path's parents is storage level; if it returns mltiple SGs, then they are all children of the input path.
=> Add method getAllSGByFile() for MManager

iotdb/src/test/java/org/apache/iotdb/db/utils/EnvironmentUtils.java
DO NOT USE `System.exit()` on UT/IT, otherwise you will get strange exceptions on Maven, such as 
```
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /Users/travis/build/apache/incubator-iotdb/iotdb && /Library/Java/JavaVirtualMachines/openjdk-11.0.1.jdk/Contents/Home/bin/java -Xmx1024m -jar /Users/travis/build/apache/incubator-iotdb/iotdb/target/surefire/surefirebooter16362168734376324752.jar /Users/travis/build/apache/incubator-iotdb/iotdb/target/surefire 2019-04-04T14-53-10_334-jvmRun1 surefire2394193058867177217tmp surefire_22130719079866104819tmp
[ERROR] Error occurred in starting fork, check output in log
[ERROR] Process Exit Code: 1 …
```
=> remove system.exit() on Test for better checking the problem when running test

iotdb/src/main/java/org/apache/iotdb/db/engine/bufferwrite/BufferWriteProcessor.java, iotdb/src/main/java/org/apache/iotdb/db/engine/overflow/io/OverflowProcessor.java
If we call flush() twice (and in the 2nt calling, `value count` = 0), then the first future instance will be replaced. If there is exception in the first flush process, we will have no idea to catch it.
In this PR, we will wait to finish the last flush process before submitting a new one.
=> fix the future instance is replaced when the flush frequency is high

iotdb/iotdb/conf/logback.xml
In this way, we can analyze the log following the timeline.
=> add a log appender: put info, warn, error log into one file; disable log_info by default

tsfile/src/main/java/org/apache/iotdb/tsfile/write/TsFileWriter.java, tsfile/src/test/java/org/apache/iotdb/tsfile/write/TsFileReadWriteTest.java
This is a case to reduce redundant codes by using Lambda expression.
We can use this style in UTs to make the codes more concise (but be careful in `src/main` for the performance consideration)
=> make TsFileWriter as AutoClosable; make TsFileReadWriteTest more concise

iotdb/src/main/java/org/apache/iotdb/db/service/TSServiceImpl.java, iotdb/src/main/java/org/apache/iotdb/db/sql/parse/ParseDriver.java
set parsing incorrect cmd as tracing level log in ParseDriver;
set TsserviceImple failed executing as info leve log;
the are for fixing the following notifications:
=> degrade log level in ParseDriver and TSServiceImpl

pom.xml
Now the apache-rat checker just print a summary on console, 
but as we can not get the rat.txt file from Travis-CI platform, we have to print the detailed result on console, like this:
=> print apache-rat violation result on console

iotdb/src/main/java/org/apache/iotdb/db/engine/querycontext/ReadOnlyMemChunk.java
In `ReadOnlyMemChunk`, the memSeries is useless after calling `init()`, so I set it to null to let GC collect it asap.
=> try to release memory asap in ReadOnlyMemChunk

iotdb/iotdb/conf/iotdb-env.sh
When I run `incubator-iotdb/iotdb/iotdb/bin/start-server.sh` on Unix/OS X, the output in console is
```bash
Starting IoTDB
Maximum memory allocation pool = 4096MMB, initial memory allocation pool = 800MMB
...
```
You can see that there are redundant "M"s in " `4096MMB`"  and "`800MMB`". I have just removed them.
The problem comes from the duplicate declaration of "M" in line 78 & 149 of file `incubator-iotdb/iotdb/iotdb/conf/iotdb-env.sh`:
- Line 78
```bash
MAX_HEAP_SIZE="${max_heap_size_in_mb}M"
```
- Line 149
```bash
echo "Maximum memory allocation pool = ${MAX_HEAP_SIZE}MB, initial memory allocation pool = ${HEAP_NEWSIZE}MB"
```
After changing the Line 149:
```bash
echo "Maximum memory allocation pool = ${MAX_HEAP_SIZE}B, initial memory …
```
=>  Fix a clerical error in console display when run 'start-server.sh'

iotdb/src/main/java/org/apache/iotdb/db/engine/filenode/FileNodeManager.java, iotdb/src/main/java/org/apache/iotdb/db/engine/filenode/FileNodeProcessor.java, iotdb/src/main/java/org/apache/iotdb/db/exception/FileNodeManagerException.java
In the current implementation, the counting management control of reading resources in FileNodeProcessor is implemented by lock, which will have a negative impact on the distributed reading process, so I change to use AtomicInteger for counting management of reading resources instead of using lock.
=> Refactor query resource count

iotdb/src/main/java/org/apache/iotdb/db/qp/executor/AbstractQueryProcessExecutor.java, iotdb/src/main/java/org/apache/iotdb/db/qp/executor/IQueryProcessExecutor.java, iotdb/src/main/java/org/apache/iotdb/db/service/TSServiceImpl.java, iotdb/src/test/java/org/apache/iotdb/db/qp/utils/MemIntQpExecutor.java, jdbc/src/main/java/org/apache/iotdb/jdbc/IoTDBStatement.java
`fetchSize` is a parameter used to control the size of the query dataset that the client fetches from the server at a time. The default value of `fetchSize` is 10000 as set in `Config`.
From the client JDBC side, `fetchSize` is an attribute of `IoTDBStatement` and it is passed to the server as shown by the following two lines when JDBC implements `nextWithoutConstraints` to get the query result:
> TSFetchResultsReq req = new TSFetchResultsReq(sql, fetchSize, queryId);
> TSFetchResultsResp resp = client.fetchResults(req); 
From the server side, `fetchSize` is used in `TSServiceImpl.fetchResults` by the following two lines:
1. > queryDataSet = createNewDataSet(statement, fetchSize, req);
2. > QueryDataSetUtils.convertQueryDataSetByFetchSize(queryDataSet, fetchSize)
However, `fetchSize` is …
=> remove useless fetchSize in some places

iotdb/src/main/java/org/apache/iotdb/db/engine/storagegroup/TsFileProcessor.java, iotdb/src/test/java/org/apache/iotdb/db/engine/memtable/MemTableFlushTaskTest.java, iotdb/src/test/java/org/apache/iotdb/db/engine/storagegroup/TsFileProcessorTest.java, tsfile/src/main/java/org/apache/iotdb/tsfile/file/metadata/ChunkMetaData.java, tsfile/src/main/java/org/apache/iotdb/tsfile/file/metadata/TsDigest.java, tsfile/src/main/java/org/apache/iotdb/tsfile/file/metadata/statistics/Statistics.java, tsfile/src/main/java/org/apache/iotdb/tsfile/read/TsFileSequenceReader.java, tsfile/src/main/java/org/apache/iotdb/tsfile/write/writer/RestorableTsFileIOWriter.java, tsfile/src/test/java/org/apache/iotdb/tsfile/file/metadata/utils/TestHelper.java
In IoTDB system, if a file is found incomplete when restoring, it will be attempted to repair and rebuild metadata information, but the rebuilt metadata information does not contain statistical information, which leads to the error of null pointer when querying such files.
corresponding Jira link:https://issues.apache.org/jira/browse/IOTDB-129
=> [IOTDB-129]Fix statistic bug when restoring incomplete tsfile

docs/Documentation/UserGuideV0.7.0/7-Tools-spark.md, pom.xml, spark/README.md, spark/src/main/scala/org/apache/iotdb/tsfile/Converter.scala, spark/src/main/scala/org/apache/iotdb/tsfile/TsFileOutputWriter.scala, spark/src/main/scala/org/apache/iotdb/tsfile/TsFileWriterFactory.scala, spark/src/test/scala/org/apache/iotdb/tsfile/ConverterTest.scala
Improve tsfile-spark-connector to support spark 2.4.3 as is mentioned in [issue IOTDB-91](https://issues.apache.org/jira/browse/IOTDB-91).
Spark has [decoupled internal Row from external Row](https://github.com/apache/spark/pull/6792),  which influences _TsFileWriterFactory_ (extends _OutputWriterFactory_) and _TsFileOutputWriter_ (extends _OutputWriter_). Therefore, function _toTsRecord_ has to change param type from _Row_ to _InternalRow_.
=> [IOTDB-91] Improve tsfile-spark-connector to support spark 2.4.3

docs/Community-Powered By.md, docs/Development.md, docs/Documentation-CHN/QuickStart.md, docs/Documentation-CHN/UserGuideV0.7.0/7-Tools-Cli.md, docs/Documentation-CHN/UserGuideV0.7.0/7-Tools-Grafana.md, docs/Documentation/Frequently asked questions.md, docs/Documentation/OtherMaterial-ReleaseNotesV0.7.0.md, docs/Documentation/OtherMaterial-Sample Data.md, docs/Documentation/QuickStart.md, docs/Documentation/UserGuideV0.7.0/7-Tools-Cli.md, docs/Documentation/UserGuideV0.7.0/7-Tools-Grafana.md, docs/Documentation/UserGuideV0.7.0/7-Tools-Hadoop.md, docs/Documentation/UserGuideV0.7.0/7-Tools-Sync.md, docs/Documentation/UserGuideV0.7.0/7-Tools-spark.md
Fix links of nav content in documents by turning nav content into "Overview" part to fix the bug proposed in [issue IOTDB-128](https://issues.apache.org/jira/browse/IOTDB-128).
=> [IOTDB-128] Fix links of nav content in documents

tsfile/src/main/java/org/apache/iotdb/tsfile/read/TsFileSequenceReader.java, tsfile/src/main/java/org/apache/iotdb/tsfile/write/writer/RestorableTsFileIOWriter.java, tsfile/src/test/java/org/apache/iotdb/tsfile/write/writer/RestorableTsFileIOWriterTest.java
As #188 is closed, I come up with a new method to support appending data at the end of a completed TsFile:
1. remove current TsFileMetadata
2. use a restorableTsFileIOWriter to write data...
=> [IOTDB-109]add a function to support appending data at the end of a completed Tsfile

docs/Development.md, docs/Documentation-CHN/UserGuideV0.7.0/4-Deployment and Management/2-Configuration.md, docs/Documentation/UserGuideV0.7.0/4-Deployment and Management/2-Configuration.md
Fix mistaken links in documents proposed in issue [IOTDB-133](https://issues.apache.org/jira/browse/IOTDB-133):
-  `iotdb-env.sh` and other configuration files shouldn't be shown as links in [Chapter 4 - Configuration page](https://iotdb.apache.org/#/Documents/latest/chap4/sec2).
- Clicking`dev@iotdb.apache.orgIn` should be jumped to email client correctly in [development page](https://iotdb.apache.org/#/Development).
=> [IOTDB-133] Fix mistaken links in documents

iotdb/src/main/java/org/apache/iotdb/db/exception/builder/ExceptionBuilder.java, iotdb/src/test/java/org/apache/iotdb/db/exception/ExceptionBuilderTest.java, tsfile/src/test/java/org/apache/iotdb/tsfile/compress/CompressTest.java, tsfile/src/test/java/org/apache/iotdb/tsfile/compress/SnappyTest.java
Methods and constructors where constant charset String literal is used (like "UTF-8") which could be replaced with a predefined Charset object like StandardCharsets.UTF_8. This may work a little bit faster because charset lookup becomes unnecessary. Also catching UnsupportedEncodingException may become unnecessary as well. In this case, the catch block will be removed automatically.
=> [IOTDB-142] Change String literal "UTF-8" into StandardCharsets.UTF_8

grafana/readme.md, grafana/readme_zh.md
Update `readme.md` and `readme_zh.md` and fix links pointing to `github.con/thulab` in `incubator-iotdb/grafana`, as is mentioned in issue [IOTDB-145](https://issues.apache.org/jira/browse/IOTDB-145).
=> [IOTDB-145] Update readme.md and readme_zh.md in incubator-iotdb/grafana

docs/Documentation-CHN/UserGuideV0.7.0/3-Operation Manual/4-Data Query.md, docs/Documentation/UserGuideV0.7.0/3-Operation Manual/4-Data Query.md
Update some outdated execution result pictures in both Chinese and English documents as is mentioned in issue [IOTDB-127](https://issues.apache.org/jira/browse/IOTDB-127).  The new pictures are uploaded [here](https://github.com/thulab/iotdb/issues/543#issuecomment-513129520).
=> [IOTDB-127] Update some execution result pictures in documents

server/src/main/antlr3/org/apache/iotdb/db/sql/parse/TSLexer.g, server/src/main/antlr3/org/apache/iotdb/db/sql/parse/TSParser.g, server/src/main/java/org/apache/iotdb/db/qp/strategy/LogicalGenerator.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBNumberPathIT.java, server/src/test/java/org/apache/iotdb/db/qp/plan/PhysicalPlanTest.java, server/src/test/java/org/apache/iotdb/db/qp/utils/MemIntQpExecutor.java, server/src/test/java/org/apache/iotdb/db/sql/SQLParserTest.java
To support series path in number format, we have the following logic in TSParser.g already:
```
nodeName
: identifier
| STAR
;
identifier
:
Identifier | integer
;
```
Then the main challenge left here is to teach antlr3 to recognize `integer` in the series path, which is easy to be confused with and recognized as `Float`, `DATETIME` partly because of the "Longest match wins first" rule of Antlr3.
For example,
|  integer   |                           float                            |                      datetime                      | seriesPath in the number format |
|------------|------------------------------------------------------------|----------------------------------------------------|------------------------------|
| +12 / -12 / 12 | +12.233 / -12.233 / +12.3332e-1 / …
=> [IOTDB-151]modify antlr3 to support timeseries path in the number format

server/src/main/java/org/apache/iotdb/db/conf/IoTDBConstant.java, server/src/main/java/org/apache/iotdb/db/conf/adapter/CompressionRatio.java, server/src/main/java/org/apache/iotdb/db/conf/adapter/IoTDBConfigDynamicAdapter.java, server/src/main/java/org/apache/iotdb/db/conf/adapter/ManageDynamicParameters.java, server/src/main/java/org/apache/iotdb/db/conf/adapter/ManageDynamicParametersMBean.java, server/src/main/java/org/apache/iotdb/db/service/IoTDB.java, server/src/main/java/org/apache/iotdb/db/service/ServiceType.java, server/src/main/java/org/apache/iotdb/db/service/TSServiceImpl.java
Add show dynamic parameters through JDBC and JMX while IoTDB is running, including memtable size threshold, memtable number, tsfile size threshold, compression ratio, storage group number, timeseries number, max timeseries number among storage groups.
1. JDBC:
Usage: show dynamic parameters
Example:
2. JMX:
Usage: Jconsle or other tools to connect JMX.
Example:
What's more, you can modify dynamic parameters through JMX, including memtable size threshold, memtable number, tsfile size threshold. 
jira link:  https://issues.apache.org/jira/browse/IOTDB-157
=> [IOTDB-157]Add show dynamic parameters

client/src/main/java/org/apache/iotdb/cli/client/AbstractClient.java
=> modify print function in AbstractClient

server/src/assembly/resources/conf/iotdb-engine.properties, server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java, server/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java, server/src/main/java/org/apache/iotdb/db/engine/cache/DeviceMetaDataCache.java, server/src/main/java/org/apache/iotdb/db/engine/cache/TsFileMetaDataCache.java, server/src/main/java/org/apache/iotdb/db/engine/cache/TsFileMetadataUtils.java
Adding configuration parameters to metadata caching module：
1、Is enable cache  parameter.
2、Memory occupancy ratio parameters of tsFileMetaData cache and chunkMetaData cache.
=> increase configuration parameters of cache

server/src/assembly/resources/tools/start-WalChecker.bat, server/src/assembly/resources/tools/start-WalChecker.sh
As many users do not set IoTDB_HOME... the script will fail. Therefore, letting user assign the folder is better.
The better way is if $IOTDB_HOME is empty, then let user assign that..
=> fix start-walchecker scripts for leting user define the wal folder

docs/Documentation/UserGuide/7-TsFile/2-Usage.md, tsfile/example/src/main/java/org/apache/iotdb/tsfile/TsFileWriteWithRowBatch.java, tsfile/src/main/java/org/apache/iotdb/tsfile/write/chunk/ChunkGroupWriterImpl.java, tsfile/src/main/java/org/apache/iotdb/tsfile/write/chunk/ChunkWriterImpl.java, tsfile/src/main/java/org/apache/iotdb/tsfile/write/chunk/IChunkWriter.java, tsfile/src/main/java/org/apache/iotdb/tsfile/write/page/PageWriter.java, tsfile/src/test/java/org/apache/iotdb/tsfile/write/TsFileReadWriteTest.java
Fix bugs and some errors in the write operation with RowBatch, including docs, tests and examples.
=> Fix bugs in RowBatch

tsfile/src/main/java/org/apache/iotdb/tsfile/encoding/encoder/DeltaBinaryEncoder.java, tsfile/src/test/java/org/apache/iotdb/tsfile/file/metadata/utils/TestHelper.java, tsfile/src/test/java/org/apache/iotdb/tsfile/file/metadata/utils/Utils.java
Used to Change Magic String to last version. If you want to know more about it, saw [this](https://issues.apache.org/jira/browse/IOTDB-165).
=> Used to change Magic String to last version

server/src/main/java/org/apache/iotdb/db/cost/statistic/Measurement.java, server/src/main/java/org/apache/iotdb/db/engine/storagegroup/StorageGroupProcessor.java, server/src/main/java/org/apache/iotdb/db/engine/storagegroup/TsFileResource.java, server/src/main/java/org/apache/iotdb/db/writelog/recover/LogReplayer.java, server/src/main/java/org/apache/iotdb/db/writelog/recover/TsFileRecoverPerformer.java, server/src/test/java/org/apache/iotdb/db/writelog/recover/LogReplayerTest.java, server/src/test/java/org/apache/iotdb/db/writelog/recover/SeqTsFileRecoverTest.java, server/src/test/java/org/apache/iotdb/db/writelog/recover/UnseqTsFileRecoverTest.java
Bug Description: 
When recovering a TsFile's `device -> start time` and `device -> end time` map and the TsFile's resource file happens not to exist, the TsFile itself will be read to update the start and end time map instead. It is implemented by `TsFileRecoverPerformer.recover` as follows:
```
for (TsDeviceMetadataIndex index : deviceMetadataIndexList) {
TsDeviceMetadata deviceMetadata = reader.readTsDeviceMetaData(index);
List<ChunkGroupMetaData> chunkGroupMetaDataList = deviceMetadata.getChunkGroupMetaDataList();
for (ChunkGroupMetaData chunkGroupMetaData : chunkGroupMetaDataList) {
for (ChunkMetaData chunkMetaData : chunkGroupMetaData.getChunkMetaDataList()) {
tsFileResource.updateTime(chunkGroupMetaData.getDeviceID(), chunkMetaData.getStartTime()); …
```
=> [IOTDB-172]fix a bug of TsFileResource updateTime 

docs/Documentation/UserGuide/6-JDBC API/1-JDBC API.md, jdbc/src/main/java/org/apache/iotdb/jdbc/Constant.java, jdbc/src/main/java/org/apache/iotdb/jdbc/IoTDBDatabaseMetadata.java, jdbc/src/main/java/org/apache/iotdb/jdbc/IoTDBMetadataResultSet.java, jdbc/src/main/java/org/apache/iotdb/jdbc/IoTDBStatement.java, jdbc/src/test/java/org/apache/iotdb/jdbc/IoTDBDatabaseMetadataTest.java, server/src/main/java/org/apache/iotdb/db/metadata/MGraph.java, server/src/main/java/org/apache/iotdb/db/metadata/MManager.java, server/src/main/java/org/apache/iotdb/db/metadata/MNode.java, server/src/main/java/org/apache/iotdb/db/metadata/MTree.java, server/src/main/java/org/apache/iotdb/db/service/TSServiceImpl.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBMetadataFetchIT.java, service-rpc/src/main/thrift/rpc.thrift
The corresponding JIRA issue: https://issues.apache.org/jira/browse/IOTDB-174
1. Create an interface for querying the timeseries number under the specified path.
2. Create an interface for querying the node number at the given level in current Metadata Tree (this could be used to query the number of devices).
3. Create an interface for querying the timeseries number of each node at the given level (this could be used to query the number of sensors under each device).
=> [IoTDB-174]Add interfaces for querying device or timeseries number

server/src/assembly/resources/sbin/start-server.bat
To fix [IOTDB-211](https://issues.apache.org/jira/projects/IOTDB/issues/IOTDB-211) "**Start command too long on windows with big classpaths in start-server.bat**", I use "%IOTDB_HOME%\lib\*" to refers to all .jar files in the directory.
>[Understanding class path wildcards](https://docs.oracle.com/javase/6/docs/technotes/tools/windows/classpath.html#Understanding):
>- Class path entries can contain the basename wildcard character *, which is considered equivalent to specifying a list of all the files in the directory with the extension .jar or .JAR. For example, the class path entry foo/* specifies all JAR files in the directory named foo. A classpath entry consisting simply of * expands to a list of all the jar files in the current directory.
>- A class path entry that contains * will …
=> [IOTDB-211]use "%IOTDB_HOME%\lib\*" to refers to all .jar files in the directory in start-server.bat

server/src/main/java/org/apache/iotdb/db/conf/directories/DirectoryManager.java
In `DirectoryManager` class, sequence and unsequence data folders are returned directly when the two lists are obtained, it is possible to modify the contents of the list outside this class, which leads to problems. So these two lists should not be published and exposed to be used outside this class.
=>  Abnormal publishing of sequence and unsequence data folders  in DirectoryManager

server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfigCheck.java, tsfile/src/main/java/org/apache/iotdb/tsfile/common/conf/TSFileConfig.java, tsfile/src/main/java/org/apache/iotdb/tsfile/file/footer/ChunkGroupFooter.java, tsfile/src/main/java/org/apache/iotdb/tsfile/file/header/ChunkHeader.java, tsfile/src/main/java/org/apache/iotdb/tsfile/file/metadata/ChunkGroupMetaData.java, tsfile/src/main/java/org/apache/iotdb/tsfile/file/metadata/ChunkMetaData.java, tsfile/src/main/java/org/apache/iotdb/tsfile/utils/Binary.java, tsfile/src/main/java/org/apache/iotdb/tsfile/utils/BytesUtils.java, tsfile/src/main/java/org/apache/iotdb/tsfile/utils/StringContainer.java
Have checked when deviceID="中文"
=> [IOTDB-195]using String.getBytes(utf-9).length to replace string.length() in ChunkGroupMetadata for supporting Chinese

tsfile/src/main/java/org/apache/iotdb/tsfile/write/TsFileWriter.java, tsfile/src/main/java/org/apache/iotdb/tsfile/write/chunk/ChunkGroupWriterImpl.java, tsfile/src/main/java/org/apache/iotdb/tsfile/write/chunk/IChunkGroupWriter.java
Avoid creating a new ChunkGroupFooter object which wastes memory. In endChunkGroup method, it creates a new ChunkGroupFooter object again.
=> Avoid creating a new ChunkGroupFooter object.

server/src/main/java/org/apache/iotdb/db/engine/storagegroup/StorageGroupProcessor.java, server/src/main/java/org/apache/iotdb/db/tools/TsFileResourcePrinter.java, server/src/main/java/org/apache/iotdb/db/writelog/recover/LogReplayer.java, tsfile/src/main/java/org/apache/iotdb/tsfile/fileSystem/FileInputFactory.java, tsfile/src/main/java/org/apache/iotdb/tsfile/fileSystem/FileOutputFactory.java, tsfile/src/main/java/org/apache/iotdb/tsfile/fileSystem/HDFSFile.java, tsfile/src/main/java/org/apache/iotdb/tsfile/fileSystem/HDFSOutput.java, tsfile/src/main/java/org/apache/iotdb/tsfile/fileSystem/TSFileFactory.java
Fix data cannot be found when restarting server in HDFS.
* [HDFS truncate function](https://issues.apache.org/jira/browse/HDFS-3107) is developed after 2.7.0, so if users have installed previous Hadoop version, they will get errors "truncate function is not supported" in server.
* In HDFS, appending and creating are totally different operations. In Java File System, we use `new FileOutputStream(file, append)` to **create**(`append` = false) or **append**(`append` = true) FileOutputStream. However in HDFS, `fs.append(path)` is used to **append** FSDataOutputStream  when the path exists, and `fs.create(path, overwrite)` is used to **create or overwrite** FSDataOutputStream. If a file with this name already exists, then if true, the file will be overwritten, and if false an exception will be …
=> [IOTDB-231] Fix data cannot be found when restarting server in HDFS

docs/Documentation/UserGuide/6-JDBC API/1-JDBC API.md, jdbc/src/main/java/org/apache/iotdb/jdbc/Constant.java, jdbc/src/main/java/org/apache/iotdb/jdbc/IoTDBDatabaseMetadata.java, jdbc/src/main/java/org/apache/iotdb/jdbc/IoTDBMetadataResultSet.java, jdbc/src/main/java/org/apache/iotdb/jdbc/IoTDBStatement.java, jdbc/src/test/java/org/apache/iotdb/jdbc/IoTDBDatabaseMetadataTest.java, jdbc/src/test/java/org/apache/iotdb/jdbc/IoTDBStatementTest.java, server/src/main/java/org/apache/iotdb/db/metadata/MGraph.java, server/src/main/java/org/apache/iotdb/db/metadata/MManager.java, server/src/main/java/org/apache/iotdb/db/metadata/MTree.java, server/src/main/java/org/apache/iotdb/db/service/TSServiceImpl.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBMetadataFetchIT.java, service-rpc/rpc-changelist.md, service-rpc/src/main/thrift/rpc.thrift
Create an interface for showing all the devices.
USAGE: `SHOW DEVICES`.
=> [IOTDB-239] Add interface for showing devices

client/pom.xml, distribution/pom.xml, example/jdbc/pom.xml, example/kafka/pom.xml, example/rocketmq/pom.xml, example/session/pom.xml, example/tsfile/pom.xml, grafana/pom.xml, jdbc/pom.xml, pom.xml, server/pom.xml, session/pom.xml, spark-iotdb-connector/pom.xml, spark-tsfile/pom.xml
1. Now, each pom file only has one declaration for the version.
2. If you need to update the version of IoTDB (e.g., from 0.9.0-SNAPSHOT to 0.9.0), you even do not need to change the version of child's module  one by one now.
2.1 just change the version declaration in root/pom.xml;
2.2 run `mvn  -N versions:update-child-modules` 
2.3 bingo! the versions of all children modules are updated automatically.
=> Reduce project version declaration

server/src/main/java/org/apache/iotdb/db/qp/strategy/LogicalGenerator.java, server/src/test/java/org/apache/iotdb/db/qp/plan/PhysicalPlanTest.java
https://issues.apache.org/jira/projects/IOTDB/issues/IOTDB-249?filter=allissues
To enable sql like "create timeseries root.vehicle.d1.s1 with datatype=int32, encoding=rle" where datatype and encoding value can be lowercase.
=> [IOTDB-249]enable lowercase in create_timeseries sql

tools/check_sigs.sh, tools/common.sh, tools/download_staged_release.sh
Hi, because the original release tool cannot run directly on my computer, I fix some problems in it and make it works.
- common.sh
- flip the returned result of `checkVerNum` and `checkRcNum`
- download_staged_release.sh
- fix some paths
Execute the following command and it will download the release package and verify the reported signature and hashes automatically. 
```
bash download_staged_release.sh 0.8.1 1
```
=> fix release tools

pom.xml
after run `mvn generate-sources`, you can find cpp, python, go apis under service-rpc/target/generated-source-{language}.
So, you just need to supply how to use these APIs in other PRs.
=> generate cpp, go, and python thrift files under service-rpc

session/src/main/java/org/apache/iotdb/session/Config.java, session/src/main/java/org/apache/iotdb/session/Session.java, session/src/test/java/org/apache/iotdb/session/IoTDBSessionIT.java, tsfile/src/main/java/org/apache/iotdb/tsfile/common/constant/TsFileConstant.java
When using Session to set storage group or create time series, the path needs to be checked in order to reject this creation if it contains special characters.
=> [IOTDB-261]Check path validity in session

server/src/main/java/org/apache/iotdb/db/conf/IoTDBConstant.java, server/src/main/java/org/apache/iotdb/db/conf/adapter/IoTDBConfigDynamicAdapter.java, server/src/main/java/org/apache/iotdb/db/engine/storagegroup/TsFileProcessor.java, server/src/main/java/org/apache/iotdb/db/metadata/MManager.java
In the dynamic parameter adjustment module, it calculated the average size of each metatable. However, considering that the number of timeseries between storage groups may vary greatly, it's appropriate to judge whether to flush the memtable according to the average memtable size. We need to adjust it according to the number of timeseries in a specific storage group.
jira link: https://issues.apache.org/jira/projects/IOTDB/issues/IOTDB-265?filter=allopenissues
=> [IOTDB-265]Re-adjust the threshold size of memtable

docs/Documentation-CHN/UserGuide/4-Operation Manual/7-IoTDB Query Language.md, docs/Documentation/UserGuide/4-Operation Manual/7-IoTDB Query Statement.md, jdbc/README.md, jdbc/src/main/java/org/apache/iotdb/jdbc/Constant.java, jdbc/src/main/java/org/apache/iotdb/jdbc/IoTDBDatabaseMetadata.java, jdbc/src/main/java/org/apache/iotdb/jdbc/IoTDBStatement.java, jdbc/src/test/java/org/apache/iotdb/jdbc/IoTDBDatabaseMetadataTest.java, pom.xml, server/src/main/java/org/apache/iotdb/db/metadata/MGraph.java, server/src/main/java/org/apache/iotdb/db/metadata/MManager.java, server/src/main/java/org/apache/iotdb/db/metadata/MTree.java, server/src/main/java/org/apache/iotdb/db/service/TSServiceImpl.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBMetadataFetchIT.java, service-rpc/src/main/thrift/rpc.thrift
Corresponding to JIRA issue: https://issues.apache.org/jira/browse/IOTDB-174
1. Fix the bug which the querying timeseries number interface cannot make a query by the specified path prefix.
2. Fix the documentation corresponding to the query operation (add the device in path).
=> [IOTDB-174] Fix querying timeseries interface cannot make a query by the specified path prefix

server/src/main/java/org/apache/iotdb/db/qp/physical/PhysicalPlan.java, tsfile/src/main/java/org/apache/iotdb/tsfile/file/footer/ChunkGroupFooter.java, tsfile/src/main/java/org/apache/iotdb/tsfile/file/header/ChunkHeader.java, tsfile/src/main/java/org/apache/iotdb/tsfile/read/TsFileSequenceReader.java, tsfile/src/main/java/org/apache/iotdb/tsfile/utils/ReadWriteIOUtils.java
Currently, deserializing the chunk header requires 2 disk read operations. One is reading chunkheader length, the other is reading chunkheader content. So this pr is for reducing IO operations in  chunk header deserialization.
=> [IOTDB-267]reduce IO operations in deserializing chunk header

server/src/main/antlr3/org/apache/iotdb/db/sql/parse/TqlParser.g
There's a bug in previous project. Insert statement failed to support number path in `insertColumnSpec`. It is fixed now.
=> fix number path insert bug

.travis.yml
Reference: 
https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received
=> set the timeout of Travis on Win as 20 min

docs/Documentation-CHN/UserGuide/3-Deployment/2-Configuration.md, docs/Documentation-CHN/UserGuide/8-Distributed Architecture/1-Shared Storage Architecture.md, docs/Documentation/UserGuide/3-Deployment/2-Configuration.md, docs/Documentation/UserGuide/8-Distributed Architecture/1-Shared Storage Architecture.md, hadoop/src/main/java/org/apache/iotdb/hadoop/fileSystem/HDFSConfUtil.java, hadoop/src/main/java/org/apache/iotdb/hadoop/fileSystem/HDFSFile.java, hadoop/src/main/java/org/apache/iotdb/hadoop/fileSystem/HDFSOutput.java, server/src/assembly/resources/conf/iotdb-engine.properties, server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java, server/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java, tsfile/src/main/java/org/apache/iotdb/tsfile/common/conf/TSFileConfig.java
Add configuration for HDFS HA. If there are more than one `hdfs_ip` in configuration, Hadoop HA is used.  Example: 
```
tsfile_storage_fs=LOCAL
hdfs_ip=localhost
hdfs_port=9000
dfs_nameservices=hdfsnamespace
dfs_ha_namenodes=nn1,nn2
dfs_ha_automatic_failover_enabled=true
dfs_client_failover_proxy_provider=org.apache.hadoop.hdfs.server.namenode.ha.ConfiguredFailoverProxyProvider
```
=> [IOTDB-271] Add configuration for HDFS HA

hadoop/src/main/java/org/apache/iotdb/hadoop/tsfile/TSFRecordReader.java, jdbc/src/main/java/org/apache/iotdb/jdbc/IoTDBQueryResultSet.java, jdbc/src/main/java/org/apache/iotdb/jdbc/Utils.java, jdbc/src/test/java/org/apache/iotdb/jdbc/UtilsTest.java, server/src/main/java/org/apache/iotdb/db/qp/executor/AbstractQueryProcessExecutor.java, session/src/main/java/org/apache/iotdb/session/SessionUtils.java, spark-tsfile/src/main/scala/org/apache/iotdb/spark/tsfile/Converter.scala, tsfile/src/main/java/org/apache/iotdb/tsfile/read/common/Field.java, tsfile/src/main/java/org/apache/iotdb/tsfile/read/query/dataset/DataSetWithoutTimeGenerator.java, tsfile/src/main/java/org/apache/iotdb/tsfile/read/query/dataset/QueryDataSet.java
Fix inconsistent ways of judging whether a Field is null by removing `isNull` field and `setNull` method. Only retain one way of defining a null field `new Field(null)`, and `isNull()` method can be realized by checking `this.dataType == null`.
=> [IOTDB-276] Fix inconsistent ways of judging whether a Field is null

client/src/main/java/org/apache/iotdb/client/AbstractClient.java
make client default fetchSize  = maxPrintRowCount, and don't need to fetching all data.
old versions have a problem , max to print 1000 lines ,but traversal server all data by 10000 lines every time。
in old :
```
IoTDB> select * from root
select * from root
+-----------------------------------+--------------+--------------+--------------+
|                               Time|root.sg1.d1.s1|root.sg1.d1.s2|root.sg1.d1.s3|
+-----------------------------------+--------------+--------------+--------------+
|      1970-01-01T08:00:00.000+08:00|             1|             1|             1|
|      1970-01-01T08:00:00.001+08:00|             1|             1|             1|
......
+-----------------------------------+--------------+--------------+--------------+
Reach maxPrintRowCount = 1000 lines …
```
=> [IOTDB-257] makes the client stop fetch when dataSize equals maxPrintRowCount and change client fetchSize less than maxPrintRowCount

jdbc/src/main/java/org/apache/iotdb/jdbc/IoTDBStatement.java
1. Start the IOTDB-Client and connect to the server successfully
2. Restart the server side
3. And then if you execute any command on the client, you will receive an error message: 'MSG: cannot get ID for statement'
I will refer to the *executeQuery()* method of reconnection for repair.
=> [IOTDB-300]reconnection to requestStmtId when broke pip

tsfile/src/main/java/org/apache/iotdb/tsfile/tool/upgrade/TsfileUpgradeToolV0_8_0.java
I have tested a bug in upgrading when using snappy compress.
=> [fix] fix upgrade when use compress

docs/Documentation-CHN/UserGuide/3-Server/4-Config Manual.md, docs/Documentation-CHN/UserGuide/8-System Design (Developer)/3-Writing Data on HDFS.md, docs/Documentation/UserGuide/3-Server/4-Config Manual.md, docs/Documentation/UserGuide/8-System Design (Developer)/3-Writing Data on HDFS.md, hadoop/src/main/java/org/apache/iotdb/hadoop/fileSystem/HDFSConfUtil.java, hadoop/src/main/java/org/apache/iotdb/hadoop/fileSystem/HDFSFile.java, server/src/assembly/resources/conf/iotdb-engine.properties, server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java, server/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java, server/src/main/java/org/apache/iotdb/db/engine/storagegroup/StorageGroupProcessor.java, tsfile/src/main/java/org/apache/iotdb/tsfile/common/conf/TSFileConfig.java
Fix bug of "Incomplete HDFS URI: no host".
Add two new configuration `core_site_path` and `hdfs_site_path` for users to config absolute file path of `core-site.xml` and `hdfs-site.xml` when Tsfile and related data files are stored in HDFS.
=> [IOTDB-304] Fix bug of incomplete HDFS URI

server/src/assembly/resources/conf/iotdb-engine.properties, server/src/main/java/org/apache/iotdb/db/conf/directories/strategy/RandomOnDiskUsableSpaceStrategy.java, server/src/test/java/org/apache/iotdb/db/conf/directories/strategy/DirectoryStrategyTest.java
When usable space of one certain directory is much more than the others (when adding a new disk), all new files will be written to this directory, which is not optimal. Therefore, RandomOnDiskUsableSpaceStrategy is added here, which will randomly choose directory based on usable space. The more usable space the directory contains, the greater the chance of being chosen.
=> [IOTDB-313] Add RandomOnDiskUsableSpaceStrategy

server/src/main/java/org/apache/iotdb/db/query/control/FileReaderManager.java
[deadlock.docx](https://github.com/apache/incubator-iotdb/files/3882286/deadlock.docx)
=> [IOTDB-319]get lock in FileReaderManager outside of the synchronized block

server/src/main/java/org/apache/iotdb/db/service/TSServiceImpl.java
Fix printing error log into log_error.log file when the server receives a wrong SQL
Now the error in server will be:`09:22:40.950 [pool-2-IoTDB-JDBC-Client-thread-1] INFO org.apache.iotdb.db.service.TSServiceImpl - meet error while parsing SQL to physical plan: Parsing error, statement [show select a from from root.b] failed when parsing AST tree to generate logical operator. Detailed information: [line 1:5  'show']`
=> [IOTDB-318] Fix printing unnecessary error log into log_error.log file

server/src/main/java/org/apache/iotdb/db/engine/storagegroup/StorageGroupProcessor.java, server/src/main/java/org/apache/iotdb/db/service/TSServiceImpl.java
This PR fixes the bug of **flush + wrong aggregation** causes failed query in v0.8.x as is described in [issue IOTDB-317](https://issues.apache.org/jira/browse/IOTDB-317).
**【The main cause of this bug】**
When a wrong aggregation sql is executed, in `IoTDBStatement.java`, **getColumnsType** function is called when creating a new `IoTDBQueryResultSet`:
```
IoTDBQueryResultSet resSet = new IoTDBQueryResultSet(this,
execResp.getColumns(), client,
operationHandle, sql, execResp.getOperationType(),
getColumnsType(execResp.getColumns()), queryId.getAndIncrement());
``` 
**getColumnsType** function calls **fetchMetadata** function in `TSServiceImpl.java`, which catches an exception (**QueryProcessException** in 0.9.x, and **PathErrorException** in 0.8.x), and uses …
=> [IOTDB-317] Fix "flush + wrong aggregation" causes failed query in v0.8.x

pom.xml
In the local development, the `package` was often used, but I found it interesting that each `package` required about 20m. Later, I found that **oss** inspection wasted a lot of time. When I deleted it, the packaging time was reduced to 2m.
Therefore, I submit this pr in the hope of saving time for people with the same problem as me
=> Move the vulnera-checks section into the apache-release profile

.travis.yml, pom.xml
Thrift 0.9 has a bug (https://issues.apache.org/jira/browse/IOTDB-322) and has been resolved from 0.10.
Tianjiang compiled the binaries files of Thrift 0.12-0.13  and by using Chris's setting, we can  let the pom automatically compile .thrift files.
Linux (Ubuntu) is upgraded from 14.04 to 16.04
OracleJDK8 is disabled on Linux while OpenJDK 8 and 11 work well.
=> [IOTDB-322] upgrade to thrift 0.12.0

docs/Documentation-CHN/UserGuide/5-Operation Manual/4-SQL Reference.md, docs/Documentation/UserGuide/5-Operation Manual/4-SQL Reference.md, server/src/main/java/org/apache/iotdb/db/query/aggregation/impl/FirstValueAggrFunc.java, server/src/main/java/org/apache/iotdb/db/query/aggregation/impl/LastValueAggrFunc.java, server/src/main/java/org/apache/iotdb/db/query/executor/AggregateEngineExecutor.java, server/src/main/java/org/apache/iotdb/db/query/factory/AggreFuncFactory.java, server/src/main/java/org/apache/iotdb/db/service/TSServiceImpl.java, server/src/test/java/org/apache/iotdb/db/integration/Constant.java, server/src/test/java/org/apache/iotdb/db/integration/IOTDBGroupByIT.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBAggregationIT.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBAggregationLargeDataIT.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBAggregationSmallDataIT.java, tsfile/src/main/java/org/apache/iotdb/tsfile/common/constant/StatisticConstant.java
refactor: change aggregation function's name: last to last_value, first to first_value.
=> [IOTDB-298] Refactor the "last" and "first" aggregators

pom.xml
I tried to use JDK11 to compile a binary file, you can get it at https://dist.apache.org/repos/dist/dev/incubator/iotdb/0.8.2/rc1.
However, if a user uses JDK8 to run it, an exception will occur:
java.lang.NoSuchMethodError: java.nio.ByteBuffer.clear()Ljava/nio/ByteBuffer;
It is because before JDK9, ByteBuffer.clear() returns  Buffer, while from JDK9 on, the method return ByteBuffer.
According to https://github.com/apache/curator/pull/312, add a parameter `–release 8` can solve the problem. 
In maven, we can add a property called 
```
<maven.compiler.release>8</maven.compiler.release>
```
=> [IOTDB-336]declare that the release version of JDK is 8

grafana/conf/application.properties, grafana/src/main/java/org/apache/iotdb/web/grafana/dao/impl/BasicDaoImpl.java
In the grafana module, timestamps are in milliseconds. In this case, when users choose "us" or "ns" in engine, it'll not work correctly. This pr is to fix this bug.
The jira link: https://issues.apache.org/jira/browse/IOTDB-337
=> [IOTDB-337]Add timestamp precision properties for grafana

docs/Documentation-CHN/UserGuide/5-Operation Manual/4-SQL Reference.md, docs/Documentation/UserGuide/5-Operation Manual/4-SQL Reference.md, jdbc/src/main/java/org/apache/iotdb/jdbc/IoTDBQueryResultSet.java, jdbc/src/main/java/org/apache/iotdb/jdbc/IoTDBStatement.java, jdbc/src/test/java/org/apache/iotdb/jdbc/IoTDBQueryResultSetTest.java, jdbc/src/test/java/org/apache/iotdb/jdbc/IoTDBStatementTest.java, server/src/assembly/resources/conf/iotdb-engine.properties, server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java, server/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java, server/src/main/java/org/apache/iotdb/db/qp/executor/AbstractQueryProcessExecutor.java, server/src/main/java/org/apache/iotdb/db/qp/logical/crud/QueryOperator.java, server/src/main/java/org/apache/iotdb/db/qp/physical/crud/QueryPlan.java, server/src/main/java/org/apache/iotdb/db/qp/strategy/LogicalGenerator.java, server/src/main/java/org/apache/iotdb/db/qp/strategy/PhysicalGenerator.java, server/src/main/java/org/apache/iotdb/db/query/dataset/DeviceIterateDataSet.java, server/src/main/java/org/apache/iotdb/db/query/dataset/EngineDataSetWithValueFilter.java, server/src/main/java/org/apache/iotdb/db/query/dataset/EngineDataSetWithoutValueFilter.java, server/src/main/java/org/apache/iotdb/db/query/dataset/ListDataSet.java, server/src/main/java/org/apache/iotdb/db/query/dataset/groupby/GroupByEngineDataSet.java, server/src/main/java/org/apache/iotdb/db/query/dataset/groupby/GroupByWithValueFilterDataSet.java, server/src/main/java/org/apache/iotdb/db/query/dataset/groupby/GroupByWithoutValueFilterDataSet.java, server/src/main/java/org/apache/iotdb/db/query/executor/AggregateEngineExecutor.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBQueryDemoIT.java, server/src/test/java/org/apache/iotdb/db/qp/plan/LogicalPlanSmallTest.java, server/src/test/java/org/apache/iotdb/db/qp/plan/PhysicalPlanTest.java, server/src/test/java/org/apache/iotdb/db/query/executor/GroupByEngineDataSetTest.java, tsfile/src/main/java/org/apache/iotdb/tsfile/read/query/dataset/DataSetWithTimeGenerator.java, tsfile/src/main/java/org/apache/iotdb/tsfile/read/query/dataset/DataSetWithoutTimeGenerator.java, tsfile/src/main/java/org/apache/iotdb/tsfile/read/query/dataset/QueryDataSet.java
Moving LIMIT&OFFSET to the server side has two benefits :-)
1. reduces the size of the result data transferred between the server and the client. In the old code, the server returns the result data starting at the first row to the client, and leaves the boring work of iterating to the OFFSET row to the client.
2. makes the code of jdbc easier to understand.
To achieve the benefits, changes in this pr include:
- The server side:
- sql->logicalPlan->physicalPlan
- Antlr4 doesn't need changing
- parse LIMIT&OFFSET parameters and save them in logicalPlan (Note that SLIMIT&SOFFSET parameters are also saved in logicalOperator. SLIMIT&SOFFSET take effect in the optimization of logicalPlan or in the generation of physicalPlan from logicalPlan.)
- pass LIMIT&OFFSET parameters from logicalPlan to …
=> [IOTDB-334] Move LIMIT&OFFSET to Server Side

grafana/src/main/java/org/apache/iotdb/web/grafana/dao/impl/BasicDaoImpl.java
When using grafana, it's unable to show the data correctly unless the type of data is Float. The data will always be 0.
The jira link: https://issues.apache.org/jira/browse/IOTDB-337
=> [IOTDB-341]Fix data type bug in grafana

example/jdbc/src/main/java/org/apache/iotdb/JDBCExample.java
in `[IOTDB-217]  A new GROUPBY syntax with supporting inner interval` ,he seems forgotten to modify the JDBC example
=> Fix jdbc example for groupby

jdbc/src/main/java/org/apache/iotdb/jdbc/Utils.java, jdbc/src/test/java/org/apache/iotdb/jdbc/UtilsTest.java
In this [pr](https://github.com/apache/incubator-iotdb/pull/514l), it restricts users to only use domain names and IP addresses. Obviously, this makes users can’t use a custom domain name like `master`. Now, you can use a JDBC URL like `jdbc:iotdb://anything:port/ or jdbc:iotdb://anything:port`.
=> [IOTDB-287] Allow anything in a JDBC URL.

server/src/main/java/org/apache/iotdb/db/qp/QueryProcessor.java, server/src/main/java/org/apache/iotdb/db/qp/strategy/LogicalGeneratorError.java, server/src/main/java/org/apache/iotdb/db/qp/strategy/ParseDriver.java, server/src/main/java/org/apache/iotdb/db/service/TSServiceImpl.java, server/src/test/java/org/apache/iotdb/db/qp/QueryProcessorTest.java, server/src/test/java/org/apache/iotdb/db/qp/plan/QPUpdateTest.java
Add an antlr4 error listener. Display syntax error information in a client.
```
IoTDB> insert into root.ln.wf02.wt02(timestamp,status) value(1,true)
insert into root.ln.wf02.wt02(timestamp,status) value(1,true)
Msg: line 1:48 mismatched input 'value' expecting VALUES
It costs 0.445s
```
=> Add antlr error listener.

pom.xml
Upgrade thrift from 0.12 to 0.13. 
As 0.12 seems a unstable version.
=> [IOTDB-345/338]upgrade thrift from 0.12 to 0.13

server/src/main/java/org/apache/iotdb/db/service/IoTDB.java, server/src/main/java/org/apache/iotdb/db/writelog/recover/TsFileRecoverPerformer.java
This pr is to fix the hidden bug in method `redoLogs()` of class `TsFileRecoverPerformer`.
The jira link: https://issues.apache.org/jira/browse/IOTDB-357
=> [IOTDB-357]Fix NullPointerException in tsfile recover performer

docs/Development-Contributing.md
Currently in the page of http://iotdb.apache.org/#/Development/Contributing has a confluence link which point to the home page of apache confluence home. I would like to do a little bit improvement:
Change the link from `https://cwiki.apache.org/confluence` to the IotDB confluenc home page `https://cwiki.apache.org/confluence/display/IOTDB`.
The detail of discussion can be found here: https://issues.apache.org/jira/browse/IOTDB-365
=> [IOTDB-365] Improve the link of confluence in Development-Document.md

jdbc/src/main/java/org/apache/iotdb/jdbc/IoTDBQueryResultSet.java
Fix bug of "Has not execute query" error when querying.
Revert the deletion of `emptyResultSet` flag to break the last query process.
=> [IOTDB-369] Fix bug of "Has not execute query" error when querying

docs/Documentation-CHN/UserGuide/8-System Design (Developer)/1-Hierarchy.md, docs/Documentation/UserGuide/8-System Design (Developer)/1-Hierarchy.md, server/src/assembly/resources/tools/tsfileToolSet/print-iotdb-data-dir.bat, server/src/assembly/resources/tools/tsfileToolSet/print-iotdb-data-dir.sh, server/src/assembly/resources/tools/tsfileToolSet/print-tsfile-resource-files.bat, server/src/assembly/resources/tools/tsfileToolSet/print-tsfile-resource-files.sh, server/src/assembly/resources/tools/tsfileToolSet/print-tsfile-sketch.bat, server/src/assembly/resources/tools/tsfileToolSet/print-tsfile-sketch.sh, server/src/main/java/org/apache/iotdb/db/tools/IoTDBDataDirViewer.java, server/src/main/java/org/apache/iotdb/db/tools/TsFileSketchTool.java
An example:
```
|==============================================================
|D:\\data\data
|--sequence
|  |--root.ln.wf01.wt01
|  |  |--1575813520203-101-0.tsfile
|  |  |--1575813520203-101-0.tsfile.resource
|  |  |  |--device root.ln.wf01.wt01, start time 1 (1970-01-01T08:00:00.001+08:00[GMT+08:00]), end time 5 (1970-01-01T08:00:00.005+08:00[GMT+08:00])
|  |  |--1575813520669-103-0.tsfile
|  |  |--1575813520669-103-0.tsfile.resource
|  |  |  |--device root.ln.wf01.wt01, start time 100 (1970-01-01T08:00:00.100+08:00[GMT+08:00]), end time 300 (1970-01-01T08:00:00.300+08:00[GMT+08:00])
|  |  |--1575813521372-107-0.tsfile
|  |  |--1575813521372-107-0.tsfile.resource
|  |  |  |--device root.ln.wf01.wt01, start time 500 (1970-01-01T08:00:00.500+08:00[GMT+08:00]), end time 540 …
```
=> [IOTDB-364] Add IoTDBDataDirViewer Tool

server/src/main/java/org/apache/iotdb/db/query/control/QueryResourceManager.java, server/src/main/java/org/apache/iotdb/db/service/TSServiceImpl.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBSequenceDataQueryIT.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBSeriesReaderIT.java, server/src/test/java/org/apache/iotdb/db/utils/EnvironmentUtils.java, session/src/test/java/org/apache/iotdb/session/utils/EnvironmentUtils.java, spark-iotdb-connector/src/test/scala/org/apache/iotdb/spark/db/EnvironmentUtils.java
When generating a queryId, two maps recording the files used by this query are created, which are not necessary for non-data queries, so we remove the map creation for non-data queries by separating data query and non-data query.
=> Do not create used file maps for non-data queries

.travis.yml
As travis will upload results to sonar and coveralls but non-committers have no permission, the related PR CI will fail.
Therefore, we can disable the two CI stage for those who have no write permission of Apache IoTDB repo. That is, these users can just fork the repo and then submit pr.
If it does not work, we can constrain the type = pull_request.
=> [IOTDB-388]disable sonar and coveralls for non-committers

server/src/test/java/org/apache/iotdb/db/writelog/recover/SeqTsFileRecoverTest.java, server/src/test/java/org/apache/iotdb/db/writelog/recover/UnseqTsFileRecoverTest.java
JIRA link: https://issues.apache.org/jira/browse/IOTDB-159
The key to reproducing, is to test UnseqTsFileRecoverTest (or SeqTsFileRecoverTest) AFTER 
first testing an integration test under the test/java/org/apache/iotdb/db/integration directory, 
such as IoTDBAuthorizationIT.
```
git clone https://github.com/apache/incubator-iotdb.git
cd incubator-iotdb
mvn clean install -Dmaven.test.skip=true
cd server
mvn test -Dtest=org.apache.iotdb.db.integration.IoTDBAuthorizationIT,org.apache.iotdb.db.writelog.recover.UnseqTsFileRecoverTest
```
FlushSubTaskPoolManager.getInstance() is shared between IoTDBAuthorizationIT and UnseqTsFileRecoverTest. 
In the integration tests under the test/java/org/apache/iotdb/db/integration directory, tearDown() will call FlushSubTaskPoolManager.stop() and finally …
=> [IOTDB-159] Fix NullPointerException in SeqTsFileRecoverTest and UnseqTsFileRecoverTest

server/src/main/antlr4/org/apache/iotdb/db/qp/strategy/SqlBase.g4, server/src/main/java/org/apache/iotdb/db/qp/logical/crud/QueryOperator.java, server/src/main/java/org/apache/iotdb/db/qp/strategy/LogicalGenerator.java, server/src/test/java/org/apache/iotdb/db/qp/plan/LogicalPlanSmallTest.java
The disable align clause is defined in the ANTLR file. And the logical plan can be generated now.
=> Define disable align clause

server/src/main/java/org/apache/iotdb/db/query/dataset/NewEngineDataSetWithoutValueFilter.java, server/src/main/java/org/apache/iotdb/db/query/executor/EngineExecutor.java, server/src/main/java/org/apache/iotdb/db/query/reader/ManagedSeriesReader.java, server/src/main/java/org/apache/iotdb/db/query/reader/seriesRelated/SeriesReaderWithoutValueFilter.java, server/src/test/java/org/apache/iotdb/db/query/reader/seriesRelated/SeriesReaderWithValueFilterTest.java, server/src/test/java/org/apache/iotdb/db/query/reader/seriesRelated/SeriesReaderWithoutValueFilterTest.java
As the distributed version needs a remote implementation of series readers which reads data from another node, abstracting an interface from the currently used reader, which is SeriesReaderWithoutValueFilter, will minimize the code changes.
=> abstract an interface ManagedSeriesReader from SeriesReaderWithoutValueFilter

server/src/main/java/org/apache/iotdb/db/qp/strategy/PhysicalGenerator.java, server/src/test/java/org/apache/iotdb/db/qp/plan/PhysicalPlanTest.java
In the previous design, we needed to move all the work removing the duplicate `Path` to the `PhysicalGenerator` class to do this, but without the `group by device` because it is a special way of working, we kept the deduplication work in the `DeviceIterateDataSet` class.
So, when a `group by device` query after `PhysicalGenerator`, `deduplicatedPaths` and `deduplicatedDataTypes` should be an empty state, and the `paths` and `datatypes` should be meet the requirements of the implementation of `DeviceIterateDataSet` , for more complex description. 
I created a `ut` `PhysicalPlanTest.testDeduplicatedPath` to describe these things.
=> [IOTDB-412]Paths are not correctly deduplicated

docs/Documentation-CHN/UserGuide/3-Server/4-Config Manual.md, docs/Documentation/UserGuide/3-Server/4-Config Manual.md, server/src/assembly/resources/conf/iotdb-env.bat, server/src/assembly/resources/conf/iotdb-env.sh, server/src/assembly/resources/sbin/start-server.bat, server/src/assembly/resources/sbin/start-server.sh
Current though we set the printGC parameter, but we forgot to enable it..
i.e., in iotdb-env.sh, though we set:
IOTDB_JMX_OPTS="$IOTDB_JMX_OPTS -Xloggc:${IOTDB_HOME}/gc.log"
, but latter, in line 153 and line 156, we set:
IOTDB_JMX_OPTS="-Diotdb.jmx.local.port=$JMX_PORT"
, which cleans all setting before...
This PR fixes the bug and fix the GC log setting.
using `start-server.sh printgc` to enable the script.
In JDK8, the log looks like:
```
ava HotSpot(TM) 64-Bit Server VM (25.144-b01) for bsd-amd64 JRE (1.8.0_144-b01), built on Jul 21 2017 22:07:42 by "java_re" with gcc 4.2.1 (Based on Apple Inc. build 5658) (LLVM build 2336.11.00)
Memory: 4k page, physical 33554432k(419872k free)
/proc/meminfo:
CommandLine flags: -XX:GCLogFileSize=10485760 -XX:InitialHeapSize=1258291200 …
```
=> [IOTDB-397]fix gc log collection in start-server.sh scripts

docs/Documentation-CHN/UserGuide/3-Server/4-Config Manual.md, docs/Documentation/UserGuide/3-Server/4-Config Manual.md, server/src/assembly/resources/conf/iotdb-env.bat, server/src/assembly/resources/conf/iotdb-env.sh, server/src/assembly/resources/sbin/start-server.bat, server/src/assembly/resources/sbin/start-server.sh
Reverts apache/incubator-iotdb#699
As the PR introduce a new problem: 
[ERROR] test(org.apache.iotdb.db.script.EnvScriptIT)  Time elapsed: 0.142 s  <<< FAILURE!
org.junit.ComparisonFailure: expected:<[If you want to change this configuration, please check conf/iotdb-env.sh(Unix or OS X, if you use Windows, check conf/iotdb-env.bat)].> but was:<[( was unexpected at this time].>
at org.apache.iotdb.db.script.EnvScriptIT.testOutput(EnvScriptIT.java:87)
at org.apache.iotdb.db.script.EnvScriptIT.testStartClientOnWindows(EnvScriptIT.java:59)
at org.apache.iotdb.db.script.EnvScriptIT.test(EnvScriptIT.java:46)
=> Revert "[IOTDB-397]fix gc log collection in start-server.sh scripts"

server/src/main/java/org/apache/iotdb/db/engine/flush/MemTableFlushTask.java
If a runtime exception is thrown in an encoding sub-task, it will die silently and prevents the io task from ending.
To avoid this, the future of the encoding task should be got before that of the io task is got.
=> [IOTDB-420] Avoid encoding task dying silently

server/src/main/java/org/apache/iotdb/db/engine/storagegroup/StorageGroupProcessor.java
If some unseq file overlaps the unsealed seq file and a merge is triggered, the overlapped data may not be able to be merged into the right file.
To resolve this, the files should be closed before a merge starts.
=> [IOTDB-422]close files before merge

server/src/main/java/org/apache/iotdb/db/engine/merge/manage/MergeResource.java, server/src/main/java/org/apache/iotdb/db/engine/merge/selector/MaxFileMergeFileSelector.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBMergeTest.java
Because the current MergeFileSelector select merge files by unseq files if the unseq files overlap seq files in a reverted order, the selected seq files will be out of order.
Example:
1. write a seq file A, which ranges [10, 20]
2. write a seq file B, which ranges [20, 30]
3. write an unseq file C, which ranges [20, 30]
4. write an unseq file D, which ranges [10, 20]
C overlaps B and D overlaps and because C is generated before D, as a result, the selected seq files will be [B, A] instead of [A, B], which will make the following merge process write data into a wrong file.
To resolve this, the selected seq files are reordered before starting the actual merge task.
=> [IOTDB-421]fix that selected seq files for merge are not sorted

server/src/main/java/org/apache/iotdb/db/qp/executor/PlanExecutor.java, server/src/main/java/org/apache/iotdb/db/qp/logical/crud/QueryOperator.java, server/src/main/java/org/apache/iotdb/db/qp/physical/crud/AggregationPlan.java, server/src/main/java/org/apache/iotdb/db/qp/physical/crud/AlignByDevicePlan.java, server/src/main/java/org/apache/iotdb/db/qp/physical/crud/FillQueryPlan.java, server/src/main/java/org/apache/iotdb/db/qp/physical/crud/GroupByPlan.java, server/src/main/java/org/apache/iotdb/db/qp/physical/crud/QueryPlan.java, server/src/main/java/org/apache/iotdb/db/qp/physical/crud/RawDataQueryPlan.java, server/src/main/java/org/apache/iotdb/db/qp/strategy/LogicalGenerator.java, server/src/main/java/org/apache/iotdb/db/qp/strategy/PhysicalGenerator.java, server/src/main/java/org/apache/iotdb/db/qp/strategy/optimizer/ConcatPathOptimizer.java, server/src/main/java/org/apache/iotdb/db/query/dataset/AlignByDeviceDataSet.java, server/src/main/java/org/apache/iotdb/db/query/dataset/DeviceIterateDataSet.java, server/src/main/java/org/apache/iotdb/db/query/executor/IQueryRouter.java, server/src/main/java/org/apache/iotdb/db/query/executor/QueryRouter.java, server/src/main/java/org/apache/iotdb/db/query/executor/RawDataQueryExecutor.java, server/src/main/java/org/apache/iotdb/db/service/TSServiceImpl.java, server/src/test/java/org/apache/iotdb/db/engine/modification/DeletionQueryTest.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBSequenceDataQueryIT.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBSeriesReaderIT.java, server/src/test/java/org/apache/iotdb/db/qp/plan/LogicalPlanSmallTest.java, server/src/test/java/org/apache/iotdb/db/qp/plan/PhysicalPlanTest.java, server/src/test/java/org/apache/iotdb/db/qp/plan/TestConcatOptimizer.java
The AlignByDevice query ( which is called groupByDevice before ) and general query aligning by time are both storaged in QueryPlan now. However, they invoke different query process bascially, so it's necessary to restructure the QueryPlan and seperate the AlignByDeviceQuery from it.
The QueryPlan is designed as base class, which has RawDataQueryPlan and AlignByDevicePlan as subclasses. This restructure may bring some usage changes, because the general query which uses QueryPlan directly before has to instantiate RawDataQueryPlan now.
If you think the design is not friendly to users, welcome to comment.
=> [IoTDB-468] Restructure QueryPlan

docs/Documentation/UserGuide/5-Operation Manual/2-DML (Data Manipulation Language).md
Fix the broken link for `Client/Shell tools` in `Chapter 5: Operation Manual
DML`
=> [IOTDB-485] Fix the broken link for `Client/Shell tools`

jdbc/src/main/java/org/apache/iotdb/jdbc/Utils.java
Variable url pattern should be defined as a constant in `org.apache.iotdb.jdbc.Utils`
=> [IOTDB-489] Variable url pattern should be defined as a constant

server/src/main/java/org/apache/iotdb/db/qp/strategy/PhysicalGenerator.java
Static members shouldn't be accessed through class instances in `org.apache.iotdb.db.qp.strategy.PhysicalGenerator`
=> [IOTDB-488] Static members shouldn't be accessed through class instances

server/src/main/java/org/apache/iotdb/db/query/dataset/NewEngineDataSetWithoutValueFilter.java
Constant name `pool ` should be all uppercase in `org.apache.iotdb.db.query.dataset.NewEngineDataSetWithoutValueFilter`
Renamed to `TASK_POOL_MANAGER `.
=> [IOTDB-491] Constant  name `pool ` should be all uppercase

example/session/src/main/java/org/apache/iotdb/SessionExample.java, session/src/main/java/org/apache/iotdb/session/Session.java
In most scenarios, we should check whether timeseries already exists before creating, otherwise the following exception may be thrown from server:
 
> org.apache.iotdb.db.exception.query.QueryProcessException: Timeseries [root.sg.d1.s1] already existorg.apache.iotdb.db.exception.query.QueryProcessException: Timeseries [root.sg.d1.s1] already exist at org.apache.iotdb.db.qp.executor.QueryProcessExecutor.createTimeSeries(QueryProcessExecutor.java:552) at org.apache.iotdb.db.qp.executor.QueryProcessExecutor.processNonQuery(QueryProcessExecutor.java:122) at org.apache.iotdb.db.service.TSServiceImpl.executeNonQuery(TSServiceImpl.java:1044) at org.apache.iotdb.db.service.TSServiceImpl.executePlan(TSServiceImpl.java:1387) at org.apache.iotdb.db.service.TSServiceImpl.createTimeseries(TSServiceImpl …
=> [IOTDB-503] Add checkTimeseriesExists for session

server/src/main/java/org/apache/iotdb/db/service/TSServiceImpl.java
`ZoneId` in `org.apache.iotdb.db.service.TSServiceImpl#getTimeZone` may be `null`
One of the scenes may trigger the bug:
> The IoTDB server throws the following error when accessing 0.10 server(master) by 0.9 shell client (latest release).
Exception trace:
> java.lang.NullPointerException: null at org.apache.iotdb.db.service.TSServiceImpl.getTimeZone(TSServiceImpl.java:1120) at org.apache.iotdb.service.rpc.thrift.TSIService$Processor$getTimeZone.getResult(TSIService.java:1853) at org.apache.iotdb.service.rpc.thrift.TSIService$Processor$getTimeZone.getResult(TSIService.java:1833) at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:38) at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:38) at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolS …
=> [IOTDB-502] Fix possible NPE in `org.apache.iotdb.db.service.TSServiceImpl`

docs/Documentation-CHN/UserGuide/5-Operation Manual/4-SQL Reference.md, docs/Documentation/UserGuide/5-Operation Manual/4-SQL Reference.md, server/src/main/antlr4/org/apache/iotdb/db/qp/strategy/SqlBase.g4, server/src/main/java/org/apache/iotdb/db/metadata/MManager.java, server/src/main/java/org/apache/iotdb/db/metadata/MTree.java, server/src/main/java/org/apache/iotdb/db/qp/executor/PlanExecutor.java, server/src/main/java/org/apache/iotdb/db/qp/strategy/PhysicalGenerator.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBAlignByDeviceIT.java, server/src/test/java/org/apache/iotdb/db/metadata/MManagerAdvancedTest.java, server/src/test/java/org/apache/iotdb/db/metadata/MManagerBasicTest.java
Now we have `show child paths PATH_PREFIX` to show the children nodes of the PREFIX PATH. However, sometimes we need more complex queries, like
1. Show all path prefixes (level6) which start with "root.a.b.*.d" (level1=root, level2=a, and level3=b, level4 can be everything, and level5=d).
2. Show all path prefixes which start with "root.a.b*" (level1= root, level2=a and level3 starts with b).
3. Combine 1 and 2 together. e.g., "root.a.b*.\*.d.\*", etc..
4. For select queries, it is also good to support wildcard like "select * from root.a.\*.b\*" (which means that the level4 starts with 'b')
=> [IOTDB-444] Enhanced wildcard query on device path

docs/Documentation-CHN/SystemDesign/5-DataQuery/2-SeriesReader.md, server/src/main/java/org/apache/iotdb/db/engine/storagegroup/StorageGroupProcessor.java, server/src/main/java/org/apache/iotdb/db/query/reader/universal/PriorityMergeReader.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBSeriesReaderIT.java
Limit the end time before current partition ends when adding readers to PriorityMergeReader, so that the batches never cross the partition border, and the coordinator node will be able to just return the batches without merging using a heap comparing the first element of each batch.
=> [IOTDB-520] Result of IBatchReader should not cross partition

server/src/main/antlr4/org/apache/iotdb/db/qp/strategy/SqlBase.g4, server/src/test/java/org/apache/iotdb/db/integration/IOTDBGroupByInnerIntervalIT.java, server/src/test/java/org/apache/iotdb/db/qp/PlannerTest.java
https://issues.apache.org/jira/projects/IOTDB/issues/IOTDB-446
=> [IOTDB-446] Can not create or query time series whose path starts with a digit but has strings

docs/Documentation-CHN/SystemDesign/5-DataQuery/2-SeriesReader.md, server/src/main/java/org/apache/iotdb/db/query/reader/universal/PriorityMergeReader.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBSeriesReaderIT.java
Reverts apache/incubator-iotdb#845
Currently, the writing process is divided by partition, so pages and chunks are not cross partition. The original logic is satisfied. The IT tests for partitions are retained to test the query process with partition.
=> Revert "[IOTDB-520] Result of IBatchReader should not cross partition"

server/src/main/antlr4/org/apache/iotdb/db/qp/strategy/SqlBase.g4, server/src/main/java/org/apache/iotdb/db/qp/constant/DatetimeUtils.java, server/src/test/java/org/apache/iotdb/db/sql/DatetimeQueryDataSetUtilsTest.java
Now we can support sqls like 
`select s2 from root.group1.d1 where time >= 2020-02-10`.
=> [IOTDB-498] Support date format "2020-02-10"

session/src/main/java/org/apache/iotdb/session/Config.java, session/src/main/java/org/apache/iotdb/session/Session.java, session/src/test/java/org/apache/iotdb/session/CheckPathValidityTest.java, session/src/test/java/org/apache/iotdb/session/IoTDBSessionIT.java
In session,  support path like: `root.sg`, `root.sg.1.2.3`, `root.sg.d1.1_1`, `root.sg."1.2.3"`, `root.sg.'1.2.3'`
=> [IOTDB-545] Update checkPathValidity in Session

docs/Documentation-CHN/SystemDesign/1-TsFile/4-Read.md, docs/Documentation/SystemDesign/1-TsFile/4-Read.md, tsfile/src/main/java/org/apache/iotdb/tsfile/read/expression/util/ExpressionOptimizer.java, tsfile/src/test/java/org/apache/iotdb/tsfile/read/filter/IExpressionOptimizerTest.java
Accidentally, previous pull request failed to be merged into master branch. Here is the details of the pull request.
Some logic in ExpressionOptimizer is modified to make the optimizer generate more efficient expression. For example, before the modification, s1 > 10 or time < 1 will be tranformed to
`ORExpression ( SingleSeriesExpression(s1 , value >10) ORExpression( SingleSeriesExpression(s1 , time <10), SingleSeriesExpression(s2 , time <10) ) )`
With the new logic, the query will be transformed to
`ORExpression ( SingleSeriesExpression(s1 , value >10 or time <10) SingleSeriesExpression(s2 , time <10) )`
With less SingleSeriesExpressions, the query can be executed more efficiently. Experiments shows that, if we have 3 devices, each containing 3 sensors, and the query is t<4838 or …
=> [IOTDB-476] Improve the ExpressionOptimizer

example/rocketmq/src/main/java/org/apache/iotdb/rocketmq/RocketMQConsumer.java, example/session/src/main/java/org/apache/iotdb/SessionExample.java, jdbc/src/main/java/org/apache/iotdb/jdbc/AbstractIoTDBResultSet.java, jdbc/src/main/java/org/apache/iotdb/jdbc/IoTDBConnection.java, jdbc/src/main/java/org/apache/iotdb/jdbc/IoTDBDatabaseMetadata.java, jdbc/src/main/java/org/apache/iotdb/jdbc/IoTDBNonAlignQueryResultSet.java, jdbc/src/main/java/org/apache/iotdb/jdbc/IoTDBQueryResultSet.java, jdbc/src/main/java/org/apache/iotdb/jdbc/IoTDBStatement.java, server/src/main/java/org/apache/iotdb/db/service/TSServiceImpl.java, server/src/test/java/org/apache/iotdb/db/integration/IOTDBGroupByIT.java, service-rpc/src/main/java/org/apache/iotdb/rpc/IoTDBConnectionException.java, service-rpc/src/main/java/org/apache/iotdb/rpc/RpcUtils.java, service-rpc/src/main/java/org/apache/iotdb/rpc/StatementExecutionException.java, session/src/main/java/org/apache/iotdb/session/Session.java, session/src/main/java/org/apache/iotdb/session/SessionDataSet.java, session/src/test/java/org/apache/iotdb/session/IoTDBSessionIT.java
Remove the IoTDBSessionException
Separate the error into IoTDBConnectionException and StatementExecutionException.
=> [IOTDB-549] Reorganize exception

hadoop/src/main/java/org/apache/iotdb/hadoop/fileSystem/HDFSConfUtil.java
Add a judgement before setting HDFS configuration to `HDFSOutput`, to avoid unnecessary settings.
=> [IOTDB-550] Fix TSMRWriteExample executes unsuccessfully

server/src/main/java/org/apache/iotdb/db/exception/query/LogicalOperatorException.java, server/src/main/java/org/apache/iotdb/db/exception/query/LogicalOptimizeException.java, server/src/main/java/org/apache/iotdb/db/qp/Planner.java, server/src/main/java/org/apache/iotdb/db/qp/logical/crud/BasicFunctionOperator.java, server/src/main/java/org/apache/iotdb/db/qp/logical/crud/FilterOperator.java, server/src/main/java/org/apache/iotdb/db/qp/logical/crud/InOperator.java, server/src/main/java/org/apache/iotdb/db/qp/strategy/PhysicalGenerator.java, server/src/main/java/org/apache/iotdb/db/qp/strategy/optimizer/ConcatPathOptimizer.java, server/src/main/java/org/apache/iotdb/db/service/TSServiceImpl.java, server/src/main/java/org/apache/iotdb/db/utils/SchemaUtils.java
Datatypes of timeseries are required during the query process to construct filters, readers, and datasets. They are currently determined in a one-by-one style and this PR will change it to a batched style which incurs the following benefits:
1. Reduced method calls and increased locality
2. Reduced communications in the distributed version
3. Possibly reduced datatype queries of the same series
The main affected classes are PhysicalGenerator, TSServiceImpl, and ConcatPathOptimizer.
=> Use a batched style to get series type

server/src/main/java/org/apache/iotdb/db/engine/cache/TsFileMetaDataCache.java, server/src/main/java/org/apache/iotdb/db/engine/storagegroup/StorageGroupProcessor.java, server/src/main/java/org/apache/iotdb/db/query/dataset/RawQueryDataSetWithoutValueFilter.java, server/src/main/java/org/apache/iotdb/db/query/executor/RawDataQueryExecutor.java, server/src/main/java/org/apache/iotdb/db/service/TSServiceImpl.java, tsfile/src/main/java/org/apache/iotdb/tsfile/read/common/ExceptionBatchData.java
Now, when some exceptions happened in query thread pool, it won't transfer it back to the query master thread. This will cause the query master thread to be in the parking state and all the resources it holds(e.g. some locks) won't be released.
This will consume the server resource and make it slower and slower, that's a fail-slow failure. And even worse, it may hold the lock that other task needs(e.g. readLock of writeQueryLock in TsFileResource, it may be needed by merge task).
=> Release query resource while exception happened in query producer thread

client/src/main/java/org/apache/iotdb/client/AbstractClient.java, pom.xml, server/src/main/java/org/apache/iotdb/db/qp/strategy/PhysicalGenerator.java, server/src/main/java/org/apache/iotdb/db/qp/strategy/optimizer/ConcatPathOptimizer.java, server/src/main/java/org/apache/iotdb/db/service/TSServiceImpl.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBGroupbyDeviceIT.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBMultiSeriesIT.java
This PR is a quick fix of version `0.9.x`: Return Empty ResultSet when queried series doesn't exist, instead of throwing an exception. And the issue is perfectly solved in the to-be-released version `0.10.0`.
=> [IOTDB-553] Return Empty ResultSet when queried series doesn't exist

server/src/main/java/org/apache/iotdb/db/engine/StorageEngine.java, server/src/main/java/org/apache/iotdb/db/engine/flush/TsFileFlushPolicy.java, server/src/main/java/org/apache/iotdb/db/engine/storagegroup/StorageGroupProcessor.java, server/src/test/java/org/apache/iotdb/db/engine/cache/DeviceMetaDataCacheTest.java, server/src/test/java/org/apache/iotdb/db/engine/storagegroup/StorageGroupProcessorTest.java, server/src/test/java/org/apache/iotdb/db/engine/storagegroup/TTLTest.java
When calling flush command. 
StorageEngine call syncCloseAllTsFileProcessors for each StorageGroupProcessor. 
Then, there may be an insert, which causes a new TsFileResource to be added to the list.
Then, StorageEngine call closeAllResource for each StorageGroupProcessor, the newly created resource is marked as closed but it is actually an empty file.
When executing query, the file will be seen as a closed file and read TsFileMetadata, the error occurs.
=> fix execute flush command while inserting bug

server/src/main/java/org/apache/iotdb/db/engine/storagegroup/StorageGroupProcessor.java, server/src/main/java/org/apache/iotdb/db/metadata/MManager.java, server/src/main/java/org/apache/iotdb/db/metadata/MTree.java, server/src/main/java/org/apache/iotdb/db/sync/receiver/transfer/SyncServiceImpl.java, server/src/main/java/org/apache/iotdb/db/sync/sender/manage/SyncFileManager.java, server/src/main/java/org/apache/iotdb/db/sync/sender/transfer/SyncClient.java, server/src/main/java/org/apache/iotdb/db/utils/FileLoaderUtils.java, server/src/test/java/org/apache/iotdb/db/metadata/MTreeTest.java, service-rpc/src/main/thrift/sync.thrift
When adding metadata which already exists in the engine. Previously, its result is as follow:
It's caused by not checking existence when adding metadata.
In this case, when you restart the engine, you will query nothing from the engine:
=> Fix bugs of add duplicated metadata

server/src/main/java/org/apache/iotdb/db/query/executor/LastQueryExecutor.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBLastIT.java
When processing *seqFileResources* in LAST query, we should make sure to find the last **non-empty** chunkMetadata to calculate the correct time-value pair.
Regression test added in server/src/test/java/org/apache/iotdb/db/integration/IoTDBLastIT.java
=> Fix empty ChunkMetadata in LAST query gives wrong answer bug

server/src/main/java/org/apache/iotdb/db/metadata/MManager.java
create timeseries root.sg1.d1.s1
delete timeseries root.sg1.d1.s1
restart iotdb
Main thread: recover mmanager, lock a writelock for mmangaer
after delete the timeseries, the data is also need to be deleted because the sg is empty.
Then, the StorageEngine is init and recover each storage group in a recover thread.
recover thread:
In each storage group processor, it wants to recover schema from mManager and lock a readlock.
Then it hangs.
I removed the write lock in MManager init and use a synchronized field.
=> fix recover deadlock

server/src/main/java/org/apache/iotdb/db/engine/StorageEngine.java, server/src/main/java/org/apache/iotdb/db/engine/memtable/AbstractMemTable.java, server/src/main/java/org/apache/iotdb/db/engine/memtable/IMemTable.java, server/src/main/java/org/apache/iotdb/db/engine/storagegroup/StorageGroupProcessor.java, server/src/main/java/org/apache/iotdb/db/engine/storagegroup/TsFileProcessor.java, server/src/main/java/org/apache/iotdb/db/exception/IoTDBException.java, server/src/main/java/org/apache/iotdb/db/exception/StorageEngineException.java, server/src/main/java/org/apache/iotdb/db/exception/WriteProcessException.java, server/src/main/java/org/apache/iotdb/db/exception/query/OutOfTTLException.java, server/src/main/java/org/apache/iotdb/db/monitor/StatMonitor.java, server/src/main/java/org/apache/iotdb/db/writelog/recover/LogReplayer.java, server/src/test/java/org/apache/iotdb/db/engine/cache/DeviceMetaDataCacheTest.java, server/src/test/java/org/apache/iotdb/db/engine/storagegroup/FileNodeManagerBenchmark.java, server/src/test/java/org/apache/iotdb/db/engine/storagegroup/StorageGroupProcessorTest.java, server/src/test/java/org/apache/iotdb/db/engine/storagegroup/TTLTest.java, server/src/test/java/org/apache/iotdb/db/engine/storagegroup/TsFileProcessorTest.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBTtlIT.java, server/src/test/java/org/apache/iotdb/db/query/reader/ReaderTestHelper.java
When no data is successfully written to memtable because of wrong data type or failed to write WAL. An empty memtable will be flushed.
This pr avoid flushing the empty memtable.
=> avoid flushing empty memtable

.travis.yml, server/src/main/java/org/apache/iotdb/db/sync/receiver/SyncServerManager.java, server/src/main/java/org/apache/iotdb/db/sync/thrift/SyncServiceEventHandler.java
This PR fixes two issues:
1. As we have more and more UT/ITs, 20 minutes are not enough for tests on WinOS +Travis. So, I set the timeout time back to 40 minutes.
2. I notice some travis failures are caused because:
a. An IT starts an IoTDB instance;
b. the sync module is put into a startup thread;
c. calling setting the timeout of the socket of the module. However, the startup thread for the sync module does not turn to run...
This PR will block the startup process until the socket is opened.
=> Fix Travis issues about timeout and the socket problem in the Sync module 

hive-connector/pom.xml
when I run `mvn package` on a new PC, an error occurs:
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] hive-connector 0.10.0-SNAPSHOT ..................... FAILURE [ 36.612 s]
[INFO] cluster 0.10.0-SNAPSHOT ............................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 36.940 s
[INFO] Finished at: 2020-03-20T14:52:43+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-remote-resources-plugin:1.5:process (process-resource-bundles) on project …
=> [IOTDB-563] fix downloading pentaho-aggdesigner-algorithm error from maven repo

site/src/main/.vuepress/public/css/index.css
A CSS file has no apache-rat.
see https://builds.apache.org/job/IoTDB-Pipeline/job/master/306/execution/node/67/log/
[INFO]  DONE  Success! Generated static files in src/.vuepress/dist.
[INFO] 
[INFO] 
[INFO] --- sitemapxml-maven-plugin:2.0.0:gen (default) @ iotdb-website ---
[INFO] Generate sitemap.xml - Start
[INFO] Generate sitemap.xml - OK
[INFO] 
[INFO] --- maven-surefire-plugin:2.22.0:test (integration-tests) @ iotdb-website ---
[INFO] 
[INFO] --- maven-dependency-plugin:3.1.1:analyze-only (check-dependencies) @ iotdb-website ---
[WARNING] Unused declared dependencies found:
[WARNING]    junit:junit:jar:4.12:test
[WARNING]    org.mockito:mockito-all:jar:1.10.19:test
[INFO] 
[INFO] --- apache-rat-plugin:0.13:check (license-check) @ iotdb-website ---
[INFO] Enabled default license …
=> add apache-rat for css files

README.md
As we are using coveralls now, I replace the badge of code coverage from codecov to coveralls.
=> Replace the Badge of codecov to coveralls

server/src/main/java/org/apache/iotdb/db/metadata/MTree.java, server/src/main/java/org/apache/iotdb/db/qp/executor/PlanExecutor.java, server/src/main/java/org/apache/iotdb/db/service/TSServiceImpl.java
In the PlanExecutor.insert or insertBatch. 
Multiple threads insert the same time series that does not exist. Then they will create schema automatically, cause a PathAlreadyExistException, we should ignore this exception.
=> fix concurrent auto create schema bug

client/src/test/resources/logback.xml, server/src/assembly/resources/conf/logback.xml, tsfile/src/test/resources/logback.xml
Add max backup log file number to 50 (by setting `maxBackupIndex`. [Reference](https://www.cnblogs.com/naaoveGIS/p/6501681.html))
=> Add max backup log file number

server/src/main/java/org/apache/iotdb/db/engine/storagegroup/StorageGroupProcessor.java
When restarting IoTDB, the upgrade thread will traverse the resource list in each SG. If the resource list is changed due to new writers. ConcurrentModificationException will occurs.
=> fix concurrent modification error in upgrade

server/src/main/java/org/apache/iotdb/db/engine/storagegroup/StorageGroupProcessor.java, tsfile/src/main/java/org/apache/iotdb/tsfile/write/writer/RestorableTsFileIOWriter.java
If an incompatible tsfile is met in the restart, the server will not start successfully. Just remove it and not to add into resource list.
=> fix meet incompatible file error in restart

cluster/pom.xml
Reverts apache/incubator-iotdb#986
=> Revert "[IOTDB-578] Cluster module should use the same thrift version with io…"

server/src/main/java/org/apache/iotdb/db/engine/storagegroup/StorageGroupProcessor.java, server/src/main/java/org/apache/iotdb/db/service/IoTDB.java
When the server started, it first register the StorageEngine, JDBCService and UpgradeService. 
If the client write new data while the upgrade thread traverses the tsfile resource list, a ConcurrentModificationException will occur.
The upgrade traverse is in the startup. no need to copy resources. Just move the JDBCService start at last.
=> [IOTDB-583] [to rel/0.9] Start JDBC service in the last

docs/UserGuide/5-Operation Manual/4-SQL Reference.md, docs/zh/UserGuide/5-Operation Manual/4-SQL Reference.md, server/src/main/java/org/apache/iotdb/db/qp/strategy/PhysicalGenerator.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBLastIT.java, server/src/test/java/org/apache/iotdb/db/qp/plan/PhysicalPlanTest.java
As discussed, the result set of **Last** query will always be displayed in a fixed three column table format and no longer support "**disable align**" syntax. 
Now the user will get an exception if adding a "**disable align**" at the end of a **Last** SQL.
=> Remove disable align syntax within LAST query

server/src/main/java/org/apache/iotdb/db/engine/storagegroup/StorageGroupProcessor.java
Use a separate serial number for file versions so that different IoTDB instances that share the same close policy will have consistent file versions despite different flush policies.
=> Separate file version from chunk version

site/pom.xml, site/src/main/package.json
Nodejs uses 512MB memory by default. However, when we upgrade vuepress from v0.x to v1.x, the memory is not enough, which causes the following errors:
[INFO] <--- Last few GCs --->
[INFO]
[INFO] FATAL ERROR: MarkCompactCollector: semi-space copy, fallback in old gen Allocation failed - JavaScript heap out of memory
[INFO] [17802:0x305e750] 310024 ms: Scavenge 1052.0 (1438.9) -> 1051.3 (1454.9) MB, 8.9 / 0.0 ms (average mu = 0.635, current mu = 0.566) allocation failure
[INFO] [17802:0x305e750] 310346 ms: Mark-sweep 1066.9 (1454.9) -> 1066.9 (1438.9) MB, 302.6 / 0.0 ms (average mu = 0.472, current mu = 0.282) allocation failure scavenge might not succeed
[INFO] [17802:0x305e750] 310356 ms: Scavenge 1066.9 (1438.9) -> 1066.2 (1454.9) MB, 9.2 / 0.0 ms (average mu = 0.472, current mu = 0.282) …
=> [IOTDB-591]enlarge memory for vue compiling

tsfile/format-changelist.md, tsfile/src/main/java/org/apache/iotdb/tsfile/file/metadata/TsFileMetadata.java, tsfile/src/main/java/org/apache/iotdb/tsfile/write/writer/ForceAppendTsFileWriter.java, tsfile/src/main/java/org/apache/iotdb/tsfile/write/writer/TsFileIOWriter.java
When we ForceOpen a TsFile and want to truncate its all metadata, we could directly get the position of MetaMarder.SEPARATOR and do truncate. No need to read each TimeseriesMetadata one by one.
=> [IOTDB-593] add metaOffset in TsFileMetadata

server/src/main/java/org/apache/iotdb/db/metadata/MManager.java
When enable parameter adapter, we first redo log, then init the seriesNumberInStorageGroups. It produces NullPointerException
=> fix init MManager bug

server/src/main/java/org/apache/iotdb/db/concurrent/WrappedRunnable.java, server/src/test/java/org/apache/iotdb/db/concurrent/IoTDBThreadPoolFactoryTest.java
PR #1015 introduced WrappedRunnable but print too many error messages in UT.
I make the error messages easy to be distinguished and reduce the number of test threads.
=> [IOTDB-573]claim the error output can be igonred in UT/ITs

client/src/assembly/resources/sbin/start-client.bat, server/src/assembly/resources/sbin/start-server.bat
I checked IoTDB-185 and it can be reproduced..
Sadly, the issue exists in v0.8.* and v0.9.*.
On winOS, if you put IoTDB in  some folder like D:\a b\iotdb, which has a blank space in the file path, then the start script will fail.
```
C:\Users\user\Downloads\a b> .\sbin\start-client.bat
````````````````````````
Starting IoTDB Client
````````````````````````
错误: 找不到或无法加载主类 b
原因: java.lang.ClassNotFoundException: b
```
Besides, start-server.bat only allows jdk8 and 11 to run IoTDB, which is not suitable because jdk12, 13 and 14 have released.
=> [IOTDB-185]fix start-client failed on WinOS if there is blank space in the file path; let start-server.bat suport jdk12,13 etc

cluster/src/main/java/org/apache/iotdb/cluster/query/ClusterPlanExecutor.java, server/src/main/java/org/apache/iotdb/db/qp/executor/PlanExecutor.java, server/src/main/java/org/apache/iotdb/db/qp/physical/PhysicalPlan.java, server/src/main/java/org/apache/iotdb/db/qp/physical/sys/AuthorPlan.java
This pull request implement author plan, including nonquery plan (such as CREATE USER) and query plan (such as LIST USER). 
The following statements are tested in the cluster:
CREATE USER ln_write_user 'write_pwd';
CREATE USER sgcc_write_user 'write_pwd';
LIST USERr;
=> [IOTDB-348] Add Author Plan

server/src/main/java/org/apache/iotdb/db/metadata/MManager.java
The  split without -1 parameter will remove the empty splits, which cause error in restart.
Also, the redo log is duplicated
=> Fix MLog recover

cluster/src/main/java/org/apache/iotdb/cluster/ClusterMain.java
Now when the user starts the iotdb cluster mode, the user can only specify the cluster configuration, and cannot override the single-server configuration. This pr is to solve this problem.
usage example:
_sbin/start-node.sh -meta_port 9111 -data_port 10001 -client_port 11001 -seed_nodes=127.0.0.1:9111:10001,127.0.0.1:9112:10002,127.0.0.1:9113:10003 -sc -rpc_port 7771_
_-sc_ is the separator between the cluster configuration and the single-server configuration, and the configuration after -sc is passed to the single-server
I hope this PR  is helpful.
=> [IOTDB-574] Specify server conf params when satrt cluster mode

server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfigCheck.java, server/src/main/java/org/apache/iotdb/db/metadata/MLogWriter.java
To upgrade old mlog, we add empty informations to all old `CREATE_TIMESERIES` records. 
We also add one more property `iotdbVersion` in system.properties for confirming whether we need to do upgrade.
=> Upgrade mlog

site/src/main/.vuepress/theme/global-components/IoTDB.vue
-- Change is on site module.
--Changing the description of 3rd slide in homepage (https://iotdb.apache.org/) carousal to resolve the grammar mistakes.
=> To Resolve grammar mistake in official website homepage

server/src/main/java/org/apache/iotdb/db/utils/AuthUtils.java
-- Resolved spelling mistakes in variable names in `AuthUtils`
-- Changing wrongly referred constant in `validatePassword` method
=> Resolving spelling mistakes in variable names in AuthUtils

server/src/main/java/org/apache/iotdb/db/engine/storagegroup/StorageGroupProcessor.java, server/src/main/java/org/apache/iotdb/db/engine/storagegroup/TsFileProcessor.java, server/src/main/java/org/apache/iotdb/db/qp/physical/crud/InsertTabletPlan.java, session/src/test/java/org/apache/iotdb/session/IoTDBSessionIT.java
When WAL is disabled,  inserting batch data with IoTDB session interfaces and update Last Query cache may crash.
JIRA issue:https://issues.apache.org/jira/browse/IOTDB-624
=> [IOTDB-624]Fix a Last cache bug when WAL is disabled

docs/UserGuide/3-Server/4-Config Manual.md, docs/UserGuide/4-Client/5-Programming - TsFile API.md, docs/zh/UserGuide/3-Server/4-Config Manual.md, docs/zh/UserGuide/4-Client/5-Programming - TsFile API.md, site/src/main/.vuepress/config.js
v0.9's docs have the following issue:
- In v0.9, there is no "load external tsfile" featuer, but the website shows it in the user guide doc.
-v0.9.2 added bloom fliter featuer but how to set it is in Programming.md, rather than Config Manual.md
=> [IOTDB-626] Fix UserGuide error of v0.9.x

hive-connector/pom.xml
pentaho-aggdesigner-algorithm is not in the maven central-repo. It requires to access repo.sprint.io. However, the repo requires https while in some pom it is defined as http.
The dependency lib is depended by calcite and hive. Therefore, upgrading Hive from 2.3.4 to 3.1.2 is a solution.
However, it is not suitable to upgrade hive version because rel/0.9 is just for fixing bugs..
Another solution is claim the correct repo address, by add the following content in hive-connector/pom.xml
```
<repositories>
<repository>
<id>for_pentaho</id>
<name>spring.io</name>
<url>https://repo.spring.io/libs-milestone</url>
<layout>default</layout>
<releases>
<enabled>true</enabled>
</releases>
<snapshots>
<enabled>false</enabled>
</snapshots>
</repository>
</repositories>
```
=> [IOTDB-563]fix pentaho can not be downloaded because of spring.io address

docs/UserGuide/7-Ecosystem Integration/1-Grafana.md, grafana/src/main/java/org/apache/iotdb/web/grafana/dao/impl/BasicDaoImpl.java, grafana/src/main/resources/application.properties, hive-connector/pom.xml
On rel/0.9, the grafana connector uses the time unit like this:
```
@Autowired
public BasicDaoImpl(JdbcTemplate jdbcTemplate) {
this.jdbcTemplate = jdbcTemplate;
Properties properties = new Properties();
String tsPrecision = properties.getProperty("timestamp_precision", "ms");
switch (tsPrecision) {
case "us":
TIMESTAMP_RADIX = 1000;
break;
case "ns":
TIMESTAMP_RADIX = 1000_000;
break;
default:
TIMESTAMP_RADIX = 1;
}
logger.info("Use timestamp precision {}", tsPrecision);
}
```
That is to say, it always is "ms"! No configuration file is read!
=> [IOTDB-636]Grafana connector does not use correct time unit

hadoop/src/main/java/org/apache/iotdb/hadoop/fileSystem/HDFSFile.java, server/src/main/java/org/apache/iotdb/db/engine/merge/task/MergeFileTask.java, server/src/main/java/org/apache/iotdb/db/engine/storagegroup/TsFileResource.java, tsfile/src/main/java/org/apache/iotdb/tsfile/fileSystem/fsFactory/HDFSFactory.java
When TsFile storage in HDFS and auto executing merge and flush, error occurs. This is caused by:
* incorrect usage of java.io.File api instead of HDFSFile and HDFSFactory.
* some function which is called by flush and merge is not implemented in HDFSFile.
=> [IOTDB-634] Fix merge and flush caused errors for TsFile storage in HDFS

example/flink/README.md, example/flink/src/main/java/org/apache/iotdb/flink/FlinkTsFileBatchSink.java, example/flink/src/main/java/org/apache/iotdb/flink/FlinkTsFileStreamSink.java, example/flink/src/main/java/org/apache/iotdb/flink/TsFlieUtils.java, flink-tsfile-connector/README.md, flink-tsfile-connector/src/main/java/org/apache/iotdb/flink/tsfile/RowTSRecordConverter.java, flink-tsfile-connector/src/main/java/org/apache/iotdb/flink/tsfile/TSRecordConverter.java, flink-tsfile-connector/src/main/java/org/apache/iotdb/flink/tsfile/TSRecordOutputFormat.java, flink-tsfile-connector/src/main/java/org/apache/iotdb/flink/tsfile/TsFileOutputFormat.java, flink-tsfile-connector/src/test/java/org/apache/iotdb/flink/tsfile/RowTSRecordOutputFormatITCase.java, flink-tsfile-connector/src/test/java/org/apache/iotdb/flink/tsfile/RowTSRecordOutputFormatTest.java, flink-tsfile-connector/src/test/java/org/apache/iotdb/flink/tsfile/RowTsFileConnectorTestBase.java, flink-tsfile-connector/src/test/java/org/apache/iotdb/flink/tsfile/RowTsFileInputFormatTestBase.java, flink-tsfile-connector/src/test/java/org/apache/iotdb/flink/tsfile/RowTsFileOutputFormatTestBase.java, flink-tsfile-connector/src/test/java/org/apache/iotdb/flink/util/TsFileWriteUtil.java, tsfile/src/main/java/org/apache/iotdb/tsfile/write/schema/Schema.java
TsFile is a columnar storage file format in Apache IoTDB. It is designed for time series data and supports efficient compression and query and is easy to be integrated into big data processing frameworks.
Apache Flink is a framework and distributed processing engine for stateful computations over unbounded and bounded data streams and becoming more and more popular in IOT scenes. So, it would be great to integrate IoTDB and Flink.
This pull request adds a TSRecordOutputFormat to support write TsFiles on flink via DataStream/DataSet API.
More detail can be found in discussion thread [1], or in the IoTDB wiki [2]
[1]https://lists.apache.org/thread.html/r6dd6afe4e8e4ca42e3ddfbc80609597788f90b214e7a81788c3b51b3%40%3Cdev.iotdb.apache.org%3E …
=> [IOTDB-560] add TSRecordOutputFormat to write TsFile via Flink DataSet/DataStream API.

server/src/main/java/org/apache/iotdb/db/engine/cache/TimeSeriesMetadataCache.java, server/src/main/java/org/apache/iotdb/db/qp/physical/crud/RawDataQueryPlan.java, server/src/main/java/org/apache/iotdb/db/qp/strategy/PhysicalGenerator.java, server/src/main/java/org/apache/iotdb/db/query/reader/series/SeriesRawDataBatchReader.java, server/src/main/java/org/apache/iotdb/db/query/timegenerator/ServerTimeGenerator.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBEngineTimeGeneratorIT.java, tsfile/src/main/java/org/apache/iotdb/tsfile/file/metadata/MetadataIndexNode.java, tsfile/src/main/java/org/apache/iotdb/tsfile/file/metadata/enums/MetadataIndexNodeType.java, tsfile/src/main/java/org/apache/iotdb/tsfile/read/TsFileSequenceReader.java, tsfile/src/main/java/org/apache/iotdb/tsfile/read/controller/MetadataQuerierByFileImpl.java
As the new TsFile MetadataIndex is designed, we could do more optimization for querying process and TimeseriesMetadata Cache.
* provide a new interface `List<TimeseriesMetadata> readTimeseriesMetadata` to get more sensors' TimeseriesMetadata and reduce IO.
* use a new method `int binarySearchInTimeseriesMetadataList` for binary searching in TimeseriesMetadataList
=> [IOTDB-631] Using new TsFile MetadataIndex to optimize query and cache

server/src/main/java/org/apache/iotdb/db/qp/executor/PlanExecutor.java, server/src/main/java/org/apache/iotdb/db/qp/strategy/optimizer/ConcatPathOptimizer.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBTagIT.java
If data is inserted using alias, it will be stored by alias path which leads to the empty result in query.
set storage group to root.sg;
create timeseries root.sg.d1.s1(speed)with datatype=FLOAT, encoding=RLE;
insert into root.sg.d1(timestamp,speed) values(1,1);
select s1 from root.sg.d1;
select speed from root.sg.d1;
=> [IOTDB-642] Data can't be inserted correctly by alias

hadoop/src/main/java/org/apache/iotdb/hadoop/fileSystem/HDFSFile.java, hadoop/src/main/java/org/apache/iotdb/hadoop/fileSystem/HDFSInput.java, hadoop/src/main/java/org/apache/iotdb/hadoop/fileSystem/HDFSOutput.java, tsfile/src/main/java/org/apache/iotdb/tsfile/read/TsFileSequenceReader.java
Fix concurrent queries cause BufferUnderflowException when storage in HDFS
* Change methods in HDFSInput to synchronized
* Add lock to TsFileSequenceReader.readHeadMagic
=> [IOTDB-643] Concurrent queries cause BufferUnderflowException when storage in HDFS

cli/src/main/java/org/apache/iotdb/cli/AbstractCli.java, server/src/main/java/org/apache/iotdb/db/metadata/MManager.java, server/src/main/java/org/apache/iotdb/db/metadata/MTree.java, server/src/main/java/org/apache/iotdb/db/qp/strategy/PhysicalGenerator.java, server/src/main/java/org/apache/iotdb/db/qp/strategy/optimizer/ConcatPathOptimizer.java, server/src/main/java/org/apache/iotdb/db/query/executor/LastQueryExecutor.java, server/src/main/java/org/apache/iotdb/db/service/TSServiceImpl.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBAliasIT.java, server/src/test/java/org/apache/iotdb/db/metadata/MTreeTest.java, tsfile/src/main/java/org/apache/iotdb/tsfile/read/common/Path.java
SQL: SELECT speed FROM root.sg.d1; (speed is the alias of s1).
Which returns the result like | Time | root.sg.d1.s1 | now.
We need to support keeping the alias in result if it's used in query, returning the result like
| Time | root.sg.d1.speed |.
This pr supports this function in rawDataQuery and lastQuery.
=> [IOTDB-661] Keep the alias column in result if it's used in query

tsfile/src/main/java/org/apache/iotdb/tsfile/file/metadata/MetadataIndexConstructor.java, tsfile/src/main/java/org/apache/iotdb/tsfile/file/metadata/MetadataIndexEntry.java, tsfile/src/main/java/org/apache/iotdb/tsfile/file/metadata/MetadataIndexNode.java, tsfile/src/main/java/org/apache/iotdb/tsfile/read/TsFileSequenceReader.java, tsfile/src/test/java/org/apache/iotdb/tsfile/file/metadata/MetadataIndexNodeTest.java, tsfile/src/test/java/org/apache/iotdb/tsfile/file/metadata/utils/TestHelper.java
Maintaining a MetadataIndexNodeType field in every metadata index node entry is unnecessary in current implement. Therefore, move MetadataIndexNodeType field to metadata index node so that all entries in this node have the same type.
=> [IOTDB-675] Move MetadataIndexNodeType from entry to node

server/src/main/java/org/apache/iotdb/db/engine/memtable/AbstractMemTable.java, server/src/main/java/org/apache/iotdb/db/service/TSServiceImpl.java
If occurs NullPointerException in AbstractMemtable in insert(), the message is null.
=> [To rel/0.9] fix null message in thrift TSStatusType

cli/src/main/java/org/apache/iotdb/cli/AbstractCli.java
After entering and executing some wrong SQL statements, execute the correct statement.
At this time, the returned result is: empty set, which is unexpected.
=> [IOTDB-681] Fix bugs caused by batch manner displaying query results in CLI

cluster/src/main/java/org/apache/iotdb/cluster/ClusterMain.java, cluster/src/main/java/org/apache/iotdb/cluster/config/ClusterDescriptor.java, cluster/src/main/java/org/apache/iotdb/cluster/server/member/MetaGroupMember.java
If the LOCAL_IP and SEED_NODES in the configuration file have both a local ip(127.0.0.1) and a real ip, the iotdb service cannot be connected to other nodes, causing raft communication to fail, and the cluster is always in the election state.
I think the LOCAL_IP and SEED_NODES should be consistent in the conf file; for the pseudo distributed mode, it can be all local ip, for the distributed mode, it must be the real ip, otherwise it will report an error at startup.
please leave your options, thanks.
=> [IOTDB-678] LOCAL_IP and SEED_NODES should be consistent in the conf file

server/src/main/java/org/apache/iotdb/db/engine/storagegroup/StorageGroupProcessor.java, server/src/main/java/org/apache/iotdb/db/engine/storagegroup/TsFileResource.java, server/src/main/java/org/apache/iotdb/db/writelog/recover/TsFileRecoverPerformer.java
When the last seq file is recovered, the endTimeMap is set and serialized. But this is not updated when inserting new data. Cause the file resource be filtered when adding a time filter.
insert into root.turbine1.d1(timestamp,s1) values(1,1);
insert into root.turbine1.d1(timestamp,s1) values(2,1);
restart iotdb
insert into root.turbine1.d1(timestamp,s1) values(12,1);
insert into root.turbine1.d1(timestamp,s1) values(13,1);
select s1 from root where time > 8
=> fix recover last file bug

.travis.yml, server/src/main/java/org/apache/iotdb/db/service/RPCService.java, server/src/main/java/org/apache/iotdb/db/service/RPCServiceThriftHandler.java, server/src/main/java/org/apache/iotdb/db/sync/receiver/SyncServerManager.java, server/src/main/java/org/apache/iotdb/db/sync/receiver/SyncServerThriftHandler.java, server/src/main/java/org/apache/iotdb/db/sync/receiver/transfer/SyncServiceImpl.java
We had JDBCServiceEventHandler but it is removed when we tried to fix the problem of Travis CI.
However, the EventHandler has the ability to release resources when a client disconnects to the server.
Therefore, we need to pick it back. And, add a similar handler for other thrift services, e.g., SyncService.
No UT added now (do not know how to add a UT to cover such a  case).
=> [IOTDB-689]add thriftEventHandler to cleanup when a client quit

session/src/main/java/org/apache/iotdb/session/pool/SessionPool.java
Now when a user uses SessionPool, and a command fails more than 3 times because the server returns IoTDBConnectionException, the user can only get message like 
"retry to execute statement on %s:%s failed %d times"
It is better to attach detailed info from the server, in case of there is more useful info.
=> [IOTDB-693]print more info if the sessionPool retry and fails more than RETRY times

server/src/main/java/org/apache/iotdb/db/service/TSServiceImpl.java, session/src/main/java/org/apache/iotdb/session/pool/SessionPool.java
The closeSession does not remove sessionId in currentSessionId.
When handleClientExist, it closeSession twice.
=> fix close twice session bug

server/src/main/java/org/apache/iotdb/db/metadata/mnode/LeafMNode.java, server/src/main/java/org/apache/iotdb/db/metadata/mnode/MNode.java
We only cache fullPath in InternalMNode
=> do not cache fullPath in LeafMNode

cluster/src/main/java/org/apache/iotdb/cluster/server/ClientServer.java, cluster/src/main/java/org/apache/iotdb/cluster/server/DataClusterServer.java, cluster/src/main/java/org/apache/iotdb/cluster/server/member/DataGroupMember.java, cluster/src/main/java/org/apache/iotdb/cluster/server/member/MetaGroupMember.java, cluster/src/main/java/org/apache/iotdb/cluster/utils/StatusUtils.java, server/src/main/java/org/apache/iotdb/db/qp/constant/SQLConstant.java, server/src/main/java/org/apache/iotdb/db/utils/CommonUtils.java, server/src/main/java/org/apache/iotdb/db/utils/TypeInferenceUtils.java, service-rpc/src/main/thrift/cluster.thrift
This pull request implements physical plan validation before fowarding. The client connects and sends requests to a node in the cluster, which should response some messages if the statement is invalid.
The validation is implemented in `MetaGroupMember` class, `validatePlan()` method.
```
Currently implemented:
- SetStorageGroupPlan: 
+ path should not exist
- InsertPlan:
+ path should exist
+ the value can be parsed into the data type of the path
```
=> [IOTDB-665] validate physical plan before fowarding

example/session/src/main/java/org/apache/iotdb/SessionExample.java, server/src/main/java/org/apache/iotdb/db/qp/executor/PlanExecutor.java, server/src/main/java/org/apache/iotdb/db/qp/physical/crud/InsertPlan.java, server/src/main/java/org/apache/iotdb/db/service/TSServiceImpl.java, server/src/main/java/org/apache/iotdb/db/utils/TypeInferenceUtils.java, server/src/main/java/org/apache/iotdb/db/writelog/recover/LogReplayer.java, server/src/test/java/org/apache/iotdb/db/engine/storagegroup/TTLTest.java, server/src/test/java/org/apache/iotdb/db/utils/TypeInferenceUtilsTest.java, service-rpc/src/main/thrift/rpc.thrift, session/src/main/java/org/apache/iotdb/session/Session.java, session/src/main/java/org/apache/iotdb/session/SessionDataSet.java, session/src/test/java/org/apache/iotdb/session/IoTDBSessionIT.java
When users use insertRecord in Object, the data type should be consistent with the value.
When users use insertRecord in String, the data type should be inferred from the value.
However, the previous rpc interface can not distinguish these two scenarios
=> [IOTDB-615] fix infer type from session

server/src/main/java/org/apache/iotdb/db/engine/storagegroup/StorageGroupProcessor.java, server/src/main/java/org/apache/iotdb/db/writelog/recover/LogReplayer.java, server/src/test/java/org/apache/iotdb/db/engine/storagegroup/TTLTest.java
When meet error when reading logs, we need to retain already recovered data in the tmp memtable.
When recover the last unclosed sequence file, we do not set the endtime. Then newly write data will all go into this new seq tsfile.
When recover, some overlapped chunk groups will be skipped.
=> fix recover endTime set bug (affect 0.10.0-SNAPSHOT)

.travis.yml, Jenkinsfile, pom.xml, site/src/main/package.json
The website source code has been moved to iotdb repo from v0.10 on, named as module site.
However, normally guys who only care about the source code of IoTDB project may do not want to compile the website code (and the compiling is time consuming and memory consuming).
Now we can use `mvn package -pl '!site'` to disable the module.
However, I'd like to disable the module by default and if someone (e.g., the Jenkins server, the website developer) wants to run it, just run `mvn package -P site`.
Or, if we want to consider the module as a subproject in IDEAJ, just click the maven panel and click Profiles -> site.
=> [IOTDB-728]Disable “site” module by default

example/session/src/main/java/org/apache/iotdb/SessionExample.java, server/src/main/java/org/apache/iotdb/db/engine/memtable/AbstractMemTable.java, server/src/main/java/org/apache/iotdb/db/engine/storagegroup/StorageGroupProcessor.java, server/src/main/java/org/apache/iotdb/db/metadata/MManager.java, server/src/main/java/org/apache/iotdb/db/metadata/MTree.java, server/src/main/java/org/apache/iotdb/db/metadata/mnode/InternalMNode.java, server/src/main/java/org/apache/iotdb/db/metadata/mnode/LeafMNode.java, server/src/main/java/org/apache/iotdb/db/metadata/mnode/StorageGroupMNode.java, server/src/main/java/org/apache/iotdb/db/qp/executor/PlanExecutor.java, server/src/main/java/org/apache/iotdb/db/qp/physical/crud/InsertPlan.java, server/src/main/java/org/apache/iotdb/db/qp/physical/crud/InsertTabletPlan.java, server/src/main/java/org/apache/iotdb/db/service/TSServiceImpl.java
(1) In MTree.getDeviceNodeWithAutoCreating(), the StorageGroup node will be created as an InternalMNode, which will cause the following MTree.getNodeByPathWithStorageGroupCheck() always throw StorageGroupNotExistException.
(2) If the measurement name has blank, when we generate new Path, the blank will be trim out. Then we create a path without blank. But in the following check, we will get the child with blank, then it stuck.
=> [IOTDB-738] Fix measurements has blank

server/src/main/java/org/apache/iotdb/db/metadata/MManager.java, server/src/main/java/org/apache/iotdb/db/metadata/MTree.java, server/src/main/java/org/apache/iotdb/db/qp/executor/PlanExecutor.java, server/src/test/java/org/apache/iotdb/db/metadata/MTreeTest.java
For count timeseries, we get all timeseries and then calculate the count. Which occupy much memory and not efficient. It's better to count while traversing the MTree.
=> [IOTDB-695] Accelerate the count timeseries query

server/src/main/java/org/apache/iotdb/db/qp/strategy/LogicalGenerator.java
This pull request supports default path in count timeseries clause.
Previously, it threws a NullPointerException when executing the statement "count timeseries group by level=2". The bug is fixed now.
=> Allow count timeseries group by level=x using default path

server/src/main/java/org/apache/iotdb/db/engine/memtable/AbstractMemTable.java, server/src/main/java/org/apache/iotdb/db/engine/storagegroup/TsFileProcessor.java, server/src/main/java/org/apache/iotdb/db/qp/executor/PlanExecutor.java, server/src/main/java/org/apache/iotdb/db/qp/physical/crud/InsertPlan.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBSimpleQueryIT.java
If we submit an empty memtable when close, it will not trigger a flush task, so the sync close will block.
=> [IOTDB-745] fix partial write and sync close bug

cluster/src/assembly/resources/conf/logback.xml, cluster/src/main/java/org/apache/iotdb/cluster/ClusterMain.java, cluster/src/main/java/org/apache/iotdb/cluster/log/applier/BaseApplier.java, cluster/src/main/java/org/apache/iotdb/cluster/log/applier/DataLogApplier.java, cluster/src/main/java/org/apache/iotdb/cluster/log/applier/MetaLogApplier.java, cluster/src/main/java/org/apache/iotdb/cluster/log/catchup/CatchUpTask.java, cluster/src/main/java/org/apache/iotdb/cluster/log/catchup/LogCatchUpTask.java, cluster/src/main/java/org/apache/iotdb/cluster/log/catchup/SnapshotCatchUpTask.java, cluster/src/main/java/org/apache/iotdb/cluster/log/manage/CommittedEntryManager.java, cluster/src/main/java/org/apache/iotdb/cluster/log/manage/PartitionedSnapshotLogManager.java, cluster/src/main/java/org/apache/iotdb/cluster/log/manage/UnCommittedEntryManager.java, cluster/src/main/java/org/apache/iotdb/cluster/log/manage/serializable/SyncLogDequeSerializer.java, cluster/src/main/java/org/apache/iotdb/cluster/query/groupby/MergeGroupByExecutor.java, cluster/src/main/java/org/apache/iotdb/cluster/server/ClientServer.java, cluster/src/main/java/org/apache/iotdb/cluster/server/handlers/caller/AppendGroupEntryHandler.java, cluster/src/main/java/org/apache/iotdb/cluster/server/handlers/caller/AppendNodeEntryHandler.java, cluster/src/main/java/org/apache/iotdb/cluster/server/handlers/caller/ElectionHandler.java, cluster/src/main/java/org/apache/iotdb/cluster/server/handlers/caller/HeartbeatHandler.java, cluster/src/main/java/org/apache/iotdb/cluster/server/handlers/caller/LogCatchUpInBatchHandler.java, cluster/src/main/java/org/apache/iotdb/cluster/server/heartbeat/HeartbeatThread.java, cluster/src/main/java/org/apache/iotdb/cluster/server/heartbeat/MetaHeartbeatThread.java, cluster/src/main/java/org/apache/iotdb/cluster/server/member/DataGroupMember.java, cluster/src/main/java/org/apache/iotdb/cluster/server/member/MetaGroupMember.java, cluster/src/main/java/org/apache/iotdb/cluster/server/member/RaftMember.java, cluster/src/test/java/org/apache/iotdb/cluster/log/catchup/CatchUpTaskTest.java, cluster/src/test/java/org/apache/iotdb/cluster/server/handlers/caller/AppendGroupEntryHandlerTest.java, cluster/src/test/java/org/apache/iotdb/cluster/server/handlers/caller/AppendNodeEntryHandlerTest.java
during matchIndex checking,start checking from follower's lastLogIndex instead of leader's lastLogIndex to accelerate checking
=> [Distrubuted] Peer tracker optimization

cluster/src/assembly/resources/conf/iotdb-cluster.properties, cluster/src/main/java/org/apache/iotdb/cluster/config/ClusterConfig.java, cluster/src/main/java/org/apache/iotdb/cluster/config/ClusterDescriptor.java, cluster/src/main/java/org/apache/iotdb/cluster/log/manage/CommittedEntryManager.java, cluster/src/main/java/org/apache/iotdb/cluster/log/manage/RaftLogManager.java, cluster/src/main/java/org/apache/iotdb/cluster/log/manage/serializable/SyncLogDequeSerializer.java, cluster/src/test/java/org/apache/iotdb/cluster/log/manage/RaftLogManagerTest.java
The main logic for deleting raft logs is as follows:
Each server periodically(3600 seconds) triggers the operation to check the deletion of the log. If the distance between the last deletion log index and  the current maximum commited index exceeds a certain threshold, it performs the deletion operation, otherwise do nothing.
please leave your opinions, thanks
=> [IOTDB-723] add raft log delete mechanism

Jenkinsfile
vuepress v1.x still has OOM bug so we have to disable the website auto deployment.
If you modify the docs, you have to manually deploy the website. For more info, read site/readme.md.
=> [IOTDB-591]disable auto deploy the website because of vuepress OOM

server/src/main/java/org/apache/iotdb/db/engine/upgrade/UpgradeLog.java, server/src/main/java/org/apache/iotdb/db/tools/upgrade/TsFileOnlineUpgradeTool.java
When using HDFS storage, users may encounter `Failed to get upgrade.txt file` error when first starting server.
Besides, when restarting server, the upgrade file path is also in `java.io.File` way.
=> [IOTDB-765] Fix failed to get upgrade.txt file when using HDFS storage

docs/UserGuide/Operation Manual/DDL Data Definition Language.md, docs/zh/UserGuide/Operation Manual/DDL Data Definition Language.md, server/src/main/antlr4/org/apache/iotdb/db/qp/strategy/SqlBase.g4, server/src/main/java/org/apache/iotdb/db/metadata/MManager.java, server/src/main/java/org/apache/iotdb/db/metadata/MTree.java, server/src/main/java/org/apache/iotdb/db/qp/executor/PlanExecutor.java, server/src/main/java/org/apache/iotdb/db/qp/logical/sys/ShowTimeSeriesOperator.java, server/src/main/java/org/apache/iotdb/db/qp/physical/sys/ShowTimeSeriesPlan.java, server/src/main/java/org/apache/iotdb/db/qp/strategy/LogicalGenerator.java, server/src/main/java/org/apache/iotdb/db/qp/strategy/PhysicalGenerator.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBSortedShowTimeseriesIT.java
The 'orderByHeatClause' is added to support this feature. The detailed syntax is:
orderByHeatClause
: ORDER BY HEAT
;
It's an optional clause, if user doesn't specify it. The action of 'show timeseries' will just be like before, the result set is sorted by the registered time of the time series.
If it is specified, firstly we will obtain all the satisfying timeseries as before, then we will sort them by the last point's timestamp. That means if the timeseries is inserted recently, it will be shown in the front. 
In the implementation, as we have got the LeafMNode before, so we can use the cachedLastValuePair field in it to get last timestamp, if the cachedLastValuePair is null, we will construct a LastQueryPlan to get it.
=> [ISSUE-1281] Show timeseries with heat sort

server/src/assembly/resources/sbin/start-server.bat, server/src/assembly/resources/tools/detect-watermark.bat, server/src/assembly/resources/tools/logVisualize/log-visualizer-cmd.bat, server/src/assembly/resources/tools/logVisualize/log-visualizer-gui.bat, server/src/assembly/resources/tools/memory-tool.bat, server/src/assembly/resources/tools/start-WalChecker.bat, server/src/assembly/resources/tools/start-sync-client.bat, server/src/assembly/resources/tools/tsfileToolSet/print-iotdb-data-dir.bat, server/src/assembly/resources/tools/tsfileToolSet/print-tsfile-resource-files.bat, server/src/assembly/resources/tools/tsfileToolSet/print-tsfile-sketch.bat, server/src/assembly/resources/tools/upgrade/offline-upgrade.bat
on WinOS, we can use "lib\*" to refer all jar files in the lib folder...
=> [IOTDB-772] The start-server.sh uses tool long java command in WinOS

cluster/src/assembly/resources/conf/iotdb-cluster.properties, cluster/src/main/java/org/apache/iotdb/cluster/config/ClusterConfig.java, cluster/src/main/java/org/apache/iotdb/cluster/config/ClusterDescriptor.java, cluster/src/main/java/org/apache/iotdb/cluster/config/ConsistencyLevel.java, cluster/src/main/java/org/apache/iotdb/cluster/exception/CheckConsistencyException.java, cluster/src/main/java/org/apache/iotdb/cluster/log/applier/BaseApplier.java, cluster/src/main/java/org/apache/iotdb/cluster/log/applier/DataLogApplier.java, cluster/src/main/java/org/apache/iotdb/cluster/query/ClusterPlanExecutor.java, cluster/src/main/java/org/apache/iotdb/cluster/query/last/ClusterLastQueryExecutor.java, cluster/src/main/java/org/apache/iotdb/cluster/server/DataClusterServer.java, cluster/src/main/java/org/apache/iotdb/cluster/server/member/DataGroupMember.java, cluster/src/main/java/org/apache/iotdb/cluster/server/member/MetaGroupMember.java, cluster/src/main/java/org/apache/iotdb/cluster/server/member/RaftMember.java, cluster/src/test/java/org/apache/iotdb/cluster/log/applier/DataLogApplierTest.java, cluster/src/test/java/org/apache/iotdb/cluster/server/member/MemberTest.java
This pr is going to support three consistency levels strong, mid and weak. Strong consistency means the server will first try to synchronize with the leader to get the newest meta data, if failed(timeout), directly report an error to the user; While mid consistency means the server will first try to synchronize with the leader, but if failed(timeout), it will give up and just use current data it has cached before; Weak consistency do not synchronize with the leader and simply use the local data.
=> [IOTDB-722] support three consistency levels: strong, mid and weak

server/src/main/java/org/apache/iotdb/db/engine/cache/ChunkMetadataCache.java
Issue description: https://issues.apache.org/jira/browse/IOTDB-777
In ChunkMetadataCache, key of this map LRULinkedHashMap<AccountableString, List<ChunkMetadata>> lruCache should be "file path dot deviceId dot sensorId", which the key of chunkMetadataCache was missing the separator between deviceId and sensorId.
=> [IOTDB-777]Missing dot between deviceId and sensorId in chunkMetadaCache

session/src/main/java/org/apache/iotdb/session/pool/SessionDataSetWrapper.java
No need to call SessionPool.closeResultSet().
Use this is ok:
try (SessionDataSetWrapper dataset = pool.executeQueryStatement("select * from root")) {
}
=> make SessionDataSetWrapper AutoCloseable

server/src/main/java/org/apache/iotdb/db/qp/physical/crud/InsertTabletPlan.java, server/src/test/java/org/apache/iotdb/db/writelog/WriteLogNodeTest.java
The serialization of boolean data in batch (tablet) is using is inconsistent with corresponding deserialization.
=> fix boolean batch serialization

cluster/src/main/java/org/apache/iotdb/cluster/query/ClusterPlanRouter.java, cluster/src/main/java/org/apache/iotdb/cluster/utils/PartitionUtils.java, server/src/main/java/org/apache/iotdb/db/qp/physical/PhysicalPlan.java, server/src/main/java/org/apache/iotdb/db/qp/physical/sys/AlterTimeSeriesPlan.java, tsfile/src/main/java/org/apache/iotdb/tsfile/utils/ReadWriteIOUtils.java, tsfile/src/test/java/org/apache/iotdb/tsfile/utils/ReadWriteIOUtilsTest.java
Now, the distributed version do not support ALTER tag or attributes, this PR[1] is used to add these functions.
I have tested those ALTER statements[2] in the user guide and all executed successfully.
please leave your opinions.
[1] https://issues.apache.org/jira/browse/IOTDB-781
[2] http://iotdb.apache.org/UserGuide/Master/Operation%20Manual/DDL%20Data%20Definition%20Language.html#update-tag-operation
=> [IOTDB-781] Support AlterTimeSeriesPlan in distributed version

client-py/src/client_example.py
ISSUE #1386  reports an issue that python client example can not connect to iotdb instance.
It is because that the cluster module change the Server's thrift rpc from BufferedTransport to FastFrameTransport (I am trying to know why...), but the python client example does not change that..
This PR fixes that.
=> fix python client example that be inconsistent with Server's thrift Transport instance

cluster/src/main/java/org/apache/iotdb/cluster/log/manage/serializable/SyncLogDequeSerializer.java, cluster/src/main/java/org/apache/iotdb/cluster/server/member/MetaGroupMember.java, cluster/src/main/java/org/apache/iotdb/cluster/utils/nodetool/function/LogView.java, service-rpc/src/main/java/org/apache/iotdb/rpc/RpcUtils.java
I found that it's unnecessary to persist meta after log's persistence in `SyncLogDequeSerializer`. Persisting meta is for security purposes.However, it is expensive to trigger the persistence meta every time a log is persisted, as this function only affects lastLogIndex, lastLogTerm, commitLogIndex and commitLogTerm, which can be inferred from the logs on disk under the current persistence policy. 
I tested this change with iotdb-benchmark, you can see a 27 to 66 percent performance improvement.Since the disk on my test machine was SSD, the impact of random writes was not so great. If it was HDD, the performance improvement would be more significant.
CLIENT_NUMBER=5
GROUP_NUMBER=20
DEVICE_NUMBER=20
SENSOR_NUMBER=20
BATCH_SIZE=50
LOOP=10
=> [Distributed] Remove unnecessary persistence

client-py/src/client_example.py, jdbc/src/main/java/org/apache/iotdb/jdbc/IoTDBConnection.java, server/src/main/java/org/apache/iotdb/db/service/TSServiceImpl.java, service-rpc/rpc-changelist.md, service-rpc/src/main/thrift/rpc.thrift, session/src/main/java/org/apache/iotdb/session/Session.java
As in 0.11.x  we are using TFastFrameTransport and incompatible with v0.10, we have to upgrade the RPC protocol version from V2 to V3.
=> [IOTDB-784]Update rpc protocol to V3

cluster/src/main/java/org/apache/iotdb/cluster/server/member/MetaGroupMember.java
This bug will cause timeout directly to user if one of the node in this group answer TIME_OUT. The `!=` will be true even they answered TIME_OUT.
=> [Distributed] fix time out equal bugs

server/src/main/java/org/apache/iotdb/db/metadata/MManager.java
Fix logic of creating MTree snapshot.
The snapshot should only be created when `System.currentTimeMillis() - logFile.lastModified() >= mtreeSnapshotThresholdTime` AND `logWriter.getLineNumber() >= mtreeSnapshotInterval`
=> Fix logic of creating MTree snapshot

server/src/main/java/org/apache/iotdb/db/service/RPCService.java, server/src/main/java/org/apache/iotdb/db/service/thrift/ThriftService.java, server/src/main/java/org/apache/iotdb/db/service/thrift/ThriftServiceThread.java, server/src/main/java/org/apache/iotdb/db/sync/receiver/SyncServerManager.java, server/src/main/java/org/apache/iotdb/db/sync/receiver/SyncServerManagerMBean.java, server/src/main/java/org/apache/iotdb/db/sync/sender/transfer/SyncClient.java
In this case, we do not need to maintain the two modules separately (to reduce the probability that one is fine but the other has bugs).
=> [IoTDB-786]refactor the thrift rpc service to reduce duplicate codes of RPC and Sync module

cli/pom.xml, distribution/pom.xml, hadoop/pom.xml, hive-connector/pom.xml, jdbc/pom.xml, pom.xml, server/pom.xml, service-rpc/pom.xml, session/pom.xml, thrift/pom.xml, tsfile/pom.xml
Jenkins build fails but do not know why...
we can fix some warning issues :
For more info, read https://builds.apache.org/job/IoTDB-Pipeline/job/master/412/execution/node/67/log/
=> fix maven warning about losing some plugin versions

server/src/main/java/org/apache/iotdb/db/query/control/QueryFileManager.java
The query reader reference is increased correctly in FileReaderManager.
However, as the QueryFileManager mix up the closed and unclosed file, the unclosed reader reference is not decreased correctly in FileReaderManager.
=> [IOTDB-766] fix release unclosed file reader bug

hadoop/src/main/java/org/apache/iotdb/hadoop/fileSystem/HDFSOutput.java, server/src/main/java/org/apache/iotdb/db/engine/storagegroup/StorageGroupProcessor.java, tsfile/src/main/java/org/apache/iotdb/tsfile/fileSystem/fileOutputFactory/HDFSOutputFactory.java, tsfile/src/main/java/org/apache/iotdb/tsfile/fileSystem/fsFactory/HDFSFactory.java, tsfile/src/main/java/org/apache/iotdb/tsfile/read/TsFileSequenceReader.java, tsfile/src/main/java/org/apache/iotdb/tsfile/write/writer/ForceAppendTsFileWriter.java, tsfile/src/main/java/org/apache/iotdb/tsfile/write/writer/TsFileIOWriter.java
As is described in issue #1503 , `BufferUnderflowException` when querying TsFile stored in HDFS is caused by the unflushed `outputstream` when calling `endChunkGroup()` method in `TsFileIOWriter`.
Besides, this PR also fixes some **POTENTIAL** bugs that **MAY** cause error when users config HDFS for TsFile storage.
=> [IOTDB-805] Fix BufferUnderflowException when querying TsFile stored in HDFS

cluster/src/main/java/org/apache/iotdb/cluster/server/DataClusterServer.java, cluster/src/main/java/org/apache/iotdb/cluster/server/heartbeat/HeartbeatThread.java, cluster/src/main/java/org/apache/iotdb/cluster/server/member/RaftMember.java
clear service map after rebuilding datagroups to avoid read old leader from old datamember which may be wrong
=> [Distributed] Fix a timeout bug

server/src/main/java/org/apache/iotdb/db/engine/querycontext/ReadOnlyMemChunk.java, server/src/main/java/org/apache/iotdb/db/metadata/MManager.java, server/src/main/java/org/apache/iotdb/db/metadata/MTree.java, server/src/main/java/org/apache/iotdb/db/metadata/mnode/MNode.java, server/src/main/java/org/apache/iotdb/db/metadata/mnode/MeasurementMNode.java, server/src/main/java/org/apache/iotdb/db/qp/logical/sys/CreateTimeSeriesOperator.java, server/src/main/java/org/apache/iotdb/db/qp/physical/sys/CreateTimeSeriesPlan.java, server/src/main/java/org/apache/iotdb/db/qp/strategy/LogicalGenerator.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBMetadataFetchIT.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBSimpleQueryIT.java, session/src/test/java/org/apache/iotdb/session/IoTDBSessionIT.java, tsfile/src/main/java/org/apache/iotdb/tsfile/write/schema/MeasurementSchema.java, tsfile/src/test/java/org/apache/iotdb/tsfile/write/schema/converter/SchemaBuilderTest.java
If not set the props, 10M timeseries will save 480M memory.
=> set props in MeasurementSchema to null by default to release memory

server/src/main/java/org/apache/iotdb/db/auth/AuthorityChecker.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBAuthorizationIT.java
As is pointed in issue #1571 , after granting `READ_TIMESERIES` privilege, user still could not use LAST.
=> [IOTDB-827] Fix no permissions for operation LAST

server/src/main/java/org/apache/iotdb/db/engine/cache/TimeSeriesMetadataCache.java, server/src/main/java/org/apache/iotdb/db/service/TSServiceImpl.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBSimpleQueryIT.java
This bug is introduced in 0.10.1-SNAPSHOT. We'd better fix it before releasing 0.10.1
=> [To rel/0.10] fix null pointer bug in reading TimeseriesMetadata

server/src/assembly/resources/conf/logback.xml
when using log.info method, the result is output to log_all file, now updated to log_info file
=> server log_info.log does not contain INFO level log

server/src/main/java/org/apache/iotdb/db/conf/adapter/ActiveTimeSeriesCounter.java
```java
@Override
public double getActiveRatio(String storageGroup) {
lock.writeLock().lock();
double ratio;
try {
ratio = activeRatioMap.get(storageGroup);
} catch (Exception e) {
ratio = 0;
LOGGER.error("Get active ratio failed", e);
} finally {
lock.writeLock().unlock();
}
return ratio;
}
```
It should use readLock instead of writeLock here
=> Use readLock in `getActiveRatio`

cluster/src/assembly/resources/conf/iotdb-cluster.properties, cluster/src/main/java/org/apache/iotdb/cluster/config/ClusterDescriptor.java
It is convenient to change the corresponding variables in the code by modifying the configuration file during testing. It is not necessary to change the code and recompile before each test.
=> Enable iotdb to set useasyncserver and useasyncapplier through configuration files

server/src/main/java/org/apache/iotdb/db/engine/memtable/AbstractMemTable.java
SQL:
```
create timeseries root.turbine1.d1.s2 with datatype=INT64, encoding=PLAIN, compression=SNAPPY
create timeseries root.turbine1.d1.s3 with datatype=INT64, encoding=PLAIN, compression=SNAPPY
insert into root.turbine1.d1(timestamp,s2,s3) values(1,2,3);
delete timeseries root.turbine1.d1.s2
create timeseries root.turbine1.d1.s2 with datatype=FLOAT, encoding=PLAIN, compression=SNAPPY
insert into root.turbine1.d1(timestamp,s2,s3) values(2,2.1,3);
```
Error:
```
java.lang.ClassCastException: java.lang.Float cannot be cast to java.lang.Long
at org.apache.iotdb.db.engine.memtable.WritableMemChunk.write(WritableMemChunk.java:47)
at org.apache.iotdb.db.engine.memtable.AbstractMemTable.write(AbstractMemTable.java:134)
at org.apache.iotdb.db.engine.memtable.AbstractMemTable.insert(AbstractMemTa …
```
=> [IOTDB-835] [To rel/0.10] Fix delete timeseries and change data type then write failed

docs/UserGuide/Operation Manual/SQL Reference.md, docs/zh/UserGuide/Operation Manual/DML Data Manipulation Language.md, docs/zh/UserGuide/Operation Manual/SQL Reference.md, server/src/main/antlr4/org/apache/iotdb/db/qp/strategy/SqlBase.g4, server/src/main/java/org/apache/iotdb/db/qp/strategy/LogicalGenerator.java
JIRA issue: https://issues.apache.org/jira/projects/IOTDB/issues/IOTDB-847?filter=allopenissues
- Fix the bug that 'List USER PRIVILEGES' cannot apply to 'root'
- Fix the bug that 'LIST PRIVILEGES USER on ' cannot apply to 'root'
- Fix typos and errors in 0.10 documentations
=> [IOTDB-847] Fix issues in Document version 0.10.X

server/src/main/java/org/apache/iotdb/db/qp/strategy/PhysicalGenerator.java, server/src/test/java/org/apache/iotdb/db/qp/PlannerTest.java
ArrayIndexOutOfBoundsException if the measurementId size is not consistent with the value size
=> [IOTDB-837] ArrayIndexOutOfBoundsException if the measurementId size is not consistent with the value size

server/src/main/java/org/apache/iotdb/db/sync/receiver/transfer/SyncServiceImpl.java, server/src/main/java/org/apache/iotdb/db/sync/sender/manage/SyncFileManager.java
In some scenario, the thrift put some bytes in the ByteBuffer, so record its position and reset it could avoid this error.
=> Fix sync bug

client-py/src/Session.py
The method `set_time_zone` of the :snake: client threw an exception with a message mentioning `get time zone`. I guess that's a typo, so I fixed it :sunglasses:
Are there tests for this client? I couldn't find any :worried:
=> Python method "set_time_zone" exception message

server/pom.xml, server/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java, server/src/test/java/org/apache/iotdb/db/conf/IoTDBDescriptorTest.java
JIRA issue: https://issues.apache.org/jira/browse/IOTDB-869
This issue occurs because IoTDB failed to load "iotdb-engine.properties" when starting on Windows.
When the file path is in the format of "D:/path" on WinOS, it will not be recognized as valid protocol when creating a URL object.
=> [IOTDB-869] Failed to insert data via Windows CLI

cli/src/main/java/org/apache/iotdb/cli/AbstractCli.java, jdbc/src/main/java/org/apache/iotdb/jdbc/IoTDBConnection.java, jdbc/src/test/java/org/apache/iotdb/jdbc/IoTDBConnectionTest.java
cli timezone will be set to cli local timezone by default, instead of server timezone
=> [IOTDB-872] Use system timezone in CLI

server/src/main/java/org/apache/iotdb/db/engine/memtable/AbstractMemTable.java, server/src/main/java/org/apache/iotdb/db/engine/storagegroup/StorageGroupProcessor.java, server/src/main/java/org/apache/iotdb/db/metadata/MManager.java, server/src/main/java/org/apache/iotdb/db/qp/executor/PlanExecutor.java, server/src/main/java/org/apache/iotdb/db/qp/physical/crud/InsertPlan.java, server/src/main/java/org/apache/iotdb/db/qp/physical/crud/InsertRowPlan.java, server/src/main/java/org/apache/iotdb/db/writelog/recover/LogReplayer.java, server/src/test/java/org/apache/iotdb/db/engine/cache/ChunkMetadataCacheTest.java, server/src/test/java/org/apache/iotdb/db/engine/modification/DeletionFileNodeTest.java, server/src/test/java/org/apache/iotdb/db/engine/modification/DeletionQueryTest.java, server/src/test/java/org/apache/iotdb/db/engine/storagegroup/StorageGroupProcessorTest.java, server/src/test/java/org/apache/iotdb/db/engine/storagegroup/TTLTest.java, server/src/test/java/org/apache/iotdb/db/writelog/recover/LogReplayerTest.java
In previous, the deviceMNode is cached in the InsertPlan.  Actually we could cache the MeasurementMNode directly instead of the MeasurementSchema and deviceMNode.
=> [IOTDB-904] fix update last cache NullPointerException

.travis.yml
The previous maven download link is invalid. So, update it to a new one.
=> Update maven download url for TravisCI (WinOS)

tsfile/src/main/java/org/apache/iotdb/tsfile/read/TsFileSequenceReader.java
Change TreeSet to List in getAllDevices
=> [IOTDB-907] Change TreeSet to List in getAllDevices

pom.xml
Right now we are not producing source jars for SNAPSHOT builds. So if you're using a SNAPSHOT version and trying to debug something, the IDE will have to use decompiling instead, which is a little unfortunate.
With this change the source jars are created for every build and not only the apache-release builds.
=> Made the source plugin create source-jars even for SNAPSHOT builds

cluster/src/main/java/org/apache/iotdb/cluster/log/applier/AsyncDataLogApplier.java, cluster/src/main/java/org/apache/iotdb/cluster/log/manage/RaftLogManager.java, cluster/src/main/java/org/apache/iotdb/cluster/server/member/RaftMember.java, cluster/src/test/java/org/apache/iotdb/cluster/log/applier/DataLogApplierTest.java, cluster/src/test/java/org/apache/iotdb/cluster/log/catchup/CatchUpTaskTest.java, cluster/src/test/java/org/apache/iotdb/cluster/log/manage/FilePartitionedSnapshotLogManagerTest.java, cluster/src/test/java/org/apache/iotdb/cluster/log/manage/MetaSingleSnapshotLogManagerTest.java, cluster/src/test/java/org/apache/iotdb/cluster/log/manage/RaftLogManagerTest.java, cluster/src/test/java/org/apache/iotdb/cluster/server/heartbeat/DataHeartbeatThreadTest.java, cluster/src/test/java/org/apache/iotdb/cluster/server/heartbeat/HeartbeatThreadTest.java
fix a deadlock when concurrently inserting and registering && applier skip remaining logs after a wrong exception && fix test
=> [Distributed] Fix a deadlock when concurrently inserting and registering && applier skip remaining logs after a wrong exception && fix test

server/src/main/java/org/apache/iotdb/db/query/control/QueryResourceManager.java
In old version, new weakReference object was constructed for each TsFileResource, which led to the statistics errors.
PS: Every object of QueryId will be cleaned in QueryResourceManager.endQuery().
=> Fix num of tsfiles statistics errors using Tracing

tsfile/src/main/java/org/apache/iotdb/tsfile/read/TsFileSequenceReader.java, tsfile/src/test/java/org/apache/iotdb/tsfile/read/GetAllDevicesTest.java, tsfile/src/test/java/org/apache/iotdb/tsfile/read/TsFileSequenceReaderTest.java, tsfile/src/test/java/org/apache/iotdb/tsfile/read/reader/ReaderTest.java, tsfile/src/test/java/org/apache/iotdb/tsfile/utils/FileGenerator.java
`getAllDevices()` in TsFileSequenceReader may cause bugs in some occasion. Therefor:
1. Add more tests for 4 occasions of MetadataIndexTree;
2. Refactor `getAllDevices()` to avoid bugs and avoid incompatible modification of TsFile structure.
=> [IOTDB-936] Refactor getAllDevices in TsFileSequenceReader

server/src/main/java/org/apache/iotdb/db/service/TSServiceImpl.java
When setting `root.tpc@127` as storage group, it should print error log in IoTDB server.
=> Print error log when set illegal storage group name

server/src/main/java/org/apache/iotdb/db/service/TSServiceImpl.java, session/src/main/java/org/apache/iotdb/session/Session.java, thrift/src/main/thrift/rpc.thrift
We should not generate a statement id for the query. Instead, we should use the statement id in the session itself.
=> Fix Session raw data query bug.

LICENSE-binary, flink-iotdb-connector/pom.xml, pom.xml
As google guava version under 24.1.1 have some vulnerability according to [1][2], so I think we need to upgrade the version.
[1]https://www.cvedetails.com/cve/CVE-2018-10237/
[2]https://github.com/google/guava/wiki/CVE-2018-10237
=> [IOTDB-939]update google guava version

docs/UserGuide/Operation Manual/DDL Data Definition Language.md, docs/UserGuide/Operation Manual/SQL Reference.md, docs/zh/UserGuide/Operation Manual/DDL Data Definition Language.md, docs/zh/UserGuide/Operation Manual/SQL Reference.md, server/src/main/java/org/apache/iotdb/db/metadata/MTree.java, server/src/test/java/org/apache/iotdb/db/metadata/MTreeTest.java
`COUNT NODES root.ln.* LEVEL=2` and `COUNT NODES root.ln LEVEL=2` are equivalent,
which means: `PrefixPath` could contains `*`, but all nodes after `*` would be ignored. Only the prefix path before `*` is valid.
=> [IOTDB-947] Fix error when counting node with wildcard

jdbc/src/main/java/org/apache/iotdb/jdbc/AbstractIoTDBJDBCResultSet.java, jdbc/src/main/java/org/apache/iotdb/jdbc/IoTDBNonAlignJDBCResultSet.java, service-rpc/src/main/java/org/apache/iotdb/rpc/IoTDBRpcDataSet.java
The wasNull method had been implemented and getXXX method should be modified according to the JDBC specification while there is null.
=> [IOTDB-912] Implement wasNull method in AbstractIoTDBJDBCResultSet

jdbc/src/main/java/org/apache/iotdb/jdbc/IoTDBResultMetadata.java
JIRA Issue: https://issues.apache.org/jira/browse/IOTDB-908
I have now implemented two methods, which are getColumnClassName() & getColumnTypeName(). Please have a review.
Btw, We still need some further discussions about how to deal with other methods such as getTableName() and getSchemaName(). What exactly are they specific to?
=> [IOTDB-908] Implement ResultSetMetadata interface for JDBC

server/src/main/java/org/apache/iotdb/db/qp/constant/SQLConstant.java
As `NOTEQUAL` equals `EQUAL_NS`, When adding two entry with the same key, the latter will overlap the former one.
=> IOTDB-889 Fix key word `EQUAL_NS` in `SQLConstant` error

server/src/main/java/org/apache/iotdb/db/metadata/MLogWriter.java
Jira Issue: https://issues.apache.org/jira/browse/IOTDB-951
=> [IOTDB-951] Fix auto-creating schema in parallel may write unrecognizable timeseries in mlog.txt

cluster/src/main/java/org/apache/iotdb/cluster/log/catchup/CatchUpTask.java, cluster/src/main/java/org/apache/iotdb/cluster/server/member/RaftMember.java, cluster/src/test/java/org/apache/iotdb/cluster/log/catchup/CatchUpTaskTest.java, server/src/main/java/org/apache/iotdb/db/metadata/MTree.java
Now, when the follower lags behind the leader a lot, one catchup task will be triggered. When catchup, it will judge whether a certain log saved in the leader's memory is consistent with the follower. If so, the leader can use logs in its memory to catch up. If the leader cannot find a log in memory that matches the follower, the leader needs to send snapshots.
When checking whether the leader's log match with the follower's, the current implementation starts from the largest index of the stored log in memory, and traverses from large to small to see whether it is consistent with the follower. However, each traversal will send one RPC. Since the maximum number of logs in memory is 1000, there may be 1000 times of RPC, and the time is O( n ). If it becomes a binary search, it only needs …
=> [IOTDB-948] Use binary search when checking the follower's match index when catchup	

cluster/src/main/java/org/apache/iotdb/cluster/query/ClusterPlanRouter.java, cluster/src/main/java/org/apache/iotdb/cluster/server/member/MetaGroupMember.java, cluster/src/main/java/org/apache/iotdb/cluster/server/member/RaftMember.java, server/src/main/java/org/apache/iotdb/db/engine/StorageEngine.java, server/src/main/java/org/apache/iotdb/db/engine/storagegroup/StorageGroupProcessor.java, server/src/main/java/org/apache/iotdb/db/exception/BatchProcessException.java, server/src/main/java/org/apache/iotdb/db/qp/executor/IPlanExecutor.java, server/src/main/java/org/apache/iotdb/db/qp/executor/PlanExecutor.java, server/src/main/java/org/apache/iotdb/db/qp/physical/PhysicalPlan.java, server/src/main/java/org/apache/iotdb/db/qp/physical/crud/InsertTabletPlan.java, server/src/main/java/org/apache/iotdb/db/qp/physical/sys/CreateMultiTimeSeriesPlan.java, server/src/main/java/org/apache/iotdb/db/service/TSServiceImpl.java
https://issues.apache.org/jira/browse/IOTDB-884
=> [IOTDB-884] group createMultiTimeseriesPlan by partitionGroup

server/src/main/java/org/apache/iotdb/db/metadata/MManager.java
There are some duplicate set storage group logs in mlog. So in recovery, an error log "root.sg1.d1" has already been set to storage group appeared. But that's normal in our concurrency control protocol. So we just catch that exception and change log level to info.
=> [IOTDB-964] Fix mlog recover log level

cli/src/test/resources/logback.xml, server/src/assembly/resources/conf/logback.xml, tsfile/src/test/resources/logback.xml
Change logback configuration:
* Update `rollingPolicy` from `TimeBasedRollingPolicy` to `FixedWindowRollingPolicy` (to delete old files according to number of files)
* Add `triggeringPolicy` of `SizeBasedTriggeringPolicy` (to limit the size of log file)
Since there is no need to maintain timestamp in log file name.
For example,
```
<rollingPolicy class="ch.qos.logback.core.rolling.FixedWindowRollingPolicy">
<fileNamePattern>${LOG_PATH}/log-error.%i.log</fileNamePattern>
<minIndex>1</minIndex>
<maxIndex>10</maxIndex>
</rollingPolicy>
<triggeringPolicy class="ch.qos.logback.core.rolling.SizeBasedTriggeringPolicy">
<maxFileSize>10MB</maxFileSize>
</triggeringPolicy>
```
As for log-error and log-warn, `maxFileSize` is 10MB, maxIndex is 10;
As for log-info and log-debug, `maxFileSize` is 50MB, …
=> [IOTDB-970] Change logback rollingPolicy and triggeringPolicy

docs/UserGuide/Operation Manual/DML Data Manipulation Language.md, docs/UserGuide/Operation Manual/SQL Reference.md, docs/zh/UserGuide/Operation Manual/DML Data Manipulation Language.md, docs/zh/UserGuide/Operation Manual/SQL Reference.md, server/src/main/java/org/apache/iotdb/db/metadata/MTree.java, server/src/main/java/org/apache/iotdb/db/qp/physical/crud/LastQueryPlan.java, server/src/main/java/org/apache/iotdb/db/query/dataset/groupby/GroupByFillDataSet.java, server/src/main/java/org/apache/iotdb/db/query/executor/LastQueryExecutor.java, server/src/main/java/org/apache/iotdb/db/query/executor/fill/LastPointReader.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBLastIT.java
JIRA issue: https://issues.apache.org/jira/browse/IOTDB-968
=> [IOTDB-968] Support time predicate in select last

tsfile/src/main/java/org/apache/iotdb/tsfile/read/TsFileSequenceReader.java
Improve `readTimeseriesMetadata()` method by not deserializing `TimeseriesMetadata` repeatedly when the buffer contains more than one measurements to be queried.
=> [IOTDB-975] Improve readTimeseriesMetadata

docs/SystemDesign/TsFile/Format.md, docs/UserGuide/Get Started/Publication.md, docs/zh/SystemDesign/TsFile/Format.md, docs/zh/UserGuide/Ecosystem Integration/Hive TsFile.md, docs/zh/UserGuide/Server/Docker Image.md, site/src/main/package.json
1. fix some errors in markdown:
"```$xslt" can not be recognized correctly. So, replacing it to shell.
2. update vue-press version to 1.7.1
=> update vue to 1.7.1 and fix shell render name in markdowns

docs/UserGuide/Operation Manual/DML Data Manipulation Language.md, docs/UserGuide/Operation Manual/SQL Reference.md, docs/zh/UserGuide/Operation Manual/DML Data Manipulation Language.md, docs/zh/UserGuide/Operation Manual/SQL Reference.md, server/src/main/java/org/apache/iotdb/db/metadata/MTree.java, server/src/main/java/org/apache/iotdb/db/qp/physical/crud/LastQueryPlan.java, server/src/main/java/org/apache/iotdb/db/qp/physical/crud/RawDataQueryPlan.java, server/src/main/java/org/apache/iotdb/db/query/dataset/groupby/GroupByFillDataSet.java, server/src/main/java/org/apache/iotdb/db/query/executor/LastQueryExecutor.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBLastIT.java
Considering query performance, we add restrictions to support only '>' or '>=' in LAST query currently.
=> Add restrictions for LAST query filter

server/src/assembly/resources/conf/logback.xml, server/src/main/java/org/apache/iotdb/db/mqtt/PublishHandler.java, server/src/main/java/org/apache/iotdb/db/qp/executor/PlanExecutor.java
In an on-line IoTDB, there is a lot of MQTT log, which causes much trouble.
2020-10-10 00:00:48,121 [nioEventLoopGroup-3-16] INFO  io.moquette.broker.metrics.MQTTMessageLogger:92 - C<-B PUBACK <1> packetID <62818> 
Besides, the measurements is null, we need to add a check
2020-06-08 15:53:11,507 [pool-4-thread-2] ERROR org.apache.iotdb.db.concurrent.IoTDBDefaultThreadExceptionHandler:31 - Exception in thread pool-4-thread-2-35 
java.lang.NullPointerException: null
at org.apache.iotdb.db.qp.executor.PlanExecutor.insert(PlanExecutor.java:891)
at org.apache.iotdb.db.qp.executor.PlanExecutor.processNonQuery(PlanExecutor.java:200)
at org.apache.iotdb.db.mqtt.PublishHandler.executeNonQuery(PublishHandler.java:116)
at org.apache.iotdb.db.mqtt.PublishHandler.onPublish(PublishHandler.java:99)
at …
=> Remove mqtt log and add InsertRowPlan check

server/src/main/java/org/apache/iotdb/db/qp/strategy/PhysicalGenerator.java, server/src/main/java/org/apache/iotdb/db/qp/strategy/optimizer/ConcatPathOptimizer.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBQueryMemoryControlIT.java, server/src/test/java/org/apache/iotdb/db/qp/plan/LogicalPlanSmallTest.java
JIRA: https://issues.apache.org/jira/browse/IOTDB-971
```
IoTDB> select count from root.group_0.d_0 slimit 10 soffset 10
Msg: 500: toIndex = 20
IoTDB> select count from root.group_0aaaa slimit 10 soffset 10
Msg: 411: Meet error in query process: SOFFSET <SOFFSETValue>: SOFFSETValue exceeds the range.
```
> The result from the first example makes little sense to users, and I think it is probably not right even, since there are 100 measurements for each device.
I think the bug has already been fixed by my PR #1884. Please check whether the problem can be reproduced on master branch before merging this PR.
I added some tests for the scenario in this PR.
--- 
> The second result is also confusing, "root.group_0aaaa" does not exist and that should be the root cause.
I made the error messages …
=> [IOTDB-971] More precise error messages of slimit and soffset

tsfile/src/main/java/org/apache/iotdb/tsfile/file/metadata/MetadataIndexNode.java, tsfile/src/main/java/org/apache/iotdb/tsfile/read/TsFileSequenceReader.java, tsfile/src/test/java/org/apache/iotdb/tsfile/file/metadata/MetadataIndexNodeTest.java
Fix reading file error in `getChunkMetadataList`, which is caused by `binarySearchInChildren`
=> [IOTDB-975] [To rel/0.10] Fix reading file error in getChunkMetadataList

server/src/main/java/org/apache/iotdb/db/metadata/PartialPath.java, server/src/main/java/org/apache/iotdb/db/qp/strategy/PhysicalGenerator.java, server/src/main/java/org/apache/iotdb/db/qp/strategy/optimizer/ConcatPathOptimizer.java, server/src/main/java/org/apache/iotdb/db/query/executor/LastQueryExecutor.java, server/src/main/java/org/apache/iotdb/db/service/TSServiceImpl.java, server/src/test/java/org/apache/iotdb/db/metadata/MTreeTest.java
Solution: use "" rather than `null` to represent  `there is no alias`
=> [Distributed] Fix thrift NPE caused by null alias

.travis.yml, server/src/main/java/org/apache/iotdb/db/engine/StorageEngine.java, server/src/main/java/org/apache/iotdb/db/service/RegisterManager.java, server/src/test/java/org/apache/iotdb/db/sync/receiver/load/FileLoaderTest.java, server/src/test/java/org/apache/iotdb/db/sync/receiver/recover/SyncReceiverLogAnalyzerTest.java, server/src/test/java/org/apache/iotdb/db/utils/EnvironmentUtils.java, server/src/test/resources/logback.xml
1. Travis usually closes 5555 port failed, because of a bug in some `tearDown()` methods..
2. This PR prolongs the wait time of closing checkTTLThread() from 30 seconds to 60 seconds
3. Once Travis finds some ports are closed failed, the travis will fail directly.
=> fix travis closing some ports failed

server/src/main/java/org/apache/iotdb/db/auth/authorizer/BasicAuthorizer.java, server/src/main/java/org/apache/iotdb/db/service/TSServiceImpl.java
How to reproduce:
run iotdb-grafana and access http://127.0.0.1:8888/search
TODO: we may break the connection if a user login failed, to avoid some malicious connections (which will take a thread for each connection).
=> fix nullpointer exception if no password is set when login

hadoop/pom.xml, hive-connector/pom.xml, pom.xml, spark-iotdb-connector/pom.xml
when releasing a new version, maven will check whether there are two different versions for a dependency.
Sadly, two dependencies in hadoop-client depend on different guava version.
Therefore, we have to converge them into one version.
=> Fix dependencies Convergence for packaing 

site/pom.xml
When graduated from the incubator, I incorrectly modify the website pom file, which leads to the docs of v0.10/0.9/0.8 lost.
=> [IOTDB-989]fix doc not found in the website

server/src/main/java/org/apache/iotdb/db/metadata/MManager.java, server/src/main/java/org/apache/iotdb/db/metadata/TagLogFile.java, tsfile/src/main/java/org/apache/iotdb/tsfile/utils/ReadWriteIOUtils.java
When should check if the tag key or value is empty before inserting it into tlog.txt. Otherwise, while restarting, we replay the tlog and when we read key and value string from tlog, will get the string length to be zero, and then will return a null.
Null can't be used as a ConcurrentHashMap key, so it will throw a NullPointerException.
=> [IOTDB-993] Fix tlog bug

grafana/pom.xml, jdbc/pom.xml, pom.xml, server/src/main/java/org/apache/iotdb/db/metadata/MManager.java, server/src/main/java/org/apache/iotdb/db/metadata/TagLogFile.java, tsfile/src/main/java/org/apache/iotdb/tsfile/utils/ReadWriteIOUtils.java
When should check if the tag key or value is empty before inserting it into tlog.txt. Otherwise, while restarting, we replay the tlog and when we read key and value string from tlog, will get the string length to be zero, and then will return a null.
Null can't be used as a ConcurrentHashMap key, so it will throw a NullPointerException.
=> [To rel/0.11] [IOTDB-993] Fix tlog bug

tsfile/src/main/java/org/apache/iotdb/tsfile/read/TsFileSequenceReader.java
If the previous query load the timeseries metadata into cache. And when it has finished for a while(the file reader has been removed from the file reader manager cache), current query use the same timeseries metadata, the cache hits. However, we have to reopne the file reader and use the reopened file reader and cached timeseries metadata to load the chunk metadata.
But the reopened reader has not init the tsfileMetadata.
=> Fix query bug

tsfile/src/main/java/org/apache/iotdb/tsfile/read/TsFileSequenceReader.java
If the previous query load the timeseries metadata into cache. And when it has finished for a while(the file reader has been removed from the file reader manager cache), current query use the same timeseries metadata, the cache hits. However, we have to reopne the file reader and use the reopened file reader and cached timeseries metadata to load the chunk metadata.
But the reopened reader has not init the tsfileMetadata.
=> [To rel/0.11 ]Fix query bug

server/src/assembly/resources/conf/iotdb-env.bat
When there are more than one memories installed in the computer, the pervious version of command can only get one memory size but not the total physical size.
=> Fix getting total memory size when there are more than one memories installed in a Windows OS computer

server/src/main/java/org/apache/iotdb/db/service/TSServiceImpl.java
https://issues.apache.org/jira/browse/IOTDB-1001
=> [IOTDB-1001] Return SUCCESS_STATUS rather than MULTIPLE_ERROR in TSServiceImpl when all inserts all successful

session/src/main/java/org/apache/iotdb/session/pool/SessionPool.java, session/src/test/java/org/apache/iotdb/session/pool/SessionPoolTest.java
Current session Pool has some concurrency problems:
1.
public static void main() {
queryByRowRecord(); // this method open a new thread to use session.
Thread.sleep(1000);
pool.close(); // this method close pool.
}
Then the pool will clear all existing sessions, which may lead to some leakage and deadlock.
2. `notifyAll()` is not called, which will lead to `wait(1000)` waits too long time.
3. More log is printed.
=> [IOTDB-1007]Fix session pool concurrency and leakage issue when pool.close is called

server/src/main/java/org/apache/iotdb/db/metadata/MLogWriter.java, server/src/test/java/org/apache/iotdb/db/utils/EnvironmentUtils.java
Fix all interrupting-related exceptions (such as `ClosedByInterruptException` / `InterruptedException`) when shutting down or restarting IoTDB in travis CI.
=> [IOTDB-1002] Fix interrupting-related exceptions in travis CI

server/src/main/java/org/apache/iotdb/db/metadata/MTree.java, server/src/main/java/org/apache/iotdb/db/query/dataset/groupby/GroupByFillDataSet.java, server/src/main/java/org/apache/iotdb/db/query/executor/LastQueryExecutor.java, server/src/main/java/org/apache/iotdb/db/query/executor/QueryRouter.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBLastIT.java
A merge lock has already been added locking the whole Last query procedure, however, this procedure may take a long time. 
This PR refactor the Last query execution process, separating it into multiple stages:
1. Get Last result by accessing cache.
2. Hold merge lock and obtain query resource.
3. Scan TsFiles to get Last value.
Now only the stage 2 will be locked.
=> Refactor LastQueryExecutor to separate the execution into multiple stages

server/src/assembly/resources/sbin/start-server.sh
need to increase max number of opened files in linux to avoid TsFileSequenceReader exception.
=> increase max open file in linux

server/src/main/java/org/apache/iotdb/db/qp/strategy/PhysicalGenerator.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBMultiSeriesIT.java
When selecting non-exist timeseries, an error message will be logged:
```
"411: Meet error in query process: org.apache.iotdb.db.exception.metadata.PathNotExistException: 
Path [root....] does not exist"
```
The exception is very unfriendly to users and may make them confused.
=> [IOTDB-1012] Remove unfriendly query process error for users

server/src/main/java/org/apache/iotdb/db/metadata/MTree.java, server/src/test/java/org/apache/iotdb/db/metadata/MManagerBasicTest.java
When executing `show child paths` for non-existent path, NullPointerException may be thrown.
=> [IOTDB-1021] Fix NullPointerException when showing child paths of non-existent path

server/src/main/java/org/apache/iotdb/db/metadata/MTree.java, server/src/main/java/org/apache/iotdb/db/qp/Planner.java, server/src/test/java/org/apache/iotdb/db/metadata/MManagerBasicTest.java
When executing `show child paths` for non-existent path, NullPointerException may be thrown.
=> [IOTDB-1021] [To rel/0.11] Fix NullPointerException when showing child paths of non-existent path

server/src/main/java/org/apache/iotdb/db/metadata/MTree.java, server/src/test/java/org/apache/iotdb/db/metadata/MManagerBasicTest.java
When executing `show child paths` for non-existent path, NullPointerException may be thrown.
=> [IOTDB-1021] [To rel/0.10] Fix NullPointerException when showing child paths of non-existent path

docs/UserGuide/Operation Manual/DML Data Manipulation Language.md, docs/zh/UserGuide/Operation Manual/DML Data Manipulation Language.md, server/src/main/java/org/apache/iotdb/db/qp/strategy/LogicalGenerator.java, server/src/main/java/org/apache/iotdb/db/qp/strategy/PhysicalGenerator.java, server/src/main/java/org/apache/iotdb/db/qp/strategy/optimizer/ConcatPathOptimizer.java, server/src/main/java/org/apache/iotdb/db/query/aggregation/AggregateResult.java, server/src/main/java/org/apache/iotdb/db/query/dataset/groupby/GroupByTimeDataSet.java, server/src/main/java/org/apache/iotdb/db/query/executor/AggregationExecutor.java, server/src/main/java/org/apache/iotdb/db/service/TSServiceImpl.java, server/src/main/java/org/apache/iotdb/db/utils/FilePathUtils.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBAggregationByLevel.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBAggregationByLevelIT.java, server/src/test/java/org/apache/iotdb/db/query/dataset/GroupByLevelDataSetTest.java, server/src/test/java/org/apache/iotdb/db/query/dataset/GroupByTimeDataSetTest.java
This PR plans to extend the "groupby level" syntax to more aggregation functions, including sum, avg, last_value, first_value, min_time, max_time, min_value, max_value.
Pay attention that this syntax currently only supports one single aggregation function with one measurement, e.g.
```
select func(<measurement>) from <path> group by level=n
```
Adding multiple aggregation functions will be regarded as wrong syntax and rejected by the server.
For the details, please refer to the design doc: https://cwiki.apache.org/confluence/display/IOTDB/Group+by+Level
=> [IOTDB-768] Extend more functions in aggregation group by level

server/src/main/java/org/apache/iotdb/db/service/TSServiceImpl.java
After some error, the system is set to read-only.
If we log too much error log when inserting data, the original error log may be covered...
=> [To rel/0.11] change error log in insertion to warn

server/src/main/java/org/apache/iotdb/db/service/TSServiceImpl.java
For NullPointerException, it most likely a bug, so log it in error level.
For other statement execution error, warn is enough.
=> catch NullPointerException and log error

server/src/main/java/org/apache/iotdb/db/engine/querycontext/ReadOnlyMemChunk.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBSimpleQueryIT.java, tsfile/src/main/java/org/apache/iotdb/tsfile/encoding/encoder/TSEncodingBuilder.java
Using default float precision when max_point_number is invalid.
=> [IOTDB-1028] fix create a timeseries but the MAX_POINT_NUMBER is not positive integer

service-rpc/src/main/java/org/apache/iotdb/rpc/IoTDBRpcDataSet.java
Change the charset of Windows console to UTF-8 does not fix the problem, since the column header is wrong again...
We'd better unify the charset to "UTF-8" instead of letting it depend on the platform.
=> [IOTDB-1034] Show timeseries error in Chinese on Windows

tsfile/src/main/java/org/apache/iotdb/tsfile/read/TsFileSequenceReader.java, tsfile/src/test/java/org/apache/iotdb/tsfile/read/TsFileSequenceReaderTest.java
=> [IOTDB-1035] [To rel/0.11] Fix bug in getDeviceTimeseriesMetadata when querying non-exist device

server/src/main/java/org/apache/iotdb/db/engine/storagegroup/TsFileResource.java
Currently delete data in files and merge will serialize tsfile resource concurrently. We need synchronize to protect it.
=> Fix TsfileResource serialize bug

session/src/test/java/org/apache/iotdb/session/IoTDBSessionSimpleIT.java, tsfile/src/main/java/org/apache/iotdb/tsfile/write/record/Tablet.java
When using insertTablet, we create a Binary[100], then insert 10 values.
The getValueBytesSize do not use the rowCount 10 when calculating the size.
#2179
=> fix insert partial tablet with binary NullPointer bug

example/flink/pom.xml, example/flink/src/main/java/org/apache/iotdb/flink/FlinkIoTDBSink.java, pom.xml
1. in master, flink-iotdb-sink registers a series with TEXT data type but write Double...
2. To run flink-iotdb-sink example on IDEA, the following dependency is needed:
```
<dependency>
<groupId>org.apache.flink</groupId>
<artifactId>flink-clients_${scala.library.version}</artifactId>
<version>${flink.version}</version>
</dependency>
```
=> fix flink iotdb example for writing data with incorrect data types

server/src/main/java/org/apache/iotdb/db/service/TSServiceImpl.java
In `insertRecords()`,
if one Row has some failed measurements, then the `failedMeasurements` field is not cleaned, which leads to the info is broadcast to the next Row...
=> [IOTDB-1040]【rel/0.11】fix when one row failed, then insertRecords() does not clear the failed messages

server/src/main/java/org/apache/iotdb/db/service/TSServiceImpl.java
In `insertRecords()`,
if one Row has some failed measurements, then the `failedMeasurements` field is not cleaned, which leads to the info is broadcast to the next Row...
=> [IOTDB-1040]fix when one row failed, then insertRecords() does not clear the failed messages

server/src/main/java/org/apache/iotdb/db/query/reader/chunk/MemPageReader.java, server/src/main/java/org/apache/iotdb/db/query/reader/series/SeriesReader.java, server/src/main/java/org/apache/iotdb/db/sync/sender/transfer/SyncClient.java, server/src/test/java/org/apache/iotdb/db/integration/IOTDBGroupByIT.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBAggregationIT.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBAggregationLargeDataIT.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBAggregationSmallDataIT.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBAlignByDeviceIT.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBLargeDataIT.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBMultiOverlappedChunkInUnseqIT.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBMultiOverlappedPageIT.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBMultiSeriesIT.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBMultiStatementsIT.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBOverlappedPageIT.java, tsfile/src/main/java/org/apache/iotdb/tsfile/read/common/BatchData.java, tsfile/src/main/java/org/apache/iotdb/tsfile/read/common/BatchDataFactory.java, tsfile/src/main/java/org/apache/iotdb/tsfile/read/common/DescReadBatchData.java, tsfile/src/main/java/org/apache/iotdb/tsfile/read/common/DescReadWriteBatchData.java, tsfile/src/main/java/org/apache/iotdb/tsfile/read/reader/page/PageReader.java
When the thrift server is initialized, the protocol is:
```
if (compress) {
protocolFactory = new TCompactProtocol.Factory();
} else {
protocolFactory = new TBinaryProtocol.Factory();
}
```
So, the client must be the same.
=> [rel/0.11] fix bug that when rpc compression = true, sync client does not use compression mode

server/src/main/java/org/apache/iotdb/db/sync/sender/transfer/SyncClient.java
When the thrift server is initialized, the protocol is:
```
if (compress) {
protocolFactory = new TCompactProtocol.Factory();
} else {
protocolFactory = new TBinaryProtocol.Factory();
}
```
So, the client must be the same.
=> fix bug that when rpc compression = true, sync client does not use compression mode

server/src/main/java/org/apache/iotdb/db/query/executor/LastQueryExecutor.java, server/src/main/java/org/apache/iotdb/db/query/executor/fill/LastPointReader.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBLastIT.java
This PR fixed two bugs related to Last Query:
- Nullpointer exception when querying Last: https://issues.apache.org/jira/browse/IOTDB-1049
- Querying Last of a timeseries after deletion gives incorrect result, because the invalid statistics is still used.
=> [IOTDB-1049] [rel/0.11]Fix Nullpointer exception and a delete bug in Last query

server/src/main/java/org/apache/iotdb/db/query/executor/LastQueryExecutor.java, server/src/main/java/org/apache/iotdb/db/query/executor/fill/LastPointReader.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBLastIT.java
This PR actually fixed two bugs related to Last Query:
- Nullpointer exception when querying Last: https://issues.apache.org/jira/browse/IOTDB-1049
- Querying Last of a timeseries after deletion gives incorrect result, because the invalid statistics is still used.
=> [IOTDB-1049] Fix Nullpointer exception and a delete bug in Last query

cluster/src/main/java/org/apache/iotdb/cluster/metadata/CMManager.java, cluster/src/main/java/org/apache/iotdb/cluster/query/LocalQueryExecutor.java, cluster/src/main/java/org/apache/iotdb/cluster/server/member/MetaGroupMember.java
This bug will lead to a hang when auto creating schema in cluster module because the leader's wants to get unregistered timeseries from the header of partitiongroup, even he is the leader who is responsible to this work.
=> [Distributed] Fix auto create schema hang

server/src/main/java/org/apache/iotdb/db/service/TSServiceImpl.java
In Query process, when we meet NullPointerException, it will not print the exception in log_error, it just use e.printStack method which won't be recorded.
=> [To rel/0.10]Null pointer log010

server/src/main/java/org/apache/iotdb/db/service/TSServiceImpl.java
In Query process, when we meet NullPointerException, it will not print the exception in log_error, it just use e.printStack method which won't be recorded.
=> Change null pointer exception log print way in query

docs/UserGuide/Operation Manual/DML Data Manipulation Language.md, docs/zh/UserGuide/Operation Manual/DML Data Manipulation Language.md, server/src/main/java/org/apache/iotdb/db/qp/sql/IoTDBSqlVisitor.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBDeletionIT.java
This PR supports to delete all data in a timeseries if there is no where clause in delete statements.
```
delete from root.sg.d1.s0
```
=> [IOTDB-1060] Support full deletion for delete statement without where clause

server/src/main/java/org/apache/iotdb/db/query/executor/LastQueryExecutor.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBLastIT.java
After deleting all data in a timeseries, execute Last statement gives incorrect output.
```
create timeseries root.ln.wf01.wt01.temperature WITH DATATYPE=FLOAT, ENCODING=RLE
insert into root.ln.wf01.wt01(timestamp,temperature) values(200,37.7)
delete from root.ln.wf01.wt01.temperature where time < 1000
select last temperature from root.ln.wf01.wt01
```
Incorrect Output:
```
+---------------------------------------+-----------------------------+-----+
|                                   Time|                   timeseries|value|
+---------------------------------------+-----------------------------+-----+
|-292275055-05-17T00.-808:52:48+08:05:43|root.ln.wf01.wt01.temperature| null|
+---------------------------------------+-----------------------------+-----+
```
This PR fixed this issue and …
=> Fix Last query output when last value does not exist in a series

hive-connector/pom.xml
Please note the notice in https://spring.io/blog/2020/10/29/notice-of-permissions-changes-to-repo-spring-io-fall-and-winter-2020
Anonymous access using /libs-snapshot or /libs-milestone in the pom.xml, or with these configured in a remote repository, should replace them with /snapshot and /milestone, respectively.
=> Fix hive-connector CI

server/src/main/java/org/apache/iotdb/db/engine/cache/TimeSeriesMetadataCache.java
Before, the parallelism in timeseries metadata cache is in device granularity. However, it's not reasonable, because same device in different files should not block each other.
So, we change the granularity to one device in one file.
=> [To rel/0.11]Change parallelism in timeseries metadata cache

server/src/main/java/org/apache/iotdb/db/engine/cache/TimeSeriesMetadataCache.java
Before, the parallelism in timeseries metadata cache is in device granularity. However, it's not reasonable, because same device in different files should not block each other.
So, we change the granularity to one device in one file.
=> Change parallelism in timeseries metadata cache

cluster/src/main/java/org/apache/iotdb/cluster/client/DataClientProvider.java, cluster/src/main/java/org/apache/iotdb/cluster/client/async/AsyncClientPool.java, cluster/src/main/java/org/apache/iotdb/cluster/client/sync/SyncClientPool.java, cluster/src/main/java/org/apache/iotdb/cluster/query/fill/ClusterPreviousFill.java, cluster/src/main/java/org/apache/iotdb/cluster/query/reader/DataSourceInfo.java, cluster/src/main/java/org/apache/iotdb/cluster/server/member/MetaGroupMember.java, cluster/src/test/java/org/apache/iotdb/cluster/client/DataClientProviderTest.java
if the node can not be connected, the server will cause NullPointerException, this pr try to solve the problem.
=> [Distributed] fix client is null cause NullPointerException

server/src/main/java/org/apache/iotdb/db/query/executor/LastQueryExecutor.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBLastIT.java
After deleting all data in a timeseries, execute Last statement gives incorrect output.
```
create timeseries root.ln.wf01.wt01.temperature WITH DATATYPE=FLOAT, ENCODING=RLE
insert into root.ln.wf01.wt01(timestamp,temperature) values(200,37.7)
delete from root.ln.wf01.wt01.temperature where time < 1000
select last temperature from root.ln.wf01.wt01
```
Incorrect Output:
```
+---------------------------------------+-----------------------------+-----+
|                                   Time|                   timeseries|value|
+---------------------------------------+-----------------------------+-----+
|-292275055-05-17T00.-808:52:48+08:05:43|root.ln.wf01.wt01.temperature| null|
+---------------------------------------+-----------------------------+-----+
```
This PR fixed this issue and …
=> [To rel/0.11] Fix incorrect last result after deleting all data

hadoop/pom.xml, hive-connector/pom.xml, spark-iotdb-connector/pom.xml
As the google guava version under 24.1.1 have some vulnerability according to [1][2], so I think we need to upgrade the version.
[1]https://www.cvedetails.com/cve/CVE-2018-10237/
[2]https://github.com/google/guava/wiki/CVE-2018-10237
=> upgrade guava version

server/src/main/java/org/apache/iotdb/db/query/control/QueryResourceManager.java
When cal parameter `MaxDeduplicatedPathNum`, the result of `(totalFreeMemoryForRead.get() / fetchSize) / POINT_ESTIMATED_SIZE` may larger than `Integer.MAX_VALUE`. Which may lead to that `MaxDeduplicatedPathNum` will set to a nagative number, which will reject all `count(*)` query.
=> Fix a bug of cal MaxDeduplicatedPathNum

server/src/main/java/org/apache/iotdb/db/sync/receiver/transfer/SyncServiceImpl.java, server/src/main/java/org/apache/iotdb/db/sync/sender/transfer/SyncClient.java
In pr [#1721](https://github.com/apache/iotdb/pull/1721), a bug of schema synchronization in the sync module is introduced. Which will lead to that the schema can not be loaded correctly on the receiver. This pr solves this problem.
=> Fix sync schema bug

server/src/main/java/org/apache/iotdb/db/engine/cache/TimeSeriesMetadataCache.java, tsfile/src/main/java/org/apache/iotdb/tsfile/read/TsFileSequenceReader.java
Currently, we add the entry size each time we put it into cache map. However, if the key already exists in cache, we will add the size again which will cause the cache used size is higher than the actual size.
Also, in this PR, I improve the process of deserializing time series metadata cache from disk.
=> [To rel/0.11][IOTDB-1068] Fix Time series metadata cache bug

tsfile/src/main/java/org/apache/iotdb/tsfile/write/writer/TsFileIOWriter.java
after `endCurrentChunk()`, currentChunkMetadata is null. so debug log keep displaying null in here.
=> debug log always display null in here

server/src/main/java/org/apache/iotdb/db/utils/SchemaUtils.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBSimpleQueryIT.java
fix incorrect MetadataException printf info.
Something as:
error: encoding BOOLEAN does not support TS_2DIFF =>
error: encoding TS_2DIFF does not support BOOLEAN 
because BOOLEAN is not a type of encoding.
=> fix incorrect MetadataException printf info.

cluster/src/main/java/org/apache/iotdb/cluster/server/member/RaftMember.java
We will encounter a exception when starting cluster server if cpu.cores > 100, so we should change the parameters for `ThreadPoolExecutor`. As `serialToParallelPool` will only do heartbeat or add/remove node, I think the coreSize can be 'allNode.size()', and the maxSize can be set to `Math.max(allNodes.size(), Runtime.getRuntime().availableProcessors())`.
=> [Distributed] Fix init serialToParallelPool bug if cpu.cores > 100

docs/UserGuide/Ecosystem Integration/Zeppelin-IoTDB.md, docs/zh/UserGuide/Ecosystem Integration/Zeppelin-IoTDB.md
If users download Zeppelin directly, the binary package is about 1.5G.
We could give two ways of installation to avoid this big surprise.
=> [IOTDB-1086] Improve document of Zeppelin installation

server/src/main/java/org/apache/iotdb/db/engine/modification/io/LocalTextModificationAccessor.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBDeletionIT.java
cherry pick from #2306
<hr>
This PR has:
<hr>
=> [To rel/0.11] [IOTDB-1065] Fix deletion bug while trying to delete data from a timeseries which contains comma

tsfile/src/main/java/org/apache/iotdb/tsfile/encoding/bitpacking/IntPacker.java, tsfile/src/main/java/org/apache/iotdb/tsfile/encoding/bitpacking/LongPacker.java, tsfile/src/main/java/org/apache/iotdb/tsfile/utils/BytesUtils.java
=> Using system arraycopy instead of manual for loop

server/src/main/java/org/apache/iotdb/db/sync/receiver/load/FileLoaderManager.java
=> Fix the input resource leak when deserializing device owner

server/src/main/java/org/apache/iotdb/db/qp/executor/PlanExecutor.java
=> [To rel/0.11] print more insert error message in client

server/src/main/java/org/apache/iotdb/db/conf/IoTDBConstant.java, server/src/main/java/org/apache/iotdb/db/qp/constant/SQLConstant.java, server/src/main/java/org/apache/iotdb/db/qp/executor/PlanExecutor.java, server/src/main/java/org/apache/iotdb/db/query/dataset/ListDataSet.java, server/src/main/java/org/apache/iotdb/db/query/udf/builtin/BuiltinFunction.java, server/src/main/java/org/apache/iotdb/db/query/udf/service/UDFRegistrationInformation.java, server/src/main/java/org/apache/iotdb/db/query/udf/service/UDFRegistrationService.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBUDFManagementIT.java
If we want to write a built-in function by writing a UDF in the future, and require this function to be automatically loaded when the system starts and cannot be unloaded by the user, we need a special built-in UDF function registration service.
JIRA: https://issues.apache.org/jira/browse/IOTDB-1071
=> [IOTDB-1071] Built-in UDF registration service

server/src/assembly/resources/conf/iotdb-engine.properties, server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java, server/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java, server/src/main/java/org/apache/iotdb/db/engine/flush/MemTableFlushTask.java, tsfile/src/main/java/org/apache/iotdb/tsfile/write/chunk/ChunkWriterImpl.java, tsfile/src/main/java/org/apache/iotdb/tsfile/write/chunk/IChunkWriter.java
=> [IOTDB-1084] [To rel/0.11] Fix temporary memory of flushing may cause OOM

cluster/src/main/java/org/apache/iotdb/cluster/coordinator/Coordinator.java, cluster/src/main/java/org/apache/iotdb/cluster/server/MetaClusterServer.java, cluster/src/main/java/org/apache/iotdb/cluster/server/member/MetaGroupMember.java, cluster/src/test/java/org/apache/iotdb/cluster/server/member/MetaGroupMemberTest.java
This PR is for fixing bug caused by #2334 
<hr>
This PR has:
<hr>
=> fix coordinator not init bug after restart

cluster/src/main/java/org/apache/iotdb/cluster/ClusterMain.java
…rt the cluster
<hr>
This PR has:
<hr>
when adding one new node into the cluster, the server can not restart again due to the
startServerCheck to check whether the node is in the seed nodes or not.
This pr is to solve the problem
=> [IOTDB-1096]Checking local node in partitiontable's all nodes or not when restart the node

server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java, server/src/main/java/org/apache/iotdb/db/engine/storagegroup/StorageGroupProcessor.java, server/src/main/java/org/apache/iotdb/db/engine/storagegroup/TsFileProcessor.java, server/src/main/java/org/apache/iotdb/db/metadata/MManager.java, server/src/main/java/org/apache/iotdb/db/rescon/MemTableManager.java, server/src/main/java/org/apache/iotdb/db/rescon/SystemInfo.java
To reproduce this bug, 
set JVM memory size to 32GB, 
tsfile_size_threshold=268435456
memtable_size_threshold=268435456
enable_mem_control=false
and insert 200 timeseries to IoTDB.
This pr restricts the flushing memtable size in one TsfileProcessor to one.
=> [IOTDB-1069] restrict the flushing memtable number to avoid OOM when mem_control is disabled

docs/UserGuide/Operation Manual/UDF User Defined Function.md, docs/zh/UserGuide/Operation Manual/UDF User Defined Function.md, server/src/main/java/org/apache/iotdb/db/query/udf/api/UDF.java, server/src/main/java/org/apache/iotdb/db/query/udf/api/UDTF.java, server/src/main/java/org/apache/iotdb/db/query/udf/api/customizer/parameter/UDFParameterValidator.java, server/src/main/java/org/apache/iotdb/db/query/udf/api/customizer/parameter/UDFParameters.java, server/src/main/java/org/apache/iotdb/db/query/udf/api/exception/UDFAttributeNotProvidedException.java, server/src/main/java/org/apache/iotdb/db/query/udf/api/exception/UDFException.java, server/src/main/java/org/apache/iotdb/db/query/udf/api/exception/UDFInputSeriesDataTypeNotValidException.java, server/src/main/java/org/apache/iotdb/db/query/udf/api/exception/UDFInputSeriesIndexNotValidException.java, server/src/main/java/org/apache/iotdb/db/query/udf/api/exception/UDFInputSeriesNumberNotValidException.java, server/src/main/java/org/apache/iotdb/db/query/udf/api/exception/UDFParameterNotValidException.java, server/src/main/java/org/apache/iotdb/db/query/udf/core/executor/UDTFExecutor.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBUDTFAlignByTimeQueryIT.java, server/src/test/java/org/apache/iotdb/db/query/udf/example/Accumulator.java, server/src/test/java/org/apache/iotdb/db/query/udf/example/Adder.java, server/src/test/java/org/apache/iotdb/db/query/udf/example/Max.java, server/src/test/java/org/apache/iotdb/db/query/udf/example/Multiplier.java, server/src/test/java/org/apache/iotdb/db/query/udf/example/SlidingSizeWindowConstructorTester1.java, server/src/test/java/org/apache/iotdb/db/query/udf/example/SlidingTimeWindowConstructionTester.java, server/src/test/java/org/apache/iotdb/db/query/udf/example/ValidateTester.java
The interface is mainly used to validate UDFParameters and it is executed before UDTF#beforeStart is called.
JIRA: https://issues.apache.org/jira/browse/IOTDB-1098
=> [IOTDB-1098] Add interface `validate` for UDF

cluster/src/main/java/org/apache/iotdb/cluster/server/member/MetaGroupMember.java, cluster/src/main/java/org/apache/iotdb/cluster/server/member/RaftMember.java, cluster/src/test/java/org/apache/iotdb/cluster/server/member/MetaGroupMemberTest.java
=> fix metaGroupMember bug when follower foward non-query plan to leader

tsfile/src/main/java/org/apache/iotdb/tsfile/common/conf/TSFileConfig.java, tsfile/src/main/java/org/apache/iotdb/tsfile/file/metadata/MetadataIndexConstructor.java, tsfile/src/main/java/org/apache/iotdb/tsfile/file/metadata/MetadataIndexNode.java, tsfile/src/main/java/org/apache/iotdb/tsfile/read/TsFileSequenceReader.java, tsfile/src/test/java/org/apache/iotdb/tsfile/read/TsFileSequenceReaderTest.java
As for the TsFile format is re-designed in v0.12, the MetadataIndexTree structure should be updated too to support query with higher efficient.
=> [IOTDB-1082] Update MetadataIndexTree structure for v0.12

cluster/src/main/java/org/apache/iotdb/cluster/server/member/DataGroupMember.java, cluster/src/main/java/org/apache/iotdb/cluster/server/member/MetaGroupMember.java, server/src/main/java/org/apache/iotdb/db/engine/storagegroup/TsFileProcessor.java
=> Fix the condition of logger with the right level globally

server/src/main/java/org/apache/iotdb/db/engine/cache/TimeSeriesMetadataCache.java, tsfile/src/main/java/org/apache/iotdb/tsfile/read/TsFileSequenceReader.java, tsfile/src/test/java/org/apache/iotdb/tsfile/read/TimeSeriesMetadataReadTest.java, tsfile/src/test/java/org/apache/iotdb/tsfile/read/TsFileSequenceReaderTest.java, tsfile/src/test/java/org/apache/iotdb/tsfile/utils/FileGenerator.java
Currently, we add the entry size each time we put it into cache map. However, if the key already exists in cache, we will add the size again which will cause the cache used size is higher than the actual size.
Also, in this PR, I improve the process of deserializing time series metadata cache from disk.
=> [IOTDB-1068] Fix Time series metadata cache bug

jdbc/src/main/java/org/apache/iotdb/jdbc/Config.java, jdbc/src/main/java/org/apache/iotdb/jdbc/IoTDBConnection.java, jdbc/src/main/java/org/apache/iotdb/jdbc/IoTDBConnectionParams.java, jdbc/src/main/java/org/apache/iotdb/jdbc/Utils.java, server/src/main/java/org/apache/iotdb/db/engine/cache/TimeSeriesMetadataCache.java, server/src/main/java/org/apache/iotdb/db/sync/sender/transfer/SyncClient.java, session/src/main/java/org/apache/iotdb/session/Config.java, session/src/main/java/org/apache/iotdb/session/Session.java
When querying large amount size of data, `Frame size larger than max length` may thrown in client.
=> [IOTDB-1103] [To rel/0.11] Fix frame size larger than max length error

cli/src/main/java/org/apache/iotdb/cli/AbstractCli.java, cli/src/main/java/org/apache/iotdb/cli/Cli.java, cli/src/main/java/org/apache/iotdb/cli/WinCli.java, cli/src/main/java/org/apache/iotdb/cli/utils/IoTPrinter.java
Before:
After:
<hr>
This PR has:
<hr>
=> fix the case that column length is not right in CLI when the value contains Chinese characters

cluster/src/main/java/org/apache/iotdb/cluster/server/member/MetaGroupMember.java, service-rpc/src/main/java/org/apache/iotdb/rpc/RpcUtils.java, zeppelin-interpreter/pom.xml, zeppelin-interpreter/src/main/java/org/apache/zeppelin/iotdb/IoTDBInterpreter.java, zeppelin-interpreter/src/test/java/org/apache/zeppelin/iotdb/IoTDBInterpreterTest.java
Previous implementation use `Session` to connect IoTDB, which has to judge whether someone SQL is a query or update.
JDBC enables the zeppelin interpreter to pass the SQL to the server and then use `hasResultSet` to determine the result format. As a result, the zeppelin interpreter has supported `show timeseries` now.
The functions related to connection, SQL parsing, and SQL result presentation.
Fix bugs about time display type and time zone.
<hr>
This PR has:
<hr>
Change `open()`, `cancel()` and `close()` related to the connection.
Change function `#internalInterpret()`, add `handleInputCmd()` and `executeQuery`. remove `getResultWithCols()`.
=> Switch Zeppelin connector from Session to JDBC

zeppelin-interpreter/src/main/java/org/apache/zeppelin/iotdb/IoTDBInterpreter.java, zeppelin-interpreter/src/test/java/org/apache/zeppelin/iotdb/IoTDBInterpreterTest.java
Fix bugs on query statements that ignore timestamps, namely, the result's first column is not `time`.
Referring to `org.apache.iotdb.cli.AbstractCli`, use `isIgnoreTimeStamp` to justify whether the result table has a timestamp column.
Including:
* testShowAllTTL
* testShowDevices
* testShowStorageGroup
* testShowTimeseries
* testShowTTL
* testShowVersion 
Encapsulate `stringBuilder.deleteCharAt(stringBuilder.length() - 1)` everywhere into the function `deleteLast(StringBuilder stringBuilder)`
<hr>
This PR has:
<hr>
* org.apache.zeppelin.iotdb.IoTDBInterpreter
* org.apache.zeppelin.iotdb.IoTDBInterpreterTest
=> Fix zeppelin bug on Show Storage Group

.dockerignore, .github/workflows/e2e.yml, test/e2e/base/docker-compose.yaml, test/e2e/cases/README.md, test/e2e/cases/cli/README.md, test/e2e/cases/cli/cleanup.sh, test/e2e/cases/cli/docker-compose.yaml, test/e2e/cases/cli/res/init.sql, test/e2e/cases/cli/run.sh
To enable building an image from the `master` branch on the fly, this patch rewrites the `Dockerfile` that was not able to build a docker image, and sets up an workflow yaml file for future E2E tests.
The result can be found [here](https://github.com/kezhenxu94/iotdb/runs/1486877542?check_suite_focus=true).
> P.S. Seems some of the docs links are staled and 404 now
=> e2e: add a simple E2E case and set up the workflow

NOTICE, NOTICE-binary, README_ZH.md, client-cpp/client-cpp-example/pom.xml, client-cpp/pom.xml, compile-tools/boost/pom.xml, compile-tools/pom.xml, compile-tools/thrift/pom.xml
in NOTICE the copyright time is 2008 - 2020.
change it to 0.11.3-SNAPSHOT
they should be removed.
=> Fix common issue 0.11 (copyright, readme)

cluster/src/main/java/org/apache/iotdb/cluster/log/manage/RaftLogManager.java, cluster/src/test/java/org/apache/iotdb/cluster/log/manage/RaftLogManagerTest.java
if an exception occurred during applying, the log would not be applied forever, and the server would be blocked.
this pr is to try to fix the problem.
=> set the log is applied when the exception occurred during applying

service-rpc/src/main/java/org/apache/iotdb/rpc/RpcUtils.java, service-rpc/src/main/java/org/apache/iotdb/rpc/TCompressedElasticFramedTransport.java, service-rpc/src/main/java/org/apache/iotdb/rpc/TElasticFramedTransport.java, service-rpc/src/main/java/org/apache/iotdb/rpc/TSnappyElasticFramedTransport.java
Change the previous `maxLength` to a more precise `maxSoftLength`, and allow compression buffer to oversize maxLength during compression and shrink it later, if the adjacent requests are smaller.
=> Allow compression buffer to oversize maxLength during compression and shrink it later

README.md, README_ZH.md
Inform the developers to upgrade their gcc or compile the Thrift compiler themselves when the precompiled compiler encounters some compatibility problems.
=> Add Thrift compiler related issues in README

server/src/main/java/org/apache/iotdb/db/utils/TypeInferenceUtils.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBInsertNaNIT.java
=> [ISSUE-2476] fix the case that isNumber method returns true when the input is "NaN"

server/src/main/java/org/apache/iotdb/db/engine/storagegroup/TsFileProcessor.java
=> fix nullpointerException when Measurements was maked failed in TsFileProcessor

client-cpp/client-cpp-example/src/SessionExample.cpp, client-cpp/src/main/IOTDBSession.cpp, client-cpp/src/main/IOTDBSession.h, client-cpp/src/test/cpp/sessionIT.cpp
This PR fixes JIRA Issue: https://issues.apache.org/jira/browse/IOTDB-1119
When executing "select last s1,s2,s3 from root.sg1.d1", it gives wrong answer:
```
+----------------------------------------+
| timestamp |     timeseries    |  value |
|     100   |  root.sg1.d1.s1   |    1   |
|     100   |  root.sg1.d1.s1   |    1   |
|     100   |  root.sg1.d1.s1   |    1   |
+----------------------------------------+
```
Query through CLI will give correct result:
```
+----------------------------------------+
| timestamp |     timeseries    |  value |
|     100   |  root.sg1.d1.s1   |    1   |
|     100   |  root.sg1.d1.s2   |    2   |
|     100   |  root.sg1.d1.s3   |    3   |
+----------------------------------------+
```
=> [To rel/0.11] Fix C++ SessionDataSet bug when reading value buffer

client-cpp/client-cpp-example/src/SessionExample.cpp, client-cpp/src/main/Session.cpp, client-cpp/src/main/Session.h, client-cpp/src/test/cpp/sessionIT.cpp
This PR fixes JIRA Issue: https://issues.apache.org/jira/browse/IOTDB-1119
When executing "select last s1,s2,s3 from root.sg1.d1", it gives wrong answer:
```
+----------------------------------------+
| timestamp |     timeseries    |  value |
|     100   |  root.sg1.d1.s1   |    1   |
|     100   |  root.sg1.d1.s1   |    1   |
|     100   |  root.sg1.d1.s1   |    1   |
+----------------------------------------+
```
Query through CLI will give correct result:
```
+----------------------------------------+
| timestamp |     timeseries    |  value |
|     100   |  root.sg1.d1.s1   |    1   |
|     100   |  root.sg1.d1.s2   |    2   |
|     100   |  root.sg1.d1.s3   |    3   |
+----------------------------------------+
```
=> [IOTDB-1119] Fix C++ SessionDataSet bug when reading value buffer

antlr/src/main/antlr4/org/apache/iotdb/db/qp/sql/SqlBase.g4, server/src/test/java/org/apache/iotdb/db/qp/physical/PhysicalPlanTest.java
Before
After
```
IoTDB> insert into root.sg.d1(time,s[1]) values (100,200)
IoTDB> insert into root.sg.d1(time,s[2) values (100,200)
IoTDB> select * from root
+-----------------------------+--------------+---------------+---------------+--------------+
|                         Time|root.sg.d1.s[y|root.sg.d1.s[1]|root.sg.d1.s[y]|root.sg.d1.s[2|
+-----------------------------+--------------+---------------+---------------+--------------+
|1970-01-01T08:00:00.100+08:00|         200.0|          200.0|          200.0|         200.0|
+-----------------------------+--------------+---------------+---------------+--------------+
It costs 0.299s
```
docs #2501 
<hr>
This PR has:
for an …
=> Support brackets with number in timeseries path

server/src/main/java/org/apache/iotdb/db/engine/compaction/utils/CompactionUtils.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBNewTsFileCompactionIT.java
Error message:
Since the tsfile format has been changed, while the chunk has only one page, the page will share the same statistic with its chunk.
So, think about the following case:
chunk1 has only one page named page1, chunk2 has only one page named page2, in the current process of merging, we first merge the two chunks' statistics, so the chunk1's statistics has been updated. Since chunk1 and chunk2 being merged, the current merged chunk has two pages, so we should generate two new statistics for each page. Since page1 shares the same statistics with chunk1 so, it has been updated before serializing to disk which is not right.
So, we should update chunk's statistic after chunk data being merged.
=> Fix merge bug that  page statistics incorrectly use the chunk statistics for new Tsfile Format

server/src/main/java/org/apache/iotdb/db/engine/storagegroup/StorageGroupProcessor.java
In the process of querying, we first acquire the tsFileManagement lock and then acquire writeLock in sgProcessor. However, in the process of deleting, we acquire writeLock in sgProcessor firstly, and then acquire the tsFileManagement lock. This will cause deadlock in IoTDB.
=> Fix dead lock between deleting data and querying in paralle.

example/session/src/main/java/org/apache/iotdb/SessionExample.java, jdbc/src/main/java/org/apache/iotdb/jdbc/IoTDBConnection.java, jdbc/src/main/java/org/apache/iotdb/jdbc/IoTDBNonAlignJDBCResultSet.java, jdbc/src/main/java/org/apache/iotdb/jdbc/IoTDBStatement.java, jdbc/src/test/java/org/apache/iotdb/jdbc/BatchTest.java, jdbc/src/test/java/org/apache/iotdb/jdbc/IoTDBConnectionTest.java, jdbc/src/test/java/org/apache/iotdb/jdbc/IoTDBStatementTest.java, service-rpc/src/main/java/org/apache/iotdb/rpc/IoTDBRpcDataSet.java, session/src/main/java/org/apache/iotdb/session/Session.java, session/src/main/java/org/apache/iotdb/session/SessionConnection.java, session/src/test/java/org/apache/iotdb/session/SessionUT.java, thrift/src/main/thrift/rpc.thrift
Timeout should be able to set in Session Level.
After this, there are three levels of timeout.
1. SQL level, user can set timeout as parameter, `executeQueryStatement(String sql, long timeout)
2. Session level, user can set timeout in session, next the whole session will use the same timeout.
3. Server level, if user set nothing (or zero), the default timeout in server configuration will be used.
=> [JAVA] Add timeout parameter in Session Level

server/src/main/java/org/apache/iotdb/db/engine/merge/task/MergeMultiChunkTask.java, server/src/main/java/org/apache/iotdb/db/engine/merge/task/MergeTask.java, server/src/main/java/org/apache/iotdb/db/engine/storagegroup/StorageGroupProcessor.java, server/src/test/java/org/apache/iotdb/db/engine/merge/MergeTaskTest.java, server/src/test/java/org/apache/iotdb/db/engine/storagegroup/StorageGroupProcessorTest.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBRemovePartitionIT.java
reproduce:
set storage group to root.test
insert into root.test.wf02.wt02(timestamp,status) values(1,true)
select * from root.test.wf02.wt02;
DELETE PARTITION root.test 0;
select * from root.test.wf02.wt02;
insert into root.test.wf02.wt02(timestamp,status) values(1,true)
select * from root.test.wf02.wt02;
flush
select * from root.test.wf02.wt02;
this is null.
Reason:
After the partition is deleted, if the insert data is non-sequential data. when the flush operation, 1 Unseq-file and 0 seq-file are merged,
The MergeTask traverses sequential files. If the sequential files are empty, the merge is skipped.
After the execution is complete, delete the unordered files. However, the merged file is not generated. Therefore, the data in the unordered file is lost.
=> IOTDB-1126 unseq tsfile delete due to merge

cluster/src/test/java/org/apache/iotdb/cluster/log/snapshot/PullSnapshotTaskTest.java
this pr is trying to fix the testSync UT in PullSnapshotTaskTest.  we do not change the planIndex when the tsfile is generated, so it's probability changed by the merge task.
=> disable the merge task in PullSnapshotTaskTest

server/src/main/java/org/apache/iotdb/db/metadata/MManager.java, server/src/main/java/org/apache/iotdb/db/metadata/mnode/MNode.java, server/src/test/java/org/apache/iotdb/db/metadata/MTreeTest.java
When existing [sub-device](https://issues.apache.org/jira/browse/IOTDB-750), `MNode.getLeafCount()` may get wrong result.
For example: We have 3 timeseries: `root.a.b.c`, `root.a.b.c.d`, `root.a.b.c.d.e`
The "leaf" count of `root.a` should be 3: c, d and e, which represents the number of timeseries.
Besides, the function name is also ambiguous, which should be modified to `getMeasurementMNodeCount()`.
=> [IOTDB-1137] MNode.getLeafCount error when existing sub-device

tsfile/src/main/java/org/apache/iotdb/tsfile/utils/PublicBAOS.java, tsfile/src/main/java/org/apache/iotdb/tsfile/write/chunk/ChunkWriterImpl.java
There are lots of synchronized methods in PublicBAOS which are unnecessary, because we have ensure the thread-safe property in upper-layer logic. Actually, the call of synchronized methods in ioTask of flush pipeline will cause the encoding task of flush pipeline to be slower. This may ve incurred by the implementation of synchronized key word in java. The encoding task will set the biased lock on, but the ioTask will revert the biased lock and change it to lightweight lock which may afffect the encoding thread, because the lock change process must be executed in a global safe point.
=> Improve flush pipeline

server/src/main/java/org/apache/iotdb/db/service/TSServiceImpl.java, server/src/test/java/org/apache/iotdb/db/integration/IOTDBGroupByIT.java
currently when use group by month and starttime is in February, there is a calculation error. 
```
IoTDB> select count(*) from root.sg1 group by ([2020-02-13, 2020-03-13), 1mo)
+----+---------------------+---------------------+---------------------+
|Time|count(root.sg1.d1.s4)|count(root.sg1.d1.s5)|count(root.sg1.d1.s2)|
+----+---------------------+---------------------+---------------------+
+----+---------------------+---------------------+---------------------+
IoTDB> select count(*) from root.sg1 group by ([2020-04-01, 2020-05-01), 1mo)
+-----------------------------+---------------------+---------------------+---------------------+
|                         Time|count(root.sg1.d1.s4)|count(root.sg1.d1.s5)|count(root.sg1.d1.s2)| …
```
=> bug fix - fetch size calculation error for group by month

server/src/main/java/org/apache/iotdb/db/query/control/QueryFileManager.java
We should assure that the remove used file operation in end query process is a atomic operation.
#2639
=> [Github Issue 2639] [To rel/0.11] Fix possible NPE during end query process

server/src/main/java/org/apache/iotdb/db/engine/flush/MemTableFlushTask.java, server/src/main/java/org/apache/iotdb/db/writelog/io/SingleFileLogReader.java
=> Add log for better tracing

server/src/main/java/org/apache/iotdb/db/engine/flush/MemTableFlushTask.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBSimpleQueryIT.java, tsfile/src/main/java/org/apache/iotdb/tsfile/write/chunk/ChunkWriterImpl.java
store last point when use sdt encoding
SDT compression is trigger by flushing, in current implementation the last point before flushing is not stored. 
The pr fixes this issue.
=> [IOTDB-1091] SDT improvement store last point

server/src/test/java/org/apache/iotdb/db/integration/IoTDBSimpleQueryIT.java
SDT algorithm uses a  parallelogram to filter raw data and its height is 2 * compression deviation. After SDT compression, if user uses linear fill, the resulting values will fall inside the parallelogram of two stored points. The absolute difference between filled value and original value is <= 2 * compression deviation.
=> [IOTDB-1091] add linear fill test case for sdt encoding

antlr/src/main/antlr4/org/apache/iotdb/db/qp/sql/SqlBase.g4, docs/UserGuide/Operation Manual/DDL Data Definition Language.md, docs/UserGuide/Operation Manual/SQL Reference.md, docs/zh/UserGuide/Operation Manual/DDL Data Definition Language.md, docs/zh/UserGuide/Operation Manual/SQL Reference.md, server/src/main/java/org/apache/iotdb/db/metadata/MManager.java, server/src/main/java/org/apache/iotdb/db/metadata/MTree.java, server/src/main/java/org/apache/iotdb/db/qp/logical/sys/ShowDevicesOperator.java, server/src/main/java/org/apache/iotdb/db/qp/physical/sys/ShowDevicesPlan.java, server/src/main/java/org/apache/iotdb/db/qp/sql/IoTDBSqlVisitor.java, server/src/main/java/org/apache/iotdb/db/qp/strategy/PhysicalGenerator.java, server/src/main/java/org/apache/iotdb/db/query/dataset/ShowDevicesDataSet.java, server/src/main/java/org/apache/iotdb/db/query/dataset/ShowDevicesResult.java, server/src/main/java/org/apache/iotdb/db/query/dataset/ShowResult.java, server/src/main/java/org/apache/iotdb/db/query/dataset/ShowTimeSeriesResult.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBAddSubDeviceIT.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBMetadataFetchIT.java, server/src/test/java/org/apache/iotdb/db/query/dataset/ListDataSetTest.java, session/src/test/java/org/apache/iotdb/session/IoTDBSessionIteratorIT.java, zeppelin-interpreter/src/test/java/org/apache/zeppelin/iotdb/IoTDBInterpreterTest.java
add new sql grammar 
”show devices with storage group“
```
IoTDB> show devices with storage group
+--------------+-------------+
|       devices|storage group|
+--------------+-------------+
|   root.sg1.d1|     root.sg1|
|root.sg2.d1.d2|     root.sg2|
|   root.sg2.d2|     root.sg2|
+--------------+-------------+
```
=> [ISSUE-2585] show devices with storage group

server/src/main/java/org/apache/iotdb/db/service/JMXService.java, server/src/main/java/org/apache/iotdb/db/service/MQTTService.java, server/src/main/java/org/apache/iotdb/db/service/MetricsService.java, server/src/main/java/org/apache/iotdb/db/service/RPCService.java, tsfile/src/main/java/org/apache/iotdb/tsfile/common/conf/TSFileDescriptor.java
Remove `final` if there are no subclasses by design, In this PR would like to using `static` take over `static final`.
=> Remove `final` if there are no subclasses by design.(Happy New Year)

server/src/main/java/org/apache/iotdb/db/engine/storagegroup/StorageGroupProcessor.java
One letter improvement, which add detailed error log information for exceptions.
Add more error info for `compaction submit task failed` in StorageGroupProcessor. for trace the error as follow:
`ERROR [2021-02-11 14:05:57,910] [pool-27-IoTDB-Flush-ServerServiceImpl-thread-1] org.apache.iotdb.db.engine.storagegroup.StorageGroupProcessor:1809 - root.fit.d2-0 compaction submit task failed `
=> [IOTDB-1155] One letter improvement, which add detailed error log information for exceptions

pom.xml
we use jaxb-runtime (v2.4) to solve compatibility problem of JDK 8 and 11, but its dependency, com.sun.xml.fastinfoset:FastInfoset:jar:1.2.14, is removed from maven's central repo. 
So, we have to upgrade jaxb-runtime.
=> [IOTDB-1151]fix dependency error because some jars are removed from maven's central repo

hive-connector/pom.xml
Fixes  the issue #2676 
**Describe the bug**
While packaging this project using maven with a version of release/0.10.0, a 401 Unauthorized error occurs in the hive-connector module.
**To Reproduce**
Steps to reproduce the behavior:
1. Checking out the branch into release/0.10.0 
2.  ```mvn clean package -DskipTests```
3. The following error occurs:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-remote-resources-plugin:1.7.0:process (process-resource-bundles) on project hive-connector: 
Execution process-resource-bundles of goal org.apache.maven.plugins:maven-remote-resources-plugin:1.7.0:
process failed: Error resolving project artifact: Could not transfer artifact org.pentaho:pentaho-aggdesigner-algorithm:pom:5.1.5-jhyde from/to for_pentaho …
```
=> [To rel/0.10]fix: hive-connector CI in release/0.10.0

pom.xml
Without this PR, we will see the following information in CI log:
`[WARNING] Checkstyle report not found: /Users/ jincheng.sunjc/iotwork/iotdb_ dev/tsfile/ checkstyle.xml `
After this fix, we can see the following information in CI log:
`[INFO] Importing /Users/ jincheng.sunjc/iotwork/iotdb_ dev/tsfile/target/checkstyle- report.xml `
=> [IOTDB-1157] Correct the config  of `sonar.java.checkstyle.reportPaths`.

.github/workflows/client.yml, .github/workflows/e2e.yml, .github/workflows/main-linux.yml, .github/workflows/main-mac.yml, .github/workflows/main-win.yml, code-coverage/pom.xml, compile-tools/thrift/pom.xml, grafana/pom.xml
1. Do not run  coverall and sonarcloud on forked repo;
2. allow manually run action.
3. add exec-maven-plugin's version for avoiding warning log.
=> Do not run  coverall and sonarcloud on forked repo and allow manually run action.

docs/Development/ContributeGuide.md, docs/zh/Development/ContributeGuide.md
Add IDE instructions for Google Java  Code Formatting.
=> [IOTDB-1156] Add IDE instructions for Code Formatting

cross-tests/pom.xml, server/src/main/java/org/apache/iotdb/db/engine/StorageEngine.java, server/src/main/java/org/apache/iotdb/db/sync/sender/manage/ISyncFileManager.java, server/src/main/java/org/apache/iotdb/db/sync/sender/manage/SyncFileManager.java, server/src/main/java/org/apache/iotdb/db/sync/sender/transfer/ISyncClient.java, server/src/main/java/org/apache/iotdb/db/sync/sender/transfer/SyncClient.java, server/src/main/java/org/apache/iotdb/db/utils/SyncUtils.java, server/src/test/java/org/apache/iotdb/db/sync/sender/manage/SyncFileManagerTest.java, server/src/test/java/org/apache/iotdb/db/sync/sender/recover/SyncSenderLogAnalyzerTest.java, server/src/test/java/org/apache/iotdb/db/sync/sender/transfer/SyncClientTest.java
=> fix sync bug for tsfiles's directory changed by vitural storage group

.git-blame-ignore-revs
Add .git-blame-ignore-revs for ignore the commit(70fc76de8b) of  code format refactor
This feature requires Git >= 2.24
To use it by default in git blame:
git config blame.ignoreRevsFile .git-blame-ignore-revs
=> [IOTDB-1156] Add .git-blame-ignore-revs for ignore the 70fc76d commit

server/src/main/java/org/apache/iotdb/db/utils/TypeInferenceUtils.java, server/src/main/java/org/apache/iotdb/db/utils/datastructure/DoubleTVList.java, server/src/main/java/org/apache/iotdb/db/utils/datastructure/FloatTVList.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBInsertNaNIT.java
=> [ISSUE-2687] [To rel/0.11] fix insert NaN bug

server/src/main/java/org/apache/iotdb/db/engine/compaction/level/LevelCompactionTsFileManagement.java, server/src/main/java/org/apache/iotdb/db/engine/compaction/utils/CompactionUtils.java, server/src/test/java/org/apache/iotdb/db/engine/compaction/CompactionChunkTest.java, server/src/test/java/org/apache/iotdb/db/engine/compaction/LevelCompactionModsTest.java, server/src/test/java/org/apache/iotdb/db/engine/compaction/LevelCompactionRecoverTest.java
Currently, the mods file will not be deleted although the compaction is finished.
This has some problem when user delete timeseries which is in compaction process(the delete operation will not work in the merged file).
This problem happens when user delete timeseries while a compaction is working.
So in this pr, I merge mods file to the target file.
=> [To rel/0.11] delete mods after merge

cluster/src/main/java/org/apache/iotdb/cluster/client/DataClientProvider.java, cluster/src/main/java/org/apache/iotdb/cluster/metadata/CMManager.java, cluster/src/main/java/org/apache/iotdb/cluster/metadata/MetaPuller.java, cluster/src/main/java/org/apache/iotdb/cluster/query/ClusterPlanExecutor.java, cluster/src/main/java/org/apache/iotdb/cluster/query/aggregate/ClusterAggregator.java, cluster/src/main/java/org/apache/iotdb/cluster/query/fill/ClusterPreviousFill.java, cluster/src/main/java/org/apache/iotdb/cluster/query/groupby/RemoteGroupByExecutor.java, cluster/src/main/java/org/apache/iotdb/cluster/query/last/ClusterLastQueryExecutor.java, cluster/src/main/java/org/apache/iotdb/cluster/query/reader/ClusterReaderFactory.java, cluster/src/main/java/org/apache/iotdb/cluster/query/reader/DataSourceInfo.java, cluster/src/main/java/org/apache/iotdb/cluster/query/reader/RemoteSeriesReaderByTimestamp.java, cluster/src/main/java/org/apache/iotdb/cluster/query/reader/RemoteSimpleSeriesReader.java, cluster/src/main/java/org/apache/iotdb/cluster/server/ClientServer.java, cluster/src/test/java/org/apache/iotdb/cluster/client/DataClientProviderTest.java, tsfile/src/main/java/org/apache/iotdb/tsfile/utils/PublicBAOS.java
for more details, please see https://issues.apache.org/jira/browse/IOTDB-1148
=> [IOTDB-1148]fix the client leak of client pool&use remote schema cache when check timeseries exist or not

example/hadoop/src/main/java/org/apache/iotdb/hadoop/tsfile/TsFileHelper.java, example/session/src/main/java/org/apache/iotdb/SessionExample.java, hadoop/src/test/java/org/apache/iotdb/hadoop/tsfile/TsFileTestHelper.java, hive-connector/src/test/java/org/apache/iotdb/hive/TsFileTestHelper.java, server/src/test/java/org/apache/iotdb/db/engine/merge/MergeTaskTest.java
Remove duplicated-throws,e.g.: `throws IoTDBConnectionException, BatchExecutionException, StatementExecutionException`
Remove `BatchExecutionException` due to there is a more general exception, 'org.apache.iotdb.rpc.StatementExecutionException', in the throws list already.
using `mvn spotless:check ` and `mvn spotless:apply` format code.
=> [IOTDB-1168] Remove duplicated-throws

server/src/main/java/org/apache/iotdb/db/engine/storagegroup/virtualSg/VirtualPartitioner.java, tsfile/src/main/java/org/apache/iotdb/tsfile/utils/RamUsageEstimator.java, tsfile/src/test/java/org/apache/iotdb/tsfile/utils/FileUtils.java
Remove unnecessary modifier, e.g.: `public` is unnecessary in interface.
=> [IOTDB-1167] Remove unnecessary modifier

server/src/main/java/org/apache/iotdb/db/engine/compaction/level/LevelCompactionTsFileManagement.java
After compaction, we need to delete a file. However, the chunk cache and timeseriesMetadata cache is also active which may be queried. So we have to clear it after the deletion of a file.
=> [To 0.11]fix merge delete cache bug

cluster/src/main/java/org/apache/iotdb/cluster/log/manage/FilePartitionedSnapshotLogManager.java, cluster/src/main/java/org/apache/iotdb/cluster/log/manage/PartitionedSnapshotLogManager.java
currently we generate snapshot for slots in all storage groups. 
this pr fixes it and generates timeseries schema snapshot for slots in current data group member only
=> filter slots for snapshots

antlr/src/main/antlr4/org/apache/iotdb/db/qp/sql/SqlBase.g4, docs/UserGuide/Operation Manual/DDL Data Definition Language.md, docs/zh/UserGuide/Operation Manual/DDL Data Definition Language.md, server/src/main/java/org/apache/iotdb/db/conf/IoTDBConstant.java, server/src/main/java/org/apache/iotdb/db/metadata/MManager.java, server/src/main/java/org/apache/iotdb/db/metadata/MTree.java, server/src/main/java/org/apache/iotdb/db/qp/constant/SQLConstant.java, server/src/main/java/org/apache/iotdb/db/qp/executor/PlanExecutor.java, server/src/main/java/org/apache/iotdb/db/qp/logical/sys/ShowChildNodesOperator.java, server/src/main/java/org/apache/iotdb/db/qp/physical/sys/ShowChildNodesPlan.java, server/src/main/java/org/apache/iotdb/db/qp/physical/sys/ShowPlan.java, server/src/main/java/org/apache/iotdb/db/qp/sql/IoTDBSqlVisitor.java, server/src/main/java/org/apache/iotdb/db/qp/strategy/PhysicalGenerator.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBMetadataFetchIT.java, server/src/test/java/org/apache/iotdb/db/metadata/MManagerBasicTest.java, server/src/test/java/org/apache/iotdb/db/metadata/MTreeTest.java, server/src/test/java/org/apache/iotdb/db/qp/PlannerTest.java
Hi all :
I have submitted a pr for  [ISSUE-2493](https://github.com/apache/iotdb/issues/2493), please take a look.
This issue about add SQL syntax for metadata queries  
The modules involved are as follows:
&ensp;&ensp;&ensp;1、antlr
&ensp;&ensp;&ensp;2、server/query planner 
&ensp;&ensp;&ensp;3、server/metadata
The local test results are as follows:
<hr>
This PR has:
<hr>
=> [ISSUE-2493] show child nodes path

server/src/main/java/org/apache/iotdb/db/engine/compaction/level/LevelCompactionTsFileManagement.java, server/src/main/java/org/apache/iotdb/db/engine/merge/task/MergeFileTask.java, server/src/test/java/org/apache/iotdb/db/engine/compaction/LevelCompactionCacheTest.java
User's query operation get invalid chunk after compaction.
After compaction, we need to delete a file.
However, the chunk cache and timeseriesMetadata cache is also active which may be queried.
So user can get invalid chunk.
We will clear the chunkMetadata cache and timeseriesMetadata cache after a compaction is done.
A windows ci problem about unseq compaction.
The error behaves like below (The 70,10 problem).
In unseq compaction, when delete tsfile,  if tsfile is reading now,  will throw exception and then cannot delete the old file in windows system.
As we have get the file lock, we just have to clear the TsFileSequenceReader cache before delete a tsfile.
=> [To rel/0.11] cherry-pick [ISSUE-2709,IOTDB-1178] Fix cache not cleared after unseq compaction bug, Fix windows 70,10 ci bug in unseq compaction ci

server/src/main/java/org/apache/iotdb/db/engine/merge/manage/MergeResource.java, server/src/main/java/org/apache/iotdb/db/engine/merge/selector/MaxFileMergeFileSelector.java, server/src/main/java/org/apache/iotdb/db/engine/storagegroup/TsFileResource.java, server/src/test/java/org/apache/iotdb/db/engine/merge/MaxFileMergeFileSelectorTest.java
Unseq compaction causes the overlap of seq files which lead to out-of-order query.
The query behaves like below.
The unseq compaction selector tries to find unseq files which overlap with some unsealed files.
However, the unsealed file's endTime is always Long.MIN_VALUE which will be ignored because [Long.MIN_VALUE, Long.MIN_VALUE) never overlap with other files .
As a result, the unseq compaction can not select an overlapped file if the file is unsealed. In this case, the unseq file's remaining data will be appended to the end of the last sealed seq file which is overlapped with the unsealed file.
When selecting the overlapped seq files with an unseq file, if we encounter an unsealed seq file, the unseq file will be excluded from this unseq merge task.
=> [To rel/0.11] cherry-pick [ISSUE-2746] Fix data overlapped bug after unseq compaction

server/src/main/java/org/apache/iotdb/db/exception/metadata/StorageGroupAlreadySetException.java, server/src/main/java/org/apache/iotdb/db/metadata/MTree.java, server/src/test/java/org/apache/iotdb/db/metadata/MManagerBasicTest.java, server/src/test/java/org/apache/iotdb/db/metadata/MTreeTest.java
Require more clear error message for deleting and creating storage group
https://issues.apache.org/jira/browse/IOTDB-1159?jql=project%20%3D%20IOTDB%20AND%20issuetype%20%3D%20Bug%20AND%20resolution%20%3D%20Unresolved%20ORDER%20BY%20priority%20DESC%2C%20updated%20DESC
=> [IOTDB-1159] set storage group exception message more clear

server/src/assembly/resources/conf/iotdb-engine.properties, server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java, server/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java, server/src/main/java/org/apache/iotdb/db/engine/storagegroup/StorageGroupProcessor.java
After adding the Wal Buffer Pool, the writing test with unseq data became 50% slower than before.
Before, as the descriptions of the design document(https://cwiki.apache.org/confluence/display/IOTDB/DirectByteBuffer+Pool+for+WAL) the default number of wal buffer for each time partition in each storage group is 4. 2 for seq and another 2 for unseq. However, if we have unseq data, then seq occupy 2 wal buffer, unseq occupy 2 wal buffer, now the wal buffer pool wil be empty. While one tsfile is closing,  it won't put the wal buffer back to the pool until the closing is finished. So the writing operation coming later will be blocked until the closing tsfile put its wal buffer back.
Now, I make the max wal buffer number for each time partition to be configurable in iotdb-engine.properties and …
=> Make the Wal buffer pool parameters to be configurable

server/src/main/java/org/apache/iotdb/db/qp/executor/PlanExecutor.java, server/src/main/java/org/apache/iotdb/db/qp/physical/crud/InsertRowsPlan.java, server/src/main/java/org/apache/iotdb/db/qp/physical/sys/CreateMultiTimeSeriesPlan.java, server/src/main/java/org/apache/iotdb/db/qp/physical/sys/DeleteTimeSeriesPlan.java, server/src/main/java/org/apache/iotdb/db/service/TSServiceImpl.java, server/src/main/java/org/apache/iotdb/db/utils/StatusUtils.java
1. Extract the common codes to one utils class (which is used to judge the final status when whose plan have multi rows)
2. Reduce the content of debug log printing of the InsertRowsPlan(which is too big when the bug log level is enabled, reduce the write throughput. In our test, we use the insertRecords interface to the performance,  the performance was 300,000 points/s before modification and it became 3.4 million points/s after modification).
=> Extract the common codes to one utils class  & Reduce the content of debug log printing of the InsertRowsPlan

server/src/main/java/org/apache/iotdb/db/engine/merge/task/MergeMultiChunkTask.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBMergeIT.java, server/src/test/resources/logback.xml
if merge path is smaller than mergeChunkSubTaskNum, will use merge path number.
so threads are not wasted.
=> [IOTDB-1174] optimize mergechunks thread number

jdbc/src/main/java/org/apache/iotdb/jdbc/AbstractIoTDBJDBCResultSet.java, jdbc/src/main/java/org/apache/iotdb/jdbc/IoTDBJDBCResultSet.java, jdbc/src/main/java/org/apache/iotdb/jdbc/IoTDBNonAlignJDBCResultSet.java, jdbc/src/test/java/org/apache/iotdb/jdbc/IoTDBJDBCResultSetTest.java
#2741
Currently, the getObject method in JDBC returns a String which does not match the JDBC standard.
In this PR, I re-implement this method by calling `IoTDBRpcDataSet.getObjectByName` and `IoTDBRpcDataSet.getObject` method directly to get the Object result.
=> [ISSUE-2741] getObject method in JDBC should return an Object

server/src/main/java/org/apache/iotdb/db/tools/TsFileSketchTool.java, tsfile/src/main/java/org/apache/iotdb/tsfile/read/reader/LocalTsFileInput.java
The tsfile format has been changed, but the tsfile sketch tool is not updated yet. While using the SketchTool to analyze a new format tsfile will throw Exception like the following:
* The new tsfile format has added a new structure called PlanIndex after each chunk group which is used by distributed iotdb, while scanning the tsfile in tsfile sketch tool, we should skip it.
* While reading data from ByteBuffer, I forgot to flip it.
* skip the PlanIndex after each chunk group which occupys 17 bytes
* flip the ByteBuffer.
=> Fix the sketch tool in new tsfile format

server/src/assembly/resources/conf/iotdb-env.bat, server/src/assembly/resources/conf/iotdb-env.sh
This PR is changing the default Maximum JVM heap size setting from 8GB to 64GB.
=> Change the default max JVM heap size from 8GB to 64GB

pom.xml
current  jetty version is 9.4.24.v20191120,  which have a high loopholes CVE-2020-27216， we can use 9.4.35.v20201120 version
=> [IOTDB-1181] Upgrade jetty jar to fix CVE-2020-27216

cluster/src/main/java/org/apache/iotdb/cluster/ClusterMain.java, cluster/src/main/java/org/apache/iotdb/cluster/query/ClusterDataQueryExecutor.java, cluster/src/main/java/org/apache/iotdb/cluster/query/reader/ClusterReaderFactory.java, cluster/src/main/java/org/apache/iotdb/cluster/query/reader/ClusterTimeGenerator.java
see [1186](https://issues.apache.org/jira/browse/IOTDB-1186).
=> [IOTDB-1186] Remove redundant sync meta leader in query process for cluster module

server/src/main/java/org/apache/iotdb/db/conf/IoTDBConstant.java
Field 'START_TIME' is never used
Update IoTDBConstant.java
=> Optimize Field 'START_TIME' is never used  in  IoTDBConstant.java

server/src/main/java/org/apache/iotdb/db/engine/storagegroup/StorageGroupProcessor.java
When covering a tsfile resource with HistoricalVersion = null, it’ll throw a NPE. 
Solution:
Using getMaxVersion method instead.
<hr>
This PR has:
<hr>
=> [To rel/0.11] avoid Collections.max(empty set) incur null pointer when recovering

cluster/src/main/java/org/apache/iotdb/cluster/client/sync/SyncClientPool.java, cluster/src/main/java/org/apache/iotdb/cluster/client/sync/SyncDataClient.java, cluster/src/main/java/org/apache/iotdb/cluster/client/sync/SyncMetaClient.java, cluster/src/main/java/org/apache/iotdb/cluster/metadata/CMManager.java, cluster/src/main/java/org/apache/iotdb/cluster/metadata/MetaPuller.java, cluster/src/main/java/org/apache/iotdb/cluster/query/ClusterPlanExecutor.java, cluster/src/main/java/org/apache/iotdb/cluster/query/aggregate/ClusterAggregator.java, cluster/src/main/java/org/apache/iotdb/cluster/query/fill/ClusterPreviousFill.java, cluster/src/main/java/org/apache/iotdb/cluster/query/groupby/RemoteGroupByExecutor.java, cluster/src/main/java/org/apache/iotdb/cluster/query/last/ClusterLastQueryExecutor.java, cluster/src/main/java/org/apache/iotdb/cluster/query/reader/ClusterReaderFactory.java, cluster/src/main/java/org/apache/iotdb/cluster/query/reader/DataSourceInfo.java, cluster/src/main/java/org/apache/iotdb/cluster/server/ClientServer.java, cluster/src/main/java/org/apache/iotdb/cluster/server/PullSnapshotHintService.java, cluster/src/main/java/org/apache/iotdb/cluster/server/service/BaseSyncService.java, cluster/src/main/java/org/apache/iotdb/cluster/server/service/DataSyncService.java, cluster/src/main/java/org/apache/iotdb/cluster/server/service/MetaSyncService.java, cluster/src/test/java/org/apache/iotdb/cluster/client/sync/SyncDataClientTest.java, cluster/src/test/java/org/apache/iotdb/cluster/client/sync/SyncMetaClientTest.java
Currently, the thread pool is used to manage inter-cluster communication access. The connection is obtained from the connection pool. After the connection is used, the connection is returned to the connection pool. After the connection is used, the interface must be called to put the connection back to the connection pool. This requires that the connection must be closed in finally.
Therefore, the connection usage is optimized here. Use try() to obtain the closed connection（push to thread pool）.
1. interface Closeable and close method. if call close , will put client to pool.
2. use try() syntax,  will put client to pool.This is the common method of closing connections for thread pools. For example, common-pool.jar.
3. In case the connection is not put back into the connection pool after …
=> [IOTDB-1189] [Distributed]optimize thread pool client close

server/src/assembly/resources/conf/iotdb-env.bat, server/src/assembly/resources/conf/iotdb-env.sh
Currently the non-heap memory is out of our control. We add a java runtime parameter to get some control of it.
Cherry pick from #2756
=> Add max direct memory size parameter to env.sh

server/src/main/java/org/apache/iotdb/db/engine/storagegroup/StorageGroupProcessor.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBDeletionIT.java
Check JIRA issue: https://issues.apache.org/jira/projects/IOTDB/issues/IOTDB-1188?filter=allopenissues
This bug has been fixed in master branch. So only 0.11 release versions have this bug.
The bug occurs when the delete path is not a full timeseries path but a device path.
If any device path contains no data, delete code will falsely return. In this way, the devices that truly contain data will not be deleted.
=> [IOTDB-1188][To rel/0.11]Fix IoTDB 0.11 unable to delete data bug

cluster/src/assembly/resources/conf/iotdb-cluster.properties, cluster/src/main/java/org/apache/iotdb/cluster/client/async/AsyncClientPool.java, cluster/src/main/java/org/apache/iotdb/cluster/client/sync/SyncClientPool.java, cluster/src/main/java/org/apache/iotdb/cluster/config/ClusterConfig.java, cluster/src/main/java/org/apache/iotdb/cluster/config/ClusterDescriptor.java
The WAIT_CLIENT_TIMEOUT_MS and maxConnectionForEachNode
parameter controls the connection generation speed and affects cluster link access. Therefore, it can be configured in the iotdb-cluster file.
=> [IOTDB-1204] set parameter in iotdb-cluster.properties

docs/UserGuide/Operation Manual/Kill Query.md, docs/zh/UserGuide/Operation Manual/Kill Query.md, server/src/assembly/resources/conf/iotdb-engine.properties, server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java, server/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java, server/src/main/java/org/apache/iotdb/db/query/control/QueryTimeManager.java, server/src/main/java/org/apache/iotdb/db/service/TSServiceImpl.java
The parameter of query timeout does not include `timeout` keyword, which is not good for searching.
=> Rename timeout parameter

hive-connector/pom.xml
Pentaho is dependent on calcite-core 1.10 (by hive), but it is always downloaded failed from spring.io repo.
see:
Error: Failed to execute goal org.apache.maven.plugins:maven-remote-resources-plugin:1.7.0:process (process-resource-bundles) on project hive-connector: Execution process-resource-bundles of goal org.apache.maven.plugins:maven-remote-resources-plugin:1.7.0:process failed: Error resolving project artifact: Could not transfer artifact org.pentaho:pentaho-aggdesigner-algorithm:pom:5.1.5-jhyde from/to central (https://repo.maven.apache.org/maven2): Transfer failed for https://repo.maven.apache.org/maven2/org/pentaho/pentaho-aggdesigner-algorithm/5.1.5-jhyde/pentaho-aggdesigner-algorithm-5.1.5-jhyde.pom for project org.pentaho:pentaho-aggdesigner-algorithm:jar:5.1.5-jhyde: …
=> [IOTDB-1226]download calcite-core's dependency penhato from public.nexus.pentaho.org rather than spring.io

cluster/src/test/java/org/apache/iotdb/cluster/client/DataClientProviderTest.java
Set WaitClientTimeoutMS to 10ms,  create client quickly..  The main thread waits until the connection is created.
ERROR:
[INFO] 
[INFO] Results:
[INFO] 
Error:  Failures: 
Error:    DataClientProviderTest.testSyncConcurrency:133 expected:<6> but was:<2>
[INFO] 
Error:  Tests run: 374, Failures: 1, Errors: 0, Skipped: 1
=> fix test executor error

server/src/main/java/org/apache/iotdb/db/qp/strategy/PhysicalGenerator.java
Only use refactoring Shortcut Keys， Extract functions and construct static classes without changing the code logic.
=> Fix refactor query code, reduce complexity

antlr/src/main/antlr4/org/apache/iotdb/db/qp/sql/SqlBase.g4, grafana/pom.xml, jdbc/pom.xml, pom.xml, server/src/main/java/org/apache/iotdb/db/engine/cache/ChunkCache.java, server/src/main/java/org/apache/iotdb/db/engine/cache/ChunkMetadataCache.java, server/src/main/java/org/apache/iotdb/db/engine/cache/TimeSeriesMetadataCache.java, server/src/main/java/org/apache/iotdb/db/engine/modification/Modification.java, server/src/main/java/org/apache/iotdb/db/engine/storagegroup/StorageGroupProcessor.java, server/src/main/java/org/apache/iotdb/db/engine/storagegroup/TsFileProcessor.java, server/src/main/java/org/apache/iotdb/db/metadata/mnode/MeasurementMNode.java, server/src/main/java/org/apache/iotdb/db/qp/Planner.java, server/src/main/java/org/apache/iotdb/db/qp/logical/Operator.java, server/src/main/java/org/apache/iotdb/db/qp/physical/PhysicalPlan.java, server/src/main/java/org/apache/iotdb/db/qp/sql/IoTDBSqlVisitor.java, server/src/main/java/org/apache/iotdb/db/query/context/QueryContext.java, server/src/main/java/org/apache/iotdb/db/query/dataset/groupby/GroupByWithValueFilterDataSet.java, server/src/main/java/org/apache/iotdb/db/query/executor/LastQueryExecutor.java, server/src/main/java/org/apache/iotdb/db/query/reader/chunk/metadata/DiskChunkMetadataLoader.java, server/src/main/java/org/apache/iotdb/db/service/TSServiceImpl.java, server/src/main/java/org/apache/iotdb/db/utils/FileLoaderUtils.java, tsfile/src/main/java/org/apache/iotdb/tsfile/file/metadata/TimeseriesMetadata.java
In this pr, we support explain sql to print the query execute plan in logs. This function can be useful while some bugs happened online and we can collect some information.
explain + the query sql, like the following:
```
explain select s1 from root.sg1.d1
```
=> [To rel/0.11] Add explain sql support

server/src/main/java/org/apache/iotdb/db/metadata/MTree.java, server/src/main/java/org/apache/iotdb/db/qp/executor/PlanExecutor.java, server/src/main/java/org/apache/iotdb/db/qp/physical/sys/CreateMultiTimeSeriesPlan.java, server/src/main/java/org/apache/iotdb/db/service/TSServiceImpl.java, server/src/test/java/org/apache/iotdb/db/qp/physical/PhysicalPlanSerializeTest.java, session/src/main/java/org/apache/iotdb/session/Session.java
For cluster, `createMultiTimeseries` is used for auto create schema.
Here is an example:
```
private static void createMultiTimeseries()
List<String> paths = new ArrayList<>();
paths.add("root.sg1.d1.(s0,s1,s2)");
paths.add("root.sg1.d1.s3");
List<TSDataType> tsDataTypes = new ArrayList<>();
tsDataTypes.add(TSDataType.INT64);
tsDataTypes.add(TSDataType.DOUBLE);
tsDataTypes.add(TSDataType.FLOAT);
tsDataTypes.add(TSDataType.INT64);
List<TSEncoding> tsEncodings = new ArrayList<>();
tsEncodings.add(TSEncoding.RLE);
tsEncodings.add(TSEncoding.RLE);
tsEncodings.add(TSEncoding.RLE);
tsEncodings.add(TSEncoding.RLE);
List<CompressionType> compressionTypes = new ArrayList<>();
compressionTypes.add(CompressionType.SNAPPY); …
```
=> [IOTDB-1235] Refactor createMultiTimeseries

server/src/main/java/org/apache/iotdb/db/conf/IoTDBConstant.java, server/src/main/java/org/apache/iotdb/db/metadata/MManager.java, server/src/main/java/org/apache/iotdb/db/metadata/MTree.java, server/src/main/java/org/apache/iotdb/db/metadata/logfile/MLogWriter.java, server/src/main/java/org/apache/iotdb/db/metadata/mnode/StorageGroupMNode.java, server/src/main/java/org/apache/iotdb/db/qp/physical/sys/StorageGroupMNodePlan.java, server/src/test/java/org/apache/iotdb/db/metadata/MManagerBasicTest.java, tsfile/src/test/java/org/apache/iotdb/tsfile/write/DefaultDeviceTemplateTest.java
`MeasurementMNode` with aligned timeseries should have specific name. For example, starting with `$#$`
=> [IOTDB-1238] Make aligned timeseries MeasurementMNode name start with "$#$"

server/src/main/java/org/apache/iotdb/db/qp/physical/crud/AggregationPlan.java, server/src/main/java/org/apache/iotdb/db/qp/physical/crud/FillQueryPlan.java, server/src/main/java/org/apache/iotdb/db/qp/physical/crud/QueryPlan.java, server/src/main/java/org/apache/iotdb/db/qp/strategy/PhysicalGenerator.java, server/src/main/java/org/apache/iotdb/db/query/control/QueryResourceManager.java, server/src/main/java/org/apache/iotdb/db/service/TSServiceImpl.java
The code structure of deduplicate() and internalExecuteQueryStatement() are so complex, so I optimized part of them.
1. abstract getMemoryParametersFromPhysicalPlan() method
2. delete redundant memory estimation in PhysicalGenerator, move it to TSServiceImpl
3. move judgement that doesn't support nonAlignQuery to QueryPlan()
=> Optimize the code structure of deduplicate() 

server/src/main/java/org/apache/iotdb/db/qp/physical/crud/AggregationPlan.java, server/src/main/java/org/apache/iotdb/db/qp/physical/crud/FillQueryPlan.java, server/src/main/java/org/apache/iotdb/db/qp/physical/crud/QueryPlan.java, server/src/main/java/org/apache/iotdb/db/qp/physical/crud/UDTFPlan.java, server/src/main/java/org/apache/iotdb/db/qp/strategy/PhysicalGenerator.java, server/src/main/java/org/apache/iotdb/db/query/control/QueryResourceManager.java, server/src/main/java/org/apache/iotdb/db/service/TSServiceImpl.java
The code structure of deduplicate() is so complex, so I optimized part of them.
This PR abstracts the method for calculating column names.
=> Optimize the code structure of deduplicate() - PART2

server/src/main/java/org/apache/iotdb/db/query/aggregation/impl/AvgAggrResult.java, server/src/test/java/org/apache/iotdb/db/integration/IOTDBGroupByInnerIntervalIT.java, server/src/test/java/org/apache/iotdb/db/integration/aggregation/IoTDBAggregationIT.java
I did serval improvements of the AVG function:
The formula to calculate AVG function is complex, it can be simplified. I removed reduncdant operations.
When we calculate the AVG, the result value will transfer into Double type. in Java, the calculation of double type will always cause the loss of accuracy. And in our test case, there are lots of values which are loss of accuracy. I try to fix it by using assertEquals(double expected, double actual, double delta)
=> simplify the Avg formula on removing redundant operations

server/src/main/java/org/apache/iotdb/db/rescon/SystemInfo.java
There are two issues.
1. In forceAsyncFlush()  method, FlushManager.getInstance().getNumberOfWorkingTasks() will always be larger than 0.
2. The forceAsyncFlush() method in SystemInfo may cause a dead lock issue. It shouldn't be in the lock of resetStorageGroupStatus.
<hr>
This PR has:
<hr>
=> [IOTDB-1247] fix insert blocked caused the bugs in mem control module

RELEASE_NOTES.md, server/src/main/java/org/apache/iotdb/db/rescon/SystemInfo.java
There are two issues.
1. In forceAsyncFlush() method, FlushManager.getInstance().getNumberOfWorkingTasks() will always be larger than 0.
2. The forceAsyncFlush() method in SystemInfo may cause a dead lock issue. It shouldn't be in the lock of resetStorageGroupStatus.
=> [IOTDB-1247] [To rel/0.11] fix the insert blocked caused the bugs in mem control module

tsfile/src/main/java/org/apache/iotdb/tsfile/file/metadata/enums/CompressionType.java, tsfile/src/main/java/org/apache/iotdb/tsfile/file/metadata/enums/MetadataIndexNodeType.java, tsfile/src/main/java/org/apache/iotdb/tsfile/file/metadata/enums/TSDataType.java, tsfile/src/main/java/org/apache/iotdb/tsfile/file/metadata/enums/TSEncoding.java
Fix bad smell code, it is not necessary to use for loop to find enums type. It can use switch case to reduce complexity from O(n) ->O(1)...
=> Use switch case in enums class 

cluster/src/main/java/org/apache/iotdb/cluster/server/member/MetaGroupMember.java, cluster/src/test/java/org/apache/iotdb/cluster/query/groupby/RemoteGroupByExecutorTest.java, cluster/src/test/java/org/apache/iotdb/cluster/server/member/MetaGroupMemberTest.java, server/src/main/java/org/apache/iotdb/db/engine/StorageEngine.java
When data is not partitioned, all data of a sequence is stored in partition 0. Therefore, during the query, we only need to route to partition 0 regardless of the interval. Therefore, partition calculation is not performed.
This reduces the time spent on partition calculation and routing to other partitions.
Current problems:
1. When
firstLB == Long.MIN_VALUE || lastUB == Long.MAX_VALUE
route all partiongroup.
2. For other time conditions, partition calculation is performed.
=> [IOTDB-1251] optimize route intervals

cluster/pom.xml
We should use statistical naming throughout the project, for jar names, and zip names.
current， cluster package-name is cluster-*.zip, and cluster-*.jar
solution：
=> [IOTDB-1255] refactor cluster package and jar name

cluster/src/test/java/org/apache/iotdb/cluster/common/TestAsyncDataClient.java, cluster/src/test/java/org/apache/iotdb/cluster/query/BaseQueryTest.java, cluster/src/test/java/org/apache/iotdb/cluster/server/member/BaseMember.java, cluster/src/test/java/org/apache/iotdb/cluster/server/member/DataGroupMemberTest.java, cluster/src/test/java/org/apache/iotdb/cluster/server/member/MetaGroupMemberTest.java, cluster/src/test/java/org/apache/iotdb/cluster/server/member/RaftMemberTest.java
Currently, we use MemberTest as the base class and reuse some of its methods. If one test-class extends the MemberTest , the test case of the MemberTest class is executed again when the test case of the subclass is executed. As a result, some tests in the MemberTest class are executed multiple times, increasing the test case execution time
Solution:
1. test case extract in MemberTest.
2. MemberTest rename a basemember class，which can not add new test case.
=> [IOTDB-1252] optimize test mult-times perform

cluster/src/assembly/resources/conf/iotdb-cluster.properties, cluster/src/main/java/org/apache/iotdb/cluster/config/ClusterConfig.java, cluster/src/main/java/org/apache/iotdb/cluster/config/ClusterDescriptor.java, cluster/src/main/java/org/apache/iotdb/cluster/log/Log.java, cluster/src/main/java/org/apache/iotdb/cluster/log/LogDispatcher.java, cluster/src/main/java/org/apache/iotdb/cluster/log/manage/CommittedEntryManager.java, cluster/src/main/java/org/apache/iotdb/cluster/log/manage/RaftLogManager.java, cluster/src/main/java/org/apache/iotdb/cluster/server/member/RaftMember.java, cluster/src/test/java/org/apache/iotdb/cluster/common/TestUtils.java, cluster/src/test/java/org/apache/iotdb/cluster/log/manage/RaftLogManagerTest.java
see https://issues.apache.org/jira/browse/IOTDB-854
limit the total  size of raftlog in memory.
<hr>
This PR has:
<hr>
=> IOTDB-854  Limit the memory foorprint of the committed log cache

site/src/main/.vuepress/config.js
just a typo error, but leads to compiler error in the site module.
=> fix Flink TsFile doc url error caused by PR2813

pom.xml
Jackson 2.10.0  have loopholes CVE-2020-25649， so need upgrate to 2.11.0.
=> [IOTDB-1256] Jackson have loopholes CVE-2020-25649

server/src/main/java/org/apache/iotdb/db/service/TSServiceImpl.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBExecuteBatchIT.java
Jira: 
https://issues.apache.org/jira/browse/IOTDB-1236
Improve jdbc performance for creating timeseries in cluster module
Refer to InsertRowsPlan to judge the type of operation specifically, and execute CreateMultiTimeSeriesPlan without affecting the execution sequence
1. Determine the type of operation
2. Assemble batch objects
3. If it is not INSERT and CREATE_TIMESERIES operations, start to execute the operation queue in order
reference
https://github.com/apache/iotdb/pull/2725
=> [IOTDB-1236] Improve jdbc performance for creating timeseries in cluster module

client-py/pypi/README.md, client-py/src/iotdb/Session.py, client-py/src/iotdb/TestContainer.py
* Add / Fix the insert_str_record method for type inference (sends TSInsertStringRecord)
* Add Support for python testcontainer with a specific IoTDB Container.
* Improved the readme a bit
<hr>
This PR has:
<hr>
python client submodule (client-py).
=> Improve Python Client:

server/src/main/java/org/apache/iotdb/db/engine/storagegroup/TsFileResource.java, tsfile/src/main/java/org/apache/iotdb/tsfile/fileSystem/fsFactory/FSFactory.java, tsfile/src/main/java/org/apache/iotdb/tsfile/fileSystem/fsFactory/HDFSFactory.java, tsfile/src/main/java/org/apache/iotdb/tsfile/fileSystem/fsFactory/LocalFSFactory.java
Cluster module introduce `Files.deleteIfExists(file.toPath())` in tsfile resource, but `toPath()` method returns `java.nio.file.Path` which doesn't work for HDFS file, and result in failure of storing tsfiles in HDFS.
=> [ISSUE-2905] Fix Files.deleteIfExists() doesn't work for HDFS file

pom.xml
jcl-over-slf4j 1.7.25 have a Security Vulnerabilities, which CVSS be greater than 9.8. so need ugrade 1.7.30
=> [IOTDB-1258] jcl-over-slf4j have security vulnerabilities CVE-2018-8088

cluster/src/main/java/org/apache/iotdb/cluster/metadata/CMManager.java
1. The syncMetaLeader  in CMManager.getAllpath accounts for 10 percent of the performance of the query.
2. The syncMetaLeader has been invoked in ClusterPhysicalGenerator.transformToPhysicalPlan.
3. The possibility of metadata change is small and cannot be the bottleneck of query.
Solution:
remove syncMetaLeader  in CMManager.getAllpath. 
test result:
Time_Range AVG before optimization: 139.38
Time_Ranger AVG after optimization: 110.19
=> [IOTDB-1260] optimize time_range query because syncMetaLeader 

cluster/src/main/java/org/apache/iotdb/cluster/coordinator/Coordinator.java, cluster/src/main/java/org/apache/iotdb/cluster/metadata/CMManager.java, example/session/src/main/java/org/apache/iotdb/SessionExample.java
Suppose the cluster has just started without any data, and client perferm a InsertTablets including two Tablets with same deviceId, the cluster will try to auto-create schema for these two tablets in a `for` loop.For the first tablet, cluster will auto-create related timeseries, but for the second tablet, the `unregisteredSeriesList` is empty, and if we don't return true at this time, the cluster will create a emply createMultiTimeseriesPlan to execute, and this will cause a endless loop which finally cause stackoverflow
=> [Distributed] Fix stackoverflow bug caused by InsertMultiTabletPlan or InsertRowsPlan 

cluster/src/main/java/org/apache/iotdb/cluster/query/reader/ClusterReaderFactory.java
optimize time_range query because syncMetaLeader
1.The syncMetaLeader has been invoked in ClusterPhysicalGenerator.transformToPhysicalPlan.
2.The possibility of metadata change is small and cannot be the bottleneck of query.
=> [IOTDB-1260] optimize time_range query because syncMetaLeader

tsfile/src/main/java/org/apache/iotdb/tsfile/read/TsFileSequenceReader.java
=> [To rel/0.11] Throw exeception when device to be queried is not in tsFileMetaData

distribution/pom.xml, distribution/src/assembly/cluster.xml
=============================================================
```
commit 64c11bc259cfc948286b8bf299792380766deb25
Author: wangchao316 <66939405+wangchao316@users.noreply.github.com>
Date: Tue Mar 23 20:54:44 2021 +0800
IOTDB-1255 refactor cluster package and jar name (#2892)
diff --git a/cluster/pom.xml b/cluster/pom.xml
index 1d2969321..9a15a0daa 100644
— a/cluster/pom.xml
+++ b/cluster/pom.xml
@@ -27,7 +27,7 @@
<version>0.12.0-SNAPSHOT</version>
<relativePath>../pom.xml</relativePath>
</parent>
-   <artifactId>cluster</artifactId>
+  <artifactId>iotdb-cluster</artifactId>
<name>cluster</name>
<properties>
<cluster.test.skip>false</cluster.test.skip>
```
============================================================
=============================================================
vi …
=> [IOTDB-1265] fix bug: correct cluster to iotdb-cluster

docs/zh/UserGuide/Appendix/Config Manual.md
按照当前手册和0.12内配置文件对比，添加部分了解的参数。剩余其他参数可能需要规划其他参数类型。所以未敢添加。
当前版本不包含配置参数如下表
####################
####################
enable_metric_service=false
metrics_port=8181
query_cache_size_in_metric=50
####################
####################
concurrent_query_thread=0
chunk_buffer_pool_enable=false
batch_size=100000
enable_mtree_snapshot=false
mtree_snapshot_threshold_time=3600
virtual_storage_group_num = 1
time_index_level=DEVICE_TIME_INDEX
####################
####################
write_read_schema_free_memory_proportion=4:3:1:2
primitive_array_size=128
flush_proportion=0.4
buffered_arrays_memory_proportion=0.6
reject_proportion=0.8
storage_group_report_threshold=16777216
max_deduplicated_path_num=1000
check_period_when_insert_blocked=50
max_waiting_time_when_insert_blocked=10000 …
=> update configuration items

server/src/assembly/resources/conf/logback.xml, server/src/main/java/org/apache/iotdb/db/conf/IoTDBConstant.java, server/src/main/java/org/apache/iotdb/db/engine/compaction/TsFileManagement.java, server/src/main/java/org/apache/iotdb/db/engine/compaction/level/LevelCompactionTsFileManagement.java, server/src/main/java/org/apache/iotdb/db/engine/merge/task/MergeFileTask.java, server/src/main/java/org/apache/iotdb/db/engine/storagegroup/StorageGroupProcessor.java, server/src/main/java/org/apache/iotdb/db/engine/storagegroup/TsFileResource.java, server/src/main/java/org/apache/iotdb/db/utils/FilePathUtils.java, server/src/test/java/org/apache/iotdb/db/engine/compaction/CompactionChunkTest.java, server/src/test/java/org/apache/iotdb/db/engine/compaction/LevelCompactionMoreDataTest.java, server/src/test/java/org/apache/iotdb/db/engine/compaction/LevelCompactionRecoverTest.java, server/src/test/java/org/apache/iotdb/db/engine/compaction/LevelCompactionTest.java, server/src/test/java/org/apache/iotdb/db/engine/compaction/LevelCompactionTsFileManagementTest.java, server/src/test/java/org/apache/iotdb/db/engine/compaction/NoCompactionTsFileManagementTest.java, server/src/test/java/org/apache/iotdb/db/engine/merge/MaxFileMergeFileSelectorTest.java, server/src/test/java/org/apache/iotdb/db/engine/merge/MergeOverLapTest.java, server/src/test/java/org/apache/iotdb/db/engine/merge/MergeTaskTest.java, server/src/test/java/org/apache/iotdb/db/engine/merge/MergeTest.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBRemovePartitionIT.java
Hi all :
I have submitted a pr for [ISSUE-2730](https://github.com/apache/iotdb/issues/2730), please take a look.
This issue about add the number of unseq merge times in TsFile name.
The modules involved are as follows:
   1、server/engine/merge
   2、server/engine/storagegroup
<hr>
This PR has:
<hr>
=> [ISSUE-2730] Add the number of unseq merge times in TsFile name.

server/src/main/java/org/apache/iotdb/db/engine/compaction/TsFileManagement.java, server/src/main/java/org/apache/iotdb/db/engine/compaction/level/LevelCompactionTsFileManagement.java, server/src/main/java/org/apache/iotdb/db/engine/storagegroup/StorageGroupProcessor.java, server/src/test/java/org/apache/iotdb/db/engine/storagegroup/StorageGroupProcessorTest.java
Currently, the cli `merge` can just execute unseq compaction, it is not conveniently for user to execute compaction. So in this PR, I change the `merge` command to execute both level compaction and unseq merge. And also, this PR may fix the 'file not found' ci problem.
There is a windows ci problem now.
Every time this ci problem occurs, there will be a file not found error and it is all windows ci. Although the wrong test was not manually merged, I guessed that it was because the last test reported 'file not found' error affected this test
So I speculate that it is caused by an unseq compaction problem.
This error happens because we submit an unseq compaction task manually when a level compaction is working, the unseq compaction will get the current tsfile list and wait for the level …
=> [To rel/0.11] Add level compaction to merge command

jdbc/src/main/java/org/apache/iotdb/jdbc/Config.java, jdbc/src/main/java/org/apache/iotdb/jdbc/IoTDBConnection.java, jdbc/src/main/java/org/apache/iotdb/jdbc/IoTDBConnectionParams.java, jdbc/src/main/java/org/apache/iotdb/jdbc/Utils.java, server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java, server/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java, server/src/main/java/org/apache/iotdb/db/sync/sender/transfer/SyncClient.java, service-rpc/src/main/java/org/apache/iotdb/rpc/RpcTransportFactory.java, service-rpc/src/main/java/org/apache/iotdb/rpc/RpcUtils.java, service-rpc/src/main/java/org/apache/iotdb/rpc/TCompressedElasticFramedTransport.java, service-rpc/src/main/java/org/apache/iotdb/rpc/TElasticFramedTransport.java, service-rpc/src/main/java/org/apache/iotdb/rpc/TSnappyElasticFramedTransport.java, service-rpc/src/main/java/org/apache/iotdb/rpc/TimeoutChangeableTFastFramedTransport.java, session/src/main/java/org/apache/iotdb/session/Session.java, session/src/main/java/org/apache/iotdb/session/SessionConnection.java
Change logs：
1. Fix the setting bug, e.g.: `RpcTransportFactory.setMaxLength(ioTDBConfig.getThriftMaxFrameSize()); `. i.e.,Don't put `max_frame_ Size` as `softmaxlength`.
2. Merge `initialBufferCapacity` and `maxFrameSize` to `thriftDefaultBufferSize`. and `thriftDefaultBufferSize` configable by user.
3. rename the key from `initial_buffer_capacity` to `thrift_default_buffer_capacity`
4. rename the key from `max_frame_size` to `thrift_max_frame_size`
5. Unified configuration items：
- `RpcUtils.java` in the service-rpc module depends on tsfile & thrift moudles
- `Config.java` in the iotdb-jdbc module depends on service-rpc & others moudles
- `IoTDBConfig.java` in the iotdb-server module depends on service-rpc & iotdb-jdbc moudles
So, such as `initial_buffer_Capacity` and `Max_frame_size` …
=>  [IOTDB-1257] Make a little bit improvement of config and fix some bugs for setting logic

server/src/main/java/org/apache/iotdb/db/engine/compaction/TsFileManagement.java, server/src/main/java/org/apache/iotdb/db/engine/compaction/level/LevelCompactionTsFileManagement.java, server/src/main/java/org/apache/iotdb/db/engine/compaction/no/NoCompactionTsFileManagement.java
A ci bug behave like below:
The problem happens in LevelCompaction. The compaction process get all seq files to merge with unseq files in one time partition t1. And the unseq compaction may select seq files which is not in time partition t1. This operation may destroy the time partition structure.
this is a cherry-pick of PR #2920 
Just submit seq files in time partition t1 for unseq compaction in `LevelCompactionTsFileManagement`.
We changed the management of the `TsFileResourceList` to groups by time partition in `NoCompactionTsFileManagement`.
We deprecated the `getTsFileList()` method.
Make unseq compaction not select seq files exceed end time of each unseq file.
We cannot implement this by adding condition `unseqEndTime >= seqStartTime` in `selectOverlappedFile`. Reason: 
Case there …
=> [To rel/0.11] Fix unseq compaction file selector conflicts with time partition bug

server/src/test/java/org/apache/iotdb/db/integration/IoTDBEngineTimeGeneratorIT.java
The test fails to be executed independently
Reason:
This test uses an empty `queryPlan`. However, `SeriesRawDataBatchReader` may need to use the path from the queryPlan.
```
return new SeriesRawDataBatchReader(
path,
queryPlan.getAllMeasurementsInDevice(path.getDevice()), \\called `allSensors`
dataType,
context,
queryDataSource,
timeFilter,
valueFilter,
null,
queryPlan.isAscending());
```
The current logic is: if we can find the `path` in `TimeSeriesMetadataCache`, then we do not need to use `allSensors`.  If not, we have to check `allSensors`.
When running the whole IT test, `TimeSeriesMetadataCache` is not empty and the `path` exists in it, so even though  `allSensors` is empty, it does not take any side effect. 
But when run the IT independently,  `TimeSeriesMetadataCache` is empty and …
=> [IOTDB-1262] The test fails to be executed independently

cluster/src/main/java/org/apache/iotdb/cluster/query/ClusterDataQueryExecutor.java, cluster/src/main/java/org/apache/iotdb/cluster/query/aggregate/ClusterAggregateExecutor.java, cluster/src/main/java/org/apache/iotdb/cluster/query/groupby/ClusterGroupByVFilterDataSet.java, cluster/src/main/java/org/apache/iotdb/cluster/query/reader/ClusterTimeGenerator.java, cluster/src/test/java/org/apache/iotdb/cluster/query/reader/ClusterTimeGeneratorTest.java, server/src/main/java/org/apache/iotdb/db/query/dataset/groupby/GroupByWithValueFilterDataSet.java, server/src/main/java/org/apache/iotdb/db/query/executor/AggregationExecutor.java, server/src/main/java/org/apache/iotdb/db/query/executor/RawDataQueryExecutor.java, server/src/main/java/org/apache/iotdb/db/query/executor/UDTFQueryExecutor.java, server/src/main/java/org/apache/iotdb/db/query/timegenerator/ServerTimeGenerator.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBEngineTimeGeneratorIT.java
More, in public ServerTimeGenerator(IExpression expression, QueryContext context, RawDataQueryPlan queryPlan) , we should remove IExpression expression, and use queryPlan.getExpression instead.
=> [IOTDB-1267] optimize ServerTimeGenerator IExpression parameter

client-cpp/src/main/Session.cpp, client-cpp/src/main/Session.h, example/client-cpp-example/src/SessionExample.cpp
Github issue:
https://github.com/apache/iotdb/issues/2919
1. Change ```SessionDataSet *executeQueryStatement()``` to ```unique_ptr<SessionDataSet> executeQueryStatement()```, to fix the memory leak bug.
2. Change the type of fields in RowRecord to ```vector<Field>```. The RowRecord structure will get full copies of Fields to avoid potential memory bugs.
3. Format the code in SessionExample.cpp
=> [ISSUE-2919] Fix C++ client memory leak bug

example/tsfile/src/main/java/org/apache/iotdb/tsfile/TsFileSequenceRead.java, tsfile/src/main/java/org/apache/iotdb/tsfile/read/TsFileSequenceReader.java, tsfile/src/main/java/org/apache/iotdb/tsfile/write/writer/TsFileIOWriter.java, tsfile/src/test/java/org/apache/iotdb/tsfile/write/writer/RestorableTsFileIOWriterTest.java
When device to be queried is not in `TsFileMetaData`, we should throw exception instead of returning `null`.
=> Throw exception when device to be queried is not in TsFileMetaData

server/src/main/java/org/apache/iotdb/db/engine/flush/FlushManager.java, server/src/main/java/org/apache/iotdb/db/monitor/StatMonitor.java, server/src/test/java/org/apache/iotdb/db/monitor/IoTDBStatMonitorTest.java
Currently, tsfile processor has storage group name with virtual storage group name. But it will cause path problem in stat monitor module which need logical storage group name. This PR fix this issue.
=> Fix monitor bug caused by virtual storage group name

client-py/src/iotdb/Session.py
IoTDB Java session API supports inferring data type, by using `InsertStringRecord`.
Python API also has a similar API, called `insert_str_record`. 
However, it does not infer the data type. Instead, it considers all values as strings.
Reason: 
the API should call `insertStringRecord`, but it calls `insertRecord` now.
=> [IoTDB-1272][to rel/0.11][Python] the session api does not infer the data as correct type

docs/UserGuide/Ecosystem Integration/Flink IoTDB.md, example/flink/src/main/java/org/apache/iotdb/flink/FlinkIoTDBSink.java, example/flink/src/main/java/org/apache/iotdb/flink/FlinkIoTDBSource.java, flink-iotdb-connector/src/main/java/org/apache/iotdb/flink/IoTDBSink.java, flink-iotdb-connector/src/main/java/org/apache/iotdb/flink/IoTDBSource.java, flink-iotdb-connector/src/main/java/org/apache/iotdb/flink/options/IoTDBOptions.java, flink-iotdb-connector/src/main/java/org/apache/iotdb/flink/options/IoTDBSinkOptions.java, flink-iotdb-connector/src/main/java/org/apache/iotdb/flink/options/IoTDBSourceOptions.java, flink-iotdb-connector/src/test/java/org/apache/iotdb/flink/DefaultIoTSerializationSchemaTest.java, flink-iotdb-connector/src/test/java/org/apache/iotdb/flink/IoTDBSinkBatchInsertTest.java, flink-iotdb-connector/src/test/java/org/apache/iotdb/flink/IoTDBSinkBatchTimerTest.java, flink-iotdb-connector/src/test/java/org/apache/iotdb/flink/IoTDBSinkInsertTest.java
This pull request implements IoTDBSource in flink scenario.
Now there are two types of options, one for IoTDBSink, another for IoTDBSource. I extracted common attributes to a super class, IoTDBOptions, and made the original one to be IoTDBSinkOptions, and created a new IoTDBSourceOptions.
I implemented IoTDBSource, which reads data from IoTDB and organizes results in form of any user-defined data type. For the latter part, an abstract mathod called `convert()` is given so that whoever use it can determine the way they like to organize the results.
=> [IOTDB-1277] Flink IoTDB source 

cluster/src/assembly/resources/conf/iotdb-cluster.properties, cluster/src/main/java/org/apache/iotdb/cluster/config/ClusterConfig.java, cluster/src/main/java/org/apache/iotdb/cluster/config/ClusterDescriptor.java, cluster/src/main/java/org/apache/iotdb/cluster/server/DataClusterServer.java, cluster/src/main/java/org/apache/iotdb/cluster/server/MetaClusterServer.java, cluster/src/main/java/org/apache/iotdb/cluster/server/member/RaftMember.java, cluster/src/main/java/org/apache/iotdb/cluster/server/service/BaseAsyncService.java, cluster/src/main/java/org/apache/iotdb/cluster/server/service/BaseSyncService.java, cluster/src/test/java/org/apache/iotdb/cluster/query/ClusterDataQueryExecutorTest.java, cluster/src/test/java/org/apache/iotdb/cluster/server/member/DataGroupMemberTest.java, cluster/src/test/java/org/apache/iotdb/cluster/server/member/RaftMemberTest.java, thrift-cluster/src/main/thrift/cluster.thrift
In the distributed version, metadata synchronization will be performed when parsing SQL statements, which will lead to parsing time consuming up to 1 second. The main reason is that the heartbeat of the master is not received in time, which leads to the delay of the synchronization time. The root cause is that metadata and data belong to the same raft replication group, which affects the judgment of whether metadata is consistent or not.
The main idea of this pr is to reduce the time of synchronization point by getting the submitted information earlier. With weak consistency, we can get 20~30% query performance improvement.
<hr>
This PR has:
<hr>
=> optimize sync leader for meta

client-cpp/pom.xml, cluster/src/assembly/resources/conf/iotdb-cluster.properties, cluster/src/main/java/org/apache/iotdb/cluster/config/ClusterConfig.java, cluster/src/main/java/org/apache/iotdb/cluster/config/ClusterDescriptor.java, cluster/src/main/java/org/apache/iotdb/cluster/server/DataClusterServer.java, cluster/src/main/java/org/apache/iotdb/cluster/server/MetaClusterServer.java, cluster/src/main/java/org/apache/iotdb/cluster/server/member/RaftMember.java, cluster/src/main/java/org/apache/iotdb/cluster/server/service/BaseAsyncService.java, cluster/src/main/java/org/apache/iotdb/cluster/server/service/BaseSyncService.java, cluster/src/test/java/org/apache/iotdb/cluster/query/ClusterDataQueryExecutorTest.java, cluster/src/test/java/org/apache/iotdb/cluster/server/member/DataGroupMemberTest.java, cluster/src/test/java/org/apache/iotdb/cluster/server/member/RaftMemberTest.java, code-coverage/pom.xml, compile-tools/pom.xml, distribution/pom.xml, example/client-cpp-example/pom.xml, example/udf/pom.xml, grafana/pom.xml, jdbc/pom.xml, pom.xml, thrift-cluster/src/main/thrift/cluster.thrift
=> [To rel/0.12] Optimize sync leader for meta (#2987)

cluster/src/main/java/org/apache/iotdb/cluster/log/catchup/LogCatchUpTask.java, cluster/src/main/java/org/apache/iotdb/cluster/log/manage/CommittedEntryManager.java
There are so many checks apply thread warnings, even though, we have handled the issue, it is better to reduce it.
Reduce the concurrency problem caused by the check apply thread and the compact entries thread.
=> [Distributed] minor improve the concurrency problem caused by the checking apply thread and the compact entries thread

cluster/src/main/java/org/apache/iotdb/cluster/log/manage/serializable/SyncLogDequeSerializer.java
The debug log outputs some useless log when serializing meta, which make it harder to find the usage info when debugging the code, so I think we can lower the debug level to trace.
=> [Distributed]Lowering the logging level from debug to trace when serializing meta 

server/src/main/java/org/apache/iotdb/db/qp/physical/crud/InsertMultiTabletPlan.java, server/src/main/java/org/apache/iotdb/db/qp/physical/crud/InsertRowsOfOneDevicePlan.java, server/src/main/java/org/apache/iotdb/db/qp/physical/crud/InsertRowsPlan.java
**[phenomenon]**
The plan index is always zero when we use insertRecords interface to test the cluster.
**[After resloved]**
After the bug was resolved, we can see that the plan index is not zero.
**[Reason]**
the plan index is not set in the sub plans when we split the InsertRowsPlan, InertMultiTabletPlans and InsertRowsOfOneDevicePlan
=> [Distributed] fix the plan index miss 

server/src/main/java/org/apache/iotdb/db/engine/compaction/TsFileManagement.java, server/src/main/java/org/apache/iotdb/db/engine/compaction/level/LevelCompactionTsFileManagement.java, server/src/main/java/org/apache/iotdb/db/engine/compaction/utils/CompactionUtils.java, server/src/test/java/org/apache/iotdb/db/engine/compaction/CompactionChunkTest.java, server/src/test/java/org/apache/iotdb/db/engine/compaction/LevelCompactionMergeTest.java, server/src/test/java/org/apache/iotdb/db/engine/compaction/LevelCompactionModsTest.java
Delete operation become invalid after compaction.
1. In `append merge`, the mods modify of chunkMetadata will not change the data of the chunk corresponding to it. However, we just merge the chunk data by BufferBytes and then delete the modification record.
2. As we change the structure of mods file in 0.12 (delete `version` and change it to `tsfileOffset` which means that only if the offset of the chunk <= `tsfileOffset`, then the modification record is valid). However, the position of chunk in tsfile may change after compaction.
1. Do not use mods file in `append merge` and keep the modification record.
2. Update the `tsfileOffset` of remain modification record to Long.MAX_VALUE, which means that it will be valid for the whole tsfile.
=> [IOTDB-1294] Compaction mods for new mods structure

server/src/main/java/org/apache/iotdb/db/query/udf/datastructure/row/ElasticSerializableRowRecordList.java
JIRA: https://issues.apache.org/jira/projects/IOTDB/issues/IOTDB-1219
The bug was reported by LGTM.com:
https://lgtm.com/projects/g/apache/iotdb/snapshot/ad13f1d09d54d7f98ab09a6b3572d64e1217644c/files/server/src/main/java/org/apache/iotdb/db/query/udf/datastructure/row/ElasticSerializableRowRecordList.java?sort=name&dir=ASC&mode=heatmap
Dereferencing a variable whose value may be 'null' may cause a 'NullPointerException'.
=> [IOTDB-1219] A potential NPE issue in ElasticSerializableRowRecordList#applyNewMemoryControlParameters

server/src/main/java/org/apache/iotdb/db/query/udf/datastructure/row/ElasticSerializableRowRecordList.java
JIRA: https://issues.apache.org/jira/projects/IOTDB/issues/IOTDB-1219
The bug was reported by LGTM.com:
https://lgtm.com/projects/g/apache/iotdb/snapshot/ad13f1d09d54d7f98ab09a6b3572d64e1217644c/files/server/src/main/java/org/apache/iotdb/db/query/udf/datastructure/row/ElasticSerializableRowRecordList.java?sort=name&dir=ASC&mode=heatmap
Dereferencing a variable whose value may be 'null' may cause a 'NullPointerException'.
=> [To rel/0.12][IOTDB-1219] A potential NPE issue in ElasticSerializableRowRecordList#applyNewMemoryControlParameters

session/src/test/java/org/apache/iotdb/session/IoTDBSessionSimpleIT.java, tsfile/src/main/java/org/apache/iotdb/tsfile/write/record/Tablet.java
The calOccupationOfOneColumn method in Tablet should use column index instead of the measurementSchema index.
<hr>
This PR has:
<hr>
=> [To Vector] Fix get buffer size bug when values contain TEXT data

server/src/main/java/org/apache/iotdb/db/qp/physical/crud/InsertTabletPlan.java, server/src/main/java/org/apache/iotdb/db/service/TSServiceImpl.java, server/src/main/java/org/apache/iotdb/db/utils/QueryDataSetUtils.java, session/src/main/java/org/apache/iotdb/session/SessionUtils.java, tsfile/src/main/java/org/apache/iotdb/tsfile/write/record/Tablet.java
Move BitMaps to the end of the ValueBuffer to keep the compatibility of the other languages clients. 
<hr>
This PR has:
<hr>
=> [To Vector] Move BitMaps to the end of the ValueBuffer

cluster/src/main/java/org/apache/iotdb/cluster/log/catchup/CatchUpTask.java
https://issues.apache.org/jira/browse/IOTDB-1317
When the follower lags behind the leader, it will catch up with the leader through the log. When it can't find the logs to catch up with in the memory of the leader, it will go to the file on the local disk to find the satisfied logs. The logs found are between the old match index and the commit index saved by the leader. However, at this time, the match index of the follower may have been updated and the old match index of the follower may have been deleted (in order to prevent a large number of logs from being kept on disk, there is a log deletion mechanism). So at this time, if you send the above logs to the follower, the follower will fail to find the matching log. At this time, this storage group will appear to write stuck phenomenon. …
=> [IOTDB-1317] Log CatchUp always failed du to not check the follower's match index

cluster/src/main/java/org/apache/iotdb/cluster/log/catchup/CatchUpTask.java
https://issues.apache.org/jira/browse/IOTDB-1317
When the follower lags behind the leader, it will catch up with the leader through the log. When it can't find the logs to catch up with in the memory of the leader, it will go to the file on the local disk to find the satisfied logs. The logs found are between the old match index and the commit index saved by the leader. However, at this time, the match index of the follower may have been updated and the old match index of the follower may have been deleted (in order to prevent a large number of logs from being kept on disk, there is a log deletion mechanism). So at this time, if you send the above logs to the follower, the follower will fail to find the matching log. At this time, this storage group will appear to write stuck phenomenon. …
=> [rel/0.12][IOTDB-1317] Log CatchUp always failed du to not check the follower's match index

pom.xml
Snappy must be compatible with the ARM server. 1.8.0 and later versions are compatible with ARM.
=> [IOTDB-1301] snappy compatible arm64

server/src/main/java/org/apache/iotdb/db/engine/storagegroup/StorageGroupProcessor.java, server/src/main/java/org/apache/iotdb/db/qp/physical/crud/InsertRowPlan.java
The InsertRowPlanTest failed due to the data type mismatching when update the last cache for an aligned timeseries.
Eventually, we don't need to update the last cache for aligned timeseries. Therefore, I add a check to fix it.
<hr>
This PR has:
<hr>
=> Fix CI failed caused by updating unnecessary vector last cache

server/src/main/java/org/apache/iotdb/db/engine/compaction/TsFileManagement.java, server/src/main/java/org/apache/iotdb/db/engine/compaction/level/LevelCompactionTsFileManagement.java, server/src/main/java/org/apache/iotdb/db/engine/compaction/utils/CompactionUtils.java, server/src/test/java/org/apache/iotdb/db/engine/compaction/CompactionChunkTest.java, server/src/test/java/org/apache/iotdb/db/engine/compaction/LevelCompactionMergeTest.java, server/src/test/java/org/apache/iotdb/db/engine/compaction/LevelCompactionModsTest.java
Delete operation become invalid after compaction.
1. In `append merge`, the mods modify of chunkMetadata will not change the data of the chunk corresponding to it. However, we just merge the chunk data by BufferBytes and then delete the modification record.
2. As we change the structure of mods file in 0.12 (delete `version` and change it to `tsfileOffset` which means that only if the offset of the chunk <= `tsfileOffset`, then the modification record is valid). However, the position of chunk in tsfile may change after compaction.
1. Do not use mods file in `append merge` and keep the modification record.
2. Update the `tsfileOffset` of remain modification record to Long.MAX_VALUE, which means that it will be valid for the whole tsfile.
=> [To rel/0.12][IOTDB-1294] Compaction mods for new mods structure

server/src/main/java/org/apache/iotdb/db/engine/memtable/AbstractMemTable.java, server/src/main/java/org/apache/iotdb/db/engine/querycontext/ReadOnlyMemChunk.java, server/src/main/java/org/apache/iotdb/db/query/reader/chunk/MemPageReader.java, tsfile/src/main/java/org/apache/iotdb/tsfile/file/metadata/VectorChunkMetadata.java
Solution:
1. ReadOnlyMemChunk for query one measurement in vector should be vector type.
2. ValueStatistics  updating logic for one column vector should be different to other vector types
<hr>
This PR has:
<hr>
=> Fix query one sensor in a vector from memtable

cluster/src/main/java/org/apache/iotdb/cluster/coordinator/Coordinator.java, server/src/main/java/org/apache/iotdb/db/engine/memtable/AbstractMemTable.java
- stand-alone:
insert some vector data to root.ln
delete from root.*
select * from root.ln
500 NPE occurs
- Reason: The delete logic and vector don't coordinate well
- cluster:
insert some vector data to root.ln
delete from root.*
select * from root.ln
data still exists
- Reason:  Vector does not currently support single column deletion
=> Delete vector data bug

server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfigCheck.java
https://issues.apache.org/jira/browse/IOTDB-1293
We need to tell users the enable_partition cannot be modified after iotdb has been started once. 
<hr>
This PR has:
<hr>
=> [IOTDB-1293] Message of enable_partition cannot be modified after iotdb started should be more clear

server/src/main/java/org/apache/iotdb/db/query/executor/QueryRouter.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBGroupByMonthIT.java, tsfile/src/main/java/org/apache/iotdb/tsfile/read/filter/GroupByMonthFilter.java
Steps:
1.  insert into root.sg.d1(time,s1) values(1522425600000, 1)
2.  select count from root.sg.d1 group by ((2018-01-31, 2018-03-31],1mo)
Reason:
Copy() method of `GroupByMonthFilter` doesn't deep copy enough elements.
=> [IOTDB-1325] StackOverflow Exception in group by natural month query

server/src/main/java/org/apache/iotdb/db/query/executor/QueryRouter.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBGroupByMonthIT.java, tsfile/src/main/java/org/apache/iotdb/tsfile/read/filter/GroupByMonthFilter.java
Steps:
insert into root.sg.d1(time,s1) values(1522425600000, 1)
select count from root.sg.d1 group by ((2018-01-31, 2018-03-31],1mo)
Reason:
Copy() method of GroupByMonthFilter doesn't deep copy enough elements.
=> [To rel/0.12] [IOTDB-1325] StackOverflow Exception in group by natural month query

jdbc/src/main/java/org/apache/iotdb/jdbc/IoTDBStatement.java, server/src/main/java/org/apache/iotdb/db/qp/executor/PlanExecutor.java, server/src/main/java/org/apache/iotdb/db/service/TSServiceImpl.java, server/src/test/java/org/apache/iotdb/db/integration/auth/IoTDBAuthorizationIT.java
1. when user does not have "create timeseries" privilege, JDBC allows user to create timeseries using executeBatch() interface. this adds authority check
2. when multiple errors occur, JDBC only shows user the last error message. this adds all error message with its SQL.
=> JDBC bug - check authority for execute batch

cluster/src/main/java/org/apache/iotdb/cluster/metadata/CMManager.java, server/src/main/java/org/apache/iotdb/db/metadata/MManager.java, server/src/main/java/org/apache/iotdb/db/metadata/mnode/MNode.java, server/src/main/java/org/apache/iotdb/db/utils/SchemaUtils.java
This bug is because we don't set FullPath for MeasurementMnode to distinguish them. 
The logic here is new since the aligned timeseries pr were merged and may require further refactoring later
=> [Cluster] Fix query multiple subSensors for multiple device timeout bug in cluster

service-rpc/src/main/java/org/apache/iotdb/rpc/RpcTransportFactory.java, service-rpc/src/main/java/org/apache/iotdb/rpc/TimeoutChangeableTFastFramedTransport.java, service-rpc/src/main/java/org/apache/iotdb/rpc/TimeoutChangeableTSnappyFramedTransport.java
TimeoutChangeableTSnappyFramedTransport do not use thriftDefaultBufferSize and thriftMaxFrameSize.
=> [IOTDB-1339] optimize TimeoutChangeableTSnappyFramedTransport

server/src/main/java/org/apache/iotdb/db/metadata/MManager.java, server/src/test/java/org/apache/iotdb/db/metadata/MManagerBasicTest.java
https://issues.apache.org/jira/browse/IOTDB-1344
When delete the storage groups, we need to clear the totalSeriesNumber by
```
totalSeriesNumber.addAndGet(-mtree.getAllTimeseriesCount(storageGroup));
```
<hr>
This PR has:
<hr>
=> [IOTDB-1344] Deleting Storage Group does not clear the count of timeseries

server/src/main/java/org/apache/iotdb/db/metadata/MManager.java, server/src/test/java/org/apache/iotdb/db/metadata/MManagerBasicTest.java
https://issues.apache.org/jira/browse/IOTDB-1344
When delete the storage groups, we need to clear the totalSeriesNumber by
```
totalSeriesNumber.addAndGet(-mtree.getAllTimeseriesCount(storageGroup));
```
=> [To rel/0.12][IOTDB-1344] Deleting Storage Group does not clear the count of time series

.github/workflows/client-go.yml, .github/workflows/client.yml, .github/workflows/e2e.yml, .github/workflows/main-unix.yml, .github/workflows/main-win.yml, .github/workflows/sonar-coveralls.yml
This is a cherry-pick to rel/0.12.
see #3121 
original PR #3122
=> [ISSUE-3121] [To rel/0.12] add maven http parameter to avoid maven downloading dependencies timeout

cluster/src/main/java/org/apache/iotdb/cluster/server/member/MetaGroupMember.java
The report log  is frequently printed. As a result, the log is updated quickly. Therefore, the log level is changed to debug.
=> [IOTDB-1349]Fix reduce frequent log printing.

antlr/src/main/antlr4/org/apache/iotdb/db/qp/sql/SqlBase.g4, server/src/test/java/org/apache/iotdb/db/qp/plan/PhysicalPlanTest.java
Example:
```sql
create timeseries root.sg.d[1].s with datatype=BOOLEAN,encoding=PLAIN
```
Related PR: #2503
=> [To rel/0.11] Support brackets with number in timeseries path

server/src/main/java/org/apache/iotdb/db/engine/flush/MemTableFlushTask.java, server/src/main/java/org/apache/iotdb/db/utils/datastructure/TVList.java, server/src/main/java/org/apache/iotdb/db/utils/datastructure/VectorTVList.java, server/src/test/java/org/apache/iotdb/db/integration/IOTDBInsertAlignedValuesIT.java
When insert aligned timeseries liked as below,
```
insert into root.sg.d1(time, (s1, s2, s3)) values (1, (1, 2, 3));
insert into root.sg.d1(time, (s1, s2, s3)) values (2, (1, 2, null));
insert into root.sg.d1(time, (s1, s2, s3)) values (2, (null, 2, 3));
``` 
we got the query result 
```
+-----------------------------+-------------+-------------+-------------+
|                         Time|root.sg.d1.s1|root.sg.d1.s2|root.sg.d1.s3|
+-----------------------------+-------------+-------------+-------------+
|1970-01-01T08:00:00.001+08:00|          1.0|          2.0|          3.0|
|1970-01-01T08:00:00.002+08:00|         null|          2.0|          3.0|
+-----------------------------+-------------+-------------+-------------+
```
The expected  result should be 
``` …
```
=> [IOTDB-1355] Support updating aligned timeseries values when insert partially

compile-tools/pom.xml
=> [To rel/0.11][ISSUE-3132] Replace the dependence repository Bintray with JFrog in compile-tool 

.github/workflows/client.yml, compile-tools/pom.xml
The compile-tool has a dependence `boost`, which needs to be downloaded from Bintray repository.
But since May 1st 2021, Bintray was not available and moved to JFrog. See https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/. 
Therefore, we have to update these URLs to new ones.
=> [ISSUE-3132] Replace the dependence repository Bintray with JFrog in compile-tool

server/src/assembly/resources/conf/logback.xml
Logs are compressed every hour. There are many compressed packages in a day, and the size of each compressed package is small. Therefore, logs are compressed by day and size.
=> [IOTDB-1350]FIx log Compression time

cli/src/main/java/org/apache/iotdb/tool/AbstractCsvTool.java
This is used to fix the problem in issue [IOTDB-1315], together with the time format problem in Windows system.
First, I solved the problem that the time format yyyy-MM-dd'T'HH:mm:ss.SSSZ was not written in AbstractCsvTool.java. The modified file involves AbstractCsvTool.java. I've added this time format to 'SUPPORT_TIME_FORMAT'.
Second, in further debugging, I found that, due to the difference in command line reading between different operating systems of Linux and Windows, not only "-tf yyyy-MM-dd\'T\'HH:mm:ss.SSSZ" will be considered as a format error under Windows, but also other time formats with spaces and ' will have format errors because of the way of adding' \ '.
The method to correct this problem is as follows:
In Windows operating system, the entering of time format string with …
=> [IOTDB-1315] fix for time format error in csv export

cluster/src/main/java/org/apache/iotdb/cluster/metadata/CMManager.java, server/src/main/java/org/apache/iotdb/db/metadata/MManager.java, testcontainer/src/test/java/org/apache/iotdb/db/sql/ClusterIT.java, testcontainer/src/test/java/org/apache/iotdb/db/sql/SingleNodeIT.java
Fix the following bug:
```
IoTDB> select avg(temperature) from root.ln.wf01.wt01;
Msg: 411: Error occurred in query process: Path [root.ln.wf01.wt01.temperature] does not exist
```
In this PR only add overide the method `transformPath` in CMManger.
=> [IoTDB-1331] Add transformPath for CMManger

cluster/src/main/java/org/apache/iotdb/cluster/query/last/ClusterLastQueryExecutor.java, testcontainer/src/test/java/org/apache/iotdb/db/sql/ClusterIT.java, testcontainer/src/test/java/org/apache/iotdb/db/sql/SingleNodeIT.java
Last plan not work in cluster mode, and I think `timeValuePairs.get(i).right` also should be judged as not null.
[jira link](https://issues.apache.org/jira/browse/IOTDB-1348)
=> [IOTDB-1348] Last plan not work in cluster mode

cli/src/main/java/org/apache/iotdb/tool/AbstractCsvTool.java, cli/src/main/java/org/apache/iotdb/tool/ExportCsv.java, cli/src/main/java/org/apache/iotdb/tool/ImportCsv.java
https://issues.apache.org/jira/browse/IOTDB-1313
This bug is about when import CSV with timestamp format `yyyy-MM-dd'T'HH:mm:ss.SSS`, the importCsv tool will treat it as `yyyy-MM-dd'T'HH:mm:ss`. It will cause the time precision lost. 
This PR is adding all formats supported in exportCsv tool.
This PR also solved https://issues.apache.org/jira/browse/IOTDB-1232。
=> [IOTDB-1232][IOTDB-1313] Fix lossing time precision when import csv with unsupported timestamp format

server/src/main/java/org/apache/iotdb/db/engine/storagegroup/StorageGroupProcessor.java
1. Set IoTDB params like below:
```java
enableMemControl: false
memtableSizeThreshold: 1*1024*1024L
```
2. Use SessionExample to write data util there are too much TsFile that cannot be compacted immediately like figure-1.
3. open cli and use `merge` command to execute compaction task.
Problem: Nothing happens after `merge` command.
The member variable timePartitionIdVersionControllerMap will be empty if there are no Memtables in memory. So the `merge` command cannot find timePartitionId to execute compaction bug.
1. use `partitionLatestFlushedTimeForEachDevice` instead.
=> [IOTDB-1369] Fix `merge` command cannot execute compaction task bug

server/src/main/java/org/apache/iotdb/db/engine/storagegroup/StorageGroupProcessor.java
1. Set IoTDB params like below:
```java
enableMemControl: false
memtableSizeThreshold: 1*1024*1024L
```
2. Use SessionExample to write data util there are too much TsFile that cannot be compacted immediately like figure-1.
3. open cli and use `merge` command to execute compaction task.
Problem: Nothing happens after `merge` command.
The member variable timePartitionIdVersionControllerMap will be empty if there are no Memtables in memory. So the `merge` command cannot find timePartitionId to execute compaction bug.
1. use `partitionLatestFlushedTimeForEachDevice` instead.
=> [To rel/0.12] Fix `merge` command cannot execute compaction task bug

cluster/src/main/java/org/apache/iotdb/cluster/metadata/CMManager.java, server/src/main/java/org/apache/iotdb/db/qp/physical/sys/ShowPlan.java, server/src/main/java/org/apache/iotdb/db/query/dataset/ShowDataSet.java, testcontainer/src/test/java/org/apache/iotdb/db/sql/Cases.java
In current cluster version, if we have more than 2,000 timeseries, when we commend SHOW TIMESERIES, it will only display 2,000 timeseries, the same as the SHOW DEVICES...
In the default settings, if we do not set any limit, the default plan.limit will be 1000(set as the fetchsize). This is weird, because if we do not set the limit, it means that I want to fetch all the data instead of fetchsize. So I remove it.
In my opinion, hasNextWithoutConstraint() method is not correct: after I have already fetched all the timeseries, it is not necessary to do fetch again... 
For example, 
if we have 10,000 timeseries, so the result.size() should be 10,000. 
After the first display(fetch size==1000), it will only display the first 1000 timeseries, 
now the index is 1000, so it is still index < …
=> [IOTDB-1266]SHOW TIMESERIES will only display 2000 timeseries

server/src/main/java/org/apache/iotdb/db/engine/compaction/utils/CompactionUtils.java, server/src/test/java/org/apache/iotdb/db/engine/compaction/CompactionChunkTest.java, server/src/test/java/org/apache/iotdb/db/engine/compaction/LevelCompactionMergeTest.java
For level compaction (take the level compaction in sequential space as an example), the size of the merged chunk is controlled by the two parameters: seq_level_num and seq_file_num_in_each_level, that is, the original chunk is expanded by seq_file_num_in_each_level^(seq_level_num-1) times. This configuration scheme has three problems as follows:
1. When configuring, you need to know the size of a chunk originally written by the user, and configure it based on experience. This configuration method is difficult for users to configure by themselves. For each user, we also need to observe files and assist in configuration, which is very inconvenient.
2. Once the user uses the default parameters without modification or configuration errors, and the user's own scene does not need to compact too …
=> [IOTDB-1357] Compaction use append chunk merge strategy when chunk is already large

server/src/assembly/resources/conf/iotdb-engine.properties, server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java, server/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java, server/src/main/java/org/apache/iotdb/db/engine/compaction/TsFileManagement.java
Currently, unseq_file_num_in_each_level will impact the max selected file num in unseq compaction. This is not intuition.
Need to optimize the compaction candidate selecting process, according to the merge_memory_budget, max_selecting_merge_file_num, max open file num in system.
=> [IOTDB-1356] Separate unseq_file_num_in_each_level from selecting candidate file in unseq compaction

server/src/main/java/org/apache/iotdb/db/metadata/MManager.java, server/src/test/java/org/apache/iotdb/db/metadata/MManagerBasicTest.java, server/src/test/java/org/apache/iotdb/db/sink/LocalIoTDBSinkTest.java
When creating aligned timeseries and inserting with mismatched data type, the MNode will be null and a NullPointerException would be thrown.
=> [IOTDB-1371] Fix NPE when creating aligned timeseries and inserting with mismatched data type

README.md, README_ZH.md, client-py/README.md
Since we no longer use travis to run CI, we need to replace the travis build status badge with github actions workflows badges.
=> Update some badges in README

example/tsfile/src/main/java/org/apache/iotdb/tsfile/TsFileSequenceRead.java, tsfile/src/main/java/org/apache/iotdb/tsfile/write/writer/TsFileIOWriter.java
MetadataIndexTree constructs error when existing more than one chunks in vector.
Here is an example.
Change config ` avg_series_point_number_threshold` to `1`.
Then, insert with aligned timeseries:
```
private static void insertTabletWithAlignedTimeseries()
// The schema of measurements of one device
// only measurementId and data type in MeasurementSchema take effects in Tablet
List<IMeasurementSchema> schemaList = new ArrayList<>();
schemaList.add(
new VectorMeasurementSchema(
new String[] {"s1", "s2"}, new TSDataType[] {TSDataType.INT64, TSDataType.INT32}));
Tablet tablet = new Tablet(ROOT_SG1_D1, schemaList, 1);
long timestamp = System.currentTimeMillis();
for (long row = 0; row < 5; row++) {
int rowIndex = …
```
=> [IOTDB-1378] Fix MetadataIndexTree constructs error when existing more than one chunks in vector

tsfile/src/main/java/org/apache/iotdb/tsfile/v2/file/metadata/TsFileMetadataV2.java, tsfile/src/main/java/org/apache/iotdb/tsfile/v2/read/TsFileSequenceReaderForV2.java
The reason is the versionInfo may be not thread safe. Two threads can deserialize it concurrently.
=> [To rel/0.12] fix versionInfo NPE when query upgrading 0.11 tsfile

server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfigCheck.java
1. change the configs in 0.11
```
enable_partition=true
partition_interval=1
```
2. start 0.11 iotdb, execute these statements.
```
IoTDB> insert into root.sg.d1(time,s1,s2) values(1001,1,2)
IoTDB> insert into root.sg.d1(time,s1,s2) values(2001,1,2)
IoTDB> flush
```
The tsfile file paths looks like
```
$ tree data
data
├── sequence
│   └── root.sg
│       ├── 1
│       │   ├── 1620653607439-1-0.tsfile
│       │   └── 1620653607439-1-0.tsfile.resource
│       └── 2
│           ├── 1620653626029-1-0.tsfile
│           └── 1620653626029-1-0.tsfile.resource
└── unsequence
```
3. Move the data files 0.12 and start server with same partition configs.
4. Execute `Select * from root` and get empty result …
=> [To rel/0.12] Fix upgrade tool cannot load old tsfile if time partition enabled in 0.11

server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfigCheck.java, tsfile/src/main/java/org/apache/iotdb/tsfile/v2/file/metadata/TsFileMetadataV2.java, tsfile/src/main/java/org/apache/iotdb/tsfile/v2/read/TsFileSequenceReaderForV2.java
Cherry pick upgrade bugs fixes PR #3178 #3154 to master
=> Cherry pick upgrade bugs fixes PR #3178 #3154 to master

server/src/main/java/org/apache/iotdb/db/qp/sql/IoTDBSqlVisitor.java, server/src/main/java/org/apache/iotdb/db/qp/utils/DatetimeUtils.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBGroupByMonthIT.java, server/src/test/java/org/apache/iotdb/db/qp/utils/DatetimeQueryDataSetUtilsTest.java
#3116 
Bug is caused by, when natural month unit is used in time interval in group by query, the flag `isIntervalByMonth` and `isSlidingStepByMonth` will be changed incorrectly.
=> [ISSUE-3116] Bug when using natural month unit in time interval in group by query

server/src/main/java/org/apache/iotdb/db/qp/sql/IoTDBSqlVisitor.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBGroupByMonthIT.java
#3116
Bug is caused by, when natural month unit is used in time interval in group by query, the flag isIntervalByMonth and isSlidingStepByMonth will be changed incorrectly.
=> [To rel/0.12] [ISSUE-3116] Bug when using natural month unit in time interval in group by query

jdbc/src/main/java/org/apache/iotdb/jdbc/IoTDBStatement.java
The `getMaxRow` and `getMoreResults` methods are used to connect IoTDB using `DataGrip`.
`IoTDB-JDBC` is not currently supported. 
I implemented two methods in which `getMoreResults` are always returning false instead of throwing an exception.
It looks OK in my local tests so far.
=> Implement some JDBC methods to support DataGrip

cli/src/main/java/org/apache/iotdb/tool/ImportCsv.java
will throw ArrayOutOfIndexError when a value is null 
ie.
time,root.fit.d4.s1,root.fit.d4.s2,root.fit.d4.s3,root.fit.d4.s4,root.fit.d4.s5
2,-2147054108,-9221527177961516032,3.40034e+34,1.7978729221545312e+304,
3,-2147054108,-9221527177961516032,3.40034e+34,1.7978729221545312e+304,1
=> split csv bug when has null value

server/src/assembly/resources/conf/iotdb-engine.properties, server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
Currently, we use inplace merge to speed up unseq compaction. However, there are some case that too much unseq data appended to one seq file which may make some seq file too large. So we change the default merge strategy to full merge instead.
=> Update force full merge config

jdbc/src/main/java/org/apache/iotdb/jdbc/IoTDBNonAlignJDBCResultSet.java, service-rpc/src/main/java/org/apache/iotdb/rpc/IoTDBRpcDataSet.java
Some users may forget to close the dataset manually after iterating the dataset which will cause resource leaky. We can automatically close it for users while there is no more data.
=> [IOTDB-1380] Automatically close the dataset while there is no more data

server/src/main/java/org/apache/iotdb/db/engine/compaction/TsFileManagement.java, server/src/main/java/org/apache/iotdb/db/engine/compaction/level/LevelCompactionTsFileManagement.java
Currently, if the unseq compaction cannot select candidates for merge, it will always run again in the same unseq file list in the continuous compaction process. So we have to avoid continuous compaction if the unseq file cannot be selected to be merged.
=> [To rel/0.12] Fix continuous compaction run into dead loop when unseq compaction cannot select candidates

server/src/main/java/org/apache/iotdb/db/engine/compaction/TsFileManagement.java, server/src/main/java/org/apache/iotdb/db/engine/compaction/level/LevelCompactionTsFileManagement.java
Currently, if the unseq compaction cannot select candidates for merge, it will always run again in the same unseq file list in the continuous compaction process. So we have to avoid continuous compaction if the unseq file cannot be selected to be merged.
=> [To rel/0.11] Fix continuous compaction run into dead loop when unseq compaction cannot select candidates

server/src/main/java/org/apache/iotdb/db/utils/FileLoaderUtils.java
1. start  the `master` branch IoTDBServer
2. use `VectorSessionExample` to insert data:
```
createTemplate();
insertTabletWithAlignedTimeseriesMethod1();
insertTabletWithAlignedTimeseriesMethod2();
```
3. use cli to select .
```
select * from root.*;
```
4.the error result like this:
```
[[INTERNAL_SERVER_ERROR] Exception occurred while executing executeQueryStatement. Index: 0][500] 500: [INTERNAL_SERVER_ERROR] Exception occurred while executing executeQueryStatement. Index: 0
```
=> fix index out of bound when VectorTimeSeriesMetadata is not find in memory

antlr/src/main/antlr4/org/apache/iotdb/db/qp/sql/SqlBase.g4, docs/UserGuide/IoTDB-SQL-Language/DML-Data-Manipulation-Language.md, docs/zh/UserGuide/IoTDB-SQL-Language/DML-Data-Manipulation-Language.md, server/src/main/java/org/apache/iotdb/db/qp/executor/PlanExecutor.java, server/src/main/java/org/apache/iotdb/db/qp/logical/crud/QueryOperator.java, server/src/main/java/org/apache/iotdb/db/qp/physical/crud/QueryPlan.java, server/src/main/java/org/apache/iotdb/db/qp/sql/IoTDBSqlVisitor.java, server/src/main/java/org/apache/iotdb/db/qp/strategy/PhysicalGenerator.java, server/src/main/java/org/apache/iotdb/db/query/dataset/RawQueryDataSetWithoutValueFilter.java, server/src/main/java/org/apache/iotdb/db/utils/QueryDataSetUtils.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBWithoutAllNullIT.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBWithoutAnyNullIT.java, tsfile/src/main/java/org/apache/iotdb/tsfile/read/common/RowRecord.java, tsfile/src/main/java/org/apache/iotdb/tsfile/read/query/dataset/QueryDataSet.java
Currently
1. IoTDB will join all the sensor value by its time, and if some sensors don't have values in that timestamp, we will fill it with null. In some analysis scenarios, we only need the row if all the columns of it have value.
2. in group by query, we will fill null for any group by interval if the columns don't have values in that group by interval. However, if all columns in that group by interval are null, maybe users don't need that RowRecord, so we want IoTDB to support this feature.
`select * from root.sg1.d1 WITHOUT NULL ANY` will fix scenario 1 and filter the rows if any column of which is null.
`select last_value(*) from root.testWithoutAllNull.d1 GROUP BY([1, 21), 5ms) WITHOUT NULL ALL` will fix scenario 2 and filter the rows if all columns of which are null.
=> [To rel/0.12] Filter RowRecord automatically if any column in it is null or all columns are null

jdbc/src/main/java/org/apache/iotdb/jdbc/IoTDBNonAlignJDBCResultSet.java, service-rpc/src/main/java/org/apache/iotdb/rpc/IoTDBRpcDataSet.java
Some users may forget to close the dataset manually after iterating the dataset which will cause resource leaky. We can automatically close it for users while there is no more data.
=> [To rel/0.11] Automatically close the dataset while there is no more data

server/src/assembly/resources/conf/iotdb-engine.properties, server/src/main/java/org/apache/iotdb/db/auth/AuthorityChecker.java, server/src/main/java/org/apache/iotdb/db/auth/authorizer/LocalFileAuthorizer.java, server/src/main/java/org/apache/iotdb/db/auth/user/BasicUserManager.java, server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java, server/src/main/java/org/apache/iotdb/db/conf/IoTDBConstant.java, server/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java, server/src/test/java/org/apache/iotdb/db/auth/authorizer/LocalFileAuthorizerTest.java, server/src/test/java/org/apache/iotdb/db/auth/user/LocalFileUserManagerTest.java
In some scenarios, the super user needs to be specified based on the environment.  Extract the super user and password to the config
=> [IOTDB-1385] Extract the super user and password to the config

server/src/main/java/org/apache/iotdb/db/query/dataset/AlignByDeviceDataSet.java, server/src/main/java/org/apache/iotdb/db/utils/QueryDataSetUtils.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBWithoutAllNullIT.java, tsfile/src/main/java/org/apache/iotdb/tsfile/read/common/RowRecord.java, tsfile/src/main/java/org/apache/iotdb/tsfile/read/query/dataset/QueryDataSet.java
The details can be seen in JIRA.
Align by device always have one device column which will never be null. While using WITHOUT NULL clause, we shouldn't take device column into consideration.
Reset the null state in RowRecord after add the device column. Also decrease the alreadyReturnedRowNum field in QueryDataset while the current RowRecord doesn't satisify the without null constraint.
=> [IOTDB-1387]  Fix Without Null ALL doesn't take effect in align by device clause

server/src/main/java/org/apache/iotdb/db/query/dataset/AlignByDeviceDataSet.java, server/src/main/java/org/apache/iotdb/db/utils/QueryDataSetUtils.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBWithoutAllNullIT.java, tsfile/src/main/java/org/apache/iotdb/tsfile/read/common/RowRecord.java, tsfile/src/main/java/org/apache/iotdb/tsfile/read/query/dataset/QueryDataSet.java
The details can be seen in JIRA.
Align by device always have one device column which will never be null. While using WITHOUT NULL clause, we shouldn't take device column into consideration.
Reset the null state in RowRecord after add the device column. Also decrease the alreadyReturnedRowNum field in QueryDataset while the current RowRecord doesn't satisify the without null constraint.
=> [IOTDB-1387] [To rel/0.12] Fix Without Null ALL doesn't take effect in align by device clause

server/src/main/java/org/apache/iotdb/db/query/dataset/groupby/LocalGroupByExecutor.java, server/src/test/java/org/apache/iotdb/db/integration/IOTDBGroupByIT.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBGroupByUnseqIT.java
we can see in the jira.
Forgot to reset the `lastReadCurArrayIndex` and `lastReadCurListIndex` while generating new BatchData which cause the new BatchData will be read from the previous `lastReadCurArrayIndex` and `lastReadCurListIndex`.
reset the `lastReadCurArrayIndex` and `lastReadCurListIndex` while generating new BatchData.
=> [IOTDB-1384] [To rel/0.11] Fix group by bug

server/src/main/java/org/apache/iotdb/db/query/dataset/groupby/LocalGroupByExecutor.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBGroupByUnseqIT.java
we can see in the jira.
Forgot to reset the `lastReadCurArrayIndex` and `lastReadCurListIndex` while generating new BatchData which cause the new BatchData will be read from the previous `lastReadCurArrayIndex` and `lastReadCurListIndex`.
reset the `lastReadCurArrayIndex` and `lastReadCurListIndex` while generating new BatchData.
=> [IOTDB-1384] [To rel/0.12] Fix group by bug

server/src/main/java/org/apache/iotdb/db/query/dataset/groupby/LocalGroupByExecutor.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBGroupByUnseqIT.java
we can see in the jira.
Forgot to reset the `lastReadCurArrayIndex` and `lastReadCurListIndex` while generating new BatchData which cause the new BatchData will be read from the previous `lastReadCurArrayIndex` and `lastReadCurListIndex`.
reset the `lastReadCurArrayIndex` and `lastReadCurListIndex` while generating new BatchData.
=> [IOTDB-1384] Fix group by bug

server/src/main/java/org/apache/iotdb/db/engine/merge/task/MergeMultiChunkTask.java, server/src/test/java/org/apache/iotdb/db/engine/merge/MergeTaskTest.java
set compaction_strategy = LEVEL_COMPACTION
use the `data` to recover the IoTDB. After Recovery, it will merge the unseq data automatically. After unseq compaction, the data of some sensor in seq file loss.
use the following SQL to check data status before and after unseq compaction.
select Channel96 from root.*.J053102.T034.V1 where time >= 2021-05-18 22:32:27 and time <= 2021-05-18 22:32:37;
Unseq compaction filter sensor by lexicographic order. However, the input sensor list may be not in lexicographic order.
Ignore the condition of lexicographic order and use traditional filter means.
=> [IOTDB-1390][To rel/0.11] Fix unseq compaction loss data bug

server/src/main/java/org/apache/iotdb/db/engine/merge/task/MergeMultiChunkTask.java, server/src/test/java/org/apache/iotdb/db/engine/merge/MergeTaskTest.java
set compaction_strategy = LEVEL_COMPACTION
use the `data` to recover the IoTDB. After Recovery, it will merge the unseq data automatically. After unseq compaction, the data of some sensor in seq file loss.
use the following SQL to check data status before and after unseq compaction.
select Channel96 from root.*.J053102.T034.V1 where time >= 2021-05-18 22:32:27 and time <= 2021-05-18 22:32:37;
Unseq compaction filter sensor by lexicographic order. However, the input sensor list may be not in lexicographic order.
Ignore the condition of lexicographic order and use traditional filter means.
=> [IOTDB-1390] Fix unseq compaction loss data bug

server/src/main/java/org/apache/iotdb/db/engine/merge/task/MergeMultiChunkTask.java, server/src/test/java/org/apache/iotdb/db/engine/merge/MergeTaskTest.java
set compaction_strategy = LEVEL_COMPACTION
use the `data` to recover the IoTDB. After Recovery, it will merge the unseq data automatically. After unseq compaction, the data of some sensor in seq file loss.
use the following SQL to check data status before and after unseq compaction.
select Channel96 from root.*.J053102.T034.V1 where time >= 2021-05-18 22:32:27 and time <= 2021-05-18 22:32:37;
Unseq compaction filter sensor by lexicographic order. However, the input sensor list may be not in lexicographic order.
Ignore the condition of lexicographic order and use traditional filter means.
=> [IOTDB-1390][To rel/0.12] Fix unseq compaction loss data bug

.github/workflows/sonar-coveralls.yml
Enable sonar-coveralls check for pr from fork repos according to [this article](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request_target).
I'm going to merge this pr directly, and test by a pr from my fork repos to see if this change is effective. 
If not, I'll revert this.
=> Enable sonar-coveralls for pr from fork repos

server/src/main/java/org/apache/iotdb/db/metadata/MManager.java, server/src/test/java/org/apache/iotdb/db/metadata/MManagerBasicTest.java
=> [ISSUE-3277][To rel/0.11] Fix TotalSeriesNumber in MManager counted twice when recovering 

server/src/assembly/resources/conf/iotdb-engine.properties, server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java, server/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java, server/src/main/java/org/apache/iotdb/db/engine/compaction/TsFileManagement.java
Currently, unseq_file_num_in_each_level will impact the max selected file num in unseq compaction. This is not intuition.
Need to optimize the compaction candidate selecting process, according to the merge_memory_budget, max_selecting_merge_file_num, max open file num in system.
=> [To rel/0.11][IOTDB-1356] Separate unseq_file_num_in_each_level from selecting candidate file in unseq compaction

cli/src/main/java/org/apache/iotdb/tool/ImportCsv.java, cli/src/test/java/org/apache/iotdb/tool/CsvLineSplitTest.java
previously when ImportCSV tool read csv files, single or double quotes are not allowed inside a string (ie ad"bcd). 
This pr changes the csv splitting method. now it allows quotes or commas inside a string value. 
csv file as following:
time,root.fit.d6.s5,root.fit.d6.s6
1,True,
4,True,aapovpba=","akava'',vava=z//z'nnn
6,True,aapovpba=','akavavava=z//z'nnn
7,True,"aapovpba=,,,akavavava=z//z'nnn"
after import csv, query result:
=> fix import csv split by comma bug

.github/workflows/main-unix.yml, .github/workflows/sonar-coveralls.yml
The CI runs very slow right now. Especially the sonar tests takes over one hour.
Since we have the e2e workflow runs the testContainer tests, it's not necessary to run these test in unix and sonar CI again.
=> Skip testContainer in unix and sonar workflow to accelerate CI

server/src/main/java/org/apache/iotdb/db/qp/executor/PlanExecutor.java
When the system executes an empty InsertTabletPlan, the system will throw the following error which is unclear:
Empty insertTabletPlan / insertRowsOfOneDevicePlan are now handled properly in PlanExecutor.
=> [IOTDB-1412] Unclear exception message thrown when executing empty InsertTabletPlan

server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
thriftMaxFrameSize and thriftDefaultBufferSize does not  in effect
=> [IOTDB-1411] thriftMaxFrameSize and thriftDefaultBufferSize does not  in effect

server/src/main/java/org/apache/iotdb/db/query/reader/series/SeriesReader.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBOverlappedPageIT.java
When judging whether a page is overlapped with merge reader, '>=' should be used rather than '>'.
=> Bug Fix: Overlapped data should be consumed first

server/src/main/java/org/apache/iotdb/db/query/aggregation/impl/CountAggrResult.java, server/src/main/java/org/apache/iotdb/db/query/reader/series/SeriesReader.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBGroupByUnseqIT.java
The bug is caused by: when overlapped chunks are unpacked, firstChunk should be updated. #3316
=> [ISSUE-3316] Query result with the same time range is inconsistent in group by query 

server/src/main/java/org/apache/iotdb/db/tools/TsFileRewriteTool.java, server/src/main/java/org/apache/iotdb/db/tools/upgrade/TsFileOnlineUpgradeTool.java
When we upgrade the 0.11 TsFiles to 0.12, the speed of upgrading become low with time.
The log of `lsof` command shows there are many upgraded and deleted old files not closed.
```
java    18179 root *595r   REG               8,33       3507  15460871 /data3/backup_iotdb/apache-iotdb-0.11.3/data/data/sequence/root.ko.trans.26/0/upgrade/1616135911533-6009-0.tsfile (deleted)
java    18179 root *596r   REG               8,33      13885  15446568 /data3/backup_iotdb/apache-iotdb-0.11.3/data/data/sequence/root.ko.trans.26/0/upgrade/1616135908452-5988-0.tsfile (deleted)
java    18179 root *597r   REG               8,33      19028  15446569 /data3/backup_iotdb/apache-iotdb-0.11.3/data/data/sequence/root.ko.trans.26/0/upgrade/1616135909755-6003-0.tsfile (deleted)
java    18179 root *598r   REG …
```
=> [To rel/0.12] Fix upgrade tool cannot close file reader

.github/workflows/sonar-coveralls.yml
I find out the sonar cannot load any information after I use `pull_request_target` instead of `pull_request`, but the coverall works well.
Therefore I'm going to revert the sonar check logic and keep the coverall one.
=> Disable pull_request_target for sonar check since it cannot load any PR revision information

server/src/main/java/org/apache/iotdb/db/engine/StorageEngine.java, server/src/main/java/org/apache/iotdb/db/engine/compaction/CompactionMergeTaskPoolManager.java, server/src/main/java/org/apache/iotdb/db/engine/compaction/StorageGroupCompactionTask.java, server/src/main/java/org/apache/iotdb/db/engine/compaction/TsFileManagement.java, server/src/main/java/org/apache/iotdb/db/engine/storagegroup/StorageGroupProcessor.java, server/src/test/java/org/apache/iotdb/db/engine/compaction/LevelCompactionCacheTest.java, server/src/test/java/org/apache/iotdb/db/engine/storagegroup/StorageGroupProcessorTest.java
Jira: https://issues.apache.org/jira/browse/IOTDB-1419
For each storage group, we only submit one compaction thread, this thread will compact all partitions one by one.
=> [IOTDB-1419][To rel/0.11] fix continuous compaction doesn't take effect when enablePartition

.github/workflows/client.yml
The client library CI was enabled only when some folders have some changes:
- client-*
- thrift-*
- service-rpc
However, it is not enough because even though the client library does not change, the server's change may occur some errors.
So, in this PR, I remove the trigger constraint.
=> enable the client library test for all changes

server/src/assembly/resources/conf/iotdb-engine.properties, server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
cherry pick #3194
Currently, we use inplace merge to speed up unseq compaction. However, there are some case that too much unseq data appended to one seq file which may make some seq file too large. So we change the default merge strategy to full merge instead.
=> [To rel/0.12] Update force full merge config

server/src/test/java/org/apache/iotdb/db/integration/IoTDBDisableAlignIT.java
the column type list now has the timestamp column if needed, so no need to recalculate index
=> fix column type bug

server/src/main/java/org/apache/iotdb/db/engine/compaction/TsFileManagement.java, server/src/main/java/org/apache/iotdb/db/engine/compaction/level/LevelCompactionTsFileManagement.java, server/src/main/java/org/apache/iotdb/db/engine/storagegroup/StorageGroupProcessor.java, server/src/test/java/org/apache/iotdb/db/engine/compaction/LevelCompactionCacheTest.java, server/src/test/java/org/apache/iotdb/db/engine/compaction/LevelCompactionLogTest.java, server/src/test/java/org/apache/iotdb/db/engine/compaction/LevelCompactionMergeTest.java, server/src/test/java/org/apache/iotdb/db/engine/compaction/LevelCompactionMoreDataTest.java, server/src/test/java/org/apache/iotdb/db/engine/compaction/NoCompactionTsFileManagementTest.java
The CompactionMergeTask does not need to clear merge status.
=> [IOTDB-1419][To rel/0.11] remove redundant clearCompactionStatus

server/src/main/java/org/apache/iotdb/db/engine/upgrade/UpgradeTask.java, server/src/main/java/org/apache/iotdb/db/service/UpgradeSevice.java, tsfile/src/main/java/org/apache/iotdb/tsfile/write/chunk/ChunkWriterImpl.java
```
"UpgradeThread-64" #364 prio=5 os_prio=0 tid=0x00007f06c478b800 nid=0x5eff waiting on condition [0x00007efa873f2000]
java.lang.Thread.State: WAITING (parking)
at sun.misc.Unsafe.park(Native Method)
- parking to wait for  <0x00007efcd37218c8> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
at …
```
=> [To rel/0.12] Fix upgrade NPE and DeadLock

cluster/src/test/java/org/apache/iotdb/cluster/common/TestUtils.java, server/src/main/java/org/apache/iotdb/db/engine/storagegroup/TsFileResource.java
in TestUtil, the file name is :
```
String fileName =
"target"
+ File.separator
+ "data"
+ File.separator
+ String.format(
TestUtils.getTestSg(sgNum)
+ File.separator
+ 0
+ File.separator
+ 0
+ File.separator
+ "0-%d-0"
+ TsFileConstant.TSFILE_SUFFIX,
i);
```
However, IoTD's TsFile name has 4 parts.
=> Fix bug caused by incorrect file name

cluster/src/test/java/org/apache/iotdb/cluster/common/TestUtils.java, cluster/src/test/java/org/apache/iotdb/cluster/server/member/DataGroupMemberTest.java, server/src/main/java/org/apache/iotdb/db/engine/compaction/TsFileManagement.java, server/src/main/java/org/apache/iotdb/db/engine/compaction/level/LevelCompactionTsFileManagement.java, server/src/main/java/org/apache/iotdb/db/engine/storagegroup/StorageGroupProcessor.java, server/src/main/java/org/apache/iotdb/db/engine/storagegroup/TsFileResource.java, server/src/test/java/org/apache/iotdb/db/engine/compaction/LevelCompactionLogTest.java, server/src/test/java/org/apache/iotdb/db/engine/compaction/LevelCompactionSelectorTest.java, server/src/test/java/org/apache/iotdb/db/engine/compaction/LevelCompactionTsFileManagementTest.java
in TestUtil, the file name is :
``` java
String fileName =
"target"
+ File.separator
+ "data"
+ File.separator
+ String.format(
TestUtils.getTestSg(sgNum)
+ File.separator
+ 0
+ File.separator
+ 0
+ File.separator
+ "0-%d-0"
+ TsFileConstant.TSFILE_SUFFIX,
i);
```
However, IoTD's TsFile name has 4 parts.
Meanwhile, the PR also update a log in compaction part from debug level to info level, which is useful for later troubleshooting.
=> [To rel/0.12] fix bug caused by incorrect file name

LICENSE-binary, server/src/test/java/org/apache/iotdb/db/integration/IoTDBClearCacheIT.java
The Caffeine cache's `invalidateAll()` + `cleanUp()` methods may not clear the cache immediately, so the `lruCache.estimatedSize() == 0` may return false after we clear the cache.
Wait 1 minutes for the clear cache processing.
=> [rel/0.12] wait for clear cache

.github/workflows/sonar-coveralls.yml
Currently coveralls doesn't check the commit pushed into master branch.
This PR is for fixing it.
=> Enable coveralls check for commit pushed into master branch

cluster/src/main/java/org/apache/iotdb/cluster/coordinator/Coordinator.java, cluster/src/main/java/org/apache/iotdb/cluster/metadata/CMManager.java, cluster/src/main/java/org/apache/iotdb/cluster/query/ClusterPlanRouter.java, cluster/src/main/java/org/apache/iotdb/cluster/server/member/DataGroupMember.java, example/session/src/main/java/org/apache/iotdb/AlignedTimeseriesSessionExample.java, server/src/main/java/org/apache/iotdb/db/engine/cache/TimeSeriesMetadataCache.java, server/src/main/java/org/apache/iotdb/db/engine/memtable/AbstractMemTable.java, server/src/main/java/org/apache/iotdb/db/engine/storagegroup/StorageGroupProcessor.java, server/src/main/java/org/apache/iotdb/db/metadata/MManager.java, server/src/main/java/org/apache/iotdb/db/metadata/template/Template.java, server/src/main/java/org/apache/iotdb/db/monitor/StatMonitor.java, server/src/main/java/org/apache/iotdb/db/qp/executor/PlanExecutor.java, server/src/main/java/org/apache/iotdb/db/qp/physical/crud/InsertPlan.java, server/src/main/java/org/apache/iotdb/db/qp/physical/crud/InsertRowPlan.java, server/src/main/java/org/apache/iotdb/db/qp/physical/crud/InsertTabletPlan.java, server/src/main/java/org/apache/iotdb/db/qp/physical/crud/RawDataQueryPlan.java, server/src/main/java/org/apache/iotdb/db/query/dataset/AlignByDeviceDataSet.java, server/src/main/java/org/apache/iotdb/db/query/executor/LastQueryExecutor.java, server/src/main/java/org/apache/iotdb/db/query/executor/fill/LastPointReader.java, server/src/test/java/org/apache/iotdb/db/metadata/MManagerBasicTest.java, session/src/main/java/org/apache/iotdb/session/Session.java, testcontainer/src/test/java/org/apache/iotdb/db/sql/Cases.java, testcontainer/src/test/java/org/apache/iotdb/db/sql/ClusterIT.java, tsfile/src/main/java/org/apache/iotdb/tsfile/write/TsFileWriter.java, tsfile/src/main/java/org/apache/iotdb/tsfile/write/record/Tablet.java
- Resolve some bugs in PR #3300
- Support partial insert for new vector interfaces
test codes:
1. **create timeseries:**
```
private static void createAlignedTimeseries()
throws StatementExecutionException, IoTDBConnectionException {
List<String> measurements = new ArrayList<>();
for (int i = 1; i <= 2; i++) {
measurements.add("s" + i);
}
List<TSDataType> dataTypes = new ArrayList<>();
dataTypes.add(TSDataType.INT64);
dataTypes.add(TSDataType.INT32);
List<TSEncoding> encodings = new ArrayList<>();
for (int i = 1; i <= 2; i++) {
encodings.add(TSEncoding.RLE);
}
session.createAlignedTimeseries(
ROOT_SG1_D1_VECTOR1, measurements, dataTypes, encodings, CompressionType.SNAPPY, null);
}
```
2. **insert records:**
```
private static void insertAlignedRecord()
throws IoTDBConnectionException, …
```
=> [IOTDB-1422] Support partial insert for new vector interfaces

server/src/main/java/org/apache/iotdb/db/engine/compaction/TsFileManagement.java, server/src/main/java/org/apache/iotdb/db/engine/storagegroup/StorageGroupProcessor.java
When Level compaction is ending(delete file in resource list and delete file in disk). The query may get a tsfile resource from resource list. However, it may be deleted by the compaction ending process later, then the query process cannot read data from the deleted resource. Whichmay cause a ci problem like below.
Get the tsfileResource list's read lock in TsFileManagament before trying to lock each tsfile and after locking all the tsfiles, we then unlock the tsfileResource list's read lock in TsFileManagament.
=> Fix compaction lock with query

server/src/main/java/org/apache/iotdb/db/engine/compaction/TsFileManagement.java, server/src/main/java/org/apache/iotdb/db/engine/storagegroup/StorageGroupProcessor.java
When Level compaction is ending(delete file in resource list and delete file in disk). The query may get a tsfile resource from resource list. However, it may be deleted by the compaction ending process later, then the query process cannot read data from the deleted resource. Whichmay cause a ci problem like below.
Get the tsfileResource list's read lock in TsFileManagament before trying to lock each tsfile and after locking all the tsfiles, we then unlock the tsfileResource list's read lock in TsFileManagament.
=> [To rel/0.12] Fix compaction lock with query

service-rpc/src/main/java/org/apache/iotdb/rpc/RpcUtils.java, session/src/main/java/org/apache/iotdb/session/Session.java, session/src/main/java/org/apache/iotdb/session/SessionConnection.java, session/src/test/java/org/apache/iotdb/session/SessionCacheLeaderUT.java
1. remove the broken session when enable cache leader
2. optimize the `insertRecords` method in session, which we can insert all the devices of data in one session connection, in the previous degien, if some of the devices belong to one session connection, we send to the server per device per connection.
=> Remove the broken cached leader connection & optimize the insertRecords method in session

server/src/main/java/org/apache/iotdb/db/engine/cache/TimeSeriesMetadataCache.java, tsfile/src/main/java/org/apache/iotdb/tsfile/file/metadata/MetadataIndexConstructor.java
Ensure there is only one vector in one MetadataIndexTree.
For example, the query process cannot determine which "s1" is queried ("vector1.s1"? "vector2.s1"?).
Unless vector1 and vector2 are in different leaf nodes in MetadataIndexTree.
=> [IOTDB-1430] Ensure only one vector in one MetadataIndexTree

server/src/main/java/org/apache/iotdb/db/engine/storagegroup/StorageGroupProcessor.java, server/src/main/java/org/apache/iotdb/db/engine/upgrade/UpgradeTask.java, server/src/main/java/org/apache/iotdb/db/tools/TsFileRewriteTool.java, tsfile/src/main/java/org/apache/iotdb/tsfile/write/chunk/ChunkWriterImpl.java
The current 0.12.1 may occur a NPE, when upgrading is finished and the UpgradeThread is clearing the upgrade folder.
The TsFile v3 has a dynamic strategy of statistics in PageHeader. If there is only one Page in a Chunk, the page header should not contains the statistics. The current UpgradeTool doesn't consider it.
<hr>
This PR has:
<hr>
=> [To rel/0.12][ISSUE-3378] Fix NPE when clear upgrade folder; Fix some upgraded pageHeader missing statistics

server/src/main/java/org/apache/iotdb/db/engine/compaction/CompactionMergeTaskPoolManager.java, server/src/main/java/org/apache/iotdb/db/engine/compaction/TsFileManagement.java, server/src/main/java/org/apache/iotdb/db/engine/compaction/level/LevelCompactionTsFileManagement.java, server/src/main/java/org/apache/iotdb/db/engine/compaction/utils/CompactionUtils.java, server/src/main/java/org/apache/iotdb/db/engine/storagegroup/StorageGroupProcessor.java, server/src/main/java/org/apache/iotdb/db/writelog/recover/TsFileRecoverPerformer.java
Currently, recover process cannot execute the continuous compaction every time, as the clearCompactionStatus may set compaction working status to false even the recover of compaction is the finished.
So we remove redundant clearCompactionStatus and synchronous to trigger the later continuous compaction.
Moreover, the PR also expands the Exception to be catched to log more error.
=> [IOTDB-1419][To rel/0.12] remove redundant clearCompactionStatus

server/src/assembly/resources/conf/iotdb-env.bat
iotdb-env.bat doesn't work as expected on Windows systems due to local variable settings. This bug cause all environment variables cannot be assessed in start-server.bat, such as heap memory settings and JMX options. Besides, it's not able to calculate memory size correctly as iotdb-env.sh does due to syntax errors in lines 70, 71, 73, and 82.
Delete SETLOCAL clause to make sure all variables are passing to start-server.bat. Also, system information(number of cores and physical memory size) is acquired in another way because of this modification.
Modify variable citations in GTR clauses to arithmetic operations instead of string comparisons.
=> fix iotdb-env.bat not working

server/src/main/java/org/apache/iotdb/db/engine/compaction/level/LevelCompactionTsFileManagement.java, server/src/main/java/org/apache/iotdb/db/engine/compaction/utils/CompactionUtils.java
1. If the merge selects the file to be compacted, the isMerging field in TsFileResource should be set to true, so that the tsfile will not be deleted by ttl.
2. A large try-finally should be added outside the CompactionUtils.merge function, if a file is opened in the middle Exception, the file that has been successfully opened before should be closed in the finally block
=> [IOTDB-1420] Fix compaction ttl bug

tsfile/src/main/java/org/apache/iotdb/tsfile/read/TsFileSequenceReader.java, tsfile/src/test/java/org/apache/iotdb/tsfile/read/MeasurementChunkMetadataListMapIteratorTest.java
=> [IOTDB-1433] [To rel/0.12] Fix bug in getMetadataAndEndOffset when querying non-exist device

tsfile/src/main/java/org/apache/iotdb/tsfile/read/TsFileSequenceReader.java, tsfile/src/test/java/org/apache/iotdb/tsfile/read/MeasurementChunkMetadataListMapIteratorTest.java
=> [IOTDB-1433] [To rel/0.11] Fix bug in getMetadataAndEndOffset when querying non-exist device

tsfile/src/main/java/org/apache/iotdb/tsfile/read/TsFileSequenceReader.java, tsfile/src/test/java/org/apache/iotdb/tsfile/read/MeasurementChunkMetadataListMapIteratorTest.java
When querying non-exist device, getMetadataAndEndOffset() may give a wrong result.
For example, this method may present results.
```
Iterator<Map<String, List<ChunkMetadata>>> iterator =
fileReader.getMeasurementChunkMetadataListMapIterator("dd");
Assert.assertFalse(iterator.hasNext());
```
=> [IOTDB-1433] Fix bug in getMetadataAndEndOffset when querying non-exist device

server/src/assembly/resources/conf/iotdb-engine.properties, server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
=> Change the default primitive array size to 32

server/src/main/java/org/apache/iotdb/db/tools/TsFileSketchTool.java, server/src/test/java/org/apache/iotdb/db/tools/TsFileSketchToolTest.java, site/src/main/.vuepress/theme/global-components/Contributor.vue
https://issues.apache.org/jira/browse/IOTDB-1437
**Reason**
When parsing, `PlanIndex` is parsed after each chunk group.
**Solution** 
Not all ChunkGroups are followed by a `PlanIndex` , which should be judged according to the marker.
=> [IOTDB-1437]Fix the tsfile sketch tool NPE

cluster/src/main/java/org/apache/iotdb/cluster/query/LocalQueryExecutor.java, cluster/src/main/java/org/apache/iotdb/cluster/query/reader/ClusterReaderFactory.java, cluster/src/main/java/org/apache/iotdb/cluster/query/reader/ClusterTimeGenerator.java, cluster/src/test/java/org/apache/iotdb/cluster/query/BaseQueryTest.java, cluster/src/test/java/org/apache/iotdb/cluster/query/ClusterDataQueryExecutorTest.java, cluster/src/test/java/org/apache/iotdb/cluster/query/reader/ClusterReaderFactoryTest.java, cluster/src/test/java/org/apache/iotdb/cluster/query/reader/ClusterTimeGeneratorTest.java, cluster/src/test/java/org/apache/iotdb/cluster/server/member/BaseMember.java, server/src/main/java/org/apache/iotdb/db/query/reader/series/SeriesRawDataBatchReader.java, server/src/main/java/org/apache/iotdb/db/query/reader/series/SeriesReader.java, server/src/main/java/org/apache/iotdb/db/query/reader/universal/PriorityMergeReader.java, server/src/main/java/org/apache/iotdb/db/query/timegenerator/ServerTimeGenerator.java
https://issues.apache.org/jira/browse/IOTDB-1442
=> [IOTDB-1442] Time filter & TTL is not used during the construction of ClusterTimeGenerator

LICENSE-binary, grafana/pom.xml, jdbc/pom.xml, pom.xml
The versions of logback-classic and logback-core on rel/0.12 and master branches are the newest stable version (1.2.3).
=> [To rel/0.11] Bump logback-classic and logback-core from 1.1.11 to 1.2.3

server/src/main/java/org/apache/iotdb/db/utils/QueryUtils.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBDeleteTimeseriesIT.java
When delete timeseries with multiple time interval, only the first delete interval is checked, which causes chunks that have been deleted are read.
#3436 
You can see the IT to reappear this bug.
=> Fix Bug: delete timeseries with multiple time interval

server/src/main/java/org/apache/iotdb/db/query/reader/series/SeriesReader.java
After PR #3317，the logic I modified seems still be something wrong. After updating firstChunkMetaData, we need to unpack overlappedTimeSeriesMetaData using it again.
=> [ISSUE-3316] Fix constructing firstChunkMetaDatahasNextChunk logic in hasNextChunk()

cluster/src/main/java/org/apache/iotdb/cluster/coordinator/Coordinator.java, cluster/src/main/java/org/apache/iotdb/cluster/metadata/CMManager.java, cluster/src/test/java/org/apache/iotdb/cluster/integration/SingleNodeTest.java, server/src/main/java/org/apache/iotdb/db/qp/physical/BatchPlan.java, server/src/main/java/org/apache/iotdb/db/qp/physical/crud/InsertRowsOfOneDevicePlan.java
This PR fixed the following 2 bugs:
1. For user who does not have CREATE_TIMESERIES privilege, JDBC executeBatch() interface shows execution success, though the unauthorized timeseries are not created.
2. if enabled auto-create schema, CMManager creates SGs for all paths ignoring privilege check. 
Now fixed as:
```
Exception in thread "main" java.sql.BatchUpdateException: 
No permissions for this operation CREATE_TIMESERIES for SQL: "CREATE TIMESERIES root.sg4.d1.s1 WITH DATATYPE=INT64"
No permissions for this operation CREATE_TIMESERIES for SQL: "CREATE TIMESERIES root.sg7.d1.s1 WITH DATATYPE=INT64"
No permissions for this operation CREATE_TIMESERIES for SQL: "CREATE TIMESERIES root.sg8.d1.s1 WITH DATATYPE=INT64"
at org.apache.iotdb.jdbc.IoTDBStatement.executeBatchSQL(IoTDBStatement.java: …
```
=> cluster bug - fix privilege check

example/session/src/main/java/org/apache/iotdb/DataMigrationExample.java
cherry pick https://github.com/apache/iotdb/pull/3461
=> [To rel/0.11] Fix DataMigrationExample OOM if migrate too many timeseries

server/src/assembly/resources/conf/iotdb-env.bat
When users use the JDK11 on Windows, the start-up script will show an error message like this.
=> Fix Windows shell error on JDK11

server/src/main/java/org/apache/iotdb/db/cost/statistic/Measurement.java, server/src/main/java/org/apache/iotdb/db/monitor/StatMonitor.java
There are two problems;
The number of successful requests is counted when the request fails
Start statistics of performance monitoring does not take effect
=> fix monitor bug

server/src/main/java/org/apache/iotdb/db/engine/storagegroup/StorageGroupProcessor.java
Currently, when we recover cross space compaction, We pass ${logicalStorageName}-${virtualStorageGroupId} to find its timeseries in MManager which must be empty.
Only pass storageGroupName to MManager.
=> [IOTDB-1462][To rel/0.12] Fix cross space compaction recover bug

server/src/main/java/org/apache/iotdb/db/engine/storagegroup/StorageGroupProcessor.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBGroupByMonthIT.java
Currently, when we recover cross space compaction, We pass ${logicalStorageName}-${virtualStorageGroupId} to find its timeseries in MManager which must be empty.
Only pass storageGroupName to MManager.
=> [IOTDB-1462] fix cross space compaction recover use wrong storage group name bug

cluster/src/main/java/org/apache/iotdb/cluster/utils/PlanSerializer.java
The BlockingDeque has some buffered ByteArrayOutputStream to reuse.
However, if the buffered ByteArrayOutputStreams are all in use, the poll() method will return a null object without waiting. which causes a null pointer.
So, we need to use the take() method to take a ByteArrayOutputStream until we could take one.
=> [To rel/0.12] [IOTDB-1464] fix take byte array null pointer

cluster/src/main/java/org/apache/iotdb/cluster/utils/PlanSerializer.java
The BlockingDeque has some buffered ByteArrayOutputStream to reuse.
However, if the buffered ByteArrayOutputStreams are all in use, the poll() method will return a null object without waiting. which causes a null pointer.
So, we need to use the take() method to take a ByteArrayOutputStream until we could take one.
=> [IOTDB-1464] fix take byte array null pointer

server/src/main/java/org/apache/iotdb/db/qp/sql/IoTDBSqlVisitor.java
For example: time interval is [now() - 1d, now())
The first now() and second now() are parsed seperately, which is wrong.
=> Bug fix: time interval is parsed incorrectly

docs/UserGuide/IoTDB-SQL-Language/DML-Data-Manipulation-Language.md, docs/zh/UserGuide/IoTDB-SQL-Language/DML-Data-Manipulation-Language.md
JR:https://issues.apache.org/jira/browse/IOTDB-1243
In Mysql: delete from table where id = 999;   if id not exist，It will not report an error, but it will display the execution result or influence result as 0
So,I think IOTDB code is true, we need update doc and  like mysql result in the future
=> [IOTDB-1243]update DML delete grammar doc

server/src/main/java/org/apache/iotdb/db/engine/compaction/level/LevelCompactionTsFileManagement.java, server/src/main/java/org/apache/iotdb/db/engine/storagegroup/StorageGroupProcessor.java
This problem occurs because when compaction processes, it will set TsFile's status to isMerging, which prevents TTL process from delete it.
However, when the Tsfile be deleted during compaction. The compaction will failed and it cannot set the isMerging status to false. So the TTL process cannot delete it.
1. When the compaction failed, set the isMerging status to false.
2. Do not check isMerging status when checking TTL.
=> [IOTDB-1461][To rel/0.12] Fix compaction conflicts with ttl 

server/src/main/java/org/apache/iotdb/db/engine/compaction/level/LevelCompactionTsFileManagement.java, server/src/main/java/org/apache/iotdb/db/engine/storagegroup/StorageGroupProcessor.java
This problem occurs because when compaction processes, it will set TsFile's status to isMerging, which prevents TTL process from delete it.
However, when the Tsfile be deleted during compaction. The compaction will failed and it cannot set the isMerging status to false. So the TTL process cannot delete it.
1. When the compaction failed, set the isMerging status to false.
2. Do not check isMerging status when checking TTL.
=> [IOTDB-1461][To rel/0.11] Fix compaction conflicts with ttl

docs/UserGuide/API/Programming-Java-Native-API.md, docs/zh/UserGuide/API/Programming-Java-Native-API.md, example/session/src/main/java/org/apache/iotdb/SessionExample.java, example/session/src/main/java/org/apache/iotdb/SessionPoolExample.java, session/src/main/java/org/apache/iotdb/session/Config.java, session/src/main/java/org/apache/iotdb/session/Session.java, session/src/main/java/org/apache/iotdb/session/pool/SessionPool.java, session/src/test/java/org/apache/iotdb/session/SessionTest.java, session/src/test/java/org/apache/iotdb/session/SessionUT.java, session/src/test/java/org/apache/iotdb/session/pool/SessionPoolTest.java
Providing a more fluent way to construct Session and SessionPool
=> [IOTDB-1463] Implement builder pattern for Session and SessionPool

server/src/main/java/org/apache/iotdb/db/metadata/MManager.java, server/src/main/java/org/apache/iotdb/db/rescon/PrimitiveArrayManager.java
Cast long to double may cause accuracy loss.
=> [To rel/0.12] PrimitiveArrayManager: improve accuracy when updating limits

example/session/src/main/java/org/apache/iotdb/SessionExample.java, session/src/main/java/org/apache/iotdb/session/Session.java, session/src/main/java/org/apache/iotdb/session/SessionConnection.java, session/src/main/java/org/apache/iotdb/session/SessionUtils.java, session/src/test/java/org/apache/iotdb/session/IoTDBSessionComplexIT.java, testcontainer/src/test/java/org/apache/iotdb/db/sql/ClusterSessionSimpleIT.java
While the cluster is running, the coordinator node may go down, which may cause the session to be unable to read or write properly.i add a session interface to connect multiple nodes.Users can now define a list that contains multiple servers that can be connected. When one of the servers goes down, try again. If it fails, connect to the next one. If all the nodes in the list fail, an exception will be thrown.
=> [IOTDB-1399]Add a session interface to connect multiple nodes

server/src/main/java/org/apache/iotdb/db/engine/merge/task/MergeMultiChunkTask.java, server/src/test/java/org/apache/iotdb/db/engine/merge/MergeTaskTest.java
Some data lost after cross space compaction.
Before compaction:
After compaction:
Use the data below and execute cross space compaction can reproduce this problem.
https://cloud.tsinghua.edu.cn/f/4c320559a2574ca9b0d5/?dl=1
In cross compaction, there is a logic: If none of the seq files has a timeseries, then data of this timeseries will be compacted into the last seq file. However, if the seq file miss the device of the timeseries, all these logic will be passed.
e.g.
compact 3 seqFile and 1 unseqFile
seqFile1: d1.s1:0-100 d1.s2:0-100
seqFile2: d1.s1:100-200
seqFile3: d2.s1:0-100
unseqFile1: d1.s3:0-100
the d1.s3 in unseqFile1 will loss.
1. Even the seq file miss the device of the timeseries, do not return.
2. Solve a bug of filterNoDataPaths.
=> [IOTDB-1469][To rel/0.12]fix cross space compaction loss data bug

server/src/main/java/org/apache/iotdb/db/metadata/MManager.java, server/src/main/java/org/apache/iotdb/db/rescon/PrimitiveArrayManager.java, server/src/main/java/org/apache/iotdb/db/utils/datastructure/TVList.java
* [To rel/0.12] Primitive Array Manager v3 #3508
=> Primitive Array Manager v3

example/session/src/main/java/org/apache/iotdb/SessionExample.java, session/src/main/java/org/apache/iotdb/session/Session.java, session/src/main/java/org/apache/iotdb/session/SessionConnection.java, session/src/main/java/org/apache/iotdb/session/SessionUtils.java, session/src/test/java/org/apache/iotdb/session/IoTDBSessionComplexIT.java
=> [To rel/0.12][IOTDB-1399]Add a session interface to connect multiple nodes

server/src/main/java/org/apache/iotdb/db/engine/StorageEngine.java, server/src/main/java/org/apache/iotdb/db/engine/storagegroup/virtualSg/VirtualStorageGroupManager.java
The path in the logger is not right.
device path -> storage group path
=> [IOTDB-1471] Fix path not right in "sg may not ready" log 

tsfile/src/main/java/org/apache/iotdb/tsfile/read/filter/GroupByMonthFilter.java, tsfile/src/test/java/org/apache/iotdb/tsfile/read/filter/GroupByMonthFilterTest.java
=> [To rel/0.12] Improve group by month performance

tsfile/src/main/java/org/apache/iotdb/tsfile/read/filter/GroupByMonthFilter.java, tsfile/src/test/java/org/apache/iotdb/tsfile/read/filter/GroupByMonthFilterTest.java
Currently, when judging whether a page/chunk/point statisfies group by month filter, we get the interval that need to juege directly instead of one by one.
=> Improve group by month performance

cluster/src/main/java/org/apache/iotdb/cluster/coordinator/Coordinator.java, cluster/src/main/java/org/apache/iotdb/cluster/metadata/CMManager.java, cluster/src/main/java/org/apache/iotdb/cluster/partition/slot/SlotPartitionTable.java, cluster/src/main/java/org/apache/iotdb/cluster/server/MetaClusterServer.java, server/src/main/java/org/apache/iotdb/db/metadata/MManager.java, server/src/main/java/org/apache/iotdb/db/service/IoTDB.java, session/src/main/java/org/apache/iotdb/session/Session.java
This PR fix these issues:
- Fix cluster auto create schema bug when retry locally
- Remove a useless auto create schema error log in `CMManager`
- Downgrade a info log when performing `executeStatementMayRedirect` in `Session`
- Add a flag in `ioTDB` to make server module  fell cluster module
=> Fix cluster auto create schema bug when retry locally 

example/session/src/main/java/org/apache/iotdb/SessionExample.java
The rel/0.12 branch supports creating timeseries by template now. We need to add a session example to tell users how to use it.
To use it, users can alter the main method as below.
```java
public static void main(String[] args)
session = new Session(LOCAL_HOST, 6667, "root", "root");
session.open(false);
// set session fetchSize
session.setFetchSize(10000);
try {
session.setStorageGroup("root.sg1");
} catch (StatementExecutionException e) {
if (e.getStatusCode() != TSStatusCode.PATH_ALREADY_EXIST_ERROR.getStatusCode()) {
throw e;
}
}
createTemplate();
insertRecord();
session.close();
}
```
<hr>
This PR has:
<hr>
=> [To rel/0.12][IOTDB-1486] Add the createTemplate Session example in 0.12

server/src/main/java/org/apache/iotdb/db/metadata/MManager.java, server/src/test/java/org/apache/iotdb/db/metadata/MManagerBasicTest.java
In the current implementation, the template-based time series is restored by calling the getMNodes function after a restart. However, the getMNodes function currently does not support template lookup and this needs to be fixed.
=> Fix template restart bug

docs/SystemDesign/TsFile/Format.md, docs/zh/SystemDesign/TsFile/Format.md
Fix wrong figure for index tree: the root node for the first and second examples should be LEAF_ENTITY type instead of INTERNAL_MEASUREMENT type.
=> [IOTDB-1454] Fix wrong figure for index tree

server/src/main/java/org/apache/iotdb/db/engine/merge/task/MergeMultiChunkTask.java, server/src/test/java/org/apache/iotdb/db/engine/merge/MergeTaskTest.java
Some data lost after cross space compaction.
Before compaction:
After compaction:
Use the data below and execute cross space compaction can reproduce this problem.
https://cloud.tsinghua.edu.cn/f/4c320559a2574ca9b0d5/?dl=1
In cross compaction, there is a logic: If none of the seq files has a timeseries, then data of this timeseries will be compacted into the last seq file. However, if the seq file miss the device of the timeseries, all these logic will be passed.
e.g.
compact 3 seqFile and 1 unseqFile
seqFile1: d1.s1:0-100 d1.s2:0-100
seqFile2: d1.s1:100-200
seqFile3: d2.s1:0-100
unseqFile1: d1.s3:0-100
the d1.s3 in unseqFile1 will loss.
1. Even the seq file miss the device of the timeseries, do not return.
2. Solve a bug of filterNoDataPaths.
=> [IOTDB-1469][To rel/0.11] fix cross space compaction loss data bug

server/src/main/java/org/apache/iotdb/db/metadata/MTree.java, server/src/test/java/org/apache/iotdb/db/metadata/MManagerBasicTest.java
Apache IoTDB v0.12 cannot count timeseries and device correctly after introducing template. 
When we create a template t1(s1, s2) and then set it to device root.sg1.d1, we expect value 2 produced by count timeseries and value 1 produced by count device. However, the actual result is 0 timeseries and 0 device.
If a MNode is using template, it should be considered as device and the schema in its template will be considered as timeseries. However, the current code only consider a MeasurementMNode as timeseries and a MNode with MeasurementMNode child as device. Therefore, the method getAllTimeseriesCount  and  getAllTimeseriesCount in MTree.java should be modified and the judging criteria will be extended with template usage. 
<hr>
This PR has:
- added unit tests or …
=> [To rel/0.12][IOTDB-1482] Fix Count Timeseries and Count Devices with Template Bug 

server/src/main/java/org/apache/iotdb/db/metadata/MTree.java, server/src/test/java/org/apache/iotdb/db/metadata/MManagerBasicTest.java
Apache IoTDB v0.12 cannot count timeseries and device correctly after introducing template.
When we create a template t1(s1, s2) and then set it to device root.sg1.d1, we expect value 2 produced by count timeseries and value 1 produced by count device. However, the actual result is 0 timeseries and 0 device.
If a MNode is using template, it should be considered as device and the schema in its template will be considered as timeseries. However, the current code only consider a MeasurementMNode as timeseries and a MNode with MeasurementMNode child as device. Therefore, the method getAllTimeseriesCount and getAllTimeseriesCount in MTree.java should be modified and the judging criteria will be extended with template usage.
<hr>
This PR has:
-  added unit tests or …
=> [IOTDB-1482]Fix timeseries count and device count with Template

flink-iotdb-connector/src/main/java/org/apache/iotdb/flink/IoTDBSink.java
After starting IoTDB, executing `FlinkIoTDBSink.java` would result in an exception "... path already exists". It turns out `IoTDBSink.initSession()` would be executed in parallel. At the very beginning, `pool.checkTimeseriesExists(option.getPath())` retruns `true` among them. After one of them creating the path successfully, the others would fail. 
What is mentioned in JIRA is not an issue, which is reported in server and it is allowed. The client should receive the feedback (storage already exists), catch the exception and ignore it.
=> [IoTDB-1449] path already exist error in IoTDBSink

server/src/test/java/org/apache/iotdb/db/integration/IoTDBContinuousQueryIT.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBTriggerExecutionIT.java
The issue sometimes can be reproduced in IoTDBContinuousQueryIT & IoTDBTriggerExecutionIT.
A background data generator will be started when a ContinuousQueryIT or a TriggerExecutionIT runs. The data generator uses JDBC client to execute insertion statements. As we already know, the JDBC connection may break because of TException occurs and it does not have the retry logic.
To resolve the issue, we can catch the exception, create a new connection and execute the statement again.
A failed run example:
https://github.com/apache/iotdb/pull/3572/checks?check_run_id=3072369955
=> [IOTDB-1506] CI fails because of JDBC connection exceptions

docs/UserGuide/Ecosystem Integration/Flink IoTDB.md, example/flink/src/main/java/org/apache/iotdb/flink/FlinkIoTDBSink.java, flink-iotdb-connector/src/main/java/org/apache/iotdb/flink/IoTDBSink.java, flink-iotdb-connector/src/main/java/org/apache/iotdb/flink/options/IoTDBSinkOptions.java
The storage group and time series registerations are not necessary in IoTDBSink, which would introduce inconvenience for users.
=> [To rel/0.12][IoTDB-1499] Remove series registeration using IoTDBSink ->  0.12

cluster/src/main/java/org/apache/iotdb/cluster/log/applier/BaseApplier.java, testcontainer/src/test/java/org/apache/iotdb/db/sql/Cases.java
Error was thrown in cluster mode when executing delete timeseries statement.
It happended frequently in the condition that ReplicateNum greater than node count.
It seems that batch exception is not handled correctly, timeseries does not exist exception should be skipped when delete timeseries plan is executing.
More details in https://issues.apache.org/jira/browse/IOTDB-1456
=> [IOTDB-1456] Fix Error occurred while executing delete timeseries statement

server/src/main/java/org/apache/iotdb/db/writelog/recover/TsFileRecoverPerformer.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBRestartIT.java
https://issues.apache.org/jira/browse/IOTDB-1513
Suppose we have the following ChunkMetadata in a unclosed tsfile:
d1.s1: ChunkMetadata(INT32, starttime=1, endtime=2)，ChunkMetadata(INT32, starttime=1, endtime=2)
d1.s2: ChunkMetadata(BOOLEAN, starttime=1, endtime=2)，ChunkMetadata(INT32, starttime=1, endtime=2)
To solve this problem, we need to group the Chunkmetadata by measurement, and only remove the first ChunkMetadata of d1.s2, because the d1.s2 may be deleted and recreated.
=> [To rel/0.11] [IoTDB-1513]fix recover TsFileResource time bug in restart

server/src/main/java/org/apache/iotdb/db/writelog/recover/TsFileRecoverPerformer.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBRestartIT.java
https://issues.apache.org/jira/browse/IOTDB-1513
Suppose we have the following ChunkMetadata in a unclosed tsfile:
d1.s1: ChunkMetadata(INT32, starttime=1, endtime=2)，ChunkMetadata(INT32, starttime=1, endtime=2)
d1.s2: ChunkMetadata(BOOLEAN, starttime=1, endtime=2)，ChunkMetadata(INT32, starttime=1, endtime=2)
To solve this problem, we need to group the Chunkmetadata by measurement, and only remove the first ChunkMetadata of d1.s2, because the d1.s2 may be deleted and recreated.
=> [IoTDB-1513] fix recover TsFileResource time interval bug

server/src/main/java/org/apache/iotdb/db/service/TSServiceImpl.java, tsfile/src/main/java/org/apache/iotdb/tsfile/read/expression/util/ExpressionOptimizer.java
StackOverflowError is encountered during query optimization in TsFile. To avoid system failure, we catch the StackOverflow error and throw QueryFilterOptimizationException。
=> Throwing exception when StackOverFlow error is encountered

server/src/main/java/org/apache/iotdb/db/qp/physical/PhysicalPlan.java
Since 0.12.2 introduce some new PhysicalPlans about template, the mlog will record some template information. 
Therefore, we need to reorder the PhysicalPlanType in master branch to keep the compatibility of mlog with 0.12.2.
=> improve mlog compatibility from 0.12.2 to 0.13.0

antlr/src/main/antlr4/org/apache/iotdb/db/qp/sql/SqlBase.g4, server/src/main/java/org/apache/iotdb/db/qp/physical/crud/InsertRowPlan.java, server/src/main/java/org/apache/iotdb/db/qp/sql/IoTDBSqlVisitor.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBInsertWithoutTimeIT.java
1.This PR support users insert data without timestamp, the server use the current system timestamp to pair with the data points.
2.When the timeseries named with time/timestamp/TIME/TIMESTAMP,  it will throw exception.
3.It doesn't support insert mult rows and will throw SQLParserException
<hr>
This PR has:
<hr>
=> [IOTDB-1059] Support sql statement insert without timestamp

server/src/main/java/org/apache/iotdb/db/engine/StorageEngine.java, server/src/main/java/org/apache/iotdb/db/engine/storagegroup/StorageGroupProcessor.java, server/src/main/java/org/apache/iotdb/db/engine/storagegroup/virtualSg/VirtualStorageGroupManager.java
When recovering IoTDB, if one storage group is not ready, all read/write requests will be rejected, which is not our respected.
To make each virtual storage group independent,  i change the ready unit of recovering IoTDB from the whole db to each independent virtual storage group, so each virtual storage group can resolve read/write requests if it has recovered.
=> [IOTDB-1478]The whole IoTDB can not read/write if any one sg is not ready

cluster/src/main/java/org/apache/iotdb/cluster/metadata/CMManager.java, testcontainer/src/test/java/org/apache/iotdb/db/sql/Cases.java
In a whole new environment, it has to be a whole new environment.
1. create timeseries root.ln.wf01.wt21 WITH DATATYPE=DOUBLE, ENCODING=RLE, compression=SNAPPY tags(tag1=v1, tag2=v2)
2. SHOW TIMESERIES root where tag1=v1
Msg: 303: The key tag1 is not a tag
Reason:
The show timeseries root... command is used to query all DataGroup groups. If a DataGroup group does not have a sequence, an error is reported. As a result, other DataGroups that have a sequence cannot obtain the result.
Solution:
we should catch a remote show-timeseries.
=> [IOTDB-1509] show timeseries throw a bug

testcontainer/src/test/java/org/apache/iotdb/db/sql/Cases.java
Remove unnecessary tests due to there reasons:
- Since each test case is currently tested in seven clusters started by TestContainer, the time to add a test CI increases by approximately 2 mins, so we need to minimize the number of test functions if possible.
- I don't think it makes any sense to put three operations functions in testContainer without checking them, and these functions should be added to applier's IT which is already done.
- Currently, master ci often fails because of the presence of leader Not found for these three functions. Although this may require us to add the corresponding retry logic, it is better to kill these unrelated functions first.
=> Fix TestContainer  IT

server/src/test/java/org/apache/iotdb/db/integration/IoTDBContinuousQueryIT.java
https://issues.apache.org/jira/browse/IOTDB-1528
1. Improve code style in IoTDBContinuousQueryIT.java 
2. Try to make CQ IT stable
CQ is asynchronously executed, the startup time and completion time of the CQ task are very dependent on the test environment. The IT sometimes failed on Github Actions but always passed on my MBP. 
At present, CQ IT fails mostly because the wait time is not long enough and the database does not produce the expected data points. We can make the test wait long enough for the database to produce more data points than expected and then do a follow-up check on the data points.
The core changes are as follows:
```java
long waitSeconds = 0;
List<Pair<Long, String>> result;
do {
Thread.sleep(waitSeconds);
waitSeconds += 1000;
statement.execute("select temperature_avg …
```
=> [IOTDB-1528] CQ IT unstable: sometimes fails on `checkCQExecutionResult()`

server/src/main/java/org/apache/iotdb/db/engine/compaction/TsFileManagement.java, server/src/main/java/org/apache/iotdb/db/engine/merge/manage/MergeResource.java, server/src/main/java/org/apache/iotdb/db/engine/merge/selector/MaxFileMergeFileSelector.java, server/src/main/java/org/apache/iotdb/db/engine/storagegroup/TsFileResource.java
In the selection of cross space compaction, current code uses a syncrhoized to ensure atomicity. However, every time a selection is carried out, the program will new a MergeTask, which may fail to ensure atomicity, and two selection process will execute simultaneously.
Moreover, in the selection of cross space compaction, the program doesn't check the file's merging status, which may cause a file to be selected by two compaction task.
We replace the synchronized with a write lock to ensure that only one selection can be carried out at the same time. And we check the merging status of file to avoid a file is selected by two compaction task
=> [To autoai] Fix lock bug in cross space compaction selection

server/src/main/java/org/apache/iotdb/db/qp/Planner.java, server/src/main/java/org/apache/iotdb/db/qp/strategy/PhysicalGenerator.java, server/src/main/java/org/apache/iotdb/db/qp/strategy/optimizer/ConcatPathOptimizer.java, server/src/main/java/org/apache/iotdb/db/qp/strategy/optimizer/ILogicalOptimizer.java, server/src/main/java/org/apache/iotdb/db/query/control/QueryResourceManager.java, server/src/main/java/org/apache/iotdb/db/service/TSServiceImpl.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBSequenceDataQueryIT.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBSeriesReaderIT.java, server/src/test/java/org/apache/iotdb/db/qp/plan/LogicalPlanSmallTest.java, server/src/test/java/org/apache/iotdb/db/utils/EnvironmentUtils.java, spark-iotdb-connector/src/test/scala/org/apache/iotdb/spark/db/EnvironmentUtils.java
Current dynamic query memory control causes some problems, maybe bugs, we'd better remove it temporary.
=> [To rel/0.11] [IOTDB-1500] Remove current dynamic query memory control

server/src/main/java/org/apache/iotdb/db/metadata/MManager.java, server/src/main/java/org/apache/iotdb/db/metadata/MTree.java
In current version, when mmanager is recovering, the failure of operation on plans read from mlog should not afftect the increasement of log index and only the logReader.next concerns. The wrong log index will result in existing record being covered by new mlog record.
Although this operation is infrequent, it can't be guaranteed that the user or tests won't use multi thread to set one storage group. The storage group node check and add should be synchronized.
<hr>
This PR has:
<hr>
=> [To rel/0.12][IOTDB-1529]Fix mlog recover idx bug and synchronize setStorageGroup

server/src/main/java/org/apache/iotdb/db/metadata/MManager.java, server/src/main/java/org/apache/iotdb/db/metadata/MTree.java
In current version, when mmanager is recovering, the failure of operation on plans read from mlog should not afftect the increasement of log index and only the logReader.next concerns. The wrong log index will result in existing record being covered by new mlog record.
Although this operation is infrequent, it can't be guaranteed that the user or tests won't use multi thread to set one storage group. The storage group node check and add should be synchronized.
<hr>
This PR has:
<hr>
=> [IOTDB-1529]Fix mlog recover idx bug and synchronize setStorageGroup

cluster/src/main/java/org/apache/iotdb/cluster/query/last/ClusterLastQueryExecutor.java, cluster/src/main/java/org/apache/iotdb/cluster/server/member/DataGroupMember.java, cluster/src/main/java/org/apache/iotdb/cluster/server/member/MetaGroupMember.java, cluster/src/main/java/org/apache/iotdb/cluster/server/member/RaftMember.java, server/src/main/java/org/apache/iotdb/db/engine/storagegroup/TsFileProcessor.java
The Thrift Client will assign a serial number to each RPC. SocketTimeoutException is a behavior of the client, after which we should discard it. If it is used to send RPC again, it will increase the serial number when sending, but it may receive the last packet when receiving data. This causes the out of sequence bug.
=> [To rel/0.12]Fix thrift out of sequence in cluster module

server/src/test/java/org/apache/iotdb/db/engine/storagegroup/StorageGroupProcessorTest.java
Sometimes check may fail because memtable flush task hasn't submitted.
=> Fix timed flush memtable test

server/src/main/java/org/apache/iotdb/db/query/reader/series/SeriesReader.java
It's a `order by time desc` bug. DescReadWriteBatchData should be flipped before returned.
=> [ISSUE-3653] [To rel/0.11] Max_time and last return inconsistent result

server/src/main/java/org/apache/iotdb/db/query/reader/series/SeriesReader.java
It's a order by time desc bug. DescReadWriteBatchData should be flipped before returned.
=> [ISSUE-3653] [To rel/0.12] Max_time and last return inconsistent result

server/src/main/java/org/apache/iotdb/db/query/reader/series/SeriesReader.java
It's a order by time desc bug. DescReadWriteBatchData should be flipped before returned.
=> [ISSUE-3653] Max_time and last return inconsistent result

server/src/main/java/org/apache/iotdb/db/metadata/MManager.java, server/src/main/java/org/apache/iotdb/db/metadata/MTree.java, server/src/main/java/org/apache/iotdb/db/metadata/mnode/EntityMNode.java, server/src/main/java/org/apache/iotdb/db/metadata/mnode/IEntityMNode.java, server/src/main/java/org/apache/iotdb/db/metadata/mnode/IMNode.java, server/src/main/java/org/apache/iotdb/db/metadata/mnode/IMeasurementMNode.java, server/src/main/java/org/apache/iotdb/db/metadata/mnode/IStorageGroupMNode.java, server/src/main/java/org/apache/iotdb/db/metadata/mnode/InternalMNode.java, server/src/main/java/org/apache/iotdb/db/metadata/mnode/MNode.java, server/src/main/java/org/apache/iotdb/db/metadata/mnode/MeasurementMNode.java, server/src/main/java/org/apache/iotdb/db/metadata/mnode/StorageGroupEntityMNode.java, server/src/test/java/org/apache/iotdb/db/metadata/MManagerBasicTest.java, server/src/test/java/org/apache/iotdb/db/metadata/mnode/MNodeTest.java
IEntityMNode defines the operations on an EntityMNode, in terms of aliasChilren and template usage for the time being. More functions like template lastCache will be implemented based on EntityMNode soon.
The EntityMNode will be used when timeseries is created or the template is used on an InternalMNode. The parent node of a MeasurementMNode and node using template will be transform to EntityMNode.
To avoid the conflict between StorageGroupMNode and EntityMNode, StorageGroupEntityMNode is implemented combining functions of both side, which means an entity can be a storage group and measurements can be created directly under a storage group path. StorageGroupEntityMNode extends EntityMNode and implements IStorageGroupMNode interface with the same code in StorageGroupMNode. 
Since the …
=> [IOTDB-1511] Implement EntityMNode

compile-tools/thrift/pom.xml
Fixes issue #3674 
It's useless and time wasted to generate Javascript client code when building cpp client.
=> [ISSUE-3674] Disable thrift code generation for Javascript

compile-tools/thrift/pom.xml
Fixes issue #3674
It's useless and time wasted to generate Javascript client code when building cpp client.
=> [To rel/0.12][ISSUE-3674] Disable thrift code generation for Javascript

site/README-zh.md, site/README.md, site/pom.xml, site/src/main/.asf.yaml
The website is no longer updated anymore after July 1st because of we are using Git rather than SVN.
see (Apache id login needed):
https://lists.apache.org/thread.html/raf30ca1c77b81bc8c535c53b7aff38e1ff3c755ce84f4a40a6d8ad53%40%3Cusers.infra.apache.org%3E
According to the doc: 
https://cwiki.apache.org/confluence/display/INFRA/Git+-+.asf.yaml+features#Git.asf.yamlfeatures-WebSiteDeploymentServiceforGitRepositories
I add the .asf.yaml file for deploying the website.
See the page for checking whether the website is healthy:
https://infra-reports.apache.org/site-source/
=> add .asf.yaml file for deploying website

server/src/main/java/org/apache/iotdb/db/engine/storagegroup/StorageGroupProcessor.java
In current no compaction strategy, the system will submit a compaction task to thread pool when system recovers, a tsfile is sealed or a timed schedule thread wakes up. The compaction task in NO_COMPACTION strategy just does nothing. But it may block the system because the submission of the task synchronized the CompactionMergeTaskManager. In this PR we stop the system from submitting compaction task when the compaction strategy is NO_COMPACTION
=> [To rel/0.12] Stop NO_COMPACTION strategy from submitting compaction task

client-cpp/src/main/Session.cpp, client-cpp/src/main/Session.h, client-cpp/src/test/main.cpp, server/src/main/java/org/apache/iotdb/db/query/control/SessionManager.java, server/src/main/java/org/apache/iotdb/db/service/TSServiceImpl.java
1. fix leak in sessionIdToStatementId & statementIdToQueryId
2. fix leak caused by cpp client: statementId not set in TSCloseOperationReq
3. fix code format of cpp tests
JIRA: https://issues.apache.org/jira/browse/IOTDB-1545
=> [IOTDB-1545] Query dataset momory leak on server caused by cpp client

client-cpp/src/main/Session.cpp, client-cpp/src/main/Session.h, client-cpp/src/test/main.cpp, server/src/main/java/org/apache/iotdb/db/query/control/SessionManager.java, server/src/main/java/org/apache/iotdb/db/service/TSServiceImpl.java
1. fix leak in sessionIdToStatementId & statementIdToQueryId
2. ix leak caused by cpp client: statementId not set in TSCloseOperationReq
3. fix code format of cpp tests
JIRA: https://issues.apache.org/jira/browse/IOTDB-1545
=> [To rel/0.12][IOTDB-1545] Query dataset momory leak on server caused by cpp client

client-cpp/src/main/Session.cpp
=> [ISSUE-3690] Memory leaks on the server when cpp client invokes `checkTimeseriesExists`

client-cpp/src/main/Session.cpp
=> [To rel/0.12][ISSUE-3690] Memory leaks on the server when cpp client invokes `checkTimeseriesExists`

server/src/main/java/org/apache/iotdb/db/tools/TsFileRewriteTool.java, server/src/main/java/org/apache/iotdb/db/tools/upgrade/TsFileOnlineUpgradeTool.java
https://issues.apache.org/jira/browse/IOTDB-1546
Some users meet OOM when upgrading some large-size merged 0.11 TsFiles.
Therefore, this PR optimizes the upgrade logic by upgrading Chunk-by-Chunk instead of ChunkGroup-by-ChunkGroup.  
The comparison of upgrading a same 2GB TsFile shows below.
<hr>
This PR has:
<hr>
=> [IOTDB-1546] [To rel/0.12] Optimize the Upgrade Tool rewrite logic to reduce the temp memory cost

cluster/src/main/java/org/apache/iotdb/cluster/config/ClusterDescriptor.java
The default max_sync_log_lag is mistakenly set to default max_read_log_lag.
=> fix defaut max_sync_log_lag

server/src/main/java/org/apache/iotdb/db/metadata/MManager.java, server/src/main/java/org/apache/iotdb/db/metadata/MTree.java, server/src/test/java/org/apache/iotdb/db/metadata/MManagerBasicTest.java
When users use session API to insert data and auto create time series, there's no syntax check on deviceIds or measurementIds before insert plan generating like SQL  parse. If there's a id contains symbol ".", like device id as root.sg.d and measurement id as a.b, the measurement id is obviously illegal and the meaning of path root.sg.d.a.b is ambiguous.  
Also solved https://issues.apache.org/jira/browse/IOTDB-1475 .
The schema names in template is also a loophole.
Currently, a syntax check is added to mtree.checkTimeseries while it's going to auto create time series.
Method checkTemplateSchemaNames is  added to mmanager  while create template
The illegal ids should be filtered when the API is invoked or a query is parsed as soon as possible before further operation.  
<hr>
This PR has: …
=> [To rel/0.12] MeasurementId check while create timeseries or template

server/src/main/java/org/apache/iotdb/db/exception/metadata/StorageGroupAlreadySetException.java, server/src/main/java/org/apache/iotdb/db/metadata/MManager.java, server/src/test/java/org/apache/iotdb/db/metadata/MManagerBasicTest.java
After operating the following operations: 
1. set storage group to root.a.sg
2. insert into root.a.d(time, s) values(1, 1)
Timeseries root.a.d.s won't be created for no storage group, but device node root.a.d will be created without storage group.
If a device node without any timeseries is created without storageGroup, then, in current code, it's unable to set any storage group on its ancestors and create any timeseries under it. Only set storage group to its descendants could be operated successfully. 
Since we don't have device node deletion oeperation, most of users will be confused and don't know how to handle this device node.
In MManager.getDeviceNodeWithAutoCreate, if there's a storageGroupAlreadyExistException, the device node will be created with out storage group check. If the …
=> [To rel/0.12][IOTDB-1556] Abort auto create device while setStorageGroup exception

server/src/main/java/org/apache/iotdb/db/engine/memtable/AbstractMemTable.java, server/src/main/java/org/apache/iotdb/db/engine/memtable/IMemTable.java, server/src/main/java/org/apache/iotdb/db/engine/storagegroup/TsFileProcessor.java
When inserting data, IoTDB first inserts data into memtable and then writes wal. If writing wal occurs error, the data in memtable should rollback, but IoTDB doesn't implement this. This problem can be fixed by changing the sequence of wal and memtable in insert.
=> [IOTDB-1541][To rel/0.12] Change sequence of wal and memtable in insert

server/src/main/java/org/apache/iotdb/db/engine/memtable/AbstractMemTable.java, server/src/main/java/org/apache/iotdb/db/engine/memtable/IMemTable.java, server/src/main/java/org/apache/iotdb/db/engine/storagegroup/TsFileProcessor.java, server/src/test/java/org/apache/iotdb/db/sink/LocalIoTDBSinkTest.java
When inserting data, IoTDB first inserts data into memtable and then writes wal. If writing wal occurs error, the data in memtable should rollback, but IoTDB doesn't implement this. This problem can be fixed by changing the sequence of wal and memtable in insert.
=> [IOTDB-1541] Change sequence of wal and memtable in insert

RELEASE_NOTES.md, server/src/main/java/org/apache/iotdb/db/concurrent/IoTDBThreadPoolFactory.java, server/src/main/java/org/apache/iotdb/db/concurrent/threadpool/IThreadPoolMBean.java, server/src/main/java/org/apache/iotdb/db/concurrent/threadpool/WrappedScheduledExecutorService.java, server/src/main/java/org/apache/iotdb/db/concurrent/threadpool/WrappedScheduledExecutorServiceMBean.java, server/src/main/java/org/apache/iotdb/db/concurrent/threadpool/WrappedSingleThreadExecutorService.java, server/src/main/java/org/apache/iotdb/db/concurrent/threadpool/WrappedSingleThreadExecutorServiceMBean.java, server/src/main/java/org/apache/iotdb/db/concurrent/threadpool/WrappedSingleThreadScheduledExecutor.java, server/src/main/java/org/apache/iotdb/db/concurrent/threadpool/WrappedSingleThreadScheduledExecutorMBean.java, server/src/main/java/org/apache/iotdb/db/concurrent/threadpool/WrappedThreadPoolExecutor.java, server/src/main/java/org/apache/iotdb/db/concurrent/threadpool/WrappedThreadPoolExecutorMBean.java, server/src/main/java/org/apache/iotdb/db/conf/IoTDBConstant.java, server/src/main/java/org/apache/iotdb/db/engine/StorageEngine.java, server/src/main/java/org/apache/iotdb/db/engine/compaction/CompactionMergeTaskPoolManager.java, server/src/main/java/org/apache/iotdb/db/engine/flush/FlushManager.java, server/src/main/java/org/apache/iotdb/db/engine/merge/manage/MergeManager.java, server/src/main/java/org/apache/iotdb/db/engine/storagegroup/StorageGroupProcessor.java, server/src/main/java/org/apache/iotdb/db/metadata/MManager.java, server/src/main/java/org/apache/iotdb/db/service/MetricsService.java, server/src/main/java/org/apache/iotdb/db/service/TSServiceImpl.java, server/src/main/java/org/apache/iotdb/db/service/UpgradeSevice.java, server/src/main/java/org/apache/iotdb/db/writelog/manager/MultiFileLogNodeManager.java, server/src/main/java/org/apache/iotdb/db/writelog/node/ExclusiveWriteLogNode.java
We use many thread pools in IoTDB and it is hard to know how many thread pool we have totally and whether a thread pool is busy.
Therefore, I unify the creation of ThreadPool, register it to JMX and allow using JMX to check its active size, pending size, etc..
When the threadpool is `shutdown()` or `shutdownNow()`, the Pool will be deregistered from JMX.
Only The server module has been upgrade to such kind of ThreadPool.
I will do the same thing in the Master branch and replace all thread pools in the cluster module using this kind of thread pool.
Once this PR is merged, in the server module, DO NOT USE `Executors.newXXX()` FUNCTIONS ANY MORE IN THE FUTURE.
See the effect:
( This PR is hard to add UT to cover the codes. I have tested manually.)
=> [To rel/0.12] add JMX monitor to all ThreadPools in the server module

server/src/test/java/org/apache/iotdb/db/integration/IoTDBCreateTimeseriesIT.java, server/src/test/java/org/apache/iotdb/db/utils/EnvironmentUtils.java
When I run this IT on my computer, it costs as long as 1 min to stop the rpc service. 
And I got an error message `org.apache.thrift.server.TThreadPoolServer:144 - Shutdown is not done after 60 SECONDS`.
The reason is this test doesn't close the statement and connection before execute `EnvironmentUtils.stopDaemon()`.
=> [To rel/0.12] Fix CreateTimeseriesIT runs slow

server/src/test/java/org/apache/iotdb/db/integration/IoTDBAutoCreateSchemaIT.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBCreateStorageGroupIT.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBQueryMemoryControlIT.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBUDFWindowQueryIT.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBUDTFAlignByTimeQueryIT.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBUDTFBuiltinFunctionIT.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBUDTFHybridQueryIT.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBUDTFNonAlignQueryIT.java
The reason see #3724 .
Also be careful, **DO NOT** use this kind of pattern to create connection and statement. It will cause connection not closed.
```java
try (Statement statement =
DriverManager.getConnection(Config.IOTDB_URL_PREFIX + "127.0.0.1:6667/", "root", "root")
.createStatement()) {
...
}
```
=> [To rel/0.12] Fix CI runs slow caused by connection not closing

server/src/main/java/org/apache/iotdb/db/service/TSServiceImpl.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBArithmeticIT.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBAutoCreateSchemaIT.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBContinuousQueryIT.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBCreateStorageGroupIT.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBCreateTimeseriesIT.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBQueryMemoryControlIT.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBSelectIntoIT.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBTriggerExecutionIT.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBUDFWindowQueryIT.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBUDTFAlignByTimeQueryIT.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBUDTFBuiltinFunctionIT.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBUDTFHybridQueryIT.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBUDTFNonAlignQueryIT.java
The reason see #3724 .
Also be careful, **DO NOT** use this kind of pattern to create connection and statement. It will cause connection not closed.
```java
try (Statement statement =
DriverManager.getConnection(Config.IOTDB_URL_PREFIX + "127.0.0.1:6667/", "root", "root")
.createStatement()) {
...
}
```
also see https://github.com/apache/iotdb/pull/3728
=> Fix CI runs slow caused by connection not closing

client-py/iotdb/utils/Tablet.py, client-py/tests/tablet_performance_comparison.py, example/mqtt-customize/pom.xml, example/session/src/main/java/org/apache/iotdb/TabletExample.java
We submit a new implementation for speeding up the **tablet insert**. The previous implementation import the built-in `struct` package to covert tablet data to byte array (see in `iotdb.utils.Tablet.Tablet#get_binary_timestamps` and `iotdb.utils.Tablet.Tablet#get_binary_values`). However, the original  implementation widely uses python `for-loop`, which is much slower than the for-loop in `Java` and `C`. 
In this pull request:
* We use `numpy` to store memory data and serialize data with `numpy.tobytes`, an efficient C-level underlying function. 
* We further use `memoryview` to concatenate multiple byte arrays. `memoryview` is a built-in buffer protocol that allows the caller to access byte arrays sequentially without intermediate copying.
* We try the `pandas` and `numpy` to narrow the …
=> A new python implementation for speeding up tablet insertion

server/src/main/java/org/apache/iotdb/db/engine/compaction/level/LevelCompactionTsFileManagement.java, server/src/main/java/org/apache/iotdb/db/engine/compaction/utils/CompactionUtils.java, server/src/main/java/org/apache/iotdb/db/engine/storagegroup/StorageGroupProcessor.java, server/src/main/java/org/apache/iotdb/db/writelog/recover/TsFileRecoverPerformer.java, server/src/test/java/org/apache/iotdb/db/engine/compaction/LevelCompactionRecoverTest.java, tsfile/src/main/java/org/apache/iotdb/tsfile/write/writer/RestorableTsFileIOWriter.java, tsfile/src/main/java/org/apache/iotdb/tsfile/write/writer/TsFileOutput.java
During compaction recover, a RestorableIOWriter of target file will be new three times:
1. First new in StorageGroupProcessor, to determine whether a file is complete
2. Second new in CompactionRecoverTask, to truncate the file to the offset logged in compaction log
3. Third new in CompactionUtils, continues to compact files.
However, the last ChunkGroup in the file will be remove when a RestorableIOWriter is new. So the data will be lost when recovering inner space compaction.
In this PR, we add a new constructor for RestorableIOWriter. Beyond this, we fix a bug when truncating target file, which may cause a marker in target tsfile to be lost.
=> [To rel/0.12] Fix compaction recover loses data

server/src/main/java/org/apache/iotdb/db/qp/sql/IoTDBSqlVisitor.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBDeletionIT.java
https://issues.apache.org/jira/browse/IOTDB-1539
For now, deletion do not support values filter, but, all conditions in where clause will be treated as time condition, thus will product two affects:
1. If the data type in condition could be parsed to Long, the statement will be executed successfully, it's dangerous!!
For example, the original statement is "delete from root.vehicle.d1.s1 where s1 > 100", but the actually statement be 
executed is "delete from root.vehicle.d1.s1 where time > 100".  Then, data may be deleted abnormally.
2. If the data type in condition could not be parsed to Long, we will get a 500 error because of a NumberFormatException.
Before the value filter feature is implemented, I temporally fixed this by return an error message like "For delete statement, where …
=> [IOTDB-1539] Fix delete operation with value filter is abnormal

pom.xml, server/src/main/java/org/apache/iotdb/db/engine/storagegroup/StorageGroupProcessor.java, server/src/main/java/org/apache/iotdb/db/writelog/node/ExclusiveWriteLogNode.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBJMXTest.java
JMX requires each monitored object having the identical address string.
However, in WAL and SG processor, some thread pool having the same name, when these objects are created multiply times.
Error log: 
https://issues.apache.org/jira/secure/attachment/13031996/log_all.log
=> [IOTDB-1567]fix some WAL and SG processor threadpools having the same JMX name

server/src/main/java/org/apache/iotdb/db/engine/storagegroup/StorageGroupProcessor.java
Check tsfile's time when recovering, make sure all tsfile time are less than System.currentTimeMillis(). If the tsfile's time is larger than System.currentTimeMillis(), the recover of corresponding virtual storage group will fail, users cannot read/write this virtual storage group until the time of the tsfile is correct.
Before fixing time：
After fixing time：
=> [IOTDB-1531] Check tsfile creation time when recovering

server/src/main/java/org/apache/iotdb/db/rescon/PrimitiveArrayManager.java
Cherry-picked from 33758d68e0294576d6d27f1bec4c01bb4113a7b8.
The actual used memory will be 50% larger than the statistic, so we need to limit the size of POOLED_ARRAYS_MEMORY_THRESHOLD, make it smaller than its actual allowed value.
=> PrimitiveArrayManager: make POOLED_ARRAYS_MEMORY_THRESHOLD smaller than its actual allowed value

cluster/src/main/java/org/apache/iotdb/cluster/coordinator/Coordinator.java, cluster/src/main/java/org/apache/iotdb/cluster/server/member/DataGroupMember.java
**Note** this is the replacement of PR: https://github.com/apache/iotdb/pull/3755
JIRA issue: https://issues.apache.org/jira/projects/IOTDB/issues/IOTDB-1473
The issue happens because auto create schema not work in cluster mode. The `insertTables()` tries to insert timeseries to `root.sg1.d2.s1`, `root.sg1.d2.s2`, `root.sg1.d2.s3` but which aren't created until the insertion. The schema create logic fail in the execution path which cause the issue.
Actually, there are three errors auto create schema related in the cluster as far as I can know (comment out the create timeseries related code in `SessionExample.java` to reproduce).
```
...
// createTimeseries();
// createMultiTimeseries();
// insertRecord();
insertTablet();   // can't auto create schema
insertTablets(); // can't auto create …
```
=> [IOTDB-1473] Fix the bug that run SessionExample.java will be failed in

tsfile/src/main/java/org/apache/iotdb/tsfile/read/query/timegenerator/node/LeafNode.java, tsfile/src/test/java/org/apache/iotdb/tsfile/read/ReadOnlyTsFileTest.java
When using valueFilter to filter data, the page's statistics are used to pre-check for conditions, but when the actual data does not exist, BatchData returns a container that does not have any data.
The LeafNode checks the BatchData, and if hasCurrent returns false, the query is broken and we actually need to continue to the next page
=> [IOTDB-1575] [To rel/0.12] Tsfile valueFilter cannot handle multiple pages

RELEASE_NOTES.md, server/src/main/java/org/apache/iotdb/db/query/control/QueryFileManager.java
#3786
This problem is caused by the reference number of query reader is not decreased corrcetly, which leads to the reference number is not 0 and the object can not be closed.
=> [To rel/0.12] [ISSUE-3786] Data file is deleted while file handle is not released

server/src/main/java/org/apache/iotdb/db/query/control/QueryFileManager.java
#3786 
This problem is caused by the reference number of query reader is not decreased corrcetly, which leads to the reference number is not 0 and the object can not be closed.
=> [IOTDB-1574] [ISSUE-3786] Data file is deleted while file handle is not released

server/src/main/java/org/apache/iotdb/db/engine/cache/ChunkCache.java, server/src/main/java/org/apache/iotdb/db/engine/cache/TimeSeriesMetadataCache.java
We used to fuzzy computing to calculate the cache size, which led to some large caches being incorrectly counted, resulting in oom. And some concurrent problems may be caused by this.
Therefore, we try to calculate the cache size exactly to avoid these problems.
=> [ISSUE-3805] OOM caused by Chunk cache

RELEASE_NOTES.md, server/src/main/java/org/apache/iotdb/db/engine/modification/ModificationFile.java, server/src/main/java/org/apache/iotdb/db/engine/modification/io/ModificationWriter.java, server/src/main/java/org/apache/iotdb/db/engine/storagegroup/StorageGroupProcessor.java
ModificationFile‘s write interface reads modifications from .mods file before writing modification, this causes deleting data costing too much time. After fixing, ModificationFile‘s write interface will write modifications directly into .mods file.
Before fixing:
After fixing:
=> [IOTDB-1585][To rel/0.12] ModificationFile‘s write interface blocking

RELEASE_NOTES.md, example/session/src/main/java/org/apache/iotdb/SessionExample.java, session/src/main/java/org/apache/iotdb/session/Session.java, session/src/main/java/org/apache/iotdb/session/pool/SessionPool.java, session/src/test/java/org/apache/iotdb/session/SessionUT.java, session/src/test/java/org/apache/iotdb/session/pool/SessionPoolTest.java
https://issues.apache.org/jira/browse/IOTDB-1587
In this PR, I do the following things:
1. rename timeout to queryTimeoutInMs in Session
2. allow users to set connectionTimeoutInMs in SessionPool
3. new Session creation strategy in SessionPool: removeSession -> tryConstructNewSession
4. new Session creation strategy in SessionPool: when the Session cannot be obtained and the thread enters the waiting loop, it will always judge whether a new Session can be created first in each loop, instead of waiting in each loop after judging whether a new Session can be created only once.
=> [To rel/0.12][IOTDB-1587] SessionPool optimization: a more aggressive Session creation strategy

example/session/src/main/java/org/apache/iotdb/SessionExample.java, session/src/main/java/org/apache/iotdb/session/Session.java, session/src/main/java/org/apache/iotdb/session/pool/SessionPool.java, session/src/test/java/org/apache/iotdb/session/SessionTest.java, session/src/test/java/org/apache/iotdb/session/pool/SessionPoolTest.java
https://issues.apache.org/jira/browse/IOTDB-1587
In this PR, I do the following things:
1. rename timeout to queryTimeoutInMs in Session
2. allow users to set connectionTimeoutInMs in SessionPool
3. new Session creation strategy in SessionPool: removeSession -> tryConstructNewSession
4. new Session creation strategy in SessionPool: when the Session cannot be obtained and the thread enters the waiting loop, it will always judge whether a new Session can be created first in each loop, instead of waiting in each loop after judging whether a new Session can be created only once.
=> [IOTDB-1587] SessionPool optimization: a more aggressive Session creation strategy

RELEASE_NOTES.md, server/src/main/java/org/apache/iotdb/db/engine/compaction/level/LevelCompactionTsFileManagement.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBTimePartitionIT.java
The bug is caused by we didn't traverse the tsfile seqeunce in time partition order.
=> [To rel/0.12] [IOTDB-1580] Error result of order by time desc when enable time partition

cluster/src/main/java/org/apache/iotdb/cluster/query/LocalQueryExecutor.java
MAX_TIME is incorrect in cluster mode with TTL.
=> [IOTDB-1588] Bug fix: MAX_TIME is incorrect in cluster mode with TTL

cluster/src/main/java/org/apache/iotdb/cluster/query/LocalQueryExecutor.java
MAX_TIME is incorrect in cluster mode with TTL.
=> [IOTDB-1588] [To rel/0.12] Bug fix: MAX_TIME is incorrect in cluster mode with TTL

README.md, README_ZH.md, docs/Download/README.md, docs/zh/Download/README.md, server/src/assembly/resources/conf/iotdb-env.sh
For more detail, please see #3865.
=> [ISSUE-3865] Meaningless connection reset issues caused by low default value for SOMAXCONN

docs/UserGuide/Appendix/Config-Manual.md, docs/zh/UserGuide/Appendix/Config-Manual.md, server/src/assembly/resources/conf/iotdb-engine.properties, server/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java, tsfile/src/main/java/org/apache/iotdb/tsfile/common/conf/TSFileConfig.java, tsfile/src/main/java/org/apache/iotdb/tsfile/common/conf/TSFileDescriptor.java, tsfile/src/main/java/org/apache/iotdb/tsfile/write/schema/MeasurementSchema.java, tsfile/src/main/java/org/apache/iotdb/tsfile/write/schema/TimeseriesSchema.java, tsfile/src/main/java/org/apache/iotdb/tsfile/write/schema/VectorMeasurementSchema.java
Currently we have a meaningless config that changes the datatype of timestamp from INT64 to INT32. 
It also may cause bug if users change the default value to INT32.
It's better to remove it.
=> Remove timestamp datatype config

cluster/src/main/java/org/apache/iotdb/cluster/log/manage/serializable/SyncLogDequeSerializer.java
When i try to figure out why this issue occurs, i find that the result of last raft log file is different with my guess.Here are the result of my test environment _(ps.I ran into the same problem.)_
We find these files of raft log:
```
/.../system/raftLog/-1869016501/49923372-9223372036854775807-244-idx, 
/.../system/raftLog/-1869016501/48875442-49224751-241-idx, 
/.../system/raftLog/-1869016501/49224752-49574061-242-idx, 
/.../system/raftLog/-1869016501/49574062-49923371-243-idx
/.../system/raftLog/-1869016501/49574062-49923371-243-data, 
/.../system/raftLog/-1869016501/49923372-9223372036854775807-244-data, 
/.../system/raftLog/-1869016501/48875442-49224751-241-data, 
/.../system/raftLog/-1869016501/49224752-49574061-242-data
```
and process these files _(242-index and 243-data?)_ : …
=> [IOTDB-1619] There is an error msg when I restart iotdb-cluster

cli/src/main/java/org/apache/iotdb/cli/AbstractCli.java
When execute sql in CLI with -e mode, we should print all results by setting continuePrint is true.
=> [IOTDB-1275] Fix backgroup exec for cli -e function causes an infinite loop in writing output file

cli/src/main/java/org/apache/iotdb/cli/Cli.java, cli/src/main/java/org/apache/iotdb/cli/WinCli.java
=> [IOTDB-1670] Fix cli -e mode didn't fetch timestamp_precision from server

server/src/assembly/resources/conf/iotdb-env.sh
A cherry-pick of https://github.com/apache/iotdb/pull/3951
=> [To rel/0.12][IOTDB-1674] Fix command interpreting error causing somaxconn warning failed

example/client-cpp-example/src/SessionExample.cpp
[IOTDB-1289] fix CPP mem-leak in SessionExample.cpp insertRecords()
=> [IOTDB-1289] to rel/0.12, fix CPP mem-leak in SessionExample.cpp insertRecords()

client-cpp/src/main/Session.cpp
[IOTDB-1287] C++ class Session has 2 useless sort()
In below codes, those 2 sort() should be useless, because "tablet.timestamps" or "times" has been sorted in sortIndexByTimestamp()
============================================
File: ./client-cpp/src/main/Session.cpp
void Session::sortTablet(Tablet& tablet) {
... 
this->sortIndexByTimestamp(index, tablet.timestamps, tablet.rowSize);    //here, has sorted timestamps
sort(tablet.timestamps, tablet.timestamps + tablet.rowSize);  //useless sort
... 
}
void Session::insertRecordsOfOneDevice(string deviceId, ...){
... 
this->sortIndexByTimestamp(index, times.data(), times.size());    //here, has sorted times
sort(times.begin(), times.end());    //useless sort
... 
}
=> [IOTDB-1287] C++ class Session has 2 useless sort()

server/src/main/java/org/apache/iotdb/db/metadata/MManager.java
Use align by device function:
select * from root.database.student(any similar sql) align by device
Will print error:
Msg: 500: [INTERNAL_SERVER_ERROR] Exception occurred: "select * from root.database.student align by device". executeStatement failed. org.apache.iotdb.db.metadata.mnode.EntityMNode cannot be cast to org.apache.iotdb.db.metadata.mnode.IMeasurementMNode
Reason:
Children may be path or root node. ("country" and "score" belong path, and "anhui" belongs path)if it belong to path node, they don't need to type cast and add their schema to the res. Otherwise, if we don't make type  judgment , will be throw type cast exception.
The actual stored time series is shown in the figure below.
=> [IOTDB-1690] Fix align by device type cast error

client-cpp/src/main/Session.cpp
Cherry-pick
- #3966
<hr>
This PR has:
<hr>
=> [IOTDB-1287] [To rel/0.12] Fix C++ class Session has 2 useless sort()

RELEASE_NOTES.md, server/src/main/java/org/apache/iotdb/db/metadata/MManager.java, server/src/main/java/org/apache/iotdb/db/metadata/mnode/MNode.java
IoTDB support tagIndex in memory for tag based timeseries query.
Current tagIndex is based on CopyOnWriteArraySet and the time complexity to construct each set is O(n2).
An existing case is that the time for recovering tagIndex for 50000 timeseries with tags costs 5min or even more, based on working environment.
Replace CopyOnWriteArraySet usage with Collections.synchronizedSet(new HashSet()) and the time cost is only 2s on my laptop.
=> [To rel/0.12][IOTDB-1703] Fix MManager slow recover with tag

antlr/src/main/antlr4/org/apache/iotdb/db/qp/sql/SqlBase.g4, docs/UserGuide/System-Tools/Load-External-Tsfile.md, docs/zh/UserGuide/System-Tools/Load-External-Tsfile.md, server/src/main/java/org/apache/iotdb/db/engine/StorageEngine.java, server/src/main/java/org/apache/iotdb/db/engine/storagegroup/StorageGroupProcessor.java, server/src/main/java/org/apache/iotdb/db/qp/constant/SQLConstant.java, server/src/main/java/org/apache/iotdb/db/qp/executor/PlanExecutor.java, server/src/main/java/org/apache/iotdb/db/qp/logical/Operator.java, server/src/main/java/org/apache/iotdb/db/qp/logical/sys/UnloadFileOperator.java, server/src/main/java/org/apache/iotdb/db/qp/sql/IoTDBSqlVisitor.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBLoadExternalTsfileIT.java, server/src/test/java/org/apache/iotdb/db/qp/physical/PhysicalPlanTest.java
MOVE command is confusing, it should move some TsFile to the target directory, but it also unloads the TsFile from IoTDB and the data moved cannot be searched any more. So, i think UNLOAD is more suitable than MOVE.
=> [IOTDB-1650] Rename the sql command `move`

antlr/src/main/antlr4/org/apache/iotdb/db/qp/sql/SqlBase.g4, server/src/main/java/org/apache/iotdb/db/qp/executor/PlanExecutor.java, server/src/main/java/org/apache/iotdb/db/qp/logical/sys/CreateFunctionOperator.java, server/src/main/java/org/apache/iotdb/db/qp/logical/sys/ShowFunctionsOperator.java, server/src/main/java/org/apache/iotdb/db/qp/physical/sys/CreateFunctionPlan.java, server/src/main/java/org/apache/iotdb/db/qp/physical/sys/ShowFunctionsPlan.java, server/src/main/java/org/apache/iotdb/db/qp/sql/IoTDBSqlVisitor.java, server/src/main/java/org/apache/iotdb/db/query/udf/service/UDFRegistrationInformation.java, server/src/main/java/org/apache/iotdb/db/query/udf/service/UDFRegistrationService.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBUDFManagementIT.java, server/src/test/java/org/apache/iotdb/db/qp/physical/PhysicalPlanTest.java, testcontainer/src/test/java/org/apache/iotdb/db/sql/Cases.java
See JIRA https://issues.apache.org/jira/browse/IOTDB-1716. The **TEMPORARY** keyword will be removed.
=> [IOTDB-1716] Remove `TEMPORARY` keyword from `CREATE FUNCTION` statement

example/client-cpp-example/pom.xml
example/client-cpp-example/pom.xml:114
below codes are useless, so should remove them.
`<fileSet>
<sourceFile>${project.parent.basedir}/../client-cpp/target/client-cpp-${project.version}cpp${os.classifier}.zip</sourceFile>
<destinationFile>${project.build.directory}/client-cpp-${project.version}cpp${os.classifier}.zip</destinationFile>
</fileSet>`
=> [IOTDB-1721] client-cpp-example pom.xml copy useless client-cpp-xxx.zip

server/src/assembly/resources/conf/iotdb-engine.properties, server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java, server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfigCheck.java, server/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java, server/src/main/java/org/apache/iotdb/db/metadata/logfile/TagLogFile.java
When user creates a timeseries with tag or attribute, the tag/attribute record will be persisted to TagLogFile.
Currently, every TagLogFile writing operation will be force flushed to  disk, and too many disk I/O will cause poor performance.
A example case is that, one timeseries creation costs 48ms and around 8000 timeseries with tag creation costs 5-6min.
Set the force flush mode of FileChannel to false and execute force flush every N writing operations. N is an customized interval value that user can config.
=> [To rel/0.12][IOTDB-1727] Fix Slow creation of timeseries with tag

server/src/main/java/org/apache/iotdb/db/engine/compaction/level/LevelCompactionTsFileManagement.java, server/src/main/java/org/apache/iotdb/db/engine/storagegroup/StorageGroupProcessor.java, server/src/main/java/org/apache/iotdb/db/qp/executor/PlanExecutor.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBLoadExternalTsFileWithTimePartitionIT.java
change name for loading dir from recursionFileDir to loadDir
add an IT for testing following case:
enable time partition
load a dir which has some tsfiles with different timeseries
because of the unorder list in loading dir, maybe an "cannot find a suitable position" message will be found, and the loading process will stop.
this case may happened before #3795
To avoid this case, i add this IT
cherry pick from #3873
=> [IOTDB-1694] change name for loading dir and add an IT for loading dir

server/src/main/java/org/apache/iotdb/db/conf/IoTDBConstant.java, server/src/main/java/org/apache/iotdb/db/sync/receiver/transfer/SyncServiceImpl.java, server/src/main/java/org/apache/iotdb/db/sync/sender/transfer/SyncClient.java
change version checking rule for sync process
before:
- Check full version number between sender and receiver.
- Stop sync process if full version number does not match
Now:
- Check major version number between sender and receiver
- Stop sync process if major version number does not match
cherry pick from #3968
=> [IOTDB-1636]change sync version check to major version

server/src/main/java/org/apache/iotdb/db/engine/storagegroup/StorageGroupProcessor.java, server/src/test/java/org/apache/iotdb/db/integration/IoTDBLoadExternalTsfileIT.java
change rule for loading tsfile with the same establish time
e.g.
we want to load a tsfile in sequence list,
the previous tsfile has file name "a-b-c-d", the subsequence tsfile has file name "e-f-g-h".
and a(establish time of this file) is equal to e.
before:
we throw a exception with message "can not load TsFile because of can not find suitable location",
and stop loading process
now:
we load this file in unsequence folder.
and this update also solve the problem of "IoTDBLoadExternalTsfileIT.loadUnsequenceTsfileTest", it will be located in unsequence folder
cherry pick from #3983
=> [IOTDB-1578] Set unsequnce when loading TsFile with the same establish time

server/src/main/java/org/apache/iotdb/db/engine/memtable/WritableMemChunk.java, server/src/main/java/org/apache/iotdb/db/writelog/recover/LogReplayer.java, server/src/main/java/org/apache/iotdb/db/writelog/recover/TsFileRecoverPerformer.java, server/src/test/java/org/apache/iotdb/db/writelog/recover/LogReplayerTest.java, server/src/test/java/org/apache/iotdb/db/writelog/recover/SeqTsFileRecoverTest.java
Jira: https://issues.apache.org/jira/browse/IOTDB-1581
When recovering a incomplete TsFile:
- Call `recoverResourceFromWriter` to recover the resource information through the ChunkMetadata information in `RestorableTsFileIOWriter`
- Call the `redoLogs` method to write the data in one or more wal files corresponding to this file to a temporary Memtable and persist to this incomplete TsFile
The deletions ( Recorded in the .mods file ) are not considered in the two aspects, resulting in the recovery time range being wider than actual.
=> [IOTDB-1581] Consider deletions when recovering tsFileResource of incomplete tsfile

compile-tools/thrift/pom.xml
[IOTDB-1718]  compile-tools/thrift/pom.xml, make-cmake-executable use wrong phase
compile-tools/thrift/pom.xml:62
```xml
<plugin>
<groupId>org.codehaus.mojo</groupId>
<artifactId>exec-maven-plugin</artifactId>
<version>1.6.0</version>
<executions>
<execution>
<id>make-cmake-executable</id>
<phase>process-sources</phase> //here, this phase is too late, becasue "cmake-generate" begin to run cmake file in <phase>generate-sources</phase>
<goals>
<goal>exec</goal>
</goals>
<configuration>
<basedir>${cmake.root.dir}/bin</basedir>
<executable>${chmod.command}</executable>
<commandlineArgs>${chmod.command.para}</commandlineArgs>
</configuration>
</execution>
</executions>
</plugin>
```
"chmod +x cmake" should be run before running cmake.
=> [IOTDB-1718] correct the position of "chmod + cmake"

server/src/main/java/org/apache/iotdb/db/service/TSServiceImpl.java, server/src/test/java/org/apache/iotdb/db/integration/aggregation/IoTDBAggregationSmallDataIT.java, service-rpc/src/main/java/org/apache/iotdb/rpc/TSStatusCode.java, service-rpc/src/test/java/org/apache/iotdb/rpc/TSStatusCodeTest.java
related Jira link: https://issues.apache.org/jira/browse/IOTDB-1736
After modified, the log looks like below:
```java
WARN  [2021-09-27 00:01:43,591] [pool-8-IoTDB-RPC-Client-2] org.apache.iotdb.db.service.TSServiceImpl:2216 - Status code: INTERNAL_SERVER_ERROR(500), operation: "SELECT max_value(d0.s0),max_value(d1.s1),max_value(d0.s3) FROM root.vehicle". executeStatement failed
org.apache.iotdb.tsfile.exception.filter.StatisticsClassException: Binary statistics does not support: max
at org.apache.iotdb.tsfile.file.metadata.statistics.BinaryStatistics.getMaxValue(BinaryStatistics.java:88)
at org.apache.iotdb.tsfile.file.metadata.statistics.BinaryStatistics.getMaxValue(BinaryStatistics.java:33)
at org.apache.iotdb.db.query.aggregation.impl.MaxValueAggrResult.updateResultFromStatistics(MaxVa …
```
=> [IOTDB-1736] Error code is not printed in TSServiceImpl's log

site/src/main/.vuepress/config.js
Measurement-Template Doc has not been added to config.js which results in that it won't be presented in our official website.
Fix this by update config.js.
=> Fix template doc display

cluster/src/main/java/org/apache/iotdb/cluster/ClusterMain.java
The parameter of '-r' is already in _removeNode.sh_
=> fix usage of removeNode

server/src/main/java/org/apache/iotdb/db/metadata/MetaUtils.java, server/src/test/java/org/apache/iotdb/db/metadata/MetaUtilsTest.java
When parsing strings, like root.sg.d. , to partialPath, an illegalPathException should be thrown rather than parse it to {"root", "sg", "d"}.
=> [To rel/0.12][IOTDB-1785] Fix Illegal String ending with . being parsed to PartialPath

server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java, server/src/main/java/org/apache/iotdb/db/sync/receiver/transfer/SyncServiceImpl.java, server/src/main/java/org/apache/iotdb/db/sync/sender/transfer/SyncClient.java
recovery bug in sender:
recovery is invalid in sender.
some tsfiles maybe re-sender to receiver.
some tsfiles maybe be deleted on receiver twice.
now make the recovery valid in sender
reconnection bug in sender and receiver:
reconnection is invalid both in sender and receiver
maybe cause the receiver delete some tsfile which should not be deleted, because the log in receiver is wrong when time partition and vg is enable.
maybe cause the sender can not connect to the receiver after the reconnection, because some info in receiver is missing after reconnection.
now the reconnect can be set correctly.
remove some debug info in receiver
cherry pick from #4217
=> [IOTDB-1877] Fix Sync recovery and reconnection bugs in both sender and receiver

server/src/main/java/org/apache/iotdb/db/qp/physical/PhysicalPlan.java, server/src/main/java/org/apache/iotdb/db/qp/utils/EmptyOutputStream.java, server/src/main/java/org/apache/iotdb/db/writelog/node/ExclusiveWriteLogNode.java, server/src/test/java/org/apache/iotdb/db/writelog/WriteLogNodeTest.java
* Print the actual size of plan when it exceeds the wal_buffer_size
* Use `PhysicalPlan.serialize(DataOutputStream stream)`  to get actual size of plan after serialization. 
* Print infomation in IOException message
* Add some test in `testOverSizedWAL` to verify the actual size of plan
* If wal_buffer_size is less than actual size, it would throw IOException.
* If wal_buffer_size is more than or equal to actual size, it would not throw IOException.
=> [IOTDB-1609] Print the actual size of plan when it exceeds the wal_buffer_size

session/src/main/java/org/apache/iotdb/session/pool/SessionPool.java
For more detail, please see ISSUE-4293.
Root cause: InterruptedException is not properly handled in synchronized wait().
=> [ISSUE-4293] SessionPool: InterruptedException is not properly handled in synchronized wait()

session/src/main/java/org/apache/iotdb/session/pool/SessionPool.java
For more detail, please see [ISSUE-4293](https://github.com/apache/iotdb/issues/4293).
Root cause: InterruptedException is not properly handled in synchronized wait().
=> [To rel/0.12][ISSUE-4293] SessionPool: InterruptedException is not properly handled in synchronized wait()

tsfile/src/main/java/org/apache/iotdb/tsfile/file/metadata/AlignedChunkMetadata.java, tsfile/src/main/java/org/apache/iotdb/tsfile/file/metadata/ChunkMetadata.java, tsfile/src/main/java/org/apache/iotdb/tsfile/file/metadata/IChunkMetadata.java, tsfile/src/main/java/org/apache/iotdb/tsfile/file/metadata/MetadataIndexConstructor.java, tsfile/src/main/java/org/apache/iotdb/tsfile/file/metadata/TimeseriesMetadata.java, tsfile/src/main/java/org/apache/iotdb/tsfile/read/TsFileSequenceReader.java, tsfile/src/main/java/org/apache/iotdb/tsfile/utils/ReadWriteIOUtils.java, tsfile/src/main/java/org/apache/iotdb/tsfile/write/writer/TsFileIOWriter.java, tsfile/src/test/java/org/apache/iotdb/tsfile/file/metadata/TimeseriesMetadataTest.java, tsfile/src/test/java/org/apache/iotdb/tsfile/read/TimeSeriesMetadataReadTest.java, tsfile/src/test/java/org/apache/iotdb/tsfile/write/MetadataIndexConstructorTest.java, tsfile/src/test/java/org/apache/iotdb/tsfile/write/TsFileIOWriterTest.java
TsFile metadata index need to support aligned timeseries and non-aligned timeseries.
Related PR: PR [#3081](https://github.com/apache/iotdb/pull/3081/files).
=> [IOTDB-1910] Support aligned timeseries in TsFile metadata index

hadoop/src/main/java/org/apache/iotdb/hadoop/fileSystem/HDFSInput.java, hadoop/src/test/java/org/apache/iotdb/hadoop/tsfile/TSFHadoopTest.java, hive-connector/pom.xml, hive-connector/src/test/java/org/apache/iotdb/hive/TSFHiveInputFormatTest.java, hive-connector/src/test/java/org/apache/iotdb/hive/TSFHiveRecordReaderTest.java, server/src/main/java/org/apache/iotdb/db/engine/cache/TimeSeriesMetadataCache.java, server/src/test/java/org/apache/iotdb/db/engine/cache/ChunkCacheTest.java, server/src/test/java/org/apache/iotdb/db/engine/compaction/inner/InnerCompactionCacheTest.java, server/src/test/java/org/apache/iotdb/db/tools/TsFileSketchToolTest.java, tsfile/src/main/java/org/apache/iotdb/tsfile/file/metadata/ChunkMetadata.java, tsfile/src/main/java/org/apache/iotdb/tsfile/fileSystem/fileOutputFactory/LocalFSOutputFactory.java, tsfile/src/main/java/org/apache/iotdb/tsfile/read/TsFileSequenceReader.java, tsfile/src/main/java/org/apache/iotdb/tsfile/read/reader/LocalTsFileInput.java, tsfile/src/main/java/org/apache/iotdb/tsfile/read/reader/TsFileInput.java, tsfile/src/main/java/org/apache/iotdb/tsfile/utils/FilePathUtils.java
In current IoTDB, after compaction finished, it will clear all the query cache, because the old file and the new file share the same key in query cache and there is no way to remove the exact old file entry in query cache.
However, we can add the compaction version into the cache entry key so that the new file generated by compaction will has a new entry instead of sharing the same key as the old file. In this way, we can avoid clearing all query cache after each compaction.
=> Add compaction version in cache key

server/src/main/java/org/apache/iotdb/db/engine/modification/ModificationFile.java, server/src/main/java/org/apache/iotdb/db/engine/modification/io/LocalTextModificationAccessor.java, server/src/main/java/org/apache/iotdb/db/engine/modification/io/ModificationReader.java, server/src/main/java/org/apache/iotdb/db/engine/modification/io/ModificationWriter.java, server/src/main/java/org/apache/iotdb/db/engine/modification/utils/TracedBufferedReader.java, server/src/main/java/org/apache/iotdb/db/engine/storagegroup/StorageGroupProcessor.java, server/src/test/java/org/apache/iotdb/db/engine/modification/io/LocalTextModificationAccessorTest.java
When we write a Deletion to a modification file, the Deletion may crash because of power-off. So, the modifications after this broken Deletion will be incorrect, so we need to truncate them to make the mods file correct.
To trace the read position, i implement TracedBufferedReader based on java.io.BufferedReader by modifying the fill() method.
=> [IOTDB-1613] Recover mods file if a delete write modification failed

pom.xml
=> [IOTDB-1859] CI fails on coveralls caused by openapi generated files

hive-connector/pom.xml
Reverts apache/iotdb#4272 to fix hive-connector issue
=> [To rel/0.12] Revert "Bump jackson-xc from 1.9.13 to 1.9.14-MULE-002"

RELEASE_NOTES.md, server/src/main/java/org/apache/iotdb/db/utils/SerializeUtils.java, server/src/test/java/org/apache/iotdb/db/utils/SerializeUtilsTest.java, tsfile/src/main/java/org/apache/iotdb/tsfile/read/common/BatchData.java, tsfile/src/main/java/org/apache/iotdb/tsfile/read/common/DescReadWriteBatchData.java
A cherry-pick of #4357 
JIRA: https://issues.apache.org/jira/browse/IOTDB-1983
As 0.12 doesn't support Vector type, I remove those codes.
=> [To rel/0.12][IOTDB-1983] Fix DescReadWriteBatchData serializing bug

RELEASE_NOTES.md, cluster/src/main/java/org/apache/iotdb/cluster/query/fill/ClusterFillExecutor.java, server/src/main/java/org/apache/iotdb/db/query/dataset/RawQueryDataSetWithValueFilter.java, server/src/main/java/org/apache/iotdb/db/query/executor/AggregationExecutor.java
The cherry-pick of #4358 
JIRA: https://issues.apache.org/jira/browse/IOTDB-1990
=> [To rel/0.12][IOTDB-1990] Fix uncheck null result by calling IReaderByTimestamp.getValuesInTimestamps()

docs/Development/ContributeGuide.md
修复了/docs/deployment/ContributeGuide.md中‘Get started quickly’路径不正确的问题。
=> [ISSUE-4314] [docs] fix the Url of 'Get started quickly' 

server/src/main/java/org/apache/iotdb/db/sync/conf/SyncConstant.java, server/src/main/java/org/apache/iotdb/db/sync/receiver/transfer/SyncServiceImpl.java, server/src/main/java/org/apache/iotdb/db/sync/sender/transfer/SyncClient.java, server/src/test/java/org/apache/iotdb/db/sync/sender/transfer/SyncClientTest.java
sync sender use "_" to replace File.separator to make sync between different os correct.
such as:
sender(windows): root.sg\0\0\1.tsfile -> root.sg_0_0_1.tsfile
receiver(linux): root.sg_0_0_1.tsfile -> root.sg/0/0/1.tsfile
but some sg name contains "_", so the parse for receiver is not correct.
such as:
sg name: root.test.g_7
receiver parse: root.test.g_7_0_0_1.tsfile -> root.test.g/7/0/0/1.tsfile
So the receiver can not got correct sg name from folder path
now, i change the chart to replace File.separator to "!", a chart that is not exist in sg's name and a tsfile'name according to anltr4.
=> [To rel/0.12][IOTDB-1985]Fix Sync Error in parse sg path between different os

cluster/src/main/java/org/apache/iotdb/cluster/query/LocalQueryExecutor.java, server/src/main/java/org/apache/iotdb/db/query/aggregation/AggregateResult.java, server/src/main/java/org/apache/iotdb/db/query/aggregation/impl/FirstValueAggrResult.java, server/src/main/java/org/apache/iotdb/db/query/aggregation/impl/FirstValueDescAggrResult.java, server/src/test/java/org/apache/iotdb/db/query/aggregation/DescAggregateResultTest.java
See JIRA https://issues.apache.org/jira/browse/IOTDB-1997
The following bugs are fixed:
1. LocalQueryExecutor passes `AggregationResult` list into an ascending and decending one to create proper reader with the `AggregationResult.isAscending()`.
2. Fix the bug of `FirstValueDescAggrResult` implementation.
3. Add java doc and unit test cases.
=> [IOTDB-1997] Fix bug of descending aggregation query

server/src/main/java/org/apache/iotdb/db/query/udf/builtin/UDTFCast.java
In the initial assignment of long or Long, uppercase L must be used instead of lowercase l. Lowercase is easy to confuse with the number 1 and cause misunderstandings.
=> [IOTDB-2004] change initial assignment of Long to uppercase L

server/src/assembly/resources/conf/iotdb-engine.properties, server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java, server/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java, server/src/main/java/org/apache/iotdb/db/engine/cache/BloomFilterCache.java, server/src/main/java/org/apache/iotdb/db/engine/cache/CacheHitRatioMonitor.java, server/src/main/java/org/apache/iotdb/db/engine/cache/CacheHitRatioMonitorMXBean.java, server/src/main/java/org/apache/iotdb/db/engine/cache/TimeSeriesMetadataCache.java, server/src/test/java/org/apache/iotdb/db/engine/cache/BloomFilterCacheTest.java, server/src/test/java/org/apache/iotdb/db/utils/EnvironmentUtils.java, spark-iotdb-connector/src/test/scala/org/apache/iotdb/spark/db/EnvironmentUtils.java, tsfile/src/main/java/org/apache/iotdb/tsfile/utils/BloomFilter.java
* Add `BloomFilterCache` to cache bloom filter instead of read from TsFile directly
* Add `BloomFilterCacheTest`
* Update `iotdb-engine.properties` about allocated memory for BloomFilterCache 
[weekly test result](http://ise.thss.tsinghua.edu.cn/confluence/pages/viewpage.action?pageId=64526429)
[experiment result](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=195726609)
=> [IOTDB-1950] Add Bloom Filter cache for query

cluster/src/main/java/org/apache/iotdb/cluster/query/LocalQueryExecutor.java, cluster/src/main/java/org/apache/iotdb/cluster/query/groupby/RemoteGroupByExecutor.java, cluster/src/main/java/org/apache/iotdb/cluster/query/last/ClusterLastQueryExecutor.java, server/src/main/java/org/apache/iotdb/db/query/dataset/groupby/GroupByFillDataSet.java, server/src/main/java/org/apache/iotdb/db/query/executor/LastQueryExecutor.java, server/src/main/java/org/apache/iotdb/db/query/executor/QueryRouter.java
This is the cherry-pick of #4384 
JIRA: https://issues.apache.org/jira/browse/IOTDB-2008
As the GroupByFillDataSet is different with master the branch, the fix is a little different.
=> [To rel/0.12][IOTDB-2008] Fix null result bug of GROUP BY FILL query

tsfile/src/main/java/org/apache/iotdb/tsfile/read/filter/GroupByMonthFilter.java, tsfile/src/main/java/org/apache/iotdb/tsfile/read/filter/factory/FilterFactory.java, tsfile/src/main/java/org/apache/iotdb/tsfile/read/filter/factory/FilterSerializeId.java, tsfile/src/main/java/org/apache/iotdb/tsfile/read/filter/operator/In.java, tsfile/src/test/java/org/apache/iotdb/tsfile/read/filter/FilterSerializeTest.java
See JIRA: https://issues.apache.org/jira/browse/IOTDB-2023
The following bugs have been fixed:
1. `GroupByMonthFilter`: It inherits `GroupByMonth` filter but doesn't override `getSerializeId()`, which returns `FilterSerializeId.GROUP_BY` and causes the deserializing instance being `GroupByFilter`.
2. `In`: Not supported in `FilterFactory`.
3. `In`: In the serializing and  deserializing method, we should use `ReadWriteUtils.write()` and `ReadWriteUtils.readInt()`. As `buffer.get()` and `stream.write()` handle only 1 byte.
=> [IOTDB-2023] Fix serializing and deserializing bugs of Filters

cli/src/assembly/resources/sbin/start-cli.sh
Co-authored-by: wangjunqing <wangjunqing.wjq@alibaba-inc.com>
cp #3336
=> [To rel/0.12][ISSUE-3335] Fix the bug of start-cli.sh -e mode can't work with wild card *

server/src/main/java/org/apache/iotdb/db/query/executor/AggregationExecutor.java, server/src/main/java/org/apache/iotdb/db/query/reader/chunk/MemAlignedPageReader.java, server/src/main/java/org/apache/iotdb/db/query/reader/series/AlignedSeriesAggregateReader.java, server/src/main/java/org/apache/iotdb/db/query/reader/series/SeriesReader.java, server/src/main/java/org/apache/iotdb/db/query/reader/series/VectorSeriesAggregateReader.java, tsfile/src/main/java/org/apache/iotdb/tsfile/file/metadata/AlignedChunkMetadata.java, tsfile/src/main/java/org/apache/iotdb/tsfile/file/metadata/AlignedTimeSeriesMetadata.java, tsfile/src/main/java/org/apache/iotdb/tsfile/read/reader/IAlignedPageReader.java, tsfile/src/main/java/org/apache/iotdb/tsfile/read/reader/page/AlignedPageReader.java
In aggregation, we need to judge whether we can use the current file/chunk/page statistics for calculations. For aligned timeseries, we should use the statistics of the time column for judgment.
=> Use statistics of time column in canUseCurrent*Statistics() method in AlignedSeriesAggregateReader

server/src/main/java/org/apache/iotdb/db/query/dataset/RawQueryDataSetWithoutValueFilter.java, tsfile/src/main/java/org/apache/iotdb/tsfile/read/common/ExceptionBatchData.java
In an IoTDB Instance, the query main thread is blocking. We could see the queryId using show query proceslist. However, we couldn't see the sub query thread of the blocked query in the jstack file.
This may be due to that the sub-thread is dead because some error（not catched by Exception）
=> [To rel/0.12] [IOTDB-2058] Query is blocked without sub-query-threads exist

server/src/main/java/org/apache/iotdb/db/qp/physical/PhysicalPlan.java, server/src/main/java/org/apache/iotdb/db/writelog/node/ExclusiveWriteLogNode.java, server/src/test/java/org/apache/iotdb/db/writelog/WriteLogNodeTest.java
There are too many  'WAL BufferOverflow' in the log, ignore it until it reaches specific amount.
=> [To rel/0.12][IOTDB-2027] Ignore too many WAL BufferOverflow log

server/src/main/java/org/apache/iotdb/db/qp/physical/PhysicalPlan.java, server/src/main/java/org/apache/iotdb/db/writelog/node/ExclusiveWriteLogNode.java, server/src/test/java/org/apache/iotdb/db/writelog/WriteLogNodeTest.java
There are too many 'WAL BufferOverflow' in the log, ignore it until it reaches specific amount.
=> [IOTDB-2027] Ignore too many WAL BufferOverflow log

server/src/main/java/org/apache/iotdb/db/query/dataset/RawQueryDataSetWithoutValueFilter.java, tsfile/src/main/java/org/apache/iotdb/tsfile/read/common/ExceptionBatchData.java
In an IoTDB Instance, the query main thread is blocking. We could see the queryId using show query proceslist. However, we couldn't see the sub query thread of the blocked query in the jstack file.
This may be due to that the sub-thread is dead because some error（not catched by Exception）
=> [IOTDB-2058] Query is blocked without sub-query-threads exist

server/src/main/java/org/apache/iotdb/db/exception/query/QueryProcessException.java, server/src/main/java/org/apache/iotdb/db/query/udf/core/executor/UDTFExecutor.java, server/src/main/java/org/apache/iotdb/db/query/udf/core/layer/SingleInputColumnSingleReferenceIntermediateLayer.java
See https://issues.apache.org/jira/browse/IOTDB-2062.
The variable tvList in SingleInputColumnSingleReferenceIntermediateLayer#constructRowSlidingSizeWindowReader() and SingleInputColumnSingleReferenceIntermediateLayer#constructRowSlidingTimeWindowReader() will materialize all iteration data until the end of the query, which may trigger useless memory control actions (resulting in meaningless file IO).
It's obviously a bug and results in low query throughput when query data is large.
=> [IOTDB-2062] UDF Framework: Potential Memory Leak in `SingleInputColumnSingleReferenceIntermediateLayer`

server/src/main/java/org/apache/iotdb/db/query/control/FileReaderManager.java, server/src/test/java/org/apache/iotdb/db/engine/cache/ChunkCacheTest.java, server/src/test/java/org/apache/iotdb/db/engine/compaction/cross/MergeTest.java, server/src/test/java/org/apache/iotdb/db/engine/compaction/inner/InnerCompactionTest.java, server/src/test/java/org/apache/iotdb/db/engine/compaction/inner/sizetiered/SizeTieredCompactionRecoverTest.java, server/src/test/java/org/apache/iotdb/db/engine/compaction/inner/sizetiered/SizeTieredCompactionTest.java, server/src/test/java/org/apache/iotdb/db/engine/compaction/utils/CompactionClearUtils.java, server/src/test/java/org/apache/iotdb/db/query/control/FileReaderManagerTest.java, server/src/test/java/org/apache/iotdb/db/query/reader/series/SeriesReaderTestUtil.java, server/src/test/java/org/apache/iotdb/db/rescon/ResourceManagerTest.java
In FileReaderManager, we cached all opened TsFileSequenceReader and maintain an usage count for each reader.
We register a timed thread (cacheFileReaderClearPeriod=100s) to check if a reader is no longer used.
We could check and release the reader when we decrease its usage count in endQuery.
=> [IOTDB-2065] TsFileSequenceReader will be cached for 100s even no longer used

server/src/main/java/org/apache/iotdb/db/query/control/FileReaderManager.java, server/src/test/java/org/apache/iotdb/db/engine/cache/ChunkCacheTest.java, server/src/test/java/org/apache/iotdb/db/engine/compaction/LevelCompactionRecoverTest.java, server/src/test/java/org/apache/iotdb/db/engine/compaction/LevelCompactionRestoreTest.java, server/src/test/java/org/apache/iotdb/db/engine/compaction/LevelCompactionTest.java, server/src/test/java/org/apache/iotdb/db/engine/merge/MergeTest.java, server/src/test/java/org/apache/iotdb/db/query/control/FileReaderManagerTest.java, server/src/test/java/org/apache/iotdb/db/query/reader/series/SeriesReaderTestUtil.java
In FileReaderManager, we cached all opened TsFileSequenceReader and maintain an usage count for each reader.
We register a timed thread (cacheFileReaderClearPeriod=100s) to check if a reader is no longer used.
We could check and release the reader when we decrease its usage count in endQuery.
=> [To rel/0.12] [IOTDB-2065] release TsFileSequenceReader soon when it is no longer used

tsfile/src/main/java/org/apache/iotdb/tsfile/compress/ICompressor.java, tsfile/src/main/java/org/apache/iotdb/tsfile/exception/compress/GZIPCompressOverflowException.java, tsfile/src/main/java/org/apache/iotdb/tsfile/write/page/PageWriter.java, tsfile/src/main/java/org/apache/iotdb/tsfile/write/page/TimePageWriter.java, tsfile/src/main/java/org/apache/iotdb/tsfile/write/page/ValuePageWriter.java, tsfile/src/test/java/org/apache/iotdb/tsfile/compress/GZIPTest.java, tsfile/src/test/java/org/apache/iotdb/tsfile/compress/LZ4Test.java, tsfile/src/test/java/org/apache/iotdb/tsfile/compress/SnappyTest.java
The return value of GZIPCompressor.getMaxBytesForCompression method is ambiguous, so i add GZIPCompressOverflowException and  a new compress interface.
=> [IOTDB-2068] GZIP compressor meets ArrayIndexOutOfBoundsException

tsfile/src/main/java/org/apache/iotdb/tsfile/read/TsFileSequenceReader.java
I use `TsFileReadWriteTest` to do a simple performance test, which writes about 50M data.
Unit: ms
| Num | Before | After |
| 1 | 1519 | 1526 |
| 2 | 1533 | 1553 |
| 3 | 1259 |     1262 |
| 4 | 1991 | 1969 |
| 5 | 1615 | 1539 |
As you can see, the performance is not influenced.
=> [IOTDB-2061] Read data in batches to limit max IO

tsfile/src/main/java/org/apache/iotdb/tsfile/compress/ICompressor.java, tsfile/src/main/java/org/apache/iotdb/tsfile/exception/compress/GZIPCompressOverflowException.java, tsfile/src/main/java/org/apache/iotdb/tsfile/write/page/PageWriter.java, tsfile/src/test/java/org/apache/iotdb/tsfile/compress/GZIPTest.java, tsfile/src/test/java/org/apache/iotdb/tsfile/compress/LZ4Test.java, tsfile/src/test/java/org/apache/iotdb/tsfile/compress/SnappyTest.java
The return value of GZIPCompressor.getMaxBytesForCompression method is ambiguous, so i add GZIPCompressOverflowException and a new compress interface.
=> [To rel/0.12][IOTDB-2068] GZIP compressor meets ArrayIndexOutOfBoundsException

metrics/dropwizard-metrics/src/main/java/org/apache/iotdb/metrics/dropwizard/DropwizardMetricManager.java, metrics/dropwizard-metrics/src/main/java/org/apache/iotdb/metrics/dropwizard/type/DropwizardAutoGauge.java, metrics/dropwizard-metrics/src/test/java/org/apache/iotdb/metrics/dropwizard/DropwizardMetricManagerTest.java, metrics/interface/src/main/java/org/apache/iotdb/metrics/MetricManager.java, metrics/interface/src/main/java/org/apache/iotdb/metrics/impl/DoNothingGauge.java, metrics/interface/src/main/java/org/apache/iotdb/metrics/impl/DoNothingMetricManager.java, metrics/interface/src/main/java/org/apache/iotdb/metrics/type/Gauge.java, metrics/micrometer-metrics/src/main/java/org/apache/iotdb/metrics/micrometer/MicrometerMetricManager.java, metrics/micrometer-metrics/src/main/java/org/apache/iotdb/metrics/micrometer/type/MicrometerAutoGauge.java, metrics/micrometer-metrics/src/main/java/org/apache/iotdb/metrics/micrometer/type/MicrometerGauge.java, metrics/micrometer-metrics/src/test/java/org/apache/iotdb/metrics/micrometer/MicrometerMetricManagerTest.java
I did two things in this pr
1. Add a new gauge implement
In some instance, say, we want to monitor a list or a queue's size, it's not convenient and has low performance to set the value every time the list or queue's size changed.
The new gauge implement is designed for this instance.
2. Add incr and decr method for gauge interface.
In some cases, we may need to get the current value, add or decrease , then put it back. 
Since the current `setValue` method cannot guarantee the atomicity of this operation, I added incr and decr method to the gauge interface.
related jira : https://issues.apache.org/jira/browse/IOTDB-2017
=> [IoTDB-2017][metric] Add a new gauge implement

server/src/main/java/org/apache/iotdb/db/engine/compaction/CompactionTaskComparator.java, server/src/test/java/org/apache/iotdb/db/engine/compaction/CompactionTaskComparatorTest.java
We specify that when two compaction tasks have the same number of seqFiles, the task with more unseqFiles has higher priority. But the current CompactionTaskComparator is written backwards, and part of the CI should be modified.
=> [IOTDB-2098] Fix priority of cross space task

cluster/src/main/java/org/apache/iotdb/cluster/query/groupby/ClusterGroupByVFilterDataSet.java, integration/src/test/java/org/apache/iotdb/db/integration/aligned/AlignedWriteUtil.java, integration/src/test/java/org/apache/iotdb/db/integration/aligned/IoTDBGroupByQueryWithValueFilter2IT.java, integration/src/test/java/org/apache/iotdb/db/integration/aligned/IoTDBGroupByQueryWithValueFilterIT.java, integration/src/test/java/org/apache/iotdb/db/integration/aligned/IoTDBGroupByQueryWithValueFilterWithDeletion2IT.java, integration/src/test/java/org/apache/iotdb/db/integration/aligned/IoTDBGroupByQueryWithValueFilterWithDeletionIT.java, server/src/main/java/org/apache/iotdb/db/query/dataset/groupby/GroupByEngineDataSet.java, server/src/main/java/org/apache/iotdb/db/query/dataset/groupby/GroupByFillEngineDataSet.java, server/src/main/java/org/apache/iotdb/db/query/dataset/groupby/GroupByWithValueFilterDataSet.java, server/src/main/java/org/apache/iotdb/db/query/dataset/groupby/GroupByWithoutValueFilterDataSet.java, server/src/main/java/org/apache/iotdb/db/query/executor/AggregationExecutor.java, server/src/main/java/org/apache/iotdb/db/utils/AlignedValueIterator.java, server/src/main/java/org/apache/iotdb/db/utils/QueryUtils.java
Aligned timeseries support group by query with value filter for standalone mode.
=> [IOTDB-1773] Aligned timeseries support group by query with value filter for standalone mode

server/src/main/java/org/apache/iotdb/db/query/dataset/RawQueryDataSetWithoutValueFilter.java
If we use limit 1 while select ** from root, the sub thread is not noticed that we only need one result, so it works until the blockingQueue is filled, which wastes lots of resource.
Therefore, we push down limit to ReadTask in RawDataSetWithoutValueFilter.
=> [IOTDB-2102] Push down limit to ReadTask in RawDataSetWithoutValueFilter

cluster/src/main/java/org/apache/iotdb/cluster/client/sync/SyncClientAdaptor.java, cluster/src/main/java/org/apache/iotdb/cluster/query/last/ClusterLastQueryExecutor.java, cluster/src/test/java/org/apache/iotdb/cluster/client/sync/SyncClientAdaptorTest.java, cluster/src/test/java/org/apache/iotdb/cluster/common/TestAsyncDataClient.java, cluster/src/test/java/org/apache/iotdb/cluster/query/last/ClusterLastQueryExecutorTest.java
cherry pick https://github.com/apache/iotdb/pull/4539
After enable_last_cache is disabled, the filter criteria are not pushed to the remote node. As a result, the query result is incorrect.
5 node , 3 rep in cluster
enable_last_cache = false
insert into root.sg1.d1(time,s1) values(1,1);
flush;
select last s1 from root.sg1.d1 where time > 1;
the query result is incorrect.
reason :
the filter criteria are not pushed to the remote node. As a result, the query result is incorrect.
=> [To rel/0.12][IOTDB-2124] the filtering condition does not take efffect for last query in cluster

server/src/main/java/org/apache/iotdb/db/engine/storagegroup/StorageGroupProcessor.java, server/src/main/java/org/apache/iotdb/db/engine/storagegroup/TsFileProcessor.java, server/src/main/java/org/apache/iotdb/db/engine/storagegroup/TsFileResource.java, server/src/main/java/org/apache/iotdb/db/writelog/recover/TsFileRecoverPerformer.java, server/src/test/java/org/apache/iotdb/db/writelog/recover/RecoverResourceFromReaderTest.java
Two changes to accelerate recovery process.
1. Change the sequence of endTsFile and serialize TsFile resource. Ending Tsfile first and then serializing TsFileResource.
2. When recovering, if a TsFileResource found, do not check the TsFile.
The reason is if we find a TsFileResource, it means the TsFile is ended. Skipping check the TsFile can save a lot of time of recovery process.
<hr>
This PR has:
<hr>
=> [IOTDB-2123] Accelerate recovery process

cluster/src/test/java/org/apache/iotdb/cluster/query/reader/ClusterReaderFactoryTest.java, server/src/main/java/org/apache/iotdb/db/query/control/QueryResourceManager.java
Each tsFile only increases the reference count once in a query process.
=> [To rel/0.12] Each tsFile only increases the reference count once in a query process

cluster/src/main/java/org/apache/iotdb/cluster/ClusterMain.java, docs/UserGuide/Cluster/Cluster-Setup-Example.md, docs/zh/UserGuide/Cluster/Cluster-Setup-Example.md
Users only set internal ip in iotdb-cluster.properties, and they often forget to set the rpc_address (public ip) in iotdb-engine.properties. So the rpc address is the default value(0.0.0.0). Session will cache the 0.0.0.0 endpoint when an insertPlan is redirected. 
We want internal ip as private ip and rpc_address as public ip. So if the rpc_address is not set, set it the same with internal ip.
=> [To rel/0.12] Fix connection refused using session when users forget to set client ip

client-py/iotdb/utils/IoTDBConstants.py
=> [IOTDB-2152] PyClient: Override __eq__() of TSDataType, TSEncoding and Compressor to avoid unexpected comparation behaviour

client-py/iotdb/utils/IoTDBConstants.py
=> [To rel/0.12][IOTDB-2152] PyClient: Override __eq__() of TSDataType, TSEncoding and Compressor to avoid unexpected comparation behaviour

code-coverage/pom.xml, server/src/main/java/org/apache/iotdb/db/query/dataset/RawQueryDataSetWithoutValueFilter.java, site/pom.xml
Currently, if the sub thread throw an Error like `OutOfMemoryError`, the main thread won't exit, it will blocked on the `take` operation of `BlockingQueue`.
Anytime we got the `ExceptionBatchData`, we should rethrow it.
=> [To rel/0.12] Rethrow other exceptions in query main thread

server/src/main/java/org/apache/iotdb/db/query/dataset/RawQueryDataSetWithoutValueFilter.java
Currently, if the sub thread throw an Error like `OutOfMemoryError`, the main thread won't exit, it will blocked on the `take` operation of `BlockingQueue`.
Anytime we got the `ExceptionBatchData`, we should rethrow it.
=> Rethrow other exceptions in query main thread

server/src/main/java/org/apache/iotdb/db/engine/merge/manage/MergeResource.java, server/src/main/java/org/apache/iotdb/db/engine/merge/task/MergeMultiChunkTask.java
reason:
The cluster version initializes the CMManager. During merge, the MManager is used. However, the MManager is not initialized.
=> [To rel/0.12][IOTDB-2140] merge throw NullPointerException

integration/src/test/java/org/apache/iotdb/db/integration/IoTDBTtlIT.java
See JIRA: https://issues.apache.org/jira/browse/IOTDB-2168
We should wait other nodes applied the log and then execute inserting.
=> [IOTDB-2168] Fix IoTDBTtlIT

server/src/main/java/org/apache/iotdb/db/engine/compaction/cross/inplace/manage/CrossSpaceMergeResource.java, server/src/main/java/org/apache/iotdb/db/engine/compaction/cross/inplace/task/CrossSpaceMergeTask.java, server/src/main/java/org/apache/iotdb/db/engine/compaction/cross/inplace/task/MergeMultiChunkTask.java, server/src/main/java/org/apache/iotdb/db/metadata/MManager.java
When we take all `partialPath`, we may have too much. Therefore, obtain the path by device first.
In a later commit, we might simplify `RecoveryMergeTask`
=> [IOTDB-2161] Get timeseries by device in merge process

server/src/main/java/org/apache/iotdb/db/engine/compaction/inner/InnerSpaceCompactionExceptionHandler.java, tsfile/src/main/java/org/apache/iotdb/tsfile/utils/TsFileUtils.java, tsfile/src/test/java/org/apache/iotdb/tsfile/utils/TsFileUtilsTest.java
Issue-2154
Add TsFileUtils.isTsFileComplete Method to check whether a TsFile is complete
Currently, we use RestorableTsFileIOWriter to check whether a TsFile is complete. However it will scan the TsFile and return truncate size if it is broken. We also need to remember to close the writer after doing the check. 
Sometimes we just need a simple method to determine whether a TsFile is complete, (by complete, only if the head magic and tail magic string exists.)
In this PR, I extract the code of deciding completeness from RestorableTsFileIOWriter and uses TsFileSequenceReader.isComplete internally
=> [IOTDB-2154]add TsFileUtils.isTsFileComplete

integration/src/main/java/org/apache/iotdb/integration/env/ClusterEnvBase.java, integration/src/main/java/org/apache/iotdb/integration/env/ClusterEnvConfig.java, integration/src/main/java/org/apache/iotdb/integration/env/ClusterNode.java, integration/src/main/java/org/apache/iotdb/itbase/env/BaseConfig.java, integration/src/test/java/org/apache/iotdb/db/integration/IoTDBPartialInsertionIT.java, integration/src/test/java/org/apache/iotdb/db/integration/IoTDBSimpleQueryIT.java, integration/src/test/java/org/apache/iotdb/db/integration/env/StandaloneEnvConfig.java
Since the configuration change needs to be done before the cluster is started, for better cluster testing, a separate test case file is split.
=> [IOTDB-2172] Refactor for IoTDBSimpleQueryIT

integration/src/test/java/org/apache/iotdb/db/integration/aggregation/IoTDBAggregationByLevelIT.java, integration/src/test/java/org/apache/iotdb/db/integration/aligned/IoTDBAggregationGroupByLevelIT.java, server/src/main/java/org/apache/iotdb/db/engine/memtable/AbstractMemTable.java, server/src/main/java/org/apache/iotdb/db/query/expression/unary/FunctionExpression.java
Only support this before:
Implement this now:
=> [IOTDB-2196] Support double star ** in group by level

integration/src/test/java/org/apache/iotdb/session/IoTDBSessionSimpleIT.java, session/src/main/java/org/apache/iotdb/session/Session.java
For some methods in Session, we have a haveSorted parameter to indicate whether multi records are in ascending order of time.
This parameter is useless, we could check this by ourselves.
(1) checkSorted
(2) if not sorted, we could sort it.
1. Delete `haveSorted` param in `insertRecordsOfOneDevice, insertAlignedRecordsOfOneDevice`. Since currently there are two overloaded version of `insertRecordsOfOneDevice, insertAlignedRecordsOfOneDevice` and they only differ in `haveSorted` param, so I merged two overloaded version into a single interface
2. Change the caller usages of above methods
=> [IOTDB-2043] refactor: remove haveSorted param from Session
