- server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/utils/MultiTsFileDeviceIterator.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/utils/MultiTsFileDeviceIteratorTest.java
- tsfile/src/main/java/org/apache/iotdb/tsfile/read/TsFileDeviceIterator.java
After the nonAligned device is deleted, an aligned device with the same name is created, and it will be compacted into the nonAligned device after compaction.
Similarly, after the aligned device is deleted, an nonAligned device with the same name is created, and it will be compacted into the aligned device after compaction.
**Solution**
Get the device and its alignment properties from the newest to the oldest file, and the device that has been obtained will no longer be obtained.
> [To rel/1.0][IOTDB-4684]Devices with the same name but different alignment properties are compacted into the wrong alignment property

- server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/exception/CompactionExceptionHandler.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/recover/CompactionRecoverTask.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/task/CrossSpaceCompactionTask.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/task/InnerSpaceCompactionTask.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/utils/CompactionUtils.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/utils/log/CompactionLogAnalyzer.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/utils/log/CompactionLogger.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/utils/log/TsFileIdentifier.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/utils/writer/AbstractCrossCompactionWriter.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/utils/writer/AbstractInnerCompactionWriter.java
- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/TsFileManager.java
- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/TsFileResource.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/FastCrossCompactionPerformerTest.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/ReadPointCompactionPerformerTest.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/cross/CrossSpaceCompactionExceptionTest.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/cross/RewriteCrossSpaceCompactionRecoverTest.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/inner/InnerSpaceCompactionExceptionTest.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/inner/sizetiered/SizeTieredCompactionRecoverTest.java
After compaction, if the target file is empty, its corresponding disk file will be deleted. If an exception or system interruption occurs, there will be problems in restart recovery and set allowCompaction to false.
2022-12-20 09:23:53,086 [pool-12-IoTDB-Recovery-Thread-Pool-1] ERROR o.a.i.d.e.c.t.CompactionRecoverTask:300 - root.iot-0 [Compaction][ExceptionHandler] target file sequence/root.iot/0/0/1670572962795-1051-2-1.inner is not complete, and some source files is lost, do nothing. Set allowCompaction to false
2022-12-20 09:23:53,087 [pool-12-IoTDB-Recovery-Thread-Pool-1] ERROR o.a.i.d.e.c.t.CompactionRecoverTask:133 - root.iot-0 [Compaction][Recover] Failed to recover compaction, set allowCompaction to false
**Reason**
Empty target files will be deleted in …
> [To rel/1.0][IOTDB-5206] Set empty target resource to DELETED and then delete it after compaction

- server/src/main/java/org/apache/iotdb/db/metadata/mtree/store/CachedMTreeStore.java
- server/src/main/java/org/apache/iotdb/db/metadata/mtree/store/disk/cache/CacheManager.java
- server/src/main/java/org/apache/iotdb/db/metadata/mtree/store/disk/cache/ICacheManager.java
Synchronous updates require a mutex lock and asynchronous updates require a shared lock. 
In order to ensure that no mutex locks are applied during the update process, the update of the StorageGroupNode needs to be changed to asynchronous.
> [IOTDB-5442] SchemaFile update StorageGroupNode asynchronously

- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/DataRegion.java
See [IOTDB-5395](https://issues.apache.org/jira/browse/IOTDB-5395).
This issue is fixed by updating file metrics when loading tsfile.
> [IOTDB-5395] Update file metrics when loading tsfile

- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/DataRegion.java
See [IOTDB-5395](https://issues.apache.org/jira/browse/IOTDB-5395).
This issue is fixed by updating file metrics when loading tsfile.
> [To rel/1.0] [IOTDB-5395] Update file metrics when loading tsfile

- server/src/main/java/org/apache/iotdb/db/metadata/mtree/store/disk/schemafile/RecordUtils.java
- server/src/test/java/org/apache/iotdb/db/metadata/mtree/schemafile/RecordUtilTests.java
- server/src/test/java/org/apache/iotdb/db/metadata/mtree/schemafile/SchemaFileTest.java
Previously, `SchemaFile` did not store `MeasurementSchema.Props` as it is a variable length and relatively less efficient field to store into persistent media. To support full capability of metadata under high cardinality circumstance, `SchemaFile` will store/restore this `Map<String, String>` after then.
This update will cost at least 4 bytes more per measurement record in `SchemaFile`, and malicious long property key or value may cause overflow exception withou decent guradian statements for property's assignment. Well-optimized access methods for constrained property set is expected in further development.
> Update SchemaFile to be compatible with MeasurementSchema.props

- integration-test/src/test/java/org/apache/iotdb/db/it/schema/IoTDBSchemaTemplateIT.java
- server/src/main/java/org/apache/iotdb/db/metadata/mtree/traverser/Traverser.java
While fetching a normal timeseries under a device using template, since there's no template provided for traverser, which is brought by the mpp  or schema fetcher analyzing stage result, current implementation still tries to check the template and result in npe.
Skip the template check while there's no template provided for traverser.
> [IOTDB-5441] Fix NPE while fetch schema that is not in template used by related device

- integration-test/src/test/java/org/apache/iotdb/db/it/builtinfunction/scalar/IoTDBDiffFunctionIT.java
- integration-test/src/test/java/org/apache/iotdb/db/it/query/IoTDBNullOperandIT.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/TypeProvider.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/statement/component/WhereCondition.java
- server/src/main/java/org/apache/iotdb/db/utils/TypeInferenceUtils.java
cause of bug1: we forget to  cast functionName to lowercase in where predicate 
cause of bug2: forget corner case when check type in FunctionExpression----input expression is `NullOperand` 
fix result:
> [IOTDB-5455]Fix case sensitive when use Diff in where & NPE when series in where/having is not exist

- server/src/main/java/org/apache/iotdb/db/mpp/plan/scheduler/FragmentInstanceDispatcherImpl.java
Currently, one FI dispatch failure will result in the dispatch of rest FI being skipped, which cannot bring complete result for mpp client.
Therefore, improve the dispatch process to dispatch all FI of one mpp task and collect all the result for return.
> [To rel/1.0][IOTDB-5399] Collect complete dispatch result for return

- server/src/main/java/org/apache/iotdb/db/metadata/cache/DataNodeSchemaCache.java
We need to open ```recordStas``` when build caffiene, otherwise the cache hit rate won't be updated.
> Open schema cache statistics

- node-commons/src/main/java/org/apache/iotdb/commons/concurrent/threadpool/WrappedThreadPoolExecutor.java
I want to use the thread pool created by the IoTDBThreadPoolFactory in CompleteFuture. However, I have found that this can cause problems with threads not being released.
Here is the example code.
```java
import org.apache.iotdb.commons.concurrent.IoTDBThreadPoolFactory;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.ExecutorService;
public class Tests {
public static void main(String[] args) {
ExecutorService flushTaskExecutor1 = IoTDBThreadPoolFactory.newFixedThreadPool(2, "1");
CompletableFuture<Void>[] completableFutures = new CompletableFuture[5];
for (int j = 0; j < 5; j++) {
completableFutures[j] =
CompletableFuture.supplyAsync(
() -> {
System.out.println("run");
return null;
},
flushTaskExecutor1);
}
CompletableFuture.allOf(completableFutures).join(); …
```
> [IOTDB-5471] Add isDone() check in WrappedThreadPoolExecutor#afterExecute

- server/src/main/java/org/apache/iotdb/db/metadata/mtree/MTreeBelowSGCachedImpl.java
- server/src/main/java/org/apache/iotdb/db/metadata/mtree/MTreeBelowSGMemoryImpl.java
- server/src/main/java/org/apache/iotdb/db/metadata/schemaregion/ISchemaRegion.java
- server/src/test/java/org/apache/iotdb/db/metadata/schemaRegion/SchemaRegionTestUtil.java
Currently, the time series reader is implemented based on ```ShowTimeSeriesResult```, which is used as temporary schema result carrier and costs construction time. The construction time of ```ShowTimeSeriesResult``` can be saved via a light implementation generating fewest extra temporary objects.
Count timeseries operation benefits from the modification most. Its time consumption decreased to 1/4~1/3.
> Accelerate Count TimeSeries

- server/src/main/java/org/apache/iotdb/db/wal/buffer/AbstractWALBuffer.java
Some test fails when wal file version is updated before next file has been created.
> Update wal file version after next file has been created

- server/src/test/java/org/apache/iotdb/db/metadata/schemaRegion/SchemaRegionBasicTest.java
Related issue: [IOTDB-5495](https://issues.apache.org/jira/browse/IOTDB-5495)
A bug about `show devices` while using `offset` has been found.
See more details at [IoTDB-5350](https://issues.apache.org/jira/browse/IOTDB-5350)
This bug only appears in version 1.0 or earlier version. In master branch, there is no such bug.
Even so, relevant unit tests in master branch need to be improved, because it does not cover this situation.
> [IOTDB-5495]Improve unit tests about `show devices`

- node-commons/src/assembly/resources/conf/iotdb-common.properties
- server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
- server/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java
- server/src/main/java/org/apache/iotdb/db/service/DataNode.java
The config ```isDefaultSchemaMemoryConfig``` was used for initiating different default schema memory allocation in cluster mode and standalone mode. Since NewIoTDB has been removed, this config becomes useless. Eliminate it.
> Eliminate isDefaultSchemaMemoryConfig

- server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/process/join/HorizontallyConcatOperator.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/OperatorTreeGenerator.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/distribution/ExchangeNodeAdder.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/distribution/SourceRewriter.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/PlanGraphPrinter.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/PlanNodeType.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/PlanVisitor.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/process/HorizontallyConcatNode.java
- server/src/test/java/org/apache/iotdb/db/mpp/execution/operator/HorizontallyConcatOperatorTest.java
- server/src/test/java/org/apache/iotdb/db/mpp/plan/plan/distribution/AggregationDistributionTest.java
VerticallyConcatOperator is used to horizontally concatenate TsBlocks with the same timestamp column. For example,
TsBlock A is:
| Time | ColumnA |
|    1    |     1.0    |
TsBlock B is:
| Time | ColumnB |
|    1    |       2.0    |
After the VerticallyConcatOperator, the result will be:
| Time | ColumnA | ColumnB |
|    1    |       1.0    |     2.0      |
Literally, I think it's a horizontal concatenation. So I suggest rename it as HorizontallyConcatOperator.
> [IOTDB-5496] Rename VerticallyConcatOperator as HorizontallyConcatOperator

- server/src/main/java/org/apache/iotdb/db/metadata/visitor/SchemaExecutionVisitor.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/executor/RegionWriteExecutor.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/scheduler/FragmentInstanceDispatcherImpl.java
see [IOTDB-5499](https://issues.apache.org/jira/browse/IOTDB-5499)
Eliminate useless log in SchemaExecutionVisitor, RegionWriteExecutor and FragmentInstanceDispatcherImpl.
> [IOTDB-5499] Eliminate useless log during auto creating schema

- isession/src/main/java/org/apache/iotdb/isession/ISession.java
- session/src/main/java/org/apache/iotdb/session/Session.java
- session/src/main/java/org/apache/iotdb/session/pool/SessionPool.java
In current code of sessionPool, each session has an independent ConcurrentHashMap to record the device -> endPoint informations. 
However, when SessionPool has large number of session and each session need to insert a large number of devices, the ConcurrentHashMaps will take a lot of memory, which may lead to OOM.
In this PR, each session will share the same ConcurrentHashMap to reduce the redundant device -> endPoint informations.
> [IOTDB-5498] Fix SessionPool OOM when the numbers of devices and sessions are large

- server/src/main/java/org/apache/iotdb/db/metadata/mtree/store/disk/cache/CacheMemoryManager.java
- server/src/main/java/org/apache/iotdb/db/metadata/schemaregion/SchemaRegionSchemaFileImpl.java
The current strategy when creating a time series is to simply throw a SeriesOverflowException if memory resources are running low. However, there may be background tasks on the system that are releasing memory at this time and memory resources may become available immediately.
This PR provides a mechanism to wait for a limited time when memory is low and a releasingTask is running.
> [IOTDB-5510] Block and wait to create timeseries when releasing memory

- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/DataRegion.java
See [IOTDB-5504](https://issues.apache.org/jira/browse/IOTDB-5504).
The reason for this bug is that integer overflow occurs when casting long to integer in `executeCompaction`.
> [IOTDB-5504] Fix illegal argument exception occurs when scheduling compaction

- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/DataRegion.java
See [IOTDB-5504](https://issues.apache.org/jira/browse/IOTDB-5504).
The reason for this bug is that integer overflow occurs when casting long to integer in `executeCompaction`.
> [To rel/1.0] [IOTDB-5504] Fix illegal argument exception occurs when scheduling compaction

- consensus/src/main/java/org/apache/iotdb/consensus/iot/logdispatcher/IoTConsensusMemoryManager.java
- consensus/src/main/java/org/apache/iotdb/consensus/iot/logdispatcher/IoTConsensusMemoryManagerMetrics.java
- consensus/src/main/java/org/apache/iotdb/consensus/iot/logdispatcher/LogDispatcher.java
- consensus/src/main/java/org/apache/iotdb/consensus/iot/logdispatcher/SyncStatus.java
- docs/UserGuide/Monitor-Alert/Metric-Tool.md
- docs/zh/UserGuide/Monitor-Alert/Metric-Tool.md
Please see details in [IOTDB-5491](https://issues.apache.org/jira/browse/IOTDB-5491).
> [IOTDB-5491] Add IoTConsumus memory control metric items

- docs/UserGuide/Monitor-Alert/Apache-IoTDB-ConfigNode-Dashboard.json
- docs/UserGuide/Monitor-Alert/Apache-IoTDB-DataNode-Dashboard.json
The reason why nodes are not limited before is that the leader distribution can be observed on the non-leader confignode. However, when there are multiple iotdb clusters in prom, the panel will display the leader distribution of all clusters, causing the cluster display to be unclear. Therefore, it is better to add instance in the attribute to limit.
Before : 
After:
> [ Metrics ] The repair leader distribution panel

- consensus/pom.xml
1. Release a ratis snapshot version including latest required patches
2. Open this PR to verify CI
The Ratis snapshot version is build upon the following commit: https://github.com/apache/ratis/commit/ebba77d8057e64492dfb318b170706f4a765462d
The Ratis snapshot branch is snapshot-branch2, see https://github.com/apache/ratis/commits/snapshot-branch2
> [IOTDB-5505] Bump Ratis version to latest 2.4.2-snapshot

- consensus/pom.xml
cherry-pick of https://github.com/apache/iotdb/pull/9027
> [To rel/1.0][IOTDB-5505] Bump Ratis version to latest 2.4.2-snapshotSnapshot

- server/src/main/java/org/apache/iotdb/db/metadata/mtree/traverser/Traverser.java
- server/src/test/java/org/apache/iotdb/db/metadata/schemaRegion/SchemaRegionTemplateTest.java
- server/src/test/java/org/apache/iotdb/db/metadata/schemaRegion/SchemaRegionTestUtil.java
When constructing timeseries black list in SchemaRegion, there won't be any schema template provided, which brings npe when trying to get child node from template. Add judgement before getting child node will fix this.
> [IOTDB-5526] Fix NPE while construct timeseries black list in SchemaRegion

- server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/selector/impl/RewriteCrossSpaceCompactionSelector.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/AbstractCompactionTest.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/CompactionSchedulerTest.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/CompactionSchedulerWithFastPerformerTest.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/cross/CrossSpaceCompactionWithFastPerformerTest.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/cross/CrossSpaceCompactionWithFastPerformerValidationTest.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/cross/CrossSpaceCompactionWithReadPointPerformerTest.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/cross/CrossSpaceCompactionWithReadPointPerformerValidationTest.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/cross/MergeUpgradeTest.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/cross/RewriteCompactionFileSelectorTest.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/utils/CompactionConfigRestorer.java
In this change, we add a limitation for cross compaction selector to increase the compaction efficiency. That is, only the unseqFile whose level larger that 0 can be selected as the candidate of cross compaction.
So, the small unseq file will be compacted inner before doing cross space compaction
> [IOTDB-5509] Add level control for cross compaction selecting

- integration-test/src/main/java/org/apache/iotdb/it/env/cluster/MppCommonConfig.java
- integration-test/src/main/java/org/apache/iotdb/it/env/cluster/MppSharedCommonConfig.java
- integration-test/src/main/java/org/apache/iotdb/it/env/remote/RemoteCommonConfig.java
- integration-test/src/main/java/org/apache/iotdb/itbase/env/CommonConfig.java
- integration-test/src/test/java/org/apache/iotdb/db/it/aggregation/IoTDBAggregationByLevel2IT.java
- integration-test/src/test/java/org/apache/iotdb/db/it/aggregation/IoTDBAggregationByLevelIT.java
- integration-test/src/test/java/org/apache/iotdb/db/it/alignbydevice/IoTDBAlignByDevice2IT.java
- integration-test/src/test/java/org/apache/iotdb/db/it/alignbydevice/IoTDBAlignByDeviceIT.java
- integration-test/src/test/java/org/apache/iotdb/db/it/alignbydevice/IoTDBOrderByWithAlignByDevice2IT.java
- integration-test/src/test/java/org/apache/iotdb/db/it/alignbydevice/IoTDBOrderByWithAlignByDeviceIT.java
- integration-test/src/test/java/org/apache/iotdb/db/it/aligned/IoTDBAlignedSeriesQuery4IT.java
- server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/LocalExecutionPlanContext.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/OperatorTreeGenerator.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/process/HorizontallyConcatNode.java
- server/src/test/java/org/apache/iotdb/db/mpp/plan/plan/PipelineBuilderTest.java
This pull request optimize the pipeline build logic for consumeAllNode like following:
1. When dop > localChildrenSize, create one new pipeline for each local child, which is not including ExchangeNode. And offer extra dop for childNode.
2. When dop <= localChildrenSize, divide local children into dop groups. These groups may include ExchangeNode but the dop for child is 1, which can avoid the situation that generate child iteratively.
> [IOTDB-4005] Optimize the pipeline build logic for consumeAllNode

- server/src/main/java/org/apache/iotdb/db/service/thrift/impl/ClientRPCServiceImpl.java
SchemaTemplate related interfaces were added after the change of syntax conventions. Now we update the related interfaces.
> [IOTDB-5469] create template with backquote characters successfully but get schema info failed

- consensus/src/main/java/org/apache/iotdb/consensus/iot/IoTConsensusServerImpl.java
Solution: Set the nextSyncIndex when timeout.
Please see details in [IOTDB-5112](https://issues.apache.org/jira/browse/IOTDB-5112) and [feishu cloud doc](https://apache-iotdb.feishu.cn/docx/TekkdtRvTo181UxI2x0c42iTnsN).
> [IOTDB-5112] Fixed IoTConsensus synchronization stuck under low load or during restart

- server/src/main/java/org/apache/iotdb/db/metadata/cache/DataNodeSchemaCache.java
When compute measurement in schema cache, the isFirst variable is not initialized as true, which results in the missing of compute device.
> Fix device alignment check during data insertion

- server/src/main/java/org/apache/iotdb/db/metadata/MManager.java
- server/src/main/java/org/apache/iotdb/db/qp/physical/sys/CreateAlignedTimeSeriesPlan.java
- server/src/main/java/org/apache/iotdb/db/service/thrift/impl/TSServiceImpl.java
Currently, IoTDB v0.13 doesn't support creating aligned timeseries with alias. Eliminate this field passed from client to server via SDK/API.
> [To rel/0.13] Fix alias check when CreateAlignedTimeSeries

- server/src/main/java/org/apache/iotdb/db/mpp/execution/driver/DataDriver.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/driver/DataDriverContext.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/fragment/FragmentInstanceContext.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/fragment/FragmentInstanceExecution.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/LocalExecutionPlanner.java
Every driver will invoke addUsedFilesForQuery() concurrently, and the TsFileResources maybe concurrently modified.
> [IOTDB-5547] Bug fix: driver will release resources concurrently which leads to concurrentModify

- server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/utils/executor/fast/AlignedSeriesCompactionExecutor.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/utils/executor/fast/NonAlignedSeriesCompactionExecutor.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/utils/executor/fast/SeriesCompactionExecutor.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/utils/executor/fast/element/ChunkMetadataElement.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/utils/executor/fast/element/PointElement.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/utils/reader/PointPriorityReader.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/FastAlignedCrossCompactionTest.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/FastNonAlignedCrossCompactionTest.java
In the past, all the chunks that overlap with the current chunk were read into the memory at one time, but now only the chunks that need to be used are read into the memory.
For example: in the figure below, first read 1 into the memory, and then read 2 3 4 in sequence. At most two chunks can be stored in the memory at the same time instead of 4 chunks.
> [IOTDB-5189][IOTDB-5529]Optimize the memory usage and execution of fast compaction

- node-commons/src/main/java/org/apache/iotdb/commons/concurrent/ThreadName.java
- server/src/main/java/org/apache/iotdb/db/metadata/mtree/store/disk/cache/CacheMemoryManager.java
- server/src/main/java/org/apache/iotdb/db/utils/concurrent/FiniteSemaphore.java
- server/src/test/java/org/apache/iotdb/db/metadata/schemaRegion/SchemaStatisticsTest.java
The current memory release uses an asynchronous producer-consumer model. A single consumer (release processor) may process multiple requests from producers at once. However, in concurrent scenarios there may be a problem of missed consumption.
For example, thread B has performed a memory release but has not set the flag bit hasReleaseTask to false.
At this time, thread A checks memory usage and finds that the release threshold has been exceeded, but hasReleaseTask is true and no new threads will be requested to release memory.
Although memory will be freed correctly at the next ensureMemoryStatus, the memory occupation at this point is not as expected. Here are two CI tests that reflect this problem: 
https://github.com/apache/iotdb/actions/runs/4192942086/jobs/7269183098 …
> [IOTDB-5549] Ensure concurrently MNode memory release

- consensus/src/main/java/org/apache/iotdb/consensus/iot/logdispatcher/IndexController.java
- consensus/src/main/java/org/apache/iotdb/consensus/iot/logdispatcher/LogDispatcher.java
- consensus/src/main/java/org/apache/iotdb/consensus/iot/logdispatcher/SyncStatus.java
- consensus/src/test/java/org/apache/iotdb/consensus/iot/logdispatcher/IndexControllerTest.java
- consensus/src/test/java/org/apache/iotdb/consensus/iot/logdispatcher/SyncStatusTest.java
- server/src/main/java/org/apache/iotdb/db/service/IoTDBShutdownHook.java
Solution: Extend the persistence strategy of log synchronization
Please see details in [IOTDB-5112](https://issues.apache.org/jira/browse/IOTDB-5512) and [feishu cloud doc](https://apache-iotdb.feishu.cn/docx/DddIdK9bnojYbsxQHFbcmkx7nKc)
> [IOTDB-5512] Fixed IoTConsensus may repeatedly send some log when restarting

- confignode/src/main/java/org/apache/iotdb/confignode/conf/ConfigNodeConfig.java
- node-commons/src/assembly/resources/conf/iotdb-common.properties
- server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
see [jira](https://issues.apache.org/jira/browse/IOTDB-5560)
> [IOTDB-5560] Increase default consensusLogAppenderBufferSize from 4M to 16M to reduce the probability of large request write failures

- integration-test/src/test/java/org/apache/iotdb/db/it/aggregation/IoTDBCountIfIT.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/ExpressionAnalyzer.java
Bug cause: Forget to ignore the Keep Expression when process `group by level`.
Fix: Add judgement in the process, this is a temporary method to fix this bug, we will use a more elegant way to replace it when multi input series Function are introduced.
> [IOTDB-5553] Fix NPE while using count_if (contains keep expression) with group by level

- client-py/iotdb/sqlalchemy/tests/test_dialect.py
- client-py/tests/test_dataframe.py
- client-py/tests/test_todf.py
Since #9085 introduced a hidden database `root.__system`, some test cases which using `show database`, `select ** from root` or `show timeseries` need to be modified.
> Fix python IT fail caused by the database root.__system

- server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/utils/executor/fast/AlignedSeriesCompactionExecutor.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/utils/executor/fast/NonAlignedSeriesCompactionExecutor.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/utils/executor/fast/SeriesCompactionExecutor.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/utils/executor/fast/element/ChunkMetadataElement.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/utils/executor/fast/element/PointElement.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/utils/reader/PointPriorityReader.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/FastAlignedCrossCompactionTest.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/FastNonAlignedCrossCompactionTest.java
In the past, all the chunks that overlap with the current chunk were read into the memory at one time, but now only the chunks that need to be used are read into the memory.
For example: in the figure below, first read 1 into the memory, and then read 2 3 4 in sequence. At most two chunks can be stored in the memory at the same time instead of 4 chunks.
> [To rel/1.0][IOTDB-5189][IOTDB-5529]Optimize the memory usage and execution of fast compaction

- docs/UserGuide/Monitor-Alert/Apache-IoTDB-DataNode-Dashboard.json
* Schema Engine Mode
* Schema Region Number
* Schema Consensus Protocol
* Time Series Number
* Memory Usage for Schema Region
* Timeseries count
* Memory Usage
* Length
* Checkpoint
> [IOTDB-5577] Metric dashboard for Schema Module

- docs/UserGuide/API/Programming-Java-Native-API.md
- docs/UserGuide/Data-Concept/Data-Model-and-Terminology.md
- docs/UserGuide/Monitor-Alert/Alerting.md
- docs/UserGuide/Operate-Metadata/Timeseries.md
- docs/UserGuide/Query-Data/Select-Expression.md
- docs/UserGuide/Write-Data/Batch-Load-Tool.md
- docs/zh/UserGuide/API/Programming-Java-Native-API.md
- docs/zh/UserGuide/Data-Concept/Data-Model-and-Terminology.md
- docs/zh/UserGuide/Monitor-Alert/Alerting.md
- docs/zh/UserGuide/Operate-Metadata/Timeseries.md
- docs/zh/UserGuide/Query-Data/Select-Expression.md
- docs/zh/UserGuide/Write-Data/Batch-Load-Tool.md
- site/src/main/.vuepress/config.js
version: rel/1.0
record：https://timechor.feishu.cn/drive/folder/fldcnOV0zj3S9g8JWspr6oDIqVf?from=from_copylink
content： Fixed the rest of the bad URL on the master branch， and added the SQL-Reference file to the official site catalogue to fix the missing file （refer to file "Reference/DML-Data-Manipulation-Language.md"）
> fix-badurl-of-1.0

- docs/zh/UserGuide/IoTDB-Introduction/Publication.md
The paper [Apache IoTDB: time-series database for internet of things] is missing in the Chinese doc, while it's listed in the English doc.
> Add a paper to the Publication Chinese doc

- server/src/main/java/org/apache/iotdb/db/metadata/mtree/store/disk/cache/CacheMemoryManager.java
flushTaskMonitor and releaseTaskMonitor should keep alive until CacheMemoryManager#clear() is invoked expecitly. So they should not throw exception in catch clause.
> [IOTDB-5578] Keep CacheMemoryManager monitor alive when exception

- metrics/interface/src/main/java/org/apache/iotdb/metrics/config/MetricConfig.java
- metrics/interface/src/test/java/org/apache/iotdb/metrics/config/MetricConfigTest.java
- server/src/assembly/resources/conf/iotdb-datanode.properties
see [jira](https://issues.apache.org/jira/browse/IOTDB-5585)
> [IOTDB-5585] Change InternalReporterType from IoTDB to Memory to reduce performance degradation

- docs/UserGuide/Query-Data/Group-By.md
- docs/zh/UserGuide/Query-Data/Group-By.md
- integration-test/src/test/java/org/apache/iotdb/db/it/groupby/IoTDBGroupByConditionIT.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/window/SeriesWindowManager.java
https://issues.apache.org/jira/browse/IOTDB-5584
When the controlColumn of first data point is false, conditon window wouldn't skip it because needSkip is intialized to false which leads to a redundant row in resultSet.
This PR fix the problem.
> [IOTDB-5584] Fix wrong intialization in GROUP BY CONDITION

- confignode/src/main/java/org/apache/iotdb/confignode/manager/ClusterSchemaManager.java
- confignode/src/main/java/org/apache/iotdb/confignode/manager/partition/PartitionManager.java
- confignode/src/main/java/org/apache/iotdb/confignode/persistence/partition/PartitionInfo.java
During dropping database, the target database will be marked as pre-deleted in PartitionInfo, which brings DatabaseNotExistsException during adjustMaxRegionGroupNum.
Filter and ignore the pre-deleted database during adjustMaxRegionGroupNum.
> [IOTDB-5516] Fix DatabaseNotExistsException caused by pre deleted database during drop database

- confignode/src/main/java/org/apache/iotdb/confignode/consensus/request/write/datanode/UpdateDataNodePlan.java
- confignode/src/main/java/org/apache/iotdb/confignode/manager/ConfigManager.java
- confignode/src/main/java/org/apache/iotdb/confignode/manager/IManager.java
- confignode/src/main/java/org/apache/iotdb/confignode/manager/node/ClusterNodeStartUtils.java
- confignode/src/main/java/org/apache/iotdb/confignode/manager/node/NodeManager.java
- confignode/src/main/java/org/apache/iotdb/confignode/persistence/node/NodeInfo.java
- confignode/src/main/java/org/apache/iotdb/confignode/service/ConfigNode.java
- confignode/src/main/java/org/apache/iotdb/confignode/service/thrift/ConfigNodeRPCServiceProcessor.java
- confignode/src/test/java/org/apache/iotdb/confignode/consensus/request/ConfigPhysicalPlanSerDeTest.java
- integration-test/src/main/java/org/apache/iotdb/it/env/cluster/AbstractEnv.java
- integration-test/src/main/java/org/apache/iotdb/it/env/cluster/AbstractNodeWrapper.java
- integration-test/src/main/java/org/apache/iotdb/it/env/cluster/ConfigNodeWrapper.java
- integration-test/src/main/java/org/apache/iotdb/it/env/cluster/DataNodeWrapper.java
- integration-test/src/test/java/org/apache/iotdb/confignode/it/cluster/IoTDBClusterNodeErrorStartUpIT.java
- integration-test/src/test/java/org/apache/iotdb/confignode/it/cluster/IoTDBClusterRestartIT.java
- integration-test/src/test/java/org/apache/iotdb/confignode/it/utils/ConfigNodeTestUtils.java
- node-commons/src/main/java/org/apache/iotdb/commons/utils/ThriftCommonsSerDeUtils.java
- node-commons/src/test/java/org/apache/iotdb/commons/utils/ThriftCommonsSerDeUtilsTest.java
- server/src/main/java/org/apache/iotdb/db/client/ConfigNodeClient.java
- server/src/main/java/org/apache/iotdb/db/conf/IoTDBStartCheck.java
- server/src/main/java/org/apache/iotdb/db/service/DataNode.java
- thrift-confignode/src/main/thrift/confignode.thrift
The cluster DataNode is now enable to modify its clientRPCEndPoint.
The [cluster Node startup protocol](https://apache-iotdb.feishu.cn/docx/BWAtdxAZ8oflr7xcJXncAAyAnMc) is updated for adapting this new feature.
An IT is added for testing this new feature.
You can find the modification result either by SQL show datanodes or in the system.properties file:
> [IOTDB-5555] Enable modify external RPC EndPoint of DataNode

- server/src/main/java/org/apache/iotdb/db/mpp/execution/exchange/MPPDataExchangeManager.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/exchange/sink/SinkChannel.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/exchange/source/SourceHandle.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/distribution/DistributionPlanner.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/distribution/ExchangeNodeAdder.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/distribution/NodeGroupContext.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/distribution/SimpleFragmentParallelPlanner.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/PlanFragment.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/sink/MultiChildrenSinkNode.java
Before this pr, calculateNodeTopologyBetweenInstance() in SimpleFragmentParallelPlanner uses recursive search to locate a ExchangeNode, which is very time-consuming when PlanNodeTree is quite large. We record a map in this pr to avoid this cost. Also, we fix the issue of wrong upstreamIndex of ExchangeNode in this pr, the ITs will be added later.
> [IOTDB-5593] Improve efficiency of DistributionPlanner by recording map instead of recursive search

- schema-engine-rocksdb/src/main/java/org/apache/iotdb/db/metadata/schemaregion/rocksdb/RSchemaRegion.java
- server/src/main/java/org/apache/iotdb/db/metadata/MetadataConstant.java
- server/src/main/java/org/apache/iotdb/db/metadata/schemaregion/ISchemaRegionParams.java
- server/src/main/java/org/apache/iotdb/db/metadata/schemaregion/RSchemaRegionLoader.java
- server/src/main/java/org/apache/iotdb/db/metadata/schemaregion/SchemaEngine.java
- server/src/main/java/org/apache/iotdb/db/metadata/schemaregion/SchemaRegion.java
- server/src/main/java/org/apache/iotdb/db/metadata/schemaregion/SchemaRegionLoader.java
- server/src/main/java/org/apache/iotdb/db/metadata/schemaregion/SchemaRegionMemoryImpl.java
- server/src/main/java/org/apache/iotdb/db/metadata/schemaregion/SchemaRegionParams.java
- server/src/main/java/org/apache/iotdb/db/metadata/schemaregion/SchemaRegionSchemaFileImpl.java
We use java reflections and annotation to implement SchemaRegionLoader, which brings better extension-ability for SchemaEngine.
> [IOTDB-5545] Implement SchemaRegionLoader for SchemaEngine

- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/OperatorTreeGenerator.java
Caused by: IdenditySink and ShuffleSink is handled incorrectly
> [IOTDB-5599] Bug: One query is divided too much tasks to be allowed by system

- integration-test/src/main/java/org/apache/iotdb/it/env/remote/RemoteServerEnv.java
- integration-test/src/test/java/org/apache/iotdb/db/it/aggregation/IoTDBAggregationIT.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/distribution/NodeGroupContext.java
cause: If all data regions are not assigned, the Collection is empty.
> [IOTDB-5604]Fix NPE when execute Agg + align by device query without assigned DataRegion

- node-commons/src/main/java/org/apache/iotdb/commons/utils/ThriftCommonsSerDeUtils.java
- service-rpc/src/main/java/org/apache/iotdb/rpc/ConfigurableTByteBuffer.java
It is possible that we need to deserialize a quite large bytebuffer whose capacity reaches the MaxMessageSize of thirft.
>  Use ConfigurableTByteBuffer instead of TByteBuffer in ThriftCommonsSerDeUtils

- node-commons/src/main/java/org/apache/iotdb/commons/utils/ThriftCommonsSerDeUtils.java
- service-rpc/src/main/java/org/apache/iotdb/rpc/ConfigurableTByteBuffer.java
It is possible that we need to deserialize a quite large bytebuffer whose capacity reaches the MaxMessageSize of thirft.
cherry-pick from https://github.com/apache/iotdb/pull/9188
> [To rel/1.1][IOTDB-5607] Use ConfigurableTByteBuffer instead of TByteBuffer in ThriftCommonsSerDeUtils

- pom.xml
This PR is trying to fix the following security alerts.
https://github.com/apache/iotdb/security/dependabot/205  https://github.com/apache/iotdb/security/dependabot/6 
jackson-mapper-asl is useless in IoTDB, just remove it.
> Remove jackson-mapper-asl to fix security alert

- docs/UserGuide/Reference/Common-Config-Manual.md
- docs/zh/UserGuide/Reference/Common-Config-Manual.md
- node-commons/src/assembly/resources/conf/iotdb-common.properties
- server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
- server/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/task/InnerSpaceCompactionTask.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/schedule/CompactionScheduler.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/schedule/CompactionTaskManager.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/schedule/comparator/DefaultCompactionTaskComparatorImpl.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/selector/impl/CrossSpaceCompactionCandidate.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/selector/impl/RewriteCrossSpaceCompactionSelector.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/selector/impl/SizeTieredCompactionSelector.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/CompactionSchedulerTest.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/CompactionSchedulerWithFastPerformerTest.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/inner/InnerCompactionSchedulerTest.java
1. Change the size of the candidateCompactionTaskQueue from 1000 to 50. The advantage is to avoid tasks blocked in the queue occupying files for a long time, resulting in no files being selected for cross-space compaction. But another impact is that once the number of files is large, because the number of tasks in the queue shrinks, the inner-space compaction will not be able to compact the latest files.
2. Priority comparison of tasks: Inner-space compaction tasks no longer distinguish between seq and unseq, but are sorted according to unified rules; under the configuration of BALANCE, cross-space compaction tasks and inner-space compaction tasks follow the first-come-first-executed rule . One thing to note is that since the priority sorting of the queue is implemented through the …
> [To rel/1.0][IOTDB-5147]Optimize compaction schedule when priority is BALANCE

- consensus/src/main/java/org/apache/iotdb/consensus/common/request/IndexedConsensusRequest.java
- consensus/src/main/java/org/apache/iotdb/consensus/iot/IoTConsensusServerImpl.java
- consensus/src/main/java/org/apache/iotdb/consensus/iot/logdispatcher/LogDispatcher.java
- consensus/src/test/java/org/apache/iotdb/consensus/iot/util/FakeConsensusReqReader.java
- consensus/src/test/java/org/apache/iotdb/consensus/iot/util/TestStateMachine.java
see [jira](https://issues.apache.org/jira/browse/IOTDB-5613)
I tested with 1c1d on the machine and the throughput improved by 70%
Before:
After：
> [IOTDB-5613] Remove unnecessary serialization in IoTConsensus when replicaNum is 1 to improve write performance

- server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/process/MergeSortOperator.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/OperatorTreeGenerator.java
- server/src/test/java/org/apache/iotdb/db/mpp/execution/operator/MergeSortOperatorTest.java
When the method of next() in mergeSortOperator has executed for a long time or too many lines has   been in tsBlockBuilder, it will return in advance.
> [IOTDB-5580] Add limitation of time and tsBlock size to MergeSortOperator  

- consensus/src/main/java/org/apache/iotdb/consensus/common/request/IndexedConsensusRequest.java
- consensus/src/main/java/org/apache/iotdb/consensus/iot/IoTConsensusServerImpl.java
- consensus/src/main/java/org/apache/iotdb/consensus/iot/logdispatcher/LogDispatcher.java
- consensus/src/test/java/org/apache/iotdb/consensus/iot/util/FakeConsensusReqReader.java
cherry-pick [pull/9204](https://github.com/apache/iotdb/pull/9204)
> [To rel/1.1][IOTDB-5613] Remove unnecessary serialization in IoTConsensus when replicaNum is 1 to improve write performance

- integration-test/src/main/java/org/apache/iotdb/it/env/cluster/MppCommonConfig.java
- integration-test/src/main/java/org/apache/iotdb/it/env/cluster/MppSharedCommonConfig.java
- integration-test/src/main/java/org/apache/iotdb/it/env/remote/RemoteCommonConfig.java
- integration-test/src/main/java/org/apache/iotdb/itbase/env/CommonConfig.java
- integration-test/src/test/java/org/apache/iotdb/db/it/IoTDBInsertMultiPartitionIT.java
- server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
- server/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java
- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/TimePartitionManager.java
When set Max_heap_size=2G and insert data of 7 years. The flush thread will be stuck. 
There is a simple way to reproduce. 
Set max_heap_size of data node to 200M, set write_memory_proportion to 10000000:1.
Then start standalone iotdb and execute the following sqls:
```sql
insert into root.sg.d1(time,s1) values(1,2);
flush;
insert into root.sg.d1(time,s1) values(2,2);
insert into root.sg.d1(time,s1) values(604800001,2);
flush;
```
Finally, you will see the last flush cannot execute successfully.
The `evictOldPartition` method in `TimePartitionManager` always peek the first TimePartitionInfo in the TreeSet in the while loop. However, the memSize of the TimePartitionInfo may be 0. In this case, the loop won't be ended.
Change the `treeSet.first()` to `treeSet.pollFirst()`.
> [IOTDB-5620] Fix flush stuck when there is a lot of time partitions in each DataRegion

- service-rpc/src/main/java/org/apache/iotdb/rpc/IoTDBRpcDataSet.java
see [IOTDB-3936]Add an interface in IClientRPCService to directly return bytebuffer instead of TSQueryDataSet
This pr is modified to add `lastReadWasNull = false;` of the `constructOneRow` method to the `constructOneTsBlock` method, resulting in a call to the next() method that meets the first of the following criteria, The `lastReadWasNull` field was not reset to false.
> [IOTDB-5487] Fix the problem that the timestamp is "null" when using jdbc

- service-rpc/src/main/java/org/apache/iotdb/rpc/IoTDBRpcDataSet.java
see [[IOTDB-3936](https://issues.apache.org/jira/browse/IOTDB-3936)]Add an interface in IClientRPCService to directly return bytebuffer instead of TSQueryDataSet
This pr is modified to add lastReadWasNull = false; of the constructOneRow method to the constructOneTsBlock method, resulting in a call to the next() method that meets the first of the following criteria, The lastReadWasNull field was not reset to false.
> [To rel/1.0] [IOTDB-5487] Fix the problem that the timestamp is "null" when using jdbc

- service-rpc/src/main/java/org/apache/iotdb/rpc/IoTDBRpcDataSet.java
see [[IOTDB-3936](https://issues.apache.org/jira/browse/IOTDB-3936)]Add an interface in IClientRPCService to directly return bytebuffer instead of TSQueryDataSet
This pr is modified to add lastReadWasNull = false; of the constructOneRow method to the constructOneTsBlock method, resulting in a call to the next() method that meets the first of the following criteria, The lastReadWasNull field was not reset to false.
> [To rel/1.1] [IOTDB-5487] Fix the problem that the timestamp is "null" when using jdbc

- server/src/main/java/org/apache/iotdb/db/rescon/SystemInfo.java
The memory calculation method in SystemInfo is not accurate because `dataRegionInfo.getMemCost()` may changed by other thread. 
This PR is for fixing this issue.
> Fix memory calculation is not accurate in SystemInfo

- server/src/main/java/org/apache/iotdb/db/rescon/PrimitiveArrayManager.java
If we set `buffered_arrays_memory_proportion` to 0, there will be a lot of unnecessary info logs. 
This PR changes the log level of array pool to DEBUG.
> Change the log level of array pool to DEBUG

- server/src/main/java/org/apache/iotdb/db/mpp/execution/driver/DataDriver.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/fragment/FragmentInstanceContext.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/fragment/FragmentInstanceExecution.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/fragment/FragmentInstanceManager.java
We will keep FIContext in memory for 5 mins, so we only keep necessary infos in FIContext for memory cost.
> Set some runtime fields in FIConetxt to null when the FI is done

- server/src/main/java/org/apache/iotdb/db/metadata/mtree/ConfigMTree.java
- server/src/test/java/org/apache/iotdb/db/metadata/mtree/ConfigMTreeTest.java
same as [[IOTDB-5240] Fix ConfigMTree snapshot deserialization while using template](https://github.com/apache/iotdb/pull/9247)
> [To rel/1.1][IOTDB-5240] Fix ConfigMTree snapshot deserialization while using template

- integration-test/src/test/java/org/apache/iotdb/db/it/query/IoTDBNoSelectExpressionAfterAnalyzedIT.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/AnalyzeVisitor.java
cause: no select expressions after analyzed, but was planned because  of expressions  in `where/having/groupBy`
> [IOTDB-5644] Fix unexpected result when there are no select expressions after analyzed in query

- docs/UserGuide/Cluster/Cluster-Maintenance.md
- docs/zh/UserGuide/Cluster/Cluster-Maintenance.md
Fix doc mistake: the schema is still writable for a ReadOnly DataNode
> [IOTDB-4497] Improve NodeStatus definition

- confignode/src/main/java/org/apache/iotdb/confignode/manager/ProcedureManager.java
Fixed the bug that readOnly regions cannot be migrated.
<hr>
This PR has:
<hr>
> [IOTDB-5300] Fix an error occurs when migrating readonly data region

- node-commons/src/main/java/org/apache/iotdb/commons/conf/CommonConfig.java
- server/src/main/java/org/apache/iotdb/db/consensus/statemachine/DataRegionStateMachine.java
- server/src/main/java/org/apache/iotdb/db/service/IoTDBShutdownHook.java
Current stop hook produces dead lock situations that prevent the process to terminate.
Ratis waits applyIndex to advance to commitIndex. However, it cannot be done when node is ReadOnly.
> [IOTDB-5659] Fix dead lock condition in shutdown hook

- node-commons/src/main/java/org/apache/iotdb/commons/conf/CommonConfig.java
- server/src/main/java/org/apache/iotdb/db/consensus/statemachine/DataRegionStateMachine.java
- server/src/main/java/org/apache/iotdb/db/service/IoTDBShutdownHook.java
cherry-pick of https://github.com/apache/iotdb/pull/9274
> [To rel/1.1][IOTDB-5659] Fix dead lock condition in shutdown hook

- server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/utils/executor/readchunk/AlignedSeriesCompactionExecutor.java
See [IOTDB-5671](https://issues.apache.org/jira/browse/IOTDB-5671).
The reason is `AlignedSeriesCompactionExecutor` load chunk from chunk cache, but doesn't manage the reference count of file reader in `FileReaderManager`, thus the reader manager will not close the reader and release the fd after compaction is finished.
> [To rel/1.1] [IOTDB-5671] Fix inode cannot be released after deletion causing waste of disk space

- server/src/main/java/org/apache/iotdb/db/engine/compaction/schedule/CompactionScheduler.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/schedule/CompactionTaskManager.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/selector/impl/RewriteCrossSpaceCompactionSelector.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/selector/impl/SizeTieredCompactionSelector.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/inner/InnerCompactionSchedulerTest.java
When the queue is full, tasks are allowed to be submitted and the task with the lowest priority is polled out.
> [IOTDB-5667] Fix compaction scheduler strategy issue

- confignode/src/main/java/org/apache/iotdb/confignode/conf/ConfigNodeStartupCheck.java
- confignode/src/main/java/org/apache/iotdb/confignode/conf/SystemPropertiesUtils.java
- node-commons/src/assembly/resources/conf/iotdb-common.properties
- node-commons/src/main/java/org/apache/iotdb/commons/exception/ConfigurationException.java
- server/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java
- server/src/main/java/org/apache/iotdb/db/conf/IoTDBStartCheck.java
Improvement:
1. The ConfigurationException must point out reason before thrown
2. Add .trim() for cluster parameters' analyzing
> [IOTDB-5676] Improve ConfigurationException description and analyzing of cluster parameters

- server/src/main/java/org/apache/iotdb/db/engine/compaction/schedule/CompactionScheduler.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/schedule/CompactionTaskManager.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/selector/impl/RewriteCrossSpaceCompactionSelector.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/selector/impl/SizeTieredCompactionSelector.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/inner/InnerCompactionSchedulerTest.java
When the queue is full, tasks are allowed to be submitted and the task with the lowest priority is polled out.
> [To rel/1.1][IOTDB-5667] Fix compaction scheduler strategy issue

- confignode/src/main/java/org/apache/iotdb/confignode/conf/ConfigNodeStartupCheck.java
- confignode/src/main/java/org/apache/iotdb/confignode/conf/SystemPropertiesUtils.java
- node-commons/src/assembly/resources/conf/iotdb-common.properties
- node-commons/src/main/java/org/apache/iotdb/commons/exception/ConfigurationException.java
- server/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java
- server/src/main/java/org/apache/iotdb/db/conf/IoTDBStartCheck.java
Improvement:
1. The ConfigurationException must point out reason before thrown
2. Add .trim() for cluster parameters' analyzing
> [To rel/1.1] [IOTDB-5676] Improve ConfigurationException description and analyzing of cluster parameters

- server/src/main/java/org/apache/iotdb/db/mpp/execution/executor/RegionWriteExecutor.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/metedata/write/CreateMultiTimeSeriesNode.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/metedata/write/MeasurementGroup.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/scheduler/AsyncPlanNodeSender.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/scheduler/FragmentInstanceDispatcherImpl.java
There was dispatch result collection logic in ```FragmentDispatcherImpl#dispatchWriteSync```, while it has been missed in ```FragmentDispatcherImpl#dispatchWriteAsync```, which may results in incomplete failure msg returned to client or unexpected failure during auto creating schema.
> [To rel/1.1] Fix dispatch result collection logic

- confignode/src/main/java/org/apache/iotdb/confignode/manager/consensus/ConsensusManager.java
Now the Simple consensus protocol of ConfigNode willl use the same folder as Ratis consensus protocol
> [IOTDB-5684] Standardize log folder of ConfigNode's Simple consensus protocol

- confignode/src/main/java/org/apache/iotdb/confignode/conf/ConfigNodeDescriptor.java
- confignode/src/main/java/org/apache/iotdb/confignode/service/ConfigNode.java
- metrics/interface/src/main/java/org/apache/iotdb/metrics/config/MetricConfig.java
- server/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java
- server/src/main/java/org/apache/iotdb/db/service/DataNode.java
(cherry picked from commit d14f37af8686dd7f8cdfb8cde60d422fe524688d)
> [To rel/1.1][IOTDB-5682] Fix the update of nodeId in Metrics (#9344)

- confignode/src/main/java/org/apache/iotdb/confignode/manager/consensus/ConsensusManager.java
Now the Simple consensus protocol of ConfigNode willl use the same folder as Ratis consensus protocol
> [To rel/1.1][IOTDB-5684] Standardize log folder of ConfigNode's Simple consensus protocol

- server/src/main/java/org/apache/iotdb/db/mpp/execution/executor/RegionWriteExecutor.java
The error msg thrown from consensus layer was not correctly returned to client. Fix it.
```
IoTDB> set system to readonly
IoTDB> create timeseries root.db2.device2.s3 int32
Msg: 600: Fail to do non-query operations because system is read-only.
```
> [To rel/1.1][IOTDB-5685] Fix error msg of failing to create a timeseries on an existing path when ReadOnly state

- confignode/src/main/java/org/apache/iotdb/confignode/consensus/statemachine/ConfigRegionStateMachine.java
- confignode/src/main/java/org/apache/iotdb/confignode/manager/consensus/ConsensusManager.java
see [jira](https://issues.apache.org/jira/browse/IOTDB-5695)
> [IOTDB-5695] Ensures backward compatibility between 1.0 and 1.1 for ConfigNode when using SimpleConsensus

- confignode/src/main/java/org/apache/iotdb/confignode/conf/ConfigNodeStartupCheck.java
- confignode/src/main/java/org/apache/iotdb/confignode/service/ConfigNodeCommandLine.java
- integration-test/src/test/java/org/apache/iotdb/confignode/it/cluster/IoTDBClusterNodeErrorStartUpIT.java
- node-commons/src/main/java/org/apache/iotdb/commons/service/StartupChecks.java
- server/src/main/java/org/apache/iotdb/db/conf/DataNodeStartCheck.java
- server/src/main/java/org/apache/iotdb/db/conf/DataNodeStartupCheck.java
- server/src/main/java/org/apache/iotdb/db/service/DataNode.java
add port check for confignode and datanode to avoid launching node which has same ports
see more information in [IOTDB-5368](https://issues.apache.org/jira/browse/IOTDB-5368)
> [IOTDB-5368] add port check for confignode and datanode

- server/src/main/java/org/apache/iotdb/db/mpp/execution/executor/RegionWriteExecutor.java
same as https://github.com/apache/iotdb/pull/9354
> [IOTDB-5685] Fix error msg of failing to create a timeseries on an existing path when ReadOnly state

- confignode/src/main/java/org/apache/iotdb/confignode/conf/ConfigNodeConfig.java
- confignode/src/main/java/org/apache/iotdb/confignode/conf/ConfigNodeDescriptor.java
- confignode/src/main/java/org/apache/iotdb/confignode/manager/ClusterSchemaManager.java
- confignode/src/main/java/org/apache/iotdb/confignode/manager/ConfigManager.java
- docs/UserGuide/Cluster/Cluster-Maintenance.md
- docs/zh/UserGuide/Cluster/Cluster-Maintenance.md
- integration-test/src/test/java/org/apache/iotdb/confignode/it/cluster/IoTDBClusterNodeGetterIT.java
- integration-test/src/test/java/org/apache/iotdb/confignode/it/utils/ConfigNodeTestUtils.java
- node-commons/src/assembly/resources/conf/iotdb-common.properties
- server/src/main/java/org/apache/iotdb/db/mpp/common/header/ColumnHeaderConstant.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/execution/config/metadata/ShowVariablesTask.java
- thrift-confignode/src/main/thrift/confignode.thrift
The parameter data_region_per_data_node is a empirical value from reall production environmennt. Replace data_region_per_processor by data_region_per_data_node will improve the efficiency of default cluster and simplify testing process.
> [IOTDB-5705] Replace data_region_per_processor by data_region_per_data_node

- confignode/src/main/java/org/apache/iotdb/confignode/conf/ConfigNodeConfig.java
- confignode/src/main/java/org/apache/iotdb/confignode/conf/ConfigNodeDescriptor.java
- confignode/src/main/java/org/apache/iotdb/confignode/manager/ClusterSchemaManager.java
- confignode/src/main/java/org/apache/iotdb/confignode/manager/ConfigManager.java
- docs/UserGuide/Cluster/Cluster-Maintenance.md
- docs/zh/UserGuide/Cluster/Cluster-Maintenance.md
- integration-test/src/test/java/org/apache/iotdb/confignode/it/cluster/IoTDBClusterNodeGetterIT.java
- integration-test/src/test/java/org/apache/iotdb/confignode/it/utils/ConfigNodeTestUtils.java
- node-commons/src/assembly/resources/conf/iotdb-common.properties
- server/src/main/java/org/apache/iotdb/db/mpp/common/header/ColumnHeaderConstant.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/execution/config/metadata/ShowVariablesTask.java
- thrift-confignode/src/main/thrift/confignode.thrift
The parameter data_region_per_data_node is a empirical value from reall production environmennt. Replace data_region_per_processor by data_region_per_data_node will improve the efficiency of default cluster and simplify testing process.
> [To rel/1.1] [IOTDB-5705] Replace data_region_per_processor by data_region_per_data_node

- node-commons/src/assembly/resources/conf/iotdb-common.properties
- server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
change default write parameter for wal part.
```
sync_wal_delay_in_ms=1500
wal_buffer_size_in_byte=33554432
wal_file_size_threshold_in_byte=31457280
wal_buffer_queue_capacity=500
```
> [TO rel/1.1][IOTDB-5704] change default write parameter for wal part

- integration-test/src/test/java/org/apache/iotdb/session/it/IoTDBSessionSchemaTemplateIT.java
- isession/src/main/java/org/apache/iotdb/isession/ISession.java
- isession/src/main/java/org/apache/iotdb/isession/pool/ISessionPool.java
- server/src/main/java/org/apache/iotdb/db/metadata/visitor/SchemaExecutionVisitor.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/executor/RegionWriteExecutor.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/Analysis.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/AnalyzeVisitor.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/parser/StatementGenerator.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/LogicalPlanVisitor.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/PlanNodeType.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/PlanVisitor.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/metedata/write/ActivateTemplateNode.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/metedata/write/BatchActivateTemplateNode.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/statement/StatementType.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/statement/StatementVisitor.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/statement/metadata/template/BatchActivateTemplateStatement.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/statement/metadata/template/DropSchemaTemplateStatement.java
- server/src/main/java/org/apache/iotdb/db/service/thrift/impl/ClientRPCServiceImpl.java
- session/src/main/java/org/apache/iotdb/session/Session.java
- session/src/main/java/org/apache/iotdb/session/SessionConnection.java
- session/src/main/java/org/apache/iotdb/session/pool/SessionPool.java
- thrift/src/main/thrift/client.thrift
When using session API, there should be an interface to provide service like ```create timeseries of schema template ```.
Add interface ```createTimeseriesOfSchemaTemplate``` to Session API, which support batch activating template on different device path.
> [IOTDB-5707] Support Activate Template for Session API

- server/src/main/java/org/apache/iotdb/db/engine/compaction/selector/utils/CrossSpaceCompactionCandidate.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/cross/MergeTest.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/cross/RewriteCompactionFileSelectorTest.java
When selecting files in cross space compaction, we need to upgrade the fileTimeindex by reading its resource file. If the resource file has been deleted by other thread, it will report "file not found" exception. To solve this problem, we check file is existed or not before reading it.
> [To rel/1.1][IOTDB-5639][compaction]Fix file not found exception in cross space compaction selector

- server/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java
**Updates:**
1. dn_core_connection_for_internal_service -> dn_core_client_count_for_each_node_in_client_manager
2. dn_max_connection_for_internal_service -> dn_max_client_count_for_each_node_in_client_manager
Fix bug of https://github.com/apache/iotdb/pull/9272
> Compatible with the client parameters on DataNode

- server/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java
**Updates:**
1. dn_core_connection_for_internal_service -> dn_core_client_count_for_each_node_in_client_manager
2. dn_max_connection_for_internal_service -> dn_max_client_count_for_each_node_in_client_manager
Fix bug of https://github.com/apache/iotdb/pull/9272
> [To rel/1.1] Compatible with the client parameters on DataNode

- server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/process/join/RowBasedTimeJoinOperator.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/process/join/merge/AscTimeComparator.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/process/join/merge/DescTimeComparator.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/process/join/merge/TimeComparator.java
more about the issue can be seen in https://issues.apache.org/jira/browse/IOTDB-5715.
The reason it that we directly use `currentTime < currentEndTime` to break the loop, however we should use `currentTime > currentEndTime` in order by time desc.
Now the query speed pf `order by time desc` is the same as `order by time asc`.
> [IOTDB-5715] Improve the performance of query order by time desc

- server/src/main/java/org/apache/iotdb/db/metadata/mtree/store/StampedWriterPreferredLock.java
- server/src/main/java/org/apache/iotdb/db/metadata/mtree/store/disk/cache/CacheMemoryManager.java
- server/src/test/java/org/apache/iotdb/db/metadata/mtree/lock/StampedWriterPreferredLockTest.java
The current stampedLock uses a writer-preferred rule, which may lead to extreme cases where a waiting write lock request blocks the subsequent release thread from acquiring the read lock, resulting in memory not being released. To solve this problem, a high priority read lock request interface needs to be introduced.
https://apache-iotdb.feishu.cn/docx/WwdAd6SYLofsAHxEJeRcDuWBnPh
> [To rel/1.1][IOTDB-5720] Fix release processor fail to release memory due to writer-preferred starvation

- integration-test/src/test/java/org/apache/iotdb/db/it/alignbydevice/IoTDBOrderByWithAlignByDeviceIT.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/process/join/merge/MergeSortComparator.java
(cherry picked from commit 6ed01068d04dffc0af03be1f79a464d0c22f978f)
> [To rel/1.1][IOTDB-5718] Fix wrong time order due to overflow in MergeSort

- client-py/iotdb/Session.py
To reproduce, insert data like
```
insert into root.test.d_01(time,s_01) values(16,1);
```
Then execute the following python code
```python
from iotdb.Session import Session
session = Session.init_from_node_urls(
node_urls=["127.0.0.1:6667"],
user="root",
password="roo",
fetch_size=1024,
zone_id="UTC+8",
)
session.open(False)
dataset = session.execute_last_data_query(["root.test.d_01.s_01"], 16)
print(dataset.has_next())
print(dataset.get_column_names())
print(dataset.next())
session.close()
```
> [To rel/0.13] Fix execution succeed with incorrect password by python api

- consensus/src/main/java/org/apache/iotdb/consensus/ratis/ApplicationStateMachineProxy.java
An error occurred during a recent run:
```shell
org.apache.iotdb.rpc.StatementExecutionException: 305: 
class org.apache.ratis.protocol.Message$1 cannot be cast to class org.apache.iotdb.consensus.ratis.ResponseMessage 
(org.apache.ratis.protocol.Message$1 and org.apache.iotdb.consensus.ratis.ResponseMessage are in unnamed module of loader 'app')
```
The error is originated from a incorrect return value in `applicationStateMachineProxy.write`, see the details in PR.
> [IOTDB-5729] Fix RatisConsensus ResponseMessage conversion error

- server/src/main/java/org/apache/iotdb/db/metadata/mtree/store/disk/schemafile/SchemaFile.java
Using a hard link when loading a SchemaFile snapshot on the current system can lead to corruption of snaptshot. Files.copy should be used instead.
> [To rel/1.1][IOTDB-5730] Fix use a hard link when loading a SchemaFile snapshot 

- server/src/main/java/org/apache/iotdb/db/metadata/mtree/MTreeBelowSGCachedImpl.java
- server/src/main/java/org/apache/iotdb/db/metadata/mtree/store/CachedMTreeStore.java
- server/src/main/java/org/apache/iotdb/db/metadata/mtree/store/MemMTreeStore.java
- server/src/main/java/org/apache/iotdb/db/metadata/mtree/store/disk/schemafile/SchemaFile.java
- server/src/main/java/org/apache/iotdb/db/metadata/rescon/ISchemaRegionStatistics.java
- server/src/main/java/org/apache/iotdb/db/metadata/rescon/MemSchemaRegionStatistics.java
- server/src/main/java/org/apache/iotdb/db/metadata/schemaregion/SchemaRegionMemoryImpl.java
- server/src/main/java/org/apache/iotdb/db/metadata/schemaregion/SchemaRegionSchemaFileImpl.java
- server/src/test/java/org/apache/iotdb/db/metadata/mtree/MTreeBelowSGTest.java
- server/src/test/java/org/apache/iotdb/db/metadata/schemaRegion/SchemaStatisticsTest.java
In order to better implement cluster quota management and enrich the metadata monitoring dashboard, it is necessary to add device-related statistical values when SchemaRegion creates and deletes device nodes.
> [To rel/1.1][IOTDB-5732] Add Device Schema Statistics

- server/src/main/java/org/apache/iotdb/db/metadata/mtree/MTreeBelowSGCachedImpl.java
- server/src/main/java/org/apache/iotdb/db/metadata/mtree/store/CachedMTreeStore.java
- server/src/main/java/org/apache/iotdb/db/metadata/mtree/store/MemMTreeStore.java
- server/src/main/java/org/apache/iotdb/db/metadata/rescon/ISchemaRegionStatistics.java
- server/src/main/java/org/apache/iotdb/db/metadata/rescon/MemSchemaRegionStatistics.java
- server/src/main/java/org/apache/iotdb/db/metadata/schemaregion/SchemaRegionMemoryImpl.java
- server/src/main/java/org/apache/iotdb/db/metadata/schemaregion/SchemaRegionSchemaFileImpl.java
- server/src/test/java/org/apache/iotdb/db/metadata/schemaRegion/SchemaStatisticsTest.java
In order to better implement cluster quota management and enrich the metadata monitoring dashboard, it is necessary to add device-related statistical values when SchemaRegion creates and deletes device nodes.
> [IOTDB-5732] Add Device Schema Statistics

- metrics/interface/src/main/java/org/apache/iotdb/metrics/AbstractMetricService.java
- server/src/main/java/org/apache/iotdb/db/engine/flush/MemTableFlushTask.java
- server/src/main/java/org/apache/iotdb/db/service/metrics/IoTDBInternalLocalReporter.java
cherry-pick [pull](https://github.com/apache/iotdb/pull/9439)
> [To rel/1.1][IOTDB-5725] Make internal report recording measurements asynchronous 

- metrics/interface/src/main/java/org/apache/iotdb/metrics/AbstractMetricService.java
- server/src/main/java/org/apache/iotdb/db/engine/flush/MemTableFlushTask.java
- server/src/main/java/org/apache/iotdb/db/service/metrics/IoTDBInternalLocalReporter.java
The flush time has been greatly reduced, and the system reject error has disappeared.
> [IOTDB-5725] Make internal report recording measurements asynchronous

- consensus/src/main/java/org/apache/iotdb/consensus/ratis/SnapshotStorage.java
- consensus/src/main/java/org/apache/iotdb/consensus/ratis/Utils.java
- consensus/src/test/java/org/apache/iotdb/consensus/ratis/SnapshotTest.java
in prevention of data race
1. delete snapshot
2. transfer snapshot
> [IOTDB-5738] Retain 2 copies of snapshot

- consensus/src/main/java/org/apache/iotdb/consensus/ratis/SnapshotStorage.java
- consensus/src/main/java/org/apache/iotdb/consensus/ratis/Utils.java
- consensus/src/test/java/org/apache/iotdb/consensus/ratis/SnapshotTest.java
cherry pick of https://github.com/apache/iotdb/pull/9474
> [To rel/1.1][IOTDB-5738] Retain 2 copies of snapshot

- server/src/main/java/org/apache/iotdb/db/metadata/mtree/store/disk/schemafile/SegmentedPage.java
- server/src/test/java/org/apache/iotdb/db/metadata/mtree/schemafile/SchemaFileTest.java
In determining the size of the pre-allocated segment for an EntityNode, an accurate calculation is performed by examining the children of the EntityNode if it has fewer than 20 children. Alternatively, the size is estimated using a hard-coded step list based on the cardinality of the EntityNode's children. 
During the flushing process of the EntityNode, the segment size is assessed prior to the insertion of each child, and the segment is re-allocated or extended according to the anticipated size. If the segment is unable to accommodate the inserted child even after an extension, an exception will be raised, indicating that the record is too large or the extension has failed.
This issue arises in an edge case where the EntityNode has fewer than 20 children, each with a large size …
> [To rel/1.1]Fix WrappedSegment extension with big name on edge case

- integration-test/src/test/java/org/apache/iotdb/db/it/schema/IoTDBSchemaTemplateIT.java
- server/src/main/java/org/apache/iotdb/db/metadata/template/ClusterTemplateManager.java
Previously, ClusterTemplateManager did not verify the compatibility between series type and its encoding, leading to incompatibility issues with erroneous creation request. 
A guardian statement has now been implemented to address this problem, and the related integration test case has been updated accordingly.
> [To rel/1.1]Fix template type check on ClusterTemplateManager

- integration-test/src/test/java/org/apache/iotdb/db/it/schema/IoTDBSchemaTemplateIT.java
- server/src/main/java/org/apache/iotdb/db/metadata/template/ClusterTemplateManager.java
(same as https://github.com/apache/iotdb/pull/9493)
Previously, ClusterTemplateManager did not verify the compatibility between series type and its encoding, leading to incompatibility issues with erroneous creation request.
A guardian statement has now been implemented to address this problem, and the related integration test case has been updated accordingly.
> Fix template type check on ClusterTemplateManager 

- library-udf/src/main/java/org/apache/iotdb/library/dprofile/util/GKArray.java
The bug is caused by the service load failure of MutableListFactoryImpl, which is used by MutableList. Thus, MutableList is replaced by ArrayList to solve the problem.
> [To rel/1.1] [ISSUE-9508] Fix the bug of UDF Median and Percentile

- library-udf/src/main/java/org/apache/iotdb/library/dprofile/util/GKArray.java
The bug is caused by the service load failure of MutableListFactoryImpl, which is used by MutableList. Thus, MutableList is replaced by ArrayList to solve the problem.
> [ISSUE-9508] Fix the bug of UDF Median and Percentile

- server/src/main/java/org/apache/iotdb/db/mpp/common/FragmentInstanceId.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/driver/DriverContext.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/exchange/MPPDataExchangeManager.java
In MemoryPool, FragmentInsatnceId doesn't contain queryId.
And I delete the useless operator Id check in DriverContext, because it will cause O(N^2) time complexity which is a problem while having many PlanNodes.
> Fix a memory free bug and delete useless O(N^2) check in DriverContext

- server/src/main/java/org/apache/iotdb/db/mpp/execution/fragment/FragmentInstanceContext.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/fragment/FragmentInstanceExecution.java
For schema related query FI, `closedFilePaths` and `unClosedFilePaths` in FragmentInstanceContext are null, so while calling `context.releaseResource()` in statemachine callback, it will throw NPE and the remaining codes won't be executed like `deRegisterFragmentInstanceFromMemoryPool` and so on which will cause resource leaky.
And in this pr, I also add the error log while there is exception throwed in the release process.
> Fix Context release source NPE

- integration-test/src/test/java/org/apache/iotdb/db/it/IoTDBFilterIT.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/ExpressionAnalyzer.java
cause: `extractGlobalTimeFilter` forget the case of `constant`
> [IOTDB-5757] Fix Not Supported Exception when use like 's3 || false' in where even Type of s3 is Boolean

- integration-test/src/test/java/org/apache/iotdb/db/it/query/IoTDBNullOperandIT.java
- server/src/main/java/org/apache/iotdb/db/mpp/transformation/dag/column/binary/CompareNonEqualColumnTransformer.java
- server/src/main/java/org/apache/iotdb/db/mpp/transformation/dag/column/binary/LogicBinaryColumnTransformer.java
Cause: method `checkType()` in `CompareNonEqualColumnTransformer` not use the safe TypeCompare method, so when a subExpression type is `null`, NPE occurs. 
Note: `LogicBinaryColumnTransformer` has same question. We don't add it case of it because there is another [bug](https://github.com/apache/iotdb/pull/9543) effects on this case.
> [IOTDB-5756] NPE when where predicate is NotEqualExpression and one of subExpression is not exist

- server/src/main/java/org/apache/iotdb/db/mpp/execution/schedule/DriverScheduler.java
- server/src/test/java/org/apache/iotdb/db/mpp/execution/schedule/DriverSchedulerTest.java
The first task is only a part of FI, so it may finish early. So we should add last task which is the root task of FI to the timeoutQueue.
> [IOTDB-5204 ] Add last task rather than first task to timeoutQueue

- integration-test/src/test/java/org/apache/iotdb/db/it/IoTDBFilterIT.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/ExpressionAnalyzer.java
cp https://github.com/apache/iotdb/pull/9543
> [To rel/1.1][IOTDB-5757] Fix Not Supported Exception when use like 's3 || false' in where even Type of s3 is Boolean

- docs/UserGuide/Reference/Common-Config-Manual.md
- docs/zh/UserGuide/Reference/Common-Config-Manual.md
- node-commons/src/assembly/resources/conf/iotdb-common.properties
- server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
- server/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java
- server/src/main/java/org/apache/iotdb/db/mpp/common/SessionInfo.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/execution/QueryExecution.java
- server/src/main/java/org/apache/iotdb/db/query/control/SessionManager.java
Since v1.0 uses redirection status code 400, which is different with v0.13. We need a strategy to adapt insert data by 0.13 client to v1.0. 
This PR adds a configuration `0.13_data_insert_adapt`. The default value is false. When set `0.13_data_insert_adapt=true`, and the Client Version was set `V_0_13`, the insert redirection info will not return to client side.
Notice: if using v1.0 client or setting Client Version to V_0_13 manually, enable this config will disable insert redirection.
> [To rel/1.1] Adapt insert data by 0.13 client

- server/src/main/java/org/apache/iotdb/db/engine/compaction/cross/rewrite/selector/RewriteCompactionFileSelector.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/inner/sizetiered/SizeTieredCompactionSelector.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/AbstractCompactionTest.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/cross/CrossSpaceCompactionValidationTest.java
Cross space compaction select one unseq file but none seq file, which causes cross compaction under this time partition can never be performed.
**Reason**
Unseq file does not overlap with any seq files under this time partition, including two cases: 1. The devices under the unseq files do not exist in the seq files. 2. The device of the unseq file exists in the seq file, but unseqDevice.startTime>seqDevice.endTime. This can happen if the data is deleted and an seq inner space compaction has been performed.
**Solution**
For nonOverlap unseq files, select the last sealed seq file, if it is valid (status is closed), then select it, otherwise stop the selection.
> [To rel/0.13][IOTDB-5726]Select the last sealed seq file for nonOverlap unseq files to compact in cross compaction

- tsfile/src/main/java/org/apache/iotdb/tsfile/read/common/block/column/ColumnEncoderFactory.java
We can directly use get result of map to judge whether the map contains the key.
> Improve ineffective check in ColumnEncoderFactory

- server/src/main/java/org/apache/iotdb/db/mpp/execution/exchange/sink/ShuffleSinkHandle.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/exchange/sink/SinkChannel.java
After lazy opening SinChannel, `blcoked` future in `SinkChannel` may be null while being aborted or closed because this FI may not be runned while the root FI may encounter error and decide to abort other FIs.
> Fix potential NPE in SinkChannel

- server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/AnalyzeVisitor.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/ConcatPathRewriter.java
- server/src/test/java/org/apache/iotdb/db/mpp/plan/analyze/AnalyzeTest.java
> [IOTDB-5764] Fix that cannot specify alias successfully when the FROM clause contains multiple path suffixes

- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/DataRegion.java
- server/src/main/java/org/apache/iotdb/db/metadata/cache/DataNodeSchemaCache.java
- server/src/test/java/org/apache/iotdb/db/metadata/cache/DataNodeSchemaCacheTest.java
The current updateLastCache interface uses the series path to update the last cache. However, the write thread needs to init a new PartialPath for it, which is meaningless.
> Optimize updateLastCache interface

- server/src/main/java/org/apache/iotdb/db/mpp/execution/exchange/sink/SinkChannel.java
We should only assign value to `bufferRetainedSizeInBytes` in `SinkChannel` after it's opened, otherwise we may encounter NPE while this sinkChannel is aborted before it's opened.
> Fix MemoryPool free NPE

- consensus/pom.xml
cherry-pick of https://github.com/apache/iotdb/pull/9587
> [To rel/1.1] Bump ratis dependency version to 2.5.0

- server/src/main/java/org/apache/iotdb/db/mpp/plan/scheduler/FragmentInstanceDispatcherImpl.java
The elapsed time of the Local Scheduler may be recorded repeatedly on the Performance Overview panel. That is, a timer is recorded even when no instance is executed locally. As a result, the elapsed time may be inaccurate.
> Fix Performance Overview Dashboard localScheduler record inaccurately

- server/src/main/java/org/apache/iotdb/db/mpp/plan/scheduler/FragmentInstanceDispatcherImpl.java
The elapsed time of the Local Scheduler may be recorded repeatedly on the Performance Overview panel. That is, a timer is recorded even when no instance is executed locally. As a result, the elapsed time may be inaccurate.
> [To rel/1.1] Fix Performance Overview Dashboard localScheduler record inaccurately 

- server/src/main/java/org/apache/iotdb/db/metadata/mtree/store/disk/cache/CacheMemoryManager.java
- server/src/main/java/org/apache/iotdb/db/metadata/rescon/MemSchemaEngineStatistics.java
We've implemented ```StampedWriterPreferredLock``` to enable memory release when a flush task is waiting for write lock. However, the priority is not set when release task try taking a read lock. Fix it.
Currently, the variable ```allowToCreateNewSeries``` is not maintained in a thread-safe manner. Use synchronized and double-check to protect it and ensure accuracy.
> [To rel/1.1] Fix SchemaEngine memory control concurrent bug

- server/src/main/java/org/apache/iotdb/db/engine/compaction/selector/impl/RewriteCrossSpaceCompactionSelector.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/selector/utils/CrossSpaceCompactionCandidate.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/cross/CrossSpaceCompactionWithFastPerformerValidationTest.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/cross/CrossSpaceCompactionWithReadPointPerformerValidationTest.java
Cross space compaction select one unseq file but none seq file, which causes cross compaction under this time partition can never be performed.
**Reason**
Unseq file does not overlap with any seq files under this time partition, including two cases: 1. The devices under the unseq files do not exist in the seq files. 2. The device of the unseq file exists in the seq file, but unseqDevice.startTime>seqDevice.endTime. This can happen if the data is deleted and an seq inner space compaction has been performed.
**Solution**
For nonOverlap unseq files, select the last sealed seq file, if it is valid (status is closed), then select it, otherwise stop the selection.
> [To rel/1.1][IOTDB-5726]Select the last sealed seq file for nonOverlap unseq files to compact in cross compaction

- server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/AnalyzeVisitor.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/ConcatPathRewriter.java
- server/src/test/java/org/apache/iotdb/db/mpp/plan/analyze/AnalyzeTest.java
(cherry picked from commit 5b1d362f7bb2c9e79d26777595250d4891aa4f92)
> [To rel/1.1] [IOTDB-5764] Fix that cannot specify alias successfully when the FROM clause contains multiple path suffixes

- integration-test/src/test/java/org/apache/iotdb/db/it/aggregation/IoTDBTagAggregationIT.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/statement/crud/QueryStatement.java
cause: forget to add SemanticCheck
origin jira: https://jira.infra.timecho.com:8443/browse/TIMECHODB-74
content of jira:
Msg: 305: [INTERNAL_SERVER_ERROR(305)] Exception occurred: "select s_19 from root.test.g_0.** where time=1535587210000 group by tags(workshop,city)". executeStatement failed. org.apache.iotdb.db.mpp.plan.expression.leaf.TimeSeriesOperand cannot be cast to org.apache.iotdb.db.mpp.plan.expression.multi.FunctionExpression
测试流程：
启动1C3D ,1副本 IoT协议
benchmark运行附件配置
给序列s_19 add tags
cli 执行查询
./sbin/start-cli.sh -h 172.20.70.2  -e "select s_19 from root.test.g_0.** where time=1535587210000 group by tags(workshop,city);"
Msg: 305: [INTERNAL_SERVER_ERROR(305)] Exception occurred: "select s_19 from root.test.g_0.** where time=1535587210000 group by tags(workshop,city)". …
> Fix unexcepted error message when use raw query with Group By Tag

- server/src/main/java/org/apache/iotdb/db/metadata/mtree/store/disk/cache/CacheMemoryManager.java
- server/src/main/java/org/apache/iotdb/db/metadata/rescon/MemSchemaEngineStatistics.java
- server/src/main/java/org/apache/iotdb/db/metadata/schemaregion/SchemaRegionSchemaFileImpl.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/schema/SchemaCountOperator.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/schema/source/DeviceSchemaSource.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/schema/source/ISchemaSource.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/schema/source/NodeSchemaSource.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/schema/source/PathsUsingTemplateSource.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/schema/source/TimeSeriesSchemaSource.java
When registering timeseries, we usually want to check current registered timeseries num via ```count timeseries```. 
Since there's a statistic value recording the total timeseries num, we can directly return such statistic value without traversing the MTree.
> [To rel/1.1] Accelerate count all schema via schema statistic

- integration-test/src/test/java/org/apache/iotdb/db/it/aggregation/IoTDBTagAggregationIT.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/LogicalPlanBuilder.java
cause: incorrect logicPlan process
origin jira: https://jira.infra.timecho.com:8443/browse/TIMECHODB-73
content of jira: 
版本
master Enterprise version 1.2.0-SNAPSHOT (Build: 71b6bbf)
复现步骤
方法一： 
create timeseries root.test.g_0.tab1.s_0 with datatype=int32;
create timeseries root.test.g_0.tab1.s_1 with datatype=int32;
insert into root.test.g_0.tab1(time,s_0,s_1) values (1,1,1);
alter timeseries root.test.g_0.tab1.s_0 add tags city=beijing;
select count(s_0) ,count(s_1) from root.test.g_0.tab1 group by tags(city);
方法二：
启动1C3D ,1副本 IoT协议
benchmark运行附件配置
给序列s_19 add tags
cli 执行查询
./sbin/start-cli.sh -h 172.20.70.2  -e "select sum(s_19),sum(s_20) from root.test.g_0.** group by tags(city);"
Msg: 301: 2
2023-04-04 13:13:48,613 [Query-Worker-Thread-7$20230404_051348_41492_1.1.0.0] WARN …
> Fix Group By Tag with empty grouped timeseries

- library-udf/Readme.md
- library-udf/pom.xml
- library-udf/src/main/java/org/apache/iotdb/library/anomaly/UDTFKSigma.java
- library-udf/src/main/java/org/apache/iotdb/library/anomaly/UDTFRange.java
- library-udf/src/main/java/org/apache/iotdb/library/anomaly/UDTFTwoSidedFilter.java
- library-udf/src/main/java/org/apache/iotdb/library/dprofile/UDAFMad.java
- library-udf/src/main/java/org/apache/iotdb/library/dprofile/UDAFMedian.java
- library-udf/src/main/java/org/apache/iotdb/library/dprofile/UDAFPercentile.java
- library-udf/src/main/java/org/apache/iotdb/library/dprofile/UDAFQuantile.java
- library-udf/src/main/java/org/apache/iotdb/library/dprofile/UDAFSpread.java
- library-udf/src/main/java/org/apache/iotdb/library/dprofile/UDTFDistinct.java
- library-udf/src/main/java/org/apache/iotdb/library/dprofile/UDTFMvAvg.java
- library-udf/src/main/java/org/apache/iotdb/library/dprofile/UDTFSample.java
- library-udf/src/main/java/org/apache/iotdb/library/dprofile/util/ExactOrderStatistics.java
- library-udf/src/main/java/org/apache/iotdb/library/util/Util.java
The size of UDF-Library jar is about **94MB**, which is extremely and surprisingly large. Since too many useless dependencies are included in the jar package, such a large package is inconvenient for users. With the following optimizations, the size is reduced to only **19MB**.
+ Remove unused dependencies, e.g., **iotdb-session**, **jama**, **java-local-outlier-factor**, **gson**, **iotdb-server**.
+ Replace the remaining *org.apache.iotdb.tsfile.file.metadata.enums.TSDataType* to *org.apache.iotdb.udf.api.type.Type*. Meanwhile, *org.apache.iotdb.commons.udf.utils.UDFDataTypeTransformer* is also removed. Thus, dependency **tsfile** is removed and **node-commons** is changed to much smaller **udf-api**.
> [ISSUE-9611] Reduce the size of UDF-Library jar

- server/src/main/java/org/apache/iotdb/db/engine/compaction/inner/utils/SingleSeriesCompactionExecutor.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/inner/InnerSpaceCompactionUtilsNoAlignedTest.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/recover/SizeTieredCompactionRecoverTest.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/utils/CompactionFileGeneratorUtils.java
See [IOTDB-5662](https://issues.apache.org/jira/browse/IOTDB-5662).
The reason for this bug is that the encoding type of chunks that merged together is different with each other.
> [To rel/0.13] [IOTDB-5662] Fix BufferedUnderflowException occurs in inner space compaction

- server/src/main/java/org/apache/iotdb/db/mpp/plan/execution/QueryExecution.java
When multiple datanodes are started, a request from a client may be distributed to different datanodes. For example, if A client sends A request to datanode A,A may forward the request to dataNode B. If an exception occurs during the execution of the request,A tries again. When the retry occurs,A fails to stop resources.
> Fixed resource stop failure after remote scheduling retry

- server/src/main/java/org/apache/iotdb/db/metadata/mtree/store/disk/schemafile/SchemaFileConfig.java
- server/src/main/java/org/apache/iotdb/db/metadata/mtree/store/disk/schemafile/SegmentedPage.java
- server/src/main/java/org/apache/iotdb/db/metadata/mtree/store/disk/schemafile/pagemgr/PageManager.java
- server/src/test/java/org/apache/iotdb/db/metadata/mtree/schemafile/SchemaFileTest.java
During a flush of `SchemaFile` for numerous Entity/Internal Nodes, a surge in dirty pages occurs due to the pre-allocation mechanism. Retrieval for a suitable `SegmentedPage` may require a full iteration if each of these pages has too little space spare to accommodate another segment. The quadratic time overhead may appear to be stucked while handling a massive number of child nodes, e.g., 10 million child nodes.
An array of LinkedLists has been introduced to index dirty pages into a tiered structure based on their spare size, considering the minimum segment and other step sizes. When a `SegmentedPage` is marked as dirty, it will be integrated into one of the LinkedLists if its spare size is larger than the minimum segment.
Although the size of `pageInstCache` is constrained by the config …
> [To rel/1.1] Resolve quadratic complexity issue when flushing numerous Internal/Entity nodes in SchemaFile

- server/src/main/java/org/apache/iotdb/db/mpp/execution/fragment/FragmentInstanceManager.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/Coordinator.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/schema/ClusterSchemaFetchExecutor.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/execution/IQueryExecution.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/execution/QueryExecution.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/execution/config/ConfigExecution.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/scheduler/ClusterScheduler.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/scheduler/IQueryTerminator.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/scheduler/IScheduler.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/scheduler/SimpleQueryTerminator.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/scheduler/load/LoadTsFileScheduler.java
- server/src/main/java/org/apache/iotdb/db/service/thrift/impl/ClientRPCServiceImpl.java
- server/src/main/java/org/apache/iotdb/db/service/thrift/impl/DataNodeInternalRPCServiceImpl.java
- server/src/main/java/org/apache/iotdb/db/service/thrift/impl/MLNodeRPCServiceImpl.java
- server/src/test/java/org/apache/iotdb/db/mpp/execution/ConfigExecutionTest.java
- server/src/test/java/org/apache/iotdb/db/mpp/execution/operator/MergeSortOperatorTest.java
- thrift/src/main/thrift/datanode.thrift
The current situation where the resultHandle.abort() method is eventually executed when a client request completes, regardless of whether an exception occurred, is not accurate. The right way to release resources is to say,
1. To end a normal operation, run resultHandle.close();
2. To terminate the exception, run resultHandle.abort().
> distinguish whether an exception has occurred when releasing the QueryExecution resource

- server/src/main/java/org/apache/iotdb/db/mpp/execution/fragment/FragmentInstanceManager.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/Coordinator.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/schema/ClusterSchemaFetchExecutor.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/execution/IQueryExecution.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/execution/QueryExecution.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/execution/config/ConfigExecution.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/scheduler/ClusterScheduler.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/scheduler/IQueryTerminator.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/scheduler/IScheduler.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/scheduler/SimpleQueryTerminator.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/scheduler/load/LoadTsFileScheduler.java
- server/src/main/java/org/apache/iotdb/db/service/thrift/impl/ClientRPCServiceImpl.java
- server/src/main/java/org/apache/iotdb/db/service/thrift/impl/DataNodeInternalRPCServiceImpl.java
- server/src/test/java/org/apache/iotdb/db/mpp/execution/ConfigExecutionTest.java
- server/src/test/java/org/apache/iotdb/db/mpp/execution/operator/MergeSortOperatorTest.java
- thrift/src/main/thrift/datanode.thrift
Optimized query request resource release：
1. 
To end a normal operation, run resultHandle.close();
To terminate the exception, run resultHandle.abort().
2.
To end a normal operation, run FragmentInstanceContext.finished();
To terminate the exception,  run FragmentInstanceContext.cancel().
3. 
Reset the stopped flag when retries occur on requests between nodes
> [To rel/1.1] distinguish whether an exception has occurred when releasing the QueryExecution resource

- server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
- server/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/selector/estimator/AbstractCompactionEstimator.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/selector/estimator/ReadPointCrossCompactionEstimator.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/selector/impl/RewriteCrossSpaceCompactionSelector.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/selector/utils/CrossCompactionTaskResource.java
- server/src/main/java/org/apache/iotdb/db/rescon/SystemInfo.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/cross/RewriteCompactionFileSelectorTest.java
1. Update memory estimation of cross space compaction and make it more accurate.
2. Increase the compaction memory control parameter, allowing users to customize the closing or opening of the compaction memory control.
> [IOTDB-5776]Update memory estimation of cross space compaction

- server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
- server/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/selector/estimator/AbstractCompactionEstimator.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/selector/estimator/ReadPointCrossCompactionEstimator.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/selector/impl/RewriteCrossSpaceCompactionSelector.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/selector/utils/CrossCompactionTaskResource.java
- server/src/main/java/org/apache/iotdb/db/rescon/SystemInfo.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/cross/RewriteCompactionFileSelectorTest.java
1. Update memory estimation of cross space compaction and make it more accurate.
2. Increase the compaction memory control parameter, allowing users to customize the closing or opening of the compaction memory control.
> [To rel/1.1][IOTDB-5776]Update memory estimation of cross space compaction

- server/src/assembly/resources/conf/iotdb-engine.properties
- server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
- server/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/cross/rewrite/selector/AbstractCompactionEstimator.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/cross/rewrite/selector/RewriteCompactionFileSelector.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/cross/rewrite/selector/RewriteCrossCompactionEstimator.java
- server/src/main/java/org/apache/iotdb/db/rescon/SystemInfo.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/cross/RewriteCompactionFileSelectorTest.java
1. Update memory estimation of cross space compaction and make it more accurate.
2. Increase the compaction memory control parameter, allowing users to customize the closing or opening of the compaction memory control.
> [To rel/0.13][IOTDB-5776]Update memory estimation of cross space compaction

- server/src/main/java/org/apache/iotdb/db/mpp/execution/schedule/DriverScheduler.java
This pr aims to fix potential deadlock in DriverScheduler caused by concurrently calling abortFramentInstance and toAborted.
See https://apache-iotdb.feishu.cn/docx/KFsvdMwL4orqkCxrdARc37W8nxf for more details.
> [IOTDB-5786] Fix potential deadlock in DriverScheduler

- server/src/main/java/org/apache/iotdb/db/engine/compaction/selector/impl/RewriteCrossSpaceCompactionSelector.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/cross/RewriteCompactionFileSelectorTest.java
The first unseq file is 0 level and it is too large to trigger unseq inner space compaction and cross space compaction.
> [IOTDB-5691] The first level-0 tsfile too large to trigger "Unsequence InnerSpaceComapction" and "CrossSpaceCompaction"

- server/src/main/java/org/apache/iotdb/db/engine/compaction/selector/impl/RewriteCrossSpaceCompactionSelector.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/cross/RewriteCompactionFileSelectorTest.java
The first unseq file is 0 level and it is too large to trigger unseq inner space compaction and cross space compaction.
> [To rel/1.1][IOTDB-5691] The first level-0 tsfile too large to trigger "Unsequence InnerSpaceComapction" and "CrossSpaceCompaction"

- server/src/main/java/org/apache/iotdb/db/mpp/execution/exchange/sink/SinkChannel.java
isFull() of SinkChannel returns its blocked while this blocked could be null if the SinkChannel is closed before it is opened. We need to check whether the blocked is null.
> Fix potential Npe of ShuffleSinkHandle

- server/src/main/java/org/apache/iotdb/db/mpp/execution/exchange/sink/SinkChannel.java
When sinkChannel invokes acknowledgeTsBlock(), bufferRetainedSizeInBytes is reduced first, but free() is not executed within Lock. If close() is called at this time, it will check bufferRetainedSizeInBytes 0 and pass. Then the finished method of fragmentInstance will be invoked, and it will check the memory reserved in memoryPool. But free() is not finished, so it will cause the memory leak exception.
> [IOTDB-5798] Fix concurrent problem when sinkChannel acknowledgeTsBlock() and close()

- server/src/main/java/org/apache/iotdb/db/mpp/execution/exchange/sink/SinkChannel.java
When sinkChannel invokes acknowledgeTsBlock(), bufferRetainedSizeInBytes is reduced first, but free() is not executed within Lock. If close() is called at this time, it will check bufferRetainedSizeInBytes 0 and pass. Then the finished method of fragmentInstance will be invoked, and it will check the memory reserved in memoryPool. But free() is not finished, so it will cause the memory leak exception.
> [To rel/1.1][IOTDB-5798] Fix concurrent problem when sinkChannel acknowledgeTsBlock() and close()

- docs/UserGuide/Reference/Common-Config-Manual.md
- docs/zh/UserGuide/Reference/Common-Config-Manual.md
- node-commons/src/assembly/resources/conf/iotdb-common.properties
- server/src/main/java/org/apache/iotdb/db/audit/AuditLogger.java
- server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
- server/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java
- server/src/main/java/org/apache/iotdb/db/metadata/cache/DataNodeDevicePathCache.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/parser/StatementGenerator.java
- server/src/main/java/org/apache/iotdb/db/protocol/mqtt/MPPPublishHandler.java
- server/src/main/java/org/apache/iotdb/db/protocol/rest/v1/handler/StatementConstructionHandler.java
- server/src/main/java/org/apache/iotdb/db/protocol/rest/v2/handler/StatementConstructionHandler.java
- server/src/main/java/org/apache/iotdb/db/service/thrift/impl/DataNodeInternalRPCServiceImpl.java
- server/src/test/java/org/apache/iotdb/db/metadata/cache/DataNodeDevicePathCacheTest.java
In write process, especially write by insertRecords interface, the PartialPath Object of deviceId may init too many times. This PR is adding a DataNodeDevicePathCache to avoid initialize duplicated PartialPath.
> Add a cache to avoid initialize duplicated device id object in write process

- docs/UserGuide/Reference/Common-Config-Manual.md
- docs/zh/UserGuide/Reference/Common-Config-Manual.md
- node-commons/src/assembly/resources/conf/iotdb-common.properties
- server/src/main/java/org/apache/iotdb/db/audit/AuditLogger.java
- server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
- server/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java
- server/src/main/java/org/apache/iotdb/db/metadata/cache/DataNodeDevicePathCache.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/parser/StatementGenerator.java
- server/src/main/java/org/apache/iotdb/db/protocol/mqtt/MPPPublishHandler.java
- server/src/main/java/org/apache/iotdb/db/protocol/rest/v1/handler/StatementConstructionHandler.java
- server/src/main/java/org/apache/iotdb/db/protocol/rest/v2/handler/StatementConstructionHandler.java
- server/src/main/java/org/apache/iotdb/db/service/thrift/impl/DataNodeInternalRPCServiceImpl.java
- server/src/test/java/org/apache/iotdb/db/metadata/cache/DataNodeDevicePathCacheTest.java
In write process, especially write by insertRecords interface, the PartialPath Object of deviceId may init too many times. This PR is adding a DataNodeDevicePathCache to avoid initialize duplicated PartialPath.
> [To rel/1.1] Add a cache to avoid initialize duplicated device id object in write process

- server/src/main/java/org/apache/iotdb/db/metadata/mtree/store/disk/cache/CacheMemoryManager.java
- server/src/main/java/org/apache/iotdb/db/metadata/schemaregion/SchemaRegionSchemaFileImpl.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/schema/SchemaCountOperator.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/schema/source/DeviceSchemaSource.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/schema/source/ISchemaSource.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/schema/source/NodeSchemaSource.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/schema/source/PathsUsingTemplateSource.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/schema/source/TimeSeriesSchemaSource.java
cherry-pick from #9609 
When registering timeseries, we usually want to check current registered timeseries num via count timeseries.
Since there's a statistic value recording the total timeseries num, we can directly return such statistic value without traversing the MTree.
> Accelerate count all schema via schema statistic

- server/src/main/java/org/apache/iotdb/db/metadata/mtree/store/disk/cache/CacheMemoryManager.java
We've implemented StampedWriterPreferredLock to enable memory release when a flush task is waiting for write lock. However, the priority is not set when release task try taking a read lock. Fix it.
> [IOTDB-5720] Fix release processor fail to release memory due to writer-preferred starvation

- server/src/main/java/org/apache/iotdb/db/metadata/mtree/store/disk/cache/CacheMemoryManager.java
- server/src/main/java/org/apache/iotdb/db/metadata/rescon/MemSchemaEngineStatistics.java
cherry-pick from #9602 
Currently, the variable allowToCreateNewSeries is not maintained in a thread-safe manner. Use synchronized and double-check to protect it and ensure accuracy.
> Double-check protect memory-control boundary to avoid concurrent bug

- antlr/src/main/antlr4/org/apache/iotdb/db/qp/sql/IoTDBSqlParser.g4
- antlr/src/main/antlr4/org/apache/iotdb/db/qp/sql/PathParser.g4
- integration-test/src/test/java/org/apache/iotdb/db/it/IoTDBSyntaxConventionIdentifierIT.java
see IOTDB-5774.
**Before:**
**After:**
> [IOTDB-5774] Fix the syntax that path nodes start or end with a wildcard to fuzzy match is not supported

- integration-test/src/test/java/org/apache/iotdb/db/it/schema/IoTDBExtendTemplateIT.java
- server/src/main/java/org/apache/iotdb/db/metadata/cache/DataNodeTemplateSchemaCache.java
NPE occurs when executing the following instructions.
``` sql
create schema template t1(s1 int32, s2 int32)
create database root.db
set schema template to root.db
insert into root.db.d1(time, s1, s2) values(1, 1, 1)
select s1, s2 into root.::(t1, t2) from root.db.d1
```
When fetch schema from DataNodeTemplateSchemaCache, there's no measurement existence check before taking the measurement from template, and this causes the NPE. 
Add existence check to fix it.
> Fix NPE when using template and executing select into

- antlr/src/main/antlr4/org/apache/iotdb/db/qp/sql/IoTDBSqlParser.g4
- confignode/src/main/java/org/apache/iotdb/confignode/manager/pipe/PipePluginCoordinator.java
- confignode/src/main/java/org/apache/iotdb/confignode/persistence/pipe/PipePluginInfo.java
- confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/pipe/plugin/DropPipePluginProcedure.java
- confignode/src/main/java/org/apache/iotdb/confignode/service/thrift/ConfigNodeRPCServiceProcessor.java
- confignode/src/test/java/org/apache/iotdb/confignode/consensus/request/ConfigPhysicalPlanSerDeTest.java
- confignode/src/test/java/org/apache/iotdb/confignode/persistence/PipeInfoTest.java
- confignode/src/test/java/org/apache/iotdb/confignode/procedure/impl/pipe/plugin/CreatePipePluginProcedureTest.java
- integration-test/src/main/java/org/apache/iotdb/it/env/cluster/AbstractNodeWrapper.java
- node-commons/src/main/java/org/apache/iotdb/commons/pipe/plugin/builtin/BuiltinPipePlugin.java
- node-commons/src/main/java/org/apache/iotdb/commons/pipe/plugin/builtin/connector/DoNothingConnector.java
- node-commons/src/main/java/org/apache/iotdb/commons/pipe/plugin/builtin/processor/DoNothingProcessor.java
- node-commons/src/main/java/org/apache/iotdb/commons/pipe/plugin/meta/ConfigNodePipePluginMetaKeeper.java
- node-commons/src/main/java/org/apache/iotdb/commons/pipe/plugin/meta/DataNodePipePluginMetaKeeper.java
- node-commons/src/main/java/org/apache/iotdb/commons/pipe/plugin/meta/PipePluginMeta.java
- node-commons/src/main/java/org/apache/iotdb/commons/pipe/plugin/meta/PipePluginMetaKeeper.java
- server/src/main/java/org/apache/iotdb/db/mpp/common/header/ColumnHeaderConstant.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/execution/config/executor/ClusterConfigTaskExecutor.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/execution/config/metadata/ShowPipePluginsTask.java
- server/src/main/java/org/apache/iotdb/db/pipe/agent/PipeAgent.java
- server/src/main/java/org/apache/iotdb/db/pipe/agent/plugin/PipePluginAgent.java
- server/src/main/java/org/apache/iotdb/db/service/DataNode.java
The following things are done in this PR:
1. support built-in pipe plugins. do_nothing_processor & do_nothing_connector are added as built-in plugins.
2. allow to create / drop the same function multiple times without errors at PipePluginAgent / PipePluginInfo to adapt the retry policy of the Procedure mechanism.
3. allow to drop a function that is not registered on leader config node so that user can have a chance to change the inconsistant registration state over different config / data nodes.
4. fix ci build error: https://ci-builds.apache.org/job/IoTDB/job/IoTDB-pip-new/job/master/173/console
---
1. 支持内置 Pipe 插件，为内置插件适配了增、删、启动流程
2. 幂等操作支持：允许在 PipePluginAgent / PipePluginInfo 层面对同一个插件进行多次增、删（不对已经注册的插件进行检查，允许 procedure 的多次执行）
3. 创建：仅仅在 coordinator 层面检查是否合规。删除：coordinator …
> [IOTDB-5788] Built-in pipe plug-in management mechanism

- server/src/main/java/org/apache/iotdb/db/mpp/execution/exchange/sink/LocalSinkChannel.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/exchange/sink/ShuffleSinkHandle.java
It is possible that ISink is early closed now, thus we do not need the check for closed state.
> remove check of closed state in ISink

- server/src/main/java/org/apache/iotdb/db/mpp/execution/exchange/MPPDataExchangeManager.java
At first, we add synchronized on decrementGet method to avoid concurrent modification on cnt or we may close the shuffleSinkHandle wrongly. However, using AtomicBoolean is enough to ensure that one channel only decrement the cnt once.
Moreover, adding synchronized on decrementGet method could lead to dead lock. Thread A invokes onFinsh of ISinkLitsener and holds the lock of it. Then A tries to lock the corresponding SinkChannel while Thread B invokes close of SinkChannel first and holds the lock of SinkChannel and then try to lock ISinkListener.
So we need to remove the synchonized keyword on decrementGet method.
> Remove unecessary synchronized on decrementCnt of SinkListener

- server/src/main/java/org/apache/iotdb/db/metadata/cache/DataNodeSchemaCache.java
- server/src/main/java/org/apache/iotdb/db/metadata/cache/DeviceUsingTemplateSchemaCache.java
- server/src/main/java/org/apache/iotdb/db/metadata/cache/TimeSeriesSchemaCache.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/schema/ClusterSchemaFetcher.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/schema/NormalSchemaFetcher.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/schema/TemplateSchemaFetcher.java
- server/src/main/java/org/apache/iotdb/db/service/thrift/impl/DataNodeInternalRPCServiceImpl.java
Currently, the DataNodeSchemaCache manages the timeseries not using template cache and DataNodeTemplateSchemaCache manages devices using template. It is hard to manage the total cache stats when keeping these separated. 
Combine these two cache.
> Combine DataNodeSchemaCache of Template and Non-Template Scenarios 

- node-commons/src/assembly/resources/conf/iotdb-common.properties
- node-commons/src/main/java/org/apache/iotdb/commons/conf/CommonConfig.java
- node-commons/src/main/java/org/apache/iotdb/commons/conf/CommonDescriptor.java
- server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/AnalyzeVisitor.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/execution/QueryExecution.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/load/LoadSingleTsFileNode.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/load/LoadTsFileNode.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/scheduler/load/LoadTsFileDispatcherImpl.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/scheduler/load/LoadTsFileScheduler.java
- Streaming query DataPartition with constraint of TTimePartitionSlotTransmitLimit while loading TsFile.
- Streaming query Schema with constraint of maxLoadingDeviceNumber while loading TsFile.
- Now, you can check loading TsFile progress in datanode log.
such as: Load TsFile %s Successfully, load process [1/10]
- Optimized the dispatching process in multi-replications cases, TsFile pieces will no longer be serialized multiple times, which means faster loading in multi-replications cases.
> [IoTDB-5721] Streaming query DataPartition and Schema while loading TsFile

- server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/utils/executor/readchunk/SingleSeriesCompactionExecutor.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/inner/ReadChunkCompactionPerformerNoAlignedTest.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/utils/CompactionFileGeneratorUtils.java
See [IOTDB-5662](https://issues.apache.org/jira/browse/IOTDB-5662).
The reason for this bug is that the encoding type of chunks that merged together is different with each other.
> [IOTDB-5662] Fix BufferedUnderflowException occurs in inner space compaction

- server/src/main/java/org/apache/iotdb/db/mpp/execution/exchange/MPPDataExchangeManager.java
cherry-picked from 6a8d009
At first, we add synchronized on decrementGet method to avoid concurrent modification on cnt or we may close the shuffleSinkHandle wrongly. However, using AtomicBoolean is enough to ensure that one channel only decrement the cnt once.
Moreover, adding synchronized on decrementGet method could lead to dead lock. Thread A invokes onFinsh of ISinkLitsener and holds the lock of it. Then A tries to lock the corresponding SinkChannel while Thread B invokes close of SinkChannel first and holds the lock of SinkChannel and then try to lock ISinkListener.
So we need to remove the synchonized keyword on decrementGet method.
> [To rel/1.1]Remove unecessary synchronized on decrementCnt of SinkListener

- server/src/main/java/org/apache/iotdb/db/sync/receiver/load/FileLoaderManager.java
The owner file will converted into a Map object. in this
deserialization process, a dangerous function readObject is used.
If device_Owner is a malicious file, it would cause executing
arbitrary code issue in the target database.
> [IOTDB-5482][To rel/0.13]Unsafe deserialize map in Sync Tool

- integration-test/src/test/java/org/apache/iotdb/db/it/schema/IoTDBAutoCreateSchemaIT.java
- integration-test/src/test/java/org/apache/iotdb/db/it/schema/IoTDBCreateAlignedTimeseriesIT.java
- integration-test/src/test/java/org/apache/iotdb/db/it/schema/IoTDBCreateStorageGroupIT.java
- integration-test/src/test/java/org/apache/iotdb/db/it/schema/IoTDBCreateTimeseriesIT.java
- integration-test/src/test/java/org/apache/iotdb/db/it/schema/IoTDBDeactivateTemplateIT.java
- integration-test/src/test/java/org/apache/iotdb/db/it/schema/IoTDBDeleteAlignedTimeseriesIT.java
- integration-test/src/test/java/org/apache/iotdb/db/it/schema/IoTDBDeleteStorageGroupIT.java
- integration-test/src/test/java/org/apache/iotdb/db/it/schema/IoTDBDeleteTimeseriesIT.java
- integration-test/src/test/java/org/apache/iotdb/db/it/schema/IoTDBExtendTemplateIT.java
- integration-test/src/test/java/org/apache/iotdb/db/it/schema/IoTDBMetadataFetchIT.java
- integration-test/src/test/java/org/apache/iotdb/db/it/schema/IoTDBSchemaTemplateIT.java
- integration-test/src/test/java/org/apache/iotdb/db/it/schema/IoTDBSortedShowTimeseriesIT.java
- integration-test/src/test/java/org/apache/iotdb/db/it/schema/IoTDBTagAlterIT.java
- integration-test/src/test/java/org/apache/iotdb/db/it/schema/IoTDBTagIT.java
- integration-test/src/test/java/org/apache/iotdb/session/it/IoTDBSessionSchemaTemplateIT.java
- integration-test/src/test/java/org/apache/iotdb/util/AbstractSchemaIT.java
The ```IoTDBSchemaTemplateIT#testInsertRecordsWithTemplate``` is duplicate with ```IoTDBSessionSchemaTemplateIT#testInsertRecordsWithTemplate```.
Remove the ```IoTDBSchemaTemplateIT#testInsertRecordsWithTemplate``` and add standalone mode and schema file mode to IoTDBSessionSchemaTemplateIT.
> [IOTDB-5841] Remove duplicate schema template IT

- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/DataRegion.java
- server/src/main/java/org/apache/iotdb/db/metadata/cache/DataNodeSchemaCache.java
- server/src/main/java/org/apache/iotdb/db/metadata/cache/TimeSeriesSchemaCache.java
- server/src/main/java/org/apache/iotdb/db/metadata/cache/dualkeycache/IDualKeyCache.java
- server/src/main/java/org/apache/iotdb/db/metadata/cache/dualkeycache/impl/CacheEntryGroupImpl.java
- server/src/main/java/org/apache/iotdb/db/metadata/cache/dualkeycache/impl/DualKeyCacheImpl.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/schema/ClusterSchemaFetcher.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/schema/ISchemaFetcher.java
- server/src/main/java/org/apache/iotdb/db/service/thrift/impl/DataNodeInternalRPCServiceImpl.java
- server/src/test/java/org/apache/iotdb/db/metadata/cache/DataNodeSchemaCacheTest.java
- server/src/test/java/org/apache/iotdb/db/mpp/plan/analyze/FakeSchemaFetcherImpl.java
- server/src/test/java/org/apache/iotdb/db/mpp/plan/plan/distribution/Util.java
Currently, when using template, last cache won't be updated after data insertion since the cache entry hasn't been initialized and cached during schema validation.
Thanks to all related info is present in data insertion plan, we can directly initialize a cache entry and cache the schema and last value.
> Support update last cache for data insertion when using template

- server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/performer/impl/FastCompactionPerformer.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/performer/impl/ReadPointCompactionPerformer.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/utils/MultiTsFileDeviceIterator.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/utils/executor/fast/AlignedSeriesCompactionExecutor.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/utils/writer/AbstractCompactionWriter.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/AbstractCompactionTest.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/FastNonAlignedCrossCompactionTest.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/ReadChunkInnerCompactionTest.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/ReadPointAlignedCrossCompactionTest.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/ReadPointNonAlignedCrossCompactionTest.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/utils/TsFileGeneratorUtils.java
- server/src/test/java/org/apache/iotdb/db/query/reader/series/AlignedSeriesScanLimitOffsetPushDownTest.java
- server/src/test/java/org/apache/iotdb/db/query/reader/series/SeriesScanLimitOffsetPushDownTest.java
- tsfile/src/main/java/org/apache/iotdb/tsfile/read/TsFileSequenceReader.java
- tsfile/src/main/java/org/apache/iotdb/tsfile/read/reader/chunk/AlignedChunkReader.java
- tsfile/src/main/java/org/apache/iotdb/tsfile/read/reader/chunk/ChunkReader.java
- tsfile/src/main/java/org/apache/iotdb/tsfile/write/chunk/AlignedChunkWriterImpl.java
**Bug Description**
1. If the compression method of the aligned value series is different from that of the time series, an error will be reported when decompressing.
2. If the compression method of the aligned value series is different from that of the time series, the target file will be corrupted.
**Reason**
1. When reading the source file, all value columns share an uncompressor, resulting in decompression failure.
2. The compression method of the time column in the alignment timeseries takes the first value column. If the source file is in the order of s0 s1 s2, and during fast compaction, the read order is s1 s0 s2 and then written to the target file in this order, that is , the time column of the original file is actually compressed according to the s0 method, and the newly written …
> [To rel/1.1][IOTDB-5807]Fix decompression error for aligned series in fast compaction

- server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/performer/impl/FastCompactionPerformer.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/performer/impl/ReadPointCompactionPerformer.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/utils/MultiTsFileDeviceIterator.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/utils/executor/fast/AlignedSeriesCompactionExecutor.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/utils/writer/AbstractCompactionWriter.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/AbstractCompactionTest.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/FastNonAlignedCrossCompactionTest.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/ReadChunkInnerCompactionTest.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/ReadPointAlignedCrossCompactionTest.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/ReadPointNonAlignedCrossCompactionTest.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/utils/TsFileGeneratorUtils.java
- server/src/test/java/org/apache/iotdb/db/query/reader/series/AlignedSeriesScanLimitOffsetPushDownTest.java
- server/src/test/java/org/apache/iotdb/db/query/reader/series/SeriesScanLimitOffsetPushDownTest.java
- tsfile/src/main/java/org/apache/iotdb/tsfile/read/TsFileSequenceReader.java
- tsfile/src/main/java/org/apache/iotdb/tsfile/read/reader/chunk/AlignedChunkReader.java
- tsfile/src/main/java/org/apache/iotdb/tsfile/read/reader/chunk/ChunkReader.java
- tsfile/src/main/java/org/apache/iotdb/tsfile/write/chunk/AlignedChunkWriterImpl.java
**Bug Description**
1. If the compression method of the aligned value series is different from that of the time series, an error will be reported when decompressing.
2. If the compression method of the aligned value series is different from that of the time series,  the target file will be corrupted.
**Reason**
1. When reading the source file, all value columns share an uncompressor, resulting in decompression failure.
2. The compression method of the time column in the alignment timeseries takes the first value column. If the source file is in the order of s0 s1 s2, and during fast compaction, the read order is s1 s0 s2 and then written to the target file in this order, that is , the time column of the original file is actually compressed according to the s0 method, and the newly written …
> [IOTDB-5807]Fix decompression error for aligned series in fast compaction

- node-commons/src/assembly/resources/conf/iotdb-common.properties
- server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
Change default parameter values for wal part. See the changes below
```
sync_wal_delay_in_ms=1500
wal_buffer_size_in_byte=33554432
wal_file_size_threshold_in_byte=31457280
wal_buffer_queue_capacity=500
```
> [IOTDB-5704] Change default parameters for wal part

- server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/Analysis.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/AnalyzeVisitor.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/execution/QueryExecution.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/write/InsertRowNode.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/write/InsertRowsNode.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/write/InsertRowsOfOneDeviceNode.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/write/InsertTabletNode.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/statement/crud/InsertBaseStatement.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/statement/crud/InsertMultiTabletsStatement.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/statement/crud/InsertRowStatement.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/statement/crud/InsertRowsOfOneDeviceStatement.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/statement/crud/InsertRowsStatement.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/statement/crud/InsertTabletStatement.java
- server/src/test/java/org/apache/iotdb/db/mpp/plan/plan/node/write/WritePlanNodeSplitTest.java
The previous logic of collect redirect information will calculate the ReplicaSet when set redirectInfo to TsStatus. However, the calculation is already done when get data partition before insert. The logic can be simplified by set RedirectInfo to Analysis and get it when construct TsStatus. 
Before this optimization
After then
> Simplify collect redirect Info logic

- node-commons/src/main/java/org/apache/iotdb/commons/utils/JVMCommonUtils.java
- server/src/assembly/resources/conf/iotdb-datanode.properties
- server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
- server/src/main/java/org/apache/iotdb/db/conf/directories/strategy/SequenceStrategy.java
1. change default multi_dir_strategy to SequenceStrategy
2. fix original bug in SequenceStrategy where one folder won't used if others space is limited
3. use `diskSpaceWarningThreshold` to decide whether a folder is full or not
Tested using 1C1D in fit16 with 1 DataRegion. See the snapshot below. The threshold is set to `0.85` in this test.
> Change default multi_dir_strategy to SequenceStrategy and fix original bug

- server/src/main/java/org/apache/iotdb/db/mpp/common/QueryId.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/schedule/DriverTaskThread.java
- server/src/main/java/org/apache/iotdb/db/mpp/metric/QueryMetricsManager.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/cache/PartitionCache.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/parser/StatementGenerator.java
- server/src/main/java/org/apache/iotdb/db/query/context/QueryContext.java
- server/src/main/java/org/apache/iotdb/db/query/control/clientsession/ClientSession.java
- thrift/src/main/thrift/client.thrift
Specific improvements are as follow:
Using data structure which is more efficient.
Antlr split optimization when using legalPathNodes
Do not execute the method of QueryMetricsManager when metric level is DO_NOTHING
>  [To rel/1.1] [IOTDB-5803] Improve query performance by reducing cpu consuming 

- server/src/main/java/org/apache/iotdb/db/mpp/execution/driver/Driver.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/schedule/AbstractDriverThread.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/execution/QueryExecution.java
1. Using a bool flag to avoid cleaning  ResultHandle up more than once
2. Forbid the query executor thread interrupted by other threads(e.g. timeout detect thread and so on)
3. Avoid TaskRunner destruction on cancel
-   Drivers may leave the TaskRunner thread's interrupt flag set during the course of processing, but doing so should not result in the TaskRunner terminating its own processing loop until the TaskExecutor is closed.
- Instead of allowing the interrupt to terminate the current task runner's loop and re-creating a new runner to replace the interrupted one, we can clear the interrupt flag after each iteration. Otherwise, TaskRunners  that were interrupted would have to replace themselves and end up creating unnecessary threads in the cached threadpool executor in the process.
> Avoid Result Handle clean up twice which will cause NPE

- server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/performer/impl/FastCompactionPerformer.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/task/AbstractCompactionTask.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/task/CrossSpaceCompactionTask.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/task/InnerSpaceCompactionTask.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/utils/executor/fast/AlignedSeriesCompactionExecutor.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/utils/writer/AbstractCompactionWriter.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/AbstractCompactionTest.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/CompactionTaskComparatorTest.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/FastAlignedCrossCompactionTest.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/FastInnerCompactionPerformerTest.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/FastNonAlignedCrossCompactionTest.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/ReadPointAlignedCrossCompactionTest.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/ReadPointNonAlignedCrossCompactionTest.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/cross/CrossSpaceCompactionWithFastPerformerTest.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/cross/CrossSpaceCompactionWithFastPerformerValidationTest.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/cross/CrossSpaceCompactionWithReadPointPerformerValidationTest.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/utils/MultiTsFileDeviceIteratorTest.java
- tsfile/src/main/java/org/apache/iotdb/tsfile/write/chunk/ValueChunkWriter.java
When there is an aligned empty value chunk in the source file, the fast compaction will report that the array is out of bounds.
**Reason**
When there is an aligned empty value chunk in the source file, it will also have corresponding chunkMetadata in the TsFile, but fastCompaction does not judge the empty value chunk when reading chunkMetadata, resulting in subsequent errors.
**Solution**
When reading chunkMetadata, it is necessary to judge whether it is an empty value chunk, and when decomposing a chunk into a page, judge whether it is an empty value page.
> [IOTDB-5825]Fix error in aligned empty value chunk in fast compaction

- server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/performer/impl/FastCompactionPerformer.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/task/AbstractCompactionTask.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/task/CrossSpaceCompactionTask.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/task/InnerSpaceCompactionTask.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/utils/executor/fast/AlignedSeriesCompactionExecutor.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/utils/writer/AbstractCompactionWriter.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/AbstractCompactionTest.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/CompactionTaskComparatorTest.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/FastAlignedCrossCompactionTest.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/FastInnerCompactionPerformerTest.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/FastNonAlignedCrossCompactionTest.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/ReadPointAlignedCrossCompactionTest.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/ReadPointNonAlignedCrossCompactionTest.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/cross/CrossSpaceCompactionWithFastPerformerTest.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/cross/CrossSpaceCompactionWithFastPerformerValidationTest.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/cross/CrossSpaceCompactionWithReadPointPerformerValidationTest.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/utils/MultiTsFileDeviceIteratorTest.java
- tsfile/src/main/java/org/apache/iotdb/tsfile/write/chunk/ValueChunkWriter.java
When there is an aligned empty value chunk in the source file, the fast compaction will report that the array is out of bounds.
**Reason**
When there is an aligned empty value chunk in the source file, it will also have corresponding chunkMetadata in the TsFile, but fastCompaction does not judge the empty value chunk when reading chunkMetadata, resulting in subsequent errors.
**Solution**
When reading chunkMetadata, it is necessary to judge whether it is an empty value chunk, and when decomposing a chunk into a page, judge whether it is an empty value page.
> [To rel/1.1][IOTDB-5825]Fix error in aligned empty value chunk in fast compaction

- node-commons/src/main/java/org/apache/iotdb/commons/utils/JVMCommonUtils.java
- server/src/assembly/resources/conf/iotdb-datanode.properties
- server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
- server/src/main/java/org/apache/iotdb/db/conf/directories/strategy/SequenceStrategy.java
1. change default multi_dir_strategy to SequenceStrategy
2. fix original bug in SequenceStrategy where one folder won't used if others space is limited
3. use `diskSpaceWarningThreshold` to decide whether a folder is full or not
Tested using 1C1D in fit16 with 1 DataRegion. See the snapshot below. The threshold is set to `0.85` in this test.
> [IOTDB-5827][To rel/1.1] Change default multi_dir_strategy to SequenceStrategy and fix original bug #9718

- confignode/src/main/java/org/apache/iotdb/confignode/manager/ClusterSchemaManager.java
- server/src/main/java/org/apache/iotdb/db/metadata/template/ClusterTemplateManager.java
- server/src/main/java/org/apache/iotdb/db/metadata/template/ITemplateManager.java
see IOTDB-5834
```
IoTDB> alter schema template t1 add (s_speed FLOAT encoding=RLE, FLOAT TEXT encoding=PLAIN compression=SNAPPY);
Msg: 507: Template t1 does not exist
IoTDB> show nodes in schema template t1
Msg: 507: Template t1 does not exist
```
> [IOTDB-5834] Fix unclear error msg when querying nonexistent schema template

- server/src/main/java/org/apache/iotdb/db/mpp/execution/schedule/queue/IndexedBlockingQueue.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/schedule/queue/multilevelqueue/MultilevelPriorityQueue.java
[#5832](https://issues.apache.org/jira/browse/IOTDB-5832)
> [To rel/1.1][IOTDB-5832] Fix Bug: The size of readyQueue is negative incorrectly

- confignode/src/main/java/org/apache/iotdb/confignode/manager/ClusterSchemaManager.java
- confignode/src/main/java/org/apache/iotdb/confignode/manager/partition/PartitionManager.java
- confignode/src/main/java/org/apache/iotdb/confignode/persistence/partition/PartitionInfo.java
When executing dropping database during data insertion, the database and data partition will be auto created after the database has been set pre-deleted, which results in unreachable regions since the database schema has been deleted in ClusterSchemaManager by the dropping database task.
Add database pre-deleted check and forbid data insertion to a database being deleted.
> [IOTDB-5831] Fix drop database won't delete totally files in disk during data insertion

- metrics/interface/src/main/java/org/apache/iotdb/metrics/metricsets/jvm/JvmThreadMetrics.java
- metrics/interface/src/main/java/org/apache/iotdb/metrics/metricsets/net/LinuxNetMetricManager.java
- metrics/interface/src/main/java/org/apache/iotdb/metrics/metricsets/net/NetMetrics.java
- server/src/main/java/org/apache/iotdb/db/engine/TsFileMetricManager.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/performer/impl/FastCompactionPerformer.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/performer/impl/ReadChunkCompactionPerformer.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/performer/impl/ReadPointCompactionPerformer.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/task/AbstractCompactionTask.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/task/CompactionTaskSummary.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/utils/executor/readchunk/AlignedSeriesCompactionExecutor.java
- server/src/main/java/org/apache/iotdb/db/service/metrics/FileMetrics.java
See [IOTDB-5828](https://issues.apache.org/jira/browse/IOTDB-5828).
This PR optimize the performance of `JVMThreadMetrics` by caching the result of thread infos, and optimize the performance of `FileMetrics` by counting file in system directory(/proc/[PID]/fd) instead of calling Runtime.exec() in Linux. This PR refactor the way of getting file size and count of temporal files in compaction. The way is changed from updating size incrementally to recording by `CompactionTaskSummary`.
> [IOTDB-5828] Optimize the performance of some parts in metrics, and correcting the metrics count of temporal file size in inner space compaction

- node-commons/src/main/java/org/apache/iotdb/commons/schema/tree/AbstractTreeVisitor.java
- server/src/main/java/org/apache/iotdb/db/metadata/mtree/traverser/Traverser.java
- server/src/main/java/org/apache/iotdb/db/metadata/mtree/traverser/TraverserWithLimitOffsetWrapper.java
- server/src/main/java/org/apache/iotdb/db/metadata/mtree/traverser/basic/DatabaseTraverser.java
- server/src/main/java/org/apache/iotdb/db/metadata/mtree/traverser/basic/EntityTraverser.java
- server/src/main/java/org/apache/iotdb/db/metadata/mtree/traverser/basic/MNodeTraverser.java
- server/src/main/java/org/apache/iotdb/db/metadata/mtree/traverser/basic/MeasurementTraverser.java
- server/src/main/java/org/apache/iotdb/db/mpp/common/schematree/visitor/SchemaTreeDeviceVisitor.java
- server/src/main/java/org/apache/iotdb/db/mpp/common/schematree/visitor/SchemaTreeMeasurementVisitor.java
- server/src/main/java/org/apache/iotdb/db/mpp/common/schematree/visitor/SchemaTreeVisitorWithLimitOffsetWrapper.java
- server/src/test/java/org/apache/iotdb/db/metadata/schemaRegion/SchemaRegionBasicTest.java
When traversing a tree structure, the current algorithm takes an greedy strategy that try match the node with states close to final state as much as possible, but not ensure a node due to match a final state do match a final state.
Add final state check and continue the traversing and state matching process until a candidate node match a final state or check all possible states.
> [IOTDB-5824] Fix show devices with * cannot display satisfied devices

- confignode/src/main/java/org/apache/iotdb/confignode/persistence/executor/ConfigPlanExecutor.java
When dropping database, the database schema shall be removed before database partition table, otherwise the pre-deleted check won't take effect.
> [IOTDB-5831]Fix drop database won't delete totally files in disk during data insertion

- node-commons/src/assembly/resources/conf/iotdb-common.properties
- server/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java
Before this change, the config `minCrossCompactionUnseqFileLevel` cannot be set by configuration file.
1. change config file `iotdb-common.properties`
2. snapshot when DataNode starts
> [To rel/1.1] Add config  min_cross_compaction_unseq_file_level for cross compaction

- server/src/main/java/org/apache/iotdb/db/mpp/plan/scheduler/AsyncPlanNodeSender.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/scheduler/AsyncSendPlanNodeHandler.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/scheduler/FragmentInstanceDispatcherImpl.java
- server/src/main/java/org/apache/iotdb/db/service/thrift/impl/DataNodeInternalRPCServiceImpl.java
- server/src/test/java/org/apache/iotdb/db/service/DataNodeInternalRPCServiceImplTest.java
- thrift/src/main/thrift/datanode.thrift
see [jira](https://issues.apache.org/jira/browse/IOTDB-5840)
> [IOTDB-5840] Enhance the problem that the insertRecords interface may cause the number of threads to balloon when there are too many data regions

- node-commons/src/assembly/resources/conf/iotdb-common.properties
- server/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java
Before this change, the config `minCrossCompactionUnseqFileLevel` cannot be set by configuration file.
1. change config file `iotdb-common.properties`
2. snapshot when DataNode starts
> Add config  min_cross_compaction_unseq_file_level for cross compaction

- server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/exception/CompactionMemoryNotEnoughException.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/task/CrossSpaceCompactionTask.java
- server/src/main/java/org/apache/iotdb/db/rescon/SystemInfo.java
- server/src/test/java/org/apache/iotdb/db/sync/pipedata/BufferedPipeDataQueueTest.java
See [IOTDB-5844](https://issues.apache.org/jira/browse/IOTDB-5844).
To address this issue, we have added a timeout mechanism to the memory allocation step in the compaction process. If sufficient memory is not allocated within a certain amount of time, a CompactionMemoryNotEnoughException will be thrown, an error log will be printed, and the compaction task will be abandoned.
> [To rel/1.1] [IOTDB-5844] Fix compaction module getting stuck

- antlr/src/main/antlr4/org/apache/iotdb/db/qp/sql/IoTDBSqlParser.g4
- antlr/src/main/antlr4/org/apache/iotdb/db/qp/sql/PathParser.g4
- integration-test/src/test/java/org/apache/iotdb/db/it/IoTDBSyntaxConventionIdentifierIT.java
(cherry picked from commit e15a3c770bddb990c6d382e948c23bc22f2755ef)
> [To rel/1.1] [IOTDB-5774] Fix the syntax that path nodes start or end with a wildcard to fuzzy match is not supported

- server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/exception/CompactionMemoryNotEnoughException.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/task/CrossSpaceCompactionTask.java
- server/src/main/java/org/apache/iotdb/db/rescon/SystemInfo.java
See [IOTDB-5844](https://issues.apache.org/jira/browse/IOTDB-5844).
To address this issue, we have added a timeout mechanism to the memory allocation step in the compaction process. If sufficient memory is not allocated within a certain amount of time, a CompactionMemoryNotEnoughException will be thrown, an error log will be printed, and the compaction task will be abandoned.
> [IOTDB-5844] Fix compaction module getting stuck 

- confignode/src/main/java/org/apache/iotdb/confignode/manager/ClusterSchemaManager.java
The DataNode fetched the predeleted database and carries on to create regions, while the database is deleted, which results in the region creation failure.
Add predeleted check on ConfigNode when return database msg to DataNode.
> [IOTDB-5831] Fix create region failure after recreate db

- server/src/main/java/org/apache/iotdb/db/engine/compaction/selector/estimator/AbstractCompactionEstimator.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/selector/estimator/ReadPointCrossCompactionEstimator.java
The memory evaluation for cross space compaction was too large, causing the compaction to get stuck.
**Solution**
After experiments, it is found that the memory evaluation of Reading SeqFile is too large, so it is necessary to accurately evaluate this part of the memory. And the compression ratio is taken from the memory.
**Experiment**
Perform a retest experiment on the source files of this environment. The sequential file size is 1.08G, the unsequential file size is 1.1 G, the totalChunkNum in each file is 60200, each device has 301 alignment timeseries, each timeseries has 2 chunks, and there are 100 devices in total. Execute cross space compaction, actual occupied memory: < 900 M, forced frequent triggering of Full GC, occupied memory < 300 M.
- Originally: calculate …
> [To rel/1.1][IOTDB-5818][Atmos][Compaction]Cross_space compaction of Aligned timeseries is stucked

- server/src/main/java/org/apache/iotdb/db/engine/compaction/selector/estimator/AbstractCompactionEstimator.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/selector/estimator/ReadPointCrossCompactionEstimator.java
The memory evaluation for cross space compaction was too large, causing the compaction to get stuck.
**Solution**
After experiments, it is found that the memory evaluation of Reading SeqFile is too large, so it is necessary to accurately evaluate this part of the memory. And the compression ratio is taken from the memory.
**Experiment**
Perform a retest experiment on the source files of this environment. The sequential file size is 1.08G, the unsequential file size is 1.1 G, the totalChunkNum in each file is 60200, each device has 301 alignment timeseries, each timeseries has 2 chunks, and there are 100 devices in total. Execute cross space compaction, actual occupied memory: < 900 M, forced frequent triggering of Full GC, occupied memory < 300 M.
- Originally: calculate …
> [IOTDB-5818][Atmos][Compaction]Cross_space compaction of Aligned timeseries is stucked

- server/src/main/java/org/apache/iotdb/db/mpp/execution/exchange/SharedTsBlockQueue.java
NPE is caused by early close of ISourceHandle. Details could be found in: https://apache-iotdb.feishu.cn/docx/TcNYdAoU4o3u2oxzf91cY5jcn7c
> [IOTDB-5851] Fix Npe with limit clause

- server/src/main/java/org/apache/iotdb/db/engine/compaction/constant/CompactionTaskStatus.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/constant/CompactionTaskType.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/task/AbstractCompactionTask.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/schedule/CompactionTaskManager.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/schedule/CompactionWorker.java
- server/src/main/java/org/apache/iotdb/db/service/metrics/recorder/CompactionMetricsManager.java
- server/src/main/java/org/apache/iotdb/db/utils/datastructure/FixedPriorityBlockingQueue.java
This PR refactor the way to update compaction task metrics. The previous way to update the metrics is updating the counting value when compaction task is submitted or starts to run, but it could be not accurate because the task submission could fail. This pr change the way of counting task by getting running task list and task waiting queue from task manager, and count them when the metrics framework tries to report the value.
> [To rel/1.1] Refactor compaction task metrics

- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/TsFileResource.java
- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/TsFileResourceList.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/AbstractCompactionTest.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/ReadPointCompactionPerformerTest.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/cross/CrossSpaceCompactionExceptionTest.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/cross/RewriteCrossSpaceCompactionRecoverTest.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/cross/RewriteCrossSpaceCompactionWithFastPerformerTest.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/cross/RewriteCrossSpaceCompactionWithReadPointPerformerTest.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/inner/sizetiered/SizeTieredCompactionRecoverTest.java
- server/src/test/java/org/apache/iotdb/db/engine/storagegroup/TsFileResourceListTest.java
Starting from version 1.0, using the load function to import data and then compact them will result in overlapped data in sequential files.
**Reason**
After version 1.0, using the load function may cause files with the same timestamp to appear in the system, and the version corresponding to the sequential file with the same timestamp is incremented, and the version of the file under a time partition is unique. Compaction use `version` as first sort dimension, resulting in an incorrect order.
**Solution**
Use `timestamp` as first sort dimension and `version` as second sort dimension.
> [To rel/1.1][IOTDB-5859]Compaction error when using Version as first sort dimension

- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/DataRegion.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/write/InsertNode.java
Cherry-pick from PR https://github.com/apache/iotdb/pull/9811
Currently, the Last cache on follower is not used for Last Query. Disabling update last cache on follower can save some memory and improve the write performance on follower node.
> Follower doesn't need to update last cache when using IoT_consensus

- node-commons/src/assembly/resources/conf/iotdb-common.properties
- server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
- server/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java
- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/DataRegion.java
- server/src/main/java/org/apache/iotdb/db/metadata/cache/DataNodeSchemaCache.java
- server/src/main/java/org/apache/iotdb/db/metadata/cache/TimeSeriesSchemaCache.java
- server/src/main/java/org/apache/iotdb/db/metadata/cache/dualkeycache/impl/DualKeyCacheBuilder.java
- server/src/main/java/org/apache/iotdb/db/metadata/cache/dualkeycache/impl/DualKeyCachePolicy.java
- server/src/main/java/org/apache/iotdb/db/metadata/cache/dualkeycache/impl/FIFOCacheEntryManager.java
- server/src/main/java/org/apache/iotdb/db/metadata/mtree/snapshot/MemMTreeSnapshotUtil.java
- server/src/test/java/org/apache/iotdb/db/metadata/cache/dualkeycache/DualKeyCacheTest.java
Currently, DataNodeSchemaCache eviction only support LRU policy, which takes overhead to manage and update cache status every time reaching a cache entry.
In this pr, FIFO policy is implemented. FIFO takes low overhead to manage and update cache status, but takes lower cache hit rate than LRU when there's cache eviction.
> Support FIFO policy for DataNodeSchemaCache Eviction

- confignode/src/main/java/org/apache/iotdb/confignode/conf/ConfigNodeConfig.java
- confignode/src/main/java/org/apache/iotdb/confignode/service/ConfigNode.java
see more information in [IOTDB-5863](https://issues.apache.org/jira/browse/IOTDB-5863)
When starting configNode, its configuration information will now be printed.
> [IOTDB-5863]add configNode configuration information print

- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/DataRegion.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/write/InsertNode.java
https://github.com/apache/iotdb/pull/9821 should disable the last cache on follower. However, that PR has a mistake that would disable the last cache on leader. 
This PR is for fixing it.
> Fix only update last cache on follower

- server/src/main/java/org/apache/iotdb/db/engine/compaction/constant/CompactionTaskStatus.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/constant/CompactionTaskType.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/task/AbstractCompactionTask.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/schedule/CompactionTaskManager.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/schedule/CompactionWorker.java
- server/src/main/java/org/apache/iotdb/db/service/metrics/recorder/CompactionMetricsManager.java
- server/src/main/java/org/apache/iotdb/db/utils/datastructure/FixedPriorityBlockingQueue.java
This PR refactor the way to update compaction task metrics. The previous way to update the metrics is updating the counting value when compaction task is submitted or starts to run, but it could be not accurate because the task submission could fail. This pr change the way of counting task by getting running task list and task waiting queue from task manager, and count them when the metrics framework tries to report the value.
> Refactor compaction task metrics

- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/DataRegion.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/write/InsertNode.java
https://github.com/apache/iotdb/pull/9821 should disable the last cache on follower. However, that PR has a mistake that would disable the last cache on leader.
This PR is for fixing it.
> [To rel/1.1] Fix only update last cache on follower

- server/src/main/java/org/apache/iotdb/db/metadata/cache/DataNodeSchemaCacheMetrics.java
fix the clear of metrics in datanode schema cache
> [IOTDB-5858] fix the clear of metric in datanode schema cache

- server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/utils/CompactionUtils.java
- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/TsFileResource.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/AbstractCompactionTest.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/FastCrossCompactionPerformerTest.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/cross/CrossSpaceCompactionWithFastPerformerValidationTest.java
In order to strengthen the accuracy of compaction, all tsfiles will be checked for time range of devices to determine whether there is overlap. If it is fileTimeIndex, it needs to be upgraded to deviceTimeIndex.
> [IOTDB-5867]Build device time index when validating tsfiles after compaction

- server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/utils/CompactionUtils.java
- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/TsFileResource.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/AbstractCompactionTest.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/FastCrossCompactionPerformerTest.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/cross/CrossSpaceCompactionWithFastPerformerValidationTest.java
In order to strengthen the accuracy of compaction, all tsfiles will be checked for time range of devices to determine whether there is overlap. If it is fileTimeIndex, it needs to be upgraded to deviceTimeIndex.
> [To rel/1.1][IOTDB-5867]Build device time index when validating tsfiles after compaction

- consensus/pom.xml
Upgrade Ratis dependency version to ratis-2.5.2 due to a recent bug fix: https://github.com/apache/ratis/pull/879
The artifacts can be found at https://repository.apache.org/content/groups/snapshots/org/apache/ratis
The git commits mirrors https://github.com/apache/ratis/commits/snapshot-branch2
> Bump Ratis version to 2.5.2-SNAPSHOT

- consensus/pom.xml
Cherry-pick of https://github.com/apache/iotdb/pull/9839
> [To rel/1.1] Bump Ratis version to 2.5.2-SNAPSHOT

- consensus/src/main/java/org/apache/iotdb/consensus/iot/IoTConsensusServerImpl.java
- consensus/src/main/java/org/apache/iotdb/consensus/iot/logdispatcher/LogDispatcher.java
- consensus/src/main/java/org/apache/iotdb/consensus/iot/logdispatcher/SyncStatus.java
- consensus/src/test/java/org/apache/iotdb/consensus/iot/logdispatcher/SyncStatusTest.java
- Change the print length of the index log segment from 1000 to 10000.
- Deleted index persistence when synchronization was completed.
> [IOTDB-5872] Reduce some IoTConsensus index logs

- server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/process/join/HorizontallyConcatOperator.java
- server/src/test/java/org/apache/iotdb/db/mpp/execution/operator/OperatorMemoryTest.java
(cherry picked from commit 10d4eba19434513caa44e8e42c3fc1728dda85a1 #9781)
> [To rel/1.1] [IOTDB-5846] Optimize the memory estimate for HorizontallyConcatOperator

- integration-test/src/test/java/org/apache/iotdb/session/it/IoTDBSessionSchemaTemplateIT.java
- session/src/main/java/org/apache/iotdb/session/Session.java
The null in RPC request cannot be recognized by Thrift, thus resulting in StringIndexOutOfBoundsException.
Add null check in session and return more readable msg.
> [IOTDB-5877] Fix StringIndexOutOfBoundsException when invoking Session.createTimeseriesUsingSchemaTemplate with list contains null

- antlr/src/main/antlr4/org/apache/iotdb/db/qp/sql/IoTDBSqlParser.g4
- integration-test/src/test/java/org/apache/iotdb/db/it/schema/IoTDBSchemaTemplateIT.java
When user cannot define specific measurements before data insertion, it's necessary to set up an empty schema template and auto extend it during data insertion.
Session already support create empty schema template, thus only antlr is modified to support create empty schema template via SQL.
> [IOTDB-5882] Support create empty schema template

- integration-test/src/test/java/org/apache/iotdb/db/it/schema/IoTDBExtendTemplateIT.java
- integration-test/src/test/java/org/apache/iotdb/session/it/IoTDBSessionSchemaTemplateIT.java
- server/src/main/java/org/apache/iotdb/db/metadata/template/alter/TemplateExtendInfo.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/schema/AutoCreateSchemaExecutor.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/execution/config/executor/ClusterConfigTaskExecutor.java
When there's duplicate measurement in one template extension request, there's no exception returned but the request is executed successfully and the registered measurement is the first one.
When extending schema template on configNode, the measurement duplication will be ignored and the first one takes effect.
Add duplication check on dataNode before sending RPC request to configNode.
Add deduplication in template auto extension during data insertion with insert records or tablets or TsFile load.
> [IOTDB-5884] Throw Exception when alter template with duplicate measurement

- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/DataRegion.java
- server/src/main/java/org/apache/iotdb/db/exception/query/OutOfTTLException.java
- server/src/main/java/org/apache/iotdb/db/tools/IoTDBDataDirViewer.java
- server/src/main/java/org/apache/iotdb/db/tools/TsFileResourcePrinter.java
There are some logs and some TsFileTools didn't consider timestamp precision. This PR is for fixing them by using another util function with precision conversion.
> [IOTDB-5888] Fix some logs didn't consider timestamp precision

- node-commons/src/main/java/org/apache/iotdb/commons/path/PartialPath.java
- node-commons/src/main/java/org/apache/iotdb/commons/path/PathPatternNode.java
- node-commons/src/main/java/org/apache/iotdb/commons/path/PathPatternUtil.java
- node-commons/src/main/java/org/apache/iotdb/commons/path/fa/nfa/SimpleNFA.java
- server/src/main/java/org/apache/iotdb/db/engine/memtable/AlignedWritableMemChunkGroup.java
- server/src/main/java/org/apache/iotdb/db/engine/memtable/WritableMemChunkGroup.java
- server/src/main/java/org/apache/iotdb/db/metadata/cache/DataNodeSchemaCache.java
- server/src/main/java/org/apache/iotdb/db/metadata/cache/DeviceUsingTemplateSchemaCache.java
- server/src/main/java/org/apache/iotdb/db/metadata/template/ClusterTemplateManager.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/schema/ClusterSchemaFetchExecutor.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/schema/ClusterSchemaFetcher.java
Currently, a device using schema template may be cached in DataNodeSchemaCache, but the cache is only used for data insertion.
Enable data query to benefit from such device cache when querying all measurements of the device, e.g. select * from root.db.d, with schema template t1 set on db.
> Support schema cache when querying all measurement of devices using template

- server/src/test/java/org/apache/iotdb/db/engine/compaction/cross/CrossSpaceCompactionSelectorTest.java
The reason for compilation failure is that the `TsFileResourceStatus.CLOSED` is changed to `TsFileResourceStatus.NORMAL`.
> [hotfix] fix compilation issue

- integration-test/src/test/java/org/apache/iotdb/db/it/aligned/IoTDBAlignedDataDeletionIT.java
- server/src/main/java/org/apache/iotdb/db/utils/datastructure/AlignedTVList.java
- server/src/test/java/org/apache/iotdb/db/utils/datastructure/VectorTVListTest.java
To reproduce:
```sql
insert into root.vehicle.d0(time,s0) aligned values (10,310)
insert into root.vehicle.d0(time,s3) aligned values (10,'text')
insert into root.vehicle.d0(time,s4) aligned values (10,true)
DELETE FROM root.vehicle.d0.s3
```
> [IOTDB-5896] Fix delete aligned TEXT data in TVList NPE

- server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/utils/MultiTsFileDeviceIterator.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/inner/ReadChunkCompactionPerformerAlignedTest.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/utils/CompactionCheckerUtils.java
See [IOTDB-5897](https://issues.apache.org/jira/browse/IOTDB-5897).
The reason for this bug is that when reading chunk that contains 0 points, the list will set the chunk metadata to null.
> [To rel/1.1][IOTDB-5897] Fix NullPointerException in compaction

- confignode/src/main/java/org/apache/iotdb/confignode/manager/ConfigManager.java
- confignode/src/main/java/org/apache/iotdb/confignode/manager/load/LoadManager.java
- confignode/src/main/java/org/apache/iotdb/confignode/manager/pipe/PipeRuntimeCoordinator.java
- confignode/src/main/java/org/apache/iotdb/confignode/persistence/pipe/PipeTaskInfo.java
- node-commons/src/main/java/org/apache/iotdb/commons/pipe/task/meta/PipeMetaKeeper.java
Fix the bug that loadManager initialization fail, by bringing its initialization to the bottom.
Related to [IOTDB-5845] Pipe: Support handling leader change in PipeRuntimeCoordinator.
> [IOTDB-5845] Failed to register PipeRuntimeCoordinator to loadPublisher in LoadManager

- server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/utils/MultiTsFileDeviceIterator.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/inner/ReadChunkCompactionPerformerAlignedTest.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/utils/CompactionCheckerUtils.java
See [IOTDB-5897](https://issues.apache.org/jira/browse/IOTDB-5897).
The reason for this bug is that when reading chunk that contains 0 points, the list will set the chunk metadata to null.
> [IOTDB-5897] Fix NullPointerException in compaction

- integration-test/src/test/java/org/apache/iotdb/db/it/schema/IoTDBDeactivateTemplateIT.java
- server/src/main/java/org/apache/iotdb/db/metadata/mtree/ConfigMTree.java
see [IOTDB-5899](https://issues.apache.org/jira/browse/IOTDB-5899)
When traversing the ConfigMTree to get template set info, paths matched by given pattern but not set template on do be collected and the id=-1, representing NON_TEMPLATE , is collected, which results in the TemplateNotExistException.
Fix the check of template usage when traversing ConfigMTree.
> [IOTDB-5899] Fix unexpected TemplateNotExistException when deactivating template

- integration-test/src/test/java/org/apache/iotdb/db/it/IOTDBLoadTsFileIT.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/load/LoadSingleTsFileNode.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/scheduler/load/LoadTsFileScheduler.java
Problems:
load a  tsfile without data will throw NPE
java.lang.NullPointerException: null
at org.apache.iotdb.commons.partition.StorageExecutor.getDataNodeLocation(StorageExecutor.java:39)
at org.apache.iotdb.db.mpp.plan.planner.plan.FragmentInstance.setExecutorAndHost(FragmentInstance.java:107)
at org.apache.iotdb.db.mpp.plan.scheduler.load.LoadTsFileScheduler.loadLocally(LoadTsFileScheduler.java:319)
at org.apache.iotdb.db.mpp.plan.scheduler.load.LoadTsFileScheduler.start(LoadTsFileScheduler.java:140)
at org.apache.iotdb.db.mpp.plan.execution.QueryExecution.schedule(QueryExecution.java:305)
at org.apache.iotdb.db.mpp.plan.execution.QueryExecution.start(QueryExecution.java:219)
at org.apache.iotdb.db.mpp.plan.Coordinator.execute(Coordinator.java:161)
at …
> [IOTDB-5901][To rel/1.1] Load: load tsfile without data will throw NPE

- server/src/main/java/org/apache/iotdb/db/engine/compaction/schedule/CompactionScheduler.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/schedule/CompactionTaskManager.java
- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/DataRegion.java
- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/TsFileManager.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/inner/sizetiered/SizeTieredCompactionSelectorTest.java
See [IOTDB-5903](https://issues.apache.org/jira/browse/IOTDB-5903).
The reason is that when getting time partitions from TsFileManager, it will only return the time partitions that contains sequence data.
> [To rel/1.1] [IOTDB-5903] Fix cannot select any inner space compaction task when there is only unsequence data

- integration-test/src/main/java/org/apache/iotdb/it/utils/TsFileGenerator.java
- integration-test/src/test/java/org/apache/iotdb/db/it/IOTDBLoadTsFileIT.java
- node-commons/src/assembly/resources/conf/iotdb-common.properties
- node-commons/src/main/java/org/apache/iotdb/commons/conf/CommonConfig.java
- node-commons/src/main/java/org/apache/iotdb/commons/conf/CommonDescriptor.java
- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/DataRegion.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/load/LoadSingleTsFileNode.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/scheduler/load/LoadTsFileScheduler.java
Cherry-picked from rel/1.1. @yschengzi 
- [IOTDB-5869] Load strategy: load all files to unsequence dir (#9837)
- [IOTDB-5721] Delete TTimePartitionSlotTransmitLimit from iotdb-common.properties (#9863)
- [IOTDB-5901] Load: load tsfile without data will throw NPE (#9894)
> [IOTDB-5869][IOTDB-5721][IOTDB-5901] Load strategy: load all files to unsequence dir

- node-commons/src/main/java/org/apache/iotdb/commons/path/PathPatternTree.java
- node-commons/src/test/java/org/apache/iotdb/commons/path/PathPatternTreeTest.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/AnalyzeVisitor.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/parser/ASTVisitor.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/statement/crud/QueryStatement.java
> [To rel/1.1] [IOTDB-5887] Optimize the construction performance of PathPatternTree without wildcards

- server/src/main/java/org/apache/iotdb/db/engine/compaction/schedule/CompactionScheduler.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/schedule/CompactionTaskManager.java
- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/DataRegion.java
- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/TsFileManager.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/inner/sizetiered/SizeTieredCompactionSelectorTest.java
See [IOTDB-5903](https://issues.apache.org/jira/browse/IOTDB-5903).
The reason is that when getting time partitions from TsFileManager, it will only return the time partitions that contains sequence data.
> [IOTDB-5903] Fix cannot select any inner space compaction task when there is only unsequence data

- integration-test/src/test/java/org/apache/iotdb/confignode/it/IoTDBConfigNodeConsensusEfficiencyIT.java
Waiting for https://issues.apache.org/jira/browse/IOTDB-5906 to fix this IT bug
> [IOTDB-5909] Ignore IoTDBConfigNodeConsensusEfficiencyIT temporary

- server/src/assembly/resources/tools/tsfile/print-iotdb-data-dir.bat
- server/src/assembly/resources/tools/tsfile/print-iotdb-data-dir.sh
- server/src/main/java/org/apache/iotdb/db/tools/IoTDBDataDirViewer.java
In V1.1.0:
```
$ ./tools/tsfile/print-iotdb-data-dir.sh  ~/Documents/iotdb/data/datanode/data/
Starting Printing the IoTDB Data Directory Overview
output save path:IoTDB_data_dir_overview.txt
data dir num:1
113  [main] WARN  o.a.i.t.c.conf.TSFileDescriptor - not found iotdb-common.properties, use the default configs. 
Exception in thread "main" java.io.IOException: Irregular data dir structure.There should be a sequence and unsequence directory under the data directory data
at org.apache.iotdb.db.tools.IoTDBDataDirViewer.main(IoTDBDataDirViewer.java:63)
```
After this fixing:
```
$ ./print-iotdb-data-dir.sh ~/Documents/iotdb/data/datanode/data/
Starting Printing the IoTDB Data Directory Overview
output …
```
> [IOTDB-5911] Fix print-iotdb-data-dir tool cannot work

- node-commons/src/main/java/org/apache/iotdb/commons/service/metric/enums/Metric.java
- server/src/main/java/org/apache/iotdb/db/mpp/metric/DataExchangeCountMetricSet.java
cause: DataExchange metric has different num of Tags
> [IOTDB-5908] Fix some query metrics not effect

- server/src/main/java/org/apache/iotdb/db/mpp/plan/scheduler/FixedRateFragInsStateTracker.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/scheduler/IFragInstanceStateTracker.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/scheduler/SimpleQueryTerminator.java
cherry-pick https://github.com/apache/iotdb/commit/12d67e08c559b6860b402de8a65aacc71ffc9ce3
> Avoid rpc invoking for SimpleQueryTerminator when endpoint is local address

- antlr/src/main/antlr4/org/apache/iotdb/db/qp/sql/IoTDBSqlParser.g4
- server/src/main/java/org/apache/iotdb/db/metadata/query/reader/SchemaReaderLimitOffsetWrapper.java
- server/src/main/java/org/apache/iotdb/db/mpp/common/header/ColumnHeaderConstant.java
- server/src/main/java/org/apache/iotdb/db/mpp/common/header/DatasetHeaderFactory.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/schema/source/LogicalViewSchemaSource.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/schema/source/SchemaSourceFactory.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/AnalyzeVisitor.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/parser/ASTVisitor.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/LogicalPlanBuilder.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/LogicalPlanVisitor.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/OperatorTreeGenerator.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/PlanNodeType.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/metedata/read/LogicalViewSchemaScanNode.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/statement/StatementVisitor.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/statement/metadata/view/ShowLogicalViewStatement.java
```
IoTDB> insert into root.db.d(time, s1, s2) aligned values(1, 1, 1)
IoTDB> create view root.view.d(s1, s2) as select s1, s2 from root.db.d
IoTDB> create view root.view.d.s3 as select s1+s2 from root.db.d
IoTDB> create view root.view.d.s4 as select (s1+s2)/2 from root.db.d
IoTDB> show view
+--------------+---------+--------+----+----------+--------+---------------------------------+
|    Timeseries| Database|DataType|Tags|Attributes|ViewType|                           Source|
+--------------+---------+--------+----+----------+--------+---------------------------------+
|root.view.d.s3|root.view|        |null| …
```
> Support Show View

- server/src/main/java/org/apache/iotdb/db/metadata/mnode/mem/info/BasicMNodeInfo.java
- server/src/main/java/org/apache/iotdb/db/metadata/schemaregion/SchemaRegionMemoryImpl.java
The memory control is missed when creating timeseries using schema template, which results in unlimited memory usage.
Add memory status check.
> Fix memory control when creating timeseries using schema template

- confignode/src/main/java/org/apache/iotdb/confignode/conf/ConfigNodeConfig.java
- confignode/src/main/java/org/apache/iotdb/confignode/conf/SystemPropertiesUtils.java
- confignode/src/main/java/org/apache/iotdb/confignode/manager/load/balancer/partition/GreedyPartitionAllocator.java
- confignode/src/main/java/org/apache/iotdb/confignode/manager/partition/PartitionManager.java
- confignode/src/main/java/org/apache/iotdb/confignode/persistence/partition/DatabasePartitionTable.java
- confignode/src/main/java/org/apache/iotdb/confignode/persistence/partition/PartitionInfo.java
- integration-test/src/test/java/org/apache/iotdb/confignode/it/partition/IoTDBPartitionInheritPolicyIT.java
- node-commons/src/assembly/resources/conf/iotdb-common.properties
- node-commons/src/main/java/org/apache/iotdb/commons/partition/DataPartitionTable.java
- node-commons/src/main/java/org/apache/iotdb/commons/partition/SeriesPartitionTable.java
We've found in real production environment that queries across different DataRegionGroups are time-consuming. Therefore we should enable and enhance the DataPartition inherit policy. The new created DataPartition will inherit its neighbor(predecessor or successor)'s allocate result if the neighbor is allocated before.
> [IOTDB-5929] Enable DataPartition inherit policy

- confignode/src/main/java/org/apache/iotdb/confignode/conf/ConfigNodeConfig.java
- confignode/src/main/java/org/apache/iotdb/confignode/conf/SystemPropertiesUtils.java
- confignode/src/main/java/org/apache/iotdb/confignode/manager/load/balancer/partition/GreedyPartitionAllocator.java
- confignode/src/main/java/org/apache/iotdb/confignode/manager/partition/PartitionManager.java
- confignode/src/main/java/org/apache/iotdb/confignode/persistence/partition/DatabasePartitionTable.java
- confignode/src/main/java/org/apache/iotdb/confignode/persistence/partition/PartitionInfo.java
- integration-test/src/test/java/org/apache/iotdb/confignode/it/partition/IoTDBPartitionInheritPolicyIT.java
- node-commons/src/assembly/resources/conf/iotdb-common.properties
- node-commons/src/main/java/org/apache/iotdb/commons/partition/DataPartitionTable.java
- node-commons/src/main/java/org/apache/iotdb/commons/partition/SeriesPartitionTable.java
We've found in real production environment that queries across different DataRegionGroups are time-consuming. Therefore we should enable and enhance the DataPartition inherit policy. The new created DataPartition will inherit its neighbor(predecessor or successor)'s allocate result if the neighbor is allocated before.
> [To rel/1.1][IOTDB-5929] Enable DataPartition inherit policy

- node-commons/src/assembly/resources/conf/iotdb-common.properties
- server/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java
The lastcache parameter in ```schema_memory_allocate_proportion``` is useless, thus should be removed. 
Besides, we need to keep compatible with previous properties file.
Introduce new config ```schema_memory_proportion```, which keep consistency with other parameters on naming style and only cover schema region, schema cache and partition cache. 
The old config ```schema_memory_allocate_proportion``` is removed from properties file, but still can take effect if an IoTDB is upgrade from previous version.
> Update schema memory control config

- node-commons/src/main/java/org/apache/iotdb/commons/schema/view/LogicalViewSchema.java
- server/src/main/java/org/apache/iotdb/db/exception/metadata/view/InsertNonWritableViewException.java
- server/src/main/java/org/apache/iotdb/db/metadata/cache/TimeSeriesSchemaCache.java
- server/src/main/java/org/apache/iotdb/db/metadata/plan/schemaregion/result/ShowTimeSeriesResult.java
- server/src/main/java/org/apache/iotdb/db/metadata/tag/TagManager.java
- server/src/main/java/org/apache/iotdb/db/mpp/common/header/ColumnHeaderConstant.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/schema/SchemaQueryScanOperator.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/schema/source/DeviceSchemaSource.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/schema/source/ISchemaSource.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/schema/source/LogicalViewSchemaSource.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/schema/source/NodeSchemaSource.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/schema/source/PathsUsingTemplateSource.java
- server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/schema/source/TimeSeriesSchemaSource.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/AnalyzeVisitor.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/execution/config/executor/ClusterConfigTaskExecutor.java
```
IoTDB> create timeseries root.abcd.d01.s01 INT32 encoding=RLE;
IoTDB> CREATE VIEW root.abcd.device.temp AS root.abcd.d01.s01;
IoTDB> create timeseries root.abcd.d01.s02 FLOAT encoding=RLE;
IoTDB> CREATE VIEW root.abcd.device.temp2 AS SELECT (s01+s02) FROM root.abcd.d01;
IoTDB>
IoTDB> show timeseries root.**;
+----------------------+-----+---------+--------+--------+-----------+----+----------+--------+------------------+--------+
|            Timeseries|Alias| Database|DataType|Encoding|Compression|Tags|Attributes|Deadband|DeadbandParameters|ViewType| …
```
> support show data types of views; fix some bugs.

- server/src/main/java/org/apache/iotdb/db/pipe/agent/runtime/PipeRuntimeAgent.java
- server/src/main/java/org/apache/iotdb/db/pipe/core/collector/realtime/PipeRealtimeDataRegionHybridCollector.java
- server/src/main/java/org/apache/iotdb/db/pipe/core/collector/realtime/PipeRealtimeDataRegionLogCollector.java
- server/src/main/java/org/apache/iotdb/db/pipe/core/collector/realtime/PipeRealtimeDataRegionTsFileCollector.java
- server/src/main/java/org/apache/iotdb/db/pipe/core/connector/impl/iotdb/v1/IoTDBThriftReceiverV1.java
- server/src/main/java/org/apache/iotdb/db/pipe/core/event/EnrichedEvent.java
- server/src/main/java/org/apache/iotdb/db/pipe/core/event/realtime/PipeRealtimeCollectEvent.java
- server/src/main/java/org/apache/iotdb/db/pipe/resource/wal/PipeWALResourceManager.java
- server/src/main/java/org/apache/iotdb/db/pipe/task/subtask/PipeConnectorSubtask.java
- server/src/main/java/org/apache/iotdb/db/pipe/task/subtask/PipeSubtask.java
- fix bugs in PipeWALResourceManager: Concurrent modification exception when check WAL TTL
- fix bugs in EnrichedEvent: PipeRealtimeCollectEvent reference count error
- fix bugs in IoTDBThriftReceiverV1: Writer stream closed because of tsfile with the same name
- add log when reporting PipeException
> [IOTDB-5942] Pipe: Fix bugs in PipeWALResourceManager, EnrichedEvent, IoTDBThriftReceiverV1

- confignode/src/main/java/org/apache/iotdb/confignode/conf/ConfigNodeConfig.java
- confignode/src/main/java/org/apache/iotdb/confignode/conf/SystemPropertiesUtils.java
- confignode/src/main/java/org/apache/iotdb/confignode/manager/partition/PartitionManager.java
- integration-test/src/test/java/org/apache/iotdb/confignode/it/partition/IoTDBPartitionGetterIT.java
- integration-test/src/test/java/org/apache/iotdb/confignode/it/utils/ConfigNodeTestUtils.java
- node-commons/src/assembly/resources/conf/iotdb-common.properties
Based on our [experimental results](https://apache-iotdb.feishu.cn/docx/YRsHdu7vJoKe88xpW5hckhWsnjh), the following two optimizations are carried out:
1. Set series_slot_num=1000
2. The getOrCreatePartition() interface checks again to see if the partition exists after acquiring the serial lock
> [To rel/1.1][IOTDB-5934] Optimize cluster partition policy

- server/src/main/java/org/apache/iotdb/db/mpp/execution/schedule/DriverScheduler.java
Wrapping clearDriverTask with task.lock() may lead to deadlock. For example: 
Thread A locks a task and then try to remove it from a SynchronizedSet(instance relatedtasks) which will try to get the lock of SynchronizedSet.
Thread B locks the SynchronizedSet first and then tries to lock the task.
> Remove unnecessary lock in runningToFinshed of DriverScheduler

- server/src/main/java/org/apache/iotdb/db/mpp/execution/schedule/DriverScheduler.java
Wrapping clearDriverTask with task.lock() may lead to deadlock. For example:
Thread A locks a task and then try to remove it from a SynchronizedSet(instance relatedtasks) which will try to get the lock of SynchronizedSet.
Thread B locks the SynchronizedSet first and then tries to lock the task.
> [To rel/1.1] Remove unnecessary lock in runningToFinshed of DriverScheduler

- iotdb-client/client-py/iotdb/sqlalchemy/IoTDBSQLCompiler.py
- iotdb-client/client-py/setup.py
The current IoTDBSQLCompiler implementation under the SQLAlchemy package is dependent on the version of SQLAlchemy. The original version was based on a 1.3 code implementation. However, many open source libraries (e.g. Superset) require that the SQLAlchemy version is 1.4 or higher. In order to adapt to the version requirements, this PR has been updated based on the source code of SQLAlchemy(https://github.com/sqlalchemy/sqlalchemy/blob/rel_1_4/lib/sqlalchemy/sql/compiler.py).
> [PyClient] Update SQLAlchemy version to 1.4

- server/src/main/java/org/apache/iotdb/db/utils/DateTimeUtils.java
DataTimeUtils.convertLongToData didn't handle time precision correctly.
> Fix DataTimeUtils convertLongToData bug

- server/src/main/java/org/apache/iotdb/db/mpp/execution/exchange/SharedTsBlockQueue.java
> [To rel/1.1][IOTDB-5963] Make sure that TsBlock blocked on memory is added in queue before the next TsBlock returned by root operator

- server/src/main/java/org/apache/iotdb/db/service/metrics/FileMetrics.java
The reason is the map in FileMetrics is not concurrent-safe type.
> [To rel/1.2] Fix ConcurrentModificationException in updating FileMetrics

- node-commons/src/main/java/org/apache/iotdb/commons/conf/CommonConfig.java
- node-commons/src/main/java/org/apache/iotdb/commons/utils/FileUtils.java
- node-commons/src/main/java/org/apache/iotdb/commons/utils/PathUtils.java
- server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
Current addDataHomeDir method in the IoTDBConfig cannot fulfill its responsibilities. We should get canonical path when using IOTDB_DATA_HOME and IOTDB_HOME
> Get canonical path when using IOTDB_DATA_HOME and IOTDB_HOME

- server/src/main/java/org/apache/iotdb/db/pipe/core/connector/impl/iotdb/v1/request/PipeTransferInsertNodeReq.java
See IOTDB-5965 for more details.
> [IOTDB-5965] Pipe: failed to transfer insert node when using schema template

- server/src/main/java/org/apache/iotdb/db/mpp/common/schematree/ClusterSchemaTree.java
- server/src/test/java/org/apache/iotdb/db/mpp/common/schematree/ClusterSchemaTreeTest.java
When constructing a SchemaTree, there's mistake on setting value ```hasViewMeasurement```, which results in the useless check in query without view.
Fix ```hasViewMeasurement``` updation.
> [To rel/1.2] Fix SchemaTree.hasView check during query analysis

- docs/UserGuide/Reference/Common-Config-Manual.md
- docs/zh/UserGuide/Reference/Common-Config-Manual.md
- node-commons/src/assembly/resources/conf/iotdb-common.properties
Since the schema_file mode of schema engine is ready for release, add schema_ engine_mode config to iotdb-commons.properties and User-Guide.
reference https://apache-iotdb.feishu.cn/docx/RcPzdulXuozjzCx8GrCccVT6nph
> [To rel/1.2] Add schema_ engine_mode config to iotdb-commons.properties and User-Guide

- confignode/src/main/java/org/apache/iotdb/confignode/service/ConfigNode.java
- server/src/assembly/resources/sbin/start-datanode.bat
- server/src/main/java/org/apache/iotdb/db/service/DataNode.java
1. Change default charset encoding to UTF-8 in `start-datanode.bat`
2. Add log when DataNode/ConfigNode starts to print the default charset
NOTICE: Before this change, the explicit setting has only been added in `start-confignode.bat`. To keep the setting is consistent between DataNode and ConfigNode, we add the explicit charset encoding setting in script for windows.
> [To rel/1.1] Change default charset encoding to UTF-8 in start-datanode.bat 

- server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/AnalyzeVisitor.java
- site/src/main/.vuepress/sidebar/V1.0.x/en.ts
- site/src/main/.vuepress/sidebar/V1.0.x/zh.ts
- site/src/main/.vuepress/sidebar/V1.1.x/en.ts
- site/src/main/.vuepress/sidebar/V1.1.x/zh.ts
- site/src/main/.vuepress/sidebar/V1.2.x/en.ts
- site/src/main/.vuepress/sidebar/V1.2.x/zh.ts
- site/src/main/.vuepress/sidebar/en.ts
- site/src/main/.vuepress/sidebar/zh.ts
This pr fix the info when the sortkey doesn't exist and fix the docs in site of order by.
The original output in normal query:
```md
IoTDB> select soc,vehicle_status from root.sg.beijing.car01 order by s1
Msg: 701: One sort item in order by should only indicate one value
```
In last query:
```md
IoTDB> select last soc,vehicle_status from root.sg.beijing.car01 order by s1
Msg: 301: ComparatorChains must contain at least one Comparator
```
Which won't show the info about the problem of sortKey, after this pr the info should be:
```md
IoTDB> select soc,vehicle_status from root.sg.beijing.car01 order by s1
Msg: 701: root.**.s1 in order by clause doesn't exist.
```
```md
IoTDB> select soc,vehicle_status from root.** order by soc
Msg: 701: root.**.soc in order by clause shouldn't refer to more …
```
> [IOTDB-5970] Fix the info of order by when sortkey doesn't exist

- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/TsFileProcessor.java
- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/TsFileResource.java
- server/src/test/java/org/apache/iotdb/db/engine/settle/SettleRequestHandlerTest.java
- server/src/test/java/org/apache/iotdb/db/engine/storagegroup/DataRegionTest.java
This bug will cause TsfileResource contains a device with endTime=Long.minValue. 
To reproduce, execute the following sql:
```
insert into root.sg.d1(time,s1) values(1,2)
insert into root.sg.d2(time,s1) values(1,2)
insert into root.sg.d3(time,s1) values(1,2)
delete from root.sg.d2.*
flush
```
Then use TsFileResourcePrinter to print the resource file.
```
Analyzing /Users/ht/Documents/iotdb/data/datanode/data/sequence/root.sg/2/0/1685960618341-1-0-0.tsfile ...
Resource plan index range [9223372036854775807, -9223372036854775808]
device root.sg.d2, start time 1 (1970-01-01T08:00:00.001), end time -9223372036854775808 (-292275055-05-17T00:52:47.192)
device root.sg.d3, start time 1 (1970-01-01T08:00:00.001), end time 1 (1970-01-01T08:00:00.001)
Analyzing the resource file folder …
```
> Fix TsfileResource error after delete device in sequence working memtable

- confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/pipe/AbstractOperatePipeProcedureV2.java
- confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/pipe/task/CreatePipeProcedureV2.java
- confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/pipe/task/DropPipeProcedureV2.java
- confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/pipe/task/StartPipeProcedureV2.java
- confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/pipe/task/StopPipeProcedureV2.java
- server/src/main/java/org/apache/iotdb/db/service/thrift/impl/DataNodeInternalRPCServiceImpl.java
Made the log printed more specified when pushing pipe meta in pipe procedures.
<hr>
This PR has:
<hr>
> [IOTDB-5976] Pipe: optimized the feedback when pipe procedure failed to pushPipeMetas

- confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/pipe/AbstractOperatePipeProcedureV2.java
- confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/pipe/task/CreatePipeProcedureV2.java
- confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/pipe/task/DropPipeProcedureV2.java
- confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/pipe/task/StartPipeProcedureV2.java
- confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/pipe/task/StopPipeProcedureV2.java
- server/src/main/java/org/apache/iotdb/db/service/thrift/impl/DataNodeInternalRPCServiceImpl.java
Made the log printed more specified when pushing pipe meta in pipe procedures.
<hr>
This PR has:
<hr>
> [To rel/1.2][IOTDB-5976] Pipe: optimized the feedback when pipe procedure failed to pushPipeMetas

- metrics/interface/src/main/java/org/apache/iotdb/metrics/metricsets/cpu/CpuUsageMetrics.java
- server/src/main/java/org/apache/iotdb/db/service/metrics/DataNodeMetricsHelper.java
See [IOTDB-5975](https://issues.apache.org/jira/browse/IOTDB-5975).
The reason for this bug is that, when a thread is no longer alive, the result of `ThreadMXBean.getThreadInfoById` will return null for this thread. To solve this bug, I check the return value and filter the null value out of the result.
> [IOTDB-5975] Fix NPE in cpu metrics

- metrics/interface/src/main/java/org/apache/iotdb/metrics/metricsets/cpu/CpuUsageMetrics.java
- server/src/main/java/org/apache/iotdb/db/service/metrics/DataNodeMetricsHelper.java
See [IOTDB-5975](https://issues.apache.org/jira/browse/IOTDB-5975).
The reason for this bug is that, when a thread is no longer alive, the result of `ThreadMXBean.getThreadInfoById` will return null for this thread. To solve this bug, I check the return value and filter the null value out of the result.
> [To rel/1.2] [IOTDB-5975] Fix NPE in cpu metrics

- iotdb-client/client-py/iotdb/Session.py
- iotdb-client/client-py/iotdb/sqlalchemy/IoTDBSQLCompiler.py
The reconnect method was copied from Java version, but there are some logic bugs in Python Client, which are caused by the following reasons.
1. The for loop of Python is different with Java. 
For example, `for i in range(0, 5)` in Python not equals to `for (int i = 0; i < 5; i++)` in Java. When `i` was set to `-1` in the loop, `i` would be changed back in the range but not in Java.
2. The random method is different between Python and Java. `random.randint(0, a)` in Python means getting a number in range [0, a]. However, in Java `random.nextInt(a)` means getting a number in range [0, a).
> Fix reconnect logic of python client

- server/src/main/java/org/apache/iotdb/db/exception/metadata/DuplicateInsertException.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/statement/crud/InsertBaseStatement.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/statement/crud/InsertMultiTabletsStatement.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/statement/crud/InsertRowsOfOneDeviceStatement.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/statement/crud/InsertRowsStatement.java
Before supporting the view, duplicate measurements are checked during the semantic analysis phase. After supporting the view, there may be duplicate writes, but semantic analysis cannot detect them. 
Now in the analysis phase, a secondary check for duplicate measurements has been added.
create timeseries and views:
```
IoTDB> create timeseries root.db.d01.s01 INT32 encoding=RLE;
IoTDB> create view root.db.d01.view_s01_a AS root.db.d01.s01;
IoTDB> create view root.db.d01.view_s01_b AS root.db.d01.s01;
```
normal insertion
```
IoTDB> insert into root.db.d01(timestamp,s01) values(1, 36);
IoTDB> insert into …
```
> Fix duplicate insertion bug caused by view

- integration-test/src/test/java/org/apache/iotdb/db/it/groupby/IoTDBGroupByConditionIT.java
- integration-test/src/test/java/org/apache/iotdb/db/it/groupby/IoTDBGroupByCountIT.java
- integration-test/src/test/java/org/apache/iotdb/db/it/groupby/IoTDBGroupByVariationIT.java
- integration-test/src/test/java/org/apache/iotdb/db/it/orderBy/IoTDBOrderByIT.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/AnalyzeVisitor.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/statement/crud/QueryStatement.java
This PR includes the following change of info when the expression in align by device is not one level:
Before:
```md
IOTDB> select status,temperature from root.** order by wt02.temperature align by device
Msg: 701: wt02.temperature in order by clausse doesn't exist.
```
```md
IOTDB> select count(status) from root.** group by count(root.ln.wt01.wf01.status,5) align by device
Msg: 701: Expression in group by should indicate one value
```
```md
IOTDB> select count(status) from root.** group by count(s1,5) align by device
(s1 doesn't exist in the result)
Msg: 701: Expression in group by should indicate one value
```
After:
```md
IOTDB> select status,temperature from root.** order by wt02.temperature align by device
Msg: 701: ALIGN BY DEVICE: the suffix paths can only be measurement or …
```
> [IOTDB-5983] Refactor error info in GROUP BY/ORDER BY in align by device

- confignode/src/main/java/org/apache/iotdb/confignode/consensus/response/pipe/task/PipeTableResp.java
Fix the following issue where `show pipe p1` shows both pipe p1 and p2. 
See https://issues.apache.org/jira/browse/IOTDB-5986
Before:
After:
> [IOTDB-5986] Pipe: fix "show pipe p1" shows multiple pipes

- server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/task/CrossSpaceCompactionTask.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/task/InnerSpaceCompactionTask.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/selector/estimator/AbstractCompactionEstimator.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/selector/estimator/ReadPointCrossCompactionEstimator.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/selector/impl/RewriteCrossSpaceCompactionSelector.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/selector/utils/CrossSpaceCompactionCandidate.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/CompactionSchedulerTest.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/CompactionTaskManagerTest.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/FastNonAlignedCrossCompactionTest.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/cross/CrossSpaceCompactionSelectorTest.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/cross/MergeTest.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/cross/RewriteCompactionFileSelectorTest.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/inner/InnerSpaceCompactionSelectorTest.java
- After copying the fileList in cross space selection, the file is deleted during the selection process, and "file not found" exception will be reported when reading the resource file or evaluating memory.
- If the file is deleted after it is selected and before the task is added into the queue, it will cause `setStatus` method to report an error from setting DELETED to COMPACTION_CANDIDATE.
- In the process of waiting in the queue, if the file is found to be deleted before the execution, compaction task will release all read lock and then set the status of a deleted file from DELETED to NORMAL.
- A deleted source file should not be set to NORMAL after compaction.
**Solution**
- Add read lock of the candidate source files and then check it is validate or not by status …
> [To rel/1.2][IOTDB-5916]Fix exception when file is deleted during compaction selection

- server/src/main/java/org/apache/iotdb/db/wal/node/WALNode.java
- server/src/main/java/org/apache/iotdb/db/wal/utils/WALEntryHandler.java
- server/src/main/java/org/apache/iotdb/db/wal/utils/WALEntryPosition.java
- server/src/main/java/org/apache/iotdb/db/wal/utils/WALInsertNodeCache.java
- server/src/test/java/org/apache/iotdb/db/wal/buffer/WALBufferCommonTest.java
- server/src/test/java/org/apache/iotdb/db/wal/checkpoint/CheckpointManagerTest.java
- server/src/test/java/org/apache/iotdb/db/wal/node/ConsensusReqReaderTest.java
- server/src/test/java/org/apache/iotdb/db/wal/node/WALEntryHandlerTest.java
- server/src/test/java/org/apache/iotdb/db/wal/node/WALNodeTest.java
- server/src/test/java/org/apache/iotdb/db/wal/recover/WALRecoverManagerTest.java
This bug is caused by that wal entries with same version id and position are overrided by others from different wal nodes. To fix this, we should add identifier in the WALEntryPosition.
> Pipe: avoid overriding wal entries when loading entries from different wal nodes

- server/src/main/java/org/apache/iotdb/db/conf/directories/TierManager.java
This PR fix a coding pattern that could possibly have security impact. This issue allows a malicious actor to potentially break out of the expected directory. The impact is limited to sibling directories. For example, `userControlled.getCanonicalPath().startsWith("/user/out")` will allow an attacker to access a directory with a name like `/user/outnot.
To demonstrate this vulnerability, consider `"/user/outnot".startsWith("/user/out")`. The check is bypassed although `/outnot` is not under the `/out` directory. It's important to understand that the terminating slash may be removed when using various `String` representations of the `File` object. 
For example, on Linux, `println(new File("/var"))` will print `/var`, but `println(new File("/var", "/")` will print `/var/`; however, …
> Fix a  a coding pattern that could possibly have security impact

- confignode/src/main/java/org/apache/iotdb/confignode/persistence/executor/ConfigPlanExecutor.java
- integration-test/src/test/java/org/apache/iotdb/confignode/it/partition/IoTDBPartitionGetterIT.java
- node-commons/src/main/java/org/apache/iotdb/commons/path/PartialPath.java
- node-commons/src/main/java/org/apache/iotdb/commons/path/PathPatternUtil.java
When executing show child nodes, ConfigMTree will return the matched child node and related databases, the SchemaRegion of which may contain more matched child nodes. 
If a database node is already the matched child node and the given path pattern doesn't contains multi-level-match wildcard, there's no need to check its SchemaRegion.
Add this mechanism to ConfigPlanExecutor.
> [To rel/1.2] Avoid useless query in SchemaRegion when executing show child nodes

- integration-test/src/test/java/org/apache/iotdb/db/it/aligned/IoTDBInsertAlignedValuesIT.java
- server/src/main/java/org/apache/iotdb/db/metadata/cache/TimeSeriesSchemaCache.java
- server/src/main/java/org/apache/iotdb/db/metadata/mtree/MTreeBelowSGCachedImpl.java
- server/src/main/java/org/apache/iotdb/db/metadata/mtree/MTreeBelowSGMemoryImpl.java
- server/src/main/java/org/apache/iotdb/db/mpp/common/schematree/ClusterSchemaTree.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/schema/ISchemaValidation.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/schema/NormalSchemaFetcher.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/statement/crud/InsertRowStatement.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/statement/crud/InsertTabletStatement.java
Support not checking `isAligned` in insertion.
Fix insertion failure when using alias series caused by `isAligned` checks.
create an aligned timeseries:
```
IoTDB> create ALIGNED timeseries root.db.d01(s01 INT32 encoding=RLE);
IoTDB> show devices;
+-----------+---------+
|     Device|IsAligned|
+-----------+---------+
|root.db.d01|     true|
+-----------+---------+
It costs 0.186s
IoTDB> show timeseries root.**;
+---------------+-----+--------+--------+--------+-----------+----+----------+--------+------------------+--------+
|     Timeseries|Alias|Database|DataType|Encoding|Compression|Tags|Attributes|Deadband|DeadbandParameters|ViewType|
+---------------+-----+--------+--------+--------+-----------+----+----------+------- …
```
> Support not checking `isAligned` in insertion

- server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/source/ShowQueriesOperator.java
- server/src/main/java/org/apache/iotdb/db/utils/TimestampPrecisionUtils.java
doc: https://apache-iotdb.feishu.cn/docx/K7L0dzczGoeib3xPdpRc5EOvnTc
fix test:
1C3D, each DataNode has different timestamp precision, all display are correct.
> [IOTDB-5996] Fix time display of show queries

- server/src/main/java/org/apache/iotdb/db/engine/compaction/cross/rewrite/task/RewriteCrossSpaceCompactionTask.java
- server/src/main/java/org/apache/iotdb/db/rescon/SystemInfo.java
See [IOTDB-5844](https://issues.apache.org/jira/browse/IOTDB-5844).
To address this issue, we have added a timeout mechanism to the memory allocation step in the compaction process. If sufficient memory is not allocated within a certain amount of time, a CompactionMemoryNotEnoughException will be thrown, an error log will be printed, and the compaction task will be abandoned.
> [To rel/0.13] [IOTDB-5844] Fix always waiting when cannot allocate memory for compaction

- confignode/src/main/java/org/apache/iotdb/confignode/manager/schema/ClusterSchemaManager.java
- confignode/src/main/java/org/apache/iotdb/confignode/service/thrift/ConfigNodeRPCServiceProcessor.java
The number of SchemaRegionGroups and DataRegionGroups in system Database should always be 1.
**Test environment:**
- region_group_extension_policy=CUSTOM
- default_region_group_num=5
- metric_reporter_list=IOTDB
**Before fix:**
**After fix:**
> [IOTDB-6000] Control the RegionGroup number of system Database

- server/src/main/java/org/apache/iotdb/db/wal/WALManager.java
- server/src/main/java/org/apache/iotdb/db/wal/node/WALNode.java
To control the total disk usage of wal, we should introduce size threshold to control wal.
1. First delete the files of the largest disk uasge wal node.
2. Snapshot or flush memtable when wal disk usage reaches the threshold.
3. Skip delete operation when wal is pinned by the iot consensus or pipe.
> Add size threshold to control wal disk usage

- confignode/src/main/java/org/apache/iotdb/confignode/persistence/executor/ConfigPlanExecutor.java
- confignode/src/main/java/org/apache/iotdb/confignode/persistence/partition/PartitionInfo.java
Use BufferedInputStream(with 32MB buffer) instead of FileInputStream in PartitionInfo
**Before improvement:**
```
2023-06-15 15:46:03,342 [ForkJoinPool.commonPool-worker-115] INFO  o.a.i.c.p.e.ConfigPlanExecutor:518 - [LoadSnapshot] Load snapshot for org.apache.iotdb.confignode.persistence.partition.PartitionInfo cost 219083 ms
```
Load snapshot of PartitionInfo costs more than 200s
**After improvement:**
```
2023-06-15 18:35:02,676 [ForkJoinPool.commonPool-worker-115] INFO  o.a.i.c.p.e.ConfigPlanExecutor:530 - [ConfigNodeSnapshot] Load snapshot for org.apache.iotdb.confignode.persistence.partition.PartitionInfo cost 12881 ms
```
Load snapshot of PartitionInfo costs only 13s
> [IOTDB-5997] Improve efficiency of ConfigNode PartitionInfo loadSnapshot

- server/src/main/java/org/apache/iotdb/db/wal/WALManager.java
- server/src/main/java/org/apache/iotdb/db/wal/node/WALNode.java
To control the total disk usage of wal, we should introduce size threshold to control wal.
1. First delete the files of the largest disk uasge wal node.
2. Snapshot or flush memtable when wal disk usage reaches the threshold.
3. Skip delete operation when wal is pinned by the iot consensus or pipe.
> [To rel/1.2] Add size threshold to control wal disk usage

- confignode/src/main/java/org/apache/iotdb/confignode/manager/partition/PartitionManager.java
**Updates:**
1. Double confirm leadership before persist partition allocation result.
2. Add unassigned partition rate if LackPartitionException occurs.
> [IOTDB-5993] ConfigNode leader changing causes lacking some DataPartition allocation result in the response of getOrCreateDataPartition method

- consensus/src/main/java/org/apache/iotdb/consensus/iot/logdispatcher/LogDispatcherThreadMetrics.java
Currently, two core metric items of iotconsensus related to synchronization speed are missing
> [Metric] Fix missing IoTConsensus metric items

- confignode/src/main/java/org/apache/iotdb/confignode/manager/ProcedureManager.java
- confignode/src/main/java/org/apache/iotdb/confignode/manager/pipe/runtime/PipeHeartbeatParser.java
- confignode/src/main/java/org/apache/iotdb/confignode/manager/pipe/runtime/PipeLeaderChangeHandler.java
- confignode/src/main/java/org/apache/iotdb/confignode/manager/pipe/runtime/PipeMetaSyncer.java
- confignode/src/main/java/org/apache/iotdb/confignode/manager/pipe/runtime/PipeRuntimeCoordinator.java
- confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/pipe/AbstractOperatePipeProcedureV2.java
- confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/pipe/runtime/PipeHandleMetaChangeProcedure.java
- confignode/src/test/java/org/apache/iotdb/confignode/procedure/impl/pipe/runtime/PipeHandleMetaChangeProcedureTest.java
- node-commons/src/main/java/org/apache/iotdb/commons/concurrent/ThreadName.java
- server/src/main/java/org/apache/iotdb/db/pipe/resource/wal/PipeWALResourceManager.java
To master: https://github.com/apache/iotdb/pull/10203
For more details, see:
[[IOTDB-5931](https://issues.apache.org/jira/browse/IOTDB-5931)] The "show cluster" command displays nodes with "Unknown" status, but these nodes can still perform read and write operations normally (https://issues.apache.org/jira/browse/IOTDB-5931)
> [To rel/1.2][IOTDB-5931] Pipe: async execute pipeHandleLeaderChange and pipeHandleMetaChange to avoid causing heartbeats to timeout

- confignode/src/main/java/org/apache/iotdb/confignode/persistence/executor/ConfigPlanExecutor.java
- confignode/src/main/java/org/apache/iotdb/confignode/persistence/partition/PartitionInfo.java
Use BufferedInputStream(with 32MB buffer) instead of FileInputStream in PartitionInfo
**Before improvement:**
```
2023-06-15 15:46:03,342 [ForkJoinPool.commonPool-worker-115] INFO  o.a.i.c.p.e.ConfigPlanExecutor:518 - [LoadSnapshot] Load snapshot for org.apache.iotdb.confignode.persistence.partition.PartitionInfo cost 219083 ms
```
Load snapshot of PartitionInfo costs more than 200s
**After improvement:**
```
2023-06-15 18:35:02,676 [ForkJoinPool.commonPool-worker-115] INFO  o.a.i.c.p.e.ConfigPlanExecutor:530 - [ConfigNodeSnapshot] Load snapshot for org.apache.iotdb.confignode.persistence.partition.PartitionInfo cost 12881 ms
```
Load snapshot of PartitionInfo costs only 13s
> [To rel/1.2][IOTDB-5997] Improve efficiency of ConfigNode PartitionInfo loadSnapshot

- metrics/interface/src/main/java/org/apache/iotdb/metrics/metricsets/cpu/CpuUsageMetrics.java
- node-commons/src/main/java/org/apache/iotdb/commons/concurrent/ThreadName.java
See [IOTDB-6010](https://issues.apache.org/jira/browse/IOTDB-6010).
The reason for npe is that when getting cpu time from map, we use `get` but not `getOrDefault`, which may cause NPE.
The reason for IndexOutOfBound Exception is that, the size of module map array and thread name array is not the same.
> [To rel/1.2][IOTDB-6010] Fix NPE and IndexOutOfRange Exception in CPU metrics

- metrics/interface/src/main/java/org/apache/iotdb/metrics/metricsets/cpu/CpuUsageMetrics.java
- node-commons/src/main/java/org/apache/iotdb/commons/concurrent/ThreadName.java
See [IOTDB-6010](https://issues.apache.org/jira/browse/IOTDB-6010).
The reason for npe is that when getting cpu time from map, we use `get` but not `getOrDefault`, which may cause NPE.
The reason for IndexOutOfBound Exception is that, the size of module map array and thread name array is not the same.
> [IOTDB-6010] Fix NPE and IndexOutOfRange Exception in CPU metrics

- confignode/src/main/java/org/apache/iotdb/confignode/manager/pipe/runtime/PipeHeartbeatParser.java
- confignode/src/main/java/org/apache/iotdb/confignode/manager/pipe/runtime/PipeLeaderChangeHandler.java
- confignode/src/main/java/org/apache/iotdb/confignode/manager/pipe/runtime/PipeRuntimeCoordinator.java
- server/src/main/java/org/apache/iotdb/db/pipe/connector/v2/IoTDBThriftConnectorV2.java
The number of resident threads has increased, which is not expected.
There is an asynchronous client thread pool introduced to improve the performance limit of syncing data from Pipe to another iotdb instance, similar to the asynchronous client thread pool of IoTConsensus. It can be seen in the compute thread monitoring item. However, there is a problem that initialization should not be performed when it is not necessary.
> [IOTDB-6013] Pipe: pipe-related threads (pools) should not be initialized unless necessary

- server/src/main/java/org/apache/iotdb/db/conf/rest/IoTDBRestServiceDescriptor.java
When configuring IOTDB_HOME, find ${IOTDB_HOME}/conf/iotdb-rest.properties
> [To rel/0.13][IOTDB-5809]The search configuration file path specification is inconsistent

- confignode/src/main/java/org/apache/iotdb/confignode/conf/SystemPropertiesUtils.java
- server/src/main/java/org/apache/iotdb/db/conf/IoTDBStartCheck.java
- server/src/main/java/org/apache/iotdb/db/service/DataNode.java
**confignode-system.properties:**
```
#Tue Jun 20 10:44:45 CST 2023
cn_internal_address=127.0.0.1
config_node_consensus_protocol_class=org.apache.iotdb.consensus.ratis.RatisConsensus
schema_engine_mode=Memory
time_partition_interval=604800000
tag_attribute_total_size=700
config_node_id=0
series_partition_slot_num=1000
config_node_list=0,127.0.0.1\:10710,127.0.0.1\:10720
timestamp_precision=ms
series_partition_executor_class=org.apache.iotdb.commons.partition.executor.hash.BKDRHashExecutor
commit_id=0bf7d75-dev
iotdb_version=1.3.0-SNAPSHOT
cn_internal_port=10710
schema_region_consensus_protocol_class=org.apache.iotdb.consensus.ratis.RatisConsensus
is_seed_config_node=true
cn_consensus_port=10720
data_region_consensus_protocol_class=org.apache.iotdb.consensus.iot.IoTConsensus …
```
> [To rel/1.2] [IOTDB-5999] system.properties patch

- server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/AnalyzeVisitor.java
Add check on group by tag query when using view.
> [To rel/1.2] Forbid GROUP BY TAG query on views

- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/load/LoadSingleTsFileNode.java
- When determining whether a tsfile should be loaded locally without splitting, you should also check that all the data in this tsfile is in the same dataregion and the same time division, without previously checking the latter
这个 PR 包含：
- 在确定 tsfile 是否应该不经过拆分直接加载到本地时，应该同时检查这个 tsfile 中的所有数据是否都在同一个 dataregion 和同一个时间分区内，而之前没有检查后者
如果未检查后者将导致如下错误
> [To rel/1.2][IOTDB-6015] Pipe: Not checking whether the tsfile data loaded locally is in the same time partition during the loading process

- confignode/src/main/java/org/apache/iotdb/confignode/conf/SystemPropertiesUtils.java
- server/src/main/java/org/apache/iotdb/db/conf/IoTDBStartCheck.java
- server/src/main/java/org/apache/iotdb/db/service/DataNode.java
**confignode-system.properties:**
```
#Tue Jun 20 10:44:45 CST 2023
cn_internal_address=127.0.0.1
config_node_consensus_protocol_class=org.apache.iotdb.consensus.ratis.RatisConsensus
schema_engine_mode=Memory
time_partition_interval=604800000
tag_attribute_total_size=700
config_node_id=0
series_partition_slot_num=1000
config_node_list=0,127.0.0.1\:10710,127.0.0.1\:10720
timestamp_precision=ms
series_partition_executor_class=org.apache.iotdb.commons.partition.executor.hash.BKDRHashExecutor
commit_id=0bf7d75-dev
iotdb_version=1.3.0-SNAPSHOT
cn_internal_port=10710
schema_region_consensus_protocol_class=org.apache.iotdb.consensus.ratis.RatisConsensus
is_seed_config_node=true
cn_consensus_port=10720
data_region_consensus_protocol_class=org.apache.iotdb.consensus.iot.IoTConsensus …
```
> [IOTDB-5999] system.properties patch

- confignode/src/main/java/org/apache/iotdb/confignode/conf/ConfigNodeDescriptor.java
- confignode/src/main/java/org/apache/iotdb/confignode/manager/pipe/runtime/PipeLeaderChangeHandler.java
- confignode/src/main/java/org/apache/iotdb/confignode/manager/schema/ClusterSchemaManager.java
- confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/pipe/task/CreatePipeProcedureV2.java
- confignode/src/main/java/org/apache/iotdb/confignode/service/thrift/ConfigNodeRPCServiceProcessor.java
- metrics/interface/src/main/java/org/apache/iotdb/metrics/config/MetricConfig.java
- metrics/interface/src/main/java/org/apache/iotdb/metrics/reporter/iotdb/IoTDBSessionReporter.java
- metrics/interface/src/main/java/org/apache/iotdb/metrics/utils/IoTDBMetricsUtils.java
- server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
- server/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java
- server/src/main/java/org/apache/iotdb/db/engine/flush/MemTableFlushTask.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/distribution/SourceRewriter.java
- server/src/main/java/org/apache/iotdb/db/service/metrics/IoTDBInternalLocalReporter.java
It's more suitable to manage default database in IoTDBConfig instead of IoTDBMetricsUtils
> [IOTDB-6011] Move default database from IoTDBMetricsUtils to IoTDBConfig

- confignode/src/main/java/org/apache/iotdb/confignode/conf/ConfigNodeDescriptor.java
- confignode/src/main/java/org/apache/iotdb/confignode/manager/pipe/runtime/PipeLeaderChangeHandler.java
- confignode/src/main/java/org/apache/iotdb/confignode/manager/schema/ClusterSchemaManager.java
- confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/pipe/task/CreatePipeProcedureV2.java
- confignode/src/main/java/org/apache/iotdb/confignode/service/thrift/ConfigNodeRPCServiceProcessor.java
- metrics/interface/src/main/java/org/apache/iotdb/metrics/config/MetricConfig.java
- metrics/interface/src/main/java/org/apache/iotdb/metrics/reporter/iotdb/IoTDBSessionReporter.java
- metrics/interface/src/main/java/org/apache/iotdb/metrics/utils/IoTDBMetricsUtils.java
- server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
- server/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java
- server/src/main/java/org/apache/iotdb/db/engine/flush/MemTableFlushTask.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/distribution/SourceRewriter.java
- server/src/main/java/org/apache/iotdb/db/service/metrics/IoTDBInternalLocalReporter.java
It's more suitable to manage default database in IoTDBConfig instead of IoTDBMetricsUtils
> [To rel/1.2][IOTDB-6011] Move default database from IoTDBMetricsUtils to IoTDBConfig

- confignode/src/main/java/org/apache/iotdb/confignode/client/async/handlers/rpc/SchemaUpdateRPCHandler.java
- confignode/src/main/java/org/apache/iotdb/confignode/manager/ProcedureManager.java
- confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/schema/AlterLogicalViewProcedure.java
- server/src/main/java/org/apache/iotdb/db/metadata/visitor/SchemaExecutionVisitor.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/execution/config/executor/ClusterConfigTaskExecutor.java
```
IoTDB> alter view root.view(v1.c1, v1.c2, v2.c1, v2.c2) as select s1,s2 from root.db.d1, root.db1.d1;
Msg: 507: Alter view [root.view.v2.c2] failed when [Alter view] because all replicaset of schemaRegion 1 failed. [TDataNodeLocation(dataNodeId:1, clientRpcEndPoint:TEndPoint(ip:127.0.0.1, port:6667), internalEndPoint:TEndPoint(ip:127.0.0.1, port:10730), mPPDataExchangeEndPoint:
TEndPoint(ip:127.0.0.1, port:10740), dataRegionConsensusEndPoint:TEndPoint(ip:127.0.0.1, port:10760), schemaRegionConsensusEndPoint:TEndPoint(ip:127.0.0.1, port:10750))]
```
```
IoTDB> alter view root.view(v1.c1, v1.c2, v2.c1, v2.c2) as select s1,s2 from root.db.d1, root.db1.d1;
Msg: 708: Batch process failed:[TSStatus(code:508, message:Path [root.view.v1.c2] does not exist), TSStatus(code:508, message:Path …
```
> [To rel/1.2] Fix error msg of altering not existing view

- confignode/src/main/java/org/apache/iotdb/confignode/client/async/handlers/rpc/SchemaUpdateRPCHandler.java
- confignode/src/main/java/org/apache/iotdb/confignode/manager/ProcedureManager.java
- confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/schema/AlterLogicalViewProcedure.java
- server/src/main/java/org/apache/iotdb/db/metadata/visitor/SchemaExecutionVisitor.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/execution/config/executor/ClusterConfigTaskExecutor.java
same as https://github.com/apache/iotdb/pull/10252
> Fix error msg of altering not existing view

- server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/AnalyzeVisitor.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/statement/crud/InsertBaseStatement.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/statement/crud/InsertMultiTabletsStatement.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/statement/crud/InsertRowsStatement.java
```
IoTDB> select c1,c2,c3,c4 into root.view.v1(c1,c2,c3,c4)  from root.view.v1;
Msg: 301: Error occurred while inserting tablets in SELECT INTO: [EXECUTE_STATEMENT_ERROR(301)] Exception occurred: insertTablets failed. org.apache.iotdb.db.exception.metadata.DuplicateInsertException: Insertion is illegal because measurement [s0] under device [root.db.d1] is duplicate.
```
```
IoTDB> select c1,c2,c3,c4 into root.view.v1(c1,c2,c3,c4)  from root.view.v1;
Msg: 301: Error occurred while inserting tablets in SELECT INTO: Insertion is illegal because measurement [s0] under device [root.db.d1] is duplicate.
```
> [To rel/1.2] Fix error msg when select into view and normal timeseries failed

- server/src/main/java/org/apache/iotdb/db/pipe/event/common/tsfile/TsFileInsertionDataTabletIterator.java
- server/src/main/java/org/apache/iotdb/db/pipe/task/subtask/PipeConnectorSubtask.java
- tsfile/src/main/java/org/apache/iotdb/tsfile/write/record/Tablet.java
```
commit 3f321225a28cb5c35f3d22d8db2d0f5f45282447 (HEAD -> rel_1.2, origin/rel/1.2, origin/rc/1.2.0.1)
Author: yschengzi <87161145+yschengzi@users.noreply.github.com>
Date: Tue Jun 20 22:14:32 2023 +0800
```
source:
```sql
insert into root.a.b1(time, s1, s2) values (1, '123', null) (2, null, '456')
insert into root.a.b2(time, s1, s2) values (1, '123', null) (2, null, '456')
insert into root.a.b3(time, s1, s2) values (1, '123', null) (2, null, '456')
flush
create pipe p1 with collector ('collector'='iotdb_collector', 'collector.realtime.mode'='file', 'collector.pattern'='root.a.b2') with connector ('connector'='iotdb_thrift_connector_v1','connector.ip'='127.0.0.1', 'connector.port'='6668')
start pipe p1
```
NPE occurs!
> [IOTDB-6021] Pipe: NPE when sync TEXT timeseries with null fields between IoTDB instances using file mode with pattern filter

- confignode/src/main/java/org/apache/iotdb/confignode/consensus/request/write/cq/ActiveCQPlan.java
- confignode/src/main/java/org/apache/iotdb/confignode/consensus/request/write/cq/AddCQPlan.java
- confignode/src/main/java/org/apache/iotdb/confignode/consensus/request/write/cq/DropCQPlan.java
- confignode/src/main/java/org/apache/iotdb/confignode/consensus/request/write/cq/ShowCQPlan.java
- confignode/src/main/java/org/apache/iotdb/confignode/consensus/request/write/cq/UpdateCQLastExecTimePlan.java
- confignode/src/main/java/org/apache/iotdb/confignode/manager/cq/CQManager.java
- confignode/src/main/java/org/apache/iotdb/confignode/manager/cq/CQScheduleTask.java
- confignode/src/main/java/org/apache/iotdb/confignode/persistence/cq/CQInfo.java
- confignode/src/main/java/org/apache/iotdb/confignode/persistence/executor/ConfigPlanExecutor.java
- confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/cq/CreateCQProcedure.java
- confignode/src/main/java/org/apache/iotdb/confignode/procedure/state/cq/CreateCQState.java
This pr aims to fix sonar bugs and code smells in confignode module about cq, including the following packages:
- confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/cq
- confignode/src/main/java/org/apache/iotdb/confignode/procedure/state/cq
- confignode/src/main/java/org/apache/iotdb/confignode/persistence/cq
- confignode/src/main/java/org/apache/iotdb/confignode/manager/cq
- confignode/src/main/java/org/apache/iotdb/confignode/consensus/request/write/cq
- confignode/src/main/java/org/apache/iotdb/confignode/consensus/response/cq
> Fix sonar bugs and code smells in confignode module about cq

- server/src/main/java/org/apache/iotdb/db/pipe/event/common/tsfile/TsFileInsertionDataTabletIterator.java
- server/src/main/java/org/apache/iotdb/db/pipe/task/subtask/PipeConnectorSubtask.java
- tsfile/src/main/java/org/apache/iotdb/tsfile/write/record/Tablet.java
See #10269 for more details.
(cherry picked from commit 06d353158c788833509ffcc5c3d9dfa623be19b1)
> [To rel/1.2][IOTDB-6021] Pipe: NPE when sync TEXT timeseries with null fields between IoTDB instances using file mode with pattern filter (#10269)

- server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/AnalyzeVisitor.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/metedata/write/view/CreateLogicalViewNode.java
When constructing pattern tree for partition fetch from configNode, the interface invoked was appendPathPattern, which takes n^2 time complexity.
When the source clause of createView is a query statement, use the schema tree fetched during analyze query of createViewStatement, and this already contains all source timeseries.
When  the source clause of createView is not a query statement, use appendFullPath to construct pattern tree, since all the given paths are precise timeseries paths.
> [To rel/1.2] Fix slow creation of view when using batch creation sql

- confignode/src/main/java/org/apache/iotdb/confignode/conf/ConfigNodeStartupCheck.java
- confignode/src/main/java/org/apache/iotdb/confignode/service/ConfigNode.java
The ConfigNode should restore cluster_name and config_node_id at the first step of restart.
> [To rel/1.2][IOTDB-5999] System properties patch

- confignode/src/main/java/org/apache/iotdb/confignode/conf/ConfigNodeStartupCheck.java
- confignode/src/main/java/org/apache/iotdb/confignode/service/ConfigNode.java
The ConfigNode should restore cluster_name and config_node_id at the first step of restart.
> [IOTDB-5999] System properties patch

- server/src/main/java/org/apache/iotdb/db/engine/load/TsFileSplitter.java
- In the split tsfile logic of load, if there is an empty value chunk, the empty ByteBuffer and the corresponding statistics should be written, not nothing, which will cause the deserialization to fail
这个 PR 包含：
- 在 load 的拆分 tsfile 逻辑中，如果出现了 empty value chunk，应当写入空的 ByteBuffer 和对应的 statistics，而不是什么都不写，不写将导致反序列化失败，并引起以下错误
> [IOTDB-6023] Pipe: LoadTsFilePieceNode error when loading tsfile with empty value chunks

- server/src/main/java/org/apache/iotdb/db/conf/rest/IoTDBRestServiceDescriptor.java
cp pr9683 When configuring IOTDB_HOME, find ${IOTDB_HOME}/conf/iotdb-rest.properties
> [IOTDB-5809]The search configuration file path specification is inconsistent

- confignode/src/main/java/org/apache/iotdb/confignode/client/DataNodeRequestType.java
- confignode/src/main/java/org/apache/iotdb/confignode/client/async/AsyncDataNodeClientPool.java
- confignode/src/main/java/org/apache/iotdb/confignode/client/async/handlers/AsyncClientHandler.java
- confignode/src/main/java/org/apache/iotdb/confignode/client/async/handlers/rpc/PipeHeartbeatRPCHandler.java
- confignode/src/main/java/org/apache/iotdb/confignode/consensus/statemachine/ConfigRegionStateMachine.java
- confignode/src/main/java/org/apache/iotdb/confignode/manager/load/service/HeartbeatService.java
- confignode/src/main/java/org/apache/iotdb/confignode/manager/pipe/runtime/PipeHeartbeatScheduler.java
- confignode/src/main/java/org/apache/iotdb/confignode/manager/pipe/runtime/PipeLeaderChangeHandler.java
- confignode/src/main/java/org/apache/iotdb/confignode/manager/pipe/runtime/PipeRuntimeCoordinator.java
- confignode/src/main/java/org/apache/iotdb/confignode/persistence/pipe/PipeTaskInfo.java
- confignode/src/main/java/org/apache/iotdb/confignode/procedure/env/ConfigNodeProcedureEnv.java
- confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/pipe/runtime/PipeHandleLeaderChangeProcedure.java
- iotdb-protocol/thrift/src/main/thrift/datanode.thrift
- node-commons/src/assembly/resources/conf/iotdb-common.properties
- node-commons/src/main/java/org/apache/iotdb/commons/concurrent/ThreadName.java
- node-commons/src/main/java/org/apache/iotdb/commons/conf/CommonConfig.java
- node-commons/src/main/java/org/apache/iotdb/commons/conf/CommonDescriptor.java
- node-commons/src/main/java/org/apache/iotdb/commons/pipe/config/PipeConfig.java
- server/src/main/java/org/apache/iotdb/db/pipe/agent/task/PipeTaskAgent.java
- server/src/main/java/org/apache/iotdb/db/service/thrift/impl/DataNodeInternalRPCServiceImpl.java
commit 3f321225a28cb5c35f3d22d8db2d0f5f45282447 (HEAD -> rel_1.2, origin/rel/1.2, origin/rc/1.2.0.1)
Author: yschengzi <87161145+yschengzi@users.noreply.github.com>
Date: Tue Jun 20 22:14:32 2023 +0800
1. Default Configuration: Source iotdb - 3C3D 2 Replicas, Target iotdb - 1C1D
2. Create metadata in the target iotdb
3. Create 100 real-time pipes and start them in the source iotdb
4. Use benchmark to create metadata and write data in the source iotdb. Benchmark Configuration: Device: 100, Sensor: 10, Database: 1, Align Sequence
1. One node became unknown
2. Even if a node is unknown, it should still be able to write
Cluster nodes should not become abnormal, and even if they do, they should still be able to write normally.
---------
* separate pipe heartbeat from cluster heartbeat
* fix: …
> [To rel/1.2][IOTDB-6017] Pipe: separate pipe heartbeat from cluster heartbeat (#10285)

- server/src/main/java/org/apache/iotdb/db/metadata/mtree/snapshot/MemMTreeSnapshotUtil.java
- tsfile/src/main/java/org/apache/iotdb/tsfile/utils/ReadWriteIOUtils.java
After restarting DataNode, the isAligned attribute of a device with only view reveals false rather than null.
Wrong method was used when loading schema region snapshot, thus false rather null was set into a DeviceNode.
Fix the recover process of schema region snapshot.
> [To rel/1.2] Fix view snapshot recover

- server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/AnalyzeVisitor.java
This issue is due to the incorrect use of the getOrCreateSchemaPartition interface when pulling schema partitions. The getOrCreateSchemaPartition interface ignores the pathPattern with suffix **. This pr resolve this problem.
> [To rel/1.2] Fix show paths using template return partition result

- confignode/src/main/java/org/apache/iotdb/confignode/persistence/executor/ConfigPlanExecutor.java
- confignode/src/main/java/org/apache/iotdb/confignode/persistence/partition/PartitionInfo.java
Use BufferedOutputStream(with 32MB buffer) instead of FileInputStream in PartitionInfo
**Before Optimization:**
```
2023-06-27 09:52:50,996 [0@group-000000000000-StateMachineUpdater] INFO  o.a.i.c.p.e.ConfigPlanExecutor:489 - [ConfigNodeSnapshot] Finish to take snapshot for org.apache.iotdb.confignode.persistence.partition.PartitionInfo, time consumption: 441904 ms
```
**After Optimization:**
```
2023-06-27 14:25:56,211 [ForkJoinPool.commonPool-worker-115] INFO  o.a.i.c.p.e.ConfigPlanExecutor:490 - [ConfigNodeSnapshot] Finish to take snapshot for org.apache.iotdb.confignode.persistence.partition.PartitionInfo, time consumption: 8330 ms
```
> [IOTDB-6030] Improve efficiency of ConfigNode PartitionInfo takeSnapshot

- confignode/src/main/java/org/apache/iotdb/confignode/persistence/executor/ConfigPlanExecutor.java
- confignode/src/main/java/org/apache/iotdb/confignode/persistence/partition/PartitionInfo.java
Use BufferedOutputStream(with 32MB buffer) instead of FileInputStream in PartitionInfo
**Before Optimization:**
```
2023-06-27 09:52:50,996 [0@group-000000000000-StateMachineUpdater] INFO  o.a.i.c.p.e.ConfigPlanExecutor:489 - [ConfigNodeSnapshot] Finish to take snapshot for org.apache.iotdb.confignode.persistence.partition.PartitionInfo, time consumption: 441904 ms
```
**After Optimization:**
```
2023-06-27 14:25:56,211 [ForkJoinPool.commonPool-worker-115] INFO  o.a.i.c.p.e.ConfigPlanExecutor:490 - [ConfigNodeSnapshot] Finish to take snapshot for org.apache.iotdb.confignode.persistence.partition.PartitionInfo, time consumption: 8330 ms
```
> [To rel/1.2][IOTDB-6030] Improve efficiency of ConfigNode PartitionInfo takeSnapshot

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/modification/Deletion.java
- iotdb-core/tsfile/src/test/java/org/apache/iotdb/tsfile/read/common/TimeRangeTest.java
When comparing whether two Deletion objects overlap, the start time and end time in the TimeRange class are used. When the start time is the minimum value of Long or the end time is the maximum value of Long, the result is problematic because the start time or end time exceeds the range of Long. This fix is to specify TimeRange as an open interval when creating the Deletion to prevent Long overflows.
> fix judgment time range is intersect,when TimeRange is Long.MIN_VALUE or Long.MAX_VALUE,TimeRange cannot be merged due to overflow behavior

- iotdb-core/consensus/src/test/java/org/apache/iotdb/consensus/ratis/RatisConsensusTest.java
After this patch, the total coverage of ratis consensus is 80%.
> Improve RatisConsensus UT coverage

- server/src/main/java/org/apache/iotdb/db/mpp/plan/parser/ASTVisitor.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/statement/metadata/AlterTimeSeriesStatement.java
```
alter view root.view.v1.c1 upsert tags(city=beijing, description='this is a capital') attributes(speed=100, color=red);
Msg: 803: No permissions for this operation, please add privilege ALTER_TIMESERIES
```
Such operation currently is implemented based on altering timeseries, which results in the authority module get ALTER_TIMESERIES operation type rather than ALTER_VIEW operation type.
Return ALTER_VIEW operation type when the AlterTimeSeriesStatement is used for altering view.
> [To rel/1.2] Fix authority check of altering view

- confignode/src/main/java/org/apache/iotdb/confignode/service/ConfigNode.java
- server/src/assembly/resources/sbin/start-datanode.bat
- server/src/main/java/org/apache/iotdb/db/service/DataNode.java
1. Change default charset encoding to UTF-8 in `start-datanode.bat`
2. Add log when DataNode/ConfigNode starts to print the default charset
NOTICE: Before this change, the explicit setting has only been added in `start-confignode.bat`. To keep the setting is consistent between DataNode and ConfigNode, we add the explicit charset encoding setting in script for windows.
> [To rel/1.2] Change default charset encoding to UTF-8 in start-datanode.bat 

- integration-test/src/main/java/org/apache/iotdb/it/env/cluster/AbstractEnv.java
- integration-test/src/main/java/org/apache/iotdb/it/env/remote/RemoteServerEnv.java
- integration-test/src/main/java/org/apache/iotdb/itbase/env/BaseEnv.java
- integration-test/src/test/java/org/apache/iotdb/confignode/it/load/IoTDBClusterRegionLeaderBalancingIT.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/load/cache/region/RegionGroupStatistics.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/load/service/StatisticsService.java
Format LoadStatistics logs to improve readability. Add ClusterIT to make sure the leader of DataRegionGroup will re-distribute as long as some DataNodes turn into ReadOnly Status.
**LoadStatistics log examples:**
```
2023-06-29 10:38:34,820 [pool-2-thread-3] INFO  o.a.i.c.m.l.s.StatisticsService:180 - [NodeStatistics] NodeStatisticsMap:  
2023-06-29 10:38:34,821 [pool-2-thread-3] INFO  o.a.i.c.m.l.s.StatisticsService:184 - [NodeStatistics]	 nodeId{1}: NodeStatistics{loadScore=9223372036854775807, status=Unknown, statusReason='null'}->NodeStatistics{loadScore=0, status=Running, statusReason='null'} 
2023-06-29 10:38:45,906 [pool-2-thread-2] INFO  o.a.i.c.m.l.s.StatisticsService:244 - [RegionLeader] RegionLeaderMap:  
2023-06-29 10:38:45,906 [pool-2-thread-2] INFO …
```
> [IOTDB-6034] Format LoadStatistics logs and add ClusterIT

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/wal/WALManager.java
Before this change, the log print original max_wal_size when throttling down. Actually its use `max_wal_size * 0.8` as the threshold of throttle down.
This PR fix this isssue.
> fix the error in wal throttle log which print wrong threshold

- server/src/main/java/org/apache/iotdb/db/wal/WALManager.java
Before this change, the log print original max_wal_size when throttling down. Actually its use max_wal_size * 0.8 as the threshold of throttle down.
This PR fix this isssue.
> [To rel/1.2] fix the error in wal throttle log which print wrong threshold 

- server/src/main/java/org/apache/iotdb/db/engine/load/TsFileSplitter.java
add isTimeChunkNeedDecode to handle whether need to writeEntireChunk.
> [To rel/1.2][IOTDB-6023] Pipe:  Fix load tsfile error while handling empty value chunk 

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/load/TsFileSplitter.java
add isTimeChunkNeedDecode to handle whether need to writeEntireChunk.
> [IOTDB-6023] Pipe: Fix load tsfile while handling empty value chunk

- server/src/main/java/org/apache/iotdb/db/engine/load/TsFileSplitter.java
add isTimeChunkNeedDecode to handle whether need to writeEntireChunk.
> [To rel/1.1][IOTDB-6023] Pipe: Fix load error while handling empty value Chunk 

- confignode/src/test/java/org/apache/iotdb/confignode/persistence/schema/TemplateTableTest.java
- integration-test/src/test/java/org/apache/iotdb/db/it/schema/IoTDBSchemaTemplateIT.java
- server/src/main/java/org/apache/iotdb/db/metadata/template/Template.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/AnalyzeVisitor.java
* Print duplicated path when creating template 
* Print reasons for not supporting upsert timeseries
> [To rel/1.2] Make error messages more detailed when creating and upserting templates

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/AnalyzeVisitor.java
cherry-pick #10330 
This issue is due to the incorrect use of the getOrCreateSchemaPartition interface when pulling schema partitions. The getOrCreateSchemaPartition interface ignores the pathPattern with suffix **. This pr resolve this problem.
> Fix show paths using template return partition result

- integration-test/src/main/java/org/apache/iotdb/it/env/cluster/MppCommonConfig.java
- integration-test/src/main/java/org/apache/iotdb/it/env/cluster/MppSharedCommonConfig.java
- integration-test/src/main/java/org/apache/iotdb/it/env/remote/RemoteCommonConfig.java
- integration-test/src/main/java/org/apache/iotdb/itbase/env/CommonConfig.java
- integration-test/src/test/java/org/apache/iotdb/db/it/cq/IoTDBCQExecInNsIT.java
- integration-test/src/test/java/org/apache/iotdb/db/it/cq/IoTDBCQExecInUsIT.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/cq/CQScheduleTask.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/statement/component/GroupByTimeComponent.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/utils/DateTimeUtils.java
In previous  implementation,  cq  in cofignode does not take  time_precision into account and think all the time `long` value will be `ms`.
> Fix CQ does not take effect in ns  time_precision

- integration-test/src/test/java/org/apache/iotdb/db/it/schema/IoTDBSchemaTemplateIT.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/schema/CountGroupByLevelMergeOperator.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/schema/CountGroupByLevelScanOperator.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/schema/SchemaQueryScanOperator.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/AnalyzeVisitor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/LogicalPlanBuilder.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/LogicalPlanVisitor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/OperatorTreeGenerator.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/plan/node/metedata/read/LevelTimeSeriesCountNode.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/plan/plan/node/metadata/read/SchemaCountNodeSerdeTest.java
cherry-pick #10347 
Fix count timeseries group by level return incorrect result.
If time series is associated with schema template, we should add template info to traverser.
ListenableFuture.addListener will execute asynchronously, which may result in a deprecated member variable next being obtained at the time of hasNext().
> Fix count timeseries group by level return incorrect result

- server/src/main/java/org/apache/iotdb/db/pipe/event/common/tablet/TabletInsertionDataContainer.java
- server/src/main/java/org/apache/iotdb/db/pipe/extractor/realtime/assigner/DisruptorQueue.java
- server/src/main/java/org/apache/iotdb/db/pipe/extractor/realtime/assigner/DisruptorQueueExceptionHandler.java
- server/src/main/java/org/apache/iotdb/db/pipe/extractor/realtime/matcher/CachedSchemaPatternMatcher.java
Cherry-picked from #10424.
See IOTDB-6041 for more details.
> [To rel/1.2][IOTDB-6041] Pipe: NPE when handling partial insertion using DisruptorQueue in extractor stage

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/modification/ModificationFile.java
When the File is deleted normally, the result returned by the File.delete () method should be true instead of false.Print only if file deletion fails should be"Delete ModificationFile {} failed."
> fixed incorrect judgment when mods files were removed causing log inaccuracies

- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/ConfigManager.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/Procedure.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/ProcedureExecutor.java
- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/ratis/RequestMessage.java
- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/ratis/ResponseMessage.java
The previous code might cause an error like this
> Fix semantic incompatibility when AtomicReference replaces volatile

- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/consensus/response/pipe/task/PipeTableResp.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/execution/config/sys/pipe/ShowPipeTask.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/utils/DateTimeUtils.java
see https://timechor.feishu.cn/docx/Hhqbd84saoPTmHxCXuCcHQKgnBg
see https://issues.apache.org/jira/browse/IOTDB-6042
after (timestamp_precision=ns):
> [IOTDB-6042] Pipe: fix CreationTime display error using non-default time_precision when executing show pipes

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/thrift/impl/DataNodeInternalRPCServiceImpl.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/schema/source/LogicalViewSchemaSource.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/schema/source/SchemaSourceFactory.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/schema/source/TimeSeriesSchemaSource.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/OperatorTreeGenerator.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/mtree/impl/mem/MTreeBelowSGMemoryImpl.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/mtree/impl/pbtree/MTreeBelowSGCachedImpl.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/read/req/IShowTimeSeriesPlan.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/read/req/SchemaRegionReadPlanFactory.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/read/req/impl/ShowTimeSeriesPlanImpl.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/read/resp/reader/impl/TimeseriesReaderWithViewFetch.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/metadata/schemaRegion/SchemaRegionBasicTest.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/metadata/schemaRegion/SchemaRegionTestUtil.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/execution/operator/schema/SchemaQueryScanOperatorTest.java
cherry pick #10370 
This PR introduces a switch needFetch for TimeseriesReaderWithViewFetch. 
```java
/**
* There is no need to pull the original sequence information from the view if needFetch is false.
* The default is false if not filtered by DataType.
*/
private final boolean needFetch;
```
If needFetch is false, the original information from the view will not be pulled asynchronously, speeding up metadata queries.
> Speed up metadata queries that do not require pulling raw information from the view

- confignode/src/main/java/org/apache/iotdb/confignode/consensus/response/pipe/task/PipeTableResp.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/execution/config/sys/pipe/ShowPipeTask.java
- server/src/main/java/org/apache/iotdb/db/utils/DateTimeUtils.java
same as https://github.com/apache/iotdb/pull/10423
> [To rel/1.2][IOTDB-6042] Pipe: fix CreationTime display error using non-default time_precision when executing show pipes

- server/src/main/java/org/apache/iotdb/db/mpp/plan/execution/config/sys/sync/ShowPipeTask.java
- server/src/main/java/org/apache/iotdb/db/utils/DateTimeUtils.java
same as https://github.com/apache/iotdb/pull/10423
> [To rel/1.1][IOTDB-6042] Pipe: fix CreationTime display error using non-default time_precision when executing show pipes

- integration-test/src/test/java/org/apache/iotdb/db/it/schema/IoTDBSchemaTemplateIT.java
- iotdb-core/confignode/src/test/java/org/apache/iotdb/confignode/persistence/schema/TemplateTableTest.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/AnalyzeVisitor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/template/ClusterTemplateManager.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/template/Template.java
cherry pick #10405
* Print duplicated path when creating template 
* Print reasons for not supporting upsert timeseries
> Make error messages more detailed when creating and upserting templates

- iotdb-core/metrics/interface/pom.xml
- iotdb-core/metrics/micrometer-metrics/pom.xml
- pom.xml
https://github.com/apache/iotdb/pull/10429 removed some netty dependencies. However, some of them are necessary for metrics module. When open the PROMETHEUS reporter, the confignode cannot start.
Therefore, this PR is recovering the necessary dependencies.
> Fix metric service cannot start

- iotdb-core/metrics/interface/src/main/java/org/apache/iotdb/metrics/reporter/prometheus/PrometheusReporter.java
> Fix issue where the metric module failed to catch exceptions at startup

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/DataRegion.java
Before this change, the `compaction scheduler thread pool` is not considered when aborting compaction. Thus, if a DataRegion is deleted, the scheduler thread is overflow.
This PR fix this issue.
> [IOTDB-5910] Fix compaction scheduler thread pool is not shutdown when aborting compaction

- iotdb-client/cli/pom.xml
details see:   https://issues.apache.org/jira/browse/IOTDB-6050
when I merge code then our tester find the import-csv.sh run failed,  Exception is ClassNotFoud
reason : in this merged pr: https://github.com/apache/iotdb/pull/8600
the package 'org.apache.iotdb.db.qp.utils' renamed to 'org.apache.iotdb.db.utils'
but  iotdb-cli moudle pom.xml is not changed, so  shade jar has no classes in new package.
> [IOTDB-6050] ClassNotFound when use csv import-csv.sh in cluster

- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/DataRegion.java
In IoTDB, the size and count of all deleted TsFiles should be deducted in TsFileMetrics. Users have noticed discrepancies between the TsFile size and count displayed on the monitoring panel and the actual file size and count on the disk. This inconsistency is due to the fact that the changes in file size and count were not recorded in TsFileMetrics when files were deleted due to TTL (Time-To-Live) expiry.
Launch an IoTDB instance and write data to it while setting the TTL. Once the TTL takes effect, you will notice the mismatch between the data reflected in the monitor and the actual data on the disk.
> [To rel/1.1] Fix not decreasing file size after ttl delete file

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/mtree/impl/mem/snapshot/MemMTreeSnapshotUtil.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/mtree/impl/pbtree/cache/CacheManager.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/mtree/impl/pbtree/cache/CacheMemoryManager.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/metadata/schemaRegion/AbstractSchemaRegionTest.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/metadata/schemaRegion/SchemaStatisticsTest.java
Fix bug occurs in `SchemaStatisticsTest`
https://apache-iotdb.feishu.cn/docx/Ykibdd0ehox4qSxsPOAcc8JGnyg
After troubleshooting, this was caused by PBTree memory management in the corner case of update then delete.
When updating measurement, PBTree management will remove the device from the cache and add it to the buffer.
When removing measurement, PBTree management removes the device's node from the device's updated buffer.
Therefore, when flushing, although the device node is regarded as volatile not, it will not be collected because it has no children. We need to add it back to the cache, otherwise the device node will not be unpinable, resulting in incorrect statistics.
> [IOTDB-5576] Some node missed out when deleting after updating

- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/service/ConfigNode.java
- iotdb-core/datanode/src/assembly/resources/sbin/start-datanode.bat
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/service/DataNode.java
refer PR https://github.com/apache/iotdb/pull/10051
1. Change default charset encoding to UTF-8 in `start-datanode.bat`
2. Add log when DataNode/ConfigNode starts to print the default charset
NOTICE: Before this change, the explicit setting has only been added in `start-confignode.bat`. To keep the setting is consistent between DataNode and ConfigNode, we add the explicit charset encoding setting in script for windows.
> Add default charset setting in start-datanode.bat and print default charset when starting

- docs/UserGuide/Reference/Common-Config-Manual.md
- docs/UserGuide/Reference/SQL-Reference.md
- docs/zh/UserGuide/Reference/Common-Config-Manual.md
- docs/zh/UserGuide/Reference/SQL-Reference.md
- integration-test/src/test/java/org/apache/iotdb/db/it/schema/IoTDBCreateAlignedTimeseriesIT.java
- integration-test/src/test/java/org/apache/iotdb/db/it/schema/IoTDBExtendTemplateIT.java
- integration-test/src/test/java/org/apache/iotdb/db/it/schema/IoTDBMetadataFetchIT.java
- integration-test/src/test/java/org/apache/iotdb/db/it/schema/IoTDBSchemaTemplateIT.java
- integration-test/src/test/java/org/apache/iotdb/db/it/schema/IoTDBSortedShowTimeseriesIT.java
- integration-test/src/test/java/org/apache/iotdb/db/it/schema/IoTDBTagIT.java
- integration-test/src/test/java/org/apache/iotdb/util/AbstractSchemaIT.java
- integration-test/src/test/java/org/apache/iotdb/zeppelin/it/IoTDBInterpreterIT.java
- iotdb-client/client-py/tests/test_dataframe.py
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/metadata/mtree/schemafile/WrappedSegmentTest.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/tools/TsFileSelfCheckToolTest.java
- iotdb-core/node-commons/src/assembly/resources/conf/iotdb-common.properties
- iotdb-core/tsfile/src/main/java/org/apache/iotdb/tsfile/common/conf/TSFileConfig.java
Change default compressor to LZ4 accoording to the experiment result in https://apache-iotdb.feishu.cn/docx/ThmHdPKw9oJv95xvLhWco2WnnLh
(The two images above are from Jinzhao Xiao, Yuxiang Huang, Changyu Hu, Shaoxu Song, Xiangdong Huang, Jianmin Wang. Time Series Data Encoding for Efficient Storage: A Comparative Analysis in Apache IoTDB. International Conference on Very Large Data Bases, VLDB, 2022. [[paper](https://sxsong.github.io/doc/22vldb-encoding.pdf)] )
> Change default compressor to LZ4

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/load/TsFileSplitter.java
**bug**：
**reason**：
we didn't handle empty pages in aligned chunk
**solution**:
add `if` statement to judge the page is empty or not, and write the entire page when it is not an empty page
> [IOTDB-6056] Pipe: Failed to load tsfile with empty pages (NPE occurs when loading)

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/task/InnerSpaceCompactionTask.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/schedule/comparator/DefaultCompactionTaskComparatorImpl.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/selector/impl/SizeTieredCompactionSelector.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/modification/ModificationFile.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/compaction/CompactionTaskComparatorTest.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/compaction/inner/InnerSpaceCompactionSelectorTest.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/tsfile/FakedTsFileResource.java
If the size of the corresponding mods file is larger than 50M, we will preferentially select this file to submit to the global priority queue. If a suitable task is selected, the hierarchical selection will not be executed. In the inner sorting rules, sorting by mods file size has the highest priority.
See documentation link for testing procedure：
https://apache-iotdb.feishu.cn/docx/HLCPdkY5LohWN9xTZIZcEE0yn0g
> added the selection of files to be merged based on mods file size in the inner compaction selector

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
maxBytesPerFragmentInstance should also be updated when updating allocatedMemoryForRead.
> update maxBytesPerFragmentInstance in setAllocateMemoryForRead of IoTDBConfig

- server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
maxBytesPerFragmentInstance should also be updated when updating allocatedMemoryForRead.
> [To rel/1.1] update maxBytesPerFragmentInstance in setAllocateMemoryForRead of IoTDBConfig 

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/service/metrics/WritingMetrics.java
Modify the parameter to call remove when remove WALNodeInfoMetrics
> Fix a bug of Writing Metrics

- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/metadata/view/ViewExpressionToStringTest.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/schema/view/viewExpression/multi/FunctionViewExpression.java
Before the tostring is like `FUNC(type=INT32, key=value)(root.db.device.s01, root.ln.d.s01)`,
Now it's like `FUNC(root.db.device.s01, root.ln.d.s01, type=INT32, key=value)`
> Fix toString method of FunctionViewExpression

- iotdb-core/consensus/src/test/java/org/apache/iotdb/consensus/iot/ReplicateTest.java
see [jira](https://issues.apache.org/jira/browse/IOTDB-6061)
> [IOTDB-6061] Fix the instability failure caused by initServer in IoTConsensus UT not binding to the corresponding port

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/load/AlignedChunkData.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/load/TsFileSplitter.java
- iotdb-core/tsfile/src/main/java/org/apache/iotdb/tsfile/file/header/PageHeader.java
- iotdb-core/tsfile/src/main/java/org/apache/iotdb/tsfile/write/chunk/ValueChunkWriter.java
in previous pr: https://github.com/apache/iotdb/pull/10487, We only considered the case where the empty page is at the end of an aligned chunk, and it's not well thought out. Empty page is skipped, causing problems with rewriting tsfile on datanode
case not considered: 
in this pr, we consider all the position of empty pages in an aligned chunk, and handle the empty page through write an empty page into the chunk.
> [IOTDB-6068] Pipe: Failed to load tsfile with first page is empty in a chunk

- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/pipe/task/PipeTaskCoordinator.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/ProcedureExecutor.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/pipe/AbstractOperatePipeProcedureV2.java
Fix:
- Add a case in executeProcedure, referring to https://github.com/apache/hbase
- Modify lock control of pipe procedures to avoid deadlock in failed procedures
> [IOTDB-6064] Pipe: Fix deadlock in rolling back procedures concurrently

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/event/common/row/PipeRowCollector.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/event/common/tsfile/TsFileInsertionDataTabletIterator.java
- iotdb-core/node-commons/src/assembly/resources/conf/iotdb-common.properties
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/conf/CommonConfig.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/conf/CommonDescriptor.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/config/PipeConfig.java
Currently, tablets in pipe transfer are created with default rowSize. If data fransfer load is high, there  will be too many thrift requests of tablet transfer. So we can add a knob to specify rowSize of pipe tablets.
> Pipe: Add a configuration parameter to control the number of rows of the tablet used within the pipe module

- iotdb-core/metrics/interface/src/main/java/org/apache/iotdb/metrics/reporter/prometheus/PrometheusTextWriter.java
Fix default labels in prometheus reporter when metrics has no tag
> Fix default labels in prometheus reporter when metrics has no tag

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/DataRegion.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/tsfile/TsFileResource.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/tsfile/timeindex/DeviceTimeIndex.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/tsfile/timeindex/FileTimeIndex.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/tsfile/timeindex/ITimeIndex.java
When IoTDB has data of 100,000 devices, 20k devices in each tsfile, 163 tsfiles total, execute a delete sql like `delete from root.db.** where time<1970-1-01T08:01:01.000+08:00`. No data actually matches the time filter.  The execution will takes over **20 hours**. 
The reason of this issue is the process of matching DeviceId in TsFileResource and the pattern `root.db.**` takes too match time. For this scenario , it will match 20k * 163 = 3,260,000 times.
This PR is fixing the above issue. We can use a hashset to record the match deviceId info for this delete operation. The maximum matching times will be reduced to the device number 100,000.
Plus, we can use a file level time filter to skip the device check before the deviceId matching.
After this fixing, the execution only takes **8 …
> Optimize the speed of delete by pattern

- iotdb-client/client-py/iotdb/Session.py
- iotdb-client/client-py/iotdb/SessionPool.py
- iotdb-client/client-py/tests/test_session.py
- iotdb-client/client-py/tests/test_session_pool.py
This PR implement a simplify  session pool for python client.
```python
"""
PoolConfig(host: str, ip: str, user_name: str, password: str, node_urls: list = None,
fetch_size: int = DEFAULT_FETCH_SIZE, time_zone: str = DEFAULT_TIME_ZONE,
max_retry: int = DEFAULT_MAX_RETRY)
"""
pool_config = PoolConfig(db.get_ip_address(), db.get_port(), [], "root", "root", 1024, "Asia/Shanghai", 3)
"""
create_session_pool(pool_config: PoolConfig, max_pool_size: int, wait_timeout_in_ms: int)
"""
session_pool = create_session_pool(pool_config, max_pool_size, 3000)
try:
session = session_pool.get_session()
except TimeoutError as e:
raise e
session.open(False)
session_pool.put_back(session)
```
> [IOTDB-6069] Support SessionPool in client-py

- iotdb-core/consensus/pom.xml
cherry-pick of https://github.com/apache/iotdb/pull/10574
> [To rel/1.2] Bump Ratis version to 2.5.2-8d897ea-SNAPSHOT

- node-commons/src/assembly/resources/conf/iotdb-common.properties
- server/src/main/java/org/apache/iotdb/db/engine/compaction/selector/impl/RewriteCrossSpaceCompactionSelector.java
The threshold of candidate size of seq tsfile in cross space compaction is changed to `target_compaction_file_size * 1.5` in this PR.
Before this change, some cross compaction task won't be executed because of this limitation, which lead to accumulation of  lots of unseq files.
> [To rel/1.1] Change the threshold of candidate size of seq tsfile in cross space

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/selector/impl/RewriteCrossSpaceCompactionSelector.java
- iotdb-core/node-commons/src/assembly/resources/conf/iotdb-common.properties
The threshold of candidate size of seq tsfile in cross space compaction is changed to `target_compaction_file_size * 1.5` in this PR.
Before this change, some cross compaction task won't be executed because of this limitation, which lead to accumulation of  lots of unseq files.
> Change the threshold of candidate size of seq tsfile in cross space

- integration-test/src/test/java/org/apache/iotdb/db/it/aligned/IoTDBAlignedLastQueryIT.java
- integration-test/src/test/java/org/apache/iotdb/db/it/last/IoTDBLastQueryLastCacheIT.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/OperatorTreeGenerator.java
Cause: The `DataNodeSeriesScanNum` of different series in one `AlignedLastQueryScanNode` are same (p1), the update and judges depend on it are unexpected (p2) .
> Fix aligned last  query

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/utils/datastructure/AlignedTVList.java
In some scenario, the Binary in AlignedTVList will be null if this field is empty in current row. We need to handle this scenario to get rid of NPE in WAL snapshot taking stage. 
See a similar issue here: https://github.com/apache/iotdb/pull/9884 
**Current fix**: we use an empty Binary as a placeholder here. It won't lead to data error because whether this field is null or not is decided by the bitMap rather than the object's value here.
> Fix the NPE issue when taking snapshot in WAL combined with Aligned Binary

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/agent/receiver/PipeReceiverAgent.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/agent/runtime/PipeRuntimeAgent.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/v1/IoTDBThriftConnectorClient.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/v1/IoTDBThriftConnectorV1.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/v1/IoTDBThriftReceiverV1.java
- iotdb-core/node-commons/src/assembly/resources/conf/iotdb-common.properties
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/conf/CommonConfig.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/conf/CommonDescriptor.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/config/PipeConfig.java
The pipe stopped and can not be restarted.
* Sender's connection timeout at sender < load operation cost time at receiver
* A sender's load tsfile request is timeout, but the request's execution can not be terminated when timeout
* Sender will retry to send a load tsfile request, which will load the same tsfile that cause the timeout before
* Serveral load tsfile requests are concurrently executing at the receiver
* The load operation performed earlier deletes files that need to be loaded
* The load operation performed later (a retry) wants to read the tsfile, but the tsfile was deleted, which may cause exception like: 
writing file sequence-root.bw-6-2735-1686907665964-1-8-8.tsfile is not available
* Add a parameter in iotdb-core/node-commons/src/assembly/resources/conf/iotdb-common.prope …
> [IOTDB-6075] Pipe: File resource races when different tsfile load operations concurrently modify the same tsfile at receiver

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/agent/receiver/PipeReceiverAgent.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/agent/runtime/PipeRuntimeAgent.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/v1/IoTDBThriftConnectorClient.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/v1/IoTDBThriftConnectorV1.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/v1/IoTDBThriftReceiverV1.java
- iotdb-core/node-commons/src/assembly/resources/conf/iotdb-common.properties
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/conf/CommonConfig.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/conf/CommonDescriptor.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/config/PipeConfig.java
* Add a parameter in iotdb-core/node-commons/src/assembly/resources/conf/iotdb-common.properties to control the connection timeout.
* Set the pipe connection timeout between sender and receiver to 15 mins to allow long time-cost load operation.
* Redesign the pipe receiver's dir to avoid file resource races when different tsfile load operations concurrently modify the same tsfile.
(cherry picked from commit 1e11ab64cc176220646f244a76d1a4cfde35b239)
> [To rel/1.2][IOTDB-6075] Pipe: File resource races when different tsfile load operations concurrently modify the same tsfile at receiver (#10629)

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/load/LoadTsFileManager.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/StorageEngine.java
After loading tsfile, it causes 100% load on one CPU core.
it was a bug in JDK1.8.
[JDK-8129861](https://bugs.openjdk.java.net/browse/JDK-8129861)
[JDK-8022642](https://bugs.openjdk.java.net/browse/JDK-8022642)
1. set corePoolSize to 1 to avoid high processor load
2. lazy initialization: init loadTsFileManager  on first call
> [IOTDB-6072] Load: workaround to CPU 100% after loading tsfile when using JDK8 runtime

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/load/LoadTsFileManager.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/StorageEngine.java
cherry-pick: [pr](https://github.com/apache/iotdb/pull/10624)
> [To rel/1.2][IOTDB-6072] Load: workaround to CPU 100% after loading tsfile when using JDK8 runtime (#10624)

- iotdb-client/session/src/main/java/org/apache/iotdb/session/Session.java
- iotdb-client/session/src/main/java/org/apache/iotdb/session/pool/SessionPool.java
The time span of https://github.com/apache/iotdb/pull/10600 is too large and other interface has changed uniformly.
> Keep special case consistent between  `LastDataQueryForOneDevice` and others

- server/src/main/java/org/apache/iotdb/db/engine/StorageEngine.java
- server/src/main/java/org/apache/iotdb/db/engine/load/LoadTsFileManager.java
cherry-pick: [pr](https://github.com/apache/iotdb/pull/10624)
> [To rel/1.1][IOTDB-6072] Load: workaround to CPU 100% after loading tsfile when using JDK8 runtime

- iotdb-core/confignode/src/assembly/resources/sbin/stop-confignode.sh
- iotdb-core/datanode/src/assembly/resources/sbin/stop-datanode.sh
- iotdb-core/node-commons/src/assembly/resources/sbin/stop-standalone.sh
support `./sbin/stop-confignode.sh -f`
support `./sbin/stop-datanode.sh -f`
support `./sbin/stop-standalone.sh -f`
> [IOTDB-6077]: Stop script addition -f

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/exception/exchange/GetTsBlockFromClosedOrAbortedChannelException.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/exchange/MPPDataExchangeManager.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/exchange/sink/SinkChannel.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/exchange/source/SourceHandle.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/scheduler/FixedRateFragInsStateTracker.java
details could be found at: https://apache-iotdb.feishu.cn/docx/WGPPdHjC2opleXxDpwAcHIJJnRd
However, we think that if we add a Lock in MppDataExchangeManager, it will make this module more complex and harder to maintain. In this pr, we decide to make a simpler fix by using the QueryTerminator as the last guard.
> Fix the issue that Drivers of query with limit clause can not be finished timely

- client-py/SessionPoolExample.py
- client-py/iotdb/SessionPool.py
- client-py/tests/test_session.py
- client-py/tests/test_session_pool.py
Session.init_from_node_urls() is not supported in rel/1.1, so we should remove it in session pool.
> [To rel/1.1] Remove multi-IP initialization in session pool of client-py

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/mtree/impl/mem/snapshot/MemMTreeSnapshotUtil.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/tag/TagManager.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/utils/FileUtils.java
Error message should not be printed when the tmp file does not exist.
> [IOTDB-6074] Ignore error message when TagManager createSnapshot

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/mtree/impl/pbtree/schemafile/WrappedSegment.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/metadata/mtree/schemafile/WrappedSegmentTest.java
The aliasKeyList in PBTree WrappedSegment maintains an index on aliases. The indexes in the aliasKeyList should be updated when updating the Record. However, the current implementation forgets to update the index in the aliasKeyList when the original Alias is null, which is a logical bug.
This PR fixes this bug and adds unit tests.
> Fix error update alias in PB_Tree WrappedSegment

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/utils/datastructure/AlignedTVList.java
In some scenario, the Binary in AlignedTVList will be null if this field is empty in current row. We need to handle this scenario to get rid of NPE in WAL snapshot taking stage. 
See a similar issue here: https://github.com/apache/iotdb/pull/9884 
**Current fix**: we use an empty Binary as a placeholder here. It won't lead to data error because whether this field is null or not is decided by the bitMap rather than the object's value here.
> [To rel/1.2] Fix the NPE issue when taking snapshot in WAL combined with Aligned Binary

- server/src/main/java/org/apache/iotdb/db/utils/datastructure/AlignedTVList.java
In some scenario, the Binary in AlignedTVList will be null if this field is empty in current row. We need to handle this scenario to get rid of NPE in WAL snapshot taking stage. 
See a similar issue here: https://github.com/apache/iotdb/pull/9884 
**Current fix**: we use an empty Binary as a placeholder here. It won't lead to data error because whether this field is null or not is decided by the bitMap rather than the object's value here.
> [To rel/1.1] Fix the NPE issue when taking snapshot in WAL combined with Aligned Binary

- iotdb-api/pipe-api/src/main/java/org/apache/iotdb/pipe/api/PipeConnector.java
- iotdb-api/pipe-api/src/main/java/org/apache/iotdb/pipe/api/PipeProcessor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/config/constant/PipeExtractorConstant.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/extractor/IoTDBDataRegionExtractor.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/pipe/extractor/IoTDBDataRegionExtractorTest.java
Problem: https://jira.infra.timecho.com:8443/browse/TIMECHODB-229
Fix: 
- When user specifies 'extractor.realtime.mode'='log', we use hybrid extractors which can automatically degrade to file mode when load is too heavy.
- Add a parameter: 'extractor.realtime.mode'='forced-log', the pipe will always use log mode and will never degrade to file mode.
> [IOTDB-6081] Pipe: use HybridExtractor instead of LogExtractor when realtime mode is set to log to avoid OOM under heavy insertion load

- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/config/RatisConfig.java
- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/exception/RatisUnderRecoveryException.java
- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/ratis/RatisConsensus.java
- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/ratis/utils/Utils.java
- iotdb-core/consensus/src/test/java/org/apache/iotdb/consensus/ratis/RatisConsensusTest.java
- iotdb-core/consensus/src/test/java/org/apache/iotdb/consensus/ratis/RecoverReadTest.java
- iotdb-core/consensus/src/test/java/org/apache/iotdb/consensus/ratis/TestUtils.java
cherry-pick of https://github.com/apache/iotdb/pull/10597
> [To rel/1.2][IOTDB-5557] [RatisConsensus] Support linearizable read during recovery

- iotdb-api/pipe-api/src/main/java/org/apache/iotdb/pipe/api/PipeConnector.java
- iotdb-api/pipe-api/src/main/java/org/apache/iotdb/pipe/api/PipeProcessor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/config/constant/PipeExtractorConstant.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/extractor/IoTDBDataRegionExtractor.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/pipe/extractor/IoTDBDataRegionExtractorTest.java
* When user specifies 'extractor.realtime.mode'='log', we use hybrid extractors which can automatically degrade to file mode when load is too heavy.
* Add a parameter: 'extractor.realtime.mode'='forced-log', the pipe will always use log mode and will never degrade to file mode.
---------
(cherry picked from commit 01378cc91b0a4349f8a714754f82054ec9b425fb)
> [To rel/1.2][IOTDB-6081] Pipe: use HybridExtractor instead of LogExtractor when realtime mode is set to log to avoid OOM under heavy insertion load

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/selector/estimator/ReadPointCrossCompactionEstimator.java
In the existing memory estimation method, the memory estimation required for seq files,unSeq files, and target files is estimated respectively. The mods file size of the source file is not factored into the memory estimate. This optimization takes the mods file size into account in memory estimates. See the documentation for details: https://apache-iotdb.feishu.cn/docx/UTkZd9ynbo99o6xuzNVc90wlnxg
> [To rel/1.2] factor the mods file size into the cross-space merge memory estimate

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/selector/estimator/ReadPointCrossCompactionEstimator.java
In the existing memory estimation method, the memory estimation required for seq files,unSeq files, and target files is estimated respectively. The mods file size of the source file is not factored into the memory estimate. This optimization takes the mods file size into account in memory estimates. See the documentation for details:https://apache-iotdb.feishu.cn/docx/UTkZd9ynbo99o6xuzNVc90wlnxg
> factor the mods file size into the cross-space merge memory estimate

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/exchange/MPPDataExchangeManager.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/exchange/sink/SinkChannel.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/memory/MemoryPool.java
If we do not add syncronized on the future of MemoryPool.tryCancel(), it may lead to memory leak like this:
When close method of SharedTsBlockQueue is invoked, it will update bufferRetainedSizeInBytes using the value returned by tryCancel because if the MemoryReservationFuture is not completed, it means that the size of TsBlock is added wrongly.(Memory used by that TsBlock is not registered in MemoryPool since reserving memory failed)
However, it's possible that the MemoryReservationFuture is completed by MemoryPool.free concurrently and then the free method registers the TsBlock in MemoryPool while tryCancel still returns the size of TsBlock, leading to remaining records in the MemoryReservationMap.
> Fix potential memory leak in MemoryPool

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/schedule/comparator/DefaultCompactionTaskComparatorImpl.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/compaction/CompactionTaskComparatorTest.java
Add time partition in compaction comparator.
If the time partition of two tasks are different. We prefer to execute task with greater time partition because we want to compact files with new data.
> [To rel/1.2] Add time partition in compaction comparator

- server/src/main/java/org/apache/iotdb/db/engine/compaction/schedule/comparator/DefaultCompactionTaskComparatorImpl.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/CompactionTaskComparatorTest.java
Add time partition in compaction comparator.
If the time partition of two tasks are different. We prefer to execute task with greater time partition because we want to compact files with new data.
> [To rel/1.1] Add time partition in compaction comparator

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/schedule/comparator/DefaultCompactionTaskComparatorImpl.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/compaction/CompactionTaskComparatorTest.java
Add time partition in compaction comparator.
If the time partition of two tasks are different. We prefer to execute task with greater time partition because we want to compact files with new data.
> Add time partition in compaction comparator

- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/cq/CQManager.java
see [jira](https://issues.apache.org/jira/browse/IOTDB-6085)
> [IOTDB-6085] NullPointerException in readAsync when Ratis leader is changing

- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/cq/CQManager.java
cherry-pick [pr](https://github.com/apache/iotdb/pull/10617)
> [To rel/1.2][IOTDB-6085] NullPointerException in readAsync when Ratis leader is changing

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/buffer/TimeSeriesMetadataCache.java
- iotdb-core/tsfile/src/main/java/org/apache/iotdb/tsfile/read/TsFileSequenceReader.java
- iotdb-core/tsfile/src/test/java/org/apache/iotdb/tsfile/read/TimeSeriesMetadataReadTest.java
The cost of new Path is too large, we need to avoid redundant of it.
> Remove  redundant new Path in query process

- server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/utils/executor/readchunk/SingleSeriesCompactionExecutor.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/inner/ReadChunkCompactionPerformerNoAlignedTest.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/utils/CompactionFileGeneratorUtils.java
See [IOTDB-5662](https://issues.apache.org/jira/browse/IOTDB-5662).
The reason for this bug is that the encoding type of chunks that merged together is different with each other.
> [To rel/1.1] [IOTDB-5662] Fix BufferedUnderflowException occurs in inner space compaction

- consensus/src/test/java/org/apache/iotdb/consensus/iot/ReplicateTest.java
- consensus/src/test/java/org/apache/iotdb/consensus/iot/StabilityTest.java
cherry-pick [pr](https://github.com/apache/iotdb/pull/10530)
> [To rel/1.1][IOTDB-6061] Fix the instability failure caused by initServer in IoTConsensus UT not binding to the corresponding port 

- iotdb-core/consensus/src/test/java/org/apache/iotdb/consensus/iot/ReplicateTest.java
- iotdb-core/consensus/src/test/java/org/apache/iotdb/consensus/iot/StabilityTest.java
cherry-pick [pr](https://github.com/apache/iotdb/pull/10540)
> [To rel/1.2][IOTDB-6061] Fix the instability failure caused by initServer in IoTConsensus UT not binding to the corresponding port

- consensus/src/test/java/org/apache/iotdb/consensus/iot/ReplicateTest.java
cherry-pick [pr](https://github.com/apache/iotdb/pull/10723)
> [To rel/1.1][IOTDB-6061] Fix the instability failure caused by initServer in IoTConsensus UT not binding to the corresponding port

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/load/AlignedChunkData.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/AnalyzeVisitor.java
- iotdb-core/tsfile/src/main/java/org/apache/iotdb/tsfile/write/chunk/AlignedChunkWriterImpl.java
Bug caused by changing the default compressType of iotdb from SNAPPY to LZ4.
buildChunk  use the default configuration to create TimeChunk, so the default compressType is different between the old version and the new version, resulting in an error.
create TimeChunk with the corresponding chunkHeader in the tsfile.
> [IOTDB-6078] Load: Allow different chunks have different compressor and encoder & Load time chunk using compressor recorded in chunk header

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/AnalyzeVisitor.java
cherry-pick: https://github.com/apache/iotdb/pull/10715
> [To rel/1.2][IOTDB-6088] Load: Optimize the schema creation process & Avoid OOM and ratis createMultiTimeseriesPlan bufferSize too large

- server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
- server/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java
- server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/AnalyzeVisitor.java
cherry-pick: https://github.com/apache/iotdb/pull/10715
> [To rel/1.1][IOTDB-6088] Load: Optimize the schema creation process & Avoid OOM and ratis createMultiTimeseriesPlan bufferSize too large 

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/extractor/IoTDBDataRegionExtractor.java
The following parameters are NOT ready for production use. This commit removes the entry of use.
```
'pipe.realtime.mode' = 'log',
'pipe.realtime.mode' = 'hybrid'
```
> [To rel/1.2] Disable some pipe extractor's features due to unstability

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/task/AbstractCompactionTask.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/task/CrossSpaceCompactionTask.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/task/InnerSpaceCompactionTask.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/selector/estimator/AbstractCompactionEstimator.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/selector/estimator/AbstractInnerSpaceEstimator.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/selector/estimator/CompactionEstimateUtils.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/selector/estimator/FastCompactionInnerCompactionEstimator.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/selector/estimator/FileInfo.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/selector/estimator/ReadChunkInnerCompactionEstimator.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/selector/estimator/ReadPointCrossCompactionEstimator.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/compaction/CompactionSchedulerTest.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/compaction/utils/CompactionTaskMemCostEstimatorTest.java
- iotdb-core/tsfile/src/main/java/org/apache/iotdb/tsfile/read/TsFileSequenceReader.java
For in-space merge, the memory evaluation process is added. At the beginning of task execution, the system evaluates the memory size of the task to determine whether the evaluation result is smaller than the configured maximum memory size. If the evaluation result is smaller than the configured maximum memory size, the task can be executed normally. Added two memory estimators, the ReadChunkEstimator and the FastCompactionEstimator, which will be used when performer of the merge task is ReadChunk. Otherwise, use FastCompactionEstimator
see https://github.com/apache/iotdb/pull/10688
> [To rel/1.2] [IOTDB-6090] add memory estimator on inner space compaction

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/task/CrossSpaceCompactionTask.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/task/InnerSpaceCompactionTask.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/utils/validator/CompactionValidator.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/utils/validator/NoneCompactionValidator.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/utils/validator/ResourceAndTsfileCompactionValidator.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/utils/validator/ResourceOnlyCompactionValidator.java
Skip compaction resources overlap validation if a task is UnSequenceSpaceTask
https://github.com/apache/iotdb/pull/10708
> [To rel/1.2] Skip compaction resources overlap validation if a task is UnSequenceSpaceTask

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/utils/executor/fast/AlignedSeriesCompactionExecutor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/utils/executor/fast/NonAlignedSeriesCompactionExecutor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/utils/executor/fast/SeriesCompactionExecutor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/utils/executor/fast/element/ChunkMetadataElement.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/utils/executor/fast/element/PageElement.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/compaction/FastCompactionPerformerWithInconsistentCompressionTypeAndEncodingTest.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/compaction/utils/CompactionTestFileWriter.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/compaction/utils/CompactionTestFileWriterTest.java
In FastCompactionPerformer, there is no logic to judge whether the CompressionType or TsEncodingType are same or not between two candidate chunk, which will lead to a false case that there are two pages whose compression type are different in one Chunk.
This PR is used to fix this issue.  That is, when dealing with chunks whose compression type are different, decode all points and compact them into a new chunk rather than copy page directly
> [To rel/1.2] Add compression and encoding type check for FastCompactionPerformer

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/task/CrossSpaceCompactionTask.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/task/InnerSpaceCompactionTask.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/utils/validator/CompactionValidator.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/utils/validator/NoneCompactionValidator.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/utils/validator/ResourceAndTsfileCompactionValidator.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/utils/validator/ResourceOnlyCompactionValidator.java
Skip compaction resources overlap validation if a task is UnSequenceSpaceTask
> Skip compaction resources overlap validation if a task is UnSequenceSpaceTask

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/DataRegion.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/HashLastFlushTimeMap.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/performer/impl/FastCompactionPerformer.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/tsfile/TsFileResource.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/tsfile/timeindex/DeviceTimeIndex.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/tsfile/timeindex/FileTimeIndex.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/tsfile/timeindex/ITimeIndex.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/LastFlushTimeMapTest.java
When recover the last flush time map from two sequence TsFiles. 
* TsFile A only contains device1 with end time = 10000
* TsFile B only contains device2 with end time = 9999
And the resources of these two TsFiles have been downgrade to FileTimeIndex.
The previous code will use TsFile B with end time = 9999 to recover the last flush time of device1, which would cause sequence files overlapped.
> Fix recover last flush time map bug

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/extractor/realtime/PipeRealtimeDataRegionHybridExtractor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/extractor/realtime/PipeRealtimeDataRegionLogExtractor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/extractor/realtime/PipeRealtimeDataRegionTsFileExtractor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/task/connection/BlockingPendingQueue.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/task/connection/PipeEventCollector.java
- iotdb-core/node-commons/src/assembly/resources/conf/iotdb-common.properties
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/conf/CommonConfig.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/consensus/index/impl/RecoverProgressIndex.java
- iotdb-core/node-commons/src/test/java/org/apache/iotdb/commons/pipe/PipeMetaDeSerTest.java
This commit fixes 2 issues:
* Subscrption running with the pattern option may cause OOM
How to reproduce:
1. execute sql:
```
create pipe test1 
with extractor (
'extractor.history.enable'='false', 
'extractor'='iotdb-extractor', 
'extractor.realtime.mode'='log',
'extractor.pattern'='root'
) 
with connector (
'connector'='iotdb-thrift-connector-v1',
'connector.node-urls'='127.0.0.1:6668'
);
start pipe test1;
```
2. run benchmark: 1 database, 10 devices, 10 measurements.
* java.lang.UnsupportedOperationException: Unsupported PipeRuntimeException type 0 caused by de/ser issue of RecoverProgressIndex
> [IOTDB-6097] Pipe: Avoid subscrption running with the pattern option causing OOM & Fix de/ser of RecoverProgressIndex

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/extractor/realtime/PipeRealtimeDataRegionHybridExtractor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/extractor/realtime/PipeRealtimeDataRegionLogExtractor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/extractor/realtime/PipeRealtimeDataRegionTsFileExtractor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/task/connection/BlockingPendingQueue.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/task/connection/PipeEventCollector.java
- iotdb-core/node-commons/src/assembly/resources/conf/iotdb-common.properties
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/conf/CommonConfig.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/consensus/index/impl/RecoverProgressIndex.java
- iotdb-core/node-commons/src/test/java/org/apache/iotdb/commons/pipe/PipeMetaDeSerTest.java
This commit fixes 2 issues:
* Subscrption running with the pattern option may cause OOM
How to reproduce:
1. execute sql: ``` create pipe test1 with extractor ( 'extractor.history.enable'='false', 'extractor'='iotdb-extractor', 'extractor.realtime.mode'='log', 'extractor.pattern'='root' ) with connector ( 'connector'='iotdb-thrift-connector-v1', 'connector.node-urls'='127.0.0.1:6668' );
start pipe test1;
```
2. run benchmark: 1 database, 10 devices, 10 measurements.
* java.lang.UnsupportedOperationException: Unsupported PipeRuntimeException type 0 caused by de/ser issue of RecoverProgressIndex <img width="1194" alt="image" src="https://github.com/apache/iotdb/assets/30497621/d2d35ee7-293b-4594-92f3-fc10b2aa8313">
(cherry picked from commit f0f168249b27e0eb50665cb65b47201cf7db3671)
> [To rel/1.2][IOTDB-6097] Pipe: Avoid subscrption running with the pattern option causing OOM & Fix de/ser of RecoverProgressIndex (#10767)

- integration-test/src/test/java/org/apache/iotdb/db/it/aligned/IoTDBInsertAlignedValues2IT.java
- iotdb-core/tsfile/src/main/java/org/apache/iotdb/tsfile/write/page/TimePageWriter.java
- iotdb-core/tsfile/src/test/java/org/apache/iotdb/tsfile/write/writer/TimeChunkWriterTest.java
To reproduce, set `max_number_of_points_in_page = 2`.
Then execute the following sqls:
```sql
insert into root.sg.d1(time, s1,s2) aligned values(1,'aa','bb')
insert into root.sg.d1(time, s1,s2) aligned values(1,'aa','bb')
insert into root.sg.d1(time, s1,s2) aligned values(1,'aa','bb')
flush
```
The reason of this bug is sometimes time page may be empty, we do not need to update the statistics.
> [IOTDB-6098] Fix a possible flush error when using aligned timeseries

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/AnalyzeVisitor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/execution/config/executor/ClusterConfigTaskExecutor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/statement/metadata/DatabaseSchemaStatement.java
In a benchmark scenario with 500 devices and 50 sensors, the load gives a No Such File error. 
`constructTsFileResource` only update the tsfile resource information and does not create a file, then every time it determines whether the file exists, causes it to go to the wrong branch and add resource to LoadTsfileStatement wrongly and repeatedly. As a result, multiple identical tsfile resources are stored in the `resources` of  `LoadTsFileStatement`.After loading the file once, it will be deleted in tmp dir and NoSuchFileException will be reported in the subsequent load.
constructTsFileResource 只会更新tsfileResource而不会创建一个新文件，导致每次对tsfile resource 逻辑判断是否存在该文件时会走入错误的分支而重复添加该 tsfile resource到 LoadTsfileStatement 中。在第一次load后，存储在临时文件夹里的tsfile会被删掉，而导致后续重复的load找不到这个文件而报错 NoSuchFIleException.
> [IOTDB-6094] Load: Fix error in if/else judgment of tsfileResource exists or not & Reduce warn log when timeseries exist

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/extractor/realtime/listener/PipeInsertionDataNodeListener.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/plan/node/load/LoadSingleTsFileNode.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/DataRegion.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/memtable/TsFileProcessor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/utils/FileLoaderUtils.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/TsFileResourceProgressIndexTest.java
Support tsfile cascade transport. For example, there are 3 iotdb clusters A, B and C. Now we can use pipe to transport tsfile from A to C (via B, A -> B -> C).
> [IOTDB-6101] Pipe: Support tsfile cascade transport 

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/extractor/realtime/listener/PipeInsertionDataNodeListener.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/plan/node/load/LoadSingleTsFileNode.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/DataRegion.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/memtable/TsFileProcessor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/utils/FileLoaderUtils.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/TsFileResourceProgressIndexTest.java
Support tsfile cascade transport. For example, there are 3 iotdb clusters A, B and C. Now we can use pipe to transport tsfile from A to C (via B, A -> B -> C).
(cherry picked from commit b3a4bdf813f7f307a4a8b06aab73432da773dcda)
> [To rel/1.2][IOTDB-6101] Pipe: Support tsfile cascade transport  (#10795)

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/thrift/impl/ClientRPCServiceImpl.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/parser/StatementGenerator.java
Generate TimeFilterExpression defaultly, we  stop us from putting NullCacheEntry in LastCache.
> Stop generating FilterExpression if we don't specify the time filter in last query session api

- iotdb-core/node-commons/src/assembly/resources/sbin/iotdb-common.sh
[To rel/1.2] Fixed issue where iotdb common.sh was null when obtaining iotdb port
> [To rel/1.2] Fixed issue where iotdb common.sh was null when obtaining iotdb port

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/utils/log/CompactionLogAnalyzer.java
If the name of a storage group contains keyword 'source', 'target', 'empty' or '.tsfile', the compaction recover task will replace these keywords, which cause the analysis failed.
> Fix compaction log keyword bug

- iotdb-core/datanode/src/assembly/resources/tools/tsfile/overlap-statistic-tool.bat
- iotdb-core/datanode/src/assembly/resources/tools/tsfile/overlap-statistic-tool.sh
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/tool/ListTimeRangeImpl.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/tool/OverlapStatisticTool.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/tool/TsFileStatisticReader.java
> Add Overlap check tool

- server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/utils/log/CompactionLogAnalyzer.java
If the name of a storage group contains keyword 'source', 'target', 'empty' or '.tsfile', the compaction recover task will replace these keywords, which cause the analysis failed.
https://github.com/apache/iotdb/pull/10785
> [To rel/1.1] Fix compaction log keyword bug

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/service/TemporaryQueryDataFileService.java
We use `deleteDirectory` instead of `cleanDirectory`.
`cleanDirectory` will only delete all the files in that directory, but will not delete the directory itself.
`deleteDirectory` will delete a directory recursively, including itself.
> [IOTDB-6104] Remove tmp directory for udf query completely while query end

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/wal/checkpoint/CheckpointManager.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/wal/node/WALNode.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/wal/checkpoint/CheckpointManagerTest.java
This commit reconstructs the execution logic of DeleteOutdatedFileTask, abstracting the collation logic into the following steps:
1. Delete obsolete wal files
2. Update the valid information ratio
3. Determine whether snapshot or flush is required based on the valid information ratio
4. Summarize the execution result and export it
In addition, there are two updates:
1. The initial assignment process of the property is moved to the constructor, which makes the code look cleaner.
2. If the retry process after snapshot or flush is deleted, it is difficult to execute statistics containing multiple retry results at a time.
> Refactoring DeleteOutdatedFileTask in WalNode

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/exception/CompactionExceptionHandler.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/task/CrossSpaceCompactionTask.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/task/InnerSpaceCompactionTask.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/utils/CompactionUtils.java
When an exception occurs in the execution of a cross-space task, when some source files exist and all target files have been generated, the system will decide to delete the remaining source files. When the source files are deleted, the number of files in the monitoring system is not updated, and it should be updated
> fix inaccurate statistics for monitoring the number of unseq Tsfile on cross compaction

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/HashLastFlushTimeMap.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/tsfile/TsFileManager.java
The bug of this reason is when recover the last flush time from TsFileResource and the compaction change the TsFileList in TsFileManager at the same time.
> Fix a concurrent bug when recover last flush time and compact

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/memtable/TsFileProcessor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/utils/datastructure/AlignedTVList.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/memtable/TsFileProcessorTest.java
When insert data into AlignedTVList like this way.
Insert 1000 rows of d1.s1 by aligned tablet interface, then insert 1000 rows of d1.s2, then then insert 1000 rows of d1.s3.
The current logic will only calculate the black and purple part of memory cost. 
Beside, the calculation of purple part is not correct.
The correct calculation is acquired array number * memory size of an array, however, the current is acquired array number * memory size of a data point.
> [IOTDB-6108] Fix AlignedTVList memory calculation is imprecise

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/execution/config/executor/ClusterConfigTaskExecutor.java
The previous if/else logic judgment will cause exceptions which excepts DATABASE_ALREADY_EXISTS to be set to success
> [IOTDB-6113] Load: Fix setDatabase does not print logs and set failure except DATABASE_ALREADY_EXISTS

- iotdb-core/datanode/src/assembly/resources/tools/schema/print-pb-tree-file.sh
`SchemaFileSketchTool` is renamed to `PBTreeFileSketchTool`.
> Fix SchemaFileSketchTool is not found

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/AlignedSeriesScanUtil.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/read/reader/chunk/MemAlignedPageReader.java
- iotdb-core/tsfile/src/main/java/org/apache/iotdb/tsfile/read/reader/page/AlignedPageReader.java
Previously, for aligned time series, we only use statistics to skip offset while the queryFilter is null, however if the query filter is time filter, it can also use that.
> [IOTDB-6112] Fix Limit & Offset push down doesn't take effect while there exist time filter

- integration-test/src/test/java/org/apache/iotdb/confignode/it/partition/IoTDBPartitionCreationIT.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/load/balancer/RegionBalancer.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/load/cache/region/RegionCache.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/thrift/impl/DataNodeRegionManager.java
**Updations:**
1. Both the Running and Unknown DataNodes can be used when making CreateRegionGroupsPlan. Since we have IoTDB-Region-Maintainer thread in PartitionManager to ensure the creation at Unknown DataNodes will finally successed.
2. Distinguish re-creation and re-deletion in IoTDB-Region-Maintainer. So that these corner cases wouldn't stuck into infinite loop.
3. A RegionGroup will always been Removing status as soon as it has been removed.
> [To rel/1.2][IOTDB-6111] Fix Region creation bugs

- iotdb-core/datanode/pom.xml
The bugsnag dependency is of no use to us, so we will remove the dependency
- Bugsnag (https://www.bugsnag.com/platforms/java, https://github.com/bugsnag/bugsnag-java) is an error monitoring platform designed for real-time monitoring and tracking of errors and crashes within applications. It provides cross-platform error monitoring and reporting tools that assist development teams in swiftly identifying and resolving issues in applications, thereby delivering a more stable and efficient application experience. When errors, crashes, or exceptions occur during application runtime, Bugsnag captures and automatically reports relevant error information, including error stack traces, environmental details, user data, and more. Development teams can utilize Bugsnag's console to review error …
> Remove useless dependency bugsnag

- distribution/pom.xml
- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/ratis/SnapshotStorage.java
- iotdb-core/datanode/pom.xml
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/protocol/legacy/IoTDBLegacyPipeConnector.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/session/SessionManager.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/thrift/impl/ClientRPCServiceImpl.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/LogicalPlanBuilder.java
- iotdb-core/node-commons/pom.xml
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/path/fa/dfa/graph/NFAGraph.java
- pom.xml
Currently, we are using both commons-lang and commons-lang3 in our code. We can replace the usage of commons-lang to commons-lang3 to reduce the distribution package size.
> Replace dependency commons-lang to commons-lang3

- iotdb-core/datanode/pom.xml
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/compaction/inner/InnerSpaceCompactionExceptionTest.java
The h2-mvstore dependency is of no use to us, so we will remove the dependency.
> Remove useless dependency h2-mvstore

- integration-test/src/test/java/org/apache/iotdb/pipe/it/IoTDBPipeDemoIT.java
Changed IoTDBPipeDemoIT timeout to avoid unstable connection causing pre-timeout.
<hr>
This PR has:
<hr>
> Pipe IT: Changed IoTDBPipeDemoIT timeout to 10 mins to allow pipe-internal retries when unstable cases occuring

- consensus/src/main/java/org/apache/iotdb/consensus/iot/client/AsyncIoTConsensusServiceClient.java
- node-commons/src/main/java/org/apache/iotdb/commons/client/async/AsyncConfigNodeHeartbeatServiceClient.java
- node-commons/src/main/java/org/apache/iotdb/commons/client/async/AsyncConfigNodeIServiceClient.java
- node-commons/src/main/java/org/apache/iotdb/commons/client/async/AsyncDataNodeHeartbeatServiceClient.java
- node-commons/src/main/java/org/apache/iotdb/commons/client/async/AsyncDataNodeInternalServiceClient.java
- node-commons/src/main/java/org/apache/iotdb/commons/client/async/AsyncDataNodeMPPDataExchangeServiceClient.java
- node-commons/src/test/java/org/apache/iotdb/commons/client/ClientManagerTest.java
This reverts commit 1afc93323562344e9356142eb89bc8800b7dd7b2 because it may introduce some other errors that will take more time to fix.
> Revert "[To rel/1.1][IOTDB-6106] Fixed the timeout parameter not working in thrift asyncClient

- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/iot/IoTConsensus.java
- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/iot/IoTConsensusServerImpl.java
- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/iot/client/DispatchLogHandler.java
- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/iot/logdispatcher/LogDispatcher.java
- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/ratis/RatisConsensus.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/concurrent/ThreadName.java
see [jira](https://issues.apache.org/jira/browse/IOTDB-6116)
> [IOTDB-6116] Disassociate the IoTConsensus retry logic from the forkjoinPool

- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/consensus/ConsensusManager.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/consensus/DataRegionConsensusImpl.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/consensus/SchemaRegionConsensusImpl.java
Currently RatisConsensus supports read timeout.
We should let it be consistent with our default request timeout, i.e. Thrift connection timeout.
> [RatisConsensus] Unify read timeout to Thrift connection timeout

- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/iot/IoTConsensus.java
- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/iot/IoTConsensusServerImpl.java
- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/iot/client/DispatchLogHandler.java
- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/iot/logdispatcher/LogDispatcher.java
- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/ratis/RatisConsensus.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/concurrent/ThreadName.java
cherry-pick [pull](https://github.com/apache/iotdb/pull/10872)
> [To rel/1.2][IOTDB-6116] Disassociate the IoTConsensus retry logic from the forkjoinPool

- example/session/src/main/java/org/apache/iotdb/DataMigrationExample.java
The example for data migration may generate warnings, causing the data import to fail. Now, I have made corrections to the example and added comments.
> Fix dataMigrationExample wrong concurrency error

- LICENSE-binary
- pom.xml
There are some vulnerability issues about early versions of guava. This PR is upgrading it to latest version.
https://mvnrepository.com/artifact/com.google.guava/guava
> Upgrade guava to avoid vulnerability issue

- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/executable/ExecutableManager.java
On some OS systems(eg.windows), it is not possible to delete a file when it is open or in use. The Jar file will be used by the acitive UDFClassLoader and can not be deleted On windows, which will lead to the failure of the CreateFunctionTask.
> Override existing jar instead of deleting it when registering UDF

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/AlignedSeriesScanOperator.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/AlignedSeriesScanUtil.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/Analysis.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/AnalyzeVisitor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/parser/ASTVisitor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/LogicalPlanBuilder.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/LogicalPlanVisitor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/OperatorTreeGenerator.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/plan/node/PlanGraphPrinter.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/plan/node/source/AlignedSeriesScanNode.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/statement/crud/QueryStatement.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/memtable/AlignedReadOnlyMemChunk.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/read/reader/chunk/DiskAlignedChunkLoader.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/read/reader/chunk/MemAlignedChunkLoader.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/read/reader/chunk/MemAlignedChunkReader.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/read/reader/chunk/MemAlignedPageReader.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/read/reader/chunk/metadata/DiskAlignedChunkMetadataLoader.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/read/reader/chunk/metadata/MemAlignedChunkMetadataLoader.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/utils/FileLoaderUtils.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/execution/operator/AlignedSeriesScanOperatorTest.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/execution/operator/OperatorMemoryTest.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/plan/plan/QueryLogicalPlanUtil.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/read/reader/chunk/MemAlignedChunkLoaderTest.java
- iotdb-core/tsfile/src/main/java/org/apache/iotdb/tsfile/read/TsFileAlignedSeriesReaderIterator.java
- iotdb-core/tsfile/src/main/java/org/apache/iotdb/tsfile/read/reader/chunk/AlignedChunkReader.java
- iotdb-core/tsfile/src/main/java/org/apache/iotdb/tsfile/read/reader/page/AlignedPageReader.java
- iotdb-core/tsfile/src/main/java/org/apache/iotdb/tsfile/read/reader/series/FileSeriesReader.java
- iotdb-core/tsfile/src/test/java/org/apache/iotdb/tsfile/write/TsFileIntegrityCheckingTool.java
- pom.xml
If we query all sensors of one device or any queried sensor has the same value count as the time column, we can use the statistics to skip.
> [IOTDB-6115] Fix Limit & Offset push down doesn't take effect while there exist null value

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/mtree/impl/pbtree/CachedMTreeStore.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/mtree/impl/pbtree/cache/CacheManager.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/mtree/impl/pbtree/cache/CacheMemoryManager.java
In PB_Tree mode, when a SchemaRegion is deleted, the corresponding MTree needs to be deleted, and all references holding MTreeStore need to be released so that the deprecated objects can be GC.
> Fix memory leak when deleting database in PB_Tree mode

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/agent/runtime/PipeRuntimeAgent.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/tsfile/TsFileResource.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/wal/recover/file/UnsealedTsFileRecoverPerformer.java
When we load a tsfile , if it has a tsFileResource, there are two cases in tsFileResource: 
1. it doesn't have a progress index, we just give it one from system.
2. it has a progress index, the index shouldn't be loaded, it should be **recovered** instead of updating.
> [IOTDB-6122] Pipe: Progress Index markers an incorrect value when load a tsfile with tsfileResource

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/wal/node/WALNode.java
info logs are often printed unnecessarily when no outdated WAL files have been deleted. This fix will reduce the log level to debug. In addition, some optimization of the printed log content.
> reduce wal log output level

- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/PermissionManager.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/TriggerManager.java
- iotdb-core/consensus/src/test/java/org/apache/iotdb/consensus/iot/StabilityTest.java
- iotdb-core/consensus/src/test/java/org/apache/iotdb/consensus/ratis/RatisConsensusTest.java
- iotdb-core/consensus/src/test/java/org/apache/iotdb/consensus/simple/SimpleConsensusTest.java
> consensus module refactor: enhance tests

- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/load/balancer/PartitionBalancer.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/load/balancer/partition/DataPartitionPolicyTable.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/partition/PartitionManager.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/structure/BalanceTreeMap.java
The DataPartitions will be allocated un-balanced if the user insert a big batch data to the cluster firstly. Because the RegionGroup quickly-extension-policy doesn't extend enough RegionGroups for the special case.
In this PR, the RegionGroup extension policy will always ensure the database have enough RegionGroups for allocate new Partitions balancely.
And this PR also add some concise log to record the DataAllotTable
> [IOTDB-6125] Fix DataPartition allocation bug when insert big batch data

- integration-test/src/test/java/org/apache/iotdb/confignode/it/partition/IoTDBAutoRegionGroupExtensionIT.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/load/balancer/PartitionBalancer.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/load/balancer/partition/DataPartitionPolicyTable.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/partition/PartitionManager.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/structure/BalanceTreeMap.java
The DataPartitions will be allocated un-balanced if the user insert a big batch data to the cluster firstly. Because the RegionGroup quickly-extension-policy doesn't extend enough RegionGroups for the special case.
In this PR, the RegionGroup extension policy will always ensure the database have enough RegionGroups for allocate new Partitions balancely.
And this PR also add some concise log to record the DataAllotTable
> [To rel/1.2] [IOTDB-6125] Fix DataPartition allocation bug when insert big batch data

- node-commons/src/main/java/org/apache/iotdb/commons/conf/IoTDBConstant.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/recover/CompactionRecoverManager.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/task/InnerSpaceCompactionTask.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/schedule/comparator/DefaultCompactionTaskComparatorImpl.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/selector/estimator/ReadPointCrossCompactionEstimator.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/selector/impl/SizeTieredCompactionSelector.java
- server/src/main/java/org/apache/iotdb/db/engine/modification/Deletion.java
- server/src/main/java/org/apache/iotdb/db/engine/modification/ModificationFile.java
- server/src/main/java/org/apache/iotdb/db/engine/storagegroup/DataRegion.java
- server/src/main/java/org/apache/iotdb/db/query/context/QueryContext.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/CompactionTaskComparatorTest.java
- server/src/test/java/org/apache/iotdb/db/engine/compaction/inner/InnerSpaceCompactionSelectorTest.java
- server/src/test/java/org/apache/iotdb/db/engine/modification/ModificationFileTest.java
- server/src/test/java/org/apache/iotdb/db/engine/storagegroup/FakedTsFileResource.java
- tsfile/src/test/java/org/apache/iotdb/tsfile/read/common/TimeRangeTest.java
The following commits are optimizations for OOM problems with mods files
> [To rel/1.1] cp commits from master to solve the mods file OOM

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java
- iotdb-core/node-commons/src/assembly/resources/conf/iotdb-common.properties
Remove the following useless configs in iotdb-common.properties.
* frequency_interval_in_minute
* freq_snr
* freq_block_size
> Remove some useless configs

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java
- iotdb-core/node-commons/src/assembly/resources/conf/iotdb-common.properties
Remove the following useless configs in iotdb-common.properties.
* frequency_interval_in_minute
* freq_snr
* freq_block_size
> [To rel/1.2] Remove some useless configs

- iotdb-core/consensus/src/test/java/org/apache/iotdb/consensus/ratis/RatisConsensusTest.java
- iotdb-core/consensus/src/test/java/org/apache/iotdb/consensus/ratis/RecoverReadTest.java
- iotdb-core/consensus/src/test/java/org/apache/iotdb/consensus/ratis/TestUtils.java
cherry-pick of https://github.com/apache/iotdb/pull/10942
> [To rel/1.2] [RatisConsensus] Fix flaky unit tests after linearizable read

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/utils/executor/fast/element/PageElement.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/utils/executor/fast/element/PointElement.java
- iotdb-core/tsfile/src/main/java/org/apache/iotdb/tsfile/read/reader/chunk/AlignedChunkReader.java
- iotdb-core/tsfile/src/main/java/org/apache/iotdb/tsfile/read/reader/page/AlignedPageReader.java
- iotdb-core/tsfile/src/main/java/org/apache/iotdb/tsfile/read/reader/page/LazyLoadAlignedPagePointReader.java
- iotdb-core/tsfile/src/test/java/org/apache/iotdb/tsfile/read/reader/LazyLoadAlignedPagePointReaderTest.java
In this PR, we add a new implementation of IPageReader to get rid of huge memory cost when reading rows of aligned timeseries.
The newly added `LazyLoadAlignedPagePointReader` will construct row one by one as needed rather than deserializing all data points of one page in memory.
Depending on `LazyLoadAlignedPagePointReader`, the memory cost of compaction for aligned chunks will decreased a lot because the data points of one Page of all chunks won't be cached in memory when doing compaction.
> add lazy page reader for aligned page reader to avoid huge memory cost when reading rows of aligned timeseries

- server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/utils/executor/fast/element/PageElement.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/utils/executor/fast/element/PointElement.java
- tsfile/src/main/java/org/apache/iotdb/tsfile/read/reader/chunk/AlignedChunkReader.java
- tsfile/src/main/java/org/apache/iotdb/tsfile/read/reader/page/AlignedPageReader.java
- tsfile/src/main/java/org/apache/iotdb/tsfile/read/reader/page/LazyLoadAlignedPagePointReader.java
- tsfile/src/test/java/org/apache/iotdb/tsfile/read/reader/LazyLoadAlignedPagePointReaderTest.java
See https://github.com/apache/iotdb/pull/10966
> [To rel/1.1] add lazy page reader for aligned page reader to avoid huge memory cost when reading rows of aligned timeseries

- iotdb-core/consensus/pom.xml
commits diff refer to https://github.com/apache/ratis/compare/release-2.5.1...snapshot-branch2
> [RatisConsensus] Bump ratis snapshot version to 2.5.2-8efe8a1-SNAPSHOT

- iotdb-core/consensus/pom.xml
cherry-pick of https://github.com/apache/iotdb/pull/10971
> [To rel/1.2] [RatisConsensus] Bump ratis snapshot version to 2.5.2-8efe8a1-SNAPSHOT

- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/consensus/statemachine/ConfigRegionStateMachine.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/consensus/ConsensusManager.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/cq/CQManager.java
- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/IStateMachine.java
- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/config/RatisConfig.java
- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/ratis/ApplicationStateMachineProxy.java
- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/ratis/utils/Utils.java
- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/simple/SimpleConsensusServerImpl.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/client/ConfigNodeClient.java
- By using ratis's notifyLeaderReady interface, we can ensure that the state machine is restored based on the latest data, thus avoiding potential incomplete recovery issues, see [jira](https://issues.apache.org/jira/browse/IOTDB-6119) for more detail
- The gc log detection threshold is increased from 500ms to 4s, so as to avoid too much useless log such as this
> [IOTDB-6119] Add ConfigNode leader service check

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/protocol/airgap/IoTDBAirGapConnector.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/protocol/thrift/async/IoTDBThriftAsyncConnector.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/protocol/thrift/sync/IoTDBThriftSyncConnector.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/event/EnrichedEvent.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/event/common/tablet/PipeRawTabletInsertionEvent.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/event/common/tsfile/PipeTsFileInsertionEvent.java
Currently when extractor.history is enabled and extractor.pattern is not set, extractor.history.start-time and extractor.history.end-time parameter will not work.
> Pipe: Fix start-time and end-time parameters not working when extracting history data

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/wal/checkpoint/CheckpointManager.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/wal/node/WALNode.java
This commit reconstructs the execution logic of DeleteOutdatedFileTask, abstracting the collation logic into the following steps:
Delete obsolete wal files
Update the valid information ratio
Determine whether snapshot or flush is required based on the valid information ratio
Summarize the execution result and export it
In addition, there are two updates:
The initial assignment process of the property is moved to the constructor, which makes the code look cleaner.
If the retry process after snapshot or flush is deleted, it is difficult to execute statistics containing multiple retry results at a time.
> [To rel/1.2] Refactoring DeleteOutdatedFileTask in WalNode

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/wal/node/WALNode.java
When the wal file disk size exceeds 50G x 0.8, the flush or snapshot logic will be triggered. However, when the active memtable is large enough, the snapshot or flush speed will always be lower than the new generation speed, so the write is always refused. The fix determines that if the threshold is exceeded, the snapshot or flush operation continues until the disk size is below the threshold. In addition, also changed the judgment conditions, the return from ` trySnapshotOrFlushMemTable ` return after failure to success
> Fixed write rejection when wal size exceeds threshold

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/wal/node/WALNode.java
wal obtains IMemTable from memTableInfo twice when deleting obsolete files. The IMemTable is not null when it is obtained the first time, but the imemtable may have been flushed when it is obtained the second time. As a result, the obtained value is null, resulting in NPE
> [To rel/1.2] fix wal npe when memTable has flushed.

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/wal/node/WALNode.java
wal obtains IMemTable from memTableInfo twice when deleting obsolete files. The IMemTable is not null when it is obtained the first time, but the imemtable may have been flushed when it is obtained the second time. As a result, the obtained value is null, resulting in NPE
> fix wal npe when memTable has flushed.

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/execution/config/metadata/ShowClusterDetailsTask.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/execution/config/metadata/ShowClusterTask.java
We need check whether the value is null while using ColumnBuilder.appendXXValue function, if it's null we need to use appendNull instead, otherwise we may encounter NPE while serializing this TsBlock.
> Fix possible NPE while executing show cluster or show cluster details

- iotdb-core/antlr/src/main/antlr4/org/apache/iotdb/db/qp/sql/IoTDBSqlParser.g4
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/parser/ASTVisitor.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/plan/parser/StatementGeneratorTest.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/utils/AuthUtils.java
- iotdb-core/node-commons/src/test/java/org/apache/iotdb/commons/utils/AuthUtilsTest.java
refine auth dcl statement to mysql/postgres style.
> fix auth parser.

- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/path/PathPatternTree.java
- iotdb-core/node-commons/src/test/java/org/apache/iotdb/commons/path/PathPatternTreeTest.java
Execute the following sql, you will see data of root.sg.d2.s1 doesn't delete by `delete from root.*.*.s1`.
```
IoTDB> insert into root.sg.d2(time,s1,s2) values(1,2,3)
IoTDB> flush
+-----------------------------+-------------+-------------+
|                         Time|root.sg.d2.s1|root.sg.d2.s2|
+-----------------------------+-------------+-------------+
|1970-01-01T08:00:00.001+08:00|          2.0|          3.0|
+-----------------------------+-------------+-------------+
It costs 0.153s
IoTDB> delete from root.*.*.s1
+-----------------------------+-------------+-------------+
| …
```
> [IOTDB-6130] Delete data by specific pattern didn't work

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/wal/WALManager.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/wal/node/WALNode.java
Fix wal triggering disk threshold too many times loop, when the threshold is triggered, the original motivation is to keep trying to delete expired files. However, when a WalNode has no files to delete, and the Wal disk file size still exceeds the threshold, the task cannot exit the loop.
Wal disk thresholds are more properly managed by Wal Manager. So this change moves this logic into the Wal Manager.
1. edit `iotdb-common.properties`, add `iot_consensus_throttle_threshold_in_byte=1073741824`(1GB) param;
2. start a 1C1D or 3C3D cluster
3. enable heavy writes (such as 10 clients) through the Grafana plugin or directly view the `data/datanode/wal` directory, with the expectation that WAL files will be sorted when they exceed 'iot_consensus_throttle_threshold_in_byte * 0.8'. Until it is …
> Fixed wal triggering disk threshold loop too many times

- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/ratis/utils/Utils.java
See the details in https://issues.apache.org/jira/browse/RATIS-1879
> [RatisConsensus] use warn_and_return to enable cluster restart when log corruption can be ignored

- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/ratis/utils/Utils.java
cherry-pick of https://github.com/apache/iotdb/pull/11036
> [To rel/1.2] [RatisConsensus] use warn_and_return to enable cluster restart when log corruption can be ignored

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/agent/task/PipeTaskAgent.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/extractor/historical/PipeHistoricalDataRegionTsFileExtractor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/resource/tsfile/PipeTsFileResourceManager.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/thrift/impl/DataNodeInternalRPCServiceImpl.java
Improvements:
* Cache the File objects to reduce the size of TsFileInsertionEvents.
* Limit the frequency of flushing TsFiles when cocurrently creating historical extractors.
* If cluster heartbeat doesn't need PipeMetaList, do not get into PipeTaskAgent. This will prevent datanode from turning UNKNOWN when many pipes are being created.
---------
(cherry picked from commit 1a3568ff2a0a812a6f2b6867fb1261a85978e0dd)
> [To rel/1.2] Pipe: Improve performance for 10000+ pipes (#11021)

- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/ratis/utils/Utils.java
- iotdb-core/consensus/src/test/java/org/apache/iotdb/consensus/ratis/utils/UtilsTest.java
see https://github.com/apache/ratis/pull/915
> [RatisConsensus] retry cache expiration time should be longer than retriable-client wait duration

- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/ratis/utils/Utils.java
- iotdb-core/consensus/src/test/java/org/apache/iotdb/consensus/ratis/utils/UtilsTest.java
cp of https://github.com/apache/iotdb/pull/11045
> [To rel/1.2] retry cache expiration time should be longer than retriable-client wait duration

- integration-test/src/test/java/org/apache/iotdb/db/it/IoTDBInsertWithQueryIT.java
- integration-test/src/test/java/org/apache/iotdb/session/it/IoTDBSessionSimpleIT.java
- iotdb-client/service-rpc/src/main/java/org/apache/iotdb/rpc/RpcUtils.java
- iotdb-client/service-rpc/src/test/java/org/apache/iotdb/rpc/RpcUtilsTest.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/partition/PartitionManager.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/thrift/impl/ClientRPCServiceImpl.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/load/AlignedChunkData.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/load/NonAlignedChunkData.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/load/TsFileSplitter.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/AnalyzeVisitor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/parser/ASTVisitor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/plan/node/load/LoadSingleTsFileNode.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/plan/node/write/InsertRowNode.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/plan/node/write/InsertRowsNode.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/plan/node/write/InsertRowsOfOneDeviceNode.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/plan/node/write/InsertTabletNode.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/statement/crud/InsertRowStatement.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/statement/crud/InsertRowsOfOneDeviceStatement.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/statement/crud/InsertTabletStatement.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/StorageEngine.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/utils/TimePartitionUtils.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/plan/plan/node/write/WritePlanNodeSplitTest.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/StorageEngineTest.java
The current support of negative timestamp is not perfect. There are two main issues.
* When query data by cli, the negative timestamp doesn't show correctly
* When insert timestamp -100, the current code will calculate the time partition id as 0. However the correct time partition id should be -1.
Execute the sql, check the query result is correct or not. Then check whether the time partition id is correct, which you can find in `data/datanode/data/sequence/root.sg/1`
```
insert into root.sg.d1(time,s1) values(-20,2)
select * from root.**
```
> [IOTDB-6138] Fix the support of negative timestamp

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/task/CrossSpaceCompactionTask.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/task/InnerSpaceCompactionTask.java
Fix compaction speed calculation.
The variable 'costTime' is 0, which makes the result of compaction speed is Infinity.
Change the data type of 'costTime' to double, and keep two decimal places in log.
> [To rel/1.2] Fix compaction speed calculation

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/exception/runtime/IntoProcessException.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/exception/runtime/ModelInferenceProcessException.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/exception/runtime/WriteLockFailedException.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/client/DataNodeInternalClient.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/process/AbstractIntoOperator.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/process/ml/ForecastOperator.java
Currently ModelInferenceException lies in a wrong path of storageengine/dataregion/exception
After this pr, it will be moved to org.apache.iotdb.db.exception.runtime.
> Fix incorrect package path for modelInferenceException

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/rescon/disk/FolderManager.java
When the system Disk availability is insufficient, the heartbeat mechanism sets the system status to `ReadOnly(DiskFull)`, and the DataNode itself sets the system status to `ReadOnly` or `ReadOnly(DiskFull)` when it allocates a new directory. These two states make the user feel confused as to why the different states occur. This fix is that the unified system state is `ReadOnly(DiskFull)` when disk availability is low.
1. Start a cluster of any size
2. Keep writing data until the disk availability is below the configured `disk_space_warning_threshold`
3. Start the CLI and run `show cluster` to check whether the node status is `ReadOnly(DiskFull)`. The expected result is `ReadOnly(DiskFull)`
**Description:** 
When the disk availability is insufficient and `DirectoryStrategy` is …
> fix datanode status is ReadOnly because the disk is full

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/wal/WALManager.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/wal/node/WALNode.java
Fix wal triggering disk threshold too many times loop, when the threshold is triggered, the original motivation is to keep trying to delete expired files. However, when a WalNode has no files to delete, and the Wal disk file size still exceeds the threshold, the task cannot exit the loop.
Wal disk thresholds are more properly managed by Wal Manager. So this change moves this logic into the Wal Manager.
1. edit `iotdb-common.properties`, add `iot_consensus_throttle_threshold_in_byte=1073741824`(1GB) param;
2. start a 1C1D or 3C3D cluster
3. enable heavy writes (such as 10 clients) through the Grafana plugin or directly view the `data/datanode/wal` directory, with the expectation that WAL files will be sorted when they exceed 'iot_consensus_throttle_threshold_in_byte * 0.8'. Until it is …
> [To rel/1.2] Fixed wal triggering disk threshold loop too many times

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/rescon/disk/FolderManager.java
When the system Disk availability is insufficient, the heartbeat mechanism sets the system status to `ReadOnly(DiskFull)`, and the DataNode itself sets the system status to `ReadOnly` or `ReadOnly(DiskFull)` when it allocates a new directory. These two states make the user feel confused as to why the different states occur. This fix is that the unified system state is `ReadOnly(DiskFull)` when disk availability is low.
1. Start a cluster of any size
2. Keep writing data until the disk availability is below the configured `disk_space_warning_threshold`
3. Start the CLI and run `show cluster` to check whether the node status is `ReadOnly(DiskFull)`. The expected result is `ReadOnly(DiskFull)`
**Description:** 
When the disk availability is insufficient and `DirectoryStrategy` is …
> [To rel/1.2] fix datanode status is ReadOnly because the disk is full

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/task/stage/PipeTaskProcessorStage.java
To reproduce:
- create 1000 devices and write some data
- create and start 1000 pipes, their patterns matching the devices
- drop all pipes
- delete all data on receiver side
- create and start the same pipes again
- execute queries on receiver side, and the data are NOT transferred.
> Pipe: include creation time in PipeProcessorSubtask#taskID to avoid task scheduling issues after 1000+ pipes' creating and dropping

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/task/CrossSpaceCompactionTask.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/task/InnerSpaceCompactionTask.java
Fix compaction speed calculation.
The variable 'costTime' is 0, which makes the result of compaction speed is Infinity.
Change the data type of 'costTime' to double, and keep two decimal places in log.
> Fix compaction speed calculation

- server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/task/CrossSpaceCompactionTask.java
- server/src/main/java/org/apache/iotdb/db/engine/compaction/execute/task/InnerSpaceCompactionTask.java
Fix compaction speed calculation.
The variable 'costTime' is 0, which makes the result of compaction speed is Infinity.
Change the data type of 'costTime' to double, and keep two decimal places in log.
> [To rel/1.1] Fix compaction speed calculation

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/event/EnrichedEvent.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/event/realtime/PipeRealtimeEvent.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/extractor/historical/PipeHistoricalDataRegionTsFileExtractor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/extractor/realtime/PipeRealtimeDataRegionExtractor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/extractor/realtime/PipeRealtimeDataRegionFakeExtractor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/extractor/realtime/PipeRealtimeDataRegionHybridExtractor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/extractor/realtime/PipeRealtimeDataRegionLogExtractor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/extractor/realtime/PipeRealtimeDataRegionTsFileExtractor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/task/connection/BlockingPendingQueue.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/task/connection/PipeEventCollector.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/task/subtask/connector/PipeConnectorSubtask.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/task/subtask/processor/PipeProcessorSubtask.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/pipe/extractor/CachedSchemaPatternMatcherTest.java
Currently, existing events can not be properly released when a pipe is dropped before all events are processed.
> Pipe: Clear reference count of on-the-fly EnrichedEvent in queues when pipe is dropped

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/event/EnrichedEvent.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/event/realtime/PipeRealtimeEvent.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/extractor/historical/PipeHistoricalDataRegionTsFileExtractor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/extractor/realtime/PipeRealtimeDataRegionExtractor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/extractor/realtime/PipeRealtimeDataRegionFakeExtractor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/extractor/realtime/PipeRealtimeDataRegionHybridExtractor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/extractor/realtime/PipeRealtimeDataRegionLogExtractor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/extractor/realtime/PipeRealtimeDataRegionTsFileExtractor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/task/connection/BlockingPendingQueue.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/task/connection/PipeEventCollector.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/task/subtask/connector/PipeConnectorSubtask.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/task/subtask/processor/PipeProcessorSubtask.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/pipe/extractor/CachedSchemaPatternMatcherTest.java
(cherry picked from commit c4ff2b13449deab7d20613e31c9ccfecf8128021)
> [To rel/1.2] Pipe: Clear reference count of on-the-fly EnrichedEvent in queues when pipe is dropped (#11077)

- iotdb-core/confignode/src/assembly/resources/conf/iotdb-confignode.properties
- iotdb-core/datanode/src/assembly/resources/conf/iotdb-datanode.properties
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/conf/CommonConfig.java
cherry-pick [pr](https://github.com/apache/iotdb/pull/11091)
> [To rel/1.2][IOTDB-6144] Adjust the default thrift timeout parameter to 60s 

- iotdb-core/confignode/src/assembly/resources/conf/iotdb-confignode.properties
- iotdb-core/datanode/src/assembly/resources/conf/iotdb-datanode.properties
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/conf/CommonConfig.java
see [jira](https://issues.apache.org/jira/browse/IOTDB-6144)
> [IOTDB-6144] Adjust the default thrift timeout parameter to 60s

- docs/UserGuide/Operate-Metadata/Auto-Create-MetaData.md
- docs/zh/UserGuide/Operate-Metadata/Auto-Create-MetaData.md
- integration-test/src/test/java/org/apache/iotdb/db/it/schema/IoTDBMetadataFetchIT.java
- integration-test/src/test/java/org/apache/iotdb/db/it/schema/IoTDBSchemaTemplateIT.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
- iotdb-core/node-commons/src/assembly/resources/conf/iotdb-common.properties
We found that in most user cases TS_2DIFF has better compression rate than RLE for INT32 and INT64 type, so we change the default encoder of INT32 and INT64 from RLE to TS_2DIFF
> [To rel/1.2] Change default encoder of INT32 and INT64 from RLE to TS_2DIFF

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/parser/ASTVisitor.java
Before:
```sql
IoTDB> select count(s1) from root.eg.exchange group by variation(2) limit 5
Msg: 301:
```
After:
```sql
IoTDB> select count(s1) from root.eg.exchange group by variation(2) limit 5
`Msg: 701: Constant operand [2] is not allowed in group by variation, there should be an expression`
```
> [IOTDB-6137] Improved error messages for expressions as constants in GROUP BY

- iotdb-core/consensus/pom.xml
include https://github.com/apache/ratis/pull/915
> [RatisConsensus] Bump ratis snapshot version to 2.5.2-284ecbb-SNAPSHOT

- integration-test/src/test/java/org/apache/iotdb/db/it/udf/IoTDBUDFWindowQueryIT.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/transformation/dag/intermediate/MultiInputColumnIntermediateLayer.java
Issue: https://issues.apache.org/jira/browse/IOTDB-6149
This pr fixed the incorrect initialization when calculating expressions with UDF which has multiple inputs.
How to reproduce:
1. Create a function with UDF that uses SlidingTimeWinodw AccessStrategy and takes multiple expressions as input.
2. Run a query using this function with multiple inputs like: select func(s1, s2) from root.sg
3. See if the ouput is correct.
Because UDFWindowIT#testSlidingTimeWindow did not check the cnt of expected rows, this bug could not be detected by the IT. I add the check in this PR now.
Also, In this pr, I removed some of the @Ignore annotions of UDFWindowIT since the exception handler of IT framework is finished as mentioned in the todo annotation.
> [IOTDB-6149] Fix incorrect output of UDF with multiple inputs

- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/pipe/task/PipeTaskCoordinator.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/pipe/task/PipeTaskCoordinatorLock.java
> Pipe: use PipeTaskCoordinatorLock instead of ReentrantLock for multi thread sync

- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/pipe/task/PipeTaskCoordinator.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/pipe/task/PipeTaskCoordinatorLock.java
(cherry picked from commit c23013463d2508eac0cf8ca0c069afd7a3fe213d)
> [To rel/1.2] Pipe: use PipeTaskCoordinatorLock instead of ReentrantLock for multi thread sync (#11129)

- iotdb-client/cli/src/main/java/org/apache/iotdb/tool/ExportTsFile.java
Fixed that the SessionDataSet was not closed after querying the IoTDB using the TsFile export tool. It should be closed after the query is completed when the Session query is normally used.
**Before this:**
Do not close the SessionDataSet after querying using Seesion.
**After this:**
Close the SessionDataSet after querying with Seesion.
> fix session sessionDataSet unclose when use export tsfile tool

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/memory/MemoryPool.java
If the MemoryReservationFuture has been cancelled or done when freeing memory, we should remove it from the queue, or it may lead to memory leak as showed in the following pic: The queries have finished, but the memory_reservation_size did not decrease.
> Remove cancelled/done MemoryReservationFuture from the queue when freeing memory

- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/iot/IoTConsensusServerImpl.java
- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/iot/IoTConsensusServerMetrics.java
- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/iot/client/DispatchLogHandler.java
- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/iot/logdispatcher/LogDispatcher.java
- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/iot/logdispatcher/LogDispatcherThreadMetrics.java
- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/iot/service/IoTConsensusRPCServiceProcessor.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/service/metric/enums/Metric.java
When the IoT follower receives a syncLogEntries request, it will go through three stages: deserialize, sort and apply. This pr adds this three timers.
> [IOTDB-6152] Add IoTConsensus Sync Log Timer

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/conf/IoTDBStartCheck.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/client/ConfigNodeInfo.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/service/DataNode.java
1. For the initial startup, the system.properties file is generated under data/system instead of data/system/schema.
2. During startup, check if there is a system.properties file under data/system/schema. If it exists, move it to data/system.
> [IOTDB-6151] Move datanode system.properties

- iotdb-client/service-rpc/src/main/java/org/apache/iotdb/rpc/RpcTransportFactory.java
cherry-pick [pull](https://github.com/apache/iotdb/pull/11145)
> [To rel/1.2][IOTDB-6156] Fixed TConfiguration invalidly in Thrift AsyncServer For IoTConsensus

- iotdb-client/service-rpc/src/main/java/org/apache/iotdb/rpc/RpcTransportFactory.java
see [jira](https://issues.apache.org/jira/browse/IOTDB-6156)
> [IOTDB-6156] Fixed TConfiguration invalidly in Thrift AsyncServer For IoTConsensus

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/DataRegion.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/tsfile/TsFileManager.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/compaction/inner/sizetiered/SizeTieredCompactionRecoverTest.java
Delete unused compaction recover code.
When a sealed tsfile's level is greater than zero, it will enter an outdated code block, which cause the file not be added into  tsFileManager.  As a result, any operation performed on this tsfile in system is not effecetive.
> Delete unused compaction recover code

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/DataRegion.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/tsfile/TsFileManager.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/compaction/inner/sizetiered/SizeTieredCompactionRecoverTest.java
Delete unused compaction recover code.
When a sealed tsfile's level is greater than zero, it will enter an outdated code block, which cause the file not be added into tsFileManager. As a result, any operation performed on this tsfile in system is not effecetive.
https://github.com/apache/iotdb/pull/11147
> [To rel/1.2] Delete unused recover code

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/rest/v1/handler/StatementConstructionHandler.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/rest/v2/handler/StatementConstructionHandler.java
After this pr, we  will get error msg while using illegal path
And we must use \`\` to include the path to be successful.
> [IOTDB-6164] Fix create illegal path through rest api bug

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/service/DataNode.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/StorageEngine.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/DataRegion.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/wal/recover/WALRecoverManager.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/compaction/cross/RewriteCrossSpaceCompactionWithFastPerformerTest.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/compaction/cross/RewriteCrossSpaceCompactionWithReadPointPerformerTest.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/compaction/recover/SizeTieredCompactionRecoverTest.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/wal/recover/WALRecoverManagerTest.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/utils/EnvironmentUtils.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/concurrent/ExceptionalCountDownLatch.java
When recover data region but meet disk error, the main thread of data node will stack at the following position.
The errored data region didn't countdown the latch in WALRecoverManager. Therefore the main thread will aways wait for the WALRecoverManager to finish recover.
After the fixing, the data node progress will exit when meets disk error.
1. Generate some data files by execute insert statement and flush.
```sql
insert into root.sg.d1(time,s1) values(1,2);
flush;
```
2. Stop data node, go to data dir `data/datanode/data/sequence/root.sg/1/0`
3. Create an empty temp file and set the temp file unchangeable to simulate the disk broken. DataNode will throw an IOException because of it.
```
touch 1695017988949-1-0-0.tsfile.resource.temp
chflags uchg …
```
> Fix datanode stuck when meets disk error 

- iotdb-client/client-py/iotdb/Session.py
- iotdb-client/client-py/iotdb/utils/IoTDBConstants.py
This PR is optimizing the insert records values serialization of Python Client. The Enum.value method in Python is not fast enough, we should try to avoid using it too much...
You can run the following code.
```Python
from datetime import datetime
import numpy as np
from iotdb.Session import Session
from iotdb.utils.IoTDBConstants import TSDataType, TSEncoding, Compressor
from iotdb.utils.NumpyTablet import NumpyTablet
ip = "127.0.0.1"
port_ = "6667"
username_ = "root"
password_ = "root"
session = Session(ip, port_, username_, password_, fetch_size=1024, zone_id="UTC+8", enable_redirection=False)
session.open(False)
device = "root.sg.d"
measurements_ = []
ts_path_lst_ = []
values_ = []
for i in range(440):
measurement = "s" + str(i)
measurements_.append(measurement) …
```
> Optimize python client insert records values serialization

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/event/common/tsfile/TsFileInsertionDataContainer.java
device metadata is deserialized from the file twice in the constructor of TsFileDataContainer, causing an IO overhead.
before:
after:
> [IOTDB-6165] Pipe: cache device metadata in TsFile reader to avoid redundant IO

- integration-test/src/test/java/org/apache/iotdb/pipe/it/IoTDBPipeDataSyncIT.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/utils/CommonUtils.java
Fix https://github.com/apache/iotdb/issues/11199, allow casting from null when deserializing InsertRowNode.
---
For this insert statement:
```sql
insert into root.sg.d1(time, s0, s1) values (3, null, 25.34);
```
The source-side pipe stream processing engine will convert it into the following RPC sent to the target-side:
```
TPipeTransferReq(version:1, type:6, body:[0, 0, 0, 0, 0, 0, 0, 1, 0, 14, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 10, 114, 111, 111, 116, 46, 115, 103, 46, 100, 49, 0, 0, 0, 2, 1, 0, 0, 0, 2, 115, 48, 3, 8, 7, 0, 0, 0, 0, 0, 0, 0, 2, 115, 49, 3, 8, 7, 0, 0, 0, 0, -2, 3, 65, -54, -72, 82, 0, 1, 0, 0, 0, 1, 49, 0, 0, 0, 0, 0, 0, 0, 0])
```
The focus here is on the deserialization logic of its `body`.
The deserialization logic is in …
> [ISSUE-11199] Pipe: fix NPE when casting from null values in InsertRowNode deserialization

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/statement/crud/PipeEnrichedInsertBaseStatement.java
Consider the following data synchronization scenario (metadata mismatch) using Pipe engine.
1. starting two instances of IoTDB
- A datanode -> 127.0.0.1:6667
- B datanode -> 127.0.0.1:6668
**NOTE**: IoTDB B should be configured with the following `iotdb-common.properties`:
```properties
enable_partial_insert=false
enable_auto_create_schema=false
```
2. connecting IoTDB B (6668) by cli and send
```sql
create TIMESERIES root.sg.d1.s0 with datatype=float;
create TIMESERIES root.sg.d1.s1 with datatype=float;
```
3. connecting IoTDB A (6667) by cli and send
```sql
create pipe test
with connector (
'connector'='iotdb-thrift-connector',
'connector.ip'='127.0.0.1',
'connector.port'='6668'
);
start pipe test;
create TIMESERIES root.sg.d1.s0 with datatype=text;
create TIMESERIES root.sg.d1.s1 with …
```
> Pipe: fix NPE in PipeEnrichedInsertBaseStatement#isQuery when analyzing statement

- iotdb-api/pipe-api/src/main/java/org/apache/iotdb/pipe/api/PipeConnector.java
- iotdb-api/pipe-api/src/main/java/org/apache/iotdb/pipe/api/PipeProcessor.java
- iotdb-api/pipe-api/src/main/java/org/apache/iotdb/pipe/api/event/dml/insertion/TsFileInsertionEvent.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/protocol/airgap/IoTDBAirGapConnector.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/protocol/thrift/async/IoTDBThriftAsyncConnector.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/protocol/websocket/WebSocketConnector.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/event/common/tsfile/PipeTsFileInsertionEvent.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/event/common/tsfile/TsFileInsertionDataContainer.java
> Pipe: fix file handle leak when processing with extractor.pattern

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/audit/AuditLogger.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/service/metrics/IoTDBInternalLocalReporter.java
Fix reason: 
1. If we manipulate series of audit as a common user, it will be rejected because of no permission;
2. We need to get the name of super user from Config.
Fix verify:
> Manipulate series of Audit and IoTDB reporter as super user

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/exchange/SharedTsBlockQueue.java
The blocked future of LocalSinkChannel is done when its downstream LocalSourceHandle asks it for data. In query with limit clause, it is possible that a Driver is blocked because its ISink is blocked. When the query finishes, we should ensure that the blocked Drivers can be waken and then be finished correctly.
> [IoTDB-6172] Finish canAddTsBlock of SharedTsBlockQueue to ensure that blocked Driver could be correctly finished

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/event/common/tsfile/PipeTsFileInsertionEvent.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/extractor/historical/PipeHistoricalDataRegionTsFileExtractor.java
> [IOTDB-6170] Pipe: Removed unnecessary parse when tsFile resources' time ranges are covered by startTime-endTime

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/Analysis.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/AnalyzeVisitor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/LogicalPlanBuilder.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/LogicalPlanVisitor.java
1. always using "Ordering.DESC" resultTimeOrder when executing last query for non-base view.
2. remove redundant variable `lastQueryNonWriteViewExpressions`, just using `lastQueryNonWritableViewSourceExpressionMap` is enough.
> Fix the data scan ordering when executing last query

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/event/common/tsfile/TsFileInsertionDataContainer.java
(cherry picked from commit 6cbe5f0d57737ee4598c1e974892e093b6657ecb)
> [To rel/1.2][IOTDB-6165] Pipe: cache device metadata in TsFile reader to avoid redundant IO (#11186)

- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/consensus/statemachine/ConfigRegionStateMachine.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/ConfigManager.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/PermissionManager.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/persistence/AuthorInfo.java
- iotdb-core/confignode/src/test/java/org/apache/iotdb/confignode/persistence/AuthorInfoTest.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/auth/role/LocalFileRoleAccessorTest.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/auth/role/LocalFileRoleManagerTest.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/auth/user/LocalFileUserAccessorTest.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/auth/user/LocalFileUserManagerTest.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/auth/authorizer/BasicAuthorizer.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/auth/authorizer/IAuthorizer.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/auth/authorizer/OpenIdAuthorizer.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/auth/entity/PriPrivilegeType.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/auth/entity/Role.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/auth/role/BasicRoleManager.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/auth/role/IRoleManager.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/auth/role/LocalFileRoleAccessor.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/auth/user/BasicUserManager.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/auth/user/IUserManager.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/auth/user/LocalFileUserAccessor.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/utils/AuthUtils.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/utils/IOUtils.java
- iotdb-core/node-commons/src/test/java/org/apache/iotdb/commons/utils/AuthUtilsTest.java
In this pr:
1. iotdb can upgrade online from pre version.
a. accept pre version raftlog and act as pre version.
b. load pre version profile and translate privilege into current version type.
c. add a lots of UT to check pre-raftlog and pre-file can be process
> Auth online upgrade

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/task/AbstractCompactionTask.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/task/CompactionTaskType.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/task/CrossSpaceCompactionTask.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/task/InnerSpaceCompactionTask.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/utils/CompactionUtils.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/schedule/CompactionScheduler.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/schedule/comparator/DefaultCompactionTaskComparatorImpl.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/selector/ICompactionSelector.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/selector/IInnerSeqSpaceSelector.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/selector/impl/SizeTieredCompactionSelector.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/compaction/CompactionTaskComparatorTest.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/compaction/cross/CrossSpaceCompactionWithFastPerformerValidationTest.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/compaction/cross/CrossSpaceCompactionWithReadPointPerformerValidationTest.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/compaction/inner/InnerSpaceCompactionSelectorTest.java
This PR mainly has the following upgrades:
1. Added the selection criteria for merging tasks in the space. When the availability of disk space is insufficient, TsFile containing mods file is preferentially selected.
2. Compaction adds the CompactionTaskType attribute to a task and compacts the task to `NORMAL` and `MOD_SETTLE`. `NORMAL` is the default value. When the disk size of the mod file exceeds 50M or the disk space availability is insufficient, the mods file sorting task is preferred. In this case, the task type is `MOD_SETTLE`. When a task is executed, the system determines the disk space availability. If the task type is `NORMAL` and the disk space availability is insufficient, the task is discarded from the priority queue to avoid unexpected errors.
3. Optimized the return value …
> Optimize merge selection process and increase disk space availability logic

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/event/EnrichedEvent.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/task/connection/PipeEventCollector.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/task/subtask/PipeSubtask.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/task/subtask/connector/PipeConnectorSubtask.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/task/subtask/processor/PipeProcessorSubtask.java
If we drop a pipe when it is transferring a large TsFile, the "drop pipe" statement will stuck for a while, until the TsFile is fully transferred or the query times out. This PR will make connector subtask close faster by early returning.
> Pipe: fix drop pipe stuck (make connector subtask close faster by early returning)

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/SelectIntoUtils.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/parser/ASTVisitor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/statement/component/IntoComponent.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/plan/analyze/AnalyzeFailTest.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/plan/analyze/AnalyzeTest.java
correct the wrong fix logic in https://github.com/apache/iotdb/pull/10060
logic now: When generate statement, don't remove back_quotes any more; 
after placeholders applied, we will remove back_quotes if necessary or check if the node name is legal.
> [IOTDB-6160] Correct the target paths verify logic in Select Into

- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/ProcedureManager.java
Before https://github.com/apache/iotdb/pull/11222, there might be an error like the following when creating or dropping a pipe:
```text
2023-09-25 23:27:42,705 [pool-32-IoTDB-MPP-Coordinator-Executor-19] WARN  o.a.i.d.q.p.e.c.ConfigExecution:126 - Failures happened during running ConfigExecution. 
org.apache.iotdb.commons.exception.IoTDBException: null
```
The reason for the error message being **null** is that the DataNode (DN) did not correctly set the status message after the procedure timeout. This PR fixes this issue.
**TBD:** I find the status code `TSStatusCode.OVERLAP_WITH_EXISTING_TASK` here to be somewhat unreasonable, although it doesn't affect the logic of the **PIPE** caller because of:
```java
return new TSStatus(TSStatusCode.PIPE_ERROR.getStatusCode()).setMessage(statusList. …
```
> Pipe: add status message for procedure execution timed out

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/LoadTsfileAnalyzer.java
When the loaded TsFile is empty, continue to load the next
> Load: skipping instead of throwing exceptions when loading empty tsfiles

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/LoadTsfileAnalyzer.java
When the loaded TsFile is empty, continue to load the next
> [To rel/1.2] Load: skipping instead of throwing exceptions when loading empty tsfiles

- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/iot/client/IoTConsensusClientPool.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/client/property/ThriftClientProperty.java
see [jira6183](https://issues.apache.org/jira/browse/IOTDB-6183)
> [IOTDB-6183] Optimize the timeout retry logic of IoTConsensus sending RPCS

- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/iot/client/IoTConsensusClientPool.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/client/property/ThriftClientProperty.java
cherry-pick [pull](https://github.com/apache/iotdb/pull/11266)
> [To rel/1.2][IOTDB-6183] Optimize the timeout retry logic of IoTConsensus sending RPCS

- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/ConfigManager.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/node/NodeManager.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/node/AddConfigNodeProcedure.java
Some Node's status might be `null` if the ConfigNode can't send heartbeat request to them. Therefore, the ConfigNode will initiate all Node's status to `Unknown` and make sure all Node's status are either exist or set to `Unknown` by default.
> [IOTDB-6185] Fix show cluster null status bug

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/process/MergeSortOperator.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/execution/operator/MergeSortOperatorTest.java
The code  in MergeSortOperator breaks too late, the smaller value behind the run-out tsBlock won't be filled in time, resulting in a wrong order.
> [IOTDB-6184] MergeSort should break when one tsBlock is run out in one iteration.

- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/ConfigManager.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/node/NodeManager.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/node/AddConfigNodeProcedure.java
Some Node's status might be `null` if the ConfigNode can't send heartbeat request to them. Therefore, the ConfigNode will initiate all Node's status to `Unknown` and make sure all Node's status are either exist or set to `Unknown` by default.
> [To rel/1.2][IOTDB-6185] Fix show cluster null status bug

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/event/common/heartbeat/PipeHeartbeatEvent.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/extractor/realtime/PipeRealtimeDataRegionHybridExtractor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/resource/wal/PipeWALResourceManager.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/task/connection/BlockingPendingQueue.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/task/connection/PipeEventCollector.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/task/subtask/processor/PipeProcessorSubtask.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/conf/CommonConfig.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/conf/CommonDescriptor.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/config/PipeConfig.java
Currently, hybrid extractor won't know the size of this buffer queue, so it can't migrate to file mode when too much event is in the buffer queue. This PR makes PipeHeartbeatEvent able to report buffer queue size to hybrid extractor.
> Pipe: make hybrid extractor aware of event collector's queue size & block processor subtask's execution when events buffered in EventCollector

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/process/AbstractConsumeAllOperator.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/process/MergeSortOperator.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/process/join/RowBasedTimeJoinOperator.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/execution/DataDriverTest.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/execution/operator/AlignedSeriesScanOperatorTest.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/execution/operator/HorizontallyConcatOperatorTest.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/execution/operator/LimitOperatorTest.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/execution/operator/MergeSortOperatorTest.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/execution/operator/OffsetOperatorTest.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/execution/operator/SingleDeviceViewOperatorTest.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/execution/operator/SortOperatorTest.java
Related issue: https://jira.infra.timecho.com:8443/browse/TIMECHODB-342
Related doc: https://apache-iotdb.feishu.cn/docx/DQhWdXTeooCouHxeMCTcG3J7n4T
In a nutshell, some of the Operators fail to limit execution time in one Next() and these Operators may occupy the Query-Worker Thread for too long.
This PR aims to add stopwatch for AbstractConsumeAllOperator and its subclasses so that their execution time can be bounded.
The test result is listed in the above related doc.
> Add stopwatch for AbstractConsumeAllOperator

- iotdb-connector/hadoop/src/main/java/org/apache/iotdb/hadoop/fileSystem/HDFSOutput.java
- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/iot/IoTConsensusServerImpl.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/conf/IoTDBStartCheck.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/task/CrossSpaceCompactionTask.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/task/InnerSpaceCompactionTask.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/utils/log/CompactionLogger.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/memtable/TsFileProcessor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/modification/io/LocalTextModificationAccessor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/modification/io/ModificationWriter.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/snapshot/SnapshotLogger.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/tsfile/TsFileResource.java
- iotdb-core/tsfile/src/main/java/org/apache/iotdb/tsfile/write/writer/LocalTsFileOutput.java
- iotdb-core/tsfile/src/main/java/org/apache/iotdb/tsfile/write/writer/TsFileIOWriter.java
- iotdb-core/tsfile/src/main/java/org/apache/iotdb/tsfile/write/writer/TsFileOutput.java
- iotdb-core/tsfile/src/test/java/org/apache/iotdb/tsfile/write/writer/TestTsFileOutput.java
The following operations have added fsync operations:
1. flush the endFile() operation to ensure that data in `tsfile` and `.resource` files is flushed to disks
2. The `configuration.dat` file is persisted and updated when the consensus group is started
3. Update`DataNodeId` and `ClusterName` for System.properties
4. Update the `snapshot.log` file
> Added fsync operation when persisting files

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/flush/CompressionRatio.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/memtable/AlignedWritableMemChunk.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/memtable/TsFileProcessor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/memtable/WritableMemChunk.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/flush/CompressionRatioTest.java
This PR has three optimizations:
1. The naming format of the compression Ratio file is changed from `Ratio-compressRatio-flushCount`to `ratio-totalMemoryDataSize-totalDiskDataSize`
2. The rule for calculating the compression ratio from the `sum(memTableSize/flushSize) / count(flushTimes)` to ` totalMemoryDataSize / totalDiskDataSize `
3. Add the `memTableSize` deduplication logic. If no deduplication is performed, the compression ratio calculated is very large, resulting in inaccurate estimation of the combined memory. Therefore, in flush encode, if data is duplicated, the size of the duplicate is removed from `memTableSize`.
> upgrade compression ratio file name format and solve the problem of high compression ratio caused by repeated data writing

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/schedule/CompactionWorker.java
if disk free ratio is less than disk_space_warning_threshold, compation task shouldn't execute
> add disk free ration check before compaction task start

- integration-test/src/test/java/org/apache/iotdb/db/it/auth/IoTDBAuthIT.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/auth/ClusterAuthorityFetcher.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/statement/sys/AuthorStatement.java
In this pr:
1. fix check role .
2. fix cache refresh token.
> [auth].fix error when check role.

- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/config/RatisConfig.java
see [jira](https://issues.apache.org/jira/browse/IOTDB-6190)
> [IOTDB-6190] Increase the threshold for Ratis to shut itself down if it detects that a process is stuck

- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/persistence/ModelInfo.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/persistence/cq/CQInfo.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/mtree/impl/mem/snapshot/MemMTreeSnapshotUtil.java
more details can be seen in https://issues.apache.org/jira/browse/IOTDB-6178.
the solutions can be found in https://apache-iotdb.feishu.cn/docx/L6XNd0HBbo57xFx1DQ0cjkNenhg
In this pr, I add fsync for schemaregion, CQInfo, ModelInfo.
> [IOTDB-6178] Add fsync for schemaregion, CQInfo, ModelInfo

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/wal/recover/file/TsFilePlanRedoer.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/wal/recover/file/UnsealedTsFileRecoverPerformer.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/wal/recover/file/TsFilePlanRedoerTest.java
- iotdb-core/tsfile/src/main/java/org/apache/iotdb/tsfile/file/header/ChunkGroupHeader.java
- iotdb-core/tsfile/src/test/java/org/apache/iotdb/tsfile/read/TsFileSequenceReaderTest.java
- iotdb-core/tsfile/src/test/java/org/apache/iotdb/tsfile/write/writer/RestorableTsFileIOWriterTest.java
After OS system shutdown and restart IoTDB service, there is a broken TsFile cannot be compacted.
It caused by this 0-level TsFile contains two chunk groups with same device id. And there are several issues to fix. 
1. Before restart IoTDB, this TsFile ended with a lot of zero bytes. However the current selfcheck logic will treated these zero bytes as correct chunk group, which cause the truncate position is not correct.
2. In TsFilePlanRedoer, there is a wrong logic of filter the InsertPlan from wal. Some InsertPlans which should be filtered are inserted into the recovering memtable. Therefore, the TsFile will contains two chunk groups with same device id.
3. in UnsealedTsFileRecoverPerformer, there is an outdated redundant logic should be removed. 
1. Add `System.exit(-1);` at the end …
> Fix bad tsfile being recoverd from wal

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/driver/Driver.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/driver/IDriver.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/fragment/FragmentInstanceManager.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/schedule/DriverScheduler.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/schedule/queue/multilevelqueue/MultilevelPriorityQueue.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/schedule/task/DriverTask.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/execution/QueryExecution.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/plan/FragmentInstance.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/statement/StatementType.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/statement/sys/ShowQueriesStatement.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/execution/schedule/DefaultDriverSchedulerTest.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/execution/schedule/DriverTaskTimeoutSentinelThreadTest.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/execution/schedule/queue/MultilevelPriorityQueueTest.java
In this PR, we introduce a new highestPriorityQueue in the MultilevelPriorityQueue, so that the ShowQuries related DriverTasks could always be executed first.
> Set ShowQuries related DriverTasks to the highest priority

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
After customizing the `dn_system_dir` option in `iotdb-datanode.properties`:
```properties
dn_system_dir=data/datanode/system-test
```
the directory path used by the pipe receiver was not taking effect:
This PR fixes this issue.
<hr>
This PR has:
<hr>
> Pipe: fix missing `pipeReceiverFileDir` update after updating `systemDir`

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/AbstractOperator.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/AlignedSeriesScanOperator.java
- iotdb-core/tsfile/src/main/java/org/apache/iotdb/tsfile/read/common/block/TsBlockBuilder.java
- iotdb-core/tsfile/src/main/java/org/apache/iotdb/tsfile/read/common/block/column/Int32ArrayColumnEncoder.java
- iotdb-core/tsfile/src/main/java/org/apache/iotdb/tsfile/read/common/block/column/TsBlockSerde.java
- iotdb-core/tsfile/src/main/java/org/apache/iotdb/tsfile/read/reader/page/AlignedPageReader.java
- iotdb-core/tsfile/src/main/java/org/apache/iotdb/tsfile/read/reader/page/ValuePageReader.java
- iotdb-core/tsfile/src/main/java/org/apache/iotdb/tsfile/read/reader/series/PaginationController.java
We do a cpu profiling for a large time range raw query case(each sql involves about 8,640,000 points and there are 30 concurrent client to do that kind of query at the same time. And found three potential performance improvement point:
1. We can init the TsBlockBuilder with the count in PageStatistics which can avoid the Array.growCapacity();
2. In AlignedPageReader, if any sensors we queried has the same count with time columnn and we don't do the delete operation, there won't exist all null row, so we can save that overhead.
3. while serializing TsBlock, we can also estimate the initial capacity using `TsBlock.getRetainedSize()`.
4. AlignedSeriesScanOperator can directly pass the TsBlock getting from AlignedSeriesScanUtil instead of rebuilding a new TsBlock while the TsBlock is large …
> [To rel/1.2] [IOTDB-6141] Optimize the large time range raw query performance

- iotdb-core/datanode/pom.xml
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java
As title, avoid initializing `pipeReceiverFileDirs` as null.
Also changes `ratis-thirdparty-misc` dependency scope from **test** to **runtime**, prevents errors during DN startup (by IDEA):
```
2023-10-18 19:20:35,234 [main] ERROR o.a.i.c.ConsensusFactory:58 - Couldn't Construct IConsensus class: org.apache.iotdb.consensus.ratis.RatisConsensus 
java.lang.reflect.InvocationTargetException: null
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:4 …
```
> Pipe: fix potential NPE risk when reflecting `pipeReceiverFileDirs`

- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/partition/QueryExecutor.java
cause: QueryExecutor doesn't support the `getRegionReplicaSet` method.
fix: implement the method
> [IOTDB-6171] Implement getRegionReplicaSet method of QueryExecutor

- integration-test/src/test/java/org/apache/iotdb/cli/it/StartClientScriptIT.java
- integration-test/src/test/java/org/apache/iotdb/tools/ExportCsvTestIT.java
- integration-test/src/test/java/org/apache/iotdb/tools/ExportTsFileTestIT.java
- iotdb-client/cli/src/test/java/org/apache/iotdb/tool/integration/ExportCsvTestIT.java
- iotdb-client/cli/src/test/java/org/apache/iotdb/tool/integration/ImportCsvTestIT.java
Some CI environment is ubuntu, but `sh` in ubuntu is indeed `dash` which is incompatible from `bash`.
So change `sh` to `bash` in integration-test.
> Use bash instead of sh in integration test.

- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/conf/CommonDescriptor.java
Performance: If the CN and DN use different common config files, and the `time_precision` config are not same between two files, DN will set the wrong partitionInterval.
> Fix partition interval may be not set correctly

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/schedule/DriverScheduler.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/schedule/DriverTaskTimeoutSentinelThread.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/schedule/ITaskScheduler.java
Before this PR, if the ddl of a DriverTask selected by the SentinelThread is very long(e.g. Integer.MAX_VALUE), the SentinelThread will sleep forever and the timeout mechanism for the query will become ineffective.
In this PR, I add a SLEEP_BOUND for the SentinelThread to ensure that it won't sleep for too long. SLEEP_BOUND is just an empirical value rather than a calculated one.
We re-push the task into the timeout queue within the lock, so the status of the task will not be changed until we finish the re-push. If the task is finished after we re-push it into the timeout queue, the task will be removed from the timeout queue either in the process of finishing/aborting a DriverTask, or when it is selected by the SentinelThread again.
> Add SLEEP_BOUND for the DriverTaskTimeoutSentinelThread

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/tsfile/TsFileResource.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/tsfile/TsFileResourceBlockType.java
Currently, TsFileResource serializes the PROGRESS INDEX information to TsFileResource files. When serializes the PROGRESS INDEX information, firstly write a byte 1 or 0 to represent whether contains the progress index, then write the content.
Now, we can extend the usage of the PROGRESS INDEX to store more information. We can introduce the  TsFileResourceBlockType to represent the block type of TsFileResource File and use more types bytes 2,3... to record the extended file block.
https://apache-iotdb.feishu.cn/docx/VIpmddFQFoa3yKxX9MhcvZ6cnXg
> Add Interface to extend TsFileResource

- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/consensus/request/ConfigPhysicalPlan.java
```bash
#!/bin/bash
iotdb_source_path="/Users/oushu/dev/iotdb"
iotdb_install_path="/tmp/iotdb"
iotdb_branch="rel/1.2"
iotdb_current_branch="sl_fix_upgrade_1.2"
echo "iotdb source path : $iotdb_source_path"
echo "iotdb install path : $iotdb_install_path"
echo "iotdb source branch : $iotdb_branch"
echo "----- check source path git status"
cd  "$iotdb_source_path"
output=$(git status  --porcelain)
if [ -n "$output" ]; then
echo "error, you have unsaved git files."
exit 1
fi
echo " git status ok"
echo "----- complie pre version iotdb"
git checkout "$iotdb_branch"
mvn clean package -pl distribution  -am -DskipTests  -T 20 > complie_pre.txt
echo "----- install into $iotdb_install_path"
cp -rf distribution/target/apache-iotdb-1.2.0-SNAPSHOT-all-bin/apache-iotdb-1.2.0-SNAPSHOT-all-bin …
```
> auth.add entry for pre version plan.

- iotdb-core/datanode/pom.xml
- iotdb-core/metrics/interface/src/main/java/org/apache/iotdb/metrics/AbstractMetricService.java
Fix the failure of metric module. Because we use SPI in metric module, so we shouldn't set metric related dependency's scope as test which may lead to failure
> Fix the failure of metric module

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/event/common/tsfile/PipeTsFileInsertionEvent.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/event/realtime/PipeRealtimeEventFactory.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/extractor/historical/PipeHistoricalDataRegionTsFileExtractor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/extractor/realtime/PipeRealtimeDataRegionLogExtractor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/extractor/realtime/listener/PipeInsertionDataNodeListener.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/DataRegion.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/memtable/TsFileProcessor.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/pipe/extractor/PipeRealtimeExtractTest.java
> [IOTDB-6202] Pipe: listen to tsfile load when realtime mode = forced-log

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/config/constant/PipeConnectorConstant.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/protocol/opcua/OpcUaConnector.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/protocol/opcua/OpcUaServerBuilder.java
The previous opc-ua-connector key directory setting "java.io.tmpdir" is not capable of keeping certificates in a long run, thus the key directory is now configurable and resides in "%IOTDB-CONF%/opc-security" directory by default.
"IOTDB-CONF" is because the directory may ususally be manually accessed by users.
The outcome:
<hr>
This PR has:
<hr>
> [IOTDB-6204] Pipe: Changed the default settings and add manual configuration logic for opc-ua-connector key directory 

- iotdb-core/confignode/src/assembly/resources/conf/confignode-env.bat
- iotdb-core/confignode/src/assembly/resources/conf/confignode-env.sh
- iotdb-core/datanode/src/assembly/resources/conf/datanode-env.bat
- iotdb-core/datanode/src/assembly/resources/conf/datanode-env.sh
1. add MEMORY_SIZE
2. MAX_HEAP_SIZE and HEAP_NEWSIZE -> ON_HEAP_MEMORY
3. DIRECT_MEMORY_SIZE -> OFF_HEAP_MEMORY
4. add calc MEMORY_SIZE
- ConfigNode  MEMORY_SIZE default is 3 / 10 on system memory, max size is 16G
- DataNode  MEMORY_SIZE default is 1 / 2 on system memory
5. change heap memory size rule
- set on heap memory size
- when memory_size_in_mb is less than 4 * 1024, we will set on heap memory size to memory_size_in_mb / 4 * 3
- when memory_size_in_mb is greater than 4 * 1024 and less than 16 * 1024, we will set on heap memory size to memory_size_in_mb / 5 * 4
- when memory_size_in_mb is greater than 16 * 1024 and less than 128 * 1024, we will set on heap memory size to memory_size_in_mb / 8 * 7
- when memory_size_in_mb is greater than 128 * 1024, we will set on heap memory size …
> feat(env):add MEMORY_SIZE parameters into env.sh/env.bat

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/load/TsFileSplitter.java
When loading TsFile with Chunk in data zone but no matched ChunkMetadata at the end of file, this Chunk needs to be skipped.
https://apache-iotdb.feishu.cn/docx/XMOHdnEwXoDp3Zx8w8ScBlcBnhe
> Skip loading Chunk without matched ChunkMetadata

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/wal/node/WALNode.java
IoTConsensus WAL always resets the insertNodes when WAL skip to a new targetIndex. But in most writting process, targetIndex is sequentially increasing, which means we may use the previous insertNodes as a cache and doesn't need to reset it everytime.
> [IOTDB-6187] IoTConsense WAL Interval Reading Strategy Optimization

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/fragment/QueryContext.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/utils/ResourceByPathUtils.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/read/reader/chunk/metadata/DiskAlignedChunkMetadataLoader.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/read/reader/chunk/metadata/DiskChunkMetadataLoader.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/utils/FileLoaderUtils.java
More details can be seen in https://jira.infra.timecho.com:8443/browse/TIMECHODB-349.
In this pr:
1. For loading from disk case, we delete `filePathModCache` in `QueryContext`,  save List<Modification> in `IChunkMetadataLoader`.
2. for loading from memory, we generating `TimeSeriesMetadata` from each `ChunkMetadata`, so we can directly use isModified function of `ChunkMetadata` to set modified of `TimeSeriesMetadata`.
In this way, we can safely delete `filePathModCache` without sacrificing query performance.
> Avoid modification causing OOM while there is much deletion entry in mods file

- example/session/src/main/java/org/apache/iotdb/SessionExample.java
- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/iot/client/AsyncIoTConsensusServiceClient.java
- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/iot/client/DispatchLogHandler.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/exception/metadata/SeriesOverflowException.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/plan/FragmentInstance.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/scheduler/AsyncPlanNodeSender.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/scheduler/AsyncSendPlanNodeHandler.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/scheduler/FragmentInstanceDispatcherImpl.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/client/ThriftClient.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/client/async/AsyncConfigNodeIServiceClient.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/client/async/AsyncDataNodeInternalServiceClient.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/client/async/AsyncDataNodeMPPDataExchangeServiceClient.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/client/async/AsyncPipeDataTransferServiceClient.java
For 3C3D 2 replicas or 3 replicas dataregion, if we kill one datanode, client should keep inserting data successfully without any error.
However, currently, there is no retry logic in dispatch for write, so if the leader of one DataRegionGroup is down, the dispatch phase will fail and will return a 302 status code to Session, and meet this kind of StatusCode, Session won't retry this write request, it will throw this exception to the upper layer. You will get the error msg like the following:
more details about this improvement can be found in this feishu doc(https://timechor.feishu.cn/docx/WuVJdNpGOowEGIxvaOlcwt9mngg)
In this pr, we add retry logic in `AsyncPlanNodeSender` which will try other replica to do the write dispatch.
I also simplify the error msg while connection is down, only …
> Improve the high availability of IoTDB

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/DataRegion.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/memtable/AbstractMemTable.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/tsfile/TsFileResource.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/DataRegionTest.java
When data is written using the insertTablet() interface and both values are null, exactly the data written is flushed. An empty TsFile file will be generated, the space cannot be deleted, and the generated resource file will be incorrect, and the endTime of the device will be Long.MIN_VALUE. This in turn affects query and merge mechanisms.
Based on this, this PR has the following two optimizations:
1. In the flush process, it is added that if the resource file is empty, the generated TsFile and.resource file are deleted
2. Enhance the judgment logic when there is no valid data in MemTable. If there is no valid data, delete the related empty Device data from the resource.
Execute the following code.
```java
public static void main(String[] args)
throws IoTDBConnectionException, …
```
> Fix TsFileResource endTime error when insert empty tablet and flush

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/service/IoTDBShutdownHook.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/StorageEngine.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/wal/WALManager.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/wal/WALManagerTest.java
1. Fixed DataNode not stopping because Wal thread could not exit, after this PR, delete outdated will only execute once.
2. When IoTDBShutDownHook and Flush delete WAL expired files, the asynchronous thread is changed to the synchronous thread, which is more convenient when checking logs
> fix datanode can't stop because wal thread.

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/conf/IoTDBStartCheck.java
Previous pr https://github.com/apache/iotdb/pull/11153 has some problem. 
Now we use replace-existing-copy. If copy success, then delete the original file.
> [IOTDB-6151] Move datanode system.properties safer

- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/ratis/utils/Utils.java
Phenomenon：
- Our Ratis RPC timeout parameter is only applied to the Client, not to the Server. 
- This results in the following RPC timeout still being 3s, which we actually set to 10s in the parameter
Solution：
- Set the corresponding parameters when starting the Ratis Server
> Fixed Ratis server RPC timeout parameter setting invalidation bug

- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/config/RatisConfig.java
change to 100 year after [pr](https://github.com/apache/iotdb/pull/11304)
> [IOTDB-6190] Increase the threshold for Ratis to shut itself down if it detects that a process is stuck 

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/rescon/CachedSchemaEngineStatistics.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/rescon/MemSchemaEngineStatistics.java
In pressure tests, the schema memory usage always wander around the memory capacity, which results in tremendous log revealing memory status changes. 
Such changes are normal system behavior and only used for system status check. Therefore, we do not need to print these logs in industrial scenarios. It is necessary to change the log level from info or warn to debug.
> degrade log level of pbtree memory status monitor

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/DataRegion.java
#11404 fixed an error that the TsFileResource endTime is not correct when insert empty tablet and flush. However, after the empty TsFile deleted, the Resource file didn't removed.
This Pr is fixing this issue.
> Fix empty tsfile resource didn't remove

- iotdb-client/isession/src/main/java/org/apache/iotdb/isession/SessionDataSet.java
- iotdb-core/datanode/src/assembly/resources/conf/datanode-env.bat
- iotdb-core/datanode/src/assembly/resources/conf/datanode-env.sh
In this pr, we do two user-friendly changes:
1. add java doc for SessionDataSet.next(), and recommend users to use SessionDataSet.DataIterator to iterate their result set if possible
2. add HeapDump configuration in datanode-env to let DBA can quickly add `-XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=`.
> Add java doc for SessionDataSet.next() method and HeapDump configuration in datanode-env

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/protocol/IoTDBConnector.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/protocol/airgap/IoTDBAirGapConnector.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/protocol/legacy/IoTDBLegacyPipeConnector.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/protocol/thrift/sync/IoTDBThriftSyncConnector.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/pipe/connector/PipeConnectorTest.java
> [IOTDB-6220] Pipe: Added connector endpoint check logic to avoid self-transmission

- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/execution/exchange/SharedTsBlockQueueTest.java
On mac with jdk17, it could be time-consuming when loading some metric props. SharedTsBlockQueueTest fails frequently due to this:
As this test aims to test whether there's deadlock and the basic functions of SharedTsBlockQueue, not the performance of it, I extended the expected test time of SharedTsBlockQueueTest and this should fix the issue.
> Extend expected test time of SharedTsBlockQueueTest

- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/compaction/cross/InsertionCrossSpaceCompactionRecoverTest.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/compaction/cross/InsertionCrossSpaceCompactionSelectorTest.java
Fix compile error cuased by concurrent PRs merge. Previous PR change the package of TSDataType, which lead to master's compile error
> fix compile error caused by concurrent PR merge in github

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/StorageEngine.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/DataRegion.java
#11421 tried to start the CompactionSchedule of each data region after all data regions recovered. However, the previous implement didn't make sure all data region recovered before init Compaction Schedule. Besides, some recovering data regions may not init Compaction Schedule.
This PR is moving the initCompactionSchedule to the recoverEndTrigger Thread where we can know the recover status of all data regions.
> Fix Compaction Schedule didn't start

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/StorageEngine.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/DataRegion.java
Before this change, a newly created DataRegion won't start compaction because the init logic is moved from DataRegion to StorageEngine, which made the init logic only run when recoving
This PR fix this issue.
> Fix the issue that compaction scheduler is not started when DataRegion created

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/recover/CompactionRecoverManager.java
Add logs of the data region directory and time partition directory in compaction recovery to find out whether each directory is scanned correctly.
> [To rel/1.2]Add compaction recover log

- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/consensus/statemachine/ConfigRegionStateMachine.java
- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/IStateMachine.java
- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/ratis/ApplicationStateMachineProxy.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/consensus/statemachine/BaseStateMachine.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/consensus/statemachine/dataregion/DataRegionStateMachine.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/consensus/statemachine/schemaregion/SchemaRegionStateMachine.java
The retry policy is never used in IStateMachine, yet it brings complexity in Ratis write while may incur poerformance penalties. We should remove it.
see https://issues.apache.org/jira/browse/IOTDB-6227
> [IOTDB-6227] Remove unused retry policy in IStateMachine

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/mtree/impl/pbtree/StampedWriterPreferredLock.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/metadata/mtree/lock/StampedWriterPreferredLockTest.java
Fix issues in concurrent scenarios, for example:
1. Thread A successfully acquire write lock
2. Thread B acquire read lock and wait
3. Thread A release write lock
4. Thread C successfully acquire write lock
At this time, Thread B may be waked up and try to get read lock. So it's necessary to judge `(prior ? writeCnt : writeCnt + writeWait) > 0` again. Otherwise, there are one writer and one reader holding lock.
> Fix concurrent read lock bug in StampedWriterPreferredLock

- iotdb-api/pipe-api/src/main/java/org/apache/iotdb/pipe/api/customizer/parameter/PipeParameterValidator.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/conf/ConfigNodeDescriptor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/protocol/airgap/IoTDBAirGapConnector.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/protocol/legacy/IoTDBLegacyPipeConnector.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/protocol/thrift/sync/IoTDBThriftSyncConnector.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/utils/NodeUrlUtils.java
Added hostName and IPv6 addresses detection of IoTDB pipe sink, and seed configNode pointing to itself.
Now the following IPs or host names pointing to the receiver on sender itself is not allowed:
1. Loopback addresses or hosts
- "localhost"
- "LOCALHOST"
- "127.0.0.1"
- "0.0.0.0.0.0.0.1"
2. General address
- "0.0.0.0"
3. All the sender's IPv4 and IPv6 addresses
- "192.168.100.56"
- "10.255.1.70"
- "fd37:634f:c2bf:421a:a63a:22aa:a80e:f5b6"
5. The senders host name
- "DESKTOP-LOUNTUK"
<hr>
This PR has:
<hr>
> [IOTDB-6220] Pipe: Changed the sink loopback detection logic to support hostName and IPv6 specification.

- pom.xml
The current version of spotless plugin we are using cannot run with JDK 21. Therefore I disabled the spotless check for JDK 21. 
After this fixing, we can run `mvn clean package -pl distribution -am -DskipTests` with JDK21 directly.
> Disable spotless for JDK 21

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/mtree/impl/pbtree/CachedMTreeStore.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/mtree/impl/pbtree/cache/CacheManager.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/mtree/impl/pbtree/cache/ICacheManager.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/mtree/impl/pbtree/flush/PBTreeFlushExecutor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/mtree/impl/pbtree/mnode/container/CachedMNodeContainer.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/mtree/impl/pbtree/mnode/container/ICachedMNodeContainer.java
The original flush implementation will collect all volatile node into a list for flush. Such mechanism will bring extra space and time costs, like duplicate reference storage and list scan.
Implement an iterative process for volatile flush. Now the Cachemanager will return a iterator, used to iteratively visit volatile subtree in memory, and the CachedMTreeStore will use it to write nodes into file.
> Implement iterative volatile node process during pbtree flush

- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/LastFlushTimeMapTest.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/compaction/AbstractCompactionTest.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/compaction/cross/InsertionCrossSpaceCompactionTest.java
Before this change, some unit tests use a simple path which only contains the file name as the path of TsFileResoruce. Another in process PR will analyze TsFileResource path to decode `DataRegion`, `Database` and so on. It needs a whole path and will throw exception when using simple path in UTs.
This PR fix it and replace the simple path with a whole path when creating TsFileResource
> Fix the path of TsFileResource in unit test

- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/udf/builtin/String/UDTFConcat.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/udf/builtin/String/UDTFEndsWith.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/udf/builtin/String/UDTFLower.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/udf/builtin/String/UDTFStartsWith.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/udf/builtin/String/UDTFStrCompare.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/udf/builtin/String/UDTFStrLength.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/udf/builtin/String/UDTFStrLocate.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/udf/builtin/String/UDTFTrim.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/udf/builtin/String/UDTFUpper.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/udf/builtin/UDTFAbs.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/udf/builtin/UDTFConst.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/udf/builtin/UDTFConstE.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/udf/builtin/UDTFConstPi.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/udf/builtin/UDTFContains.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/udf/builtin/UDTFInRange.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/udf/builtin/UDTFMatches.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/udf/builtin/UDTFMath.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/udf/builtin/UDTFOnOff.java
- library-udf/pom.xml
- library-udf/src/main/java/org/apache/iotdb/library/anomaly/UDTFRange.java
- library-udf/src/main/java/org/apache/iotdb/library/dprofile/UDTFSample.java
- library-udf/src/main/java/org/apache/iotdb/library/string/UDTFRegexMatch.java
- library-udf/src/main/java/org/apache/iotdb/library/string/UDTFRegexReplace.java
- library-udf/src/main/java/org/apache/iotdb/library/string/UDTFRegexSplit.java
- library-udf/src/main/java/org/apache/iotdb/library/string/UDTFStrReplace.java
Make all available scalar User Defined Functions(including built-in UDFs and UDFs in library-udf) into batch processing. The involved files which contain relevent UDFs can be viewed in Github's Commits page.
This PR also fix some bad code smells in library-udf.
<hr>
This PR has:
> Make all built-in scalar UDF into batch processing

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/config/constant/PipeConnectorConstant.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/protocol/legacy/IoTDBLegacyPipeConnector.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/protocol/thrift/async/IoTDBThriftAsyncConnector.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/protocol/thrift/sync/IoTDBThriftSyncConnector.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/protocol/thrift/sync/IoTDBThriftSyncConnectorClient.java
THIS PR is a follow-up in Pipe for https://github.com/apache/iotdb/pull/11218.
When using iotdb-thrift-sync-connector and iotdb-legacy-pipe-connector, now can configure the sender-side SSL related settings in parameters.
| Key                      | Value                                                        | Value Range       | Required or Optional with Default |
| ------------------------ | ------------------------------------------------------------ | ----------------- | --------------------------------- |
| sink.ssl.enable          | Whether the data service of one of the DN in the target IoTDB supports SSL. | Boolean: true, false | Optional: Default is false         |
| sink.ssl.trust-store-path | The path to the certificate of the Trust Store required for SSL when connecting to …
> Pipe: preliminary SSL support for pipe connector (sink) sync client

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/DataRegion.java
#11404 fixed when inserting empty Tablet and flush, some empty TsFileResource generated. However, after inserting empty Tablet, killing and restarting DataNode, the empty TsFileResource will still be generated.
To fix it, we need to add the deletion logic of #11404 to the position where resource recovered from WAL. 
1. start 1C1D iotdb and execute the following code.
```java
public static void main(String[] args)
session =
new Session.Builder()
.host(LOCAL_HOST)
.port(6667)
.username("root")
.password("root")
.version(Version.V_1_0)
.build();
session.open(false);
insertTablet();
session.close();
}
private static void insertTablet() throws IoTDBConnectionException, StatementExecutionException {
// The schema of measurements of …
```
> fix empty resource recovered from wal

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/extractor/realtime/assigner/DisruptorQueue.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/resource/memory/PipeMemoryManager.java
Allocating memory for the DisruptorQueue requires ensuring that the memory size is a power of 2, so the Memory Framework provides `Function` method for users to customize their own reallocate strategy.
> [IOTDB-6240] Pipe: Fix bug with PipeMemoryManager allocating memory for the DisruptorQueue

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/plan/node/write/InsertNode.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/DataRegion.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/DataRegionTest.java
If all the data types in the insertPlan are inconsistent with the registered metadata, memtable will consider all the columns written to fail when calculating the total number of points. In this case, totalPointNum will not increase and will remain 0. However, the calculation of memSize does not consider the case of fail. So the memSize will increase.
After flush, the system determines whether to delete the TsFile according to whether the tsfile is empty.
According to the previous write scenario, totalMemtableSize is not 0 and workMemTable is null. Therefore, the TsFile is considered not empty, resulting in that the TsFile is not deleted.
To fix it, before entering the TsFileProcessor, check that all data types in the write request do not match the registered metadata, and if they do, …
> Fix empty tsfile generated when all datatypes in one insert mismatching

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/service/DataNode.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/DataRegion.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/wal/utils/listener/AbstractResultListener.java
#11172 was trying to fix datanode stuck issue when meets disk error. However, there are still some problems need to fix.
1. When DataRegion compaction recover failed, the CountDownLatch of WALRecoverManager needs to countdown as well.
2. The waitForResult method of AbstractResultListener may have the endless loop, when catches an InterruptedException.  We need to add a break logic to exit the loop.
3. After calling the stop method in DataNode, some threads may still live. Therefore, adding a `System.exit` is a better way to exit the DataNode.
See #11172
> Fix datanode stuck when meets disk error

- iotdb-client/jdbc/src/main/java/org/apache/iotdb/jdbc/Utils.java
- iotdb-client/jdbc/src/test/java/org/apache/iotdb/jdbc/UtilsTest.java
- iotdb-client/service-rpc/pom.xml
- iotdb-client/service-rpc/src/main/java/org/apache/iotdb/rpc/UrlUtils.java
- iotdb-client/service-rpc/src/test/java/org/apache/iotdb/rpc/UrlUtilsTest.java
- iotdb-client/session/src/main/java/org/apache/iotdb/session/util/SessionUtils.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/utils/NodeUrlUtils.java
- iotdb-core/node-commons/src/test/java/org/apache/iotdb/commons/utils/NodeUrlUtilsTest.java
IPv6 is used to parse the IP address and port number in the URL.
this function , we has been tested in ipv6 server。
> [IOTDB-1476]IoTDB support IPv6

- iotdb-core/metrics/core/src/main/java/org/apache/iotdb/metrics/core/IoTDBMetricManager.java
- iotdb-core/metrics/interface/src/main/java/org/apache/iotdb/metrics/AbstractMetricManager.java
- iotdb-core/metrics/interface/src/main/java/org/apache/iotdb/metrics/impl/DoNothingMetricManager.java
[IOTDB-6206](https://issues.apache.org/jira/projects/IOTDB/issues/IOTDB-6206?filter=allissues)
1. Reduce the length of micrometer's internal histogram ringBuffer to optimize writing efficiency
2. Reduce some duplicate parameter
> [IOTDB-6206] Metric Core: Shrink ringBuffer length to optimize histogram and timer's record performance

- integration-test/src/test/java/org/apache/iotdb/db/it/IoTDBInsertWithQueryIT.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/aggregation/timerangeiterator/SingleTimeWindowIterator.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/AggregationUtil.java
Before fix, the result of select count(*) from root.** is always 0, now it will be the right value.
See details in TIMECHODB-434.
> Fix aggregation error when inserting negative timestamp

- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/schema/DeactivateTemplateProcedure.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/schema/DeleteTimeSeriesProcedure.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/schema/UnsetTemplateProcedure.java
Previously, delete timeSeries / deactivate template procedure will execute the same rollback logic each state, however only the first state requires that. This PR fixed this and did some refactor to improve the coding style.
<hr>
This PR has:
<hr>
> [IOTDB-6238] Fix delete timeSeries / deactivate template procedure rollback logic

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/extractor/realtime/PipeRealtimeDataRegionHybridExtractor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/extractor/realtime/PipeRealtimeDataRegionLogExtractor.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/conf/CommonConfig.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/conf/CommonDescriptor.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/config/PipeConfig.java
As title.
In the following 4 cases, we should not extract any more tablet events. all the data represented by the tablet events should be carried by the following tsfile event:
1. The historical extractor has not consumed all the data.
2. HybridExtractor will first try to do extraction in log mode, and then choose log or tsfile mode to continue extracting, but if Wal size > maximum size of wal buffer, the write operation will be throttled, so we should not extract any more tablet events.
3. The number of pinned memtables has reached the dangerous threshold.
4. The number of tsfile events in the pending queue has exceeded the limit.
> Pipe: introduce pipe_max_allowed_pinned_memtable_count param for realtime hybrid mode

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/conf/IoTDBStartCheck.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/client/ConfigNodeInfo.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/service/DataNode.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/rescon/disk/TierManager.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/service/RegisterManager.java
This PR supplements the time taken by each module during DataNode startup. When DataNode startup is slow, it helps us quickly locate the module that causes the slow startup.
> add time cost log for datanode start

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/performer/impl/ReadChunkCompactionPerformer.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/task/AbstractCompactionTask.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/task/CrossSpaceCompactionTask.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/task/InnerSpaceCompactionTask.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/task/InsertionCrossSpaceCompactionTask.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/io/CompactionTsFileWriter.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/compaction/FastInnerCompactionPerformerTest.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/compaction/ReadChunkInnerCompactionTest.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/compaction/cross/RewriteCrossSpaceCompactionWithReadPointPerformerTest.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/compaction/inner/InnerCompactionEmptyTsFileTest.java
- iotdb-core/tsfile/src/main/java/org/apache/iotdb/tsfile/write/chunk/AlignedChunkWriterImpl.java
- iotdb-core/tsfile/src/main/java/org/apache/iotdb/tsfile/write/chunk/ChunkWriterImpl.java
- iotdb-core/tsfile/src/main/java/org/apache/iotdb/tsfile/write/chunk/IChunkWriter.java
1. Mark target file as DELETED status if the target file is empty in ReadChunkCompactionPerformer
2. Skip the target file which is marked as DELETED status when validate compaction result
> Check empty target file after sequence InnerSpaceCompactionTask

- iotdb-api/pipe-api/src/main/java/org/apache/iotdb/pipe/api/customizer/parameter/PipeParameterValidator.java
Problem:
validator passes when validating an optional parameter, even if the parameter entered by the user is not in the specified range
问题：
validator 在验证一个可选参数时，即使用户输入的参数不在指定范围内，也会通过验证
> [IOTDB-6246] Pipe: Validator validates the range of values for optional parameters improperly

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/wal/utils/WALEntryHandler.java
See: https://github.com/apache/iotdb/actions/runs/6810140489/job/18517907223?pr=11508
WALEntryHandlerTest.testConcurrentGetValue.
Previously, the WALEntryHandler "getInsertNode" let "res = value" and then judge "res != null" to imply the "value != null", and then return the "value" to the caller. However, the value may be set null by another thread, so after "res = value", the value may be set no null, causing potential IT failure and point losing.
This PR fixed this problem and return "res" directly.
<hr>
This PR has:
<hr>
> Pipe: Added concurrency check to avoid WALEntryHandler#getInsertNode returning null to fix potential NPE

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/recover/CompactionRecoverManager.java
Add logs of the data region directory and time partition directory in compaction recovery to find out whether each directory is scanned correctly.
> Add logs in compaction recovery

- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/consensus/request/write/region/CreateRegionGroupsPlan.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/persistence/partition/DatabasePartitionTable.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/persistence/partition/PartitionInfo.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/statemachine/CreateRegionGroupsProcedure.java
- iotdb-core/confignode/src/test/java/org/apache/iotdb/confignode/consensus/request/ConfigPhysicalPlanSerDeTest.java
- iotdb-core/confignode/src/test/java/org/apache/iotdb/confignode/persistence/PartitionInfoTest.java
- iotdb-core/confignode/src/test/java/org/apache/iotdb/confignode/procedure/impl/CreateRegionGroupsProcedureTest.java
**Jira:** https://issues.apache.org/jira/browse/IOTDB-6239
This PR reverts the updation of CreateRegionGroupsPlan in https://github.com/apache/iotdb/pull/11481. Because it's too expensive to supporting the compability in the current serialization framework.
The compability problem can be resolved by importing thrift-idl framework, which might be implemented at v1.4.0
> [IOTDB-6239] Revert updation of CreateRegionGroupsPlan

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/task/InsertionCrossSpaceCompactionTask.java
Fix insertion compaction replace keyword bug.
If the data directory of IoTDB contains the keyword 'unsequence', this will cause the target file of InsertionCompaction to appear in the wrong dir.
The dir 'test-load-unsequence' is replaced to 'test-load-sequence' in target compaction file.
> Fix insertion compaction replace keyword bug

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/DataRegion.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/tsfile/TsFileResource.java
(describe what the issue is and what the impact if we don't fix it)
(explain how the issue is created in previous change)
(explain the changes in this PR and describe how to fix the issue)
Validate flushed TsFile without holding closeQueryLock.
Before this fix, the validation of writing will be performed when holding the write lock of 'closeQueryLock' if TsFile correctness validation is enabled, which block other threads to close TsFile or query.
> Validate flushed tsfile without holding closeQueryLock

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/scheduler/AsyncSendPlanNodeHandler.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/service/IoTDBShutdownHook.java
1. If TimeoutException happened while sending write FI, we need to retry sending this FI to another follower.
2. We need to stop rpc service firstly in shut down hook, because we don't want to receive more client requests which will also be refused in the later process.
> Support high available while meeting timeout exception

- iotdb-core/confignode/src/assembly/resources/conf/confignode-env.bat
- iotdb-core/confignode/src/assembly/resources/conf/confignode-env.sh
- iotdb-core/datanode/src/assembly/resources/conf/datanode-env.bat
- iotdb-core/datanode/src/assembly/resources/conf/datanode-env.sh
Recently, we found in some real user cases that when OOM occurs in the DataNode process (although we should ensure that OOM does not happen, but we all know that bugs will always exist), some threads(e.g. rpc listening threads) may exit unexpectedly which may cause some strange things to happen. For example, if the heartbeat listening thread on the DataNode unexpectedly exits due to OOM, and then the OOM recovers on its own (some large queries end, or some compaction tasks end), but this thread will never exist again, causing the DataNode to remain in unknown state, because the ConfigNode can no longer contact it via heartbeat.
Therefore, we feel that OOM is a high-risk error, and we should let the process exit directly to avoid the loss of some key threads.
And I did an experiment and …
> DataNode & ConfigNode exit directly while meeting OutOfMemoryError

- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/consensus/index/ProgressIndex.java
Problem:
ProgressIndex cann't compare with null, modify args in ProgressIndex#topologicalCompareTo to nonnull.
问题：
ProgressIndex 不能和 null 比，修改  ProgressIndex#topologicalCompareTo 的入参为 nonnull
> [IOTDB-6250] Pipe: Fix topological sort with null ProgressIndex 

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/consensus/statemachine/dataregion/DataExecutionVisitor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/DataRegion.java
Before this change, some write operations will return `QUERY_PROCESS_ERROR` when catching BatchProcessException. The status seems wired for write operations. And especially in IoTConsensus, it won't trigger operation retry when the response code is `QUERY_PROCESS_ERROR`.
Thus, to fix this issue, we will return WRITE_PROCESS_ERROR if write operation catches BatchProcessException
> Return WRITE_PROCESS_ERROR when catching BatchProcessException in writing process

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/DataRegion.java
rename the file only when it exists. Otherwise, the file is not renamed.
1. start a 1C1D cluster
2. execute `insert into root.a1.d1 (time,s4) values (14,"123f111aa");`
3. execute `delete timeseries root.a1.d1.**`
4. execute `flush`
5. observe for any of the following errors
> add file validate when rename file, avoid rename error because file is not exist

- integration-test/src/main/java/org/apache/iotdb/it/env/cluster/config/MppCommonConfig.java
- integration-test/src/main/java/org/apache/iotdb/it/env/cluster/config/MppSharedCommonConfig.java
- integration-test/src/main/java/org/apache/iotdb/it/env/remote/config/RemoteCommonConfig.java
- integration-test/src/main/java/org/apache/iotdb/itbase/env/CommonConfig.java
- integration-test/src/test/java/org/apache/iotdb/db/it/IoTDBInsertMultiRowIT.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/AnalyzeVisitor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/plan/node/write/InsertNode.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/plan/node/write/InsertRowsOfOneDeviceNode.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/plan/plan/node/write/WritePlanNodeSplitTest.java
When an insertRecordsOfOneDevice write request contains data from two time partitions 0 and 1, assuming that the first data is sequential data from a 0 partition, the initial value of isSequence is false. The isSequence is set to true after the code block of line 2794 is entered and the first data is written to the sequential space of the 0 partition. If the second data is an out-of-order data in the 1 partition, isSequence is still true, and the out-of-order data in the 2794 line is not entered into the out-of-order judgment, and the out-of-order data will be written into the order space of the 1 partition. This causes timestamp overlaps between sequential space files in the 1 partition.
To fix it, when doing insertRecordsOfOneDeviceNode split, the different time of the same DataRegion …
> Fix insertRecordsOfOneDevice causes data out of order

- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/consensus/ConsensusManager.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/consensus/DataRegionConsensusImpl.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/consensus/SchemaRegionConsensusImpl.java
Previous we only retry 3 times, waiting 500ms each.
We should align this parameter with connection timeout.
> Increase retry timeout for ratis retry mechanism

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/HashLastFlushTimeMap.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/tsfile/TsFileManager.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/rescon/memory/TimePartitionManager.java
1. When a sequence tsfile is flushed, the LastFlushTimeMap will update with the end time of the devices of the tsfile. The method `updateLatestFlushTime` is called here and put the value to LastFlushTimeMap, which is correct in normal cases. However, if the lastFlushTime is modified by `load`, the end time of unsequence space may larger than the sequence space, and the LastFlushTime may be set to a smaller value.
2. When recover the LastFlushTime of a device, TsFileManager will search the sequence files in reverse order and find the last sequence file who contains the device. If the LastFlushTimeMap of a time partition is evicted by FlushCallback of another  tsfile and there is a unclosed tsfile in the evicted time partition, the next write of the time partition will recover the …
> Fix update and recovery of LastFlushTimeMap

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/performer/impl/ReadChunkCompactionPerformer.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/utils/MultiTsFileDeviceIterator.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/utils/executor/fast/AlignedSeriesCompactionExecutor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/utils/executor/fast/NonAlignedSeriesCompactionExecutor.java
Use faster constructor of PartialPath in Compaction.
The constructor of PartialPath with device and measurement may cost long time, this pr replace these usage to another constructor.
> Use faster constructor of PartialPath in Compaction

- integration-test/src/test/java/org/apache/iotdb/pipe/it/IoTDBPipeClusterIT.java
This test intends to test the behaviour when the sender has a temporary node joined and then removed, but in reality it just tears it down. In this circumstance the IT may fail. However, the "remove" method is currently not provided thus this PR ignored this test.
<hr>
This PR has:
<hr>
> Pipe: ignore the IoTDBPipeClusterIT.testNewDataNodeFailureAfterTransferringData to avoid inevitable IT failure

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/utils/MultiTsFileDeviceIterator.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/compaction/ReadChunkInnerCompactionTest.java
Fix aligned device modification not matched in MultiTsFileDeviceIterator
1. delete all data of db with modification
2. trigger an inner space compaction with ReadChunkCompactionPerformer
3. execute a query with the deleted datas
> Fix aligned device modification not matched in MultiTsFileDeviceIterator

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/schedule/DriverTaskThread.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/schedule/queue/multilevelqueue/MultilevelPriorityQueue.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/timer/RuleBasedTimeSliceAllocator.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/execution/DataDriverTest.java
- iotdb-core/node-commons/src/assembly/resources/conf/iotdb-common.properties
This PR does the following two things: 
1. Allocates longer time slices for higher-level tasks in the MultiLevelPriorityQueue. 
3. Changes the default time slice length to 200ms.
> Extend time slice for DriverTasks in higher level queue and double default EXECUTION_TIME_SLICE

- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/iot/client/DispatchLogHandler.java
Currently, iotconsensus only determines the first one when deciding whether to retry, which is inaccurate. 
In fact, if any request in a batch fails, we will retry the whole batch
> Enhance IoTConsensus retry judgement to all writenodes in a batch

- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/compaction/CompactionSchedulerTest.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/compaction/utils/CompactionConfigRestorer.java
This UT is testing large file merging, which requires a large amount of memory, and the CI environment has a small memory. As a result, the file merging is limited due to the merging memory control, and the merging cannot be completed.
To fix it, we need setEnableCompactionMemControl= false for this UT.
> Fix UT testLargeFileInLowerLevel timeout

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/protocol/thrift/async/IoTDBThriftAsyncConnector.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/protocol/thrift/async/handler/PipeTransferTabletBatchEventHandler.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/protocol/thrift/async/handler/PipeTransferTabletInsertionEventHandler.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/protocol/thrift/async/handler/PipeTransferTsFileInsertionEventHandler.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/protocol/websocket/WebSocketConnector.java
Previously, when TException is encountered, the async pipe will just warn and ignore it, causing event to lose and forever pinned.
This PR resolved these problems and made the code tidier.
<hr>
This PR has:
<hr>
> Pipe: Fixed event forever pinned and retry never invoked when TException encountered in IoTDBThriftAsyncConnector

- integration-test/src/test/java/org/apache/iotdb/db/it/auth/IoTDBAuthIT.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/common/schematree/ClusterSchemaTree.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/common/schematree/ISchemaTree.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/common/schematree/visitor/SchemaTreeVisitorFactory.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/AnalyzeVisitor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/mtree/traverser/Traverser.java
```
create aligned timeseries root.sg.d1(s1 float encoding=rle, s2 int64 encoding=rle);
create timeseries root.sg.d2.s1 with datatype=float,encoding=rle;
create timeseries root.sg.d2.s2 with datatype=int64,encoding=rle;
create device template t1 aligned (temperature FLOAT encoding=Gorilla, status BOOLEAN encoding=PLAIN);
set device template t1 to root.sg.aligned_template;
show paths set device template t1;
create timeseries using device template on root.sg.aligned_template;
insert into root.sg.d1(time,s1,s2) values(1,1,1),(2,2,2),(3,3,3),(4,4,4),(5,5,5),(6,6,6),(7,7,7),(8,8,8),(9,9,9),(10,10,10);
insert into root.sg.d2(time,s1,s2) values(1,1,1),(2,2,2),(3,3,3),(4,null,4),(6,6,null);
insert into root.sg.aligned_template(time,temperature,status) …
```
> Fix query data with authority return unexpected result

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/DataRegion.java
Modify compaction schedule policy for insertion compaction. Skip the selection of other compaction task if any insertion compaction task num is submitted. 
Before this PR:
After this PR:
All files loaded into unsequence space are moved to sequence space directly.
> Modify compaction schedule for insertion compaction

- integration-test/src/test/java/org/apache/iotdb/session/it/IoTDBSessionSimpleIT.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/statement/crud/InsertMultiTabletsStatement.java
Currently insertTablets API  didn't return schema validation error. This PR is fixing it. The error information of each insertTablet should be passed out to insertTabletsStatement.
Set `enable_auto_create_schema=false`
Execute the following code
```java
public static void main(String[] args)
session =
new Session.Builder()
.host(LOCAL_HOST)
.port(6667)
.username("root")
.password("root")
.build();
session.open(false);
insertTablets();
session.close();
}
private static void insertTablets() throws IoTDBConnectionException, StatementExecutionException {
// The schema of measurements of one device
// only measurementId and data type in MeasurementSchema take effects in Tablet
List<MeasurementSchema> schemaList = new ArrayList<>(); …
```
> Fix insertTablets API didn't return schema validation error

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/AbstractDataSourceOperator.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/AbstractSeriesAggregationScanOperator.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/AlignedSeriesScanOperator.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/SeriesScanOperator.java
The process of PlanNode to Operator is a single-thread and blocking oepration in scheduling, so we should not put too much heavy work in it, we should try our best to let it simple and fast, so some heavy and unnecessary work should be delayed into the DriverTask which will be executed in seperated query worker thread and is async.
> Accelerate the process of PlanNode to Operator

- integration-test/src/test/java/org/apache/iotdb/db/it/auth/IoTDBAuthIT.java
- integration-test/src/test/java/org/apache/iotdb/db/it/auth/IoTDBTemplatePermissionIT.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/schema/AutoCreateSchemaExecutor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/statement/internal/InternalBatchActivateTemplateStatement.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/statement/metadata/template/AlterSchemaTemplateStatement.java
more details can be seen in https://jira.infra.timecho.com:8443/browse/TIMECHODB-395
> Fix AutoCreateSchema using template without WRITE_SCHEMA

- integration-test/src/test/java/org/apache/iotdb/db/it/alignbydevice/IoTDBAlignByDeviceWithTemplateIT.java
- integration-test/src/test/java/org/apache/iotdb/db/it/alignbydevice/IoTDBOrderByLimitOffsetAlignByDeviceIT.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/payload/evolvable/request/PipeTransferTabletBatchReq.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/AnalyzeVisitor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/TemplatedInfo.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/TypeProvider.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/OperatorTreeGenerator.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/SubPlanTypeExtractor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/TemplatedLogicalPlan.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/TemplatedLogicalPlanBuilder.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/plan/PlanFragment.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/plan/node/PlanNode.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/plan/node/PlanNodeType.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/plan/node/process/SingleDeviceViewNode.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/plan/node/source/AlignedSeriesScanNode.java
In this pr, I extract all common variables in align by device query (and all queried devices are set in one template) to a class named  `TemplateInfo`.  So in LogicalPlan, DistributedPlan and Schedule step, we can use this structure to accelerate the construction, avoiding repeated creation and serialization.
Before optimization:
schedule: 5000ms
After optimization:
schedule: 700ms
> Use template to reduce the repeated creation and serialization in align by device query

- iotdb-core/tsfile/src/main/java/org/apache/iotdb/tsfile/file/metadata/statistics/BinaryStatistics.java
the first value and last value initialization process in BinaryStatistics is time consuming, and there is no need for us to do it.
> Improve BinaryStatistics deserialization

- iotdb-core/node-commons/src/assembly/resources/sbin/iotdb-common.sh
see https://jira.infra.timecho.com:8443/browse/TIMECHODB-441?filter=10506
Solution:
When the parameter cannot be found in the configuration file, use the default value
> fix the parameter is null causing lsof error

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/common/schematree/ClusterSchemaTree.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/metadata/schemaRegion/SchemaRegionTemplateTest.java
```
--1. CREATE TEMPLATE
create device template t1 (temperature FLOAT encoding=RLE, status BOOLEAN encoding=PLAIN compression=SNAPPY);
show schema templates;
show device templates;
create database root.sg1;
--2. SET TEMPLATE
set device template t1 to root.sg1.d1;
show paths set schema template t1;
show paths set device template t1;
--3. ACTIVATE TEMPLATE
create timeseries of device template on root.sg1.d1;
show paths using device template t1;
show devices root.sg1.**;
show timeseries;
show timeseries root.sg1.**;
--4. INSERT DATA
insert into root.sg1.d1(time, temperature, status) values(1, 1, 1);
insert into root.sg1.d1(time, temperature, status) values(2, 2, 0), (3, 3, 1);
select * from root.sg1.d1;
--5. QUERY
insert into root.sg1.d1.GPS(time, latitude, longitude) values(1, 1, 1);
show …
```
> Fix fetch nested device with template will miss some devices

- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/metadata/schemaRegion/AbstractSchemaRegionTest.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/metadata/schemaRegion/SchemaRegionBasicTest.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/path/fa/dfa/PatternDFA.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/path/fa/dfa/graph/DFAGraph.java
- iotdb-core/node-commons/src/test/java/org/apache/iotdb/commons/path/PatternDFATest.java
Use HashMap instead of 2D arrays to avoid space occupation in sparse matrices. Experiments with `testFetchSchemaPerfomance` demonstrate that performance is not affected, but there is a significant reduction in memory usage.
Before：
After：
> Optimize memory usage of fetchSchema when inserting data

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/execution/memory/StatementMemorySourceVisitor.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/plan/analyze/FakeSchemaFetcherImpl.java
Before fix, the explain result of below sql list is empty.
`CREATE database root.sg2;
CREATE schema template t2 aligned (s1 FLOAT encoding=RLE, s2 BOOLEAN encoding=PLAIN compression=SNAPPY, s3 INT32);
SET SCHEMA TEMPLATE t2 to root.sg2;
INSERT INTO root.sg2.d1(timestamp,s1,s2,s3) values(1,1.1,false,1), (2,2.2,false,2);
INSERT INTO root.sg2.d2(timestamp,s1,s2,s3) values(1,11.1,false,11), (2,22.2,false,22);
INSERT INTO root.sg2.d3(timestamp,s1,s2,s3) values(1,111.1,true,null), (4,444.4,true,44);
INSERT INTO root.sg2.d4(timestamp,s1,s2,s3) values(1,1111.1,true,1111), (5,5555.5,false,5555);
SELECT * FROM root.sg2.** ALIGN BY DEVICE;`
> Fix explain error when align by device + template

- iotdb-core/tsfile/src/main/java/org/apache/iotdb/tsfile/read/reader/page/AlignedPageReader.java
- iotdb-core/tsfile/src/main/java/org/apache/iotdb/tsfile/read/reader/page/PageReader.java
In some query cases, of the limit is much less than the count of each page, we should use limit instead of page size as the init capacity of the result block.
> Use min(limt, page size) as the init capacity of result block

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/cache/partition/PartitionCache.java
more details can be seen in https://jira.infra.timecho.com:8443/browse/TIMECHODB-447
we can find that if the cache is cleared between these two line, we will try to create an already existing database.
> Fix concurrent bug in PartitonCache

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/consensus/statemachine/dataregion/DataRegionStateMachine.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/consensus/statemachine/dataregion/DataRegionStateMachineTest.java
The logic for executing write requests in the follower involves assembling a batch of insertRowsNode that share the same deviceId into a single insertRowsOfOneDeviceNode for execution. However, during the assembly process, there's no consideration for ordering.
When the follower's dataRegion executes the writing of insertRowsOfOneDeviceNode, we simplify the logic for checking orderliness due to the default assumption of sorted data. However, if insertRowsOfOneDeviceNode isn't sorted, it may result in disordered data within the sequence space.
> Fix follower data may out of order

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/common/schematree/ClusterSchemaTree.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/common/schematree/ISchemaTree.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/schema/SchemaFetchScanOperator.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/AnalyzeVisitor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/schema/ClusterSchemaFetchExecutor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/schema/ClusterSchemaFetcher.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/schema/ISchemaFetcher.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/execution/config/executor/ClusterConfigTaskExecutor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/LogicalPlanBuilder.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/LogicalPlanVisitor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/OperatorTreeGenerator.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/plan/node/metedata/read/SchemaFetchScanNode.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/statement/internal/SchemaFetchStatement.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/ISchemaRegion.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/impl/SchemaRegionMemoryImpl.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/impl/SchemaRegionPBTreeImpl.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/mtree/impl/mem/MTreeBelowSGMemoryImpl.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/mtree/impl/pbtree/MTreeBelowSGCachedImpl.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/read/resp/reader/impl/TimeseriesReaderWithViewFetch.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/metadata/schemaRegion/SchemaRegionBasicTest.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/metadata/schemaRegion/SchemaRegionTemplateTest.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/execution/operator/OperatorMemoryTest.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/execution/operator/schema/SchemaFetchScanOperatorTest.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/plan/analyze/ExpressionAnalyzerTest.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/plan/analyze/FakeSchemaFetcherImpl.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/plan/plan/distribution/Util.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/plan/plan/distribution/Util2.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/plan/plan/node/metadata/read/SchemaFetchMergeNodeTest.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/plan/plan/node/metadata/read/SchemaFetchScanNodeTest.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/path/PathPatternTree.java
This PR fix some query bugs with authority:
1. Query pure template series with partitial authority.
2. Query view series without origin time series read authority.
For implementation, I removed the authorityScope field from the ClusterSchemaTree for better maintenance. To avoid redundant measurement when ClusterSchemaTree uses templates, the query engine will determine whether to fetch schema with template by `authorityScope`.
```java
// If the authority scope of query statement contains full path, we should fetch schema
// without template. Otherwise, the result ISchemaTree may contain template series that is
// not authorized to access.
boolean allWildcardLeaf = !authorizedPatternTree.isContainFullPath() && authorizedPatternTree.isContainWildcard();
```
If allWildcardLeaf is true, the …
> Fix query return unexpected result with authority

- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/ConfigManager.java
The series_partition_slot_num parameter has been replaced by series_slot_num, and the error message needs to be updated
> Adjust series_partition_slot_num to series_slot_num in the response message

- integration-test/src/test/java/org/apache/iotdb/pipe/it/IoTDBPipeExtractorIT.java
- integration-test/src/test/java/org/apache/iotdb/pipe/it/extractor/IoTDBPipeExtractorIT.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/pipe/task/CreatePipeProcedureV2.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/pipe/task/DropPipeProcedureV2.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/pipe/task/StartPipeProcedureV2.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/pipe/task/StopPipeProcedureV2.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/extractor/historical/PipeHistoricalDataRegionTsFileExtractor.java
To enhance the availability of Pipe, even if an exception occurs during the `executeFromOperateOnDataNodes` (`rollbackFromOperateOnDataNodes`) phase of procedures like create/start/stop/drop pipe on CN, where pipe metadata on DN is not synchronized with CN, it is considered successful. The pipe metadata will be automatically synchronized within at most one synchronization cycle.
<hr>
This PR has:
<hr>
> Pipe: degrade exception to log when executing pipe procedure operations on DN to enhance the availability

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/fragment/FragmentInstanceContext.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/transformation/dag/column/binary/CompareBinaryColumnTransformer.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/transformation/dag/column/ternary/BetweenColumnTransformer.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/transformation/dag/transformer/binary/CompareEqualToTransformer.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/transformation/dag/transformer/binary/CompareGreaterEqualTransformer.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/transformation/dag/transformer/binary/CompareGreaterThanTransformer.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/transformation/dag/transformer/binary/CompareLessEqualTransformer.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/transformation/dag/transformer/binary/CompareLessThanTransformer.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/transformation/dag/transformer/binary/CompareNonEqualTransformer.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/transformation/dag/transformer/ternary/BetweenTransformer.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/transformation/dag/util/TransformUtils.java
Related doc: https://apache-iotdb.feishu.cn/docx/VjxMd1BdHotEeIxHzsxc382Jnec
Simply put, this PR avoids unnecessary creation of String objects when comparing Binary types, and ceases computation when encountering an entirely empty column.
Before this PR, doTransform occupied 18.6% of the execution time：
After this PR, doTransform occupied 13.1% of the execution time：
> Optimizing the Binary comparison method in CompareBinaryColumnTransformer

- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/ratis/utils/Utils.java
We need to compute the consensus group id to raft group id mapping every time. This is cpu-consuming and we can avoid them simply by adding a weak-value cache.
> [RatisConsensus] Cache group id in the write/read critical path

- integration-test/src/test/java/org/apache/iotdb/db/it/alignbydevice/IoTDBAlignByDeviceWithTemplateIT.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/process/TopKOperator.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/TemplatedAnalyze.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/execution/operator/TopKOperatorTest.java
Fix the possible npe in TopKOperator when the children device operators of TopKOperator all have no result.
> Fix npe in TopKOperator when topKResult is null.

- integration-test/src/test/java/org/apache/iotdb/db/it/auth/IoTDBAuthIT.java
- integration-test/src/test/java/org/apache/iotdb/db/it/auth/IoTDBTemplatePermissionIT.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/schema/AutoCreateSchemaExecutor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/statement/internal/InternalBatchActivateTemplateStatement.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/statement/metadata/template/AlterSchemaTemplateStatement.java
It change back to the previous definition, we only allow root to alter the template.
> Only root can alter template

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/driver/Driver.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/exchange/sink/LocalSinkChannel.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/exchange/sink/ShuffleSinkHandle.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/exchange/sink/SinkChannel.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/exchange/source/LocalSourceHandle.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/exchange/source/SourceHandle.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/fragment/FragmentInstanceExecution.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/memory/MemoryPool.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/Operator.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/process/TopKOperator.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/schema/SchemaFetchScanOperator.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/AbstractDataSourceOperator.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/LastCacheScanOperator.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/source/ShowQueriesOperator.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/schedule/DriverTaskTimeoutSentinelThread.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/execution/operator/FillOperatorTest.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/execution/operator/LastQueryMergeOperatorTest.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/execution/operator/LinearFillOperatorTest.java
This PR adds a close method to TokOperator, ensuring that its child Operators are properly closed when it is closed, and guaranteeing that the SourceHandle and SinkChannel of the data transmission module are correctly cleaned up even when the query times out.
The close method of the Operator should be an interface, and the implementation of a new Operator must include logic for resource cleanup.
> Fix close method of TopOperator and make close method of Operator an interface

- iotdb-core/consensus/pom.xml
- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/ratis/metrics/CounterProxy.java
- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/ratis/metrics/GaugeProxy.java
- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/ratis/metrics/IoTDBMetricRegistry.java
- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/ratis/metrics/MetricRegistryManager.java
- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/ratis/metrics/RatisMetricsManager.java
- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/ratis/metrics/TimerProxy.java
- pom.xml
Bump ratis version to 3.0.0 and change the metrics implementation.
The metrics can be correctly created and referred. see
> [IOTDB-6259] Bump ratis version to 3.0.0

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/AnalyzeVisitor.java
see [TIMECHODB-467]
Before fix, the sqls below will throw npe.
`create timeseries root.db.t1.s1 with dataType=BOOLEAN;
create timeseries root.db.t1.s2 with dataType=INT32;
create timeseries root.db.t1.s3 with dataType=INT64;
create timeseries root.db.t1.s4 with dataType=FLOAT;
create timeseries root.db.t1.s5 with dataType=DOUBLE;
create timeseries root.db.t1.s6 with dataType=TEXT;
create aligned timeseries root.db.t2(s11 boolean encoding=PLAIN compressor=lz4,s12 INT32 encoding=TS_2DIFF compressor=SNAPPY,s13 INT64 encoding=GORILLA compressor=LZ4,s14 FLOAT encoding=RLE compressor=SNAPPY,s15 DOUBLE encoding=GORILLA compressor=LZ4,s16 TEXT encoding=DICTIONARY compressor=SNAPPY);
insert into root.db.t1(time,s1,s2,s3,s4,s5,s6) values(1,true,1,1,1.2,1.3,'hi');
insert into …
> Fix the error when last query non-writble view with same sensors

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/selector/impl/SizeTieredCompactionSelector.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/compaction/inner/InnerSpaceCompactionSelectorTest.java
Fix a bug that the TsFileResource whose status is not NORMAL may be selected by selectTaskBaseOnModFile.
Though a tsfile with a mods file whose size is larger than 50M has been selected into a CompactionTask (or other status: COMPACTING, DELETED), it may selected as  candidate of another compaction task by 'selectTaskBaseOnModFile'.
> Fix inner compaction select task base on mod file

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/service/metrics/file/TsFileMetrics.java
In the recovery process of datanode, the updateRemainData method of TsFileMetrics will update the tsfile size and count twice than the real values.
After fixing, the number will be correct.
> Fix tsfile counted twice in TsFileMetrics

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/DataRegion.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/schedule/CompactionScheduler.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/settle/SettleRequestHandler.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/compaction/CompactionSchedulerTest.java
1. Fix UT CompactionSchdulerTest.testLargeFileInLowerLevel
2. Add concurrency control when schedule compaction to avoid conflict from timed compaction schdule and manually triggeered compaction schdule
> Fix compaction UTs and add concurrency control when schedule compaction

- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/partition/PartitionManager.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/persistence/partition/DatabasePartitionTable.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/persistence/partition/PartitionInfo.java
- iotdb-core/confignode/src/test/java/org/apache/iotdb/confignode/persistence/PartitionInfoTest.java
Added getRegionId api for partitionManager for pipe.
This PR can return the TConsensusGroupId for a given integer, Optional.empty() if it doesn't match any of the existing IDs.
<hr>
This PR has:
<hr>
> Added getRegionId api for partitionManager

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/process/TopKOperator.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/distribution/DistributionPlanner.java
ShuffleSinkNode set dop as 1, which is unexpected for TopKNode.
> TopKNode will use IdentityNode but not ShuffleSinkNode

- iotdb-client/cli/src/main/java/org/apache/iotdb/cli/AbstractCli.java
- iotdb-client/jdbc/src/main/java/org/apache/iotdb/jdbc/IoTDBStatement.java
We need to regenerate a statement id while reconnecting, otherwise we will get the following error msg.
> Fix reconnect bug for JDBC

- iotdb-core/confignode/src/assembly/resources/conf/iotdb-confignode.properties
- iotdb-core/datanode/src/assembly/resources/conf/iotdb-datanode.properties
This parameter is only valid for the first startup
> Enhance the note of parameter seed_config_node 

- integration-test/src/test/java/org/apache/iotdb/db/it/IOTDBLoadTsFileIT.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/LoadTsfileAnalyzer.java
As titile.
IoTDB> create user user01 'pass1234';
IoTDB> GRANT WRITE_DATA ON root.** TO USER user01;
> [IOTDB-6264] Load: Optimized Validation Messages with 'write_data' Permissions When Loading TsFiles Without schema Creation

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/selector/impl/SizeTieredCompactionSelector.java
- iotdb-core/node-commons/src/assembly/resources/conf/iotdb-common.properties
Two new inner compaction configurations:
1. inner_compaction_task_selection_disk_redundancy
2. inner_compaction_task_selection_mods_file_threshold
When the size of the mods file corresponding to TsFile exceeds **inner_compaction_task_selection_mods_file_threshold** or disk availability is lower than the sum of **(disk_space_warning_threshold + inner_compaction_task_selection_disk_redundancy)**, inner compaction tasks containing mods files are selected first.
> add config for inner compaction selector

- integration-test/src/test/java/org/apache/iotdb/pipe/it/IoTDBPipeSwitchStatusIT.java
- integration-test/src/test/java/org/apache/iotdb/pipe/it/IoTDBPipeSyntaxIT.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/persistence/pipe/PipeTaskInfo.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/pipe/task/CreatePipeProcedureV2.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/pipe/task/StartPipeProcedureV2.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/pipe/task/StopPipeProcedureV2.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/agent/task/PipeTaskAgent.java
As title, set the pipe status to `RUNNING` in create pipe procedure, so that users do not need to manually start the pipe after creating it.
**TODO:**
<hr>
This PR has:
<hr>
> Pipe: automatically start pipe upon creation & allow to start RUNNING pipe & allow to stop STOPPED pipe 

- iotdb-api/pipe-api/src/main/java/org/apache/iotdb/pipe/api/customizer/parameter/PipeParameterValidator.java
As title.
Example:
```sql
create pipe extractor_realtime_1 
with extractor ('extractor'='iotdb-extractor', 'extractor.pattern'='root.aligned','extractor.history.enable'='false','extractor.realtime.enable'='0') 
with connector ('connector'='iotdb-thrift-connector', 'connector.ip'='127.0.0.1', 'connector.port'='6667');
```
* Before fix:
* After fix:
> Pipe: Make error message reported by pipe parameter check clearer

- integration-test/src/test/java/org/apache/iotdb/db/it/alignbydevice/IoTDBAlignByDeviceWithTemplateIT.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/TemplatedAnalyze.java
Before fix, slimit and soffset is invalid in align by device with template. 
Now I add `ColumnPaginationController` usage in `TemplatedAnalyze.java`.  More details are shown in integration-tests.
> Make slimit and soffset available in align by device with template

- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/ratis/RatisConsensus.java
Ratis required clientId serverId and groupId when constructing reply messge.
> [RatisConsensus] Fix Precondition failure on consensus read

- iotdb-api/pipe-api/src/main/java/org/apache/iotdb/pipe/api/customizer/parameter/PipeParameters.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/persistence/pipe/PipePluginInfo.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/agent/plugin/PipeConnectorConstructor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/protocol/thrift/sync/IoTDBThriftSyncConnector.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/execution/config/executor/ClusterConfigTaskExecutor.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/plugin/builtin/BuiltinPipePlugin.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/plugin/builtin/connector/IoTDBSslConnector.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/plugin/builtin/connector/IoTDBThriftSslConnector.java
1. iotdb-ssl-sink -> iotdb-thrift-ssl-sink 
2. allow not specifying connector in kv attrs 
3. support kv attrs that dont have sink. processor. sink. prefixes
> Pipe: rename iotdb-thrift-ssl-sink & allow not specifying connector in kv attrs & support kv attrs that don't have sink. / processor. / sink. prefixes

- iotdb-core/consensus/src/test/java/org/apache/iotdb/consensus/ratis/DiskGuardianTest.java
- iotdb-core/consensus/src/test/java/org/apache/iotdb/consensus/ratis/RatisConsensusTest.java
- iotdb-core/consensus/src/test/java/org/apache/iotdb/consensus/ratis/RecoverReadTest.java
- iotdb-core/consensus/src/test/java/org/apache/iotdb/consensus/ratis/TestUtils.java
For addMemberToGroup UT:
- The previous UT operates the underlying state machine only after the leader is elected, and the state machine may not be fully restored at this time, thus making some subsequent judgments wrong. This PR changes to ensure that the Leader's state machine is not read until the leader is ready (i.e., the state machine is restored) to ensure that the CI environment does not fail
For testThresholdSnapshot UT:
- In CI environment, some threads are scheduled slowly, requiring 3 chances to generate Snapshot may lead to instability, so this PR is changed to 12 times, which is as low as possible in CI environment with weak resource environment
> Improved stability of Ratis addMemberToGroup and testThresholdSnapshot UT

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/DataRegion.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/HashLastFlushTimeMap.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/ILastFlushTimeMap.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/DataRegionTest.java
- iotdb-core/node-commons/src/assembly/resources/conf/iotdb-common.properties
Add `enable_separate_data` param to switch whether to enable data separation or not. The default is true, which means the data is separated into sequence and unsequence data dir. If it is false, all data will be written to the unsequence data dir.
Our system maintains two data structures in the `HashLastFlushTimeMap` class, one is `partitionLatestFlushedTimeForEachDevice` and the other is `globalLatestFlushedTimeForEachDevice`. The former is used to separate seq and unseq data in each partition, and the latter is used for last cache queries.
1. When the `enable_separate_data` parameter is false, `partitionLatestFlushedTimeForEachDevice` is no longer maintained in the memory. There is no need to judge the order of data, and the data is written directly to the unseq data directory. In the …
> Add a param to switch whether to enable data separation or not

- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/iot/client/DispatchLogHandler.java
The status code returned for handling BatchProcessException is `WRITE_PROCESS_ERROR`, but this status code was not included in the retry judgment of IoT, so the batch that caused BatchProcessException did not retry, resulting in inconsistent data between IoT replications.
To fix the problem, we add the status code `WRITE_PROCESS_ERROR` in IoT Retry judgment.
Besides, the atomicity issue of storage engine write operations can also lead to data inconsistency, which will be fixed in subsequent work.
> [IOTDB-5706] Data inconsistency between IoT protocol replications

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/snapshot/SnapshotTaker.java
Currently, a hard link of mods file is created when taking snapshot for data region, but the mods file is not immutable, which means the snapshot could be updated. We need to make sure the snapshot is immutable too, so a copy of mods file should be created instead of hard link.
> Take snapshot for mods using copy instead of hard link

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/mtree/impl/pbtree/schemafile/pagemgr/PageManager.java
[Previously](https://github.com/apache/iotdb/pull/11467) this mechanism was disabled for more efficient when there are many devices using template with no descendents. The modification would throw exception if nested device and its parental device are both using template, which means a device using template does have a descendent.
The optimization should be considered in further development.
> PBTree: Enable pre-allocation for Internal/Device child node

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/utils/writer/AbstractInnerCompactionWriter.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/utils/writer/FastInnerCompactionWriter.java
1. skip seal page if the next page cannot be flushed directly.
2. Fix the compaction metric if FastCompactionPerformer is used for sequence InnerSpaceCompaction
> Fix some problems of FastCompactionPerformer

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/payload/evolvable/builder/PipeTransferBatchReqBuilder.java
As title. With the introduction of `PipeEventCommitter`, each DR assigns commit id independently to events. Events with the same commit id in different DRs may be lost if using commit id as a condition for duplication check.
<hr>
This PR has:
<hr>
> Pipe: fix losing points when enable batch mode introduced by progress commit framework refactor

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/mtree/impl/pbtree/memory/ReleaseFlushMonitor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/mtree/impl/pbtree/memory/buffer/NodeBuffer.java
Since the ReleaseFlushMonitor takes the responsibility of rounded flush until all volatile nodes being flushed, there's no need to implement complex modification-sensitive iterator in NodeBuffer. Remove related logic.
> Simplify NodeBuffer iterator logic

- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/iot/logdispatcher/LogDispatcher.java
do not set SafelyDeletedSearchIndex as it is Long.MAX_VALUE when replica is 1.
> [IOTDB-6266] Add the ability to flush syncIndex and update reader periodically for IoTConsensus

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/wal/buffer/AbstractWALBuffer.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/wal/node/WALNode.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/wal/utils/WALEntryHandler.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/wal/utils/WALFileUtils.java
Problem:
- Due to the concurrent execution of the renaming of the wal file and the reading of the wal file by the pipe, the pipe may not be able to fetch the wal file when it reads the wal file, resulting in an NPE.
Solution:
1. change Files.renameTo in wal code to Files.move for better atomicity and visibility.
2. add logging when wal fetches a file
3. add logging when pipe fetches a wal value to print the memtable id and wal file version id that it failed to fetch.
问题：
- 由于wal 文件的重命名和 pipe 读取 wal 文件存在并发执行的情况，导致 pipe 读取 wal 文件时可能无法获取 wal 文件，导致 NPE
解决方案：
1. 将 wal 代码中的 Files.renameTo 改成原子性和可见性更好的 Files.move
2. 增加 wal 获取文件时的日志
3. 增加 pipe 获取 wal 值时的日志，打印未能获取的 memtable id 和 wal file version id
> [IOTDB-6262] Pipe: fix NPE while deserializing WAL (caused by non-atomic WAL rename operation during pipe read)

- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/service/JMXService.java
Previously, the concurrent call to "registerMBean" or "deregisterMBean" may cause after 2 threads seeing the same state simultaneously, that one thread changes the state and make another one throw InstanceAlreadyExistsException or InstanceNotFoundException. This PR fixed this problem by adding synchronize to the 2 functions.
Log example when exception occurs:
```
2023-11-02 15:52:49,880 [pool-34-IoTDB-ClientRPC-Processor-44$20231102_075249_05132_1] ERROR o.a.i.c.s.JMXService:56 - Failed to registerMBean org.apache.iotdb.threadpool:type=org.apache.iotdb.db.queryengine.plan.scheduler.load.LoadTsFileDispatcherImpl
javax.management.InstanceAlreadyExistsException: org.apache.iotdb.threadpool:type=org.apache.iotdb.db.queryengine.plan.scheduler.load.LoadTsFileDispatcherImpl
        at …
```
> Load: Fix InstanceAlreadyExistsException caused by concurrent registration on JMXService

- iotdb-core/node-commons/src/assembly/resources/conf/iotdb-common.properties
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/conf/CommonDescriptor.java
Old:
```
```
New:
```
```
Old parameters can also be parsed and applied.
> Pipe: Changed the property files' "extractor" and "connector" related parameters to their "source" and "sink" counterparts

- iotdb-connector/flink-sql-iotdb-connector/src/main/java/org/apache/iotdb/flink/sql/common/Options.java
- iotdb-connector/flink-sql-iotdb-connector/src/main/java/org/apache/iotdb/flink/sql/factory/IoTDBDynamicTableFactory.java
- iotdb-connector/flink-sql-iotdb-connector/src/main/java/org/apache/iotdb/flink/sql/function/IoTDBCDCSourceFunction.java
Currently, only full data can be consumed, not only real-time data. A new property `cdc.mode` can resolve this problem.
> flink-sql-iotdb-connector: add property `cdc.mode` in cdc connector

- iotdb-core/node-commons/src/assembly/resources/conf/iotdb-common.properties
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/conf/CommonConfig.java
> Pipe: Set pipe_sink_selector_number to pipe_sink_core_client_number to improve the performance of concurrent file transfers

- integration-test/src/main/java/org/apache/iotdb/it/env/cluster/config/MppDataNodeConfig.java
- integration-test/src/main/java/org/apache/iotdb/it/env/remote/config/RemoteDataNodeConfig.java
- integration-test/src/main/java/org/apache/iotdb/itbase/env/DataNodeConfig.java
- integration-test/src/test/java/org/apache/iotdb/db/it/IOTDBLoadTsFileIT.java
Question:
- IOTDBLoadTsFileIT.testLoadWithMods fails to pass the CI, the client displays NPE and the logs show that TsFileWriterManager has been closed.
- The reason is that the Load receiver is unable to persist the file fragments within the Thrift timeout, which causes the Load to advance to the second phase and close the TsFileWriterManager that is persisting at the receiver, resulting in an exception being thrown.
Solution:
- Increase IOTDBLoadTsFileIT.testLoadWithMods to test the Thrift Timeout time and the upper limit of Load file fragment size in the scenario.
问题：
- IOTDBLoadTsFileIT.testLoadWithMods 无法通过 CI，客户端显示 NPE ，日志显示 TsFileWriterManager has been closed.
- 原因在于 Load 接收端无法在 Thrift 超时时间内持久化文件碎片，导致 Load 提前进入第二阶段，关闭了接收端正在进行持久化的 TsFileWriterManager，导致抛出异常
解决方案：
- 调大 …
> [IOTDB-6276] Load IT: Add ConnectionTimeoutMs for IOTDBLoadTsFileIT.testLoadWithMods

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/resource/tsfile/PipeTsFileResourceManager.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/resource/wal/PipeWALResourceManager.java
> Pipe: Ignore ConcurrentModificationException caused by PipeWALResourceManager#ttlCheck() & PipeTsFileResourceManager#ttlCheck()

- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/DataRegionTest.java
Fix UT DataRegion.testMerge. This UT test manually triggered merge, which may cause concurrent issue.
If the unsequence inner space compaction task is finised before sequence space compaction task, the test may failed.
> Fix UT DataRegion.testMerge

- integration-test/src/test/java/org/apache/iotdb/confignode/it/partition/IoTDBPartitionGetterIT.java
- iotdb-core/antlr/src/main/antlr4/org/apache/iotdb/db/qp/sql/IoTDBSqlParser.g4
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/consensus/request/read/region/GetRegionIdPlan.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/partition/PartitionManager.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/persistence/partition/DatabasePartitionTable.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/persistence/partition/PartitionInfo.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/service/thrift/ConfigNodeRPCServiceProcessor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/execution/config/executor/ClusterConfigTaskExecutor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/parser/ASTVisitor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/statement/metadata/GetRegionIdStatement.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/partition/DataPartitionTable.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/partition/SeriesPartitionTable.java
- iotdb-protocol/thrift-confignode/src/main/thrift/confignode.thrift
In https://github.com/apache/iotdb/pull/9665, I improved the SQL query for displaying regionId. However, it didn't support SQL queries based on a time range. Now, it supports SQL queries based on a time range.
sql with range time example
you can see more information in https://apache-iotdb.feishu.cn/docx/NnzTdj3RcoSJyjxDSFxc01PJnvY#doxcnXfK9CBQk8fnRF5GpLiiuyh
> Show regionId supports SQL queries by time range.

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/schedule/CompactionTaskManager.java
- iotdb-core/node-commons/src/assembly/resources/conf/iotdb-common.properties
Currently, the parameter compaction_write_throughput_mb_per_sec doesn't support negative value and negative values make RateLimitor throwing exceptions.
Any value less than or equal to 0 means no limit in the compaction_write_throughput_mb_per_sec.
> Compaction rate limiter parameter supports negative value

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/mtree/impl/pbtree/flush/PBTreeFlushExecutor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/mtree/impl/pbtree/flush/Scheduler.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/mtree/impl/pbtree/memory/ReleaseFlushMonitor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/mtree/impl/pbtree/schemafile/pagemgr/BTreePageManager.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/mtree/impl/pbtree/schemafile/pagemgr/PageManager.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/metadata/mtree/schemafile/MonitorTest.java
Previously, a NPE could occur due to eviction checks and executions being performed on different objects. 
If two threads, T1 and T2, concurrently decrement the reference count of the same page, one would be blocked by an exclusive lock before entering eviction process. Suppose T1 acquires the lock and completes the eviction. Before T2 can obtain the lock, another thread T3 might acquire it and attempt to read the evicted page. This action triggers a disk read and creates a new page object, even while T2 still holds a page object with the same page index. Eventually, when T2 proceeds with eviction, it finds the reference count of its page to be zero and evicts the page with same page index which is actually held by T3. This erroneous eviction could subsequently lead to an NPE when T3 …
> PBTree: Fix NPE in SchemaFile conccurency control

- pom.xml
Fix the error when running `mvn clean package -DskipTests -P apache-release`
> Fix no file error when release new version

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/tsfile/TsFileManager.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/LastFlushTimeMapTest.java
A machine with 32G memory, 5 million devices, while writing data from 10 time partitions at the same time, the write speed is very slow, CPU sampling found that it takes more time to recover the last flush time from TimeIndex.
1c1d
8GB DataNode 
write_memory_proportion=1000000000:1
flush_proportion=0.01
chunk_timeseriesmeta_free_memory_proportion=2:200:400:100:400:400:1:100
BenchMark
DB_SWITCH=IoTDB-110-SESSION_BY_RECORDS
LOOP=50
DEVICE_NUMBER=20000
SENSOR_NUMBER=1
VECTOR=false
INSERT_DATATYPE_PROPORTION=0:0:1:0:0:0
BATCH_SIZE_PER_WRITE=1
**Before throughput(point/s) = 8799.88**
**After throughput(point/s) = 19597.55**
> Avoid reading file when recover last flush time from FileTimeIndex

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/flush/NotifyFlushMemTable.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/memtable/AbstractMemTable.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/memtable/IMemTable.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/memtable/TsFileProcessor.java
As title.
---
**Regeneration:**
During disk flushing, it is now impossible to determine whether the content of a tsfile is forwarded through a pipe or contains data written by a regular client. Therefore, for data synchronized from A to B in log mode, if B establishes a bidirectional connection to A in file mode, there may be an issue with B rewriting part of the data written by A.
```sql
create pipe a2b with source ('realtime.mode'='log') with sink ('node-urls'='127.0.0.1:6668', 'forwarding-pipe-requests'='false');
create pipe b2a with source ('realtime.mode'='file') with sink ('node-urls'='127.0.0.1:6667', 'forwarding-pipe-requests'='false');
```
---
**Solution:**
Add an flag for memtable to determine whether the generated tsfile contains content written non-pipe forwarded; only forward …
> Pipe: add flag for memtable to avoid retransmission of tsfile generated by forwarded insertion

- iotdb-core/consensus/src/main/java/org/apache/iotdb/consensus/iot/client/DispatchLogHandler.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/consensus/statemachine/dataregion/DataExecutionVisitor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/consensus/statemachine/dataregion/DataRegionStateMachine.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/DataRegion.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/memtable/TsFileProcessor.java
> DataRegion should return WRITE_PROCESS_REJECT to Consensus when insert rejected

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/mtree/impl/pbtree/schemafile/ISchemaPage.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/mtree/impl/pbtree/schemafile/SchemaPage.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/mtree/impl/pbtree/schemafile/pagemgr/BTreePageManager.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/mtree/impl/pbtree/schemafile/pagemgr/PageManager.java
Fix conccurency control when try to read alias, or read miss.
<hr>
This PR has:
<hr>
> PBTree: Fix conccurency control with alias read

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/mtree/impl/pbtree/flush/PBTreeFlushExecutor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/mtree/impl/pbtree/schemafile/pagemgr/BTreePageManager.java
1. Add stack trace logic during exception processing
2. Add page referent check and release logic during iterating B+ Tree pages to avoid wrong page eviction and deadlock.
> PBTree: Fix NPE during concurrent creating and iterating schema

- iotdb-core/tsfile/src/main/java/org/apache/iotdb/tsfile/compress/ICompressor.java
- iotdb-core/tsfile/src/main/java/org/apache/iotdb/tsfile/compress/IUnCompressor.java
This pr cache the instance of LZ4Factory to avoid performance problem.
> Cache LZ4Factory to avoid performance problem with LZ4Factory

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/exchange/source/SourceHandle.java
This pr adds missing synchronized on abort of SourceHandle. If we do not hold the lock before aborting the SourceHandle, there may be concurrent issues.
> Add missing synchronized on abort of SourceHandle

- integration-test/src/test/java/org/apache/iotdb/db/it/orderBy/IoTDBOrderByIT.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/optimization/LimitOffsetPushDown.java
We cannot push limit down to scan if we have order by clause. 
Limit/Offset only works on the sorted results.
> [IOTDB-6275] Disable limit/offset push down in ORDER BY

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/mtree/impl/pbtree/CachedMTreeStore.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/mtree/impl/pbtree/lock/LockManager.java
Here's the deadlock description:
flushMonitor + readCnt wait -> 
releaseMonitor+Scheduler#synchronize wait -> 
worker release readWait -> 
snapshot  writeWait -> 
flushMonitor + readCnt
Enable the release worker to surpass the write lock waiting thread to directly execute memory release.
Thus the release worker only have to wait for write lock protected execution finished, and the releaseMonitor won't hold the object header lock for long.
> PBTree: Fix deadlock of PBTree release and flush

- integration-test/src/test/java/org/apache/iotdb/db/it/IoTDBRestServiceIT.java
- integration-test/src/test/java/org/apache/iotdb/db/it/schema/IoTDBMetadataFetchIT.java
- iotdb-core/antlr/src/main/antlr4/org/apache/iotdb/db/qp/sql/IoTDBSqlParser.g4
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/operator/schema/source/DeviceSchemaSource.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/parser/ASTVisitor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/read/resp/info/impl/ShowDevicesResult.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/utils/filter/DeviceFilterVisitor.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/queryengine/execution/operator/schema/SchemaQueryScanOperatorTest.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/conf/IoTDBConstant.java
This modification is based on the work in https://github.com/apache/iotdb/pull/11681.
The main improvements of this work are:
- Implemented new syntax for null checking in template filtering.
- Supported distinguishing between the template name 'null' and the null value.
- Fixed the scenario where using the string 'null' as a return result led to an empty null value.
The expected outcomes of this implementation are as follows:
```
// Query to display activated template columns effect
IoTDB > show devices
// Execution result
+-----------------+-------------+-------------+
|          devices|    isAligned|     template|
+-----------------+-------------+-------------+
|root.ln.wf01.wt01|        false|           t1|
|root.ln.wf01.wt02|        false|           t2|
|root.ll.wf02.wt02| …
```
> Support_NewTemplateFilteringSyntax_IsNull_IsNotNull

- iotdb-api/pipe-api/src/main/java/org/apache/iotdb/pipe/api/customizer/parameter/PipeParameters.java
- iotdb-api/pipe-api/src/main/java/org/apache/iotdb/pipe/api/exception/PipeConnectionException.java
- iotdb-api/pipe-api/src/main/java/org/apache/iotdb/pipe/api/exception/PipeParameterNotValidException.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/protocol/legacy/IoTDBLegacyPipeConnector.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/protocol/thrift/async/IoTDBThriftAsyncConnector.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/protocol/thrift/sync/IoTDBThriftSyncClientManager.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/protocol/thrift/sync/IoTDBThriftSyncConnector.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/plugin/builtin/connector/iotdb/IoTDBConnector.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/plugin/builtin/connector/iotdb/thrift/IoTDBMetaConnector.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/task/meta/PipeStaticMeta.java
As title, with more details:
1. Concealing the `ssl.trust-store-pwd` in parameters.
2. Implementing stricter checks for SSL in the case of async connector.
3. Standardizing exceptions thrown during the construction of `IoTDBThriftSyncConnectorClient` as `PipeConnectionException`.
4. Standardizing exceptions thrown during the parsing of node URLs as `PipeParameterNotValidException`.
<hr>
This PR has:
<hr>
> Pipe: conceal SSL trust store password & improve exception messages for sink connection establishment

- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/exception/NotEnoughDataNodeException.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/load/balancer/RegionBalancer.java
Add log for NotEnoughDataNodeException. Therefore when the cluster DataNode is not enough, we can compare the detailed information between registered DataNodes and the replicationFactor.
> Add log for NotEnoughDataNodeException

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/consensus/statemachine/dataregion/DataExecutionVisitor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/plan/node/write/InsertMultiTabletsNode.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/plan/node/write/InsertRowsNode.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/plan/node/write/InsertRowsOfOneDeviceNode.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/DataRegion.java
When an InsertTabletsNode contains the system reject status, the consensus will retry it endlessly.
> Clear status in InsertNodes to fix consensus endless retry

- iotdb-client/session/src/main/java/org/apache/iotdb/session/Session.java
- iotdb-client/session/src/test/java/org/apache/iotdb/session/SessionCacheLeaderTest.java
- iotdb-client/session/src/test/java/org/apache/iotdb/session/SessionConnectionTest.java
- iotdb-client/session/src/test/java/org/apache/iotdb/session/SessionTest.java
- iotdb-client/session/src/test/java/org/apache/iotdb/session/pool/SessionPoolExceptionTest.java
- iotdb-client/session/src/test/java/org/apache/iotdb/session/pool/SessionPoolTest.java
In Session & SessionPool UT, we should set `enableAutoFetch` to `false` to avoid NPE in close.
> try fix SessionPoolTest UT

- iotdb-core/confignode/src/assembly/resources/sbin/register-confignode.sh
- iotdb-core/datanode/src/assembly/resources/sbin/register-datanode.sh
This shell script can register confignode and datanode systemd services and start/stop them using "systemctl".
> Use systemctl to control confignode and datanode

- iotdb-api/pipe-api/src/main/java/org/apache/iotdb/pipe/api/exception/PipeConnectionException.java
- iotdb-api/pipe-api/src/main/java/org/apache/iotdb/pipe/api/exception/PipeParameterNotValidException.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/protocol/legacy/IoTDBLegacyPipeConnector.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/connector/protocol/thrift/sync/IoTDBThriftSyncClientManager.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/plugin/builtin/connector/iotdb/IoTDBConnector.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/plugin/builtin/connector/iotdb/thrift/IoTDBMetaConnector.java
As title, this PR serves as further optimizations following https://github.com/apache/iotdb/pull/11806 to provide more user-friendly information and log the root cause.
<hr>
This PR has:
<hr>
> Pipe: improve exception messages for sink connection establishment and node urls validation

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/executor/RegionWriteExecutor.java
PATH_ALREADY_EXIST and ALIAS_ALREADY_EXIST is what we expect, we should never print it as Exception
> Print Exception only when encountering unexpected TSStatus

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/mtree/impl/pbtree/schemafile/pagemgr/BTreePageManager.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/mtree/impl/pbtree/schemafile/pagemgr/PageManager.java
Previously, there was a deadlock issue caused by a reentrant write lock that would only unlock once, leading to a situation where any read thread attempting to access the page would be blocked.
This reentrant lock scenario, although rare, occurred recurrently on the test server. If one page has just allocated (more precisely, pre-allocated) last few bytes, it will be removed from local(context) index buckets but not added back. Right now a segment of this page was transplanted into another page, the previous implementation failed to update spare space variation of this page in the local index buckets, which are designed for quick retrieval based on specified spare space. However, this page might have been previously marked in the global index bucket, with a spare space before allocation. …
> PBTree: Fix deadlock when segment deleted

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/mtree/impl/pbtree/schemafile/pagemgr/BTreePageManager.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/mtree/impl/pbtree/schemafile/pagemgr/PageManager.java
As the page lock is a field within page instance, any read thread blocked by the lock had already held the instance. If the executing writing thread transplanted the target segment or replaced the page instance, the read thread may proceed with a stale page. Although this issue has not occured yet, it is possible to take place in further test and should be fixed as this revision did.
<hr>
This PR has:
<hr>
> PBTree: Prevent Concurrent Read With Stale Page

- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/pipe/agent/PipeConfigNodeAgent.java
- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/pipe/agent/plugin/PipePluginConfigNodeAgent.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/agent/plugin/PipePluginDataNodeAgent.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/agent/plugin/dataregion/PipeDataRegionPluginAgent.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/agent/plugin/schemaregion/PipeSchemaRegionPluginAgent.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/agent/plugin/PipePluginAgent.java
- iotdb-core/node-commons/src/main/java/org/apache/iotdb/commons/pipe/plugin/builtin/connector/iotdb/thrift/IoTDBMetaConnector.java
As title.
<hr>
This PR has:
<hr>
> Pipe: fix PipeDataRegionPluginAgent initialization order & avoid instantiating meta source and sink

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/thrift/impl/DataNodeInternalRPCServiceImpl.java
The heartbeat process now will print the available disk space and the total disk space when the remaining disk space is less than the disk space warning threshold.
> Add disk space log in cluster heartbeat

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/thrift/impl/DataNodeInternalRPCServiceImpl.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/common/MPPQueryContext.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/executor/RegionWriteExecutor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/Coordinator.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/cache/schema/DataNodeSchemaCache.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/analyze/schema/ClusterSchemaFetcher.java
In this PR:
1. remove useless write lock on schema cache when execute deletion
2. coordinator will acquire a read lock on schema cache, which will block deletion's cache invalidation.
3. solves the DEAD data problem: these data have no metadata but only data.
> fix insert&delete cases dead data.

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/wal/buffer/AbstractWALBuffer.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/wal/buffer/WALBuffer.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/wal/checkpoint/CheckpointManager.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/wal/node/WALNode.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/wal/node/WALEntryHandlerTest.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/wal/node/WalDeleteOutdatedNewTest.java
1. Select all less than unFlushMemTableMinVersion wal file, remember to CandidateFiles
2. In CandidateFiles, select all files smaller than safelyDeleteIndex, denoted as MustDeletedFiles
3. Delete MustDeletedFiles
1. Obtain all wal files in a WalNode except the last file, which are called AllWalFiles
2. Obtain CheckPointManager. All not flush or be pin memTableId2Info MemTable, remember to ActiveMemTable
3. Get the set of MEMtables that each wal file contains, and refer to it as MemTableIdsOfWalMap
4. Traverse AllWalFiles and determine whether the deletion conditions in the optimization idea are met according to ActiveMemTable and MemTableIdsOfWalMap. If yes, delete the current file.
> Optimized wal file deletion algorithm

- integration-test/src/test/java/org/apache/iotdb/db/it/aligned/IoTDBAlignedSeriesQueryWithDeletionIT.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/memtable/AlignedWritableMemChunk.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/utils/datastructure/AlignedTVList.java
Execute the following sqls
```
insert into root.sg1.factory0.d1.group1(time, s_lat, s_son) aligned values (10,3.3,4.4),(20,13.3,14.4),(30,23.3,24.4),(40,43.3,44.4);
insert into root.sg1.factory0.d1.group1(time, s_lat, s_son, s_boolean) aligned values (10,3.3,4.4, true),(20,13.3,14.4, false),(30,23.3,24.4, true),(40,43.3,44.4, true);
select * from root.sg1.factory0.d1.group1;
delete from root.sg1.factory0.d1.group1.* where time < 30;
select * from root.sg1.factory0.d1.group1;
```
The following error will appear.
```
Msg: org.apache.iotdb.jdbc.IoTDBSQLException: 301: Declared positions (2) does not match column 0's number of entries (3)
```
The reason of this bug is when we use rowBitMap to get the information of whether the row is all null, we alway need to getValueIndex method first.
> Fix aligned timeseries query error after delete some data in memtable

- iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/load/cache/LoadCache.java
There is no need to pay more time when leader election was interrupted. Since all the information just stored in memory. The ConfigNode will re-calculate them when restart.
> Return when leader election waiting is interrupted

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/exception/CompactionFileCountExceededException.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/exception/CompactionLastTimeCheckFailedException.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/exception/CompactionMemoryNotEnoughException.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/exception/CompactionValidationFailedException.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/performer/impl/FastCompactionPerformer.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/task/AbstractCompactionTask.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/schedule/CompactionWorker.java
1. Reduce stack message of known compaction exceptions in log (CompactionMemoryNotEnoughException, CompactionFileCountExceedException, CompactionValidationFailedException, CompactionLastTimeCheckFailedException and FileCannotTransitToCompactingException).
2. Avoid trace stack for known compaction exceptions by reimplement 'fillInStackTrace' method.
> Reduce stack message of known compaction exceptions in log

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/service/metrics/WritingMetrics.java
The current code contains the following metrics errors, this PR is for fixing them.
```
2024-01-04 14:27:40,447 [pool-9-IoTDB-StorageEngine-2] ERROR o.a.i.m.utils.MetricInfo:52 - The size of metric tags should be even, but was name,region,2.
2024-01-04 14:27:40,447 [pool-9-IoTDB-StorageEngine-1] ERROR o.a.i.m.utils.MetricInfo:52 - The size of metric tags should be even, but was name,region,1.
```
> fix the error of writing metrics

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/wal/recover/WALRecoverManager.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/wal/utils/WALFileUtils.java
If the iotdb contains unflushed data, suddenly outages (for example, kill -9). After an outage, the data directory is copied to the iotdb of another directory, and data is lost after startup.  This PR solves the problem of lost data.
1. Start an iotdb and write one piece of data,` insert into root.test.d1 (s1) values (1) `.
2. Run the kill -9 command to stop the ConfigNode and DataNode processes.
3. Copy the 'data' directory into a new iotdb and start it (the new iotdb will not be the same as the previous path).
4. Verify that data exists, `select * from root.test.**`
The data is missing. It can't be found.
The data is recovered and can be found.
> Fix lose data when recover data dir onto a new iotdb

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/mtree/impl/pbtree/CachedMTreeStore.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/mtree/impl/pbtree/flush/Scheduler.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/schemaengine/schemaregion/mtree/impl/pbtree/memory/ReleaseFlushMonitor.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/metadata/mtree/schemafile/MonitorTest.java
Dead lock happened when:
* Thread A try to flush all, hold Scheduler's synchronized lock, acquire store read lock.
* Thread A try to schedule flush, hold store read lock, acquire Scheduler's synchronized lock.
Solution: Make store all read&write locks are acquired after Scheduler's synchronized lock.
> PBTree: fix deed lock in ReleaseFlushMonitor and Scheduler

- iotdb-core/confignode/src/assembly/resources/conf/confignode-env.sh
- iotdb-core/datanode/src/assembly/resources/conf/datanode-env.sh
CrashOnOutOfMemoryError will generate a crash file while meeting OOM error.
> Change ExitOnOutOfMemoryError to CrashOnOutOfMemoryError

- integration-test/src/test/java/org/apache/iotdb/db/it/IOTDBLoadTsFileIT.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/agent/runtime/PipeRuntimeAgent.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/pipe/progress/assigner/SimpleConsensusProgressIndexAssigner.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/protocol/thrift/impl/DataNodeInternalRPCServiceImpl.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/execution/load/LoadTsFileManager.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/LocalExecutionPlanner.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/planner/plan/node/load/LoadSingleTsFileNode.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/scheduler/load/LoadTsFileDispatcherImpl.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/queryengine/plan/scheduler/load/LoadTsFileScheduler.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/StorageEngine.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/utils/TsFileResourceUtils.java
- iotdb-protocol/thrift-datanode/src/main/thrift/datanode.thrift
Problems:
The Load TsFile process uses a two-phase transaction commit to ensure consistency. Currently, commands are sent directly to each DataNode through the Thrift framework during the second stage of validation, which does not ensure that the loaded TsFiles are organized within the DataRegionGroup. This does not ensure that the loaded TsFiles are organized within the DataRegionGroup, nor can they be correctly identified as progress by the Pipe system.
Solution:
A RecoverProgressIndex will be added to the second stage command, so that when a local load or a cross-DataNode load is performed, the ProgressIndex will be incorporated into the TsFileResource to complete the progress identification.
问题：
Load TsFile 过程中使用了两阶段事务提交的方式保证一致性。目前在第二阶段确认的过程中直接通过 Thrift 框架发送指令到各个 DataNode 上，这无法保证加载的 …
> [IOTDB-6287] Load: Add Progress Index for the Second Phase of Load TsFile

- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/task/CrossSpaceCompactionTask.java
- iotdb-core/datanode/src/main/java/org/apache/iotdb/db/storageengine/dataregion/compaction/execute/task/InnerSpaceCompactionTask.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/compaction/ReadChunkInnerCompactionTest.java
- iotdb-core/datanode/src/test/java/org/apache/iotdb/db/storageengine/dataregion/compaction/cross/CrossSpaceCompactionExceptionTest.java
Fix compaction log is not deleted after exception.
```
protected boolean doCompaction() {
long startTime = System.currentTimeMillis();
// get resource of target file
recoverMemoryStatus = true;
LOGGER.info(
"{}-{} [Compaction] {} InnerSpaceCompaction task starts with {} files, "
+ "total file size is {} MB, memory cost is {} MB",
storageGroupName,
dataRegionId,
sequence ? "Sequence" : "Unsequence",
selectedTsFileResourceList.size(),
selectedFileSize / 1024 / 1024,
memoryCost == 0 ? 0 : (double) memoryCost / 1024 / 1024);
boolean isSuccess = true;
try {
prepare();
try (SimpleCompactionLogger compactionLogger = new SimpleCompactionLogger(logFile)) {
// Here is tmpTargetFile, which is xxx.target
targetTsFileList = new ArrayList<>(Collections.singletonList(targetTsFileResource)); …
```
> Fix compaction log is not deleted after exception
